### ISSUE TITLE
status of current Netopeer2 Implementation in terms of compliance to RFC 6241 

### ISSUE THREAD

**Issue by vishalwc** [CESNET/Netopeer2#100]
is there any document or reference which talks about the implementation status in terms of 
RFC 6241 compliance for example replace command and Lock command is not working

**Comment by michalvasko** [comment]
Hi,
the whole RPC should be supported, if some operations are not working, please create an issue (the ones you mentioned are quite basic and believed to work properly for quite some time now). But, looking at all the capabilities, `URL` and `Confirmed Commit` are currently not supported, they may be later.

Regards,
Michal

**Comment by vishalwc** [comment]
Thanks Michal
