### ISSUE TITLE
x509 certificate using netopeer

### ISSUE THREAD

**Issue by nikhilpati** [CESNET/netopeer2#1000]
Hi all ,
      I am little confused to implement x509 certificate . so how we can implement x509 certificate using netopeer ?

**Comment by michalvasko** [comment]
Then you should read the relevant section in [README](https://github.com/CESNET/Netopeer2/tree/devel#tls-listen) and test it that way. Based on that you should be able to modify the configuration so that it works with your specific certificates.

**Comment by nikhilpati** [comment]
ok fine ,
 but i was little confused that how we can create a openssl x509 certificate and how to use it using netopeer2 ?   
 We are following attached README.txt file to create a certificate on linux platform :-

[README.txt](https://github.com/CESNET/netopeer2/files/7083568/README.txt)
.

**Comment by michalvasko** [comment]
There is a testing certificate provided and you can configure it using the steps in the README I have referenced. That way all the nodes in the [TLS server configuration](https://github.com/CESNET/netopeer2/blob/master/modules/ietf-tls-server%402019-07-02.yang#L101) are correctly populated. You can do that directly if you read the descriptions in the YANG module(s) but what I have suggested should make this simpler, there are quite many parameters that need to set correctly.
