### ISSUE TITLE
Netconf doesn’t work with windows radius server

### ISSUE THREAD

**Issue by ezehreubenccie** [CESNET/netopeer2#1002]
Please I need help too. I cannot get an established netconf session to my Cisco 4331 isr router. 

I use aaa configuration that uses a windows 2016 server. Regular ssh connections work but netconf doesn’t work even though it is configured correctly on the router. when I enter ssh -p 830 user@router-name or IP address, I get permission denied.

when I took out the aaa authentication I had no problems. So it looks like there is a configuration missing on the radius server. I have researched online, opened Cisco tickets, still no success. I am beginning to think that netconf and restconf only work with local creds or Cisco ISE  not Windows radius(Network policy server). Please any help will be appreciated.

**Comment by michalvasko** [comment]
Replied in #230, please do not create duplicate posts.

**Comment by ezehreubenccie** [comment]
ok, My apologies, Michal for creating a duplicate post. But could you help me with this issue. What information do you need to help me?

**Comment by michalvasko** [comment]
You have not replied to what I asked, you have not mentioned using either *netopeer2-server* or *netopeer2-cli* so I do not understand why are you asking us for help.
