### ISSUE TITLE
Warning/error while compiling code with -lyang Flag

### ISSUE THREAD

**Issue by bkumarrr** [CESNET/netopeer2#1003]
Hi @michalvasko 
I am compiling my application with -lyang but getting below error 
cc demo_sysrepo.c -o demo -lsysrepo -lpthread -lyang 
**/usr/bin/ld: warning: libyang.so.2, needed by //usr/local/lib/libsysrepo.so, may conflict with libyang.so.1**

Output of  `ldconfig -p | grep sysrepo` -
	**libsysrepo.so.6 (libc6,x86-64) => /usr/local/lib/libsysrepo.so.6
	libsysrepo.so.5 (libc6,x86-64) => /usr/local/lib/libsysrepo.so.5
	libsysrepo.so.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libsysrepo.so.5
	libsysrepo.so.0.7 (libc6,x86-64) => /usr/local/lib/libsysrepo.so.0.7
	libsysrepo.so (libc6,x86-64) => /usr/local/lib/libsysrepo.so
	libsysrepo.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libsysrepo.so**
Output of  `ldconfig -p | grep yang`-
	**libyang.so.2 (libc6,x86-64) => /usr/local/lib/libyang.so.2
	libyang.so.2 (libc6,x86-64) => /lib/libyang.so.2
	libyang.so.1 (libc6,x86-64) => /usr/local/lib/libyang.so.1
	libyang.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libyang.so.1
	libyang.so (libc6,x86-64) => /usr/local/lib/libyang.so
	libyang.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libyang.so
	libyang.so (libc6,x86-64) => /lib/libyang.so**

**Comment by michalvasko** [comment]
You have installed and are linking against both *libyang* v1 and v2 in one application (one indirectly by *sysrepo*), that is not possible because you will have symbol conflicts, obviously.

**Comment by bkumarrr** [comment]
Hi @michalvasko Thanks 
Above issue is resolved.
But I am wishing to subscribe for configuration data and operational data in same application code,To achieve this I have used `sr_module_change_subscribe` and `sr_oper_get_items_subscribe` . But when I am trying to get data with` > get --filter-xpath /my:*` command, I am only getting configuration data

**Comment by michalvasko** [comment]
Paste the code of your application, impossible to help otherwise.

**Comment by bkumarrr** [comment]
Below is my code:

**#define _QNX_SOURCE /* sleep() */
#define _GNU_SOURCE

#include <inttypes.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "sysrepo.h"

volatile int exit_application = 0;

/* new changes */
static int
dp_get_items_cb(sr_session_ctx_t *session, uint32_t sub_id, const char *module_name, const char *xpath,
        const char *request_xpath, uint32_t request_id, struct lyd_node **parent, void *private_data)
{
    printf("\n\n ========== DATA FOR \"%s\" \"%s\" REQUESTED =======================\n\n", module_name, xpath);
    if (!strcmp(module_name, "my") && !strcmp(xpath, "/my:led-state/temperature")) {
        lyd_new_path(NULL, sr_get_context(sr_session_get_connection(session)), "/my:led-state/temperature", "True", 0, parent);
        //lyd_new_path(*parent, NULL, "/examples:stats/counter2", "1052", 0, NULL);
    }

    return SR_ERR_OK;
}


static int
print_current_config(sr_session_ctx_t *session, const char *module_name)
{
    sr_val_t *values = NULL;
    size_t count = 0;
    int rc = SR_ERR_OK;
    char *xpath;

    if (asprintf(&xpath, "/%s:*//.", module_name) == -1) {
        return SR_ERR_NO_MEMORY;
    }
    rc = sr_get_items(session, xpath, 0, 0, &values, &count);
    free(xpath);
    if (rc != SR_ERR_OK) {
        return rc;
    }
    printf("Running config is :%d\n",values[1].data.uint8_val);
    sr_free_values(values, count);

    return rc;
}

const char *
ev_to_str(sr_event_t ev)
{
    switch (ev) {
    case SR_EV_CHANGE:
        return "change";
    case SR_EV_DONE:
        return "done";
    case SR_EV_ABORT:
    default:
        return "abort";
    }
}

static int
module_change_cb(sr_session_ctx_t *session, uint32_t sub_id, const char *module_name,const char *xpath, sr_event_t event,
        uint32_t request_id, void *private_data)
{
    sr_change_iter_t *it = NULL;
    int rc = SR_ERR_OK;
    char path[512];
    sr_change_oper_t oper;
    sr_val_t *old_value = NULL;
    sr_val_t *new_value = NULL;
    char *state;
    char cmd[BUFSIZ] = "sudo echo %d > /sys/class/leds/input2::capslock/brightness";
    char cmmdd[BUFSIZ];

    printf("\n\n ========== EVENT %s CHANGES: ====================================\n\n", ev_to_str(event));
    sprintf(path, "/%s:*//.", module_name);

    /* Create an iterator for retrieving the changes (list of newly added / removed / modified nodes)
     *  in module-change callbacks. It cannot be used outside the callback */
    rc = sr_get_changes_iter(session, path, &it);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }
    /* Return the next change from the provided iterator created by sr_get_changes_iter call.
     * Data are represented as sr_val_t structures.  */
    while ((rc = sr_get_change_next(session, it, &oper, &old_value, &new_value)) == SR_ERR_OK) {
	    if(oper == SR_OP_MODIFIED) {
		    printf("Value modified from  %d ", old_value->data.uint8_val);
		    printf(" to ");
		    printf("%d\n", new_value->data.uint8_val);
		    if(new_value->data.uint8_val == 0 || new_value->data.uint8_val == 1) {
			    if(new_value->data.uint8_val == 0) {
				    state = "low";
				    printf("\n Capslock led state is getting change to %s",state);
				    sprintf(cmmdd,cmd,new_value->data.uint8_val);
				    system(cmmdd);
				    printf("\n LED operation is Done \n");

			    }else if (new_value->data.uint8_val == 1) {
				    state = "high";
				    printf("\n Capslock led state is getting change to %s",state);
				    sprintf(cmmdd,cmd,new_value->data.uint8_val);
				    system(cmmdd);
				    printf("\n LED operation is Done \n");

			    } else {
				    printf("\nInvalid option Led will be only change its state when will get input as 0 and 1\n");
				    printf("\n LED operation Failed \n");
			    }
			    sr_free_val(old_value);
			    sr_free_val(new_value);
		    }
	    }

    }

cleanup:
    sr_free_change_iter(it);
    return SR_ERR_OK;
}

static void
sigint_handler(int signum)
{
    (void)signum;

    exit_application = 1;
}

int
main()
{
    sr_conn_ctx_t *connection = NULL;
    sr_session_ctx_t *session = NULL;
    sr_subscription_ctx_t *subscription = NULL;
    int rc = SR_ERR_OK;
    const char *mod_name = "my";

    printf("Application will watch for changes in \"%s\".\n", mod_name);

    /* connect to sysrepo */
    rc = sr_connect(0, &connection);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }

    /* start session */ 
    rc = sr_session_start(connection, SR_DS_RUNNING, &session);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }

    /* read current config */
    printf("\n ========== READING RUNNING CONFIG: ==========\n\n");
    if (print_current_config(session, mod_name) != SR_ERR_OK) {
        goto cleanup;
    }

    /* subscribe for changes in running config */
    rc = sr_module_change_subscribe(session, mod_name,NULL, module_change_cb, NULL, 0, SR_SUBSCR_CTX_REUSE, &subscription);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }
   
    printf("\n\n ========== LISTENING FOR CHANGES ==========\n\n");
   /* loop until ctrl-c is pressed / SIGINT is received */
    signal(SIGINT, sigint_handler);
    signal(SIGPIPE, SIG_IGN);
    while (!exit_application) {
        sleep(1000);
    }
    /*new changes */
     rc = sr_oper_get_items_subscribe(session, mod_name,"/my:led-state/temperature", dp_get_items_cb, NULL, SR_SUBSCR_CTX_REUSE, &subscription);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    } 
    printf("Application exit requested, exiting.\n");

cleanup:
    sr_disconnect(connection);
    return rc ? EXIT_FAILURE : EXIT_SUCCESS;
}**

and below is my Yang module

**module my {
    namespace "urn:sysrepo:my";
    prefix my;

    revision 2021-05-29 {
        description "Initial revision.";
    }
    container led-data {
        description "Configuration container for led";
        leaf turned-on {
            description " determining whether the LED is on or off.";
            type uint8;
        }
    }
    container led-state {
        description "State data container of the LED.";
        config false;
        leaf temperature {
            description "Actual LED Condition";
            type boolean;
        }

    }
}**

**Comment by michalvasko** [comment]
You are subscribing to providing the data after the infinite loop that waits for the application exit, put it before it and it should work.

**Comment by bkumarrr** [comment]
previously it was before loop only,That time application used to exit just after running it by printing "Application will watch for changes in my"

**Comment by michalvasko** [comment]
Then you had some other problem there. In any case, it is a problem in your application, not in *sysrepo*.
