### ISSUE TITLE
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.

### ISSUE THREAD

**Issue by prafullpk** [CESNET/netopeer2#1004]
I installed Netopeer2 client setup on Ubuntu VM.
All dependency library installed (Libyang, sysrepo, libconf2, openssl, libssh, netopeer2)
But once connecting to netconf server by this netopeer cli client. its giving warning as below.
and being connected to server but yang modules commands are not executing.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
> exit

**Comment by michalvasko** [comment]
You are safe to ignore these warnings.

**Comment by prafullpk** [comment]
ok thanks, but we are not able to run yang modules command and xpath filering commands.
get --filter-xpath
yang leaf xml tree not displaying.
please advise.

**Comment by michalvasko** [comment]
Can you paste the actual *netopeer2-cli* output?

**Comment by prafullpk** [comment]
Password:
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
> get --filter-xpath /o-ran-software-management.yang
DATA
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"/>

>
generally it should show complete mo xml tree with yang leaf / but its only showing -<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"/>

**Comment by michalvasko** [comment]
> generally it should show complete mo xml tree with yang leaf / but its only showing -

Why do you think so? You have just guessed the XPath filter without actually finding out what is expected, no wonder it does not work. Please look at XPath and its syntax. What you probably wanted to use in this case is `get --filter-xpath /o-ran-software-management:*`.

**Comment by michalvasko** [comment]
That is a fixed problem, please use *netopeer2* and all its dependencies from the `devel` branches. They should be properly released shortly.

**Comment by prafullpk** [comment]
Ok thanks, So can you please guide, how to download netoper2 from devel branche to solve this issue.

get --filter-xpath /o-ran-software-management:software-inventory
ly ERROR: Unknown XML prefix "xml". (Line number 1.)
nc ERROR: Session 159: received an invalid message (Unknown XML prefix "xml".).
cli_send_recv: Failed to receive a reply.

**Comment by michalvasko** [comment]
How did you get the *netopeer2* you are using? Simply checkout the `devel` branch and follow the [install instructions](https://github.com/CESNET/Netopeer2/#compilation-and-installation) for each project.
