### ISSUE TITLE
TLS Connection issue

### ISSUE THREAD

**Issue by kishore-vvdn** [CESNET/netopeer2#1006]
HI

**i am unable configure tls connection using local host.**

[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: LN: Listening on 0.0.0.0:830 for SSH connections.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Ext SHM was defragmented and 4128 B were saved.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-keystore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-truststore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.

**i am not getting TLS listening state in server side
i tried the following method to change the configuration
1)sysrepocfg --merge=/home/kishore/nxp_netopeer2/Netopeer2/example_configuration/tls_keystore.xml -d startup ietf-keystore
sysrepocfg error: Invalid option or missing argument: -
But sysrepocfg dont have the --merge option
2)sysrepocfg --edit=vim -m ietf-keystore
to change the configuration to tls_keystore.xml but unable to achieve it**

**in README file** 
### TLS listen

To support clients connecting using TLS, configuration files `tls_keystore.xml`, `tls_truststore.xml`,
and `tls_listen.xml` needs to be merged into *sysrepo* configuration of modules *ietf-keystore*,
*ietf-truststore*, and *ietf-netconf-server*, respectively.

**but im unable to configure this
could you please help me, how change these configuration to TLS connection?**

**Netopeer and dependencies versions** 
Netopeer2 -- v1.1.39
Libnetconf -- v1.1.26
libssh     --      0.9.5
libyang  -- v1.0.184
sysrepo -- v1.4.70

**Comment by michalvasko** [comment]
You are using a really old *sysrepo* version but with some luck this will work. But you cannot use commands from the legacy *sysrepo*, just use `sysrepocfg -h` to see the new syntax. You can merge a configuration file using `sysrepocfg -E<path-to-file> -d running -m ietf-keystore` (best to merge it to running for it to take effect immediately, you can then `copy-config` from running to startup).

**Comment by kishore-vvdn** [comment]
Thanks for your quick reply. I am able to connect local server.

could please suggest me which sysrepo version should i use?


i want to connect remote server uisng tls.

could you please tell how to generate certificates(server.crt,client.crt,server.key,client.key,ca.pem) for each server and client for remote connection?
certificates generated based on user name?

**please suggest the procedure to connect for remote device over tls.**



thanks

**Comment by michalvasko** [comment]
Ideally, you should use the latest v2 version (2.0.40) found only in `devel` branch for now, should be properly released soon. As for generating certificates and connecting using TLS, it requires considerable amount of configuration. I have tried to help with that by providing the example XML files, which you can just update with values from your certificates and it should work. Look into the corresponding YANG modules for description of the nodes. Finally, please do not ask how to generate certificates, there are many tutorials online so just use one.
