### ISSUE TITLE
sysrepo callback error on anyxml edit-config 

### ISSUE THREAD

**Issue by prudhivi66** [CESNET/netopeer2#1008]
I am getting callback invocation error during edit-config.please let me know this is right forum to ask the below query.
We would like to confirm if sysrepo supports callback invocation or anyxml data.

ERROR:sysrepo.subscription:<bound method ConfigChangeSubscriber.on_module_have_changed of <netconf_server.sysrepo_interface.config_change_subscriber.ConfigChangeSubscriber object at 0x7f4778f11a58>> callback failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sysrepo/subscription.py", line 221, in module_change_callback
    include_implicit_defaults=subscription.include_implicit_defaults,
  File "/usr/local/lib/python3.6/dist-packages/sysrepo/session.py", line 499, in get_changes
    node=libyang.DNode.new(ctx, node_p[0]),
  File "/usr/local/lib/python3.6/dist-packages/libyang/data.py", line 598, in new
    raise TypeError("node type %s not implemented" % cdata.schema.nodetype)
TypeError: node type 32 not implemented
2021-09-06 15:07:55,866 DEBG 'netopeer2-server' stdout output:
[ERR]: NP: Failed to send an RPC (User callback failed).

**Comment by michalvasko** [comment]
I think these anyxml and anydata nodes were not properly supported some time ago so you are probably using an old version.

**Comment by prudhivi66** [comment]
We are using the sysrepo python version 0.4.2 and netopeer2 version 1.1.76.
please let me know did I need to upgrade the version.

**Comment by michalvasko** [comment]
Ah, it seems the not-implemented error is in Python so in the bindings you are using. Then you can try asking in the `sysrepo-python` project, whether there are any plans of implementing this. We cannot help you.
