### ISSUE TITLE
No resolvent found for leafref

### ISSUE THREAD

**Issue by betsyrosemanuel** [CESNET/Netopeer2#101]
Hi,
     I tried installing the yang bbf-entity-extension using sysrepoctl but got the following error
[ERR] (srctl_ly_log_cb:479) libyang: No resolvents found for leafref "../../ietf-entity:physical-entity/ietf-entity:name".
[ERR] (srctl_ly_log_cb:479) libyang: Leafref is not conditional based on "entity-config" feature as its target.
[ERR] (srctl_ly_log_cb:479) libyang: Module "bbf-entity-extension" parsing failed.
Error: Unable to load the module by libyang.
Install operation failed.

**Comment by michalvasko** [comment]
Hi,
I could not find the schema, but based on the error it seems there is a leafref with value `../../ietf-entity:physical-entity/ietf-entity:name` and this target leaf has `if-feature` statement including feature `entity-config`. In that case the leafref itself should have an `if-feature` statement including a superset of `entity-config` feature ([RFC 7950 sec 9.9.](https://tools.ietf.org/html/rfc7950#section-9.9) last paragraph).

Regards,
Michal
