### ISSUE TITLE
Subscribe for notification issue

### ISSUE THREAD

**Issue by masif-cs** [CESNET/netopeer2#1012]
Hi,

Earlier I use to subscribe multiple yangs by calling 'n' subscribe calls but later when we moved to 1.x latest, we were allowed to do only one subscribe, so I changed the logic to send only one subscription with filter-xpath like `/o-ran-uplane-conf:*|/ietf-hardware:*|/o-ran-supervision:*|/o-ran-fm:*|/o-ran-sync:*` this.

Now after upgrade to 2.x latest, I am still able to subscribe with single subscription just like above but when the server is in 1.x and client is in 2.x, same subscription is failing.

Could you please help me resolve it, so that it works seemlessly in any version of client and server.

**Comment by michalvasko** [comment]
I am not sure what you expect for us to do, allowing multiple subscriptions was a bug and it was fixed at some point. We do not keep compatibility with previous bugs. Still, I do not know the reason why it should fail with *netopeer2-cli* v2, it is the server that generates the error.

**Comment by masif-cs** [comment]
I am not asking for multiple subscribe on same session to be supported. What I mean here is I am trying to perform single subscribe from v2 netopeer-client to latest v1 netopeer-server in above pipe separated filter-xpath format, but it fails.

 Where as if both server and client are in same version either latest v1 or v2, same format works fine. So what could be the reason and how to fix it.

subscribe --filter-xpath /_3gpp-common-managed-element:*|/commscope_3gpp-nr-nrm-nrcelldu:*
ERROR
type: application
tag: operation-failed
severity: error
message: libyang error

**Comment by iGovindY** [comment]
Hi Michal,

I think in-general notification subscription from a netopeer2-client with 2.0 version to a netopeer2-server with 1.x is not working.
please see below.

client2.0 means: `Netopeer2 CLI 2.0.64` from `devel` branch
client1.x means: `Netopeer2 CLI 2.0.62` from `liyang1` branch
server1.x means: `netopeer2-server 1.1.76` from `libyang1` branch

#### with client2.0 and server1.x 
notification subscribe gives error on server.
**on client**
```
> subscribe --filter-xpath /ietf-netconf-notifications:*
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	message:  libyang error
>
```
**on server**
```
| INFO | LY | netopeer2-server | Resolving unresolved data nodes and their constraints... |
| INFO | LY | netopeer2-server | All data nodes and constraints resolved. |
| INFO | LY | netopeer2-server | Resolving unresolved data nodes and their constraints... |
| INFO | LY | netopeer2-server | All data nodes and constraints resolved. |
| INFO | SR | netopeer2-server | Published event "rpc" "/notifications:create-subscription" with ID 7 priority 0 for 1 subscribers. |
| INFO | SR | netopeer2-server | Processing "/notifications:create-subscription" "rpc" event with ID 7 priority 0 (remaining 1 subscribers). |
| ERROR | LY | netopeer2-server | Unknown module "ncn". |
| ERROR | LY | netopeer2-server | Resolving XPath expression "(/ncn:*)" failed. (/ietf-yang-library:yang-library) |
| ERROR | SR | netopeer2-server | Resolving XPath expression "(/ncn:*)" failed. |
| INFO | SR | netopeer2-server | Failed processing of "rpc" event with ID 7 priority 0 (remaining 1 subscribers). |
| ERROR | SR | netopeer2-server | libyang error |
| WARNING | SR | netopeer2-server | Event "rpc" with ID 7 priority 0 failed (libyang error). |
| ERROR | NP | netopeer2-server | Failed to send an RPC (User callback failed). |
| INFO | NP | netopeer2-server | Session 3: thread 3 event new RPC. |
| INFO | NP | netopeer2-server | Session 3: thread 3 event reply error. |
```

---

#### with client1.x and server1.x 
notification subscribe works fine.

**Comment by michalvasko** [comment]
Right, that would actually make sense. I am not able to remember all this without a specific use-case but now I see that *libyang* v1 uses module names instead of prefixes in the `xpath` metadata that defines the filter in NETCONF RPCs. That is incorrect because XML prefixes should be used instead, which is implemented by *libyang* v2, but *libyang* v1 was simply not equipped to deal with this properly so it was simplified at the cost of interoperability issues. So I am not able to help you.

**Comment by masif-cs** [comment]
Ok I got it. So what I tried is if the yang module name and yang prefix name is same then subscription works fine between V1 and V2.

I have one more question not related to above discussion. Earlier when we use to do get-config then we use to get only yang level data but now I see that we are getting some ietf-netconf-nmda data as top level node along with the content like below. Is there any ways to remove it? Though I have checked code and seen that you have removed it in V2 but still asking if there is any other way to achieve it. Earlier this flag LYP_NETCONF use to avoid printing the rpc name.

```
<data xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-nmda">
  <hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
    <component>
      <name>Kumar</name>
    </component>
  </hardware>
</data>
```

**Comment by michalvasko** [comment]
There were some exceptions in handling a few standard RPCs in *libnetconf2* v1, which I have removed. You can easily get the "old behavior" by printing the data tree in the `struct lyd_node_any` `data` node. But the rpc-reply now always corresponds to the definition of `output` in YANG of the particular RPC, which was the intention.
