### ISSUE TITLE
Connection issue between netopeer2-server and netopeer2-cli 

### ISSUE THREAD

**Issue by bkumarrr** [CESNET/netopeer2#1013]
Hi All
I am connecting to netopeer2-server from netopeer2-cli but getting below error-
```
> connect --host 192.168.0.11
nc ERROR: Unable to connect to 192.168.0.11:830 (Connection refused).
nc ERROR: SSH channel poll error ().
cmd_connect: Connecting to the 192.168.0.11:830 as user "test" failed.
>
``` 
Please give your valuable comment on this and suggest some solution
NOTE: I am able to ping from both sides

**Comment by michalvasko** [comment]
I am not sure I can help you because `Connection refused` simply means that it was not possible to establish any connection with the other end, usually it is due to the server not listening. If it is, your connection may be blocked by some firewall.

**Comment by bkumarrr** [comment]
I am Able to take ssh from both sides 
Is this issue can be because of different version of netopeer2 [ as these are at different machines ] ?

**Comment by michalvasko** [comment]
No, this issue is too basic to be cause by version mismatch. Like I said then, it will most likely be a firewall problem because SSH connects on port 22 but NETCONF on 830.
