### ISSUE TITLE
netopeer2-server crashe issue 

### ISSUE THREAD

**Issue by bkumarrr** [CESNET/netopeer2#1015]
Hi All
I am when i am running netopeer2-server using `netopeer2-server -d -v3` getting below errors 

**[INF]: LY: Plugin "/usr/lib/libyang1/extensions/yangdata.so" successfully loaded.
[INF]: LY: Plugin "/usr/lib/libyang1/extensions/nacm.so" successfully loaded.
[INF]: LY: Plugin "/usr/lib/libyang1/extensions/metadata.so" successfully loaded.
[INF]: LY: Plugin "/usr/lib/libyang1/user_types/user_yang_types.so" successfully loaded.
[INF]: LY: Plugin "/usr/lib/libyang1/user_types/user_inet_types.so" successfully loaded.
[INF]: LY: Reading module "ietf-yang-metadata".
[INF]: LY: Module "ietf-yang-metadata@2016-08-05" successfully parsed as implemented.
[INF]: LY: Reading module "yang".
[INF]: LY: Resolving "yang" unresolved schema nodes and their constraints...
[INF]: LY: All "yang" schema nodes and constraints resolved.
[INF]: LY: Module "yang@2017-02-20" successfully parsed as implemented.
[INF]: LY: Reading module "ietf-inet-types".
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-inet-types" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-inet-types@2013-07-15" successfully parsed as implemented.
[INF]: LY: Reading module "ietf-yang-types".
[INF]: LY: Module "ietf-yang-types@2013-07-15" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-yang-types" in /etc/sysrepo/yang.
[INF]: LY: Resolving "sysrepo" unresolved schema nodes and their constraints...
[INF]: LY: All "sysrepo" schema nodes and constraints resolved.
[INF]: LY: Module "sysrepo@2021-01-18" successfully parsed as implemented.
[ERR]: LY: Failed to find matching hash for a child of "module". (/sysrepo:sysrepo-modules/module)
[ERR]: SR: Failed to find matching hash for a child of "module".
[ERR]: NP: Connecting to sysrepo failed (libyang error).
[ERR]: NP: Server init failed.
[INF]: NP: Server terminated.**
Please suggest me solution for this issue 
Thanks

**Comment by michalvasko** [comment]
That is quite weird, did you update *sysrepo* from some older version? In any case, should be fixed by running `make sr_clean` for *sysrepo*, which will completely reset it.

**Comment by bkumarrr** [comment]
Thanks @michalvasko Able to run now

**Comment by bkumarrr** [comment]
when I am importing xml file in sysrepo that time getting below error 
`sysrepocfg -Issh_callhome.xml -d running -m ietf-netconf-server`
**[ERR]: Unknown libyang error.
sysrepocfg error: Failed to connect (libyang error)**
Please help

**Comment by michalvasko** [comment]
At least use `-v3` to see more messages. But it seems like some fundamental problem, maybe some library incompatibility (older versions).
