### ISSUE TITLE
Error while enabling callhome feature in netopeer2

### ISSUE THREAD

**Issue by bkumarrr** [CESNET/netopeer2#1016]
Hi I am trying to enable callhome using netopeer2
But getting below error please help-
`$ sysrepocfg -Issh_callhome.xml -d running -m ietf-netconf-server`

**sysrepocfg error: libyang: Unknown element "keepalives".
sysrepocfg error: Data parsing failed**

**Comment by michalvasko** [comment]
Most probably you have some older version of `ietf-netconf-server` module installed from previous versions of *netopeer2*. Properly uninstall the old versions (most importantly `make sr_clean` for *sysrepo*) and try again.

**Comment by bkumarrr** [comment]
netopeer2-server is using `ietf-netconf-server@2019-07-02.yang`
and below are some version -
netopeer2-server 1.1.70
libsysrepo v1.4.122
yangre 1.10.17
libnetconf2 v1.1.43

**Comment by bkumarrr** [comment]
I have made yocto recipes to build netopeer2-server on target machine and I have installed `ietf-netconf-server@2019-07-02.yang` module and enabled this feature also using `sysrepoctl `

**Comment by michalvasko** [comment]
The install scripts are in separate files for this exact reason, so you can just copy them and execute on the target machine to avoid problems such as yours.

**Comment by bkumarrr** [comment]
Thanks @michalvasko 
Are you talking about the scripts which are in `/netopeer2/scripts `directory

**Comment by michalvasko** [comment]
Yes, they all need to be executed on the target machine for *netopeer2* installation to be considered complete. Also, you should have started the issue with mentioning that you are cross-compiling, it is a crucial piece of information, for next time.

**Comment by bkumarrr** [comment]
Yes , sorry @michalvasko for this time

**Comment by bkumarrr** [comment]
When I build netopeer2 and flash this in target machine and while running these scripts getting below logs :
`$ ./merge_config.sh `
**[ERR]: Module "ietf-netconf-server" was not found in sysrepo.
sysrepocfg error: Getting data failed (Invalid argument)**

`$ ./merge_hostkey.sh `
**[ERR]: Module "ietf-keystore" was not found in sysrepo.
sysrepocfg error: Getting data failed (Invalid argument)**

`$ ./setup.sh `
**Required environment variables not defined!**

**Comment by michalvasko** [comment]
Look, you decided to cross-compile it so it is up to you to get it right, there is no official guide even though we have tried to make it as easy as possible. Look into the original [install steps](https://github.com/CESNET/netopeer2/blob/devel/CMakeLists.txt#L300), you need to do exactly the same.

**Comment by bkumarrr** [comment]
Hi @michalvasko 
I have installed all required modules and able to run `merge_hostkey.sh` script but not able to run` merge_config.sh ` getting error like -
**sysrepocfg error: libyang: Unknown element "keepalives".
sysrepocfg error: Data parsing failed**

**Comment by michalvasko** [comment]
What do you mean you have installed the required modules? You **must** execute `setup.sh` successfully, as the **first** step and I am getting tired of repeating this. Otherwise you will keep encountering some errors.

**Comment by bkumarrr** [comment]
I have installed the mentioned modules which are in  `setup.sh`, getting some error while executing `setup.sh` like **Required environment variables not defined!**

**Comment by michalvasko** [comment]
That is why I have referenced the `cmake` script that executes this script so you can see what you need to define before executing `setup.sh`. I am simply not able to help you more.

**Comment by bkumarrr** [comment]
Thanks @michalvasko 
I am able to do now
