### ISSUE TITLE
json support for netopeer2 user-rpc --content

### ISSUE THREAD

**Issue by chendrashekarp** [CESNET/netopeer2#1017]
Hi @michalvasko ,
when i am trying to send an RPC content in json format im getting error as **ly ERROR: Invalid character sequence "{
"file-download":
{", expected element tag start ('<'). (Line number 1.)
nc ERROR: Failed to create RPC, perhaps a required feature is disabled.
cli_send_recv: Failed to send the RPC.**

Any idea on this.

**Comment by michalvasko** [comment]
*netopeer2-cli* is a NETCONF client and NETCONF supports only XML encoding so I do not think this should be supported even though it may be possible.
