### ISSUE TITLE
edit-config RPC failure

### ISSUE THREAD

**Issue by igortern** [CESNET/netopeer2#1022]
Hi,
The same problem is experienced with devel snapshot of sysrepo,libyang,libnetconf2 and netopeer2 and with the latest release (as of Sep 27).
Attempt to apply a configuration using netopeer-cli command 

- \> edit-config --target running --defop merge --test test-then-set --config=1-infra.txt

fails with error 

ERROR

	type:     application
	tag:      operation-failed
	severity: error
	message:  Callback event "rpc" with ID 1 processing timed out.

	type:     application
	tag:      operation-failed
	severity: error
	message:  User callback failed.

- sysrepo-devel/build/examples/application_changes_example ietf-interfaces
started alongside doesn't report any changes. 

- there are the following messages in netopeer2-server log

  [INF]: SR: Published event "rpc" "/ietf-netconf:edit-config" with ID 1 priority 0 for 1 subscribers.
  [ERR]: SR: Callback event "rpc" with ID 1 processing timed out.
  [WRN]: SR: Event "rpc" with ID 1 priority 0 failed (Timeout expired).
  [ERR]: SR: User callback failed.
  [ERR]: NP: Failed to send an RPC (User callback failed).

- there are also errors during netopeer-server startup

  [INF]: SR: Published event "rpc" "/ietf-netconf-nmda:get-data" with ID 1 priority 0 for 1 subscribers.
  [INF]: SR: Processing "/ietf-netconf-nmda:get-data" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
  [ERR]: LY: Internal error (/home/igort/Perforce/OLT/aspen/main/build/host-sim/third_party/libyang/libyang-devel/src/printer_lyb.c:419).
  [ERR]: SR: Internal error (/home/igort/Perforce/OLT/aspen/main/build/host-sim/third_party/libyang/libyang-devel/src/printer_lyb.c:419).
  [ERR]: SR: Callback event "rpc" with ID 1 processing timed out.
  [WRN]: SR: Event "rpc" with ID 1 priority 0 failed (Timeout expired).
  [ERR]: SR: User callback failed.
  [ERR]: NP: Failed to send an RPC (User callback failed).
  [INF]: NP: Session 1: thread 3 event new RPC.
  [INF]: NP: Session 1: thread 3 event reply error.

sysrepo repository and 1-infra.yc script are attached.

Could you help?

Best Regards,
Igor

[1-infra.txt](https://github.com/CESNET/netopeer2/files/7233910/1-infra.txt)
[sysrepo.zip](https://github.com/CESNET/netopeer2/files/7233917/sysrepo.zip)

**Comment by sjahngtera** [comment]
I also have the same exact issue when I send the "get" command on netopeer2-cli.
And once this error occurs, I keep getting these errors even for the commands that worked well, so I have to restart it or so.

**Comment by mrsugaranil** [comment]
Hi everybody,
I am facing the same issue with the version of Netopeer2 2.0.28. Previously, I was using version 1.1.70 and it was working perfectly. With new version I get ERROR "message:  Callback event "rpc" with ID 1 processing timed out." like you. 
Firstly,
I execute the server with "netopeer2-server -d -v3"
Next;
From client I execute "netopeer2-cli", then connect to server "connect --host IP ADDR --port 830 --login root"

Until here everthing is OK. But later, if try to "get" operational and state data from the server, I get timeout error as mention above. Furthermore, at the output of server debug messages I see;

**[ERR] Internal error (/usr/src/debug/libyang/2.0.88-r0/libyang-2.0.88/src/printer_lyb.c:419)**

RPC with ID 1 processing timeout and callback failed. 

Did you solve this problem? I spend too much effort to migrate APIs from version 1.x to 2.x. I hope solution is easy :(

Best regards,
Anil

**Comment by lePici** [comment]
Hi, it should be fixed now. I tried a similar scenario and from my point of view it was fine after the bugfix.

**Comment by igortern** [comment]
Hi, I can confirm that it works now. Is it possible to fast-track a release that includes this fix? As it stands, the latest release is unusable because of this problem. When we release our netconf server to customers, we prefer to base it on a release rather than devel to make behavior more predictable.
Thanks,
Igor

**Comment by michalvasko** [comment]
Yes, this is quite a major problem so in a few weeks there should be a new release.

**Comment by igortern** [comment]
thanks
