### ISSUE TITLE
Publishing RPMs?

### ISSUE THREAD

**Issue by esend7881** [CESNET/netopeer2#1027]
Similar to how the previous version had their RPMs published, will the new v2.x have its RPMs published here?

https://download.opensuse.org/repositories/home:/liberouter/CentOS_7/x86_64/

or maybe something like:
https://download.opensuse.org/repositories/home:/liberouter-v2/...

**Comment by michalvasko** [comment]
No, sorry, but we will not be building packages this way anymore. Generally, they should be available in the official repositories on Linux distributions but that will take some time and you can always build them yourself. That is, once the scripts are ready for all the projects, which should be by the end of this year latest.

**Comment by esend7881** [comment]
@michalvasko - good to know. I assume once the RPMs are up on official Linux distros, it will be noted in the readme files. Until this happens, our team will most likely stick with the previous 1.x versions of netopeer2.
