### ISSUE TITLE
access Netconf agt-rpc debug log message

### ISSUE THREAD

**Issue by netconfnewbee** [CESNET/netopeer2#1030]
In an SIL "get" callback,  I want to access  the "m" value displayed in the netconf log message:

     agt_rpc: <get> for 1=test@127.0.0.1 (m:1) [2021-10-05T04:16:22Z]

I am new to netconf so I apologize for the stupid question.

**Comment by michalvasko** [comment]
The message you have pasted is not familiar to me so I must assume it is generated by software not from our projects so I cannot help you.

**Comment by netconfnewbee** [comment]
I am using the Yuma123 Netconf package and yangcli.   I start Netconf with debug enabled.   Every time I issue a "get" in
yangcli I see the agt-rpc message I mentioned.

**Comment by netconfnewbee** [comment]
I found the code in ~/yuma123/netconf/src/agt/agt_rpc.c
in the procedure agt_rpc_dispatch ( see msgid )

       if (LOGDEBUG) {
            const xmlChar *msgid;
            tstamp_datetime(tstampbuff);
            if (attr != NULL && attr->attr_val != NULL) {
                msgid = attr->attr_val;
            } else {
                msgid = NCX_EL_NONE;
            }
            log_debug("\nagt_rpc: <%s> for %u=%s@%s (m:%s) [%s]",
                      method.elname,
                      scb->sid,
                      scb->username ? scb->username : NCX_EL_NONE,
                      scb->peeraddr ? scb->peeraddr : NCX_EL_NONE,
                      msgid,
                      tstampbuff);

But how do I access this data from a "get" callback which only has
limited arguments:

   static status_t mycallback (
      ses_cb_t *scb,
      getcb_mode_t cbmode,
      const val_value_t *virval,
      val_value_t *dstval)

AND, *scb is NULL.

**Comment by michalvasko** [comment]
You are not using our software, ask the authors of the one you are using for help.
