### ISSUE TITLE
sysrepo crashes on assertion

### ISSUE THREAD

**Issue by igortern** [CESNET/netopeer2#1039]
Hi,
With the latest set netopeer2 v2.0.30, sysrepo v2.0.47, libyang 2.0.97 and libnetconf2 2.0.19
sysrepo fails on assertion.

  _bcmolt_netconf_server: /home/igort/Perforce/OLT/aspen/main/build/host-sim/third_party/sysrepo/sysrepo- 
  2.0.47/src/common.c:4913: sr_xpath_next_name: Assertion `xpath && (xpath[0] == '/')' failed.`_

The issue can be reproduced using the attached repo sysrepo.zip and 2 netopeer2-cli edit-config scripts 1-infra.txt and 2-config-olt.txt applied in that order.

Could you have a look?

Thanks,
Igor
[2-config-olt.txt](https://github.com/CESNET/netopeer2/files/7325539/2-config-olt.txt)
[1-infra.txt](https://github.com/CESNET/netopeer2/files/7325540/1-infra.txt)
[sysrepo.zip](https://github.com/CESNET/netopeer2/files/7325541/sysrepo.zip)

**Comment by michalvasko** [comment]
I could not reproduce it but I think it is caused by some active operational subscription, do you have some? What is the XPath you subscribed for providing?

**Comment by igortern** [comment]
It works now, thanks!
Would it be possible to expedite the next release with this fix? So far there hasn't been any 2.x release that could be used with PON OLT yang model set. Consequently, all flavors of PON OLT netconf server released on github ([https://github.com/balapi/netconf-polt](url)), to BBF and to customers are forced to use the latest 1.x version.
Thanks,
Igor

**Comment by michalvasko** [comment]
Then you need to help us properly test *sysrepo* in your use-case so that it works. I do not see the point of making a new release after every bug fix.

**Comment by igortern** [comment]
Btw, if you can let me know about 2 days before the next release, I can test on BBF WT-385 yang models set to make sure that it works. I thought about adding an automatic regression test, but it isn't trivial.
Thanks,
Igor

**Comment by michalvasko** [comment]
Fine but if it works now, in all likelihood it should work even later if no major changes are implemented, I try to add a test for each found problem (I have added for this one but not mentioned it).
