### ISSUE TITLE
How Multiple RPC's at a same time is handled in netopeer2-server

### ISSUE THREAD

**Issue by bkumarrr** [CESNET/netopeer2#1040]
Hi 
I wish to learn let's say two RPC's are coming from netopeer2-cli at a same time targeting same datastore and second RPC containing the data to replace RPC1 configuration then how It is handled by netopeer2-server internally

**Comment by bkumarrr** [comment]
Do we have any mechanism to prioritize the client ?

**Comment by michalvasko** [comment]
I am not sure how to express myself more clearly, there are no priorities. The whole mechanism is quite complex and I would have to look into the code to determine what exactly it depends on. But if we are speaking only about connections (NETCONF sessions) to *netopeer2-server*, they are polled in order of being added using round-robin I believe.
