### ISSUE TITLE
Notification issue due to path.

### ISSUE THREAD

**Issue by Shubham-dash** [CESNET/netopeer2#1042]
Hi @michalvasko actually i have an issue looking for a help from u I am working on netopeer2-server/client sending XML from client side to set a callback for changes done in yang module but while I am sending XML connection is lost between server-client.Could u please help to come out of this.
Here are the logs I am getting in client side.
client side logs:
```
nc ERROR: Session 1: SSH channel poll error (Socket error: disconnected).
cli_send_recv: Failed to receive a reply.
```
XML I am sending :
```xml
<rpc message-id="101"
       xmlns="urn:o-ran:laa-operations:1.0">
        <start-measurements xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
		<band-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
                <band-number>n78</band-number>
                <carrier-center-frequency>3.4</carrier-center-frequency>
                </band-config>
        </start-measurements>
</rpc>
```

**Comment by michalvasko** [comment]
It meas the server crashed, usually. Are you using your server or *netopeer2-server*?

**Comment by Shubham-dash** [comment]
Ya i am using netopeer2-server only.So what could be the problem in this process?

**Comment by Shubham-dash** [comment]
Hi, @michalvasko I am writing an application to get a notification so I am giving a path in my macro for leaf in yang but that not working may be due to an incorrect path so, please give a solution for this. I am attaching below a particular leaf for which I want notification.

yang module : o-ran-laa-operations.yang
macro I am using in code:

#define laa_notif       "/o-ran-laa-operations:measurement-result"
#define laa_notif_node1 laa_notif "/band-result[band-number='BAND_46_SUBBAND_A']"
#define laa_notif_node2 laa_notif_node1 "/measurement-success"
#define laa_notif_node3 laa_notif_node1 "/failure-message='TIMEOUT'"
leaf:

leaf failure-message {
     when "../measurement-success='false'";
     type enumeration{
       enum TIMEOUT {
         description "Timed out waiting for measurement completion.";
       }
     }
     description "This value indicates the detailed error message for failure of the measurement at O-RU.";
   }

**Comment by michalvasko** [comment]
You cannot set `leaf` values with a predicate, you need to use the `value` parameter of `lyd_new_path()` (if you are using it). So the correct path is just
```
#define laa_notif_node3 laa_notif_node1 "/failure-message"
```
