### ISSUE TITLE
netopeer2-cli hitting assertion failure at lyd_insert_node() while connecting to server over TLS

### ISSUE THREAD

**Issue by ManabIPI** [CESNET/netopeer2#1043]
Getting below assertion failure in lyd_insert_node() while connecting to server over TLS

root@debian:~/net# cd netopeer2/build/
root@debian:~/net/netopeer2/build# ./netopeer2-cli
> connect --tls --host 10.12.93.111
netopeer2-cli: /root/net/libyang/src/tree_data.c:2553: lyd_insert_node: Assertion `(parent || first_sibling_p) && node && (node->hash || !node->schema)' failed.
Aborted

**Comment by akshathakm** [comment]
Hi @Michal Vasko

We are using the following version of netopeer2 and sysrepo

# netopeer2-cli
> version
**Netopeer2 CLI 2.0.64**
Compile time: Oct 18 2021, 08:34:45
>


# sysrepoctl --version
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with **libsysrepo v2.0.47 (SO v6.4.13)**
