### ISSUE TITLE
XML not working for yang module.

### ISSUE THREAD

**Issue by Shubham-dash** [CESNET/netopeer2#1044]
Hi everyone
I wrote XML for my yang module i.e; o-ran-laa-operations.yang but getting issue of Netopeer2-server/client connection lost i think there is problem in the format of XML then what should be the correct format for the mentioned yang module? so can anyone help me in this.

below is the XML format i wrote :
```xml
<rpc message-id="101"
	xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
        <start-measurements xmlns="urn:o-ran:laa-operations:1.0">
	<band-config>
                <band-number>N78</band-number>
                <channel-center-frequency>3.4</channel-center-frequency>
	</band-config>
        </start-measurements>
</rpc>
```

**Comment by michalvasko** [comment]
Okay but I am asking you to use 2.0.30, which is the latest 2.0 release. Also, you could attach the YANG module where these data are defined because there is an underlying issue causing this whole problem caused by you trying to send data that have no definition in YANG. My guess is that you should be using `user-rpc` instead of `edit-config`.

**Comment by Shubham-dash** [comment]
Thanks @michalvasko for your reply now i got the issue i was not using user-rpc.

**Comment by michalvasko** [comment]
`edit-config` RPC is used only for configuration data. For your own RPCs, you must use `user-rpc`.

**Comment by Shubham-dash** [comment]
Hi, @michalvasko I am writing an application to get a notification so I am giving a path in my macro for leaf in yang but that not working may be due to an incorrect path so, please give a solution for this. I am attaching below a particular leaf for which I want notification.

yang module : o-ran-laa-operations.yang

leaf:
 leaf failure-message {
      when "../measurement-success='false'";
      type enumeration{
        enum TIMEOUT {
          description "Timed out waiting for measurement completion.";
        }
      }
      description "This value indicates the detailed error message for failure of the measurement at O-RU.";
    }
