### ISSUE TITLE
Getting "ly WARNING" in client side.

### ISSUE THREAD

**Issue by Shubham-dash** [CESNET/netopeer2#1048]
Hi everyone 
I am getting some list of warnings while I am connecting to my client to the server any solution for this that I can resolve.

These are the warnings i am getting in client side :

ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Invalid value "SHARED-CELL-ETH-INTERFACE" which does not fit the type (Invalid enumeration value "SHARED-CELL-ETH-INTERFACE".).
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Invalid value "SHARED-CELL-ETH-INTERFACE" which does not fit the type (Invalid enumeration value "SHARED-CELL-ETH-INTERFACE".).
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Invalid value "SHARED-CELL-ETH-INTERFACE" which does not fit the type (Invalid enumeration value "SHARED-CELL-ETH-INTERFACE".).
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Invalid value "SHARED-CELL-ETH-INTERFACE" which does not fit the type (Invalid enumeration value "SHARED-CELL-ETH-INTERFACE".).
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Missing explicit "deprecated" status that was already specified in parent, inheriting.
ly WARNING: Invalid value "SHARED-CELL-ETH-INTERFACE" which does not fit the type (Invalid enumeration value "SHARED-CELL-ETH-INTERFACE".).

**Comment by Shubham-dash** [comment]
Ok, thanks. So how to resolve this issue?

**Comment by michalvasko** [comment]
Being brief, by making sure the XPath expressions make sense with respect to [RFC 7950](https://datatracker.ietf.org/doc/html/rfc7950). But fine, if you attach the actual YANG module(s), I will tell you the exact problem.

**Comment by yirs2001** [comment]
I met the same warning message by install o-ran-uplane-conf.yang.
The yang model is got from O-RAN.WG4.MP-YANGs-v06.00.
[o-ran-uplane-conf.zip](https://github.com/CESNET/netopeer2/files/7471825/o-ran-uplane-conf.zip)
thanks.

**Comment by yirs2001** [comment]
I met the same warning messages by install o-ran-processing-elements.yang
It comes from O-RAN.WG4.MP-YANGs-v06.00.
[o-ran-processing-element.zip](https://github.com/CESNET/netopeer2/files/7471858/o-ran-processing-element.zip)
Thanks.

**Comment by michalvasko** [comment]
I see, then this warning is invalid, the module is fine. What *libyang* version are you using? The latest version 2.0.109 does not generate this warning.

**Comment by yirs2001** [comment]
based on  Netopeer2 latest Release 18 version 2.0.30  
This release depends on libyang (v2.0.97), libnetconf2 (v2.0.19) and sysrepo (v2.0.47).

**Comment by michalvasko** [comment]
The warnings you have posted are certainly not from *libyang* 2.0.97, you are using some older version on the client, hence the messages.

**Comment by yirs2001** [comment]
For my case, I installed whole packages based pure docker ubuntu 18.04 image.
And Netopeer2/libyang/libnetconf2/sysrepo are all source-built & make install.
I also check if I apt-get/apt install Libyang, the answer is no.
My Netopeer2-server & netopeer-cli are both running in the same docker container.
any idea?
Thanks so much.

**Comment by michalvasko** [comment]
There will never be packages available in the official repositories right away and the first versions of our projects in versions 2 are just being published, the process takes quite a lot of time compared to the pace of the development. So you are best to compile everything from source if you want to stay up-to-date, `devel` branches always include the most recent versions.

**Comment by yirs2001** [comment]
Thanks.
I do the following test in docker ubuntu 18.04 image
I tried to build Netopeer2/libyang/libnetconf2/sysrep from the source & all checkout with level branch.
And I still got the same warnings.
1. the issue is because the feature is not enabled, so the enum type is not defined.
ex. 
the feature SHARED_CELL is not enabled in o-ran-processing-element.yang
so, the enum SHARED-CELL-ETH-INTERFACE  is not defined.
112     leaf transport-session-type {
113       type enumeration {
114         enum ETH-INTERFACE {
115           description "VLAN based CUS Transport ";
116         }
117         enum UDPIP-INTERFACE {
118           description "UDP/IP based CUS Transport ";
119         }
120         enum ALIASMAC-INTERFACE{
121           description "Alias MAC address based CUS Transport ";
122         }
123         enum SHARED-CELL-ETH-INTERFACE {
124           if-feature "SHARED_CELL";
125           description "VLAN based CUS Transport used for Shared Cell scenario";
126         }
127       }
128       default ETH-INTERFACE;
129       description
130         "the type of transport session used for identifying different processing
131         elements";
132     }

**Comment by michalvasko** [comment]
I though this was implemented and working but seems it was not. If you try the latest *libyang* from `devel`, it should work.

**Comment by yirs2001** [comment]
Thanks, I test with libyang f4fa90d, it works.
==================================
I don't know if it is suitable for post here.
There is similar warning which is still existed:
[WRN]: LY: Invalid value "TRUE" which does not fit the type (Invalid boolean value "TRUE".).
[WRN]: LY: Previous warning generated by XPath subexpression[73] "ordered-transmission-supported = 'TRUE'" with context node "/o-ran-uplane-conf:user-plane-configuration/static-low-level-rx-endpoints/transmission-order-group".
[WRN]: LY: Invalid value "TRUE" which does not fit the type (Invalid boolean value "TRUE".).
[WRN]: LY: Previous warning generated by XPath subexpression[73] "ordered-transmission-supported = 'TRUE'" with context node "/o-ran-uplane-conf:user-plane-configuration/static-low-level-rx-endpoints/transmission-order-group".
[WRN]: LY: Invalid value "TRUE" which does not fit the type (Invalid boolean value "TRUE".).
[WRN]: LY: Previous warning generated by XPath subexpression[73] "ordered-transmission-supported = 'TRUE'" with context node "/o-ran-uplane-conf:user-plane-configuration/static-low-level-rx-endpoints/transmission-order".
[WRN]: LY: Invalid value "TRUE" which does not fit the type (Invalid boolean value "TRUE".).
[WRN]: LY: Previous warning generated by XPath subexpression[73] "ordered-transmission-supported = 'TRUE'" with context node "/o-ran-uplane-conf:user-plane-configuration/static-low-level-rx-endpoints/transmission-order".
[WRN]: LY: Invalid value "TRUE" which does not fit the type (Invalid boolean value "TRUE".).
[WRN]: LY: Previous warning generated by XPath subexpression[0] "static-transmission-window-control-supported = 'TRUE'" with context node "/o-ran-uplane-conf:user-plane-configuration/endpoint-types".
[WRN]: LY: Invalid value "TRUE" which does not fit the type (Invalid boolean value "TRUE".).
[WRN]: LY: Previous warning generated by XPath subexpression[57] "dynamic-transmission-window-control-supported = 'TRUE'" with context node "/o-ran-uplane-conf:user-plane-configuration/endpoint-types".
[WRN]: LY: Invalid value "TRUE" which does not fit the type (Invalid boolean value "TRUE".).
[WRN]: LY: Previous warning generated by XPath subexpression[0] "static-transmission-window-control-supported = 'TRUE'" with context node "/o-ran-uplane-conf:user-plane-configuration/endpoint-types".
[WRN]: LY: Invalid value "TRUE" which does not fit the type (Invalid boolean value "TRUE".).
[WRN]: LY: Previous warning generated by XPath subexpression[57] "dynamic-transmission-window-control-supported = 'TRUE'" with context node "/o-ran-uplane-conf:user-plane-configuration/endpoint-types".
[WRN]: LY: Invalid value "TRUE" which does not fit the type (Invalid boolean value "TRUE".).
[WRN]: LY: Previous warning generated by XPath subexpression[3] "dynamic-uniformly-distributed-transmission-supported = 'TRUE'" with context node "/o-ran-uplane-conf:user-plane-configuration/endpoint-types/dynamic-uniformly-distributed-transmission-per-section-supported".
[WRN]: LY: Invalid value "TRUE" which does not fit the type (Invalid boolean value "TRUE".).
[WRN]: LY: Previous warning generated by XPath subexpression[3] "dynamic-transmission-window-control-supported = 'TRUE'" with context node "/o-ran-uplane-conf:user-plane-configuration/endpoint-types/dynamic-transmission-window-control-per-section-supported".


In o-ran-uplane-conf.yang:
I didn't enable feature ORDERED-TRANSMISSION.
1563       leaf ordered-transmission-supported {                                                         
1564         if-feature feat:ORDERED-TRANSMISSION;                                                       
1565         type boolean;                                                                               
1566         description                                                                                 
1567           "Endpoint supports ordered transmission of U-plane messages                               
1568            and can be configured with ordered-transmission = TRUE";                                 
1569       }
...
1951       leaf transmission-order {                                                                     
1952         when "(/user-plane-configuration/endpoint-types[id=current()/../endpoint-type]/ordered-transmission-supported = 'TRUE')";
1953         if-feature feat:ORDERED-TRANSMISSION;                                                       
1954         type uint32;                                                                                
1955         description                                                                                 
1956           "The value indicates relative order of sending U-plane messages specific to same symbol   
1957            and transmission window by two endpoints with ordered-transmission = TRUE                
1958            belonging to the same transmission-order-group;                                          
1959            multiple endpoints may report the same value if their relative sending order is not guaranteed";
1960       }                                                                                             
1961                                                                                                     
1962       leaf transmission-order-group {                                                               
1963         when "(/user-plane-configuration/endpoint-types[id=current()/../endpoint-type]/ordered-transmission-supported = 'TRUE')";
1964         if-feature feat:ORDERED-TRANSMISSION;                                                       
1965         type uint32;                                                                                
1966         description                                                                                 
1967           "The value indicates a group of endpoints that preserve relative ordering of message sending;
1968            message sending between endpoints in different groups is not guaranteed";                
1969       }

**Comment by michalvasko** [comment]
This warning has nothing to do with features and tells you exactly what the problem is. `TRUE` is not a valid value boolean value in YANG, only `true` and `false` is.

**Comment by yirs2001** [comment]
Thanks.
For my understanding. Because the feature: ORDERED-TRANSMISSION is not defined.
So #line 1962 leaf transmission-order-group shouldn't be existed.
Then we won't get warning, is that correct?

**Comment by michalvasko** [comment]
Whether the feature is enabled or not, the XPath is invalid, hence the warning. But it is true the problem will not affect functioning in case the feature is disabled so I suppose you can ignore it.

**Comment by yirs2001** [comment]
Thanks.
