### ISSUE TITLE
edit-config question

### ISSUE THREAD

**Issue by linbolin** [CESNET/netopeer2#1050]
Hello!
    When the configuration data changes, the configuration callback function is called, The callback function setting fails, but the netopeer2-cli displays success.
    How should this problem be handled.

**Comment by jktjkt** [comment]
Be sure to read the documentation about the [change event types, especially the `SR_EV_CHANGE` vs. `SR_EV_DONE`](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__change__subs__api.html#gad007e862874bda7141c58ca72d8c1067).

**Comment by linbolin** [comment]
The problem has been solved, thank you very much!
