### ISSUE TITLE
TLS issue: LN: SSL_accept failed (sslv3 alert bad certificate)

### ISSUE THREAD

**Issue by spavell** [CESNET/netopeer2#1052]
Hi, 

I'm trying to connect to the server using TLS. I have followed the README and issues that other have raised but upon connection the server always giving the same error:  [ERR]: LN: SSL_accept failed (sslv3 alert bad certificate). I'm using the xmls and certificates provided in the repo under example_configuration and all the dependancies are the latest to the date.

Please suggest what am I doing wrong.

1. Server side 
sysrepocfg --edit=tls_keystore.xml -m ietf-keystore
sysrepocfg --edit=tls_truststore.xml -m ietf-truststore
sysrepocfg --edit=ls_listen.xml -m ietf-netconf-server
netopeer2-server -dv2

2. Client side 
netopeer2-cli
cert replaceown  ./example_configuration/tls_certs/client.crt ./example_configuration/tls_certs/client.key
cert add ./example_configuration/tls_certs/ca.pem

connect --tls --host 172.17.0.2
nc ERROR: SSL_connect failed (certificate verify failed).
cmd_connect: Connecting to the 172.17.0.2:6513 failed.

> cert display
-----ca----- serial: 45ce2c8a91ef25294dad0221461662941bd5e11a
Subject: C=CZ, ST=South Moravia, L=Brno, O=CESNET z.s.p.o., OU=TMC, CN=example CA/emailAddress=ca@example.org
Issuer:  C=CZ, ST=South Moravia, L=Brno, O=CESNET z.s.p.o., OU=TMC, CN=example CA/emailAddress=ca@example.org
Valid until: Sep  1 10:21:01 2031 GMT

> cert displayown
OK: Using *.crt certificate with a separate private key.
-----CRT----- serial: 47f82c15c5f3457a6d35a7ea427f46e71ca49fc0
Subject: C=CZ, ST=South Moravia, L=Brno, O=CESNET z.s.p.o., OU=TMC, CN=client/emailAddress=client@example.org
Issuer:  C=CZ, ST=South Moravia, L=Brno, O=CESNET z.s.p.o., OU=TMC, CN=example CA/emailAddress=ca@example.org
Valid until: Sep  1 10:28:18 2031 GMT

Thanks,
Pavel

**Comment by michalvasko** [comment]
The answer is in the [README](https://github.com/CESNET/netopeer2/#tls-listen), second paragraph. Server hostname (`172.17.0.2`) comparison with the identity in the certificate (`localhost`) fails.

**Comment by spavell** [comment]
Thanks for pointing it out to me. If I understand correctly, in order to work outside the local host I have to provide my own certificates and update the xml files?

**Comment by michalvasko** [comment]
Yes, that is how the requirements are specified so the example certificates can really be used only for basic testing of the TLS connection. Although that may not be a bad thing.

**Comment by spavell** [comment]
Ok thanks a lot.

Then a quick question if I may regarding listen.xml. In the xml the ca fingerprint is 
<fingerprint>02:20:E1:AD:CC:92:71:E9:EA:6A:85:DF:A7:FF:8C:BB:B9:D5:E4:EE:74</fingerprint> 
but when I check ca fingerprint with openssl, it doesn't have the first '02':
openssl x509 -noout -fingerprint -inform pem -in ca.pem 
SHA1 Fingerprint=20:E1:AD:CC:92:71:E9:EA:6A:85:DF:A7:FF:8C:BB:B9:D5:E4:EE:74 
Am I suppose to add it to the fingerprint by myself?

Thanks

**Comment by michalvasko** [comment]
Yes, you need to add it yourself. It is always advised to read the [description](https://github.com/CESNET/netopeer2/blob/master/modules/ietf-x509-cert-to-name%402014-12-10.yang#L60) of the value you are setting.
