### ISSUE TITLE
Notification is not working for yang module.

### ISSUE THREAD

**Issue by Shubham-dash** [CESNET/netopeer2#1058]
Hi everyone
I am getting issue for not getting notification from server to client while I am sending RPC to the server for yang module i.e; o-ran-laa-operations.yang this yang module is containing notification node(measurement-result) but every time it is throwing error like this ([ERR]: Not found node "measurement-result" in path.).Please help me with this problem I am facing.

The notification sending function i am using in code : sr_event_notif_send()

The code snippet to get notification with particular path is : 
```C
     #define laa_notif "/o-ran-laa-operations:measurement-result"
     #define laa_notif_node1  laa_notif"/band-number" 
     #define laa_notif_node2    laa_notif"/measurement-success"       

     values[0].xpath = strdup(laa_notif_node1);
     values[0].type = SR_ENUM_T;
     values[0].dflt = 0;
     values[0].data.enum_val = band_num;

     values[1].xpath = strdup(laa_notif_node2);
     values[1].type = SR_BOOL_T;
     values[1].dflt = 0;
     values[1].data.bool_val = ret;
     sr_event_notif_send(session,laa_notif,values,values_cnt,0,0);
```

**Comment by michalvasko** [comment]
I would have to see the YANG module, it seems the notification is not found for some reason. There may be false `if-feature` statement on it, for example.

**Comment by Shubham-dash** [comment]
Ya in my yang module RPC statements was containing if-feature statement I have edited if-feature statement I was not using that but I forgot to edit that feature also present inside the notification node now done that thing but again getting error like this below :  

[ERR]: Predicate missing for list "band-result" in path "/o-ran-laa-operations:measurement-result/band-result/band-number".

**Comment by michalvasko** [comment]
It seems `band-number` is a list and it needs a predicate with value for its key. I would suggest using `sr_event_notif_send_tree()` where you create the notification with `lyd_new_path()`, I believe it would be much shorter and simpler.

**Comment by Shubham-dash** [comment]
`band-result` is a list inside notification node and then this node is uses grouping `band-result-element` 
Below is my yang module 
module o-ran-laa-operations {
	yang-version 1.1;
  namespace "urn:o-ran:laa-operations:1.0";
  prefix "o-ran-laa-operations";

  import o-ran-module-cap {
    prefix "mcap";
  }

  organization "O-RAN Alliance";

  contact
    "www.o-ran.org";

  description
    "This module defines the operations for DFS measurement.

    Copyright 2019 the O-RAN Alliance.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS'
    AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
    IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
    ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
    LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
    CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
    SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
    INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
    CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
    POSSIBILITY OF SUCH DAMAGE.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
    this list of conditions and the above disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the above disclaimer in the documentation
    and/or other materials provided with the distribution.
    * Neither the Members of the O-RAN Alliance nor the names of its
    contributors may be used to endorse or promote products derived from
    this software without specific prior written permission.";

  revision "2019-07-03" {
    description
      "version 1.1.0

      1) corrected error in module reference for LAA feature";

    reference "ORAN-WG4.M.0-v01.00";
  }

  revision "2019-02-04" {
    description
      "version 1.0.0

      1) imported model from xRAN
      2) changed namespace and reference from xran to o-ran";

    reference "ORAN-WG4.M.0-v01.00";
  }

  typedef band-num {
    type enumeration {
      enum BAND_46_SUBBAND_A {
        description
          "46a: 5150 MHz 	-	5250 MHz";
      }
      enum BAND_46_SUBBAND_B {
        description
          "46b: 5250 MHz 	-	5350 MHz";
      }
      enum BAND_46_SUBBAND_C {
        description
          "46c: 5470 MHz 	-	5725 MHz";
      }
      enum BAND_46_SUBBAND_D1 {
        description
          "46d1: 5725 MHz 	-	5850 MHz";
      }
      enum BAND_46_SUBBAND_D2 {
        description
          "46d2: 5850 MHz 	-	5925 MHz";
      }
    }
    description
      "This value indicates the list of bands supported as per the document,
      3GPP TS 36.104 V14.2.0 (2016-12), 'Section 5.5 Operation bands'.";
  }

  grouping band-configuration {
    description
      "Grouping for band configuration";

    leaf band-number {
      type band-num;
      description
        "This value indicates the list of bands supported as per the document,
        3GPP TS 36.104 V14.2.0 (2016-12), 'Section 5.5 Operation bands'.";
    }
    leaf-list channel-center-frequency {
      type uint16;
      units kilohertz;
      description
        "This value indicates carrier center frequency in KHz";
    }
  }

  grouping measurement-parameters {
    description
      "Grouping for measurement parameters";

    leaf duration-per-channel {
      type uint16;
      units milliseconds;
      description
        "This value indicates measurement duration per channel in milliseconds.";
    }

    leaf maximum-response-time {
      type uint16;
      units seconds;
      description
        "This value indicates maximum response time (i.e., timer) in seconds.";
    }
  }

  grouping channel-result-element {
    description
      "Grouping for channel result element";

    leaf measured-channel {
      type uint16;
      units kilohertz;
      description
        "This value indicates carrier center frequency for which the result is computed in KHz.";
    }

    leaf occupancy-ratio {
      type uint8;
      units percent;
      description
        "This value indicates occupancy ratio in percentage.";
    }

    leaf average-rssi {
      type int8;
      units dBm;
      description
        "This value indicates average RSSI in dBm";
    }
  }

  grouping band-result-element {
    description
      "Grouping for band result element";

    leaf band-number {
      type band-num;
      description
        "This value indicates the band for which the result is computed.";
    }

    leaf measurement-success {
      type boolean;
      description
        "This value indicates whether the measurement is successful for the given band.";
    }
    leaf failure-message {
      when "../measurement-success='false'";
      type enumeration {
        enum TIMEOUT {
          description "Timed out waiting for measurement completion.";
        }
      }
      description "This value indicates the detailed error message for failure of the measurement at O-RU.";
    }

    list channel-result {
      when "../measurement-success='true'";
      key "measured-channel";
      description "Results for a particular channel";

      uses channel-result-element;
    }
  }

  //rpc definitions
  rpc start-measurements {
    if-feature mcap:LAA;
    description "Measurements for Carrier-Selection and Dynamic Frequency Selection (DFS)";
     input {
      list band-config {
        key "band-number";
        description "Per band configuration for measurements.";

        uses band-configuration;
      }

      uses measurement-parameters;
    }

    output {
      list band-config {
        key "band-number";
        description "Output list for all the bands requested for measurements.";

        leaf band-number {
          type band-num;
          description
            "This value indicates the list of bands supported as per the document,
            3GPP TS 36.104 V14.2.0 (2016-12), 'Section 5.5 Operation bands'.";
        }
        leaf-list carrier-center-frequency {
          type uint16;
          units kilohertz;
          description
            "This value indicates carrier center frequency in KHz";
        }
        leaf status {
          type enumeration {
            enum ACCEPTED {
              description "This indicates the measurements for particular sub band is accepted at O-RU.";
            }
            enum REJECTED {
              description "This indicates the measurements for particular sub band is rejected at O-RU.";
            }
          }
          description "This value indicates the status of the measurement acceptance at O-RU.";
        }

	leaf error-message {
          when "../status='REJECTED'";
          type string;
          description
            "This value indicates the detailed error message for the measurement being rejected at O-RU.";
        }
      }
    }
  }

  // notifications
  notification measurement-result {
    if-feature mcap:LAA;
    description "Notification to provide the results of carrier selection and DFS.";
    list band-result {
      key "band-number";
      description "Results for a particular sub band under band 46.";

      uses band-result-element;
    }
  }
}

**Comment by michalvasko** [comment]
In that case your node paths seem wrong because you are skipping the list `band-result` completely. You must include it and set its key value directly in the path such as:
```
.../band-list[band-number='BAND_46_SUBBAND_A']...
```

**Comment by Shubham-dash** [comment]
@michalvasko 
i have updated my Macro
` #define laa_notif_node1  laa_notif"/band-result[band-number='BAND_46_SUBBAND_A']"`
After updating below error is coming at server side 
**[ERR]: Invalid argument path (lyd_new_path2()).**

**Comment by michalvasko** [comment]
I really do not know what you are doing there to get `invalid argument` error. T have tried [this](https://github.com/CESNET/netopeer2/files/7504699/test.tar.gz) example application and it worked just fine.

**Comment by Shubham-dash** [comment]
I am not getting the actual issue getting same issue of invalid path again here is my application below : 


#define _GNU_SOURCE
#define _XOPEN_SOURCE 500

#include <inttypes.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include<stdbool.h>
#include <errno.h>
#include <sysrepo/values.h>

#include <libyang/libyang.h>

#include "sysrepo.h"

#define RPC "/o-ran-laa-operations:start-measurements"
#define RPC1 RPC "/band-number"
#define RPC_freq RPC "/channel-center-frequency"

#define laa_notif       "/o-ran-laa-operations:measurement-result"
#define laa_notif_node1 laa_notif "/band-result[band-number='BAND_46_SUBBAND_A']"
#define laa_notif_node2 laa_notif_node1 "/measurement-success"

volatile int exit_application = 0;

static int
rpc_cb(sr_session_ctx_t *session, uint32_t sub_id, const char *path, const sr_val_t *input, const size_t input_cnt,
        sr_event_t event, uint32_t request_id, sr_val_t **output, size_t *output_cnt, void *private_data)
{
    size_t i=2;

    (void)session;
    (void)sub_id;
    (void)event;
    (void)request_id;
    (void)private_data;
    sr_val_t *values = NULL;
    uint32_t values_cnt = 0;
   // size_t values_cnt = 0;
    char *band_num = NULL,*freq = NULL;   //*custom_par = NULL;
    int ret = 0;
    printf("\n\n ========== RPC \"%s\" RECEIVED: =======================\n\n", path);
     if(!strcmp(path,RPC)) {
	if(strcmp(path,RPC1) || strcmp(path,RPC_freq)) {
		band_num = input[i - 1].data.string_val;
		printf("Band number is :%s\n",band_num);
		printf("Carrier freq. is :%d\n",input[i].data.uint16_val);
     		ret = 1;
	}
    else { 
		printf("Inside Else.\n");
        }

  }
        sr_new_values(2, &values);
	values_cnt = 3;
	values = calloc(values_cnt,sizeof *values);
	if(values == NULL) {
		printf("Calloc failed\n");
        }
	bool status;
	if(ret == 1) {
		status = 1;
	} else status = 0;

        values[0].xpath = strdup(laa_notif_node1);
        values[0].type = SR_LIST_T;
        values[0].dflt = 0;
        values[0].data.enum_val = band_num;
 
        values[1].xpath = strdup(laa_notif_node2);
        values[1].type = SR_BOOL_T;
        values[1].dflt = 0;
        values[1].data.bool_val = 1;

        sr_event_notif_send(session,laa_notif,values,values_cnt,0,0);
        sr_free_values(values, values_cnt);  


   return SR_ERR_OK;

}

static void
sigint_handler(int signum)
{
    (void)signum;

    exit_application = 1;
}

int
main(void)
{
    sr_conn_ctx_t *connection = NULL;
    sr_session_ctx_t *session = NULL;
    sr_subscription_ctx_t *subscription = NULL;
    int rc = SR_ERR_OK;
    const char *path;

    path = "/o-ran-laa-operations:start-measurements";
    printf("Application will subscribe to \"%s\" RPC.\n\n", path);

    /* turn logging on */
    sr_log_stderr(SR_LL_WRN);

    /* connect to sysrepo */
    rc = sr_connect(0, &connection);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }

    /* start session */
    rc = sr_session_start(connection, SR_DS_RUNNING, &session);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }

    /* subscribe for the RPC */
    rc = sr_rpc_subscribe(session, path, rpc_cb, NULL, 0, 0, &subscription);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }

    printf("\n\n ========== LISTENING FOR RPC ==========\n\n");


    /* loop until ctrl-c is pressed / SIGINT is received */
    signal(SIGINT, sigint_handler);
    signal(SIGPIPE, SIG_IGN);
    while (!exit_application) {
        sleep(1000);
    }

    printf("Application exit requested, exiting.\n");

cleanup:
    sr_disconnect(connection);
    return rc ? EXIT_FAILURE : EXIT_SUCCESS;
}

**Comment by michalvasko** [comment]
Well, you are allocating 3 `values` but filling only 2 so the last item is empty, which generates the error. Please try to debug your programs yourself before asking for help, this is a really basic problem.

**Comment by Shubham-dash** [comment]
Hi @michalvasko 
I have tried by allocating 2 `values ` in above code.still getting same error 
please help !!!

**Regards**
Shubham

**Comment by michalvasko** [comment]
How exactly does your allocation look like? `values_cnt` must also be 2.

**Comment by Shubham-dash** [comment]
@michalvasko 
I have tried with` values_cnt` 2 also .but still same error i am getting

**Comment by michalvasko** [comment]
I have tested [this](https://github.com/CESNET/netopeer2/files/7512989/test.tar.gz) example with the notification being subscribed by *sysrepo* example, this is the output:
```
sysrepo/examples/notif_subscribe_example o-ran-laa-operations
Application will subscribe to "o-ran-laa-operations" notifications.



 ========== LISTENING FOR NOTIFICATIONS ==========



 ========== NOTIFICATION "/o-ran-laa-operations:measurement-result" RECEIVED =======================

/o-ran-laa-operations:measurement-result/band-result[band-number='BAND_46_SUBBAND_A'] (list instance)
/o-ran-laa-operations:measurement-result/band-result[band-number='BAND_46_SUBBAND_A']/band-number = BAND_46_SUBBAND_A
/o-ran-laa-operations:measurement-result/band-result[band-number='BAND_46_SUBBAND_A']/measurement-success = true
```

**Comment by Shubham-dash** [comment]
thanks, @michalvasko for your valuable time now notification is working fine in my code.


**Regards,**
Shubham
