### ISSUE TITLE
client and server connection issue with call home

### ISSUE THREAD

**Issue by chendrashekarp** [CESNET/netopeer2#1063]
Hi @michalvasko ,
after running netopeer-cli and trying to connect to server with call-home getting below error .
can you give any suggestions on this issue.
```

> listen
Waiting 60s for an SSH Call Home connection on port 4334...
The authenticity of the host '::ffff:192.168.10.23' cannot be established.
ssh-rsa key fingerprint is a3:7a:1e:4d:ba:c8:43:18:a5:89:b7:fe:f6:62:2a:6c:c1:76:74:b4.
Are you sure you want to continue connecting (yes/no)? yes
root@::ffff:192.168.10.23 password:
nc ERROR: Server <hello> timeout elapsed.
cmd_listen: Receiving SSH Call Home on port 4334 as user "root" failed.
```

**Comment by michalvasko** [comment]
Was there an actual timeout after you input the password or you saw the error immediately? What did the server print if executed with `-d -v2`?

**Comment by chendrashekarp** [comment]
Hi @michalvasko ,
getting this error immediately.

**Comment by michalvasko** [comment]
What *libssh* version are you using?

**Comment by chendrashekarp** [comment]
Hi @michalvasko ,
libssh version is 
`0.8.90`

**Comment by michalvasko** [comment]
That is not a valid version but `master` compiled from source, who knows when. Uninstall this version and install instead a specific version, 0.9.6 is the latest but 0.9.5 is fine, too. Then try again.

**Comment by chendrashekarp** [comment]
Okay Michal , I will update once I check this thing

Reagards,
Chendrashekar p
________________________________

**Comment by chendrashekarp** [comment]
Hi @michalvasko ,
i upgraded the libssh to 0.9.6 ,
i am trying to connect netopeer2 server using connect ,

getting this error  at client :
```

nc ERROR: Server <hello> timeout elapsed.
ly ERROR: Value "root" was not found in the dictionary.
ly ERROR: Value "192.168.2.217" was not found in the dictionary.
cmd_connect: Connecting to the 192.168.2.217:830 as user "root" failed

```

and at server :
```
[INF]: LN: Accepted a connection on 0.0.0.0:830 from 192.168.2.178:49818.
[INF]: SR: Session 33 (user "root", CID 1) created.
[INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: LN: Received an SSH message "request-auth" of subtype "none".
[INF]: LN: Received an SSH message "request-auth" of subtype "interactive".
[INF]: LN: Received an SSH message "request-auth" of subtype "interactive".
[INF]: LN: User "root" authenticated.
[INF]: LN: Received an SSH message "request-channel-open" of subtype "session".
[INF]: LN: Received an SSH message "request-channel" of subtype "subsystem".
[INF]: SR: Session 34 (user "root", CID 1) created.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-start).
[ERR]: LN: Session 2: SSH channel unexpected EOF.
[INF]: NP: Session 2: thread 3 event session terminated.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-end).
[2021/11/12 09:31:21.002046, 1] ssh_socket_exception_callback:  Socket exception callback: 2 (104)
[2021/11/12 09:31:21.002081, 1] ssh_socket_exception_callback:  Socket error: Connection reset by peer
[2021/11/12 09:31:21.002118, 1] ssh_socket_exception_callback:  Socket exception callback: 2 (104)
[2021/11/12 09:31:21.002145, 1] ssh_socket_exception_callback:  Socket error: Connection reset by peer

```

**Comment by michalvasko** [comment]
I see, then it seems it will be the version of your libraries, which *libyang*, *libnetconf2*, *sysrepo*, and *netopeer2* are you using?

**Comment by chendrashekarp** [comment]
netopeer2 :**2.0.28**
yanglint : **2.0.88**
libsysrepo **v2.0.41**
libnetconf2 : **2.0.17**

**Comment by michalvasko** [comment]
Those should be fine, please make sure you are really using them. If you run `ldconfig -p`, you will see all the libraries found on your system, make sure there is only one version of *libssh*, *libyang*, *libnetconf*, and *libsysrepo*. Then you can run `ldd netopeer2-server` to see the libraries linked with the server.

**Comment by chendrashekarp** [comment]
Hi @michalvasko ,
attaching a output file of a netopee2_cli with verb 3
please have a look and tell me if you find anything .[
[DU_output.txt](https://github.com/CESNET/netopeer2/files/7528307/DU_output.txt)
](url)

**Comment by michalvasko** [comment]
Right the 8th line says `libssh 0.9.3`, which is a buggy version causing this problem, that is why I have told you to use 0.9.5 or 0.9.6.

**Comment by chendrashekarp** [comment]
libssh netopeer2 is linking from other folder rather from /usr/local/lib,
replaced the files with /usr/local/lib/libssh*
