### ISSUE TITLE
Can we connect multiple client using TLS and please elaborate certificate creation method 

### ISSUE THREAD

**Issue by kishore-vvdn** [CESNET/netopeer2#1065]
I am trying to with multiple client by creating certificates for each client and Updating the tls_keystore.xml  tls_listen.xml  tls_truststore.xml file with client certificate details.But still i am unable to make server and client communication.

NF]: LY: All data nodes and constraints resolved.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: LN: Listening on 0.0.0.0:830 for SSH connections.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: LN: Listening on 0.0.0.0:6513 for TLS connections.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Ext SHM was defragmented and 4256 B were saved.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Ext SHM was defragmented and 4368 B were saved.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-keystore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-truststore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: LN: Accepted a connection on 0.0.0.0:6513.
[INF]: SR: Session 12 (user "root") created.
[INF]: SR: Session 13 (user "root") created.
[INF]: SR: Session 14 (user "root") created.
**[ERR]: LN: SSL_accept failed (tlsv1 alert unknown ca).**

i am using netopeer2 v1.1.39 

And i am able to make communication with the certificates which you have provide under tls_certs/

I am following the below links to create certificates
https://www.makethenmakeinstall.com/2014/05/ssl-client-authentication-step-by-step/
https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/Security/SSL/GeneratingCertificationsAndKeys.htm#1
https://gerrit.cesnet.cz/plugins/gitiles/github/CESNET/Netopeer2/+/e84838a06b1272155ed2d985c52d2683f26578c1/server/configuration/

Could please provide more details on how to create certificates for multiple clients?

Thanks in advance.

**Comment by michalvasko** [comment]
Look, you should really learn more about how certificates and TLS work in general, that is not specific for *netopeer2*. After that the error message should actually tell you the problem (does not always happen with OpenSSL). If you look at the example configuration, the Certificate Authority certificate is there and is used for verifying the client certificate(s). It seems you have not configured this certificate properly, it is not know.
