### ISSUE TITLE
Get rpc showing issue 

### ISSUE THREAD

**Issue by Abrahamma97** [CESNET/netopeer2#1066]
Hi @michalvasko ,
I am successfully able to use get-config after netopeer2 client and server connection. But I am not able to use  get command from client. 
netopeer - v1.1.70
sysrepo - v1.4.122

The following error is seen

Netopeer client log 
> get
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	message:  Internal error

Additional logs:
Netopeer2 server log
Dec 28 23:19:42 abey daemon.warn netopeer2-server[869]: Event "operational" with ID 3 failed (Internal error).                               
Dec 28 23:19:42 abey daemon.err netopeer2-server[869]: Getting data "/*" from sysrepo failed (User callback failed).                         
Dec 28 23:19:42 abey daemon.info netopeer2-server[869]: Failed processing of "rpc" event with ID 4 priority 0 (remaining 1 subscribers).     
Dec 28 23:19:42 abey daemon.err netopeer2-server[869]: Internal error                                                                        
Dec 28 23:19:42 abey daemon.warn netopeer2-server[869]: Event "rpc" with ID 4 priority 0 failed (User callback failed).                      
Dec 28 23:19:42 abey daemon.err netopeer2-server[869]: Failed to send an RPC (User callback failed).                                         
Dec 28 23:19:42 abey daemon.info netopeer2-server[869]: Session 1: thread 2 event new RPC.                                                   
Dec 28 23:19:42 abey daemon.info netopeer2-server[869]: Session 1: thread 2 event reply error.

**Comment by michalvasko** [comment]
Pretty sure this has already been fixed, please update your *sysrepo*, it is quite an old version that you are using.

**Comment by Abrahamma97** [comment]
ok thanks
