### ISSUE TITLE
Running sysrepoctl --install but nothing in log

### ISSUE THREAD

**Issue by mpet** [CESNET/netopeer2#1067]
Hi,

I run the following command:
/usr/bin/sysrepoctl --install /home/netconf/tailf-xsd-types.yang
I start netopeer2 using:
/usr/bin/netopeer2-server -d  -v3

Is there any way to see if install was ok

br,

//mike

**Comment by michalvasko** [comment]
Run `sysrepoctl -l`, it will print all the installed modules.
