### ISSUE TITLE
connecting netopeer2-cli with netopeer2-server is getting failed via TLS 

### ISSUE THREAD

**Issue by bkumarrr** [CESNET/netopeer2#1069]
Hi,
When I am trying to connect via tls below error is coming 

**connect --tls --host 192.168.34.108 --cert /etc/ssl/certs --key /etc/ssh/ssh_host_rsa_key.pub
cmd_connect: Trusted CA directory empty, use "cert add" command to add certificates.
nc ERROR: Loading the client certificate from '/etc/ssl/certs' failed (PEM lib).
cmd_connect: Connecting to the 192.168.34.108:6513 failed.**

Kindly give me suggestion if i am doing something wrong

**Comment by michalvasko** [comment]
You must specify the exact client certificate to use, not just a directory with some certificates. Also, the first message says you have no trusted certificates on the client meaning any certificate presented by the server will be refused.
