### ISSUE TITLE
User callback failed on executing <get> RPC

### ISSUE THREAD

**Issue by aswinSasthri** [CESNET/netopeer2#1070]
Hi @michalvasko , Could you please guide us on this?

Unable to perform "get" RPC using netopeer2-cli options, as it throws back an error like:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/93334131/142626561-b0766049-4ebb-414e-90ed-83c4335b540c.png)

Hoping for guidance on this issue.

**Comment by michalvasko** [comment]
Based on this report I can guess only that your callbacks retrieving state data are taking too long. Try increasing *netopeer2* timeout using the `-t` parameter (see `netopeer2 -h`).

**Comment by aswinSasthri** [comment]
Thanks @michalvasko , this issue has been resolved by trying the command:
netopeer2-cli -t5

Thanks, 
Aswin S
