### ISSUE TITLE
edit-config RPC failure - Netopeer2 (v1.1.77 devel) 

### ISSUE THREAD

**Issue by Selva-Senthilvelan** [CESNET/netopeer2#1071]
I switched recently to the following software versions from the Devel branch(v1) for an ARM platform:
**Netopeer2 v1.1.77   Sysrepo v1.4.146   Libyang 1.0.240   Libnetconf2 1.1.46** 

I am observing that a specific edit-config RPC operation fails sometimes, but works most of the times. I used Netopeer2 v1.1.39 stable version previously and never had issues with this edit-config operation. 

Here are the error logs from netconf client and server side during the failure:

> **netconf-client:**  edit-config RPC failure details:
> 	Tag:      operation-failed
>         Type:     application
>         Severity: error
> 
> **netopeer2-server:**
> user.info : edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
> user.err  : Failed to send an RPC (**User callback failed**).                                            
> user.info : Session 4: thread 0 event new RPC.                                                                             
> user.info : Session 4: thread 0 event reply error.

What causes the **User Callback Failed [SR_ERR_CALLBACK_FAILED]** error for this edit-config RPC and is this a known issue? What is the best way to handle this error?

Thanks for your support!

**Comment by michalvasko** [comment]
Well, there should definitely be another specific error before
```
user.err : Failed to send an RPC (User callback failed).
```
without which it is really impossible to tell what went wrong. Not sure why it is not there, perhaps some application *sysrepo* callback has failed and has not generated a proper error, did you look at the output of the application subscribed to handling the particular configuration changes?
