### ISSUE TITLE
edit-config question

### ISSUE THREAD

**Issue by linbolin** [CESNET/netopeer2#1073]
Edit config, the setting callback function will be called when the setting data is different from the data in the database. I hope to call the setting callback function no matter whether the data is the same or different from the data in the database. How should this be achieved?

**Comment by linbolin** [comment]
Looking forward to your help, thank you very much!

**Comment by jktjkt** [comment]
What would be the point of that? In other words, why do you need this? Are you aware of [`SR_EV_ENABLED`](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__change__subs__api.html#ggad007e862874bda7141c58ca72d8c1067a11b3249384640ee1795f861657a952fb)?

**Comment by linbolin** [comment]
For example, I have three leaves in total. The first two leaves are used as location parameters and the third leaf is used as configuration parameters. When I modify only the third configuration parameter, the first two leaf location parameters cannot be obtained in the callback function, so it cannot be configured downward.

**Comment by linbolin** [comment]
All, I think the corresponding information of the first two leaf positioning parameters can also be obtained in the callback function without changing the first two leaf positioning parameters.

**Comment by linbolin** [comment]
Therefore, I think the corresponding information of the first two leaf positioning parameters can also be obtained in the callback function without changing the first two leaf positioning parameters.

**Comment by michalvasko** [comment]
> When I modify only the third configuration parameter, the first two leaf location parameters cannot be obtained in the callback function, so it cannot be configured downward.

Not true, you can get any data by directly requesting them in the callback using the standard functions, such as `sr_get_data()`.

**Comment by jktjkt** [comment]
In that case I think a reasonable way of designing the callbacks is to have a common subscription for all three leafs. One this CB is hit, you fetch all three values and do your business with them. In that case you probably do not necessary case whether A, B or C has changed -- just that there's been *a* change, and that you have to react to it, somehow.

**Comment by linbolin** [comment]
Thank you for your help. My problem has been solved.
