### ISSUE TITLE
How to save sysrepo startup configuration 

### ISSUE THREAD

**Issue by Abrahamma97** [CESNET/netopeer2#1074]
Hi @michalvasko ,

Can you give me an insight on how we can save the sysrepo running or startup configuration locally to a file in .XML format where netopeer sever and sysrepo permission.

**Comment by jktjkt** [comment]
Have a look at the output of `sysrepocfg --help`.

**Comment by Abrahamma97** [comment]
ok thanks I got the same.
sudo sysrepocfg --export=/home/abey/Documents/Abey.xml -d startup

this I can give by terminal. Hope I should use the same command in sysrepo session connected applications or is there better alternatives as in apis for the same.

**Comment by michalvasko** [comment]
All `sysrepocfg` does is calls some *sysrepo* API functions, so everything it does can be done by any application. In this case you want to call `sr_get_data()` and then you can do what you want with the result including print it into a file by *libyang* API functions.
