### ISSUE TITLE
Some capabilities are missing in hello message(status).

### ISSUE THREAD

**Issue by vaibhav1713109** [CESNET/netopeer2#1075]
Hi @michalvasko 
After connecting with netconf cli i exchange the hello capabilities by using status cmd but below capabilities are missing can you see this and also tell why port is different every time when i perform call home feature.

Following capabilities not present in Hello capabilities exchange message "
Discard change operation
Lock and un-lock operations
Confirmed commit Capability
Cancel commit operation
URL capability

> status
Current NETCONF session:
  ID          : 2
  Host        : ::ffff:192.168.2.91
  Port        : 47628
  Transport   : SSH
  Capabilities:
	urn:ietf:params:netconf:base:1.0
	urn:ietf:params:netconf:base:1.1
	urn:ietf:params:netconf:capability:writable-running:1.0
	urn:ietf:params:netconf:capability:candidate:1.0
	urn:ietf:params:netconf:capability:rollback-on-error:1.0
	urn:ietf:params:netconf:capability:validate:1.1
	urn:ietf:params:netconf:capability:startup:1.0
	urn:ietf:params:netconf:capability:xpath:1.0
	urn:ietf:params:netconf:capability:with-defaults:1.0?basic-mode=explicit&also-supported=report-all,report-all-tagged,trim,explicit
	urn:ietf:params:netconf:capability:notification:1.0
	urn:ietf:params:netconf:capability:interleave:1.0
	urn:ietf:params:xml:ns:yang:ietf-yang-metadata?module=ietf-yang-metadata&revision=2016-08-05
	urn:ietf:params:xml:ns:yang:1?module=yang&revision=2017-02-20
	urn:ietf:params:xml:ns:yang:ietf-inet-types?module=ietf-inet-types&revision=2013-07-15
	urn:ietf:params:xml:ns:yang:ietf-yang-types?module=ietf-yang-types&revision=2013-07-15
	urn:ietf:params:netconf:capability:yang-library:1.1?revision=2019-01-04&content-id=61
	urn:sysrepo:plugind?module=sysrepo-plugind&revision=2020-12-10
	urn:ietf:params:xml:ns:yang:ietf-netconf-acm?module=ietf-netconf-acm&revision=2018-02-14
	urn:ietf:params:xml:ns:netconf:base:1.0?module=ietf-netconf&revision=2013-09-29&features=writable-running,candidate,rollback-on-error,validate,startup,url,xpath
	urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults?module=ietf-netconf-with-defaults&revision=2011-06-01
	urn:ietf:params:xml:ns:yang:ietf-netconf-notifications?module=ietf-netconf-notifications&revision=2012-02-06
	urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring?module=ietf-netconf-monitoring&revision=2010-10-04
	urn:ietf:params:xml:ns:netconf:notification:1.0?module=notifications&revision=2008-07-14
	urn:ietf:params:xml:ns:netmod:notification?module=nc-notifications&revision=2008-07-14
	urn:ietf:params:xml:ns:yang:ietf-x509-cert-to-name?module=ietf-x509-cert-to-name&revision=2014-12-10
	urn:ietf:params:xml:ns:yang:iana-crypt-hash?module=iana-crypt-hash&revision=2014-08-06
	urn:notification_history?module=notification_history
	urn:ietf:params:xml:ns:yang:iana-if-type?module=iana-if-type&revision=2017-01-19

**Comment by michalvasko** [comment]
> why port is different every time when i perform call home feature

The printed port is not the one the client was listening on but rather the one the session is actually established on with the server. That is auto-assigned by the kernel and differs for every connection and every client.

> Following capabilities not present in Hello capabilities exchange message "
Discard change operation

What capability do you have in mind, can you reference some specification?

> Lock and un-lock operations

Same problem, I am not aware of any specific capability for these operations.

> Confirmed commit Capability

Unless you are using a recent version of *netopeer2* v2, this capability is actually not supported.

> Cancel commit operation

Has no specific capability and support for this operation is indicated by the `confirmed-commit` capability.

> URL capability

This is an optional capability that is disabled if you compile *netopeer2* without having the devel package of `libcurl` installed.
