### ISSUE TITLE
Warning is seen :There is no instance of "/avey:system-apps/avey_manager", but it is not.

### ISSUE THREAD

**Issue by Abrahamma97** [CESNET/netopeer2#1076]
Hi @michalvasko 

Nov 24 14:44:59 avey daemon.info netopeer2-server[2051]: Resolving unresolved data nodes and their constraints...
Nov 24 14:44:59 avey daemon.info netopeer2-server[2051]: There is no instance of "/avey:system-apps/avey_manager", but it is not .

I am not understanding why this is coming. Can you please help.

**Comment by michalvasko** [comment]
Ignore it, it is no longer being printed in v2 of *netopeer2*.
