### ISSUE TITLE
Netopeer2-cli gives this error on trying to connect with netopeer2-server-->  Failed to create socket (Address family not supported by protocol).

### ISSUE THREAD

**Issue by bijit999** [CESNET/netopeer2#1077]
Hi , when we do listen from netopeer2-cli  it gives this error::
>
>
> listen
nc ERROR: Failed to create socket (Address family not supported by protocol).
Waiting 60s for an SSH Call Home connection on port 4334...
nc ERROR: nc_accept_callhome: libnetconf2 not initialized.
cmd_listen: Receiving SSH Call Home on port 4334 as user "root" failed.
>
>
>
VERSION: Netopeer2 CLI 2.0.64
Kindly give me suggestion .

**Comment by michalvasko** [comment]
My guess is that your system does not support IPv6 and the default host to listen on is `::0`. If you just run
```
listen --host 0.0.0.0
```
it should work.

**Comment by bijit999** [comment]
> My guess is that your system does not support IPv6 and the default host to listen on is `::0`. If you just run
> 
> ```
> listen --host 0.0.0.0
> ```
> 
> it should work.

Thank you , it worked.
