### ISSUE TITLE
Use of ly_verb_dbg and LY_LOG_DBG_GROUP without conditioning on NDEBUG

### ISSUE THREAD

**Issue by fabioantonini** [CESNET/Netopeer2#108]
Hi
in the main.c of netopeer2-server the LY_LOG_DBG_GROUP flags are used without any conditioning on NDEBUG.
in libyang.h file the functions ly_verb_dbg and the enum type LY_LOG_DBG_GROUP are defined only if the symbol NDEBUG is not declared 

#ifndef NDEBUG

/**
 * @typedef LY_LOG_DBG_GROUP
 * @brief Selected displayed debug message groups.
 */
typedef enum {
    LY_LDGDICT = 0x01,  /**< Dictionary additions and deletions. */
    LY_LDGYANG = 0x02,  /**< YANG parser messages. */
    LY_LDGYIN = 0x04,   /**< YIN parser messages. */
    LY_LDGXPATH = 0x08, /**< XPath parsing end evaluation. */
    LY_LDGDIFF = 0x10   /**< Diff processing and creation. */
} LY_LOG_DBG_GROUP;
/**
 * @brief Enable specific debugging messages (independent of log level).
 * @param[in] dbg_groups Bitfield of #LY_LOG_DBG_GROUP - enabled debug message groups.
 */
void ly_verb_dbg(int dbg_groups);
#endif

**Comment by michalvasko** [comment]
Hi,
should be fine now.

Regards,
Michal

**Comment by fabioantonini** [comment]
Hi Michal

thanks a lot for your support?

I have noticed that you fixed the problem in the 'notifications' branch. 
I'm using the 'devel' branch.

Do you advise to use the 'notifications' branch instead of the 'devel' 
or has I to port the fix on the devel by myself?

regards

fabio

**Comment by michalvasko** [comment]
Hi,
of course, sorry, my bad.

Michal

**Comment by fabioantonini** [comment]
Thanks

fabio
