### ISSUE TITLE
Use `command -v` instead of `which`

### ISSUE THREAD

**Issue by oerdnj** [CESNET/netopeer2#1082]
The verbose build in the Debian sid chroot complains loudly about:
```
14: /usr/bin/which: this version of `which' is deprecated; use `command -v' in scripts instead.
```

I think this is reasonable suggestion.

**Comment by michalvasko** [comment]
Seems fine to me except I had to check portability of `command(1)` but it seems to have been specified in POSIX.1‐2001 so no problems.
