### ISSUE TITLE
edit-config problem

### ISSUE THREAD

**Issue by linbolin** [CESNET/netopeer2#1084]
Hello, I need to realize the device reset function. After I reset the device successfully, I reset the device again. It is detected that the data has no change and will not enter the callback function. How can I realize this to enter the callback function again?

**Comment by michalvasko** [comment]
You have skipped lots of important details without which I can only guess what you mean so try to look at the [`ENABLE`](https://github.com/sysrepo/sysrepo/blob/master/src/sysrepo_types.h#L393) *sysrepo* subscribe flag.
