### ISSUE TITLE
Get filter does not give access denied even after denying in nacm.

### ISSUE THREAD

**Issue by Abrahamma97** [CESNET/netopeer2#1086]
Hi @michalvasko ,
I do not get access denied in  when requesting even after denying the same in nacm. 
> get --filter-xpath /o-ran-sync:*
DATA

Normally when allowing o-ran-sync with read permission I will get data. When denying, data is not got and will get  a blank instead of Access denied.
Is this expected?

**Comment by michalvasko** [comment]
[Yes](https://datatracker.ietf.org/doc/html/rfc8341#section-3.2.4).

**Comment by Abrahamma97** [comment]
The NETCONF server replies rejecting the protocol operation with an "access-denied" error.

31 <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-iid="11">
33 <rpc-error>
34 <error-type>protocol</error-type>
35 <error-tag>access-denied</error-tag>
36 <error-severity>error</error-severity>
37 </rpc-error>
38 </rpc-reply>

But this is not seen @michalvasko .
Should I give rwx permission to any yang with nacm to get this rpc reply?

**Comment by Abrahamma97** [comment]
Thanks resolved
