### ISSUE TITLE
Netopeer-Server daemon execution

### ISSUE THREAD

**Issue by v19981999** [CESNET/netopeer2#1089]
I've installed Netopeer2 successfully and am able to use the CLI as required as well.
But when I try to run netopeer2-server -d, It gives the following error :

[ERR] : NP: Subscribing for providing "ietf-netconf-monitoring" state data failed (Invalid argument).
[ERR] : NP: Server data subscribe failed.

How to resolve this issue ? I'm new to Netconf and Netopeer, please help guide me through this.
I'm trying to connect 2 Ubuntu VMs using Netopeer2 and get the data from one to another. Is there any tutorial/example for this ?

Thank you

**Comment by michalvasko** [comment]
Where did you get *netopeer2*, what version is it?

**Comment by V-1998** [comment]
I got it directly from the Ubuntu packages by using the command : sudo apt-get install netopeer2
The version of Netopeer2 is 1.1.39

**Comment by michalvasko** [comment]
I see. You should definitely not get this error but I would still strongly advise to use a newer version, that one is more than a year old. Best would be to remove all those packages and use the latest [release](https://github.com/CESNET/netopeer2/releases/tag/v2.0.35) instead. There are even packages provided for Ubuntu 20.

**Comment by V-1998** [comment]
Will try out the newer version.
Do you know how I could install it directly using the command line ?
I'm using an Ubuntu VM

**Comment by michalvasko** [comment]
Not sure what you mean by "directly using the command line". You cannot install newer versions using `apt` because they are not yet in a repository but you can install downloaded packages or clone and compile the git repository yourself using the command line (terminal) just like everything else.

**Comment by V-1998** [comment]
Is there any other source besides GitHub I can clone it from ?

**Comment by michalvasko** [comment]
You are asking strange questions so I have difficulty answering them. By clone I mean `git clone` and there is no reason for a project to have more repositories. So no, you cannot clone it from anywhere else.

**Comment by V-1998** [comment]
Thanks for the clarification. 
My setup isn't a standard setup and it's tough to explain it.
Thank you again for the responses, its appreciated :)

**Comment by V-1998** [comment]
After git cloning using:
git clone https://github.com/CESNET/netopeer2.git
cd netopeer2
mkdir build && cd build && cmake .. && make && make install

The cmake command isn't running. Is there any other way to setup Netopeer2 after cloning ?
