### ISSUE TITLE
X509 certificate support for ssh

### ISSUE THREAD

**Issue by Ritesh545** [CESNET/netopeer2#1090]
Hi Michal ,
we are planning to support client and server authentication based on ssh using X.509 certificates as per ORAN specification WG4-MP-V5.
We can see that Netopeer2 support authentication on TLS using the X509 certificate. Does netopeer2 support authentication based on ssh using X.509 certificates?

**Comment by michalvasko** [comment]
No, it currently does not support this kind of authentication.
