### ISSUE TITLE
Connecting Netopeer2 server with Any other Netconf Client

### ISSUE THREAD

**Issue by aswinSasthri** [CESNET/netopeer2#1091]
Hi @michalvasko , 

Can all the functionalities of Netconf protocol be realised, by connecting netopeer2-server with any other client other than Netopeer2-cli ?
If yes, what are the other supported Netconf Clients, which can communicate with the netopeer2-server ?

**Comment by michalvasko** [comment]
Yes, *netopeer2* v2 (version 1 was sometimes sending incorrect messages) should be fully compatible with any NETCONF 1.0 and/or NETCONF 1.1 client. I cannot recommend you any because I am using only *netopeer2-cli*.

**Comment by jktjkt** [comment]
Ypu might give [`netconf-cli`](https://github.com/CESNET/netconf-cli) a try. It's an interactive CLI which fetches all the YANG models and builds a nice shell that you can navigate around.
