### ISSUE TITLE
connection error between netopeer2-cli and netopeer2-server 

### ISSUE THREAD

**Issue by bkumarrr** [CESNET/netopeer2#1096]
Hi All
I am facing one issue while connecting netopeer2-cli with netopeer2-server 
below is error 
> connect --host 192.168.23.30 --login root
nc ERROR: Unable to connect to 192.168.23.30 (Connection refused).
nc ERROR: SSH channel poll error ().
cmd_connect: Connecting to the 192.168.23.30:830 as user "root" failed.

NOTE: 1.) netopeer2-server is running
           2.) able to ping from both the sides

**Comment by michalvasko** [comment]
It may be a firewall problem, NETCONF SSH uses port 830, which need to be allowed.
