### ISSUE TITLE
netconf rpc reply error

### ISSUE THREAD

**Issue by masif-cs** [CESNET/netopeer2#1100]
Hi,

I see that sometime my netconf edit-config rpc fails with below error:
Type:     application
Tag:      operation-failed
Severity: error

Even though the XML input to RPC remains same. Could you please help me understanding when this error will come?

**Comment by michalvasko** [comment]
What *netopeer2* version are you using? What is the error message? There must be some.

**Comment by masif-cs** [comment]
I am using netopeer2 version 2.0.25. I was not able to collect logs on server side when this issue happened. This issue is happening intermittently.

**Comment by michalvasko** [comment]
I cannot help you without the error message, the error information you posted is as a generic error as they come.

**Comment by masif-cs** [comment]
Hi @michalvasko ,

I got below logs at client:
Tag: operation-failed Type: application Severity: error Message: Callback event "rpc" with ID 2 processing timed out."

And below logs at server:
Failed to send an RPC (User callback failed).
Session 1: thread 0 event new RPC
Session 1: thread 0 event reply error

Could you please help now.

**Comment by michalvasko** [comment]
That seems like a standard timeout, try running *netopeer2* with parameter `-t 10`, for example (look at help `netopeer2-server -h` for details).

**Comment by masif-cs** [comment]
Hi @michalvasko ,

I am getting error like these. I am not sure why I will get this error and this is happening intermittently. Same configuration is successful once and fails next time.

Tag: operation-failed Type: application Severity: error Path: /o-ran-uplane-conf:user-plane-configuration Message: Unknown element "X0005B9_prach-config"
Tag: operation-failed Type: application Severity: error Path: /o-ran-operations:operational-info Message: Unknown element "o-ran-operations"
Tag: operation-failed Type: application Severity: error Path: / Message: Unknown element "o-ran-processing-element"
