### ISSUE TITLE
Netconf Access Control Management is not filtering "get-schema" requests

### ISSUE THREAD

**Issue by lucianocuchi** [CESNET/netopeer2#1103]
Hi,

My objective is to deny  to a group of user to be able to download the schemas os some models of the sysrepo database.

I have started with the most basic configuration in ietf-netconf-nacm which is a deny-all:

```
<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
  <enable-nacm>true</enable-nacm>
  <read-default>deny</read-default>
  <write-default>deny</write-default>
  <exec-default>deny</exec-default>
  <enable-external-groups>true</enable-external-groups>
</nacm>
```

But I have found that, although there is a deny-all policy, any logged user is able to download any schema from the database (if you already now the model name, because the access to the ietf-yang-library and ietf-netconf-monitoring is correctly denied)
```
> get --filter-xpath /ietf-yang-library:*
DATA
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"/>

> get-schema --model ietf-yang-library
MODULE
module ietf-yang-library {
  yang-version 1.1;
  namespace "urn:ietf:params:xml:ns:yang:ietf-yang-library";
  prefix yanglib;
[ TRUNCATED OUPUT ]
```

The OS I'm running the tests is Ubuntu 18.04.6 LTS and the versions that I'm using are:

```
root@ab262005e309:/# sysrepoctl -V
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.0.53 (SO v6.4.19)

root@ab262005e309:/# netopeer2-server -V    
netopeer2-server 2.0.35
```

I think there is a bug with this, right? or is it the expected behaviour? 

Thank you very much for your support,

Luciano

**Comment by michalvasko** [comment]
Right, `get-schema` was handled internally by *libnetconf2* so NACM was not applied at all. Fixed.

**Comment by lucianocuchi** [comment]
Great! Thank you very much!
