### ISSUE TITLE
get-data --datastore operational with a subtree filter does not appear to be returning the correct data

### ISSUE THREAD

**Issue by bbergquist0930** [CESNET/netopeer2#1104]
Using the model for `issue1`, I made the configuration nodes be "in use" and also setup an operational callback for the "serial-num".  
```
> get-data --datastore operational --filter-xpath /issue1:*
DATA
<data xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-nmda">
  <hardware xmlns="i1">
    <component>
      <name>ComponentName</name>
      <class>O-RAN-RADIO</class>
      <serial-num>1234</serial-num>
      <feature>
        <wireless>true</wireless>
      </feature>
    </component>
  </hardware>
</data>
```
Now I try using the same subtree filter as in the `test_get_operational_data`.   The filter looks like
```
brett@brett-Precision-7740:~/git/netconf/sysrepo/build$ cat /home/brett/git/netconf/filter.xml 
<hardware xmlns="i1">
    <component>
      <name>ComponentName</name>
      <class>O-RAN-RADIO</class>
      <serial-num>1234</serial-num>
      <feature>
        <wireless>true</wireless>
      </feature>
    </component>
  </hardware>
brett@brett-Precision-7740:~/git/netconf/sysrepo/build$ 
```

I now try using that filter 
```

> get-data --datastore operational --filter-subtree=/home/brett/git/netconf/filter.xml
DATA
<data xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-nmda"/>

> 
```
This does not return anything.

Using `get` with the same filter does return correctly
```
> get  --filter-subtree=/home/brett/git/netconf/filter.xml
DATA
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <hardware xmlns="i1">
    <component>
      <name>ComponentName</name>
      <class>O-RAN-RADIO</class>
      <serial-num>1234</serial-num>
      <feature>
        <wireless>true</wireless>
      </feature>
    </component>
  </hardware>
</data>
```
However using `get` is not performant when there are callbacks to be invoked and the advise is to use `get-data` as the replacement.

**Comment by bbergquist0930** [comment]
This filter works 
```
<hardware xmlns="i1">
    <component>
      <name>ComponentName</name>
      <class></class>
      <serial-num></serial-num>
      <feature>
              <wireless></wireless>
      </feature>
    </component>
  </hardware>
```
and return 
```
> get-data --datastore operational  --filter-subtree=/home/brett/git/netconf/filter.xml
DATA
<data xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-nmda">
  <hardware xmlns="i1">
    <component>
      <name>ComponentName</name>
      <class>O-RAN-RADIO</class>
      <serial-num>1234</serial-num>
      <feature>
        <wireless>true</wireless>
      </feature>
    </component>
  </hardware>
</data>

> 
```

As soon as you add a value to be filtered on like 
```
<hardware xmlns="i1">
    <component>
      <name>ComponentName</name>
      <class></class>
      <serial-num></serial-num>
      <feature>
              <wireless>true</wireless>
      </feature>
    </component>
  </hardware>
```
Then the `class` and `serial-num` are no longer returned in the output
```
DATA
<data xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-nmda">
  <hardware xmlns="i1">
    <component>
      <name>ComponentName</name>
      <feature>
        <wireless>true</wireless>
      </feature>
    </component>
  </hardware>
</data>

> 
```

**Comment by bbergquist0930** [comment]
Strangely this filter works
```
<hardware xmlns="i1">
    <component>
      <name>ComponentName</name>
      <class>O-RAN-RADIO</class>
      <serial-num></serial-num>
      <feature>
              <wireless></wireless>
      </feature>
    </component>
  </hardware>
```
> get-data --datastore operational  --filter-subtree=/home/brett/git/netconf/filter.xml
DATA
<data xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-nmda">
  <hardware xmlns="i1">
    <component>
      <name>ComponentName</name>
      <class>O-RAN-RADIO</class>
      <serial-num>1234</serial-num>
      <feature>
        <wireless>true</wireless>
      </feature>
    </component>
  </hardware>
</data>

> 
```

**Comment by michalvasko** [comment]
Can you please attach the YANG module(s)? No idea what `issue1` is. Also, what versions are you using, of *netopeer2* at least?

**Comment by bbergquist0930** [comment]
libyang v2.0.112
sysrepo v2.0.53
Netopeer2 v2.0.35

The `issue1.yang` is part of the Netopeer2 tests

https://github.com/CESNET/netopeer2/blob/master/tests/modules/issue1.yang

The test is basically this one

https://github.com/CESNET/netopeer2/blob/e6cdbb912cb82b81d7698a3f3d6c15a17f805cc4/tests/test_filter.c#L825

but trying to use `get-data` instead of `get`.   There seem to be no tests for `get-data`.   

I will see if I can write a test case using `get-data` and this module that is equivalent to `test_get_operational_data` test.

**Comment by bbergquist0930** [comment]
I added this pull request with a new test.  The test fails because I think the filtering is not working correctly at this point.

https://github.com/CESNET/netopeer2/pull/1105

**Comment by michalvasko** [comment]
Okay, thanks for the test (they are obviously needed for `get-data`) and it should work now.
