### ISSUE TITLE
Q: Linux PAM

### ISSUE THREAD

**Issue by iljatab** [CESNET/netopeer2#1107]
Hi Michal,

From a ticket from October 2020 "Query about custom PAM based authentication #739" I found that to support Linux PAM we have to implement our own module and link it to netopeer2-server.

Did anything change during last year?
DineshReddyK, the author of original ticket, was going to contribute such support, did it happen?

BRGDS,
Ilja.

**Comment by michalvasko** [comment]
No, no contribution was made and PAM is still not supported, unfortunately.

**Comment by iljatab** [comment]
Thanks for clarification!
