### ISSUE TITLE
How to transplant netopeer2 to ARM?I have finished the cross complie of netopeer2.

### ISSUE THREAD

**Issue by NTUGY** [CESNET/netopeer2#1108]
I am a novice.Can you show the detailed steps?For example, how to package the directory structure。Thank you so much.

**Comment by jktjkt** [comment]
Use a tool such as [buildroot](https://buildroot.org/), or [Yocto](https://www.yoctoproject.org/). Don't try to reinvent the wheel.

**Comment by NTUGY** [comment]
> Use a tool such as [buildroot](https://buildroot.org/), or [Yocto](https://www.yoctoproject.org/). Don't try to reinvent the wheel. Also, please do not ask for detailed steps in unrelated issue reports.

Hi,jktjkt
Thank you for your help.Thank you so much.
