### ISSUE TITLE
function not compatible for sysrepo version.

### ISSUE THREAD

**Issue by Shubham-dash** [CESNET/netopeer2#1109]
Hi @michalvasko 
I am working on an application that contains this function `sr_session_get_event_nc_id ()` but the issue is this function is not compatible with the sysrepo version I am having can any other function we can use in place of this.

my current sysrepo version: v2.0.54 (SO v6.4.20)

**Comment by michalvasko** [comment]
Look into *netopeer2* [README](https://github.com/CESNET/netopeer2/#sysrepo-callbacks). Then, the function you want to use is `sr_session_get_orig_data()`.
