### ISSUE TITLE
Error tag are not reflecting according to RFC6241.

### ISSUE THREAD

**Issue by vaibhav1713109** [CESNET/netopeer2#1111]
Hi 
@michalvasko  i am pushing the xml with vlan out of range it didn't show expected output, i see this issue in lots of error tags.

Reflecting:
ERROR
type:     application
tag:      operation-failed
severity: error
path:     /ietf-interfaces:interfaces/interface/o-ran-interfaces:vlan-id
message:  Value "12000" does not satisfy the constraint "1..4094" (range, length, or pattern).

Expected:
"The request or response (that would be generated) is too large for the implementation to handle.

error-tag:      too-big
error-type:     transport, rpc, protocol, application
error-severity: error
error-info:     none

**Comment by jktjkt** [comment]
The error tag `too-big` is documented to mean "*The request or response (that would be generated) is too large for the implementation to handle*". That does not sound like something to use when a custom YANG model rejects a leaf value.

Realistically speaking, this error message is as good as it goes: you have an XPath that you can point back to whoever triggered this request. There are more complex models out there where error conditions are much, much more complex.

**Comment by vaibhav1713109** [comment]
Hi @jktjkt 
How we configure a large request.

**Comment by jktjkt** [comment]
It is not clear to me what error you're seeing, or what error you're trying to prevent.

**Comment by vaibhav1713109** [comment]
Means how i am able to get too-big error.


this i want

>>>
error-tag:      too-big
   error-type:     transport, rpc, protocol, application
   error-severity: error
   error-info:     none
   Description:    The request or response (that would be generated) is
                   too large for the implementation to handle.

**Comment by michalvasko** [comment]
You can generate any custom error in the *sysrepo* callback ([README](https://github.com/CESNET/netopeer2/tree/devel#sysrepo-callbacks)). However, you can do so only after the data pass YANG validation. A value not matching some restriction is not `too-big` error, which means that the reaction to a configuration change is causing something "too big", not that the configuration value itself is too big.
