### ISSUE TITLE
RPC Failure Error 

### ISSUE THREAD

**Issue by vpai-cs** [CESNET/netopeer2#1112]
Hi,

I'm observing edit-config RPC failure due to timeout. This issue is observed occasionally. Below are the logs observed at the netopeer client and server respectively:

Logs at Netopeer client:
Tag: operation-failed Type: application Severity: error Message: Callback event "rpc" with ID 2 processing timed out."

Logs at Netopeer server:
[ERR] Callback event "rpc" with ID 2 processing timed out.
Callback event "rpc" with ID 2 processing timed out.
[WRN] Event "rpc" with ID 2 priority 0 failed (Timeout expired).
Event "rpc" with ID 2 priority 0 failed (Timeout expired).
Failed to send an RPC (User callback failed).
Session 1: thread 0 event new RPC.
Session 1: thread 0 event reply error.

The following software versions from the Devel branch(v1) is used:
Netopeer2 v1.1.77   Sysrepo v1.4.146   Libyang 1.0.240   Libnetconf2 1.1.46

Could you please guide me in handling the issue?

**Comment by jktjkt** [comment]
What data are you editing, and which code handles the edits in question? How much time does it take for that code to return `SR_ERR_OK`?

**Comment by michalvasko** [comment]
What @jktjkt is asking about is probably the problem (your callbacks taking too long). Try running `netopeer2-server` with additional parameter `-t 10`, for example.
