### ISSUE TITLE
Delete the running configuration of a particular yang or xpath.

### ISSUE THREAD

**Issue by Abrahamma97** [CESNET/netopeer2#1115]
Hi @michalvasko 
When giving --help I am able to see only startup and no xpath scpecification in help syntax. 
`> delete-config --help
delete-config [--help] --target startup [--rpc-timeout <seconds>]`

Can you please elaborate if we are able to delete the running configuration of a particular yang or xpath.

**Comment by komik0** [comment]
You can just use edit-config with operation="delete"
[This](https://github.com/CESNET/Netopeer2/issues/15#issuecomment-240291086) apply also to your problem, not only to lists
