### ISSUE TITLE
How to get notification for current connected user and whenever connected user switched to another user.

### ISSUE THREAD

**Issue by ekuekta** [CESNET/netopeer2#1117]
I am trying to get user access notification through fualt manager application. I dont know how to get notification for current connected user and whenever connected user switched to another user from fault manager application. Please help me with this issue.

**Comment by michalvasko** [comment]
Try subscribing to [this](https://github.com/sysrepo/sysrepo/blob/master/modules/ietf-netconf-notifications.yang#L170) notification. There is no other that would fit your description.
