### ISSUE TITLE
confirmed commit is failing because of a hardcoded module name in netconf_confirmed_commit.c

### ISSUE THREAD

**Issue by bbergquist0930** [CESNET/netopeer2#1118]
Line 678 looks like 
```
 if ((rc = sr_check_module_ds_access(conn, "edit1", SR_DS_RUNNING, &read, &write))) {
```

**Comment by bbergquist0930** [comment]
Here is a pull request for this issue
https://github.com/CESNET/netopeer2/pull/1119

Interesting that all of the unit tests pass but that must be because the "edit1" module is loaded while the test is running.

**Comment by michalvasko** [comment]
Of course, thanks for the fix.
