### ISSUE TITLE
netopper2 build error

### ISSUE THREAD

**Issue by linbolin** [CESNET/netopeer2#1122]
mesg: ttyname failed: Inappropriate ioctl for device
[ERR] Shared memory version mismatch (6, expected 8), remove the SHM to fix.
sysrepoctl error: Failed to connect (Operation not supported)
For more details you may try to increase the verbosity up to "-v3".
[ERR] Shared memory version mismatch (6, expected 8), remove the SHM to fix.
sysrepoctl error: Failed to connect (Operation not supported)
For more details you may try to increase the verbosity up to "-v3".
CMake Error at cmake_install.cmake:85 (message):
   scripts/setup.sh failed: 1

**Comment by linbolin** [comment]
Hello！
Today, after I updated libyng, libnetconf 2, sysrepo and netopeer2 codes, the above error message appeared in the compilation. Is this the reason for the version mismatch?

**Comment by michalvasko** [comment]
You still have some data from an older *sysrepo* version. Run `make sr_clean` to delete it all and fix this error.

**Comment by linbolin** [comment]
Thank you.
