### ISSUE TITLE
Netopeer2 make install error

### ISSUE THREAD

**Issue by v19981999** [CESNET/netopeer2#1124]
Hello,

I followed the instructions of installing all libraries : libnetconf2, libssh, libyang, sysrepo, uncrustify and netopeer2

All the other libraries installation went without error.

Getting this error while trying to use "make install" for netopeer2 

-- Up-to-date: /usr/local/bin/netopeer2-server
-- Up-to-date: /usr/local/share/man/man8/netopeer2-server.8
-- Installing missing sysrepo modules...
[ERR] Shared memory version mismatch (2, expected 8), remove the SHM to fix.
Sysrepoct1 error: Failed to connect (Operation not supported)
For more details you may try to increase the verbosity up to "-v3".
[ERR] Shared memory version mismatch (2, expected 8), remove the SHM to fix.
Sysrepoctl error: Failed to connect (Operation not supported)
For more details you may try to increase the verbosity up to "-v3".
CMake Error at cmake_install.cmake: 90 (message):
       scripts/setup.sh failed: 1

I tried rebooting the system as well, to clean shm. It continues to give the same error.
Please help resolve the issue.

**Comment by michalvasko** [comment]
Having the same error after reboot is definitely strange as the main SHM should be deleted. But you can always make a full cleanup yourself, run `make sr_clean`, which should fix this.
