### ISSUE TITLE
NACM Recovery Session - Question

### ISSUE THREAD

**Issue by pramodpillaip** [CESNET/netopeer2#1125]
Hi , 
As per my understanding the recovery session user's UID is set during build time by setting the value of cmake variable NACM_RECOVERY_UID to desired value ( say 1324)
And on the netopeer2 server , we need to have a linux user with the same user id ( 1324). When the user with UID 1324 connects to the Netopeer server the session is identified as recovery session.

The question is 
- how do I verify that the  recovery session behavior is working. Is there any log that I can looking at which says "Recovery session is active"
Or any other simple testcase I can use to verify .

Regards
Pramod

**Comment by michalvasko** [comment]
Your understanding is correct but there is no simple way to verify that you have a recovery session. What I can think of is to log with any other user and once you get access denied error, try to perform the same operation with the recovery session. But that depends on your NACM configuration, by default you are not permitted to write any data, for example.

**Comment by pramodpillaip** [comment]
Thanks for your feedback. Let me try to figure out a testing method , the way you suggested.
