### ISSUE TITLE
filter type:"subtree" error

### ISSUE THREAD

**Issue by linbolin** [CESNET/netopeer2#1126]
When the filter type is subtree, query XML as follows:

```xml
<get>
  <filter type:"subtree">
    <components xmlns="http://openconfig.net/yang/brilliance-equipment"/>
  </filter>
</get>
```

The following error code is returned:
```xml
<?xml version="1.0" encoding="utf-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="23">
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message xml:lang="en">Identifier ""subtree"&gt;
    &lt;components xmlns="http://openconfig.net/yang/brilliance-equipment"/&gt;
  &lt;/filter&gt;
&lt;/get&gt;&lt;/rpc&gt;" starts with an invalid character.</error-message>
  </rpc-error>
</rpc-reply>
```

**Comment by linbolin** [comment]
<get-config>
  <source>
    <running/>
  </source>
  <filter type:"subtree">
    <components xmlns="http://openconfig.net/yang/brilliance-equipment"/>
  </filter>
</get-config>

**Comment by linbolin** [comment]
How should this problem be handled?

**Comment by michalvasko** [comment]
[This](https://datatracker.ietf.org/doc/html/rfc6241#section-6.4) is the specification of subtree filter, what you wrote is not even a valid XML. Use `<filter type="subtree">` instead.
