### ISSUE TITLE
Netopeer2-server exits upon deletion of /ietf-netconf-server:netconf-server container

### ISSUE THREAD

**Issue by senrajib** [CESNET/Netopeer2#113]
Hi Michal

We found Netopeer exiting when we delete netconf-server container like below

sr_delete_item(session, "/ietf-netconf-server:netconf-server", SR_EDIT_DEFAULT)

Is this a expected behavior that at least one of 1. listening endpoint and 2. a callhome client must be configured for Netopeer2 to be running?

-Rajib

**Comment by michalvasko** [comment]
Hi Rajib,
I believe the server was crashing on a failed assert in this case. It should work properly now, you will also need to update *libnetconf2*.

Regards,
Michal

**Comment by senrajib** [comment]
Hi Michal
Even after cleaning callhome container like below from ietf-netconf-server.running DS , we are observing
callhome TCP connection stays in ESTABLISHED state. Is it the right behavior? We were expecting callhome TCP connections to go away as soon as we delete callhome config.

sr_delete_item(session, "/ietf-netconf-server:netconf-server/call-home", SR_EDIT_DEFAULT)

[root@MaestrOS ~]# netstat -an | grep 60830
tcp        0      0 10.1.18.83:49968        10.1.23.100:60830       ESTABLISHED
[root@MaestrOS ~]# netstat -an | grep 60830
tcp        0      0 10.1.18.83:49968        10.1.23.100:60830       ESTABLISHED
[root@MaestrOS ~]# netstat -an | grep 60830
tcp        0      0 10.1.18.83:49968        10.1.23.100:60830       ESTABLISHED
[root@MaestrOS ~]# cat /etc/sysrepo/data/ietf-netconf-server.running
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <listen>
    <endpoint>
      <name>test_ssh_listen_endpt</name>
      <ssh>
        <address>0.0.0.0</address>
        <port>830</port>
        <host-keys>
          <host-key>
            <name>test_ssh_listen_key</name>
            <public-key>ssh_host_rsa_key</public-key>
          </host-key>
        </host-keys>
      </ssh>
    </endpoint>
  </listen>
</netconf-server>

**Comment by michalvasko** [comment]
Hi Rajib,
it was intended for established sessions to not be terminated after the Call Home client is deleted. This is an implementation dependent decision and this is how we decided, do you have a problem with it or it's just unexpected?

Regards,
Michal

**Comment by senrajib** [comment]
Hi Michal
Thanks for clarifying the behavior !
We were under the impression that deletion of callhome configuration should make Netopper2 drop established TCP connection. Lets say , due to some network issue connection is disturbed very frequently  and each time a new TCP socket is created resulting to many stale socket entry in the system, occupying system resources.

Any clue why disconneted socket entry was decided to preserve?
-Rajib

**Comment by michalvasko** [comment]
Hi Rajib,
be careful, I am talking about NETCONF sessions remaining established (which of course require an underlying TCP/IP connection), if a TCP/IP connection remains after the NETCONF session is terminated, it may be a problem. In what state are the sockets left?

Regards,
Michal

**Comment by senrajib** [comment]
Hi Michal

Ok . We now understand that a callhome TCP connection won't be dropped by Netopeer2-Server till Netconf session remains established on that TCP connection even if callhome configuration is deleted from ietf-netconf-server.running DS.

In this case , the client didn't terminate ssh or NETCONF session. We expected server to drop the callhome TCP connection by exclusively deleting callhome configuration.

-Rajib

**Comment by michalvasko** [comment]
Okay, in that case it seems to me everything is now as expected.

Regards,
Michal
