### ISSUE TITLE
How we can trigger APPLICATION and TIMEOUT error in software download event

### ISSUE THREAD

**Issue by PriyaSharma30** [CESNET/netopeer2#1132]
When the O-RU completes the software download or software download fails, the O-RU shall send NETCONF
download-event notification with one of the following statuses:
 a) COMPLETED
 b) AUTHENTICATION_ERROR - source available, wrong credentials
 c) PROTOCOL_ERROR – sFTP protocol error
 d) FILE_NOT_FOUND - source not available
 e) APPLICATION_ERROR - operation failed due to internal reason
  f) TIMEOUT - source available, credentials OK, Operation timed out (e.g. source becomes unavailable during ongoing operation).

TIMEOUT -> how we can trigger the scenario with sfp 25G?
APPLICATION_ERROR -> How we can trigger this scenario?

**Comment by michalvasko** [comment]
For such a general question I can give only a general answer. Create the notification and use [sr_event_notif_send](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__notif__subs__api.html#ga7f6f8be6ee0fdc7159307806109765e6) or [sr_event_notif_send_tree](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__notif__subs__api.html#ga80933c95964ab86301268213eea868eb) to send it. Any NETCONF sessions subscribed to this notification will then receive it.
