### ISSUE TITLE
cli: `user-rpc` is silently modified

### ISSUE THREAD

**Issue by jktjkt** [CESNET/netopeer2#1135]
I'm playing with NETCONF notifications, and I'm trying to send this [example from an RFC](https://datatracker.ietf.org/doc/html/rfc5277#page-13) (I stripped the `<rpc>` envelope because `netopeer2-cli` adds it automatically):

```xml
<get xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<filter type="subtree">
<netconf xmlns="urn:ietf:params:xml:ns:netmod:notification">
   <streams/>
 </netconf>
</filter>
</get>
```
...but when I use that as a content of an RPC, this is what the client actually sends (I'm using `verb 3` here):
```xml
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="34">
<get xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<filter type="subtree"></filter>
</get>
</rpc>
```
Why is the inner element, the`<netconf xmlns="urn:ietf:params:xml:ns:netmod:notification">`, being silently removed?

**Comment by michalvasko** [comment]
This was quite a specific bug, should work properly with latest *libnetconf2*.

**Comment by jktjkt** [comment]
thanks
