### ISSUE TITLE
deb package install failed on 2.0.35.2

### ISSUE THREAD

**Issue by liangliu-lab** [CESNET/netopeer2#1137]
The installation is on Ubuntu20.04, below depencies installed
libsysrepo6_2.0.53.1-1_amd64.deb, libyang2_2.0.112.1-1_amd64.deb, libnetconf2-2_2.0.24.1-1_amd64.deb

Did anyone met the same below?  Thanks.

the failed spot here:
/var/lib/dpkg/info/netopeer2.postrm: line 79: -l: command not found
groupdel: group 'netconf' does not exist

Here is the whole installing log:
xxxxxx@yyyy:~/Downloads$ sudo dpkg -i netopeer2_2.0.35.2-1_amd64.deb 
Selecting previously unselected package netopeer2.
(Reading database ... 209829 files and directories currently installed.)
Preparing to unpack netopeer2_2.0.35.2-1_amd64.deb ...
Unpacking netopeer2 (2.0.35.2.gcb2503f-1) over (2.0.35.2.gcb2503f-1) ...
/var/lib/dpkg/info/netopeer2.postrm: line 79: -l: command not found
groupdel: group 'netconf' does not exist
dpkg: warning: old netopeer2 package post-removal script subprocess returned error exit status 6
dpkg: trying script from the new package instead ...
/var/lib/dpkg/tmp.ci/postrm: line 79: -l: command not found
groupdel: group 'netconf' does not exist
dpkg: error processing archive netopeer2_2.0.35.2-1_amd64.deb (--install):
 new netopeer2 package post-removal script subprocess returned error exit status 6
/var/lib/dpkg/tmp.ci/postrm: line 79: -l: command not found
groupdel: group 'netconf' does not exist
dpkg: error while cleaning up:
 new netopeer2 package post-removal script subprocess returned error exit status 6
Processing triggers for man-db (2.9.1-1) ...
Errors were encountered while processing:
 netopeer2_2.0.35.2-1_amd64.deb

**Comment by michalvasko** [comment]
Only the `postrm` script failed and you do not have to worry much about that. I have fixed
```
groupdel: group 'netconf' does not exist
```
error but this
```
/var/lib/dpkg/tmp.ci/postrm: line 79: -l: command not found
```
seems like `sysrepoctl` was not found on your system, which is a major problem and I have no idea how that could happen under normal circumstances. Unless you forcibly removed the `sysrepo` package.
