### ISSUE TITLE
Crash in netopeer2-server in sr_rwunlock

### ISSUE THREAD

**Issue by meghna-doshi** [CESNET/netopeer2#1138]
Hi,
We are observing following assertion in netopeer2-server code.
Mostly this happened on a "get" call from the client. Can you please help us find fix for this.

"netopeer2-server|INFO ""LY"" All data nodes and constraints resolved.
"netopeer2-server|INFO ""LY"" Resolving unresolved data nodes and their constraints...
"netopeer2-server|INFO ""LY"" All data nodes and constraints resolved.",debug,"svt-setup"
"netopeer2-server|INFO ""SR"" Published event ""rpc"" ""/ietf-netconf:get"" with ID 263 priority 0 for 1 subscribers."
"netopeer2-server|INFO ""LY"" Resolving unresolved data nodes and their constraints..."
netopeer2-server|ERROR ""SR"" Waiting on a conditional variable failed (sr_shmsub_notify_wait_wr: Connection timed out)."
netopeer2-server: /workspace/agent/PRG-Builds/OTA/6.0.1.149/ran_3rdparty/open_source/netconf/sysrepo/src/common.c:3269: sr_rwunlock: Assertion `!rwlock->readers[0] && !rwlock->upgr && (rwlock->writer == cid)' failed."

netopeer2-server as per CMakeList.txt file :
set(NP2SRV_VERSION 1.1.76)

**Comment by michalvasko** [comment]
Likely a locking problem that was fixed in v2. I can only suggest to avoid the timeout because that is a problem no matter what but it is hard to say what is causing it. You may be causing a dead lock depending on what exactly are you doing in the operational callbacks (assuming you have some).
