### ISSUE TITLE
Whether action type nodes support？

### ISSUE THREAD

**Issue by linbolin** [CESNET/netopeer2#1139]
Hello！
    Whether action type nodes support？
eg:
action reset{
	description 
		"Reset.";
}
If yes, how can I register the corresponding callback function?

**Comment by michalvasko** [comment]
Try [this](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__rpc__subs__api.html#gad8922c407eab01fb0ba7aec2114a8d7e) function, read its description.
