### ISSUE TITLE
lyd_find_path() usages

### ISSUE THREAD

**Issue by barbarost** [CESNET/netopeer2#1141]
Hi,

In `netopeer2` source code, there are many `lyd_find_path()` usages where its return value is not checked but output `node` variable is checked against NULL.
For instance (`np2srv_rpc_commit_cb()` of `src/netconf_confirmed_commit.c`),
```
    struct lyd_node *node;
    :
    :
    /* check if confirmed-commit */
    lyd_find_path(input, "confirmed", 0, &node);
    if (node) {
        rc = np2srv_confirmed_commit_cb(session, input);
        goto cleanup;
    }
```
In this case, `node` can be initialized to have a random value (since it is local variable) and `lyd_find_path()` can return with an error, not modifying `node`, but code will branch into `if` condition with an invalid `node` value.
I think the code either should check the return value of `lyd_find_path()` or set `node` to NULL before calling `lyd_find_path()`.

**Comment by michalvasko** [comment]
The only error that can occur is a memory allocation problem, which is not handled everywhere in *netopeer2*. Otherwise the `node` will be set. Feel free to provide patches to handle all the errors.

**Comment by barbarost** [comment]
For the code I shared above, on my platform `node` is having a random non-NULL value initially. For the `"confirmed"` leaf, `lyd_find_path()` returns `LY_EVALID` and `node` is not set by `lyd_find_path()`. But in that case, since `node` is random and non-NULL, it causes to take the `if` branch there and a segmentation fault inside `np2srv_confirmed_commit_cb()`.

I would suggest to change the code as below (for all `lyd_find_path()` calls and will try to create a patch):
```
    /* check if confirmed-commit */
    node = NULL;
    lyd_find_path(input, "confirmed", 0, &node);
    if (node) {
        rc = np2srv_confirmed_commit_cb(session, input);
        goto cleanup;
    }
```

**Comment by michalvasko** [comment]
Real question is why `lyd_find_path()` returns `LY_EVALID` in your case.

**Comment by barbarost** [comment]
That's right, I will check for it. But in any case, `netopeer2-server` shouldn't crash with invalid input or invalid YANG modules.

**Comment by barbarost** [comment]
OK, returning `LY_EVALID` happens in `_ly_path_compile()` when `confirmed-commit` feature of `ietf-netconf` is not enabled:
```
908	        if (!node2 || (op && (node2->nodetype & (LYS_RPC | LYS_ACTION | LYS_NOTIF)) && (node2 != op))) {
(gdb) p node2
$18 = (const struct lysc_node *) 0x0
(gdb) p op
$19 = (const struct lysc_node *) 0x0
(gdb) list
903	        if (!ctx_node && ext) {
904	            node2 = lysc_ext_find_node(ext, mod, name, name_len, 0, getnext_opts);
905	        } else {
906	            node2 = lys_find_child(ctx_node, mod, name, name_len, 0, getnext_opts);
907	        }
908	        if (!node2 || (op && (node2->nodetype & (LYS_RPC | LYS_ACTION | LYS_NOTIF)) && (node2 != op))) {
909	            LOGVAL(ctx, LYVE_XPATH, "Not found node \"%.*s\" in path.", (int)name_len, name);
910	            ret = LY_EVALID;
911	            goto cleanup;
912	        }
(gdb) step
909	            LOGVAL(ctx, LYVE_XPATH, "Not found node \"%.*s\" in path.", (int)name_len, name);
```
Once `confirmed-commit` feature of `ietf-netconf` is enabled, `_ly_path_compile()` returns `LY_ENOTFOUND` and `node` is set to be NULL:
```
np2srv_rpc_commit_cb (session=0x19bbf0, UNUSED_sub_id=108, UNUSED_op_path=0x177a80 "/ietf-netconf:commit", input=0x19bd30, event=SR_EV_RPC, UNUSED_request_id=1, UNUSED_output=0x178e30, UNUSED_private_data=0x0)
    at netopeer2-2.1.13/src/netconf_confirmed_commit.c:838
838	    pthread_mutex_lock(&commit_ctx.lock);
Value returned is $5 = 0
(gdb) step
840	    lyd_find_path(input, "confirmed", 0, &node);
(gdb) step
lyd_find_path (ctx_node=0x19bd30, path=0x37434 "confirmed", output=0 '\000', match=0x15782e3c) at libyang-2.0.142/src/tree_data.c:4568
4568	    LY_ERR ret = LY_SUCCESS;
(gdb) finish
Run till exit from #0  lyd_find_path (ctx_node=0x19bd30, path=0x37434 "confirmed", output=0 '\000', match=0x15782e3c) at libyang-2.0.142/src/tree_data.c:4568
np2srv_rpc_commit_cb (session=0x19bbf0, UNUSED_sub_id=108, UNUSED_op_path=0x177a80 "/ietf-netconf:commit", input=0x19bd30, event=SR_EV_RPC, UNUSED_request_id=1, UNUSED_output=0x178e30, UNUSED_private_data=0x0)
    at netopeer2-2.1.13/src/netconf_confirmed_commit.c:841
841	    if (node) {
Value returned is $6 = LY_ENOTFOUND
(gdb) p node
$7 = (struct lyd_node *) 0x0
(gdb) 
```

**Comment by michalvasko** [comment]
I did some improvements and check the return value where simple enough but also, you will not be able to start the server anymore if `confirmed-commit` is not enabled.
