### ISSUE TITLE
Capability missing in Server hello message

### ISSUE THREAD

**Issue by j1y3p4rk** [CESNET/netopeer2#1143]
Hi michalvasko,

After successful TLS handshake and secure channel establishment, server sends hello message. 
I think 'truststore' and 'keystore' capabilities are missing in the hello message from server side.  Shouldn't those two modules be included in the capability exchange?

![Picture1](https://user-images.githubusercontent.com/4647774/153216745-257cf536-9a27-4d90-aa96-b7659232ed95.png)
e

**Comment by michalvasko** [comment]
Yet again, no, they [should not](https://datatracker.ietf.org/doc/html/rfc7950#page-12) (last bullet) be there.

**Comment by j1y3p4rk** [comment]
Thanks for the quick reply. 
Then, shouldn't list other modules like acm, x509-cert-to-name above either?
