### ISSUE TITLE
Want the ssh-callhome retry mechanism to occur after a fixed interval of time.

### ISSUE THREAD

**Issue by bijit999** [CESNET/netopeer2#1144]
Hi , 
I want the ssh-callhome retry mechanism to occur after a fixed interval of time after the connectivity from the client side is broken  . 
Is there any parameter available which can can control the time gap between consecutive callhome retries . 
If such a parameter is available is there any api which we can use to get the value .
Thank you.

**Comment by michalvasko** [comment]
Look at the parameter is [this container](https://github.com/CESNET/netopeer2/blob/master/modules/ietf-netconf-server%402019-07-02.yang#L377).

**Comment by bijit999** [comment]
Hi @michalvasko , thanks for the previous update . I did went through that container , i found out that if the connectivity type is periodic , then we can control the retry mechanism by using different period values. But i noticed one thing that the server uses this formula for calculating the retry time ---------
reconnect_in = (time(NULL) - client->conn.period.anchor_time) % (client->conn.period.period * 60);
-----------------
Now if we set the period as 1 , then we get the reconnect time between 0 to 59 (as mod is used there) every time the client disconnects.
So, is there any possible way to get the same retry value for the same period value every time the client disconnects .
Thank you.

**Comment by bijit999** [comment]
Thanks for the update.

**Comment by bijit999** [comment]
Hi @michalvasko , i took the devel branch and tried doing that but  i can see that  when the client disconnects the server waits for a certain period of time , then it tries to reconnect continuously . But what i want is that after trying to connect once it should again wait for that amount of time that we mentioned before trying to reconnect again.
example: how it is working now

[INF]:LN: Trying to reconnect..... in A seconds.
[INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4334.
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4334.
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4334.
[INF]: LN: getsockopt() error (Connection refused).

how i want it to be : 
[INF]:LN: Trying to reconnect..... in A seconds.
[INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4334.
[INF]: LN: getsockopt() error (Connection refused).
[INF]:LN: Trying to reconnect..... in A seconds.
[INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4334.
[INF]: LN: getsockopt() error (Connection refused).
[INF]:LN: Trying to reconnect..... in A seconds.
[INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4334.
[INF]: LN: getsockopt() error (Connection refused).
[INF]:LN: Trying to reconnect..... in A seconds.

So , is it possible that before each retry it will wait for A seconds .
Thank you

**Comment by michalvasko** [comment]
No, this timeout is not described by `ietf-netconf-server` module so libnetconf2 does not implement it. I have used 1 second as a fixed period, you can change it only directly in the code.

**Comment by bijit999** [comment]
One more issue I am facing right now is that , every time I update the <period> parameter , the new <period> parameter value that is updated is not being used for the retry and it is still using the old value , it only gets reflected when I restart the netopeer-server.
 So , restarting the netopeer-server every time I change this parameter is not what is desired. 
So , can any thing be done on this so that we can avoid doing this restart.
Thank you.

**Comment by michalvasko** [comment]
Regarding the `period`, even in the [current draft](https://datatracker.ietf.org/doc/html/draft-ietf-netconf-netconf-client-server#page-48) the value is in minutes meaning the authors do not expect use-cases when reconnecting after seconds. We implement the standardized module so the only way of getting this functionality into *netopeer2* is to write to the NETCONF mailing list and ask for this change.

As for the `period` changes, they should be applied right away and used for the next back-off when an existing NETCONF Call Home session is terminated. Can you provide verbose output of the server to verify that it does not work as intentional?

**Comment by bijit999** [comment]
Hi , @michalvasko here are the logs for cli and server 
Are you sure you want to continue connecting (yes/no)? yes
root@::ffff:127.0.0.1 password:
`>`
>
> get --filter-xpath /ietf-netconf-server:netconf-server/call-home/netconf-client/connection-type/periodic/*
DATA
`<data` xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  `<netconf-server` xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
    `<call-home>`
      `<netconf-client>`
        `<name>default-client</name>`
        `<connection-type>`
          `<periodic>`
            `<period>2</period>`
            `<idle-timeout>0</idle-timeout>`
          `</periodic>`
        `</connection-type>`
      `</netconf-client>`
    `</call-home>`
  `</netconf-server>`
`</data>`

`>` edit-config --target running --config=/build/oam/config/yang/config/ssh_callhome.xml --defop replace
OK

`>` get --filter-xpath /ietf-netconf-server:netconf-server/call-home/netconf-client/connection-type/periodic/*
DATA
`<data` xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  `<netconf-server` xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
    `<call-home>`
      `<netconf-client>`
        `<name>default-client</name>`
        `<connection-type>`
          `<periodic>`
            `<period>1</period>`
            `<idle-timeout>0</idle-timeout>`
          `</periodic>`
        `</connection-type>`
      `</netconf-client>`
    `</call-home>`
  `</netconf-server>`
`</data>`

`>exit`

----------------------------------- on exiting from cli in server logs 

[INF]: LN: Call Home client "default-client" session terminated.
[INF]: LN: Call Home client "default-client" reconnecting in 120 seconds.
[ERR]: LN: Session 2: Waiting for Call Home thread failed (Connection timed out).
[2022/03/24 13:24:59.598192, 1] ssh_socket_exception_callback:  Socket exception callback: 1 (0)
[2022/03/24 13:24:59.598283, 1] ssh_socket_exception_callback:  Socket error: disconnected
[ERR]: SR: Internal error (/opt/dev/sysrepo/src/common.c:3826).
[ERR]: SR: Internal error (/opt/dev/sysrepo/src/common.c:3826).

here we can still see that retry time is 120 seconds , but it should have been 60 seconds (as we changed the period value from 2 to 1) .

**Comment by michalvasko** [comment]
Okay, so if you update *libnetconf2*, you should no longer see the errors in the output. Also, the periodic parameters were really not being applied, which should be fixed in latest *netopeer2* `devel`.

**Comment by bijit999** [comment]
Hi  @michalvasko , now I am able to get the period parameters without restarting the server , so the fix worked .
Thank you for the support .
