### ISSUE TITLE
NC_ENABLED_TLS and  NC_ENABLED_SSH not found

### ISSUE THREAD

**Issue by LoveCPro** [CESNET/netopeer2#1145]
Q:
-- Found LibSSH:XXX/tmpfs/lib/ (Required is at least version "0.7.0") 
-- Looking for NC_ENABLED_SSH
-- Looking for NC_ENABLED_SSH - not found
-- Looking for NC_ENABLED_TLS
-- Looking for NC_ENABLED_TLS - not found
CMake Error at server/CMakeLists.txt:145 (message):
  Missing SSH support in libnetconf2, server requires SSH to be supported.

tmpfs/include has nc_client.h and nc_server.h, and FindLibNetconf2.cmake can also find these two files. But executing cmake still shows that NC_ENABLED_SSH and NC_ENABLED_TLS cannot be found

**Comment by michalvasko** [comment]
What *netopeer2* version are you compiling? There were some problems with this before but it should have been fixed.

**Comment by LoveCPro** [comment]
Netopeer2: 1.1.7，libssh： 0.7.6

**Comment by michalvasko** [comment]
That is 2 years old, I really cannot help you then.
