### ISSUE TITLE
Store SSH X509 certificate configuration at Netopeer2 for using with SSH Server[Question] 

### ISSUE THREAD

**Issue by ankit7gup** [CESNET/netopeer2#1146]
Hi Michal,

As currently SSH X509 certificates are not supported by Netopeer2-server. We plan to use external SSH server and connect to Netopeer2-server via Unix Socket(using -u option). Meanwhile to store the respective configuration in the datastore, I want to use below parameters. Additionally, ietf-keystore config shall also get modified for respective leafrefs.
```xml
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
    <listen>
        <endpoint>
            <name>default-ssh</name>
            <ssh>
                <tcp-server-parameters>
                    <local-port>1830</local-port> [830 Port to be used to listen at SSH server and this port at netopeer2-server to connect from ssh server]
                    <local-address>127.0.0.1</local-address>
            </tcp-server-parameters>
             <ssh-server-parameters>
                            <server-identity>
                                <host-key>
                                    <name>default-key</name>
                                    <certificate>
                                            <keystore-reference>
                                                    <asymmetric-key></asymmetric-key> [respective values to be added in reference to ietf-keystore parameters from merge_hostkey.sh]
                                                    <certificate></certificate> [respective values to be added in reference to ietf-keystore parameters from merge_hostkey.sh]
                                            </keystore-reference>
                                    </certificate>
                                </host-key>
                            </server-identity>
                        </ssh-server-parameters>
            </ssh>
        </endpoint>
    </listen>
</netconf-server>
```

**merge_hostkey.sh**
```
CONFIG="<keystore xmlns=\"urn:ietf:params:xml:ns:yang:ietf-keystore\">
    <asymmetric-keys>
        <asymmetric-key>
            <name>genkey</name>
            <algorithm>rsa2048</algorithm>
            <public-key>$PUBKEY</public-key>
            <private-key>$PRIVKEY</private-key>
        </asymmetric-key>
    </asymmetric-keys>
</keystore>"
```
Question 1: Can you please confirm, if doing so, won't affect the existing functionality. Or something else/additional I need to do?

Question 2: Is there any plan to add SSH X509 support in the recent future?

Thanks!

Regards,
Ankit

**Comment by michalvasko** [comment]
> Can you please confirm, if doing so, won't affect the existing functionality. Or something else/additional I need to do?

You do not have to have any `ietf-netconf-server` configuration if you plan to connect only using the UNIX socket. That configuration is only for SSH/TLS connections.

> Is there any plan to add SSH X509 support in the recent future?

No.

**Comment by ankit7gup** [comment]
I also want to modify the port number that has to be used for connect in netopeer2-server from 830 to some other number, during config load via sysrepocfg. 
For doing that, sysrepocfg, asks for additional parameters to be set. 
While running same config as a merge operation using netopeer2-cli, I am able to set.

**Comment by michalvasko** [comment]
Then just modify the [original config](https://github.com/CESNET/netopeer2/blob/master/scripts/merge_config.sh), it seems you are missing some data from it.

**Comment by ankit7gup** [comment]
Thanks Michal, With the mentioned config and added parameter it worked.
