### ISSUE TITLE
How to enable logging in netopeer2 ?

### ISSUE THREAD

**Issue by vedprajapati** [CESNET/netopeer2#1147]
To debug the issue of some RPC Failures, we want to enable traces inside netopeer2.
Are there some set of APIs which can be called from the main thread to enable Debug level logs within netopeer2 ?
If yes, should these APIs be called before server_init() API ?

**Comment by michalvasko** [comment]
I can only reference how *netopeer2* sets its own verbosity using [parameters](https://github.com/CESNET/netopeer2/blob/master/src/main.c#L1122). The server itself does not have much to output, it is mostly about all the libraries printing their messages (libyang, sysrepo, libnetconf2).

**Comment by vedprajapati** [comment]
Thanks for your reply Michal.
Taking reference from the handling of option "-c MSG", we tried calling the _nc_verbosity(NC_VERB_DEBUG)_ API from our main thread before calling _server_init()_ but it is causing some crash in the process. Is there any limitation in calling the _nc_verbosity()_ API ?
Also, please guide on how we can enable the traces within all the libraries ?

**Comment by michalvasko** [comment]
i have no idea what you are doing but calling `nc_verbosity()` definitely should not result in a crash. If you have your own callback set, that is what may be causing the problem.

> Also, please guide on how we can enable the traces within all the libraries ?

There are only debug messages, I do not know what you mean by traces. Printing all the called functions or something? That is not supported.
