### ISSUE TITLE
Query on netconf connections

### ISSUE THREAD

**Issue by meghna-doshi** [CESNET/netopeer2#1148]
Hi,
We had one query related to the netconf sessions.
If any netconf client does "connect" to the netconf server, is there a way that the netopeer2-server can inform some application about 
1. the connection establishment
2. the connection release (in case the established connection is lost)

**Comment by michalvasko** [comment]
1. Subscribe to [this](https://github.com/sysrepo/sysrepo/blob/master/modules/ietf-netconf-notifications.yang#L170) notification.
2. Subscribe to [this](https://github.com/sysrepo/sysrepo/blob/master/modules/ietf-netconf-notifications.yang#L179) notification.
