### ISSUE TITLE
Failed to edit-config if there is a char ' in leaf-list

### ISSUE THREAD

**Issue by fanchanghu** [CESNET/Netopeer2#115]
Hi,
I'm using devel-server branch, and you can reproduce this issue by following data:

a.yang
```
module a {
    namespace "aa:1";
    prefix "a";
	
    container c1 {
		leaf-list f1{type string;}
    }
}
```
d.xml
```
<c1 xmlns="aa:1"><f1>abc's</f1></c1>
```

**Comment by michalvasko** [comment]
Hi,
please try it now.

Regards,
Michal

**Comment by fanchanghu** [comment]
Hi,
This issue is fixed, but it does still not work if there are both ' and " in one string, such as :
```
<c1 xmlns="aa:1"><f1>abc's "hello" </f1></c1>
```

**Comment by michalvasko** [comment]
Hi,
in short, sysrepo does not support setting values with both `'` and `"`, so it is not allowed. But, to elaborate, there is an inconsistency in what can be a value in YANG and what a Literal in XPath 1.0 (the latter does not allow your example) and this is the real cause.

Regards,
Michal

**Comment by fanchanghu** [comment]
In fact, I does not really need  both ' and " in one string, just a question. thanks for explanation.
