### ISSUE TITLE
NETCONF Authentication based on X.509 certificate using SSH

### ISSUE THREAD

**Issue by JoemonChittilapilly** [CESNET/netopeer2#1150]
Does X.509 certificate work with ssh?
If yes , what are the steps to use it with netopeer2 and I am using netopeer-cli as client

**Comment by michalvasko** [comment]
No, we currently do not support X.509 certificate use for SSH.

**Comment by JoemonChittilapilly** [comment]
While using TLS listen how do I connect NETCONF client using client.cert

**Comment by michalvasko** [comment]
Depends on the client, for *netopeer2-cli* you need to use the `cert` command to add your own credentials and the trusted CA certificates to accept the server certificate.

**Comment by JoemonChittilapilly** [comment]
can you help me with the cert commands to connect using netopeer-2 cli

**Comment by michalvasko** [comment]
Knowing basic information about the certificates and which need to be trusted/used based on TLS principles is the first step. Then, you should now what to do based on the help of the command
```
cert -h
```
What exactly is the problem?

**Comment by JoemonChittilapilly** [comment]
When i am adding ca.pem using cert command in netopeer2-cli 
_> cert add ca.pem
Segmentation fault (core dumped)_

what is meant by this error and how to rectify it.

**Comment by JoemonChittilapilly** [comment]
Netopeer2 CLI 2.0.62

**Comment by michalvasko** [comment]
I see, I am almost certain it is some compatibility problem on your end. You can try reinstalling *netopeer2* with all its dependencies or use a tool (`gdb`/`valgrind`) to provide more information about the crash and paste it here to learn some details about the problem.

**Comment by nicholasthorn** [comment]
In

> When i am adding ca.pem using cert command in netopeer2-cli _> cert add ca.pem Segmentation fault (core dumped)_
> 
> what is meant by this error and how to rectify it.

In case it helps people following - I found that this segfault may occur when you don't specify the full (ie not relative) path to the certificate in question in netopeer2-cli

**Comment by michalvasko** [comment]
No idea why you commented on a closed unrelated issue, please refrain from doing so in the future, but it should be fixed.
