### ISSUE TITLE
Shared memory version mismatch (1381123419, expected 7), remove the SHM to fix

### ISSUE THREAD

**Issue by PeterYFPeng** [CESNET/netopeer2#1152]
There is a process in my system that will use shm too. When I run this process, the netopeer2-server or sysrepo command will fail. The log is below: 

root@localhost:~/SageranTcpLib_fudan/sample# netopeer2-server -d -v3
[INF]: LY: Searching for "ietf-yang-types" in "/home/user/cs/M-Plane-Scripts/sysrepo/build/repository/yang".
[INF]: LY: Newer revision than "ietf-yang-types@2013-07-15" not found, using this as the latest revision.
[ERR]: SR: Shared memory version mismatch (1381123419, expected 7), remove the SHM to fix.
[ERR]: NP: Connecting to sysrepo failed (Operation not supported).
[ERR]: NP: Server init failed.
[INF]: NP: Server terminated.

root@localhost:~/SageranTcpLib_fudan/sample# sysrepoctl -l
[ERR]: Shared memory version mismatch (1381123419, expected 7), remove the SHM to fix.
sysrepoctl error: Failed to connect (Operation not supported)
For more details you may try to increase the verbosity up to "-v3".

I can clear the /dev/shm and reboot my system to run netopeer2-server successfully without my process

**Comment by michalvasko** [comment]
Why would your process use the exact same SHM name as *sysrepo*? Obviously, it won't work.

**Comment by PeterYFPeng** [comment]
> Why would your process use the exact same SHM name as _sysrepo_? Obviously, it won't work.

Sorry. I have checked the SHM name. The name of my module is not the same as the sysrepo used.
But this problem has not been happened after that I upgraded my system

**Comment by nanfengnan1** [comment]
i have meet his question. such as this description:
root@localhost:/opt/deps/sysrepo/build# ./sysrepoctl -l
[ERR] Shared memory version mismatch (6, expected 9), remove the SHM to fix.
sysrepoctl error: Failed to connect (Operation not supported)
For more details you may try to increase the verbosity up to "-v3".

i didi't know how to resolve this qz. hope to help me.

**Comment by michalvasko** [comment]
You have updated *sysrepo* and this error prevents the old SHM to be used, which would not work. It should be enough to restart your system (to delete all the files in `/dev/shm`) but you can do that manually from *sysrepo* `build` dir by running `make shm_clean`.

**Comment by nanfengnan1** [comment]
thanks. use your methods, sysrepo works well.
