### ISSUE TITLE
netopeer2-server starts even sysrepo-plugind is not started

### ISSUE THREAD

**Issue by maksimvuleta** [CESNET/netopeer2#1156]
I use the netopee2-server v1.1.76 and sysrepo v.1.4.140.

I am able to start the netopeer2-server without sysrepo-plugind started. Also, I can connect to the netopee2-server and get the data. 

I noticed this in the case when I run sysrepo-plugind and netopeer2-server by some script and do the get data and the data I got was not complete because the sysrepo-plugind was still initializing my plugins. 

Is there any sysrepo/netopeer2 feature I can use to prevent this? Maybe some signal (or file) that will guarantee that sysrepo finished all plugins initialization?

**Comment by jktjkt** [comment]
This is not a bug in Netopeer; the NETCONF server has no way of knowing that all applications that happen to use sysrepo have already started.

This looks like an excellent job for your init system. If you use systemd, I suggest to rely on their `Requires`, `PartOf`, etc stanzas.

Also, you're on a legacy release of the software stack; you might want to prioritize upgrades to v2.

**Comment by maksimvuleta** [comment]
I am aware that netopeer does not know about all applications. 
My question is there anything on the sysrepo side that can tell me the sysrepo with all plugins is up and initialization is done?

**Comment by michalvasko** [comment]
There is not except for the current `master`/`devel` version where a full support for *systemd* was added and it is notified by `sysrepo-plugind` once the initialization is finished. If using versions 1.x you can only sleep for some time and hope for the best. Or implement some communication in your plugin initialization callback.

**Comment by jktjkt** [comment]
> is there anything on the sysrepo side that can tell me the sysrepo with all plugins is up and initialization is done?

No. Sysrepo is "just a YANG database", and it also does not know up front whether all subscribers have already connected. Even if it performed some heuristics such as "is there at least one subscriber to each YANG model?" or "all `config: true` subtrees covered by a subscription?", there will be no way of reliably ensuring that, e.g., all `operational` data have been pushed.

If I were you I would solve this via systemd unit dependencies. The fact that `sysrepo-plugind` uses `sd_notify()` should help a lot.

**Comment by maksimvuleta** [comment]
Thank you both for your answers. 

We do not have systemd on our device, so it is not a solution for us. 
So, we will implement some communication in our plugin init callback, for now. That was also our idea if there is nothing on sysrepo side that can help us.
