### ISSUE TITLE
callbacks priorities

### ISSUE THREAD

**Issue by matkocc** [CESNET/netopeer2#1157]
Hi,

I am wondering whether it is possible to increase the priority of callback over others callbacks from other modules. E.g. if I want set higher priority for 1 RPC callback over every other callback.

Netopeer2 v1.1.53

Thanks,
    Matko

**Comment by michalvasko** [comment]
It does not make sense to want to set an RPC callback priority with regard to other RPCs. They are all independent and if possible executed concurrently.
