### ISSUE TITLE
Possibility of updating notifications and nc-notifications data models ?

### ISSUE THREAD

**Issue by Wexiwa** [CESNET/netopeer2#1159]
Hello,

I was wondering from where `notifications` and `nc-notifications` came from, after looking for them on the [YangCatalog](https://www.yangcatalog.org) I see that they seem to be vendor (Cisco) specific implementations of the `RFC 5277`.

Looking a bit more on other implementation of the `RFC 5277` I found the ones from IETF, which are more recent:
- [ietf-5277-netmod@2016-06-15](https://www.yangcatalog.org/yang-search/module_details/ietf-5277-netmod@2016-06-15)  to replace  `nc-notifications@2008-07-14`
- [ietf-event-notifications@2016-10-27](https://www.yangcatalog.org/yang-search/module_details/ietf-event-notifications@2016-10-27) to replace `notifications@2008-07-14`

They seem to be almost compatible (it seems there is a new leaf [/netconf/streams/stream/replayLogAgedTime](https://www.yangcatalog.org/yang-search/show_node/ietf-5277-netmod/%2Fnetmod-notif:netconf%3Fcontainer%2Fnetmod-notif:streams%3Fcontainer%2Fnetmod-notif:stream%3Flist%2Fnetmod-notif:replayLogAgedTime%3Fleaf/2016-06-15)) and I guess it would involve to update the path in `netopeer2`.

Do you think this update would be that easily feasible so you could plan to do it ?

I would be glad to propose a pull request, however I am afraid I lack too much knowledge regarding Yang, Netconf and the CESNET projects to be able to offer quality content.

**Comment by michalvasko** [comment]
The first module seems fine but it is almost the same to the one we use, like you said, so I see a lot of changes and perhaps compatibility problems for little benefit.

The other module `ietf-event-notifications` seems rather close to the even more recent `ietf-subscribed-notifications`. We fully implement and support the latter so I again do not see the benefits outweigh the cost and problems.
