### ISSUE TITLE
Support for TLS 1.3 ?

### ISSUE THREAD

**Issue by mpet** [CESNET/netopeer2#1162]
Hi,

Will netopeer2 support TLS 1.3 in the future?

br,

//mike

**Comment by michalvasko** [comment]
I would start by asking a question, what makes you think it does not support it? Seems OpenSSL supports it for a long time and I could not find any information about some special commands needed to support it.

**Comment by mpet** [comment]
Hi @michalvasko 
Sorry my heading is about that but I think you got the message anyway. Thanks I will try it out.
