### ISSUE TITLE
Need help to create XML node for GET request

### ISSUE THREAD

**Issue by SumitPhutrapahl** [CESNET/netopeer2#1164]
Hello Michal Vasko!

This is just a request for help because I cannot find and answer in Google or Libyang documentation. 

I'm working on [o-ran-performance-management.yang](https://github.com/CESNET/netopeer2/files/8185644/o-ran-performance-management.txt) and cannot create XML node for YANG node "/o-ran-performance-management:performance-measurement-objects/measurement-capabilitites/epe-stats-objects[measurement-object='TEMPERATURE']/component-class".

The field is of identityref type.
![изображение](https://user-images.githubusercontent.com/92869702/156759301-e3be6d25-5e04-4d1a-ba65-bfa17c744e6c.png)
There are few similar identities in [iana-hardware.yang](https://github.com/CESNET/netopeer2/files/8185664/iana-hardware.txt). But when I try to create the leaf-list of size 1 with identity "ianahw:chassis" inside GET request callback I'm gettint error 7  (LY_EVALID - Validation failure) from **lyd_new_path** function.

My code:

```
struct lyd_node *capabilities_p = NULL;
ret = lyd_new_path(*parent, NULL, "/o-ran-performance-management:performance-measurement-objects/measurement-capabilitites/epe-stats-objects[measurement-object='TEMPERATURE']/measurement-object", "TEMPERATURE", 0, &capabilities_p);
if (ret != LY_SUCCESS) {
	syslog(LOG_ERR, "Failed to add 'measurement-object' field; error %d", ret);
	return SR_ERR_LY;
}
ret = lyd_new_path(capabilities_p, NULL, "/o-ran-performance-management:performance-measurement-objects/measurement-capabilitites/epe-stats-objects[measurement-object='TEMPERATURE']/component-class", "chassis", 0, NULL);
if (ret != LY_SUCCESS) {
    syslog(LOG_ERR, "Failed to add 'component-class' field; error %d", ret);
    return SR_ERR_LY;
}
```

The first one is created successfully. But the second one not.

Could you please suggest me how to do that (to create the 'component-class' field correctly).

**Comment by michalvasko** [comment]
To not require any additional information and be unambiguous, all API functions expect JSON format of all values/paths. That means that you must use the module name instead of import prefix.
```
iana-hardware:chassis
```

**Comment by SumitPhutrapahl** [comment]
That works! Thank you very much! Will keep in mind this format.
![изображение](https://user-images.githubusercontent.com/92869702/156884802-1d25d6df-84c9-4bb5-826a-2659e650e86e.png)
