### ISSUE TITLE
some questions about np2srv_get_rpc_data API

### ISSUE THREAD

**Issue by itercheng** [CESNET/netopeer2#1169]
@michalvasko 

Please allow me to have some doubts about  np2srv_get_rpc_data function. because it just got all possible data first as described, and then used the filter the second time. why not use the filter for the first time. it can avoid triggering multiple operation subscribe ? Please refer following examples:

1. subscribing two operational API
    sr_oper_get_items_subscribe(sess, "Device_Module", "/Device_Module:Device/LogMgmt/PeriodicUploadEnable", my_cb, NULL, SR_SUBSCR_CTX_REUSE | SR_SUBSCR_DONE_ONLY, &subscr);

   sr_oper_get_items_subscribe(sess, "Device_Module", "/Device_Module:Device/FaultMgmt", my_cb, NULL, SR_SUBSCR_CTX_REUSE | SR_SUBSCR_DONE_ONLY, &subscr);

2. than send get data request from client.
  get --filter-xpath=/Device_Module:Device/FaultMgmt

3.  sever will get all data under Device_Module so that trigger both of my subscribes. but I expect to trigger only the callback for the same filter I gave it.

so I tried to modify np2srv_get_rpc_data API to use filter the first time.  this will achieved my expectation , but I am not sure if it will cause other problem. What do you think about? Thank you in advance.

 op_filter_data_get(session, 0, get_opts, &mod_filter, ev_sess, &all_data) Modify as 
 op_filter_data_get(session, 0, get_opts, filter, ev_sess, data)

**Comment by michalvasko** [comment]
So yet again, if you want to learn exactly the reason (with the specific use-case) look at the issue referenced in the commit 9dbefcf3e21b0d41248ef141281fd461d76ca88a. To avoid these inefficiencies, use `get-data` instead of `get`.

**Comment by itercheng** [comment]
Hi michalvasko:
Thanks for quick reply. I understand that the data should be got from both the running and operation database. but it make me confused why  all the data under this module  should be got in first retrieval action.  Could you please kindly give me more details about this action ?
The  
https://github.com/CESNET/netopeer2/commit/9dbefcf3e21b0d41248ef141281fd461d76ca88a you mentioned seems to describe the problems of config and state(in order to keep the synchronization between config and state). is that right?

**Comment by michalvasko** [comment]
> Could you please kindly give me more details about this action ?

Not really, I referenced the issue so you can see for yourself. In short, before only the selected data were being retrieved but it was not working, now it is. To tell you the details I would have to understand the exact problem again, which would be a waste of time for me.

**Comment by michalvasko** [comment]
> The problem here is that I need the server to work with the original RPC in an efficient, scalable way.

I see, I do not think I can help you with that. *sysrepo* offers too much options of providing data and together with NMDA this results in the mess you see. Back when I was working on the issue I remember it took me considerable time to understand it and come up with a fix. I do not think it is worth it to do so again because it is unlikely that I could fix this in some reasonable way even though it was a long time ago and many things have changed.
