### ISSUE TITLE
Netopeer2 server not able to establish connection to all configured Callhome clients

### ISSUE THREAD

**Issue by senrajib** [CESNET/Netopeer2#117]
Hi Michal
I had configured  three callhome clients at a time  by writing into sysrepo datastore using sysrepo APIs. Repeated this test several times. Observed Netopeer2 server able to connect to only one client or sometime two clients but not to all. When i configured them individually , Netopeer2 server was able to establish connection to all of them.Configuration as below

-Rajib

[root@MaestrOS ~]# netstat -an | grep 60830
tcp        0      0 10.1.18.83:43644        10.1.23.141:60830       ESTABLISHED
[root@MaestrOS ~]#

[ietf-netconf-server.zip](https://github.com/CESNET/Netopeer2/files/870298/ietf-netconf-server.zip)

**Comment by michalvasko** [comment]
Hi,
please provide the netopeer verbose (`-v2`) output, it should be clear from it what was happening.

Regards,
Michal

**Comment by senrajib** [comment]
Hi Michal 
As you said , i am running Netopeer2 as below
Please find the debug logs attached.
[debuglog.zip](https://github.com/CESNET/Netopeer2/files/871894/debuglog.zip)

-Rajib
///////////////////////
[root@MaestrOS ~]# ps -eaf | grep netopee
root     17529     1  5 03:41 ?        00:00:00 /usr/sbin/netopeer2-server -d -v2 3
root     17588  1431  0 03:41 pts/0    00:00:00 grep --color=auto netopee
[root@MaestrOS ~]#
[root@MaestrOS ~]#
[root@MaestrOS ~]# cat /etc/sysrepo/data/ietf-netconf-server.running
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <listen>
    <endpoint>
      <name>test_ssh_listen_endpt</name>
      <ssh>
        <address>0.0.0.0</address>
        <port>830</port>
        <host-keys>
          <host-key>
            <name>test_ssh_listen_key</name>
            <public-key>ssh_host_rsa_key</public-key>
          </host-key>
        </host-keys>
      </ssh>
    </endpoint>
  </listen>
  <call-home>
    <netconf-client>
      <name>Controller1</name>
      <ssh>
        <host-keys>
          <host-key>
            <name>rsa_key</name>
            <public-key>ssh_host_rsa_key</public-key>
          </host-key>
        </host-keys>
        <endpoints>
          <endpoint>
            <name>ed1</name>
            <address>10.1.23.142</address>
            <port>60830</port>
          </endpoint>
        </endpoints>
      </ssh>
      <connection-type>
        <periodic>
          <idle-timeout>180</idle-timeout>
          <reconnect_timeout>30</reconnect_timeout>
        </periodic>
      </connection-type>
      <reconnect-strategy>
        <max-attempts>4</max-attempts>
        <start-with>last-connected</start-with>
      </reconnect-strategy>
    </netconf-client>
    <netconf-client>
      <name>Controller3</name>
      <ssh>
        <host-keys>
          <host-key>
            <name>rsa_key</name>
            <public-key>ssh_host_rsa_key</public-key>
          </host-key>
        </host-keys>
        <endpoints>
          <endpoint>
            <name>ed1</name>
            <address>10.1.23.141</address>
            <port>60830</port>
          </endpoint>
        </endpoints>
      </ssh>
      <connection-type>
        <periodic>
          <idle-timeout>180</idle-timeout>
          <reconnect_timeout>30</reconnect_timeout>
        </periodic>
      </connection-type>
      <reconnect-strategy>
        <max-attempts>4</max-attempts>
        <start-with>last-connected</start-with>
      </reconnect-strategy>
    </netconf-client>
    <netconf-client>
      <name>Controller4</name>
      <ssh>
        <host-keys>
          <host-key>
            <name>rsa_key</name>
            <public-key>ssh_host_rsa_key</public-key>
          </host-key>
        </host-keys>
        <endpoints>
          <endpoint>
            <name>ed1</name>
            <address>10.1.23.139</address>
            <port>60830</port>
          </endpoint>
        </endpoints>
      </ssh>
      <connection-type>
        <persistent>
          <idle-timeout>180</idle-timeout>
          <keep-alives>
            <max-wait>30</max-wait>
            <max-attempts>3</max-attempts>
          </keep-alives>
        </persistent>
      </connection-type>
      <reconnect-strategy>
        <max-attempts>4</max-attempts>
        <start-with>first-listed</start-with>
      </reconnect-strategy>
    </netconf-client>
  </call-home>
</netconf-server>
[root@MaestrOS ~]# netstat -an | grep 60830
tcp        0      0 10.1.18.83:60670        10.1.23.142:60830       ESTABLISHED
[root@MaestrOS ~]# netstat -an | grep 60830
tcp        0      0 10.1.18.83:60670        10.1.23.142:60830       ESTABLISHED
[root@MaestrOS ~]# netstat -an | grep 60830
tcp        0      0 10.1.18.83:60670        10.1.23.142:60830       ESTABLISHED
[root@MaestrOS ~]#

/////////////////////

**Comment by michalvasko** [comment]
From the log it seems you only set the CH client `Controller1`, which proceeded to immediately successfully connect, so please provide the log, in which you set all 3 clients (would be nice if you could filter the log a bit, right now I am interested only in *netopeer2-server* output, not *sysrepo*, so much clutter).

Regards,
Michal

**Comment by senrajib** [comment]
Hi Michal

Not sure why would Netopeer2 not receive all 3 client's configuration when sysrepo ietf-netconf-server.running shows all three client configurations. Please check in below 

-Rajib
[ietf-netconf-server.zip](https://github.com/CESNET/Netopeer2/files/871973/ietf-netconf-server.zip)

**Comment by michalvasko** [comment]
Hi Rajib,
I believe if you fix issue #118, this one will also disappear.

Regards,
Michal

**Comment by senrajib** [comment]
Hi Michal
After taking new libs , still observing this issue. Netopeer2 is not attempting callhome connection to all configured clients.

-Rajib

**Comment by michalvasko** [comment]
Hi Rajib,
so did you resolve the issue #118? It could be seen in the logs, so please check. If so, then close that issue and try this again.

Regards,
Michal

**Comment by senrajib** [comment]
Hi Michal

Thanks for the reply! As you had indicated of some modifications into Netopeer2 code base, i am testing reconnect_timeout instead of reconnect-timeout. But still see Netopeer2 server attempting callhome connection for two clients out of three clients configured.

 [root@MaestrOS ~]# cat /var/log/debuglog | grep "Call"
Apr  6 03:03:51 MaestrOS netopeer.sh[19023]: netopeer2-server[19033]: Call Home                                                                                                                                                              client "Controller2" connecting...
Apr  6 03:03:51 MaestrOS netopeer2-server[19033]: Call Home client "Controller2"                                                                                                                                                              connecting...
Apr  6 03:03:51 MaestrOS netopeer.sh[19023]: netopeer2-server[19033]: Call Home                                                                                                                                                              client "Controller1" connecting...
Apr  6 03:03:51 MaestrOS netopeer2-server[19033]: Call Home client "Controller1"                                                                                                                                                              connecting...

**Comment by michalvasko** [comment]
Hi Rajib,
that means the callback for the 3rd client was not called for some reason, could you provide the output? Also, please, use lower verbosity for *sysrepo*, `-l3` is almost always good enough.

Regards,
Michal

**Comment by senrajib** [comment]
Hi Michal,

In (latest Neopeer2 devel code base ) Ietf_netconf_server.c : module_change_resolve() , still 'reconnect-timeout' is being used instead of reconnect_timeout resulting  module_change_cb breaking out from while loop  and  not parsing any further module change from sysrepo.

Apr  6 08:11:16 MaestrOS netopeer2-server[12937]: Unknown value "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='Controller2']/connection-type/periodic/reconnect_timeout" change.

-Rajib

**Comment by michalvasko** [comment]
Hi Rajib,
this is because the change is not in the code, but in the model that is shipped with *netopeer2*, you are still using the old one. I have told you this before, so again, the easiest way of fixing this is finding you local copy of the model in sysrepo `repository/yang` directory (`ietf-netconf-server`) and change `reconnect-timeout` to `reconnect_timeout`.

Regards,
Michal

**Comment by senrajib** [comment]
Hi Michal

Not sure if i follow you on this. My ietf-netconf-server.yang already contains reconnect_timeout for periodic connections. And sysrepo happily accepts my config and same is reflecting in ietf-netconf-server.running. Am i still missing anything?

-Rajib

**Comment by michalvasko** [comment]
Hi Rajib,
I am sorry, I thought there was no change needed in the code itself, my bad, try again now.

Regards,
Michal
