### ISSUE TITLE
Not able to install netopeer2: Makefile:73: recipe for target 'install' failed

### ISSUE THREAD

**Issue by rgaura** [CESNET/netopeer2#1178]
Hello There

I am facing this subject mentioned error.
I am using Ubuntu Bionic 18.04 LTS Virtual M/c.
Added pre-requisites for all of your modules: cmake, libpcre2, openssl, libssh, cmocka
Added the modules in this order libyang->libnetconf2->sysrepo->netopeer2.
But when I install netopeer2, on make install I gives this:

Install the project...
-- Install configuration: "Debug"
-- Up-to-date: /usr/local/share/yang/modules/netopeer2
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf-monitoring@2010-10-04.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-truststore@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-crypto-types@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-x509-cert-to-name@2014-12-10.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-yang-push@2019-09-09.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-yang-patch@2017-02-22.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/iana-crypt-hash@2014-08-06.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf-nmda@2019-01-07.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tls-common@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tls-server@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf@2013-09-29.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tcp-server@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/nc-notifications@2008-07-14.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-restconf@2017-01-26.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-ip@2018-02-22.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-ssh-server@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf-server@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-interfaces@2018-02-20.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-ssh-common@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tcp-common@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-yang-schema-mount@2019-01-14.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-network-instance@2019-01-21.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf-acm@2018-02-14.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/notifications@2008-07-14.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-datastores@2017-08-17.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-subscribed-notifications@2019-09-09.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tcp-client@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-keystore@2019-07-02.yang
-- Installing: /usr/local/bin/netopeer2-server
-- Set runtime path of "/usr/local/bin/netopeer2-server" to ""
-- Up-to-date: /usr/local/share/man/man8/netopeer2-server.8
-- Installing missing sysrepo modules...
mesg: ttyname failed: Inappropriate ioctl for device
sysrepoctl: /home/ubuntu/netconf/sysrepo/src/plugins/ds_lyb.c:139: srpds_lyb_init: Assertion `!srlyb_file_exists(srpds_name, path)' failed.
[WRN] Recovered a lock with a dead owner (sr_lydmods_conn_ctx_update).
sysrepoctl: /home/ubuntu/netconf/sysrepo/src/plugins/ds_lyb.c:162: srpds_lyb_init: Assertion `!srlyb_file_exists(srpds_name, path)' failed.
/home/ubuntu/netconf/netopeer2/scripts//setup.sh: line 56: 40629 Aborted                 (core dumped) '/usr/local/bin/sysrepoctl' -a -i /usr/local/share/yang/modules/netopeer2/ietf-netconf-acm@2018-02-14.yang -s '/usr/local/share/yang/modules/netopeer2' -p '600' -v2 -o 'root' -g 'root'
CMake Error at cmake_install.cmake:85 (message):
   scripts/setup.sh failed: 134

Makefile:73: recipe for target 'install' failed
make: *** [install] Error 1
root@ubuntu:~/netconf/netopeer2/build#

I followed steps and items as you have shown in github netopeer2 site.
Is it possible to suggest here what went wrong or did I missed any steps.

Thanks
Rajeev
[netop_install2.txt](https://github.com/CESNET/netopeer2/files/8350552/netop_install2.txt)

**Comment by michalvasko** [comment]
What version of `sysrepo` are you using?

**Comment by rgaura** [comment]
Hello Michal
I just took the clone on 27 March from master, also checked with devel branch as well. Both were showing the same output.
The problem is the final make install in netopeer2 performs important stuff, so if this is not successful, its like all the effort goes waste.
And my apologies for writing back after so much time. But if you can answer and suggest, that will be helpful.
Thanks
Rajeev

**Comment by michalvasko** [comment]
Almost certainly you have some invalid/obsolete data present that are causing the problem, you should start by completely removing all the old versions of libraries and data. Also, execute `make sr_clean` for *sysrepo* to reset it. Then try to reinstall everything again.

**Comment by rgaura** [comment]
This works fine now. Thanks

**Comment by rishi-diwaker1** [comment]
i am getting the some error, what did you do to fix it?
even sudo make sr_clean won't solve the problem
