### ISSUE TITLE
why the operation="delete/remove" in xml file is ignored when executing cmd edit-config

### ISSUE THREAD

**Issue by zewei0920** [CESNET/netopeer2#1179]
hello, 
I am using the released version netopeer2-server 2.0.35 and it's depend libs 

my question is as below:

1.  netopeer2-cli command execute successfully when I want to remove or delete a pg：
`edit-config --target running --config=/apps/scripts/del_pg.xml`

```
<pgs xmlns="urn:ccsa:yang:wdm-protection-group">
        <pg operation="delete">
          <pg-id>4</pg-id>
        </pg>
</pgs>
```

or like this:
`edit-config --target running --config=/apps/scripts/remove_pg.xml`
```
<pgs xmlns="urn:ccsa:yang:wdm-protection-group">
        <pg operation="remove">
          <pg-id>4</pg-id>
        </pg>
</pgs>
```

2. but netopeer2-server identify this is a CREATE command ?? 
```
========== EVENT change CHANGES: ====================================

CREATED: /wdm-protection-group:pgs/pg[pg-id='4'] (list instance)
======================== 0 =================
Error [../netconf/hn_protection_group.c],[change_config_data_protection_group_cb],[205]:invalid pg id: 4


 ========== EVENT done CHANGES: ====================================

CREATED: /wdm-protection-group:pgs/pg[pg-id='4'] (list instance)
======================== 0 =================
Error [../netconf/hn_protection_group.c],[change_config_data_protection_group_cb],[205]:invalid pg id: 4
```
3.  So it seems like the operation="" is ignored whatever it is.  

Question:  is there something wrong with my command or script ? 
Could you help ?  Thanks a lot in advance.

**Comment by michalvasko** [comment]
Look at the definition of [`operation`](https://datatracker.ietf.org/doc/html/rfc6241#section-7.2), you are missing its namespace.
