### ISSUE TITLE
While using -U option, /var/run/netopeer2-server.sock file is not getting generated

### ISSUE THREAD

**Issue by ankit7gup** [CESNET/netopeer2#1180]
Hi Michal, 
I am using netopper2 server with -U option, but I can see /var/run/netopeer2-server.sock file is not getting generated thus unable to connect on the unix socket. But as per netopeer2 server logs, it shows listening on the socket.

[INF]: SR: Session 288 (user "root", CID 156) created.
[INF]: LN: Listening on /var/run/netopeer2-server.sock for UNIX connections.

Any suggestions appreciated. Thanks!

**Comment by michalvasko** [comment]
Not sure how to help, it has always worked fine for me. Have you tried changing the path or something? I need to know more about your use-case.

**Comment by ankit7gup** [comment]
I have not checked with changed any path. And using the "root" user to start the process. Only starting the netopeer2-server with mentioned arguments: netopeer2-server -d -v2 -U -t 100.

**Comment by michalvasko** [comment]
I have tried running the server with the same parameters and it seems to be working just fine so I am really not able to help.
