### ISSUE TITLE
Does the server check cert-to-name when establishing a TLS connection?

### ISSUE THREAD

**Issue by Nofun111** [CESNET/netopeer2#1181]
In file `tls_listen.xml`
```XML
<cert-to-name>
    <id>1</id>
    <fingerprint>02:E9:38:1F:F6:8B:62:DE:0A:0B:C5:03:81:A8:03:49:A0:00:7F:8B:F3</fingerprint>
    <map-type xmlns:x509c2n="urn:ietf:params:xml:ns:yang:ietf-x509-cert-to-name">x509c2n:specified</map-type>
    <name>root</name>
</cert-to-name>
```
Does the server check name `root` in client username? No matter what I configure the name to, it can establish the TLS connection normally. It looks like the server doesn't check the name.
```C
    VRB("Cert verify CTN: new client username recognized as \"%s\".", session->username);

    if (server_opts.user_verify_clb && !server_opts.user_verify_clb(session)) {
        VRB("Cert verify: user verify callback revoked authorization.");
        X509_STORE_CTX_set_error(x509_ctx, X509_V_ERR_APPLICATION_VERIFICATION);
        return 0;
    }

    return 1;
```
It looks like `server_opts.user_verify_clb` is NULL.

**Comment by michalvasko** [comment]
> It looks like the server doesn't check the name.

What "name"? I do not understand the question at all. In TLS, the client identifies itself by a certificate and the server needs to assign some username for this client. It does so using the cert-to-name process, which is, in short, looking for a matching fingerprint in the configuration and then deriving the username from the certificate according to the configuration. In this case it is just a fixed username no matter what information is in the certificate.
