### ISSUE TITLE
Connecting  remote netopeer2-client  the connection is getting closed at local netconf session.

### ISSUE THREAD

**Issue by Abrahamma97** [CESNET/netopeer2#1182]
Hi @michalvasko,
I am taking local netconf session and after which when I am using "connect --ssh --host 192.168.4.50 --port 830 --login root" from remote netopeer2-client  the connection is getting closed as local netconf session.

root@localboard:~$ssh root@localhostip -p 830 -s netconf
Interactive SSH Authentication
Type your password:
Password: 
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><capabilities><capability>urn:ietf:params:netconf:base:1.0</capability><capability>urn:ietf:params:netconf:base:1.1</capability><capability>urn:ietf:params:netconf:capability:writable-running:1.0</capability><capability>urn:ietf:params:netconf:capability:candidate:1.0</capability><capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</capability><capability>urn:ietf:params:netconf:capability:validate:1.1</capability><capability>urn:ietf:params:netconf:capability:startup:1.0</capability><capability>urn:ietf:params:netconf:capability:xpath:1.0</capability><capability>urn:ietf:params:netconf:capability:with-defaults:1.0?basic-mode=explicit&amp;also-supported=report-all,report-all-tagged,trim,explicit</capability><capability>urn:ietf:params:netconf:capability:notification:1.0</capability><capability>urn:ietf:params:netconf:capability:interleave:1.0</capability><capability>urn:ietf:params:xml:ns:yang:ietf-yang-metadata?module=ietf-yang-metadata&amp;revision=2016-08-05</capability><capability>urn:ietf:params:xml:ns:yang:1?module=yang&amp;revision=2017-02-20</capability><capability>urn:ietf:params:xml:ns:yang:ietf-inet-types?module=ietf-inet-types&amp;revision=2013-07-15</capability><capability>urn:ietf:params:xml:ns:yang:ietf-yang-types?module=ietf-yang-types&amp;revision=2013-07-15</capability><capability>urn:ietf:params:netconf:capability:yang-library:1.1?revision=2019-01-04&amp;content-id=61</capability><capability>urn:sysrepo:plugind?module=sysrepo-plugind&amp;revision=2020-12-10</capability><capability>urn:ietf:params:xml:ns:yang:ietf-netconf-acm?module=ietf-netconf-acm&amp;revision=2018-02-14</capability><capability>urn:ietf:params:xml:ns:netconf:base:1.0?module=ietf-netconf&amp;revision=2013-09-29&amp;features=writable-running,candidate,rollback-on-error,validate,startup,url,xpath</capability><capability>urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults?module=ietf-netconf-with-defaults&amp;revision=2011-06-01</capability><capability>urn:ietf:params:xml:ns:yang:ietf-netconf-notifications?module=ietf-netconf-notifications&amp;revision=2012-02-06</capability><capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring?module=ietf-netconf-monitoring&amp;revision=2010-10-04</capability><capability>urn:ietf:params:xml:ns:netconf:notification:1.0?module=notifications&amp;revision=2008-07-14</capability><capability>urn:ietf:params:xml:ns:netmod:notification?module=nc-notifications&amp;revision=2008-07-14</capability><capability>urn:ietf:params:xml:ns:yang:ietf-x509-cert-to-name?module=ietf-x509-cert-to-name&amp;revision=2014-12-10</capability><capability>urn:ietf:params:xml:ns:yang:iana-crypt-hash?module=iana-crypt-hash&amp;revision=2014-08-06</capability><capability>urn:notification_history?module=notification_history</capability><capability>urn:ietf:params:xml:ns:yang:iana-if-type?module=iana-if-type&amp;revision=2017-01-19</capability></capabilities><session-id>3</session-id></hello>]]>]]>Connection to 192.168.4.91 closed by remote host.

Can you please let me know the reason why this could be happening?

**Comment by michalvasko** [comment]
Look at the output of `netopeer2-server`. Most likely, it does not get the hello message it expects. It is a really bad idea to try to use `ssh(1)` for NETCONF connections, you need to use a proper NETCONF client such as `netopeer2-cli`.

**Comment by Abrahamma97** [comment]
Hi @michalvasko ,
I am getting the below out 
`[ERR]: LN: Client's <hello> timeout elapsed.`
May I know why it is a really bad idea to try to use ssh(1) for NETCONF connections.

**Comment by michalvasko** [comment]
Because in NETCONF, SSH is just the transport protocol, you communicate using the NETCONF protocol. Sending proper NETCONF messages using a shell that `ssh` provides is almost impossible.

**Comment by marchest** [comment]
Hi @Abrahamma97,

Having same issue while connecting cli. Did you find a solution?

`[ERR]: LN: Client's <hello> timeout elapsed.`

**Comment by Abrahamma97** [comment]
Hi @marchest ,
I second @michalvasko s opinion. Sending proper NETCONF messages using a shell that ssh provides is almost impossible. This should be the reason.

**Comment by marchest** [comment]
Hi @Abrahamma97 ,

Thanks
