### ISSUE TITLE
<get> RPC does not show operational data for some YANG models but it does for others

### ISSUE THREAD

**Issue by avazquezrd** [CESNET/netopeer2#1183]
I have seen that, depending on the used YANG model, NETCONF `<get>` RPC is not procesed by a Sysrepo Plugin that has been previously registered as operational data provider for that model.

I'm using the latest version of Netopeer2 1.x and its dependencies (cannot use 2.x version due to incompatibility with Sysrepo Python bindings):

```
LIBYANG=1.0.240
SYSREPO=1.4.140
LIBSSH=0.9.6
LIBNETCONF2=1.1.46
NETOPEER2=1.1.76
```

To reproduce this, I use these models (and their dependencies):

1. [`ietf-hardware`](https://github.com/YangModels/yang/blob/main/standard/ietf/RFC/iana-hardware%402018-03-13.yang)
2. [`bbf-device-aggregation`](https://github.com/BroadbandForum/yang/blob/master/standard/common/bbf-device-aggregation.yang)

And this is a very simple Python script that can be used as Sysrepo Plugin to see what seems to be failing:
```python
import time
import sysrepo as sr


class SRConnector:
    def __init__(self):
        self.connection = sr.Connection(sr.SR_CONN_DEFAULT)
        self.session = sr.Session(self.connection)
        self.context = self.session.get_context()
        self.sub_state = sr.Subscribe(self.session)

        self.xpaths_state = [
            '/bbf-device-aggregation:devices',
            '/ietf-hardware:hardware'
        ]

        for xpath in self.xpaths_state:
            self.subscribe_state(xpath, self.callback_state)

        print("Subscribed to all XPaths.")

    def subscribe_state(self, xpath: str, callback) -> None:
        self.sub_state.oper_get_items_subscribe(
            xpath.split(':')[0][1:], xpath, callback, xpath,
            sr.SR_SUBSCR_DEFAULT | sr.SR_SUBSCR_CTX_REUSE
        )
        print("Subscribed to operational data in {}".format(xpath))

    # noinspection PyUnusedLocal
    def callback_state(self, session, module: str, xpath: str,
                       request_xpath: str, request_id: int, parent,
                       private_data) -> None:
        print(f"XPATH: {xpath} / REQ_XPATH: {request_xpath}")

        return sr.SR_ERR_OK


if __name__ == '__main__':
    SRConnector()
    while True:
        time.sleep(0.001)
```

As you can see, this plugin is registered as operational data provider for both models and, when a request is processed, the plugin output should show the requested XPath. I have tested this in three different ways, with different results:

1. `sysrepocfg`
2. `netopeer2-cli` + `<get-data>`
3. `netopeer2-cli` + `<get>`

### `sysrepocfg`

In shell:
```
sysrepocfg -X -x /ietf-hardware:hardware -d operational
sysrepocfg -X -x /bbf-device-aggregation:devices -d operational
```

Plugin output:
```
XPATH: /ietf-hardware:hardware / REQ_XPATH: /ietf-hardware:hardware
XPATH: /bbf-device-aggregation:devices / REQ_XPATH: /bbf-device-aggregation:devices
```

In both cases, it works as expected: the plugin processes the requests for both XPaths.

### `netopeer2-cli` + `<get-data>`

In `netopeer2-cli`, after connecting to NETCONF Server:
```
> get-data -d operational --filter-xpath /bbf-device-aggregation:devices
> get-data -d operational --filter-xpath /ietf-hardware:hardware
```

Plugin output:
```
XPATH: /ietf-hardware:hardware / REQ_XPATH: /ietf-hardware:hardware
XPATH: /bbf-device-aggregation:devices / REQ_XPATH: /bbf-device-aggregation:devices
```

In both cases, it works as expected: the plugin processes the requests for both XPaths.

### `netopeer2-cli` + `<get>`

In `netopeer2-cli`, after connecting to NETCONF Server:
```
> get --filter-xpath /ietf-hardware:hardware
> get --filter-xpath /bbf-device-aggregation:devices
```

Plugin output:
```
XPATH: /ietf-hardware:hardware / REQ_XPATH: /ietf-hardware:hardware
```

**Requests for the first model are processed properly, as in previous cases, but the second one, `bbf-device-aggregation:devices` is not working. So, what could be happening here?**

**Comment by michalvasko** [comment]
Too bad you cannot use *sysrepo* v2 because this is fixed there, most likely. In general, you should not be using `<get>` because `<get-data>` is better in every way and that is the only advice I can give you. *netopeer2* v1 is obsolete.

**Comment by avazquezrd** [comment]
Thanks for your answer. I would also like to migrate to v2 but, as mentioned, we depend on sysrepo-python bindings. Regarding the use of `<get-data>` instead of `<get>`, does this mean that `<get>` should be also deprecated and not used any more? I thought that `<get-data>` was more like a flexible version of `<get-config>` where you could just select the specific datastore you want, while `<get>` gives you both running and operational data, right?

**Comment by michalvasko** [comment]
> does this mean that <get> should be also deprecated and not used any more?

Ideally, yes.

> `<get-data>` was more like a flexible version of `<get-config>` where you could just select the specific datastore you want, while `<get>` gives you both running and operational data, right?

With NMDA support, it is not that simple. `<get>` is supposed to return `running` configuration data and `operational` state data. However, there can be different `running` and `operational` data for a configuration node. So, generally, you should be just fine with using `<get-data>` for a specific datastore.

**Comment by avazquezrd** [comment]
Ok, thanks! We will try to do it this way in the client and use v2 as soon as we can.
