### ISSUE TITLE
Pushing data with Session ID

### ISSUE THREAD

**Issue by JoemonChittilapilly** [CESNET/netopeer2#1187]
1. When connecting to multiple NETCONF server can we use session ID in the XML to be pushed to differentiate between different servers? If Yes, How?
2. We are using ncclient as NETCONF client, Should we use different ncclient manager objects for different NETCONF servers and how are they mapped to session IDs?

**Comment by michalvasko** [comment]
No, session ID is defined to be unique for a single NETCONF server. You will have to create some unique session information yourself.

**Comment by JoemonChittilapilly** [comment]
OK, Thank you @michalvasko
