### ISSUE TITLE
RPC related query 

### ISSUE THREAD

**Issue by shikha-jindal** [CESNET/netopeer2#1188]
Hi 

We have three RPC named software-download, software-install and software-activate.
but rpc response is same for all three rpc as follows 
`<status xmlns="urn:o-ran:software-management:1.0">STARTED</status>`

response will be for the RPC which we sent but there can be other scenarios also so Is there any way to figure out that to which RPC this response belongs to??
Please find attached yang for reference. 

[o-ran-software-management.txt](https://github.com/CESNET/netopeer2/files/8450333/o-ran-software-management.txt)

**Comment by jktjkt** [comment]
Surely your NETCONF client knows which operation it has just requested, right?

**Comment by shikha-jindal** [comment]
yes. 

so there is no other way to know which rpc , response belongs to ?/

**Comment by masif-cs** [comment]
Hi @michalvasko 
Actually we have 3 different RPC which has same input and output parameters. Now we want to identify which RPC response is received without checking which RPC we have sent.

Is there any way to identify that? Or is there any way to get the RPC name in the xml output? Like in our case RPC name is software-install
software-download
software-activate

**Comment by michalvasko** [comment]
Look at the [example](https://datatracker.ietf.org/doc/html/rfc6241#section-4.2) in the RFC. The only way to pair RPC with a reply is using `message-id` value, which must be the same.
