### ISSUE TITLE
ietf interfaces admin-status leaf error 

### ISSUE THREAD

**Issue by vishalwc** [CESNET/Netopeer2#119]
Hi ,
we are using devel-server branch  and getting following error on get request 
```
Mar 29 18:43:44 netopeer2-server[22573]: Unknown element "admin-status". (/ietf-interfaces:interfaces-state/interface[name='0.1']/admin-status)
Mar 29 18:43:44 netopeer2-server[22573]: Internal error (Netconf_v2/Netopeer2/server/op_get_config.c:812)
Mar 29 18:43:44 netopeer.sh[22563]: netopeer2-server[22573]: Unknown element "admin-status". (/ietf-interfaces:interfaces-state/interface[name='0.1']/admin-status)
Mar 29 18:43:44 netopeer.sh[22563]: netopeer2-server[22573]: Internal error (Netconf_v2/Netopeer2/server/op_get_config.c:812)
Mar 29 18:43:44 netopeer2-server[22573]: Session 1: thread 1 event new RPC.
Mar 29 18:43:44 netopeer2-server[22573]: Session 1: thread 1 event reply error.
```

Get RPC request 
```xml
<get>
  <filter type="subtree">
    <if:interfaces-state xmlns:enif="http://www.en.com/ns/en-interfaces"
                         xmlns:ip="urn:ietf:params:xml:ns:yang:ietf-ip"
                         xmlns:if="urn:ietf:params:xml:ns:yang:ietf-interfaces"/>
  </filter>
</get>
```
ERROR Reply 
```
error-message xml:lang="en">Internal error (Netconf_v2/Netopeer2/server/op_get_config.c:812)</error-message>
```

**Comment by michalvasko** [comment]
Hi,
the problem will be connected to the `if-feature if-mib` that `admin-status` is dependent on. So, to begin with, please provide the output of `sysrepoctl -l` and also, what application subscribes to `ietf-interfaces` data?

Regards,
Michal

**Comment by vishalwc** [comment]
[DBG] Setting log level for stderr logs to 4.
Sysrepo schema directory: /etc/sysrepo/yang/
Sysrepo data directory:   /etc/sysrepo/data/
(Do not alter contents of these directories manually)
[DBG] Connecting to Sysrepo Engine.
[DBG] Connecting to socket=/var/run/sysrepod.sock
[INF] Connected to daemon Sysrepo Engine at socket=/var/run/sysrepod.sock
[DBG] Sending session-start request.
[DBG] session-start request sent, waiting for response.
[DBG] session-start response received, processing.
[DBG] Sending list-schemas request.
[DBG] list-schemas request sent, waiting for response.
[DBG] list-schemas response received, processing.

Module Name                   | Revision   | Data Owner          | Permissions | Submodules                    | Enabled Features
---------------------------------------------------------------------------------------------------------------------------------
ietf-inet-types               | 2013-07-15 |                     |             |                               |
ietf-yang-types               | 2013-07-15 |                     |             |                               |
ietf-netconf-monitoring       | 2010-10-04 | root:root           | 666         |                               |
ietf-netconf-acm              | 2012-02-22 | root:root           | 666         |                               |
ietf-netconf                  | 2011-06-01 | root:root           | 666         |                               |
ietf-interfaces               | 2014-05-08 | root:root           | 666         |                               |
iana-if-type                  | 2014-05-08 |                     |             |                               |
ietf-netconf-with-defaults    | 2011-06-01 |                     |             |                               |
ietf-system                   | 2014-08-06 | root:root           | 666         |                               |
iana-crypt-hash               | 2014-08-06 |                     |             |                               |
ietf-netconf-server           | 2016-11-02 | root:root           | 666         |                               | listen ssh-listen tls-listen call-home ssh-call-home tls-call-home
ietf-x509-cert-to-name        | 2014-12-10 |                     |             |                               |
ietf-ssh-server               | 2016-11-02 |                     |             |                               |
ietf-keystore                 | 2016-10-31 | root:root           | 666         |                               |
ietf-tls-server               | 2016-11-02 |                     |             |                               |

**Comment by vishalwc** [comment]
yes got it . enabled the if-mib feature and it is working now

**Comment by michalvasko** [comment]
That is good, but what application provides `ietf-interfaces` data, please? Your situation still should not have occurred, there is some inconsistency with the features.

Michal
