### ISSUE TITLE
Documentation needed-Developer Guide ?

### ISSUE THREAD

**Issue by marchest** [CESNET/netopeer2#1192]
Hi all,

Is there any documentation like manual page, developer guide etc? 

Thanks

**Comment by michalvasko** [comment]
Well, yes, there is a manual page that should not be too difficult to find (`doc/netopeer2-server.8`) but you can see everything relevant when you run `netopeer2-server -h`. There is not much to document, this is an implementation of a NETCONF server, which is a standardized protocol and you can learn all about it in its [RFC](https://datatracker.ietf.org/doc/html/rfc6241).

**Comment by marchest** [comment]
Well, i don't call that as documentation but thanks!

**Comment by michalvasko** [comment]
You asked for a manual page or a developer guide, I said there is the former and that the latter is not needed.
