### ISSUE TITLE
 Client <hello> timeout elapsed error.

### ISSUE THREAD

**Issue by marchest** [CESNET/netopeer2#1194]
Hi,

After installation netopeer2 with the following versions im getting client timout elapsed error. I've tried with netopeer cli and MG Browser but no changes.

**netopeer2-server > 2.1.16
libsysrepo > 2.1.42
libyang > v2.0.164
libssh > 0.9.6
libnetconf2 > 2.1.7**

**System:
"Ubuntu 20.04.3 LTS (Focal Fossa)"**

This is MG-SOFT Netconf Browser logs.
![image](https://user-images.githubusercontent.com/13980801/163821049-cffeaf86-59ef-45b7-a3ee-d3bb684afdcd.png)

Netopeer logs are below ,immediately returns time out.

![image](https://user-images.githubusercontent.com/13980801/163821280-f6ac4bff-aa8b-40f9-966a-8c2488afc818.png)

Same error is occuring even if try with netopeer cli. How to exceed this problem?

Thanks in advance.

**Comment by michalvasko** [comment]
I have told you everything I could, I am not able to help more. I still think buggy *libssh* version is the most likely problem and have no more ideas.
