### ISSUE TITLE
Doubt: NACM authorisation unexpected behaviour

### ISSUE THREAD

**Issue by Abrahamma97** [CESNET/netopeer2#1196]
Hi @michalvasko ,
I had a doubt. Consider a yang model with leaf a. Configuration is already present in running configuration with leaf value a= '10''. I have denied write access to the corresponding yang model with same leaf in the nacm rule list. But when I use edit-config rpc and supply the same configuration it can be seen that no nacm access denied error is coming. But if I am changing the value of leaf a to another value and push then the nacm access denied is given. I just wanted  to know if this is expected and why we are not denying nacm write access even if it is same value.

**Comment by jktjkt** [comment]
This is explained in https://datatracker.ietf.org/doc/html/rfc8341#section-3.2.5 .
