### ISSUE TITLE
Creating TLS connection with default certs failing: [ERR]: LN: SSL_accept failed (tlsv1 alert unknown ca).

### ISSUE THREAD

**Issue by rgaura** [CESNET/netopeer2#1197]
Hello Sir

I wanted to make a TLS connection, firstly using the defaults certs present in example_configuration/tls_certs dir.

I tried performing the steps you have mentioned in README:
TLS listen
To support clients connecting using TLS, configuration files tls_keystore.xml, tls_truststore.xml, and tls_listen.xml needs to be merged into sysrepo configuration of modules ietf-keystore, ietf-truststore, and ietf-netconf-server, respectively. After doing so, a NETCONF client can connect using client.crt certificate and client.key private key and having ca.pem CA certificate set as trusted. These example certificates can be found in example_configuration/tls_certs. netopeer2-cli can easily be configured this way and the TLS connection tested.

I have merged all the xmls as suggested by you above.

I am getting this issue while adding ca.pem:
> cert add tls_certs/ca.pem
get_default_trustedCA_dir: Default trusted CA directory does not exist, creating it.
cert add: c_rehash execution failed

I was able to add client cert and key
> cert replaceown tls_certs/client.crt tls_certs/client.key

when I try to connect, it says:
> connect --tls
get_default_CRL_dir: Default CRL dir does not exist, creating it.
nc ERROR: SSL_connect failed (certificate verify failed).
nc ERROR: SSL error (unknown state).
cmd_connect: Connecting to the localhost:6513 failed.

On the server side, it says:

[INF]: SR: Processing "ietf-netconf-server" "done" event with ID 1 priority 0 (remaining 22 subscribers).
[INF]: LN: Listening on 0.0.0.0:6513 for TLS connections.
[INF]: SR: Successful processing of "done" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: LgN: Accepted a connection on 0.0.0.0:6513 from 127.0.0.1:58720.
[INF]: SR: Session 257 (user "root", CID 75) created.
[INF]: SR: Session 258 (user "root", CID 75) created.
[INF]: SR: Session 259 (user "root", CID 75) created.
[ERR]: LN: SSL_accept failed (tlsv1 alert unknown ca).

I am not using any external ca/certs/etc, all from the example setup suggested in README.

Please suggest where I am going wrong.

Thanks
rajeev

**Comment by michalvasko** [comment]
> cert add: c_rehash execution failed

That is the problem. Most likely, you do not have this utility installed, so please do, in some cases it is not part of the stardard `openssl` package. I have also added check for this into the `cmake` list, not sure why it was not there yet.

**Comment by rgaura** [comment]
Hello Michal

Yes, right, installed openssl-perl package and c_rehash got installed. That error is resolved, but still not able to connect:

Server side: 172.31.140.145:

[INF]: SR: No scheduled changes.
[INF]: SR: Connection 101 created.
[INF]: SR: Session 922 (user "root", CID 101) created.
[INF]: SR: Triggering "ietf-subscribed-notifications" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: LN: Listening on 0.0.0.0:830 for SSH connections.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: LN: Listening on 0.0.0.0:6513 for TLS connections.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-keystore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-truststore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: LN: Accepted a connection on 0.0.0.0:6513 from 172.31.140.161:47922.
[INF]: SR: Session 952 (user "root", CID 101) created.
[INF]: SR: Session 953 (user "root", CID 101) created.
[INF]: SR: Session 954 (user "root", CID 101) created.
[ERR]: LN: SSL_accept failed (tlsv1 alert unknown ca).

Client Side:

[root@localhost example_configuration]# netopeer2-cli
> cert display
No certificates found in the default trusted CA directory.
> cert add tls/ca.pem
cert add: Cannot access certificate "tls/ca.pem": No such file or directory
> cert add tls_certs/ca.pem
> cert replaceown tls_certs/client.crt tls_certs/client.key
>
> connect --tls --host 172.31.140.145
nc ERROR: SSL_connect failed (certificate verify failed).
nc ERROR: SSL error (unknown state).
cmd_connect: Connecting to the 172.31.140.145:6513 failed.
>
>
> cert display
-----ca----- serial: 45ce2c8a91ef25294dad0221461662941bd5e11a
Subject: C=CZ, ST=South Moravia, L=Brno, O=CESNET z.s.p.o., OU=TMC, CN=example CA/emailAddress=ca@example.org
Issuer:  C=CZ, ST=South Moravia, L=Brno, O=CESNET z.s.p.o., OU=TMC, CN=example CA/emailAddress=ca@example.org
Valid until: Sep  1 10:21:01 2031 GMT

>
> cert displayown
OK: Using *.crt certificate with a separate private key.
-----CRT----- serial: 47f82c15c5f3457a6d35a7ea427f46e71ca49fc0
Subject: C=CZ, ST=South Moravia, L=Brno, O=CESNET z.s.p.o., OU=TMC, CN=client/emailAddress=client@example.org
Issuer:  C=CZ, ST=South Moravia, L=Brno, O=CESNET z.s.p.o., OU=TMC, CN=example CA/emailAddress=ca@example.org
Valid until: Sep  1 10:28:18 2031 GMT

>

TLS Connection from client (172.31.140.161) ==> server (172.31.140.145)
This time its different systems, not localhost, that is the only change.

Thanks
Rajeev

**Comment by michalvasko** [comment]
> cert add: Cannot access certificate "tls/ca.pem": No such file or directory

This error is definitely not good but I do not understand why it is then displayed. But just to be sure, I would clear the whole CA directory (`~/.netopeer2-cli/certs`) and then try to install the certificates again, without errors. I think the command `cert add` needs an absolute path, did not find time to fix it, so try it that way. After that, try connecting again.
