### ISSUE TITLE
sysrepoctl : misleading error message on deprecated statement

### ISSUE THREAD

**Issue by robbynet** [CESNET/netopeer2#1200]
Hello,
The following command is used to load new version of yang file where several deprecated statements has been added : 
sysrepoctl --verbosity 3  --install o-ran-compression-factors.yang

Leads to following error message returned by sysrepoctl  : 
[ERR] A current definition "compression-formats" is not allowed to reference deprecated definition "compression-formats".

No error detected after human review of statement deprecated added in the yang file compared to RFC7950 (Yang 1.1 DML)
Maybe there are some bad usages of deprecated statement in the yang file ?
But current error message returned by sysrepoctl does not help to understand the root cause, wonder if the error message from sysrepoctl is properly formatted ?
[o-ran-compression-factors.zip](https://github.com/CESNET/netopeer2/files/8546459/o-ran-compression-factors.zip)

netopeer2-server 2.1.2
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.1.1 (SO v7.0.1)

**Comment by michalvasko** [comment]
Yes, it was just a false positive when checking an unused grouping, fixed in `devel`.
