### ISSUE TITLE
Support of feature local-binding-supported

### ISSUE THREAD

**Issue by robbynet** [CESNET/netopeer2#1202]
Hello,
Does Netopeer2 supports feature local-binding-supported from ietf-tcp-client for call-home :
    leaf local-address {
      **if-feature "local-binding-supported";**
      type inet:ip-address;
      description
        "The local IP address/interface (VRF?) to bind to for when
         connecting to the remote peer.  INADDR_ANY ('0.0.0.0') or
         INADDR6_ANY ('0:0:0:0:0:0:0:0' a.k.a. '::') MAY be used to
         explicitly indicate the implicit default, that the server
         can bind to any IPv4 or IPv6 addresses, respectively.";
    }

**Comment by michalvasko** [comment]
No, this feature is not supported.
