### ISSUE TITLE
SSH callhome failing with user other than root

### ISSUE THREAD

**Issue by ankit7gup** [CESNET/netopeer2#1203]
Hi Michal,

I am facing an issue where using libnetconf2 based Netconf client application, I am trying to connect to Netconf server via Callhome over SSH. While Netconf Client application send connect request to netconf server below error is observed.
The mentioned user is present in linux with root privilege and also, the same user is added under the user group for Netconf ACM.
 

[INF]: LN: Successfully connected to 192.168.1.230:4334 over IPv4.
[INF]: SR: Session 749 (user "root", CID 146) created.
[INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: LN: Received an SSH message "request-auth" of subtype "none".
[INF]: LN: Received an SSH message "request-auth" of subtype "password".
[INF]: LN: Failed user "ankit" authentication attempt (#1).
[ERR]: LN: Communication SSH socket unexpectedly closed.
[INF]: LN: Trying to connect via IPv4 to 192.168.1.230:4334.
[INF]: LN: Successfully connected to 192.168.1.230:4334 over IPv4.
[INF]: SR: Session 750 (user "root", CID 146) created.
[INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: LN: Received an SSH message "request-auth" of subtype "none".
[INF]: LN: Received an SSH message "request-auth" of subtype "password".
**[INF]: LN: Failed user "ankit" authentication attempt (#1).
[ERR]: LN: Communication SSH socket unexpectedly closed.**
[INF]: LN: Trying to connect via IPv4 to 192.168.1.230:4334.
[INF]: LN: Successfully connected to 192.168.1.230:4334 over IPv4.
[INF]: SR: Session 751 (user "root", CID 146) created.

Your inputs here will be helpful. Thanks!

**Comment by michalvasko** [comment]
The log simply says that you have tried to authenticate using a password, failed, and then disconnected. Nothing more I can help you with.
