### ISSUE TITLE
The netconf client received a timeout error

### ISSUE THREAD

**Issue by PeterYFPeng** [CESNET/netopeer2#1209]
issue description: 
I used sysrepo APIs to subscribe the module change and the operational data getting action. If the callback functions spend a long time. The netconf client will receive a timeout error.

The sysrepo plugin sbuscription is below: 

rc = **sr_module_change_subscribe**(session, "foxconn-system", "/foxconn-system:fsystem/pm-config", foxconn_system_pmconfig_change_cb, NULL, 0,
            SR_SUBSCR_ENABLED | SR_SUBSCR_DONE_ONLY, &subscription);
rc = **sr_oper_get_items_subscribe**(session, MODULE_NAME, "/foxconn_sync:sync", foxconn_sync_state_cb, NULL, SR_SUBSCR_CTX_REUSE, &subscription);

The timeout time test:
If I do a 3 seconds sleep in the callback function of sr_module_change_subscribe, the timeout error will happen.
If I do a 5 seconds sleep in the callback function of sr_oper_get_items_subscribe, the timeout error will happen.

When I deal with the sr_module_change_subscribe, I use a thread to do my business to prevent the timeout error

The sysrepo has provide a tool named sysrepocfg to read the configuration or data of running, operational, startup datastore.
This tool provides a operation to set the timeout time:
-t, --timeout <seconds>      Set the timeout for the operation, otherwise the default one is used.
Such as:
sysrepocfg --edit=xxx.json -d running -m module_name -t 10

So I have a question about this time, Is there a timeout setting at the netopeer2-server side?

**Comment by michalvasko** [comment]
Should be quite easy to discover on your own, just run `netopeer2-server -h`.

**Comment by PeterYFPeng** [comment]
I am so sorry. I have asked a so stupid question. I've been looking for the answer in the Yang models, but I'm ignoring the functionality of netopeer2-server itself.
