### ISSUE TITLE
netopeer2 server installation failure

### ISSUE THREAD

**Issue by betsyrosemanuel** [CESNET/Netopeer2#121]
Hi,
    Im unable to install the netopeer2 server(devel) and get the following error. I understand that CMocka is optional and could u please tell me why im getting the error. I understand that it has something to do with the keystored 
```
cmake -DCMAKE_INSTALL_PREFIX=//home/mkarthig/repo/mkarthig/5601/sw/vobs/dsl/sw/y/build/netconfdevel/output -DLIBNETCONF2_LIBRARY=//home/mkarthig/repo/mkarthig/5601/sw/vobs/dsl/sw/y/build/netconfdevel/output/lib/libnetconf2.so -DLIBNETCONF2_INCLUDE_DIR=//home/mkarthig/repo/mkarthig/5601/sw/vobs/dsl/sw/y/build/netconfdevel/output/include -DLIBYANG_INCLUDE_DIR=//home/mkarthig/repo/mkarthig/5601/sw/vobs/dsl/sw/y/build/netconfdevel/output/include -DLIBYANG_LIBRARY=//home/mkarthig/repo/mkarthig/5601/sw/vobs/dsl/sw/y/build/netconfdevel/output/lib/libyang.so -DSYSREPO_INCLUDE_DIR=//home/mkarthig/repo/mkarthig/5601/sw/vobs/dsl/sw/y/build/netconfdevel/output/include -DSYSREPO_LIBRARY=//home/mkarthig/repo/mkarthig/5601/sw/vobs/dsl/sw/y/build/netconfdevel/output/lib/libsysrepo.so ..
-- The C compiler identification is GNU 4.7.0
-- Check for working C compiler: /home/mkarthig/repo/mkarthig/5601/sw/vobs/esam/build/reborn/buildroot-isam-reborn-cavium-srntd/output/host/usr/bin/mips64-octeon-linux-gnu-gcc
-- Check for working C compiler: /home/mkarthig/repo/mkarthig/5601/sw/vobs/esam/build/reborn/buildroot-isam-reborn-cavium-srntd/output/host/usr/bin/mips64-octeon-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /bin/pkg-config (found version "0.27.1") 
-- Failed to learn keystored keys directory, rerun cmake and set KEYSTORED_KEYS_DIR manually or the server configuration will not work.
-- Server configuration off, default SSH host key will be used.
-- Default host key set to "/etc/ssh/ssh_host_rsa_key".
CMake Error at CMakeLists.txt:77 (string):
  string sub-command STRIP requires two arguments.


-- libnetconf2 was compiled with support of up to  threads
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for NC_ENABLED_SSH
-- Looking for NC_ENABLED_SSH - found
-- Looking for NC_ENABLED_TLS
-- Looking for NC_ENABLED_TLS - found
-- Found sysrepo: //home/mkarthig/repo/mkarthig/5601/sw/vobs/dsl/sw/y/build/netconfdevel/output/lib/libsysrepo.so  
-- Could NOT find CMocka (missing:  CMOCKA_LIBRARIES CMOCKA_INCLUDE_DIR) (Required is at least version "1.0.0")
-- Configuring incomplete, errors occurred!
See also "/home/mkarthig/repo/mkarthig/5601/sw/y/build/netconfdevel/Netopeer2-devel-server/server/build/CMakeFiles/CMakeOutput.log".
See also "/home/mkarthig/repo/mkarthig/5601/sw/y/build/netconfdevel/Netopeer2-devel-server/server/build/CMakeFiles/CMakeError.log".
```

**Comment by michalvasko** [comment]
Hi,
CMocka is optional, so I am not sure why configuring failed, probably because of the invalid command on the line 77. I think I have fixed that, so please pull *netopeer2* and run `cmake` again. Regarding *keystored*, please look into `/netopeer2/server/configuration/README.md`. If you don't care about configuration, everything is fine.

Regards,
Michal

**Comment by betsyrosemanuel** [comment]
hi, 
   I tried building the netopeer2 server again and got the same error message. 
-- The C compiler identification is GNU 4.7.0
-- Check for working C compiler: /home/mkarthig/repo/mkarthig/5601/sw/vobs/esam/build/reborn/buildroot-isam-reborn-cavium-srntd/output/host/usr/bin/mips64-octeon-linux-gnu-gcc
-- Check for working C compiler: /home/mkarthig/repo/mkarthig/5601/sw/vobs/esam/build/reborn/buildroot-isam-reborn-cavium-srntd/output/host/usr/bin/mips64-octeon-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /bin/pkg-config (found version "0.27.1") 
-- Failed to learn keystored keys directory, rerun cmake and set KEYSTORED_KEYS_DIR manually or the server configuration will not work.
-- Server configuration off, default SSH host key will be used.
-- Default host key set to "/etc/ssh/ssh_host_rsa_key".
CMake Error at CMakeLists.txt:77 (string):
  string sub-command STRIP requires two arguments.


-- libnetconf2 was compiled with support of up to  threads
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for NC_ENABLED_SSH
-- Looking for NC_ENABLED_SSH - found
-- Looking for NC_ENABLED_TLS
-- Looking for NC_ENABLED_TLS - found
-- Found sysrepo: //home/mkarthig/repo/mkarthig/5601/sw/vobs/dsl/sw/y/build/netconfdevel/output/lib/libsysrepo.so  
-- Could NOT find CMocka (missing:  CMOCKA_LIBRARIES CMOCKA_INCLUDE_DIR) (Required is at least version "1.0.0")
-- Configuring incomplete, errors occurred!
See also "/home/mkarthig/repo/mkarthig/5601/sw/y/build/netconfdevel/Netopeer2-devel-server/server/build/CMakeFiles/CMakeOutput.log".
See also "/home/mkarthig/repo/mkarthig/5601/sw/y/build/netconfdevel/Netopeer2-devel-server/server/build/CMakeFiles/CMakeError.log".

**Comment by fabioantonini** [comment]
Hi

I faced the same problem in my environment. I have fixed the problem 
passing the following option to the cmake command

-DCMOCKA_ROOT_DIR:PATH=$CROSS_PATH/../tiesse/src/netopeer2/cmocka-1.1.0/ 
-DCMOCKA_LIBRARY:FILEPATH=$CROSS_PATH/../tiesse/src/netopeer2/cmocka-1.1.0/build/src/libcmocka.so

Of course in your case the paths must reflect your environment

regards

fabio

**Comment by michalvasko** [comment]
@betsyrosemanuel You are getting the same error because you did not properly update *netopeer2* (just look at the line 77 in `CMakeLists.txt`, there is something different now). So please, try in the `build` directory:
```
git pull
rm CMakeCache.txt
cmake ..
```

@fabioantonini CMocka is optional, so it has nothing to do with the configure fail and that is what we are solving now.

Regards,
Michal

**Comment by betsyrosemanuel** [comment]
@michalvasko It worked...
Thanks
