### ISSUE TITLE
unknown np2 server option

### ISSUE THREAD

**Issue by fchn289** [CESNET/netopeer2#1210]
hi,

![image](https://user-images.githubusercontent.com/100677967/167240839-29cfb87c-af4f-4a46-9619-ca358eb9c276.png)

is "-f" supported? above code is in tests/np_test.c

btw, "-v3" is also not supported, the max is "-v2", right?

**Comment by michalvasko** [comment]
Yes, `-f` is supported, look at `netopeer2-server -h`. And `-v3` seems to be unsupported verbosity but it is normalized to `-v2` so it makes no difference.

**Comment by fchn289** [comment]
ah, yes, "-f" supported in latest code.
