### ISSUE TITLE
Hooks to know status of netconf clients with netopeer2-server application

### ISSUE THREAD

**Issue by palyogendra** [CESNET/netopeer2#1211]
Hi,

My requirement: I am writing an foobar application which can hook to netopeer2-server application to know status of netconf clients. Essentially, whenever a netconf client connects with netopeer2-server, netopeer2-server should let the foobar application know about it and similarly on the disconnect of netconf client with netopeer2-server.

Any thoughts on above or how to go about it ?

Best Regards, Yogen

**Comment by michalvasko** [comment]
You can subscribe to `ietf-netconf-notifications:netconf-session-start` and `ietf-netconf-notifications:netconf-session-end` notifications, respectively.

**Comment by palyogendra** [comment]
Cool. Let me try out. Appreciate your quick reply Michal

**Comment by palyogendra** [comment]
I could verify this and it helped in. Closing this ticket.
