### ISSUE TITLE
There are no matching subscribers for RPC/action "/o-ran-usermgmt:chg-password".

### ISSUE THREAD

**Issue by pkolla09** [CESNET/netopeer2#1212]
Hi i am new here,please guide me where i went wrong.
When i am trying use  user-rpc --content /home/wifi/Netconf/Mplane-dev/o-ran-usermgmt_rpc.xml. I am getting an error in netopeer2-cli as
There are no matching subscribers for RPC/action "/o-ran-usermgmt:chg-password".
![usrmngmt](https://user-images.githubusercontent.com/105207246/167387231-ae2141a8-84a6-4274-ac2b-42657daec4dc.png)

**Comment by michalvasko** [comment]
You did not do anything particularly wrong. You have tried to execute the RPC `/o-ran-usermgmt:chg-password` that should run the specific Remote Procedure Call on the server. However, there is no subscription that would actually execute the RPC so it fails, naturally. You can use `sysrepo/examples/rpc_subscribe_example /o-ran-usermgmt:chg-password` to create a simple subscription that will simply print the RPC it receives.

**Comment by pkolla09** [comment]
Hi , i have run 
root@wifi-KU55x:/home/wifi/Netconf/sysrepo-master/sysrepo-master/build/examples# ./rpc_subscribe_example /o-ran-usermgmt:chg-password
and run 
user-rpc --content /home/wifi/Netconf/Mplane-dev/o-ran-usermgmt_rpc.xml at netopeer2 cli side
![chngpass](https://user-images.githubusercontent.com/105207246/167394359-eb6a25fc-019d-464d-a124-0a3aabe8ee7a.png)

![cli_usrmgmt](https://user-images.githubusercontent.com/105207246/167394363-96d9f3e9-643d-4753-ab31-c68af3ff34c5.png)
I got error at client side but rpc got received where i ran ./rpc_subscribe_example .please go through the attachments and help me to understand what is happening

**Comment by pkolla09** [comment]
Hi, can you suggest me how to add output of rpc.
 If i am adding directly the output node "status" in to the xml, it throws an error Invalid opaque node "status" found
else it throws an error Mandatory node "status" instance does not exist.
![output](https://user-images.githubusercontent.com/105207246/167401341-35a58f13-4717-4507-9328-6149a6bc7e38.png)

**Comment by michalvasko** [comment]
Look, you really should try to learn more about 1.) [YANG](https://www.rfc-editor.org/rfc/rfc7950.html) and 2.) [NETCONF](https://datatracker.ietf.org/doc/html/rfc6241). Then, read through [sysrepo docs](https://netopeer.liberouter.org/doc/sysrepo/master/html/). And then try to actually use *sysrepo*/*netopeer2*. Otherwise you will keep having these basic problems.

**Comment by pkolla09** [comment]
Thank you it really helped and i solved my issue.
