### ISSUE TITLE
ABOUT SUDO PRIVILEGE

### ISSUE THREAD

**Issue by PriyaSharma30** [CESNET/netopeer2#1214]
Hi
Acc. to ORAN-WG4.MP.0-v02.00.00.pdf for file_mgmt, trace , troubleshooting have execute permission (X).
![image](https://user-images.githubusercontent.com/96615773/168040899-0631ca82-018e-4669-92d8-7591f03f730b.png)

My question is that in any group if any yang module {example file_mgmt} have only execute permission instead of RWX  then in that case for that group the file_mgmt notification are coming or not?

![image](https://user-images.githubusercontent.com/96615773/168042656-abe2b51d-a2a8-4348-ad07-bf3335de91ad.png)

![image](https://user-images.githubusercontent.com/96615773/168042774-dbd0dfe1-ff1b-4551-ae68-00548993a258.png)

**Comment by michalvasko** [comment]
It is difficult to understand what exactly is your question. What permissions are exactly in the first table? What is `sudo`, `nms`, or `fm-pm`? Seems like something o-ran-specific so you will have to formulate the question limiting yourself to the functionality of *sysrepo*/*netopeer2*.

**Comment by PriyaSharma30** [comment]
Hi @michalvasko 
If some notification  is coming from netopeer-server side for specific rpc does it required to have that RPC  RWX permission to retrieve the notification?

**Comment by michalvasko** [comment]
You do not understand, what is "RWX permission"? The only permissions I can think of are those printed by `sysrepoctl -l` or NACM one, so what are you talking about?

**Comment by PriyaSharma30** [comment]
Yes, I'm asking about NACM.

**Comment by michalvasko** [comment]
Then you just have to read the RFC to learn everything relevant. [This](https://datatracker.ietf.org/doc/html/rfc8341#section-3.4.6) is the section about notifications.

**Comment by PriyaSharma30** [comment]
Thanks a lot for the clarification.
