### ISSUE TITLE
ietf-tls-client and ietf-tls-server versions

### ISSUE THREAD

**Issue by gabilm** [CESNET/netopeer2#1215]
Hi.

Current versions of netopeer2 are based on TLS models from 2019 (https://datatracker.ietf.org/doc/html/draft-ietf-netconf-tls-client-server-14). 

We need to update the TLS models (client, server and common) to newer versions (for example https://datatracker.ietf.org/doc/draft-ietf-netconf-tls-client-server/27/) to deploy new applications making use of them. 

Directly change the models doesn't work, because other main models (such as ietf-netconf-server) depend on them.

So, is there any version of netopeer2 based on newer TLS models (not necessarely the lastest)?
Could it be possible to update them in some way without breaking the system?

Thanks in advance.

Best regards, Gabi.

**Comment by michalvasko** [comment]
> So, is there any version of netopeer2 based on newer TLS models (not necessarely the lastest)?
Could it be possible to update them in some way without breaking the system?

There is no other version except for the current one and I do not think you can update them without breaking TLS support of *netopeer2*. We are waiting for all these modules to finally be released as RFCs when we want to update them. As no one knows when that is going to happen and we got tired or periodically updating the modules only to be updated later, we are stuck with the current ones.

**Comment by gabilm** [comment]
Ok, I understand. 

Thank you for you quick response.

Best regards, Gabi.
