### ISSUE TITLE
Query on netopeer2 dependency for c_reshash

### ISSUE THREAD

**Issue by meghna-doshi** [CESNET/netopeer2#1216]
Hi,
We took latest code from devel branch of netopeer2 on May 12th 2022 and found one new dependency added in **cli/CMakeLists.txt**

```
find_program(C_REHASH c_rehash)
    if(NOT C_REHASH)
        message(FATAL_ERROR "c_rehash Perl OpenSSL script not found!")
    endif()
```

What is this dependency for and what if we comment out this part, does it create any issue?

**Comment by michalvasko** [comment]
Its is required for OpenSSL to read trusted CA certificates. So, if you do not use TLS in CLI, you do not need it, otherwise you most definitely do.

**Comment by meghna-doshi** [comment]
Hi Michal,
We already have openssl installed on the server, how to get this c_rehash utility?

**Comment by michalvasko** [comment]
It depends on the distribution you are on but it will almost certainly be part of a standard package. If it is not in the `openssl` package, it can be `openssl-perl`, for example.
