### ISSUE TITLE
When setting SCRIPT_DIR, DESTDIR is not taken into account

### ISSUE THREAD

**Issue by hthiery** [CESNET/netopeer2#1217]
Since update to netopeer2 2.1.23 the setup.sh script does not work any longer if netopeer2 is installed with:

 `make DESTDIR=<CUSTOM-DEST-DIR-PREFIX> install`.

This sets SCRIPT_DIR to value without DESTDIR:
`set(SCRIPT_DIR "${CMAKE_INSTALL_PREFIX}/share/netopeer2" CACHE STRING "Directory where to copy the install scripts to")`

e.g.` /usr/share/netopeer2/setup.sh`

`install(DIRECTORY "${PROJECT_SOURCE_DIR}/scripts/" DESTINATION ${SCRIPT_DIR} USE_SOURCE_PERMISSIONS)`
While this will install the file to: `<CUSTOM-DEST-DIR-PREFIX>/usr/share/netopeer2/setup.sh`

and the script is later called from the installation path (without the DESTDIR prefix):
`/usr/share/netopeer2/setup.sh`

This was observed while updating the netopeer2 package in buildroot.

**Comment by michalvasko** [comment]
Right, based on my testing it seems to work now.
