### ISSUE TITLE
How to deny a user's ssh login?

### ISSUE THREAD

**Issue by Nofun111** [CESNET/netopeer2#1218]
In netopeer2-cli, we can generally connect to netopeer2-server by specifying the user name through the command `connect --login <username>` or `listen --login <username>`.
In netopeer2-server, can I deny a user's ssh login?

**Comment by michalvasko** [comment]
No, *netopeer2-server* currently directly uses system user configuration.

**Comment by Nofun111** [comment]
Thank you very much for your quick reply
