### ISSUE TITLE
why rpc-get via local socket return empty rpc-reply

### ISSUE THREAD

**Issue by fchn289** [CESNET/netopeer2#1220]
hi,

seems np2srv_rpc_get_cb() is not callback when rpc-get recieved.

BR

**Comment by michalvasko** [comment]
Can you provide more details? What is the output of the server? What version of *netopeer2* are you using?

**Comment by fchn289** [comment]
Thank you for reply,

[DBG]: Session 1: sending message:
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="26"><get-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><source><running/></source><filter type="subtree"><examples xmlns="urn:examples"></examples></filter></get-config></rpc>

[DBG]: Session 1: received message:
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="26"><data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"></data></rpc-reply>


===
version = netopeer2-1.1.70

**Comment by fchn289** [comment]
> hi,
> 
> seems np2srv_rpc_get_cb() is not callback when rpc-get recieved.
> 
> BR

np2srv_rpc_get_cb() is called, I found it by replacing logging via fprintf(stderr,...). however, the reply is still empty.

**Comment by michalvasko** [comment]
Even though you are using the old version, I do not think there is any bug. Do you actually have any `running` configuration set, does `sysrepocfg -X` print anything?

**Comment by fchn289** [comment]
sysrepocfg -X print nothing

**Comment by fchn289** [comment]
is above rpc get-config correct? since netopeer2-server print this:

libyang[1]: Schema node "examples:examples" not found (/examples:examples) with context node "/examples:cont".

**Comment by michalvasko** [comment]
Based on all this information you should know what the problem is. There is no `examples` top-level node, only `cont`.

**Comment by fchn289** [comment]
yes, should nc_rpc_getconfig(...,![image](https://user-images.githubusercontent.com/100677967/169501944-d81a9c20-6c4b-4403-835b-58a625cf080d.png),...) instead of 
![image](https://user-images.githubusercontent.com/100677967/169502034-0abd8952-0f9a-479a-8b9e-7e4e93491c6c.png)

**Comment by michalvasko** [comment]
Right, that should work.

**Comment by fchn289** [comment]
![image](https://user-images.githubusercontent.com/100677967/169502899-114e87ed-e11b-46d4-8d83-fc5041ec7eb3.png)

then how nc_rpc_get() all?

**Comment by michalvasko** [comment]
No reason why I should repeat the specification, just read about [`get-config`](https://datatracker.ietf.org/doc/html/rfc6241#section-7.1) and you should learn everything you need to.

**Comment by fchn289** [comment]
ok, thank you for help
