### ISSUE TITLE
new feature: can netopeer server official support non-root user?

### ISSUE THREAD

**Issue by fchn289** [CESNET/netopeer2#1222]
if so, I may contribute as I practiced recently on netopeer2-1.1.70.

**Comment by michalvasko** [comment]
Feel free to contribute however you want, I will decide what to do with your changes once I see them.

**Comment by fchn289** [comment]
in https://github.com/CESNET/netopeer2/issues/747 you replied:

> Okay, this is odd but I have just tried it and I got refused by NACM no matter what I did.

is this issue fixed in latest load? or we still have to use -DNACM_RECOVERY_UID to workaround?

**Comment by michalvasko** [comment]
What issue would that be? You cannot write into NACM with any user just like that, it would defeat its purpose.

**Comment by fchn289** [comment]
when non-root running netopeer2 server under netopeer2-1.1.70, the client got access-denied in rpc-reply. I referred to https://github.com/CESNET/netopeer2/issues/747 & workaround by -DNACM_RECOVERY_UID.

Now if officially support non-root, we need to correctly configure NACM rather than workaround. what's your opinion?

**Comment by michalvasko** [comment]
Configuring NACM recovery user is not a workaround. It is one way of bypassing the NACM, which occurs for `root`, by default. Proper solution is configuring NACM itself so that the desired users have access to the specific data they should have access to. When doing this with `sysrepocfg`, NACM itself is not being applied, which simplifies things, but you need to have *sysrepo* access to the data instead with the specific system user. That is, by default, granted only to the user creating the first *sysrepo* connection. On a fresh system, this occurs when installing *netopeer2*, so that user is `root`.

**Comment by fchn289** [comment]
OK. then this is step-by-step (succ under netopeer2-1.1.70):

export NP2_MODULE_PERMS=600
export NP2_MODULE_DIR=my/etc/netopeer2/modules/
SYSREPO_REPOSITORY_PATH=my/repository/
SYSREPO_SHM_PREFIX=my_prefix
export SYSREPOCTL_EXECUTABLE=my/sysrepoctl
export LIBYANG_USER_TYPES_PLUGINS_DIR=my/usr/lib/libyang1/user_types
export LIBYANG_EXTENSIONS_PLUGINS_DIR=my/usr/lib/libyang1/extensions
my/netopeer2/script/setup.sh //if not install server yang modules
rebuild netopeer2 (mkdir build; cd build; cmake -DNACM_RECOVERY_UID=my non-root uid ..; make; make install
run (./netopeer2-server -d -v2 -p./netopeer2-server.pid -t10 -U./t1_sock)

**Comment by michalvasko** [comment]
Sorry, I have noticed only now that you are still using *netopeer2* v1. That is obsolete and I do not see the point of your contribution.

**Comment by fchn289** [comment]
I assume same/similar steps should be ok for latest load (you can comment). Then no code change, I have complete my contribution. If these steps are valuable in README, better

**Comment by michalvasko** [comment]
README could perhaps have a section about this but your steps would need some improvements before they could be published. So I would leave it as it is.

**Comment by fchn289** [comment]
whenever README is updated, please can you let me know? I want to learn the official/complete solution. Thank you.

**Comment by michalvasko** [comment]
I have nothing like that planned because running the server as non-root is possible almost by chance, but not really intended. For one, you cannot bind to the official NETCONF SSH port 830 unless you are `root`, so the whole solution should generally be avoided, which is why there is no official information.

**Comment by fchn289** [comment]
local socket can avoid port=830 issue

**Comment by michalvasko** [comment]
Yes, but I would consider such a server not to have all its functionality, if you cannot even connect remotely. I have told you everything, I will not be writing any such section into the README. If you (or someone else) will and the quality will be sufficient, I will merge it.

**Comment by fchn289** [comment]
how about this:

## Non-root privilege

Officially, netopeer2 server requires root privilege. However, non-root is also attractive in many cases, eg CI test, multi-np2-server on same machine by different users. Here's a way to run without root-privilege:

1. export NP2_MODULE_PERMS=600
2. export NP2_MODULE_DIR=`my`/etc/netopeer2/modules/
3. export SYSREPO_REPOSITORY_PATH=`my`/repository/
4. export SYSREPO_SHM_PREFIX=my_prefix
5. export SYSREPOCTL_EXECUTABLE=`my`/sysrepoctl
6. export LIBYANG_USER_TYPES_PLUGINS_DIR=`my`/usr/lib/libyang1/user_types
7. export LIBYANG_EXTENSIONS_PLUGINS_DIR=`my`/usr/lib/libyang1/extensions
8. `my`/netopeer2/script/setup.sh **//if not install server yang modules**
9. mkdir build; cd build; cmake -DNACM_RECOVERY_UID=`my non-root uid` ..; make; make install **//rebuild netopeer2 for non-root uid**
10. ./netopeer2-server -d -v2 -p./netopeer2-server.pid -t10 -U./t1_sock **//non-root running**

Note:
- since used local socket, SSH related functionality is not available

**Comment by michalvasko** [comment]
Sorry, but the quality of this section is quite poor. Many of the environment variables are redundant, they have no explanation whatsoever, and you even have some *libyang* v1 variables set meaning this is still for v1 of the projects, which are deprecated. For these reasons, I cannot accept it in this form.
