### ISSUE TITLE
Commit failed 

### ISSUE THREAD

**Issue by grinbergzvika** [CESNET/netopeer2#1223]
Hi,
Please Advise,
I'm trying to commit to updating the RUNNING
1) I perform edit-config for the variable in candidate - success
2) Operate validate - success
3) Commit. - falied
I expect to get the value updated in running
(If I do copy-config it success to copy candidate --> running)

I get the following line in the CLI

"[ERR]: Unknown element" sysrepo-modules ". (Path: / sysrepo: sysrepo-modules)"

Zvika

**Comment by michalvasko** [comment]
What *sysrepo*/*netopeer2* version are you using? This seems like a bug I have fixed a long time ago.

**Comment by grinbergzvika** [comment]
Hi, 
I am using an old version, I should upgrade in the near future, if there is a commit number of the fixed bug? that I can look.
Sysrepo (1.4.70)
Libyang (1.10.184)
Netopeer(1.1.39)

Thanks,
Zvika.

**Comment by michalvasko** [comment]
I do not know, just try the latest release and you will see whether it works or not.
