### ISSUE TITLE
Connect failed at second time

### ISSUE THREAD

**Issue by helijia21** [CESNET/netopeer2#1225]
Run netopeer2-server -d and work well.
Once the client disconnected, next time (the same client), i get a refused ..
and i found that just run the script  sh /usr/local/share/netopeer2/merge_config.sh   then  the client can connnect to the server again.
Any everytime the client get a message about remember  a key?

I just want only ssh password every time.

**Comment by michalvasko** [comment]
Run the server as `netopeer2-server -d -v2` and provide the output, if it does not help you discover the problem. You should be able to reconnect as many times as you want.

**Comment by helijia21** [comment]
use netconf server xml like that

<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <listen>
    <endpoint>
      <name>default-ssh</name>
      <ssh>
        <tcp-server-parameters>
          <local-address>0.0.0.0</local-address>
          <keepalives>
            <idle-time>1</idle-time>
            <max-probes>10</max-probes>
            <probe-interval>5</probe-interval>
          </keepalives>
        </tcp-server-parameters>
        <ssh-server-parameters>
          <server-identity>
            <host-key>
              <name>default-key</name>
              <public-key>
                <keystore-reference>genkey</keystore-reference>
              </public-key>
            </host-key>
          </server-identity>
          <client-authentication>
            <supported-authentication-methods>
              <passsword/>
              <other>interactive</other>
            </supported-authentication-methods>
          </client-authentication>
        </ssh-server-parameters>
      </ssh>
    </endpoint>
  </listen>
</netconf-server>

notice that in the <supported-authentication-methods> , remove the <public-key> leaf .
then run  sysrepocfg -m this.xml and restart netopeer2-server.
