### ISSUE TITLE
Attribute name is missing in xml but in error-tag it through an error of unknown element.

### ISSUE THREAD

**Issue by vaibhav1713109** [CESNET/netopeer2#1226]
1. Attribute name is missing in xml but in error-tag it through an error of unknown element.
> edit-config --target running --config --defop replace

		Replace with below xml

```xml
<port-transceivers>
    <port-transceiver-data>
      <interface-name>eth0.100</interface-name>
      <port-number>0</port-number>
      <name>ru-port0</name>
    </port-transceiver-data>
</port-transceivers>
```

		Error-tag 

```
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	path:     /
	message:  Unknown element "port-transceivers".
```

2. If we change the type of any leaf in xml netopeer-server through invalid-value instead of bad-element.
> edit-config --target running --config --defop merge

		Replace with below xml

```xml
<sync xmlns="urn:o-ran:sync:1.0">
 <ptp-config>
 <domain-number>24</domain-number>
 <accepted-clock-classes>
 <clock-classes>true</clock-classes>
 </accepted-clock-classes>
 <ptp-profile>G_8275_1</ptp-profile>
 <g-8275-1-config>
 <multicast-mac-address>FORWARDABLE</multicast-mac-address>
 <delay-asymmetry>0</delay-asymmetry>
 </g-8275-1-config>
 </ptp-config>
 <ptp-status>
 <reporting-period>10</reporting-period>
 </ptp-status>
 <synce-config>
 <acceptance-list-of-ssm>PRC</acceptance-list-of-ssm>
 <acceptance-list-of-ssm>EEC1</acceptance-list-of-ssm>
 <ssm-timeout>10</ssm-timeout>
 </synce-config>
 <synce-status>
 <reporting-period>10</reporting-period>
 </synce-status>
</sync>

```

		Error-tag 

```
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	path:     /o-ran-sync:sync/ptp-config/accepted-clock-classes[clock-classes='true']/clock-classes
	message:  Invalid value "true" in "clock-classes" element.
```
3. If we delete a node which is not exist netopeer-server should through data-missing error.
> user-rpc 

		Replace with below xml

```xml
<edit-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
 <target>
   <running/>
 </target>
 <config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
	<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces" xc:operation="delete">
		     <interface>
		       <name>eth1.130</name>
		     </interface>
	</interfaces>
 </config>
</edit-config>

```

		Error Tag

```
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	message:  Node "interface" to be deleted does not exist.
```

**Comment by Abrahamma97** [comment]
@michalvasko  I have the same doubt, can you clarify on this?

**Comment by michalvasko** [comment]
It took me a while because I have also added a new test and now the server should return all the errors specified in the YANG and NETCONF RFCs. Meaning your use-case 3. should be covered. As for 1. and 2., please reference the text that specifies these errors should be returned, otherwise they are implementation-dependent and hence fine the way they are.

**Comment by Abrahamma97** [comment]
Ok Thanks for clarifying it.

**Comment by vaibhav1713109** [comment]
Hi @michalvasko 

1.I want to trigger bad-element but when i give wrong type, out of range and pattern mismatch, invalid value is triggered
error-tag:      bad-element
   error-type:     protocol, application
   error-severity: error
   error-info:     <bad-element> : name of the element w/ bad value
   Description:    An element value is not correct; e.g., wrong type,
                   out of range, pattern mismatch.

2. Want to trigger bad-element but when i remove a attribute form a yang it through an unknown element error.
error-tag:      missing-attribute
   error-type:     rpc, protocol, application
   error-severity: error
   error-info:     <bad-attribute> : name of the missing attribute
                   <bad-element> : name of the element that is supposed
                     to contain the missing attribute
   Description:    An expected attribute is missing.

**can you please explain me i didn't get the above error and how can i trigger the above errors???**

**Comment by michalvasko** [comment]
Okay, I have added generating of these few errors, try it now.
