### ISSUE TITLE
LN: Session 5: Failed to write reply (would block)

### ISSUE THREAD

**Issue by meghna-doshi** [CESNET/netopeer2#1228]
Hi,
Logs attached, it has logs for sometime before issue happened, in case that helps.
Summary from logs:

1. here our proprietary netconf client tried create subscription but below error is seen in logs :

`2022-06-02T18:11:37.534845011Z netopeer2-server|ERROR "netopeer2-server-log" [ERR]: LN: Session 5: Failed to write reply (would block)`

2. Then the client tried again subscription but this time netopeer2-server returned error saying already subscribed. 

```
2022-06-02T18:18:06.697028232Z netopeer2-server|ERROR "netopeer2-server-log" [ERR]: SR: Session already subscribed.
2022-06-02T18:18:06.697105358Z netopeer2-server|ERROR "netopeer2-server-log" [ERR]: SR: User callback failed.
2022-06-02T18:18:06.697123374Z netopeer2-server|ERROR "netopeer2-server-log" [ERR]: NP: Failed to send an RPC (User callback failed).
```

1. From code and other issues reported on similar problem appears like the rpc response couldnt process in 10 seconds (which is default timeout) but if you see the timestamp of the logs, we dont see 10 second difference from the time "subscription" was received and this error message (would block) was returned.
2. Also if say due to some error, failure happened (would block error) then atleast the next time subscribe call should have succeeded instead of saying session already subscribed.

Can you please help us figure out what really went wrong in the system and if there is any fix for this issue. We are not able to reproduce it so we are not clear which case this issue is happening. We have only one netconf client session active(as you can see in logs also)

NP2SRV_VERSION 2.1.10
[netopeer-log.txt](https://github.com/CESNET/netopeer2/files/8828336/netopeer-log.txt)

**Comment by michalvasko** [comment]
The default poll timeout is 10 milliseconds, not seconds. It seems fairly small but it is just for writing data on a socket so it should be sufficient. You can try to increase the timeout by `cmake -DPOLL_IO_TIMEOUT=1000 ..` to 1 s and check whether the problem is solved.
