### ISSUE TITLE
How to create/delete new ssh user as programmatically?

### ISSUE THREAD

**Issue by marchest** [CESNET/netopeer2#1229]
Hi,

I am trying to make user operations programmatically such as changing ssh password or create/delete user operations. Is there any api to achive such operations.?

Thanks,

**Comment by michalvasko** [comment]
*netopeer2-server* uses the standard system users for SSH authentication (for now) so you will have to modify those.

**Comment by marchest** [comment]
Hi @michalvasko ,

Thanks for the quick response.
