### ISSUE TITLE
Netopeer2 daemon comes up ,due to Notifcation changes, causes sysrepo crash  

### ISSUE THREAD

**Issue by vishalwc** [CESNET/Netopeer2#123]
Hi Michal
we Updated to sysrepo/devel to 2e5fd2a..578698f

Netopeer Init logs ( looks like netconf-server endpoints get request fails ) 
 
netopeer2-server[24170]: (cl_message_recv:211) Sysrepo server disconnected.
netopeer2-server[24170]: (cl_request_process:449) Unable to receive the message with response (session id=1326882673, operation=get-items).
  **netopeer2-server[24170]: (sr_get_items_iter:1030) Sending get_items request failed '/ietf-netconf-server:netconf-server/listen/endpoint[ssh]//*'**
netopeer2-server[24170]: Failed to get "The peer disconnected" values iterator from sysrepo (`).
netopeer2-server[24170]: Server init failed.
netopeer2-server[24170]: (cl_message_send:170) Error by sending of the message: Broken pipe.
netopeer2-server[24170]: (cl_request_process:438) Unable to send the message with request (session id=1326882673, operation=unsubscribe).
netopeer2-server[24170]: (cl_subscription_close:243) Error by processing of the request.
netopeer2-server[24170]: (sr_unsubscribe:2845) Error by closing of the subscription: The peer disconnected.
netopeer2-server[24170]: (cl_message_send:170) Error by sending of the message: Broken pipe.
netopeer2-server[24170]: (cl_request_process:438) Unable to send the message with request (session id=1326882673, operation=unsubscribe).
netopeer2-server[24170]: (cl_subscription_close:243) Error by processing of the request.
netopeer2-server[24170]: (sr_unsubscribe:2845) Error by closing of the subscription: The peer disconnected.
netopeer2-server[24170]: (cl_message_send:170) Error by sending of the message: Broken pipe.
netopeer2-server[24170]: (cl_request_process:438) Unable to send the message with request (session id=1326882673, operation=unsubscribe).
netopeer2-server[24170]: (cl_subscription_close:243) Error by processing of the request.
netopeer2-server[24170]: (sr_unsubscribe:2845) Error by closing of the subscription: The peer disconnected.
netopeer2-server[24170]: (cl_message_send:170) Error by sending of the message: Broken pipe.
netopeer2-server[24170]: (cl_request_process:438) Unable to send the message with request (session id=1326882673, operation=unsubscribe).
netopeer2-server[24170]: (cl_subscription_close:243) Error by processing of the request.
netopeer2-server[24170]: (sr_unsubscribe:2845) Error by closing of the subscription: The peer disconnected.
netopeer2-server[24170]: (cl_message_send:170) Error by sending of the message: Broken pipe.
netopeer2-server[24170]: (cl_request_process:438) Unable to send the message with request (session id=1326882673, operation=unsubscribe).
netopeer2-server[24170]: (cl_subscription_close:243) Error by processing of the request.
netopeer2-server[24170]: (sr_unsubscribe:2845) Error by closing of the subscription: The peer disconnected.
netopeer2-server[24170]: (cl_message_send:170) Error by sending of the message: Broken pipe.
netopeer2-server[24170]: (cl_request_process:438) Unable to send the message with request (session id=1326882673, operation=unsubscribe).
netopeer2-server[24170]: (cl_subscription_close:243) Error by processing of the request.
netopeer2-server[24170]: (sr_unsubscribe:2845) Error by closing of the subscription: The peer disconnected.
netopeer2-server[24170]: (cl_message_send:170) Error by sending of the message: Broken pipe.
netopeer2-server[24170]: (cl_request_process:438) Unable to send the message with request (session id=1326882673, operation=unsubscribe).
netopeer2-server[24170]: (cl_subscription_close:243) Error by processing of the request.
netopeer2-server[24170]: (sr_unsubscribe:2845) Error by closing of the subscription: The peer disconnected.
netopeer2-server[24170]: (cl_message_send:170) Error by sending of the message: Broken pipe.
netopeer2-server[24170]: (cl_request_process:438) Unable to send the message with request (session id=1326882673, operation=unsubscribe).
netopeer2-server[24170]: (cl_subscription_close:243) Error by processing of the request.
netopeer2-server[24170]: (sr_unsubscribe:2845) Error by closing of the subscription: The peer disconnected.
netopeer2-server[24170]: (cl_message_send:170) Error by sending of the message: Broken pipe.
netopeer2-server[24170]: (cl_request_process:438) Unable to send the message with request (session id=1326882673, operation=unsubscribe).
netopeer2-server[24170]: (cl_subscription_close:243) Error by processing of the request.
netopeer2-server[24170]: (sr_unsubscribe:2845) Error by closing of the subscription: The peer disconnected.
netopeer2-server[24170]: (cl_message_send:170) Error by sending of the message: Broken pipe.
netopeer2-server[24170]: (cl_request_process:438) Unable to send the message with request (session id=1326882673, operation=unsubscribe).
netopeer2-server[24170]: (cl_subscription_close:243) Error by processing of the request.
netopeer2-server[24170]: (sr_unsubscribe:2845) Error by closing of the subscription: The peer disconnected.
netopeer2-server[24170]: (cl_message_send:170) Error by sending of the message: Broken pipe.
netopeer2-server[24170]: (cl_request_process:438) Unable to send the message with request (session id=1326882673, operation=unsubscribe).
netopeer2-server[24170]: (cl_subscription_close:243) Error by processing of the request.
netopeer2-server[24170]: (cl_sm_cleanup:1756) Client Subscription Manager successfully destroyed.
netopeer2-server[24170]: (sr_unsubscribe:2845) Error by closing of the subscription: The peer disconnected.
netopeer2-server[24170]: (cl_message_send:170) Error by sending of the message: Broken pipe.
netopeer2-server[24170]: (cl_request_process:438) Unable to send the message with request (session id=1326882673, operation=session-stop).
netopeer2-server[24170]: (sr_session_stop:571) Error by processing of the request

sysrepo aborts during netopeer2 init   
**yang_read_module: Assertion `module' failed.
Aborted**

see the logs below 

[DBG] (cm_out_notif_process:1376) Sending a notification to '/tmp/sysrepo-subscriptions/ietf-netconf-server/24170.TgSG4c.sock'.
[DBG] (sm_connection_find_dst:573) Cannot find the connection with dst_address address='/tmp/sysrepo-subscriptions/ietf-netconf-server/24170.TgSG4c.sock'.
[DBG] (cm_out_notif_process:1391) Creating a new connection for the notification destination '/tmp/sysrepo-subscriptions/ietf-netconf-server/24170.TgSG4c.sock'
[DBG] (sm_connection_start:353) New connection started successfully, fd=16, conn ctx=0x6976d0.
[DBG] (cm_conn_buffer_expand:477) Output buffer for fd=16 expanded to 1024 bytes.
[DBG] (cm_conn_out_buff_flush:505) Sending 111 bytes of data.
[DBG] (cm_conn_out_buff_flush:511) 111 bytes of data sent.
[DBG] (sr_cbuff_dequeue:532) Circular buffer dequeue, new buffer head=4, count=0.
[DBG] (rp_get_items_req_process:783) Processing get_items request.
[INF] (rp_dt_get_values_wrapper_with_opts:1355) Get items request startup datastore, xpath: /ietf-netconf-server:netconf-server/listen/endpoint[ssh]//*, offset: 0, limit: 100
[DBG] (ac_set_identity:155) Switching identity to UID='0' and GID='0' (username: root).
[DBG] (dm_load_data_tree_file:1122) Loaded module ietf-netconf-server: mtime sec=1491462550 nsec=836638489
[DBG] (dm_load_data_tree_file:1189) Usage count ietf-netconf-server incremented (value=1)
[INF] (dm_load_data_tree_file:1195) Data file /etc/sysrepo/data/ietf-netconf-server.startup loaded successfully
[DBG] (ac_set_identity:155) Switching identity to UID='0' and GID='0' (username: root).
[DBG] (dm_load_data_tree_file:1122) Loaded module ietf-keystore: mtime sec=1491462550 nsec=619638475
**[DBG] (dm_module_clb:446) CALLBACK FOR MODULE (null) urn:ietf:params:xml:ns:yang:ietf-keystore
sysrepod: /mnt/local/satheeshk/git_open_prj/devel_branch/libyang/src/parser_yang.c:2680: 
yang_read_module: Assertion `module' failed.
Aborted**

**Comment by michalvasko** [comment]
Please do not duplicate issues, you wrote the same in #120.
