### ISSUE TITLE
SSH connection failure

### ISSUE THREAD

**Issue by hthiery** [CESNET/netopeer2#1232]
I tried to manually setup a sysrepo/netopeer2 installation. I installed all modules and enables the required feature (like done in setup.sh), created the hostkey (like done in merge_hostkey.sh) and enalbed SSH  (like done in merge_config.sh).

Now I get the following error in the CLI:

```
> connect localhost
nc ERROR: Starting the SSH session failed (Socket error: Connection reset by peer).
cmd_connect: Connecting to the localhost:830 as user "root" failed.
```

and netopeer2 logs this error:
```
[INF]: LN: Accepted a connection on 0.0.0.0:830 from 127.0.0.1:38712.
[INF]: SR: Session 128 (user "root", CID 38) created.
[2022/06/28 07:31:06.841984, 1] pki_private_key_from_base64:  Parsing private key PK - Invalid key tag or value
[ERR]: LN: Failed to set hostkey "genkey" (/tmp/gyFsev).
```

Any idea what is going wrong?

**Comment by hthiery** [comment]
unfortunately I cannot use the provided scripts on the target since I do not have bash installed and the scripts does not work with sh ;-/

**Comment by jktjkt** [comment]
My random Google hits lead to `mbedtls`. Are you sure you've built against OpenSSL? Which version? How do your keys and certs files look like? Check against what happens locally (no cross-builds) and with the original bash script.

**Comment by hthiery** [comment]
Hi Jan, indeed MBEDTLS was selected as backend instead of OpenSSL. I will change and do a rebuild and let you know if this helps. Regardless on an locally build all works fine.

**Comment by hthiery** [comment]
Hi, I can confirm that switching to OpenSSL will solve the issue.
