### ISSUE TITLE
Confirmed commit w/o persist-id is not conform to RFC 6241

### ISSUE THREAD

**Issue by pfeige** [CESNET/netopeer2#1236]
Hi,

The RFC 6241 requires that any follow-up commit, the confirming commit and a cancel commit w/o persist-id MUST be issued on the same session that issued the confirmed commit. I tried the following test scenarios:
~~~
* open session 1
* edit-config candidate datastore
* confirmed commit w/o persist-id 
* open session 2
* confirmed commit w/o persist-id -> rejected = OK
* commit w/o persist-id -> accepted = not OK
~~~
~~~
* open session 1
* edit-config candidate datastore
* confirmed commit w/o persist-id 
* open session 2
* cancel-commit -> accepted = not OK
~~~
Could you please have a look on this?

BR,
Peter

**Comment by pfeige** [comment]
OK, now it is rejected. 
But the error tag for commit and cancel-commit is currently 'operation-failed'. Shouldn't this be 'invalid-value'?
And probably the error message for cancel-commit should start with 'Pending cancel-commit'.

**Comment by michalvasko** [comment]
My understanding is that `invalid-value` should be used for cases when there is any invalid value in the RPC. In this case it is the NETCONF session.

**Comment by pfeige** [comment]
But according to my tests a follow-up confirmed-commit is using the tag invalid-value already.

**Comment by michalvasko** [comment]
Alright, fine, it should be like I said now.

**Comment by pfeige** [comment]
OK, I can live with that.
Thanks!
