### ISSUE TITLE
netopeer2 server client connection via ipv6

### ISSUE THREAD

**Issue by vishruthy97** [CESNET/netopeer2#1238]
here in ietf-tcp-server@2019-07-02.yang file, under grouping tcp-server-grouping
it is given as INADDR_ANY (0.0.0.0) or INADDR6_ANY (0:0:0:0:0:0:0:0 a.k.a. ::) as follows

leaf local-address {
         type inet:ip-address;
         mandatory true;
         description
           "The local IP address to listen on for incoming
            TCP client connections.  INADDR_ANY (0.0.0.0) or
            INADDR6_ANY (0:0:0:0:0:0:0:0 a.k.a. ::) MUST be
            used when the server is to listen on all IPv4 or
            IPv6 addresses, respectively.";
}

can you please tell how to add support for the both ipv4 and ipv6 connection.
Note : when we give (0.0.0.0) here, ipv4 connection is getting established but not ipv6 connection but when we give (::) here, both ipv4 and ipv6 connections are getting established succesfully.

**Comment by jktjkt** [comment]
What problem are you reporting? Sounds like `::` works just fine for you. The reason why it works is that on Linux, sockets typically have the flag `IPV6_V6ONLY` off, and that means that the "IPv6" socket that listens on any address is usually listening in a dual-stack mode, supporting both IPv4 and IPv6.

**Comment by vishruthy97** [comment]
Thank you so much for the clarification. That's what my question was, is that okay to have (::) to support both IPv4 and IPv6 connections. Now I understood.
Thanks again for the support.
