### ISSUE TITLE
How app knows that there is create-subscription rpc about specific stream?

### ISSUE THREAD

**Issue by jamespark76** [CESNET/netopeer2#1241]
Hello.

This is a question.

How application knows that there is create-subscription rpc about specific stream?

It seems netopeer2 main function handles create-subscription rpc. 

/* subscribe to create-subscription */
SR_RPC_SUBSCR("/notifications:create-subscription", np2srv_rpc_subscribe_cb);

Is there a simple way (API) application to know there comes create-subscription rpc about specific stream?

Thansk.

**Comment by michalvasko** [comment]
Well, you can subscribe to the `create-subscription` RPC and then you will be notified about it, too. But I am not sure what you need this for, the streams are fully managed by *netopeer2* and currently are based on the installed modules.

**Comment by jamespark76** [comment]
Hello Michal,

I think my explanation is not enough. 

Basic function (create-subscription) must be handled in netopeer2 main source as it is. 
My application just wants to notify that there is create-subscription rpc about specific stream.
Now, I am trying to implement o-ran-supervision feature. 

My application wants to run specific scenarios if there is create-subscription rpc about o-ran-supervision stream.

Is is possible to use sr_rpc_subscribe() or sr_rpc_subscribe_tree() about create-subscription rpc in both netopeer2 main and my application?

I am using the latest netopeer2 (v2.1.23), libyang (v2.0.194). libnetconf2 (v2.1.11) and sysrepo (v2.1.64).

Best Regards,
James Park

**Comment by michalvasko** [comment]
> Is is possible to use sr_rpc_subscribe() or sr_rpc_subscribe_tree() about create-subscription rpc in both netopeer2 main and my application?

Yes, that is exactly what I was talking about:
> you can subscribe to the create-subscription RPC and then you will be notified about it, too.

**Comment by jamespark76** [comment]
I will check this and get back to you if I have further questions. Thanks for quick response.

**Comment by navneetkaurPS** [comment]
Hi Michael

I am trying the achieve the same functionality as asked by James in this thread. My code goes like: -

int ret_sub = sr_rpc_subscribe(sr_sess, "/notifications:create-subscription", 
                  sub_callback, NULL, 1, SR_SUBSCR_DEFAULT, &sr_rpc_sub);
    if (ret_sub != SR_ERR_OK) {
        PRINT_MSG(LOG_INFO,"Subscribing /notifications:create-subscription rpc failed\n");
    }

From client I send 

> subscribe --filter-xpath /o-ran-supervision:supervision-notification

I am unable to get the filter xpath string in callback function. Below is the gdb output : -
(gdb) p input[1]
$7 = {xpath = 0xffffcc004040 "/notifications:create-subscription/filter", type = SR_ANYXML_T, dflt = 0,
  origin = 0x0, data = {binary_val = 0xffffcc002530 "", bits_val = 0xffffcc002530 "", bool_val = -872405712,
    decimal64_val = 1.3906668513100855e-309, enum_val = 0xffffcc002530 "", identityref_val = 0xffffcc002530 "",
    instanceid_val = 0xffffcc002530 "", int8_val = 48 '0', int16_val = 9520, int32_val = -872405712,
    int64_val = 281474104304944, string_val = 0xffffcc002530 "", uint8_val = 48 '0', uint16_val = 9520,
    uint32_val = 3422561584, uint64_val = 281474104304944, anyxml_val = 0xffffcc002530 "",
    anydata_val = 0xffffcc002530 ""}}
(gdb) p input[0]
$8 = {xpath = 0xffffcc000b20 "/notifications:create-subscription/stream", type = SR_STRING_T, dflt = 1,
  origin = 0x0, data = {binary_val = 0xffffcc004ce0 "NETCONF", bits_val = 0xffffcc004ce0 "NETCONF",
    bool_val = -872395552, decimal64_val = 1.3906668513602826e-309, enum_val = 0xffffcc004ce0 "NETCONF",
    identityref_val = 0xffffcc004ce0 "NETCONF", instanceid_val = 0xffffcc004ce0 "NETCONF", int8_val = -32 '\340',
    int16_val = 19680, int32_val = -872395552, int64_val = 281474104315104,
    string_val = 0xffffcc004ce0 "NETCONF", uint8_val = 224 '\340', uint16_val = 19680, uint32_val = 3422571744,
    uint64_val = 281474104315104, anyxml_val = 0xffffcc004ce0 "NETCONF", anydata_val = 0xffffcc004ce0 "NETCONF"}}


I want specific functionality to be achieved when subscribed on this filter xpath. How can I achieve this ?

netopeer2 version 2.1.42

Thanks
Navneet

**Comment by michalvasko** [comment]
Right, the old API does not support metdata, you will have to use `sr_rpc_subscribe_tree()` instead.

**Comment by navneetkaurPS** [comment]
thanks it worked for me
