### ISSUE TITLE
Disconnecting from server side.

### ISSUE THREAD

**Issue by vinayhb012114** [CESNET/netopeer2#1243]
@michalvasko,
From the server side,I need to disconnect session for certain users. How to do that?
If I use np2srv_del_session_cb(); and  nc_session_free(), I am getting error messages at client side as showm below.
c ERROR: SSH channel unexpected EOF.
nc ERROR: Failed to receive a reply to <get-schema>.
ly ERROR: Loading "ietf-netconf-acm" module failed.
ly ERROR: Parsing module "ietf-netconf" failed.
nc ERROR: Loading base NETCONF schema failed.
ly ERROR: Value "cm_admin" was not found in the dictionary.
ly ERROR: Value "10.0.2.15" was not found in the dictionary.
cmd_connect: Connecting to the 10.0.2.15:830 as user "cm_admin" failed

**Comment by vinayhb012114** [comment]
Test report:
[o-ran-usermgmt-v3.0.xlsx](https://github.com/CESNET/netopeer2/files/9167098/o-ran-usermgmt-v3.0.xlsx)

**Comment by michalvasko** [comment]
There is no proper mechanism to terminate a NETCONF session from server-side, so you cannot avoid some errors. But there should not be leaks on the side of the client. Anyway, you should just need to call the [callback](https://github.com/CESNET/netopeer2/blob/devel/src/main.c#L1014) for terminated sessions.
