### ISSUE TITLE
CMakeLists.txt looking for sysrepo executables causes a problem in an embedded build (Yocto) environment

### ISSUE THREAD

**Issue by bbergquist0930** [CESNET/netopeer2#1252]
This code 
```
# find sysrepoctl to be used for installation and tests
if (NOT SYSREPOCTL_EXECUTABLE)
    find_program(SYSREPOCTL_EXECUTABLE sysrepoctl)
endif()
if (NOT SYSREPOCTL_EXECUTABLE)
    message(FATAL_ERROR "Unable to find sysrepoctl, set SYSREPOCTL_EXECUTABLE manually.")
endif()

# find sysrepocfg to be used for installation and tests
if (NOT SYSREPOCFG_EXECUTABLE)
    find_program(SYSREPOCFG_EXECUTABLE sysrepocfg)
endif()
if (NOT SYSREPOCFG_EXECUTABLE)
    message(FATAL_ERROR "Unable to find sysrepocfg, set SYSREPOCFG_EXECUTABLE manually.")
endif()
```
is looking for the sysrepo executables.   However these are only going to be used if `INSTALL_MODULES` or `GENERATE_HOSTKEY` or `MERGE_LISTEN_CONFIG` are defined.  In an embedded build environment like Yocto, those actions are not going to be run on the host system, but will be deferred and run on the target system when it boots.

A simple `if` around the above allows better support for an embedded build.   Attached is a patch that I am using.

[check-for-install-or-test.patch.txt](https://github.com/CESNET/netopeer2/files/9246785/check-for-install-or-test.patch.txt)

**Comment by michalvasko** [comment]
No problem, fixed.
