### ISSUE TITLE
why configs applied in the running config presists during system restarts?

### ISSUE THREAD

**Issue by alireza11048** [CESNET/netopeer2#1255]
Hi,
I'm newbiew in the netconf world and I've just installed the netopper2/sysrepo setup. 
as I've understood, the configs which applied to the running datastore should be disappeared when the services restart (for example when the system reboots) unless the running config is copied to the startup-config. however, I'm experiencing a different things, in this manner that without coping the running config to the startup-config, the configs persist during restarts.
haven't I understood the running/startup datastores correctly? could anyone kindly explain to me what is happening?

thanks in advance

**Comment by michalvasko** [comment]
Yes, you understood it correctly and `running` should always be replaced by `startup` on system reboot. What exactly are you experiencing? What *sysrepo* version are you using?

**Comment by alireza11048** [comment]
Thanks for your response,
for example, if I change ietf-interfaces config with the below command to config an interface, even after restarting the system the applied configuration exists in the running datastore. but as it applied to the running datastore, I expect that they should be removed from the running datastore.
`edit-config --target running --config=set_ip_conf.xml`

P.S:
in the netopeer-cli, this is the "edit-config help" output:
`edit-config [--help] --target running|candidate --config[=<file>] [--defop merge|replace|none] [--test set|test-only|test-then-set] [--error stop|continue|rollback] [--rpc-timeout <seconds>]`
as you can see, the valid target options are the candidate and running. why the startup datastore doesn't exist in the available options?

thanks in advance

**Comment by michalvasko** [comment]
Strictly speaking, it all depends on whether `/dev/shm` directory is being cleared (all files removed) on reboot or not on your system. But it is on all the systems I have worked on.

> why the startup datastore doesn't exist in the available options?

Because it is not supported by the [spec](https://github.com/CESNET/netopeer2/blob/master/modules/ietf-netconf%402013-09-29.yang#L438).
