### ISSUE TITLE
Could NOT find LibNETCONF2: Found unsuitable version "3.1.6"

### ISSUE THREAD

**Issue by newacforwork22** [CESNET/netopeer2#1260]
Hi, 
libnetconf2 is installed but getitng as not found
![Screenshot (139)](https://user-images.githubusercontent.com/105341738/186711390-83542d1a-31ca-4e53-bc9c-f8938d10e869.png)

**Comment by michalvasko** [comment]
Yes, you have an old version of *libnetconf2* installed so you need to update it. You can always find the latest versions in the `devel` branches of the respective projects.

**Comment by raghavendraks444** [comment]
thanks for reply @michalvasko 

I checked out to devel branch but now I am getting as libpam not found 
![image](https://user-images.githubusercontent.com/105341738/186858007-215fe656-9d28-4f89-999b-00302588d626.png)

**Comment by michalvasko** [comment]
And why have you not solved the problem yourself by installing `libpam` but are pasting the output here? Yes, there is a new dependency but that really should not be a problem.
