### ISSUE TITLE
Since #322, fixed in v2.1.36, TLS Call Home failed

### ISSUE THREAD

**Issue by robbynet** [CESNET/netopeer2#1261]
View on v2.1.36
With new SSL checks taking place to conform to RFC6125 via [#322](https://github.com/CESNET/libnetconf2/issues/322), listen command needs an additional parameter to pass CN/SAN of part of the NC Server Certificate

**Comment by michalvasko** [comment]
Okay, now it should all work much better as I have implemented several improvements. Directly connected to this issue, the server hostname is no longer being checked if not specified. The option to specify it was added (and can be tested in *netopeer2-cli*) when it is being verified.

**Comment by robbynet** [comment]
Thanks for the fix, it has been successfully tested !
