### ISSUE TITLE
Pipelining and notifications

### ISSUE THREAD

**Issue by robbynet** [CESNET/netopeer2#1266]
Hello,
Pipelining is specified in chapter 4.5 of RFC 6241 and supported by Netopeer2, meaning that a given RPC on a given NETCONF Session is serialized  until the previous one ( one the same NETCONF Session ) ended.
Question : In case some RPC are serialized, does it prevent notifications being transmitted from NC Server to NC Client ?

**Comment by michalvasko** [comment]
No, notifications have their own queue and thread in *netopeer2*.

**Comment by robbynet** [comment]
Thanks for support !
