### ISSUE TITLE
netopeer make error

### ISSUE THREAD

**Issue by iraponomareva** [CESNET/netopeer2#1268]
hello, when I try to install netopeer2, I get this error, could you help me?

-- Installing missing sysrepo modules...
/usr/local/bin/sysrepoctl: error while loading shared libraries: libsysrepo.so.7: cannot open shared object file: No such file or directory
/usr/local/bin/sysrepoctl: error while loading shared libraries: libsysrepo.so.7: cannot open shared object file: No such file or directory
CMake Error at cmake_install.cmake:111 (message):
   scripts/setup.sh failed: 127

make: *** [Makefile:86: install] Ошибка 1

**Comment by michalvasko** [comment]
Run `# ldconfig`.

**Comment by iraponomareva** [comment]
thanks
