### ISSUE TITLE
 how to add a model.yang question

### ISSUE THREAD

**Issue by iraponomareva** [CESNET/netopeer2#1269]
I'm sorry, could you help me? In the netopeer-server version, it was possible to add a yang model using netopeer-manager: sudo netopeer-manager add --name <model_name> --model ./model.yin --transapi /usr/local/lib/model.so --datastore ./datastore.xml . How can I add a model to netopeer2-server?

**Comment by michalvasko** [comment]
When using *netopeer2*, it is actually the datastore that does all the work with YANG modules and YANG data, *sysrepo*. Look at its [documentation](https://netopeer.liberouter.org/doc/sysrepo/master/html/index.html). Specifically, use `sysrepoctl` to manage YANG modules and `sysrepocfg` for working with YANG data.

**Comment by iraponomareva** [comment]
thanks
