### ISSUE TITLE
problem whis netopeer2-cli connect

### ISSUE THREAD

**Issue by iraponomareva** [CESNET/netopeer2#1270]
do I understand correctly, the connection error is due to an incorrect password?

>connect
root@localhost password: 
nc ERROR: Unable to authenticate to the remote server (all attempts via supported authentication methods failed).
cmd_connect: Connecting to the localhost:830 as user "root" failed.

**Comment by michalvasko** [comment]
Yes, `password` authentication method failed because of that and there are no more methods to try.

**Comment by iraponomareva** [comment]
How can I change the authentication method?

**Comment by michalvasko** [comment]
By default, all are enabled but you can configure them in `ietf-netconf-server` YANG data for the server side (*netopeer2-server*) and using the `auth` command for the client side in *netopeer2-cli*.
