### ISSUE TITLE
get command is not working on very first 

### ISSUE THREAD

**Issue by sudarkodi07** [CESNET/netopeer2#1271]
Hi @michalvasko ,

when I push get in netopeer2-cli, I am getting the below error message.

> get
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	message:  Callback event "rpc" with ID 1 processing timed out.

But the above error is only during first time, after this it is fetching perfect.

Can you brief me why this is happening??

Is there any possibilities to change to default processing time.

**Comment by michalvasko** [comment]
It seems you have too much data there and the default timeout is not enough. Increase it for the server using the parameter `-t 10`, for example.

**Comment by sudarkodi07** [comment]
Hi @michalvasko, If I increase it for the server then after reboot of my total application, I need to re-increase the parameter again or once done will reflect everytime?

**Comment by michalvasko** [comment]
It is an executable parameter - every time you run the executable you have to specify the parameter.

**Comment by sudarkodi07** [comment]
Ok @michalvasko, Understood
Thanks.
