### ISSUE TITLE
problem with transAPI

### ISSUE THREAD

**Issue by iraponomareva** [CESNET/netopeer2#1273]
please tell me, are netopeer and netopeer2 transAPI compatible? I have a module created to work with netopeer, an error occurs when trying sysrepoctl --install. As I understand it, it is connected with transAPI formation for different versions of netopeer

**Comment by michalvasko** [comment]
There is no transAPI in *netopeer2*, it would be needlessly complex. It is part of the datastore implementation, which is [sysrepo](https://github.com/sysrepo/sysrepo) for *netopeer2*. Just read through its [docs](https://netopeer.liberouter.org/doc/sysrepo/master/html/) and especially the [plugin example](https://netopeer.liberouter.org/doc/sysrepo/master/html/example.html) which technically replaces the transAPI modules from the ancient *netopeer*.

**Comment by iraponomareva** [comment]
So, without making modifications, it will not work to connect the module to netopeer2? I'm new to netopeer, it's still difficult to me to understand the subtleties.

**Comment by michalvasko** [comment]
No, it will absolutely not work with *netopeer2*/*sysrepo*. If you are new to *netopeer* then I suggest you abandon and forget about it right now without wasting more time on it and focus on *sysrepo*.

**Comment by iraponomareva** [comment]
ok, thanks
