### ISSUE TITLE
netconf notification timeout

### ISSUE THREAD

**Issue by som-1981** [CESNET/netopeer2#1274]
Hello, 

Regarding NETCONF notification timeout what is the default value when an RPC message is sent from the netconf client to a Netconf server and Netconf server does not respond back with a notification due to some reason. 

Is this a global timeout or per notification we need to define a timeout at the netconf client if netconf server does not respond back with a notification.

Thanks,

**Comment by michalvasko** [comment]
What use-case are you talking about exactly? The client can send an `<rpc>` message and then expect a `<rpc-reply>`. Or, the client can subscribe for receiving notifications and then the server asynchronously sends `<notification>` messages as they are generated. Which are you talking about?

**Comment by som-1981** [comment]
I should have made it clear. I am talking about the second case.
The client can subscribe for receiving notifications and then the server asynchronously sends <notification> messages as they are generated.

**Comment by michalvasko** [comment]
Then what timeout are you talking about? The client nor the server do not know when a new notification is generated. Only once there is one, it is sent to the client.
