### ISSUE TITLE
Url ability

### ISSUE THREAD

**Issue by lilililizheng** [CESNET/netopeer2#1279]
hi，I use netopeer2 as the server, now I need to do active/standby, I want to know how to synchronize the master and slave. The value can be full synchronization or incremental synchronization。I think the url capability might be able to do that,but I ran rpc and found that netconf does not support url
![image](https://user-images.githubusercontent.com/106649263/196352747-b1bfff15-4b49-40af-a1c1-b906c650686e.png)
![image](https://user-images.githubusercontent.com/106649263/196352827-ab413a7c-91e8-445d-b963-644c0c5357ef.png)

**Comment by michalvasko** [comment]
Check `cmake` log, you need to have `libcurl` installed for URL to work.

**Comment by lilililizheng** [comment]
Thank you. Do you have any suggestions on how to synchronize data between master and slave devices?

**Comment by michalvasko** [comment]
Please do not duplicate issues, this one is finished and I will reply in the other one soon.

**Comment by lilililizheng** [comment]
thanks，Looking forward to your reply.

**Comment by lilililizheng** [comment]
Well, if I say master/slave, you might understand. There are two devices A/B, A works normally, and B takes over the work of A immediately when A goes wrong, so I hope to keep the data of A/B consistent at all times. Is there any way to make this happen? Or is this work done at the netconf level.
