### ISSUE TITLE
IPv4/IPv6 NETCONF SSH/TLS listen configuration

### ISSUE THREAD

**Issue by jamespark76** [CESNET/netopeer2#1282]
Hello @michalvasko,

I have a question about IPv4 / IPv6 NETCONF SSH/TLS listen configuration.
I am able to configure IPv4 or IPv6 NETCONF SSH/TLS listen respectively with ietf-netconf-server.yang configuration.

Is it possible to configure IPv4 / IPv6 dual listen at the same time?

[IPv4 NETCONF SSH/TLS listen only]
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address Foreign Address State
tcp        0      0 0.0.0.0:830   0.0.0.0:*       LISTEN
tcp        0      0 0.0.0.0:6513  0.0.0.0:*       LISTEN

[IPv6 NETCONF SSH/TLS listen only]
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address Foreign Address State
tcp        0      0 :::830        :::*            LISTEN
tcp        0      0 :::6513       :::*            LISTEN

Best Regards,
James Park

**Comment by michalvasko** [comment]
You can always create more endpoints with their own listening address. However, IPv6 address `::` should listen on both IPv4 and IPv6.

**Comment by jamespark76** [comment]
Hello @michalvasko,

As you recommended, I checked IPv6 address (::) works for IPv4 client connection, but IPv4 client ip address displays like ::ffff:x.x.x.x.

I created additional ssh/tls ipv4/ipv6 endpoints. However, it seems first ssh/tls ipv4(0.0.0.0) or ipv6(::) valid only.

(1) ipv4 endpoint first

<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <listen>
    <endpoint>
      <name>listen-ssh-ipv4</name>
    </endpoint>
    <endpoint>
      <name>listen-ssh-ipv6</name>
    </endpoint>
    <endpoint>
      <name>listen-tls-ipv4</name>
    </endpoint>
    <endpoint>
      <name>listen-tls-ipv6</name>
    </endpoint>
  </listen>
</netconf-server>

[netstat -a]
tcp 0 0 0.0.0.0:830 0.0.0.0:* LISTEN
tcp 0 0 0.0.0.0:6513 0.0.0.0:* LISTEN

(2) ipv6 endpoint first

<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <listen>
    <endpoint>
      <name>listen-ssh-ipv6</name>
    </endpoint>
    <endpoint>
      <name>listen-ssh-ipv4</name>
    </endpoint>
    <endpoint>
      <name>listen-tls-ipv6</name>
    </endpoint>
    <endpoint>
      <name>listen-tls-ipv4</name>
    </endpoint>
  </listen>
</netconf-server>

[netstat -a]
tcp 0 0 :::830 :::* LISTEN
tcp 0 0 :::6513 :::* LISTEN

Thanks.

**Comment by jamespark76** [comment]
Hello @michalvasko,

As you recommended, I checked IPv6 address (::) works for IPv4 client connection, but IPv4 client ip address displays like ::ffff:x.x.x.x.

I created additional ssh/tls ipv4/ipv6 endpoints. However, it seems first ssh/tls ipv4(0.0.0.0) or ipv6(::) valid only.

(1) ipv4 endpoint first

#<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
#  <listen>
#    <endpoint>
#      <name>listen-ssh-ipv4</name>
#    </endpoint>
#    <endpoint>
#      <name>listen-ssh-ipv6</name>
#    </endpoint>
#    <endpoint>
#      <name>listen-tls-ipv4</name>
#    </endpoint>
#    <endpoint>
#      <name>listen-tls-ipv6</name>
#    </endpoint>
#  </listen>
#</netconf-server>

[netstat -a]
tcp 0 0 0.0.0.0:830 0.0.0.0:* LISTEN
tcp 0 0 0.0.0.0:6513 0.0.0.0:* LISTEN

(2) ipv6 endpoint first

#<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
#  <listen>
#    <endpoint>
#      <name>listen-ssh-ipv6</name>
#    </endpoint>
#    <endpoint>
#      <name>listen-ssh-ipv4</name>
#    </endpoint>
#    <endpoint>
#      <name>listen-tls-ipv6</name>
#    </endpoint>
#    <endpoint>
#      <name>listen-tls-ipv4</name>
#    </endpoint>
#  </listen>
#</netconf-server>

[netstat -a]
tcp 0 0 :::830 :::* LISTEN
tcp 0 0 :::6513 :::* LISTEN

Thanks.

**Comment by jamespark76** [comment]
Hello @michalvasko,

As you recommended, I checked IPv6 address (::) works for IPv4 client connection, but IPv4 client ip address displays like ::ffff:x.x.x.x.

I created additional ssh/tls ipv4/ipv6 endpoints. However, it seems first ssh/tls ipv4(0.0.0.0) or ipv6(::) valid only.

(1) ipv4 endpoint first

` <listen>                         `
`   <endpoint>                     `
`     <name>listen-ssh-ipv4</name> `
`   </endpoint>                    `
`   <endpoint>                     `
`     <name>listen-ssh-ipv6</name> `
`   </endpoint>                    `
`   <endpoint>                     `
`     <name>listen-tls-ipv4</name> `
`   </endpoint>                    `
`   <endpoint>                     `
`     <name>listen-tls-ipv6</name> `
`   </endpoint>                    `
` </listen>                        `


[netstat -a]
tcp 0 0 0.0.0.0:830 0.0.0.0:* LISTEN
tcp 0 0 0.0.0.0:6513 0.0.0.0:* LISTEN

(2) ipv6 endpoint first

` <listen>                         `
`   <endpoint>                     `
`     <name>listen-ssh-ipv6</name> `
`   </endpoint>                    `
`   <endpoint>                     `
`     <name>listen-ssh-ipv4</name> `
`   </endpoint>                    `
`   <endpoint>                     `
`     <name>listen-tls-ipv6</name> `
`   </endpoint>                    `
`   <endpoint>                     `
`     <name>listen-tls-ipv4</name> `
`   </endpoint>                    `
` </listen>                        `

[netstat -a]
tcp 0 0 :::830 :::* LISTEN
tcp 0 0 :::6513 :::* LISTEN

Thanks.

**Comment by michalvasko** [comment]
I have tested it with the current version in `devel`, the configuration:
```xml
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <listen>
    <endpoint>
      <name>default-ssh</name>
      <ssh>
        <tcp-server-parameters>
          <local-address>127.0.0.1</local-address>
          <keepalives>
            <idle-time>1</idle-time>
            <max-probes>10</max-probes>
            <probe-interval>5</probe-interval>
          </keepalives>
        </tcp-server-parameters>
        <ssh-server-parameters>
          <server-identity>
            <host-key>
              <name>default-key</name>
              <public-key>
                <keystore-reference>genkey</keystore-reference>
              </public-key>
            </host-key>
          </server-identity>
          <client-authentication>
            <supported-authentication-methods>
              <publickey/>
              <passsword/>
            </supported-authentication-methods>
          </client-authentication>
        </ssh-server-parameters>
      </ssh>
    </endpoint>
    <endpoint>
      <name>default-ssh2</name>
      <ssh>
        <tcp-server-parameters>
          <local-address>::1</local-address>
          <keepalives>
            <idle-time>1</idle-time>
            <max-probes>10</max-probes>
            <probe-interval>5</probe-interval>
          </keepalives>
        </tcp-server-parameters>
        <ssh-server-parameters>
          <server-identity>
            <host-key>
              <name>default-key</name>
              <public-key>
                <keystore-reference>genkey</keystore-reference>
              </public-key>
            </host-key>
          </server-identity>
          <client-authentication>
            <supported-authentication-methods>
              <publickey/>
              <passsword/>
            </supported-authentication-methods>
          </client-authentication>
        </ssh-server-parameters>
      </ssh>
    </endpoint>
  </listen>
</netconf-server>
```
netopeer2-server -d -v3 logs:
```
...
[INF]: LN: Listening on 127.0.0.1:830 for SSH connections.
[INF]: LN: Listening on ::1:830 for SSH connections.
...
```
ss -lt output:
```
State            Recv-Q           Send-Q                       Local Address:Port                              Peer Address:Port           Process           
LISTEN           0                5                                127.0.0.1:netconf-ssh                            0.0.0.0:*                                
LISTEN           0                5                                    [::1]:netconf-ssh                               [::]:*                                
```

When I tried address `::` I got:
```
LISTEN           0                5                                        *:netconf-ssh                                  *:* 
```
which seem to listen on both IPv4 and IPv6 but that depend on the system you are on.

**Comment by jamespark76** [comment]
I have tested your attached xml.

My device shown like below.

'''
Proto    Recv-Q     Send-Q      Local Address                      Foreign Address   State
tcp        0             0                  localhost.localdomain:830  0.0.0.0:*                 LISTEN
tcp        0             0                  localhost:830                       :::*                         LISTEN
''''

This works only internal netconf connection, and not available for external netconf connections.


I changed your xml like below and check again.

<name>default-ssh</name>
<local-address>0.0.0.0</local-address>

<name>default-ssh2</name>
<local-address>::</local-address>

'''
Proto    Recv-Q    Send-Q      Local Address   Foreign Address   State
tcp        0             0                 0.0.0.0:830        0.0.0.0:*                 LISTEN
''''

Only first IPv4 is valid, but it's available for external netconf connection.

Did I miss something about configurations?

Best Regards,

**Comment by jamespark76** [comment]
For your information, my device is enabled both IPv4(0.0.0.0) and IPv6(::) address for SSH port(22).

```
Proto   Recv-Q   Send-Q Local Address   Foreign Address   State
tcp     0        0 0.0.0.0:ssh          0.0.0.0:*         LISTEN
tcp     0        0 :::ssh               :::*              LISTEN
```

Thanks.

**Comment by jktjkt** [comment]
By default, Linux uses a setting which causes IPv6 sockets to also accept IPv4 connections; these are mapped to IPv6 addresses automatically. Check your `/proc/sys/net/ipv6/bindv6only` and read [`man ipv6(7)`](https://man7.org/linux/man-pages/man7/ipv6.7.html), the part about `IPV6_V6ONLY`. If your distro follows this default, just configure a single endpoint which listens on `::`, and it will do the trick by accepting both IPv4 and IPv6 connections.

**Comment by jamespark76** [comment]
Hello @jktjkt,

I already verified IPv6 address (::) works for both IPv4 and IPv6 connections as @michalvasko recommended in this thread.

```
As you recommended, I checked IPv6 address (::) works for IPv4 client connection, 
but IPv4 client ip address displays like ::ffff:x.x.x.x.
```

/proc/sys/net/ipv6/bindv6only flag in my device is 0(false) as default.

**Comment by michalvasko** [comment]
As seem from the output I posted, **run the server with parameters** `-d -v2`. Then you will see what interfaces are being listened on without having to run `netstats` or `ss`. When I tried the non-working configuration (according to you) I got this output
```
[INF]: LN: Listening on 0.0.0.0:830 for SSH connections.
[ERR]: LN: Could not bind "::" port 830 (Address already in use).
```
which makes sense.

**Comment by jktjkt** [comment]
> but IPv4 client ip address displays like ::ffff:x.x.x.x.

Why is this a problem?

**Comment by jamespark76** [comment]
Hello @michalvasko,

When I tried my configuration, log messages are shown like below.

(1) IPv4 first

```
<name>default-ssh</name>
<local-address>0.0.0.0</local-address>

<name>default-ssh2</name>
<local-address>::</local-address>
```
```
[INF] Listening on 0.0.0.0:830 for SSH connections.
[ERR] Could not bind \"::\" port 830 (Broken pipe).
```

(2) IPv6 first

```
<name>default-ssh2</name>
<local-address>::</local-address>

<name>default-ssh</name>
<local-address>0.0.0.0</local-address>
```
```
[INF] Listening on :::830 for SSH connections.
[ERR] Could not bind \"0.0.0.0\" port 830 (Broken pipe).
```

As I wrote above, both IPv4(0.0.0.0) and IPv6(::) address can be enable for normal SSH port(22).

I will close this issue because it seems your test environment is different from mine so I can't get support for this.

Best Regards,
James

**Comment by michalvasko** [comment]
> I will close this issue because it seems your test environment is different from mine so I can't get support for this.

You are probably right about that because it is the first time I see such an error, weird.

**Comment by jktjkt** [comment]
If you try to listen on `0.0.0.0` and `::` at the same time **and** if your system defaults to IPv6 sockets listening on IPv6-mapped IPv4 addresses as well, then this cannot work. A correct fix is to either:
- listen on `::` only **and** make sure that the v6-mapped-v4-addresses are enabled
- or listen on both `0.0.0.0` **and** on `::`, but configure the v6 socket with `IPV6_V6ONLY`

@michalvasko do you have `/proc/sys/net/ipv6/bindv6only` set to `1` by any chance?

**Comment by michalvasko** [comment]
No, I have it `0`. I assume that is why I got the error `Address already in use` when trying to listen on both separately, since IPv6 binds to both IPv6 and IPv4.

**Comment by jamespark76** [comment]
Hello @jktjkt @michalvasko,

Finally, it works by set /proc/sys/net/ipv6/bindv6only as 1.

```
Proto  Recv-Q  Send-Q  Local Address  Foreign Address  State
tcp         0       0  0.0.0.0:6513   0.0.0.0:*        LISTEN
tcp         0       0  0.0.0.0:830    0.0.0.0:*        LISTEN
tcp         0       0  :::6513        :::*             LISTEN
tcp         0       0  :::830         :::*             LISTEN
```

Both SSH/TLS IPv4 and IPv6 listen are enabled together. Thanks for support.

Best Regards,
James
