### ISSUE TITLE
Query on change in nc_session struct

### ISSUE THREAD

**Issue by meghna-doshi** [CESNET/netopeer2#1284]
Hi,
We were using earlier netopeer2 version 2.1.10

here nc_session struct had **ntf_thread** variable which we had set to 1.

```
struct {
            /* client side only data */
            uint64_t msgid;
            char **cpblts;                 /**< list of server's capabilities on client side */
            pthread_mutex_t msgs_lock;     /**< lock for the msgs buffer */
            struct nc_msg_cont *msgs;      /**< queue for messages received of different type than expected */
            ATOMIC_T ntf_thread;           /**< flag whether notification thread for this session is running or not,
                                                2 means it should quit */

            /* client flags */
            /* some server modules failed to load so the data from them will be ignored - not use strict flag for parsing */
#           define NC_SESSION_CLIENT_NOT_STRICT 0x40
        } client;

```

But now we upgraded to latest version 2.1.41, here the struct is changed slightly and ntf_thread seems to be replaced by following 2 attributes, so we have set those as 1:

```
m_ncSessionObj->opts.client.ntf_thread_count = 1;
m_ncSessionObj->opts.client.ntf_thread_running = 1;

```
So wanted to know if this is fine (considering we had earlier set ntf_thread = 1 )

**Comment by michalvasko** [comment]
You are on your own when using private structures. And I may be reluctant to generally provide support to you having learnt this, no wonder you have non-reproducible issues when not using the libraries the way there were designed.

**Comment by meghna-doshi** [comment]
Hi Michal,
This is not related to any customization.
We have not touched single line of core code.
This change came from latest rebase, so we are asking if the change from ntf_thread = 1  to 

m_ncSessionObj->opts.client.ntf_thread_count = 1;
m_ncSessionObj->opts.client.ntf_thread_running = 1;

is fine? Since earlier the struct had only single variable ntf_thread and now it is replaced by the above 2 variables in the structure definition.

**Comment by michalvasko** [comment]
In the README, there is the [Usage](https://github.com/CESNET/libnetconf2/#usage) section. Those 2 headers are **all** that you should ever include in your programs. You are including `session_p.h` (p stands for private) as well and that is why I refuse to help. Why exactly do you need to do that, why do you have to access private structures?

**Comment by meghna-doshi** [comment]
Hi Michal,
So the reason we have included session_p.h file is to write a netconf client using the netopeer2-cli code to handle M plane interface.
Since the netopeer2-cli binary directly cannot be used for that, we have used APIs of netopeer2-cli only. But to start the client thread in our application, with our limited understanding of the netopeer2 code, we have initialized those variables.
If there is a API which can do this, then we are ready to use it.

**Comment by michalvasko** [comment]
> write a netconf client using the netopeer2-cli code

I am not really sure what "API" does *netopeer2-cli* has but you should not have done this, anyway. The CLI is quite usable but still far from a robust NETCONF client and if you want that, you should write your own just using *libnetconf2*, without the CLI code.
