### ISSUE TITLE
A single Netconf server for multiple devices?

### ISSUE THREAD

**Issue by mezfa** [CESNET/netopeer2#1285]
Hello,

Is it possible to use a **Single Netconf server** with the associated datastore for multiple devices?

I have a specific use case involving 4 devices: 
  - 3 network devices (belonging to the same network) that we would like to manage remotely (mainly retrieve information).
  - a remote device used as Netconf client

![image](https://user-images.githubusercontent.com/3809576/197768924-9a45c261-a7b9-45ff-a9bc-49dccf5d887e.png)

Due to limited resources on Device2 and Device3, we would like to deploy a single Netconf server (only on Device1). Thus, Device1 will be an intermediate between the Netconf_client and Device2/Device3 (as shown in the following). 

Device2    <--- socket --->    Device1 (Netconf_Server)    <--- netconf --->    Netconf_Client

Therefore, sockets and scripts could be used for the communication between Device2 and Device1. For instance, when the Netconf_Client make an Netconf RPC request, it is received by Device1, that will translate and forward the request to Device2 via sockets. 

Is this design possible? can the datastore of Device1 be also used to store information associated to Device2 and Device3?

Any help is appreciated !

**Comment by michalvasko** [comment]
Although such a design is not officially supported, our suite is quite versatile and should allow you to implement this, in several ways and without modifying our code. My advice would be to implement it the following way.

Any configuration changes or custom RPCs must be subscribed to by *sysrepo* apps/plugins that are supposed to apply the configuration changes/execute the RPC. In your case you can do that remotely by sending the required information to the target device instead of applying it locally.

**Comment by mezfa** [comment]
Thank you Michal for your reply! 

I am not sure if I get well your point. 
Does this mean that a single Netopeer2 server could be installed on only one device (Device1) while sysrepo should be installed on all other devices ? (see next figure)

![image](https://user-images.githubusercontent.com/3809576/197829228-241c7678-ccb6-4bd2-a007-3920cade36e2.png)

Thus, when the Netconf client forward an RPC request destined to Device2, it will be received by Device1 Netopeer2 and then forwarded to sysrepo of Device2 and vice versa for the RPC reply. 

Could you please provide more details on the following: 
" In your case you can do that remotely by sending the required information to the target device instead of applying it locally."

Thanks !

**Comment by michalvasko** [comment]
No, the link *sysrepo* <-> *netopeer2* cannot be remote the way you designed it, it is always local. What I meant is that `Apps` on `Device1` will be remotely connected to `Device2`, using your own protocol and socket or whatever.

**Comment by mezfa** [comment]
Ok that's clear. 

In this case, should the ### Device1 include information of

**Comment by mezfa** [comment]
Ok that's clear. 

In this case, should Device1 include in its datastore information of Device2 ? Thus, when the Netconf_Client requests an information regarding Device2 => Device1 will be able to provide this information from its datastore. 

I am just trying to understant how Netconf RPC and Netconf Notification destined to Device2 are being processed via Device1. Is it as the following?

![image](https://user-images.githubusercontent.com/3809576/198024174-40a4feca-8f82-4262-842c-af6636ee6f1c.png)

**Netconf Request/Response**
Netconf request destined to Device2 will firstly arrive to the Netconf Server on Device1, and what should be the next steps?

**Netconf Notification**
When there are notifications, should Device2 forward the notification to Device1, then Device1 will transfer it to Netconf_client via Netconf ? 

Thank you for your help !

**Comment by michalvasko** [comment]
So I made the effort and changed the design to what I meant.
![untitled](https://user-images.githubusercontent.com/12510224/198029560-b55fd4a1-e5b7-4831-a7fe-6967d2a683ad.png)
It will be up to you to somehow communicate all requests and notifications from `App2` to `Device2` and vice versa, for *sysrepo*/*netopeer2* both devices will seem to be locally on `Device1`. And yes, as @jktjkt mentioned, this communication may not be completely trivial to implement.

**Comment by mezfa** [comment]
Thank you so much Jan and Michal for your quick responses and your help ! it is clear to me now. 
This is intended for an ARM-based embedded system. There will be several applications running on the device consuming most of the resources, hence the need to minimize resources consumption. 
Indeed, implementing this communication between Device1 and Device2 may not be trivial and needs to be studied.
