### ISSUE TITLE
Concurrent reader limit 10 reached!

### ISSUE THREAD

**Issue by lilililizheng** [CESNET/netopeer2#1288]
![image](https://user-images.githubusercontent.com/106649263/198516357-5077dc8f-babe-4b41-9c00-f6d5242ab2b4.png)

What's going on here, that I occasionally get this

**Comment by lilililizheng** [comment]
This is true of both sysrepo-plugind and netopeer2-server

**Comment by michalvasko** [comment]
The most probable cause is you executing *sysrepo* code that does not release the context lock (every `*_acquire_*()` function needs a complementing `release` function call). If not that then there may be some bugs in the versions you are using (in `master`, `devel` has lots of fixes compared to that).

**Comment by lilililizheng** [comment]
I'm pretty sure every lock in the plug-in is released.

ly_ctx = sr_acquire_context(sr_session_get_connection(session));
sr_release_context(sr_session_get_connection(session));

These two functions always appear in pairs in code. I have made this mistake for a long time, so I always have the above problem, but after I fix it, it still happens occasionally. This is my software version. Is it too old?
![image](https://user-images.githubusercontent.com/106649263/199423822-c0173d78-ea5a-4c15-91e6-078885cee8ec.png)

**Comment by michalvasko** [comment]
Your version is fairly old so you can try updating it. If you still see the error, I would attempt to fix it somehow if you provide more information about the use-case.

**Comment by lilililizheng** [comment]
Thanks, I always thought the older version would be more stable, but I will update it. By the way, one of the other questions I just got, can I get the xml that the client sends me in the plug-in? I mean at the sysrepo level, I know that the xml is already parsed and written to the database at the netconf level, but I want to get this xml here after the sr_module_change_subscribe function is executed successfully, and I want to back it up and send it to another netconf server.

**Comment by lilililizheng** [comment]
By that I mean assembling database changes into xml, including operations. In this case, I would send the xml directly to the other server and then use the sysrepocfg tool to write the data changes to the database, thus ensuring synchronization between the two machines, which would be difficult if I were to assemble the xml myself from the data and operations provided by the sr_get_change_tree_next function.

**Comment by jktjkt** [comment]
Trying to implement replication via application-level callbacks does not sound like a good idea.

**Comment by michalvasko** [comment]
It seems there is no API but you can get it quite easily. It should be enough to get any change using `sr_get_change_tree_next`, then find the top-level parent of `node`, and print it into XML. But yes, as @jktjkt points out, it is generally not a good idea to try to replicate the data this way because you can easily lose consistency or encounter other problems.

**Comment by lilililizheng** [comment]
But I can't think of any other way to ensure that the data is consistent between the two machines. Do you have any suggestions?

**Comment by michalvasko** [comment]
The problem is with the requirement itself, why should the same data be needed to be on 2 machines?

**Comment by lilililizheng** [comment]
That's what I need. I need to be able to use the other machine when the first one breaks down or the power goes out, and it works just like the first one

**Comment by michalvasko** [comment]
There is no such use-case supported by NETCONF so I would expect you should ideally be connected to both NETCONF servers and the client send all RPCs to both. Other than that you could subscribe to the RPCs on one machine and in the callback send the whole RPC to the other machine, which is probably the most simple and direct way to implement this. This should even allow you to abort the whole RPC in case executing it on machine 2 fails. However, if it then fails on machine 1, there is not a way to revert it on machine 2.

**Comment by lilililizheng** [comment]
thanksthanks
