### ISSUE TITLE
Questions about  rfc6241#section-6.2.1

### ISSUE THREAD

**Issue by rydy** [CESNET/netopeer2#1289]
Hi Michal,

[Version 2.1.23](https://github.com/CESNET/netopeer2/releases/tag/v2.1.23)

I tested sending the following RPCS to get the data.

Sent: 
```
	<get xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
		<filter type="subtree">
			<user-plane-configuration xmlns="urn:o-ran:uplane-conf:1.0">
				<static-low-level-tx-endpoints/>
			</user-plane-configuration>
		</filter>
	</get>
```

Recv: 
```
	<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
	  <user-plane-configuration xmlns="urn:o-ran:uplane-conf:1.0">
		<static-low-level-tx-endpoints>
		  <name>DigitalTxPath0</name>
		  <array>TxArray0</array>
		  <endpoint-type>0</endpoint-type>
		</static-low-level-tx-endpoints>
		<static-low-level-tx-endpoints>
		  <name>DigitalTxPath1</name>
		  <array>TxArray0</array>
		  <endpoint-type>0</endpoint-type>
		</static-low-level-tx-endpoints>
		<static-low-level-tx-endpoints>
		  <name>DigitalTxPath2</name>
		  <array>TxArray0</array>
		  <endpoint-type>0</endpoint-type>
		</static-low-level-tx-endpoints>
		<static-low-level-tx-endpoints>
		  <name>DigitalTxPath3</name>
		  <array>TxArray0</array>
		  <endpoint-type>0</endpoint-type>
		</static-low-level-tx-endpoints>
	  </user-plane-configuration>
	</data>
```

Sent(without namespace): 
```
	<get xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
		<filter type="subtree">
			<user-plane-configuration>
				<static-low-level-tx-endpoints/>
			</user-plane-configuration>
		</filter>
	</get>
```

Recv: 
`		<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"/>`

Refer to [rfc6241#section-6.2.1](https://www.rfc-editor.org/rfc/rfc6241#section-6.2.1) : 

`	If an element within the <filter> element is not qualified by a namespace (e.g., xmlns=""), then the server MUST evaluate all the XML namespaces it supports, when processing that subtree filter node.`

Sending RPC without namespace did not get data, is this not correct?

Thanks.

**Comment by michalvasko** [comment]
Top-level elements without a namespace were not supported, they should now be in the latest version.

**Comment by rydy** [comment]
> Top-level elements without a namespace were not supported, they should now be in the latest version.

Ok, I'll check back with the latest version to see if it's supported.
