### ISSUE TITLE
Invalid SSH_MSG_GLOBAL_REQUEST packet

### ISSUE THREAD

**Issue by lilililizheng** [CESNET/netopeer2#1290]
Hello, when I used the netopeer2-server service, whenever the client connected, I would always keep printing the following content, sometimes the service would disconnect, and after a few seconds to reconnect.
![image](https://user-images.githubusercontent.com/106649263/199719351-f72c1433-127b-4f82-b8aa-fa4a77bb16fe.png)

**Comment by lilililizheng** [comment]
Sometimes the client message cannot be sent or the server message cannot be sent，I used tcpdump to capture packets and found that the server seemed to be constantly sending messages to the client

**Comment by michalvasko** [comment]
What kind of NETCONF client are you using? It does not seem to be a problem with the server but the client.

**Comment by lilililizheng** [comment]
<dependency>
    <groupId>net.juniper.netconf</groupId>
    <artifactId>netconf-java</artifactId>
    <version>2.1.1.6-SNAPSHOT</version>
</dependency>

This is the connected client used on the Java side.But the client shouldn't affect the server, right?

**Comment by lilililizheng** [comment]
![image](https://user-images.githubusercontent.com/106649263/199722566-6f19d8f6-e3b5-4286-92c4-e8a338134399.png)
By the way, this is another problem I encountered today, which I did not encounter again after recompiling

**Comment by lilililizheng** [comment]
![image](https://user-images.githubusercontent.com/106649263/199723951-b8ee7284-52a6-4f46-ac91-4a1bcc0aacf5.png)
This problem occurs when the java client is disconnected

**Comment by michalvasko** [comment]
> But the client shouldn't affect the server, right?

I do not understand, of course the client affects the server. But it continues to work normally, just prints some warnings and errors.

The client seem to have some weird session termination routine, no `GLOBAL_REQUEST` SSH message is defined for NETCONF over SSH so it should not be sending it. And *libssh* actually complains that the packet with this message is itself invalid. The only problem on the server side may perhaps be an old *libssh* version but I doubt it so I think there is nothing for us to do.

**Comment by lilililizheng** [comment]
![image](https://user-images.githubusercontent.com/106649263/199869700-0698b22e-6884-4b34-8b19-c7ad92ef4f38.png)
Now everything I do goes over time

**Comment by lilililizheng** [comment]
hei, I was wondering how netopeer2 can ssh over a key
