### ISSUE TITLE
merge_config.sh manually run error

### ISSUE THREAD

**Issue by mx568549060** [CESNET/netopeer2#1291]
`version:  libnetconf2-2.1.18 libyang-2.0.231 sysrepo-2.1.84 netopeer2-2.1.36`
I cross-compiling netopeer2 .from "README.md",manually run the scripts "setup.sh  merge_hostkey.sh merge_config.sh" on device,the first two run ok,but merge_config.sh run error.

```
# sh ./merge_config-arm.sh 
[INF] Connection 46 created.
[INF] Session 19 (user "root", CID 46) created.
[INF] No datastore changes to apply.
[ERR] Invalid leafref value "genkey" - no existing target instance "/ks:keystore/ks:asymmetric-keys/ks:asymmetric-key/ks:name". (Schema location "/ietf-netconf-server:netconf-server/listen/endpoint/transport/ssh/ssh/ssh-server-parameters/server-identity/host-key/host-key-type/public-key/public-key/local-or-keystore/keystore/keystore-reference", data location "/ietf-netconf-server:netconf-server/listen/endpoint[name='default-ssh']/ssh/ssh-server-parameters/server-identity/host-key[name='default-key']/public-key/keystore-reference".)
[ERR] Validation failed.
sysrepocfg error: Failed to merge edit data (Validation failed)
For more details you may try to increase the verbosity up to "-v3".
```

**Comment by michalvasko** [comment]
Are you sure `merge_hostkey.sh` was applied correctly? The referenced data (that are not found and cause the error) should be set by that script.

**Comment by mx568549060** [comment]
> 
Thanks for reply.
Yes,I am sure, I study the script carefully, error occured when the script set data.
The device ssh service work fine， i can login in device by ssh.

below is the script file
[merge_config-arm.sh.txt](https://github.com/CESNET/netopeer2/files/9936152/merge_config-arm.sh.txt)

**Comment by mx568549060** [comment]
> Are you sure `merge_hostkey.sh` was applied correctly? The referenced data (that are not found and cause the error) should be set by that script.

sorry,I misunderstand what you said.
merge_hostkey.sh run no error reported
```
# sh ./merge_hostkey-arm.sh 
[INF] Connection 49 created.
[INF] Session 22 (user "root", CID 49) created.
[INF] No datastore changes to apply.
```

**Comment by michalvasko** [comment]
Run `sysrepocfg -X -m ietf-keystore`, you should see the `genkey` configured if `merge_hostkey.sh` was successfully applied.

**Comment by mx568549060** [comment]
> Run `sysrepocfg -X -m ietf-keystore`, you should see the `genkey` configured if `merge_hostkey.sh` was successfully applied.

Thank you !
All works fine  already.
I forget upload `openssl ` on devices, and in merge_hostkey.sh maybe i change the `OPENSSL_EXECUTABLE`  that cause no openssl error occur.
```
OPENSSL_EXECUTABLE=/var/netconf/openssl
if [ -n "$OPENSSL_EXECUTABLE" ]; then
```
