### ISSUE TITLE
ssh key

### ISSUE THREAD

**Issue by lilililizheng** [CESNET/netopeer2#1292]
hei, I was wondering how netopeer2 can ssh over a key

**Comment by lilililizheng** [comment]
![image](https://user-images.githubusercontent.com/106649263/199949393-8fed0ee5-0203-4800-b7a7-a818c6075a62.png)
I tried to connect through the key, but encountered this error, I do not know what the path of the relevant key is.

**Comment by michalvasko** [comment]
The client has rejected server host SSH key for some reason, again, nothing to do with the server. Look for the cause in the client output or something like that.

**Comment by lilililizheng** [comment]
ok,thanks
