### ISSUE TITLE
operation  error

### ISSUE THREAD

**Issue by lilililizheng** [CESNET/netopeer2#1294]
![image](https://user-images.githubusercontent.com/106649263/200280456-bdfafac8-0d54-41aa-a203-8dce82dcef4e.png)

I want to move my third row of data to the first row, based on the key value move, I sent the RPC above.But I printed op in the function below, and the result was 3, 1, 0, in that order
![image](https://user-images.githubusercontent.com/106649263/200280117-6dcb1686-d4c5-4784-83ae-395de5a9978a.png)

Did I move the rpc wrong or did I move the operation just like that

**Comment by michalvasko** [comment]
Please also provide the original data and the modified data (after the edit-config was applied).

**Comment by lilililizheng** [comment]
In fact, I only want to receive op= 3, not subsequent op=1 and op=0

**Comment by michalvasko** [comment]
The resulting data look correct. And you got the additional operations (changes) because you have not only changed the order but also modified `row` and `source-row` leaves.

**Comment by lilililizheng** [comment]
thanks
