### ISSUE TITLE
Error in make install with latest release

### ISSUE THREAD

**Issue by ankit7gup** [CESNET/netopeer2#1295]
Hi Michal, 

Getting below error while doing make install in latest release.

-- Installing missing sysrepo modules...
-- Generating a new RSA host key "genkey" if not already added...
CMake Error at cmake_install.cmake:112 (message):
   scripts/merge_hostkey.sh failed: 1

make: *** [install] Error 1

Regards,
Ankit

**Comment by michalvasko** [comment]
As there is no error message whatsoever it is probably a command that should always succeed and I cannot help you. You can try running the script manually and there could be more output.

**Comment by ankit7gup** [comment]
Ok, I ran it manually (also added some prints), below is the observation:

SCRIPT CHANGES:
#!/usr/bin/env bash
set -e
echo "Before sysrepocfg"
# optional env variable override
if [ -n "$SYSREPOCFG_EXECUTABLE" ]; then
    echo "Inside If $SYSREPOCFG_EXECUTABLE"
    SYSREPOCFG="$SYSREPOCFG_EXECUTABLE"
# avoid problems with sudo PATH
elif [ `id -u` -eq 0 ]; then
    echo "In elif"
    SYSREPOCFG=`su -c 'command -v sysrepocfg' -l $USER`

else
    echo "In else"
    SYSREPOCFG=`command -v sysrepocfg`
fi
echo "After Sysrepocfg"

if [ -n "$OPENSSL_EXECUTABLE" ]; then
    OPENSSL="$OPENSSL_EXECUTABLE"
elif [ `id -u` -eq 0 ]; then
    OPENSSL=`su -c 'command -v openssl' -l $USER`
else
    OPENSSL=`command -v openssl`
fi


OUTPUT:
[root@afb84db0ffa3 scripts]#
[root@afb84db0ffa3 scripts]# ./merge_hostkey.sh
Before sysrepocfg
In elif
[root@afb84db0ffa3 scripts]#

**Comment by michalvasko** [comment]
Um, so please run `su -c 'command -v sysrepocfg' -l $USER`. Or maybe first `echo $USER`.

**Comment by ankit7gup** [comment]
[root@afb84db0ffa3 build]# echo  $USER

[root@afb84db0ffa3 build]# su -c 'command -v sysrepocfg' -l $USER
[root@afb84db0ffa3 build]#
[root@afb84db0ffa3 build]# whoami
root

**Comment by jktjkt** [comment]
The `USER` env var is traditionally set by `login(1)`. What kind of environment do you have that this standard variable is unset or empty?

**Comment by ankit7gup** [comment]
This is centos7

**Comment by jktjkt** [comment]
What modifications have been performed on your build machine? I'm getting a properly set up environment which includes `$USER` when I SSH into a standard CentOS7 host. How are you accessing the host, what is the environment, how are you building, etc?

**Comment by michalvasko** [comment]
Could you also please run `command -v openssl`?

**Comment by ankit7gup** [comment]
command -v openssl
/ankit/sysroot_arm/bin/openssl

**Comment by ankit7gup** [comment]
> What modifications have been performed on your build machine? I'm getting a properly set up environment which includes `$USER` when I SSH into a standard CentOS7 host. How are you accessing the host, what is the environment, how are you building, etc?

This is centos7 standard docker image.

**Comment by ankit7gup** [comment]
After changing the script assignment of sysrepocfg and openssl to hardcode "sysrepocfg" and "openssl", make install and script both works fine.

**Comment by michalvasko** [comment]
You are definitely the first having this problem and it may be actually a faulty system but the fix was simple so try it with the latest version, should work without any changes to the scripts.

**Comment by ankit7gup** [comment]
Sure, thanks!
