### ISSUE TITLE
Curl Undefined reference while make

### ISSUE THREAD

**Issue by ankit7gup** [CESNET/netopeer2#1296]
Hi Michal,

If curl is installed, and detected by cmake, it gives undefined reference error while make. Had to pass "-lcurl" in cmake -DCMAKE_EXE_LINKER_FLAGS to make it succeed.

regards,
Ankit

**Comment by michalvasko** [comment]
In *netopeer2* build directory please run `rm -rf *`, `cmake ..` and provide the output. Then, run `VERBOSE=1 make` and provide that output, too.

**Comment by ankit7gup** [comment]
Attached the logs
[screenlog.txt](https://github.com/CESNET/netopeer2/files/9979790/screenlog.txt)

**Comment by michalvasko** [comment]
Thanks, I could not find anything suspicious there. But it seems like the module `FindCURL.cmake` is not doing its job, it is shipped with `cmake`. I am guessing you are using some really old `cmake` version but there is nothing I can do about this, you can try updating it.

**Comment by ankit7gup** [comment]
> Thanks, I could not find anything suspicious there. But it seems like the module `FindCURL.cmake` is not doing its job, it is shipped with `cmake`. I am guessing you are using some really old `cmake` version but there is nothing I can do about this, you can try updating it.

I am using cmake version 3.20.1

**Comment by jktjkt** [comment]
You're apparently trying to build for ARM, yet your build system is using x86_64 libraries and it is invoking a system compiler (which can only produce x86 and x86_64 binaries). That cannot work. You'll have to set up a working cross-compiling environment first. This is a complex task, and it is definitely *not* just a matter of using a `-DCMAKE_INSTALL_PREFIX`. One possible way is to use Buildroot which support building Linux images with sysrepo (and Netopeer2, and...) just fine.

**Comment by jktjkt** [comment]
How does the file `/ankit/sysroot_arm/lib64/cmake/CURL/CURLConfig.cmake` look like, and how was it created?

**Comment by ankit7gup** [comment]
cmake was installed in a user defined path. Attaching the same.
[CURLConfig.cmake.txt](https://github.com/CESNET/netopeer2/files/9980255/CURLConfig.cmake.txt)

**Comment by michalvasko** [comment]
I just needed a moment to properly test it, there is a problem and it should be fixed now. Not sure if correctly (seems a bit cumbersome) but at least it works. I have not used imported `cmake` targets before.

**Comment by ankit7gup** [comment]
Thanks Michal!

**Comment by ankit7gup** [comment]
Yes it works now.
