### ISSUE TITLE
Questions about https://www.rfc-editor.org/rfc/rfc6241#section-4.2.

### ISSUE THREAD

**Issue by rydy** [CESNET/netopeer2#1297]
Hi Michal,

[Version 2.1.23](https://github.com/CESNET/netopeer2/releases/tag/v2.1.42)

I tried sending the following RPC
```
<edit-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <target>
        <running/>
    </target>
    <default-operation>merge</default-operation>
    <test-option>test-then-set</test-option>
    <error-option>continue-on-error</error-option>
    <config>
        <user-plane-configurationxmlns="urn:o-ran:uplane-conf:1.0">
            <low-level-rx-endpoints>
                <name>DigitalRxPath1</name>
                <e-axcid>
                    <o-du-port-bitmask>49152</o-du-port-bitmask>
                    <band-sector-bitmask>16128</band-sector-bitmask>
                    <ccid-bitmask>240</ccid-bitmask>
                    <ru-port-bitmask>15</ru-port-bitmask>
                    <eaxc-id>0</eaxc-id>
                </e-axcid>
            </low-level-rx-endpoints>
        </user-plane-configuration>
    </config>
</edit-config>
```

Refer to [rfc6241#section-4.3](https://www.rfc-editor.org/rfc/rfc6241#section-4.3), I expect to receive a reply in the following format.
```
<rpc-reply xmlns="URN" xmlns:junos="URL">
    <rpc-error>
        <error-severity>error-severity</error-severity>
        <error-path>error-path</error-path>
        <error-message>error-message</error-message>
        <error-info>...</error-info>
    </rpc-error>
</rpc-reply>
```

I actually received was the following, ls the reply correct?

```
Recv: ERROR	type:     application

	tag:      operation-failed

	severity: error

	message:  User callback failed



	type:     application

	tag:      operation-failed

	severity: error

	message:  User callback failed.

```

Thanks,
Best regards.

**Comment by michalvasko** [comment]
It is just how the CLI outputs the error, it is received as an XML. But I am wondering why did you get 2 `User callback failed.` errors. That should not happen unless you generated one yourself in some callback.

**Comment by rydy** [comment]
> It is just how the CLI outputs the error, it is received as an XML. But I am wondering why did you get 2 `User callback failed.` errors. That should not happen unless you generated one yourself in some callback.

Yes, I generated the `User callback failed.` ,  I didn't use netopeer2-cli, I used the netconf clent meter, and  I should get an XML-related reply.

**Comment by michalvasko** [comment]
In that case it is your NETCONF client that formats the error, I assure you the server sends it in the correct XML form.

**Comment by rydy** [comment]
> > In that case it is your NETCONF client that formats the error, I assure you the server sends it in the correct XML form.
> 
> Ok, I will checke it.

I used Netconf-client meter of the third-party to test netopeer2-server,  Netconf-client meter of the third-party received was the following.
```
ERROR	type:     application

	tag:      operation-failed

	severity: error

	message:  User callback failed



	type:     application

	tag:      operation-failed

	severity: error

	message:  User callback failed.
```
I'm not sure which side is the problem, Is there any way to print the relevant xml reply on the netopeer2-server?

**Comment by michalvasko** [comment]
Yes, you can run `# netopeer2-server -d -c MSG` and the server will print all received and sent messages but be aware of NETCONF chunk-framing mechanism (the messages will be split and include chunking metadata).

**Comment by rydy** [comment]
> -c MSG



> It is just how the CLI outputs the error, it is received as an XML. But I am wondering why did you get 2 `User callback failed.` errors. That should not happen unless you generated one yourself in some callback.

I return ‘SR_ERR_CALLBACK_FAILED’ in the callback，I don't know why I replied twice.

```
[INF]: SR: Published event "rpc" "/ietf-netconf:edit-config" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: NP: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
[INF]: SR: Published event "update" "o-ran-aggregation-base" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Event "update" with ID 1 priority 0 succeeded.
[INF]: SR: Published event "change" "o-ran-aggregation-base" with ID 1 priority 0 for 1 subscribers.
[ERR]: SR: User callback failed
[WRN]: SR: Event "change" with ID 1 priority 0 failed (User callback failed).
[ERR]: SR: User callback failed.
[INF]: SR: Failed processing of "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[ERR]: SR: User callback failed
[WRN]: SR: Event "rpc" with ID 1 priority 0 failed (User callback failed).
[ERR]: SR: User callback failed.
[ERR]: NP: Failed to send an RPC (User callback failed).
[DBG]: LN: Session 1: Sending message:

#490


[DBG]: LN: Session 1: Sending message:
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="75"><rpc-error><error-type>application</error-type><error-tag>operation-failed</error-tag><error-severity>error</error-severity><error-message xml:lang="en">User callback failed</error-message></rpc-error><rpc-error><error-type>application</error-type><error-tag>operation-failed</error-tag><error-severity>error</error-severity><error-message xml:lang="en">User callback failed.</error-message></rpc-error></rpc-reply>

[DBG]: LN: Session 1: Sending message:

##


[INF]: NP: Session 1: thread 1 event new RPC.
[INF]: NP: Session 1: thread 1 event reply error.

```

**Comment by michalvasko** [comment]
No, you have replied only once but the other reply is automatically generated for any callback-generated error. In this case it results in 2 same errors but I am not sure what to do about it. The distinction between callback-generated and library-generated errors seems useful to me.

**Comment by rydy** [comment]
> No, you have replied only once but the other reply is automatically generated for any callback-generated error. In this case it results in 2 same errors but I am not sure what to do about it. The distinction between callback-generated and library-generated errors seems useful to me.

Refer to [rfc6241#section-4.3](https://www.rfc-editor.org/rfc/rfc6241#section-4.3), As I understand it, there should be only one error reply, Otherwise, it is incompatible with the netconf-client of the third-party.  What do you think?

**Comment by michalvasko** [comment]
Read the second paragraph. All you need to know is that almost certainly you would get some invalid-reply error in your NETCONF client in case it receives invalid `<error-reply>`. Since you see the error displayed, it is valid.

**Comment by rydy** [comment]
> Read the second paragraph. All you need to know is that almost certainly you would get some invalid-reply error in your NETCONF client in case it receives invalid `<error-reply>`. Since you see the error-reply displayed, it is valid.

I see, thanks for your help.
