### ISSUE TITLE
libyang fails to load yang module

### ISSUE THREAD

**Issue by joanlandry** [CESNET/Netopeer2#13]
I loaded the yang model into the /etc/sysrepo/yang directory:
and try to install it:

sysrepoctl --install --yang=/etc/sysrepo/yang/ietf-netconf-server.yang --owner=root:root --permissions=666
Installing a new module from file '/etc/sysrepo/yang/ietf-netconf-server.yang' ...
Error: Unable to load the module by libyang.
Install operation cancelled.

**Comment by michalvasko** [comment]
Hi,
the problem will likely be in the ietf-netconf-server YANG version. If you are using the newest draft module, it is YANG 1.1 and this is not yet supported in libyang. However, if you try the devel branch of libyang, it should work. Do not forget to include all the module's imports in the same directory as the main module for sysrepoctl to be able to find them.

Regards,
Michal

**Comment by joanlandry** [comment]
thanks for the info
