### ISSUE TITLE
Disable writable-running is NOT able to recognize ietf module in client

### ISSUE THREAD

**Issue by vishalwc** [CESNET/Netopeer2#130]
using Netopper disable API , disabled  writable-running capability on the server but client is not able to recognize the ietf modules. see the logs below .
expectation is it should recognize and get the configuration .

secondly will it work , the sysrepo API can modify the running datastore ? 

Server Protocol Capabilities
```
   base:1.0
   candidate:1.0
   rollback-on-error:1.0
   startup:1.0
   xpath:1.0
   notification:1.0
   interleave:1.0
   with-defaults:1.0
   base:1.1
   validate:1.1
```

Server Module Capabilities
```
   ietf-yang-metadata@2016-08-05
   yang@2017-02-20
   ietf-inet-types@2013-07-15
   ietf-yang-types@2013-07-15
   ietf-yang-library@2016-06-21
   ietf-netconf@2011-06-01
      Features:
         candidate
         rollback-on-error
         validate
         startup
         xpath
   ietf-netconf-monitoring@2010-10-04
   ietf-netconf-with-defaults@2011-06-01
   notifications@2008-07-14
   nc-notifications@2008-07-14
   ietf-netconf-notifications@2012-02-06
```

ietf_system ietf_interface missing .....

**Comment by michalvasko** [comment]
Hi,
firstly, this may somehow be caused by your changes. Secondly, were `ietf-system` and `ietf-interfaces` installed before your change? What is the output of `sysrepoctl -l`?

Regards,
Michal

**Comment by vishalwc** [comment]
[root@MaestrOS ~]# sysrepoctl -l
Sysrepo schema directory: /etc/sysrepo/yang/
Sysrepo data directory:   /etc/sysrepo/data/
(Do not alter contents of these directories manually)

Module Name                   | Revision   | Data Owner          | Permissions | Submodules                    | Enabled Features
---------------------------------------------------------------------------------------------------------------------------------
ietf-inet-types               | 2013-07-15 |                     |             |                               |
ietf-yang-types               | 2013-07-15 |                     |             |                               |
ietf-netconf-monitoring       | 2010-10-04 | root:root           | 666         |                               |
ietf-netconf-acm              | 2012-02-22 | root:root           | 666         |                               |
ietf-netconf                  | 2011-06-01 | root:root           | 666         |                               |
ietf-interfaces               | 2014-05-08 | root:root           | 666         |                               | if-mib
iana-if-type                  | 2014-05-08 |                     |             |                               |
ietf-netconf-with-defaults    | 2011-06-01 |                     |             |                               |
ietf-system                   | 2014-08-06 | root:root           | 666         |                               |
iana-crypt-hash               | 2014-08-06 |                     |             |                               |
ietf-netconf-server           | 2016-11-02 | root:root           | 666         |                               | listen ssh-listen tls-listen call-home ssh-call-home tls-call-home
ietf-x509-cert-to-name        | 2014-12-10 |                     |             |                               |
ietf-ssh-server               | 2016-11-02 |                     |             |                               |
ietf-keystore                 | 2016-10-31 | root:root           | 666         |                               |
ietf-tls-server               | 2016-11-02 |                     |             |                               |
ietf-netconf-notifications    | 2012-02-06 | root:root           | 666         |                               |
nc-notifications              | 2008-07-14 | root:root           | 666         |                               |

**Comment by michalvasko** [comment]
Okay, seems fine, so next please send the output of `netopeer2-server -d -v2`.

Regards,
Michal

**Comment by vishalwc** [comment]
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Connected to daemon Sysrepo Engine at socket=/var/run/sysrepod.sock
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Netopeer2 connected to sysrepod.
Apr 19 22:17:31 MaestrOS sysrepod[16176]: [INF] New session created successfully, real user=root, effective user=(null), session id=53065789.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Extension plugin "/usr/local/lib64/libyang/metadata.so" successfully loaded.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Extension plugin "/usr/local/lib64/libyang/nacm.so" successfully loaded.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Reading module "ietf-yang-metadata".
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Module "ietf-yang-metadata" successfully parsed.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Reading module "yang".
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Resolving "yang" unresolved schema nodes and their constraints...
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: All "yang" schema nodes and constraints resolved.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Module "yang" successfully parsed.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Reading module "ietf-inet-types".
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Resolving derived type "union" failed, it will be attempted later.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Resolving type default "" failed, it will be attempted later.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Resolving derived type "union" failed, it will be attempted later.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Resolving type default "" failed, it will be attempted later.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Resolving derived type "union" failed, it will be attempted later.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Resolving type default "" failed, it will be attempted later.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Resolving derived type "union" failed, it will be attempted later.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Resolving type default "" failed, it will be attempted later.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: All "ietf-inet-types" schema nodes and constraints resolved.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Module "ietf-inet-types" successfully parsed.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Reading module "ietf-yang-types".
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Module "ietf-yang-types" successfully parsed.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Reading module "ietf-yang-library".
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Module "ietf-yang-library" successfully parsed.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Reading module "ietf-netconf".
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Module "ietf-netconf" successfully parsed.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Reading module "ietf-netconf-monitoring".
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Module "ietf-netconf-monitoring" successfully parsed.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Reading module "ietf-netconf-with-defaults".
Apr 19 22:17:31 MaestrOS sysrepod[16176]: [INF] Get schema 'ietf-netconf', revision: '(null)', submodule: '(null)', submodule revision: '(null)'
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Reading module "ietf-netconf".
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Module "ietf-netconf" already in context.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Module "ietf-netconf" successfully parsed.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Module "ietf-netconf-with-defaults" successfully parsed.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Reading module "notifications".
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Module "notifications" successfully parsed.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Reading module "nc-notifications".
Apr 19 22:17:31 MaestrOS sysrepod[16176]: [INF] Get schema 'notifications', revision: '(null)', submodule: '(null)', submodule revision: '(null)'
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Reading module "notifications".
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Module "notifications" already in context.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Module "notifications" successfully parsed.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Module "nc-notifications" successfully parsed.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Reading module "ietf-netconf-notifications".
Apr 19 22:17:31 MaestrOS sysrepod[16176]: [INF] Get schema 'ietf-netconf', revision: '(null)', submodule: '(null)', submodule revision: '(null)'
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Reading module "ietf-netconf".
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Module "ietf-netconf" already in context.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Module "ietf-netconf" successfully parsed.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Resolving XPath expressions of "killed-by" failed, it will be attempted later.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Resolving XPath expressions of "common-session-parms" failed, it will be attempted later.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Resolving "ietf-netconf-notifications" unresolved schema nodes and their constraints...
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: All "ietf-netconf-notifications" schema nodes and constraints resolved.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Module "ietf-netconf-notifications" successfully parsed.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Sysrepo does not have the "ietf-netconf-server" module or keystored keys dir unknown, using default NETCONF server options.
Apr 19 22:17:31 MaestrOS netopeer2-server[23284]: Listening on 0.0.0.0:830 for SSH connections.

**Comment by michalvasko** [comment]
There seems to be something wrong because `sysrepoctl` lists a different set of modules that `netopeer2-server`. Could you maybe now provide `repository/data/internal/sysrepo-module-dependencies.xml`?

Regards,
Michal

**Comment by vishalwc** [comment]
<module xmlns="urn:ietf:params:xml:ns:yang:sysrepo-module-dependencies">
  <name>ietf-inet-types</name>
  <revision>2013-07-15</revision>
  <prefix>inet</prefix>
  <namespace>urn:ietf:params:xml:ns:yang:ietf-inet-types</namespace>
  <filepath>/etc/sysrepo/yang/ietf-inet-types@2013-07-15.yang</filepath>
  <latest-revision>true</latest-revision>
  <submodule>false</submodule>
  <implemented>true</implemented>
  <has-data>false</has-data>
  <has-persist>false</has-persist>
</module>
<module xmlns="urn:ietf:params:xml:ns:yang:sysrepo-module-dependencies">
  <name>ietf-yang-types</name>
  <revision>2013-07-15</revision>
  <prefix>yang</prefix>
  <namespace>urn:ietf:params:xml:ns:yang:ietf-yang-types</namespace>
  <filepath>/etc/sysrepo/yang/ietf-yang-types@2013-07-15.yang</filepath>
  <latest-revision>true</latest-revision>
  <submodule>false</submodule>
  <implemented>true</implemented>
  <has-data>false</has-data>
  <has-persist>false</has-persist>
</module>
<module xmlns="urn:ietf:params:xml:ns:yang:sysrepo-module-dependencies">
  <name>ietf-netconf-monitoring</name>
  <revision>2010-10-04</revision>
  <prefix>ncm</prefix>
  <namespace>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring</namespace>
  <filepath>/etc/sysrepo/yang/ietf-netconf-monitoring@2010-10-04.yang</filepath>
  <latest-revision>true</latest-revision>
  <submodule>false</submodule>
  <implemented>true</implemented>
  <has-data>true</has-data>
  <has-persist>true</has-persist>
  <instance-identifiers>
    <instance-identifier>
      <xpath>/ietf-netconf-monitoring:netconf-state/datastores/datastore/locks/partial-lock/locked-node</xpath>
      <orig-module-revision>2010-10-04</orig-module-revision>
      <orig-module-name>ietf-netconf-monitoring</orig-module-name>
    </instance-identifier>
  </instance-identifiers>
  <op-data-subtrees>
    <op-data-subtree>
      <xpath>/ietf-netconf-monitoring:netconf-state</xpath>
      <orig-module-revision>2010-10-04</orig-module-revision>
      <orig-module-name>ietf-netconf-monitoring</orig-module-name>
    </op-data-subtree>
  </op-data-subtrees>
</module>
<module xmlns="urn:ietf:params:xml:ns:yang:sysrepo-module-dependencies">
  <name>ietf-netconf-acm</name>
  <revision>2012-02-22</revision>
  <prefix>nacm</prefix>
  <namespace>urn:ietf:params:xml:ns:yang:ietf-netconf-acm</namespace>
  <filepath>/etc/sysrepo/yang/ietf-netconf-acm@2012-02-22.yang</filepath>
  <latest-revision>true</latest-revision>
  <submodule>false</submodule>
  <implemented>true</implemented>
  <has-data>true</has-data>
  <has-persist>true</has-persist>
  <op-data-subtrees>
    <op-data-subtree>
      <xpath>/ietf-netconf-acm:nacm/denied-operations</xpath>
      <orig-module-revision>2012-02-22</orig-module-revision>
      <orig-module-name>ietf-netconf-acm</orig-module-name>
    </op-data-subtree>
    <op-data-subtree>
      <xpath>/ietf-netconf-acm:nacm/denied-data-writes</xpath>
      <orig-module-revision>2012-02-22</orig-module-revision>
      <orig-module-name>ietf-netconf-acm</orig-module-name>
    </op-data-subtree>
    <op-data-subtree>
      <xpath>/ietf-netconf-acm:nacm/denied-notifications</xpath>
      <orig-module-revision>2012-02-22</orig-module-revision>
      <orig-module-name>ietf-netconf-acm</orig-module-name>
    </op-data-subtree>
  </op-data-subtrees>
</module>
<module xmlns="urn:ietf:params:xml:ns:yang:sysrepo-module-dependencies">
  <name>ietf-netconf</name>
  <revision>2011-06-01</revision>
  <prefix>nc</prefix>
  <namespace>urn:ietf:params:xml:ns:netconf:base:1.0</namespace>
  <filepath>/etc/sysrepo/yang/ietf-netconf@2011-06-01.yang</filepath>
  <latest-revision>true</latest-revision>
  <submodule>false</submodule>
  <implemented>true</implemented>
  <has-data>true</has-data>
  <has-persist>true</has-persist>
  <dependencies>
    <dependency>
      <module-name>ietf-netconf-acm</module-name>
      <module-revision>2012-02-22</module-revision>
      <type>import</type>
    </dependency>
    <dependency>
      <module-name>ietf-netconf-with-defaults</module-name>
      <module-revision>2011-06-01</module-revision>
      <type>extension</type>
    </dependency>
  </dependencies>
</module>
<module xmlns="urn:ietf:params:xml:ns:yang:sysrepo-module-dependencies">
  <name>ietf-interfaces</name>
  <revision>2014-05-08</revision>
  <prefix>if</prefix>
  <namespace>urn:ietf:params:xml:ns:yang:ietf-interfaces</namespace>
  <filepath>/etc/sysrepo/yang/ietf-interfaces@2014-05-08.yang</filepath>
  <latest-revision>true</latest-revision>
  <submodule>false</submodule>
  <implemented>true</implemented>
  <has-data>true</has-data>
  <has-persist>true</has-persist>
  <op-data-subtrees>
    <op-data-subtree>
      <xpath>/ietf-interfaces:interfaces-state</xpath>
      <orig-module-revision>2014-05-08</orig-module-revision>
      <orig-module-name>ietf-interfaces</orig-module-name>
    </op-data-subtree>
  </op-data-subtrees>
  <dependencies>
    <dependency>
      <module-name>iana-if-type</module-name>
      <module-revision>2014-05-08</module-revision>
      <type>extension</type>
    </dependency>
    <dependency>
      <module-name>adva-ensemble-interfaces</module-name>
      <module-revision>2016-11-09</module-revision>
      <type>extension</type>
    </dependency>
  </dependencies>
</module>
<module xmlns="urn:ietf:params:xml:ns:yang:sysrepo-module-dependencies">
  <name>iana-if-type</name>
  <revision>2014-05-08</revision>
  <prefix>ianaift</prefix>
  <namespace>urn:ietf:params:xml:ns:yang:iana-if-type</namespace>
  <filepath>/etc/sysrepo/yang/iana-if-type@2014-05-08.yang</filepath>
  <latest-revision>true</latest-revision>
  <submodule>false</submodule>
  <implemented>true</implemented>
  <has-data>false</has-data>
  <has-persist>false</has-persist>
  <dependencies>
    <dependency>
      <module-name>ietf-interfaces</module-name>
      <module-revision>2014-05-08</module-revision>
      <type>import</type>
    </dependency>
  </dependencies>
</module>
<module xmlns="urn:ietf:params:xml:ns:yang:sysrepo-module-dependencies">
  <name>ietf-netconf-with-defaults</name>
  <revision>2011-06-01</revision>
  <prefix>ncwd</prefix>
  <namespace>urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults</namespace>
  <filepath>/etc/sysrepo/yang/ietf-netconf-with-defaults@2011-06-01.yang</filepath>
  <latest-revision>true</latest-revision>
  <submodule>false</submodule>
  <implemented>true</implemented>
  <has-data>false</has-data>
  <has-persist>false</has-persist>
  <dependencies>
    <dependency>
      <module-name>ietf-netconf</module-name>
      <module-revision>2011-06-01</module-revision>
      <type>import</type>
    </dependency>
  </dependencies>
</module>
<module xmlns="urn:ietf:params:xml:ns:yang:sysrepo-module-dependencies">
  <name>ietf-system</name>
  <revision>2014-08-06</revision>
  <prefix>sys</prefix>
  <namespace>urn:ietf:params:xml:ns:yang:ietf-system</namespace>
  <filepath>/etc/sysrepo/yang/ietf-system@2014-08-06.yang</filepath>
  <latest-revision>true</latest-revision>
  <submodule>false</submodule>
  <implemented>true</implemented>
  <has-data>true</has-data>
  <has-persist>true</has-persist>
  <dependencies>
    <dependency>
      <module-name>ietf-netconf-acm</module-name>
      <module-revision>2012-02-22</module-revision>
      <type>import</type>
    </dependency>
    <dependency>
      <module-name>iana-crypt-hash</module-name>
      <module-revision>2014-08-06</module-revision>
      <type>import</type>
    </dependency>
    <dependency>
      <module-name>adva-ensemble-system</module-name>
      <module-revision>2016-10-06</module-revision>
      <type>extension</type>
    </dependency>
    <dependency>
      <module-name>adva-ensemble-system-info</module-name>
      <module-revision>2016-10-06</module-revision>
      <type>extension</type>
    </dependency>
  </dependencies>
  <op-data-subtrees>
    <op-data-subtree>
      <xpath>/ietf-system:system-state</xpath>
      <orig-module-revision>2014-08-06</orig-module-revision>
      <orig-module-name>ietf-system</orig-module-name>
    </op-data-subtree>
  </op-data-subtrees>
</module>
<module xmlns="urn:ietf:params:xml:ns:yang:sysrepo-module-dependencies">
  <name>iana-crypt-hash</name>
  <revision>2014-08-06</revision>
  <prefix>ianach</prefix>
  <namespace>urn:ietf:params:xml:ns:yang:iana-crypt-hash</namespace>
  <filepath>/etc/sysrepo/yang/iana-crypt-hash@2014-08-06.yang</filepath>
  <latest-revision>true</latest-revision>
  <submodule>false</submodule>
  <implemented>true</implemented>
  <has-data>false</has-data>
  <has-persist>true</has-persist>
</module>
<module xmlns="urn:ietf:params:xml:ns:yang:sysrepo-module-dependencies">
  <name>ietf-netconf-server</name>
  <revision>2016-11-02</revision>
  <prefix>ncs</prefix>
  <namespace>urn:ietf:params:xml:ns:yang:ietf-netconf-server</namespace>
  <filepath>/etc/sysrepo/yang/ietf-netconf-server@2016-11-02.yang</filepath>
  <latest-revision>true</latest-revision>
  <submodule>false</submodule>
  <implemented>true</implemented>
  <has-data>true</has-data>
  <has-persist>true</has-persist>
  <dependencies>
    <dependency>
      <module-name>ietf-x509-cert-to-name</module-name>
      <module-revision>2014-12-10</module-revision>
      <type>import</type>
    </dependency>
    <dependency>
      <module-name>ietf-ssh-server</module-name>
      <module-revision>2016-11-02</module-revision>
      <type>import</type>
    </dependency>
    <dependency>
      <module-name>ietf-tls-server</module-name>
      <module-revision>2016-11-02</module-revision>
      <type>import</type>
    </dependency>
    <dependency>
      <module-name>ietf-keystore</module-name>
      <module-revision>2016-10-31</module-revision>
      <type>data</type>
      <orig-modules>
        <orig-module>
          <orig-module-name>ietf-netconf-server</orig-module-name>
          <orig-module-revision>2016-11-02</orig-module-revision>
        </orig-module>
      </orig-modules>
    </dependency>
    <dependency>
      <module-name>ietf-x509-cert-to-name</module-name>
      <module-revision>2014-12-10</module-revision>
      <type>data</type>
      <orig-modules>
        <orig-module>
          <orig-module-name>ietf-netconf-server</orig-module-name>
          <orig-module-revision>2016-11-02</orig-module-revision>
        </orig-module>
      </orig-modules>
    </dependency>
  </dependencies>
</module>
<module xmlns="urn:ietf:params:xml:ns:yang:sysrepo-module-dependencies">
  <name>ietf-x509-cert-to-name</name>
  <revision>2014-12-10</revision>
  <prefix>x509c2n</prefix>
  <namespace>urn:ietf:params:xml:ns:yang:ietf-x509-cert-to-name</namespace>
  <filepath>/etc/sysrepo/yang/ietf-x509-cert-to-name@2014-12-10.yang</filepath>
  <latest-revision>true</latest-revision>
  <submodule>false</submodule>
  <implemented>false</implemented>
  <has-data>false</has-data>
  <has-persist>false</has-persist>
</module>
<module xmlns="urn:ietf:params:xml:ns:yang:sysrepo-module-dependencies">
  <name>ietf-ssh-server</name>
  <revision>2016-11-02</revision>
  <prefix>sshs</prefix>
  <namespace>urn:ietf:params:xml:ns:yang:ietf-ssh-server</namespace>
  <filepath>/etc/sysrepo/yang/ietf-ssh-server@2016-11-02.yang</filepath>
  <latest-revision>true</latest-revision>
  <submodule>false</submodule>
  <implemented>false</implemented>
  <has-data>false</has-data>
  <has-persist>true</has-persist>
  <dependencies>
    <dependency>
      <module-name>ietf-keystore</module-name>
      <module-revision>2016-10-31</module-revision>
      <type>import</type>
    </dependency>
  </dependencies>
</module>
<module xmlns="urn:ietf:params:xml:ns:yang:sysrepo-module-dependencies">
  <name>ietf-keystore</name>
  <revision>2016-10-31</revision>
  <prefix>ks</prefix>
  <namespace>urn:ietf:params:xml:ns:yang:ietf-keystore</namespace>
  <filepath>/etc/sysrepo/yang/ietf-keystore@2016-10-31.yang</filepath>
  <latest-revision>true</latest-revision>
  <submodule>false</submodule>
  <implemented>false</implemented>
  <has-data>true</has-data>
  <has-persist>true</has-persist>
  <op-data-subtrees>
    <op-data-subtree>
      <xpath>/ietf-keystore:keystore/private-keys/private-key/algorithm</xpath>
      <orig-module-revision>2016-10-31</orig-module-revision>
      <orig-module-name>ietf-keystore</orig-module-name>
    </op-data-subtree>
    <op-data-subtree>
      <xpath>/ietf-keystore:keystore/private-keys/private-key/key-length</xpath>
      <orig-module-revision>2016-10-31</orig-module-revision>
      <orig-module-name>ietf-keystore</orig-module-name>
    </op-data-subtree>
    <op-data-subtree>
      <xpath>/ietf-keystore:keystore/private-keys/private-key/public-key</xpath>
      <orig-module-revision>2016-10-31</orig-module-revision>
      <orig-module-name>ietf-keystore</orig-module-name>
    </op-data-subtree>
  </op-data-subtrees>
  <instance-identifiers>
    <instance-identifier>
      <xpath>/ietf-keystore:certificate-expiration/certificate</xpath>
      <orig-module-revision>2016-10-31</orig-module-revision>
      <orig-module-name>ietf-keystore</orig-module-name>
    </instance-identifier>
  </instance-identifiers>
</module>
<module xmlns="urn:ietf:params:xml:ns:yang:sysrepo-module-dependencies">
  <name>ietf-tls-server</name>
  <revision>2016-11-02</revision>
  <prefix>tlss</prefix>
  <namespace>urn:ietf:params:xml:ns:yang:ietf-tls-server</namespace>
  <filepath>/etc/sysrepo/yang/ietf-tls-server@2016-11-02.yang</filepath>
  <latest-revision>true</latest-revision>
  <submodule>false</submodule>
  <implemented>false</implemented>
  <has-data>false</has-data>
  <has-persist>false</has-persist>
  <dependencies>
    <dependency>
      <module-name>ietf-keystore</module-name>
      <module-revision>2016-10-31</module-revision>
      <type>import</type>
    </dependency>
  </dependencies>
</module>
<module xmlns="urn:ietf:params:xml:ns:yang:sysrepo-module-dependencies">
  <name>ietf-netconf-notifications</name>
  <revision>2012-02-06</revision>
  <prefix>ncn</prefix>
  <namespace>urn:ietf:params:xml:ns:yang:ietf-netconf-notifications</namespace>
  <filepath>/etc/sysrepo/yang/ietf-netconf-notifications@2012-02-06.yang</filepath>
  <latest-revision>true</latest-revision>
  <submodule>false</submodule>
  <implemented>true</implemented>
  <has-data>true</has-data>
  <has-persist>true</has-persist>
  <dependencies>
    <dependency>
      <module-name>ietf-netconf</module-name>
      <module-revision>2011-06-01</module-revision>
      <type>import</type>
    </dependency>
  </dependencies>
  <instance-identifiers>
    <instance-identifier>
      <xpath>/ietf-netconf-notifications:netconf-config-change/edit/target</xpath>
      <orig-module-revision>2012-02-06</orig-module-revision>
      <orig-module-name>ietf-netconf-notifications</orig-module-name>
    </instance-identifier>
  </instance-identifiers>
</module>
<module xmlns="urn:ietf:params:xml:ns:yang:sysrepo-module-dependencies">
  <name>nc-notifications</name>
  <revision>2008-07-14</revision>
  <prefix>manageEvent</prefix>
  <namespace>urn:ietf:params:xml:ns:netmod:notification</namespace>
  <filepath>/etc/sysrepo/yang/nc-notifications@2008-07-14.yang</filepath>
  <latest-revision>true</latest-revision>
  <submodule>false</submodule>
  <implemented>true</implemented>
  <has-data>true</has-data>
  <has-persist>true</has-persist>
  <dependencies>
    <dependency>
      <module-name>notifications</module-name>
      <module-revision>2008-07-14</module-revision>
      <type>import</type>
    </dependency>
  </dependencies>
  <op-data-subtrees>
    <op-data-subtree>
      <xpath>/nc-notifications:netconf</xpath>
      <orig-module-revision>2008-07-14</orig-module-revision>
      <orig-module-name>nc-notifications</orig-module-name>
    </op-data-subtree>
  </op-data-subtrees>
</module>
<module xmlns="urn:ietf:params:xml:ns:yang:sysrepo-module-dependencies">
  <name>notifications</name>
  <revision>2008-07-14</revision>
  <prefix>ncEvent</prefix>
  <namespace>urn:ietf:params:xml:ns:netconf:notification:1.0</namespace>
  <filepath>/etc/sysrepo/yang/notifications@2008-07-14.yang</filepath>
  <latest-revision>true</latest-revision>
  <submodule>false</submodule>
  <implemented>false</implemented>
  <has-data>true</has-data>
  <has-persist>true</has-persist>
  <op-data-subtrees>
    <op-data-subtree>
      <xpath>/notifications:notification</xpath>
      <orig-module-revision>2008-07-14</orig-module-revision>
      <orig-module-name>notifications</orig-module-name>
    </op-data-subtree>
  </op-data-subtrees>
</module>

**Comment by vishalwc** [comment]
[sysrepo-module-dependencies.zip](https://github.com/CESNET/Netopeer2/files/942854/sysrepo-module-dependencies.zip)
added the file

**Comment by michalvasko** [comment]
Hmm, it also seems correct so my bet is on you having some mixed-up installation of *sysrepo*, `sysrepoctl` reads the modules from one path, `sysrepod` from another. So, try to correctly uninstall everything and then install it all again.

Regards,
Michal

**Comment by vishalwc** [comment]
I have just updated , disable changes and build the netopeer2 alone with other old lib ( sysrepo , libnetconf2 etc )  and did the installation .

Now here the problem I observed by updating the sysrepo to latest 

Changes in 2f9a23e is causing below configuration to fail and hence 830 port is not coming up 

netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <listen>
    <endpoint>
      <name>test_ssh_listen_endpt</name>
      <ssh>
        <address>0.0.0.0</address>
        <port>830</port>
        <host-keys>
          <host-key>
            <name>test_ssh_listen_key</name>
            <public-key>ssh_host_rsa_key</public-key>
          </host-key>
        </host-keys>
      </ssh>
    </endpoint>
  </listen>
</netconf-server>

**Comment by michalvasko** [comment]
Hi,
I have just tried a fresh installation of everything and it worked fine for me, the default configuration was applied and I connected with `netopeer2-cli` on port `830`, so what exactly does not work for you?

Regards,
Michal

**Comment by vishalwc** [comment]
This is the error logs with latest library for above configuration in xml file 
sysrepocfg -l 4 -d startup -i /etc/sysrepo/yang/init.xml ietf-netconf-server


[ERR] Error by processing of the get-items request (session id=1650637412): Resolving XPath expression "/ietf-x509-cert-to-name:*//." failed..
[ERR] Sending get_items request failed '/ietf-x509-cert-to-name:*//.'
[ERR] Error by sr_get_items_iter: Request contains unknown element
[DBG] Sending get-items request.
[DBG] get-items request sent, waiting for response.
[DBG] get-items response received, processing.
[DBG] No items found for xpath '/ietf-netconf-server:*//.'
[DBG] <LYD_DIFF_CREATED> parent: /ietf-netconf-server:netconf-server/listen, new node: /ietf-netconf-server:netconf-server/listen/endpoint[name='test_ssh_listen_endpt']
[DBG] Sending set-item request.
[DBG] set-item request sent, waiting for response.
[DBG] set-item response received, processing.
[DBG] Sending set-item request.
[DBG] set-item request sent, waiting for response.
[DBG] set-item response received, processing.
[DBG] Sending set-item request.
[DBG] set-item request sent, waiting for response.
[DBG] set-item response received, processing.
[DBG] Sending set-item request.
[DBG] set-item request sent, waiting for response.
[DBG] set-item response received, processing.
[DBG] Sending set-item request.
[DBG] set-item request sent, waiting for response.
[DBG] set-item response received, processing.
[DBG] Sending commit request.
[DBG] commit request sent, waiting for response.
[DBG] commit response received, processing.
[ERR] Commit operation failed with 1 error(s).
[ERR] Error returned from sr_commit: Validation of the changes failed.
[ERR] /ietf-netconf-server:netconf-server/listen/endpoint[name='test_ssh_listen_endpt']/ssh/host-keys/host-key[name='test_ssh_listen_key']/public-key : Leafref "/ietf-keystore:keystore/ietf-keystore:private-keys/ietf-keystore:private-key/ietf-keystore:name" of value "ssh_host_rsa_key" points to a non-existing leaf.
Errors were encountered during importing. Cancelling the operation.
[DBG] Sending session-stop request.
[DBG] session-stop request sent, waiting for response.
[DBG] session-stop response received, processing.

**Comment by michalvasko** [comment]
Hi,
please try the referenced pull request, it should fix this.

Regards,
Michal

**Comment by vishalwc** [comment]
ok Thanks Michal . 
one more question, if  we disable writable running datastore looks like we can lock the running datastore 
is this expected ?

**Comment by michalvasko** [comment]
Hi,
yes, this is expected because it is defined so in NETCONF [RFC](https://tools.ietf.org/html/rfc6241#section-8.2). Anyway, I am not sure whether it makes any sense, you may ask on NETCONF mailing list and if errata are approved, we can talk about changing *netopeer2-server*.

Regards,
Michal
