### ISSUE TITLE
NACM not filtering "get-schema" requests - update

### ISSUE THREAD

**Issue by lucianocuchi** [CESNET/netopeer2#1300]
Related to https://github.com/CESNET/netopeer2/issues/1103

Sorry but I am reopening this issue because it is still happening (I couldn't test thoroughly last time)

**Problem:** 
I am able to download the schema of a yang model with get-schema when NACM rules are forbiding it.

**Environment**
The system is running on a docker with Ubuntu 20.04.5 LTS and:

```
root@b6e1db830473:/# sysrepoctl -V
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.1.84 (SO v7.8.10)


root@b6e1db830473:/# netopeer2-server -V
netopeer2-server 2.1.36
```

**Test detail**
I have tested it with a basic-configuration of deny-all:

```
<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
  <enable-nacm>true</enable-nacm>
  <read-default>deny</read-default>
  <write-default>deny</write-default>
  <exec-default>deny</exec-default>
  <enable-external-groups>true</enable-external-groups>
</nacm>
```

Also tested it with a specific rule for get-schema rpc

```
<!-- DENY GET-SCHEMA RPC -->
<rule>
  <name>DENY_GET_SCHEMA</name>
  <module-name>ietf-netconf-monitoring</module-name>
  <rpc-name>get-schema</rpc-name>
  <access-operations>exec</access-operations>
  <action>deny</action>
</rule
```

And also tested it with rules that deny any access to the module description in ietf-netconf-monitoring::

```
<rule>
    <name>Hide_tibit-netconf_Schema1</name>
    <path  xmlns:ncm="urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring">/ncm:netconf-state/ncm:schemas/ncm:schema[ncm:identifier="tibit-netconf"][ncm:version="2022-07-12"][ncm:format="ncm:yang"]</path>			
    <access-operations>*</access-operations>
    <action>deny</action>
    <comment>Do not allow any access to the TIBIT YANG MODELS schemas</comment>
</rule>
```

In all cases any user can retrieve any YANG module schema with "get-schema" RPC.

Maybe get-schema is still being handled by libnetconf2 and NACM not applied?

Thanks and regards,
Luciano

**Comment by michalvasko** [comment]
I really do not know why would you want to forbid `get-schema`, all the YANG modules should be public and even those that are not must be found on the client side for it to be able to communicate with the server. In any case, it should now work although it required some effort as no simple solution was possible.

**Comment by michalvasko** [comment]
What do you mean it fails? All branches `devel` should definitely work.

**Comment by lucianocuchi** [comment]
Let me check it better tomorrow and I will updat3. I have had a compilation
error using devel branches, maybe my environment

**Comment by lucianocuchi** [comment]
Hi, tested and working fine now with all branches in `devel`

Thanks!

```
<?xml version="1.0" encoding="UTF-8"?> 
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"> 
        <capabilities> 
                <capability>urn:ietf:params:netconf:base:1.0</capability> 
        </capabilities> 
</hello>]]>]]>


<rpc message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
 <get-schema xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring">
   <identifier>ietf-netconf</identifier>
 </get-schema>
</rpc>]]>]]>

<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="101">
  <rpc-error>
    <error-type>protocol</error-type>
    <error-tag>access-denied</error-tag>
    <error-severity>error</error-severity>
    <error-path>/ietf-netconf-monitoring:get-schema</error-path>
    <error-message xml:lang="en">Executing the operation is denied because "netconf" NACM authorization failed.</error-message>
  </rpc-error>
</rpc-reply>]]>]]>
```
