### ISSUE TITLE
The netopeer-server service is terminated

### ISSUE THREAD

**Issue by lilililizheng** [CESNET/netopeer2#1302]
hi
Last night I had netopeer2 running on the server, but today I found that it was terminated.
![image](https://user-images.githubusercontent.com/106649263/203238568-073b4be4-30b5-47b8-8fe4-3fb74aa86114.png)

I checked the coredump file and it was not caused by a crash，and I checked the history, it was not manually killed。Does netopeer2 provide any way to check how it was terminated?

**Comment by michalvasko** [comment]
On any abnormal termination you should see some additional messages, this seems like a standard termination, when the server receives `SIGTERM`.

**Comment by lilililizheng** [comment]
Yes, nothing wrong happened, and I suspect it was accidentally killed by another process
