### ISSUE TITLE
Enable callhome will lead to terminate port 830 on netopeer2-server

### ISSUE THREAD

**Issue by wxes9250310s** [CESNET/netopeer2#1304]
Hi,

I am trying to enable call-home by command "sysrepocfg --import=ssh_callhome.xml -d running -m ietf-netconf-server -f xml".
It seems that everything is fine, and the netconf client can use "listen" to connect to netconf server.
However, I found that port 830 will be terminated once I enable call-home.
Is it a issue?
Can I enable both of call-home and port 830 at the same time?
Thanks.

**Comment by wxes9250310s** [comment]
Hi,

I think I find the way to enable both of them.
In ssh_callhome.xml, I add </listen> part.
Then, I can use both of listen and connect in netopeer2-cli to connect to netopeer2-server.
Thanks.

**Comment by michalvasko** [comment]
> In ssh_callhome.xml, I add part.

That is not a proper solution. You are executing `--import` which does what it implies, imports the configuration **replacing** whatever is there before, which effectively disables listen. If you want to **merge** a configuration into existing one, use `--edit` instead.

**Comment by wxes9250310s** [comment]
Thanks for the explanation!
I did replace --import with --edit to do it, and it works fine.
Thanks again!

**Comment by michalvasko** [comment]
1. `-evim` does not equal `-Evim`, they are different commands.
2. The `import` command simply **replaces** the existing configuration with the new one. `merge`, as the name implies, **merges** the old and the new configuration. Thus preserving the `listen` config, in this case. If you still do not understand then explain what exactly is confusing.

**Comment by awan119** [comment]
I see.
In in my case, I have implemented `sysrepocfg --import=ssh_callhome.xml --format=xml --datastore=running --module=ietf-netconf-server`, then default configuration is replaced by ssh_callhome.xml now.

So how do I get `ietf-netconf-server module` back to default? What is the correct way to do?
I guess one method is to replace module with default listen configuration, but where the defualt xml is in netopeer2 repo?
The other method is to delete ssh_callhome.xml, but I don't still know how to delete it with command.

Sorry for asking very basic question here. Thank you very much.

**Comment by michalvasko** [comment]
I honestly do not know how to explain this to you. I can only write that having the default *netopeer2* installation, run
```
sysrepocfg --edit=ssh_callhome.xml --format=xml --datastore=running --module=ietf-netconf-server
```
and the `listen` configuration will be kept.

**Comment by awan119** [comment]
Thanks for your patience.

Let me clarify my problem now.

Before I ran `sysrepocfg --import=ssh_callhome.xml --format=xml --datastore=running --module=ietf-netconf-server`, port was 830. But now it changes to 4334.

How to use 830 port again when I run `netopeer2-server -d -v 2`?

Log now is below:
```
root@accton:/home/accton/sysrepo_Netopeer2/netopeer2/example_configuration# netopeer2-server -d -v 2
[INF]: SR: Connection 95 created.
[INF]: SR: Session 834 (user "root", CID 95) created.
[INF]: SR: Triggering "ietf-subscribed-notifications" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-keystore" "done" event on enabled data.
[INF]: LN: Call Home client "default-client" endpoint "default-ssh" connecting...
[INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4334.
[INF]: LN: getsockopt() error (Connection refused).
[INF]: SR: Triggering "ietf-truststore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4334.
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4334.
[INF]: LN: getsockopt() error (Connection refused).

```

So I think it causes by importing xml. That's why I want to delete ssh_callhome.xml in module if I could.

Now in the cli terminal I couldn't connect to localhost after importing xml. And you're right that listen is working, but I don't know the password of `root@::ffff:127.0.0.1`...

```
> knownhosts
ID Hostname Algorithm Key

0: [127.0.0.1]:830 ssh-rsa: (key 0)
1: [::ffff:127.0.0.1]:36970 ssh-rsa: (key 1)

> connect --host localhost --port 4334 --login accton
nc ERROR: Unable to connect to localhost:4334 (Connection refused).
cmd_connect: Connecting to the localhost:4334 as user "accton" failed.
>
> connect --host localhost --port 830 --login accton
nc ERROR: Unable to connect to localhost:830 (Connection refused).
cmd_connect: Connecting to the localhost:830 as user "accton" failed.
>
> connect localhost
nc ERROR: Unable to connect to localhost:830 (Connection refused).
cmd_connect: Connecting to the localhost:830 as user "root" failed.
>
> listen
Waiting 60s for an SSH Call Home connection on port 4334...
The authenticity of the host '::ffff:127.0.0.1' cannot be established.
ssh-rsa key fingerprint is 49:f6:59:c7:8a:32:28:e0:d5:ba:8b:a9:04:30:b0:92:ef:8a:55:53.
Are you sure you want to continue connecting (yes/no)? yes
root@::ffff:127.0.0.1 password:
```

Do you have any advice?

**Comment by awan119** [comment]
Hi,

Thank you very much. Now I know the problem I faced was the other question.

I have edited shadow for root user and now I could use both connect and listen module.

Thank you again.
