### ISSUE TITLE
sysrepo-plugind cleanup error

### ISSUE THREAD

**Issue by lilililizheng** [CESNET/netopeer2#1305]
I used the message queue in the plug-in, then executed it, and if I didn't get the msgrcv result, the plug-in would crash. This then causes my entire netopeer2-server service to become unavailable, and when I execute any rpc request in netopeer2-cli it returns me a timeout error.
<img width="447" alt="f015478128e0c9435dc7ce6f2b046fe" src="https://user-images.githubusercontent.com/106649263/204188519-e1e75eee-df8c-4faf-8b0f-4f7616841046.png">

**Comment by lilililizheng** [comment]
When I close sysrepo-plugind-d-v3, it prints:sysrepo-plugind error : Exiting without a proper cleanup，But a problem with one of my plug-ins should not render the entire service useless

**Comment by lilililizheng** [comment]
And I did not restart netopeer2-server to solve the problem, only by executing the setup.sh script to reset the database

**Comment by lilililizheng** [comment]
mkfifo failed appeared when I restarted the plug-in after the problem occurred

[ERR]sysrepo-plugind: Plugin "routeing"initialization failed (System function call failed)
[ERR]mkfifo() failod (Filo oyistsl

**Comment by lilililizheng** [comment]
![image](https://user-images.githubusercontent.com/106649263/204190172-c45b401c-ac0d-4648-a833-134ed7550320.png)
I can only provide clues of possible problems as far as possible. The following is the situation under the event pipo path

**Comment by lilililizheng** [comment]
I have followed the reason, it seems that the event pipo was not cleared correctly when the plug-in was cleared again

**Comment by michalvasko** [comment]
What version of *sysrepo* are you using? I would guess you are doing something in the plugin that you are not supposed to, causing a dead lock or something similar.

**Comment by lilililizheng** [comment]
sysrepocfg - sysrepo configuration manipulation tool, compiled with libsysrepo v2.1.64 (SO v7.6.6)

![image](https://user-images.githubusercontent.com/106649263/204219835-52defc9d-031b-476c-b528-bdac6f2662cc.png)
![image](https://user-images.githubusercontent.com/106649263/204219885-37d5c902-54a9-468b-bd29-13571bf6553d.png)

I use message queue communication in this plug-in, I do not use this in the other plug-ins and do not have this problem

**Comment by michalvasko** [comment]
1. It may be wise to update to the latest version, there are many improvements including some stability fixes that may prevent the RPC problem you encountered.
2. You using "message queue communication" should not matter, in general.
3. If you switch the datastore of `session`, it remains switched for all the other `init` and `cleanup` plugin calls.
4. You are calling `sr_unsubscribe` in the cleanup but I see no subscriptions being made in `init`. Assuming you have posted the whole function.

**Comment by lilililizheng** [comment]
![image](https://user-images.githubusercontent.com/106649263/204222546-3a2c7464-993b-4099-9b46-48c56431656a.png)
This is the following code from the first figure above. By the way, is this a reasonable way to switch databases?

**Comment by michalvasko** [comment]
Okay, then my points 3. and 4. are invalid. There is no other way to switch datastores. So I would suggest you update *sysrepo*. Also, the problem could possibly be in one of the callbacks, the `init` function does not matter. And the the very first log you provided is too trimmed, some previous errors are those that are relevant and cause the RPC to not be processed.

**Comment by lilililizheng** [comment]
Ok, I will update to the latest version. If this problem occurs, I will provide all the log information to you. Thank you for your clarification

**Comment by lilililizheng** [comment]
Hey, if you call back a blocking message in the function, what happens when the message is never received? I found that in the sr_module_change_subscribe function, the plugin cleans normally if I don't block, and if I do block, when I close the plugin, the code doesn't go to sr_plugin_cleanup_cb. It's an abnormal exit

**Comment by lilililizheng** [comment]
In this rpc, for example, I have to wait for the result of msgrcv before I can return the value of the rpc, but if I don't receive the value of msgrcv, that will cause the problem above. The program ends abnormally, and I want to return an error when I don't receive the message for the specified time, rather than keep blocking and exit abnormally

**Comment by michalvasko** [comment]
> if you call back a blocking message in the function, what happens when the message is never received?

There are some rules that are expected not to be broken. You callback is supposed to handle an event and return. Obviously, if you never return the event is blocked indefinitely, which breaks handling the event further. There is no way to prevent this and, like I said, it is expected a callback always returns. So yes, use a timeout after which, if a message is not received, the callback returns, with an error if you want.
