### ISSUE TITLE
Automatic IPv6 call home connection without providing password for listen

### ISSUE THREAD

**Issue by rgaura** [CESNET/netopeer2#1306]
Hello Michal

I have recently got an issue, where we are setting up a call home connection.
 Everything is default as it is mentioned in documentation, no customization.

Sysrepo version: libsysrepo v2.1.64 (SO v7.6.6)

Before starting we have configured ssh_callhome.xml

Started netopeer2-server

It started looking out for the its callhome server:

Point1:

```
[INF]: LN: Trying to connect via IPv6 to ::1:4334.
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Trying to connect via IPv4 to [127.0.0.1:4334](http://127.0.0.1:4334/).
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Trying to connect via IPv6 to ::1:4334.
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Trying to connect via IPv4 to [127.0.0.1:4334](http://127.0.0.1:4334/).
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Trying to connect via IPv6 to ::1:4334.
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Trying to connect via IPv4 to [127.0.0.1:4334](http://127.0.0.1:4334/).
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Trying to connect via IPv6 to ::1:4334.
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Trying to connect via IPv4 to [127.0.0.1:4334](http://127.0.0.1:4334/).
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Trying to connect via IPv6 to ::1:4334.
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Trying to connect via IPv4 to [127.0.0.1:4334](http://127.0.0.1:4334/).
```

But if we see carefully, it tries first for IPv4 and then IPv6 and so on, repetitively.

Query1:

Is it possible to make this whole setup connection using only IPv4 OR Only IPv6, but not together. If possible, how?

===================================

Point2:

Once the successful IPv4 connection is established, we see the following logs:

```
[INF]: LN: Successfully connected to localhost:4334 over IPv6.
[INF]: SR: Session 1478 (user "root", CID 529) created.
[INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: LN: Received an SSH message "request-auth" of subtype "none".
[INF]: LN: Received an SSH message "request-auth" of subtype "password".
[INF]: LN: User "root" authenticated.
[INF]: LN: Received an SSH message "request-channel-open" of subtype "session".
[INF]: LN: Received an SSH message "request-channel" of subtype "subsystem".
[INF]: LN: Call Home client "default-client" session 1 established.
[INF]: SR: Session 1479 (user "root", CID 529) created.
 ```

Query2:

Even if the connection is established over IPv4, it is mentioning IPv6:

"Successfully connected to localhost:4334 over IPv6."

This is confusing.

=====================================

Point3:

There is a special case, where, after starting netopee2-cli and then giving listen and <enter-key> ..
```
> listen
Waiting 60s for an SSH Call Home connection on port 4334...
The authenticity of the host '::1' cannot be established.
ssh-rsa key fingerprint is 15:1f:38:30:bb:64:a6:68:f7:2e:e2:d2:b2:07:69:89:b6:a7:f6:33.
 ```

.. I did not do anything, did not gave the "yes" below, nor the password:
```
Are you sure you want to continue connecting (yes/no)? XXX
nc ERROR: Request authentication methods timeout.
cmd_listen: Receiving SSH Call Home on port 4334 as user "root" failed.
```
.. Then, on the server side, I saw these logs, specially see the line between "[[[[[[INFORMATION]]]]]]" tags:
```
[INF]: LN: Trying to connect via IPv4 to [127.0.0.1:4334](http://127.0.0.1:4334/).
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Trying to connect via IPv6 to ::1:4334.
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Trying to connect via IPv4 to [127.0.0.1:4334](http://127.0.0.1:4334/).
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Trying to connect via IPv6 to ::1:4334.
[[[[[[INFORMATION]]]]]]
[INF]: LN: Successfully connected to localhost:4334 over IPv6.
[INF]: SR: Session 1481 (user "root", CID 529) created.
[ERR]: LN: User failed to authenticate for too long, disconnecting.
[INF]: LN: Trying to connect via IPv6 to ::1:4334.
[INF]: LN: Successfully connected to localhost:4334 over IPv6.
[INF]: SR: Session 1482 (user "root", CID 529) created.
[ERR]: LN: SSH key exchange timeout.
[INF]: LN: Trying to connect via IPv6 to ::1:4334.
[INF]: LN: Successfully connected to localhost:4334 over IPv6.
[INF]: SR: Session 1483 (user "root", CID 529) created.
[ERR]: LN: SSH key exchange timeout.
[INF]: LN: Trying to connect via IPv6 to ::1:4334.
[INF]: LN: Successfully connected to localhost:4334 over IPv6.
[INF]: SR: Session 1484 (user "root", CID 529) ceated.
[ERR]: LN: SSH key exchange timeout.
[INF]: LN: Trying to connect via IPv6 to ::1:4334.
[INF]: LN: Successfully connected to localhost:4334 over IPv6.
[INF]: SR: Session 1485 (user "root", CID 529) created.
[ERR]: LN: SSH key exchange error (Socket error: Connection reset by peer).
[[[[[[INFORMATION]]]]]]
[INF]: LN: Trying to connect via IPv6 to ::1:4334.
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Trying to connect via IPv4 to [127.0.0.1:4334](http://127.0.0.1:4334/).
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Trying to connect via IPv6 to ::1:4334.
[INF]: LN: getsockopt() error (Connection refused).
 ```

This was again confusing. It is informing ..

"Successfully connected to localhost:4334 over IPv6."

.. and then it is informing:
```
[INF]: SR: Session 1481 (user "root", CID 529) created.
[ERR]: LN: User failed to authenticate for too long, disconnecting.
[INF]: LN: Trying to connect via IPv6 to ::1:4334.
```

Is this right flow?

Are you trying to tell here that, socket connection is established but since SSH authentication is failing, I can't let you in?

Otherwise, please correct me

=================================

Point4:

If we see the following logs:
```
[INF]: NP: Session 2: thread 4 event session terminated.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-end).
[INF]: LN: Call Home client "default-client" session terminated.
[2022/11/24 03:32:46.048567, 1] ssh_socket_exception_callback:  Socket exception callback: 1 (0)
[2022/11/24 03:32:46.048616, 1] ssh_socket_exception_callback:  Socket error: disconnected
[ERR]: SR: Internal error (/home/xxx/LIB/netconf/sysrepo-2.1.64/src/common.c:3948).
[ERR]: SR: Internal error (/home/xxx/LIB/netconf/sysrepo-2.1.64/src/common.c:3948).
[INF]: LN: Trying to connect via IPv6 to ::1:4334.
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Trying to connect via IPv4 to [127.0.0.1:4334](http://127.0.0.1:4334/).
[INF]: LN: getsockopt() error (Connection refused).
 ```

After "Socket error: disconnected", there are two lines showing common.c internal error.

This is not some application generated error, this is just for information, correct.

Please suggest on the above points, in case you feel I am wrong anywhere, I request you to correct me.

Thanks

Rajeev

**Comment by michalvasko** [comment]
1. Change the `address` in `ssh_callhome.xml`. There is `localhost` that normally connects on both IPv4 and IPv6 (but it depends on the configuration of your system). You can put an IP address there instead, for example.
2. > Even if the connection is established over IPv4, it is mentioning IPv6:

   No, it attempts to connect using either of them and should then print the protocol that was actually used for the connection. What makes you think it was established using IPv4 if it prints IPv6?
3. You must distinguish between the layers, specifically the protocols used on the layers. To have a working NETCONF session, there must be successful connection made on TCP/IP, SSH, and then NETCONF protocols. What you see is that the first protocol is connected (TCP/IP) but the second one fails (SSH). Exactly what I would expect to happen if you do not authenticate yourself.
4. This problem should be solved in the latest versions of *libnetconf2* and/or *sysrepo*, so just update to get rid of it. But it should cause no real problems, I believe.

**Comment by rgaura** [comment]
Thank you for the response Michal

Regarding 1, 3 and 4, I understood the points, thank you for clarifying.

I have little confusion about point 2.
So, in that case, if it is "localhost" and it will try to connect to either of IPv4 or IPv6, I am always seeing it log as

[INF]: LN: Successfully connected to localhost:4334 over IPv6.
but never on IPv4.

Does it defaults to IPv6 as a standard, considering the future addressing as IPv6.

Thanks
Rajeev

**Comment by michalvasko** [comment]
I think IPv6 is tried first, at least that is what is happening on my system. But it depends on the system and its settings, no way for *libnetconf2* to influence that.
