### ISSUE TITLE
For edit-config operation If RPC have both parent and child node and specify operation="delete" on parent node with default operation as merge, Its returning error.

### ISSUE THREAD

**Issue by ArpitGupta05** [CESNET/netopeer2#1307]
- Below is the current configuration
```
> get-config --source=running --filter-xpath=/network-instances/network-instance
DATA
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <network-instances xmlns="http://openconfig.net/yang/network-instance">
    <network-instance>
      <name>default</name>
      <config>
        <name>default</name>
      </config>
      <protocols>
        <protocol>
          <identifier xmlns:oc-pol-types="http://openconfig.net/yang/policy-types">oc-pol-types:OSPF</identifier>
          <name>105</name>
          <config>
            <identifier xmlns:oc-pol-types="http://openconfig.net/yang/policy-types">oc-pol-types:OSPF</identifier>
            <name>105</name>
            <enabled>true</enabled>
          </config>
        </protocol>
      </protocols>
    </network-instance>
  </network-instances>
</data>
```
- Send edit-config request with below payload
```
cat networkd2.xml
<network-instances xmlns="http://openconfig.net/yang/network-instance" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <network-instance>
    <name>default</name>
    <config>
      <name>default</name>
    </config>
    <protocols>
     <protocol xc:operation="delete">
       <identifier xmlns:oc-pol-types="http://openconfig.net/yang/policy-types">oc-pol-types:OSPF</identifier>
       <name>105</name>
       <config>
         <identifier xmlns:oc-pol-types="http://openconfig.net/yang/policy-types">oc-pol-types:OSPF</identifier>
         <name>105</name>
       </config>
     </protocol>
  </protocols>
  </network-instance>
</network-instances>
```

> edit-config --target=running --config=/home/arpit/sonic/xml/networkd2.xml
ERROR
        type:     protocol
        tag:      data-missing
        severity: error
        message:  **Node "config" to be deleted does not exist.**

>

Netopeer2 logs :
[INF]: SR: Event "rpc" with ID 1 priority 0 succeeded.
[INF]: NP: Session 1: thread 2 event new RPC.
[INF]: SR: Published event "rpc" "/ietf-netconf:get-config" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:get-config" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: SR: Successful processing of "rpc" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 1 priority 0 succeeded.
[INF]: NP: Session 1: thread 0 event new RPC.
[INF]: SR: Published event "rpc" "/ietf-netconf:edit-config" with ID 2 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 2 priority 0 (remaining 1 subscribers).
[INF]: NP: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
**[ERR]: SR: Node "config" to be deleted does not exist.**
[ERR]: SR: Applying operation "delete" failed.
[INF]: SR: Failed processing of "rpc" event with ID 2 priority 0 (remaining 1 subscribers).
[ERR]: SR: NETCONF error occurred.
[WRN]: SR: Event "rpc" with ID 2 priority 0 failed (Item not found).
[ERR]: SR: User callback failed.
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 1: thread 1 event new RPC.
[INF]: NP: Session 1: thread 1 event reply error.

-Delete is working for below payload when only specify parent node 
```
<network-instances xmlns="http://openconfig.net/yang/network-instance" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <network-instance>
    <name>default</name>
    <config>
      <name>default</name>
    </config>
    <protocols>
     <protocol xc:operation="delete">
       <identifier xmlns:oc-pol-types="http://openconfig.net/yang/policy-types">oc-pol-types:OSPF</identifier>
       <name>105</name>
     </protocol>
  </protocols>
  </network-instance>
</network-instances>
```

Please help in it.Thanks in advance.

**Comment by michalvasko** [comment]
What makes you think this is not working correctly? I would partly agree that it may not exactly be expected but I believe this is how the `delete` operation should behave. If you want non-existing edit nodes silently ignored, just use `remove` instead.

**Comment by ArpitGupta05** [comment]
Hi Michalvasko,
Thanks for Reply. I agree that delete operation returns error for non existing configuration.
But Here although configuration exists, delete operation is returning error "config" to be deleted does not exist" .This is the issue.
Please refer enclosed get-config output, configuration exists for both  parent node "protocol [identifier=ospf, name=105]" and child "config [identifier=ospf, name=105]"
but delete operation for "protocol [identifier=ospf, name=105]" is failing even though configuration exist.

**Comment by michalvasko** [comment]
Oh, sorry, have not looked at that. What *sysrepo* version are you using?

**Comment by ArpitGupta05** [comment]
I am using  sysrepo version [v2.2.12] and commit 162c93a644a3e8a6bf18c4d2100067187c243076

git branch
* (HEAD detached at 162c93a6)
  master

**Comment by ArpitGupta05** [comment]
Hi Michalvasko

This issue is the same of https://github.com/sysrepo/sysrepo/issues/2920 and its fixed in Latest SysRepo Version
