### ISSUE TITLE
Question about RESTCONF support

### ISSUE THREAD

**Issue by jamespark76** [CESNET/netopeer2#1309]
Hello @michalvasko,

Do you have any plans to support RESTCONF feature along with current NETCONF server?

I found some previous history about RESTCONF support but there was no more update since last year.
-> RESTCONF server implement #460

Current O-RAN M-Plane specification includes Async Notifications over JSON/REST (HTTP/TLS). 
As you know, ietf-subscribed-notifications supports both NETCONF and RESTCONF.

Best Regards,
James Park

**Comment by michalvasko** [comment]
No, there is currently no plan to support RESTCONF because we do not have a use-case for it.

**Comment by jktjkt** [comment]
And just FYI, we're (slowly) working on a RESTCONF server at https://github.com/CESNET/rousette. [Patches welcome.](https://gerrit.cesnet.cz/q/project:CzechLight/rousette)

**Comment by jamespark76** [comment]
Hello @michalvasko @jktjkt,

Thanks for sharing information.
