### ISSUE TITLE
ly ERROR: Augment target node "private-key-type" in grouping "asymmetric-key-pair-with-certs-grouping" was not found

### ISSUE THREAD

**Issue by rydy** [CESNET/netopeer2#1310]
Hi,

I updated the latest devel branch and the following error occurred via the netopeer2-cli.

netopeer2-cli
```
> connect
root@localhost password:
ly ERROR: Augment target node "private-key-type" in grouping "asymmetric-key-pair-with-certs-grouping" was not found. (/ietf-keystore:keystore/{uses='keystore-grouping'}/asymmetric-keys/asymmetric-key/{uses='ks:asymmetric-key-pair-with-certs-grouping'}/{uses='ct:asymmetric-key-pair-with-certs-grouping'})
cmd_connect: Connecting to the localhost:830 as user "root" failed.
```

By the way, I want to support `schema-mount`, how do set parameter `PATH` in `netopeer2-server`, can you give any examples? 

Thanks,
Best regards.

**Comment by michalvasko** [comment]
The error will most likely be caused by some YANG module incompatibility. It should not occur but you probably have all the old modules downloaded and the client uses them with the new ones that is causing the problems. Try removing all the stored modules, by default in `~/.netopeer2-cli/modules/`.

As for the schema mount, if you want to use it, it is your responsibility to understand it first and I mean it. It is not that simple and the specs are not easy to understand but I am not here to explain the standard but provide support using our tools. But, in short, you need to provide the server with the operational data of `ietf-yang-library` and `ietf-yang-schema-mount` YANG modules.

**Comment by rydy** [comment]
> The error will most likely be caused by some YANG module incompatibility. It should not occur but you probably have all the old modules downloaded and the client uses them with the new ones that is causing the problems. Try removing all the stored modules, by default in `~/.netopeer2-cli/modules/`.
> 
> As for the schema mount, if you want to use it, it is your responsibility to understand it first and I mean it. It is not that simple and the specs are not easy to understand but I am not here to explain the standard but provide support using our tools. But, in short, you need to provide the server with the operational data of `ietf-yang-library` and `ietf-yang-schema-mount` YANG modules.

I see, Thanks.

**Comment by rydy** [comment]
> 

The `~/.netopeer2-cli/modules/` has deleted, but the problem persists.

```
[root@bogon Baicells_O-DU_O1]# rm -rf ~/.netopeer2-cli/modules/
[root@bogon Baicells_O-DU_O1]# netopeer2-cli
> connect
root@localhost password:
ly ERROR: Augment target node "private-key-type" in grouping "asymmetric-key-pair-with-certs-grouping" was not found. (/ietf-keystore:keystore/{uses='keystore-grouping'}/asymmetric-keys/asymmetric-key/{uses='ks:asymmetric-key-pair-with-certs-grouping'}/{uses='ct:asymmetric-key-pair-with-certs-grouping'})
cmd_connect: Connecting to the localhost:830 as user "root" failed.
>


```

**Comment by michalvasko** [comment]
What exactly did you update to `devel`, all the 4 projects (libyang, libnetconf2, sysrepo, netopeer2)?

**Comment by rydy** [comment]
> What exactly did you update to `devel`, all the 4 projects (libyang, libnetconf2, sysrepo, netopeer2)?

Yes，All the 4 projects are `devel`.

**Comment by michalvasko** [comment]
Have you installed your own `ietf-crypto-types` YANG? The supplied revision 2019-07-02 is expected, which matches the supplied `ietf-keystore` revision.

**Comment by rydy** [comment]
> Have you installed your own `ietf-crypto-types` YANG? The supplied revision 2019-07-02 is expected, which matches the supplied `ietf-keystore` revision.

I have installed two versions of `ietf-crypto-types`.

```
sysrepoctl -l
Sysrepo repository: /root/yangr/O1/bin/O-DU/Baicells_O-DU_O1/sysrepo_repository

Module Name                   | Revision   | Flags | Owner     | Startup Perms | Submodules | Features
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
iana-crypt-hash               | 2014-08-06 | i     |           |               |            |
iana-hardware                 | 2018-03-13 | I     | root:root | 600           |            |
iana-if-type                  | 2017-01-19 | I     | root:root | 600           |            |
ietf-crypto-types             | 2019-07-02 | i     |           |               |            |
ietf-crypto-types             | 2019-04-29 | I     | root:root | 600           |            |
ietf-datastores               | 2018-02-14 | I     | root:root | 666           |            |

```

**Comment by michalvasko** [comment]
That will be the problem. `ietf-keystore` does not have import of `ietf-crypto-types` by revision so it probably uses your revision of the module, which has a different non-suitable grouping. Best would be for you not to implement the older revision of the module (there are only typedefs and groupings, you do not need it implemented) and then import it by revision in whatever modules you want. By default, the latest revision should then be imported.
