### ISSUE TITLE
[compile] CMakeLists.txt error

### ISSUE THREAD

**Issue by ydong08** [CESNET/netopeer2#1312]
version: 2.1.42

relevant document: CMakeLists.txt

1. variable 
after calling find_package(OpenSSL), OPENSSL_INCLUDE_DIRS variable  is not exist, correct is OPENSSL_INCLUDE_DIR.

2. include directory
src/common.c -> nc_server.h -> libnetconf2/session_server.h -> openssl/x509.h (if enable NC_ENABLED_TLS) ，compile goes wrong in this case.
my workaround is add "include_directories(${OPENSSL_INCLUDE_DIR})", it looks work well.

**Comment by michalvasko** [comment]
You are right, it seems the singular is used for some reason even though all the other packages always use the plural.
