### ISSUE TITLE
Support of external-client-auth-supported

### ISSUE THREAD

**Issue by robbynet** [CESNET/netopeer2#1319]
At installation step Netopeer2 exposed support of feature local-client-auth-supported
Question : Does Netopeer2 supported feature external-client-auth-supported as well ?

**Comment by michalvasko** [comment]
Well, there is a bit of a mess in the currently used `ietf-netconf-server` YANG modules. The users are being read locally from the system but looking at the module it would probably be considered external. In any case, this is the only way of getting the users currently. We are working on supporting the almost-released draft versions of these YANG modules that should provide much more options but that is far from being finished.

**Comment by robbynet** [comment]
Thanks for the answer
