### ISSUE TITLE
Handling of subtree filters with unknown top-level element

### ISSUE THREAD

**Issue by pfeige** [CESNET/netopeer2#1322]
Hi, I'm referring to the closed [issue #1229](https://github.com/CESNET/netopeer2/issues/1299) concerning the handling of a subtree filter with unknown top-level element for create-subscription. Unfortunately, I could not verify the fix until now. We have two kinds of testcases with such subtree filters one for create-subscription and another for get and get-config. The old behavior of the netopeer2 was to return an rpc-error in case of create-subscription and to return and rpc-reply with empty data in case of get and get-config. I cannot say when exactly this has changed but with the actual implementation both a create-subscription and a get/get-config return an rpc-error for such subtree filters. 

Now my question is: Would it be possible (with reasonable effort) to restore the old behaviour - create-subscription returns rpc-error and get/get-config return empty data? If not, I could also live with the implementation before your fix - a subtree filter with unknown top-level element is ignored for create-subscription and returns empty data for get/get-config. I'm sorry to bother you again with this subject but I think a rpc-error for get/get-config with such a subtree filter is a bit hard and not the appropriate reaction.

**Comment by pfeige** [comment]
We have two different tests uing filters with unknown elements. One test with a RPC create-subscription and one with a RPC get. The test with create-subscriptions expects to get an rpc-error and the test with the get expects empty data. Some time ago these tests were passed with an earlier stack version. Now this behavior has changed - there is always an rpc-error for unknown top-level elements. Thats why my question, whether it would be possible to have the old behaviour back.

**Comment by michalvasko** [comment]
Okay, I think I get it now. But why behave differently in the 2 cases? Your tests failing is obviously not an argument and I think it makes more sense this way.

**Comment by pfeige** [comment]
I don't know, why this was implemented that way first. If you feel the outcome should be the same for such a subtree filter, I have to accept it.

**Comment by michalvasko** [comment]
If you provide some reasonable argument, I have no problem with changing it, I just cannot think of any. There is no purpose in using a filter that can never match any nodes so I think it is beneficial to inform the user about that. Also, the behavior would be consistent, which is also generally desired.

**Comment by pfeige** [comment]
OK, thanks!
