### ISSUE TITLE
NACM read response with no read permit

### ISSUE THREAD

**Issue by jamespark76** [CESNET/netopeer2#1323]
Hello.

I am using netopeer2 v2.1.36.

I configured read/write/exec permission with deny as default, and I did not configure permit action in rule list for specific test yang. 
edit-config and user-rpc returned access-denied error while trying to access this test yang. This access-denied error is expected and correct. 

However, get returned rpc-reply with no data. According to M-Plane specification, netopeer2-server replies access-denied error for get rpc just like edit-config and user-rpc. Is this expected behavior?

```
<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
  <enable-nacm>true</enable-nacm>
  <read-default>deny</read-default>
  <write-default>deny</write-default>
  <exec-default>deny</exec-default>
  <enable-external-groups>false</enable-external-groups>
  <groups>
    <group>
      <name>usergroup</name>
      <user-name>username</user-name>
    </group>
  </groups>
```

```
[edit-config]
ERROR
	type:     protocol
	tag:      access-denied
	severity: error
	path:   xxxxxx
	message:  Executing the operation is denied because "username" NACM authorization failed.

[user-rpc]
ERROR
	type:     protocol
	tag:      access-denied
	severity: error
	path:     xxxxx
	message:  Executing the operation is denied because "username" NACM authorization failed.

[get]
DATA
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"/>

```

Thanks.
James

**Comment by michalvasko** [comment]
> According to M-Plane specification...

Well, *netopeer2* is compliant with the standardized specification in [RFC 8341](https://datatracker.ietf.org/doc/html/rfc8341#section-3-2-4) and behaves accordingly.
