### ISSUE TITLE
Take control on rpc get and rpc get-config

### ISSUE THREAD

**Issue by robbynet** [CESNET/netopeer2#1325]
Hello,
We need to get confirmation on facility provided by Netopeer2.
Looking at current implementation of ietf-netconf:get-config and ietf-netconf:get into Netopeer2 : 

- SR_RPC_SUBSCR("/ietf-netconf:get-config", np2srv_rpc_get_cb);
- SR_RPC_SUBSCR("/ietf-netconf:get", np2srv_rpc_get_cb);

And putting aside the significant effort that should be required by the application.
We do not see any way for an application, that would like to enhance NETCONF Access control on those rpcs, to take control over Netopeer2 on those rpcs via any sort of overloading subscription or other artifact.

Please can you confirm on that ?
Regards.

**Comment by michalvasko** [comment]
No, you cannot influence the output generated by the *netopeer2* RPCs.
