### ISSUE TITLE
[question]TLS callhome established, and send a lot of configurations, then TLSv1.2 Encrypted Alert

### ISSUE THREAD

**Issue by adamzyg** [CESNET/netopeer2#1326]
Hi,
    I encountered a strange problem. After the TLS callhome connection was successful and a lot of configuration data was sent, the callhome client suddenly reported an Encrypted Alert, and then the callhome disconnected. According to the TLSv1.2 protocol, after the handshake is successful, the two parties will negotiate a symmetric encryption algorithm to send data. Why does the Encrypted Alert suddenly appear?
The attachment is the pcap package I captured, can you help me analyze it?
[test1.zip](https://github.com/CESNET/netopeer2/files/10215877/test1.zip)

**Comment by michalvasko** [comment]
> The attachment is the pcap package I captured, can you help me analyze it?

I cannot, sorry, you will to have ask someone with much more insight into TLS than me. For example, the OpenSSL guys, this is not really a *netopeer2* issue.
