### ISSUE TITLE
TLS callhome establishment happens with v1.2 followed by v1 attempts

### ISSUE THREAD

**Issue by Bharanidharan-S** [CESNET/netopeer2#1327]
Dear Team,

We are using TLS call-home feature for client server connection establishment with netopeer2-server 1.1.77 & netopeer2-cli 2.0.64.
Here the client server establishments can happen only with tlsv1.2, lesser versions are omitted.
But what we see from tcpdump, client is sending hello using tlsv1 with multiple attempts & finally it tries to connect using tlsv1.2. Due to which the connection establishment is taking more time.

Below are the server logs where the connection timeout happened for tlsv1.
```
Timed out after 5s (Operation now in progress).
Trying to connect the pending socket 213.
Timed out after 5s (Operation now in progress).
Failed to connect socket 213 after 5 retries, closing.
Trying to connect via IPv6 to fe80::205:b9ff:fe52:8500.
Trying to connect the pending socket 213.
Timed out after 5s (Operation now in progress).
```

For reference, tcpdump shows the retries with tlsv1:
<img width="733" alt="client_hello_v1_v12" src="https://user-images.githubusercontent.com/13120192/208036450-99dbec4d-1b34-4a6c-9066-73689464913d.PNG">

Also please let us know why nearly 20 secs taken for tlsv1 handshake. What makes such delay? Incase of tlsv1.2, no such delays seen. For reference, screenshot of a tlsv1 handshake attached:
<img width="920" alt="closed_v12_handshake" src="https://user-images.githubusercontent.com/13120192/208042347-5f6e2e86-d6b2-481a-8cb9-c16a2960c4e1.PNG">

How do we make changes in netopeer2 client side, so that any attempts are only with tlsv1.2?

**Comment by michalvasko** [comment]
I would say then that this behaves as it should, look into `SSL_CTX_new(3)`. The client and server are supposed to negotiate the highest supported version by both and then use it. However, it definitely must not take 5 seconds to create a TLS connection so there is probably something wrong. Try updating OpenSSL, there is not much else you can do, this is all performed directly by the library and we have minimal control over what happens.

**Comment by Bharanidharan-S** [comment]
Openssl installed in our system is 1.0.2 - hope it supports TLSv1.2.

Got an information from google that Openssl versions till 1.0.0h supports SSLv2, SSLv3 and TLSv1.0. From Openssl 1.0.1 onward support for TLSv1.1 and TLSv1.2 is added.

In that case, probably highest supported version TLSv1.2 must be negotiated as you pointed out. But why is it trying initially with lower version 1.1 & then goes to higher version 1.2? Are you still recommending us to upgrade openssl? if yes, which version of openssl are you recommending?

**:: OpenSSL Version in our system ::**
[bs1122@siq5g-vm2 onecell5g]$ openssl
OpenSSL> version
OpenSSL 1.0.2k-fips  26 Jan 2017
OpenSSL>

[bs1122@siq5g-vm2]$ openssl ciphers -v | awk '{print $2}' | sort | uniq
SSLv3
TLSv1.2

**Comment by michalvasko** [comment]
You are using an unsupported version, which is a security risk, additional to the compatibility problems. Use a [supported version](https://www.openssl.org/policies/releasestrat.html).
