### ISSUE TITLE
CLI listen command failed to convert IPv4 address

### ISSUE THREAD

**Issue by robbynet** [CESNET/netopeer2#1328]
Env having  Netopeer2 v2.1.42 + patch delivered via this ticket : https://github.com/CESNET/netopeer2/issues/1321

1) Call Home OK with IP

> listen --ssh --host 172.1.1.5 --login netconf
Waiting 60s for an SSH Call Home connection on port 4334...
The authenticity of the host '172.1.1.10' cannot be established.
ssh-rsa key fingerprint is c1:a6:6f:c6:e8:90:43:1c:41:32:c2:45:8a:55:b1:cf:fc:db:e2:3d.
Are you sure you want to continue connecting (yes/no)? yes
netconf@172.1.1.10 password:

2) Conversion from hostname to IP is OK at OS level
> ping odusim
PING odusim (172.1.1.5) 56(84) bytes of data.
64 bytes from odusim (172.1.1.5): icmp_seq=1 ttl=64 time=0.071 ms
64 bytes from odusim (172.1.1.5): icmp_seq=2 ttl=64 time=0.062 ms

3) Call Home KO with corresponding hostname 

> listen --ssh --host odusim --login netconf
nc ERROR: Failed to convert IPv4 address "odusim".
Waiting 60s for an SSH Call Home connection on port 4334...
nc ERROR: nc_accept_callhome: libnetconf2 not initialized.
cmd_listen: Receiving SSH Call Home on port 4334 as user "netconf" failed.
>

While option --host of connect command accepted a host name or an IP

**Comment by michalvasko** [comment]
I have clarified the parameter meaning but I suppose you wanted to be able to use a hostname and expected it translated into an IP address. Is it really necessary? I have looked at what `ietf-netconf-client` supports for listening endpoints and it is only an IP address.

**Comment by robbynet** [comment]
Agreed, it is not a must to have. Point is if we look at ietf-netconf-server, remote-address ( reflected the NC Client )  is a hostname, moreover NC Client hostname is also embedded into the X.509 certificate making NC Client hostname being well know into the NC Client env as well. So from End to End TLS testing perspective, being able to always refer a given node using same hostname reference is more convenient and error less than having to refer it sometime with its IP and other with its hostname.

**Comment by robbynet** [comment]
Ok, then I think taht, as proposed above,  clarification of the parameter meaning is enough,  as I do not think new option of listen cmd is needed for hostname of NETCONF Server as it could interfere with recent option --peername

**Comment by michalvasko** [comment]
Oh, that is exactly what I suggested, to add such an option because I have completely forgotten it has already been added. Then there is really nothing to improve and any changes would be redundant.
