### ISSUE TITLE
TLS Renegotiation

### ISSUE THREAD

**Issue by robbynet** [CESNET/netopeer2#1329]
Does NETCONF Server supported https://datatracker.ietf.org/doc/html/rfc5746 ?
Meaning : 
1 ) TLS client initiates TLS renegotiation and sends Client Hello message to the TLS server with "renegotiation info" extension contains the client verify data
2 ) TLS server sends the Server Hello message with "renegotiation info" extension contains both the client verify data and server verify data

**Comment by michalvasko** [comment]
I have no idea, I would guess it all depends on OpenSSL, unless some special configuration is needed.
