### ISSUE TITLE
get --filter-xpath failure in 2.1.42

### ISSUE THREAD

**Issue by vinayhb012114** [CESNET/netopeer2#1330]
hi @michalvasko
We have updated netopeer2 to latest 2.1.42 version. And also we updated libnetcon2, libyang and sysrepo
versions as per readme.md of netopeer2.We met all the requirements which is required for "2.1.42 netopeer2".
After upgradation we are facing following issue:
1)when we try fetching data from client side(netopeer-cli side) using get "--filter-xpath" for any module we are getting below error.
  Example: 
get --filter-xpath /<module_name>:*
ERROR
    type:     application
    tag:      operation-failed
    severity: error
    message:  Invalid arguments for function "sr_get_data".
    type:     application
    tag:      operation-failed
    severity: error
    message:  User callback failed.

We are getting error for all the yang modules, 
I found that it is returning in sr_get_data() (SR_CHECK_ARG_APIRET will return back), so what is the right way to solve this,
 Please help us to resolve this.

**Comment by michalvasko** [comment]
Please use the `devel` versions instead until the next release, this bug has been fixed.

**Comment by vinayhb012114** [comment]
@michalvasko, 
can you please provide that fix here, something like commit-id, So I will take only that part.

**Comment by michalvasko** [comment]
I am sorry but I do not know anymore what exactly fixed this error (and in which project). There were several important fixes right after the release.

**Comment by jamespark76** [comment]
Hello @michalvasko,

Do you have any plans to release new version after v2.1.42? Thanks.

**Comment by michalvasko** [comment]
At the beginning of the next year, likely.

**Comment by vinayhb012114** [comment]
@michalvasko we changed SR_OPER_MASK 0xFFFF to 31 , so that now SR_CHECK_ARG_APIRET .
So will it affect any other functionality??
In previous versions SR_OPER_MASK value was 31 (before netopeer 2.1.42v), now it has been changed to 0xFFFF.
so if I revert back to 31, will this affect anything else???

**Comment by michalvasko** [comment]
I do not understand, why should `SR_CHECK_ARG_APIRET` fail (and in which function)? The mask was enlarged because there was a flag added that did not fit, there should be enough reserve for future now as well.

**Comment by vinayhb012114** [comment]
> I do not understand, why should `SR_CHECK_ARG_APIRET` fail (and in which function)? The mask was enlarged because there was a flag added that did not fit, there should be enough reserve for future now as well.

**Comment by vinayhb012114** [comment]
@michalvasko SR_CHECK_ARG_APIRET() is failing in sr_get_data(). When we trigger get --filter-xpath /<module_name>:*
this sr_get_data() fails and returns error as "Inavid arguement". 
In side sr_get_data, SR_CHECK_ARG_APIRET->macro fails.

**Comment by michalvasko** [comment]
I see. Look, I have told you what to do (update the projects) and if you refuse, you are on your own. I am sorry the latest release turned out for the worse but we would not learn about all these problems before the release anyway (because users would not update and report the problems).
