### ISSUE TITLE
Not receiving Netconf notification via nc_recv_notif

### ISSUE THREAD

**Issue by rekhapedaballi** [CESNET/netopeer2#1334]
hi,
Netconf notification has been sent from netconf server ,while the application is waiting for rpc reply using "nc_recv_reply"
The function ""nc_recv_reply" received notification and the same is been skipped to fetch the rpc-reply.
Issue here is we could not again receive the above notification via "nc_recv_notif".
Could you please let us know what could be the issue here if not receiving notification.Is the notification lost forever as we skip this message in  "nc_recv_reply" function?

Below code snippet of recv_msg() shows that we are again adding the buffer in to queue and hence we think that notification can not be lost.
Please let us know if we are missing anything.
```C
recv_msg()
{

if (ret != expected) {
        cont_ptr = &session->opts.client.msgs;
        while (*cont_ptr) {
            cont_ptr = &((*cont_ptr)->next);
        }
        *cont_ptr = malloc(sizeof **cont_ptr);
        if (!*cont_ptr) {
            ERRMEM;
            ret = NC_MSG_ERROR;
            goto cleanup_unlock;
        }
        (*cont_ptr)->msg = msg;
        msg = NULL;
        (*cont_ptr)->type = ret;
        (*cont_ptr)->next = NULL;
    }
}
```
Regards,
Rekha

**Comment by michalvasko** [comment]
Then you have created the issue in the wrong repository, fixed. As for the problem, I am not sure how to help but I would think you are doing something wrong because there are tests for this particular functionality so it should work.
