### ISSUE TITLE
How can I tell if netopeer2 supports yang 1.0 or yang 1.1?

### ISSUE THREAD

**Issue by mpet** [CESNET/netopeer2#1335]
Hi,

Is it possible to see which version of yang Netopeer2 supports?

br,

//mike

**Comment by michalvasko** [comment]
You mean in general? It depends on *libyang*, which supports both YANG 1.0 and 1.1 for quite a few years now. Or are you asking about a particular YANG module, whether the implemented version is written in YANG 1.0 or YANG 1.1?

**Comment by mpet** [comment]
I asked about libyang.

I checked the _hello_ message:

`<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
	<capabilities>
		<capability>urn:ietf:params:netconf:base:1.0</capability>
		<capability>urn:ietf:params:netconf:base:1.1</capability>
		<capability>urn:ietf:params:netconf:capability:writable-running:1.0</capability>
		<capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
		<capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</capability>
		<capability>urn:ietf:params:netconf:capability:validate:1.1</capability>
		<capability>urn:ietf:params:netconf:capability:startup:1.0</capability>
		<capability>urn:ietf:params:netconf:capability:xpath:1.0</capability>
		<capability>urn:ietf:params:netconf:capability:with-defaults:1.0?basic-mode=explicit&amp;also-supported=report-all,report-all-tagged,trim,explicit</capability>
		<capability>urn:ietf:params:netconf:capability:notification:1.0</capability>
		<capability>urn:ietf:params:netconf:capability:interleave:1.0</capability>
		<capability>urn:ietf:params:xml:ns:yang:ietf-yang-metadata?module=ietf-yang-metadata&amp;revision=2016-08-05</capability>
		<capability>urn:ietf:params:xml:ns:yang:1?module=yang&amp;revision=2017-02-20</capability>
		<capability>urn:ietf:params:xml:ns:yang:ietf-inet-types?module=ietf-inet-types&amp;revision=2013-07-15</capability>
		<capability>urn:ietf:params:xml:ns:yang:ietf-yang-types?module=ietf-yang-types&amp;revision=2013-07-15</capability>
		<capability>urn:ietf:params:netconf:capability:yang-library:1.1?revision=2019-01-04&amp;content-id=32</capability>
		<capability>urn:sysrepo:plugind?module=sysrepo-plugind&amp;revision=2020-12-10</capability>
		<capability>urn:ietf:params:xml:ns:yang:ietf-netconf-acm?module=ietf-netconf-acm&amp;revision=2018-02-14</capability>
		<capability>urn:ietf:params:xml:ns:netconf:base:1.0?module=ietf-netconf&amp;revision=2013-09-29&amp;features=writable-running,candidate,rollback-on-error,validate,startup,url,xpath</capability>
		<capability>urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults?module=ietf-netconf-with-defaults&amp;revision=2011-06-01</capability>
		<capability>urn:ietf:params:xml:ns:yang:ietf-netconf-notifications?module=ietf-netconf-notifications&amp;revision=2012-02-06</capability>
		<capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring?module=ietf-netconf-monitoring&amp;revision=2010-10-04</capability>
		<capability>urn:ietf:params:xml:ns:netconf:notification:1.0?module=notifications&amp;revision=2008-07-14</capability>
		<capability>urn:ietf:params:xml:ns:netmod:notification?module=nc-notifications&amp;revision=2008-07-14</capability>
		<capability>urn:ietf:params:xml:ns:yang:ietf-x509-cert-to-name?module=ietf-x509-cert-to-name&amp;revision=2014-12-10</capability>
		<capability>urn:ietf:params:xml:ns:yang:iana-crypt-hash?module=iana-crypt-hash&amp;revision=2014-08-06</capability>
	</capabilities>
	<session-id>2</session-id>
</hello>`

In here is:

`<capability>urn:ietf:params:netconf:capability:yang-library:1.1?revision=2019-01-04&amp;content-id=32</capability>`

Does this mean that Netopeer2 only supports yang 1.1?

Have seen this from another **NETCONF** enabled device in the hello message:

<nc:capability>urn:ietf:params:netconf:capability:yang-library:1.0?revision=2019-01-04&amp;module-set-id=33002b99aaf7e7cbfb16d78198496b1d</nc:capability>
<nc:capability>urn:ietf:params:netconf:capability:yang-library:1.1?revision=2019-01-04&amp;content-id=33002b99aaf7e7cbfb16d78198496b1d</nc:capability>

Does it mean that the server supports both yang 1.0 and yang 1.1 at the same time?

br,

//mike

**Comment by michalvasko** [comment]
Support for `yang-library` does not equal YANG 1.0 or YANG 1.1 support. Also, advertising both `yang-library:1.0` and `yang-library:1.1` is not a good idea and rather confusing. Incidentally, `ietf-yang-library` YANG module in revision `2019-01-04` is written in YANG 1.1 so based on that you know it is supported. However, there is no direct way of knowing whether a server supports YANG 1.1 (when it will always support 1.0 as well) so I would just assume it always does, the standard is old enough now.

**Comment by mpet** [comment]
Thx for making it clear!
