### ISSUE TITLE
Notifications stopped on replay subscription

### ISSUE THREAD

**Issue by anjansat** [CESNET/netopeer2#134]
Hi Michal,

After subscribing with replay, existing/new subscriber clients stop receiving notification due to Netopeer2 didn’t receive callback.
I could see this issue continuously and as of now restarting netopeer2, resolves issue(re-subscription).

The following are the steps to reproduce:

I connected with CLI1, subscribed with simple subscribe(it started receiving all notifications). Then I connected with CLI2, CLI1 received a netconf-session-start notification.
I then executed subscribe --begin -30 (replay of last 30 seconds) in CLI2 and got mine netconf-session-start followed by replayComplete. 

After this, none of the notifications are received by CLI1 and CLI2.

Regards
Anjan

**Comment by michalvasko** [comment]
Hi Anjan,
I connected with CLI1, subscribed. Connected with CLI2, CLI1 got the notif. CLI2 subscribed `--begin -30`, got its `session-start`. Connected with CLI3, both CLI1 and CLI2 got its 'session-start' notif. I was fixing the problem you are describing maybe a week ago, try using most recent `devel` revision (you must also `install` it) and then report back.

Regards,
Michal
