### ISSUE TITLE
Vlan support for netopeer2 communication

### ISSUE THREAD

**Issue by chendrashekarp** [CESNET/netopeer2#1340]
Hi @michalvasko ,How to use netopeer2 server with vlan tagging

**Comment by jktjkt** [comment]
Since VLAN is an L2 concept, and Netopeer2 uses L4 (TCP) sockets, there's nothing Netopeer-specific. What functionality are you looking for? Do you want to, say, have Netopeer2 listen on some IP address which is assigned to some VLAN on some interface?

**Comment by chendrashekarp** [comment]
Yes jan kundrat

Regards,
Chendrashekar p
________________________________

**Comment by jktjkt** [comment]
The NETCONF server supports the [`ietf-netconf-server`](https://datatracker.ietf.org/doc/html/draft-ietf-netconf-netconf-client-server-14) draft, so you can use the YANG data to configure how the server operates, including the listening endpoints. Also check the [documentation on Netopeer2's homepage](https://github.com/CESNET/netopeer2#server-configuration).

**Comment by chendrashekarp** [comment]
hi @jktjkt / @michalvasko  ,

1. server side i have changed /ietf-netconf-server:netconf-server/listen/.../ssh/tcp-server-parameters/local-address to the desired IP address(created on vlan interface), but when i try to do connect from client i am getting error msg as connection refused, i am able to see [INF]: LN: Listening on 192.168.12.1:830 for SSH connections in netopeer-server logs , please guide me through required changes, for connect & listen(call-home)
2. For call-home , enabled the feature `local-binding-supported` in `ietf-tcp-client` and added the local IP address(ip assigned to vlan interfcae) , same unable to achieve call-home 

please give some suggestion on this

**Comment by michalvasko** [comment]
Well, you can always check the output of `ss -l4` (for example) to make sure the socket is being listened on. If you are getting `connection refused` error from the other peer, it means there is a network issue (firewall, ...) and I cannot help you with that.

**Comment by chendrashekarp** [comment]
thanks for the response
