### ISSUE TITLE
The netopeer2-server died

### ISSUE THREAD

**Issue by lilililizheng** [CESNET/netopeer2#1341]
Jan 30 22:32:11 QSG netopeer2-server[482]: Published event "rpc" "/zdxlz-ha:ha-state" with ID 4 priority 0 for 1 subscribers.
Jan 30 22:32:11 QSG netopeer2-server[482]: Event "rpc" with ID 4 priority 0 succeeded.
Jan 30 22:32:11 QSG netopeer2-server[482]: Session 13: thread 0 event new RPC.
Jan 30 22:32:11 QSG netopeer2-server[482]: Published event "rpc" "/zdxlz-ha:incr-sync" with ID 4 priority 0 for 1 subscribers.
Jan 30 22:32:11 QSG netopeer2-server[482]: Event "rpc" with ID 4 priority 0 succeeded.
Jan 30 22:32:11 QSG netopeer2-server[482]: Session 15: thread 0 event new RPC.
Jan 30 22:32:11 QSG netopeer2-server[482]: Published event "rpc" "/ietf-netconf:get-config" with ID 51 priority 0 for 1 subscribers.
Jan 30 22:32:11 QSG netopeer2-server[482]: Processing "/ietf-netconf:get-config" "rpc" event with ID 51 priority 0 (remaining 1 subscribers).
Jan 30 22:32:11 QSG netopeer2-server[482]: Successful processing of "rpc" event with ID 51 priority 0 (remaining 0 subscribers).
Jan 30 22:32:11 QSG netopeer2-server[482]: Event "rpc" with ID 51 priority 0 succeeded.
Jan 30 22:32:11 QSG netopeer2-server[482]: Session 16: thread 3 event new RPC.
Jan 30 22:32:12 QSG netopeer2-server[482]: Published event "rpc" "/ietf-netconf-nmda:get-data" with ID 54 priority 0 for 1 subscribers.
Jan 30 22:32:12 QSG netopeer2-server[482]: Processing "/ietf-netconf-nmda:get-data" "rpc" event with ID 54 priority 0 (remaining 1 subscribers).
Jan 30 22:32:12 QSG netopeer2-server[482]: Published event "operational get" "/zdxlz-device-state:device-state/*" with ID 47.
Jan 30 22:32:13 QSG netopeer2-server[482]: Event "operational get" with ID 47 succeeded.
Jan 30 22:32:13 QSG netopeer2-server[482]: Successful processing of "rpc" event with ID 54 priority 0 (remaining 0 subscribers).
Jan 30 22:32:13 QSG netopeer2-server[482]: Event "rpc" with ID 54 priority 0 succeeded.
Jan 30 22:32:13 QSG netopeer2-server[482]: Session 17: thread 0 event new RPC.
Jan 30 22:32:37 QSG netopeer2-server[482]: Published event "rpc" "/ietf-netconf:get-config" with ID 52 priority 0 for 1 subscribers.
Jan 30 22:32:37 QSG netopeer2-server[482]: Processing "/ietf-netconf:get-config" "rpc" event with ID 52 priority 0 (remaining 1 subscribers).
Jan 30 22:32:37 QSG netopeer2-server[482]: Successful processing of "rpc" event with ID 52 priority 0 (remaining 0 subscribers).
Jan 30 22:32:37 QSG netopeer2-server[482]: Event "rpc" with ID 52 priority 0 succeeded.
Jan 30 22:32:37 QSG netopeer2-server[482]: Session 12: thread 4 event new RPC.
Jan 30 22:32:37 QSG netopeer2-server[482]: Published event "rpc" "/ietf-netconf-nmda:get-data" with ID 55 priority 0 for 1 subscribers.
Jan 30 22:32:37 QSG netopeer2-server[482]: Processing "/ietf-netconf-nmda:get-data" "rpc" event with ID 55 priority 0 (remaining 1 subscribers).
Jan 30 22:32:37 QSG netopeer2-server[482]: Published event "operational get" "/ietf-interfaces:interfaces/*" with ID 3.
Jan 30 22:32:37 QSG netopeer2-server[482]: Event "operational get" with ID 3 succeeded.
Jan 30 22:32:37 QSG netopeer2-server[482]: Successful processing of "rpc" event with ID 55 priority 0 (remaining 0 subscribers).
Jan 30 22:32:37 QSG netopeer2-server[482]: Event "rpc" with ID 55 priority 0 succeeded.
Jan 30 22:32:37 QSG netopeer2-server[482]: Session 13: thread 4 event new RPC.
Jan 30 22:32:59 QSG netopeer2-server[482]: Published event "rpc" "/ietf-netconf-nmda:get-data" with ID 56 priority 0 for 1 subscribers.
Jan 30 22:32:59 QSG netopeer2-server[482]: Processing "/ietf-netconf-nmda:get-data" "rpc" event with ID 56 priority 0 (remaining 1 subscribers).
Jan 30 22:32:59 QSG netopeer2-server[482]: Published event "operational get" "/zdxlz-device-state:device-state/*" with ID 48.
Jan 30 22:33:00 QSG netopeer2-server[482]: Event "operational get" with ID 48 succeeded.
Jan 30 22:33:00 QSG netopeer2-server[482]: Successful processing of "rpc" event with ID 56 priority 0 (remaining 0 subscribers).
Jan 30 22:33:00 QSG netopeer2-server[482]: Event "rpc" with ID 56 priority 0 succeeded.
Jan 30 22:33:00 QSG netopeer2-server[482]: Session 6: thread 1 event new RPC.
Jan 30 22:33:12 QSG netopeer2-server[482]: Published event "rpc" "/ietf-netconf:get-config" with ID 53 priority 0 for 1 subscribers.
Jan 30 22:33:12 QSG netopeer2-server[482]: Processing "/ietf-netconf:get-config" "rpc" event with ID 53 priority 0 (remaining 1 subscribers).
Jan 30 22:33:12 QSG netopeer2-server[482]: Successful processing of "rpc" event with ID 53 priority 0 (remaining 0 subscribers).
Jan 30 22:33:12 QSG netopeer2-server[482]: Event "rpc" with ID 53 priority 0 succeeded.
Jan 30 22:33:12 QSG netopeer2-server[482]: Session 15: thread 0 event new RPC.
Jan 30 22:33:13 QSG netopeer2-server[482]: Published event "rpc" "/ietf-netconf-nmda:get-data" with ID 57 priority 0 for 1 subscribers.
Jan 30 22:33:13 QSG netopeer2-server[482]: Processing "/ietf-netconf-nmda:get-data" "rpc" event with ID 57 priority 0 (remaining 1 subscribers).
Jan 30 22:33:13 QSG netopeer2-server[482]: Published event "operational get" "/zdxlz-device-state:device-state/*" with ID 49.
Jan 30 22:33:14 QSG netopeer2-server[482]: Event "operational get" with ID 49 succeeded.
Jan 30 22:33:14 QSG netopeer2-server[482]: Successful processing of "rpc" event with ID 57 priority 0 (remaining 0 subscribers).
Jan 30 22:33:14 QSG netopeer2-server[482]: Event "rpc" with ID 57 priority 0 succeeded.
Jan 30 22:33:14 QSG netopeer2-server[482]: Session 16: thread 0 event new RPC.
Jan 30 22:33:16 QSG netopeer2-server[482]: Published event "rpc" "/ietf-netconf:get-config" with ID 54 priority 0 for 1 subscribers.
Jan 30 22:33:16 QSG netopeer2-server[482]: Processing "/ietf-netconf:get-config" "rpc" event with ID 54 priority 0 (remaining 1 subscribers).
Jan 30 22:33:16 QSG netopeer2-server[482]: Successful processing of "rpc" event with ID 54 priority 0 (remaining 0 subscribers).
Jan 30 22:33:16 QSG netopeer2-server[482]: Event "rpc" with ID 54 priority 0 succeeded.
Jan 30 22:33:16 QSG netopeer2-server[482]: Session 17: thread 3 event new RPC.
Jan 30 22:33:16 QSG netopeer2-server[482]: Published event "rpc" "/ietf-netconf-nmda:get-data" with ID 58 priority 0 for 1 subscribers.
Jan 30 22:33:16 QSG netopeer2-server[482]: Processing "/ietf-netconf-nmda:get-data" "rpc" event with ID 58 priority 0 (remaining 1 subscribers).
Jan 30 22:33:16 QSG netopeer2-server[482]: Published event "operational get" "/ietf-interfaces:interfaces/*" with ID 4.
Jan 30 22:33:16 QSG netopeer2-server[482]: Event "operational get" with ID 4 succeeded.
Jan 30 22:33:16 QSG netopeer2-server[482]: Successful processing of "rpc" event with ID 58 priority 0 (remaining 0 subscribers).
Jan 30 22:33:16 QSG netopeer2-server[482]: Event "rpc" with ID 58 priority 0 succeeded.
Jan 30 22:33:16 QSG netopeer2-server[482]: Session 12: thread 1 event new RPC.
Jan 30 22:34:00 QSG netopeer2-server[482]: Published event "rpc" "/ietf-netconf-nmda:get-data" with ID 59 priority 0 for 1 subscribers.
Jan 30 22:34:00 QSG netopeer2-server[482]: Processing "/ietf-netconf-nmda:get-data" "rpc" event with ID 59 priority 0 (remaining 1 subscribers).
Jan 30 22:34:00 QSG netopeer2-server[482]: Published event "operational get" "/zdxlz-device-state:device-state/*" with ID 50.
Jan 30 22:34:01 QSG netopeer2-server[482]: Event "operational get" with ID 50 succeeded.
Jan 30 22:34:01 QSG netopeer2-server[482]: Successful processing of "rpc" event with ID 59 priority 0 (remaining 0 subscribers).
Jan 30 22:34:01 QSG netopeer2-server[482]: Event "rpc" with ID 59 priority 0 succeeded.
Jan 30 22:34:01 QSG netopeer2-server[482]: Session 1: thread 1 event new RPC.
Jan 30 22:34:14 QSG netopeer2-server[482]: Published event "rpc" "/ietf-netconf-nmda:get-data" with ID 60 priority 0 for 1 subscribers.
Jan 30 22:34:14 QSG netopeer2-server[482]: Processing "/ietf-netconf-nmda:get-data" "rpc" event with ID 60 priority 0 (remaining 1 subscribers).
Jan 30 22:34:14 QSG netopeer2-server[482]: Published event "operational get" "/zdxlz-device-state:device-state/*" with ID 51.
Jan 30 22:34:15 QSG netopeer2-server[482]: Event "operational get" with ID 51 succeeded.
Jan 30 22:34:15 QSG netopeer2-server[482]: Successful processing of "rpc" event with ID 60 priority 0 (remaining 0 subscribers).
Jan 30 22:34:15 QSG netopeer2-server[482]: Event "rpc" with ID 60 priority 0 succeeded.
Jan 30 22:34:15 QSG netopeer2-server[482]: Session 13: thread 0 event new RPC.
Jan 30 22:35:01 QSG netopeer2-server[482]: Published event "rpc" "/ietf-netconf-nmda:get-data" with ID 61 priority 0 for 1 subscribers.
Jan 30 22:35:01 QSG netopeer2-server[482]: Processing "/ietf-netconf-nmda:get-data" "rpc" event with ID 61 priority 0 (remaining 1 subscribers).
Jan 30 22:35:01 QSG netopeer2-server[482]: Published event "operational get" "/zdxlz-device-state:device-state/*" with ID 52.
Jan 30 22:35:02 QSG netopeer2-server[482]: Event "operational get" with ID 52 succeeded.
Jan 30 22:35:02 QSG netopeer2-server[482]: Successful processing of "rpc" event with ID 61 priority 0 (remaining 0 subscribers).
Jan 30 22:35:02 QSG netopeer2-server[482]: Event "rpc" with ID 61 priority 0 succeeded.
Jan 30 22:35:02 QSG netopeer2-server[482]: Session 2: thread 0 event new RPC.
Jan 30 22:35:03 QSG netopeer2-server[482]: Session 12: SSH channel poll error (Socket error: disconnected).
Jan 30 22:35:03 QSG netopeer2-server[482]: Session 12: thread 0 event session terminated.
Jan 30 22:35:03 QSG netopeer2-server[482]: Published event "notif" "ietf-netconf-notifications" with ID 55 priority 0 for 2 subscribers.
Jan 30 22:35:03 QSG netopeer2-server[482]: Processing "notif" "ietf-netconf-notifications" event with ID 55.
Jan 30 22:35:03 QSG netopeer2-server[482]: Successful processing of "notif" event with ID 55 priority 0 (remaining 0 subscribers).
Jan 30 22:35:03 QSG netopeer2-server[482]: Generated new event (netconf-session-end).
Jan 30 22:35:03 QSG netopeer2-server[482]: Session 17: SSH channel poll error (Socket error: disconnected).
Jan 30 22:35:03 QSG netopeer2-server[482]: Session 17: thread 0 event session terminated.
Jan 30 22:35:03 QSG netopeer2-server[482]: Published event "notif" "ietf-netconf-notifications" with ID 56 priority 0 for 2 subscribers.
Jan 30 22:35:03 QSG netopeer2-server[482]: Processing "notif" "ietf-netconf-notifications" event with ID 56.
Jan 30 22:35:03 QSG netopeer2-server[482]: Successful processing of "notif" event with ID 56 priority 0 (remaining 0 subscribers).
Jan 30 22:35:03 QSG netopeer2-server[482]: Generated new event (netconf-session-end).
Jan 30 22:35:03 QSG netopeer2-server[482]: Session 16: SSH channel poll error (Socket error: disconnected).
Jan 30 22:35:03 QSG netopeer2-server[482]: Session 16: thread 0 event session terminated.
Jan 30 22:35:03 QSG netopeer2-server[482]: Published event "notif" "ietf-netconf-notifications" with ID 57 priority 0 for 2 subscribers.
Jan 30 22:35:03 QSG netopeer2-server[482]: Processing "notif" "ietf-netconf-notifications" event with ID 57.
Jan 30 22:35:03 QSG netopeer2-server[482]: Successful processing of "notif" event with ID 57 priority 0 (remaining 0 subscribers).
Jan 30 22:35:03 QSG netopeer2-server[482]: Generated new event (netconf-session-end).
Jan 30 22:35:03 QSG netopeer2-server[482]: Session 15: SSH channel poll error (Socket error: disconnected).
Jan 30 22:35:03 QSG netopeer2-server[482]: Session 15: thread 0 event session terminated.
Jan 30 22:35:03 QSG netopeer2-server[482]: Published event "notif" "ietf-netconf-notifications" with ID 58 priority 0 for 2 subscribers.
Jan 30 22:35:03 QSG netopeer2-server[482]: Processing "notif" "ietf-netconf-notifications" event with ID 58.
Jan 30 22:35:03 QSG netopeer2-server[482]: Successful processing of "notif" event with ID 58 priority 0 (remaining 0 subscribers).
Jan 30 22:35:03 QSG netopeer2-server[482]: Generated new event (netconf-session-end).
Jan 30 22:35:03 QSG netopeer2-server[482]: Session 14: SSH channel poll error (Socket error: disconnected).
Jan 30 22:35:03 QSG netopeer2-server[482]: Session 14: thread 0 event session terminated.
Jan 30 22:35:03 QSG netopeer2-server[482]: Session 13: SSH channel poll error (Socket error: disconnected).
Jan 30 22:35:03 QSG netopeer2-server[482]: Session 13: thread 3 event session terminated.
Jan 30 22:35:03 QSG netopeer2-server[482]: Published event "notif" "ietf-netconf-notifications" with ID 59 priority 0 for 1 subscribers.
Jan 30 22:35:03 QSG netopeer2-server[482]: Processing "notif" "ietf-netconf-notifications" event with ID 59.

**Comment by lilililizheng** [comment]
I found out that my service died, and this is the last log

**Comment by michalvasko** [comment]
Depending on the version you are using, it may be enough to just update it, in case it is really old. If not, you need to learn more details about what is happening and for that I would suggest trying to run the server directly using `# netopeer2-server -d -v2` and even using `gdb` or `valgrind` for getting more information in case the server really crashes.

**Comment by itercheng** [comment]
Hi michalvasko
   my question is similar to this. The netconf server side suddenly print out the following error when it runs for a while.


The 1 condition:
Mar 10 03:44:11 GR daemon.info netopeer2-server[881]: Resolving unresolved data nodes and their constraints...
Mar 10 03:44:11 GR daemon.info netopeer2-server[881]: All data nodes and constraints resolved.
Mar 10 03:44:11 GR daemon.info netopeer2-server[881]: Netconf server send reply to cli --- msgid[22]
Mar 10 03:44:11 GR daemon.info netopeer2-server[881]: [2023-03-10T03-44-1678419851] /root/workspace/cli2/libnetconf2-1.1.43/src/session_server.c 1416 r : 6 ####  start to reply netconf client #### RPC_NAME = ietf-netconf-monitoring
Mar 10 03:44:11 GR daemon.info netopeer2-server[881]: [2023-03-10T03-44-1678419851] /root/workspace/cli2/libnetconf2-1.1.43/src/session_server.c 1430 ####  Reply netconf client sucessfully #### RPC_NAME = ietf-netconf-monitoring
Mar 10 03:44:11 GR daemon.info netopeer2-server[881]: Session 16: thread 1 event new RPC.
Mar 10 03:44:11 GR daemon.err netopeer2-server[881]: Session 16: SSH channel poll error (Socket error: disconnected).
Mar 10 03:44:11 GR daemon.info netopeer2-server[881]: Session 16: thread 0 event session terminated.


The 2 condiction:
Mar 10 03:33:18 GR daemon.info netopeer2-server[881]: Netconf server send reply to cli --- msgid[2870]
Mar 10 03:33:18 GR daemon.info netopeer2-server[881]: [2023-03-10T03-33-1678419198] /root/workspace/cli2/libnetconf2-1.1.43/src/session_server.c 1416 r : 6 ####  start to reply netconf client #### RPC_NAME = ietf-netconf
Mar 10 03:33:18 GR daemon.info netopeer2-server[881]: [2023-03-10T03-33-1678419198] /root/workspace/cli2/libnetconf2-1.1.43/src/session_server.c 1430 ####  Reply netconf client sucessfully #### RPC_NAME = ietf-netconf
Mar 10 03:33:18 GR daemon.info netopeer2-server[881]: Session 13: thread 1 event new RPC.
Mar 10 03:34:13 GR daemon.err netopeer2-server[881]: Session 13: SSH channel poll error (Socket error: Connection timed out).
Mar 10 03:34:13 GR daemon.info netopeer2-server[881]: Session 13: thread 1 event session terminated.

The 3 case:
Mar 10 06:50:04 GR daemon.info netopeer2-server[881]: Netconf server send reply to cli --- msgid[3169]
Mar 10 06:50:04 GR daemon.info netopeer2-server[881]: [2023-03-10T06-50-1678431004] /root/workspace/cli2/libnetconf2-1.1.43/src/session_server.c 1416 r : 6 ####  start to reply netconf client #### RPC_NAME = heart-beat
Mar 10 06:50:04 GR daemon.info netopeer2-server[881]: [2023-03-10T06-50-1678431004] /root/workspace/cli2/libnetconf2-1.1.43/src/session_server.c 1430 ####  Reply netconf client sucessfully #### RPC_NAME = heart-beat
Mar 10 06:50:04 GR daemon.info netopeer2-server[881]: Session 18: thread 0 event new RPC.
Mar 10 06:50:05 GR daemon.err netopeer2-server[881]: Session 18: SSH channel poll error (Socket error: Connection reset by peer).
Mar 10 06:50:05 GR daemon.info netopeer2-server[881]: Session 18: thread 0 event session terminated.


 In the preceding three cases, the socket link is closed abnormally. Is this an existing problem? Has the new version been fixed? 
Do I  need to update all versions to the latest? Or just netopeer2 or ssh version ? 

netopeer2-1.1.70
libnetconf2-1.1.43
sysrepo-1.4.140
libyang.so.1.10.32
libssh-0.9.5

Thank you in advance for your help.

**Comment by michalvasko** [comment]
You are using obsolete versions of our software that are not supported anymore, I cannot help you.
