### ISSUE TITLE
Multiple TLS listen usernames support

### ISSUE THREAD

**Issue by jamespark76** [CESNET/netopeer2#1347]
Hello.

I have questions about TLS authentication about netopeer2 v2.1.49 (latest).

1. Does netopeer2 support multiple TLS listen endpoints?

2. Does netopeer2 support multiple TLS user account (NETCONF username)?

Thanks.

**Comment by michalvasko** [comment]
1. Naturally.
2. There is no TLS user account. In `cert-to-name` you configure whatever username you want for specific certificates/info in certificates that is then used mainly for NACM checks. It has no connection to the system users (unlike SSH).

**Comment by jamespark76** [comment]
I tried configuring two different TLS listen endpoints in the ietf-netconf-server.yang file. 
However, only the first TLS listen endpoint seems to be working, and the second endpoint always results in an authentication failure. The error message displayed is: "nc ERROR: Server certificate error (certificate signature failure)."

Each TLS listen endpoint operates independently, utilizing a different certificate 
that is configured through ietf-netconf-server.yang, ietf-truststore.yang and ietf-keystore.yang.

I tested like below. 


```
[1] listen-tls1 (authentication success)
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <listen>
    <endpoint>
      <name>listen-tls1</name>
    </endpoint>
  </listen>
</netconf-server>

[2] listen-tls2 (authentication success)
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <listen>
    <endpoint>
      <name>listen-tls2</name>
    </endpoint>
  </listen>
</netconf-server>

[3] listen-tls1 (authentication success), listen-tls2 (authentication failure)
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <listen>
    <endpoint>
      <name>listen-tls1</name>
    </endpoint>
    <endpoint>
      <name>listen-tls2</name>
    </endpoint>
  </listen>
</netconf-server>

[4] listen-tls2 (authentication success), listen-tls1 (authentication failure)
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <listen>
    <endpoint>
      <name>listen-tls2</name>
    </endpoint>
    <endpoint>
      <name>listen-tls1</name>
    </endpoint>
  </listen>
</netconf-server>
```


I inserted some traces in the "nc_accept()" and "nc_accept_tls_session()" functions and checked the value of "bind_idx". 
The "bind_idx" always indicates the first TLS endpoint, and it appears that there is no further processing to handle the next "bind_idx" for the second TLS endpoint. 

Could you please look into this issue?

**Comment by michalvasko** [comment]
What *libnetconf2* version are you using? I have briefly tested it and it seemed fine. I did not get to actually connect because of the annoying TLS hostname verification which obviously failed when testing on localhost using 2 interfaces.

**Comment by jamespark76** [comment]
(1) I am using the latest version of netopeer2 v2.1.49, libyang v2.1.30, libnetconf2 v2.1.28, and sysrepo v2.2.36.

(2) I have tested with three different devices (netconf server and two netconf clients). Each device has a unique IP address. 


I have configured each TLS listen endpoint with a different port like below, and both listen-tls1 and listen-tls2 endpoints are now functioning.

```
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <listen>
    <endpoint>
      <name>listen-tls1</name>
      <tls>
        <tcp-server-parameters>
          <local-address>0.0.0.0</local-address>
          <local-port>6513</local-port>
        </tcp-server-parameters>
      </tls>
    </endpoint>
    <endpoint>
      <name>listen-tls2</name>
      <tls>
        <tcp-server-parameters>
          <local-address>0.0.0.0</local-address>
          <local-port>6514</local-port>
        </tcp-server-parameters>
      </tls>
    </endpoint>
  </listen>
</netconf-server>
```

Is it necessary to configure a different port for each TLS listen endpoint in order to support multiple TLS listen endpoints?

**Comment by michalvasko** [comment]
> Is it necessary to configure a different port for each TLS listen endpoint in order to support multiple TLS listen endpoints?

Well, either a different port of different address (or both). You previously had both the same and saw no error when starting the server?

**Comment by jamespark76** [comment]
I noticed an error when starting the netopeer2-server with the same port and IP address.

```
(1) For listen-tls1 endpoint with local-port (6513) and listen-tls2 endpoint with local-port (6513):
{2023.02.14 18:05:12 [INF] Listening on 0.0.0.0:6513 for TLS connections."}
{2023.02.14 18:05:12 [ERR] Could not bind \"0.0.0.0\" port 6513 (Broken pipe)."}

(2) For listen-tls1 endpoint with local-port (6513) and listen-tls2 endpoint with local-port (6514):
{2023.02.14 18:11:36 [INF] Listening on 0.0.0.0:6513 for TLS connections."}
{2023.02.14 18:11:36 [INF] Listening on 0.0.0.0:6514 for TLS connections."}
```

Is configuring multiple endpoints with different port and/or IP address the only way to support multiple TLS NACM accounts?

**Comment by michalvasko** [comment]
> Is configuring multiple endpoints with different port and/or IP address

This is a completely basic networking requirement that you definitely should have been aware of, no system will let you bind to the same **address** and **port** twice since it uses these 2 items to direct data sent over the network, it must be unambiguous.

> support multiple TLS NACM accounts?

This is the first time you have mentioned NACM. I suppose you mean you want to be authenticated as multiple users on a single TLS endpoint, which of course if possible. Username resolution is handled by `cert-to-name` configuration and there you have absolute freedom how to assign usernames to certificates. It can be anything from direct coupling of usernames and client certificates or using specific fields of the certificates as usernames.

**Comment by jamespark76** [comment]
Yes, I want to configure multiple NACM usernames on a single TLS endpoint. 
Despite your explanation, I still do not understand how to configure multiple certificates and cert-to-names on a single TLS endpoint.

If I am incorrect, please correct me below.

The fingerprint in cert-to-name is generated from the CA certificate (ca-certs: ca.pem), which is always a fixed value according to the certificate. The servercert and clientcerts are generated based on the CA certificate.

Could you please show me how to configure another username (e.g. tls-test2) in the original example (tls_listen.xml) below?"

```
[tls_listen.xml in example_configuration]

<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <listen>
    <endpoint>
      <name>default-tls</name>
      <tls>
        <tcp-server-parameters>
          <local-address>0.0.0.0</local-address>
          <keepalives>
            <idle-time>1</idle-time>
            <max-probes>10</max-probes>
            <probe-interval>5</probe-interval>
          </keepalives>
        </tcp-server-parameters>
        <tls-server-parameters>
          <server-identity>
            <keystore-reference>
              <asymmetric-key>serverkey</asymmetric-key>
              <certificate>servercert</certificate>
            </keystore-reference>
          </server-identity>
          <client-authentication>
            <required/>
            <ca-certs>cacerts</ca-certs>
            <client-certs>clientcerts</client-certs>
            <cert-maps>
              <cert-to-name>
                <id>1</id>
                <fingerprint>02:20:E1:AD:CC:92:71:E9:EA:6A:85:DF:A7:FF:8C:BB:B9:D5:E4:EE:74</fingerprint>
                <map-type xmlns:x509c2n="urn:ietf:params:xml:ns:yang:ietf-x509-cert-to-name">x509c2n:specified</map-type>
                <name>tls-test</name>
              </cert-to-name>
            </cert-maps>
          </client-authentication>
        </tls-server-parameters>
      </tls>
    </endpoint>
  </listen>
</netconf-server>
```

**Comment by jamespark76** [comment]
First of all, thanks for the quick response.

For example TLS configuration, I referred to the source folder netopeer2-2.1.49/example_configuration/tls_certs.

To obtain the SHA1 fingerprint, I ran the following commands:

$ openssl x509 -in ca.pem -noout -fingerprint
SHA1 Fingerprint=20:E1:AD:CC:92:71:E9:EA:6A:85:DF:A7:FF:8C:BB:B9:D5:E4:EE:74

$ openssl x509 -in client.crt -noout -fingerprint
SHA1 Fingerprint=37:B8:CA:1D:C1:B4:DF:77:6E:D4:21:DB:C4:C5:9F:B2:27:0B:3E:7C

In this reason, I thought the SHA1 Fingerprint is from the CA certificate (ca.pem) and not the client certificate (client.crt).

I will configure the fingerprint of the client certificate as you mentioned, and then get back to you. Thanks.

**Comment by jamespark76** [comment]
Finally, it is working after configuring the client certificates in the ietf-truststore and adding the fingerprint of the client certificates to the <cert-to-name> block on the TLS listen endpoint in the ietf-netconf-server. Thank you for your support.
