### ISSUE TITLE
What private key format of netopeer is required?

### ISSUE THREAD

**Issue by wjzu2023** [CESNET/netopeer2#1349]
When netopeer use the private key that TPM create, but report error "Failed to set hostkey "genkey" (/tmp/hTStDY)".

**Comment by michalvasko** [comment]
We are working on a major update of *libnetconf2* where the format of the keys should be handled better in general but currently you need to use keys that have the header in PEM format as
```
-----BEGIN RSA PRIVATE KEY-----
```
with `RSA` being replaced by the actual key type (such as `EC`).

**Comment by wjzu2023** [comment]
> We are working on a major update of _libnetconf2_ where the format of the keys should be handled better in general but currently you need to use keys that have the header in PEM format as
> 
> ```
> -----BEGIN RSA PRIVATE KEY-----
> ```
> 
> with `RSA` being replaced by the actual key type (such as `EC`).

Hi michalvasko, thanks for your reply. I have some questions. When the client and the server establish interaction, they must send the private key? What is the use of the private key after the client gets it?

**Comment by michalvasko** [comment]
What keys are you talking about exactly, server host key, client authorized key or another? In any case, you can learn about their purpose in the RFCs of the SSH protocol.

**Comment by michalvasko** [comment]
You have not answered my question and I have no idea what "strong authentication" means. Also, I still do not understand what exactly are you asking, I think you should learn some basic information about SSH keys first.

**Comment by wjzu2023** [comment]
> is only used as strong authentication

I refer the link https://www.ssh.com/academy/ssh/protocol.

**Comment by michalvasko** [comment]
Oh, seems to have no exact meaning and is just a buzzword.

**Comment by wjzu2023** [comment]
I intercepted a paragraph. “Strong authentication with SSH keys
There are several options that can be used for user authentication. The most common ones are passwords and public key authentication.

The public key authentication method is primarily used for automation and sometimes by system administrators for single sign-on. It has turned out to be much more widely used than we ever anticipated. The idea is to have a cryptographic key pair - public key and private key - and configure the public key on a server to [authorize access](https://www.ssh.com/ssh/authorized_keys/) and grant anyone who has a copy of the private key access to the server. The keys used for authentication are called [SSH keys](https://www.ssh.com/ssh/key/). Public key authentication is also used with smartcards, such as the CAC and PIV cards used by US government.

The main use of key-based authentication is to enable secure automation. Automated secure shell file transfers are used to seamlessly integrate applications and also for automated systems & configuration management.

We have found that large organizations have way more SSH keys than they imagine, and [managing SSH keys](https://www.ssh.com/iam/ssh-key-management/) has become very important. SSH keys grant access as user names and passwords do. They require a similar provisioning and termination processes.

In some cases we have found several million SSH keys authorizing access into production servers in customer environments, with 90% of the keys actually being unused and representing access that was provisioned but never terminated. Ensuring proper policies, processes, and audits also for SSH usage is critical for proper identity and access management. Traditional identity management projects have overlooked as much as 90% of all credentials by ignoring SSH keys. We provide [services](https://www.ssh.com/products/services) and [tools](https://www.ssh.com/products/universal-ssh-key-manager/) for implementing SSH key management.” 

You can have a look.

**Comment by michalvasko** [comment]
Yes, I have briefly went through the paragraph, it talks about SSH `publickey` authentication method. What exactly is your *netopeer2*-specific question?

**Comment by wjzu2023** [comment]
Yeah, before I don't think private key should be sent. When I delete the private key parameters in merge_hostkey.sh, some questions occur.

**Comment by michalvasko** [comment]
That is what I meant when I said you should learn something about SSH keys in general. The private key is **never** sent anywhere and should be reasonably secured (using *sysrepo* access control, having it in the configuration is no less dangerous than when being in `~/.ssh` directory). Only the public key is being sent over SSH as part of `publickey` authentication.

I have not said anything specific to *neopteer2* that you would not be able to find online. Please, try to keep the questions relevant, these issues are meant to provide support for the project they are created in.
