### ISSUE TITLE
How can we limit the number of simultaneous sessions supported by netopeer2? 

### ISSUE THREAD

**Issue by akhilpuresoftware** [CESNET/netopeer2#1350]
HI,

I'm on netopeer2 version 2.1.42, I want to put a limit on number of simultaneous sessions supported by netopeer2.

**Comment by michalvasko** [comment]
This option has been removed in `ietf-netconf-server` YANG configuration modules in favor of various timeouts. So use those instead to avoid redundant stale sessions.

**Comment by akhilpuresoftware** [comment]
Hi Michal,
I'm not aware about the various timeouts you are talking about, it will be really helpful if you can explain the same in some more detail.  
Thanks

**Comment by michalvasko** [comment]
Well, for listen connections there seems to be only the [idle-timeout](https://github.com/CESNET/netopeer2/blob/master/modules/ietf-netconf-server%402019-07-02.yang#L138). Then Call Home sessions have several parameters to tune either [connection type](https://github.com/CESNET/netopeer2/blob/master/modules/ietf-netconf-server%402019-07-02.yang#L377).
