### ISSUE TITLE
Netopeer support that set the password for the private key in merge_hostkey.sh?

### ISSUE THREAD

**Issue by wjzu2023** [CESNET/netopeer2#1352]

**Comment by michalvasko** [comment]
Actually, I am not certain whether this is supported or not but I think it might, it depends to some extent on *libssh*. Just try to use the data of a password-encrypted private key and you will see what happens.

**Comment by wjzu2023** [comment]
> Actually, I am not certain whether this is supported or not but I think it might, it depends to some extent on _libssh_. Just try to use the data of a password-encrypted private key and you will see what happens.

When use password-encrypted private key, Netopeer occur error:
"Feb 16 08:12:20 ORU3668_MAIN daemon.err netopeer2-server[913]: Failed to set hostkey "genkey" (/tmp/RsZ9HY)".

**Comment by wjzu2023** [comment]
Maybe Netopeer check private key format.

**Comment by michalvasko** [comment]
It seems *libssh* does not support using password-protected host keys so it is not going to work no matter what we do. On one hand it seems like a reasonable use-case, on the other you are the very first to ask about it so I suppose it is not used in practice. There is also the problem of how to get the password, the server is not supposed to be interactive in any way.
