### ISSUE TITLE
When use netopeer-cli(root user), how to hide the private-key?

### ISSUE THREAD

**Issue by wjzu2023** [CESNET/netopeer2#1355]
Hi Michal, I want to hide or encrypted the private key(root user).

**Comment by jktjkt** [comment]
If you're connecting via SSH, authenticating via a private key, and you trying to figure out how to keep the private key on the client encrypted on-disk, consult `ssh-keygen` (or any other SW you used for generating that key). The CLI can load encrypted keys just fine. Or are you looking for something else?

**Comment by wjzu2023** [comment]
> If you're connecting via SSH, authenticating via a private key, and you trying to figure out how to keep the private key on the client encrypted on-disk, consult `ssh-keygen` (or any other SW you used for generating that key). The CLI can load encrypted keys just fine. Or are you looking for something else?

Hi Jan, when I use below config(the private key have encrypted):
CONFIG="<keystore xmlns=\"urn:ietf:params:xml:ns:yang:ietf-keystore\">
    <asymmetric-keys>
        <asymmetric-key>
            <name>genkey</name>
            <algorithm>rsa2048</algorithm>
            <public-key>$PUBKEY</public-key>
            <private-key>$PRIVKEY</private-key>
        </asymmetric-key>
    </asymmetric-keys>
</keystore>"

The netopeer occur error, does I need modify the config?

**Comment by jktjkt** [comment]
The goal is to have the server configurable 100% via YANG data, and that means that any outside information that cannot be provided by YANG is not desirable. The server needs access to crypto material, and in this context that means the cleartext of a private key. The YANG model does not support provisioning a pair of a) an encrypted key, b) the passphrase for decrypting it. Even if it did, what would be the point? The YANG database would have to contain all the information for decrypting such a key anyway.

What problem are you trying to solve? Note that the usual NACM access control applies to crypto keys as well.

**Comment by wjzu2023** [comment]
> The goal is to have the server configurable 100% via YANG data, and that means that any outside information that cannot be provided by YANG is not desirable. The server needs access to crypto material, and in this context that means the cleartext of a private key. The YANG model does not support provisioning a pair of a) an encrypted key, b) the passphrase for decrypting it. Even if it did, what would be the point? The YANG database would have to contain all the information for decrypting such a key anyway.
> 
> What problem are you trying to solve? Note that the usual NACM access control applies to crypto keys as well.

The purpose is to hide or encrypt the private key for all users. The exposed private key is insecure maybe.

**Comment by jktjkt** [comment]
Use NACM rules to deny your "all users" (except those who can provision that key in the first place) access to said crypto material.

**Comment by michalvasko** [comment]
Note that it is not accessible by default because of the use of `nacm:default-deny-all` extension so as long as the system *sysrepo* datastore files are not accessible, the keys cannot be accessed by NETCONF either and are secure.

**Comment by wjzu2023** [comment]
> Use NACM rules to deny your "all users" (except those who can provision that key in the first place) access to said 

> Note that it is not accessible by default because of the use of `nacm:default-deny-all` extension so as long as the system _sysrepo_ datastore files are not accessible, the keys cannot be accessed by NETCONF either and are secure.

Thanks.

**Comment by wjzu2023** [comment]
> Note that it is not accessible by default because of the use of `nacm:default-deny-all` extension so as long as the system _sysrepo_ datastore files are not accessible, the keys cannot be accessed by NETCONF either and are secure.

Thanks for your supporting.
