### ISSUE TITLE
For filtering RW/config data for get-config from client

### ISSUE THREAD

**Issue by chendrashekarp** [CESNET/netopeer2#1359]
Hi @michalvasko  , is there a way to apply custom filters at server for sending the response for get-config on an xpath?

**Comment by michalvasko** [comment]
What "filters" are you talking about exactly? XPath filter for `get-config` works as it should and according to the [spec](https://datatracker.ietf.org/doc/html/rfc6241#section-8.9.5.1).

**Comment by chendrashekarp** [comment]
Hi @michalvasko  , i want to add filters at server such that particular netconf-client user only can read the data from a list with key (i will have the mapping between user-name & key)

**Comment by chendrashekarp** [comment]
Hi @michalvasko, please find the snap-shot & attaching the yang too
![image](https://user-images.githubusercontent.com/86454044/220843038-ca1e2a11-8e71-4604-83b5-da79224a226f.png)
[processing_elements.txt](https://github.com/CESNET/netopeer2/files/10811146/processing_elements.txt)
Need your inputs on this

**Comment by michalvasko** [comment]
It seems this would match creating a NACM entry for this list with the [`USER`](https://datatracker.ietf.org/doc/html/rfc8341#page-36) XPath variable. Unfortunately, it is not currently supported but once I have some spare time, I will try to look at it.

**Comment by chendrashekarp** [comment]
Hi @michalvasko , this is bit urgent , is there any expected date for this ? Please

**Comment by michalvasko** [comment]
Well, I may get to it fairly soon (a day or two later) but I have no idea how long it would take to implement. There is a reason it is not supported, it may be quite challenging.

**Comment by chendrashekarp** [comment]
Okay @michalvasko , Thank you

**Comment by michalvasko** [comment]
Should be supported in the latest *sysrepo*, you can now use `$USER` instead of a key value in a `path` node in NACM and it will be replaced by the current user.
