### ISSUE TITLE
Libyang version to build latest netopeer2 and sysrepo

### ISSUE THREAD

**Issue by mathieu-mercier** [CESNET/Netopeer2#136]
I have a question about what version of libyang to use to build the latest netopeer2 and sysrepo.

With version 112 I have errors building sysrepo
-fdebug-prefix-map=/workdir/build/tmp/sysroots/qemux86=   -m32 -march=i586  --sysroot=/workdir/build/tmp/sysroots/qemux86 -Wall -Wpedantic -std=gnu11 -Wno-strict-aliasing   -fPIC -o CMakeFiles/COMMON.dir/utils/xpath.c.o   -c /workdir/uap-sysrepo/src/utils/xpath.c
| /workdir/uap-sysrepo/src/common/sr_mem_mgmt.c: In function 'sr_msg_free':
| /workdir/uap-sysrepo/src/common/sr_mem_mgmt.c:508:28: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
|      sr_mem_ctx_t *sr_mem = (sr_mem_ctx_t *)msg->_sysrepo_mem_ctx;
|                             ^
| /workdir/uap-sysrepo/src/common/sr_protobuf.c: In function 'sr_gpb_req_alloc':
| /workdir/uap-sysrepo/src/common/sr_protobuf.c:372:33: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
|          msg->_sysrepo_mem_ctx = (uint64_t)sr_mem;
|                                  ^
| /workdir/uap-sysrepo/src/common/sr_protobuf.c: In function 'sr_gpb_resp_alloc':
| /workdir/uap-sysrepo/src/common/sr_protobuf.c:640:33: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
|          msg->_sysrepo_mem_ctx = (uint64_t)sr_mem;
|                                  ^
| ERROR: oe_runmake failed
| /workdir/uap-sysrepo/src/common/sr_protobuf.c: In function 'sr_gpb_notif_alloc':
| /workdir/uap-sysrepo/src/common/sr_protobuf.c:729:33: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
|          msg->_sysrepo_mem_ctx = (uint64_t)sr_mem;
|                                  ^
| /workdir/uap-sysrepo/src/common/sr_protobuf.c: In function 'sr_gpb_notif_ack_alloc':
| /workdir/uap-sysrepo/src/common/sr_protobuf.c:778:33: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
|          msg->_sysrepo_mem_ctx = (uint64_t)sr_mem;
|                                  ^
| /workdir/uap-sysrepo/src/common/sr_utils.c: In function 'sr_dup_datatree_to_ctx':
| /workdir/uap-sysrepo/src/common/sr_utils.c:762:19: warning: implicit declaration of function 'lyd_dup_to_ctx' [-Wimplicit-function-declaration]
|              dup = lyd_dup_to_ctx(root, 1, ctx);
|                    ^~~~~~~~~~~~~~
| /workdir/uap-sysrepo/src/common/sr_utils.c:762:17: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
|              dup = lyd_dup_to_ctx(root, 1, ctx);
|                  ^
| /workdir/uap-sysrepo/src/common/sr_utils.c:764:13: warning: implicit declaration of function 'lyd_merge_to_ctx' [-Wimplicit-function-declaration]
|              lyd_merge_to_ctx(&dup, root, LYD_OPT_EXPLICIT, ctx);
|              ^~~~~~~~~~~~~~~~
| /workdir/uap-sysrepo/src/common/sr_protobuf.c: In function 'sr_gpb_internal_req_alloc':
| /workdir/uap-sysrepo/src/common/sr_protobuf.c:877:33: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
|          msg->_sysrepo_mem_ctx = (uint64_t)sr_mem;
|                                  ^
| /workdir/uap-sysrepo/src/common/sr_utils.c: In function 'sr_find_schema_node':
| /workdir/uap-sysrepo/src/common/sr_utils.c:2450:47: warning: passing argument 2 of 'lys_find_xpath' from incompatible pointer type [-Wincompatible-pointer-types]
|      struct ly_set *set = lys_find_xpath(NULL, node, expr, options);
|                                                ^~~~
| In file included from /workdir/build/tmp/sysroots/qemux86/usr/include/libyang/libyang.h:20:0,
|                  from /workdir/uap-sysrepo/src/common/sr_utils.c:36:
| /workdir/build/tmp/sysroots/qemux86/usr/include/libyang/tree_schema.h:1683:16: note: expected 'const char *' but argument is of type 'const struct lys_node *'
|  struct ly_set *lys_find_xpath(const struct lys_node *node, const char *expr, int options);
|                 ^~~~~~~~~~~~~~
| /workdir/uap-sysrepo/src/common/sr_utils.c:2450:53: warning: passing argument 3 of 'lys_find_xpath' makes integer from pointer without a cast [-Wint-conversion]
|      struct ly_set *set = lys_find_xpath(NULL, node, expr, options);
|                                                      ^~~~
| In file included from /workdir/build/tmp/sysroots/qemux86/usr/include/libyang/libyang.h:20:0,
|                  from /workdir/uap-sysrepo/src/common/sr_utils.c:36:
| /workdir/build/tmp/sysroots/qemux86/usr/include/libyang/tree_schema.h:1683:16: note: expected 'int' but argument is of type 'const char *'
|  struct ly_set *lys_find_xpath(const struct lys_node *node, const char *expr, int options);
|                 ^~~~~~~~~~~~~~
| /workdir/uap-sysrepo/src/common/sr_utils.c:2450:26: error: too many arguments to function 'lys_find_xpath'
|      struct ly_set *set = lys_find_xpath(NULL, node, expr, options);
|                           ^~~~~~~~~~~~~~
| In file included from /workdir/build/tmp/sysroots/qemux86/usr/include/libyang/libyang.h:20:0,
|                  from /workdir/uap-sysrepo/src/common/sr_utils.c:36:
| /workdir/build/tmp/sysroots/qemux86/usr/include/libyang/tree_schema.h:1683:16: note: declared here
|  struct ly_set *lys_find_xpath(const struct lys_node *node, const char *expr, int options);
|                 ^~~~~~~~~~~~~~

With version 174 I have errors building netopeer2:
/workdir/build/tmp/work/i586-poky-linux-musl/libnetconf2/1.0+gitAUTOINC+64bad2c9df-r0/git/src/session_client.c:293:5: error: unknown type name 'ly_module_clb'
     ly_module_clb old_clb = NULL;

     ^~~~~~~~~~~~~
/workdir/build/tmp/work/i586-poky-linux-musl/libnetconf2/1.0+gitAUTOINC+64bad2c9df-r0/git/src/messages_server.c: In function 'nc_err_libyang':
/workdir/build/tmp/work/i586-poky-linux-musl/libnetconf2/1.0+gitAUTOINC+64bad2c9df-r0/git/src/messages_server.c:471:14: error: 'LYVE_INVALATTR' undeclared (first use in this function)
         case LYVE_INVALATTR:
              ^~~~~~~~~~~~~~

Is there a single version of libyang that can build last week's releases of netopeer2 and sysrepo?

**Comment by TrinityCoder** [comment]
Hello,

towards the end, I think you are talking about the compilation of [libnetconf2](https://github.com/CESNET/libnetconf2), not Netopeer2, right?

Anyway, I believe your actual problem is that your version of libnetconf2 is too old. I think so because of the  last error message:

> /workdir/build/tmp/work/i586-poky-linux-musl/libnetconf2/1.0+gitAUTOINC+64bad2c9df-r0/git/src/messages_server.c: In function 'nc_err_libyang':
> /workdir/build/tmp/work/i586-poky-linux-musl/libnetconf2/1.0+gitAUTOINC+64bad2c9df-r0/git/src/messages_server.c:471:14: error: 'LYVE_INVALATTR' undeclared (first use in this function)
> case LYVE_INVALATTR:

I took a look at the commit history of libnetconf2 and found [this commit from 2nd of March](https://github.com/CESNET/libnetconf2/commit/37fdad5c19391f2475751bc139b5f5edf284f3da), This commit renamed ```LYVE_INVALATTR``` to ```LYVE_INMETA```.

Your sources of libnetconf2 are old (they do not include this commit), but your version of [libyang](https://github.com/CESNET/libyang) is current, therefore it contains the ```LYVE_INMETA``` instead of the old ```LYVE_INVALATTR``` identifier.

The solution is straightforward - update your libnetconf2 sources to current version, then recompile and install it and then you should be able to compile both Sysrepo and Netopeer2 without any problem.

**Comment by michalvasko** [comment]
Hi,
if you have the latest revisions of all the libraries (from either `devel` or `master` branches), and something fails to compile, please create an issue. If not, then update it and try again. Also, you can fairly easily check whether some symbols are defined in a library, so if it fails to compile, but the symbols are there, you have something wrong on your system.

Regards,
Michal

**Comment by rkrejci** [comment]
I was planning to create libyang release when other projects were released to have compatible "packages", but I forget about it. I'm going to create the release.

**Comment by rkrejci** [comment]
libyang now has release 0.12-r2
