### ISSUE TITLE
SSH channel unexpected EOF.

### ISSUE THREAD

**Issue by cigdem123** [CESNET/netopeer2#1360]
Hi, I'm having trouble connecting to the server. I can connect to radio via ssh 
sudo netopeer2-cli
> connect --host=10.20.12.110 --port=830 --login=root
root@10.20.12.110 password: 
nc ERROR: SSH channel unexpected EOF.
cmd_connect: Connecting to the 10.20.12.110:830 as user "root" failed.

**Comment by michalvasko** [comment]
Try running the server with `netopeer2-server -d -v2` and look at its output, it should tell you what is happening.

**Comment by cigdem123** [comment]
Thanks for the feedback, i couldn't understand this problem

[ERR]: NP: Unable to open the PID file "/var/run/netopeer2-server.pid" (Permission denied)

**Comment by michalvasko** [comment]
You need to run the server as `root`, that is pretty much what the error says.

**Comment by cigdem123** [comment]
i run it on my pc but i need to use faxconn radio as server. Ip address of this server : 10.20.12.110
sudo netopeer2-server -d -v2
[INF]: SR: Datastore copied from <startup> to <running>.
[INF]: SR: Connection 1 created.
[INF]: SR: Session 1 (user "root", CID 1) created.
[INF]: SR: Triggering "ietf-subscribed-notifications" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: LN: Listening on 0.0.0.0:830 for SSH connections.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-keystore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-truststore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.

**Comment by michalvasko** [comment]
So you have some device between the CLI and the server? Then I cannot help you since our tools are not at fault here, the EOF is sent by that radio.

**Comment by cigdem123** [comment]
i'm using netopeer2-cli only, server is faxconn radio. Are you telling the problem is radio

**Comment by michalvasko** [comment]
If the CLI is not connecting directly to the server (which you have implied but I am not certain of that), it is not the server that is sending the SSH EOF but the radio, so yes, you need to look at that radio more, not the server nor CLI.

**Comment by cigdem123** [comment]
okey, thank you.
