### ISSUE TITLE
Yang model notification not able to get for o-ran-usermgmt users (operator,installer,observer)

### ISSUE THREAD

**Issue by Shubham-dash** [CESNET/netopeer2#1365]
Hi @michalvasko 
I am not getting yang model notification for `log-management, file-management` when login with different users of o-ran-usermgmt.yang as (operator, observer and installer ) but there NACM access is given as `exec` for `sudo , nms,fm-pm` can you please help me to come out of this issue

**Comment by michalvasko** [comment]
I am not sure I understand, you want to get YANG notifications from some ORAN modules on some events? You would have to implement that, *netopeer2* sends only the few standardized NETCONF notifications on its own.

**Comment by Shubham-dash** [comment]
Using the `root user` which is the default user, I am able to get notifications but on the other users I am not getting can I know the reason why this is happening?

**Comment by michalvasko** [comment]
You mention absolutely no details so it is next to impossible to help you but if the used system user makes a difference, *sysrepo* access control may be causing the missed notifications. Not sure if NACM is even used, it depends on your exact use-case.
