### ISSUE TITLE
How to know if netopeer2 server has failed to establish callhome to known netconf clients

### ISSUE THREAD

**Issue by saraaibak** [CESNET/netopeer2#1373]
Hi @michalvasko,

How to know that netopeer2 server has failed to establish callhome to all known netconf clients. I need to set the maximum number of attempts which server will be trying to connect to each client and also need to take an action if netopeer2 server is not able to connect to any of the known clients after that many tries per client. I tried setting `max-attempts` under `reconnect-strategy` in `ietf-netcof-server.yang`, but in that case connection tries are repeating in round robin method [for endpoints under the same netconf client only / but need to set the same for each netconf client] and I am not able to know if the attempts are over for all the clients.

**Comment by michalvasko** [comment]
There is currently no way to "know" this, Call Home is implemented according to all the standardized specs and nothing like this is there. If you really need this, you could define your own notification and then generate it whenever you need but that would require changing *netopeer2* code.
