### ISSUE TITLE
Cannot lock running datastore after starting confirmed commit

### ISSUE THREAD

**Issue by pfeige** [CESNET/netopeer2#1375]
Hi Michal,

after starting a confirmed commit a lock of the running datastore is rejected.
~~~
connect --login user
edit-config --target candidate
commit --confirmed
lock --target running
ERROR - There is an ongoing confirmed commit.
~~~
From my point of view this should be allowed and accepted. What do you think?

BR,
Peter

**Comment by michalvasko** [comment]
Okay, this specific case should work. Please test the fix, I did not bother to write a test because it seemed not worth it.
