### ISSUE TITLE
cannot establish the ssh connection during upgrade libssh to v0.9.5

### ISSUE THREAD

**Issue by kaizhang0124** [CESNET/netopeer2#1376]
I have upgrade the libssh version from 0.7.7 to 0.9.5. but the netopeer2-server is output error as below. 

[INF]: LN: Call Home client "default-client" connecting...
[INF]: LN: Trying to connect via IPv4 to 10.1.1.90:4334.
[INF]: LN: Call Home client "test-client" connecting...
[INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4334.
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Successfully connected to 10.1.1.90:4334 over IPv4.
[INF]: SR: Session 37 (user "root") created.
[ERR]: LN: SSH key exchange error (Could not sign the session id).
[INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4334.
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Trying to connect via IPv4 to 10.1.1.90:4334.
[INF]: LN: Successfully connected to 10.1.1.90:4334 over IPv4.
[INF]: SR: Session 38 (user "root") created.
[ERR]: LN: SSH key exchange error (Could not sign the session id).
[INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4334.
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Trying to connect via IPv4 to 10.1.1.90:4334.
[INF]: LN: Successfully connected to 10.1.1.90:4334 over IPv4.
[INF]: SR: Session 39 (user "root") created.
[ERR]: LN: SSH key exchange error (Could not sign the session id).
[INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4334.
[INF]: LN: getsockopt() error (Connection refused).

currently the libnetconf2 version is v1.1.46, whether the libssh0.9.5 is mismatch with libnetconf2 v1.1.46? because the call-home is normal  for libssh0.7.7

**Comment by michalvasko** [comment]
I have never seen this error
```
[ERR]: LN: SSH key exchange error (Could not sign the session id).
```
so I do not think I can help. But you using *libssh* 0.7.7 and *libnetconf2* 1.1.46 tells me you are using an old distribution and an old *libnetconf2* version so I guess it is time to update both. I am quite sure it will work then.

**Comment by kaizhang0124** [comment]
thanks for your remind. I will re-compile the libnetconf2&netopeer2 base on the libssh0.9.5
