### ISSUE TITLE
CLI "yang" parsing fails despite libyang plugins being correctly loaded

### ISSUE THREAD

**Issue by mathieu-mercier** [CESNET/Netopeer2#138]
I have a CLI issue that looks like the ones discussed in this [libyang issue](https://github.com/CESNET/libyang/issues/291) and in this [libyang faq](https://github.com/CESNET/libyang/blob/master/FAQ.md), only the libyang modules seem properly loaded in my case.

I have libyang.so in /usr/lib and the plugins in /usr/lib/libyang.

This is the output of the CLI session with libyang logging set to debug:
~# netopeer2-cli 
ly VERBOSE: Extension plugin "/usr/lib/libyang/metadata.so" successfully loaded.
ly VERBOSE: Extension plugin "/usr/lib/libyang/nacm.so" successfully loaded.
ly VERBOSE: Reading module "ietf-yang-metadata".
ly VERBOSE: Module "ietf-yang-metadata" successfully parsed.
ly VERBOSE: Reading module "yang".
ly VERBOSE: Resolving "yang" unresolved schema nodes and their constraints...
ly VERBOSE: All "yang" schema nodes and constraints resolved.
ly VERBOSE: Module "yang" successfully parsed.
ly VERBOSE: Reading module "ietf-inet-types".
ly VERBOSE: Resolving derived type "union" failed, it will be attempted later.
ly VERBOSE: Resolving type default "" failed, it will be attempted later.
ly VERBOSE: Resolving derived type "union" failed, it will be attempted later.
ly VERBOSE: Resolving type default "" failed, it will be attempted later.
ly VERBOSE: Resolving derived type "union" failed, it will be attempted later.
ly VERBOSE: Resolving type default "" failed, it will be attempted later.
ly VERBOSE: Resolving derived type "union" failed, it will be attempted later.
ly VERBOSE: Resolving type default "" failed, it will be attempted later.
ly VERBOSE: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
ly VERBOSE: All "ietf-inet-types" schema nodes and constraints resolved.
ly VERBOSE: Module "ietf-inet-types" successfully parsed.
ly VERBOSE: Reading module "ietf-yang-types".
ly VERBOSE: Module "ietf-yang-types" successfully parsed.
ly VERBOSE: Reading module "ietf-yang-library".
ly VERBOSE: Module "ietf-yang-library" successfully parsed.
    >
    > connect --host localhost --login root --port 6001
Interactive SSH Authentication
Type your password:
Password: 
ly VERBOSE: Extension plugin "/usr/lib/libyang/metadata.so" already loaded.
ly VERBOSE: Extension plugin "/usr/lib/libyang/nacm.so" already loaded.
ly VERBOSE: Reading module "ietf-yang-metadata".
ly VERBOSE: Module "ietf-yang-metadata" successfully parsed.
ly VERBOSE: Reading module "yang".
ly ERROR: Invalid keyword "type" as a child to "annotation". (/)
ly ERROR: Module "yang" parsing failed.
ly VERBOSE: Extension plugin "/usr/lib/libyang/metadata.so" already loaded.
ly VERBOSE: Extension plugin "/usr/lib/libyang/nacm.so" already loaded.
ly VERBOSE: Reading module "ietf-yang-metadata".
ly VERBOSE: Module "ietf-yang-metadata" successfully parsed.
ly VERBOSE: Reading module "yang".
ly ERROR: Invalid keyword "type" as a child to "annotation". (/)
ly ERROR: Module "yang" parsing failed.
cmd_connect: Connecting to the localhost:6001 as user "root" failed.

The strange thing is that when starting the "yang" module is parsed correctly but the parsing fails when connecting to the server.

This is with latest libyang, libnetconf2, netopeer2 and sysrepo.

**Comment by rkrejci** [comment]
Hi, this is really weird. I'm nto able to reproduce the issue, anyway, please try the following:
1. get the list of linked libraries for your netopeer2-cli
```
# ldd `which netopeer2-cli`
```
2. there should be a path to libnetconf2, use the path and run again the ldd
```
# ldd LIBNETCONF2_ABSOLUT_PATH
```
3. please provide the full output of the both commands

**Comment by mathieu-mercier** [comment]
Here is the output you requested:

~# ldd `which netopeer2-cli`
	/lib/ld-musl-i386.so.1 (0x800aa000)
	libyang.so.0.12 => /usr/lib/libyang.so.0.12 (0xb7650000)
	libnetconf2.so.0.8 => /usr/lib/libnetconf2.so.0.8 (0xb7617000)
	libcrypto.so.1.0.0 => /usr/lib/libcrypto.so.1.0.0 (0xb7417000)
	libc.so => /lib/ld-musl-i386.so.1 (0x800aa000)
	libpcre.so.1 => /usr/lib/libpcre.so.1 (0xb73cf000)
	libssh.so.4 => /usr/lib/libssh.so.4 (0xb7354000)
	libssh_threads.so.4 => /usr/lib/libssh_threads.so.4 (0xb7351000)
	libssl.so.1.0.0 => /usr/lib/libssl.so.1.0.0 (0xb72e5000)
	libz.so.1 => /lib/libz.so.1 (0xb72cd000)
~# ldd /usr/lib/libnetconf2.so.0.8
	ldd (0x800af000)
	libssh.so.4 => /usr/lib/libssh.so.4 (0xb76e7000)
	libssh_threads.so.4 => /usr/lib/libssh_threads.so.4 (0xb76e4000)
	libc.so => ldd (0x800af000)
	libssl.so.1.0.0 => /usr/lib/libssl.so.1.0.0 (0xb7678000)
	libcrypto.so.1.0.0 => /usr/lib/libcrypto.so.1.0.0 (0xb7478000)
	libyang.so.0.12 => /usr/lib/libyang.so.0.12 (0xb738f000)
	libz.so.1 => /lib/libz.so.1 (0xb7377000)
	libpcre.so.1 => /usr/lib/libpcre.so.1 (0xb732f000)

I suspect that the problem may be because my system uses musl instead of glibc.
See this entry about a difference between musl and glibc:
http://wiki.musl-libc.org/wiki/Functional_differences_from_glibc#Lazy_bindings

I don't understand yet what implications this has for the libyang plugin loading code.  I will investigate further but please tell me if you see right away what should be changed!

Thanks

**Comment by rkrejci** [comment]
`ldd` output seems fine. It doesn't seem to me to be connected with lazy bindings to me - libyang does not use it, so it should work the same way even in glibc.

What version of musl are you using and on which platform?

**Comment by mathieu-mercier** [comment]
musl 1.1.15 on 32-bit linux kernel 4.8.12 running in qemu.

~# /usr/lib/libc.so
musl libc (i386)
Version 1.1.15-git-6-g39494a2

~# uname -a
Linux qemux86 4.8.12-yocto-standard #1 SMP PREEMPT Tue Apr 11 15:53:42 UTC 2017 i686 GNU/Linux

I can add logs to libyang if you point me what/where to trace.

Thanks

**Comment by rkrejci** [comment]
Hi, can you please try to compile and run the enclosed program and post the output? (remove the `.txt` suffix, it should need just `-ldl` option to compile). Ideally if you would be able to run it with valgrind, but it should be enough to run it even without valgrind.

[ldsotest.c.txt](https://github.com/CESNET/Netopeer2/files/1001415/ldsotest.c.txt)

**Comment by mathieu-mercier** [comment]
Sorry no valgrind but here is the output:
~# ldsotest 
object 1: 0xb77d5370
object 2: 0xb77d5370
object 1: /usr/lib/libyang/metadata.so (3077799936)
object 2: /usr/lib/libyang/metadata.so (3077799936)
closing object 2 (0)
object 1: /usr/lib/libyang/metadata.so (3077799936)
object 2: /usr/lib/libyang/metadata.so (3077799936)
closing object 1 (0)
object 1: /usr/lib/libyang/metadata.so (3077799936)
object 2: /usr/lib/libyang/metadata.so (3077799936)

**Comment by mislavn** [comment]
I found the issue:

> musl’s dynamic loader loads libraries permanently for the lifetime of the process, until it exits or calls exec. dlclose is a no-op. This is very different from glibc’s approach of reference counting libraries and unloading them when the count reaches zero.

On Lede (musl), netopeer2-cli worked when I loaded the plugins only once, for that I deleted the code:
```
        /* load the plugin - first, try if it is already loaded... */
        dlhandler = dlopen(str, RTLD_NOW | RTLD_NOLOAD);
        dlerror();    /* Clear any existing error */
        if (dlhandler) {
            /* the plugin is already loaded */
            LOGVRB("Extension plugin \"%s\" already loaded.", str);
            free(str);

            /* keep the refcount of the shared object correct */
            dlclose(dlhandler);
            continue;
        }
```

I will make a patch which should work for musl and glibc/uclibc.

**Comment by rkrejci** [comment]
Please test the proposed patch in CESNET/libyang#487
