### ISSUE TITLE
Getting "required feature is disable" error from netopeercli for action rpc script

### ISSUE THREAD

**Issue by balaji07s** [CESNET/netopeer2#1380]
Hi team,

Previously I was using the older sysrepo version 1.4.140. Where the following action RPC configuration was working fine when pushed from netopeercli.

```
<action xmlns="urn:ietf:params:xml:ns:yang:1"> 
    <hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware"> 
      <component> 
        <name>ontCard_ont2_1</name> 
        <bbf-hw:reset> 
          <bbf-hw:reset-type>bbf-hw:hardware-reset</bbf-hw:reset-type> 
        </bbf-hw:reset> 
      </component> 
    </hardware> 
  </action>
```

But now after moving to the latest sysrepo version of 2.2.12, if I push the same script via netopeercli it is throwing the below error.
```
> user-rpc --content /root/temp/onu_reboot.xml
ly ERROR: Node "action" not found in the "yang" module. (Line number 2.)
nc ERROR: Failed to create RPC, perhaps a required feature is disabled.
cli_send_recv: Failed to send the RPC.
```
Could you please share your input on this?

Thanks.

**Comment by michalvasko** [comment]
> But now after moving to the latest sysrepo version of 2.2.12

This version is not the latest one. Try using the current latest version and I think this should be working again, specifically update all the projects *libyang*, *libnetconf2*, *sysrepo*, and *netopeer2*.
