### ISSUE TITLE
restconf

### ISSUE THREAD

**Issue by lilililizheng** [CESNET/netopeer2#1384]
I would like to know if netopeer2-server supports the restconf protocol, and if so, how do I use it.

**Comment by michalvasko** [comment]
It does not. There is a separate [project](https://github.com/CESNET/rousette) with the ultimate goal of creating a RESTCONF server on top of *sysrepo* but it is not finished and I do not know details as to the exact state it is in.

**Comment by jktjkt** [comment]
The current status of [`rousette`, currently the almost-RESTCONF server :)](https://github.com/CESNET/rousette) is that basic, unauthenticated read-only access works. Anything which requires authentication & authorization is currently not supported, and these HTTP requests are being rejected.

It's an open source project, so patches are welcome, as usual. If there are no external contributions, we plan to eventually get around to implementing all the RESTCONF-related features, but it's currently a best-effort project.

**Comment by lilililizheng** [comment]
Thanks, restconf is more useful than netconf in some cases
