### ISSUE TITLE
multiple instance of netopeer2 server to handle multiple repository path

### ISSUE THREAD

**Issue by SagarGowda89** [CESNET/netopeer2#1385]
Hi,

I want to start multiple instance of netopeer2 server to handle multiple repository path. can you please let me know how to enable it

Thanks
Sagar

**Comment by michalvasko** [comment]
Let me start by saying that this is not a good idea and may result in a chaotic architecture. But it is possible and you need to have the same amount of *sysrepo* instances installed that use different [env variables](https://github.com/sysrepo/sysrepo#used-run-time-enviromental-variables) that distinguish between them. Then, each *netopeer2* instance needs to set these env variables to the same values as are used for *sysrepo* operations effectively pairing each server instance with a *sysrepo* instance.

**Comment by SagarGowda89** [comment]
Hi Michaelvasco,

I have tried to run directly.  It's working.
