### ISSUE TITLE
Getting error while trying to change remote-address for callhome

### ISSUE THREAD

**Issue by uttamsingh-ps** [CESNET/netopeer2#1387]
Hi @michalvasko, i am getting error while trying to change **remote-address** for callhome

```
root@localhost:~# sysrepocfg --edit=vim -m ietf-netconf-server
[ERR] Locking a mutex failed (sr_modinfo_changesub_rdlock: Connection timed out).
[ERR] Internal error (/home/user/workspace/sysrepo/src/common.c:4229).
[ERR] Internal error (/home/user/workspace/sysrepo/src/common.c:4229).
sysrepocfg error: Replace config failed (Timeout expired)

```

**Comment by michalvasko** [comment]
What *sysrepo* version are you using? The problem occurred before, these messages on their own do not help at all.

**Comment by uttamsingh-ps** [comment]
root@localhost:~# sysrepoctl -V
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.2.60 (SO v7.14.20)

**Comment by michalvasko** [comment]
No, you are not based on the internal error [common.c:4229](https://github.com/sysrepo/sysrepo/blob/master/src/common.c#L4229).

**Comment by uttamsingh-ps** [comment]
My Bad the version of netopeer2 we tried both 2.1.59 and 2.1.42
with both same issue is coming
so the logs shared are of verion of sysrepo [v2.2.12](https://github.com/sysrepo/sysrepo/releases/tag/v2.2.12)

originally when we used to use version 2.1.42 of netopeer2 we never faced this issue, after upgrading to netopeer2 2.1.59 the issue started facing. Now even on downgrading back we face same issue. Is that some references of the shm/sysrepo/libraries are not getting uninstalled or we have call some sysrepo API which is has taken lock and not released. Need directions on how to debug ahead.

**Comment by michalvasko** [comment]
The simplest fix is to exec `make sr_clean` in *sysrepo* `build`, which will completely reset the whole *sysrepo* and remove all the SHM segments, YANG modules, and data. If you encounter the issue after this, please report it with the steps you did.
