### ISSUE TITLE
RET motor set-tilt issue.

### ISSUE THREAD

**Issue by Shubham-dash** [CESNET/netopeer2#1391]
Hi,
I am using ACE technologies DURA RET motor for the purpose of electrical tilt so the working process I am following to calibrate or to run the motor is as follows :

1. Sending some HDLC frames via m-plane (netopeer2-cli) which includes **`address assignment, link establishment, alarm subscribe, and information request`**, and then we are doing **`calibration/ setting tilt`**.

the problem I am facing is **`calibration is working fine for the motor as the motor is running from its initial to final`** but in the case of **`set-tilt the motor is not running though I am getting correct responses sometimes`**. if anyone is working on it or has any ideas, please share a solution.

I am pasting some logs for the set-tilt of TX and RX for reference please check.

TX Data:
0000 - **`7e 01 76 33 02 00 1e 00-b4 31 7e`**                  .v3.....1

```
**## UART_Tx Data[0]: 0x7E
## UART_Tx Data[1]: 0x01
## UART_Tx Data[2]: 0x76
## UART_Tx Data[3]: 0x33
## UART_Tx Data[4]: 0x02
## UART_Tx Data[5]: 0x00
## UART_Tx Data[6]: 0x1E
## UART_Tx Data[7]: 0x00
## UART_Tx Data[8]: 0xB4
## UART_Tx Data[9]: 0x31
## UART_Tx Data[10]: 0x7E
```

***** before UART_Rx ******

********* inside UART-Rx func ******
```
UART_Rx data[0] = 7e
UART_Rx data[1] = 1
UART_Rx data[2] = 1e
UART_Rx data[3] = 33
UART_Rx data[4] = 1
UART_Rx data[5] = 0
UART_Rx data[6] = 0
UART_Rx data[7] = bf
UART_Rx data[8] = 15
UART_Rx data[9] = 7e
```**

**Comment by michalvasko** [comment]
This seems like a really HW-specific issue and this is the wrong place to ask so I do not think anyone here will be able to help.
