### ISSUE TITLE
Port 830 connection gets closed on running sysrepocfg -m ietf-netconf-server

### ISSUE THREAD

**Issue by navneetkaurPS** [CESNET/netopeer2#1392]
We are facing issue where port 830 gets closed when we give below command

sysrepocfg -C ssh_callhome.xml -m ietf-netconf-server -d running -v4

Unless we reboot the machine netopeer2 server on rerunning could open the 830 port.

[ssh_callhome.zip](https://github.com/CESNET/netopeer2/files/11366530/ssh_callhome.zip)

**Comment by michalvasko** [comment]
It is not an issue, there is default configuration that includes listening on port 830 and you **replace** it with configuration that only has a Call Home connection so it behaves as it should. If you want to **merge** the Call Home configuration instead, use `-Essh_callhome.xml` instead of `-C`.
