### ISSUE TITLE
How to kill the netconf session from sysrepo application using session ID

### ISSUE THREAD

**Issue by NaveenSivakmr** [CESNET/netopeer2#1394]
Hi @michalvasko,

I am using the below packages 

**libnetconf2-2.1.28
libyang-2.1.30
netopeer2-2.1.49
sysrepo-2.2.36**   

I  have an application using sysrepo API's. My requirementis like, I need to close a particular netconf client from that sysrepo application in some certain cases. I have the netconf session ID. Using this ID , is there any API support to close a netconf session from sysrepo application.

Earlier we were using the different versions of netopeer packages

**libnetconf2-1.1.43
libyang-1.0.255
netopeer2-1.1.70
sysrepo-1.4.122** 

While using these versions it was possible to kill a netopeerclient session  using sr_rpc_send function from our application . But after updating  netopeer2 and supported package  versions, we are unable to kill the netopeer client like we did before. While going through the netopeer2 source code we came to understanding that in the latest versions there is check to identify the source of orginating RPC and netconf RPCs are ignored based on this check if they are not send in a NETCONF session. We tried commenting out the this check in the np2srv_rpc_kill_cb in netconf.c file .But then we got the errors as below

ERR] Callback event "rpc" with ID 1 processing timed out.
[WRN] Event "rpc" with ID 1 priority 0 failed (Timeout expired).
[WRN] Connection with CID 1 is dead.
[WRN] Recovering RPC/action "/ietf-netconf:kill-session" subscription of CID 1.
[ERR] User callback failed.

I believe the errors are from sysrepo. Can you kindly suggest us a way to implement our requirement as it required for us to terminate a session if it's inactive.(Inactive is decided if a session fails to send RPC to reset the counter monitoring different netopeer client sessions.

Kindly help on this

Thanks for your time in advance

**Comment by michalvasko** [comment]
Generally, this is intentionally not possible because you should not be able to affect NETCONF sessions by any non-NETCONF mechanisms. What you can always do is create a temporary NETCONF session and then use `kill-session`. That will make sure all the requirements of this RPC (such as passing a NACM check) are met.

**Comment by NaveenSivakmr** [comment]
Is it possible to create a temporary netconf session within our application. If yes can you please tell us the best way to do so?

**Comment by michalvasko** [comment]
I just meant you will create it, kill the session, and terminate it. There is no special way, just connect to the locally running *netopeer2-server* as if you were connecting to a remote NETCONF server.

**Comment by NaveenSivakmr** [comment]
I belive the best way to create a session is using  the nc_connect_unix() api since the nc_connect_ssh() will require authentication even if we are connecting to the localhost. The question that i have now is it just enough to send normal path as an arguement to the nc_connect_unix() or is socket that the netopeer server is already binded to?

**Comment by michalvasko** [comment]
Yes, you can connect via a UNIX socket if you want. To connect, you first need to set up *netopeer2-server* to create the socket and then you can connect to it. Using parameter `-U`, look at `netopeer2-server -h` for more details.

**Comment by michalvasko** [comment]
1. That is expected. For the client to pick up that it's connection has been terminated there would have to be some continuous communication with the server. Since there is not, it is learned on the next occasion such as trying to send an RPC.
2. The logs mean there is a memory leak. Depending on what exactly you are doing, it may be your fault or a bug in our library.
