### ISSUE TITLE
Internal error while sending notifications to multiple subscribers

### ISSUE THREAD

**Issue by ankit7gup** [CESNET/netopeer2#1399]
Hi @michalvasko,

We are using latest sysrepo-netopeer2.

While sending notifications to multiple subscribers with/without subscription filter, we are observing below error..
One client is based on old version of libnconf2 and another client uses NcClient.

netopeer2-server[1410]: Internal error (/usr/src/debug/sysrepo/git-r0/git/src/shm_sub.c:4385).

5 subscriptions are being done. Attached image

![image](https://github.com/CESNET/netopeer2/assets/61405352/c100f26c-2a7f-4af8-8a61-46cec99fad22)

Please suggest.

Thanks!

regards,
Ankit

**Comment by michalvasko** [comment]
It would be best if I could reproduce it but that may not be that simple, so I would at least need to see the error. Please apply the patch and post the printed error.
```patch
diff --git a/src/shm_sub.c b/src/shm_sub.c
index eccefe9f..6d2b670b 100644
--- a/src/shm_sub.c
+++ b/src/shm_sub.c
@@ -4382,6 +4382,7 @@ sr_shmsub_notif_listen_filter_is_valid(const struct lyd_node *notif, const char
     }
 
     if (lyd_eval_xpath(notif, xpath, &result)) {
+        sr_errinfo_new_ly(&err_info, LYD_CTX(notif), notif);
         SR_ERRINFO_INT(&err_info);
         sr_errinfo_free(&err_info);
         return 0;
```

**Comment by michalvasko** [comment]
Please try to use the latest *libyang* from the `devel` branch, I believe this has already been fixed.

**Comment by ankit7gup** [comment]
> Please try to use the latest _libyang_ from the `devel` branch, I believe this has already been fixed.

Can you please share the commit, if this can be done as a patch on last official release. Thanks!

**Comment by michalvasko** [comment]
Fine, https://github.com/CESNET/libyang/commit/3ff82dd469432b0d55c348b31ca8575e59b4d5a2.

**Comment by ankit7gup** [comment]
We tested with the code patch, seems like error is not there anymore, but if using create subscriptions, no notification is received with or without filters.
Please suggest.

**Comment by michalvasko** [comment]
If you are certain the filter you use is supposed to match a notification but it is not received, perhaps you have not subscribed to the stream that the notification is a part of? `NETCONF` includes all the notifications. Another problem that may occur is with NACM, if the subscriber does not have read access to the notification, it is silently dropped as per the specs.

If none of these issues occurred then I assume there really is a bug and you can either try to collect more information and even debug yourself to some extent or help me reproduce the problem.

**Comment by ankit7gup** [comment]
Using User-rpc with xml for create-subscription without any filter (NETCONF stream by default) notifications are not being printed, can only be seen with verbose level enabled. But same is visible and printed if using subscribe option from the cli.

**Comment by michalvasko** [comment]
Yes, that makes sense. It is one thing to subscribe for the notifications to be **sent** to the client but it is another to actually **receive** them. The simple *netopeer2-cli* does that only if `subscribe` is run, it does not inspect every RPC sent whether it is not `create-subscription` or `establish-subscription` since there are dedicated commands for that.

**Comment by michalvasko** [comment]
I am still confused, you wrote your own NC client using *libnetconf2* and are getting the error you posted? Just follow what `netopeer2-cli` is doing and it must work. I think there had been a function you needed to call on the client if you expect to receive notifications, which has most likely been removed later since I cannot even find the error in the current *libnetconf2*.

**Comment by ankit7gup** [comment]
> I am still confused; you wrote your own NC client using _libnetconf2_ and are getting the error you posted? Just follow what `netopeer2-cli` is doing and it must work. I think there had been a function you needed to call on the client if you expect to receive notifications, which has most likely been removed later since I cannot even find the error in the current _libnetconf2_.

Yes, there is own Nc client written using libnetconf2 which uses Libnetconf2 V0.11. 
Below is the API being used.
nc_recv_notif_dispatch(session, &ncClient::lnc2_notifClb);

  /* we read notif, want a rpc-reply */
    if (msgid && (msgtype == NC_MSG_NOTIF)) {
        if (!session->opts.client.ntf_tid) {
            ERR("Session %u: received a <notification> but session is not subscribed.", session->id);
            lyxml_free(session->ctx, xml);
            return NC_MSG_ERROR;
        }

**Comment by michalvasko** [comment]
Like I said, look into the code of *netopeer2-cli* in that version for functions to call. I cannot help you with such an outdated library,
