### ISSUE TITLE
I can't connect netopeer2-server

### ISSUE THREAD

**Issue by alecanty** [CESNET/netopeer2#1404]
Hi,
I installed the yang-sysrepo-libnetconf2 requirements for netopeer2 from the devel branch on ubuntu 20.04. Libssh version I installed is 0.8.6 . I open the Netopeer2 server with the command " **netopeer2-server -d -v3** " and I do not get an error in the opening part. 
The error that I got :

> [INF]: LN: Accepted a connection on 0.0.0.0:830 from 127.0.0.1:45992.
[INF]: SR: Session 114 (user "root", CID 30) created.
[INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: LN: Received an SSH message "request-auth" of subtype "none".
[INF]: LN: Received an SSH message "request-auth" of subtype "password".
[INF]: LN: Failed user "alecanty" authentication attempt (#1).
[2023/05/23 19:34:03.937809, 1] ssh_packet_disconnect_callback:  Received SSH_MSG_DISCONNECT: 11:Bye Bye
[ERR]: LN: Communication SSH socket unexpectedly closed.

After the installation, I have not made any server and client-side settings. Where can I do the settings that need to be made before opening the server and where these settings are made? Where can I access the user and password settings that I will connect to?

**Comment by michalvasko** [comment]
> Where can I do the settings that need to be made before opening the server and where these settings are made?

No manual configuration changes are needed after *netopeer2* installation to make it work. But you can adjust them the same way you would any other YANG configuration, in *sysrepo*. You can use `sysrepocfg`, to see the configuration use `sysrepocfg -X -m ietf-netconf-server`.

> Where can I access the user and password settings that I will connect to?

Currently, the users are read directly from the system and cannot be changed without changing the actual system users. We are working on updates that will allow configuring the users separately for NETCONF.
