### ISSUE TITLE
I can receive notification with subscribe, but not with subscribe --stream NETCONF

### ISSUE THREAD

**Issue by 13065166838** [CESNET/netopeer2#1406]
Hello Sir

In netopeer2-cli, we use subscribe and subscribe --stream NETCONF to test, both of them can receive kpi notification, but the latter can't receive supervision notification.
Can you give us some advice on how to troubleshoot the problem?

I am using following versions:
libnetconf2-v2.0.24
libyang-v2.0.112
sysrepo-v2.0.53

cli log:

> subscribe --stream NETCONF
nc DEBUG: Sending message:

#198

nc DEBUG: Sending message:
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="84"><create-subscription xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0"><stream>NETCONF</stream></create-subscription></rpc>

> subscribe
nc DEBUG: Sending message:

#153

nc DEBUG: Sending message:
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="84"><create-subscription xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0"/></rpc>

nc DEBUG: Received message:
<notification xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0"><eventTime>2022-03-24T11:50:26.743525740+00:00</eventTime><supervision-notification xmlns="urn:o-ran:supervision:1.0"/></notification>

>
notification (2022-03-24T11:50:26.743525740+00:00)
<supervision-notification xmlns="urn:o-ran:supervision:1.0"/>

Thanks

**Comment by michalvasko** [comment]
Seems like a bug and my suggestion is to update the versions you are using. They are quite old, anyway.
