### ISSUE TITLE
Using netopper2 for configuraing network interfaces and routing, etc.

### ISSUE THREAD

**Issue by 1061136002** [CESNET/netopeer2#1410]
Hi, I've installed and configured the netopeer2 on computer A and computer B. 
I run netopeer2-server on computer A and run netopeer2-cli on computer B. Through CLI, computer B is connected with computer A. 
My question is, how to configure A's IP address and routing, etc ,through CLI just use "edit-config ...."
Any extra app should be installed? is there any tutorial about this?

thanks in advance

**Comment by michalvasko** [comment]
Whatever you actually want to configure you have to code yourself or look for an existing solution but it is difficult to write something generic working on multiple platforms/distributions/... In any case, our projects provide just the framework, no actual functionality.

**Comment by michalvasko** [comment]
There is [sysrepo documentation](https://netopeer.liberouter.org/doc/sysrepo/master/html/) but do not expect to learn how to configure routing or whatever using it. There is general developer information which includes an explanation of implemented concepts for configuration of pretty much anything.
