### ISSUE TITLE
Password less authentication to netopeer2 server using netopeer2-cli

### ISSUE THREAD

**Issue by ChinmayaAgarwal** [CESNET/netopeer2#1413]
Hi,

Is there a way we can configure password less client connection to netopeer2-server using netopeer2-cli in the latest sysrepo/netopeer2-server version? If yes, which yang models/sample XMLs will be used to configure it?

Thanks and Regards,
Chinmaya Agarwal.

**Comment by michalvasko** [comment]
SSH `publickey` authentication is enabled on the server [by default](https://github.com/CESNET/netopeer2/blob/master/scripts/merge_config.sh#L45). So you only need to set up the CLI, set the key pair to be used using the command `auth keys add <public_key> <privake_key>`.

**Comment by qupfer** [comment]
Hi,
I have trouble with it too. But I know, that it worked in the past.
```
> auth keys
The keys used for SSH authentication:
#0: examples/admin_id_rsa (private examples/admin_id_rsa.pub)

> auth pref
The SSH authentication method preferences:
        'publickey':   10
        'password':    2
        'interactive': 1
        
        
> connect 
nc ERROR: Opening an SSH channel failed (Access denied for 'none'. Authentication that can continue: publickey,password).
cmd_connect: Connecting to the localhost:830 as user "root" failed.


> connect --login admin
admin@localhost password: 

```

**Comment by michalvasko** [comment]
Look at the output of the server, when run with `-d -v2`. I have not mentioned before that you need to set up the server correctly as well to accept the SSH key. That is currently working just like for `sshd(7)`, put the public key in `~/.ssh/authorized_keys` for the user that is allowed to authorize using the SSH key.
