### ISSUE TITLE
How to subscribe to multiple netconf callhome sessions with client

### ISSUE THREAD

**Issue by navneetkaurPS** [CESNET/netopeer2#1419]
Scenario : I have one client in ietf-netconf-server and able to establish call home connection. Opened a new terminal on same client machine, waiting in listen mode, wait will timeout but not get the call home request from netconf server until previous session is closed.

Is it possible that netopeer2 server establish multiple call home connections to same netconf client ?

**Comment by michalvasko** [comment]
> Is it possible that netopeer2 server establish multiple call home connections to same netconf client ?

No, you will have to create another client with the same IP addresses and a second connection will be established.
