### ISSUE TITLE
netopeer2-server crash while trying to send Disconnect notif

### ISSUE THREAD

**Issue by Krisscut** [CESNET/netopeer2#1432]
Hi !

I am in a situation where I noticed a crash in the netopeer2-server when it was in the process of sending a notification about a disconnected client.
Not sure if this is related to it since in the same trace prior to this there is a similar error but without the crash.

![image](https://github.com/CESNET/netopeer2/assets/8125922/fbf41df8-79a2-4e7b-b6ba-d8c273b8d118)
[snippet_one_run_crash.txt](https://github.com/CESNET/netopeer2/files/11937455/snippet_one_run_crash.txt)

**Version info:**
netopeer2-2.1.49

**Comment by michalvasko** [comment]
Definitely a problem but you are using quite an old version so there is a good chance it has been fixed. Generally, I can only fix issues when using the latest versions of `devel` branches of all the projects or at least the latest release (but that is not the case now, there are already quite a lot of stability improvements in the `devel` branches).

**Comment by Krisscut** [comment]
I updated to the latest release of netopeer2 (2.1.62).
I just wanted to clarify this point before performing more runs on it:

>  (but that is not the case now, there are already quite a lot of stability improvements in the devel branches)

Does it mean you would rather have a reproduction on the devel branches because you suspect the issue is already fixed ?
Usually I don't run on devel but it it is close enough to release I can try !

**Comment by michalvasko** [comment]
> Does it mean you would rather have a reproduction on the devel branches because you suspect the issue is already fixed ?

It is **always** best to use the `devel` branches when trying to reproduce any problems. I have only given up strictly requiring because many people are not willing to update to it.

> Usually I don't run on devel but it it is close enough to release I can try !

Please do.
