### ISSUE TITLE
Require guidance around Netopeer2

### ISSUE THREAD

**Issue by hrmnboparai** [CESNET/netopeer2#1433]
Hey michalvasko and community, I have built Netopeer2 but I am having difficulty in handling edit-config function myself. Can you please guide me as from where should I start exploring code in the directory so that I can understand things better.

**Comment by michalvasko** [comment]
*netopeer2* is actually just a remote NETCONF server for *sysrepo*, which is the main component you work with. So I suggest you start by reading its [documentation](https://netopeer.liberouter.org/doc/sysrepo/master/html/).

**Comment by hrmnboparai** [comment]
I greatly appreciate the support you provide to everyone. Thanks buddy.

**Comment by hrmnboparai** [comment]
Hey Michalvasko i have read the provided link and APIs mentioned in the sysrepo documentation. Now how should I proceed to know about Netopeer2 more since it does not have any documentation?

**Comment by michalvasko** [comment]
It has no documentation because it implements only the full specification of [NETCONF 1.1](https://datatracker.ietf.org/doc/html/rfc6241) so pretty much everything you need to know is in the RFC. Some additional details are at the end in the [README](https://github.com/CESNET/netopeer2/#nacm).
