### ISSUE TITLE
Change time netopeer2-server reported an error

### ISSUE THREAD

**Issue by lilililizheng** [CESNET/netopeer2#1434]
![image](https://github.com/CESNET/netopeer2/assets/106649263/8f580ae9-d6ca-40ac-be57-cbb78f2f267b)
The rpc of changing the time was sent, and the time in the plug-in was successfully changed, but the server reported an error

**Comment by michalvasko** [comment]
It seems *libssh* generated the error because it is using `CLOCK_REALTIME` to measure idle timeout. Nothing we can do about it, I am afraid, you can try reporting the problem to the *libssh* team.
