### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by navneetkaurPS** [CESNET/netopeer2#1439]
Random runtime issue is observed: -

**[ERR] Internal error (/var/lib/jenkins/workspace/Build_Package-Release-All/sysrepo/src/common.c:2428**

Netopeer2 version : 2.1.59
Also done a make clean, But the issue persists.
Sometimes we observe the issue when updating data in yang model using sysrepocfg --edit=vim

1) What could be the possible cause for the same? 
2) Is there way I can enable debug logs for netopeer2, libyang and sysrepo to provide you to assess what wrong we are doing in our application ?

**Comment by michalvasko** [comment]
1. Seems like a lock problem, somehow there are more unlocks than locks.
2. Yes, you run the server with `-d -v2`, it should then print information about what is going on. But you can provide the most information by describing your use-case in such a detail that I can reproduce it. Also, the issue may have already been fixed, you can try using the latest versions in the `devel` branches of all our projects.
