### ISSUE TITLE
Question (only): Aware of RESTCONF work?

### ISSUE THREAD

**Issue by RodneyCummings** [CESNET/Netopeer2#144]
I need an open-source Linux implementation of RESTCONF in C. I primarily need server-side.

Are contributors aware of work on a "LibRestconf", and integration into Netopeer2?

If not, do you have any guidelines/suggestions for someone who wants to start such an effort?

**Comment by rkrejci** [comment]
Hi, we are not aware of any existing open-source implementation of RESTCONF in C. We have it in our TODO, but we don't have enough resources to work on it now or in a near future.

The idea we have around the RESTCONF in Netopeer2 is about an alternative "transport" library to libnetconf2 - librestconf. Netopeer2-server can then use functions from such a library to receive requests and send resonses.

**Comment by harshapic** [comment]
@rkrejci  Its been a year raising this issue, reiterating same question are any efforts to get restconf in Netopeer2 server implementations just like in "https://github.com/CESNET/Netopeer/tree/restconf-impl" .
Is "libnetconf2" python modules only was to implement Restconf server as it already implemented few things in Netopeer2GUI

**Comment by rkrejci** [comment]
No, the situation is still the same - we have a lot of work with NETCONF and YANG stuff, and currently no free resources to work on RESTCONF.

libnetconf2 python module does not implement RESTCONF, it is pure NETCONF. Netopeer2GUI is also NETCONF only - python backend serves there as a NETCONF proxy between the frontend (user's browser) and NETCONF servers (devices).
