### ISSUE TITLE
ietf-yang-library@2019-01-04 module not found during make install in Netopeer2

### ISSUE THREAD

**Issue by hrmnboparai** [CESNET/netopeer2#1442]
Hey michalvasko,
 I have attached a screenshot for the problem. I was able to completely install it multiple times before but this time it is showing module not found error. The module is present in sysrepo/modules in my machine
![error](https://github.com/CESNET/netopeer2/assets/60837282/22d04076-4c6d-47de-922b-2de898ba311e)

**Comment by michalvasko** [comment]
I think this happens when you have a mixup of SHM and repository files that are using different paths. Run `make sr_clean` and after that *netopeer2* installation should work.

**Comment by hrmnboparai** [comment]
Hey michalvaso,
It built successfully after that but server is not starting now.
![Servererror](https://github.com/CESNET/netopeer2/assets/60837282/ef00c733-fb65-4078-9d40-45a053929a39)

**Comment by michalvasko** [comment]
Run it with `-d -v2` to see some output, please. Probably you need to run `make install` for *netopeer2* after `make sr_clean` so that the server installs everything it needs.
