### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by hrmnboparai** [CESNET/netopeer2#1443]
[INF]: LN: Failed to retrieve the shadow entry .

I installed sysrepo and netopeer2 and changed the port from default to 8000 in netopeer2/modules/ietf-netconf-server@2019-07-02.yang. After that I tried to connect using netopeer2-cli and this was the result

In netopeer2-cli it shows 
"nc ERROR: Unable to authenticate to the remote server (all attempts via supported authentication methods failed).
cmd_connect: Connecting to the localhost:8000 as user "harmandeep" failed."
![AuthError](https://github.com/CESNET/netopeer2/assets/60837282/585416b5-e6f8-4664-b27d-8d7eae52eab2)

**Comment by michalvasko** [comment]
I do not think the problem is the changed port, does the user `harmandeep` exist on the system?
