### ISSUE TITLE
How to set the key exchange algorithm for netopeer2-server?

### ISSUE THREAD

**Issue by Agao404** [CESNET/netopeer2#1456]
Hi michalvasko,

I specified KexAlgorithms diffie-hellman-group-exchange-sha256 in the client's config file, but the connection to netopeer2-server fails. If I comment out the KexAlgorithms parameter in the config file, I can connect successfully.
Can you please give some suggestions?

Here are some logs。
server:
[INF]: LN: Accepted a connection on 0.0.0.0:830 from 10.7.3.30:65315.
[INF]: SR: Session 394 (user "root", CID 19) created.
[2000/01/13 05:14:36.943868, 1] ssh_retrieve_dhgroup:  Unable to open moduli file: No such file or directory.

client:
> connect --login dasUser --host 10.7.3.200
nc DEBUG: nc_sock_connect(10.7.3.200, 830, -1, -1)
nc VERBOSE: Trying to connect via IPv4 to 10.7.3.200:830.
nc VERBOSE: Successfully connected to 10.7.3.200:830 over IPv4.
[2023/08/16 07:45:17.933824, 1] socket_callback_connected:  Socket connection callback: 1 (0)
[2023/08/16 07:45:18.059305, 1] ssh_known_hosts_read_entries:  Failed to open the known_hosts file '/etc/ssh/ssh_known_hosts': No such file or directory
nc ERROR: SSH connect timeout.
cmd_connect: Connecting to the 10.7.3.200:830 as user "dasUser" failed.
>

libnetconf2：2.1.35
libyang: 2.1.96
sysrepo:2.2.93
libssh 0.10.5

**Comment by michalvasko** [comment]
This behavior depends only on *libssh*, which seems to have printed a relevant error. In any case, you need to ask them for help, I do not know these details.
