### ISSUE TITLE
Questions about callhome

### ISSUE THREAD

**Issue by Agao404** [CESNET/netopeer2#1463]
I currently have a problem related to callhome and would like to ask for your help to see if it is as expected.

Scenario: In the following network diagram, DU2 will assign callhome IP to AU2, AU1 will not callHome to DU2 directly, but will send the callhome IP to AU1, and AU1 will callHome to DU2 to get some configurations after receiving it.
![image](https://github.com/CESNET/netopeer2/assets/104612620/50f20454-952e-468b-97a5-371bfa773658)

Issue: When AU1 successfully callHome to DU2, I reboot AU2, and found that AU1 won't callhome to DU2 again. I check the network status is ESTABLISHED through netstate command, but actually AU1 can't communicate with DU2, and won't re-initiate the callhome request.   
Is this in line with expectations, please?
![企业微信截图_16935613169259](https://github.com/CESNET/netopeer2/assets/104612620/6527c9f7-e37d-4db9-91dc-98f972ab550d)

**Comment by michalvasko** [comment]
Have you enabled `keepalives`? In any case, even based on the TCP status, it seems the problem is in the lower layers and we have no control over those if the connection is reported as working.
