### ISSUE TITLE
Netconf not reply OK when configuring xml.

### ISSUE THREAD

**Issue by Ray123456a** [CESNET/netopeer2#1465]
Hi, here is my problem, when I configuring the xml, these node parameters can be configured sucessfully, but I didn't recived the "OK" response.
![image](https://github.com/CESNET/netopeer2/assets/137867640/df7c7a3a-f1d7-4c84-be2f-fdb8956c290f)

**Comment by michalvasko** [comment]
Seems it takes too long for you to apply the configuration changes. Run *netopeer2* with `-t 30` to increase the default 5 s timeout.

**Comment by Ray123456a** [comment]
My netopeer2-server is running with -t 500

**Comment by michalvasko** [comment]
Oh, sorry, it is the client that times out, so add `--rpc-timeout 500` to the `edit-config` command.

**Comment by Ray123456a** [comment]
![image](https://github.com/CESNET/netopeer2/assets/137867640/5b2ade5b-c0e3-4a38-a706-c4be4a8deb29)
Still not work

**Comment by michalvasko** [comment]
What *netopeer2* version are you using? If the current release, this will most likely be a problem in your callbacks. Perhaps you do not even need such long timeouts but you need to fix a dead lock that you created.

**Comment by Ray123456a** [comment]
![image](https://github.com/CESNET/netopeer2/assets/137867640/794bbb65-a86d-4936-a4b8-4caafe7db880)

**Comment by michalvasko** [comment]
Like I said, you should update first because the next version 2.1.69 includes some concurrency fixes already. But please update to 2.1.71, the latest release.

**Comment by 13065166838** [comment]
Is it possible that the compilation of the underlying libraries is caused by inappropriate directives being used

**Comment by 13065166838** [comment]
Hello,
        I'm trying to build netopeer2 with custom library and header that I've put in other directory by doing this:
![企业微信截图_1694504941800](https://github.com/CESNET/netopeer2/assets/134588366/05ccf9d9-cd6f-4c66-95c8-5da7aa425edc)

but end up meet this error:
![企业微信截图_16945049789268](https://github.com/CESNET/netopeer2/assets/134588366/c0ff800b-f7b9-4cb7-aaba-4e3421283e8c)
![企业微信截图_16945050308633](https://github.com/CESNET/netopeer2/assets/134588366/46c24f69-5997-4a0b-8ec6-cf917aa1e210)

**Comment by michalvasko** [comment]
Firstly, I do not understand why you are writing into an unrelated issue, you should have created a new one.

It seems you are cross-compiling *netopeer2* and so are largely on your own, there is no official guide for that. But the [few words](https://github.com/CESNET/netopeer2/#compilation-options) mentioning it will be helpful in this case.
