### ISSUE TITLE
Possible SYN flooding on port 830

### ISSUE THREAD

**Issue by sivawabtec** [CESNET/netopeer2#1467]
Hello,

I see this error in dmesg once in a while. What does this signify? Is it concerning? appreciate the help!
"TCP: request_sock_TCPv6: Possible SYN flooding on port 830. Sending cookies. Check SNMP counters"

We use the below versions:
netopeer2: v1.1.39
libyang: v1.0.184
sysrepo: v1.4.70
libnetconf2: v1.1.26

**Comment by michalvasko** [comment]
Not sure what causes this but I have found it mentioned only together with some other major problems so if your only concern are the messages themselves, it is probably okay. Also, you should not be using *sysrepo* v1.x anymore and I am not able to provide any more support.

**Comment by jktjkt** [comment]
It's a message from your kernel that's telling you that there's a high rate of incoming TCP connections to your NETCONF server. An example of how to troubleshoot this is on [RedHat's portal](https://access.redhat.com/solutions/30453).
