### ISSUE TITLE
edit config self-defined yang model failed

### ISSUE THREAD

**Issue by Ray123456a** [CESNET/netopeer2#1468]
Hello , I defined a yang model as a augment of o-ran-performance-management.yang. And I have installed it sucessfully, but it failed when I want to enabled the augment nodes.
Here is the augment node as below:
![1](https://github.com/CESNET/netopeer2/assets/137867640/5a4e1e1a-5225-4cb3-8227-70f568885bf4)

The "netopeer2-cli" occured an error printing as below:
![2](https://github.com/CESNET/netopeer2/assets/137867640/464be2cb-94bf-4b88-9f7c-7fb0e286d9af)

**Comment by michalvasko** [comment]
You have not included the content of `N3_antenna_kpi_config.xml` but I assume you have not used the XML namespace of `vendor-specific-performance-management.yang` and kept the namespace of `o-ran-performance-management.yang`. That is the problem, augment nodes need to be in the namespace of their module.

**Comment by michalvasko** [comment]
Yes, the problem is exactly what I described in my previous reply, fix it accordingly.

**Comment by Ray123456a** [comment]
So , I have changed the xmlns as "urn:vs:performance-management:1.0", it still error occured:
![image](https://github.com/CESNET/netopeer2/assets/137867640/c8c3aecb-cb94-47aa-9de5-a9ccff9c7aab)

**Comment by Ray123456a** [comment]
![image](https://github.com/CESNET/netopeer2/assets/137867640/3d897b79-19aa-4641-8974-1c0e3f15c07f)

**Comment by michalvasko** [comment]
Look, these are complete basics of XML so I should not have to be explaining this to you. I said change the namespace of the augmented nodes only, keep the namespace of **performance-measurement-objects** the way it was. Just put `xmlns="urn:vs:performance-management:1.0` on **vendor-specific-measurement-objects** and it will work.

**Comment by Ray123456a** [comment]
Got it, my problem solved, thank you so much!!!
