### ISSUE TITLE
There is no rpc-reply  when <delete-config> target is candidate 

### ISSUE THREAD

**Issue by lqlucky** [CESNET/netopeer2#1473]
Hi,

I found use the following RPC , netopeer2-server (2.0.22) do not send rpc-reply

```
<rpc message-id="101"
xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<delete-config>
<target>
<candidate/>
</target>
</delete-config>
</rpc>

```

Is this a bug?

**Comment by michalvasko** [comment]
You are using a really old *netopeer2-server* so the first thing to do would be to update it. However, `delete-config` does not allow `candidate` as the child of `target`, it does not make sense and I could not even send such an RPC using *netopeer2-cli* because of this.

**Comment by lqlucky** [comment]
Will consider updating to the latest version later, we use other client and there is no restriction that target cannot be candidate.
Is there a standard document about delete-config does not allow candidate as the child of target?

**Comment by michalvasko** [comment]
Yes, there is the standard [NETCONF RFC](https://datatracker.ietf.org/doc/html/rfc6241#page-98).

**Comment by lqlucky** [comment]
OK, solved my question. Thanks for your reply
