### ISSUE TITLE
Support for RFC 7758: Time Capability in NETCONF

### ISSUE THREAD

**Issue by venkukakumani** [CESNET/netopeer2#1475]
Hi Team,

could you please confirm whether Netopeer2 supports "RFC 7758: Time Capability in NETCONF", if not is there a plan to support this functionality?

Thanks
Venkat

**Comment by michalvasko** [comment]
The first time I hear about this RFC/capability so no, *netopeer2* does not support this nor is there a plan to. But it seems fairly simple to implement.
