### ISSUE TITLE
2 sets of tls_certs on one endpoint

### ISSUE THREAD

**Issue by tbarkham** [CESNET/netopeer2#1477]
Overview: I would like to be able to have an "admin" and "guest" set of certs configured to the same endpoint
(I wrote a script to generate all the proper .cert, .key, and .pem files)

in [example_configuration/], 
[tls_keystore.xml] contains one "asymmetric-key" entry named "serverkey" with a "certificate" entry named "servercert"
[tls_truststore.xml] contains 2 lists of "certificates" entries: one list named "clientcerts" and another named "cacerts"
[tls_listen.xml] references both "serverkey" and "servercert" in its "keystore-reference" entry and later references "cacerts" and "clientcerts" in its "client-authentication" entry

In a broad sense, is it possible to "add a guest set of entries to each one of these xml files"
I have tried adding:
another "asymmetric-key" entry (in [tls_keystore.xml]), with "public-key" "private-key" "certificate"s values from a different set of .crt and .key files.
another "certificate" entry to the "clientcerts" "certificates" list and another "certificate" entry in "cacerts" "certificates" list in [tls_truststore.xml] 
another "cert-to-name" entry in [tls_listen.xml]
(I have also tried various combinations of [above], but nothing seems to work)

But this doesnt work as I get "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate signature failure (_ssl.c:1131)" when trying to connect with the guest set of certs

Is this even possible? Or does netopeer associate a single set of tls certs with a specific port?

I am able to add another endpoint, on a different port (6512), with these "guest" certs and I can connect that way, but I would like to be able to use these same "guest" certs to connect to the default port (6513) which is associated with the "admin" set of tls certs

**Comment by michalvasko** [comment]
What exactly are you trying to do? Have your server present a different certificate for different clients? Use different client certificates for authenticating different clients?

**Comment by tbarkham** [comment]
You can actually go ahead and close this I figured it out ... for anyone interested how I got it to work was getting the finger print for the server.crt and client.crt, and made a "cert-to-name" entry for each of their fingerprints
