### ISSUE TITLE
Is it possible to view the rpc messages replied by the release version of netopeer2-server

### ISSUE THREAD

**Issue by Agao404** [CESNET/netopeer2#1482]
Hi,
For the release version of netopeer2-server, is there a debugging method to get the reply from the server side? For example, when a get-rpc is received from a client, the reply can be viewed on the server side.

**Comment by michalvasko** [comment]
No, since there is one in the debug build, as you have probably noticed.

**Comment by Agao404** [comment]
Okay, thanks for the reply.
Currently I'm having a problem, after calling home to the client on the server side, I sent a get-rpc query on the client side for information about the interface, but the response I get is missing some nodes.
However in this case I am using netopeer2-cli in the device to query the interface information and it is right.
Could this mean that the message replied by the server is correct and there is an exception in the process of receiving it by a different client.

**Comment by michalvasko** [comment]
> Could this mean that the message replied by the server is correct and there is an exception in the process of receiving it by a different client.

Perhaps but checking what the actual RPC is is definitely a good idea, use a debug-build server for that.

**Comment by Agao404** [comment]
Ok，thank you.
