### ISSUE TITLE
How to user "replay" option when subscribe something on netopeer2-cli.

### ISSUE THREAD

**Issue by Ray123456a** [CESNET/netopeer2#1484]
I don't found out the example of this option.
![image](https://github.com/CESNET/netopeer2/assets/137867640/7281a60d-21ea-493e-858a-b735233778ba)

**Comment by michalvasko** [comment]
It is all standardized and explained in the official [RFC](https://datatracker.ietf.org/doc/html/rfc5277#section-3.3).
