### ISSUE TITLE
make install erro

### ISSUE THREAD

**Issue by gicfgg** [CESNET/netopeer2#1486]
sh-4.2# make install
[ 56%] Built target serverobj
[ 69%] Built target netopeer2-server
[100%] Built target netopeer2-cli
Install the project...
-- Install configuration: "Debug"
-- Up-to-date: /usr/local/share/yang/modules/netopeer2
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-yang-schema-mount@2019-01-14.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf@2013-09-29.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-interfaces@2018-02-20.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/iana-crypt-hash@2014-08-06.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tcp-common@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-restconf@2017-01-26.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tls-common@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-yang-push@2019-09-09.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tls-server@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf-server@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-ssh-server@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-keystore@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tcp-client@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf-nmda@2019-01-07.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-truststore@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-crypto-types@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-x509-cert-to-name@2014-12-10.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf-acm@2018-02-14.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-subscribed-notifications@2019-09-09.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-ip@2018-02-22.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/notifications@2008-07-14.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tcp-server@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-network-instance@2019-01-21.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf-monitoring@2010-10-04.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/nc-notifications@2008-07-14.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-yang-patch@2017-02-22.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-ssh-common@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-datastores@2018-02-14.yang
-- Up-to-date: /usr/local/share/netopeer2
-- Up-to-date: /usr/local/share/netopeer2/remove.sh
-- Up-to-date: /usr/local/share/netopeer2/merge_hostkey.sh
-- Up-to-date: /usr/local/share/netopeer2/merge_config.sh
-- Up-to-date: /usr/local/share/netopeer2/setup.sh
-- Installing: /usr/local/sbin/netopeer2-server
-- Set non-toolchain portion of runtime path of "/usr/local/sbin/netopeer2-server" to ""
-- Up-to-date: /usr/local/share/man/man8/netopeer2-server.8
-- Installing missing sysrepo modules...
" not found in local searchdirs.
" module failed.
sysrepoctl error: Failed to connect (libyang error)
For more details you may try to increase the verbosity up to "-v3".
" not found in local searchdirs.
" module failed.
sysrepoctl error: Failed to connect (libyang error)
For more details you may try to increase the verbosity up to "-v3".
CMake Error at cmake_install.cmake:108 (message):
   scripts/setup.sh failed: 1

make: *** [install] Error 1

what can i do,thank you

**Comment by michalvasko** [comment]
What version of *netopeer2* are you installing? What shell exactly are you using?

**Comment by gicfgg** [comment]
2.1.71 , centos 7 on docker , Bourne Again Shell（/bin/bash）

**Comment by michalvasko** [comment]
I have tested it on a fresh CentOS 7.9 image in docker and it worked fine (except for having a really outdated libraries so I would strongly suggest you use a more recent distribution). Can you provide the output of `sysrepoctl -l`? In any case, I would guess there are some other leftover libraries causing issues so my suggestion is to fully remove all of our libraries and reinstall them again.

**Comment by gicfgg** [comment]
I have tested it on CentOS 7.9 as you suggested,  it seems the problem is sysrepoctl, but it is sucessfully installed. here's make install output of netopeer and sysrepo.

sh-4.2# make install
[ 56%] Built target serverobj
[ 69%] Built target netopeer2-server
[100%] Built target netopeer2-cli
Install the project...
-- Install configuration: "Debug"
-- Installing: /usr/local/share/yang/modules/netopeer2
-- Installing: /usr/local/share/yang/modules/netopeer2/ietf-subscribed-notifications@2019-09-09.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/ietf-netconf-monitoring@2010-10-04.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/ietf-yang-schema-mount@2019-01-14.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/ietf-x509-cert-to-name@2014-12-10.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/ietf-truststore@2019-07-02.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/ietf-ssh-common@2019-07-02.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/ietf-keystore@2019-07-02.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/ietf-ip@2018-02-22.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/ietf-tcp-common@2019-07-02.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/ietf-ssh-server@2019-07-02.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/notifications@2008-07-14.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/ietf-netconf-acm@2018-02-14.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/nc-notifications@2008-07-14.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/ietf-interfaces@2018-02-20.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/ietf-tls-server@2019-07-02.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/ietf-datastores@2018-02-14.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/ietf-network-instance@2019-01-21.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/ietf-tls-common@2019-07-02.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/ietf-crypto-types@2019-07-02.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/ietf-yang-push@2019-09-09.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/ietf-netconf-nmda@2019-01-07.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/ietf-tcp-server@2019-07-02.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/ietf-netconf-server@2019-07-02.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/ietf-netconf@2013-09-29.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/ietf-tcp-client@2019-07-02.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/ietf-yang-patch@2017-02-22.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/iana-crypt-hash@2014-08-06.yang
-- Installing: /usr/local/share/yang/modules/netopeer2/ietf-restconf@2017-01-26.yang
-- Installing: /usr/local/share/netopeer2
-- Installing: /usr/local/share/netopeer2/remove.sh
-- Installing: /usr/local/share/netopeer2/setup.sh
-- Installing: /usr/local/share/netopeer2/merge_config.sh
-- Installing: /usr/local/share/netopeer2/merge_hostkey.sh
-- Installing: /usr/local/sbin/netopeer2-server
-- Set non-toolchain portion of runtime path of "/usr/local/sbin/netopeer2-server" to ""
-- Installing: /usr/local/share/man/man8/netopeer2-server.8
-- Installing missing sysrepo modules...
/usr/local/bin/sysrepoctl: error while loading shared libraries: libsysrepo.so.7: cannot open shared object file: No such file or directory
/usr/local/bin/sysrepoctl: error while loading shared libraries: libsysrepo.so.7: cannot open shared object file: No such file or directory
CMake Error at cmake_install.cmake:108 (message):
   scripts/setup.sh failed: 127


make: *** [install] Error 1
sh-4.2# sysrepoctl -l
sysrepoctl: error while loading shared libraries: libsysrepo.so.7: cannot open shared object file: No such file or directory









[ 37%] Built target srobj
[ 38%] Built target sysrepo
[ 44%] Built target sysrepoctl
[ 49%] Built target sysrepocfg
[ 59%] Built target sysrepo-plugind
[ 62%] Built target application_changes_example
[ 66%] Built target sr_set_item_example
[ 69%] Built target sr_get_items_example
[ 72%] Built target notif_subscribe_example
[ 76%] Built target notif_send_example
[ 79%] Built target rpc_send_example
[ 83%] Built target rpc_subscribe_example
[ 86%] Built target oper_data_pull_example
[ 89%] Built target oper_data_push_example
[ 93%] Built target oper_pull_push_example
[ 96%] Built target oper_data_poll_example
[100%] Built target oven
Install the project...
-- Install configuration: "Debug"
-- Installing: /usr/local/share/yang/modules/sysrepo
-- Installing: /usr/local/share/yang/modules/sysrepo/ietf-netconf-notifications.yang
-- Installing: /usr/local/share/yang/modules/sysrepo/ietf-origin.yang
-- Installing: /usr/local/share/yang/modules/sysrepo/sysrepo-factory-default.yang
-- Installing: /usr/local/share/yang/modules/sysrepo/ietf-yang-library@2016-06-21.yang
-- Installing: /usr/local/share/yang/modules/sysrepo/sysrepo-monitoring.yang
-- Installing: /usr/local/share/yang/modules/sysrepo/sysrepo-plugind.yang
-- Installing: /usr/local/share/yang/modules/sysrepo/ietf-datastores.yang
-- Installing: /usr/local/share/yang/modules/sysrepo/ietf-netconf.yang
-- Installing: /usr/local/share/yang/modules/sysrepo/ietf-factory-default.yang
-- Installing: /usr/local/share/yang/modules/sysrepo/ietf-netconf-with-defaults.yang
-- Installing: /usr/local/share/yang/modules/sysrepo/ietf-netconf-acm.yang
-- Installing: /usr/local/share/yang/modules/sysrepo/ietf-yang-library@2019-01-04.yang
-- Installing: /usr/local/share/yang/modules/sysrepo/sysrepo.yang
-- Installing: /usr/local/lib64/libsysrepo.so.7.19.3
-- Installing: /usr/local/lib64/libsysrepo.so.7
-- Set non-toolchain portion of runtime path of "/usr/local/lib64/libsysrepo.so.7.19.3" to ""
-- Installing: /usr/local/lib64/libsysrepo.so
-- Installing: /usr/local/include/sysrepo.h
-- Installing: /usr/local/include/sysrepo_types.h
-- Installing: /usr/local/include/sysrepo/plugins_datastore.h
-- Installing: /usr/local/include/sysrepo/version.h
-- Installing: /usr/local/include/sysrepo/values.h
-- Installing: /usr/local/include/sysrepo/xpath.h
-- Installing: /usr/local/include/sysrepo/error_format.h
-- Installing: /usr/local/include/sysrepo/netconf_acm.h
-- Installing: /usr/local/lib64/pkgconfig/sysrepo.pc
-- Installing: /usr/local/bin/sysrepoctl
-- Set non-toolchain portion of runtime path of "/usr/local/bin/sysrepoctl" to ""
-- Installing: /usr/local/bin/sysrepocfg
-- Set non-toolchain portion of runtime path of "/usr/local/bin/sysrepocfg" to ""
-- Installing: /usr/local/bin/sysrepo-plugind
-- Set non-toolchain portion of runtime path of "/usr/local/bin/sysrepo-plugind" to ""
-- Installing: /usr/local/share/man/man1/sysrepoctl.1
-- Installing: /usr/local/share/man/man1/sysrepocfg.1
-- Installing: /usr/local/share/man/man8/sysrepo-plugind.8
-- Installing: /usr/local/lib64/sysrepo-plugind/plugins

**Comment by michalvasko** [comment]
Just run `# ldconfig` to fix this.

**Comment by gicfgg** [comment]
I tried `# ldconfig` it didn't work,and I tried to edit  `/etc/ld.so.conf` as follewed, it didn't work still

include ld.so.conf.d/*.conf
/usr/local/lib/
/usr/local/unimrcp/lib/
/usr/local/apr/lib/
/usr/local/lib64/

sh-4.2# sysrepoctl -l -v3
" not found in local searchdirs.
" module failed.
sysrepoctl error: Failed to connect (libyang error)

sh-4.2# make install
[ 56%] Built target serverobj
[ 69%] Built target netopeer2-server
[100%] Built target netopeer2-cli
Install the project...
-- Install configuration: "Debug"
-- Up-to-date: /usr/local/share/yang/modules/netopeer2
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-subscribed-notifications@2019-09-09.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf-monitoring@2010-10-04.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-yang-schema-mount@2019-01-14.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-x509-cert-to-name@2014-12-10.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-truststore@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-ssh-common@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-keystore@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-ip@2018-02-22.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tcp-common@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-ssh-server@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/notifications@2008-07-14.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf-acm@2018-02-14.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/nc-notifications@2008-07-14.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-interfaces@2018-02-20.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tls-server@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-datastores@2018-02-14.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-network-instance@2019-01-21.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tls-common@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-crypto-types@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-yang-push@2019-09-09.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf-nmda@2019-01-07.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tcp-server@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf-server@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf@2013-09-29.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tcp-client@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-yang-patch@2017-02-22.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/iana-crypt-hash@2014-08-06.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-restconf@2017-01-26.yang
-- Up-to-date: /usr/local/share/netopeer2
-- Up-to-date: /usr/local/share/netopeer2/remove.sh
-- Up-to-date: /usr/local/share/netopeer2/setup.sh
-- Up-to-date: /usr/local/share/netopeer2/merge_config.sh
-- Up-to-date: /usr/local/share/netopeer2/merge_hostkey.sh
-- Installing: /usr/local/sbin/netopeer2-server
-- Set non-toolchain portion of runtime path of "/usr/local/sbin/netopeer2-server" to ""
-- Up-to-date: /usr/local/share/man/man8/netopeer2-server.8
-- Installing missing sysrepo modules...
sysrepoctl: /s4netopeer/sysrepo-2.2.105/src/common.c:3672: sr_ident2mod_ds: Assertion `0' failed.
" not found in local searchdirs.
" module failed.
sysrepoctl error: Failed to connect (libyang error)
For more details you may try to increase the verbosity up to "-v3".
CMake Error at cmake_install.cmake:108 (message):
   scripts/setup.sh failed: 1


make: *** [install] Error 1

**Comment by jktjkt** [comment]
sysrepo and libyang are picky about the "system state", and this state it split among the repository path (by default, `/etc/sysrepo`) and the shared memory (`/dev/shm`). Make sure that both have been cleaned, and re-run the installation of the whole stack (that is, libyang, sysrepo, libnetconf2, netopeer2, in this order) from scratch.

**Comment by gicfgg** [comment]
I got it from release, is this what you mean?
But i do notice on sysrepo page `This release depends on libyang ([v2.1.111](https://github.com/CESNET/libyang/releases/tag/v2.1.111))`,maybe this is the matter?
wget https://github.com/CESNET/libyang/archive/refs/tags/v2.1.128.tar.gz
wget https://github.com/sysrepo/sysrepo/archive/refs/tags/v2.2.105.tar.gz

**Comment by michalvasko** [comment]
Sorry, there was an unscheduled *libyang* release that broke these dependencies, please use either the current `master` or `devel` of all the projects, it should work then.

**Comment by gicfgg** [comment]
thank you very much,I use master of all the project, it worked!
