### ISSUE TITLE
 Netopeer server stops/crashes after error in sending notification

### ISSUE THREAD

**Issue by ankit7gup** [CESNET/netopeer2#1488]
Hi @michalvasko,

In our system where 2 client's are connected to the server, and one of them terminates the session, we have observed that netopeer server stops suddenly.
Would it be possible to infer anything from the below logs. Thanks!

 info netopeer2-server[1385]: EV LISTEN: "o-ran-supervision" "notif" ID 5387 processing.
 info netopeer2-server[1385]: EV LISTEN: "o-ran-supervision" "notif" ID 5387 priority 0 success (remaining 0 subscribers).
 info netopeer2-server[1385]: EV ORIGIN: "/o-ran-supervision:supervision-watchdog-reset" "rpc" ID 5388 priority 0 for 1 subscribers published.
 info netopeer2-server[1385]: EV ORIGIN: "/o-ran-supervision:supervision-watchdog-reset" "rpc" ID 5388 priority 0 succeeded.
 info netopeer2-server[1385]: Session 2: thread 0 event new RPC.
 err netopeer2-server[1385]: Session 7: SSH channel poll error (Socket error: Connection timed out).
 info netopeer2-server[1385]: Session 7: thread 1 event session terminated.
 err netopeer2-server[1385]: Invalid union value "À#036" - no matching subtype found. (Schema location "/ietf-netconf-notifications:netconf-session-end/source-host".)
 warning netopeer2-server[1385]: Failed to send a notification (libyang error).
 info netopeer2-server[1385]: Call Home client "vlan_client_2401:4900:0014:0408:0000:0000:0001:0972" session terminated.
 info netopeer2-server[1385]: Trying to connect via IPv6 to 2401:4900:14:408::1:972:4334.
 info netopeer2-server[1385]: Timed out after 500 ms (Operation now in progress).
 info netopeer2-server[1385]: EV LISTEN: "o-ran-supervision" "notif" ID 5388 processing.
 info netopeer2-server[1385]: EV LISTEN: "o-ran-supervision" "notif" ID 5388 priority 0 success (remaining 0 subscribers).
 info netopeer2-server[1385]: EV ORIGIN: "/o-ran-supervision:supervision-watchdog-reset" "rpc" ID 5389 priority 0 for 1 subscribers published.
 info netopeer2-server[1385]: EV ORIGIN: "/o-ran-supervision:supervision-watchdog-reset" "rpc" ID 5389 priority 0 succeeded.
 info netopeer2-server[1385]: Session 2: thread 0 event new RPC.

Version used: 2.1.59

**Comment by michalvasko** [comment]
I would suggest to update *netopeer2* to the latest release, there were a lot of concurrency/robustness improvements.
