### ISSUE TITLE
Not able to "sudo make install" netopeer2. I had installed everything properly earlier but now I'm getting the below error. I'm also getting a similar error when I try to run "sysrepoctl -l".

### ISSUE THREAD

**Issue by amal-k-ajay** [CESNET/netopeer2#1490]
amal@amal-VirtualBox:~/Desktop/workspace/netopeer2/build$ sudo make install

[ 18%] Built target serverobj
[ 22%] Built target netopeer2-server
[ 26%] Built target test_rpc
[ 30%] Built target test_edit
[ 35%] Built target test_filter
[ 39%] Built target test_subscribe_filter
[ 43%] Built target test_subscribe_param
[ 47%] Built target test_parallel_sessions
[ 52%] Built target test_candidate
[ 56%] Built target test_with_defaults
[ 60%] Built target test_nacm
[ 64%] Built target test_sub_ntf
[ 69%] Built target test_sub_ntf_advanced
[ 73%] Built target test_sub_ntf_filter
[ 77%] Built target test_yang_push
[ 81%] Built target test_yang_push_advanced
[ 85%] Built target test_confirmed_commit
[ 90%] Built target test_error
[100%] Built target netopeer2-cli
Install the project...
-- Install configuration: "Debug"
-- Up-to-date: /usr/share/yang/modules/netopeer2
-- Up-to-date: /usr/share/yang/modules/netopeer2/ietf-tcp-common@2019-07-02.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/ietf-subscribed-notifications@2019-09-09.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/ietf-tcp-server@2019-07-02.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/nc-notifications@2008-07-14.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/notifications@2008-07-14.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/ietf-yang-push@2019-09-09.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/ietf-keystore@2019-07-02.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/ietf-netconf@2013-09-29.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/ietf-netconf-nmda@2019-01-07.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/ietf-tcp-client@2019-07-02.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/ietf-network-instance@2019-01-21.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/ietf-ssh-server@2019-07-02.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/ietf-yang-schema-mount@2019-01-14.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/ietf-interfaces@2018-02-20.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/ietf-restconf@2017-01-26.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/ietf-tls-common@2019-07-02.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/ietf-netconf-server@2019-07-02.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/ietf-tls-server@2019-07-02.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/ietf-ssh-common@2019-07-02.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/ietf-netconf-acm@2018-02-14.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/ietf-datastores@2018-02-14.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/ietf-crypto-types@2019-07-02.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/ietf-yang-patch@2017-02-22.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/ietf-x509-cert-to-name@2014-12-10.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/iana-crypt-hash@2014-08-06.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/ietf-netconf-monitoring@2010-10-04.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/ietf-truststore@2019-07-02.yang
-- Up-to-date: /usr/share/yang/modules/netopeer2/ietf-ip@2018-02-22.yang
-- Up-to-date: /usr/share/netopeer2
-- Up-to-date: /usr/share/netopeer2/remove.sh
-- Up-to-date: /usr/share/netopeer2/merge_config.sh
-- Up-to-date: /usr/share/netopeer2/setup.sh
-- Up-to-date: /usr/share/netopeer2/merge_hostkey.sh
-- Up-to-date: /usr/sbin/netopeer2-server
-- Up-to-date: /usr/share/man/man8/netopeer2-server.8
-- Up-to-date: /usr/lib/systemd/system/netopeer2-server.service
-- Installing missing sysrepo modules...
" not found in local searchdirs.
" module failed.
sysrepoctl error: Failed to connect (libyang error)
For more details you may try to increase the verbosity up to "-v3".
" not found in local searchdirs.
" module failed.
sysrepoctl error: Failed to connect (libyang error)
For more details you may try to increase the verbosity up to "-v3".
**CMake Error at cmake_install.cmake:116 (message):
   scripts/setup.sh failed: 1**

make: *** [Makefile:110: install] Error 1

I saw a similar issue posted earlier ( https://github.com/CESNET/netopeer2/issues/1442 ) and I tried running the command "make sr_clean" in the build folder of sysrepo and installing netopeer2. Still the issue persists. Can someone provide me with any insight into solving this issue? 

P.S: I'm a university student and very new to this.

**Comment by michalvasko** [comment]
I would like to reproduce this because I have never encountered it and there may be a way of preventing it from happening. But I would think you have something wrong in the setup, some old libraries being used or something similar, so my suggestion is to completely uninstall all our projects and install then anew.

**Comment by amal-k-ajay** [comment]
Hi Michal,
I'm using xubuntu on VirtualBox. I was also wondering if the old libraries were interfering with it so I created a new virtual machine and tried again from scratch but still I'm getting the same issue. I'll try uninstalling all the projects and installing them anew now.

**Comment by michalvasko** [comment]
Okay but I can test that, too, if you send a link to the exact image you are using.

**Comment by amal-k-ajay** [comment]
Hi Michal,
Did you mean share the ovf file of the VM? ( I've uploaded that here: https://drive.google.com/file/d/11b-KnLtNtcSlayBS2GrYBYSg1YUrQvFg/view?usp=sharing ). I ran the below commands to install the dependencies, everything into a folder named workspace. 
[commands.txt](https://github.com/CESNET/netopeer2/files/13176852/commands.txt)

**Comment by michalvasko** [comment]
I meant the xUbuntu image that you have used but this will do, too. Going to try it out.

**Comment by amal-k-ajay** [comment]
Oh, I used xubuntu-22.04.3 (http://ftp.uni-kl.de/pub/linux/ubuntu-dvd/xubuntu/releases/22.04/release/) . Thanks for the help.

**Comment by amal-k-ajay** [comment]
Hi Michal,
Thank you. It is working now.
