### ISSUE TITLE
Netopeer2 Server hanged that netopeer2-cli can not connected 

### ISSUE THREAD

**Issue by DiepHieu99** [CESNET/netopeer2#1495]
Testing for a long time in a System,
I've discovered Netopeer2-server locked rpc session ( this session receive and process other rpcs) that make netopeer2-client (in other devices and localhost can not connected)
When kill all netopeer2 process and run again, it's back to normal.

The Netopeer2 version I use is 1.1.70

**Comment by michalvasko** [comment]
Could you please elaborate a but more, I do not think I understand. The whole server stops responding or what exactly happens? How many clients are connected, what do they generally do, just send RPCs or subscribe to notifications as well? What version are you using, did you mean 2.1.70?

**Comment by bingbin12389** [comment]
> Could you please elaborate a but more, I do not think I understand. The whole server stops responding or what exactly happens? How many clients are connected, what do they generally do, just send RPCs or subscribe to notifications as well? What version are you using, did you mean 2.1.70?

The netopeer2-server process is still running on system, at that time the server stop responding to other RPCs I send from netopeer2-client and also can not connect more client. There are more than 2 clients are connected, one for subscribing to notificattion and get active-alarms, the other one send RPCs. When I check log netopeer2-server It was stop. At the end, I kill all netopeer2 process and rerun netopeer2 process it back to normal. The netopeer2 version is 1.1.70 I use in my project is outdate.

**Comment by michalvasko** [comment]
I see, I cannot help you if you are using such an old version. You can only update it if you encounter any problems.
