### ISSUE TITLE
Query: Can sysrepo+netopeer2 achieve data isolation based on the client?

### ISSUE THREAD

**Issue by adamzyg** [CESNET/netopeer2#1496]
Frankly speaking, this demand may be a bit reckless.
Because we have the following requirements:
1. there is a yang module, which contain a notification
2. there are two netconf client, every one create different config data
3. the requirement is each client only wants to receive notifications generated by its own configuration data

I should describe this requirement clearly. Based on my current understanding of the Netconf implementation of the sysrepo+netopeer2 mechanism, I don't know how to complete this requirement. So I would like to ask the author for any suggestions.

**Comment by jktjkt** [comment]
Hi, this is a NETCONF server which implements various RFCs related to NETCONF. In these RFCs it's defined that there are no per-client notifications, and that the clients share a view of a common datastore content. What YANG models are you implementing that they are asking for something which is not according to the IETF RFCs?

**Comment by michalvasko** [comment]
I would reply pretty much the same as @jktjkt, it seems the architecture of your solution is not really compliant with YANG. However, it could be modeled properly when some identification of the specific config data (of the client) is included in the notification and then each client can filter only those referring to itself.
