### ISSUE TITLE
peer mount

### ISSUE THREAD

**Issue by rydy** [CESNET/netopeer2#1497]
Hi,

I have a question, Will [peer mounting](https://www.ietf.org/archive/id/draft-clemm-netmod-peermount-02.html#name-operations-beyond-data-retr) be supported in the future? 
Based on the current netopeer2, I want to implement peermount, do you have any suggestions?

**Comment by michalvasko** [comment]
You waste no time, the draft is rather new and I have not been aware of it so no, we have no plans of supporting it, currently. I went quickly through it and I think I understand the general idea but it seems there is just a "mount client" defined as an opaque external entity that is identified by IP address/host name/whatever and should provide the mounted data if requested by the server.

It seems this mount client is outside the scope of that draft. I understand that but at the same time I think it would be a good idea to have a separate draft for its specification. Or how exactly did you plan on implementing it? I cannot help you much without this information.

Still, this does not seem exactly like a trivial feature and a great care should should be taken when design the whole solution.
