### ISSUE TITLE
netopeer2-cli problems with systemd

### ISSUE THREAD

**Issue by mislavn** [CESNET/Netopeer2#150]
Hi Radek,

I have a problem with netopeer2-cli when sysrepo and Netopeer2 server are run with systemd.

Everything is run inside a docker container. If I use the docker container without systemd everything works just fine.

When I use systemd, netopeer2-cli would not ask me for a password on `connect` command.

netopeer2-cli:
```
> connect --login netconf
The authenticity of the host 'localhost' cannot be established.
ssh-rsa key fingerprint is eb:66:bb:27:62:86:cd:e4:ed:e8:c8:12:c3:c6:0a:a7:2a:52:e8:9e.
Are you sure you want to continue connecting (yes/no)? yes
nc ERROR: ttyname_r failed (Inappropriate ioctl for device).
nc ERROR: Authentication failed (Invalid argument in ssh_userauth_kbdint_setanswer).
cmd_connect: Connecting to the localhost:830 as user "netconf" failed.
```

netopeer2-server:
```
May 31 15:42:16 b588e41887e3 netopeer2-server[128]: netopeer2-server[128]: Accepted a connection on :::830.
May 31 15:42:16 b588e41887e3 netopeer2-server[128]: Accepted a connection on :::830.
May 31 15:42:16 b588e41887e3 netopeer2-server[128]: [2017/05/31 15:42:16.951334, 1] ssh_server_connection_callback:  SSH client banner: SSH-2.0-libssh-0.7.3
May 31 15:42:16 b588e41887e3 netopeer2-server[128]: [2017/05/31 15:42:16.951355, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-libssh-0.7.3
May 31 15:42:17 b588e41887e3 netopeer2-server[128]: [2017/05/31 15:42:17.008132, 2] ssh_server_curve25519_init:  SSH_MSG_KEX_ECDH_REPLY sent
May 31 15:42:17 b588e41887e3 netopeer2-server[128]: [2017/05/31 15:42:17.008197, 2] ssh_server_curve25519_init:  SSH_MSG_NEWKEYS sent
May 31 15:42:17 b588e41887e3 netopeer2-server[128]: [2017/05/31 15:42:17.016937, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
May 31 15:42:17 b588e41887e3 netopeer2-server[128]: netopeer2-server[128]: Received an SSH message "request-service" of subtype "ssh-userauth".
May 31 15:42:17 b588e41887e3 netopeer2-server[128]: netopeer2-server[128]: Received an SSH message "request-auth" of subtype "none".
May 31 15:42:17 b588e41887e3 netopeer2-server[128]: Received an SSH message "request-service" of subtype "ssh-userauth".
May 31 15:42:17 b588e41887e3 netopeer2-server[128]: netopeer2-server[128]: Received an SSH message "request-auth" of subtype "interactive".
May 31 15:42:17 b588e41887e3 netopeer2-server[128]: [2017/05/31 15:42:17.017295, 2] ssh_message_auth_interactive_request:  Warning: Got a keyboard-interactive response but it seems we didn't send the request.
May 31 15:42:17 b588e41887e3 netopeer2-server[128]: Received an SSH message "request-auth" of subtype "none".
May 31 15:42:17 b588e41887e3 netopeer2-server[128]: Received an SSH message "request-auth" of subtype "interactive".
May 31 15:42:17 b588e41887e3 netopeer2-server[128]: [2017/05/31 15:42:17.017842, 1] ssh_packet_disconnect_callback:  Received SSH_MSG_DISCONNECT: 11:Bye Bye
May 31 15:42:17 b588e41887e3 netopeer2-server[128]: netopeer2-server[128]: Communication SSH socket unexpectedly closed.
May 31 15:42:17 b588e41887e3 netopeer2-server[128]: Communication SSH socket unexpectedly closed.

```
Can you give me a hint where could be the problem?

Do you need any other logs or the dockerfile?

**Comment by jktjkt** [comment]
How are you launching the ``netopeer2-server`` process? Are you relying on the socket activation by any chance?

We aren't using containers with systemd, but we're running netopeer as a systemd's unit. Here's something that works reasonably well for us:

```
[Unit]
Description=A NETCONF server on top of sysrepo
After=syslog.target network.target sysrepod.service
Requires=sysrepod.service
PartOf=sysrepod.service

[Service]
Type=forking
ExecStart=/usr/bin/netopeer2-server
PIDFile=/var/run/netopeer2-server.pid
PrivateTmp=yes
PrivateDevices=yes
ProtectSystem=yes
ProtectHome=yes
SystemCallArchitectures=native
Restart=always

[Install]
WantedBy=multi-user.target
```

The ``PartOf=sysrepo.service`` is interesting -- it ensures that whenever the ``netopeer2-server`` dies and launches again, that the ``sysrepod`` is restarted as well. We had to do that because we saw "weird failure modes" otherwise (and we don't have the logs anymore, ENOTIME, sorry).

**Comment by mislavn** [comment]
> How are you launching the netopeer2-server process? Are you relying on the socket activation by any chance?

Hi @jktjkt, yes we are using socket activation.

> The PartOf=sysrepo.service is interesting -- it ensures that whenever the netopeer2-server dies and launches again, that the sysrepod is restarted as well. We had to do that because we saw "weird failure modes" otherwise (and we don't have the logs anymore, ENOTIME, sorry).

That is helpful, thanks.

I did a few tests and I think the problem is not in systemd or Netopeer2 but in the way the docker container is run.

To use systemd inside docker I had to run docker with:

`sudo docker run -d -v /sys/fs/cgroup:/sys/fs/cgroup:ro --cap-add SYS_ADMIN -p 830:830 --name sysrepo --rm --privileged --entrypoint=/sbin/init sysrepo/sysrepo-netopeer2:snabb_devel`

But if I run another docker container with

`docker run -i -t --rm sysrepo/sysrepo-netopeer2:snabb_devel bash`

I can use netopeer2-cli from the second docker container to connect to the first one with systemd.

@rkrejci  what do you think, is there a bug/problem in netopeer2-cli or should I close the ticket?

**Comment by rkrejci** [comment]
It seems to me as two different issues. Which libnetconf2 version are you using?

**Comment by rkrejci** [comment]
The thing with getting password is that the default libnetconf callback for this (used also by cli) expects that it is taken from terminal device (stdin is one of the pseudo terminals). According to the error message you are getting it seems that the `STDIN_FILENO` (file with file descriptor 0) is not pseudo terminal. Is it possible in you use case?

**Comment by mislavn** [comment]
> It seems to me as two different issues. Which libnetconf2 version are you using?

I used the latest master.

> The thing with getting password is that the default libnetconf callback for this (used also by cli) expects that it is taken from terminal device (stdin is one of the pseudo terminals). According to the error message you are getting it seems that the STDIN_FILENO (file with file descriptor 0) is not (pseudo) terminal. Is it possible in you use case?

That makes sense. Probably the problem is somewhere in the way the docker container is run.
I will close this ticket.

**Comment by jktjkt** [comment]
IMHO it's a bit unsafe to use socket activation here -- in my experience, Netopeer2's startup is quite a heavyweight process, and it's probably not a good idea to use socket activation for that.

**Comment by mislavn** [comment]
> IMHO it's a bit unsafe to use socket activation here -- in my experience, Netopeer2's startup is quite a heavyweight process, and it's probably not a good idea to use socket activation for that.

At the moment we where using the systemd script for testing purposes. When we build a production grade software we will take that into account, thanks for the advice.
