### ISSUE TITLE
[Query] Notification timeout error

### ISSUE THREAD

**Issue by ankit7gup** [CESNET/netopeer2#1500]
Hi @michalvasko ,

I have a query, in which situation, application can get timeout error while trying to send a notification. with below parameters.
sr_notif_send_tree(session, notif_structure, timeout = 0, wait = 0)

Internal Application Logs: 
Could not send notification, Timeout expired" SR_ERR_TIME_OUT" 

We are using the netopeer2 version 2.1.59

**Comment by michalvasko** [comment]
Probably a dead lock problem and it is no use creating similar issues over and over. You will have to update *netopeer2*, there is no other way to get rid of them.

**Comment by ankit7gup** [comment]
We are already in process to upgrade. Just want to make sure, With the latest upgrade, even this one will be resolved.

**Comment by michalvasko** [comment]
I cannot guarantee that but we did rather extensive testing and found no more issues after several fixes.
