### ISSUE TITLE
sr_oper_get_subscribe returning SR_ERR_INVAL_ARG for specific yang model

### ISSUE THREAD

**Issue by zdevcic** [CESNET/netopeer2#1504]
Hello,

we are using netopeer2 v2.1.59 and on attempt to subscribe for oper data we are getting SR_ERR_INVAL_ARG. It is happening for specific yang model only:

[vendor-specific-thresholds.yang.txt](https://github.com/CESNET/netopeer2/files/13501086/vendor-specific-thresholds.yang.txt)

Error is returned for the first leaf: using-vswr-major-threshold.

What we find significant here is that leafs of container using-vswr-thresholds are all read-only, but container itself is not specified as read only (so it is read-write by default). With such yang model we get SR_ERR_INVAL_ARG.

But, if we specify container using-vswr-thresholds as read only, then all works fine and no issues.

Is this a bug present here, since attached yang model which is triggering error is generally allowed as well?

Thank you.

**Comment by michalvasko** [comment]
What is the error message? Enable logging by calling `sr_log_stderr(SR_LL_ERR)`.

**Comment by zdevcic** [comment]
Error we are getting is:

**[ERR] Operational get subscription for XPath "/vendor-specific-thresholds:vswr-thresholds/using-vswr-thresholds/using-vswr-major-threshold" already exists and SR_SUBSCR_OPER_MERGE not used.**

Really not sure why it says that subscription already exists, because this is the first and only attempt of it, I have checked my code and traces to verify this detail.

Also, as already mentioned, declaring related container using-vswr-thresholds as "config false;" in the yang resolves the issue. Hard to relate the way we avoid/resolve the issue with error description we get.

**Comment by jktjkt** [comment]
Please post your code on how exactly you are creating that subscription.

**Comment by zdevcic** [comment]
I use same approach for all XPaths in the app, number of them, at all other places it works fine except this one.

**Comment by zdevcic** [comment]
After more checks and tests I came up with the conclusion that issue is caused by double subscription happening, but it was double subscription for config data (container global-vswr-thresholds), not for oper data (container using-vswr-thresholds) as sysrepo error suggests. After removing double config data subscription, oper data subscription is successful.

As earlier explained, really if we explicitly declare container using-vswr-thresholds as read-only ("config false;"), issue is not observed. Interesting and also a bit confusing/misguiding detail.

Not sure if you think there is more to investigate in sysrepo code, based on my summary. In any case I have no more queries and thank you for your support.

**Comment by michalvasko** [comment]
Could you please share the exact XPath you were subscribed to twice?

**Comment by zdevcic** [comment]
First subscription was towards regex:

/vendor-specific-thresholds:vswr-thresholds/global-vswr-thresholds

Then we had same subscription, but towards exact paths:

/vendor-specific-thresholds:vswr-thresholds/global-vswr-thresholds/vswr-major-threshold
/vendor-specific-thresholds:vswr-thresholds/global-vswr-thresholds/vswr-critical-threshold

**Comment by michalvasko** [comment]
And you are talking about `sr_module_change_subscribe()`, right?

**Comment by zdevcic** [comment]
Will update once I have detailed info.
