### ISSUE TITLE
ietf-netconf-monitoring:netconf-state does not return required sub modules

### ISSUE THREAD

**Issue by mattiaswal** [CESNET/netopeer2#1511]
I try to download all needed yang models automatically, but i cant list the sub modules since they are missing
in ietf-netconf-monitoring:netconf-state/schemas. According to the [RFC](https://www.rfc-editor.org/rfc/rfc6022) they should also be there.

sysrepo say:
<pre>
{
            "name": "ietf-ipv6-unicast-routing",
            "revision": "2018-03-13",
            "namespace": "urn:ietf:params:xml:ns:yang:ietf-ipv6-unicast-routing",
            "location": [
              "file:///etc/sysrepo/yang/ietf-ipv6-unicast-routing@2018-03-13.yang"
            ],
            "submodule": [
              {
                "name": "ietf-ipv6-router-advertisements",
                "revision": "2018-03-13",
                "location": [
                  "file:///etc/sysrepo/yang/ietf-ipv6-router-advertisements@2018-03-13.yang"
                ]
              }
            ]
          },
</pre>

but when listing modules from netopeer2 i only get ietf-ipv6-unicast-routing

**Comment by michalvasko** [comment]
Okay, should be fixed.

**Comment by mattiaswal** [comment]
Thanks, it works now!

**Comment by troglobit** [comment]
Amazing response time on this one, wow! :exploding_head::tada:
