### ISSUE TITLE
call-home connection error (Communication SSH socket unexpectedly closed)

### ISSUE THREAD

**Issue by chendu471** [CESNET/netopeer2#1513]
Hi @michalvasko , facing issue with call-home , attaching the screenshot of the error
**netopeer2-cli:**
![image](https://github.com/CESNET/netopeer2/assets/64268873/28071ac7-add7-495f-9cd9-66ddf60302f8)
**netopeer2-server:**
![image](https://github.com/CESNET/netopeer2/assets/64268873/2cd5ab04-3ac3-40a7-8174-8b11821da9e6)

**ssh-version:**
![image](https://github.com/CESNET/netopeer2/assets/64268873/935ced32-556a-4692-bf59-bba1b56c0719)

**OS-details:**
![image](https://github.com/CESNET/netopeer2/assets/64268873/c92ecc55-be31-4e21-8574-1c0c58fb55c3)

**netopeer2-server:**
![image](https://github.com/CESNET/netopeer2/assets/64268873/24037d19-eeb1-488c-a123-3a456e401716)

I am facing this issue only for root user

**Comment by michalvasko** [comment]
Can you normally log in as `root`? The information is taken from the system so it should work exactly as it does normally. Also, you are using quite an old version of *netopeer2* so updating it and all the dependencies may help.
