### ISSUE TITLE
Slow fetching of operational data

### ISSUE THREAD

**Issue by mzagozen** [CESNET/netopeer2#1515]
We use netopeer2 and sysrepo as a model driven NETCONF device simulator for our testing. We have a container image where all the components are installed and we can mount in our (or vendors) YANG models and startup / operational data at runtime. This works very well since some improvements were made to sysrepo with regards to handling large schemas, so nice work!

These are the versions of the components we use:
- LIBYANG_TAG=v2.1.111
- SYSREPO_TAG=v2.2.105
- LIBSSH_TAG=libssh-0.10.5
- LIBNETCONF2_TAG=v2.1.37
- NETOPEER2_TAG=v2.1.71

To load operational data from XMLs into sysrepo we use the sysrepo Python
library like so:

```python
with sysrepo.SysrepoConnection() as conn:
    with conn.start_session("operational") as sess:
        with conn.get_ly_ctx() as ctx:
            for file_oper in files:
                with open(file_oper) as f:
                    data = ctx.parse_data_file(f, "xml", parse_only=True)
                sess.edit_batch_ly(data)
                sess.apply_changes()
```

We keep the connection to sysrepo open to preserve the data .This approach
allows us to load any valid XML containing operational data into sysrepo.

We have found that fetching this operational via NETCONF data using subtree filtering is slow when large schemas are loaded. Our test suite includes a performance test where we query the operational data a number of times to get the average. The results for a simple schema with essentially just a couple of nodes are below. The first test is fetching data directly from sysrepo, then we use XPath and subtree filtering with netopeer2.

```
make test-sysrepo
make[5]: Entering directory '/home/runner/work/notconf/notconf/fixups/test/yang-modules'
docker cp ../../../perftest/test-sysrepo.py test-yang-test_yang-modules-latest-6810250131:/
docker exec test-yang-test_yang-modules-latest-6810250131 /test-sysrepo.py --path /bob/state/great
--- sysrepo 1000 get_data: mean=0.132152 ms; σ=0.031530 ms ---
make[5]: Leaving directory '/home/runner/work/notconf/notconf/fixups/test/yang-modules'
make test-netopeer-xpath
make[5]: Entering directory '/home/runner/work/notconf/notconf/fixups/test/yang-modules'
docker run -t --rm --network container:test-yang-test_yang-modules-latest-6810250131 --name test-yang-test_yang-modules-latest-6810250131-test-netconf test-netconf -n 100 -get-data -datastore operational -filter-xpath /bob/state/great
--- netopeer 100: mean=1.136439 ms σ=0.923629 ms
make[5]: Leaving directory '/home/runner/work/notconf/notconf/fixups/test/yang-modules'
make test-netopeer-subtree
make[5]: Entering directory '/home/runner/work/notconf/notconf/fixups/test/yang-modules'
docker run -t --rm --network container:test-yang-test_yang-modules-latest-6810250131 --name test-yang-test_yang-modules-latest-6810250131-test-netconf test-netconf -n 100 -get-data -datastore operational -filter-subtree "<bob><state><great/></state></bob>"
--- netopeer 100: mean=1.132265 ms σ=0.094334 ms
```

The results for a more complex using vendor YANG models from Nokia for SROS are below. Even fetching operational data directly from sysrepo is significantly slower. Interestingly adding in netopeer using XPath filtering only adds 1.5ms to the mean time, which is comparable to the simple schema results above. However when we use subtree filtering the mean time is 71ms which is significantly slower.

```
make test-sysrepo
make[3]: Entering directory '/home/runner/work/notconf/notconf/fixups/yang/vendor/nokia'
podman cp ../../../../perftest/test-sysrepo.py test-yang-sros-22.2-6810250131:/
podman exec test-yang-sros-22.2-6810250131 /test-sysrepo.py --path "/state/chassis[chassis-class='router'][chassis-number='1']/peq[peq-slot='12']/equipped-type" -n 100
--- sysrepo 100 get_data: mean=16.973753 ms; σ=0.397774 ms ---
make[3]: Leaving directory '/home/runner/work/notconf/notconf/fixups/yang/vendor/nokia'
make test-netopeer-xpath
make[3]: Entering directory '/home/runner/work/notconf/notconf/fixups/yang/vendor/nokia'
podman run -t --rm --network container:test-yang-sros-22.2-6810250131 --name test-yang-sros-22.2-6810250131-test-netconf test-netconf -n 100 -get-data -datastore operational -filter-xpath "/state/chassis[chassis-class='router'][chassis-number='1']/peq[peq-slot='12']/equipped-type"
--- netopeer 100: mean=18.658908 ms σ=2.926695 ms
make[3]: Leaving directory '/home/runner/work/notconf/notconf/fixups/yang/vendor/nokia'
make test-netopeer-subtree
make[3]: Entering directory '/home/runner/work/notconf/notconf/fixups/yang/vendor/nokia'
podman run -t --rm --network container:test-yang-sros-22.2-6810250131 --name test-yang-sros-22.2-6810250131-test-netconf test-netconf -n 100 -get-data -datastore operational -filter-subtree "<state><chassis><chassis-class>router</chassis-class><chassis-number>1</chassis-number><peq><peq-slot>12</peq-slot><equipped-type/></peq></chassis></state>"
--- netopeer 100: mean=71.214750 ms σ=4.249701 ms
```

The reason we're looking to improve this is that the network management system (Cisco NSO) queries the devices using subtree filtering and the performance is not adequate when making thousands of queries. All the code and the models for this are available in https://github.com/mzagozen/notconf. The results were taken from CI runs:
- https://github.com/mzagozen/notconf/actions/runs/6810250131/job/18518190771 for the simple schema
- https://github.com/mzagozen/notconf/actions/runs/6810250131/job/18518515645 for the large SROS schema

**Comment by jktjkt** [comment]
Nice work. I'm not the maintainer of this SW, but according to the examples you provided, you're getting average response times of 70ms, which look reasonable to me. What bottleneck(s) are you hitting, and what is the expected performance? In other words, why is this a problem?

**Comment by mzagozen** [comment]
My goal is to use this as an open source drop-in replacement for *netsim* (based on Tail-f ConfD) which is the simulator we currently use. With *netsim* we're getting responses to the same NETCONF queries in an average of 3ms, which is over 20x faster.  So the bottleneck is just the time it takes to get a response to a query compared to the baseline. We have some performance-intensive tests that are taking too long to complete because of this. Now one could argue why we're making thousands of queries to fetch the data in the first place, but that is a discussion we must have with the NMS vendor (Cisco) :)

**Comment by michalvasko** [comment]
Okay, I have tried your repo and running the tests and it works fine but that is not much use to me if I am to optimize anything. And there is way too many new things for me to get all the information I need by myself so I could use your help.

But before any optimizations in the code, are you able to use different XPath/subtree filter? If you specify the module name of the first node in the XPath or the namespace of `state` in the subtree filter, you could significantly improve the performance.

So, to optimize anything, I would need to reproduce the specific use-case locally so that I can collect `callgrind` or `perf` data. Or you could provide them yourself, if you can.

**Comment by michalvasko** [comment]
Okay, I had some time so I found all the required files and the problem was fairly basic. Should be fixed and both the XPath and subtree filters take the same amount of time to evaluate.

**Comment by mzagozen** [comment]
Thank you for looking into this @michalvasko! I can confirm the time to evaluate a subtree expression is now equivalent for sysrepo and netopeer2.

> But before any optimizations in the code, are you able to use different XPath/subtree filter? If you specify the module name of the first node in the XPath or the namespace of state in the subtree filter, you could significantly improve the performance.

Good suggestion. The NETCONF client we use in real environment (Cisco NSO) already does this, but I now added it to the notconf test suite as well. I did not see an appreciable difference in the performance though.

**Comment by michalvasko** [comment]
> Good suggestion. The NETCONF client we use in real environment (Cisco NSO) already does this, but I now added it to the notconf test suite as well. I did not see an appreciable difference in the performance though.

Fair enough, I guess it is negligible compared to the other more demanding tasks.
