### ISSUE TITLE
netopeer2 debian package fails to install

### ISSUE THREAD

**Issue by nhathaway** [CESNET/netopeer2#1516]
Install log below (on Ubuntu 22.04):

Selecting previously unselected package netopeer2.
(Reading database ... 183185 files and directories currently installed.)
Preparing to unpack .../netopeer2_2.1.71-ubuntu1_amd64.deb ...
Unpacking netopeer2 (2.1.71-ubuntu1) ...
Setting up netopeer2 (2.1.71-ubuntu1) ...
[ERR] Datastore plugin "JSON notif" not found.
sysrepoctl error: Failed to connect (Item not found)
For more details you may try to increase the verbosity up to "-v3".
[ERR] Datastore plugin "JSON notif" not found.
sysrepoctl error: Failed to connect (Item not found)
For more details you may try to increase the verbosity up to "-v3".
dpkg: error processing package netopeer2 (--configure):
 installed netopeer2 package post-installation script subprocess returned error exit status 1
Processing triggers for man-db (2.10.2-1) ...
Errors were encountered while processing:
 netopeer2
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by nhathaway** [comment]
Versions: 

libyang2_2.1.128
libsysrepo7_2.2.105
libnetconf2-3_2.1.37

I notice that the offending/missing plugin is mentioned in common.c of sysrepo.

**Comment by nhathaway** [comment]
$ sysrepoctl --version
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.2.105 (SO v7.19.3)

$ sysrepoctl -L -v3
[ERR] Datastore plugin "JSON notif" not found.
sysrepoctl error: Failed to connect (Item not found)

**Comment by michalvasko** [comment]
You most likely have some old version of *sysrepo* installed as well, which was compiled and installed manually, not from a package. I have just build packages from `master` branches of all the projects and installed them on Ubuntu 22, all worked fine.

**Comment by nhathaway** [comment]
No, that's not it. I do notice that there have been changes on the sysrepo master branch since the release in August. Can you build the release rather than the head of master?

**Comment by nhathaway** [comment]
https://github.com/sysrepo/sysrepo/commit/dcea390f83fb95151afb56f6e045c4d4b7fac10b

This may be significant

**Comment by michalvasko** [comment]
You are probably right, there were some problems because of the extra *libyang* release. So use the current `master` for now, a new release is planned early next year.

**Comment by nhathaway** [comment]
I built with libyang 2.1.111 and now that error is not present.

**Comment by michalvasko** [comment]
That should be fine as well.
