### ISSUE TITLE
Netopeer2-Server latest release installation behaving differently when installed at different times.

### ISSUE THREAD

**Issue by Bhanupriya03** [CESNET/netopeer2#1517]
On 13th December 2023, we installed netopeer2-server and all other packages from their latest released branches. Please find below the details of all the packages : 

libnetconf2 : 2.1.37 
libssh : 0.9.7 
libyang : 2.1.128
netopeer2 : 2.1.71
openssl : 3.2.0
sysrepo : 2.2.105

We were able to compile all these packages successfully then. 
But today (19th December 2023), we tried installing all the above packages with the same steps and with the same versions but we are getting the following issue while doing 'make install' in netopeer2 : 

[root@discourse build]# make install
Consolidate compiler generated dependencies of target serverobj
[ 56%] Built target serverobj
Consolidate compiler generated dependencies of target netopeer2-server
[ 69%] Built target netopeer2-server
Consolidate compiler generated dependencies of target netopeer2-cli
[100%] Built target netopeer2-cli
Install the project...
-- Install configuration: "Debug"
-- Up-to-date: /usr/local/share/yang/modules/netopeer2
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/iana-crypt-hash@2014-08-06.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-crypto-types@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-datastores@2018-02-14.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-interfaces@2018-02-20.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-ip@2018-02-22.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-keystore@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf-acm@2018-02-14.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf-monitoring@2010-10-04.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf-nmda@2019-01-07.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf-server@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf@2013-09-29.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-network-instance@2019-01-21.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-restconf@2017-01-26.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-ssh-common@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-ssh-server@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-subscribed-notifications@2019-09-09.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tcp-client@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tcp-common@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tcp-server@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tls-common@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-tls-server@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-truststore@2019-07-02.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-x509-cert-to-name@2014-12-10.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-yang-patch@2017-02-22.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-yang-push@2019-09-09.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-yang-schema-mount@2019-01-14.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/nc-notifications@2008-07-14.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/notifications@2008-07-14.yang
-- Up-to-date: /usr/local/share/netopeer2
-- Up-to-date: /usr/local/share/netopeer2/merge_config.sh
-- Up-to-date: /usr/local/share/netopeer2/merge_hostkey.sh
-- Up-to-date: /usr/local/share/netopeer2/remove.sh
-- Up-to-date: /usr/local/share/netopeer2/setup.sh
-- Installing: /usr/local/sbin/netopeer2-server
-- Set runtime path of "/usr/local/sbin/netopeer2-server" to ""
-- Up-to-date: /usr/local/share/man/man8/netopeer2-server.8
-- Installing missing sysrepo modules...
**" not found in local searchdirs.
" module failed.
sysrepoctl error: Failed to connect (libyang error)
For more details you may try to increase the verbosity up to "-v3".
" not found in local searchdirs.
" module failed.
sysrepoctl error: Failed to connect (libyang error)
For more details you may try to increase the verbosity up to "-v3".
CMake Error at cmake_install.cmake:104 (message):
   scripts/setup.sh failed: 1

make: *** [Makefile:83: install] Error 1**

Also, the system configurations are same for both the VMs : 
CentOS Linux release 8.4.2105

Please suggest how to proceed further.

**Comment by michalvasko** [comment]
Obviously, you are installing different versions of the packages (how else could possibly be the results different?). Most likely they are the latest releases but *libyang* had a separate release, which broke other projects. Please take the projects from their current `master` or `devel` branches, those should work. A new release is planned for early next year that should again work properly.

**Comment by Bhanupriya03** [comment]
Hi Michal

Thank you so much for the response.

I tried compiling devel branches for all the projects and it compiled successfully. Also, I was able to start netopeer2-server successfully. However, I wasn't able to do password less connection between netopeer2-cli and netopeer2-server. I did the following steps for the same : 

1. Append <public-key> to the authorized_keys
2. On netopeer2-cli, auth keys add <public-key> <private-key>
3. On netopeer2-cli, auth pref publickey 1
4. On netopeer2-cli, auth pref password 0
5. On netopeer2-cli, auth pref interactive 0
6. Restarted netopeer2-server

Wasn't able to achieve password less connection with these steps. Please suggest how to proceed further in this.

**Comment by michalvasko** [comment]
Right, you may have used the `master` branch if you wanted everything to work as before. We are still finishing some new functionality and you need to put the authorized keys into *netopeer2-server* configuration now, they are not automatically read from the system.
