### ISSUE TITLE
Setting default operation as replace in the RPC gives "data model already exists" error.

### ISSUE THREAD

**Issue by rosy8** [CESNET/Netopeer2#152]
Hi,

When default-op is "replace", its giving error as below..

```xml
<?xml version="1.0" encoding="utf-8"?>
 <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="13">
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>data-exists</error-tag>
    <error-severity>error</error-severity>
    <error-path>/xxx-config/vrf:vrfs/vrf[name='Test']</error-path>
    <error-message xml:lang="en">Request could not be completed because the relevant data model content already `exists.</error-message>
 </rpc-error>
</rpc-reply>
```

By looking at the code and log, what I could get that it's trying to do "sr_set_item" before doing "sr_delete_item". 

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
based on [this](https://github.com/CESNET/Netopeer2/blob/master/server/op_editconfig.c#L492) line what you are describing should not happen. So, please provide the initial configuration (also with model would be nice) and the edit-config you are trying to execute.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Thanks for responding back.
 Below is the rpc request 

`<?xml version="1.0" encoding="utf-8"?>
`<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="">
  `<edit-config>`
   `<target>`
      `<candidate/>`
    `</target>`
   **`<default-operation>replace</default-operation>`**
    `<config>`
     `<xxx-config xmlns="http://www.abc.com/ns/xxx-config">`
       ` <vrfs xmlns="http://www.abc.com/ns/xxx-vrf">`
          `<vrf>`
            `<name>Test</name>`
            `<owner-tag/>`
            `<l3-forwarding>false</l3-forwarding>`
            `<bgp>true</bgp>`
            `<domain>default</domain>`
          `</vrf>`
        `</vrfs>`
      `</xxx-config>`
    `</config>`
  `</edit-config>`
`</rpc>`

I could not debug it but by looking at the code flow what I am suspecting its hitting the code as mentioned below 
        **case NP2_EDIT_REPLACE_INNER:**
        case NP2_EDIT_CREATE:
            /* create the node, but it must not exists */
            ret = sr_set_item(sessions->srs, path, &value, **SR_EDIT_STRICT);**

==log==
 netopeer2-server[4039]: Resolving unresolved data nodes and their constraints...
 netopeer2-server[4039]: All data nodes and constraints resolved.
 sysrepod[4028]: [INF] Set item request candidate datastore, xpath: /xxx-config/xxx-vrf:vrfs/vrf[name='Test']
 sysrepod[4028]: [INF] Data file /etc/sysrepo/data/xxx-config.running loaded successfully
 sysrepod[4028]: [ERR] Setting of item failed /xxx-config/xxx-vrf:vrfs/vrf[name='Test'] 74
 sysrepod[4028]: [ERR] Set item failed
 sysrepod[4028]: [ERR] Set item failed for '/xxx-config:ensemble-config/xxx-vrf:vrfs/vrf[name='Test']', session id=1706326020.
 **netopeer2-server[4039]: Error by processing of the set-item request (session id=1706326020): The item already exists.**
 netopeer2-server[4039]: Error by processing of the request.
 netopeer2-server[4039]: Session 2: thread 0 event new RPC.

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
it should be fixed, but for next time a few comments. Look at how I edited your comment and please enclose the code the way I do, what you were doing is fine for one line code, not for blocks. Also, I asked for initial configuration and the model, but you provided neither. I managed to reproduce the issue without this information, but that is not always the case, so please stick to what I ask of you for me to be able to fix issues effectively.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Thanks for the fix.
Hey sorry, I misread it and instead of posting initial config I posted the edit-config which we were sending. 
Regarding model, it was clearly visible from XML, so that's why did not post it. 

Regarding editing, the process which I follow is actually a  tedious one which even I donot like to do. 
So I will really appreciate if you could let me know how you edit/ what you do when posting a big chunks of code especially if its in the above format . It will be very helpful .

Thanks in advance.

Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
the simplest way of inserting code probably is simply pasting it, selecting it all, and clicking `<>` icon from the top tool bar in reply editing window. You will notice it will enclose your code in \`\`\`. Optionally, you can specify syntax highlighting by adding the language name after those first \`\`\` such as \`\`\`C.

Regards,
Michal
