### ISSUE TITLE
Question about  TLS connect faild

### ISSUE THREAD

**Issue by lqlucky** [CESNET/netopeer2#1521]
Hi, 

1. Used version as following:
sysrepo-2.2.105 + libyang-2.1.111 + netopeer2-2.1.71 + libnetconf2-2.1.37

2. Certificate and config use under netopeer2/example_configuration

3. Client use netopeer2-cli

4. Scenario as follow:

> cert add ./ca.pem
> cert display
-----ca----- serial: 45ce2c8a91ef25294dad0221461662941bd5e11a
Subject: C=CZ, ST=South Moravia, L=Brno, O=CESNET z.s.p.o., OU=TMC, CN=example CA/emailAddress=ca@example.org
Issuer:  C=CZ, ST=South Moravia, L=Brno, O=CESNET z.s.p.o., OU=TMC, CN=example CA/emailAddress=ca@example.org
Valid until: Sep  1 10:21:01 2031 GMT
> connect --tls --cert ./client.crt --key ./client.key //connect successful

> connect --tls --host 10.8.15.219 --cert ./client.crt --key ./client.key //connect failed 
Error as follow:
nc ERROR: Server certificate error (Hostname mismatch).
nc ERROR: SSL connect to "10.8.15.219" failed (certificate verify failed).
cmd_connect: Connecting to the 10.8.15.219:6513 failed.

Why did the above error occur?

**Comment by Roytak** [comment]
As far as I know you can not use the example certificate for any domain other than localhost. That is why you are getting the error. Make sure to setup the server's certificate correctly.
