### ISSUE TITLE
can't connect to server, Showing remote host key changed.

### ISSUE THREAD

**Issue by Siddalingeshwar123** [CESNET/netopeer2#1524]
Hi,
I have been facing some issue while connecting from cli to server 
The cli logs are:
![image](https://github.com/CESNET/netopeer2/assets/96812180/0a8d718b-f3f0-4634-8b05-08e44b6a1bb2)
The server logs are: 
![image](https://github.com/CESNET/netopeer2/assets/96812180/96a910e1-6d26-4f4a-990d-98daf82de6f8)
Thanks!

**Comment by michalvasko** [comment]
This is not a problem specific to *netopeer2* and it would good to try to understand what exactly is going on to avoid potential security issues. But, to solve this problem (during testing) you can simply remove the offending key(s) using the `knownohsts --del <idx>` command in the CLI.

**Comment by Siddalingeshwar123** [comment]
Thanks @michalvasko but now I am facing new errors
![image](https://github.com/CESNET/netopeer2/assets/96812180/03d9fcbf-2177-46da-8435-40fc657d689c)

**Comment by michalvasko** [comment]
On your system, the `root` user is not allowed to authenticate using a password so the server refuses to do it as well. Not sure what else to tell you, either use another user or change your system `root` user.

**Comment by Siddalingeshwar123** [comment]
Hi @michalvasko , If we use another user we can't access files while using:
edit-config --source running --test test-only --config=interfaces.xml

**Comment by michalvasko** [comment]
Fine, then fix your `root` user or you can also use SSH keys to authenticate, not the password.

**Comment by Siddalingeshwar123** [comment]
We have already used SSH key. This is the process we used
Generate the ssh keys using this command   

ssh-keygen -f id_rsa -N ""   

Public and private keys will be generated in the root directory.     

Create a directory .ssh using this command   

mkdir –p .ssh/authorized_keys   

Copy the public key id_rsa.pub to this file /root/.ssh/authorized_keys   

cp id_rsa.pub /root/.ssh/authorized_keys  
After copying the public key, we can connect to the netopeer2-server, get into this path /usr/local/bin and execute this command netopeer2-cli. We will get into the prompt “>”  

# sudo netopeer2-cli  

**Help command provides all the available commands related to netopeer2-cli.   

Provide the below three auth related commands to manage ssh authentication options.**   

>auth pref publickey 4 && auth keys add /root/id_rsa.pub /root/id_rsa && auth hostkey-check disable

**Comment by michalvasko** [comment]
Normally, the keys are stored in `~/.ssh/id_rsa(.pub)` and `authorized_keys` is a file with all the authorized public keys. Also, I do not think `&&` works in the CLI, it is not bash but a custom command line that supports only direct commands.

**Comment by Siddalingeshwar123** [comment]
Could you please look into it
![image](https://github.com/CESNET/netopeer2/assets/96812180/4136d1aa-f681-4513-96af-466a50c3d9aa)
and the server log is
![image](https://github.com/CESNET/netopeer2/assets/96812180/ed19dd65-016b-4f68-b759-73a1a9f90412)

**Comment by michalvasko** [comment]
Firstly, you ignored the message
```
The new private key is not accessible...
```
meaning the CLI is not able to read the keys it is supposed to use so they will never be used, obviously.

Then, you may want to change the authentication preferences, print them with `auth pref` and then can make `publickey` most preferred by calling `auth pref publickey 4`, for example.
