### ISSUE TITLE
netopeer2 build getting failed

### ISSUE THREAD

**Issue by RSowndarya** [CESNET/netopeer2#1525]
Hi,
i'm using devel branch of libyang,sysrepo,libnetconf2 and netopeer2.
while building netopeer2,observed the error as below:

#make install
[ 44%] Built target serverobj
[ 61%] Built target netopeer2-server
[100%] Built target netopeer2-cli
Install the project...
-- Install configuration: "Debug"
-- Up-to-date: /usr/local/share/yang/modules/netopeer2
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-restconf@2017-01-26.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-yang-push@2019-09-09.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/notifications@2008-07-14.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-datastores@2018-02-14.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf-nmda@2019-01-07.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-interfaces@2018-02-20.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf-monitoring@2010-10-04.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-yang-patch@2017-02-22.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf@2013-09-29.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-network-instance@2019-01-21.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-subscribed-notifications@2019-09-09.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-ip@2018-02-22.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-netconf-acm@2018-02-14.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/nc-notifications@2008-07-14.yang
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/ietf-yang-schema-mount@2019-01-14.yang
-- Up-to-date: /usr/local/share/netopeer2/scripts
-- Up-to-date: /usr/local/share/netopeer2/scripts/merge_config.sh
-- Up-to-date: /usr/local/share/netopeer2/scripts/remove.sh
-- Up-to-date: /usr/local/share/netopeer2/scripts/setup.sh
-- Up-to-date: /usr/local/share/netopeer2/scripts/common.sh
-- Up-to-date: /usr/local/share/netopeer2/scripts/merge_hostkey.sh
-- Up-to-date: /usr/local/sbin/netopeer2-server
-- Up-to-date: /usr/local/share/man/man8/netopeer2-server.8
-- Up-to-date: /etc/pam.d/netopeer2.conf
-- Installing missing sysrepo modules...
-- Generating a new RSA host key "genkey" if not already added...
CMake Error at cmake_install.cmake:129 (message):
   scripts/merge_hostkey.sh failed: 127

make: *** [Makefile:100: install] Error 1

Could suggest me a solution for this?

**Comment by michalvasko** [comment]
There is no error, unfortunately. Can you maybe run the script manually for it to print something?

**Comment by RSowndarya** [comment]
hi Michal,

As suggested i have added print and run the script manually. But it didn't get print.

**Comment by michalvasko** [comment]
Okay, that complicates it. What Linux are you on, what shell are you using?

**Comment by RSowndarya** [comment]
Hi michal, 

Build issue got resolved now. I have tried ssh callhome with example_configuration  provided with devel branch.
After authentication, timeout occured and observed few errors too in server.

**CLI:**
> listen
Waiting 60s for an SSH Call Home connection on port 4334...
The authenticity of the host '::ffff:127.0.0.1' cannot be established.
ssh-rsa key fingerprint is 19:20:34:99:50:4f:84:b7:ce:eb:57:dd:9d:29:06:d4:77:e6:c1:aa.
Are you sure you want to continue connecting (yes/no)? yes
Keyboard-Interactive Authentication
Please enter your authentication token
root's password:
>
> status
Current NETCONF session:
  ID          : 33
  Host        : ::ffff:127.0.0.1
  Port        : 59680
  Transport   : SSH
  Capabilities:
        urn:ietf:params:netconf:base:1.0
        urn:ietf:params:netconf:base:1.1
        urn:ietf:params:netconf:capability:writable-running:1.0
        urn:ietf:params:netconf:capability:candidate:1.0
        urn:ietf:params:netconf:capability:confirmed-commit:1.1
        urn:ietf:params:netconf:capability:rollback-on-error:1.0
        urn:ietf:params:netconf:capability:validate:1.1
        urn:ietf:params:netconf:capability:startup:1.0
        urn:ietf:params:netconf:capability:xpath:1.0
        urn:ietf:params:netconf:capability:with-defaults:1.0?basic-mode=explicit&also-supported=report-all,report-all-tagged,trim,explicit
        urn:ietf:params:netconf:capability:notification:1.0
        urn:ietf:params:netconf:capability:interleave:1.0
        urn:ietf:params:netconf:capability:url:1.0?scheme=http,https,ftp,ftps,file
        urn:ietf:params:xml:ns:yang:ietf-yang-metadata?module=ietf-yang-metadata&revision=2016-08-05
        urn:ietf:params:xml:ns:yang:ietf-inet-types?module=ietf-inet-types&revision=2013-07-15
        urn:ietf:params:xml:ns:yang:ietf-yang-types?module=ietf-yang-types&revision=2013-07-15
        urn:ietf:params:xml:ns:yang:ietf-netconf-acm?module=ietf-netconf-acm&revision=2018-02-14
        urn:ietf:params:netconf:capability:yang-library:1.1?revision=2019-01-04&content-id=600881550
        urn:sysrepo:plugind?module=sysrepo-plugind&revision=2022-08-26
        urn:ietf:params:xml:ns:netconf:base:1.0?module=ietf-netconf&revision=2013-09-29&features=writable-running,candidate,confirmed-commit,rollback-on-error,validate,startup,url,xpath
        urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults?module=ietf-netconf-with-defaults&revision=2011-06-01
        urn:ietf:params:xml:ns:yang:ietf-netconf-notifications?module=ietf-netconf-notifications&revision=2012-02-06
        urn:ietf:params:xml:ns:netconf:notification:1.0?module=notifications&revision=2008-07-14
        urn:ietf:params:xml:ns:netmod:notification?module=nc-notifications&revision=2008-07-14
        urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring?module=ietf-netconf-monitoring&revision=2010-10-04
        urn:ietf:params:xml:ns:yang:ietf-x509-cert-to-name?module=ietf-x509-cert-to-name&revision=2014-12-10
        urn:ietf:params:xml:ns:yang:iana-crypt-hash?module=iana-crypt-hash&revision=2014-04-04&features=crypt-hash-md5,crypt-hash-sha-256,crypt-hash-sha-512
>

**SERVER:**
[INF]: LN: Call Home client "default-client" timeout of 5 seconds expired, reconnecting.
[INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4334.
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Call Home client "default-client" timeout of 5 seconds expired, reconnecting.
**[INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4334.
[INF]: LN: Successfully connected to localhost:4334 over IPv4.
[ERR]: LN: SSH key exchange timeout.**
[INF]: SR: EV LISTEN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 1 priority 0 processing (remaining 1 subscribers).
[INF]: NP: Module "ietf-datastores@<any>" was requested.
[INF]: SR: EV LISTEN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 1 priority 0 success (remaining 0 subscribers).
[INF]: SR: EV LISTEN: "/ietf-netconf:get" "rpc" ID 1 priority 0 processing (remaining 1 subscribers).
**[ERR]: NP: np2srv_rpc_get_cb: Failed to find NETCONF session with NC ID 33.**
[INF]: SR: EV LISTEN: "/ietf-netconf:get" "rpc" ID 1 priority 0 fail (remaining 1 subscribers).
[INF]: SR: EV LISTEN: "/ietf-netconf:get" "rpc" ID 2 priority 0 processing (remaining 1 subscribers).
[ERR]: NP: np2srv_rpc_get_cb: Failed to find NETCONF session with NC ID 33.
[INF]: SR: EV LISTEN: "/ietf-netconf:get" "rpc" ID 2 priority 0 fail (remaining 1 subscribers).
[INF]: LN: Call Home client "default-client" timeout of 5 seconds expired, reconnecting.
[INF]: LN: Call Home client "default-client" endpoint "default-ssh" failed connection attempt limit 3 reached.
[INF]: LN: Call Home client "default-client" endpoint "default-ssh" connecting...
[INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4334.
[INF]: LN: getsockopt() error (Connection refused).


Could you please help on this.

**Comment by michalvasko** [comment]
What *libssh* version are you using?

**Comment by RSowndarya** [comment]
using libssh 0.9.5

**Comment by michalvasko** [comment]
> Build issue got resolved now.

Actually, could you mention briefly what the problem was? Maybe there is something to improve.

As for the SSH error, it is quite strange so I am asking again, what platform are you on, are you cross-compiling? What crypto backend library is your *libssh* using? Ideally, it should be OpenSSL, there are some problems with *grypt*, for example.

**Comment by RSowndarya** [comment]
> what platform are you on, are you cross-compiling? 

Linux 5.13.0-30-generic . No we are not cross-compiling

>Ideally, it should be OpenSSL, there are some problems with _grypt_, for example.

Yes, openssl only, its version is 3.0.0

**Comment by michalvasko** [comment]
Then I suggest you turn on debug messages and maybe see something relevant there, for server its `-c SSH`. However, this is a *libssh* issue so I will likely not be able to help and you should ask them.

**Comment by michalvasko** [comment]
Not really, starting from 0.9.5 it should work, but we are always using (and testing with) recent versions, currently 0.10.5.

**Comment by RSowndarya** [comment]
Hi Michal,

We are facing issue  frequently during netopeer2 build. Please find the error log as below:

**_-- Installing missing sysrepo modules...
-- Generating a new RSA host key "genkey" if not already added...
CMake Error at cmake_install.cmake:141 (message):
   scripts/merge_hostkey.sh failed: 127

Makefile:99: recipe for target 'install' failed
make: *** [install] Error 1_**


Could you please share your comments on this ?

**Comment by michalvasko** [comment]
You said you fixed this previously but have not replied how exactly. I cannot comment anything as there is no error message.

**Comment by RSowndarya** [comment]
just rebuild done for the specific module at that time it got fixed. No other particular fixes we done.

**Comment by RSowndarya** [comment]
> What specific module? 

sysrepo and netopeer2

**Comment by michalvasko** [comment]
I do not understand but it does not matter, without more information I am not able to help.

**Comment by RSowndarya** [comment]
> Hi Michal,
> 
> We are facing issue frequently during netopeer2 build. Please find the error log as below:
> 
> **_-- Installing missing sysrepo modules... -- Generating a new RSA host key "genkey" if not already added... CMake Error at cmake_install.cmake:141 (message): scripts/merge_hostkey.sh failed: 127
> 
> Makefile:99: recipe for target 'install' failed make: *** [install] Error 1_**
> 
> Could you please share your comments on this ?


Issue got fixed after copying libs to expected path.
