### ISSUE TITLE
ietf-truststore compatibility between version 2.1.71 and version 2.2.13

### ISSUE THREAD

**Issue by robbynet** [CESNET/netopeer2#1529]
Hello
Please help to clarify the understanding with content of this new Netoper2 version 2.2.13
Question : Can you confirm that there is not backward compatibility provided by Netopeer2 with new revision 28-12-2023 of ietf-truststore delivered in Netopeer2 version 2.2.13 ?
Meaning that NC Client must to be update with new revision 28-12-2023 of ietf-truststore to interoperate with a NC Server running Netopeer2  version 2.2.13.

**Comment by michalvasko** [comment]
Yes, these module revisions are not compatible with each other when the draft is being updated. However, this module will most likely be final and published in an RFC so this update should be the last.

**Comment by robbynet** [comment]
Thanks for the confirmation
