### ISSUE TITLE
Getting error while doing make of "keystored "

### ISSUE THREAD

**Issue by rosy8** [CESNET/Netopeer2#153]
Hi Michal,

I took latest code from all the git-repos and trying to make the libraries..
I had also cleaned up all the old lib related to these from my box (/usr/lib64, /usr/local/lib64) etc ..
But while installing keystored I am getting the some dependency error as shown below...

-sh-4.2$ cmake -D CMAKE_BUILD_TYPE:String="Debug" ..
-- The C compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1")
CMake Warning at CMakeLists.txt:57 (message):
  keystored pkg-config file copied into a directory not searched by
  pkg-config.

CMake Warning at CMakeLists.txt:58 (message):
  For netopeer2-server configuration to work, pkg-config search path must
  include "/usr/local/lib64/pkgconfig" or keystored keys directory will have
  to be set manually to "/usr/local/etc/keystored/keys".

-- Found sysrepo: /usr/local/lib64/libsysrepo.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/haripriyap/gitcode_devel/Netopeer2/keystored/build
-sh-4.2$ make
Scanning dependencies of target keystored
[100%] Building C object CMakeFiles/keystored.dir/keystored.c.o
Linking C shared library libkeystored.so
[100%] Built target keystored
-sh-4.2$ sudo make install
[100%] Built target keystored
Install the project...
-- Install configuration: "Debug"
-- Installing: /usr/local/lib64/pkgconfig/keystored.pc
-- Installing: /usr/local/etc/keystored/keys
CMake Error at cmake_install.cmake:56 (message):
    Command sysrepoctl list failed:
    /usr/local/bin/sysrepoctl: error while loading shared libraries: libyang.so.0.12: cannot open shared object file: No such file or directory

make: *** [install] Error 1

============================
-sh-4.2$ ldd /usr/local/bin/sysrepoctl
        linux-vdso.so.1 =>  (0x00007fffc6963000)
        libsysrepo.so.0.6 => /lib64/libsysrepo.so.0.6 (0x00007fef41a51000)
        libyang.so.0.13 => /lib64/libyang.so.0.13 (0x00007fef41744000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fef4153b000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fef4131f000)
        libredblack.so.0 => /lib64/libredblack.so.0 (0x00007fef4111b000)
        libev.so.4 => /lib64/libev.so.4 (0x00007fef40f0c000)
        libprotobuf-c.so.1 => /lib64/libprotobuf-c.so.1 (0x00007fef40d03000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fef40941000)
        libyang.so.0.12 => not found                                            ==========>> ??
        libm.so.6 => /lib64/libm.so.6 (0x00007fef4063e000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fef4043a000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007fef401d8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fef41e50000)
-sh-4.2$

======================
But while installing libyang,  I got only the following .so...

Install the project...
-- Install configuration: "Debug"
-- Installing: /usr/local/lib64/libyang.so.0.13.13
-- Installing: /usr/local/lib64/libyang.so.0.13
-- Installing: /usr/local/lib64/libyang.so
-- Up-to-date: /usr/local/include/libyang/libyang.h
-- Up-to-date: /usr/local/include/libyang/tree_schema.h
-- Up-to-date: /usr/local/include/libyang/tree_data.h
-- Up-to-date: /usr/local/include/libyang/extensions.h
-- Up-to-date: /usr/local/include/libyang/xml.h
-- Up-to-date: /usr/local/include/libyang/dict.h
-- Installing: /usr/local/lib64/pkgconfig/libyang.pc
-- Installing: /usr/local/bin/yanglint
-- Removed runtime path from "/usr/local/bin/yanglint"
-- Up-to-date: /usr/local/share/man/man1/yanglint.1
-- Installing: /usr/local/lib64/libyang/nacm.so
-- Removed runtime path from "/usr/local/lib64/libyang/nacm.so"
-- Installing: /usr/local/lib64/libyang/metadata.so
-- Removed runtime path from "/usr/local/lib64/libyang/metadata.so"
-sh-4.2$

Please let me know if I am missing anything here.

Thanks in advance.
-Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
I will help you this time, but having some basic experience with developing software on Linux, you should have been able to resolve this. It is complaining, while executing `sysrepoctl`, that it cannot find `libyang.0.12` because you already have `libyang.0.13`, so what does this tell you? That your installed version of `sysrepoctl` is linking with an old version of *libyang*. So, simply recompile and install *sysrepo* and it should be fixed.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Thanks for your reply. No problem, It got resolved.
I was recompiling but somehow the old sysrepoctl  was not getting overwritten. So once I removed that manually from my box it got resolved.

Regards,
Rosy
