### ISSUE TITLE
[Query] SSH callhome max attempts status check

### ISSUE THREAD

**Issue by ankit7gup** [CESNET/netopeer2#1531]
Hi @michalvasko 

I have a query regarding the max-attempts for SSH call home. The requirement is for the application to know if the max-attempts are tried for SSH call home towards the client and server has now stopped trying to attempt any more call home requests.
Can you please help to share how this can be achieved, is there any other parameter which keeps the check for current attempt count? Or some way by which this info can be known to the application if call home requests have exhausted and still no client has accepted it yet.

Thanks for the support!

Regards,
Ankit

**Comment by michalvasko** [comment]
The `ietf-netconf-server` module does not publish this information in any way so your application is not compatible with it. Once max-attempts are reached, the next Call Home client according to the configured strategy is selected so it never "stops trying to connect to Call Home clients" unless it connects to one of its endpoints.
