### ISSUE TITLE
still server is not running

### ISSUE THREAD

**Issue by codebindeee** [CESNET/netopeer2#1535]
root@22:~# systemctl status netopeer2.service 

× netopeer2.service - server for implementing network configuration management

     Loaded: loaded (/lib/systemd/system/netopeer2.service; disabled; vendor pr>

     Active: failed (Result: exit-code) since Thu 2024-02-08 09:59:11 IST; 14mi>

   Main PID: 3643 (code=exited, status=1/FAILURE)

        CPU: 24ms

Feb 08 09:59:11 22 systemd[1]: netopeer2.service: Scheduled restart job, restar>

Feb 08 09:59:11 22 systemd[1]: Stopped server for implementing network configur>

Feb 08 09:59:11 22 systemd[1]: netopeer2.service: Start request repeated too qu>

Feb 08 09:59:11 22 systemd[1]: netopeer2.service: Failed with result 'exit-code>

Feb 08 09:59:11 22 systemd[1]: Failed to start server for implementing network >

root@22:~# netopeer2-server -v3

**Comment by michalvasko** [comment]
Please stop creating new issues.
