### ISSUE TITLE
"/notif:notification" not found error on connecting

### ISSUE THREAD

**Issue by ss8-suzushun** [CESNET/netopeer2#1536]
[version information]
netopeer2 : 2.0.77
libnetconf2 : 2.1.20
libyang : 2.46.3
sysrepo : 2.2.150

Hi,
When connect is executed, the following message is output and the connection does not succeed. 
The same thing is happening with callhome.
How do you solve this error?

・connect

```
$ netopeer2-cli
load_config: No saved configuration.
> connect --host 172.27.127.21 --login john
john@172.27.127.21 password:
　…
ly ERROR: Augment target node "/notif:notification" from module "yuma-system" was not found. (Path "/yuma-system:{augment='/notif:notification'}".)
cmd_connect: Connecting to the 172.27.127.21:830 as user "john" failed.
```

・listen
```
> listen --host 0.0.0.0 --timeout 800 --login john
Waiting 800s for an SSH Call Home connection on port 4334...
The authenticity of the host '172.27.127.21' cannot be established.
ssh-ed25519 key fingerprint is XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX.
Are you sure you want to continue connecting (yes/no)? yes
john@172.27.127.21 password:
　…
ly ERROR: Augment target node "/notif:notification" from module "yuma-system" was not found. (Path "/yuma-system:{augment='/notif:notification'}".)
cmd_listen: Receiving SSH Call Home on port 4334 as user "john" failed.
>
```

**Comment by michalvasko** [comment]
You have quite a mix of the versions, latest *libyang* and *sysrepo* and ancient *libnetconf2* and *netopeer2*, which may be a problem on its own. Can you provide `yuma-system.yang` the server is using?

**Comment by ss8-suzushun** [comment]
thank you for your response
[yuma-system.yang.txt](https://github.com/CESNET/netopeer2/files/14219779/yuma-system.yang.txt)

**Comment by michalvasko** [comment]
Okay, I have modified the module and if you install the latest *netopeer2*, you should no longer get the error.

**Comment by ss8-suzushun** [comment]
I have confirmed that the issue is resolved.
Thank you : )
