### ISSUE TITLE
Security impact of URL support for <source> and <target> parameters 

### ISSUE THREAD

**Issue by vlahan** [CESNET/Netopeer2#1537]
Currently the server comes with default enabled (ENABLE_URL=ON) support for URLs as `<source>` and `<target>` parameters in the config manipulation RPCs (https://datatracker.ietf.org/doc/html/rfc6241#section-8.8).

Unfortunately, it seems that currently there is no sanitization of the provided URLs (including the use of the "file://" protocol), nor any NACM rights mitigation. As a result, the external client can copy / overwrite, etc. files with the rights of the user under which the server is executed (which would be root on many real-world deployments).

For example, `copy-config --target url:file:///test.conf --source running` will create a copy  of the running datastore in the root of the FS. One can even copy any source file and overwrite any destination file within the rights of the user running the server.

Mitigation of the above problem might involve a combination of:

- Disabling URL support by default (ENABLE_URL=OFF)
- Disabling of the file:// protocol when initializing libcurl (https://github.com/curl/curl/blob/master/docs/CURL-DISABLE.md#curl_disable_file)
- Constraining the local folders that can be used as `<source>` or `<target>` parameters (e.g similarly to confD https://discuss.tail-f.com/t/url-capability-examples/1533)
- Making sure that libcurl is executed in the context of the current client user instead of the netopeer2-server

**Comment by michalvasko** [comment]
You are right and by default it all works as you described, every authenticated user can do this. I am not sure it is a real security problem, though, because it is up to you to configure authenticated users that you trust. If not, you can customize their access rights using NACM (you can forbid executing `copy-config`).

**Comment by jktjkt** [comment]
This sounds like a security issue because user `foo` that's connecting over NETCONF can create files in the local filesystem as `root`. That is a bug on its own, even if some custom config was needed to trigger this operation.

How is `copy-config` currently implemented? Does the user  need a special NACM rule for that RPC? Is the NACM filtering (that would limit the scope of the content of the config payload that's copied to whatever is NACM-visible to the current user) in place?

Anyway, disabling the `file:` scheme sounds like a reasonable minimum to do. In fact, I suggest limiting the URLs to `https:` (and maybe `http:` as well if you think that having a cleartext, "insecure" upload/download is worth the convenience).

**Comment by michalvasko** [comment]
> This sounds like a security issue because user foo that's connecting over NETCONF can create files in the local filesystem as root. That is a bug on its own, even if some custom config was needed to trigger this operation.

Well, like I said, the use `foo` may not even exist on the system, what should the owner then be?

> Does the user need a special NACM rule for that RPC?

No.

> Is the NACM filtering (that would limit the scope of the content of the config payload that's copied to whatever is NACM-visible to the current user) in place?

Yes.

> Anyway, disabling the file: scheme sounds like a reasonable minimum to do.

I am not sure about this, why shouldn't the users be allowed to work (backup/load) with configurations stored on the system? I think there may be a use-case for this.

**Comment by vlahan** [comment]
I still think this is a significant issue. In my view trusting an external user to run copy-config is completely different with trusting this user to do any read / write as root (owner of netopeer2-server) on the local FS (at the moment one can even use "file:///" for both source and destination in single call, so one can copy / overwrite at will).

**Comment by michalvasko** [comment]
Okay, but a reasonable solution needs to be found. So what about adding a new compile-time variable `ENABLE_URL_FILE` that will be `OFF` by default, will that make everyone happy?

**Comment by vlahan** [comment]
That sounds like a good pragmatic solution! 

Down the road, ideally some kind of file path jail system or allow/deny lists that can be controlled via NACM might enable more safe use of the file URLs.

**Comment by jktjkt** [comment]
> a new compile-time variable `ENABLE_URL_FILE` that will be `OFF` by default, will that make everyone happy?

If it has some documentation which explains that in the context of a NETCONF server, this allows all authenticated users to overwrite arbitrary files as `root`, and therefore it has vast security implications, then OK, I'll be happy :). Bonus points if Netopeer2-server checks for this at build time as well and issues a warning about a config that's insecure.

**Comment by michalvasko** [comment]
> if ENABLE_URL=ON then one can enable / disable URLs only via model features

What do you mean, some new features? There is only one feature right now, `url`.

I have pushed a change for this, was more difficult than I thought and I still need to add support for older `libcurl`...

**Comment by michalvasko** [comment]
Okay, is there any point to such a change? It was never the idea to manually change supported YANG features of `ietf-netconf` but rather let *netopeer2* set them according to its compile-time options.
