### ISSUE TITLE
Moving from Netopeer to Netopeer2

### ISSUE THREAD

**Issue by Jojosep** [CESNET/Netopeer2#154]
I have a quite complex TransAPI for my Netopeer server. It was working well until I found an issue with the server (or my code; I posted an issue on the old Netopeer project) and I realized that the average response time on the old Netopeer project is larger than my deadline because Netopeer is in abandoned (or deprecated) state and I was wondering if I could easily import my work on the new Netopeer2 - sysrepo projects.

I've been looking the docs from Netopeer2 and sysrepo projects and I did not manage to find any documentation on how to create a transAPI.

I did see that sysrepo seems to be the guy who updates the database, applies the configuration changes to the system and notifies the Netopeer2 and, if I understood things correctly, Netoeer2 is only an intermediary between the ssh connection and sysrepo. Correct me if I'm wrong please.

Is there any guide or examples on how to create (or import from Netopeer) a custom transAPI (with a custom YANG) on this new projects?

Thank you.

**Comment by jktjkt** [comment]
> I did see that sysrepo seems to be the guy who updates the 
> database, applies the configuration changes to the system and 
> notifies the Netopeer2 and, if I understood things correctly, 
> Netoeer2 is only an intermediary between the ssh connection and 
> sysrepo. Correct me if I'm wrong please.

That's correct.

> Is there any guide or examples on how to create (or import from 
> Netopeer) a custom transAPI (with a custom YANG) on this new 
> projects?

In sysrepo world, things are a bit different. In order to listen for 
changeas and have a chance to do something with them as they are about to 
be commited, you want to register an appropriate callback. Check the 
documentation at 
http://www.sysrepo.org/static/doc/html/subscribtions.html#rds_subscriptions 
.

-- 
Trojitá, a fast Qt IMAP e-mail client -- http://trojita.flaska.net/

**Comment by Jojosep** [comment]
Thanks for your quick and accurate response @jktjkt.

Then instead of manually creating the paths file and auto-generate all the callbacks i just have to register the functions on a sysrepo module and make sure that the path to the proper yang container (or variable) is correctly set in each function am I right?

Oh and one last thing; do you know any examples of a sysrepo module I can take a look at please? Even the most simple example would do the trick :)

Thanks a lot

**Comment by jktjkt** [comment]
Take a look to the examples directory in the sysrepo tree (as you noticed, Netopeer2-server is just a NETCONF frontend; you don't have to care about it at all when implementing/porting your chagnes).

- A standalone example shows [how to subscribe and process the changes](https://github.com/sysrepo/sysrepo/blob/master/examples/application_changes_example.c). It doesn't *do* anything, it just prints out the changed data IIRC.
- There's also a plugin that [provides access to hostname changes, time control and ``poweroff``/``reboot``](https://github.com/sysrepo/sysrepo-plugin-ietf-system/blob/master/system-plugin.c). Just ignore anything that is specific to the ``sysrepo-plugind`` (basically, bits with ``plugin`` in their names) and you're good to go.
- There are also other application-specific examples under the @sysrepo project on GitHub.

Also please read through the docs that I linked to -- there are very nice resources about *how* to use SR and how to do that with security in mind.

**Comment by Jojosep** [comment]
That was all I was asking for -- and even a bit more ;) -- Thank you! I'll check this out
