### ISSUE TITLE
Not able to install netopeer2: make: *** [Makefile:100: install] Error 1

### ISSUE THREAD

**Issue by rishi-diwaker1** [CESNET/netopeer2#1541]
i am getting the some error while building netopeer2
below is my terminal output
I am using Ubuntu 22.04 LTS, and i have downloaded all the prerequisites for netopeer2
Added the modules in this order libyang->libnetconf2->sysrepo->netopeer2.
Please help 

rishi@rishi:~/netopeer2/build$ sudo make install
[ 44%] Built target serverobj
[ 61%] Built target netopeer2-server
[100%] Built target netopeer2-cli
Install the project...
-- Install configuration: "Debug"
-- Up-to-date: /usr/local/share/yang/modules/netopeer2
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/[ietf-subscribed-notifications@2019-09-09.yang](mailto:ietf-subscribed-notifications@2019-09-09.yang)
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/[ietf-yang-push@2019-09-09.yang](mailto:ietf-yang-push@2019-09-09.yang)
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/[ietf-interfaces@2018-02-20.yang](mailto:ietf-interfaces@2018-02-20.yang)
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/[ietf-network-instance@2019-01-21.yang](mailto:ietf-network-instance@2019-01-21.yang)
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/[nc-notifications@2008-07-14.yang](mailto:nc-notifications@2008-07-14.yang)
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/[ietf-netconf@2013-09-29.yang](mailto:ietf-netconf@2013-09-29.yang)
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/[ietf-netconf-nmda@2019-01-07.yang](mailto:ietf-netconf-nmda@2019-01-07.yang)
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/[ietf-ip@2018-02-22.yang](mailto:ietf-ip@2018-02-22.yang)
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/[notifications@2008-07-14.yang](mailto:notifications@2008-07-14.yang)
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/[ietf-datastores@2018-02-14.yang](mailto:ietf-datastores@2018-02-14.yang)
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/[ietf-netconf-monitoring@2010-10-04.yang](mailto:ietf-netconf-monitoring@2010-10-04.yang)
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/[ietf-yang-patch@2017-02-22.yang](mailto:ietf-yang-patch@2017-02-22.yang)
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/[ietf-restconf@2017-01-26.yang](mailto:ietf-restconf@2017-01-26.yang)
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/[ietf-yang-schema-mount@2019-01-14.yang](mailto:ietf-yang-schema-mount@2019-01-14.yang)
-- Up-to-date: /usr/local/share/yang/modules/netopeer2/[ietf-netconf-acm@2018-02-14.yang](mailto:ietf-netconf-acm@2018-02-14.yang)
-- Up-to-date: /usr/local/share/netopeer2/scripts
-- Up-to-date: /usr/local/share/netopeer2/scripts/common.sh
-- Up-to-date: /usr/local/share/netopeer2/scripts/merge_config.sh
-- Up-to-date: /usr/local/share/netopeer2/scripts/remove.sh
-- Up-to-date: /usr/local/share/netopeer2/scripts/setup.sh
-- Up-to-date: /usr/local/share/netopeer2/scripts/merge_hostkey.sh
-- Up-to-date: /usr/local/sbin/netopeer2-server
-- Up-to-date: /usr/local/share/man/man8/netopeer2-server.8
-- Up-to-date: /usr/local/lib/systemd/system/netopeer2-server.service
-- Up-to-date: /etc/pam.d/netopeer2.conf
-- Installing missing sysrepo modules...
-- Generating a new RSA host key "genkey" if not already added...
CMake Error at cmake_install.cmake:141 (message):
scripts/merge_hostkey.sh failed: 1

make: *** [Makefile:100: install] Error 1

**Comment by michalvasko** [comment]
Please use the latest `devel` *netopeer2* version or at least take the last commit, some error output should now be printed.
