### ISSUE TITLE
Getting error during netopeer2 build

### ISSUE THREAD

**Issue by RSowndarya** [CESNET/netopeer2#1546]
Hi,

I am facing below error during netopeer2 build.

>[ERR] Grouping "ks:local-or-keystore-asymmetric-key-grouping" referenced by a uses statement not found. (Path "/ietf-ssh-server:{grouping='ssh-server-grouping'}/server-identity/host-key/host-key-type/public-key/public-key/{uses='ks:local-or-keystore-asymmetric-key-grouping'}".)
sysrepoctl error: Failed to update modules (libyang error)
For more details you may try to increase the verbosity up to "-v3".
CMake Error at cmake_install.cmake:117 (message):
   scripts/setup.sh failed: 1

If you could provide your comments, it would be helpful.

**Comment by michalvasko** [comment]
Seems like an incompatibility of the YANG modules, they were updated recently. A problem would be if you had a use-case for one or more of those modules in their older revision, otherwise you can just remove all the modules (`make sr_clean` in *sysrepo*) and reinstall *netopeer2*.
