### ISSUE TITLE
How to generate netconf-confirmed-commit notification

### ISSUE THREAD

**Issue by chunlovemail** [CESNET/netopeer2#1548]
sh-5.1# sysrepoctl -h
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.1.84 (SO v7.8.10)

sh-5.1# netopeer2-server -V
netopeer2-server 2.1.36

 Use netopeer2-cli to connect server and execute "subscribe" to receive notifications. I modify the candidate data and execute "commit --confirm-timeout 120". I can see the "netconf-config-change", but here is NO "netconf-confirmed-commit ",
 
 After this, I execute command "commit --confirmed-commit", there is still NO "netconf-confirmed-commit "
 
 Am my procedure WRONG? or the "netconf-confirmed-commit" notification is NOT support in the laster code?

**Comment by michalvasko** [comment]
Actually, we have completely missed this notification and it is not implemented and never sent. It is not a priority but I have noted it and we will implement it once there is some spare time, will reply here.

**Comment by chunlovemail** [comment]
Hi Michalvasko,
    Thanks for your response, I got it

**Comment by lePici** [comment]
Sending `netconf-confirmed-commit` notifications has been implemented. Please try it by updating Netopeer's `devel` branch.
