### ISSUE TITLE
Discuss about using yang metadata in netopeer2-server

### ISSUE THREAD

**Issue by fanchanghu** [CESNET/netopeer2#155]
Hi,
I have occured a problem, I want to discuss it here. 
In my project, some users just want to set the values of leaf-list to new values no matter what the old values are. But it seems NETCONF does not provide an operation to do this, so I try to define a yang metadata to add an attribute to NETCONF's message to indicate that all values of the specified leaf-list should be replaced by new values. 
This may need netopeer to support some plugin mechanisms to process user-defined yang metadata, or is there any other plans to support this?

**Comment by rkrejci** [comment]
Hi, YANG extensions mechanism is extremely generic, so it is really challenging to cover all possible use cases. We don't have any plans neither resources to support this in some short term, but I'm going to leave this issue open as possible future enhancement.

I can imagine another approach - if you have control on the client side, you can change leaf-list modification request to remove all the current leaf-list instances and then creating the new ones.

**Comment by fanchanghu** [comment]
I agree it can be controlled on the client side, but more complex and inefficient, the client need query the 
data first, then delete the old values and create the new. If this is done in a script, it will need some more complex grammars.

**Comment by rkrejci** [comment]
Definitely, but as I said, we are limited by resources. You can provide pull request or some reason to our organisation to allow us spending more time (to add another developers to work) on this.

**Comment by fanchanghu** [comment]
Hi,
I'm glad to contribute to netopeer2, but I'm not sure I can implement new features up to your standard, however, I will have a try.

Back to this issue, a feature about metadata, it is extremely generic, as you said, so I think we need provide a plugin in netopeer2 server to make users handle it themselves.

According to the RFC, metadata annotations can be used for both operation requests and responses, so I plan to provide some callbacks for `edit-config`, `copy-config`, `get` and `get-config`.

In my general plan, for `edit-config` and `copy-config`, the callbacks look like below:
```
typedef int (*np_ec_before_clb)(struct np_ec_clb_ctx *ec_ctx, struct lyd_node *config);
typedef int (*np_ec_node_clb)(struct np_ec_clb_ctx *ec_ctx, struct lyd_node *node);
typedef int (*np_ec_after_clb)(struct np_ec_clb_ctx *ec_ctx);
```
Here, `ec` means _edit-config and copy-config_,  `struct np_ec_clb_ctx` contains information that the callbacks may need, such as libnetconf session, sysrepo session, current datastore, and so on. `np_ec_before_clb` will be called before any nodes are handled, `np_ec_node_clb` will be called every times that one node is handled, `np_ec_after_clb` will be called after all nodes have been handled. Netopeer2 server will work well just like now if no such plugin is provided.

The plugin for `get` and `get-config` can also be done in the manner like above.

Do you think this plan can cover our feature, or do you have any other suggestions about this? I'm willing to work on this plan if you can agree to it.

**Comment by fanchanghu** [comment]
Hi,
I have added some base code to make it clear about how I would implement this feature, any suggestion about it? 
I will finish the rest of it (such as copy-config, tests, api description) if it could be agreed.
@rkrejci
