### ISSUE TITLE
Password Input Bug 

### ISSUE THREAD

**Issue by Omnamasivaya26** [CESNET/netopeer2#1557]
When the password is entered incorrectly, and a backspace key is used, it includes that as a character and results in the wrong password (failed authentication). I know this is a low-level priority bug, but sometimes it is annoying, especially if the password is long and the user knows only the last character is misspelled. They try to correct it using the backspace key, but it results in failed authentication. Therefore, I suggest fixing this issue in the next version.

**Comment by michalvasko** [comment]
Okay, should work now, I am actually not sure why the raw mode was used and these characters not interpreted.
