### ISSUE TITLE
Query on confirm-commit capability

### ISSUE THREAD

**Issue by MoshikaKarthesan** [CESNET/netopeer2#1559]
We have disabled confirm-commit capability but on issuing commit from netopeer2-cli we are observing the below logs
which we don't expect. Can we have a solution to this issue?
16:32:04: %NETOPEER2@12-3-SYSLOG: Not found node "confirmed" in path. (Schema location "/ietf-netconf:commit".)
16:32:04: %NETOPEER2@12-3-SYSLOG: Not found node "persist-id" in path. (Schema location "/ietf-netconf:commit".)

**Comment by michalvasko** [comment]
It should not be that difficult to find the places where the error is generated using a debugger, for example. My guess would be somewhere in the `commit` RPC processing in `netconf_confirmed_commit.c`. But you have modified the code so I am unable to help even if I wanted to.

**Comment by MoshikaKarthesan** [comment]
We have just disabled the capability "confirmed-commit"
Commented NP2_CHECK_FEATURE("confirmed-commit") only. 
We haven't made any customization in np2srv_rpc_commit_cb 
It is throwing error in the below lines in np2srv_rpc_commit_cb while finding "confirmed" and persist-id.

    /* check if confirmed-commit */
    if (!lyd_find_path(input, "confirmed", 0, NULL)) {
        rc = np2srv_confirmed_commit_cb(session, input);
        goto cleanup;
    }

    /* persist-id */
    if (!lyd_find_path(input, "persist-id", 0, &node)) {
        persist_id = lyd_get_value(node);
    }

**Comment by michalvasko** [comment]
I see, that is still not supported (as you can see). The enabled feature set cannot be changed normally.
