### ISSUE TITLE
Require about rollback data when copy-config failed

### ISSUE THREAD

**Issue by fanchanghu** [CESNET/Netopeer2#156]
Now, netopeer server just leaves the data in the session when copy-config failed, it seems that NETCONF protocol does not describe how to act in this situation, and I prefer to rollback the data rather that just left them in the session, how do think about this?

**Comment by michalvasko** [comment]
Hi,
I think it makes more sense to leave them be. That allows you to just change the faulty data and do copy-config again. Otherwise you would have to change all the other data except for the faulty part, which is likely the larger portion.

Regards,
Michal

**Comment by fanchanghu** [comment]
I don't understand why leaving data in the session will simplify next copy-config data, copy-config will always remove all old data and create the new, so the user can also just change the faulty data in the source and do copy-config again.
Another problem is that it is hard to abort the data left in the session if the users do not backup the old data, they must close the current session and open a new one. If they use netopeer2-cli, they must disconnect from the server and reconnect again.

**Comment by michalvasko** [comment]
For the former, I guess this more of a point-of-view issue, but I still think not everyone would expect the configuration to roll-back so as long as it is not mentioned in any sdandard (RFC), it will not change the way you want.

For the latter, you can always "reset" a datastore configuration to some other datastore configuration using *copy-config*, so there is no problem there.

Regards,
Michal
