### ISSUE TITLE
Does Netopeer2 support the "disable running datastore" feature?

### ISSUE THREAD

**Issue by nullromo** [CESNET/netopeer2#1563]
I updated libyang, libnetconf2, sysrepo, and netopeer2 to the latest `master`.

I tried running `make sr_clean` in sysrepo and then the netopeer2 setup script `setup.sh`. The Netopeer server runs fine with `netopeer-server -d`.

Then I tried that process again, but I modified the `setup.sh` script to include `--module-plugin "running:"` for the module install command.

```diff
- CMD_INSTALL="$CMD_INSTALL -i $1/$2 -p '$PERMS'"
+ CMD_INSTALL="$CMD_INSTALL -i $1/$2 -p '$PERMS' --module-plugin 'running:'"
```

Then when I run the Netopeer2 server, I just get an immediate segfault.

```
$ sudo netopeer2-server -d -v3
[INF]: SR: Connection 12 created.
[INF]: SR: Session 1 (user "root", CID 12) created.
Segmentation fault
```

Is Netopeer2 supposed to support disabling the running datastore?

**Comment by nullromo** [comment]
Update: I added the `-m 'running:` flag to each module individually in the `common.sh` script, and I found that the only ones that cause the segfault are:

- ietf-keystore
- ietf-truststore
- ietf-netconf-server

If any of those include the `-m 'running:'` flag, then Netopeer2 segfaults.

**Comment by michalvasko** [comment]
Please try the latest *sysrepo* `devel`, it should be fixed.

**Comment by nullromo** [comment]
It works with the current `devel` branch; thank you. However, I noticed a strange behavior.

With the running datastore disabled, `sysrepocfg -X -d running -m my-module` and `sysrepocfg -X -d startup -m my-module` produce the same results. This is what I would expect. The running datastore is disabled, so the output mirrors the startup datastore.

However, with Netopeer2, using `<source><running/></source>` in a `get-config` request will always output an empty tree if the running datastore is disabled. `<source><startup/></source>` gives me the data. Is this intended?

**Comment by michalvasko** [comment]
Right, I have not tested disabling *netopeer2* modules and as you observed, it did not work correctly. Please try it with the latest *sysrepo* `devel`, it should be fixed.

**Comment by nullromo** [comment]
Everything appears fixed on the latest `devel` for libyang, libnetconf2, sysrepo, and netopeer2. Excellent and thank you!

Would it be worth adding an option to the Netopeer `setup.sh` script for this? i.e. a variable alongside `NP2_MODULE_DIR`, `NP2_MODULE_PERMS`, and `LN2_MODULE_DIR` that causes the script to install the modules with the `-m` flag.

**Comment by michalvasko** [comment]
Okay, I have added the variable to the setup script but I would keep it "hidden" from `cmake` so if you want to use, you manually have to set the env variable.

**Comment by nullromo** [comment]
I think that's a good solution. Closing the issue.
