### ISSUE TITLE
How to enable TCP keepalive on netopeer2-server?

### ISSUE THREAD

**Issue by lqlucky** [CESNET/netopeer2#1564]
Hi michal,

After testing, I found that netopeer2-server does not actively send keepalive, but replies.
keepalives configuration as follow:
![image](https://github.com/CESNET/netopeer2/assets/14229408/91249aec-3b86-493f-aeef-18d7083c4d87)

Wireshark capture as follow, 10.8.16.124 is netopeer2-cli, 10.8.15.105 is netopeer2-server
![image](https://github.com/CESNET/netopeer2/assets/14229408/9ac84193-c6ec-4b44-9292-920bc928a8cb)

Is there any way to enable that?

version:
netopeer2-server: 2.1.71
libnetconf2: 2.1.37

**Comment by Roytak** [comment]
Hi, I tested this in current devel and it was bugged. I fixed it there, but as this is an older version I can't really help. Client side keepalives seem to always be enabled (that's the Wireshark capture), but your config looks good to me. Not sure what is wrong, but it should work in the latest devel.

**Comment by lqlucky** [comment]
I see, thanks for your reply. I will update it when you release the new version.
Could close this issue.
