### ISSUE TITLE
Netopeer2-server couldn't Bind to 830 port

### ISSUE THREAD

**Issue by biswajit84** [CESNET/netopeer2#1569]
Hi,
After installing all the dependent packages of netopeer to user defined custom directory, Netopeer2-server not able to bind port 830 as I am not starting it in root privilege. So whats the procedure to  modify the port  number.
I am using latest netopeer2-2-19 and sysrepo-2.2.170.  

My query is:
1. How to find from which path all the yang files are getting fetched and loaded . Also how to change it.

Log:
` ./netopeer2-server -d -v3 -p /home/biswajit/netopeer.pid `
` [INF]: SR: Connection 2 created.`
`[INF]: SR: Session 9 (user "biswajit", CID 2) created.`
`[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.`
`[ERR]: LN: Could not bind "0.0.0.0" port 830 (Permission denied).`
`[ERR]: LN: Configuring node "local-port" failed.`
`[ERR]: LN: Filling netconf-server failed.`
`[ERR]: NP: Configuring NETCONF server failed.`
`[INF]: SR: Triggering "ietf-keystore" "done" event on enabled data.`
`[INF]: SR: Triggering "ietf-truststore" "done" event on enabled data.`
`[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.`
`[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.`
`[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.`
`[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data. `

**netopeer2-2.2.19 Install Logs**:

-- Install configuration: "Debug"
-- Up-to-date: /home/biswajit/MPLANE/Install/share/yang/modules/netopeer2
-- Up-to-date: /home/biswajit/MPLANE/Install/share/yang/modules/netopeer2/ietf-network-instance@2019-01-21.yang
-- Up-to-date: /home/biswajit/MPLANE/Install/share/yang/modules/netopeer2/ietf-yang-schema-mount@2019-01-14.yang
-- Up-to-date: /home/biswajit/MPLANE/Install/share/yang/modules/netopeer2/ietf-subscribed-notifications@2019-09-09.yang
-- Up-to-date: /home/biswajit/MPLANE/Install/share/yang/modules/netopeer2/nc-notifications@2008-07-14.yang
-- Up-to-date: /home/biswajit/MPLANE/Install/share/yang/modules/netopeer2/ietf-interfaces@2018-02-20.yang
-- Up-to-date: /home/biswajit/MPLANE/Install/share/yang/modules/netopeer2/ietf-datastores@2018-02-14.yang
-- Up-to-date: /home/biswajit/MPLANE/Install/share/yang/modules/netopeer2/ietf-yang-patch@2017-02-22.yang
-- Up-to-date: /home/biswajit/MPLANE/Install/share/yang/modules/netopeer2/ietf-ip@2018-02-22.yang
-- Up-to-date: /home/biswajit/MPLANE/Install/share/yang/modules/netopeer2/ietf-restconf@2017-01-26.yang
-- Up-to-date: /home/biswajit/MPLANE/Install/share/yang/modules/netopeer2/ietf-netconf@2013-09-29.yang
-- Up-to-date: /home/biswajit/MPLANE/Install/share/yang/modules/netopeer2/ietf-yang-push@2019-09-09.yang
-- Up-to-date: /home/biswajit/MPLANE/Install/share/yang/modules/netopeer2/ietf-netconf-monitoring@2010-10-04.yang
-- Up-to-date: /home/biswajit/MPLANE/Install/share/yang/modules/netopeer2/ietf-netconf-nmda@2019-01-07.yang
-- Up-to-date: /home/biswajit/MPLANE/Install/share/yang/modules/netopeer2/notifications@2008-07-14.yang
-- Up-to-date: /home/biswajit/MPLANE/Install/share/yang/modules/netopeer2/ietf-netconf-acm@2018-02-14.yang
-- Up-to-date: /home/biswajit/MPLANE/Install/share/netopeer2/scripts
-- Up-to-date: /home/biswajit/MPLANE/Install/share/netopeer2/scripts/remove.sh
-- Up-to-date: /home/biswajit/MPLANE/Install/share/netopeer2/scripts/merge_hostkey.sh
-- Up-to-date: /home/biswajit/MPLANE/Install/share/netopeer2/scripts/common.sh
-- Up-to-date: /home/biswajit/MPLANE/Install/share/netopeer2/scripts/merge_config.sh
-- Up-to-date: /home/biswajit/MPLANE/Install/share/netopeer2/scripts/setup.sh
-- Up-to-date: /home/biswajit/MPLANE/Install/sbin/netopeer2-server
-- Up-to-date: /home/biswajit/MPLANE/Install/share/man/man8/netopeer2-server.8
-- Installing missing sysrepo modules (setup.sh)...
-- Generating a new RSA host key "genkey" if not already added (merge_hostkey.sh)...
-- Merging default server listen configuration if there is none (merge_config.sh)...
-- Up-to-date: /home/biswajit/MPLANE/Install/bin/netopeer2-cli
-- Up-to-date: /home/biswajit/MPLANE/Install/share/man/man1/netopeer2-cli.1

Regards
Biswajit

**Comment by michalvasko** [comment]
The default configuration is installed by the scripts, the listening endpoint by `merge_config.sh`. You can prevent the script from running as part of `make install` (by setting a cmake var) but you still need to set some configuration for the server to listen and a client to be able to connect. The configuration is stored in *sysrepo*, YANG module `ietf-netconf-server`. You can use `sysrepocfg -E vim -m ietf-netconf-server` (for example) to edit the configuration.

**Comment by biswajit84** [comment]
Hi,
Thanks alot for prompt reply. After executing " bin/sysrepocfg -E vim -m ietf-netconf-server" I have added:
`  <local-port>2830</local-port>` and now server is listening on 2830 port. But when I am trying to run netopeer2-cli and trying to connect,its failing with the error at server that:
`[INF]: LN:  Failed to retrieve the shadow entry for "biswajit".`
`[ERR]: LN: Unable to get biswajit's credentials.`
Complete log:
**Terminal 1:**
./netopeer2-server -d -v3 -p /home/biswajit/netopeer.pid
[INF]: SR: Connection 11 created.
[INF]: SR: Session 36 (user "biswajit", CID 11) created.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: LN: Listening on 0.0.0.0:2830 for SSH connections.
[INF]: SR: Triggering "ietf-keystore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-truststore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: LN: Accepted a connection on 0.0.0.0:2830 from 127.0.0.1:48840.
[INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: LN: Received an SSH message "request-auth" of subtype "none".
[INF]: LN: Received an SSH message "request-auth" of subtype "interactive".
[INF]: LN: Failed to retrieve the shadow entry for "biswajit".
[ERR]: LN: Unable to get biswajit's credentials.
[INF]: LN: Failed user "biswajit" authentication attempt (#1).
[2024/04/24 10:07:12.834611, 1] ssh_packet_disconnect_callback:  Received SSH_MSG_DISCONNECT: 11:Bye Bye
[ERR]: LN: Communication SSH socket unexpectedly closed.
^[[B^C[INF]: NP: Server terminated.

**Terminal 2:**

`./netopeer2-cli`
`load_config: No saved configuration.`
`> connect --host localhost --login biswajit --port 2830`
`The authenticity of the host 'localhost' cannot be established.`
`ssh-rsa key fingerprint is 08:f9:ba:34:fc:68:43:dd:d7:07:8e:c1:f1:02:a7:da:7d:39:55:3e.`
`Are you sure you want to continue connecting (yes/no)? yes`
`nc ERROR: Unable to authenticate to the remote server (all attempts via supported authentication methods failed).`
`cmd_connect: Connecting to the localhost:2830 as user "biswajit" failed.`

Need your help in finding the issue.

Regards,
Biswajit

**Comment by biswajit84** [comment]
Hi,
To clarify my understanding as per above statement : the `non-root` netopeer2-client can't connect to netopeer2-server started by same `non-root` user.
Then netopeer2-cli application has to be executed by root only.
Let me know whether my understanding is correct or not.
So let me know if  there is  any other solution .

Regards,
Biswajit

**Comment by michalvasko** [comment]
I suggest you also edit your authentication configuration, it is the same YANG module and so the same command, but the container `client-authentication`. There are many ways the authentication can be set up, look into `example_configuration/ssh_listen.xml` for examples. You could also read the descriptions of all the YANG nodes in their YANG modules to understand what each does.

**Comment by jktjkt** [comment]
> the `non-root` netopeer2-client can't connect to netopeer2-server started by same `non-root` user

That's incorrect.

> Then netopeer2-cli application has to be executed by root only.

That's also incorrect.

This is purely a server-side matter. First, you need root to bind to port 830; you can trivially work that around by configuring the server to listen at a port > 1024, which you did. This is a feature of the Unix permission model. Second, the server then needs root to verify the client's credentials against your system configuration -- again, that's your Unix system dictating what can be done and what cannot be done.

I have no idea what you need to achieve, but there are many workarounds -- you could run without any server-side authentication by letting the clients connect over a Unix socket, or you can set up a purely NETCONF-level authentication by not configuring the server to authenticate against the system's user accounts in the first place, but by providing a user database in the YANG data. Or you can run the server as root, and can probably run it also as an SSH subsystem with a little bit of coding. Now, what the best option is depends on your specific use case, and you have to understand your system's architecture if you want to design your system. (By deploying a NETCONF server, you effectively *are* designing your system, and one needs a certain level of Unix proficiency to do that properly. There's no way around that I'm afraid.)

**Comment by biswajit84** [comment]
Thanks alot for clarification.Your input helped a lot.

Regards,
Biswajit
