### ISSUE TITLE
Get filter data with one request

### ISSUE THREAD

**Issue by woojiq** [CESNET/netopeer2#1571]
After upgrading netconf stack:
```
libsysrepo v2.1.64 -> v2.2.33
netopeer2-server 2.1.23 -> 2.1.49
```

We notice that netopeer calls our get_oper_cb (via sysrepo) for each leaf in the filter tree (before it called only once for full tree):
```xml
<get>
  <filter type="subtree">
    <classifiers xmlns="urn:bbf:yang:bbf-qos-classifiers">
        <classifier-entry>
           <source-mac-address xmlns="urn:bbf:yang:bbf-qos-composite-filters">
              <any-multicast-mac-address/>
              <broadcast-address/>
              <cfm-multicast-address/>
           <destination-mac-address xmlns="urn:bbf:yang:bbf-qos-composite-filters">
              <any-multicast-mac-address/>
              <broadcast-address/>
              <cfm-multicast-address/>
           </destination-mac-address>
           <vlans xmlns="urn:bbf:yang:bbf-qos-composite-filters">
              <tag>
                 <index/>
              </tag>
              <untagged/>
           </vlans>
        </classifier-entry>
        <system-default-actions/>
     </classifiers>
  </filter>
  <with-defaults xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults">report-all</with-defaults>
</get>
```
I'm not 100% sure, but I think the behavior changed in the commit: https://github.com/CESNET/netopeer2/commit/a217dc201f3f2cbb87cff3d84a0daa5767de22be
Maybe relevant issue: https://github.com/sysrepo/sysrepo/issues/2805

We are currently upgrading our code base to the latest version of sysrepo/netopeer. But in the meantime can ask if there is an easy way to get the old behavior for filter-tree but stay on the latest version? Maybe there is some kind of flag when subscribing to our callbacks (I think not, because the flags are for sysrepo, not netopeer)?
To be clear:
Current behavior: for each leaf in the filter tree, netopeer makes a separate request to sysrepo.
Desired behavior: one request to sysrepo and then filtering on the netopeer side like it was almost 2 years ago :)

**Comment by michalvasko** [comment]
> We notice that netopeer calls our get_oper_cb (via sysrepo) for each leaf in the filter tree (before it called only once for full tree):

What are you subscribed to? I am not sure I understand, if you have separate subscriptions to all the leaves, all of them must be called (and should have been even before) but if you have only a single subscriptions, only that can be called. Please include more details about your subscriptions and maybe the paths they are getting, anything relevant.

**Comment by woojiq** [comment]
We subscribe for yang modules only using `sr_oper_get_subscribe`.
Before updating netopeer2 called sysrepo only once ("get" request similar to the above but bigger):
```
netopeer2: Published event "operational" "/bbf-qos-classifiers:classifiers" with ID 2.
callback: Generating state data: request_id=2, module_name="bbf-qos-classifiers", path="/bbf-qos-classifiers:classifiers", request_xpath="/bbf-qos-classifiers:*"
```
But after the update we have 10+ of these logs:
```
netopeer2: Published event "operational get" "/bbf-qos-classifiers:classifiers" with ID 232.
callback: Generating state data: request_id=232, module_name="bbf-qos-classifiers", path="/bbf-qos-classifiers:classifiers", request_xpath="/bbf-qos-classifiers:classifiers/classifier-entry/description"
...
netopeer2: Published event "operational get" "/bbf-qos-classifiers:classifiers" with ID 233.
callback: Generating state data: request_id=233, module_name="bbf-qos-classifiers", path="/bbf-qos-classifiers:classifiers", request_xpath="/bbf-qos-classifiers:classifiers/classifier-entry/match-criteria/match-all"
...
<etc>
```

**Comment by michalvasko** [comment]
So that definitely does not seem right but I am not sure it is worth trying out since even the version you are using now is more than a year old. Why have you not updated to the latest release?

**Comment by woojiq** [comment]
So I partially reverted the above commit and it works for us as expected 🙃 I'll close this issue as for now.
P.S. _upgrading is hard (but it's definitely better than reverting in long term) when everything depends on it and you have dozens of custom patches_.
