### ISSUE TITLE
Need a clarification

### ISSUE THREAD

**Issue by biswajit84** [CESNET/netopeer2#1572]
Hi,
I am trying to understand how netopeer can help me in bringing up mplane. As I am new starting with basic doubts:
Objective:
Establish TLS netconf session with client->Initiate Callhome->On callhome reply wait for request

So to achieve this, am I supposed to netconf API for TLS session and and use sysrepo api,the callback will invoke to read the config data.
OR in netopeer we have apis which can be achieved without calling sysrespo apis explicitely.

Regards,
Biswajit

**Comment by michalvasko** [comment]
*netopeer2* is just a NETCONF interface for *sysrepo*, you will not interact with it locally at all. I would suggest you start by reading about [sysrepo](https://netopeer.liberouter.org/doc/sysrepo/master/html/) to learn about its features. As for a NETCONF connection, I do not understand what you want to do. You can either connect **normally** or using **Call Home** so I am going to assume you want the latter. For that you will have to configure *netopeer2* to initiate Call Home connections, find out in [README](https://github.com/CESNET/netopeer2?tab=readme-ov-file#tls-call-home) how. You can use `sysrepocfg` to import/merge configuration files into *sysrepo*.
