### ISSUE TITLE
Not able to start netopeer2-server with TLS

### ISSUE THREAD

**Issue by biswajit84** [CESNET/netopeer2#1574]
Hi ,
I have followed the bellow steps to start netopeer2-server as TLS
1.Merge the tls_keystore.xml,tls_truststore.xml,tls_listen.xml  present in example_configuration directory as below:
```
sysrepocfg -E /home/biswajit/netopeer2-evaluation/extract/netopeer2-2.2.19/example_configuration/tls_keystore.xml -d running -m ietf-keystore
sysrepocfg -E /home/biswajit/netopeer2-evaluation/extract/netopeer2-2.2.19/example_configuration/tls_truststore.xml -d running -m ietf-truestore
sysrepocfg -E /home/biswajit/netopeer2-evaluation/extract/netopeer2-2.2.19/example_configuration/tls_listen.xml -d running -m ietf-netconf-server
```
2. Execute ./netopeer2-server -d -v3 -p try.pid
```
[INF]: SR: Connection 35 created.
[INF]: SR: Session 62 (user "biswajit", CID 35) created.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[ERR]: LN: Could not bind "0.0.0.0" port 830 (Permission denied).
[ERR]: LN: Configuring node "local-port" failed.
[ERR]: LN: Filling netconf-server failed.
[ERR]: NP: Configuring NETCONF server failed.
[INF]: SR: Triggering "ietf-keystore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-truststore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
```
Ideally It should print like:Listening on 0.0.0.0:6513 for TLS connections. 
Let me know if I am missing any steps..

Regards,
Biswajit

**Comment by biswajit84** [comment]
Hi ,
I tried below commands as well :
sysrepocfg --edit=tls_keystore.xml -m ietf-keystore -d startup -v3
sysrepocfg --edit=tls_truststore.xml -m ietf-truststore -d startup -v3
sysrepocfg --edit=tls_listen.xml -m ietf-netconf-server -d startup -v3
Then when Execute netopeer2-server not sure still its not listening of 6513 tls port.

`$./netopeer2-server -d -v3 -p /home/biswajit/try.pid   `                                                                   
 `[INF]: SR: Session 51 (user "biswajit", CID 28) created.`
`[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.`
`[INF]: SR: Triggering "ietf-keystore" "done" event on enabled data.`
`[INF]: SR: Triggering "ietf-truststore" "done" event on enabled data.`
`[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.`
`[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.`
`[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.`
`[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data. `

Regards,
Biswajit

**Comment by michalvasko** [comment]
Not sure about the second case, you seem to have removed all `listen` configuration, but in the first case the error is obvious and I do not understand why you were not able to fix it. Please, try to understand what you are doing with the executed commands, you are **merging** additional configuration into *sysrepo*. But the original SSH listening port 830 remains there, which requires `root` privileges to bind to. You can use `sysrepocfg -E vim -m ietf-netconf-server` to check the current configuration of the server and delete the SSH listening config, for example.

**Comment by biswajit84** [comment]
Thanks alot valuable input. When I executed the  `sysrepocfg -E vim -m ietf-netconf-server ` I didnt find any configuration so after I merge all the three xmls, its working as expected .
