### ISSUE TITLE
netopeer2 segfault

### ISSUE THREAD

**Issue by joanlandry** [CESNET/Netopeer2#158]
We are seeing a netopeer2 segfault - at ths point in time we do not know how to recreate so we do not have much info - the debuglog is also not very detailed as to what caused the fault. Any info on where this is in the libraries would be helpful.

Jul 10 11:40:59 CA17 netopeer2-server[9773]: Resolving unresolved data nodes and their constraints...
Jul 10 11:40:59 CA17 netopeer2-server[9773]: All data nodes and constraints resolved.
Jul 10 11:40:59 CA17 sysrepod[9763]: [INF] Refresh session request running datastore
Jul 10 11:40:59 CA17 sysrepod[9763]: [INF] No operation has been performed on this session so far
Jul 10 11:40:59 CA17 netopeer2-server[9773]: Resolving unresolved data nodes and their constraints...
Jul 10 11:40:59 CA17 netopeer2-server[9773]: All data nodes and constraints resolved.
Jul 10 11:40:59 CA17 netopeer2-server[9773]: Session 2: thread 4 event new RPC.

Jul 10 11:40:59 CA17 kernel: : [156675.148598] netopeer2-serve[9871]: segfault at 31 ip 00007ffff7067208 sp 00007ffff0efcb20 error 4 in libc-2.17.so[7ffff6f87000+1b7000]
Jul 10 11:40:59 CA17 sysrepod[9763]: [INF] Closing the connection 0x69f790.
Jul 10 11:40:59 CA17 sysrepod[9763]: [INF] Closing the connection 0x699010.
Jul 10 11:40:59 CA17 sysrepod[9763]: [INF] Closing the connection 0x6985f0.

**Comment by michalvasko** [comment]
Hi,
from this output I cannot help you in any way, you would have to provide more output.

Regards,
Michal

**Comment by joanlandry** [comment]
ok - currently not easy to replicate an do not have any output from netopeer2 so closing this issue

**Comment by joanlandry** [comment]
I have the level at 2 which is the max - can you provide info on how to get more output from netopeer2

**Comment by rkrejci** [comment]
read about the `-c` option, debug messages are provided in categories to avoid printing all kinds of debug messages.

**Comment by joanlandry** [comment]
I get an error when I use -c - can you provide an example?
[root@MaestrOS ~]# netopeer2-server -d -v 2 -c EDIT_CONFIG
netopeer2-server: invalid option -- 'c'
Usage: netopeer2-server [-dhV] [-v level]
 -d                  debug mode (do not daemonize and print
                     verbose messages to stderr instead of syslog)
 -h                  display help
 -V                  show program version
 -v level            verbose output level:
                         0 - errors
                         1 - errors and warnings
                         2 - errors, warnings and verbose messages

**Comment by michalvasko** [comment]
Hi,
you have an old version of *netopeer2-server*, please update it and it will work. By the way, if you trying to debug a crash or provide some information about it for us, it is enough to use `-v2` and rather execute the server with `valgrind`.

Regards,
Michal
