### ISSUE TITLE
Trying callhome feature test in netopeer2

### ISSUE THREAD

**Issue by biswajit84** [CESNET/netopeer2#1580]
Hi,
I am trying to test the callhome feature .
Both server & client are able to connected over TLS.
Then I have loaded the tls_callhome.xml as below:
 ./sysrepocfg -E tls_callhome.xml -d running -m ietf-netconf-server.

How to configure client so that it will listen on callhome port i.e. 4335 and able to connect.
Server side log:
./netopeer2-server  -v 3 -p try.pid
[INF]: Listening on 0.0.0.0:6513 for TLS connections.
[INF]: Call Home client "default-client" endpoint "default-tls" connecting...
[INF]: Trying to connect via IPv4 to 127.0.0.1:4335.
[INF]: Call Home client "default-client" timeout of 5 seconds expired, reconnecting.
[INF]: Trying to connect via IPv4 to 127.0.0.1:4335.
[INF]: getsockopt() error (Connection refused).
[INF]: Call Home client "default-client" timeout of 5 seconds expired, reconnecting.
[INF]: Trying to connect via IPv4 to 127.0.0.1:4335.
[INF]: getsockopt() error (Connection refused).
[INF]: Call Home client "default-client" timeout of 5 seconds expired, reconnecting.
[INF]: Call Home client "default-client" endpoint "default-tls" failed connection attempt limit 3 reached.
[INF]: Call Home client "default-client" endpoint "default-tls" connecting...
[INF]: Trying to connect via IPv4 to 127.0.0.1:4335.
[INF]: getsockopt() error (Connection refused).
[INF]: Call Home client "default-client" timeout of 5 seconds expired, reconnecting.
[INF]: Trying to connect via IPv4 to 127.0.0.1:4335.
[INF]: getsockopt() error (Connection refused).
[INF]: Call Home client "default-client" timeout of 5 seconds expired, reconnecting.
[INF]: Trying to connect via IPv4 to 127.0.0.1:4335.

./netopeer2-cli
load_config: No saved configuration.
> connect --tls --host localhost  --port 4335 --cert client.crt --key client.key --trusted ca.pem
nc ERROR: Unable to connect to localhost:4335 (Connection refused).

Regards,
Biswajit

**Comment by michalvasko** [comment]
The CLI has all the command documented, just use `listen -h` and you will see all the supported options.

**Comment by michalvasko** [comment]
Obviously, fix the error it printed.
```
nc ERROR: Failed to convert IPv4 address "localhost".
```
I have never seen this and your system does not seem to be configured well but you should just be able to use `127.0.0.1` instead.
