### ISSUE TITLE
Does Netopeer support time capability: https://datatracker.ietf.org/doc/rfc7758/

### ISSUE THREAD

**Issue by chiragjain1293** [CESNET/netopeer2#1583]
Does Netopeer support time capability: https://datatracker.ietf.org/doc/rfc7758/.  i.e scheduling a netconf command

**Comment by michalvasko** [comment]
No, this capability is not supported. Seems it is just an experimental feature and hearing about it first time now (when it was published in 2016), I would say it was not adopted.

**Comment by chiragjain1293** [comment]
Thanks @michalvasko for confirmation
