### ISSUE TITLE
Detection of callhome start/Stop from external application 

### ISSUE THREAD

**Issue by biswajit84** [CESNET/netopeer2#1584]
Hi,
As I dont want to change anything in netopeer, Is it possible to get callback of external application can be invoked  during start/stop of callhome session.

Regards,
Biswajit

**Comment by michalvasko** [comment]
You can subscribe to `netconf-session-start/stop` notifications. However, it is not really possible to detect whether a Call Home or a standard NETCONF session was established. No other way to detect a new session.

**Comment by biswajit84** [comment]
As per my understanding there is a nc_session_is_callhome in libnetconf which can detect whether the session is callhome session or not .. 
Is it possible to call nc_session_is_callhome from netopeer2 so that we can get the notification in our external application .
If yes please share how can we achieve it ..

**Comment by michalvasko** [comment]
Well, yes, you can call that in *neotpeer2* and then put this information into the notification (after you update its YANG definition). But that requires changing *netopeer2* code, which you said you do not want to do.

**Comment by biswajit84** [comment]
The reason which I dont want to change is:whenever we will upgrade the netopeer version should be smooth one.
As there is no other way of getting the callhome start session,then we have to modify the netopeer.
"update its YANG definition "  you mean to say I am supposed to modify the netconf-session-start/stop  yang file.
Whether I am supposed to invoke  nc_session_is_callhome in np2srv_new_session_cb function.
Let me know whether my understanding is correct or not..

**Comment by michalvasko** [comment]
When you are modifying *netopeer2* code, I think you can simply "call" your callback meaning execute the code you want when a Call Home session is created. It will be simpler than modifying the notification.

**Comment by michalvasko** [comment]
It is an augment, so you must use
```
event_data[3].xpath = "/ietf-netconf-notifications:netconf-session-start/notif-augment:callhome-session";
```

I have answered you now because the issue was trivial but you are asking me to help you debug your own code, that is really not the kind of support we provide.
