### ISSUE TITLE
Can netopeer2-server be used against a custom datastore implementation?

### ISSUE THREAD

**Issue by bala1796** [CESNET/netopeer2#1585]
I had a look through the documentation and it looks like netopeer2 uses sysrepo as the datastore. Is it possible to use our own datastore and still use netopeer2-server? My research led me to sysrepo's datastore plugin APIs - can they be used to achieve what we want? We do not want to use sysrepo to manage the data but rather want netopeer2-server to interact with our application directly. What is the best way to achieve this? 

Thanks.

**Comment by michalvasko** [comment]
> Is it possible to use our own datastore and still use netopeer2-server?

Yes.

> What is the best way to achieve this?

Definitely using a custom DS plugin. Just note that is not trivial to write it correctly but if you do, it is the best and most efficient.

**Comment by bala1796** [comment]
Thanks for the confirmation.

Is there any way to completely get around using sysrepo and connect netopeer2-server to our application? (I'm guessing no?)

I apologize if this question sounds trivial, but if we choose to implement this custom DS plugin, we would not want to maintain a "copy" of the database in a sysrepo context. Does this custom DS plugin enable sysrepo to directly map to the configuration database held in our application's memory? 

Also, if sysrepo directly has access to the app configuration, does sysrepo handle RPCs (such as edit-config, get-config etc.) and modify the configuration itself or is it possible to delegate the work to our application for every RPC?

**Comment by michalvasko** [comment]
> Is there any way to completely get around using sysrepo and connect netopeer2-server to our application?

*netopeer2* needs a datastore and a middle layer between NETCONF and actual configuration data so no, this is not possible even in theory.

> Does this custom DS plugin enable sysrepo to directly map to the configuration database held in our application's memory?

That is precisely what it enables, if you choose to write your plugin that way. The plugin are just callbacks that are mainly supposed to store and load the data. Where the store/load them from is totally up to you.

> is it possible to delegate the work to our application for every RPC?

No, why would you want to do this? Your application (using the plugin API) will only get the processed and broken down changes of an `edit-config` and similarly processed all the other RPCs.

**Comment by bala1796** [comment]
Hi Michal,

So I'm working on implementing the DS plugin for an app and I have a few questions. 

I have an application which runs as a daemon -- let's call it "DaemonApp". The daemon maintains the datastore and is responsible for providing/modifying the data it holds in its internal data structures (not sysrepo) . To achieve this, I'm thinking of implementing an IPC mechanism within the load_cb/store_cb in the DS plugin with which I can contact DaemonApp to retrieve/supply information. I believe that would cover configuration data. But what about other operations such as custom RPC/Actions, providing status data? 

In the sysrepo docs, I see that there is a way to subscribe to providing status data and a separate subscription to receive RPC/Actions. In my case, what would be the efficient way to implement this? 

![image](https://github.com/user-attachments/assets/62473eb3-6c8a-4a8d-9881-09ab88c2d419)
Would it look like this?

**Comment by jktjkt** [comment]
Just my two cents here -- in my opinion, adding a small glue layer which listens for sysrepo events and updates the app's configuration on the fly (and which listens for app-specific events and pushes data back to sysrepo) is not a huge amount of work. You get many benefits that way, including out-of-box support for NETCONF-level push notifications, much better test coverage, the option of using standard YANG models and the possibility of splitting the data among multiple such model (or rather YANG top-level elements from multiple models), and the community experience that might help you in debugging some intricate issues. The cost of that is "just a bunch of JSON files in a memory-mapped SHM filesystem", which doesn't look like a terrible overhead to me.

So I'm wondering -- how much data are we talking about? What is that app doing? Is it *really* worth the effort of doing a fully custom DS implementation? Have you *tried* to use the usual module change callbacks, and have you found a real performance bottleneck somewhere? I know that "on paper", it looks awesome to have an API which "avoids data duplication", but sometimes it's just easier and less error-prone to implement an API that's already provided -- even if we have that whooping 5MB of data in RAM *twice* :).

**Comment by bala1796** [comment]
@jktjkt We are trying to integrate netopeer as a netconf server into an existing system which holds the configuration data. This app also receives configuration updates through non-netconf sources and we don't want the overhead of updating sysrepo every time (we might evaluate the overhead at a later point). This is the reason we are looking into the custom DS plugin.

My question was about how we can handle custom RPCs/Action/operational data requests if we use the custom DS plugin. Would the custom DS plugin only be used for loading/storing configuration data? Should the app subscribe to provide operational data and RPC/Actions?

**Comment by michalvasko** [comment]
> Would the custom DS plugin only be used for loading/storing configuration data?

Yes.

> Should the app subscribe to provide operational data and RPC/Actions?

It may. It is completely independent of the custom DS plugin.

**Comment by jktjkt** [comment]
> we don't want the overhead of updating sysrepo every time

One of the problems with the architecture that you're pursuing is that you will get inconsistent results over standard protocols. Netopeer2 supports [RFC 8639](https://datatracker.ietf.org/doc/html/rfc8639), and your implementation with a custom DS won't tell sysrepo (and therefore Netopeer2) about config changes from these "other" systems. As a result, standard-compliant clients will get a different idea of how the "current configuration" looks like. This won't be fun to debug.
