### ISSUE TITLE
Not been able to establish ssh-connection with netopeer2-server

### ISSUE THREAD

**Issue by VishalGujela** [CESNET/netopeer2#1586]
Hi,
**Mentioning the logs of server that im getting while establishing connection:**
[INF]: SR: Connection 6 created.
[INF]: SR: Session 73 (user "root", CID 6) created.
[WRN]: SR: Connection with CID 5 is dead.
[WRN]: SR: Recovering RPC/action "/ietf-netconf:get-config" subscription of CID 5.
[WRN]: SR: Recovering RPC/action "/ietf-netconf:edit-config" subscription of CID 5.
[WRN]: SR: Recovering RPC/action "/ietf-netconf:copy-config" subscription of CID 5.
[WRN]: SR: Recovering RPC/action "/ietf-netconf:delete-config" subscription of CID 5.
[WRN]: SR: Recovering RPC/action "/ietf-netconf:lock" subscription of CID 5.
[WRN]: SR: Recovering RPC/action "/ietf-netconf:unlock" subscription of CID 5.
[WRN]: SR: Recovering RPC/action "/ietf-netconf:get" subscription of CID 5.
[WRN]: SR: Recovering RPC/action "/ietf-netconf:kill-session" subscription of CID 5.
[WRN]: SR: Recovering RPC/action "/ietf-netconf:commit" subscription of CID 5.
[WRN]: SR: Recovering RPC/action "/ietf-netconf:cancel-commit" subscription of CID 5.
[WRN]: SR: Recovering RPC/action "/ietf-netconf:discard-changes" subscription of CID 5.
[WRN]: SR: Recovering RPC/action "/ietf-netconf:validate" subscription of CID 5.
[WRN]: SR: Recovering RPC/action "/ietf-netconf-monitoring:get-schema" subscription of CID 5.
[WRN]: SR: Recovering RPC/action "/notifications:create-subscription" subscription of CID 5.
[WRN]: SR: Recovering RPC/action "/ietf-netconf-nmda:get-data" subscription of CID 5.
[WRN]: SR: Recovering RPC/action "/ietf-netconf-nmda:edit-data" subscription of CID 5.
[WRN]: SR: Recovering RPC/action "/ietf-subscribed-notifications:establish-subscription" subscription of CID 5.
[WRN]: SR: Recovering RPC/action "/ietf-subscribed-notifications:modify-subscription" subscription of CID 5.
[WRN]: SR: Recovering RPC/action "/ietf-subscribed-notifications:delete-subscription" subscription of CID 5.
[WRN]: SR: Recovering RPC/action "/ietf-subscribed-notifications:kill-subscription" subscription of CID 5.
[WRN]: SR: Recovering RPC/action "/ietf-yang-push:resync-subscription" subscription of CID 5.
[WRN]: SR: Recovering module "ietf-netconf-monitoring" operational get subscription of CID 5.
[WRN]: SR: Recovering module "nc-notifications" operational get subscription of CID 5.
[INF]: SR: Triggering "ietf-subscribed-notifications" "done" event on enabled data.
[WRN]: SR: Recovering module "ietf-subscribed-notifications" operational get subscription of CID 5.
[WRN]: SR: Recovering module "ietf-subscribed-notifications" operational get subscription of CID 5.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: LN: Listening on 0.0.0.0:830 for SSH connections.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[WRN]: SR: Recovering module "ietf-netconf-server" operational get subscription of CID 5.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-keystore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-truststore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[WRN]: SR: Recovering module "sysrepo-monitoring" operational get subscription of CID 5.
[INF]: LN: Accepted a connection on 0.0.0.0:830 from 127.0.0.1:35632.
[INF]: SR: Session 104 (user "root", CID 6) created.

**And these are the logs im getting on netopeer2-cli**

connect --ssh localhost --login amantya
nc ERROR: Remote host key changed, the connection will be terminated!
nc ERROR: Checking the host key failed.
cmd_connect: Connecting to the localhost:830 as user "amantya" failed.

Please let me know if there's anything that i need to do while setting up environment or if there's something im missing.
Thanks
Vishal

**Comment by michalvasko** [comment]
Please try to solve the problem on your own before asking for support. This is a common SSH issue that you can easily understand. Once you do, you can use the `knownhosts` CLI command, with `--del` parameter.

**Comment by VishalGujela** [comment]
Sorry for this inconvenience.
And Thanks for the support
