### ISSUE TITLE
Callback event "rpc" with ID 1 processing timed out.

### ISSUE THREAD

**Issue by falilou076** [CESNET/netopeer2#1588]
Hi michalvasko:

i use the docker image sysrepo/sysrepo-netopeer2:latest
netopeer2-server: 2.1.49
sysrepo: v2.2.36

I try to do an edit-config on cli (edit-config --target=candidate --config=/opt/dev/global.xml) but i have this error:
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Callback event "rpc" with ID 1 processing timed out.

        type:     application
        tag:      operation-failed
        severity: error
        message:  User callback failed.
        
I also change the timeout on server with "netopeer2-server -t 30" and add '--rpc-timeout 30' to my edit-config command  but i always have  the same error. 
Thanks for any help you can give

**Comment by michalvasko** [comment]
I can only suggest you do not use a Docker image (or create your own with the actual latest versions) because it is not maintained by us and not up-to-date.

**Comment by falilou076** [comment]
Ah ok I understood  thank you for your answer
