### ISSUE TITLE
subscription of "ietf-netconf-notifications" failed

### ISSUE THREAD

**Issue by biswajit84** [CESNET/netopeer2#1589]
Hi,
While running netopeeer2-server , I got below on netopeer2-server.So after doing make sr_clean and reinstall of netopeer ,it worked.
Since I was testing on x86 machine where the complete source code was also present, so I was able to clean the sysrepo and got rid off the issue.
My doubt is how to catch such  errors on real time while running on target where there will be no source code and how to clean the sysrepo.

`[ERR]: SR: Waiting for subscription of "ietf-netconf-notifications" failed, previous event "notif" ID 1 was not processed.
[WRN]: NP: Failed to send a notification (Timeout expired).`

Regards
Biswajit

**Comment by michalvasko** [comment]
What *netopeer2* version are you using?

**Comment by biswajit84** [comment]
I am using 2.2.19
$ Install/sbin/netopeer2-server -V
netopeer2-server 2.2.19

**Comment by michalvasko** [comment]
I see, ideally, these kinds of errors should not occur in the latest version. Without reproducing it, I will not be able to fix this. But I am working on improving and refactoring notification subscriptions currently, so it is possible it will still be fixed in the next release.

**Comment by biswajit84** [comment]
Hi,
Let me know if you need any other logs so that I can share next time whenever I will see the same issue.

Regards,
Biswajit

**Comment by michalvasko** [comment]
The only logs that could perhaps help are the full *netopeer2-server* logs (or not full but with logs in reasonable past before the error) with INF log level (`-v2`).

**Comment by biswajit84** [comment]
Hi,
Please find the forground logs collected during the execution of netopeer2-server below.

 # ./netopeer2-server -d -v3 -p ~/temp.pid
[INF]: SR: Connection 40 created.
[INF]: SR: Session 125 (user "biswajit", CID 40) created.
[WRN]: SR: Connection with CID 27 is dead.
[WRN]: SR: Recovering RPC/action "/ietf-netconf:get-config" subscription of CID 27.
[WRN]: SR: Recovering RPC/action "/ietf-netconf:edit-config" subscription of CID 27.
[WRN]: SR: Recovering RPC/action "/ietf-netconf:copy-config" subscription of CID 27.
[WRN]: SR: Recovering RPC/action "/ietf-netconf:delete-config" subscription of CID 27.
[WRN]: SR: Recovering RPC/action "/ietf-netconf:lock" subscription of CID 27.
[WRN]: SR: Recovering RPC/action "/ietf-netconf:unlock" subscription of CID 27.
[WRN]: SR: Recovering RPC/action "/ietf-netconf:get" subscription of CID 27.
[WRN]: SR: Recovering RPC/action "/ietf-netconf:kill-session" subscription of CID 27.
[WRN]: SR: Recovering RPC/action "/ietf-netconf:commit" subscription of CID 27.
[WRN]: SR: Recovering RPC/action "/ietf-netconf:cancel-commit" subscription of CID 27.
[WRN]: SR: Recovering RPC/action "/ietf-netconf:discard-changes" subscription of CID 27.
[WRN]: SR: Recovering RPC/action "/ietf-netconf:validate" subscription of CID 27.
[WRN]: SR: Recovering RPC/action "/ietf-netconf-monitoring:get-schema" subscription of CID 27.
[WRN]: SR: Recovering RPC/action "/notifications:create-subscription" subscription of CID 27.
[WRN]: SR: Recovering RPC/action "/ietf-netconf-nmda:get-data" subscription of CID 27.
[WRN]: SR: Recovering RPC/action "/ietf-netconf-nmda:edit-data" subscription of CID 27.
[WRN]: SR: Recovering RPC/action "/ietf-subscribed-notifications:establish-subscription" subscription of CID 27.
[WRN]: SR: Recovering RPC/action "/ietf-subscribed-notifications:modify-subscription" subscription of CID 27.
[WRN]: SR: Recovering RPC/action "/ietf-subscribed-notifications:delete-subscription" subscription of CID 27.
[WRN]: SR: Recovering RPC/action "/ietf-subscribed-notifications:kill-subscription" subscription of CID 27.
[WRN]: SR: Recovering RPC/action "/ietf-yang-push:resync-subscription" subscription of CID 27.
[WRN]: SR: Recovering module "ietf-netconf-monitoring" operational get subscription of CID 27.
[WRN]: SR: Recovering module "nc-notifications" operational get subscription of CID 27.
[WRN]: SR: Recovering module "iana-ssh-public-key-algs" operational get subscription of CID 27.
[WRN]: SR: Recovering module "iana-ssh-key-exchange-algs" operational get subscription of CID 27.
[WRN]: SR: Recovering module "iana-ssh-encryption-algs" operational get subscription of CID 27.
[WRN]: SR: Recovering module "iana-ssh-mac-algs" operational get subscription of CID 27.
[WRN]: SR: Recovering module "ietf-subscribed-notifications" operational get subscription of CID 27.
[WRN]: SR: Recovering module "ietf-subscribed-notifications" operational get subscription of CID 27.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: LN: Call Home client "default-client" endpoint "default-tls" connecting...
[INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4335.
[INF]: LN: getsockopt() error (Connection refused).
[INF]: SR: Triggering "ietf-keystore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-truststore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[WRN]: SR: Recovering module "sysrepo-monitoring" operational get subscription of CID 27.
[INF]: LN: Call Home client "default-client" timeout of 5 seconds expired, reconnecting.
[INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4335.
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Call Home client "default-client" timeout of 5 seconds expired, reconnecting.
[INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4335.
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Call Home client "default-client" timeout of 5 seconds expired, reconnecting.
[INF]: LN: Call Home client "default-client" endpoint "default-tls" failed connection attempt limit 3 reached.
[INF]: LN: Call Home client "default-client" endpoint "default-tls" connecting...
[INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4335.
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Call Home client "default-client" timeout of 5 seconds expired, reconnecting.
[INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4335.
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Call Home client "default-client" timeout of 5 seconds expired, reconnecting.
[INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4335.
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Call Home client "default-client" timeout of 5 seconds expired, reconnecting.
[INF]: LN: Call Home client "default-client" endpoint "default-tls" failed connection attempt limit 3 reached.
[INF]: LN: Call Home client "default-client" endpoint "default-tls" connecting...
[INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4335.
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Call Home client "default-client" timeout of 5 seconds expired, reconnecting.
[INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4335.
[INF]: LN: getsockopt() error (Connection refused).
[INF]: LN: Call Home client "default-client" timeout of 5 seconds expired, reconnecting.
[INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4335.
[INF]: LN: Successfully connected to localhost:4335 over IPv4.
[INF]: LN: Cert verify: depth 1.
[INF]: LN: Cert verify: subject: /C=CZ/ST=South Moravia/L=Brno/O=CESNET z.s.p.o./OU=TMC/CN=example CA/emailAddress=ca@example.org.
[INF]: LN: Cert verify: issuer:  /C=CZ/ST=South Moravia/L=Brno/O=CESNET z.s.p.o./OU=TMC/CN=example CA/emailAddress=ca@example.org.
[INF]: LN: Cert verify CTN: entry with a matching fingerprint found.
[INF]: LN: Cert verify CTN: new client username recognized as "tls-test".
[INF]: LN: Cert verify: depth 0.
[INF]: LN: Cert verify: subject: /C=CZ/ST=South Moravia/L=Brno/O=CESNET z.s.p.o./OU=TMC/CN=client/emailAddress=client@example.org.
[INF]: LN: Cert verify: issuer:  /C=CZ/ST=South Moravia/L=Brno/O=CESNET z.s.p.o./OU=TMC/CN=example CA/emailAddress=ca@example.org.
[INF]: LN: Client certificate verified.
[INF]: LN: Session 1: Call Home client "default-client" session 1 established.
[INF]: SR: Session 135 (user "biswajit", CID 40) created.
[INF]: NP: Callhome data:1
[WRN]: SR: Connection with CID 38 is dead.
[WRN]: SR: Recovering module "ietf-netconf-notifications" notification subscription of CID 38.
[WRN]: SR: Recovering module "ietf-netconf-notifications" notification subscription of CID 38.
[WRN]: SR: Recovering module "ietf-netconf-notifications" notification subscription of CID 38.
[INF]: SR: EV ORIGIN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 1 priority 0 for 1 subscribers published.
[INF]: SR: EV LISTEN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 1 priority 0 processing (remaining 1 subscribers).
[INF]: NP: Module "ietf-datastores@<any>" was requested.
[INF]: SR: EV LISTEN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 1 priority 0 success (remaining 0 subscribers).
[INF]: SR: EV ORIGIN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 1 priority 0 succeeded.
[INF]: NP: Session 1: thread 2 event new RPC.
[INF]: SR: EV ORIGIN: "/ietf-netconf:get" "rpc" ID 1 priority 0 for 1 subscribers published.
[INF]: SR: EV LISTEN: "/ietf-netconf:get" "rpc" ID 1 priority 0 processing (remaining 1 subscribers).
[INF]: SR: EV LISTEN: "/ietf-netconf:get" "rpc" ID 1 priority 0 success (remaining 0 subscribers).
[INF]: SR: EV ORIGIN: "/ietf-netconf:get" "rpc" ID 1 priority 0 succeeded.
[INF]: NP: Session 1: thread 0 event new RPC.
[INF]: SR: EV ORIGIN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 2 priority 0 for 1 subscribers published.
[INF]: SR: EV LISTEN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 2 priority 0 processing (remaining 1 subscribers).
[INF]: NP: Module "o-ran-wg4-features@2023-12-11" was requested.
[INF]: SR: EV LISTEN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 2 priority 0 success (remaining 0 subscribers).
[INF]: SR: EV ORIGIN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 2 priority 0 succeeded.
[INF]: NP: Session 1: thread 1 event new RPC.
[INF]: SR: EV ORIGIN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 3 priority 0 for 1 subscribers published.
[INF]: SR: EV LISTEN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 3 priority 0 processing (remaining 1 subscribers).
[INF]: NP: Module "o-ran-usermgmt@2023-12-11" was requested.
[INF]: SR: EV LISTEN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 3 priority 0 success (remaining 0 subscribers).
[INF]: SR: EV ORIGIN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 3 priority 0 succeeded.
[INF]: NP: Session 1: thread 1 event new RPC.
[INF]: SR: EV ORIGIN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 4 priority 0 for 1 subscribers published.
[INF]: SR: EV LISTEN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 4 priority 0 processing (remaining 1 subscribers).
[INF]: NP: Module "o-ran-supervision@2022-12-05" was requested.
[INF]: SR: EV LISTEN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 4 priority 0 success (remaining 0 subscribers).
[INF]: SR: EV ORIGIN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 4 priority 0 succeeded.
[INF]: NP: Session 1: thread 2 event new RPC.
[INF]: SR: EV ORIGIN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 5 priority 0 for 1 subscribers published.
[INF]: SR: EV LISTEN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 5 priority 0 processing (remaining 1 subscribers).
[INF]: NP: Module "notif-augment@<any>" was requested.
[INF]: SR: EV LISTEN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 5 priority 0 success (remaining 0 subscribers).
[INF]: SR: EV ORIGIN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 5 priority 0 succeeded.
[INF]: NP: Session 1: thread 1 event new RPC.
[INF]: SR: EV ORIGIN: "/ietf-netconf:get" "rpc" ID 2 priority 0 for 1 subscribers published.
[INF]: SR: EV LISTEN: "/ietf-netconf:get" "rpc" ID 2 priority 0 processing (remaining 1 subscribers).
[INF]: SR: EV LISTEN: "/ietf-netconf:get" "rpc" ID 2 priority 0 success (remaining 0 subscribers).
[INF]: SR: EV ORIGIN: "/ietf-netconf:get" "rpc" ID 2 priority 0 succeeded.
[INF]: NP: Session 1: thread 1 event new RPC.
[ERR]: SR: Waiting for subscription of "ietf-netconf-notifications" failed, previous event "notif" ID 4 was not processed.
[WRN]: NP: Failed to send a notification (Timeout expired).
 `

**Comment by michalvasko** [comment]
Please use the latest releases and try again, the changes I have mentioned before have been finished.
