### ISSUE TITLE
level 4 debuglog is not displaying much info

### ISSUE THREAD

**Issue by joanlandry** [CESNET/Netopeer2#159]
There was a time when the logs from level 4 from netopeer2 where very elaborate and helpful. Now I see more or less nothing in the log. I recall a time when we use to see the rpc text followed by the msgs sent to sysrepo, followed by the rpc resp etc - now all I see is the the rpc is received.

How do we get back the ability to get more debug info from netopeer2 - as we are seeing a segfault but have no way to know what is going on.

**Comment by michalvasko** [comment]
Hi,
it was changed a bit, try `netopeer2-server -h`.

Regards,
Michal

**Comment by joanlandry** [comment]
level 2 gives no log detail either - nothing to help debug an issue

**Comment by joanlandry** [comment]
there use to be a level 4 option some time in the past that provided a lot more detailed log info for debugging - now it appears that info is not available anymore. The other day when I posted an issue where netopeer2 crashed you asked me to provide a more detailed log. All I could provide was what was available via level 2 which had nothing to go on as to where the segfault occurred.  What can I do to get a more detailed log - so that if netopeer2 segfaults we would be able to have an idea what it was doing?
