### ISSUE TITLE
How command searchpath works

### ISSUE THREAD

**Issue by Netzo91** [CESNET/netopeer2#1591]
Hi,

I want to clarify how the command searchpath works.

In the help it say : `Set the directory, which will be used when searching for modules. Modules
are always needed to be able to work with the same data as a NETCONF server.
They are searched locally (in this directory) only if the server does not
support the <get-schema> NETCONF operation`

What does that mean? 
if the server supports get-schema even if modules are pointed locally by searchpath, netopeer2-cli will use those via get-schema?
is there a way to bypass get-schema modules for the netopeer2-cli (without modify the server)?

Thanks in advance for your reply

**Comment by michalvasko** [comment]
Where are you reading this description? It is not up-to-date, modules are first searched locally (if the revision is known) and only if not found `get-schema` is used to retrieve them from the server.

**Comment by AeroFlorian** [comment]
Hi,
This is directly in the code: [netopeer2/cli/doc/netopeer2-cli.1 at 373eb48edaf86c5d44a5f86399d2e38f9de76bf0 · CESNET/netopeer2 (github.com)](https://github.com/CESNET/netopeer2/blob/373eb48edaf86c5d44a5f86399d2e38f9de76bf0/cli/doc/netopeer2-cli.1#L1198) 
 
![image](https://github.com/CESNET/netopeer2/assets/32739256/3ba040a2-98eb-4ceb-8994-ca6e8f6a18bf)


What we want to do here is use different revisions for models on client side and server side:
 
![image](https://github.com/CESNET/netopeer2/assets/32739256/d2dd32f2-e360-43d7-8fff-2db9dd3f0b4c)


Then, we want to validate that when Netconf client sends requests and gets responses they are valid with its set of Yang models (revision A)
We tried sending an edit-config rpc that is valid on revision B but not valid on revision A, and netopeer2-cli sent it without checking it was valid.
Same with a get rpc, the response from netopeer2-server was valid in revision B but not in revision A and netopeer2-cli received it and displayed it without checking.

The questions we have are:
-	Does netopeer2-cli validate the requests/answers based on its own set of yangs?
-	If not, is there a way to do the scenario we want? And what for is searchpath used?

**Comment by michalvasko** [comment]
> What we want to do here is use different revisions for models on client side and server side:

No, do not do this, it is not supported, goes directly against NETCONF specs, and can cause nothing but issues.

**Comment by michalvasko** [comment]
It is just another configuration parameter. Any modules downloaded using `get-schema` are stored in the search path and the next time you connect to the same server, the modules can be loaded locally. But if you already have all the modules, you can use searchpath to point to the right directory and the modules do not have to be downloaded at all, for optimization.

**Comment by robbynet** [comment]
The reality in our field is that NC Clients having a set of Yang in Vn must interoperate with other devices hosting NC Servers executed with a set of Yang in Vn+1. How is it possible to test such interoperability with the NC Client/Server components made available by Netopeer2 ?

**Comment by robbynet** [comment]
Because get-schema is not used by our real NC Client even if supported by the NC Server

**Comment by robbynet** [comment]
Thanks for the sharing, now state of the art is clear.

**Comment by AeroFlorian** [comment]
Additional question: 
      Does netopeer2-cli validates requests/responses based on their modules stored?

**Comment by michalvasko** [comment]
The CLI loads all the server modules when establishing the connection because it parses all the NETCONF messages. So yes, all the requests and responses are parsed (and validated) by *libyang*.

**Comment by AeroFlorian** [comment]
Thanks for clarifications, let's close the question

**Comment by jktjkt** [comment]
> The reality in our field is that NC Clients having a set of Yang in Vn must interoperate with other devices hosting NC Servers executed with a set of Yang in Vn+1.

This should work just fine as long as your NETCONF servers properly bump the revision date on each change. Is that the case for your servers? (For development purposes, setting the cache directory to a throwaway location looks like a sensible step.)

**Comment by robbynet** [comment]
> > The reality in our field is that NC Clients having a set of Yang in Vn must interoperate with other devices hosting NC Servers executed with a set of Yang in Vn+1.
> 
> This should work just fine as long as your NETCONF servers properly bump the revision date on each change. Is that the case for your servers? (For development purposes, setting the cache directory to a throwaway location looks like a sensible step.)

Yes, O-RAN WG4 is always taking care to change revision of the module when modifications in the modules are performed.

**Comment by jktjkt** [comment]
Then you should have no problems; you can let the code slowly fill up directory with local copies of YANG files retrieved from various NETCONF servers. If you're using some SW that's using libnetconf2, and if this software has a problem with, say, `example@2024-01-01.yang` and `example@2024-01-02.yang` both existing on disk in that directory, please file a bug. This feature is (I suppose) intended to be used as a caching optimization.
