### ISSUE TITLE
How to use an IPv6 address to connect to netopeer2-server

### ISSUE THREAD

**Issue by hi-Mr-ye** [CESNET/netopeer2#1592]
Hi
I can only connect to netopeer2-server through an IPv4 address using the connect command under the netopeer2-cli tool.
How to use an IPv6 address to connect to netopeer2-server?

**Comment by michalvasko** [comment]
Change the address *netopeer2* is listening on (for example, using `sysrepocfg -Evim -m ietf-netconf-server`) to an IPv6 address (can be just `::`) and then connect to it.

**Comment by hi-Mr-ye** [comment]
Thank you for your answer.
Can only be modified through sysrepocfg -Evim -m ietf-netconf-server? 
Is there any other way to modify this configuration, such as which function?

**Comment by michalvasko** [comment]
Of course, use *sysrepo* functions ([docs](https://netopeer.liberouter.org/doc/sysrepo/devel/html/edit_data.html)).

**Comment by hi-Mr-ye** [comment]
Thank you again for your answer. I will close this issue.
