### ISSUE TITLE
netopeer2-server crash after SSH socket error: connection timed out.

### ISSUE THREAD

**Issue by DaemonZhao** [CESNET/netopeer2#1594]
Hi，Michal
     Recently，I got some questions about netopeer2-server which crashed sometime，Especially when the network latency increases；
Here is the log when netopeer2-serer crashed:

_INF]: NP: Session 8: thread 3 event new RPC.
[2024/06/22 15:26:02.778992, 1] ssh_socket_exception_callback:  Socket exception callback: 2 (110)
[2024/06/22 15:26:02.779238, 1] ssh_socket_exception_callback:  Socket error: Connection timed out
[ERR]: LN: Session 8: SSH channel poll error (Socket error: Connection timed out).
[INF]: NP: Session 8: thread 2 event session terminated.
[ERR]: LY: Invalid union value "hmac-sha1,hmac-sha2-256,hmac-sha2-512" - no matching subtype found. (Schema location "/ietf-netconf-notifications:netconf-session-end/source-host".)
[ERR]: SR: Invalid union value "hmac-sha1,hmac-sha2-256,hmac-sha2-512" - no matching subtype found. (Schema location "/ietf-netconf-notifications:netconf-session-end/source-host".)
[WRN]: NP: Failed to send a notification (libyang error).
[INF]: LN: Call Home client "default-client" session terminated.
[INF]: LN: Trying to connect via IPv4 to 192.168.30.1:4334.
[ERR]: SR: Internal error (/home/wwh1/path/sysrepo-2.1.84/src/common.c:3976).
[ERR]: SR: Internal error (/home/wwh1/path/sysrepo-2.1.84/src/common.c:3976).

Hardware:
Embedded Operating System
# uname -a
Linux ultichip 4.19.78-ucV1.2.1 #5 Wed Nov 8 15:51:58 CST 2023 armv7l GNU/Linux
Version:
netopeer2-server -V
netopeer2-server 2.1.36
sysrepoctl -V
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.1.84 (SO v7.8.10)

**Comment by DaemonZhao** [comment]
There is another scenario that would cause the service's call home process to terminate：When there is a significant network latency， like this:
[INF]: NP: Session 18: thread 4 event new RPC.
[2024/06/22 15:06:47.292686, 1] ssh_socket_exception_callback:  Socket exception callback: 1 (0)
[2024/06/22 15:06:47.292908, 1] ssh_socket_exception_callback:  Socket error: disconnected
[ERR]: LN: Session 18: SSH channel poll error (Socket error: disconnected).
[INF]: NP: Session 18: thread 4 event session terminated.
[INF]: LN: Call Home client "default-client" session terminated.
[INF]: LN: Trying to connect via IPv4 to 192.168.30.1:4334.
[INF]: LN: getsockopt() error (Connection refused).
[ERR]: LY: Invalid union value "0▒^E" - no matching subtype found. (Schema location "/ietf-netconf-notifications:netconf-session-end/source-host".)
[ERR]: SR: Invalid union value "0▒^E" - no matching subtype found. (Schema location "/ietf-netconf-notifications:netconf-session-end/source-host".)
[WRN]: NP: Failed to send a notification (libyang error).
[ERR]: SR: Internal error (/home/wwh1/netop-1013/ntsim-compile/4_OpenSourceCode/2022_08_03/sysrepo-2.1.84/src/common.c:3976).
[ERR]: SR: Internal error (/home/wwh1/netop-1013/ntsim-compile/4_OpenSourceCode/2022_08_03/sysrepo-2.1.84/src/common.c:3976).
[ERR]: LN: Call Home client "default-client" was not found.
[INF]: LN: Call Home client "default-client" thread exit.

Is this normal? And how can it be restored?

**Comment by michalvasko** [comment]
Please update all the libraries and *netopeer2*, I cannot help you with such an outdated version, there were lots of problems fixed since.

**Comment by DaemonZhao** [comment]
Do you mean to use the latest Tag version of the libraries and netopeer2?
Eg:
    netopeer2    V2.2.19
    libyang        V2.2.8
    libnetconf2  V3.0.17
   These library versions compatible with each other, right? Please provide guidance. Thank you so much.

**Comment by michalvasko** [comment]
You always see all the versions on *netopeer2* [release](https://github.com/CESNET/netopeer2/releases/tag/v2.2.19) page (which correspond to the `master` branches of the projects). But there were some problems with this release so the safest is to use the `devel` branches. There should be a new release soon but I am still fixing some things.

**Comment by DaemonZhao** [comment]
Okay, I understand. Thank you very much for your prompt response.
