### ISSUE TITLE
build netopeer2

### ISSUE THREAD

**Issue by zhoulinghua** [CESNET/Netopeer2#160]
I do not know how to build netopeer2.
can you help me. thank you!

**Comment by michalvasko** [comment]
Hi,
it seems you are quite new to Linux, so I will try to get you started. In case you do not know `git`, the very first thing you need to do is to clone this repository, you do that with
```
git clone https://github.com/cesnet/netopeer2
```
Then open `netopeer2/server/README.md` and follow instructions there, starting with cloning some other repositories as they are prerequisites of *netopeer2*.

Just wondering, how come you have a binary of `netopeer2-server` and you have not compiled it yourself? We do not provide binary packages yet (but will soon).

Regards,
Michal

**Comment by zhoulinghua** [comment]
thank you!
I have downloaded it. I install libyang,libnetconf.
but I have an error when installing sysrepo

$ git clone https://github.com/sysrepo/sysrepo.git
$ cd sysrepo
$ mkdir build; cd build
$ cmake ..
$ make

not find makefile

**Comment by michalvasko** [comment]
Oh, okay, lets keep the discussion there then.
