### ISSUE TITLE
netopeer2-server: /home/ubuntn/libyang-2.0.112/src/parser_xml.c:696: lydxml_subtree_r: Assertion `xmlctx->status == LYXML_ELEM_CLOSE' failed.  Aborted (core dumped)

### ISSUE THREAD

**Issue by musefanhua** [CESNET/netopeer2#1607]
Hello, I used netopeer2-2.0.35 to build a service, and used gonetconf as a client to connect to the service. When I sent some specially constructed data packets, the service debug mode was aborted. The information is as follows: netopeer2 -server: /home/ubuntn/libyang-2.0.112/src/parser_xml.c:696: lydxml_subtree_r: Assertion `xmlctx->status == LYXML_ELEM_CLOSE' failed.

Aborted (core dumped), 
is this a BUG?

**Comment by jktjkt** [comment]
That's a very old version; can you reproduce the error with the newest release? What YANG models are in use, and how does the request which triggers the error message looks like?
