### ISSUE TITLE
Complete example for callback mechanism e.g when changing/reading some field via netopeer2-server

### ISSUE THREAD

**Issue by capiman** [CESNET/netopeer2#1609]
Is there some complete example, how to register a callback when a field is changed or read-back via netopeer2-server?

**Comment by michalvasko** [comment]
For that focus on the *sysrepo* project and its [examples](https://github.com/sysrepo/sysrepo/tree/master/examples).

**Comment by capiman** [comment]
Thanks! I will do it!
