### ISSUE TITLE
Call home to loopback IP is failing

### ISSUE THREAD

**Issue by svashok** [CESNET/netopeer2#1611]
Hi Michal,

When we try to run a sample netconf client in the same VM where netconf server is hosted, we get the following error during call home.

local call home failing at 
sysrepocfg error: Invalid leafref value "default-ssh" - no target instance "/ncs:netconf-server/ncs:listen/ncs:endpoints/ncs:endpoint/ncs:name" with the same value. (path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='default-ssh']/endpoints/endpoint[name='local']/ssh/ssh-server-parameters/client-authentication/libnetconf2-netconf-server:endpoint-reference") (Validation failed)

Any suggestions please?

**Comment by svashok** [comment]
Basically I use the loopback IP for call home and this is the XML used:
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
<listen>
<endpoints>
<endpoint>
<name>default-ssh</name>
<ssh>
<tcp-server-parameters>
<local-address>0.0.0.0</local-address>
</tcp-server-parameters>
<ssh-server-parameters>
<server-identity>
<host-key>
<name>default-key</name>
<public-key>
<central-keystore-reference>genkey</central-keystore-reference>
</public-key>
</host-key>
</server-identity>
<client-authentication>
<users>
<user>
<name>root</name>
<keyboard-interactive xmlns="urn:cesnet:libnetconf2-netconf-server">
<use-system-auth/>
</keyboard-interactive>
</user>
</users>
</client-authentication>
</ssh-server-parameters>
</ssh>
</endpoint>
</endpoints>
</listen>
</netconf-server>

**Comment by michalvasko** [comment]
The XML you posted includes only a `listen` endpoint. You need to **merge** the Call Home configuration into this one, if you want to reference the `listen` endpoint authentication settings from a `call-home` endpoint.

**Comment by svashok** [comment]
After adding the call home configuration and IETF keystore in the same XML, call home is working. Thanks.

I have a follow up question please. Can a Netconf server dynamically initiate call home to an additional client without restarting the server, when it is already running and connected with a few clients? One option is to use configured-client-info, but that has to be sent by an existing client. The existing clients will not have the information about the new client.

**Comment by michalvasko** [comment]
You can modify *netopeer2-server* configuration in run-time, so just normally add another client and the server should adjust itself accordingly.
