### ISSUE TITLE
Does netopeer-cli support public key based authentication

### ISSUE THREAD

**Issue by safwan2m** [CESNET/netopeer2#1614]
I'm able to ssh into another system using ssh public key, but how do I replicate the same using netopeer2-cli, couldn't find any documentation regarding this, so posted a query.

**Comment by safwan2m** [comment]
I'm trying to setup call-home using ssh and want to do public key-based authentication. I'm able to setup the call-home functionality successfully, but unable to figure out how to switch from interactive password-based authentication to public key-based authentication.

**Comment by michalvasko** [comment]
I wouldn't think this too hard to find, look at the `auth` command (`auth --help`).

**Comment by safwan2m** [comment]
Yes, I was able to find it. Thank you.

**Comment by safwan2m** [comment]
Solved, by checking the documentation for auth. Was difficult first-time user.
