### ISSUE TITLE
Unable to receive callback when trying to subscribe custom yang model using sr_oper_get_subscribe()

### ISSUE THREAD

**Issue by konu27** [CESNET/netopeer2#1621]
Hi 
I am trying to read data from a file and send to netconf client whenever a get-config request is sent, instead of reading from default sysrepo data.
I have tried to subscribe my yang data model using sr_oper_get_subscribe() function and I have implemented above functionality in my call back function. I am unable to receive any hit for my subscribed yang data model. 
I Want to know if these feature is supported by sysrepo and how to resolve this.

Thankyou.

**Comment by michalvasko** [comment]
No, your use-case is not supported. *sysrepo* is a datastore and there is no reason for it to just take some file contents instead of the data it has stored.
