### ISSUE TITLE
Mechanism for distinguishing notifications between multiple subscriptions

### ISSUE THREAD

**Issue by AndersonRTUS** [CESNET/netopeer2#1630]
Hi there,

I'm using `establish-subscription` to create multiple subscriptions within a single NETCONF session. After that, I start receiving notifications, but the issue is that I'm unable to differentiate between them. My question is: Is there any mechanism for distinguishing notifications? I do have the subscription IDs, but they don't seem to be included in the received notifications. I understand that this may not be supported per RFC8639, but I was hoping there might be some other way to differentiate them.

Thanks!

**Comment by michalvasko** [comment]
No, there is no such mechanism to my knowledge.

**Comment by ACE-777** [comment]
@michalvasko Thank you for the clarification! Appreciate the quick response)

**Comment by AndersonRTUS** [comment]
@michalvasko thank you for the clarification! Appreciate the quick response)
