### ISSUE TITLE
op_generic get an unexpected empty non-presence container node and send to sysrepo

### ISSUE THREAD

**Issue by qmm161** [CESNET/Netopeer2#164]
Hi,

I defined an yang model for rpc testing, when I tested it with an xml like below I find netopeer2-server send a leaf node for f1 and an empty container node for npcont to sysrepo in op_generic. Should netopeer2-server remove this emtpy non-presence container node before sending to sysrepo?

yang model:
```yang
module TestRpc {
	namespace "ns:test:nonpresence:container:rpc";
	prefix TestRpc;

	rpc setdata{
		input{
			leaf f1{
				type uint32;
			}
			
			container npcont {
				leaf f1 {
					type string;
				}
			}
		}
		output{
			leaf f1{
				type uint32;
			}
		}		
	}
}
```

---

rpc request xml:
```
<setdata xmlns="ns:test:nonpresence:container:rpc">
    <f1>1</f1>
</setdata>
```

**Comment by michalvasko** [comment]
Hi,
what exactly is the problem? We can skip default nodes (enpty non-presence container can be considered to be default - it is implicitly in the datastore if the parent exists) to make it more effective but it does not make any real difference.

Regards,
Michal
