### ISSUE TITLE
Get started failing for o-ran yang models

### ISSUE THREAD

**Issue by zdevcic** [CESNET/netopeer2#1642]
Hello,

started observing one strange issue and need your help. Basically all was running smoothly for a long time, and after some activities executed it stopped working. Not sure which exact activity caused problem to start happening (trying to figure it out now), but it includes upgrading versions of sysrepo, netopeer2, libnetconf2 and libyang (no actual upgrade since all versions were on the latest), and installing set of models (most of them were already installed in the system at desired release so not upgraded at all). Generally, would not expect any of these activities create some issue. 

Issue observed in netopeer2-cli is that now simple get fails for all o-ran models (works for most of ietf models), e.g.

_get --filter-xpath=/o-ran-uplane-conf:*_

response is

_ERROR
	type:     application
	tag:      operation-failed
	severity: error
	message:  Storing value failed._

I have tried to debug further by executing "verb verbose" before  connect and get the same error listed for all o-ran models loading attempt 

**"The requested format is not supported."**

Looking into the netopeer2 code I can see it raised if model is not yang/yin, but it cannot be the case since no change in the models at all. All of them are proper yang models. Used to work, now it fails.

Cannot conclude more. Please advise.

Thanks a lot.

**Comment by michalvasko** [comment]
That seems like a failed upgrade and some old libraries still being used. Clean your system and make sure there are no old libraries or files and reinstall everything, that should solve this problem.

**Comment by zdevcic** [comment]
You are fully right. In the meantime we approached reinstall, and that solved the issue. 

Really some old libraries were there, so I can confirm your RCA.

Please close the issue.

Thanks a lot.
