### ISSUE TITLE
capabilies comfirm

### ISSUE THREAD

**Issue by RogerYaozhenyu** [CESNET/Netopeer2#165]
hi, last year, i asked a question about capbilites about libnetconf2 or libnetconf. detailes pls refer to the link as below:
https://github.com/CESNET/libnetconf/issues/248
Now , i want to confirm that if the capablities whch list below are supported  in Netopeer2 now? thanks, 
if not support, do you have a roadmap to support in the future?
hope can get your feedback.

:notification
:notification1.1
:confirmed-commit
:confirmed-commit:1.1
:partial-lock
:time:1.0
:yang-library
:yang-push:1.0

**Comment by michalvasko** [comment]
Hi,

- `:notification` supported,
- `:notification1.1` will be supported once an RFC and not a draft,
- `:confirmed-commit` not supported, obsolete,
- `:confirmed-commit:1.1` not supported, but will be in future,
- `:partial-lock` not supported, no plans for implementation, but it still may be added in future,
- `:time:1.0` not supported, no plans for implementation, but it still may be added in future,
- `:yang-library` supported,
- `:yang-push:1.0` not supported (related more to RESTCONF), no plans for implementation, but still may be added in future.

Regards,
Michal
