### ISSUE TITLE
Errors with ietf-yang-schema-mount after updating Netopeer2 Docker Image

### ISSUE THREAD

**Issue by sjakubek** [CESNET/netopeer2#1651]
Hello, 

I am not very experienced in this area, so any guidance or suggestions would be really appreciated.

After updating the Docker image to the latest version of Netopeer2, I'm encountering issues when installing additional 3GPP YANG modules into the sysrepo datastore. My setup worked with a previous version of Netopeer2, so it seems like recent changes are causing the problem. I suspect something has changed, as I updated the container image after about two years.

I have basic 3GPP YANG modules installed in sysrepo, all from the [Tag_Rel16_SA96](https://forge.3gpp.org/rep/sa5/MnS/-/tree/Tag_Rel16_SA96/yang-models) branch, including:

* `ietf-inet-types.yang`
* `ietf-yang-types.yang`
* `_3gpp-common-top.yang`
* `_3gpp-common-yang-extensions.yang`
* `_3gpp-common-yang-types.yang`
* `_3gpp-common-trace.yang`
* `_3gpp-common-fm.yang`
* `_3gpp-common-measurements.yang`
* `_3gpp-common-subscription-control.yang`
* `_3gpp-common-managed-element.yang`

These modules install without issues. However, when I install additional 3GPP NRM YANG modules (aligned with the same 3GPP common YANG modules), I start seeing repeated errors related to `ietf-yang-schema-mount` during startup:

``
[ERR] No "ietf-yang-schema-mount" operational data set needed for parsing mounted data.
``

This error appears for almost every installed NRM module, even though the modules themselves do get installed, and the status looks fine when checked using sysrepoctl -l.

I also noticed that the `ietf-yang-schema-mount` module already existed in the updated Netopeer2 Docker image, with the exact same revision as the one from the 3GPP repository (2019-01-14). Hence, I didn’t re-import it.

Here’s a snippet of the error log:

```
[INFO] Installing _3gpp-common-subnetwork.yang
[ERR] No "ietf-yang-schema-mount" operational data set needed for parsing mounted data.
[ERR] No "ietf-yang-schema-mount" operational data set needed for parsing mounted data.
[INFO] Installing _3gpp-common-ep-rp.yang
[ERR] No "ietf-yang-schema-mount" operational data set needed for parsing mounted data.
...
```

My Question: Is there a step I might be missing in terms of setting operational data for the ietf-yang-schema-mount module?

Many thanks!

**Comment by michalvasko** [comment]
After some digging it turns out your use-case exposed a fairly unrelated bug even though the error was harmless in your case. If you use the current *libyang* `devel`, the error will be gone.

**Comment by michalvasko** [comment]
No, it should not and you can ignore the error.
