### ISSUE TITLE
Netopeer2-server listening on ipv6

### ISSUE THREAD

**Issue by Vineet0197** [CESNET/netopeer2#1653]
My Kubernetes cluster supports only IPv6 to establish communication between two pods. And this netopeer2-server is running as a process inside one of my application pod. please help me how I can achieve to make this netopeer2-server listening on ipv6 ?

FYI, supervisord.conf includes following for netopeer2-server : 
```
[inet_http_server]
port = 0.0.0.0:9001

[program:netopeer2-server]
command=/usr/local/bin/netopeer2-server -d
autorestart=true
startretries=10
redirect_stderr=true
priority=4
```

Output for the processes running in my application :
```
root@o1mediator:/# ps -aef
UID          PID    PPID  C STIME TTY          TIME CMD
root           1       0  0 11:39 ?        00:00:00 /usr/bin/python3 /usr/bin/supervisord -n
root           7       1  0 11:39 ?        00:00:00 python3 /usr/local/bin/process-state.py
**root           8       1  0 11:39 ?        00:00:00 /usr/local/bin/netopeer2-server -d**
root           9       1  0 11:39 ?        00:00:00 /usr/local/bin/o1agent -f /etc/o1agent/config-file.json
root          36       7  0 11:39 ?        00:00:00 python3 /usr/local/bin/process-state.py
root          45       7  0 11:39 ?        00:00:00 python3 /usr/local/bin/process-state.py
root          51       0  0 11:42 pts/0    00:00:00 /bin/bash
root          60      51  0 11:42 pts/0    00:00:00 ps -aef
root@o1mediator:/#
```

Output of netstat -tnlp command :
```
root@o1mediator:/# netstat -tnlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:3000            0.0.0.0:*               LISTEN      45/python3
**tcp        0      0 0.0.0.0:830             0.0.0.0:*               LISTEN      8/netopeer2-server**
tcp        0      0 0.0.0.0:9001            0.0.0.0:*               LISTEN      1/python3
tcp6       0      0 :::4588                 :::*                    LISTEN      9/o1agent
tcp6       0      0 :::8080                 :::*                    LISTEN      9/o1agent
tcp6       0      0 :::4560                 :::*                    LISTEN      9/o1agent
tcp6       0      0 :::4561                 :::*                    LISTEN      9/o1agent
root@o1mediator:/#
```

I want this netopeer2-server to use tcp6 for listening on ipv6. This is CRITICAL feature I want to implement in my official project.

**Comment by michalvasko** [comment]
Just edit the configuration of the server. You can use `sysrepocfg -Evim -d running -m ietf-netconf-server`, there you can change the `local-address` value to `::`, for example. To make sure the change is kept even after a reboot, do the same change using `-d startup` parameter as well.

**Comment by Vineet0197** [comment]
Instead of this manual configuration change, can you help me to do this configuration at the startup of this netopeer2-server process inside my application using supervisord.conf ?

**Comment by Vineet0197** [comment]
Thanks @michalvasko  for the support. I able to enable netopeer2-server listening on ipv6 using the above command at the startup itself.

**Comment by michalvasko** [comment]
That is fine because pretty much the same way even the default configuration is [set up](https://github.com/CESNET/netopeer2/blob/master/scripts/merge_config.sh#L95).
