### ISSUE TITLE
SR: Waiting on a conditional variable failed (sr_notif_sub_del: Connection timed out) && Failed to write a notification (Broken pipe)

### ISSUE THREAD

**Issue by rydy** [CESNET/netopeer2#1659]
Hi
    I'm using version [2.2.19](https://github.com/CESNET/netopeer2/releases/tag/v2.2.19),When "SR: Waiting on a conditional variable failed (sr_notif_sub_del: Connection timed out) && Failed to write a notification (Broken pipe)" occurs,netopeer2-server cannot be started. Is there any other way except redeploy sysrepo? What causes this error?
 
Here are some logs and core files:
[netopeer2-server.log](https://github.com/user-attachments/files/17520218/netopeer2-server.log)
[core-netopeer2-serve-22801-1729132934.zip](https://github.com/user-attachments/files/17520219/core-netopeer2-serve-22801-1729132934.zip)

Thanks.

**Comment by michalvasko** [comment]
As I have already told you, the subscriptions were significantly refactored since then and so I am unable to help you with any problems with the version you are using. There were lots of since-fixed issues.

**Comment by rydy** [comment]
> As I have already told you, the subscriptions were significantly refactored since then and so I am unable to help you with any problems with the version you are using. There were lots of since-fixed issues.

ok, I updated to [2.2.31](https://github.com/CESNET/netopeer2/releases/tag/v2.2.31)
