### ISSUE TITLE
On board a new module in sysrepo we are unable to make changes via netconf

### ISSUE THREAD

**Issue by darren-west** [CESNET/Netopeer2#166]
Hi,

When I onboard a new module in sysrepo I am returned a bad element request when trying to make changes through netconf. If I restart the server I am then able to make changes.

Is there any way to refresh or update the netopeer server without restarting?

Thanks in advance,
Darren

**Comment by michalvasko** [comment]
Hi Darren,
can you please post the output of `netopeer2-server` when you install a new module into `sysrepo`? It should adjust accordingly an no restart should be needed.

Regards,
Michal

**Comment by rkrejci** [comment]
How old is the NETCONF session you are using? Is it established after the change on the server?

**Comment by darren-west** [comment]
Hi,

I will run through exactly what I did:

1) Ran `docker run -it -p 830:830 sysrepo/sysrepo-netopeer2`
2) docker exec -it container_id /bin/bash
3) sysrepoctl --install --yang test.yang

```
module test {

  namespace "http://test.com/test";
  prefix test;

  import ietf-yang-types { prefix yang; }

 container test {
   	leaf name {
   		type string;
   	}
  }
}
```
5) Connected through netopeer cli and dumped the payload
```
    <test xmlns="http://test.com/test">
      <name>Update {i}</name>
    </test>
```

6) I would expect this to fail as there are no registered callbacks on the module but the error I receive is `netopeer2-server[11]: Unknown element "test".` I would expect it to be Invalid argument.

I have tried this with a registered callback and i get the same error.

If i now restart the netopeer2-server then I get the expected invalid argument error.

Because I connect to netopeer2-server after installing the module I assume the session is not the problem?

Thanks in advance,
Darren

**Comment by darren-west** [comment]
I also just ran the `sysrepoctl --install --yang --owner netconf`
And there is no log message printed from netopeer2-server:
```
/turing-machine:turing-machine/transition-function/delta[label='write separator']/output/state = 3
/turing-machine:turing-machine/transition-function/delta[label='write separator']/output/symbol = 0
/turing-machine:turing-machine/transition-function/delta[label='write separator']/output/head-move = left
/turing-machine:turing-machine/transition-function/delta[label='go home'] (list instance)
/turing-machine:turing-machine/transition-function/de
2017-08-09 11:00:43,072 INFO success: sysrepod entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-08-09 11:00:43,072 INFO success: sysrepo-plugind entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-08-09 11:00:43,072 INFO success: netopeer2-server entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```
Last messages printed were the above

**Comment by michalvasko** [comment]
Hi,
I have just tried your scenario and everything worked exactly as expected. However, I have used most recent `devel` versions of all the libraries and applications and no docker. You are saying you used 0.6.0 meaning `master`. It is best to switch to `devel` anyway because it will be merged to `master` in the next few days.

Regards,
Michal

**Comment by darren-west** [comment]
Hi,
Thanks i have found the issue was to do with versions. Using the tagged release for Netopeer2 the issue exists if you using the latest master it works. The tagged version that doesnt work is v0.3-r1.
Regards,
Darren
