### ISSUE TITLE
Possible to set a SSH banner message in netopeer2 

### ISSUE THREAD

**Issue by mpet** [CESNET/netopeer2#1660]
Hi,
We would like to test to set SSH banner when we connect to Netopeer2. Is it possible?

br,

//mike

**Comment by michalvasko** [comment]
No, the configuration of the SSH banner is not currently supported.

**Comment by mpet** [comment]
@michalvasko  any plans to include it?

**Comment by michalvasko** [comment]
Since this is a fairly simple change, it will be supported. However, only the server (*netopeer2*) will be able to customize its banner, it does not for the client, *libssh* limitation.

**Comment by michalvasko** [comment]
Done, with a special *netopeer2* banner, which can be customized.
