### ISSUE TITLE
line wrapping the logs of netopeer2-server

### ISSUE THREAD

**Issue by sukesh9995** [CESNET/netopeer2#1663]
Hi @michalvasko,

netopeer2-server -d -c MSG command is not doing a line wrap of the log messages. So, the data is getting truncated at the end of the screen.

But netopeer2-cli with verb 3 is doing a line wrapping and i could get all the data properly.

Is there any configuration which needs to be changed to get all the logs from netopeer2-server?

Regards,
Sukesh

**Comment by michalvasko** [comment]
There is no configuration but it should not be needed, your terminal or whatever application displaying the output should do the wrapping. If it is not, I suggest you try another one.
