### ISSUE TITLE
 ECDSA key support

### ISSUE THREAD

**Issue by rosy8** [CESNET/netopeer2#1666]
Hello,

We are testing the TLS handshake using an ECDSA key and have noticed that the handshake fails with the error: "[ERR]: SSL_accept failed (no shared cipher)."

I attempted to list the ciphers available for that session before the ssl_accept call and confirmed that the ciphers are indeed present on the server side. (STACK_OF(SSL_CIPHER) *ciphers = SSL_get_ciphers(ssl);)

Additionally, I tried to specifically set the private key to NC_SSH_KEY_ECDSA by specifically hardcoding it as shown below

int  tls_set_server_cert_clb(const char *name, void *user_data, char **cert_path, char **cert_data,
                                               char **privkey_path, char **privkey_data,
                                               NC_SSH_KEY_TYPE *privkey_type)
{
.........................
    *cert_path = strdup(cpath.c_str());
    *privkey_path = strdup(pkey.c_str());
    *privkey_type= NC_SSH_KEY_ECDSA;

 }

Logs:
tls_set_server_cert_clb]  privkey_type=>3
……

[ERR]: SSL_accept failed (no shared cipher).
[ERR]: SSL_accept failed - Free session->ti.tls)

However, the ssl_accept call still fails with the error "no cipher found." According to the packet capture (pcap), the client hello message lists all ciphers from the client side which inculdes the ECDSA ciphers.

I would appreciate any guidance on specific settings or configurations we might have missed. 

FYI:  The TLS handshale works while using the openssl client server command.

TLS Server:
openssl s_server -accept 1234 -cert /tmp/cert.pem -cipher 'ALL'  -debug -key /tmp/key.key
 
TLS Client:
openssl s_client -host <hostname> -port 1234 -CAfile /tmp/test/cacert.

Openssl version used:
openSSL 1.0.2k  26 Jan 2017

Thank you in advance.

Regards,
Haripriya

**Comment by Roytak** [comment]
Hello, 
I am not sure what to suggest other than updating netopeer2 to the latest version. A TLS test that uses an EC key is now part of the libnetconf2 repository (https://github.com/CESNET/libnetconf2/commit/acfb5cb8f7d4025333cd63ae9cf8422af0c689f3) and it works. It's also possible that it works just because of a newer OpenSSL version being used and required.

If updating is not possible, then what you can try is to edit the libnetconf2 code in session_server_tls.c and add the specific TLS ciphersuites (the ones offered by the client) to the SSL/SSL_CTX structs there.

**Comment by rosy8** [comment]
Hi @Roytak ,

Thanks for your response.
We are using Tailf Confd as a netconf server.

Yeah, updating the OpenSSL version would not be possible at this stage. 
However, I updated the libnetconf2 code as follows..

File : session_server_tls.c
Function : nc_accept_tls_session(...)

Added the following to the SSL_CTX
    // Set the desired TLS cipher suites
    const char *cipher_list = "ECDHE-ECDSA-AES256-GCM-SHA384"; 
    if (SSL_CTX_set_cipher_list(tls_ctx, cipher_list) != 1) { 
        ERR(session, "Failed to set TLS cipher suites (%s).", ERR_reason_error_string(ERR_get_error()));
        goto error; 
    }

==> Post doing this, also the ssl_accept fails  with "no cipher" found.
[ERR]: ########################## CIPHERS:Start -[goto error tag] ###################################
[ERR]: SSL_accept failed (no shared cipher).
[ERR]: SSL_accept failed - Free session->ti.tls)


While dumping the supported ciphers, I observed that only "ECDHE-ECDSA-AES256-GCM-SHA384" was listed, as shown below:
[ERR]: CIPHERS: Initialized ciphers (ECDHE-ECDSA-AES256-GCM-SHA384).
However, without specifying this cipher suite, a comprehensive list of all supported ciphers was displayed.

void print_ciphers(struct nc_session *session, SSL *ssl, const char * str) {
    const char *cipher;
    STACK_OF(SSL_CIPHER) *ciphers = SSL_get_ciphers(ssl);
...
}

Any further guidance would be helpful.

Regards,
Rosy

**Comment by rosy8** [comment]
Hello,

I tried to dump the key to check whether private key is being set properly or not and found that its being set properly also.

Function: :nc_tls_ctx_set_server_cert_key(SSL_CTX *tls_ctx, const char *cert_name)



    EVP_PKEY *set_pkey = SSL_CTX_get0_privatekey(tls_ctx); 
    if (set_pkey) {
        ERR(NULL, "Private key successfully set."); 

        // Check if the key is ECDSA
        if (EVP_PKEY_base_id(set_pkey) == EVP_PKEY_EC) {
            ERR(NULL, "The private key is of type ECDSA."); 

            // Dump the private key details in "EC PRIVATE KEY" format
            EC_KEY *ec_key = EVP_PKEY_get1_EC_KEY(set_pkey); 
            if (ec_key) {
                BIO *bio = BIO_new(BIO_s_mem());
                if (PEM_write_bio_ECPrivateKey(bio, ec_key, NULL, NULL, 0, NULL, NULL)) {
                    char *key_data;
                    long key_len = BIO_get_mem_data(bio, &key_data);
                    ERR(NULL, "Private Key:\n%.*s", (int)key_len, key_data); 
                }
                BIO_free(bio);
                EC_KEY_free(ec_key);
            } else {
                ERR(NULL, "Failed to retrieve the EC key from the private key.");
            }
        } else {
            ERR(NULL, "The private key is not of type ECDSA.");
        }
    } else {
        ERR(NULL, "Failed to retrieve the private key from the SSL context.");
    }


Logs:

[ERR]: CIPHERS: Loading the server certificate from path (/tmp/certs/device/cert-0-0.pem).
[ERR]: CIPHERS: Loading the private key (/tmp/certs/private/key-x-x.pem).
[ERR]: Private key successfully set.
[ERR]: The private key is of type ECDSA.
[ERR]: Private Key:
-----BEGIN EC PRIVATE KEY-----
==
-----END EC PRIVATE KEY-----

So the private key is also being loaded properly and its the same as present in the server side.
However, still the ssl_accept fails with the "no cipher found" error.

Regards,
Haripriya,

**Comment by michalvasko** [comment]
I am sorry but we cannot help you any more, we do not provide support for deprecated *netopeer2* and/or OpenSSL versions. We made sure it works in the current versions and if you cannot use those, you are on your own.

**Comment by rosy8** [comment]
> I am sorry but we cannot help you any more, we do not provide support for deprecated _netopeer2_ and/or OpenSSL versions. We made sure it works in the current versions and if you cannot use those, you are on your own.

Hi Michal,

Thank you for your response.

I understand that support for deprecated versions of Netopeer2 and OpenSSL is no longer provided. However, we are using ConfD, not Netopeer2.

I am seeking your guidance regarding libnetconf2. The issue I am encountering appears to be related to libnetconf2. Bute yes, internally, it uses OpenSSL APIs.

Interestingly, the TLS handshake works seamlessly with standard OpenSSL client/server commands, which adds to my confusion. If the current OpenSSL version did not support ECDSA, I believe it should not have worked with the standard OpenSSL client/server commands.

Could you please advise if there might be a specific API or configuration that we might have missed that could resolve this issue? Or should I post this query in the libnetconf2 page?

Any insights or suggestions you could provide would be immensely helpful.

Thank you for your understanding and support.

Reagrds,
Haripriya Patel

**Comment by michalvasko** [comment]
Okay, we are the maintainers of *libnetconf2* as well so it does not matter where you create the issue or in which project is the problem. What I am saying is that we have no specific advice to give you because we have no more information than you do so we could only do what you are doing, try various fixes until it finally works. And we do not have a reason to spend time doing this because it works fine in our current versions so while it may help you specifically, there is no benefit to us or the community. So I am again sorry, but this is not included in the free support we provide.

**Comment by michalvasko** [comment]
Any [supported version](https://endoflife.date/openssl) is fine. Using any unsupported version is a major security risk.

**Comment by rosy8** [comment]
> Any [supported version](https://endoflife.date/openssl) is fine. Using any unsupported version is a major security risk.

Thank you, Michal.

Regrads,
Haripriya

**Comment by Roytak** [comment]
Hi,

> While dumping the supported ciphers, I observed that only "ECDHE-ECDSA-AES256-GCM-SHA384" was listed, as shown below:

This seems to be TLS1.2 only cipher, can you make sure that both the client and the server offer TLS1.2? If yes, then the last suggestion I have is to analyze the pcap from the successful handshake with OpenSSL's s_client and s_server and actually set all the ciphersuites (or possibly even TLS/SSL versions) offered by both the client and the server, not just one (and not just on the server). If that does not work, then I can not help you.

**Comment by rosy8** [comment]
> Hi,
> 
> > While dumping the supported ciphers, I observed that only "ECDHE-ECDSA-AES256-GCM-SHA384" was listed, as shown below:
> 
> This seems to be TLS1.2 only cipher, can you make sure that both the client and the server offer TLS1.2? If yes, then the last suggestion I have is to analyze the pcap from the successful handshake with OpenSSL's s_client and s_server and actually set all the ciphersuites (or possibly even TLS/SSL versions) offered by both the client and the server, not just one (and not just on the server). If that does not work, then I can not help you.

Hi @Roytak ,

Thank you for your suggestion.
Actually, I had already tried adding a few specific ciphers supported by both the client and server and still encountered the same error.  However, I will try adding all the ciphers and give it another try. 

Regards,
Haripriya
