### ISSUE TITLE
Clarification on Redis-Plugin and Data Fetching in Netopeer

### ISSUE THREAD

**Issue by VishalGujela** [CESNET/netopeer2#1669]
Hi,
I am currently working with the Redis DB plugin in the context of Netopeer and Sysrepo, and I was hoping to clarify how data is fetched from Redis when triggered by a get-config operation. Initially, I assumed that the process involved a direct call to the Redis plugin via Sysrepo, with some form of query being executed to retrieve and parse the data. However, after tracing the callback function np2srv_rpc_get_cb, I believe my initial understanding may be incorrect, as the flow appears to be different.

Could you kindly help me understand how exactly the data is parsed and fetched in this case? Specifically, I would appreciate any guidance on how the Sysrepo plugin, Netopeer library, and the Redis plugin interact during the get-config operation, and how I can use them to retrieve data from Redis.

Thank you in advance for your time and assistance. I look forward to your response.

Best regards,
Vishal

**Comment by michalvasko** [comment]
To answer you exactly I would need to know the reason why you are looking into this. But chances are you can safely ignore how *netopeer2* interacts with *sysrepo* and just focus on the redis plugin itself, reading data is performed by the [load](https://github.com/sysrepo/sysrepo/blob/master/src/plugins/ds_redis.c#L3855) function.

**Comment by michalvasko** [comment]
You will have to go through the code to find out how exactly is everything stored.

**Comment by VishalGujela** [comment]
Thanks @michalvasko 
I was able to fetch and parse the data accordingly
