### ISSUE TITLE
Require concurrence support for multi clients

### ISSUE THREAD

**Issue by fanchanghu** [CESNET/Netopeer2#167]
Hi,
This is a requirement about concurrence, this requirement may not be implemented in netopeer2, but the feature seems being provided by netopeer2, so I want to discuss it here.

This requirement is for avoiding the clients of netopeer2-server be blocked by each other, however, it is blocked in sysrepo client API such as `sr_rpc_send` now, because it gets a lock in `sr_conn_ctx_t` and unlocks it after the rpc response is received. If the rpc needs a long time to finish or timeout, all the other clients will be blocked.

**Comment by michalvasko** [comment]
Hi,
you are correct, *netopeer2-server* should support as much concurrence as is possible at this point, so please open this issue in *sysrepo*, that is where the problem is.

Regards,
Michal
