### ISSUE TITLE
getting Error message while sending kill-session rpc

### ISSUE THREAD

**Issue by biswajit84** [CESNET/netopeer2#1673]
Hi,
we are using sysrepo-2.2.170 and netopeer2-2.2.19.
while sending kill-session rpc from external application, I am getting error as "operation not supported" error message.
I hv crosschecked on passing correct session id.
```
 sr_val_t* input = {0};
    sr_val_t* output = NULL;
    size_t output_cnt = 0;
    int rc;
    input = (sr_val_t *)calloc(1, sizeof(sr_val_t));
    input->xpath = strdup("/ietf-netconf:kill-session/session-id");
    input->type = SR_UINT32_T;
    input->data.uint32_val = sessionId;
    rc = sr_rpc_send(session, "/ietf-netconf:kill-session", input, 1, 0, &output, &output_cnt);
    if (rc != SR_ERR_OK) {
        printf("Error sending RPC: %s\n", sr_strerror(rc));
    }
```
**Error Message:**
[WRN] EV ORIGIN: "/ietf-netconf:kill-session" "rpc" ID 1 priority 0 failed (Operation not supported).
[ERR] User callback failed.
 
Can you please help  how to solve the issue.

Regards,

**Comment by michalvasko** [comment]
Yes, this is intentional because you cannot kill a NETCONF session outside of the NETCONF protocol context. You need to connect to *netopeer2* in your application first by establishing a NETCONF session and then you can kill other sessions (if you have the correct permissions).

**Comment by biswajit84** [comment]
do we have any documentation for the same stating "kill a NETCONF session outside of the NETCONF protocol context"

**Comment by michalvasko** [comment]
Not explicitly, but all the NETCONF RPCs (found in `ietf-netconf`) can be executed only by a NETCONF session. Seems natural and also prevents unauthorized users from bypassing the NACM rules.

**Comment by biswajit84** [comment]
Atleast If you can locate the piece of code where its doing the check then it will be really helpful.

**Comment by michalvasko** [comment]
Sure, [here](https://github.com/CESNET/netopeer2/blob/master/src/common.c#L63).

**Comment by biswajit84** [comment]
Thanks alot for your response.
Now after the external application  connected to netopeer2-server through the unix domain socket, I am able to send the kill-session rpc and netopeer server also closing the session. But I have a doubt.
Even after the session got terminated the netopeer-cli didn't get any message.
But strange thing is if I again try to listen it gave message on netopeer2-cli like:"cmd_listen: Already connected to 127.0.0.1"
but when i execute quit, it is giving below message:

> nc ERROR: Communication socket unexpectedly closed (OpenSSL).
> nc ERROR: Invalid session to write to.
> nc ERROR: Invalid session to read from.
> nc ERROR: Failed to receive a reply to <close-session>.   

netopeer2-server log:

> [INF]: LN: getsockopt() error (Connection refused).
> [INF]: LN: Call Home client "default-client" timeout of 5 seconds expired, reconnecting.
> [INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4335.
> [INF]: LN: Successfully connected to localhost:4335 over IPv4.
> [INF]: LN: Cert verify: depth 1.
> [INF]: LN: Cert verify: subject: /C=CZ/ST=South Moravia/L=Brno/O=CESNET z.s.p.o./OU=TMC/CN=example CA/emailAddress=ca@example.org.
> [INF]: LN: Cert verify: issuer:  /C=CZ/ST=South Moravia/L=Brno/O=CESNET z.s.p.o./OU=TMC/CN=example CA/emailAddress=ca@example.org.
> [INF]: LN: Cert verify CTN: entry with a matching fingerprint found.
> [INF]: LN: Cert verify CTN: new client username recognized as "tls-test".
> [INF]: LN: Cert verify: depth 0.
> [INF]: LN: Cert verify: subject: /C=CZ/ST=South Moravia/L=Brno/O=CESNET z.s.p.o./OU=TMC/CN=client/emailAddress=client@example.org.
> [INF]: LN: Cert verify: issuer:  /C=CZ/ST=South Moravia/L=Brno/O=CESNET z.s.p.o./OU=TMC/CN=example CA/emailAddress=ca@example.org.
> [INF]: LN: Client certificate verified.
> **[INF]: LN: Session 2: Call Home client "default-client" session 2 established.**
> [INF]: SR: Session 540 (user "test-user", CID 113) created.
> [INF]: NP: Callhome data:1
> [INF]: SR: EV ORIGIN: "ietf-netconf-notifications" "notif" ID 1 priority 0 for 2 subscribers published.
> [INF]: NP: Generated new event (netconf-session-start).
> [INF]: SR: EV ORIGIN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 6 priority 0 for 1 subscribers published.
> [INF]: SR: EV LISTEN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 6 priority 0 processing (remaining 1 subscribers).
> [INF]: NP: Module "ietf-datastores@<any>" was requested.
> [INF]: SR: EV LISTEN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 6 priority 0 success (remaining 0 subscribers).
> [INF]: SR: EV ORIGIN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 6 priority 0 succeeded.
> [INF]: NP: Session 2: thread 2 event new RPC.
> [INF]: SR: EV ORIGIN: "/ietf-netconf:get" "rpc" ID 3 priority 0 for 1 subscribers published.
> [INF]: SR: EV LISTEN: "/ietf-netconf:get" "rpc" ID 3 priority 0 processing (remaining 1 subscribers).
> [INF]: SR: EV LISTEN: "/ietf-netconf:get" "rpc" ID 3 priority 0 success (remaining 0 subscribers).
> [INF]: SR: EV ORIGIN: "/ietf-netconf:get" "rpc" ID 3 priority 0 succeeded.
> [INF]: NP: Session 2: thread 2 event new RPC.
> [INF]: SR: EV ORIGIN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 7 priority 0 for 1 subscribers published.
> [INF]: SR: EV LISTEN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 7 priority 0 processing (remaining 1 subscribers).
> [INF]: NP: Module "o-ran-wg4-features@2023-12-11" was requested.
> [INF]: SR: EV LISTEN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 7 priority 0 success (remaining 0 subscribers).
> [INF]: SR: EV ORIGIN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 7 priority 0 succeeded.
> [INF]: NP: Session 2: thread 0 event new RPC.
> [INF]: SR: EV ORIGIN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 8 priority 0 for 1 subscribers published.
> [INF]: SR: EV LISTEN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 8 priority 0 processing (remaining 1 subscribers).
> [INF]: NP: Module "o-ran-usermgmt@2023-12-11" was requested.
> [INF]: SR: EV LISTEN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 8 priority 0 success (remaining 0 subscribers).
> [INF]: SR: EV ORIGIN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 8 priority 0 succeeded.
> [INF]: NP: Session 2: thread 0 event new RPC.
> [INF]: SR: EV ORIGIN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 9 priority 0 for 1 subscribers published.
> [INF]: SR: EV LISTEN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 9 priority 0 processing (remaining 1 subscribers).
> [INF]: NP: Module "o-ran-supervision@2022-12-05" was requested.
> [INF]: SR: EV LISTEN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 9 priority 0 success (remaining 0 subscribers).
> [INF]: SR: EV ORIGIN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 9 priority 0 succeeded.
> [INF]: NP: Session 2: thread 0 event new RPC.
> [INF]: SR: EV ORIGIN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 10 priority 0 for 1 subscribers published.
> [INF]: SR: EV LISTEN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 10 priority 0 processing (remaining 1 subscribers).
> [INF]: NP: Module "notif-augment@<any>" was requested.
> [INF]: SR: EV LISTEN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 10 priority 0 success (remaining 0 subscribers).
> [INF]: SR: EV ORIGIN: "/ietf-netconf-monitoring:get-schema" "rpc" ID 10 priority 0 succeeded.
> [INF]: NP: Session 2: thread 0 event new RPC.
> [INF]: SR: EV ORIGIN: "/ietf-netconf:get" "rpc" ID 4 priority 0 for 1 subscribers published.
> [INF]: SR: EV LISTEN: "/ietf-netconf:get" "rpc" ID 4 priority 0 processing (remaining 1 subscribers).
> [INF]: SR: EV LISTEN: "/ietf-netconf:get" "rpc" ID 4 priority 0 success (remaining 0 subscribers).
> [INF]: SR: EV ORIGIN: "/ietf-netconf:get" "rpc" ID 4 priority 0 succeeded.
> [INF]: NP: Session 2: thread 1 event new RPC.
> [INF]: SR: EV ORIGIN: "/ietf-netconf:kill-session" "rpc" ID 1 priority 0 for 1 subscribers published.
> [INF]: SR: EV LISTEN: "/ietf-netconf:kill-session" "rpc" ID 1 priority 0 processing (remaining 1 subscribers).
> [INF]: SR: EV LISTEN: "/ietf-netconf:kill-session" "rpc" ID 1 priority 0 success (remaining 0 subscribers).
> [INF]: SR: EV ORIGIN: "/ietf-netconf:kill-session" "rpc" ID 1 priority 0 succeeded.
> [INF]: NP: Session 1: thread 0 event new RPC.
> [INF]: NP: Session 2: thread 0 event session terminated.
> [INF]: SR: EV ORIGIN: "ietf-netconf-notifications" "notif" ID 2 priority 0 for 2 subscribers published.
> [INF]: NP: Generated new event (netconf-session-end).
> [INF]: LN: **Call Home client "default-client" session terminated.**
> [INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4335.
> [INF]: LN: getsockopt() error (Connection refused).
> [INF]: LN: Call Home client "default-client" timeout of 5 seconds expired, reconnecting.
> [INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4335.
> [INF]: LN: getsockopt() error (Connection refused).
> [INF]: LN: Call Home client "default-client" timeout of 5 seconds expired, reconnecting.
> [INF]: LN: Call Home client "default-client" endpoint "default-tls" failed connection attempt limit 3 reached.
> [INF]: LN: Call Home client "default-client" endpoint "default-tls" connecting...
> [INF]: LN: Trying to connect via IPv4 to 127.0.0.1:4335.


netopeer-cli log:
 
> ./netopeer2-cli
> load_config: No saved configuration.
> >listen --tls --host 127.0.0.1 --port 4335 --cert client.crt --key client.key --trusted ca.pem
> cmd_listen: Waiting 60s for a TLS Call Home connection on port 4335...
> >
> >
> >
> > listen --tls --host 127.0.0.1 --port 4335 --cert client.crt --key client.key --trusted ca.pem
> cmd_listen: Already connected to 127.0.0.1.
> > quit
> nc ERROR: Communication socket unexpectedly closed (OpenSSL).
> nc ERROR: Invalid session to write to.
> nc ERROR: Invalid session to read from.
> nc ERROR: Failed to receive a reply to <close-session>.
>

**Comment by michalvasko** [comment]
> Even after the session got terminated the netopeer-cli didn't get any message.

That is expected. You have **killed** the session so it is not a graceful termination and the client is not informed that its session is killed. Even if you wanted to, there is no mechanism to communicate session termination from a NETCONF server to a client, only client can request the termination via `<close-session>` RPC.

**Comment by biswajit84** [comment]
So if my external application(which has netconf connection with Netopeer) sends `close-session` RPC  for ongoing callhome session of other client then whether the respective client(having callhome session) will get any notification  of connection getting closed?

**Comment by michalvasko** [comment]
No, you can send `<close-session>` only for your own NETCONF session. NETCONF does not really support changing other NETCONF sessions than yours (for good reason, I think) and `<kill-session>` is just a last-resort solution in case a session is misbehaving. If you require this feature, you should change your design and prevent requiring this. The NETCONF session needs to manage itself.

**Comment by biswajit84** [comment]
Thanks a lot for clarifying all the doubts.
