### ISSUE TITLE
there is some thing wrong with the xpath when delete all leaf list elements  master branch

### ISSUE THREAD

**Issue by ZhaoGuangYue** [CESNET/Netopeer2#17]
there is some thing wrong with the xpath when delete all leaf list elements 
as an example ,when use the follow xml to delete the data,the xpath is like 
/TestDelLeafList:RootContainer/secondLevelLeafList[.='']
when use this xpath to operator sysrepo data ,it report Error!
`<RootContainer xmlns="urn:ietf:params:xml:ns:yang:fox" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0"> 
<secondLevelLeafList xc:operation="delete"></secondLevelLeafList>
</RootContainer>`

**Comment by rkrejci** [comment]
Solved in #15
