### ISSUE TITLE
I seem unable to make a netconf request to set data in the startup datastore or copy to the startup datastore

### ISSUE THREAD

**Issue by darren-west** [CESNET/Netopeer2#174]
Hi,
I am trying to copy data from Running to Startup or just event set data in Startup and seem unable to do either.
I dont know the exact NETCONF request for copying but I want to achieve something similar to the sysrepo function call 
```
int sr_copy_config(sr_session_ctx_t *session, const char *module_name,
        sr_datastore_t src_datastore, sr_datastore_t dst_datastore);
```
i.e. copy all the config from Running to Startup for module x. 
```
<rpc message-id="101"
	  xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
   <copy-config>
	 <target>
	   <running/>
	 </target>
	 <source>
	   <startup/>
	 </source>
   </copy-config>
 </rpc>
```
This does not work and I do not know how to set the module?

To set the data I have tried:
NETCONF request
```
<edit-config>
	<target>
		<startup/>
	</target>
	<config>
		<example xmlns="http://example.com/example">
			<name>Name 1</name>
		</example>
	</config>
</edit-config>
```

The YANG model is:
YANG model 
```
module example {

  namespace "http://example.com/example";
  prefix example;

  import ietf-yang-types { prefix yang; }

  container example {
	leaf name { type string; }
  }
}
```

many thanks in advance,
Darren

**Comment by jktjkt** [comment]
Hi Darren, have you tried to look at the raw NETCONF protocol messages that are produced by some existing NETCONF client when you attempt to issue a `copy-config`? You can use the `netopeer2-cli` for this purpose.

**Comment by michalvasko** [comment]
Hi Darren,
your RPC message is wrong, it performs `copy-config` from *startup* to *running*, you wanted it the other way around. Also, `edit-config` operation does not support target *startup*, you have to edit some other datastore and then use `copy-config`.

Regards,
Michal
