### ISSUE TITLE
Can't establish connection between netopeer2-cli and netopeer2-server(sysrepo)

### ISSUE THREAD

**Issue by Harish-Shivakumar** [CESNET/Netopeer2#180]
Can't establish connection between netopeer2-cli and netopeer2-server(sysrepod)

when I try to connect I am getting this error in cli
> connect --login root
nc ERROR: Remote host key changed, the connection will be terminated!
nc ERROR: Checking the host key failed.
cmd_connect: Connecting to the localhost:830 as user "root" failed.

on netopeer2-server i get this

netopeer2-server[13997]: Accepted a connection on 0.0.0.0:830.
[2017/09/22 15:07:20.666585, 2] ssh_pki_import_privkey_base64:  Trying to decode privkey passphrase=false
[2017/09/22 15:07:20.667944, 1] ssh_server_connection_callback:  SSH client banner: SSH-2.0-libssh_0.7.0
[2017/09/22 15:07:20.668003, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-libssh_0.7.0
[2017/09/22 15:07:20.746079, 2] ssh_server_curve25519_init:  SSH_MSG_KEX_ECDH_REPLY sent
[2017/09/22 15:07:20.746157, 2] ssh_server_curve25519_init:  SSH_MSG_NEWKEYS sent
[2017/09/22 15:07:20.762434, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
[2017/09/22 15:07:20.762512, 1] ssh_packet_disconnect_callback:  Received SSH_MSG_DISCONNECT: 11:Bye Bye
netopeer2-server[13997]: SSH key exchange error (Received SSH_MSG_DISCONNECT: 11:Bye Bye).

and on sysrepod on got this

[DBG] (sr_cbuff_enqueue:516) Circular buffer enqueue to position=3, current count=1.
[DBG] (rp_msg_process:4130) Threads: active=0/4, 1 requests in queue
[DBG] (cm_delayed_request_cb:290) Delayed request sent to the Request Processor.
[DBG] (rp_worker_thread_execute:3747) Thread id=140361897506560 signaled.
[DBG] (sr_cbuff_dequeue:532) Circular buffer dequeue, new buffer head=4, count=0.
[DBG] (rp_notif_store_cleanup_req_process:2856) Processing notif-store-cleanup request.
[DBG] (np_notification_store_cleanup:1888) Notification store cleanup requested.
[DBG] (np_get_all_notification_files:594) Listing notification directories in '/home/tel/Documents/netconf2/sysrepo/build/repository/data/notifications/'.
[DBG] (np_get_all_notification_files:611) Listing notification directory 'ietf-netconf-notifications'.
[DBG] (np_get_notification_files:548) Listing notification data files for 'ietf-netconf-notifications' modified from '1970-01-01 05:30' to '2017-09-22 14:13'.
[DBG] (sr_cbuff_enqueue:516) Circular buffer enqueue to position=6, current count=1.
[DBG] (np_setup_notif_store_cleanup_timer:707) Notification store cleanup timer set up for 600 seconds.
[DBG] (cm_msg_enqueue_cb:1787) New message enqueued into CM message queue.
[DBG] (sr_cbuff_dequeue:532) Circular buffer dequeue, new buffer head=7, count=0.
[DBG] (rp_worker_thread_execute:3735) Thread id=140361897506560 will wait.
[DBG] (cm_delayed_msg_process:323) Scheduling a delayed request for 600.000000 seconds.

Please help me resolve this.

**Comment by michalvasko** [comment]
Hi,
the SSH key your local server is using for its identification has changed, which could mean (if you were connecting to a remote server) that it is a fake phishing server. For these cases there is the command `knownhosts` in *netopeer2-cli*. You must delete the previously stored server key for it to work, it should be named `localhost` or `127.0.0.1`.

Regards,
Michal
