### ISSUE TITLE
cmake issues in libnetconf2 and Netopeer2-cli

### ISSUE THREAD

**Issue by mohitarora24** [CESNET/Netopeer2#181]
I was trying to install netopeer2-cli on a RHEL 7 machine. And in my home directory since I do not have root access on that particular server.

Usually the steps worked fine for netopeer-cli, but facing issues with netopeer2-cli.

Steps:
1. Install cmake in my home directory (/home/mohit/installs/)
```
wget https://cmake.org/files/v3.9/cmake-3.9.3-Linux-x86_64.sh
cd ~/installs/
sh sources/cmake-3.9.3-Linux-x86_64.sh (first "Y" to accept the license, then "n" to install in current directory)
```

2. Install libyang in the same directory
```
cd ~/installs/sources/
git clone https://github.com/CESNET/libyang.git
cd libyang/
git checkout devel
mkdir build; cd build
~/installs/bin/cmake ../ -DCMAKE_INSTALL_PREFIX:PATH=/home/mohit/installs
make
make install
```

3. Install cmocka in the same directory
```
cd ~/installs/sources/
cd cmocka
git checkout tags/cmocka-1.0.1
mkdir build; cd build
~/installs/bin/cmake ../ -DCMAKE_INSTALL_PREFIX:PATH=/home/mohit/installs
make
make install
```

4. Install libssh in the same directory
```
cd ~/installs/sources/
git clone git://git.libssh.org/projects/libssh.git
cd libssh
mkdir build; cd build
~/installs/bin/cmake ../ -DCMAKE_INSTALL_PREFIX:PATH=/home/mohit/installs
make
make install
```

5. Install libnetconf2 in the same directory
```
cd ~/installs/sources/
git clone https://github.com/CESNET/libnetconf2.git
cd libnetconf2
mkdir build; cd build
~/installs/bin/cmake ../ -DCMAKE_INSTALL_PREFIX:PATH=/home/mohit/installs
make
make install
```
**Issue 1**
`make` fails at linking stage as it could not find `libssh_threads.so` which is there at `/home/mohit/installs/lib/libssh_threads.so`. If libssh library had been installed at standard location it would have found it. Here also it finds libssh.so as its absolute path is hardcoded but not libssh_threads.so

The output of CMake file - `/home/mohit/installs/sources/libnetconf2/build/CMakeFiles/netconf2.dir/link.txt` - has:
`-Wl,-rpath,/home/mohit/installs/lib:/home/mohit/installs/lib64: -lpthread /home/mohit/installs/lib/libssh.so `**`-L/home/mohit/installs/lib/libssh.so -lssh_threads`**` -lcrypt -lssl -lcrypto /home/mohit/installs/lib64/libyang.so`

As you can see library path `-L` is incorrect, it should be just: `-L/home/mohit/installs/lib/` (without the libssh.so). If I fix that then `make` passes successfully.

6. After I'm done installing libnetconf2, now install netopeer2-cli in the same directory
```
cd ~/installs/sources/
git clone https://github.com/CESNET/Netopeer2.git
cd Netopeer2/cli
mkdir build; cd build
~/installs/bin/cmake ../ -DCMAKE_INSTALL_PREFIX:PATH=/home/mohit/installs
make
make install
```

**Issue 2**
Again, `make` fails at linking stage as it could not find `libssh.so` and `libssh_threads.so`
If I add: `-Wl,-rpath,/home/mohit/installs/lib` to `/home/mohit/installs/sources/Netopeer2/cli/build/CMakeFiles/netopeer2-cli.dir/link.txt`, it works fine.

Note: I'm still unsure of the differences between using `-L` and using `-Wl,-rpath,` :)

**Issue 3**
Now, after all is done and netopeer2-cli is installed. And I try to run it:
```
~$ ~/installs/bin/netopeer2-cli
/home/mohit/installs/bin/netopeer2-cli: error while loading shared libraries: libyang.so.0.13: cannot open shared object file: No such file or directory
```
At this time:
```
~$ ldd ~/installs/bin/netopeer2-cli
	linux-vdso.so.1 =>  (0x00007ffce510d000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f4d00d1c000)
	libyang.so.0.13 => not found
	libnetconf2.so.0.9 => not found
	libssl.so.10 => /lib64/libssl.so.10 (0x00007f4d00aae000)
	libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f4d006c5000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f4d00304000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4d00f7a000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f4d000b8000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f4cffdd2000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f4cffbce000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f4cff99c000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f4cff797000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f4cff581000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f4cff372000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f4cff16d000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f4cfef53000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f4cfed2d000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f4cfeacc000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f4cfe8a7000)
```
If I do `export LD_LIBRARY_PATH=LD_LIBRARY_PATH:$HOME/installs/lib64` then it runs fine.

---

Do not know how to fix these issues in CMakeFiles by myself. But if they're fixed it would be great. Many thanks.

**Comment by michalvasko** [comment]
Hi,
it is not really possible to make CMake build files as generic as you would need them to be. Still, `libssh` linking was not performed in the best way (mostly due to faulty `FindLibSSH` CMake module not written by us) so I tried to enhance it. Now the compilation will hopefully work without any additional commands. Still, you should compile all the applications having CMake variable `CMAKE_LIBRARY_PATH` defined as `/home/mohit/installs/lib`, which is how you specify a custom library path to CMake.

But, executing the compiled binaries is another matter, I believe, for then also `ldd` must find all your libraries. Normally, you would add the path into `ld.so.conf` or `ld.so.conf.d` and then check that a library is found with `ldconfig -p` but you can do neither without root access. So, environment variable `LD_LIBRARY_PATH` is probably your best bet here.

Regards,
Michal
