### ISSUE TITLE
Netopeer2-server crashed with error message "Illegal instruction (core dumped)"

### ISSUE THREAD

**Issue by swathins079** [CESNET/Netopeer2#183]
Hi,

The crash happened after installing the yang modules - iana-if-type.yang, ietf-ip.yang and ietf-interfaces.yang. The following commands were used to install those modules.

Commands:
-------------------------------------------------------------------------------------------
sysrepoctl --install --yang=/tmp/iana-if-type.yang --permissions=666
sysrepoctl --install --yang=/tmp/ietf-ip.yang --permissions=666
sysrepoctl --install --yang=/tmp/ietf-interfaces.yang --permissions=666

Log:
-------------------------------------------------------------------------------------------
netopeer2-server[31233]: Loading added schema "ietf-netconf-notifications@2012-02-06" from sysrepo.
netopeer2-server[31233]: Reading module "ietf-netconf-notifications".
netopeer2-server[31233]: Module "ietf-netconf-notifications" already in context.
netopeer2-server[31233]: Module "ietf-netconf-notifications" successfully parsed.
netopeer2-server[31233]: Generated new event (netconf-capability-change).
netopeer2-server[31233]: Resolving unresolved data nodes and their constraints...
netopeer2-server[31233]: All data nodes and constraints resolved.
netopeer2-server[31233]: Generated new internal event (yang-library-change).
netopeer2-server[31233]: Loading added schema "nc-notifications@2008-07-14" from sysrepo.
netopeer2-server[31233]: Reading module "nc-notifications".
netopeer2-server[31233]: Module "nc-notifications" already in context.
netopeer2-server[31233]: Module "nc-notifications" successfully parsed.
netopeer2-server[31233]: Generated new event (netconf-capability-change).
netopeer2-server[31233]: Resolving unresolved data nodes and their constraints...
netopeer2-server[31233]: All data nodes and constraints resolved.
netopeer2-server[31233]: Generated new internal event (yang-library-change).
netopeer2-server[31233]: Loading added schema "notifications@2008-07-14" from sysrepo.
netopeer2-server[31233]: Reading module "notifications".
netopeer2-server[31233]: Module "notifications" already in context.
netopeer2-server[31233]: Module "notifications" successfully parsed.
netopeer2-server[31233]: Generated new event (netconf-capability-change).
netopeer2-server[31233]: Resolving unresolved data nodes and their constraints...
netopeer2-server[31233]: All data nodes and constraints resolved.
netopeer2-server[31233]: Generated new internal event (yang-library-change).
netopeer2-server[31233]: Loading added schema "iana-if-type@2014-05-08" from sysrepo.
netopeer2-server[31233]: Reading module "iana-if-type".
netopeer2-server[31233]: Error by processing of the get-schema request (session id=1564899904): Requested schema model is not known.
netopeer2-server[31233]: Error by processing of the request.
netopeer2-server[31233]: Unable to get ietf-interfaces module from sysrepo (Requested schema model is not known).
netopeer2-server[31233]: Importing "ietf-interfaces" module into "iana-if-type" failed.
netopeer2-server[31233]: Module "iana-if-type" parsing failed.
netopeer2-server[31233]: Unable to parse installed module iana-if-type@2014-05-08 from sysrepo (Operation succeeded), schema won't be available.
netopeer2-server[31233]: Resolving unresolved data nodes and their constraints...
netopeer2-server[31233]: All data nodes and constraints resolved.
netopeer2-server[31233]: Generated new internal event (yang-library-change).
Illegal instruction (core dumped)

Deleting the modules don't have an impact on the netopeer-server.

Regards,
Swathin

**Comment by jktjkt** [comment]
How did you build the binaries, and what architecture and CPUs and HW are you building and running this on?

**Comment by swathins079** [comment]
Hi,

I am using the following commands to build the netopeer2-server.

```
mkdir build
cd build && \
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE="debug" .. && \
make -j2 && \
sudo make install
```
It is running on a ubuntu 17.04 based virtual machine. The output of "uname -a" is:

> Linux netopeer2 4.10.0-33-generic #37-Ubuntu SMP Fri Aug 11 10:55:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Thanks,
Swathin

**Comment by michalvasko** [comment]
Hi Swathin,
my guess is that something went wrong after `ietf-interfaces` model failed to be retrieved from *sysrepo*. However, it should not have failed in the first place (because it is imported by `iana-if-type`) and even if it did, `iana-if-type` model should have been thrown away but based on the output I think it was not.

I will take a look at the problem of the model not being disposed of, but `ietf-interfaces` fails to load from *sysrepo* because of some invalid configuration, most likely. You can post the output of `sysrepoctl -l`, it may give some hints.

Regards,
Michal

**Comment by swathins079** [comment]
Hi,

Please find below the output of the sysrepoctl -l.

Sysrepo schema directory: /etc/sysrepo/yang/
Sysrepo data directory:   /etc/sysrepo/data/
(Do not alter contents of these directories manually)

Module Name                   | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
ietf-netconf-notifications    | 2012-02-06 | Installed   | root:root           | 666         |                               |
ietf-netconf                  | 2011-06-01 | Imported    |                     |             |                               |
ietf-netconf-acm              | 2012-02-22 | Imported    |                     |             |                               |
nc-notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
notifications                 | 2008-07-14 | Installed   | root:root           | 666         |                               |

Regards,
Swathin

**Comment by michalvasko** [comment]
Hi Swathin,
it seems to me you have 2 *sysrepo* installations which are interfering with each other, there is no`iana-if-type` in your output at all. So, my suggestion is to properly cleanup all sysrepo files and then install it again.

Regards,
Michal

**Comment by swathins079** [comment]
Hi Michal,

The error happens due to the import statement in the iana-if-type.yang.

```
    import ietf-interfaces {
      prefix if;
    }
```
I think the order of installation matters. The ietf-interfaces.yang should be installed before installing iana-if-type.yang. I was trying to install iana-if-type.yang first and ietf-interfaces.yang at last.

Thanks,
Swathin

**Comment by swathins079** [comment]
Hi Michal,

I am trying to install the iana-if-type after starting the sysrepod and netopeer2-server.

As per my investigation, the libyang is trying to install the dependent modules as well. If the library is not present in the directory, it will throw the error.

In our case, it is trying to install ietf-interfaces.yang while installing iana-if-type.yang. I can also see that the libyang is looking for the dependent modules in the same directory.

Regards,
Swathin

**Comment by michalvasko** [comment]
Hi Swathin,
even though I have not tried it yet, I believe I understand what the problem may be and I am going to look at it, but I am not able to do it right know. When I finish the current work I will take a look, please be patient. If an issue is left opened with the last reply being from the person that opened the issue, this is most likely the situation.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
I have looked at the issue. It did not work correctly, but I encountered different problems than you, probably because I have used the `devel-server` branch server. You have used `master`, right? It should work now in `devel-server`, you are free to pick that version.

Regards,
Michal

**Comment by swathins079** [comment]
Thanks Michal, I will switch to the branch devel-server. 

Regards,
Swathin

**Comment by swathins079** [comment]
Thanks Michal, I didn't encounter any crash after installing a new model.

Regards,
Swathin
