### ISSUE TITLE
Generic notification from netopeer2 server to client

### ISSUE THREAD

**Issue by dileepravindran** [CESNET/Netopeer2#184]
Hi , 

 I was able to successfully install  netopeer2  server and client and establish a session .

I'm trying to send a generic notification from netopeer2 server to client . 

Creation of subscription was successful from netopeer2-cli to netopeer2-server using 'subscribe'  on  netopeer2-cli prompt 

can you provide me a sample code just as https://github.com/CESNET/libnetconf/issues/170#issuecomment-194834454

to send notifications to clients

Thanks
Dileep

**Comment by michalvasko** [comment]
Hi Dileep,
there is no sample code of this, the closest is [this page](http://www.sysrepo.org/static/doc/html/subscribtions.html) even though it talks about data subscriptions, not notification subscriptions. Howeveer, you will want to do something similar. I suppose you already have a YANG model with the notification definition. You need to install it into *sysrepo*. Then you must write either a plugin or a standalone daemon that will handle creating this notification. Simply, by connecting to sysrepo and then calling `sr_event_notif_send`. If, at this time, you will have a NETCONF client connected to *netopeer2-server* and subscribed to notifications, it will receive it.

I am probably not too detailed but you must figure some things on your own, understand how *sysrepo* works in general. You can also take a look at example code in `sysrepo/examples`.

Regards,
Michal

**Comment by dileepravindran** [comment]
Thanks Michal!
    
It worked.  I had to connect my daemon to sysrepo , load the schemas from sysrepo and then use  sr_event_notif_send() to send a NETCONF notification.
