### ISSUE TITLE
'get-config' operation got default nodes (expected not)

### ISSUE THREAD

**Issue by fanchanghu** [CESNET/Netopeer2#189]
Hi,
'get-config' operation will get some empty container nodes (they should be default nodes) even if user does not configure any data explicitly. Following steps can reproduce this issue.
1, intall following module to sysrepo:
```
module ModuleA {
	namespace "urn:a";
	prefix a;
	container MO1 {
		container MO2 {
			leaf f1{type string; default "abc";}
		}
	}
}
```
2, executing `get-config --source running --defaults explicit` in `netopeer2-cli` will create following output(expect empty):
```
<MO1 xmlns="urn:a">
</MO1>
```

**Comment by michalvasko** [comment]
Hi,
it should work now in the `devel-server` branch, you need to update *libyang* as well.

Regards,
Michal

**Comment by fanchanghu** [comment]
Hi,
I have got the latest version of `libyang` and `netopeer2`, and it works now, thanks.
