### ISSUE TITLE
ssh call-home not working with error: Error by processing of the get changes request (session id=953131957): Get changes call can be issued only on notification session.

### ISSUE THREAD

**Issue by darshana-jk** [CESNET/Netopeer2#191]
How to reproduce:
Used the latest git repos of libyang, libnetconf2, sysrepo & Netopeer2.
1. Build all 4 packages.
2. start sysrepod 
`sysrepod -d -l4'
3. start 
`sysrepo-plugind -d`
4. start Netopeer2-server 
`netopeer2-server -d -v 2`
The last output from Netopeer2-server:
```
netopeer2-server[29845]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_ssh_listen_endpt']/name" created.
netopeer2-server[29845]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_ssh_listen_endpt']/ssh" created.
netopeer2-server[29845]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_ssh_listen_endpt']/ssh/address" created.
netopeer2-server[29845]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_ssh_listen_endpt']/ssh/port" created.
netopeer2-server[29845]: Listening on 0.0.0.0:830 for SSH connections.
netopeer2-server[29845]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_ssh_listen_endpt']/ssh/host-keys" created.
netopeer2-server[29845]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_ssh_listen_endpt']/ssh/host-keys/host-key[name='test_ssh_listen_key']/name" created.
netopeer2-server[29845]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_ssh_listen_endpt']/ssh/host-keys/host-key[name='test_ssh_listen_key']/public-key" created.
```
Looks like the server initialised successfully.

5. Try to merge the call-home entries to the `ietf-netconf-server` running DS:

```sysrepocfg --merge=Netopeer2/server/configuration/ssh_callhome.xml --format=xml  --datastore=running ietf-netconf-server -l 3```
```The new configuration was successfully applied.```

**However: from the Netopeer2-server**
```
netopeer2-server[29845]: DEBUG: Calling sr_get_changes_iter: xpath=/ietf-netconf-server:netconf-server//*
netopeer2-server[29845]: (cl_request_process:562) Error by processing of the get changes request (session id=953131957): Get changes call can be issued only on notification session.
netopeer2-server[29845]: (sr_get_changes_iter:2683) Sending get_changes request failed '/ietf-netconf-server:netconf-server//*'
netopeer2-server[29845]: DEBUG: sysrepo returned: Operation not supported
netopeer2-server[29845]: np2srv_sr_get_changes_iter failed (sysrepo: Operation not supported).

```

Looks like the cause is that we are using the `np_sess->srs` to do the sr_get_changes_iter() and sysrepo complains about it. 

```module_change_cb(sr_session_ctx_t *session, const char *UNUSED(module_name), sr_notif_event_t event,  void *private_ctx)
```
The content is different between the `sr_session_ctx_t *session` (in the previous versions we used this in sr_get_changes_iter)  passed to the callback and the session context structure contained in the `private_ctx`. 
Debug info:
```
(gdb) p *session
$2 = {conn_ctx = 0x7ffff00022d0, id = 501712891, lock = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}, last_error = SR_ERR_OK, error_info = 0x0, error_info_size = 0, error_cnt = 0, notif_session = true, commit_id = 1240655229}
(gdb) p np_sess->srs
$3 = (sr_session_ctx_t *) 0x639bf0
(gdb) p *np_sess->srs
$4 = {conn_ctx = 0x637820, id = 1399706074, lock = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}, last_error = SR_ERR_OK, error_info = 0x0, error_info_size = 0, error_cnt = 0, notif_session = false, commit_id = 0}
```

Git versions:

commit 99815913fe9a05f65953a1e34bbb2153bd46f7ef
Author: Michal Vasko <mvasko@cesnet.cz>
Date:   Wed Nov 15 15:15:51 2017 +0100

    VERSION bump to version 0.14.44
Git repo libnetconf2
commit 262067e50f03aa2effdbf203842679c9cf3838c3
Author: Radek Krejci <rkrejci@cesnet.cz>
Date:   Wed Nov 8 12:51:10 2017 +0100

    VERSION bump version to 0.10.16
Git repo sysrepo
commit a617b0f53d582a953febc6a1a06eabf6223ee500
Merge: c5b731b e47f8ef
Author: Michal Vasko <mvasko@cesnet.cz>
Date:   Wed Nov 15 14:46:54 2017 +0100

    Merge pull request #987 from jktjkt/fix-memleak
    
    BUGFIX sysrepoctl memory leak
Git repo Netopeer2
commit b0ccf3c380ce5edbacae7c70aca96717f15541c4
Author: Michal Vasko <mvasko@cesnet.cz>
Date:   Thu Nov 2 13:24:44 2017 +0100

    server MAINTENANCE unrecognized gcc7 fallthrough fixed

**Comment by michalvasko** [comment]
Hi,
you are right, no reason not to use the session provided by *sysrepo* anyway. Should work now.

Regards,
Michal

**Comment by darshana-jk** [comment]
Thanks Michal,
I have tested and its fixed now.
