### ISSUE TITLE
Failed to get "/ietf-keystore:keystore/private-keys/private-key/certificate-chains/certificate-chain[name='test_server_cert']/certificate[1]" from sysrepo (Item not found).

### ISSUE THREAD

**Issue by dileepravindran** [CESNET/Netopeer2#197]
Hi , 
with reference to https://github.com/CESNET/Netopeer2/issues/193 , i was able to make server listen on TLS  0.0.0.0:6513 . configured with "test_server_cert" . while trying to connect the client using connect --tls , connection establishment fails . below i have mentioned client and server log 

Client log
nc ERROR: SSL_connect failed (Connection reset by peer).
cmd_connect: Connecting to the localhost:6513 failed.

Server Log
netopeer2-server[27473]: Module "ietf-netconf-with-defaults@2011-06-01" successfully parsed as implemented.
netopeer2-server[27473]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_ssh_listen_endpt']/name" created.
netopeer2-server[27473]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_ssh_listen_endpt']/ssh" created.
netopeer2-server[27473]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_ssh_listen_endpt']/ssh/address" created.
netopeer2-server[27473]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_ssh_listen_endpt']/ssh/port" created.
netopeer2-server[27473]: Listening on 0.0.0.0:830 for SSH connections.
netopeer2-server[27473]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_ssh_listen_endpt']/ssh/host-keys" created.
netopeer2-server[27473]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_ssh_listen_endpt']/ssh/host-keys/host-key[name='test_ssh_listen_key']/name" created.
netopeer2-server[27473]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_ssh_listen_endpt']/ssh/host-keys/host-key[name='test_ssh_listen_key']/public-key" created.
netopeer2-server[27473]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/name" created.
netopeer2-server[27473]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls" created.
netopeer2-server[27473]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/address" created.
netopeer2-server[27473]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/port" created.
netopeer2-server[27473]: Listening on 0.0.0.0:6513 for TLS connections.
netopeer2-server[27473]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/certificates" created.
netopeer2-server[27473]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/certificates/certificate[name='test_server_cert']/name" created.
netopeer2-server[27473]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth" created.
netopeer2-server[27473]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth/trusted-ca-certs" created.
netopeer2-server[27473]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth/cert-maps" created.
netopeer2-server[27473]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth/cert-maps/cert-to-name[id='1']/id" created.
netopeer2-server[27473]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth/cert-maps/cert-to-name[id='1']/fingerprint" created.
netopeer2-server[27473]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth/cert-maps/cert-to-name[id='1']/map-type" created.
netopeer2-server[27473]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth/cert-maps/cert-to-name[id='1']/name" created.
netopeer2-server[27473]: Accepted a connection on 0.0.0.0:6513.
netopeer2-server[27473]: Failed to get "/ietf-keystore:keystore/private-keys/private-key/certificate-chains/certificate-chain[name='test_server_cert']/certificate[1]" from sysrepo (Item not found).
netopeer2-server[27473]: Server certificate callback failed.
netopeer2-server[27473]: nc_session_is_connected: internal error (/home/user/libnetconf2/src/io.c:554).
netopeer2-server[27473]: nc_session_free: internal error (/home/user/libnetconf2/src/session.c:665).

**Comment by michalvasko** [comment]
Hi,
do you have *sysrepo-plugind* with `keystored` running? As is written in the README?

Regards,
Michal

**Comment by dileepravindran** [comment]
sysrepo-plugind  daemon had got killed . re installed sysrepo .
started daemon in the order  sysrepod , sysrepo-plugind  and then netopeer2-server.

now i get this error log on server 

netopeer2-server[27870]: Loading the server private key failed (No such file or directory).
netopeer2-server[27870]: nc_session_is_connected: internal error (/home/user/libnetconf2/src/io.c:554).
netopeer2-server[27870]: nc_session_free: internal error (/home/user/libnetconf2/src/session.c:665).

**Comment by michalvasko** [comment]
Look, you need to learn to solve some basic problem on your own. The whole installation you currently have is most likely a mess. Properly remove all the applications (most importantly the *sysrepo* repository, `sysrepoctl -l` prints the path to it) and then reinstall all that is needed for configuration as written in the README. It will work afterwards.

Regards,
Michal

**Comment by dileepravindran** [comment]
this is what sysrepoctl -l show


Module Name                   | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
example-module                |            | Installed   | root:root           | 666         |                               |
test-module                   |            | Installed   | root:root           | 666         |                               |
referenced-data               |            | Installed   | root:root           | 666         |                               |
small-module                  |            | Installed   | root:root           | 666         |                               |
info-module                   |            | Installed   |                     |             |                               |
module-a                      | 2016-02-10 | Installed   | root:root           | 666         |  sub-a-one sub-a-two          |
module-b                      | 2016-02-05 | Installed   | root:root           | 666         |                               |
module-a                      | 2016-02-02 | Imported    |                     |             |  sub-a-one sub-a-two          |
ietf-interfaces               | 2014-05-08 | Installed   | root:root           | 666         |                               |
iana-if-type                  | 2014-05-08 | Installed   |                     |             |                               |
ietf-ip                       | 2014-06-16 | Installed   |                     |             |                               |
state-module                  | 2016-07-01 | Installed   | root:root           | 666         |                               |
top-level-mandatory           |            | Installed   | root:root           | 666         |                               |
cross-module                  |            | Installed   | root:root           | 666         |                               |
turing-machine                | 2013-12-27 | Installed   | root:root           | 666         |                               |
ietf-netconf-notifications    | 2012-02-06 | Installed   | root:root           | 666         |                               |
ietf-netconf                  | 2011-06-01 | Imported    |                     |             |                               |
ietf-netconf-acm              | 2012-02-22 | Imported    |                     |             |                               |
nc-notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
notifications                 | 2008-07-14 | Installed   | root:root           | 666         |                               |
servers                       |            | Installed   | root:root           | 666         |                               |
swig-test-cpp-changes         | 2017-03-09 | Installed   | root:root           | 666         |                               |
swig-test-cpp-operations      | 2017-03-09 | Installed   | root:root           | 666         |                               |
ietf-x509-cert-to-name        | 2014-12-10 | Installed   |                     |             |                               |
ietf-keystore                 | 2016-10-31 | Installed   | root:root           | 600         |                               |
ietf-netconf-server           | 2016-11-02 | Installed   | root:root           | 600         |                               | listen ssh-listen tls-listen call-home ssh-call-home tls-call-home
ietf-ssh-server               | 2016-11-02 | Imported    |                     |             |                               |
ietf-tls-server               | 2016-11-02 | Imported    |                     |             |                               |
ietf-system                   | 2014-08-06 | Installed   | root:root           | 600         |                               | authentication local-users
iana-crypt-hash               | 2014-08-06 | Imported    |                     |             |                               |

**Comment by michalvasko** [comment]
I meant the very first two lines that you have either skipped when copying the content here or you have some really old version of *sysrepoctl*. There you see the path to the repository.

Regards,
Michal

**Comment by dileepravindran** [comment]
okay . i was able to get it working after removing and installing sysrepo . 
 
i used user-rpc  load_server_key.xml on netopeer2-cli command prompt and worked fine 

i also tried the sysrepocfg command "sysrepocfg --merge=load_server_key.xml --format=xml --datastore=startup ietf-keystore" which threw up  the error

[ERR] (srcfg_import_datastore:801) Unable to parse the input data: Unknown element "action". ()
Errors were encountered during importing. Cancelling the operation.

i'm i using the right sysrepocfg for loading server key?

**Comment by michalvasko** [comment]
Hi,
`load_server_key.xml` includes the content of an action (almost similar to an RPC) so you must send that using `user-rpc` command, it is not a configuration snippet. But again, you would have known if you were familiar with YANG 1.1 to at least some extent.

Regards,
Michal

**Comment by dileepravindran** [comment]
okay. this means we need to use  netopeer2-cli to configure  netopeer2-server for enabling TLS?

**Comment by michalvasko** [comment]
More precisely, it means you must invoke the action using NETCONF so you need to connect to *netopeer2-server* using a NETCONF client. Any should work, *netopeer2-cli* will, too.

Regards,
Michal

**Comment by shubhtrix** [comment]
Hi @dileepravindran 

Have you got it working over TLS. I mean are you able to get any data through netopeer-cli over TLS. I'm also stuck somewhere while establishing the connection between server & client if you can help me out with it. For details you can have a look at #289 . 

Regards,
Shubham

**Comment by dileepravindran** [comment]
Hello Shubnam, 
    you should have these installed , ietf-keystore.yang ,ietf-netconf-server.yang,ietf-system.yang,ietf-x509-cert-to-name.yang.
you can check using the command sysrepoctl -l and enable these features
sysrepoctl --module ietf-netconf-server --feature-enable listen
        sysrepoctl --module ietf-netconf-server --feature-enable ssh-listen
        sysrepoctl --module ietf-netconf-server --feature-enable tls-listen
        sysrepoctl --module ietf-netconf-server --feature-enable call-home
        sysrepoctl --module ietf-netconf-server --feature-enable tls-call-home
        sysrepoctl --module ietf-netconf-server --feature-enable ssh-call-home

After all the above are enabled. use sysrepocfg to load ietf-keystore 
example
 sysrepocfg --merge=/path/to/stock_key_config.xml --format=xml --datastore=startup ietf-keystore
 sysrepocfg --merge=/path/to/stock_config.xml --format=xml --datastore=startup ietf-netconf-server
        sysrepocfg --merge=/path/to/load_server_certs.xml --format=xml --datastore=startup ietf-keystore
        sysrepocfg --merge=/path/to/tls_listen.xml --format=xml --datastore=startup ietf-netconf-server


then you start
sysrepod
 sysrepo-plugind
  netopeer2-server

**Comment by shubhtrix** [comment]
Ya Hi!!
Glad to hear from you...
This is th sysrepoctl -l output 

`root@SHUBH:/home/shubham/WORK# sysrepoctl -l 
Sysrepo schema directory: /etc/sysrepo/yang/
Sysrepo data directory:   /etc/sysrepo/data/
(Do not alter contents of these directories manually)

Module Name                | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
ietf-netconf-notifications | 2012-02-06 | Installed   | root:root           | 666         |                               |
ietf-netconf               | 2011-06-01 | Installed   | root:root           | 666         |                               | writable-running candidate rollback-on-error validate startup xpath
ietf-netconf-acm           | 2012-02-22 | Imported    |                     |             |                               |
nc-notifications           | 2008-07-14 | Installed   | root:root           | 666         |                               |
notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
turing-machine             | 2013-12-27 | Installed   | root:root           | 666         |                               |
iana-if-type               | 2014-05-08 | Installed   |                     |             |                               |
ietf-interfaces            | 2014-05-08 | Installed   | root:root           | 666         |                               |
ietf-ip                    | 2014-06-16 | Installed   |                     |             |                               |
ietf-netconf-with-defaults | 2011-06-01 | Installed   |                     |             |                               |
ietf-netconf-monitoring    | 2010-10-04 | Installed   | root:root           | 666         |                               |
ietf-x509-cert-to-name     | 2014-12-10 | Installed   |                     |             |                               |
ietf-keystore              | 2016-10-31 | Installed   | root:root           | 600         |                               |
ietf-netconf-server        | 2016-11-02 | Installed   | root:root           | 600         |                               | listen ssh-listen tls-listen call-home ssh-call-home tls-call-home
ietf-ssh-server            | 2016-11-02 | Imported    |                     |             |                               |
ietf-tls-server            | 2016-11-02 | Imported    |                     |             |                               |
ietf-system                | 2014-08-06 | Installed   | root:root           | 600         |                               | authentication local-users
iana-crypt-hash            | 2014-08-06 | Imported    |                     |             |                               |
ietf-yang-library          | 2018-01-17 | Installed   | root:root           | 666         |                               |

`
2.) Second part is something like this: 
`root@SHUBH:/home/shubham/WORK# sysrepoctl --module ietf-netconf-server --feature-enable listen 
Enabling feature 'listen' in the module 'ietf-netconf-server'.
[ERR] libyang error: Node already exists.
Operation completed successfully.
root@SHUBH:/home/shubham/WORK# sysrepoctl --module ietf-netconf-server --feature-enable ssh-listen 
Enabling feature 'ssh-listen' in the module 'ietf-netconf-server'.
[ERR] libyang error: Node already exists.
Operation completed successfully.
root@SHUBH:/home/shubham/WORK# sysrepoctl --module ietf-netconf-server --feature-enable tls-listen
Enabling feature 'tls-listen' in the module 'ietf-netconf-server'.
[ERR] libyang error: Node already exists.
Operation completed successfully.
root@SHUBH:/home/shubham/WORK# sysrepoctl --module ietf-netconf-server --feature-enable call-home 
Enabling feature 'call-home' in the module 'ietf-netconf-server'.
[ERR] libyang error: Node already exists.
Operation completed successfully.
root@SHUBH:/home/shubham/WORK# sysrepoctl --module ietf-netconf-server --feature-enable tls-call-home 
Enabling feature 'tls-call-home' in the module 'ietf-netconf-server'.
[ERR] libyang error: Node already exists.
Operation completed successfully.
root@SHUBH:/home/shubham/WORK# sysrepoctl --module ietf-netconf-server --feature-enable ssh-call-home 
Enabling feature 'ssh-call-home' in the module 'ietf-netconf-server'.
[ERR] libyang error: Node already exists.
Operation completed successfully.
root@SHUBH:/home/shubham/WORK# 
`
3.) All sysrepocfg commands successfully applied :+1: 

4.) sysrepod started then sysrepo-plugind started 
and finally 

**UP-TO THIS POINT ALL SEEMS GOOD**
5.) NOW when trying to connect through netopeer2-cli
`root@SHUBH:/home/shubham/WORK/01_GIT/REST_CONF/02_C_BASED_2/Netopeer2/server/configuration/tls# netopeer2-cli 
> cert add /home/shubham/WORK/01_GIT/REST_CONF/02_C_BASED_2/Netopeer2/server/configuration/tls/ca.pem 
> Doing /root/.netopeer2-cli/certs

> ASED_2/Netopeer2/server/configuration/tls/client.crt /home/shubham/WORK/01_GIT/REST_CONF/02_C_BASED_2/Netopeer2/server/configuration/tls/client.key 
> connect --tls 
nc ERROR: SSL_connect failed (Connection reset by peer).
cmd_connect: Connecting to the localhost:6513 failed.
> 
> 
> 
`

**Now what should I do to communicate through netopeer2-cil**

**Comment by shubhtrix** [comment]
@dileepravindran  so if the previous comment seems a bit garbage kind of thing the final out put while connecting through Netopeer2-cli is prompting this:

`
> cert add /home/shubham/WORK/01_GIT/REST_CONF/02_C_BASED_2/Netopeer2/server/configuration/tls/ca.pem 
> Doing /root/.netopeer2-cli/certs

> ASED_2/Netopeer2/server/configuration/tls/client.crt /home/shubham/WORK/01_GIT/REST_CONF/02_C_BASED_2/Netopeer2/server/configuration/tls/client.key 
> connect --tls 
nc ERROR: SSL_connect failed (Connection reset by peer).
cmd_connect: Connecting to the localhost:6513 failed.
> 
`

**Comment by dileepravindran** [comment]
once you start netopeer2-server .. is it listening on tls port?

**Comment by dileepravindran** [comment]
once you finish u need to load the load_server_key.xml through rpc command 
netopeer2-cli
connect --host 127.0.0.1 --login $ssl_name
user-rpc --content /path/to/load_server_key.xml

to load the server certs

**Comment by shubhtrix** [comment]
@dileepravindran  hello!!
YOUR QUESTION : **once you start netopeer2-server .. is it listening on tls port?once you start netopeer2-server .. is it listening on tls port?**

`VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/name" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/ssh" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/ssh/address" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/ssh/port" created.
VERBOSE: Listening on 0.0.0.0:830 for SSH connections.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/ssh/host-keys" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/ssh/host-keys/host-key[name='imported SSH key']/name" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/ssh/host-keys/host-key[name='imported SSH key']/public-key" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/name" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/address" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/port" created.
VERBOSE: Listening on 0.0.0.0:6513 for TLS connections.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/certificates" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/certificates/certificate[name='test_server_cert']/name" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth/trusted-ca-certs" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth/cert-maps" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth/cert-maps/cert-to-name[id='1']/id" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth/cert-maps/cert-to-name[id='1']/fingerprint" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth/cert-maps/cert-to-name[id='1']/map-type" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth/cert-maps/cert-to-name[id='1']/name" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/name" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/ssh" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/ssh/address" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/ssh/port" created.
VERBOSE: Listening on 0.0.0.0:830 for SSH connections.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/ssh/host-keys" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/ssh/host-keys/host-key[name='imported SSH key']/name" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/ssh/host-keys/host-key[name='imported SSH key']/public-key" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/name" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/address" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/port" created.
VERBOSE: Listening on 0.0.0.0:6513 for TLS connections.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/certificates" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/certificates/certificate[name='test_server_cert']/name" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth/trusted-ca-certs" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth/cert-maps" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth/cert-maps/cert-to-name[id='1']/id" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth/cert-maps/cert-to-name[id='1']/fingerprint" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth/cert-maps/cert-to-name[id='1']/map-type" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth/cert-maps/cert-to-name[id='1']/name" created.
`

check few debug logs from the bottom.

**Comment by shubhtrix** [comment]
Yes It is listening on TLS 0.0.0.0:6513 as you can see in the above debug logs of netopeer2.
But  using `connect --host 127.0.0.1 --login $ssl_name` this command I'm able to connect through SSH not SSL connection......and the next command `user-rpc --content /path/to/load_server_key.xml` giving me something like this....

> 
> user-rpc --content /home/shubham/WORK/01_GIT/REST_CONF/02_C_BASED_2/Netopeer2/server/configuration/load_server_key.xml 
ly ERROR: Unknown element "keystore". (/)
cli_send_recv: Failed to send the RPC.
> 
>

**Comment by dileepravindran** [comment]
ietf-keystore permission is at 600, change it to 666
 sysrepoctl --install --yang=/path/to/ietf-keystore.yang --owner=$ssl_name:$ssl_name --permissions=666
connect through ssh first and load the load_server_key.xml file which will have the private key 
then connect through TLS from netopeer-cli

**Comment by shubhtrix** [comment]
On ssh connection netopeer2-cli 
 
> connect --host 127.0.0.1 --login shubham
Interactive SSH Authentication
Type your password:
Password: 
nc ERROR: No yang-library modules information for session 1.
ly ERROR: Invalid arguments (lys_features_change()).
> 
> 
> connect --host 127.0.0.1 --login shubham
Interactive SSH Authentication
Type your password:
Password: 
nc ERROR: No yang-library modules information for session 1.
ly ERROR: Invalid arguments (lys_features_change()).
> 
 **Is this the problem???**

**Comment by dileepravindran** [comment]
did u change the permission ?, can you paste sysrepoctl -l output

**Comment by shubhtrix** [comment]
**sysrepoctl --install --yang=/path/to/ietf-keystore.yang --owner=$ssl_name:$ssl_name --permissions=666**
output : 
`
Module Name                | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
ietf-netconf-notifications | 2012-02-06 | Installed   | root:root           | 666         |                               |
ietf-netconf               | 2011-06-01 | Installed   | root:root           | 666         |                               | writable-running candidate rollback-on-error validate startup xpath
ietf-netconf-acm           | 2012-02-22 | Imported    |                     |             |                               |
nc-notifications           | 2008-07-14 | Installed   | root:root           | 666         |                               |
notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
turing-machine             | 2013-12-27 | Installed   | root:root           | 666         |                               |
iana-if-type               | 2014-05-08 | Installed   |                     |             |                               |
ietf-interfaces            | 2014-05-08 | Installed   | root:root           | 666         |                               |
ietf-ip                    | 2014-06-16 | Installed   |                     |             |                               |
ietf-netconf-with-defaults | 2011-06-01 | Installed   |                     |             |                               |
ietf-netconf-monitoring    | 2010-10-04 | Installed   | root:root           | 666         |                               |
ietf-x509-cert-to-name     | 2014-12-10 | Installed   |                     |             |                               |
ietf-keystore              | 2016-10-31 | Installed   | root:root           | 666         |                               |
ietf-netconf-server        | 2016-11-02 | Installed   | root:root           | 666         |                               | listen ssh-listen tls-listen call-home ssh-call-home tls-call-home
ietf-ssh-server            | 2016-11-02 | Imported    |                     |             |                               |
ietf-tls-server            | 2016-11-02 | Imported    |                     |             |                               |
ietf-system                | 2014-08-06 | Installed   | root:root           | 666         |                               | authentication local-users
iana-crypt-hash            | 2014-08-06 | Imported    |                     |             |                               |
ietf-yang-library          | 2018-01-17 | Installed   | root:root           | 666         |                               |
`
And still it is there: 
 
> 
> user-rpc --content /home/shubham/WORK/01_GIT/REST_CONF/02_C_BASED_2/Netopeer2/server/configuration/load_server_key.xml 
ly ERROR: Unknown element "keystore". (/)
cli_send_recv: Failed to send the RPC.
>

**Comment by shubhtrix** [comment]
**And sysrepo-plugind reporting me this **
`
/turing-machine:turing-machine/transition-function/delta[label='final step']/output/head-move = right [default]

[ERR] (ks_privkey_get_cb:146) File "/usr/local/etc/keystored/keys/test_server_key.pub.pem" could not be accessed (No such file or directory).
[ERR] (ks_privkey_get_cb:146) File "/usr/local/etc/keystored/keys/test_server_key.pub.pem" could not be accessed (No such file or directory).
[ERR] (ks_privkey_get_cb:146) File "/usr/local/etc/keystored/keys/test_server_key.pub.pem" could not be accessed (No such file or directory).
`

**Comment by dileepravindran** [comment]
is keystore installed properly ? all these should files should be present

**Comment by shubhtrix** [comment]
@dileepravindran  sorry for the previous comment that time sysrepod-pluin not started properly that's why ..... Leave the previous comment

**Comment by dileepravindran** [comment]
one thing i can see is that you have set permission to root and connecting through shubham, try connecting through root

**Comment by dileepravindran** [comment]
you need to start in this order 
 sysrepod
 sysrepo-plugind
  netopeer2-server

and then connect netopeer-clu

**Comment by shubhtrix** [comment]
the order is correct :+1:  I mean using the same order.

**Comment by shubhtrix** [comment]
Tried one more time everything with root permissions : 

AS ROOT : 03:22 PM : CMakeModules :) netopeer2-cli 
> connect --host localhost --login root
Interactive SSH Authentication
Type your password:
Password: 
nc ERROR: No yang-library modules information for session 1.
ly ERROR: Invalid arguments (lys_features_change()).
> 
> user-rpc --content /home/shubham/WORK/01_GIT/REST_CONF/02_C_BASED_2/Netopeer2/server/configuration/load_server_key.xml 
ly ERROR: Unknown element "keystore". (/)
cli_send_recv: Failed to send the RPC.
> 

Same error

**Comment by dileepravindran** [comment]
something wrong with your keystore?try re installing everything and configuring newly . 
thats the only solution i can think of right now

**Comment by shubhtrix** [comment]
Hello @dileepravindran 
Oh...
Oops!!! hell of a task, it has so many dependencies.... cmoka, swig, sysrepo, libyang2, libnetconf2, protobuf, protobufc etc...

What I figured out is when I try to connect over ssh it gives **No yang-library modules information for session ** which I think should not be there LIBNETCONF hitting this error from `session_client.c` form here  
`    modules = lyd_find_path(data_rpl->data, "/ietf-yang-library:modules-state/module");`
lyd_find_path returning NULL so the error below :- 
  
> connect --host localhost --login root
    Interactive SSH Authentication
    Type your password:
    Password:
> nc ERROR: No yang-library modules information for session 1.
> ly ERROR: Invalid arguments (lys_features_change()).
