### ISSUE TITLE
Question: subtree filters with content match node

### ISSUE THREAD

**Issue by ustcpxy** [CESNET/Netopeer2#198]
```
<get-config>
  <source>
    <running/>
  </source>
  <filter type="subtree">
    <if:interfaces xmlns:if="urn:ietf:params:xml:ns:yang:ietf-interfaces">
      <if:interface>
        <if:name>eth0</if:name>
      </if:interface>
    </if:interfaces>
  </filter>
</get-config>
```

send above xml to netopeer2-server, 
in function `op_get`, it will create two filters like below:
/ietf-interfaces:interfaces/interface[name='eth0']/name
/ietf-interfaces:interfaces/interface[name='eth0']

is it correct behavior?

**Comment by michalvasko** [comment]
Hi,
I believe it is. The first filter is perhaps redundant but it is likely an optimization (in some similar cases it would not be redundant). If the result conforms to the [RFC](https://tools.ietf.org/html/rfc6241#section-6.2), it is correct.

Regards,
Michal

**Comment by ustcpxy** [comment]
Thanks.
the get result is correct.
