### ISSUE TITLE
if more than two leafs in  the container of modify data, the edit-config operation will  failed.

### ISSUE THREAD

**Issue by ZhaoGuangYue** [CESNET/Netopeer2#2]
if more than two leafs in  the container of modify data, the edit-config operation will  failed.
i found the xpath that constructed in the function is wrong when edit the third leaf in the container.
for example:
**my model define is like this:**

```
module ME {
  namespace "urn:ietf:params:xml:ns:yang:z";
  prefix ME;
  revision 2016-05-10;
 
  container ME{
    leaf MEId{
      type uint32{
	    range "1";
	  }
	  mandatory true;
	  config true;
	  description "Object ID of managed NE";
    }
  
	leaf vName{
	  type string{
		length "1..128";
	  }
	  mandatory true;
	  config true;
	  description "NE provider";
    }
  
    leaf rMode{
      type int32{
	    range "1..65535";
	  }
	  mandatory true;
	  config true;
	  description "Radio Standard";
    }
  }
}
```

**the xpath of rMode construct in the function is like**
**/ME:ME/vName/rMode**
as we see  the xpath is not right,and the right xpath is "**/ME:ME/rMode**"

i check the code ,wonder is there any thing wrong with "op_editconfig" function in operations.c when deal leaf node?
and i wonder :if the local parameter "missing_keys" and "lastkey" in function op_editconfig is used to judge the current leaf is list or is  single leaf node? when the leaf is only leaf node ,the lastkey need reinitialize to zero,as the "dfs_nextsibling" will "--" operation on the  lastkey

**Comment by michalvasko** [comment]
Hi,
it would be best if you could provide the original configuration and then the edit-config you tried to apply, so we can duplicate your issue.

Regards,
Michal

**Comment by ZhaoGuangYue** [comment]
Thanks for your reply,and my model and configuration is as follows:

**model**
module ME {
  namespace "urn:ietf:params:xml:ns:yang:zte";
  prefix ME;
  revision 2016-05-10;

  container ME{
    leaf MEId{
      type uint32{
        range "1";
      }
      mandatory true;
      config true;
      description "Object ID of managed NE";
    }

    leaf vName{
      type string{
        length "1..128";
      }
      mandatory true;
      config true;
      description "NE provider";
    }

    leaf rMode{
      type int32{
        range "1..65535";
      }
      mandatory true;
      config true;
      description "Radio Standard";
    }
  }
}

**edit data**
<ME xmlns="urn:ietf:params:xml:ns:yang:zte" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="create">
  <MEId>1</MEId>
  <vName>zte</vName>
  <rMode>1</rMode>
</ME>

 **ps :original configuration is empty ,and  i want use edit-config to create  config data**

**Comment by rkrejci** [comment]
Seems working for me with the current master (93e4f83). Please try it again and let us know if the issue remains.
