### ISSUE TITLE
[Question] Run multiple netopeer2 and sysrepo instances on the same machine

### ISSUE THREAD

**Issue by hoannd** [CESNET/Netopeer2#202]
I am considering to integrate netopeer2 and sysrepo into our app. We run two instances of our app on a Linux machine. Each app have its own configuration and state datastore. I my opinion, each instance of the controlled app will have its own netopeer2 and sysrepo. So I have some questions:
1. Can I run multiple instances of netopeer2 and sysrepo on the same machine?
2. If yes can you show me some steps to setup this configuration?
3. Can I use one netopeer2 server to connect to two sysrepos? Each sysrepo stores config and state data of a controlled app.

**Comment by jktjkt** [comment]
That's not how sysrepo (and therefore also Netopeer2) are typically used. It is also not how the NETCONF standard designed things to behave. Just use one `sysrepod` instance and connect to it from both instances of your application. You'll need a properly designed YANG module to cover both instances of your application.

**Comment by hoannd** [comment]
Thanks jktjkt. I will try to update my YANG module as your suggest. My case is a little more complicate: two instances with some common (config, state, performance), some different one. So it will take me more time to redesign my YANG module.
