### ISSUE TITLE
Query: How to find the port for which admin-state is being configured

### ISSUE THREAD

**Issue by karthikakrishnamurthy** [CESNET/Netopeer2#203]
Hi,
I am sending  the following xml from the Netopeer2 agent  cli... 

<switch xmlns="urn:onf:config:yang">
  <id>openvswitch</id>
  <resources>
    <port>
      <name>eth1</name>
      <configuration>
        <admin-state>down</admin-state>
      </configuration>
    </port>
  </resources>
</switch>

I have registered application callback in Netopeer2 server (using the function sr_subtree_change_subscribe)  to configure my hardware switch depending upon the input i get from xml.

Inside the registered callback, 

I am able to get xpath 
xpath:/of-config:switch/resources/port[name='eth1']/configuration/admin-state

Though this xpath shows the port name, is there any other easy way to get port name through some functions so that i don't have to parse the above string ?

Thank you.

**Comment by swathins079** [comment]
Hi,

"sr_xpath_key_value" will get you the eth1.

Regards,
Swathin

**Comment by karthikakrishnamurthy** [comment]
Thank you :)...This is exactly what i wanted :)
