### ISSUE TITLE
Failed to reply a notification message to cli when the notification is defined at container

### ISSUE THREAD

**Issue by zzyyll2** [CESNET/Netopeer2#206]
~~~yang
module test-notif {
  yang-version 1.1;
  namespace "urn:test-notif";
  prefix tn;
  
  container root {
    notification notif1 {
          leaf f1 {
            type string;
          }
	}
  }
}
~~~

It looks like that the problem is here:
~~~code
API struct nc_server_notif *
nc_server_notif_new(struct lyd_node* event, char *eventtime, NC_PARAMTYPE paramtype)
{
    struct nc_server_notif *ntf;

// Here, event->schema is the root node,but it's nodetype is not equal LYS_NOTIF.//
    _if (!event || event->schema->nodetype != LYS_NOTIF) {
        ERRARG("event");
        return NULL;_
    } else if (!eventtime) {
        ERRARG("eventtime");
        return NULL;
    }

~~~

**Comment by jktjkt** [comment]
I think that it is not valid to define notifications in other places than at the very top of a YANG module. See [RFC 6020, page 144](https://tools.ietf.org/html/rfc6020#page-144) and look for occurrences of `notification-stmt` in the ABNF grammar.

**Comment by fanchanghu** [comment]
Hi, 
it seems YANG 1.1 adds support for defining notification in container or list, see this: https://tools.ietf.org/html/rfc7950#section-7.16

**Comment by michalvasko** [comment]
Hi @zzyyll2,
you were right, this check was the only problem and it should work now.

Regards,
Michal
