### ISSUE TITLE
typedef with type decimal64 will not success when edit-config.

### ISSUE THREAD

**Issue by fanchanghu** [CESNET/Netopeer2#21]
Hi, 
I got failed when I do edit-config with below module and xml:
```
module a {
  namespace "aaa:1";
  prefix a;
  
  typedef typeA{
	type decimal64{
	  fraction-digits 1;
	  range "-10..-1";
	}
  }
  
  container aa
  {
    leaf f1{
	  type typeA;
	}
  }
}
```

```
<aa xmlns="aaa:1">
<f1>-3.0</f1>
</aa>
```
And I found that this bugs may be caused in function `op_set_srval`, when type is derived from decimal64, `((struct lys_node_leaf *) leaf->schema)->type.info.dec64.dig` is zero, and the fraction-digits is defined in the base type.
when I fix it like above,  edit-config is ok,  but get-config still fail, the log has this:
```
netopeer2-server[1561]: Value "-30" does not satisfy a constraint (range, length, or pattern). (/a:aa/f1)
netopeer2-server[1561]: Failed to create node "f1" as a child of "aa". (/a:aa/f1)
```
It seems that sysrepo return -30 as the value.

**Comment by rkrejci** [comment]
The bug was in libyang and it was already fixed in devel branch. Anyway, I have cherry-picked the fix into master branch, so please verify that it now (libyang 0.9.185) works as expected. Note that the problem was probably already in edit-config which stored value `-30` into sysrepo.
