### ISSUE TITLE
Not able to connect netconf4j with Netopeer2

### ISSUE THREAD

**Issue by neenuanil** [CESNET/Netopeer2#211]
I am using the latest version of NetconfServer, Version-0.4-r2.

I am trying to connect with server using java library netconf4j but i cant read any values from server.Can u pls help.Logs from netconf server side is given. Client is sending the request and waiting for the reply.But server timeouts saying inactive session.

[2018/01/08 11:43:34.603955, 2] ssh_pki_import_privkey_base64:  Trying to decode privkey passphrase=false
[2018/01/08 11:43:34.605195, 1] ssh_server_connection_callback:  SSH client banner: SSH-2.0-Ganymed Build_210
[2018/01/08 11:43:34.605239, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-Ganymed Build_210
[2018/01/08 11:43:34.732021, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
netopeer2-server[10279]: Received an SSH message "request-service" of subtype "ssh-userauth".
netopeer2-server[10279]: Received an SSH message "request-auth" of subtype "none".
netopeer2-server[10279]: Received an SSH message "request-auth" of subtype "password".
netopeer2-server[10279]: User "root" authenticated.
netopeer2-server[10279]: Received an SSH message "request-channel-open" of subtype "session".
netopeer2-server[10279]: Received an SSH message "request-channel" of subtype "subsystem".
netopeer2-server[10279]: Resolving unresolved data nodes and their constraints...
netopeer2-server[10279]: All data nodes and constraints resolved.
[2018/01/08 11:43:34.834003, 2] grow_window:  growing window (channel 43:100) to 1280000 bytes
netopeer2-server[10279]: Generated new event (netconf-session-start).

netopeer2-server[10279]: Session 12: inactive read timeout elapsed.
netopeer2-server[10279]: Session 12: thread 1 event session terminated.
netopeer2-server[10279]: Generated new event (netconf-session-end).

**Comment by michalvasko** [comment]
Hi,
this means that *netopeer2-server* expects some data to be sent to it but it fails to receive it. Likely, *netconf4j* has some NETCONF message formatting error. If you turn on received message printing and post it here, I should be able to tell you exactly what the problem is. To enable this in the server, start it with `-c MSG`.

Regards,
Michal

**Comment by neenuanil** [comment]
Hi,

Thanks Michal

Here is the message:

netopeer2-server[24454]: Accepted a connection on 0.0.0.0:830.
[2018/01/08 18:29:50.493166, 2] ssh_pki_import_privkey_base64:  Trying to decode privkey passphrase=false
[2018/01/08 18:29:50.494406, 1] ssh_server_connection_callback:  SSH client banner: SSH-2.0-Ganymed Build_210
[2018/01/08 18:29:50.494439, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-Ganymed Build_210
[2018/01/08 18:29:50.649215, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
netopeer2-server[24454]: Received an SSH message "request-service" of subtype "ssh-userauth".
netopeer2-server[24454]: Received an SSH message "request-auth" of subtype "none".
netopeer2-server[24454]: Received an SSH message "request-auth" of subtype "password".
netopeer2-server[24454]: User "root" authenticated.
netopeer2-server[24454]: Received an SSH message "request-channel-open" of subtype "session".
netopeer2-server[24454]: Received an SSH message "request-channel" of subtype "subsystem".
netopeer2-server[24454]: Resolving unresolved data nodes and their constraints...
netopeer2-server[24454]: All data nodes and constraints resolved.
netopeer2-server[24454]: Session 11: sending message:
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><capabilities><capability>urn:ietf:params:netconf:base:1.0</capability><capability>urn:ietf:params:netconf:base:1.1</capability><capability>urn:ietf:params:netconf:capability:writable-running:1.0</capability><capability>urn:ietf:params:netconf:capability:candidate:1.0</capability><capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</capability><capability>urn:ietf:params:netconf:capability:validate:1.1</capability><capability>urn:ietf:params:netconf:capability:startup:1.0</capability><capability>urn:ietf:params:netconf:capability:xpath:1.0</capability><capability>urn:ietf:params:netconf:capability:with-defaults:1.0?basic-mode=explicit&amp;also-supported=report-all,report-all-tagged,trim,explicit</capability><capability>urn:ietf:params:netconf:capability:notification:1.0</capability><capability>urn:ietf:params:netconf:capability:interleave:1.0</capability><capability>
netopeer2-server[24454]: Session 11: sending message:
urn:ietf:params:xml:ns:yang:ietf-yang-metadata?module=ietf-yang-metadata&amp;revision=2016-08-05</capability><capability>urn:ietf:params:xml:ns:yang:1?module=yang&amp;revision=2017-02-20</capability><capability>urn:ietf:params:xml:ns:yang:ietf-inet-types?module=ietf-inet-types&amp;revision=2013-07-15</capability><capability>urn:ietf:params:xml:ns:yang:ietf-yang-types?module=ietf-yang-types&amp;revision=2013-07-15</capability><capability>urn:ietf:params:xml:ns:yang:ietf-datastores?module=ietf-datastores&amp;revision=2017-08-17</capability><capability>urn:ietf:params:xml:ns:yang:ietf-yang-library?module=ietf-yang-library&amp;revision=2017-08-17&amp;module-set-id=40</capability><capability>urn:ietf:params:xml:ns:yang:example?module=example-module</capability><capability>urn:rd?module=referenced-data</capability><capability>urn:ietf:params:xml:ns:yang:small-module?module=small-module</capability><capability>urn:ietf:params:xml:ns:yang:info?module=info-module</capability><capability>
netopeer2-server[24454]: Session 11: sending message:
ns:yang:module-a?module=module-a&amp;revision=2016-02-10</capability><capability>ns:yang:module-b?module=module-b&amp;revision=2016-02-05</capability><capability>ns:yang:state-module?module=state-module&amp;revision=2016-07-01</capability><capability>test:top-level-mandatory?module=top-level-mandatory</capability><capability>urn:cm?module=cross-module</capability><capability>http://example.net/turing-machine?module=turing-machine&amp;revision=2013-12-27</capability><capability>urn:ietf:params:xml:ns:yang:ietf-netconf-acm?module=ietf-netconf-acm&amp;revision=2012-02-22</capability><capability>urn:ietf:params:xml:ns:netconf:base:1.0?module=ietf-netconf&amp;revision=2011-06-01&amp;features=writable-running,candidate,rollback-on-error,validate,startup,xpath</capability><capability>urn:ietf:params:xml:ns:yang:ietf-netconf-notifications?module=ietf-netconf-notifications&amp;revision=2012-02-06</capability><capability>urn:ietf:params:xml:ns:netconf:notification:1.0?module=notifications&amp;revision=2008-07-14
netopeer2-server[24454]: Session 11: sending message:
</capability><capability>urn:ietf:params:xml:ns:netmod:notification?module=nc-notifications&amp;revision=2008-07-14</capability><capability>http://example.com/ns/servers?module=servers</capability><capability>urn:ietf:params:xml:ns:yang:swig-test-cpp-changes?module=swig-test-cpp-changes&amp;revision=2017-03-09</capability><capability>urn:ietf:params:xml:ns:yang:swig-test-cpp-operations?module=swig-test-cpp-operations&amp;revision=2017-03-09</capability><capability>urn:ietf:params:xml:ns:yang:swig-test?module=swig-test&amp;revision=2017-03-09</capability><capability>urn:ietf:params:xml:ns:yang:ietf-interfaces?module=ietf-interfaces&amp;revision=2014-05-08</capability><capability>urn:ietf:params:xml:ns:yang:ietf-ip?module=ietf-ip&amp;revision=2014-06-16</capability><capability>urn:ietf:params:xml:ns:yang:iana-if-type?module=iana-if-type&amp;revision=2014-05-08</capability><capability>urn:ietf:params:xml:ns:yang:test-module?module=test-module</capability><capability>
netopeer2-server[24454]: Session 11: sending message:
urn:ietf:params:xml:ns:yang:ietf-x509-cert-to-name?module=ietf-x509-cert-to-name&amp;revision=2014-12-10</capability><capability>urn:ietf:params:xml:ns:yang:ietf-keystore?module=ietf-keystore&amp;revision=2016-10-31</capability><capability>urn:ietf:params:xml:ns:yang:ietf-ssh-server?module=ietf-ssh-server&amp;revision=2016-11-02</capability><capability>urn:ietf:params:xml:ns:yang:ietf-tls-server?module=ietf-tls-server&amp;revision=2016-11-02</capability><capability>urn:ietf:params:xml:ns:yang:ietf-netconf-server?module=ietf-netconf-server&amp;revision=2016-11-02&amp;features=listen,ssh-listen,tls-listen,call-home,ssh-call-home,tls-call-home</capability><capability>urn:ietf:params:xml:ns:yang:iana-crypt-hash?module=iana-crypt-hash&amp;revision=2014-08-06</capability><capability>urn:ietf:params:xml:ns:yang:ietf-system?module=ietf-system&amp;revision=2014-08-06&amp;features=authentication,local-users</capability><capability>
netopeer2-server[24454]: Session 11: sending message:
urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring?module=ietf-netconf-monitoring&amp;revision=2010-10-04</capability><capability>urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults?module=ietf-netconf-with-defaults&amp;revision=2011-06-01</capability></capabilities><session-id>11</session-id></hello>
netopeer2-server[24454]: Session 11: sending message:
]]>]]>
[2018/01/08 18:29:50.759360, 2] grow_window:  growing window (channel 43:100) to 1280000 bytes
netopeer2-server[24454]: Session 11: received message:
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
	<capabilities>
		<capability>urn:ietf:params:netconf:base:1.1</capability>
		<capability>urn:ietf:params:netconf:base:1.0</capability>
	</capabilities>
</hello>

netopeer2-server[24454]: -------------------------------urn:ietf:params:netconf:base:1.1--------------------------------
netopeer2-server[24454]: -------------------------------urn:ietf:params:netconf:base:1.0--------------------------------
netopeer2-server[24454]: Generated new event (netconf-session-start).
netopeer2-server[24454]: Session 11: inactive read timeout elapsed.
netopeer2-server[24454]: Session 11: thread 4 event session terminated.
netopeer2-server[24454]: Generated new event (netconf-session-end).

**Comment by michalvasko** [comment]
Hi,
I am not sure how did those 2 lines starting with `----------------` appeared there, I am guessing it is your local modification. Ignoring that, I have not taken into consideration that the server will only print out complete messages (the hello message) so the partial one is not displayed. To see it you will either have to use a debugger with the server or get it somehow from the client. Anyway, I am almost certain there is no problem with the server so you should maybe seek some help from the client creators instead.

Regards,
Michal

**Comment by neenuanil** [comment]
Hi Michal,
Problem solved!!!!!

Problem was with the client java code. I was adding two capabilities to the session by mistake.

<capability>urn:ietf:params:netconf:base:1.1</capability>
<capability>urn:ietf:params:netconf:base:1.0</capability>

I removed "<capability>urn:ietf:params:netconf:base:1.1</capability>"  and everything worked fine.

Thanks for your help.
