### ISSUE TITLE
how to <edit-config> more than one yang module in one xml file

### ISSUE THREAD

**Issue by shaqianqing** [CESNET/netopeer2#212]
hi：
    I test <edit-config> function with netopeer-cli,but i find out in one xml file that i can config one yang module data,I want to ask ,how to <edit-config> more than one yang module in one xml file.

thank you!

**Comment by michalvasko** [comment]
Hi,
simply include the other module's top-level nodes with children as siblings to the other top-level nodes. This XML does not have to have one root even though it is then technically not a well-formed XML. However, it is inserted as a child of the `edit-config` RPC so it does not matter.

Regards,
Michal

**Comment by shaqianqing** [comment]
sorry,I don't understand what you mean.I list the two yang module and xml file below,can you point the problem of the xml file ,thanks very much

yang moule first：
module sipuser {
  namespace "http://www.raisecom.com/sipuser";
  prefix sipuser;
  
  


  description
    "This module contains a collection of YANG definitions for
     managing data forward device.";

  revision 2017-07-03 {
    description
      "Initial revision.";
  }

    /*
   * Configuration data nodes
   */
  container sipuser {
        description
                "sipuser configuration parameters.";   
	  container userInfos {
		description
		  "Interface configuration parameters.";

		list userInfo {
		  key "number";
		  
		  description
			"the list of userInfo.";

		  leaf number {
			type string;
			description
			  "The number of the sipuser.";
		  }
		  
		  leaf name {
			type string;
			description
			  "The name of the sipuser.";
		  }
		  
		  leaf password {
			type string;
			description
			  "The password of the sipuser.";
		  }
		}
	  }
	  }
  rpc getdataflow {
    description
      "Get the tenant data flowing.";
  }
}

yang moule second：
module fxsuser {
  namespace "http://www.raisecom.com/fxsuser";
  prefix fxsuser;
  
  


  description
    "This module contains a collection of YANG definitions for
     managing data forward device.";

  revision 2017-07-03 {
    description
      "Initial revision.";
  }

    /*
   * Configuration data nodes
   */
  container userInfos {
		description
		  "Interface configuration parameters.";

		list userInfo {
		  key "number";
		  
		  description
			"the list of userInfo.";

		  leaf number {
			type string;
			description
			  "The number of the fxsuser.";
		  }
		  
		  leaf name {
			type string;
			description
			  "The name of the fxsuser.";
		  }
		  
		  leaf password {
			type string;
			description
			  "The password of the fxsuser.";
		  }
		}
	  }
}


here the xml file
<?xml version="1.0" encoding="UTF-8"?>
<fxsuser xmlns="http://www.raisecom.com/fxsuser">
  <userInfos xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
  		<userInfo xc:operation="create">
          <number>1002</number>
          <name>sip-1002</name>
          <password>sip-1002</password>
      </userInfo>
    </userInfos>  
</fxsuser>
<sipuser xmlns="http://www.raisecom.com/sipuser">
    <userInfos xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
  		<userInfo xc:operation="create">
          <number>1002</number>
          <name>sip-1002</name>
          <password>sip-1002</password>
      </userInfo>
</sipuser>


 I execute the command “edit-config --config=addUser.xml running”，the result is：
"edit-config: failed to parse the file."

How to write an example of a XML file that can config  fxsuser and sipuser at the same time?

**Comment by shaqianqing** [comment]
sorry,I don't understand what you mean.I list the two yang module and xml file below,can you point the problem of the xml file ,thanks very much

# yang moule first：

`module sipuser {
  namespace "http://www.raisecom.com/sipuser";
  prefix sipuser;

  description
    "This module contains a collection of YANG definitions for
     managing data forward device.";

  revision 2017-07-03 {
    description
      "Initial revision.";
  }

    /*
   * Configuration data nodes
   */
  container sipuser {
        description
                "sipuser configuration parameters.";   
	  container userInfos {
		description
		  "Interface configuration parameters.";

		list userInfo {
		  key "number";
		  
		  description
			"the list of userInfo.";

		  leaf number {
			type string;
			description
			  "The number of the sipuser.";
		  }
		  
		  leaf name {
			type string;
			description
			  "The name of the sipuser.";
		  }
		  
		  leaf password {
			type string;
			description
			  "The password of the sipuser.";
		  }
		}
	  }
	  }
  rpc getdataflow {
    description
      "Get the tenant data flowing.";
  }
}`

# yang moule second：
**module fxsuser {
namespace "http://www.raisecom.com/fxsuser";
prefix fxsuser;

description
"This module contains a collection of YANG definitions for
managing data forward device.";

revision 2017-07-03 {
description
"Initial revision.";
}

/*
Configuration data nodes
*/
container userInfos {
description
"Interface configuration parameters.";

list userInfo {
key "number";

 description
   "the list of userInfo.";

 leaf number {
   type string;
   description
     "The number of the fxsuser.";
 }
 
 leaf name {
   type string;
   description
     "The name of the fxsuser.";
 }
 
 leaf password {
   type string;
   description
     "The password of the fxsuser.";
 }
}
}
}**

# here the xml file
`**<?xml version="1.0" encoding="UTF-8"?>
<fxsuser xmlns="http://www.raisecom.com/fxsuser">
  <userInfos xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
  		<userInfo xc:operation="create">
          <number>1002</number>
          <name>sip-1002</name>
          <password>sip-1002</password>
      </userInfo>
    </userInfos>  
</fxsuser>
<sipuser xmlns="http://www.raisecom.com/sipuser">
    <userInfos xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
  		<userInfo xc:operation="create">
          <number>1002</number>
          <name>sip-1002</name>
          <password>sip-1002</password>
      </userInfo>
</sipuser>
**`

I execute the command “edit-config --config=addUser.xml running”，the result is：
"edit-config: failed to parse the file."

How to write an example of a XML file that can config fxsuser and sipuser at the same time?

**Comment by michalvasko** [comment]
Hi,
the XML generally seems fine except in the second tree you are missing the closing tag for `userInfos`. When I tested it there was a problem with the client parsing the error reply from the server (which is fixed now) but the server displayed even before
```
Invalid (mixed names) opening (userInfos) and closing (sipuser) element tags. (/rpc/edit-config/config/sipuser/userInfos)
```
which seems clear enough to me.

Regards,
Michal
