### ISSUE TITLE
Custom module in for netopeer2

### ISSUE THREAD

**Issue by jhkrf** [CESNET/netopeer2#215]
Hi,
I have knowledge of netopeer but I'm new to netopeer2, and so if anyone can help me with the development of a new custom module into netopeer2 just like development of transapi in netopeer. Any reference link or material would be appreciable.
Thanks  in advance

**Comment by michalvasko** [comment]
Hi,
the datastore for *netopeer2* is not part of the project, it uses a separate datastore [sysrepo](https://github.com/sysrepo/sysrepo) so all the information you are looking for can be found there. It is always useful to go through the [documentation](http://www.sysrepo.org/static/doc/html/index.html) and then you should look at the examples in `sysrepo/examples`.

Also, if you can wait a few days, I am just now documenting in detail on how to write a module for *sysrepo* and it will be part of its documentation. That should probably be exactly what you are looking for.

Regards,
Michal

**Comment by jhkrf** [comment]
Thank you for the help, the document was really helpful in developing my own module for netopeer2.
But I'm struck on a point that where can i include my own data(dynamic response) into the module. Is there anyway or any document for that.

Thanks in Advance

**Comment by michalvasko** [comment]
Hi,
I have no idea what is it you want to do, I have never heard "dynamic response" in this context. I think you are missing some information about how *sysrepo* and *netopeer2-server* work, so try to describe what you want in detail and I should be able to correct you.

Regards,
Michal

**Comment by jhkrf** [comment]
Hi,
With context to dynamic response, I mean the data which i was able to fill in the C file in the Netopeer.
in Netopeer we have two file main.c and init.c file and we are able to execute our data by modifying the main.c file but here in Netopeer2 I'M unable to do so, this is what i wanted to ask that where can we add our own code in Netopeer2.
Thanks in advance

**Comment by michalvasko** [comment]
Hi,
you want to look at [sysrepo](https://github.com/sysrepo/sysrepo), which provides the same and even extended functionality of our old *netopeer*. It would be best if you clone the repository `devel` branch, build the documentation (`make doc`), open it (`sysrepo/doc/html/index.html`), and look at *Developer Guide / Getting Started*. It is a simple tutorial that shows how to write a *sysrepo* application (in *netopeer-server* it was a transAPI module).

Regards,
Michal

**Comment by jhkrf** [comment]
Hello,
I got your point about the sysrepo application, things are working fine with the config true data but as soon as I change the config true to config false it shows the error of "**_Error: Unable to parse the data: Unknown element "ver".._**" here ver is my leaf node to which I have assigned config false. I have even tried it writing inside "int sr_dp_get_items_subscribe()" which is used for config false nodes but still the error remains the same, is there anyway out to use the config false node.
Thanks in advance

**Comment by michalvasko** [comment]
Hi,
I do not really know what you are asking, this are basic problems. Naturally, you cannot treat state (`config false`) data the same way as configuration data. You need to use the function you mentioned. If you get this error, you are not including the header file that defines it, you should definitely know that. As the first thing you should have included `sysrepo.h`.

Regards,
Michal

**Comment by jhkrf** [comment]
Hi,
 I was working with the rpc and so I used the ( **sr_rpc_subscribe** ) and called the under the (**sr_plugin_init_cb**) function. There were no error while compiling and the code was good to execute. But when I used the user-rpc command it showed that t**_here is no rpc subscription_**, why is there no rpc subscription and how to get the rpc subscription.
 Thanks in advance

**Comment by michalvasko** [comment]
Hi,
I assume you implemented it as a plugin then meaning you should get a `*.so` file. YOu must put this file into the sysrepo plugin directory and have `sysrepo-plugind` running. Did you do that?

Regards,
Michal

**Comment by jhkrf** [comment]
Hi,
Yes I tried to do it as plugin but I'm not able to generate any  *.so file, is ther any other way around to implement RPC. Yes my sysrepo-plugind was running but htere was no *.so file.
It would be a real help if you can share your document about __writing module for sysrepo_  .
Thanks in advance

**Comment by michalvasko** [comment]
Hi,
there is a tutorial in the docs, but it will not be available online until tomorrow (you can build it, however, with `make doc` and when you then open it, it is in `Developer Guide / Getting Started`. Also, you can look at how example plugins are compiled and installed in `sysrepo/examples/plugins/CMakeLists.txt`.

Regards,
Michal
