### ISSUE TITLE
 Unable to send <rpc> message to netopeer2-server while running sysrepo datastore.

### ISSUE THREAD

**Issue by rajanishWanderer** [CESNET/netopeer2#216]
Hi All !!
I was trying to emulate the demo of dnsmasq and sysrepo integration as mentioned on dnsmasq-demo. 
1. During the installation, based on dnsmasq-sysrepo-github :
    Third step asks for the following command:
     sysrepoctl --init --module=sysrepo-dnsmasq
    
     which results in the following error:
     sysrepoctl: urecognized option '--init'
     sysrepoctl: option '-' is invalid. Exiting.

     Inorder to fix this issue I followed the reply given on : init-query 
     where it was mentioned that instead of init, install may do the task.
    
     So I do the following, and get the following result:
     [root@rajneesh yang]# sysrepoctl -i --yang "sysrepo-dnsmasq@2016-01-                 22.yang"
     Installing a new module from file 'sysrepo-dnsmasq@2016-01-22.yang'...
     Installing the YANG file to '/etc/sysrepo/yang/sysrepo-dnsmasq@2016-01-               22.yang'...
     Installing data files for module 'sysrepo-dnsmasq'...
     Notifying sysrepo about the change...
     Install operation completed successfully.
      Then I do the next step:
      [root@rajneesh yang]# sysrepocfg --import=dnsmasq.xml --datastore=startup          sysrepo-dnsmasq
      The new configuration was successfully applied.
2. Expecting that all configurations are applied successfully I tried to emulate the video on dnsmasq-demo-video. 
     a) It may be noted that the video uses direct ssh rather than using the netopeer2-cli with the command : 
        ssh admin@127.0.0.1 -p 6001 -s netconf (Followed suite with requisite changes.)
         At 1:26 in the video, the person typing makes an <rpc> call to get the configuration of the dnsmasq:
```xml
        #252
<rpc message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <get-config>
        <source>
            <running\>
        </source>
        <filter>
            <dnsmasq-cfg xmlns="urn:ietf:params:xml:ns:yang:dnsmasq"/>
        </filter>
    </get-config>
</rpc>
##
```

        But when I follow the step my Netopeer2-server hangs on the following step:
        [2018/01/22 11:35:10.231346, 2] grow_window:  growing window (channel                43:0) to 1280000 bytes
        netopeer2-server[354]: Session 3: inactive read timeout elapsed.

       Which implies I couldn't perform the <rpc> call.
3. To try by some other means I utilized the netopeer2-cli program obtained from Netopeer2-github .
     wherein after connecting to the server I try get-config with the following unsuccessful attempts.
     
   a) get-config --source running
       output: DATA
       output: <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="2">
                   <data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"/></rpc-reply>
   b) get-config --source running --filter-xpath urn:ietf/params:xml/ns:yang/dnsmasq
       output:
       ly VERBOSE: Resolving unresolved data nodes and their constraints...
       ly VERBOSE: All data nodes and constraints resolved.
       ly ERROR: Module name "urn" refers to an unknown module.
       cli_send_recv: Failed to send the RPC.
   c) get-config --source running --filter-xpath "yang/dnsmasq"
       output:
```xml
       <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="3">
       <rpc-error><error-type>application</error-type><error-tag>operation-failed</error-tag>
       <error-severity>error</error-severity>
       <error-message xml:lang="en">np2srv_sr_get_items_iter failed (sysrepo: Invalid argument).</error-message>
       </rpc-error></rpc-reply>
```
```
       ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  np2srv_sr_get_items_iter failed (sysrepo: Invalid argument).
```

The expected output is:
```xml
     <rpc-reply message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
     <data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
     <dnsmasq-cfg xmlns="urn:ietf:params:xml:ns:yang:dnsmasq">
     <username>root</username>
     <groupname>root</groupname>
     <dns-server><enabled>true</enabled><port>53</port></dns-server>
     </dnsmasq-cfg></data></rpc-reply>
```
     
What shall be the correct procedure to run the same ? Any help or advice shall be of great value.

**Comment by michalvasko** [comment]
Hi,

1. `--init` command was removed because it was redundant, you correctly performed `--install` instead.

2. Yes, there were some additional timeouts introduced and it does not work well with `ssh(1)`. 

3. You were right to use `netopeer2-cli`, it is much more convenient. The output of the first `get-config` would imply that the model `dnsmasq` is not enabled, that is why you cannot see its configuration. The video is quite old and I am not sure how the model is supposed to be enabled, but generally you can use "fake" subscriptions to enable the model by running `examples/application_example sysrepo-dnsmasq`. After that you should see the data in the `get-config`.

Filtering only the data from this model is possible but you were mixing *subtree* and *xpath* NETCONF filters so it could not work. Subtree filter was used in the example and you can use it also in `netopeer2-cli`. Also, you can use XPath filter in which case the path would be `/sysrepo-dnsmasq:dnsmasq-cfg`. You must use the model name instead of the namespace followed by the subtree you want to get.

Regards,
Michal

**Comment by rajanishWanderer** [comment]
Thanks Michal for the last reply. It was helpful in getting it to work.
Although I hit another halt. I am trying to perform an edit-config with the following command:
`edit-config --target running --config=dhcp.xml`
which is in fact:
`<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="5"><edit-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><target><running/></target><config><dnsmasq-cfg xmlns="urn:ietf:params:xml:ns:yang:dnsmasq">
        <dhcp-server>
                <dhcp-pool>
                        <start-addr>192.168.1.70</start-addr>
                        <end-addr>192.168.1.80</end-addr>
                        <lease-time>1000</lease-time>
                </dhcp-pool>
        </dhcp-server>
</dnsmasq-cfg>
</config></edit-config></rpc>'

Now at the dnsmasq side I am getting the output as:
`========== DNSMASQ CONFIG HAS CHANGED ==========

dnsmasq: started, version  DNS disabled
dnsmasq: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
Error: Requested resource is already locked`


whereas I should get the following output:
`dnsmasq: started, version  cachesize 150
dnsmasq: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify
dnsmasq-dhcp: DHCP, IP range 192.168.1.70 -- 192.168.1.80, lease time 16m40s
dnsmasq: reading /etc/resolv.conf
dnsmasq: using nameserver 10.0.2.3#53
dnsmasq: read /etc/hosts - 7 addresses
dnsmasq-dhcp: DHCPDISCOVER(tap0) 52:54:00:12:34:56
dnsmasq-dhcp: DHCPOFFER(tap0) 192.168.1.80 52:54:00:12:34:56
dnsmasq-dhcp: DHCPREQUEST(tap0) 192.168.1.80 52:54:00:12:34:56
dnsmasq-dhcp: DHCPACK(tap0) 192.168.1.80 52:54:00:12:34:56`


Also on the netopeer2-cli side I am getting the acknowledgement message:
`<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="5"><ok/></rpc-reply>

OK`

Further the ' get-config --source running --filter-xpath  /sysrepo-dnsmasq:dnsmasq-cfg'
works properly. 
Is there something I am missing ? Do correct me if I am doing something astray.

**Comment by rajanishWanderer** [comment]
<dnsmasq-cfg xmlns="urn:ietf:params:xml:ns:yang:dnsmasq">
        <dhcp-server>
                <dhcp-pool>
                        <start-addr>192.168.1.70</start-addr>
                        <end-addr>192.168.1.80</end-addr>
                        <lease-time>1000</lease-time>
                </dhcp-pool>
        </dhcp-server>
</dnsmasq-cfg>

This is the configuration I am trying to set.

**Comment by michalvasko** [comment]
Hi,
the error does not seem to be a *sysrepo* or *netopeer2-server* error so I cannot really help you. Anyway, if you want to learn and understand how to write sysrepo plugins/daemons then I would point you to Developer Guide/Getting Started in the current sysrepo `devel` branch documentation (you may have to generate it yourself with `make doc` as it has been merged just now). This dnsmasq demo is ancient.

Regards,
Michal
