### ISSUE TITLE
op_generic.c has a bug

### ISSUE THREAD

**Issue by bmenasin** [CESNET/Netopeer2#219]
for (i = 0; i < set->number; ++i) {
            if (set->set.d[i]->dflt) {
                --in_count;
                continue;   **-------------------> index i will not be contiguous**
            }

if (op_set_srval(set->set.d[i], lyd_path(set->set.d[i]), 0, &input[i], &str)) {    **----> input[i] is not correct as index i might not be contiguous**

I solved in my view by adding a new variable for index in input. Not sure if it is the correct way but solves my issue with rpc input.

Please look into this issue and either provide fix or let me fix it.

**Comment by michalvasko** [comment]
Hi,
you are right, please try it with the fix.

Regards,
Michal

**Comment by bmenasin** [comment]
Thanks for fixing this issue.

Regards,
Raj
