### ISSUE TITLE
Query: How to subscribe for operational data...

### ISSUE THREAD

**Issue by KarthikaElamathy** [CESNET/netopeer2#220]
Hi,
I introduced a operational data in my yang file

  container switch {
    description
      "switch and attributes";

    leaf id {
      type string;
      description
        "A unique but locally arbitrary identifier that uniquely identifies a
         switch";
    }

    container  some-arbitrary-container {
      description
        "-----";
      config false;

      leaf some-arbitrary-leaf {
        type uint32;
        default 0;
        description
          "----";
      }
    }

I tried to register the callback for this operational state data in the Netopeer2-server application the following way. 
rc = sr_dp_get_items_subscribe(session, /switch/some-arbitrary-container/some-arbitrary-leaf, subtree_arbitrary_cb, (void*)&callback_called, SR_SUBSCR_CTX_REUSE, &np2srv.sr_subscr);

For some reason,  when i do get operation from the netopeer2-cli, this callback is never triggered. 

What am i missing here ?

**Comment by michalvasko** [comment]
Hi,
try `oper_data_example` in the examples, it should work and do what you want to do. You can then modify the example/your program to fit your use-case. It is possible you cannot perform such a subscription on the *netopeer2* sysrepo session, it is not a standard one.

Regards,
Michal

**Comment by karthikakrishnamurthy** [comment]
Hi,

Thank you. It is not working with Netopeer2. Does this mean that there is no way to get operational data through Netopeer2 ?

**Comment by michalvasko** [comment]
Hi,
you should always be able to start a new standard session and use that one.

Regards,
Michal

**Comment by karthikakrishnamurthy** [comment]
Hi,

Thanks again. Is there any documentation where i could read more about this "standard session". I am not sure whether i understood why operational data is not working with same session of Netopeer2 completely. 

Regards,
Karthika

**Comment by michalvasko** [comment]
Hi Karthika,
actually, I don't know what session you are using for the subscription. I was only talking about sessions started with `sr_session_start_user` instead of just `sr_session_start`.

Anyway, do you really need to modify *neopeer2-server* code? It should work, but it is always better to keep your modules separate (for simple netopeer2 updates, for instance).

Regards,
Michal

**Comment by karthikakrishnamurthy** [comment]
Hi,

I am not modifying netopeer2-server code exactly. I am subscribing  for different xpaths in netopeer2-server (main.c file) and calling the SDK functions in the callbacks to configure my switch.  I hope this is right.  Please let me know if this is wrong idea. 

Sorry to trouble you again... 
I read about sr_session_start_user and sr_session_start in sysrepo documentation.  I am (netopeer-server is) using sr_session_start  to connect between sysrepo and netopeer2-server and so sr_session_start is the one that is used for subscription.  Even the example what you shared uses sr_session_start. 

Anyways i will check again whether i am subscribing properly

**Comment by michalvasko** [comment]
Hi,
for one, you **are** modifying *netopeer2-server* code, `main.c` is the **main** server file. Secondly, I was talking about sessions started with `sr_session_start_user` as being the non-standard ones, `sr_session_start` is the common function that should almost always be used.

For your problem, you do have the wrong idea, do not add your subscriptions into the server code (I have actually looked into `main.c` and found no suitable place to put the subscription into - that is likely why it is not working for you). You want to create a [sysrepo](https://github.com/sysrepo/sysrepo) plugin or daemon (`oper_data_example.c` is a daemon) that will manage your switch.

Regards,
Michal

**Comment by karthikakrishnamurthy** [comment]
Hi,

Thank you.  This helped a lot. I will change code accordingly. 

Regards,
Karthika
