### ISSUE TITLE
Query: What is wrong with ianaift:ethernetCsmacd ?

### ISSUE THREAD

**Issue by psch-k** [CESNET/Netopeer2#222]
Hi,
when I check an interface of a remote netconf client, I get an error:
`ly ERROR: Invalid value "ianaift:ethernetCsmacd" in "type" element. (/ietf-interfaces:interfaces/interface[name='eth1']/type)
nc ERROR: Failed to parse <get-config> reply.
`
I cannot see what is wrong with this value.

Some additional information which i think may be helpful:
I just started with netconf management, till now I used snmp for this kind of tasks.
On a fedora 26 system, I installed libyang, sysrepo, libnetconf2, netopeer2 and the required stuff around it. The first test was to start sysrepod / sysrepo-plugind / netopeer2-server and connect with it (locally) with netopeer2-cli (I made no changes, I just used the system as it was after installation), which seems to work so far (doing some 'get' and 'get-config').
Next test was to connect with a 'real' netconf managed device (which uses the 'old' libnetconf and netopeer via TLS). The connection succeeded, but trying to get some information about an interface, I get the error mentioned above.
I am not sure, whether I missed some declaration or configuration, or whether this is an error. If this is an error, I am not sure whether the error is in netopeer2, libnetconf2 or libyang. Can anybody point me in a promising direction?
I attached the log of a session, maybe this helps.
Thank You in Advance,
Peter
[netopeer2-cli.log](https://github.com/CESNET/Netopeer2/files/1720800/netopeer2-cli.log)

**Comment by michalvasko** [comment]
Hi Peter,
the problem is (seen in the output) that `ianaift` XML namespace declaration is missing. This is one of the many problems of the old *netopeer-server* and *libnetconf* so all I can do is suggest you update the *netopeer* on your device and use *netopeer2*.

Regards,
Michal

**Comment by psch-k** [comment]
Hi Michal,
thank you very much for the fast reply. It is the answer, I was afraid of (I cannot change the netopper-server device I used). I double-checked 'my' example with a completely different device, which also uses the old libnetconf, but NOT the old netopeer-server; they use the libnetconf-API directly in their own management software. Therefore, I am rather sure that the old libnetconf is the bad guy, not the old netopeer. OK, we shouldn't care about it.

Interoperability with the old netopeer is not a goal of my project, it is just a 'nice to have' for checking / debugging things with a running system as partner. Therefore I think, this issue can be closed.

Kind Regards,
Peter
