### ISSUE TITLE
High Availability

### ISSUE THREAD

**Issue by sandeep-shenoy-mitel** [CESNET/netopeer2#225]
How is high availability acheived on NETOPEER server?

**Comment by michalvasko** [comment]
Hi,
I am not exactly sure what is it you are asking, but I think the answer may be threads? You will have to be more specific.

Regards,
Michal

**Comment by sandeep-shenoy-mitel** [comment]
Is it possible to have a NETOPEER server cluster , so that if one node/server fails the others serve requests. Or is there an ACTIVE/STANDBY configuration so that failure of ACTIVE node is handled with bringing STANDBY in service.

**Comment by michalvasko** [comment]
Oh, you are talking about a cluster environment. Netopeer2 was meant to run on a single machine so in this case you would have to implement the whole distributed platform yourself.

Regards,
Michal
