### ISSUE TITLE
Failed to set hostkey "ssh_host_rsa_key"

### ISSUE THREAD

**Issue by lrodrin** [CESNET/Netopeer2#226]
Hi,

I can't connect netopeer2-cli with netopeer-server.

**SERVER ERROR
netopeer2-server[28562]: Accepted a connection on 0.0.0.0:830.
[2018/02/28 10:13:55.196794, 1] ssh_bind_options_set_algo:  Setting method: no algorithm for method "server host key algo" (/usr/local/etc/keystored/keys/ssh_host_rsa_key.pem)

netopeer2-server[28562]: Failed to set hostkey "ssh_host_rsa_key" (/usr/local/etc/keystored/keys/ssh_host_rsa_key.pem).

CLIENT ERROR
connect
nc ERROR: Starting the SSH session failed (Socket error: disconnected).
cmd_connect: Connecting to the localhost:830 as user "root" failed.**

Can you help me? THX.

Laura.

**Comment by michalvasko** [comment]
Hi Laura,
I have a vague memory of seeing this error with an old *libssh* version, which do you use?

Regards,
Michal

**Comment by lrodrin** [comment]
Hi Michal,

I use 0.7.5 version. 

Regards,
Laura

**Comment by michalvasko** [comment]
Hi Laura,
so that should not be the problem, how did you get the private key? Did you generate it using `keystored` or used some you already had? I am quite lost because what you see is a libssh error (but possibly caused by a problem in our software).

Regards,
Michal

**Comment by lrodrin** [comment]
Hi Michal,

I'm using keystored. But I need to install manually ietf-keystore.yang and ietf-netconf-server.yang using sysrepoctl. Maybe is sysrepo?

If I don't, in make install:

[100%] Built target keystored
Linking C shared library CMakeFiles/CMakeRelink.dir/libkeystored.so
Install the project...
-- Install configuration: "debug"
-- Up-to-date: /usr/local/lib/pkgconfig/keystored.pc
-- Up-to-date: /usr/local/etc/keystored/keys
-- Importing module ietf-x509-cert-to-name into sysrepo...
-- Importing module ietf-keystore into sysrepo...
CMake Error at cmake_install.cmake:96 (message):
    Command sysrepocfg export failed:
    [ERR] Module 'ietf-keystore@<latest>' is not present in the dependency graph.
    [ERR] Module 'ietf-keystore:<latest>' is not installed.
    [ERR] Get module 'ietf-keystore' failed
    [ERR] Getting data tree failed (10) for xpath '/ietf-keystore:*//.'
    [ERR] rp_dt_prepare_data failed
    [ERR] Get items failed for '/ietf-keystore:*//.', session id=1669898316.
    [ERR] Error by processing of the get-items request (session id=1669898316): Requested schema model is not known.
    [ERR] Sending get_items request failed '/ietf-keystore:*//.'
    [ERR] (srcfg_get_module_data:249) Error by sr_get_items_iter: Requested schema model is not known
    Errors were encountered during exporting. Cancelling the operation.

Makefile:61: recipe for target 'install' failed
make: *** [install] Error 1

Thanks,
Laura

**Comment by michalvasko** [comment]
Hi Laura,
that is certainly not necessary, if you stick to the guide in `netopeer2/server/configuration/README.md`. This particular problem is fixed by installing `keystored`, it will also install `ietf-keystore.yang`.

Regards,
Michal

**Comment by lrodrin** [comment]
Hi Michal,

Doesn't work U-U. I will try to fix it. If I have any news i will say it to you.

Thanks for your time and help,
Laura

**Comment by lrodrin** [comment]
It work's if you before install manually:

cp ietf-keystore@2016-10-31.yang /root/sysrepo/build/repository/yang/
cp ietf-netconf-server@2016-11-02.yang /root/sysrepo/build/repository/yang/
cp ietf-x509-cert-to-name@2014-12-10.yang /root/sysrepo/build/repository/yang/
cp ietf-ssh-server@2016-11-02.yang /root/sysrepo/build/repository/yang/
cp ietf-tls-server@2016-11-02.yang /root/sysrepo/build/repository/yang/
cp ietf-system@2014-08-06.yang /root/sysrepo/build/repository/yang/
cp ietf-keystore.persist /root/sysrepo/build/repository/data/
cp ietf-keystore.running /root/sysrepo/build/repository/data/
cp ietf-keystore.running.lock /root/sysrepo/build/repository/data/
cp ietf-keystore.startup /root/sysrepo/build/repository/data/
cp ietf-keystore.startup.lock /root/sysrepo/build/repository/data/

sysrepoctl --install --yang=/root/sysrepo/build/repository/yang/ietf-keystore@2016-10-31.yang --owner=root:root --permissions=666
sysrepoctl --install --yang=/root/sysrepo/build/repository/yang/ietf-netconf-server@2016-11-02.yang --owner=root:root --permissions=666

**Comment by michalvasko** [comment]
Please, post the output of `sysrepoctl -l` before trying to install *keystored* and failing. Also, what *sysrepo* version are you using and from which branch?

Regards,
Michal

**Comment by lrodrin** [comment]
Hi Michal,

The sysrepo master version,

![image](https://user-images.githubusercontent.com/7712795/36837375-81a177c2-1d3c-11e8-95ac-27ed42e67d4e.png)

Regards,
Laura

**Comment by michalvasko** [comment]
Hi Laura,
it would be best if you rebuild and reinstall the whole *sysrepo* before installing *keystored* but it may be enough for you to remove the models `ietf-x509-cert-to-name`, `ietf-keystore`, `ietf-netconf-server`, and `ietf-system` (`# sysrepoctl -u -m <module-name>`). You have done so successfully if they do not show up in the output of `sysrepoctl -l`. If you then try to install *keystored*, it should succeed.

Also, the `sysrepoctl -l` output you posted is invalid because `ietf-keystore`, `ietf-netconf-server`, and `ietf-system` do not have data files. I assume it is the result of your manual installations so please do not do that, you will almost certainly break something that way.

Regards,
Michal

**Comment by lrodrin** [comment]
Hi Michal,

The previous image is the result of:

git clone https://github.com/sysrepo/sysrepo.git
cd sysrepo; mkdir build; cd build
cmake .. && make -j8 && make install

Regards,
Laura.

**Comment by michalvasko** [comment]
Hi Laura,
that is possible only if some old repository was used, *sysrepo* does not include the last 7 models in your output. So, if you look at the first 2 lines of `sysrepoctl -l` output they should look like this
```
Sysrepo schema directory: <schema-path>
Sysrepo data directory: <data-path>
```

The paths should end with `/repository/schema` and `/repository/data`. Best would be if you removed the whole `/repository` directory and try it all again. I guarantee you, if done properly, you will not have `ietf-keystore` or any other from those last models installed.

Regards,
Michal

**Comment by lrodrin** [comment]
ACK Michal, I will try it!

Thank you very much for your time.

Regards,
Laura

**Comment by agva123** [comment]
Hi @lrodrin - did you resolve the issue successfully? I am having the exact same issue as yours and I am stuck searching for solutions. Would appreciate your feedback.

**Comment by lrodrin** [comment]
Hi @agva123,

My problem came from sysrepo, libyang and libnetconf2 old libraries. Using ldconfig -p I found and erased the old and repeated libraries. Then when you re-compile and re-build libyang, libnetconf2, sysrepo and netopeer2 keystored, server and cli was perfect.

For example, I used ldconfig -p | grep libyang. Remove manually the old libraries. And execute again ldcondig for changes.

You need to have something like:
![captura](https://user-images.githubusercontent.com/7712795/39516189-796f588a-4dfc-11e8-8646-9ef1cae405ac.PNG)

**Comment by agva123** [comment]
Problem solved! Thank you @lrodrin for your great suggestion! It looks like ldconfig points to an old version of libssh (4.4.1), while it looks like sysrepo works with libssh 4.5.0. 
After I removed /etc/ld.so.cache and regenerate with sudo ldconfig, and re-run sysrepo and netopeer2, it worked well and I am now able to ssh to port 830. 
Thanks again.

**Comment by lrodrin** [comment]
You are welcome @agva123! I'm glad you've solved the problem :D

Best regards,
Laura.

**Comment by dwdrajesh** [comment]
> Hi @agva123,
> 
> My problem came from sysrepo, libyang and libnetconf2 old libraries. Using ldconfig -p I found and erased the old and repeated libraries. Then when you re-compile and re-build libyang, libnetconf2, sysrepo and netopeer2 keystored, server and cli was perfect.
> 
> For example, I used ldconfig -p | grep libyang. Remove manually the old libraries. And execute again ldcondig for changes.
> 
> You need to have something like:
> ![captura](https://user-images.githubusercontent.com/7712795/39516189-796f588a-4dfc-11e8-8646-9ef1cae405ac.PNG)



> Problem solved! Thank you @lrodrin for your great suggestion! It looks like ldconfig points to an old version of libssh (4.4.1), while it looks like sysrepo works with libssh 4.5.0.
> After I removed /etc/ld.so.cache and regenerate with sudo ldconfig, and re-run sysrepo and netopeer2, it worked well and I am now able to ssh to port 830.
> Thanks again.

Hi,
I seem to have the latest libraries for libyang, libsysrepo, libnetconf2 and libssh (the version numbers might be different from when these were posted on this forum). But I still get this error: **
"Failed to set hostkey "ssh_host_rsa_key" (/usr/local/etc/keystored/keys/ssh_host_rsa_key.pem)."

And here is the 
![1](https://user-images.githubusercontent.com/16168453/49760932-a8f7bc00-fc93-11e8-888e-c1f6582f15e5.png)

**Comment by michalvasko** [comment]
Hi,
well, based on this output you, too, have 2 versions of `libssh` installed so that may be again the problem. You should remove one, run `# ldconfig`, and recompile the applications.

Regards,
Michal

**Comment by dwdrajesh** [comment]
Hi, 
I did a "sudo apt-get purge libssh-4" which succeeded but "sudo apt-get purge libssh" complained "Unable to locate package". 
Anyway I did a reinstall of libssh from source based on this link: (since my Ubuntu 16.04 doesn't support the libssh4 it seems): https://github.com/CESNET/Netopeer2/blob/master/.travis-install-libs.sh .

But the issue still occurs. 
Here is what I get even now if i check ldconfig for libssh:

![4](https://user-images.githubusercontent.com/16168453/49809078-03dcf200-fd2c-11e8-8e8e-5ba5d7f36e0a.png)

**Comment by michalvasko** [comment]
Hi,
did you try running just `# ldconfig` to update your links? Anyway, you can actually have 2 `libssh` versions on your system, you just need to make sure *libnetconf2* and *netopeer2* is linked with the right (new) one. You can check that if you run `ldd <binary-path>` on `netopeer2-server`, for example.

Regards,
Michal

**Comment by dwdrajesh** [comment]
Hi Michal,
Thank you very much for replying. Unfortunately, both libnetconf2 and netopeer2-server seem to be using the same version of libssh.so as can be seen in the attached screenshot: 
![4](https://user-images.githubusercontent.com/16168453/49813353-4d7e0a80-fd35-11e8-96eb-3443a1edca75.png)

**Comment by michalvasko** [comment]
Hi,
the key seems fine but please, **DO NOT** use it for any real use-case because you have just compromised it (I forgot to tell you not to paste it here). So, do you know which of the 2 *libssh* versions is the new one? My guess is that *netopeer2* is still not linked with that one. Even when having several shared library versions installed you can force one of them to be used as some flags for compilation.

Regards,
Michal

**Comment by dwdrajesh** [comment]
Hi Michal,
It seems both netconf2 and netopeer2-server are pointing to the same version of libssh. Here is what I get : 
![7](https://user-images.githubusercontent.com/16168453/49878143-e758bc80-fdf4-11e8-8a80-8e214b1c18f8.png)

**Comment by michalvasko** [comment]
Look, what we are solving right now is how to link *libnetconf2* and *netopeer2* with a particular library version (you still have not told me whether `/usr/lib/libssh.so.4` or `/usr/lib/x86_64-linux-gnu/libssh.so.4` point to the new version). That is not a *netopeer2* problem but a generic Linux one so search for the solution rather than waste my time. When you get to the point that you **know for certain** that you are using correct *libssh* version and still get an error, then you can come back and ask us for help. Although I am not sure what would I tell you then because it is working for us and lots of other people. Sorry.

Regards,
Michal

**Comment by dwdrajesh** [comment]
I think when I did an uninstall/purge for libssh-4 , the "ldconfig -p | grep libssh.so" was only showing: /usr/lib/libssh.so (Neither /usr/lib/libssh.so.4 and /usr/lib/x86_64-linux-gnu/libssh.so.4" was shown). This means that both /usr/lib/x86_64-linux-gnu/libssh.so.4 and /usr/lib/libssh.so.4 are installed when we install libssh-4 from source. I am not sure what to look for to tell that either one points to the latest version or if they are both different libraries for either x86_64 ? But anyway both netconf2 and netopeer2 point to the same one: /usr/lib/x86_64-linux-gnu/libssh.so.4.

**Comment by michalvasko** [comment]
Hi,
I doubt installing `libssh` from source would install it to more locations, the problem is in something else.

Regards,
Michal
