### ISSUE TITLE
Question: is TLS call home with intermediate CAs supported?

### ISSUE THREAD

**Issue by darshana-jk** [CESNET/Netopeer2#227]
I have successfully tested the TLS callhome with rootCA (only rootCA)
However when an ICA is involved, it fails with the error:
```
Fri Mar  2 05:20:20 2018 daemon.err netopeer2-server[2406]: Cert verify: fail (unable to get local issuer certificate).
Fri Mar  2 05:20:20 2018 daemon.err netopeer2-server[2406]: SSL_accept failed ((null)).
```
When an ICA/rootCA is used.
i.e. in ietf-keystore datastore: 
```
    <trusted-certificates>
        <name>tls server_trusted_ca_list</name>
        <trusted-certificate>
                <name>my_ica</name>
               <certificate>.ICA cert..</certificate>
        <trusted-certificate>
                <name>root_ca</name>
               <certificate>.rootCA cert..</certificate>
    <trusted-certificates>
```
Is using an ICA supported?

Please let me know I will provide more information on other involved modules.
Darshana.

**Comment by michalvasko** [comment]
Hi Darshana,
I believe it should work. Can you post the certificate chain you are using? What is the client certificate, what are the certificates up to the root CA and which certificates you have configured as trusted.

Regards,
Michal

**Comment by darshana-jk** [comment]
Hi Michal,

Yes it works. I tested with both server and clients having different cert chains (having ICAs).
It must be some thing wrong with the original certs I used.

Regards,
Darshana.
