### ISSUE TITLE
How to handle sysrepo-plugind crash?

### ISSUE THREAD

**Issue by mislavn** [CESNET/netopeer2#228]
If sysrepo-plugind crashes the NETCONF server will not return any message.

You can test this with the plugin turing-machine by editing:
```
--- a/examples/plugins/turing-machine.c
+++ b/examples/plugins/turing-machine.c
@@ -52,6 +52,8 @@ module_change_cb(sr_session_ctx_t *session, const char *module_name, sr_notif_ev
 {
     SRP_LOG_DBG_MSG("turing-machine configuration has changed.");
 
+    printf("string_val %s\n", ((sr_val_t *) private_ctx)->data.string_val);
+
     retrieve_current_config(session);
 
     return SR_ERR_OK;

```

After some NETCONF edit command the sysrepo-plugind will crash and NETCONF client will not get any message returned.

**Comment by michalvasko** [comment]
Hi,
having the referenced pull request merged, the client should receive time out error in case `sysrepo-plugind` crashes. I am not sure what more is there to do. Did you have something in mind?

Regards,
Michal

**Comment by mislavn** [comment]
Hi,

I think a time out error is enough for now, thank you.

Regards,
Mislav

**Comment by rkrejci** [comment]
Well, I had something else in my mind. In case a sysrepo plugin crashes, it should be limited only to the plugin. Now, it affects all the plugins by shutting down the sysrepo-plugind. The daemon (libsysrepo) should check for the plugin crash when using its callbacks and in case of crash it should return an error and switch of the specific plugin while the others are still working fine.

**Comment by mislavn** [comment]
If it's not a problem to implement that would be great to have.

Should I reopen this issue then?

**Comment by michalvasko** [comment]
We will see how big a challenge will it be.
