### ISSUE TITLE
Netconf ssh login radius Authentication

### ISSUE THREAD

**Issue by dongyangf** [CESNET/Netopeer2#230]
Hi All，

The Netconf authentication username code is invoked by the following function:

Netopeer2:
Worker_thread->nc_accept

Libnetconf2:
Nc_accept->nc_accept_ssh_session->nc_sshcb_auth_password-> auth_password_get_pwd_hash-> getpwnam_r

The getpwnam_r system function gets the user name and password from /etc/passwd, then calls auth_password_compare_pwd to verify the password, then returns the result of auth.

Use the Linux local username password to authenticate.
If radius authentication is to be implemented, I understand that libnetconf2 can only be modified;

Whether the above description is correct？

Thanks, Dongyang

**Comment by michalvasko** [comment]
Hi,
yes, to implement *radius* authentication for SSH `password` authentication you would have to write your own `nc_sshcb_auth_password`.

Regards,
Michal

**Comment by dongyangf** [comment]
Hi Michal,

Can you provide a callback function interface for Raduis/TACACS validation? In this way, we don't have to modify the libnetconf code.

Regards,
Dongyang

**Comment by liyi0** [comment]
Hi，Michael，
    we modified function nc_sshcb_auth_kbdint() and nc_sshcb_auth_password() to support aaa-server authentication. But when tried to login using netopeer cli, it still failed.

[root@x86-2 /home/fandy/shasta/apps_pub/netopeer2/cli/build]# ./netopeer2-cli 
> connect --login guangjung01 --host 172.16.166.252 --port 830
Interactive SSH Authentication
Type your password:
Password: 
nc ERROR: Session 3: SSH channel unexpected EOF.
nc ERROR: Session 3: failed to send request for yang-library data.
nc ERROR: Session 3: invalid session, discarding.
cmd_connect: Connecting to the 172.16.166.252:830 as user "guangjung01" failed.

    The aaa-server authentication was successful.  But the SSH channel still failed.
    Please give some advice.
    Thanks a lot.

**Comment by michalvasko** [comment]
Hi,
please try the most recent *libnetconf2* and use `nc_server_ssh_set_passwd_auth_clb` to set your own `passwd` callback (you will have to modify *netopeer2-server*). We may add more options and callbacks later.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
what exactly is the problem? If you set your own authentication callbacks in *libnetconf2*, you can do whatever verification you want in them and accept only specific username/password pairs.

Regards,
Michal

**Comment by reuben3010** [comment]
Hi Micheal,
Thanks for the feedback. Actually my problem has been fixed. I was using the wrong ip address, instead of the IP address
Registered in the radius server. I appreciate the reply.

**Comment by ezehreubenccie** [comment]
Please I need help too. I cannot get an established netconf session to my Cisco 4331 isr router. 

I use aaa configuration that uses a windows 2016 server. Regular ssh connections work but netconf doesn’t work even though it is configured correctly on the router. when I enter ssh -p 830 user@router-name or IP address, I get permission denied.

when I took out the aaa authentication I had no problems. So it looks like there is a configuration missing on the radius server. I have researched online, opened Cisco tickets, still no success. I am beginning to think that netconf and restconf only work with local creds or Cisco ISE  not Windows radius(Network policy server). Please any help will be appreciated.

**Comment by michalvasko** [comment]
I fail to see the connection to *netopeer2* and how exactly are we supposed to help.
