### ISSUE TITLE
subscribe  notifications error

### ISSUE THREAD

**Issue by dongyangf** [CESNET/Netopeer2#231]
> subscribe --filter-xpath /ietf-netconf-notifications
OK
> subscribe --filter-xpath /notifications
ERROR
        type:     protocol
        tag:      in-use
        severity: error
        message:  Already subscribed.

> 

Thanks, Dongyang

**Comment by michalvasko** [comment]
Hi,
you cannot have more subscriptions on one session, the error is quite clear ([RFC](https://tools.ietf.org/html/rfc5277#section-6.5) ref - we send another error but I think ours is much clearer).

Also, the XPath filters you use are wrong, you would not get any notifications. What you probably meant is `--filter-xpath /ietf-netconf-notifications:*` which you could have done simply by specifying the stream `--stream ietf-netconf-notifications`. To subscribe to both modules you could use `--filter-xpath "/ietf-netconf-notifications:* or /notifications:*"`.

Regards,
Michal

**Comment by dongyangf** [comment]
Hi Michal,
Thank you very much!
Regards,
Dongyang
