### ISSUE TITLE
SSH authentication issue with netopeer2-server

### ISSUE THREAD

**Issue by agva123** [CESNET/Netopeer2#240]
Hi,

I was installing netopeer2-server and sysrepo in an embedded platform. Both servers came up fine. However when I try an ssh to the server from outside, using the following command:

ssh ncuser@192.168.1.10 -p 830

 I hit the following error from server side:

netopeer2-server[544]: Accepted a connection on 0.0.0.0:830.
[2017/10/18 12:41:30.571123, 1] ssh_bind_options_set_algo:  Setting method: no algorithm for method "server host key algo" (/etc/ssh/ssh_host_rsa_key)

netopeer2-server[544]: Failed to set hostkey "default" (/etc/ssh/ssh_host_rsa_key).

Same error if I use netopeer2-cli to connect and the error on the cli shows:
> connect
nc ERROR: Starting the SSH session failed (Socket error: Connection reset by peer).
cmd_connect: Connecting to the localhost:830 as user "ncuser" failed.

Btw it runs all fine on x86 Linux.

Could anyone shed some light on to it?

Thank you.

**Comment by agva123** [comment]
Problem solved with help from the community. I posted my solution on another thread.

Problem solved! Thank you @lrodrin for your great suggestion! It looks like ldconfig points to an old version of libssh (4.4.1), while it looks like sysrepo works with libssh 4.5.0.
After I removed /etc/ld.so.cache and regenerate with sudo ldconfig, and re-run sysrepo and netopeer2, it worked well and I am now able to ssh to port 830.

**Comment by wyb1249** [comment]
@agva123 I receive the same problem, and Problem solved.
by the way，log as：
‘
root@switch2:/usr/local/lib# VERBOSE: Accepted a connection on 0.0.0.0:830.
ERROR: inet_ntop failed (No space left on device).
[2018/07/20 05:39:04.971238, 1] ssh_bind_options_set_algo:  Setting method: no algorithm for method "server host key algo" (/etc/ssh/ssh_host_rsa_key)

ERROR: Failed to set hostkey "default" (/etc/ssh/ssh_host_rsa_key).
’

**Comment by dwdrajesh** [comment]
Hi @agva123 , is there any way to check which version of libssh the sysrepo and netconf is using? I can see that there is only one version installed on my system through ldconfig:
ldconfig -p | grep libssh:
	libssh.so.4 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssh.so.4
	libssh.so.4 (libc6,x86-64) => /usr/lib/libssh.so.4
	libssh.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssh.so
	libssh.so (libc6,x86-64) => /usr/lib/libssh.so

But I remember having to install the latest libssh (from source since Ubuntu 16.04 only supports an older version).
Also, I am looking at the netconf code since the error line "Failed to set hostkey" is coming from "libnetconf2/src/session_server_ssh.c line 1315" after it fails to add hostkeys.
 Thanks

**Comment by michalvasko** [comment]
Hi,
you can learn that with `ldd <path-to-binary>`. You want to check your *netopeer2-server* because *sysrepo* itself does not use `libssh`.

Regards,
Michal
