### ISSUE TITLE
Copy config failing when key names contain slashes

### ISSUE THREAD

**Issue by pfeige** [CESNET/netopeer2#242]
Hi,

with the modified testcase in this commit https://github.com/frimpler/Netopeer2/commit/95f3fa0434a3cdcd10a68054e4be05f0e5b6972c an issue in copy-config is shown.

### Description

When a XPATH expression contains key names with slashes the consisting nodes are not found properly using the function strrchr().

### Proposed Solution

The proposed solution https://github.com/frimpler/Netopeer2/commit/476d304a39376ac80193bc95166126e6a8295f17 considers the quotes for key names to skip unwanted slashes.

Regards,
Peter

**Comment by michalvasko** [comment]
Hi Peter,
the problem is there and your solution seems fine, will you please provide a pull request?

Regards,
Michal
