### ISSUE TITLE
netopper2 registering applicable callback for rpc

### ISSUE THREAD

**Issue by Rohit2387** [CESNET/netopeer2#244]
Hi,

Is there any document avl that i can read to know how to register callback which will be invoke for particular rpc ,how to pass data to callabck
And how to send data back(application data) to client(netooper2-cli).
for example:if get is trigger i want my register callback should be invoked.
And how i can return data that can be send as get response.

**Comment by smalls12** [comment]
You're probably better off looking at the sysrepo github page since that is where most of the heavy lifting will be occurring.

Look in the examples directory.

**Comment by Rohit2387** [comment]
OK.callback registration part also i will find in sysrepo example code?

**Comment by michalvasko** [comment]
Hi,
so you want to write your own NETCONF server? We have not documented that, so I would point you to our implementation, `netopeer2-server`. But strictly speaking you only need `libnetconf2`.

Regards,
Michal
