### ISSUE TITLE
netopeer2-cli return error when run subscribe command

### ISSUE THREAD

**Issue by caizhiyu** [CESNET/netopeer2#247]
when I ran the subscribe command in the netopeer2-cli it returned some errors：
root@OpenWrt:/etc/sysrepo/yang# netopeer2-cli 
> connect 
Interactive SSH Authentication
Type your password:
Password: 
> subscribe 
nc ERROR: Session 2: missing "notifications" schema in the context.
cli_send_recv: Failed to send the RPC.
what does this error mean?

**Comment by babukt** [comment]
Observed the same issue even though I have installed yangs in Sysrepo. 

> subscribe --stream NETCONF
nc ERROR: Session 24591: missing "notifications" schema in the context.
cli_send_recv: Failed to send the RPC.

Not sure where netopeer2-cli is expecting to setup the schema context.

root@Attella-ODL-Server:/home/attella/orm_yangs# sysrepoctl --list
Sysrepo schema directory: /etc/sysrepo/yang/
Sysrepo data directory:   /etc/sysrepo/data/
(Do not alter contents of these directories manually)

Module Name                  | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
ietf-netconf-notifications   | 2012-02-06 | Installed   | root:root           | 666         |                               |
ietf-netconf                 | 2011-06-01 | Installed   | root:root           | 666         |                               | writable-running candidate rollback-on-error validate startup xpath url
ietf-netconf-acm             | 2018-02-14 | Imported    |                     |             |                               |
nc-notifications             | 2008-07-14 | Installed   | root:root           | 666         |                               |
notifications                | 2008-07-14 | Installed   | root:root           | 666         |                               |
turing-machine               | 2013-12-27 | Installed   | root:root           | 666         |                               |
iana-if-type                 | 2014-05-08 | Installed   |                     |             |                               |
ietf-interfaces              | 2014-05-08 | Installed   | root:root           | 666         |                               |
ietf-ip                      | 2014-06-16 | Installed   |                     |             |                               |
ietf-netconf-with-defaults   | 2011-06-01 | Installed   |                     |             |                               |
ietf-netconf-monitoring      | 2010-10-04 | Installed   | root:root           | 666         |                               |
ietf-yang-library            | 2018-01-17 | Installed   | root:root           | 666         |                               |
ietf-datastores              | 2017-08-17 | Imported    |                     |             |                               |

root@Attella-ODL-Server:/home/attella/orm_yangs#

**Comment by michalvasko** [comment]
Hi,
what platform are you on, how did you install *sysrepo* and *netopeer2-server*?

Regards,
Michal

**Comment by babukt** [comment]
> Hi,
> what platform are you on, how did you install _sysrepo_ and _netopeer2-server_?
> 
> Regards,
> Michal

I installed on Ubuntu... I followed steps mentioned in the below links.

https://github.com/CESNET/Netopeer2/tree/master/server
https://github.com/sysrepo/sysrepo/blob/master/INSTALL.md

**Comment by michalvasko** [comment]
Hi,
I have just quickly tried it on Ubuntu 18.04 and when I simply compiled and installed current `master` *libyang*, *sysrepo*, *libnetconf2*, and *netopeer2-server*, it worked fine. That means you have something wrong with you installation, perhaps 2 installations with different paths? You can check that with `# ldconfig -p | grep libsysrepo`.

Regards,
Michal

**Comment by babukt** [comment]
Hi Michal,

I hope sysrepo is installed in a single path.

root@server:~# ldconfig -p | grep libsysrepo
	libsysrepo.so.0.7 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libsysrepo.so.0.7
	libsysrepo.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libsysrepo.so

I'm on Ubuntu 16.04.

And another point to add.. on netopeer2-cli,  I don't see any data printed for get-config as well, but device is sending response for the request. 
I'm using cli to connect an external netconf server, not the netopeer2 server. 

Wil try re-install again, Do you suspect any other issue?

**Comment by michalvasko** [comment]
Hi,
I am confused now, you are connecting with `netopeer2-cli` to some other NETCONF server? Then it does not have anything to do with *sysrepo*. Or are you talking about 2 issues? Then you should have created a new issue. Please, first clear this up before I can help you further.

Regards,
Michal

**Comment by babukt** [comment]
I'm connecting to external netconf server not, netopeer2-server.

1. netopeer2-cli is successful in connecting to server
2. I don't see any data printed for get-config, even though netconf server is sending the response
3. Not able to send create-subscription

subscribe --stream NETCONF
nc ERROR: Session 24591: missing "notifications" schema in the context.
cli_send_recv: Failed to send the RPC.

**Comment by michalvasko** [comment]
Hi,
can you post the output of `status` once you connect using *neotpeer2-cli*? Actually, the output, if any, of the `connect` command itself may also be helpful. As for your problem `2.`, it depends what the server responds with, they may only be default data (which CLI can print but does not by default) or their schema is not loaded in the client (and you should be warned about this).

Regards,
Michal
