### ISSUE TITLE
libnetconf2 usage

### ISSUE THREAD

**Issue by Rohit2387** [CESNET/netopeer2#250]
Hi,

How i can use libnetconf2 for different netconf operation.What all API provided by libnetconf2 how i will come to know?
For example 
API for responding hello message?
API for responding get message?
API to specify listening port for request?
Basically i want to know how i can start libnetconf2 usage.

**Comment by michalvasko** [comment]
Hi,
there is basic documentation for *libnetconf2* but you must generate it yourself with `make doc`. However, we expect almost everyone to use *netopeer2* so there may be some things missing. That being said, I would further refer you to `netopeer2-server` with things you will not understand from the documentation. Look at its code and try to understand how it works.

Regards,
Michal
