### ISSUE TITLE
notification can't be send out while netopeer is handling rpc

### ISSUE THREAD

**Issue by qmm161** [CESNET/Netopeer2#256]
_nc_server_notif_send_ return **NC_MSG_WOULDBLOCK** when try to lock session failed by calling _nc_session_lock_, and then the notification will be free.

**Comment by michalvasko** [comment]
Hi,
you can now adjust the notification timeout if 5 seconds is not enough.

Regards,
Michal

**Comment by qmm161** [comment]
Hi,
this would block sysrepo client thread for too long time.

**Comment by michalvasko** [comment]
Hi,
we have given it some thought and it should not be too difficult to implement almost full concurrency between RPCs and notifications. I will let you know when it is finished.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
you can try the lateste `devel` libnetconf2, it should allow netopeer2 to process notifications and RPCs almost independently.

Regards,
Michal

**Comment by qmm161** [comment]
Hi,
thanks, I will merge the commit to our project.

**Comment by michalvasko** [comment]
Hi,
just note that I have tested in only briefly and it was quite a big change in *libnetconf2* so the implementation may potentially have some major bugs that will need fixing.

Regards,
Michal
