### ISSUE TITLE
The netopeer2-cli copy-config doesn't take effect

### ISSUE THREAD

**Issue by darcyllingyan** [CESNET/Netopeer2#263]
Hi,
I have import some XML data to the startup datastore, I want to copy it to the running datastore, but it doesn't take effect, can anyone give some suggestion? Thanks！

**Comment by michalvasko** [comment]
Hi,
I would need much more information, best all required for reproducing it (the YANG model, `startup` datastore content, command you used, what was its output). However, do you have `running` enabled, have any active subscriptions to it?

Regards,
Michal

**Comment by darcyllingyan** [comment]
The running isn't enabled, will use the devel-branch and enable the running to test again.
