### ISSUE TITLE
Before write the data to datastore, I want to add some callback for users to handle the data, such as validation, read, whether there is doc for me to refer

### ISSUE THREAD

**Issue by darcyllingyan** [CESNET/Netopeer2#266]
Hi,
Based on the edit-config, the data could be written to sysrepo, I want to know if I want to add some callback functions for users to handle the new data, such as validation, read(couldn't write), whether there is some examples for me to refer?

Thanks
Darcy

**Comment by michalvasko** [comment]
Hi Darcy,
all of this is handled outside *netopeer2*, in *sysrepo*. So, there is a fairly decent [documentation](http://www.sysrepo.org/static/doc/html/index.html) and many examples in `sysrepo/examples`.

Regards,
Michal

**Comment by darcyllingyan** [comment]
Hi Michal,
Thanks very much for the response, I will refer to it.

Thanks
Darcy
