### ISSUE TITLE
Get with selection node subtree filter returns an empty tree when the selection node is a key

### ISSUE THREAD

**Issue by alangefe** [CESNET/Netopeer2#267]
When the selection node in a subtree filter corresponds to a node that is a key, an empty tree will be returned in a response to a get, even if there are valid matching nodes in the datastore.

I've created a unit test in alangefe/netopeer2@af946dc that demonstrates the use case and the expected behavior.

The change in behavior was introduced in 9e793f1. In prior commits this use case is working correctly. The nodes are being omitted due to the new call to `opget_build_subtree_from_sysrepo_is_key()` from `opget_build_subtree_from_sysrepo()`.

**Comment by michalvasko** [comment]
Hi,
I did not thought about this use case when making the optimization, so I reverted it, thanks.

Regards,
Michal
