### ISSUE TITLE
nacm support details required

### ISSUE THREAD

**Issue by sheetaljoshi** [CESNET/Netopeer2#270]
Hi,

I am trying to find out more details about NACM support provided, but I can't find any documentation or links to enabling nacm feature. I followed sysrepo guide (https://github.com/sysrepo/sysrepo/blob/1ce49fa5b9f88d105fed1dca0a1dcf2416131248/INSTALL.md) to compile with NACM but it doesn't help (https://github.com/sysrepo/sysrepo/issues/1155). 

Let me know there are any links or documents that can help enable NACM feature.

Thanks,
Sheetal

**Comment by michalvasko** [comment]
Hi Sheetal,
like you mentioned, NACM is technically *sysrepo* feature so we can discuss it in the other issue.

Regards,
Michal
