### ISSUE TITLE
netopeer2-server cant connect to onos/odl

### ISSUE THREAD

**Issue by yuliya2017** [CESNET/Netopeer2#276]
Hi all I would be grateful if you can please help me with the problem. 
I am using Netopeer2 and Sysrepo to connect a device to ONOS or ODL controllers, however any time I push configurations about the device (such as ip addr, port, username, password) to controllers netopeer2-server gets an error.  (please check the file for error).
I cant seem to find a solution. I have installed everything from scratch to get latest versions of code, but error is still there. 

[netopeer2-server_error_on_connecting _to_controller.txt](https://github.com/CESNET/Netopeer2/files/2090714/netopeer2-server_error_on_connecting._to_controller.txt)

Thank you kindly for your help. 
Yuliya

**Comment by swathins079** [comment]
please use the latest version of libssh.

Regards,
Swathin

**Comment by yuliya2017** [comment]
I have re-downloaded and recompiled everything  again, and error is still there. What else can I try to get rid of this problem?

Thank you.
Yuliya

**Comment by michalvasko** [comment]
Hi,
you did not have to redownload and recompile all the applications, just *libssh*, did you? What version are you using?

Regards,
Michal

**Comment by yuliya2017** [comment]
Hi Michal, 
I know I didn't have to redo everything, i did it to make sure everything was up to date. 
The libssh version i am using is Libssh: 0.7.9 , Netopeer2: 0.5.24, sysrepo: 0.7.4

Thank you
 Yuliya

**Comment by michalvasko** [comment]
Hi Yuliya,
I am still leaning towards *libssh* causing the issue (based on the output, it crashes during `ssh_handle_key_exchange()`). The last release was version 0.7.5 so you must be using some unofficial one. Please, install libssh 0.7.5 and try again.

Regards,
Michal

**Comment by yuliya2017** [comment]
Hi  Michal,
Thank you very much for your help. You were correct it was libssh version mismatch. I used the command "git clone http://git.libssh.org/projects/libssh.git" from https://github.com/CESNET/libnetconf2 to install the library. But for some reason using this command it downloaded wrong version of libssh, when i downloaded libssh zip from the https://git.libssh.org/projects/libssh.git/ it all worked. 
Thank you for your help.

Yuliya

**Comment by michalvasko** [comment]
Hi Yuliya,
glad to hear that.

Regards,
Michal

**Comment by anabel1012** [comment]
Hi @yuliya2017 
Having same problem, could you tell me which versions of netopeer2, libyang, libnetconf2, sysrepo and libssh you have?

Thank you,
Ana
