### ISSUE TITLE
Unexpectedly getting SSH_MSG_DISCONNECT

### ISSUE THREAD

**Issue by rosy8** [CESNET/netopeer2#277]
Hi Michal,

I am getting " Received SSH_MSG_DISCONNECT"  even though I have not sent any terminate request .
Would you please let me know why I am getting so ?

netopeer2-server[18527]: All data nodes and constraints resolved.
netopeer2-server[18527]: Session 1: thread 1 event new RPC.
netopeer2-server[18527]: Received a realtime notification "/xxx-system:config" (1528824627).
<b>[2018/06/12 12:30:30.067786, 1] ssh_packet_disconnect_callback:  Received SSH_MSG_DISCONNECT: 11:Closed due to user request. </b>
[2018/06/12 12:30:30.068658, 1] ssh_socket_exception_callback:  Socket exception callback: 2 (-8191)
[2018/06/12 12:30:30.069119, 1] ssh_socket_exception_callback:  Socket error: Unknown error -8191
<b>netopeer2-server[18527]: Session 1: communication socket unexpectedly closed.</b>
<b>netopeer2-server[18527]: Session 1: failed to write reply.</b>
netopeer2-server[18527]: Session 1: thread 3 event new RPC.
netopeer2-server[18527]: Session 1: thread 3 event session terminated.
netopeer2-server[18527]: Received a realtime notification "/ietf-netconf-notifications:netconf-config-change" (1528824630).
netopeer2-server[18527]: Received a realtime notification "/ietf-netconf-notifications:netconf-session-end" (1528824630).
netopeer2-server[18527]: Generated new event (netconf-session-end).
netopeer2-server[18527]: Received a realtime notification "/ietf-netconf-notifications:netconf-config-change" (1528824630).

Regard's
Rosy

**Comment by rosy8** [comment]
Hi Michal,

Output of what ? 

Regard's
Rosy

**Comment by rosy8** [comment]
Hi Michal,

Following the sysrepo logs..which may be helpful to you..

[INF] Resuming commit with id 64564683 continue with write
[INF] Unlock datastore request
[INF] Unlock datastore request
[INF] Dropping session id=420563133.
[INF] Commit id 64564683 received all notifications
[INF] Unlock datastore request
[INF] Data file /etc/sysrepo/data/xxx-config.running loaded successfully
[INF] Data file /etc/sysrepo/data/ietf-netconf-notifications.running is empty
[WRN] Unable to connect to subscriber socket=/var/run/sysrepo-subscriptions/ietf-netconf-notifications/3681.7Hq70J.sock: No such file or directory
[INF] Closing the connection 0x6af660.
[INF] Unlock datastore request
[WRN] Unable to connect to subscriber socket=/var/run/sysrepo-subscriptions/ietf-netconf-notifications/3681.7Hq70J.sock: No such file or directory
[INF] Closing the connection 0x6af660.
[INF] Unlock datastore request
[INF] Dropping session id=1888680785.
[INF] New session created successfully, real user=root, effective user=(null), session id=1738035917.
[INF] Resuming commit with id 728669223 continue with write
[INF] Unlock datastore request
[INF] Unlock datastore request
[INF] Dropping session id=1738035917.
[INF] Commit id 728669223 received all notifications
[INF] Unlock datastore request
[INF] Data file /etc/sysrepo/data/ietf-netconf-notifications.running is empty
[WRN] Unable to connect to subscriber socket=/var/run/sysrepo-subscriptions/ietf-netconf-notifications/3681.7Hq70J.sock: No such file or directory
[INF] Closing the connection 0x6af660.
[INF] Unlock datastore request

Regard's
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
output of the other end meaning a NETCONF client, whatever you are using. It has nothing to do with *sysrepo*, there is no SSH connection to it.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

I am using the MG Soft browser as netconf client.
And there I just get  "Session terminated successfully."

Regard's
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
than I would say your client does not terminate the session properly using `<close-session>` but simply by closing the SSH connection. It is their issue, not ours.

Regards,
Michal
