### ISSUE TITLE
Identityref predicate values do not contain the module name when the module name is the same as the identityref

### ISSUE THREAD

**Issue by bhart3** [CESNET/Netopeer2#279]
### Description
With the below YANG model and snippet, the error that we am seeing is "Identityref predicate value 'melt-cdcr' missing module name". This error is being generated in resolve_partial_json_data_nodeid() in resolve.c in libyang. This problem seems to be caused by commit 310bc58 in libyang that requires an identityref value to be in the format "<module>:<value>". The root cause of this problem seems to be the following:

1) sysrepo sends just value of the identityref if the value of the identityref is in the same module as the identityref itself
2) sysrepo removes the leaf-list predicate from the xpath in rp_dt_create_xpath_for_node() in rp_dt_xpath.c

resolve_partial_json_data_nodeid() seems to get the identityref value either from the xpath or the identityref value, and neither of these has the module name, so this error is reported

This is the yang model that was used to simulate the error.
```yang
module simplified-melt {
  namespace "urn:ietf:params:xml:ns:yang:simplified-melt";
  prefix smelt;
  identity measurement-class;
  
  identity melt-cdcr {
    base measurement-class;
  }
  
  container melt {
    list pmd-profile {
      key name;
      
      leaf name {
        type string;
      }
      
      leaf-list measurement-class {
        type identityref {
          base measurement-class;
        }
        ordered-by user;
      }
    }
  }
}
```

Here is the RPC snippet.
```xml
<melt xmlns="urn:ietf:params:xml:ns:yang:simplified-melt">
  <pmd-profile>
    <name>melt-pmd-01</name>
    <measurement-class>melt-cdcr</measurement-class>
  </pmd-profile>
</melt>
```

Lastly, we noticed that some of the test code in netopeer2 that mimics sysrepo was not that same so this error could not be reproduced on netopeer2 without some code changes.

We had  to change test_edit_get_config.c to fully mimic sysrepo.
```c
int
__wrap_sr_get_item_next(sr_session_ctx_t *session, sr_val_iter_t *iter, sr_val_t **value)
{
    ...
        path = lyd_path(ietf_if_set->set.d[0]);
        /* Copied from sysrepo rp_dt_create_xpath_for_node() */
        
        /* remove leaf-list predicate */
        if (LYS_LEAFLIST & ietf_if_set->set.d[0]->schema->nodetype) {
           char *leaf_list_name = strstr(path, "[.='");
           if (NULL != leaf_list_name) {
               *leaf_list_name = 0;
           } else if (NULL != (leaf_list_name = strstr(path, "[.=\""))) {
               *leaf_list_name = 0;
           }
        }
        /* End copy */
        
        *value = calloc(1, sizeof **value);
    ...
}
```

**Comment by michalvasko** [comment]
Hi,
it should be fixed now. Nevertheless, if you create a pull request with a new *netopeer2* test case, I will be happy to merge it.

Regards,
Michal
