### ISSUE TITLE
Generating header and .yin file from yang file

### ISSUE THREAD

**Issue by rajnkamr** [CESNET/Netopeer2#28]
I see there are multiple yang files in Netopeer2/modules folder

Along with yang files there are .yin files and .h files.
please let me know if these .h and .yin files are generated files.

ietf-netconf@2011-06-01.h
ietf-netconf@2011-06-01.yang
ietf-netconf@2011-06-01.yin
ietf-netconf-acm.h
ietf-netconf-acm.yang
ietf-netconf-acm.yin
ietf-netconf-monitoring.h
ietf-netconf-monitoring.yang
ietf-netconf-monitoring.yin
ietf-netconf-with-defaults@2011-06-01.h
ietf-netconf-with-defaults@2011-06-01.yang
ietf-netconf-with-defaults@2011-06-01.yin

**Comment by rkrejci** [comment]
Yes, they are. In future we probably will remove the YIN files.

**Comment by rajnkamr** [comment]
Is there any way to generate and use it for now

**Comment by rkrejci** [comment]
These files are used only for internal purposes. If you want to have your YANG schema in Netopeer2 server, use [sysrepo](http://www.sysrepo.org/Sysrepo) instead.
