### ISSUE TITLE
Netopeer2 stream subscription fails

### ISSUE THREAD

**Issue by anusha2508** [CESNET/netopeer2#281]
Hi,

We want to use the notification mechanism provided by netopeer2 and sysrepo by subscribing to a specific stream. But we could see few errors while subscribing for a stream. If no stream is specified while subscribing, we could see all kind of notifications, but how can we filter the notifications by subscribing to a specific stream?.

We are using python ncclient module to get the netconf manager connection and using "create-subscription" and "take_notification" api's to subscribe and receive the notifications.

Python program
------------------
m = ncclient.manager.connect_ssh(host='10.10.10.10', port=830, username='user',password='Pass@123',hostkey_verify=False,timeout=120)
m.create_subscription(stream_name='stream-name')

Error
-------
    m.create_subscription(stream_name='streamName')
  File "/usr/local/lib/python2.7/dist-packages/ncclient/manager.py", line 162, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/ncclient/manager.py", line 232, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/ncclient/operations/subscribe.py", line 64, in request
    return self._request(node)
  File "/usr/local/lib/python2.7/dist-packages/ncclient/operations/rpc.py", line 337, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: Unknown element "stream".

Syslog error
-----
Jun 15 18:32:05 ubuntu netopeer2-server[3388]: Unknown element "stream". (/notifications:create-subscription)
Jun 15 18:32:05 ubuntu sysrepod[3377]: [WRN] (cm_subscr_conn_create:1408) Unable to connect to subscriber socket=/tmp/sysrepo-subscriptions/ietf-netconf-notifications/4673.S6aqs8.sock: No such file or directory
Jun 15 18:32:05 ubuntu sysrepod[3377]: [WRN] (cm_subscr_conn_create:1408) Unable to connect to subscriber socket=/tmp/sysrepo-subscriptions/ietf-netconf-notifications/6842.0fdZej.sock: No such file or directory
Jun 15 18:32:05 ubuntu netopeer2-server[3388]: Session 5: SSH channel poll error (Socket error: disconnected).
Jun 15 18:32:05 ubuntu sysrepod[3377]: [WRN] (cm_subscr_conn_create:1408) Unable to connect to subscriber socket=/tmp/sysrepo-subscriptions/ietf-netconf-notifications/4673.S6aqs8.sock: No such file or directory
Jun 15 18:32:05 ubuntu sysrepod[3377]: [WRN] (cm_subscr_conn_create:1408) Unable to connect to subscriber socket=/tmp/sysrepo-subscriptions/ietf-netconf-notifications/6842.0fdZej.sock: No such file or directory

Could someone please provide some inputs on this and also please clarify if the created subscriptions in the netopeer2 are persistent??
Thank You.

Best Regards,
Anusha K

**Comment by michalvasko** [comment]
Hi Anusha,
it should all work as expected. Can you please provide output of `# sysrepoctl -l`? And also of *netopeer2-server* during startup with `# netopeer2-server -d -v2`? Thanks.

Regards,
Michal

**Comment by anusha2508** [comment]
Hi Michal,

Thanks four your response.
Please find the requested outputs in the attachment.

Best Regards,
Anusha K
[netopeer2-server-ouput.txt](https://github.com/CESNET/Netopeer2/files/2113884/netopeer2-server-ouput.txt)
[sysrepoctl-output.txt](https://github.com/CESNET/Netopeer2/files/2113885/sysrepoctl-output.txt)

**Comment by michalvasko** [comment]
Hi Anusha,
the output seems fine. Can you please try to use `netopeer2-cli` to subscribe to a stream? I am not sure where the problem is, maybe ncclient has something wrong so I just want to rule that out.

Regards,
Michal

**Comment by anusha2508** [comment]
Hi Michal,
We have already verified with netopeer2-cli to enable a stream subscription and it is working.
Now we are even able to subscribe for stream using ncclient with xml string format(by specifying stream),
"dispatch" ncclient api is used to send the subscription request for a stream.

Could you please let us know if the active subscriptions for a particular stream can be retrieved using sysrepo client library ??

Best Regards,
Anusha K

**Comment by michalvasko** [comment]
Hi Anusha,
no, neither *sysrepo* nor *netopeer2* do not provide information about active subscription.

Regards,
Michal
