### ISSUE TITLE
Validate rpc with datastore argument segfaults Netopeer2-Client

### ISSUE THREAD

**Issue by gitter-runner** [CESNET/Netopeer2#282]
Hi,
I'm trying out the operations offered by the Netopeer2-cli and I managed to segfault the client while using the validate operation on a datastore. Only the client crashes. When using it with the _--src-config_ argument, it works correctly.

How to reproduce:

Netopeer2-cli:

> validate --help
> _validate [--help] (--source running|startup|candidate | --src-config[=<file>])_
> validate --source candidate
> _Segmentation fault (core dumped)_

Netopeer2-server with highest verbosity:

> _VERBOSE: All data nodes and constraints resolved.
> VERBOSE: Session 1: thread 1 event new RPC.
> [2018/06/15 11:12:37.196298, 1] ssh_socket_exception_callback:  Socket exception callback: 1 (0)
> [2018/06/15 11:12:37.196844, 1] ssh_socket_exception_callback:  Socket error: disconnected
> ERROR: Session 1: SSH channel poll error (Socket error: disconnected).
> VERBOSE: Session 1: thread 2 event session terminated.
> VERBOSE: Generated new event (netconf-session-end)._

Sysrepod:

> _[INF] (rp_dt_refresh_session:1042) No operation has been performed on this session so far
> [INF] (dm_unlock_datastore:1639) Unlock datastore request
> [INF] (sm_session_drop:491) Dropping session id=1929967775._

Sysrepoctl:

> sysrepoctl -l
> _Sysrepo schema directory: /etc/sysrepo/yang/
> Sysrepo data directory:   /etc/sysrepo/data/
> (Do not alter contents of these directories manually)
> 
> Module Name                | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
> -----------------------------------------------------------------------------------------------------------------------------------------------
> ietf-netconf-acm           | 2012-02-22 | Installed   | root:root           | 666         |                               |
> ietf-netconf-notifications | 2012-02-06 | Installed   | root:root           | 666         |                               |
> ietf-netconf               | 2011-06-01 | Imported    |                     |             |                               |
> nc-notifications           | 2008-07-14 | Installed   | root:root           | 666         |                               |
> notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
> turing-machine             | 2013-12-27 | Installed   | root:root           | 666         |                               |
> iana-if-type               | 2014-05-08 | Installed   |                     |             |                               |
> ietf-interfaces            | 2014-05-08 | Installed   | root:root           | 666         |                               |
> ietf-ip                    | 2014-06-16 | Installed   |                     |             |                               |
> ietf-x509-cert-to-name     | 2014-12-10 | Installed   |                     |             |                               |
> ietf-keystore              | 2016-10-31 | Installed   | root:root           | 666         |                               |
> ietf-netconf-server        | 2016-11-02 | Installed   | root:root           | 666         |                               | listen ssh-listen tls-listen call-home ssh-call-home tls-call-home
> ietf-ssh-server            | 2016-11-02 | Imported    |                     |             |                               |
> ietf-tls-server            | 2016-11-02 | Imported    |                     |             |                               |
> ietf-system                | 2014-08-06 | Installed   | root:root           | 666         |                               | authentication local-users
> iana-crypt-hash            | 2014-08-06 | Imported    |                     |             |                               |_

Version (master, debug):
_Libyang 0.15.123
Libnetconf2 0.11.37
Sysrepo 0.7.4
Netopeer2-server 0.5.24_

Best regards,
Tamas

**Comment by michalvasko** [comment]
Hi Tamas,
thanks, is fixed now.

Regards,
Michal
