### ISSUE TITLE
Access with get-rpc to ietf-netconf-monitoring despite NACM rule

### ISSUE THREAD

**Issue by gitter-runner** [CESNET/Netopeer2#286]
Hello,
I'm using the latest Netopeer2-Sysrepo master with nacm enabled. I created a limited group next to an admin group with all permissions granted. I applied two module rules to the limited group, limited users cannot access nacm or monitoring data. See the nacm rules below. Despite this, I managed to access the monitoring data via the netopeer2-cli's get-rpc. The rules worked for the nacm get-rpc, and I did't get any data with get-config either. See log files.

**NACM:**

```
<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
  <groups>
    <group>
      <name>admin</name>
      <user-name>xubuntu12</user-name>
    </group>
    <group>
      <name>limited</name>
      <user-name>netconf</user-name>
    </group>
  </groups>
  <rule-list>
    <name>admin-acl</name>
    <group>admin</group>
    <rule>
      <name>permit-all</name>
      <module-name>*</module-name>
      <access-operations>*</access-operations>
      <action>permit</action>
      <comment>
        Allow the 'admin' group complete access to all
        operations and data.
      </comment>
    </rule>
  </rule-list>
  <rule-list>
    <name>limited-acl</name>
    <group>limited</group>
    <rule>
      <name>deny-ncm</name>
      <module-name>ietf-netconf-monitoring</module-name>
      <access-operations>*</access-operations>
      <action>deny</action>
      <comment>
        Do not allow 'limited' group any access to the NETCONF
        monitoring information.
      </comment>
    </rule>
    <rule>
      <name>deny-nacm</name>
      <module-name>ietf-netconf-acm</module-name>
      <access-operations>*</access-operations>
      <action>deny</action>
      <comment>
        Do not allow 'limited' group any access to the NETCONF
        ACM information.
      </comment>
    </rule>
  </rule-list>
</nacm>
```

**Sysrepoctl:**

> xubuntu12@xubuntu12-VirtualBox:/home/netconf/$ sysrepoctl -l
> Sysrepo schema directory: /home/netconf/sysrepo/build/repository/yang/
> Sysrepo data directory:   /home/netconf/sysrepo/build/repository/data/
> (Do not alter contents of these directories manually)
> 
> Module Name                | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
> -----------------------------------------------------------------------------------------------------------------------------------------------
> ietf-netconf-acm           | 2012-02-22 | Installed   | root:root           | 666         |                               |
> ietf-netconf-notifications | 2012-02-06 | Installed   | root:root           | 666         |                               |
> ietf-netconf               | 2011-06-01 | Installed   | root:root           | 666         |                               | candidate validate
> nc-notifications           | 2008-07-14 | Installed   | root:root           | 666         |                               |
> notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
> turing-machine             | 2013-12-27 | Installed   | root:root           | 666         |                               |
> iana-if-type               | 2014-05-08 | Installed   |                     |             |                               |
> ietf-interfaces            | 2014-05-08 | Installed   | root:root           | 666         |                               |
> ietf-ip                    | 2014-06-16 | Installed   |                     |             |                               |
> ietf-x509-cert-to-name     | 2014-12-10 | Installed   |                     |             |                               |
> ietf-keystore              | 2016-10-31 | Installed   | root:root           | 666         |                               |
> ietf-netconf-server        | 2016-11-02 | Installed   | root:root           | 666         |                               | listen ssh-listen tls-listen call-home ssh-call-home tls-call-home
> ietf-ssh-server            | 2016-11-02 | Imported    |                     |             |                               |
> ietf-tls-server            | 2016-11-02 | Imported    |                     |             |                               |
> ietf-system                | 2014-08-06 | Installed   | root:root           | 666         |                               | authentication local-users
> iana-crypt-hash            | 2014-08-06 | Imported    |                     |             |                               |
> oven                       | 2018-01-19 | Installed   | root:root           | 666         |                               |
> ietf-netconf-monitoring    | 2010-10-04 | Installed   | root:root           | 666         |                               |
> 

**Netopeer2-cli:**
[LOG_netopeer2cli_180621.txt](https://github.com/CESNET/Netopeer2/files/2124033/LOG_netopeer2cli_180621.txt)

**Netopeer2-server:**
[LOG_netopeer2server_180621.txt](https://github.com/CESNET/Netopeer2/files/2124034/LOG_netopeer2server_180621.txt)

**Sysrepod:**
[LOG_sysrepod_180621.txt](https://github.com/CESNET/Netopeer2/files/2124035/LOG_sysrepod_180621.txt)

Versions: master, debug
Libyang 0.15.129
Libssh 0.7.5
Libnetconf2 0.11.37
Sysrepo 0.7.4
Netopeer2-server 0.5.24

Best regards,
Tamas

**Comment by michalvasko** [comment]
Hi Tamas,
that was quite expected with our implementation, should work now correctly (but update *libnetconf2*, *netopeer2*, and also *sysrepo*).

Regards,
Michal
