### ISSUE TITLE
Netopeer2 make install error due to not finding ietf-yang-library.yang

### ISSUE THREAD

**Issue by vhuertas** [CESNET/Netopeer2#287]
Hi all,

After having installed libyang, libnetconf2 and sysrepo, I tried to install netopeer2. Everything seemed to go well until I entered "make install". The following ERROR text was displayed:

root@cuda1:/home/cuda1/git/Netopeer2/server/build> make install
[ 88%] Built target serverobj
[100%] Built target netopeer2-server
Install the project...
Install configuration: "debug"
Up-to-date: /usr/local/bin/netopeer2-server Module ietf-netconf already installed.
Feature writable-running in ietf-netconf already enabled.
Feature candidate in ietf-netconf already enabled.
Feature rollback-on-error in ietf-netconf already enabled.
Feature validate in ietf-netconf already enabled.
Feature startup in ietf-netconf already enabled.
Feature xpath in ietf-netconf already enabled.
Module ietf-netconf-with-defaults already installed.
Module ietf-netconf-monitoring already installed.
Module notifications already installed.
Module nc-notifications already installed.
Module ietf-netconf-notifications already installed.
Installing module ietf-yang-library...
[ERR] libyang: Opening file "/home/cuda1/git/Netopeer2/server/scripts/../../modules/ietf-yang-library.yang" failed (No such file or directory).
Error: Unable to load the module by libyang.
Installing a new module from file '/home/cuda1/git/Netopeer2/server/scripts/../../modules/ietf-yang-library.yang'...
Install operation failed.

I realiazed that in the git repository the ietf-yang-library.yang is not included... Can it be considered as an issue?

Thanks for your attention
Regards,

**Comment by michalvasko** [comment]
Hi,
sorry about that, forgot to commit new files.

Regards,
Michal
