### ISSUE TITLE
After pulling git master and running "make install" of netopeer2 another error is displayed related to ietf-datastores

### ISSUE THREAD

**Issue by vhuertas** [CESNET/Netopeer2#288]
Hi again,

I have updated the git repository. Now the ietf-yang-library.yang missing file issue is solved but another error is displayed. Maybe it has no effect on the final installation but anyway I wanted to post it and let you know.

root@cuda1:/home/cuda1/git/Netopeer2/server/build> make install
[ 88%] Built target serverobj
[100%] Built target netopeer2-server
Install the project...
-- Install configuration: "debug"
-- Up-to-date: /usr/local/bin/netopeer2-server
- Module ietf-netconf already installed.
- Feature writable-running in ietf-netconf already enabled.
- Feature candidate in ietf-netconf already enabled.
- Feature rollback-on-error in ietf-netconf already enabled.
- Feature validate in ietf-netconf already enabled.
- Feature startup in ietf-netconf already enabled.
- Feature xpath in ietf-netconf already enabled.
- Module ietf-netconf-with-defaults already installed.
- Module ietf-netconf-monitoring already installed.
- Module notifications already installed.
- Module nc-notifications already installed.
- Module ietf-netconf-notifications already installed.
- Installing module ietf-yang-library...
[ERR] Module 'ietf-datastores@2017-08-17' is not present in the dependency graph.
[ERR] Module 'ietf-datastores@2017-08-17' is not present in the dependency graph.
[ERR] Module 'ietf-datastores@2017-08-17' is not present in the dependency graph.
[ERR] Module 'ietf-datastores@2017-08-17' is not present in the dependency graph.
[ERR] Module 'ietf-datastores@2017-08-17' is not present in the dependency graph.
[ERR] Module 'ietf-datastores@2017-08-17' is not present in the dependency graph.
[ERR] Module 'ietf-datastores@2017-08-17' is not present in the dependency graph.
[ERR] Module 'ietf-datastores@2017-08-17' is not present in the dependency graph.
[ERR] Module 'ietf-datastores@2017-08-17' is not present in the dependency graph.
[ERR] Module 'ietf-datastores@2017-08-17' is not present in the dependency graph.
[ERR] Module 'ietf-datastores@2017-08-17' is not present in the dependency graph.
[ERR] Module 'ietf-datastores@2017-08-17' is not present in the dependency graph.
Installing a new module from file '/home/cuda1/git/Netopeer2/server/scripts/../../modules/ietf-yang-library.yang'...
Installing the YANG file to '/etc/sysrepo/yang/ietf-yang-library@2018-01-17.yang'...
Installing data files for module 'ietf-yang-library'...
Notifying sysrepo about the change...
Install operation completed successfully.
- Module ietf-keystore not installed, skipping configuration models installation.

Does the ietf-datastores.yang file inclusion forces me to rebuild the sysrepo and netopeer2 code?

Kind regards,

**Comment by michalvasko** [comment]
Hi,
it does have an effect on installation and you need to update *sysrepo* (it was already patched on Friday, this time).

Regards,
Michal
