### ISSUE TITLE
Netopeer server configured over TLS 

### ISSUE THREAD

**Issue by shubhtrix** [CESNET/netopeer2#289]
Able to successfully compile and install Netopeer2 and all it's dependencies. And i'm running the netopeer2-server with example configuration for TLS server upto this part all went well..... 
Possibly Error below might not be a bug to the package but if you people can help me out with the same. Thanks a lot..... 

```
VERBOSE: Resolving "ietf-system" unresolved schema nodes and their constraints...
VERBOSE: All "ietf-system" schema nodes and constraints resolved.
VERBOSE: Module "ietf-system@2014-08-06" successfully parsed as implemented.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/name" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/address" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/port" created.
VERBOSE: Listening on 0.0.0.0:6513 for TLS connections.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/certificates" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/certificates/certificate[name='test_server_cert']/name" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth/trusted-ca-certs" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth/cert-maps" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth/cert-maps/cert-to-name[id='1']/id" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth/cert-maps/cert-to-name[id='1']/fingerprint" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth/cert-maps/cert-to-name[id='1']/map-type" created.
VERBOSE: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='test_tls_listen_endpt']/tls/client-auth/cert-maps/cert-to-name[id='1']/name" created.


VERBOSE: Accepted a connection on 0.0.0.0:6513.
ERROR: np2srv_sr_get_item failed (sysrepo: Item not found).
ERROR: Server certificate callback failed.
ERROR: nc_session_is_connected: internal error (/media/shubh/EXT4_WS/02_INVENTUM/01_RESTCONF/dependencies/libnetconf2/src/io.c:597).
ERROR: nc_session_free: internal error (/media/shubh/EXT4_WS/02_INVENTUM/01_RESTCONF/dependencies/libnetconf2/src/session.c:742).
VERBOSE: Accepted a connection on 0.0.0.0:6513.
ERROR: np2srv_sr_get_item failed (sysrepo: Item not found).
ERROR: Server certificate callback failed.
ERROR: nc_session_is_connected: internal error (/media/shubh/EXT4_WS/02_INVENTUM/01_RESTCONF/dependencies/libnetconf2/src/io.c:597).
ERROR: nc_session_free: internal error (/media/shubh/EXT4_WS/02_INVENTUM/01_RESTCONF/dependencies/libnetconf2/src/session.c:742).
VERBOSE: Accepted a connection on 0.0.0.0:6513.
ERROR: np2srv_sr_get_item failed (sysrepo: Item not found).
ERROR: Server certificate callback failed.
```

**Comment by michalvasko** [comment]
Hi,
firstly, please update libnetconf2, then you will not see any internal errors. Secondly, install `keystored` and then run `sysrepo-plugind` (just as described in the `README`). It should work then.

Regards,
Michal

**Comment by shubhtrix** [comment]
> Ya thanks once again and errors removed with patch on libnetconf2.... 
`
VERBOSE: Accepted a connection on 0.0.0.0:6513.
ERROR: np2srv_sr_get_item failed (sysrepo: Item not found).
ERROR: Server certificate callback failed.
`
> But connection is still not established ..... It seems to me that maybe my ietf-keystored.startup is incorrectly configured can you have a look, am giving correct configuration or not....

'<action xmlns="urn:ietf:params:xml:ns:yang:1">
 <keystore xmlns="urn:ietf:params:xml:ns:yang:ietf-keystore">
  <private-keys>
      <load-private-key>
        <name>test_server_key</name>
        <private-key>MIIEowIBAAKCAQEAsdI1TBjzX1PgQXFuPCw5/kQwU7qkrhirMcFAXhI8EoXepPa9
fKAVuMjHW32P6nNzDpnhFe0YGdNloIEN3hJJ87cVOqj4o7zZMbq3zVG2L8As7MTA
8tYXm2fSC/0rIxxRRemcGUXM0q+4LEACjZj2pOKonaivF5VbhgNjPCO1Jj/TamUc
0aViE577C9L9EiObGM+bGbabWk/KWKLsvxUc+sKZXaJ7psTVgpggJAkUszlmwOQg
FiMSR53E9/CAkQYhzGVCmH44Vs6Hzs3RZjOTbce4wr4ongiA5LbPeSNSCFjy9loK
paE1rtOjkNBVdiNPCQTmLuODXUTKgkeL+9v/OwIDAQABAoIBAG/4MG1JbL4C/7vV
pBcpth7Aaznd1eJ2UB4VVOWnT8JOH2L6p1h5KRRhAP9AMkXsCnAQPyZiVAG3FlAZ
01SZaY2YJDr6uQ3JVW4155TWtgSdWux//Ass+lJ17lJ0SRxjsV13ez6CsDWeRjc+
2xy0S+KJgqk71XzhJG9fZLYyuddp3U/i3xFPUAcQM9xXKxcaD7g6LJf+a9pt6rim
Eqq/pjJxDgTsRLARsazYuxrlOB445mvnLiYhOf2/MvI80jIUKaj8BeAhg49UIg/k
mIh0xdevkcxBFer/BjBjscWaFjx14D6nkFMw7vtCum5KfalLN2edZKAzByOudGD4
5KnRp3ECgYEA6vnSoNGg9Do80JOpXRGYWhcR1lIDO5yRW5rVagncCcW5Pn/GMtNd
x2q6k1ks8mXKR9CxZrxZGqeYObZ9a/5SLih7ZkpiVWXG8ZiBIPhP6lnwm5OeIqLa
hr0BYWcRfrGg1phj5uySZgsVBE+D8jH42O9ccdvrWv1OiryAHfKIcwMCgYEAwbs+
HfQtvHOQXSYNhtOeA7IetkGy3cKVg2oILNcROvI96hS0MZKt1Rko0UAapx96eCIr
el7vfdT0eUzNqt2wTKp1zmiG+SnX3fMDJNzMwu/jb/b4wQ20IHWNDnqcqTUVRUnL
iksLFoHbTxsN5NpEQExcSt/zzP4qi1W2Bmo18WkCgYEAnhrk16LVux9ohiulHONW
8N9u+BeM51JtGAcxrDzgGo85Gs2czdwc0K6GxdiN/rfxCKtqgqcfCWlVaxfYgo7I
OxiwF17blXx7BVrJICcUlqpX1Ebac5HCmkCYqjJQuj/I6jv1lI7/3rt8M79RF+j5
+PXt7Qq97SZd78nwJrZni4MCgYAiPjZ8lOyAouyhilhZvI3xmUpUbMhw6jQDRnqr
clhZUvgeqAoxuPuA7zGHywzq/WVoVqHYv28Vjs6noiu4R/chlf+8vD0fTYYadRnZ
Ki4HRt+sqrrNZN6x3hVQudt3DSr1VFXl293Z3JonIWETUoE93EFz+qHdWg+rETtb
ZuqiAQKBgD+HI/syLECyO8UynuEaDD7qPl87PJ/CmZLMxa2/ZZUjhaXAW7CJMaS6
9PIzsLk33y3O4Qer0wx/tEdfnxMTBJrgGt/lFFdAKhSJroZ45l5apiavg1oZYp89
jSd0lVxWSmrBjBZLnqOl336gzaBVkBD5ND+XUPdR1UuVQExJlem4</private-key>
      </load-private-key>
    <private-key>
      <name>test_server_key</name>
      <certificate-chains>
        <certificate-chain>
          <name>test_server_cert</name>
      <certificate>MIIECTCCAvGgAwIBAgIBCDANBgkqhkiG9w0BAQsFADCBjDELMAkGA1UEBhMCQ1ox
FjAUBgNVBAgMDVNvdXRoIE1vcmF2aWExDTALBgNVBAcMBEJybm8xDzANBgNVBAoM
BkNFU05FVDEMMAoGA1UECwwDVE1DMRMwEQYDVQQDDApleGFtcGxlIENBMSIwIAYJ
KoZIhvcNAQkBFhNleGFtcGxlY2FAbG9jYWxob3N0MB4XDTE1MDczMDA3MjU1MFoX
DTM1MDcyNTA3MjU1MFowgYUxCzAJBgNVBAYTAkNaMRYwFAYDVQQIDA1Tb3V0aCBN
b3JhdmlhMQ8wDQYDVQQKDAZDRVNORVQxDDAKBgNVBAsMA1RNQzEXMBUGA1UEAwwO
ZXhhbXBsZSBzZXJ2ZXIxJjAkBgkqhkiG9w0BCQEWF2V4YW1wbGVzZXJ2ZXJAbG9j
YWxob3N0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsdI1TBjzX1Pg
QXFuPCw5/kQwU7qkrhirMcFAXhI8EoXepPa9fKAVuMjHW32P6nNzDpnhFe0YGdNl
oIEN3hJJ87cVOqj4o7zZMbq3zVG2L8As7MTA8tYXm2fSC/0rIxxRRemcGUXM0q+4
LEACjZj2pOKonaivF5VbhgNjPCO1Jj/TamUc0aViE577C9L9EiObGM+bGbabWk/K
WKLsvxUc+sKZXaJ7psTVgpggJAkUszlmwOQgFiMSR53E9/CAkQYhzGVCmH44Vs6H
zs3RZjOTbce4wr4ongiA5LbPeSNSCFjy9loKpaE1rtOjkNBVdiNPCQTmLuODXUTK
gkeL+9v/OwIDAQABo3sweTAJBgNVHRMEAjAAMCwGCWCGSAGG+EIBDQQfFh1PcGVu
U1NMIEdlbmVyYXRlZCBDZXJ0aWZpY2F0ZTAdBgNVHQ4EFgQU83qEtQDFzDvLoaII
vqiU6k7j1uswHwYDVR0jBBgwFoAUc1YQIqjZsHVwlea0AB4N+ilNI2gwDQYJKoZI
hvcNAQELBQADggEBAJ+QOLi4gPWGofMkLTqSsbv5xRvTw0xa/sJnEeiejtygAu3o
McAsyevSH9EYVPCANxzISPzd9SFaO56HxWgcxLn9vi8ZNvo2wIp9zucNu285ced1
K/2nDZfBmvBxXnj/n7spwqOyuoIc8sR7P7YyI806Qsfhk3ybNZE5UHJFZKDRQKvR
J1t4nk9saeo87kIuNEDfYNdwYZzRfXoGJ5qIJQK+uJJv9noaIhfFowDW/G14Ji5p
Vh/YtvnOPh7aBjOj8jmzk8MqzK+TZgT7GWu48Nd/NaV8g/DNg9hlN047LaNsJly3
NX3+VBlpMnA4rKwl1OnmYSirIVh9RJqNwqe6k/k=</certificate>
        </certificate-chain>
      </certificate-chains>
    </private-key>
  </private-keys>
  <trusted-certificates>
    <name>test_trusted_ca_list</name>
    <trusted-certificate>
      <name>test_ca</name>    <certificate>MIID7TCCAtWgAwIBAgIJAMtE1NGAR5KoMA0GCSqGSIb3DQEBBQUAMIGMMQswCQYD
VQQGEwJDWjEWMBQGA1UECAwNU291dGggTW9yYXZpYTENMAsGA1UEBwwEQnJubzEP
MA0GA1UECgwGQ0VTTkVUMQwwCgYDVQQLDANUTUMxEzARBgNVBAMMCmV4YW1wbGUg
Q0ExIjAgBgkqhkiG9w0BCQEWE2V4YW1wbGVjYUBsb2NhbGhvc3QwHhcNMTQwNzI0
MTQxOTAyWhcNMjQwNzIxMTQxOTAyWjCBjDELMAkGA1UEBhMCQ1oxFjAUBgNVBAgM
DVNvdXRoIE1vcmF2aWExDTALBgNVBAcMBEJybm8xDzANBgNVBAoMBkNFU05FVDEM
MAoGA1UECwwDVE1DMRMwEQYDVQQDDApleGFtcGxlIENBMSIwIAYJKoZIhvcNAQkB
FhNleGFtcGxlY2FAbG9jYWxob3N0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
CgKCAQEArD3TDHPAMT2Z84orK4lMlarbgooIUCcRZyLe+QM+8KY8Hn+mGaxPEOTS
L3ywszqefB/Utm2hPKLHX684iRC14ID9WDGHxPjvoPArhgFhfV+qnPfxKTgxZC12
uOj4u1V9y+SkTCocFbRfXVBGpojrBuDHXkDMDEWNvr8/52YCv7bGaiBwUHolcLCU
bmtKILCG0RNJyTaJpXQdAeq5Z1SJotpbfYFFtAXB32hVoLug1dzl2tjG9sb1wq3Q
aDExcbC5w6P65qOkNoyym9ne6QlQagCqVDyFn3vcqkRaTjvZmxauCeUxXgJoXkyW
cm0lM1KMHdoTArmchw2Dz0yHHSyDAQIDAQABo1AwTjAdBgNVHQ4EFgQUc1YQIqjZ
sHVwlea0AB4N+ilNI2gwHwYDVR0jBBgwFoAUc1YQIqjZsHVwlea0AB4N+ilNI2gw
DAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQUFAAOCAQEAI/1KH60qnw9Xs2RGfi0/
IKf5EynXt4bQX8EIyVKwSkYKe04zZxYfLIl/Q2HOPYoFmm3daj5ddr0ZS1i4p4fT
UhstjsYWvXs3W/HhVmFUslakkn3PrswhP77fCk6eEJLxdfyJ1C7Uudq2m1isZbKi
h+XF0mG1LxJaDMocSz4eAya7M5brwjy8DoOmA1TnLQFCVcpn+sCr7VC4wE/JqxyV
hBCk/MuGqqM3B1j90bGFZ112ZOecyE0EDSr6IbiRBtmeNbEwOFjKXhNLYdxpBZ9D
8A/368OckZkCrVLGuJNxK9UwCVTe8IhotHUqU9EqFDmxdV8oIdU/OzUwwNPA/Bd/
9g==</certificate>
    </trusted-certificate>
  </trusted-certificates>
</keystore>
</action>
` 
Actually, I combined two `load_server_key.xml and load_server_certs.xml` from Netopeer2/server/configuration/  . This seems to be the only failure for server certificate call back failed ...... But don't know how to resolve the same.

**Comment by michalvasko** [comment]
Hi,
if this is your `ietf-keystore.startup` then it definitely is wrong. Those `load*.xml` files are not configuration data directly, but `actions` (read more [here](https://tools.ietf.org/html/rfc7950#section-7.15)) to be sent to the server using NETCONF. Also, for the third time, **you have not installed keystored**. If you have it configured properly, then during `sysrepo-plugind -d -l4` startup, it will inform about `keystored` being successfully initialized.

Regards,
Michal

**Comment by shubhtrix** [comment]
Hello @michalvasko ,

Thanks for the link RFC-7950...

**For key-stored not INSTALLED:: please check (Few lines from bottom):** 
'
/turing-machine:turing-machine/transition-function/delta[label='right end']/output/head-move = left
/turing-machine:turing-machine/transition-function/delta[label='write separator'] (list instance)
/turing-machine:turing-machine/transition-function/delta[label='write separator']/label = write separator
/turing-machine:turing-machine/transition-function/delta[label='write separator']/input (container)
/turing-machine:turing-machine/transition-function/delta[label='write separator']/input/state = 2
/turing-machine:turing-machine/transition-function/delta[label='write separator']/input/symbol = 1
/turing-machine:turing-machine/transition-function/delta[label='write separator']/output (container)
/turing-machine:turing-machine/transition-function/delta[label='write separator']/output/state = 3
/turing-machine:turing-machine/transition-function/delta[label='write separator']/output/symbol = 0
/turing-machine:turing-machine/transition-function/delta[label='write separator']/output/head-move = left
/turing-machine:turing-machine/transition-function/delta[label='go home'] (list instance)
/turing-machine:turing-machine/transition-function/delta[label='go home']/label = go home
/turing-machine:turing-machine/transition-function/delta[label='go home']/input (container)
/turing-machine:turing-machine/transition-function/delta[label='go home']/input/state = 3
/turing-machine:turing-machine/transition-function/delta[label='go home']/input/symbol = 1
/turing-machine:turing-machine/transition-function/delta[label='go home']/output (container)
/turing-machine:turing-machine/transition-function/delta[label='go home']/output/head-move = left
/turing-machine:turing-machine/transition-function/delta[label='final step'] (list instance)
/turing-machine:turing-machine/transition-function/delta[label='final step']/label = final step
/turing-machine:turing-machine/transition-function/delta[label='final step']/input (container)
/turing-machine:turing-machine/transition-function/delta[label='final step']/input/state = 3
/turing-machine:turing-machine/transition-function/delta[label='final step']/input/symbol = 
/turing-machine:turing-machine/transition-function/delta[label='final step']/output (container)
/turing-machine:turing-machine/transition-function/delta[label='final step']/output/state = 4
/turing-machine:turing-machine/transition-function/delta[label='final step']/output/head-move = right [default]
[INF] Sysrepo plugin daemon initialized successfully.


`
I checked it with ` ps -aux | grep sysrepo-plugind ` seems the daemon was running already **I'VE ALREADY COMPILED AND INSTALLED KEYSTORED** from /Netopeer2/keystored. Should I need to configure it with something? Running it with -d -l4 parameters. 

Actually SSH was working fine out of the box, I was able to connect and get data. But with TLS some configuration is not correct trying to resolve it... :(

**Comment by michalvasko** [comment]
Hi,
I am not sure I understand but did you restart `sysrepo-plugind` after installing `keystored`? Anyway, can you attach the output file of `sysrepocfg --datastore startup --export=output_file.xml --format=xml ietf-keystore`?

Regards,
Michal

**Comment by shubhtrix** [comment]
Ya hi!!!

Ya I Installed keystored and every-time after running netopeer2-server I start sysrepo-plugind.... I know there is some part of the configuration I'm not able to figure out....

`AS ROOT : 07:14 PM : configuration :) sysrepocfg --datastore startup --export=output_file.xml --format=xml ietf-keystore 
The configuration was successfully exported.
AS ROOT : 07:14 PM : configuration :) 
`
Whoa!!! oops getting a blank `output_file.txt` :/ 
 
SERVER_SIDE : - 
`
VERBOSE: Accepted a connection on 0.0.0.0:6513.
ERROR: np2srv_sr_get_item failed (sysrepo: Item not found).
ERROR: Server certificate callback failed.
` 
CLIENT_SIDE : - 
`
> connect --tls 
nc ERROR: SSL_connect failed (Connection reset by peer).
cmd_connect: Connecting to the localhost:6513 failed.
> 
`

**Comment by michalvasko** [comment]
Hi,
that means you have no configuration set. Then TLS will not work, naturally. I though I was clear enough in the `netopeer2/server/configuration/README` but if not, I can try to elaborate.

The section you are interested in is TLS, obviously. In it it is described how to set up TLS listen meaning standard TLS connections. For importing a private key there is a separate section. You can read there that private keys must be imported using an **action** ([RFC](https://tools.ietf.org/html/rfc7950#section-7.15)), not a standard `<edit-config>`. You can use *netopeer2-cli* to send the actions, too, but with command `user-rpc` and using the prepared XML files. In short, execute `action` with `load_server_key.xml` and execute `edit-config` with `load_server_certs.xml` and `tls_listen.xml`. Your server should then be set up. For client configuration, look into the README section `Listen`/`TLS`/`Client`, I think it is clear enough.

Regards,
Michal

**Comment by shubhtrix** [comment]
Hello,

Ya actually, I came this far reading that README only. I'll go with your suggestions again and will let you know the status. Thanks for all your helps and suggestions.

Regards,
Shubham

**Comment by shubhtrix** [comment]
Hello,

Ya actually, I came this far reading that README only. I'll go with your suggestions again and will let you know the status. Thanks for all your helps and suggestions.

Regards,
Shubham

**Comment by shubhtrix** [comment]
Hi @michalvasko 

Is it possible to get the reply from Netopeer2-server (listening over TLS 0.0.0.0/6513) using any other utility such as curl or directly from my browser???? 
e.g., If I want to use POSTMAN Linux application to GET or POST something to netopeer2-server....

Thanks & Regards, 
Shubham

**Comment by michalvasko** [comment]
Hi Shubham,
no, simple HTTP GET or POST will not work (that is the RESTCONF protocol, we only support NETCONF). But, you should always be able to connect using SSH, configure all the TLS parameters and then try to connect using TLS.

Regards,
Michal
