### ISSUE TITLE
Xpath question

### ISSUE THREAD

**Issue by P-KH** [CESNET/Netopeer2#291]
Any idea why the following statement returns an "invalid argument"?
The root XML-Node is "data" and the XPath expression "//data[1]" should return the root node.

  > get --filter-xpath //data[1]
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	message:  np2srv_sr_get_items_iter failed (sysrepo: Invalid argument).

**Comment by P-KH** [comment]
Thanks for your quick reply.

When I try the following statement, then there is no results:

`get-config --source running --filter-xpath //ietf-netconf-server:listen[1]
DATA`

Could you please give us a XPath-example (with get or get-config)?
Thanks

**Comment by michalvasko** [comment]
Hi,
what is the output of unfiltered `get-config --source running`? That XPath is right, I think.

Regards,
Michal

**Comment by P-KH** [comment]
```xml
<config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<turing-machine xmlns="http://example.net/turing-machine">
  <transition-function>
    <delta>
      <label>left summand</label>
      <input>
        <state>0</state>
        <symbol>1</symbol>
      </input>
    </delta>
    <delta>
      <label>separator</label>
      <input>
        <state>0</state>
        <symbol>0</symbol>
      </input>
      <output>
        <state>1</state>
        <symbol>1</symbol>
      </output>
    </delta>
    <delta>
      <label>right summand</label>
      <input>
        <state>1</state>
        <symbol>1</symbol>
      </input>
    </delta>
    <delta>
      <label>right end</label>
      <input>
        <state>1</state>
        <symbol/>
      </input>
      <output>
        <state>2</state>
        <head-move>left</head-move>
      </output>
    </delta>
    <delta>
      <label>write separator</label>
      <input>
        <state>2</state>
        <symbol>1</symbol>
      </input>
      <output>
        <state>3</state>
        <symbol>0</symbol>
        <head-move>left</head-move>
      </output>
    </delta>
    <delta>
      <label>go home</label>
      <input>
        <state>3</state>
        <symbol>1</symbol>
      </input>
      <output>
        <head-move>left</head-move>
      </output>
    </delta>
    <delta>
      <label>final step</label>
      <input>
        <state>3</state>
        <symbol/>
      </input>
      <output>
        <state>4</state>
      </output>
    </delta>
  </transition-function>
</turing-machine>
<keystore xmlns="urn:ietf:params:xml:ns:yang:ietf-keystore">
  <private-keys>
    <private-key>
      <name>ssh_host_rsa_key</name>
    </private-key>
  </private-keys>
</keystore>
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <listen>
    <endpoint>
      <name>all-interfaces</name>
      <ssh>
        <address>0.0.0.0</address>
        <port>830</port>
        <host-keys>
          <host-key>
            <name>imported SSH key</name>
            <public-key>ssh_host_rsa_key</public-key>
          </host-key>
        </host-keys>
      </ssh>
    </endpoint>
  </listen>
</netconf-server>
</config>
```

**Comment by michalvasko** [comment]
Hi,
it should work with updated *sysrepo*, it could not handle XPaths starting with `//` before.

Regards,
Michal

**Comment by P-KH** [comment]
Hello,

Thank you.
Do you know whether or when this bug fix will be applied to the following docker:
[https://hub.docker.com/r/sysrepo/sysrepo-netopeer2/](url)

**Comment by mislavn** [comment]
Hi,

I will build a new image, the docker tag `latest` uses the master branch while the tag `devel` uses the devel branch.

Regards,
Mislav

**Comment by P-KH** [comment]
Hi,

Unfortunately we get the following error in `devel `docker:

`WARNING: Previous warning generated by XPath subexpression[3] "map-type = 'ietf-x509-cert-to-name:specified'".

ncERROR: Module "ietf-netconf-acm@2018-02-14" is supposed to be imported, but no other module imports it.
cmd_connect: Connecting to the localhost:830 as user "netconf" failed.`

**Comment by mislavn** [comment]
Hi,

I'll take a look.

**Comment by mislavn** [comment]
Hi,

I made a quick fix and updated the docker image but the underlying issue with the YANG model remains:
```
> connect 
Interactive SSH Authentication
Type your password:
Password: 
ly WARNING: Previous warning generated by XPath subexpression[3] "map-type = 'ietf-x509-cert-to-name:specified'".
ly ERROR: Module "ietf-netconf-acm" parsing failed.
ly ERROR: Module "ietf-netconf-acm@2018-02-14" in another revision "2012-02-22" already implemented.
> 
```

For the fix in the dockerfile I added:
```
RUN \
      sysrepoctl -i -g /opt/dev/sysrepo/yang/ietf-netconf-acm\@2018-02-14.yang

```

@michalvasko do you know why the YANG model was not properly installed by the cmake file?

**Comment by michalvasko** [comment]
Hi,
I have encountered it too, the model was being loaded from server test files where an older revision was used. If you update *netopeer2*, it should be fixed. Also, the model is being installed only when NACM is enabled or did you mean something else?

Regards,
Michal

**Comment by mislavn** [comment]
Hi,

I used the latest devel-server and master branch and still get the same issue.

**Comment by michalvasko** [comment]
I am not sure how are you testing it, but if using `netopeer2-cli`, try removing the model cache (`~/.netopeer2-cli/models/`).

Regards,
Michal

**Comment by P-KH** [comment]
Hello,

Here you can see the content of the `.netopeer2-cli` folder. There is no `models` directory (we are using the devel docker environment for testing):


```
root@91749f5f5b49:~# ls .netopeer2-cli/
config.xml  history
```

And here are the warning & error messages, that appear after the connect command:

```
ly WARNING: Previous warning generated by XPath subexpression[3] "map-type = 'ietf-x509-cert-to-name:specified'".
ly ERROR: Module "ietf-netconf-acm" parsing failed.
ly ERROR: Module "ietf-netconf-acm@2018-02-14" in another revision "2012-02-22" already implemented.
```

But it seems that the connection is made (at least the `status` command works fine). Now if we try the following command:

`get-config --source running --filter-xpath //ietf-netconf-server:listen[1]`

we get the following error on the client:
```
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	message:  np2srv_sr_get_items_iter failed (sysrepo: Sysrepo-internal error).
```

and the following logs are visible on the server side:
```
2018-07-02 06:26:48,017 DEBG 'sysrepod' stdout output:
[ERR] (ac_check_module_node_permissions:273) Cannot insert new entry into binary tree for module access control info.
[ERR] (rp_dt_prepare_data:1200) Access control check failed for xpath '//ietf-netconf-server:listen[1]//.'
[ERR] (rp_dt_get_values_wrapper_with_opts:1358) rp_dt_prepare_data failed
[ERR] (rp_get_items_req_process:830) Get items failed for '//ietf-netconf-server:listen[1]//.', session id=1053904025.

2018-07-02 06:26:48,018 DEBG 'netopeer2-server' stdout output:
ERROR: np2srv_sr_get_items_iter failed (sysrepo: Sysrepo-internal error).
```

Could you please help us?

Thanks.

**Comment by michalvasko** [comment]
Hi,
this was exactly the state before I made those patches so I am almost positive the image you are using does not have the most recent versions of neither *netopeer2* nor *sysrepo*. So, unless you, generally, use the updated applications, I cannot help you.

Regards,
Michal
