### ISSUE TITLE
Error : During keystore make install 

### ISSUE THREAD

**Issue by shubhtrix** [CESNET/netopeer2#295]
Hi 
After successful configuration of keystore, it is prompting error while installation (make install).

[100%] Built target keystored
Install the project...
-- Install configuration: "debug"
-- Installing: /usr/local/lib/pkgconfig/keystored.pc
-- Up-to-date: /usr/local/etc/keystored/keys
- Module ietf-x509-cert-to-name already installed.
- Module ietf-keystore already installed.
[ERR] Module 'ietf-keystore@<latest>' is not present in the dependency graph.
/usr/local/bin/sysrepocfg: Module 'ietf-keystore' is not installed.
writing RSA key
- Importing ietf-keystore stock key configuration...
[ERR] Module 'ietf-keystore@<latest>' is not present in the dependency graph.
/usr/local/bin/sysrepocfg: Module 'ietf-keystore' is not installed.
-- Installing: /usr/local/lib/sysrepo/plugins/libkeystored.so

Regards,
Shubham

**Comment by michalvasko** [comment]
Hi,
can you try it now? It may or may not be fixed.

Regards,
Michal

**Comment by shubhtrix** [comment]
Hello!!!

Nop, with that change not worked.

Regards,
Shubham

**Comment by michalvasko** [comment]
So, then I assume you are using the up-to-date *netopeer2* repository. In that case, can you post the output of `sysrepoctl -l` please?

Regards,
Michal

**Comment by shubhtrix** [comment]
Hello!
Ya I tried it with **master** branch netopeer2 repository. Considering, it is having the updated/usable changes. 
And the output for sysrepoctl -l is : 

Module Name                | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
example-module             |            | Installed   | root:root           | 666         |                               |
test-module                |            | Installed   | root:root           | 666         |                               |
referenced-data            |            | Installed   | root:root           | 666         |                               |
small-module               |            | Installed   | root:root           | 666         |                               |
info-module                |            | Installed   |                     |             |                               |
id-ref-base                |            | Installed   | root:root           | 666         |                               |
id-ref-aug                 |            | Installed   |                     |             |                               |
id-def-base                |            | Installed   |                     |             |                               |
id-def-extended            |            | Installed   |                     |             |                               |
module-a                   | 2016-02-10 | Installed   | root:root           | 666         |  sub-a-one sub-a-two          |
module-b                   | 2016-02-05 | Installed   | root:root           | 666         |                               |
module-a                   | 2016-02-02 | Imported    |                     |             |  sub-a-one sub-a-two          |
ietf-interfaces            | 2014-05-08 | Installed   | root:root           | 666         |                               |
iana-if-type               | 2014-05-08 | Installed   |                     |             |                               |
ietf-ip                    | 2014-06-16 | Installed   |                     |             |                               |
state-module               | 2016-07-01 | Installed   | root:root           | 666         |                               |
top-level-mandatory        |            | Installed   | root:root           | 666         |                               |
cross-module               |            | Installed   | root:root           | 666         |                               |
turing-machine             | 2013-12-27 | Installed   | root:root           | 666         |                               |
ietf-netconf-notifications | 2012-02-06 | Installed   | root:root           | 666         |                               |
ietf-netconf               | 2011-06-01 | Installed   | root:root           | 666         |                               | writable-running candidate rollback-on-error validate startup xpath
ietf-netconf-acm           | 2012-02-22 | Imported    |                     |             |                               |
nc-notifications           | 2008-07-14 | Installed   | root:root           | 666         |                               |
notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
servers                    |            | Installed   | root:root           | 666         |                               |
swig-test-cpp-changes      | 2017-03-09 | Installed   | root:root           | 666         |                               |
swig-test-cpp-operations   | 2017-03-09 | Installed   | root:root           | 666         |                               |
swig-test                  | 2017-03-09 | Installed   | root:root           | 666         |                               |
ietf-netconf-with-defaults | 2011-06-01 | Installed   |                     |             |                               |
ietf-netconf-monitoring    | 2010-10-04 | Installed   | root:root           | 666         |                               |
ietf-yang-library          | 2018-01-17 | Installed   | root:root           | 666         |                               |
ietf-keystore              | 2016-10-31 | Installed   | root:root           | 666         |                               |
ietf-netconf-server        | 2016-11-02 | Installed   | root:root           | 666         |                               | listen ssh-listen tls-listen call-home ssh-call-home tls-call-home
ietf-x509-cert-to-name     | 2014-12-10 | Installed   |                     |             |                               |
ietf-ssh-server            | 2016-11-02 | Installed   |                     |             |                               |
ietf-tls-server            | 2016-11-02 | Installed   |                     |             |                               |
ietf-system                | 2014-08-06 | Installed   | root:root           | 666         |                               | authentication local-users
ietf-netconf-acm           | 2018-02-14 | Installed   | root:root           | 666         |                               |
iana-crypt-hash            | 2014-08-06 | Installed   |                     |             |                               |
ietf-datastores            | 2017-08-17 | Installed   |                     |             |                               |

**And again the ssh connect is prompting at login**  :
 
AS ROOT : 12:12 PM : ~ :) netopeer2-cli 
> connect --host localhost --login root 
Interactive SSH Authentication
Type your password:
Password: 
root@localhost password: 
nc ERROR: **No yang-library modules information for session 1**.
ly ERROR: **Invalid arguments** (lys_features_change()).
> 
> 
> get 
DATA
<yang-library xmlns="urn:ietf:params:xml:ns:yang:ietf-yang-library">
  <checksum>44</checksum>
</yang-library>
<modules-state xmlns="urn:ietf:params:xml:ns:yang:ietf-yang-library">
  <module-set-id>44</module-set-id>
</modules-state>
<turing-machine xmlns="http://example.net/turing-machine">
  <transition-function>
    <delta>.....

**Comment by shubhtrix** [comment]
This is my current cloned repository information for your reference....

AS ROOT : 12:44 PM : dependencies :) ls
libnetconf2  libyang  Netopeer2  sysrepo
AS ROOT : 12:44 PM : dependencies :) cd libnetconf2/
AS ROOT : 12:44 PM : libnetconf2 :) git branch 
* master
AS ROOT : 12:44 PM : libnetconf2 :) cd ../libyang/
AS ROOT : 12:44 PM : libyang :) git branch 
* master
AS ROOT : 12:44 PM : libyang :) cd ../Netopeer2/
AS ROOT : 12:45 PM : Netopeer2 :) git branch 
* master
AS ROOT : 12:45 PM : Netopeer2 :) cd ../sysrepo/
AS ROOT : 12:45 PM : sysrepo :) git branch 
* master
AS ROOT : 12:45 PM : sysrepo :)

**Comment by michalvasko** [comment]
Hi,
please use sysrepo `devel` branch, there are some *ietf-yang-library* fixes that should resolve the error you are seeing. It is then best to use `devel` of all the libraries, *libyang*, *libnetconf2*, and *netopeer2*. Before reinstalling it, please remove the whole *sysrepo* repository (displayed on the first line of `sysrpeoctl -l` output).

Regards,
Michal

**Comment by shubhtrix** [comment]
Hi!
Thanks. will check that out with all devel branches.

Regards,
Shubham
