### ISSUE TITLE
Silly question: libnetconf2 compilation fails

### ISSUE THREAD

**Issue by sadovski** [CESNET/Netopeer2#297]
I guess I'm missing something obvious:
1) 'cmake' step passed without issues. I got
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen missing components:  dot
-- Found CMocka: /usr/local/lib/libcmocka.so (Required is at least version "1.0.0") 
-- valgrind executable not found! Disabling memory leaks tests
-- Configuring done
-- Generating done
-- Build files have been written to: /home/akivas/libnetconf2/build
2) after that compilation failed:
$ make
 Building C object CMakeFiles/netconf2.dir/src/messages_server.c.o
In file included from /home/akivas/libnetconf2/src/messages_server.c:23:0:
/home/akivas/libnetconf2/src/session_server.h:222:63: error: unknown type name ‘LYS_VERSION’; did you mean ‘NC_VERSION’?
 const char **nc_server_get_cpblts_version(struct ly_ctx *ctx, LYS_VERSION version);
                                                               ^~~~~~~~~~~
                                                               NC_VERSION
In file included from /home/akivas/libnetconf2/src/messages_server.c:20:0:
/home/akivas/libnetconf2/src/messages_server.c: In function ‘nc_err_libyang’:
/home/akivas/libnetconf2/src/messages_server.c:376:17: error: called object is not a function or function pointer
         switch (ly_vecode(ctx)) {
                 ^

I cannot figure out what i missed... appreciate any help

Regards,
     Akiva

**Comment by michalvasko** [comment]
Hi Akiva,
you are compiling with an old *libnetconf2* and *libyang* version. Install recent versions (if using `devel-server` branch of netopeer2, then `devel`, otherwise `master`) and make sure they are used by executing
```
# ldconfig -p | grep "\(libyang\|libnetconf2\)"
```
The found versions should be those most recently installed.

Regards,
Michal

**Comment by sadovski** [comment]
Thank you, Michal!
  after updating libyang/libnetconf2 I managed to make good progress, however 'make install' of Netopeer2-server failed with following error message:
- Installing module ietf-yang-library...

[ERR] (srctl_ly_log_cb:500) libyang: Module "ietf-yang-library" in another revision already implemented.
[ERR] (srctl_ly_log_cb:500) libyang: Module "ietf-yang-library" parsing failed.
Error: Unable to load the module by libyang.
Installing a new module from file '/home/akivas/Netopeer2/server/scripts/../../modules/ietf-yang-library.yang'...
Install operation failed.

This issue resembles another one (already closed)
[](https://github.com/CESNET/Netopeer2/issues/287)
but error message is different. 

I rebuild ldconfig cache, now it contains:

akivas@akivas-VirtualBox:~/libyang/build$ ldconfig -p | grep "\(libyang\|libnetconf2\)"
	libyang.so.0.15 (libc6,x86-64) => /usr/local/lib/libyang.so.0.15
	libyang.so.0.14 (libc6,x86-64) => /usr/local/lib/libyang.so.0.14
	libyang.so (libc6,x86-64) => /usr/local/lib/libyang.so
	libnetconf2.so.0.11 (libc6,x86-64) => /usr/local/lib/libnetconf2.so.0.11
	libnetconf2.so.0.10 (libc6,x86-64) => /usr/local/lib/libnetconf2.so.0.10
	libnetconf2.so (libc6,x86-64) => /usr/local/lib/libnetconf2.so


What I'm doing wrong?

Regards,
    Akiva

**Comment by michalvasko** [comment]
Hi Akiva,
it should work unless you are using some old libraries. So, remove the old ones (`libyang.so.0.14` and `libnetconf2.so.0.10`), reinstall the new ones, and it should be fixed.

Regards,
Michal

**Comment by sadovski** [comment]
Thanks for help&support. We can close the issue.
