### ISSUE TITLE
I think we should Refactoring our code ,as the function  is to long to check and view

### ISSUE THREAD

**Issue by ZhaoGuangYue** [CESNET/Netopeer2#3]
I think we should Refactoring our code ,as the function  is to long to check and view

i think the extract function and creat new file is useable

**Comment by michalvasko** [comment]
Hi,
what function do you mean, op_editconfig? Anyway, my guess is you used the master branch of netopeer2, if you look at the devel-server branch, the operations are divided into files there. If you want to have all the latest features and bugfixes I suggest you use that branch. But you will need the devel branch of libnetconf2 as well.

Regards,
Michal

**Comment by ZhaoGuangYue** [comment]
recently i check out the master branch code, and when i check and view it.I found it is hard to
 read it,as it use to much "goto" statement and lots of functions are so long to understand.
So i think,  can we replace goto  statement with function and extract functions in order to divide the long function to smaller one?

**Comment by michalvasko** [comment]
But what function(s) are you referring to?

**Comment by rkrejci** [comment]
Please check the `devel-server` branch code. Anyway, you can do the changes and provide them as pull request where we can discuss them more specifically. Right now you are talking too generically.
