### ISSUE TITLE
Multiple netconf client session nt working

### ISSUE THREAD

**Issue by rajnkamr** [CESNET/Netopeer2#30]
I already have an ongoing session, when i try to connect via other netconf client to Netopeer2-server it gives it does not connect.

netopeer2-server[15736]: (cl_request_process:423) session-start request sent, waiting for response.
netopeer2-server[15736]: (cl_request_process:445) session-start response received, processing.
netopeer2-server[15736]: nc_ps_add_session: failed to wait for a pollsession condition (Connection timed out).
netopeer2-server[15736]: nc_ps_add_session: failed to wait for a pollsession condition (Connection timed out).
netopeer2-server[15736]: nc_ps_add_session: failed to wait for a pollsession condition (Connection timed out).
netopeer2-server[15736]: Internal error (/root/Netopeer2/server/main.c:591)
netopeer2-server[15736]: (cl_request_process:401) Sending session-stop request.

**Comment by michalvasko** [comment]
Hi,
please pull libnetconf2, it should be solved already.

Regards,
Michal

**Comment by rajnkamr** [comment]
Problem is seen with libnetconf2 as well.
I am having libnetconf2 libraries.

**Comment by michalvasko** [comment]
Hi,
you are saying you have installed the most recent version of libnetconf2 (at least 0.6.19 for master branch and 0.7.19 for the devel branch) and this issue still occurs?

Regards,
Michal

**Comment by NickZengXL** [comment]
Hi,
I also hit this issue. And I use libnetconf2 0.7.38.

# set version
set(LIBNETCONF2_MAJOR_VERSION 0)
set(LIBNETCONF2_MINOR_VERSION 7)
set(LIBNETCONF2_MICRO_VERSION 38)

**Comment by michalvasko** [comment]
Hi,
the issues you replied to are really old and more importantly, closed, so please create another issue even though you have the same problem. That is, if you still experience it after updating *libnetconf2* and *netopeer2-server* to latest versions (lnc2 `0.8.62` or `0.9.4`, server `0.3.75`).

Regards,
Michal
