### ISSUE TITLE
netopeer2-cli says "Already connected" after a server restart

### ISSUE THREAD

**Issue by P-KH** [CESNET/netopeer2#300]
Hello,

It seems to be a bug & I wanted to report it here:

We kill the netopeer2-server process and here you can see what the netopeer2-cli shows:

```
> 
nc ERROR: Session 1: SSH channel poll error (Socket error: disconnected).
> 
> 
> 
> connect --host localhost --port 830 --login netconf
cmd_connect: Already connected to localhost.
> subscribe 
nc ERROR: Session 1: invalid session to send RPCs.
cli_send_recv: Failed to send the RPC.
> status 
Client is not connected to any NETCONF server.
```

I think it is strange, that it says "Already connected" after the connection to the server is lost.

**Comment by michalvasko** [comment]
Hi,
it is quite strange, what command caused CLI to learn about server being disconnected? Or it was discovered by TCP keep-alive on its own?

Regards,
Michal

**Comment by P-KH** [comment]
Hi,

No it was not a keep-alive thing, as far as I can tell.
The `status` command returned: `Client is not connected to any NETCONF server.`

First after a `disconnect` command the CLI was in a normal / stable state again.

Best regards,
PKH

**Comment by michalvasko** [comment]
Hi,
so what command caused
```
nc ERROR: Session 1: SSH channel poll error (Socket error: disconnected).
```
to be printed? That is the moment when CLI learned that it got disconnected from the server and since then it should act accordingly when issuing other commands.

Regards,
Michal
