### ISSUE TITLE
<get> response times increased noticeably in netopeer2@46f2ee0

### ISSUE THREAD

**Issue by alangefe** [CESNET/Netopeer2#304]
The time it takes the server to supply a response to a `get` operation has increased observably beginning in 46f2ee0.

Beginning in 46f2ee0, certain response data that used to be obtained internally by netopeer2-server (e.g., ietf-netconf-monitoring) is instead obtained from sysrepo. As a result, `get` operations are noticeably slower. The slowdown is particularly noticeable when larger numbers of models have been loaded.

Below are average `get` response times, averaged over 50 iterations, measured on the same machine, before and after 46f2ee0. The first row shows the `get` response time increase when about 70 models are present; the second row when about 300 models are present.

models | before 46f2ee0 | after 46f2ee0
--- | --- | ---
~70 | 2.2s | 6.4s
~300 | 3.3s | 9.4s

**Comment by michalvasko** [comment]
Hi,
yes, sorry about that but it is required. The data are going through sysrepo so that NACM can be applied, it was not before, which was a problem.

Regards,
Michal

**Comment by alangefe** [comment]
Closed with #314, included in server-0.6.4.
