### ISSUE TITLE
Segmentation fault or lockup when terminating netopeer2-server with signal

### ISSUE THREAD

**Issue by alangefe** [CESNET/Netopeer2#306]
When netopeer2-server is sent a signal to terminate it (e.g., `SIGTERM`), it will intermittently crash or lock up, beginning in 3f4bc5e.

The problem was introduced by the reordering of `main()`'s cleanup label in 3f4bc5e. `sr_disconnect()` will free `np2srv.sr_conn` when it calls `cl_connection_cleanup()`. The subsequent call to `nc_ps_clear()` results in calls that attempt to use the freed `sr_conn_ctx_t`. (Stack traces are included below.) The contents of the memory are undefined at this point, so any number of things can happen, including a segmentation fault or a lockup when attempting to acquire a freed lock.

Here is a stack trace for the case where memory from the freed `sr_conn_ctx_t` is used, resulting in a segmentation fault:

```
#0  sr_uint32_to_buff () at sysrepo/src/common/sr_utils.c:75
#1  cl_message_send () at sysrepo/src/clientlib/cl_common.c:156
#2  cl_request_process () at sysrepo/src/clientlib/cl_common.c:498
#3  sr_session_stop () at sysrepo/src/clientlib/client_library.c:568
#4  free_ds () at netopeer2/server/main.c:296
#5  nc_session_free () at libnetconf2/src/session.c:617
#6  nc_ps_clear () at libnetconf2/src/session_server.c:1573
#7  main () at netopeer2/server/main.c:1576
```

And here is a stack trace for the case where the code attempts to acquire the lock on the freed `sr_conn_ctx_t`, resulting in a lockup:

```
#0  __lll_lock_wait () from libpthread.so.0
#1  pthread_mutex_lock () from libpthread.so.0
#2  cl_request_process () at sysrepo/src/clientlib/cl_common.c:495
#3  sr_session_stop () at sysrepo/src/clientlib/client_library.c:568
#4  free_ds () at netopeer2/server/main.c:296
#5  nc_session_free () at libnetconf2/src/session.c:617
#6  nc_ps_clear () at libnetconf2/src/session_server.c:1597
#7  main () at netopeer2/server/main.c:1576
```

**Comment by michalvasko** [comment]
Hi,
you are right, sorry about that.

Regards,
Michal
