### ISSUE TITLE
Logging NETCONF messages

### ISSUE THREAD

**Issue by abubakarmuqaddas** [CESNET/Netopeer2#307]
Is it possible if all the received NETCONF messages by the netopeer2 can be seen/logged? Is there a capability like this in Netopeer2 server?

Regards
Abubakar

**Comment by michalvasko** [comment]
Hi Abubakar,
no, this is not directly supported. You can, however, print them if you start the server with `-c MSG`. But, there will also be other clutter.

Regards,
Michal

**Comment by abubakarmuqaddas** [comment]
Hi Michal,

The NETCONF XML messages are not printing. I am using the following command to start the server:

`sudo netopeer2-server -d -v2 3 -c MSG`

Only got the following messages when I ran some RPCs:

```
VERBOSE: Resolving unresolved data nodes and their constraints...
VERBOSE: All data nodes and constraints resolved.
VERBOSE: Session 1: thread 2 event new RPC.
VERBOSE: Resolving unresolved data nodes and their constraints...
VERBOSE: All data nodes and constraints resolved.
VERBOSE: Session 1: thread 0 event new RPC.
VERBOSE: Resolving unresolved data nodes and their constraints...
VERBOSE: All data nodes and constraints resolved.
VERBOSE: Resolving unresolved data nodes and their constraints...
VERBOSE: All data nodes and constraints resolved.
VERBOSE: Session 1: thread 2 event new RPC.
```

Am I running the command correctly?

Regards
Abubakar

**Comment by michalvasko** [comment]
Hi Abubakar,
I do not know what *netopeer2-server* version are you using because with those parameters the most recent version will refuse to start. Please, update it.

Regards,
Michal

**Comment by abubakarmuqaddas** [comment]
Hi Michal,

I pulled the latest code, and it is working now. Thanks!

Regards
Abubakar

**Comment by himaniadsar** [comment]
Hi,
How to get sys logs in Netopeer 2 at run time?

Regards,
Himani

**Comment by michalvasko** [comment]
Please stop asking similar question in different issues, it is completely redundant.
