### ISSUE TITLE
netconf sessions increase when client does not terminate the session using <close-session>

### ISSUE THREAD

**Issue by chunlovemail** [CESNET/Netopeer2#308]
### Description

1. Using nc-hammer https://github.com/damianoneill/nc-hammer  as the client. When the nc-hammer had finished a command, it closed the SSH connection without send `<close-session>`.
2. But the netopeer2-server session won't be closed.
3. This may like other issue #277 

### Versions
```
root@localhost:~# netopeer2-server -V   netopeer2-server 0.5.26
compile time: Aug  4 2018, 15:29:49
```

### Attachments
The log is as shown below:
```
`/home/chuny/shasta/libs_pub/libnetconf2/src/io.c nc_read Session 1: SSH channel unexpected EOF.
/home/chuny/shasta/libs_pub/libnetconf2/src/io.c nc_read_until.
/home/chuny/shasta/libs_pub/libnetconf2/src/io.c nc_read_msg_io.
nc_ps_poll, 1508, ret: 0x00e0
worker_thread 1197, ret: 0x00e0
nc_ps_poll, 1498, ret: 0x0002`
```

From the log, we can see that:
1. When client close the SSH connection without using `<close-session>`, the netopeer2-server will read error with `"Session 1: SSH channel unexpected EOF"`
2. Then nc_ps_poll return 0x00e0 which means `NC_PSPOLL_ERROR | NC_PSPOLL_SESSION_ERROR | NC_PSPOLL_SESSION_TERM`. But the newest code doesn't terminate and chose to poll again.
3.  Because of the Clients has close the connection, the netopeer2-server will read `NC_PSPOLL_TIMEOUT` by the connection. Then it continues to `nc_ps_poll` again while the netopeer2-server won't terminate the session. As a result, the session number increase.

I had modified the code as shown below. Please help to check whether it makes sense.
```
`if ((rc & (NC_PSPOLL_NOSESSIONS | NC_PSPOLL_TIMEOUT | NC_PSPOLL_ERROR))
    && !(rc&NC_PSPOLL_SESSION_TERM)) {
    /* if there is no active session, timeout, or an error, rest for a while */
    pthread_rwlock_unlock(&np2srv.ly_ctx_lock);
    np_sleep(10);
    continue;
}`
```

Thanks!

**Comment by michalvasko** [comment]
Hi,
you are right and your proposed fix seems correct to me, thanks! But I do not think this bug is connected in any way to the problem in #277.

Regards,
Michal

**Comment by chunlovemail** [comment]
Hi Michal,
    Yes, you are right. Seems that two questions are unrelated.

Regargs,
Chun
