### ISSUE TITLE
Failed to update leaf node if default-operation is "none".

### ISSUE THREAD

**Issue by corrollFang** [CESNET/Netopeer2#313]
Version: 

NetOpeer2-0.4.21
libyang-0.14.78
libnetconf2-0.10.30
sysrepo-0.7.3
-------------------------------------
### Description:

If the default-operation is "none", it's failed to update leaf-node.
 No error returned, but the leaf value doesn't change.
I suppose the latest version also has this issue .

### Possible reason:
Netopeer2/server/op_editconfig.c:op_editconfig(struct lyd_node *rpc, struct nc_session *ncs)

The variable "ret" is initialized as "-1" for every node(line:384), but it's not updated if default-operation is none, so the test "if (!ret)" is failed(line:526)

### Reproduce steps:

1.  YANG files
```
module test-def-oper{

    namespace "http://test-def-oper";
    prefix "test";
    revision "2018-08-05"{
        description
            "Initial revision.";
    }

    container c1
    {
        list list-entry
        {
            key "key-id";
            leaf key-id
            {
                type int32;
                description "Key Node.";
            }
            leaf change-value-node
            {
                type string;
                description "Try to change its value.";
            }
        }
    }
}
```
2. Create list-entry[1]
```
<?xml version="1.0" encoding="utf-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="14">
  <edit-config>
    <target>
      <running/>
    </target>
    <config>
      <c1 xmlns="http://test-def-oper">
        <list-entry>
          <key-id>1</key-id>
          <change-value-node>Original</change-value-node>
        </list-entry>
      </c1>
    </config>
  </edit-config>
</rpc>
```
3. Use replace operation on leaf node to update leaf value as "New-Value", it's failed. No error returned, but the leaf value doesn't change.
```
<?xml version="1.0" encoding="utf-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="14">
  <edit-config>
    <target>
      <running/>
    </target>
    <default-operation>none</default-operation>
    <config>
      <c1 xmlns="http://test-def-oper">
        <list-entry>
          <key-id>1</key-id>
          <change-value-node xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="replace">New-Value</change-value-node>
        </list-entry>
      </c1>
    </config>
  </edit-config>
</rpc>
```

**Comment by michalvasko** [comment]
Hi,
it should be fixed now, please use the most recent *netopeer2-server* version from either `master` or `devel(-server)`. Whichever branch you choose, you must have the same branch also of *libyang*, *sysrepo*, and *libnetconf2*.

Regards,
Michal
