### ISSUE TITLE
can not delete the whole node of leaflist

### ISSUE THREAD

**Issue by crystalyxiaoxianer** [CESNET/Netopeer2#32]
Sorry to bother you，but I have a problem when I want to delete the whole leaflist. 
model is as follows:

```
module Sub{
    namespace "urn:ietf:params:xml:ns:yang:zte:sub";
    prefix Sub;
    revision 2016-05-10;

    container RootContainer{
		
        container secondLevelContainer{
            leaf secondleaf{
                type int8;
            }
		    
            leaf secondleaf2{
                type int8;
                default 2;
            }
			
            leaf-list leaflist{
                type string;
            }
        }
    }
}
```
first, I add data for sub model using netopeer2-client：
```xml
<RootContainer xmlns="urn:ietf:params:xml:ns:yang:zte:sub" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
	<secondLevelContainer>
	    <leaflist>a</leaflist>
		<leaflist>b</leaflist>
	</secondLevelContainer>
</RootContainer>
```

then，I delete the whole leaflist with xml file as follows,but netopeer2-client throw an error:
```xml
<RootContainer xmlns="urn:ietf:params:xml:ns:yang:zte:sub" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
	<secondLevelContainer>
	   <leaflist xc:operation="delete"></leaflist>
	</secondLevelContainer>
</RootContainer>
```
netopeer2-client show the infomation is:
```
ERROR
type: application
tag: data-missing
severity: error
path: /Sub:RootContainer/secondLevelContainer/leaflist[.='']
message: Request could not be completed because the relevant data model content does not exist.
```

 my problem is  the protocol of netconf is not exactly to describe "delete operation" of leaflist. Is this normal or a bug?  Look forward to your reply to solve my confusion. Thank you very much.

**Comment by crystalyxiaoxianer** [comment]
Sorry the description of xml is not show .
add is as follows:

< leaflist >a< /leaflist >

< leaflist >b< /leaflist >

delete is as follows:

< leaflist xc:operation="delete" >< /leaflist >

**Comment by rkrejci** [comment]
This is intended behavior. Since the leaf-list can be defined as string and an empty string can be a valid value, using an empty leaf-list value to delete all the instances would be problematic because you wouldn't be able to delete the specific instance with empty string. The leaf-list value is used as a key to identify the specific instance. Similarly, you are not allowed to delete all instances of a list by not providing the list's keys.

**Comment by crystalyxiaoxianer** [comment]
Sorry to bother you again，If I want to replace all entries of leaflist with current values exists in data tree，what should I do?
I try to do like this,but add new entry of leaflist:
<leaflist xc:operation="replace">c</leaflist>
finally,I get three entries of leaflist.

Otherwise，If I want to delete the whole leaflist, I can only delete all entries of leaflist  like this?
<RootContainer xmlns="urn:ietf:params:xml:ns:yang:zte:sub" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
    <secondLevelContainer>
       <leaflist xc:operation="delete">a</leaflist>
       <leaflist xc:operation="delete">b</leaflist>
    </secondLevelContainer>
</RootContainer>

or delete parent of leaflist like this?
<RootContainer xmlns="urn:ietf:params:xml:ns:yang:zte:sub" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
    <secondLevelContainer xc:operation="delete">
    </secondLevelContainer>
</RootContainer>

Look forward to your reply to solve my confusion. Thank you very much.

**Comment by rkrejci** [comment]
`replace` operation on leaf-list make sense only for moving the instance in case of user-ordered leaf-list - see [RFC 7950](https://tools.ietf.org/html/rfc7950#section-7.7.9). So the only option is to delete all instances (by specifying them) and create the new instances. If you have no other data next to the leaf-list instances, you could also `replace` the container (the `secondLevelContainer` in your example). Deleting and creating the container would also work.

**Comment by crystalyxiaoxianer** [comment]
hi，I read RFC 7950.

**Comment by crystalyxiaoxianer** [comment]
Hi,There is a word in RFC 7950 that is "In a <copy-config> or in an <edit-config> with a "replace" operation
   that covers the entire leaf-list, the leaf-list order is the same as
   the order of the XML elements in the request."  

Then I verified it. In an <edit-config> with a "replace" can not cover the entire leaf-list. Does "replace" not work? Look forward to your reply to solve my confusion. Thank you very much.

**Comment by rkrejci** [comment]
you can cover the entire leaf-list by specifying `replace` operation into its parent container:
```
<RootContainer xmlns="urn:ietf:params:xml:ns:yang:zte:sub" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <secondLevelContainer xc:operation="replace">
    <leaflist>c</leaflist>
    <leaflist>d</leaflist>
  </secondLevelContainer>
</RootContainer>
```

This would remove the `a` and `b` instances of the leaflist and create new `c` and `d` instances. RFC just says that if the leaf-list is user-ordered, server has to keep the specified order of the instances.

**Comment by crystalyxiaoxianer** [comment]
Hi,I'm very sorry.  Have you reviced my personal email?

**Comment by rkrejci** [comment]
No, I didn't, but I would prefer to keep this conversation public.

**Comment by crystalyxiaoxianer** [comment]
OK,Because of my personal reason, Would you  delete the namespace zte word in your last comment to keep "urn:ietf:params:xml:ns:yang:sub"? Please,Thank you very much.
