### ISSUE TITLE
Netopeer2-server doesn't process when session count exceeds nc_max_sessions 

### ISSUE THREAD

**Issue by chunlovemail** [CESNET/Netopeer2#321]
### Description
Netopeer2-server doesn't process when session count exceeds `nc_max_sessions`. As a result, client will wait to timeout when tring to connect server.

### Steps to Reproduce
1. Config `nc_max_sessions` number to 20 and 20 clients have connected to server successfully.
2. When a new client tries to connect to server, the server will do nothing for the current count has been reached to 20.
3. For the server neither `accept`/`close` new session nor send back a rejection message, the client will wait till timeout.

The code in file main.c `worker_thread()` function is as shown below:
```
/* try to accept new NETCONF sessions */
if (nc_server_endpt_count()
    && (!np2srv.nc_max_sessions || (nc_ps_session_count(np2srv.nc_ps) < np2srv.nc_max_sessions))) {
    msgtype = nc_accept(0, &ncs);
    if (msgtype == NC_MSG_HELLO) {
        np2srv_new_session_clb(NULL, ncs);
    }
}
```

**Expected behavior:**
Server can accept the request and close the session automatically.
I had modified the code and it runs OK with test. The code is as shown below:
```
/* try to accept new NETCONF sessions */
if (nc_server_endpt_count()) {
    msgtype = nc_accept(0, &ncs);
    if (msgtype == NC_MSG_HELLO) {
        np2srv_new_session_clb(NULL, ncs);

        if ((np2srv.nc_max_sessions > 0 ) && (nc_ps_session_count(np2srv.nc_ps) > np2srv.nc_max_sessions)) {
            nc_session_set_term_reason(ncs, NC_SESSION_TERM_OTHER);
            nc_session_set_status(ncs, NC_STATUS_INVALID);
        }
    }
}
```
Please help to check whether it make sense^_^

### Versions
```
root@localhost:~# netopeer2-server -V
netopeer2-server 0.5.26
compile time: Aug 19 2018, 08:50:37
```

Thanks!

**Comment by michalvasko** [comment]
Hi,
I believe this parameter's purpose is to protect from possible DoS attacks. That is why once the limit is reached, new sessions are completely ignored by the server so that it does not waste any more resources. It is true that clients will not learn why the server is ignoring them but I still think the behavior is correct as it is.

Regards,
Michal

**Comment by chunlovemail** [comment]
Hi Michal,

    I got it, thanks!

Regards,
chun
