### ISSUE TITLE
Not able to subscribe multiple streams within same netconf session 

### ISSUE THREAD

**Issue by shishirpandey29** [CESNET/netopeer2#325]
Hello,
I have implemented a netconf client using libnetconf2 and have a requirement to subscribe to two notification streams in same  netconf session.
During testing with  Netopeer2 and Sysrepo-0.7.4 ,found  that after subscribing to one stream , was not able to subscribe second stream within a same netconf session and got below error msg for second stream in same netconf session.
Error Msg :"  
 type:     protocol
  tag:      in-use
 severity: error
 Already subscribed.
"
I think, Netopeer2 is restricting on one notification stream per per session.
Shouldn't Netopeer2  support multiple streams  per  netconf -session ?

**Comment by michalvasko** [comment]
Hi,
this is a feature and there is no need to change this anyway. You are free to use your own filter instead of a stream which will select only the notifications you want. So one subscription should always be enough.

Regards,
Michal
