### ISSUE TITLE
Netopeer2 connecting with remote netopeer2-cli but connection is inconsistent

### ISSUE THREAD

**Issue by vishalwc** [CESNET/Netopeer2#33]
connect to remote server first time 

```
[root@MaestrOS build]# ./netopeer2-cli
> connect --host 10.1.17.37 --port 6001 --login security
Interactive SSH Authentication
Type your password:
Password:
nc ERROR: Session 2: SSH channel unexpected EOF.
nc ERROR: Session 2: failed to receive a reply to <get-schema>.
ly ERROR: User module retrieval callback failed!
nc ERROR: Session 2: invalid session to send RPCs.
nc ERROR: Session 2: failed to send the <get-schema> RPC.
nc ERROR: Session 2: invalid session to send RPCs.
nc ERROR: Session 2: failed to send the <get-schema> RPC.
ly ERROR: User module retrieval callback failed!
ly ERROR: Invalid value "ietf-netconf-acm" of "import".
ly ERROR: Importing "ietf-netconf-acm" module into "ietf-netconf" failed.
ly ERROR: Module "ietf-netconf" parsing failed.
nc ERROR: Loading base NETCONF schema failed.
cmd_connect: Connecting to the 10.1.17.37:6001 as user "security" failed.
> quit
```

stop the netopeer server and restarts it 

```
root@blr-sol-xn-cg ~]# /usr/sbin/netopeer2-server
[root@blr-sol-xn-cg ~]#
[root@blr-sol-xn-cg ~]#
[root@blr-sol-xn-cg ~]# netstat -plant | grep 6001
tcp        0      0 0.0.0.0:6001            0.0.0.0:*               LISTEN      2339/netopeer2-serv
```

on Remote Client the cli get stucked  

```
[root@MaestrOS build]# ./netopeer2-cli
> connect --host 10.1.17.37 --port 6001 --login security
nc ERROR: Unable to connect to 10.1.17.37:6001.
cmd_connect: Connecting to the 10.1.17.37:6001 as user "security" failed.
> quit
[root@MaestrOS build]#
[root@MaestrOS build]#
[root@MaestrOS build]#
[root@MaestrOS build]#
[root@MaestrOS build]#
[root@MaestrOS build]#
[root@MaestrOS build]#
[root@MaestrOS build]#
[root@MaestrOS build]# ./netopeer2-cli
> connect --host 10.1.17.37 --port 6001 --login security
Interactive SSH Authentication
Type your password:
Password:
```

**Comment by vishalwc** [comment]
the above observation is with the  netopeer-server & sysrepo  compiled with x86-64 toolchain and running on x86_64 based server 
through netstat -plant | grep 6001it seems it is waiting for connection to get disconnected from server side and new connection from remote end has been stalled

**Comment by michalvasko** [comment]
Hi,
what you are describing seems to me is basically a feature, not a bug, of sockets. Anyway, I don't think there is anything to be fixed in CLI or server. I would focus on failing to connect to the server the first time, that should not happen, what did the server print?

Regards,
Michal

**Comment by ostack** [comment]
this issue may be same with #14

**Comment by jjin62** [comment]
with all the latest code built (sysrepo, libyang, libnetconf2 and netopeer2), I saw the similar issue:

~/datastore/Netopeer2/cli/build$ ./netopeer2-cli 
> connect -p 6001 --login root
Interactive SSH Authentication
Type your password:
Password: 
nc ERROR: Session 2: error reply to a <get-schema> RPC (tag "invalid-value", message "The requested format is not supported.").
nc ERROR: Session 2: error reply to a <get-schema> RPC (tag "invalid-value", message "The requested format is not supported.").
ly ERROR: Importing "ietf-netconf-acm" module into "ietf-netconf" failed.
ly ERROR: Module "ietf-netconf" parsing failed.
nc ERROR: Loading base NETCONF schema failed.
cmd_connect: Connecting to the localhost:6001 as user "root" failed.
> 

on the server side:
netopeer2-server[3529]: Session 1: SSH channel unexpectedly closed.

**Comment by jjin62** [comment]
when I run Netpeer2-cli as root, it works.

**Comment by michalvasko** [comment]
Hi,
then it seems to be a problem with access rights or your user *netopeer2-cli* settings. It's hard for me to help you if it's the former, to make sure it is not the latter just delete directory `~/.netopeer2-cli`.

Regards,
Michal

**Comment by jjin62** [comment]
thanks for the help. non-root user works now after deleting .netopeer2-cli.

BTW, is it possible to run netopee2-server as non-root user? when I try it, I got:

~/Netopeer2/server/build$ ./netopeer2-server -d -v 3
netopeer2-server[31537]: Unable to open Netopeer2 PID file '/var/run/netopeer2-server.pid': Permission denied.

**Comment by michalvasko** [comment]
Hi,
no, the server must be run with root privileges.

Regards,
Michal
