### ISSUE TITLE
 "ietf-netconf" feature "writable-running" not enabled in sysrepo.

### ISSUE THREAD

**Issue by rosy8** [CESNET/netopeer2#330]
Hi Michal,

I was trying to run with the latest code.. 
But while running  netopeer2-server , I am getting the following error ..

<b>ERROR: Module "ietf-netconf" feature "writable-running" not enabled in sysrepo. </b>
ERROR: Server init failed.
VERBOSE: Client Subscription Manager successfully destroyed.

Have I  missed something here ?
Regards,
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
`# make install` of *netopeer2-server* should fix this, it will install and enable all the features it needs.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Thank you for your reply.
I have copied all the required lib/bin related to sysrepo/netopeer etc to my box ( In my case build server and box are different setup).

==Sysrepo runs as usual as i have pointed out eralier...

[DBG] Setting log level for stderr logs to 4.
[DBG] Connection Manager init started.
[DBG] Initiating circular buffer for 10 elements.
[DBG] Session Manager initialized successfully, ctx=0x603230.
[DBG] Initializing sysrepo server at socket=/var/run/sysrepod.sock
[DBG] Request Processor init started.
[DBG] Initiating circular buffer for 10 elements.
[DBG] Circular buffer enqueue to position=0, current count=1.
[DBG] Notification store cleanup timer set up for 600 seconds.
[DBG] Notification Processor initialized successfully.
[INF] Initializing Data Manager, schema_search_dir=/etc/sysrepo/yang/, data_search_dir=/etc/sysrepo/data/
[DBG] Connection Manager initialized successfully.
[INF] Sysrepo daemon initialized successfully.
[DBG] Starting CM event loop.
[DBG] New message enqueued into CM message queue.
[DBG] Circular buffer dequeue, new buffer head=1, count=0.
[DBG] Scheduling a delayed request for 600.000000 seconds.
[DBG] Starting worker thread id=140737314277120.
[DBG] Thread id=140737314277120 will wait.
[DBG] Starting worker thread id=140737305884416.
[DBG] Thread id=140737305884416 will wait.
[DBG] Starting worker thread id=140737297491712.
[DBG] Thread id=140737297491712 will wait.
[DBG] Starting worker thread id=140737289099008.
[DBG] Thread id=140737289099008 will wait.

 But when i start netopeer-server then the problem starts..

=================== snippet of the sysrepo log ===========
[DBG] Processing unsubscribe request.
[DBG] Notification unsubscribe: dst_address='/var/run/sysrepo-subscriptions/_global-subscriptions/25208.0a8ezK.sock', dst_id=602563539.
[DBG] Circular buffer enqueue to position=2, current count=1.
[DBG] New message enqueued into CM message queue.
[DBG] Circular buffer dequeue, new buffer head=3, count=0.
[DBG] Sending 27 bytes of data.
[DBG] 27 bytes of data sent.
[DBG] fd 6 readable (revents 1)
[DBG] 107 bytes of data received on fd 6
[DBG] fd 6 would block
[DBG] New message of size 103 bytes received.
[DBG] Circular buffer enqueue to position=0, current count=1.
[DBG] Threads: active=1/4, 1 requests in queue
[DBG] Circular buffer dequeue, new buffer head=1, count=0.
[DBG] Processing unsubscribe request.
[DBG] Notification unsubscribe: dst_address='/var/run/sysrepo-subscriptions/_global-subscriptions/25208.0a8ezK.sock', dst_id=340627798.
[DBG] Circular buffer enqueue to position=3, current count=1.
[DBG] New message enqueued into CM message queue.
[DBG] Circular buffer dequeue, new buffer head=4, count=0.
[DBG] Sending 27 bytes of data.
[DBG] 27 bytes of data sent.
[DBG] fd 7 readable (revents 1)
[DBG] Input buffer for fd=7 expanded to 1024 bytes.
[DBG] Peer on fd 7 disconnected.
[INF] Closing the connection 0x68b730.
[DBG] Subscription server at '/var/run/sysrepo-subscriptions/_global-subscriptions/25208.0a8ezK.sock' has disconnected.
[DBG] Requesting removal of subscriptions for the destination '/var/run/sysrepo-subscriptions/_global-subscriptions/25208.0a8ezK.sock'.
[DBG] Circular buffer enqueue to position=1, current count=1.
[DBG] Threads: active=1/4, 1 requests in queue
[DBG] Connection stop requested, fd=7.
[DBG] fd 6 readable (revents 1)
[DBG] Peer on fd 6 disconnected.
[INF] Closing the connection 0x68bc40.
[DBG] RP session stop, session id=662640048.
[WRN] There are some (1) unprocessed messages for the session id=662640048 when session stop has been requested, this can lead to unspecified behavior - check RP caller code!!!
[INF] Dropping session id=662640048.
[DBG] Connection stop requested, fd=6.
[DBG] RP session cleanup, session id=662640048.
[INF] Unlock datastore request
[DBG] Circular buffer dequeue, new buffer head=2, count=0.
[DBG] Processing unsubscribe destination request.
[DBG] Thread id=140737314277120 will wait.


=============snippet of netopeer log =============================

ERBOSE: Loading schema "ietf-netconf-server@2016-11-02" from sysrepo.
VERBOSE: Reading module "ietf-netconf-server".
VERBOSE: Reading module "ietf-x509-cert-to-name".
VERBOSE: Module "ietf-x509-cert-to-name@2014-12-10" successfully parsed as imported.
VERBOSE: Reading module "ietf-ssh-server".
VERBOSE: Reading module "ietf-keystore".
VERBOSE: Module "ietf-keystore@2016-10-31" already in context.
VERBOSE: Module "ietf-keystore@2016-10-31" successfully parsed as implemented.
VERBOSE: Module "ietf-ssh-server@2016-11-02" successfully parsed as imported.
VERBOSE: Reading module "ietf-tls-server".
VERBOSE: Module "ietf-tls-server@2016-11-02" successfully parsed as imported.
VERBOSE: Resolving "ietf-netconf-server" unresolved schema nodes and their constraints...
WARNING: Identity found, but in a non-implemented module "ietf-x509-cert-to-name".
WARNING: Failed to resolve identityref "ietf-x509-cert-to-name:specified". (/ietf-netconf-server:map-type)
WARNING: Previous warning generated by XPath subexpression[3] "map-type = 'ietf-x509-cert-to-name:specified'".
WARNING: Identity found, but in a non-implemented module "ietf-x509-cert-to-name".
WARNING: Failed to resolve identityref "ietf-x509-cert-to-name:specified". (/ietf-netconf-server:map-type)
WARNING: Previous warning generated by XPath subexpression[3] "map-type = 'ietf-x509-cert-to-name:specified'".
VERBOSE: All "ietf-netconf-server" schema nodes and constraints resolved.
VERBOSE: Module "ietf-netconf-server@2016-11-02" successfully parsed as implemented.
VERBOSE: Loading schema "ietf-x509-cert-to-name@2014-12-10" from sysrepo.
VERBOSE: Module ietf-x509-cert-to-name@2014-12-10 already present in context.
VERBOSE: Loading schema "ietf-ssh-server@2016-11-02" from sysrepo.
VERBOSE: Module ietf-ssh-server@2016-11-02 already present in context.
VERBOSE: Loading schema "ietf-tls-server@2016-11-02" from sysrepo.
VERBOSE: Module ietf-tls-server@2016-11-02 already present in context.
VERBOSE: Loading schema "ietf-netconf-notifications@2012-02-06" from sysrepo.
VERBOSE: Reading module "ietf-netconf-notifications".
VERBOSE: Reading module "ietf-netconf".
VERBOSE: Module "ietf-netconf@2011-06-01" already in context.
VERBOSE: Module "ietf-netconf@2011-06-01" successfully parsed as implemented.
VERBOSE: Resolving "ietf-netconf-notifications" unresolved schema nodes and their constraints...
VERBOSE: All "ietf-netconf-notifications" schema nodes and constraints resolved.
VERBOSE: Module "ietf-netconf-notifications@2012-02-06" successfully parsed as implemented.
VERBOSE: Loading schema "nc-notifications@2008-07-14" from sysrepo.
VERBOSE: Reading module "nc-notifications".
VERBOSE: Reading module "notifications".
VERBOSE: Module "notifications@2008-07-14" successfully parsed as imported.
VERBOSE: Module "nc-notifications@2008-07-14" successfully parsed as implemented.
VERBOSE: Loading schema "notifications@2008-07-14" from sysrepo.
VERBOSE: Module notifications@2008-07-14 already present in context.
<b>ERROR: Module "ietf-netconf" feature "candidate" not enabled in sysrepo. </b>
ERROR: Server init failed.
VERBOSE: Client Subscription Manager successfully destroyed.
[root@MaestrOS yang]#

SInce we are not using writable-running so I had commented that part of the code from netopeer.
So now I am getting error for the candidate..

Please let me know if I have to  specifically enable these feature in sysrepo   ??
Or I am missing something during the installation process..

Regards,
Haripriya Patel

**Comment by michalvasko** [comment]
Hi Rosy,
normally, if you `make` and `# make install` *libyang*, *sysrepo*, *libnetconf2*, and *netopeer2-server* in this order, it will work because during netopeer installation all the required models and features are enabled in sysrepo. However, you mentioned some copying of files. That should also work, but you must also copy the repository after all the installation steps I have mentioned.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

It got resolved. 
Thank you.

Regards,
Rosy

**Comment by koala027** [comment]
Hi Rosy8, could you share your final soulution, since i meet the same issue, thanks a lot!

**Comment by D21IT184** [comment]
Hey rosy8 how did you resolve it, you did the steps as michal said or any other solution

**Comment by macauleycheng** [comment]
According to cmake_install.cmake in Netopeer2/build folder. It will do some script located in /usr/share/netopeer2/scripts/.
After you installed you will find it. If you do copy related files, you shall run this scripts by yourself.

NP2_MODULE_DIR="/usr/share/yang/modules/netopeer2"
NP2_MODULE_OWNER="root"
NP2_MODULE_GROUP="root"
NP2_MODULE_PERMS=600
LN2_MODULE_DIR="/usr/share/yang/modules/libnetconf2"
/usr/share/netopeer2/scripts/setup.sh
/usr/share/netopeer2/scripts/merge_hostkey.sh
/usr/share/netopeer2/scripts/merge_config.sh
