### ISSUE TITLE
Dose netopeer2-server have heartbeat?

### ISSUE THREAD

**Issue by leimgitub** [CESNET/netopeer2#336]
My netopeer2-server version is 0.5.26.

I found netopeer2-server continue said "netopeer2-server[1637]: nc_session_rpc_lock: internal error /libs_pub/libnetconf2/src/session.c:203)."

Is there a heartbeat in the code, so the other application to monitor heartbeat. If the heartbeat fail, I can restart netopeer2-server.

Thanks advance.

**Comment by michalvasko** [comment]
Hi,
there should be a TCP/IP keep-alive so there is no need to restart *netopeer2-server*. Still, the error is a weird one, can you maybe provide some information so I can reproduce it?

Regards,
Michal
