### ISSUE TITLE
OpenSSH-7.8's new key format breaks key conversion

### ISSUE THREAD

**Issue by jktjkt** [CESNET/Netopeer2#337]
Just a heads up related to `keystored/scripts/ssh-key-import.sh`. OpenSSH 7.8 changed its default key format also for SSH host keys, and therefore simply copying stuff won't work. There's a [pending patch for libssh](https://www.libssh.org/archive/libssh/2018-09/0000007.html), but in the meanwhile, we should probably consider just generating a new keypair for the NETCONF server.

This is as simple as calling:
```bash
ssh-keygen -m pem -t rsa -q -N "" -f /etc/keystored/keys/ssh_host_rsa_key.pem
```

**Comment by michalvasko** [comment]
Hi,
thanks, I have made the change now.

Regards,
Michal
