### ISSUE TITLE
netopeer2: Failed to set hostkey "ssh_host_rsa_key" (/etc/keystored/keys/ssh_host_rsa_key.pem)

### ISSUE THREAD

**Issue by hzc9107** [CESNET/Netopeer2#339]
## Summary
- Installing Netopeer2 on openWRT system
- netopeer2-server installs netopeer2-keystore
- **Problem**: Failed to set hostkey when receiving a message

## Description
I am using the openWRT build system in order to create an OS image for a networking switch. I would like to add Netopeer2-server in order to be able to configure the switch using netconf from an ODL controller. I have successfully compiled the OS image, but when I try establishing a netconf session it keeps giving the message:

```
VERBOSE: Accepted a connection on :::830.                                                                                                                               
ERROR: Failed to set hostkey "ssh_host_rsa_key" (/etc/keystored/keys/ssh_host_rsa_key.pem).          
```

I had experienced this error once before when installing the netopeer2 server on a virtualmachine. That time the error went away once I generated the file, but in this case the file is there and the contents are what they are expected to be. Therefore I suspect the error must be somewhere else. I have checked a previous thread here asking for the same error, and there it was mentioned that it might be a library issue with sysrepo or libssh. Below is the result for the `sysrepoctl -l` command:

```
Module Name                | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
nc-notifications           | 2008-07-14 | Installed   | root:root           | 666         |                               |
ietf-netconf-acm           | 2012-02-22 | Installed   | root:root           | 644         |                               |
ietf-netconf-notifications | 2012-02-06 | Installed   | root:root           | 600         |                               |
ietf-netconf               | 2011-06-01 | Implemented | root:root           | 600         |                               | writable-running candidate rollback-on-error validate startup xpath
ietf-keystore              | 2016-10-31 | Installed   | root:root           | 600         |                               |
ietf-ssh-server            | 2016-11-02 | Installed   |                     |             |                               |
ietf-tls-server            | 2016-11-02 | Installed   |                     |             |                               |
iana-crypt-hash            | 2014-08-06 | Installed   |                     |             |                               |
ietf-x509-cert-to-name     | 2014-12-10 | Installed   |                     |             |                               |
ietf-netconf-server        | 2016-11-02 | Installed   | root:root           | 600         |                               | listen ssh-listen
ietf-netconf-monitoring    | 2010-10-04 | Installed   | root:root           | 600         |                               |
ietf-netconf-with-defaults | 2011-06-01 | Installed   |                     |             |                               |
ietf-system                | 2014-08-06 | Installed   | root:root           | 600         |                               | authentication local-users`
```

I am wondering if this modules make sense for the deployment of netopeer2 using the keystore, given that the version that I installed on the virtualmachine didn't use the keystore and therefore the libraries are different. Also the versions of the library that I am currently using are:

- libssh.so.4.4.2
- libnetconf2.so.0.11.37
- libyang.so.0.15.130
- libsysrepo.so.0.7.4

I would really appreciate it if you could provide some insights on the topic.

**Comment by michalvasko** [comment]
Hi,
I am not sure what the problem may be. Are you sure file `/etc/keystored/keys/ssh_host_rsa_key.pem` exists and is accessible? Is it the correct format meaning does it start with `-----BEGIN RSA PRIVATE KEY-----`?

Regards,
Michal

**Comment by hzc9107** [comment]
You are right, there was a problem with the key. It seems that the flow was generating a OpenSSH rsa private key and was not being recognized by the server.

Thanks a lot for the help,

Hugo
