### ISSUE TITLE
Operational data not showing in Netopeer2-cli

### ISSUE THREAD

**Issue by yuliya2017** [CESNET/Netopeer2#340]
Hi all, 
I am using Netopeer2 and Sysrepo to communicate with device and use Netconf/Yang to configure the device. I have successfully created yang model that I am able to use to edit the device settings, however there are state data also present. I have used `oper_data_example.c ` as an example to read state data.
When I execute `get-config` command in `netopeer2-cli` the response shows all details of configurable elements of the device in the `netopeer2-cli`, and state data info shows up only in `sysrepo-plugind` window. 
I was wondering what am I missing in order to get state data showing in the netopeer2-cli window with all the rest of device information. 

Thank you for your help in advance. 

Kind Regards, 
Yuliya

**Comment by jktjkt** [comment]
Don't use the `get-config` command, use `get`. These two operations are different, check https://tools.ietf.org/html/rfc6241#section-7.1 and https://tools.ietf.org/html/rfc6241#section-7.7 .

**Comment by yuliya2017** [comment]
Hi Jan,

Thank you for your help. I totally forgot about get command.

Many Thanks,

Yuliya Verbishchuk
MSc. Student

________________________________
