### ISSUE TITLE
Support for SSH's proxy jumping

### ISSUE THREAD

**Issue by jktjkt** [CESNET/netopeer2#341]
It is quite useful (e.g., in a lab) to access stuff via an SSH jump host. The `libssh` library [supports the `ProxyCmd` stanza from `ssh_config`](http://api.libssh.org/master/group__libssh__session.html#gaaa9d400920cad4d6e4a0fb09ff8c7b01), but `netopeer2-cli` manages its own TCP socket and therefore it is not possible to connect via a SSH proxy.

**Comment by michalvasko** [comment]
So, are you fine with just exposing this *libssh* option using a *libnetconf2* API function or did you have something else in mind?

Regards,
Michal

**Comment by jktjkt** [comment]
In a perfect world, I would love to have `netopeer2-cli` follow my SSH settings, and therefore also the `ProxyCmd`. A strong reason for that is the fact that it is already using my user account's `.ssh/known_hosts`. One can always hack around this via SSH tunneling and `tsocks` which is what I'm using right now, so this is a low-priority wishlist item from me.

As I'm experimenting with the libnetconf2 APIs more (I have some client C++ bindings which I plan on submitting in a week or two), I am bumping into more bits I do not fully understand. I'll keep you posted.
