### ISSUE TITLE
Could we open source the project based on Netopeer2?

### ISSUE THREAD

**Issue by HongjunNi** [CESNET/Netopeer2#342]
Hi guys,

We have developed a project based on Netopeer2, and want to upstream it to a community with Apache 2.0 License.  Is this ok for us to do so?

Thanks,
Hongjun

**Comment by jktjkt** [comment]
Short answer is **yes**. If you're interested in details and/or if you're actually modifying the Netopeer2 itself, you shoud read [its very short license](https://github.com/CESNET/Netopeer2/blob/master/LICENSE) for a list of requirements that you have to do.

**Comment by HongjunNi** [comment]
Thank you Jan. 
Yes, we will follow all the requirements in the license.

**Comment by HongjunNi** [comment]
Hi Jan,

We want to open source a project, which name is Sweetcomb. And we will mention in its introduction that this project leverages Netopeer2 project.  Do we need your prior written permission as per Netopeer2 License?

Thanks a lot,
Hongjun

**Comment by HongjunNi** [comment]
Hi Jan,

We want to open source a project named Sweetcomb, which is developed on Netopeer2 project. We will mention in its introduction that this project leverages Netopeer2 project. Do we need your prior written permission as per Netopeer2 License?

Thanks a lot,
Hongjun

**Comment by HongjunNi** [comment]
Hi Jan,

We want to open source a project named Sweetcomb, which is developed on netopeer2 project. We will mention in its introduction that this project leverages Netopeer2 project. Do we need your prior written permission as per Netopeer2 License?

Thanks a lot,
Hongjun

**Comment by HongjunNi** [comment]
Hi Jan,

We want to open source a project named Sweetcomb, which is developed on netopeer2 project. We will mention in its introduction that this project leverages Netopeer2 project. Do we need your prior written permission as per Netopeer2 License?

Thanks a lot,
Hongjun

**Comment by HongjunNi** [comment]
Hi Jan,

We want to open source a project named Sweetcomb, which is developed on netopeer2 project. We will mention in its introduction that this project leverages Netopeer2 project. Do we need your prior written permission as per Netopeer2 License?

Thanks a lot,
Hongjun

**Comment by HongjunNi** [comment]
Hi Jan,

We want to open source a project named Sweetcomb, which is developed on netopeer2 project. We will mention in its introduction that this project leverages Netopeer2 project. Do we need your prior written permission as per Netopeer2 License?

Thanks a lot,
Hongjun

**Comment by HongjunNi** [comment]
Hi Jan,

We want to open source a project named Sweetcomb, which is developed on netopeer2 project. We will mention in its introduction that this project leverages Netopeer2 project. Do we need your prior written permission as per Netopeer2 License?

Thanks a lot,
Hongjun

**Comment by HongjunNi** [comment]
Hi Jan,

We want to open source a project named Sweetcomb, which is developed on netopeer2 project. We will mention in its introduction that this project leverages Netopeer2 project. Do we need your prior written permission as per Netopeer2 License?

Thanks a lot,
Hongjun

**Comment by HongjunNi** [comment]
Hi Jan,

We want to open source a project named Sweetcomb, which is developed on netopeer2 project. We will mention in its introduction that this project leverages Netopeer2 project. Do we need your prior written permission as per Netopeer2 License?

Thanks a lot,
Hongjun

**Comment by HongjunNi** [comment]
Hi Jan,

We want to open source a project named Sweetcomb, which is developed on netopeer2 project. We will mention in its introduction that this project leverages Netopeer2 project. Do we need your prior written permission as per Netopeer2 License?

Thanks a lot,
Hongjun
