### ISSUE TITLE
Error while compiling netopeer2 server

### ISSUE THREAD

**Issue by vprasad** [CESNET/netopeer2#343]
Hi ,

I am trying to compile the netopeer2 on qnx .
I am compiled the libyang and libnetconf2 with SSH enabled .
However when i try to compile netopeer2 it gives following error:-

-- Looking for pthread_rwlockattr_setkind_np - not found
-- Looking for NC_ENABLED_SSH
-- Looking for NC_ENABLED_SSH - not found
-- Looking for NC_ENABLED_TLS
-- Looking for NC_ENABLED_TLS - not found
CMake Error at CMakeLists.txt:140 (message):
  Missing SSH support in libnetconf2, server requires SSH to be supported.

May i know why "NC_ENABLED_SSH" flags are not found.?

Thanks,

**Comment by michalvasko** [comment]
Well, it says it right there, "Missing SSH support in libnetconf2", I do not know what I should add to that. Compile libnetconf2 properly first, then you can move on to netopeer2.

Regards,
Michal

**Comment by Arvliu** [comment]
@vprasad , How did you solve the "Missing SSH support in libnetconf2, server requires SSH to be supported. " issue?
