### ISSUE TITLE
Error in model-install.sh.in script

### ISSUE THREAD

**Issue by bhart3** [CESNET/Netopeer2#348]
As of commit 2c1e69b, we are seeing a failure in our Travis CI build for netopeer2 integration tests.

```
[ERR] (srctl_ly_log_cb:506) libyang: Unable to use search directory "/tmp/repo/Netopeer2/server/../../modules" (No such file or directory)
Error: Unable to initialize libyang context.
```

Here is a link to the build: https://travis-ci.org/ADTRAN/netopeer2-integration-tests/builds/452476348
(Lines 2857-2858 is the error)

This error is caused by incorrect paths in server/scripts/model-install.sh.in. When CMake converts the script, the new location is in server/model-install.sh. However, the paths are with respect to the original location. Therefore, I think this:

```
: ${STOCK_CONFIG:=$local_path/../stock_config.xml}
: ${YANG_DIR:=$local_path/../../modules}
```

should be this:

```
: ${STOCK_CONFIG:=$local_path/stock_config.xml}
: ${YANG_DIR:=$local_path/../modules}
```

Alternatively, CMake could just put the converted script in its original location.

**Comment by michalvasko** [comment]
Hi,
please try it now.

Regards,
Michal
