### ISSUE TITLE
netopeer2 server working via ipv6

### ISSUE THREAD

**Issue by dong-accelink1** [CESNET/Netopeer2#349]
Hello, 
Would like to know how to let netopeer2 server works in ipv6 environment, another machine can connect the node by ssh command alone, but netopeer2 cli reports connection refused with ip6 addr.

> connect --host fe80::20c:29ff:fea4:2793%ens33 --login test
nc ERROR: Unable to connect to fe80::20c:29ff:fea4:2793%ens33:830 (Connection refused).
cmd_connect: Connecting to the fe80::20c:29ff:fea4:2793%ens33:830 as user "test" failed.

many thanks,
Regards

**Comment by dong-accelink1** [comment]
BTW, netopeer2 cli works well if using IPv4 addr

**Comment by michalvasko** [comment]
Hi,
I am not sure what the problem may be but try to increase verbosity first, whether that does not provide a hint (`verb verbose`). So, you can connect from the same machine with `ssh(1)` but not with *netopeer2-cli*?

Regards,
Michal

**Comment by dong-accelink1** [comment]
Hi Michal,

thanks for your response first. the setup is
1. the machine A( is running netopeer2-server): 
ifconfig
ens33     Link encap:Ethernet  HWaddr 00:0c:29:a4:27:93
          inet addr:10.100.103.30  Bcast:10.100.103.255  Mask:255.255.255.0
          inet6 addr: fe80::20c:29ff:fea4:2793/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:17448 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4365 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1770114 (1.7 MB)  TX bytes:1921228 (1.9 MB)
          Interrupt:19 Base address:0x2000

2. another node B:
ifconfig
ens33     Link encap:Ethernet  HWaddr 00:0c:29:d3:1c:93
          inet addr:10.100.103.25  Bcast:10.100.103.255  Mask:255.255.255.0
          inet6 addr: fe80::20c:29ff:fed3:1c93/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:38954 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4178 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:3572863 (3.5 MB)  TX bytes:486247 (486.2 KB)
          Interrupt:19 Base address:0x2000

if I use ssh command on node B to connect to node A, it is ok, log is
~$ ssh -vv -6 fe80::20c:29ff:fea4:2793%ens33
OpenSSH_7.2p2 Ubuntu-4ubuntu2.4, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: resolving "fe80::20c:29ff:fea4:2793%ens33" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to fe80::20c:29ff:fea4:2793%ens33 [fe80::20c:29ff:fea4:2793%ens33] port 22.
debug1: Connection established.
debug1: key_load_public: No such file or directory
debug1: identity file /home/test/.ssh/id_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/test/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/test/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/test/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/test/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/test/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/test/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/test/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.4
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.4
debug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.4 pat OpenSSH* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to fe80::20c:29ff:fea4:2793%ens33:22 as 'test'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
debug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:auoC3JZiS9QZeVAkzu1fh+12seex5nA1e8n0htvi4zo
debug1: Host 'fe80::20c:29ff:fea4:2793%ens33' is known and matches the ECDSA host key.
debug1: Found key in /home/test/.ssh/known_hosts:2
debug2: set_newkeys: mode 1
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug2: set_newkeys: mode 0
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS received
debug2: key: /home/test/.ssh/id_rsa ((nil))
debug2: key: /home/test/.ssh/id_dsa ((nil))
debug2: key: /home/test/.ssh/id_ecdsa ((nil))
debug2: key: /home/test/.ssh/id_ed25519 ((nil))
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey,password
debug1: Next authentication method: publickey
debug1: Trying private key: /home/test/.ssh/id_rsa
debug1: Trying private key: /home/test/.ssh/id_dsa
debug1: Trying private key: /home/test/.ssh/id_ecdsa
debug1: Trying private key: /home/test/.ssh/id_ed25519
debug2: we did not send a packet, disable method
debug1: Next authentication method: password
test@fe80::20c:29ff:fea4:2793%ens33's password:
debug2: we sent a password packet, wait for reply
debug1: Authentication succeeded (password).
Authenticated to fe80::20c:29ff:fea4:2793%ens33 ([fe80::20c:29ff:fea4:2793%ens33]:22).
debug1: channel 0: new [client-session]
debug2: channel 0: send open
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug2: callback start
debug2: fd 3 setting TCP_NODELAY
debug2: client_session2_setup: id 0
debug2: channel 0: request pty-req confirm 1
debug1: Sending environment.
debug1: Sending env LANG = en_US.UTF-8
debug2: channel 0: request env confirm 0
debug2: channel 0: request shell confirm 1
debug2: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug2: channel_input_status_confirm: type 99 id 0
debug2: PTY allocation request accepted on channel 0
debug2: channel 0: rcvd adjust 2097152
debug2: channel_input_status_confirm: type 99 id 0
debug2: shell request accepted on channel 0
Welcome to Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-116-generic i686)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
Last login: Mon Nov 12 00:22:51 2018 from fe80::20c:29ff:fed3:1c93%ens33
test@ubuntu:~$

But when I start netopeer2-cli to connect to netopeer2-server on node A, the log is:
> verb debug
> connect --host fe80::20c:29ff:fea4:2793 --login test
nc ERROR: Unable to connect to fe80::20c:29ff:fea4:2793:830 (Invalid argument).
cmd_connect: Connecting to the fe80::20c:29ff:fea4:2793:830 as user "test" failed.
> connect --host fe80::20c:29ff:fea4:2793%ens33 --login test
nc ERROR: Unable to connect to fe80::20c:29ff:fea4:2793%ens33:830 (Connection refused).
cmd_connect: Connecting to the fe80::20c:29ff:fea4:2793%ens33:830 as user "test" failed.
> verb verbose
> connect --host fe80::20c:29ff:fea4:2793%ens33 --login test
nc ERROR: Unable to connect to fe80::20c:29ff:fea4:2793%ens33:830 (Connection refused).
cmd_connect: Connecting to the fe80::20c:29ff:fea4:2793%ens33:830 as user "test" failed.
> connect --host 10.100.103.30 --login test
nc VERBOSE: Successfully connected to 10.100.103.30:830 over IPv4.
[2018/11/12 00:20:05.247234, 2] ssh_connect:  libssh 0.7.5 (c) 2003-2014 Aris Adamantiadis, Andreas Schneider, and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
[2018/11/12 00:20:05.247274, 2] ssh_connect:  Socket connecting, now waiting for the callbacks to work
[2018/11/12 00:20:05.247313, 1] socket_callback_connected:  Socket connection callback: 1 (0)
[2018/11/12 00:20:05.253206, 1] ssh_client_connection_callback:  SSH server banner: SSH-2.0-libssh_0.7.5
[2018/11/12 00:20:05.253246, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-libssh_0.7.5
[2018/11/12 00:20:05.379588, 2] ssh_packet_dh_reply:  Received SSH_KEXDH_REPLY
[2018/11/12 00:20:05.401816, 2] ssh_client_curve25519_reply:  SSH_MSG_NEWKEYS sent
[2018/11/12 00:20:05.402403, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
[2018/11/12 00:20:05.403453, 2] ssh_packet_newkeys:  Signature verified and valid
[2018/11/12 00:20:05.403919, 1] ssh_userauth_request_service:  Failed to request "ssh-userauth" service
[2018/11/12 00:20:05.406510, 2] ssh_packet_userauth_failure:  Access denied. Authentication that can continue: publickey,keyboard-interactive,password
[2018/11/12 00:20:05.406748, 1] ssh_packet_userauth_failure:  Access denied. Authentication that can continue: publickey,keyboard-interactive,password
nc VERBOSE: Keyboard-interactive authentication.
Interactive SSH Authentication
Type your password:
Password:
nc VERBOSE: Authentication successful.
[2018/11/12 00:20:13.117524, 2] channel_open:  Creating a channel 43 with 64000 window and 32768 max packet
[2018/11/12 00:20:13.118791, 2] ssh_packet_channel_open_conf:  Received a CHANNEL_OPEN_CONFIRMATION for channel 43:43
[2018/11/12 00:20:13.118831, 2] ssh_packet_channel_open_conf:  Remote window : 32000, maxpacket : 35000
[2018/11/12 00:20:13.120295, 2] channel_request:  Channel request subsystem success
ly VERBOSE: Extension plugin "/usr/local/lib/libyang/nacm.so" successfully loaded.
ly VERBOSE: Extension plugin "/usr/local/lib/libyang/metadata.so" successfully loaded.
ly VERBOSE: Reading module "ietf-yang-metadata".
ly VERBOSE: Module "ietf-yang-metadata@2016-08-05" successfully parsed as implemented.
ly VERBOSE: Reading module "yang".
ly VERBOSE: Resolving "yang" unresolved schema nodes and their constraints...
ly VERBOSE: All "yang" schema nodes and constraints resolved.
ly VERBOSE: Module "yang@2017-02-20" successfully parsed as implemented.
ly VERBOSE: Reading module "ietf-inet-types".
ly VERBOSE: Resolving derived type "union" failed, it will be attempted later.
ly VERBOSE: Resolving type default "" failed, it will be attempted later.
ly VERBOSE: Resolving derived type "union" failed, it will be attempted later.
ly VERBOSE: Resolving type default "" failed, it will be attempted later.
ly VERBOSE: Resolving derived type "union" failed, it will be attempted later.
ly VERBOSE: Resolving type default "" failed, it will be attempted later.
ly VERBOSE: Resolving derived type "union" failed, it will be attempted later.
ly VERBOSE: Resolving type default "" failed, it will be attempted later.
ly VERBOSE: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
ly VERBOSE: All "ietf-inet-types" schema nodes and constraints resolved.
ly VERBOSE: Module "ietf-inet-types@2013-07-15" successfully parsed as implemented.
ly VERBOSE: Reading module "ietf-yang-types".
ly VERBOSE: Module "ietf-yang-types@2013-07-15" successfully parsed as implemented.
ly VERBOSE: Reading module "ietf-datastores".
ly VERBOSE: Module "ietf-datastores@2017-08-17" successfully parsed as implemented.
ly VERBOSE: Reading module "ietf-yang-library".
ly VERBOSE: Module "ietf-yang-library@2017-08-17" successfully parsed as implemented.
[2018/11/12 00:20:13.149929, 2] grow_window:  growing window (channel 43:43) to 1280000 bytes
[2018/11/12 00:20:13.197312, 2] channel_rcv_change_window:  Adding 1248212 bytes to channel (43:43) (from 31788 bytes)
ly VERBOSE: Reading module "ietf-netconf-monitoring".
ly VERBOSE: Module "ietf-netconf-monitoring@2010-10-04" successfully parsed as implemented.
ly VERBOSE: Searching for "ietf-netconf" in /usr/local/share/libnetconf2.
ly VERBOSE: Searching for "ietf-netconf" in /home/test/x86/Netopeer2-0.4-r2/cli.
ly VERBOSE: Loading schema from "/usr/local/share/libnetconf2/ietf-netconf.yin" file.
ly VERBOSE: Reading module "ietf-netconf".
ly VERBOSE: Searching for "ietf-netconf-acm" in /usr/local/share/libnetconf2.
ly VERBOSE: Searching for "ietf-netconf-acm" in /home/test/x86/Netopeer2-0.4-r2/cli.
ly VERBOSE: Loading schema from "/usr/local/share/libnetconf2/ietf-netconf-acm.yin" file.
ly VERBOSE: Reading module "ietf-netconf-acm".
ly VERBOSE: Resolving "ietf-netconf-acm" unresolved schema nodes and their constraints...
ly VERBOSE: All "ietf-netconf-acm" schema nodes and constraints resolved.
ly VERBOSE: Module "ietf-netconf-acm@2012-02-22" successfully parsed as imported.
ly VERBOSE: Resolving "ietf-netconf" unresolved schema nodes and their constraints...
ly VERBOSE: All "ietf-netconf" schema nodes and constraints resolved.
ly VERBOSE: Module "ietf-netconf@2011-06-01" successfully parsed as implemented.
ly VERBOSE: Resolving unresolved data nodes and their constraints...
ly VERBOSE: All data nodes and constraints resolved.
ly VERBOSE: Resolving unresolved data nodes and their constraints...
ly VERBOSE: All data nodes and constraints resolved.
ly VERBOSE: Module "org-openroadm-pm-types@2017-12-15" now implemented.
ly VERBOSE: Module "org-openroadm-resource@2018-03-30" now implemented.
ly VERBOSE: Module "org-openroadm-probable-cause@2018-03-30" now implemented.
ly VERBOSE: Module "org-openroadm-user-mgmt@2017-12-15" now implemented.
ly VERBOSE: Module "org-openroadm-swdl@2018-03-30" now implemented.
ly VERBOSE: Module "org-openroadm-switching-pool-types@2017-12-15" now implemented.
ly VERBOSE: Module "org-openroadm-resource-types@2018-03-30" now implemented.
ly VERBOSE: Module "org-openroadm-port-types@2018-03-30" now implemented.
ly VERBOSE: Module "org-openroadm-physical-types@2018-03-30" now implemented.
ly VERBOSE: Module "org-openroadm-interfaces@2018-03-30" now implemented.
ly VERBOSE: Module "org-openroadm-device-types@2018-03-30" now implemented.
ly VERBOSE: Module "org-openroadm-equipment-states-types@2017-12-15" now implemented.
ly VERBOSE: Module "org-openroadm-common-types@2018-03-30" now implemented.
ly VERBOSE: Module "org-openroadm-common-state-types@2018-03-30" now implemented.
ly VERBOSE: Module "org-openroadm-common-optical-channel-types@2018-03-30" now implemented.
ly VERBOSE: Module "org-openroadm-common-node-types@2018-03-30" now implemented.
ly VERBOSE: Module "org-openroadm-common-link-types@2018-03-30" now implemented.
ly VERBOSE: Module "org-openroadm-common-equipment-types@2018-03-30" now implemented.
ly VERBOSE: Module "org-openroadm-common-amplifier-types@2018-03-30" now implemented.
ly VERBOSE: Module "org-openroadm-common-alarm-pm-types@2018-03-30" now implemented.
ly VERBOSE: Module "ietf-x509-cert-to-name@2014-12-10" now implemented.
ly VERBOSE: Module "notifications@2008-07-14" now implemented.
ly VERBOSE: Module "ietf-netconf-acm@2012-02-22" now implemented.
ly VERBOSE: Module "ietf-yang-types@2013-07-15" now implemented.
ly VERBOSE: Module "ietf-inet-types@2013-07-15" now implemented.
> disconnect
> connect --host fe80::20c:29ff:fea4:2793%ens33 --login test
nc ERROR: Unable to connect to fe80::20c:29ff:fea4:2793%ens33:830 (Connection refused).
cmd_connect: Connecting to the fe80::20c:29ff:fea4:2793%ens33:830 as user "test" failed.
>

the problem is: it is ok if connect ipv4 addr of node A, it is connection refused when ipv6 addr is used, expect my log is full, many thanks your analysis in advance.

**Comment by michalvasko** [comment]
Hi,
with `ssh(1)` you are connecting on port `22`, with `netopeer2-cli` on port `830` (that is the NETCONF SSH default). You can test the connection (if you don't trust `netopeer2-cli`) with `ssh(1)` by
```
ssh -vv -6 fe80::20c:29ff:fea4:2793%ens33 -p 830 -s netconf
```

If you then receive the `hello` message, it should be possible to connect with `netopeer2-cli` as well.

Regards,
Michal

**Comment by dong-accelink1** [comment]
Hi Michal,

Many thanks for your quick response, you are correct that the command can not run successfully, it is
~$ ssh -vv -6 fe80::20c:29ff:fea4:2793%ens33 -p 830 -s netconf
OpenSSH_7.2p2 Ubuntu-4ubuntu2.4, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: resolving "fe80::20c:29ff:fea4:2793%ens33" port 830
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to fe80::20c:29ff:fea4:2793%ens33 [fe80::20c:29ff:fea4:2793%ens33] port 830.
debug1: connect to address fe80::20c:29ff:fea4:2793%ens33 port 830: Connection refused
ssh: connect to host fe80::20c:29ff:fea4:2793%ens33 port 830: Connection refused
test@ubuntu:~$

then I add port parameter when connecting with netopeer2-cli, the log is 
> connect --host fe80::20c:29ff:fea4:2793%ens33 --port 22 --login test
nc VERBOSE: Successfully connected to fe80::20c:29ff:fea4:2793%ens33:22 over IPv6.
[2018/11/12 00:50:42.432998, 2] ssh_connect:  libssh 0.7.5 (c) 2003-2014 Aris Adamantiadis, Andreas Schneider, and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
[2018/11/12 00:50:42.433032, 2] ssh_connect:  Socket connecting, now waiting for the callbacks to work
[2018/11/12 00:50:42.433058, 1] socket_callback_connected:  Socket connection callback: 1 (0)
[2018/11/12 00:50:42.452847, 1] ssh_client_connection_callback:  SSH server banner: SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.4
[2018/11/12 00:50:42.452901, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.4
[2018/11/12 00:50:42.452940, 1] ssh_analyze_banner:  We are talking to an OpenSSH client version: 7.2 (70200)
[2018/11/12 00:50:42.523025, 2] ssh_packet_dh_reply:  Received SSH_KEXDH_REPLY
[2018/11/12 00:50:42.543470, 2] ssh_client_curve25519_reply:  SSH_MSG_NEWKEYS sent
[2018/11/12 00:50:42.543587, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
[2018/11/12 00:50:42.587245, 2] ssh_packet_newkeys:  Signature verified and valid
The authenticity of the host 'fe80::20c:29ff:fea4:2793%ens33' cannot be established.
ssh-ed25519 key fingerprint is 9d:df:9c:4b:5b:22:2b:db:aa:73:6a:ba:c8:67:c9:c4:46:08:83:68.
Are you sure you want to continue connecting (yes/no)? yes
[2018/11/12 00:50:45.118718, 1] ssh_userauth_request_service:  Failed to request "ssh-userauth" service
[2018/11/12 00:50:45.124451, 2] ssh_packet_userauth_failure:  Access denied. Authentication that can continue: publickey,password
[2018/11/12 00:50:45.124497, 1] ssh_packet_userauth_failure:  Access denied. Authentication that can continue: publickey,password
nc VERBOSE: Password authentication (host "fe80::20c:29ff:fea4:2793%ens33", user "test").
test@fe80::20c:29ff:fea4:2793%ens33 password:
nc VERBOSE: Authentication successful.
[2018/11/12 00:50:47.529491, 2] channel_open:  Creating a channel 43 with 64000 window and 32768 max packet
[2018/11/12 00:50:47.754313, 2] ssh_packet_global_request:  Received SSH_MSG_GLOBAL_REQUEST packet
[2018/11/12 00:50:47.754407, 2] ssh_packet_global_request:  UNKNOWN SSH_MSG_GLOBAL_REQUEST hostkeys-00@openssh.com 0
[2018/11/12 00:50:47.754422, 1] ssh_packet_process:  Couldn't do anything with packet type 80
[2018/11/12 00:50:47.754759, 2] ssh_packet_channel_open_conf:  Received a CHANNEL_OPEN_CONFIRMATION for channel 43:0
[2018/11/12 00:50:47.754787, 2] ssh_packet_channel_open_conf:  Remote window : 0, maxpacket : 32768
[2018/11/12 00:50:47.756128, 1] channel_request:  Channel request subsystem failed
nc ERROR: Starting the "netconf" SSH subsystem failed (Channel request subsystem failed).
cmd_connect: Connecting to the fe80::20c:29ff:fea4:2793%ens33:22 as user "test" failed.
>

it looks like there is still something wrong about ssh, could you please give some suggestions about how to let it work? thanks

Regards,

**Comment by michalvasko** [comment]
Hi,
what are you trying to do? On port `22` you are most likely connecting to `sshd(7)` and without special config it acts as an SSH virtual terminal. *netopeer2-cli* is a NETCONF client so it needs to connect to a NETCONF server. Do you have any running on port `22`?

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
only IPv4 is listened on by default. To change it, you need to enable server configuration (more info in `netopeer2/server/configuration`). Having that working, you just need to change the listen address to, for example, `::`. You can do that with
```
sysrepocfg -d startup -f xml -e vim ietf-netconf-server
```

Regards,
Michal

**Comment by dong-accelink1** [comment]
Hi Michal,

many thanks for your support, I am trying it.  
Regards,
