### ISSUE TITLE
Copy config from candidate to running fails

### ISSUE THREAD

**Issue by bhart3** [CESNET/Netopeer2#351]
This issue was present as of commit b9c54c7.

In our tests, we get an error when we run any tests that try to do this copy-config. The error is:
`RPCError: Request could not be completed because the requested operation failed for a non-specific reason.`

We've written integration tests that demonstrate these copy-config failures. The source code for these tests are [here](https://github.com/ADTRAN/netopeer2-integration-tests/blob/master/tests/test_candidate_config.py#L5) and [here](https://github.com/ADTRAN/netopeer2-integration-tests/blob/master/tests/test_candidate_config.py#L56). The YANG model is [here](https://github.com/ADTRAN/netopeer2-integration-tests/blob/master/yang/test-models/test-candidate-config.yang). The [CI results](https://travis-ci.org/ADTRAN/netopeer2-integration-tests/builds/454203314) at lines 7491 and 7493 for the tests (currently marked as xfail) show the failing test cases.

**Comment by michalvasko** [comment]
Hi,
it should not fail anymore.

Regards,
Michal
