### ISSUE TITLE
netopeer2 server can not authenticate a user - failed to set up a connection

### ISSUE THREAD

**Issue by victor5d** [CESNET/Netopeer2#352]
I've got the latest libyang, libnetconf2, sysrepo and netopeer2 packages yesterday (Nov. 14, 2018). I've got all the packages built and installed on my Ubuntu 18.04.1 linux machine. I started the server successfully with "-v2 -d". But when I tried to set up a session using the netopeer2-cli, it did not go through due to the server failed to authenticate the user. Please note that the same user worked fine with 'ssh user@127.0.0.1' on the same machine.  

Any help would be appreciated.

Below is the output from the server:
-----------------------------------------------
[INF]: Netopeer2 connected to sysrepod.
[INF]: Plugin "/usr/local/lib/libyang/extensions/nacm.so" successfully loaded.
[INF]: Plugin "/usr/local/lib/libyang/extensions/libyang_ext_test.so" successfully loaded.
[INF]: Plugin "/usr/local/lib/libyang/extensions/metadata.so" successfully loaded.
[INF]: Plugin "/usr/local/lib/libyang/extensions/yangdata.so" successfully loaded.
[INF]: Plugin "/usr/local/lib/libyang/user_types/user_date_and_time.so" successfully loaded.
[INF]: Reading module "ietf-yang-metadata".
[INF]: Module "ietf-yang-metadata@2016-08-05" successfully parsed as implemented.
[INF]: Reading module "yang".
[INF]: Resolving "yang" unresolved schema nodes and their constraints...
[INF]: All "yang" schema nodes and constraints resolved.
[INF]: Module "yang@2017-02-20" successfully parsed as implemented.
[INF]: Reading module "ietf-inet-types".
[INF]: Resolving derived type "union" failed, it will be attempted later.
[INF]: Resolving derived type "union" failed, it will be attempted later.
[INF]: Resolving derived type "union" failed, it will be attempted later.
[INF]: Resolving derived type "union" failed, it will be attempted later.
[INF]: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
[INF]: All "ietf-inet-types" schema nodes and constraints resolved.
[INF]: Module "ietf-inet-types@2013-07-15" successfully parsed as implemented.
[INF]: Reading module "ietf-yang-types".
[INF]: Module "ietf-yang-types@2013-07-15" successfully parsed as implemented.
[INF]: Reading module "ietf-datastores".
[INF]: Module "ietf-datastores@2017-08-17" successfully parsed as implemented.
[INF]: Reading module "ietf-yang-library".
[INF]: Module "ietf-yang-library@2018-01-17" successfully parsed as implemented.
[INF]: Loading schema "ietf-netconf-notifications@2012-02-06" from sysrepo.
[INF]: Reading module "ietf-netconf-notifications".
[INF]: Reading module "ietf-netconf".
[INF]: Reading module "ietf-netconf-acm".
[INF]: Module "ietf-netconf-acm@2018-02-14" successfully parsed as imported.
[INF]: Module "ietf-netconf@2011-06-01" successfully parsed as imported.
[INF]: Resolving "ietf-netconf-notifications" unresolved schema nodes and their constraints...
[INF]: All "ietf-netconf-notifications" schema nodes and constraints resolved.
[INF]: Module "ietf-netconf-notifications@2012-02-06" successfully parsed as implemented.
[INF]: Loading schema "ietf-netconf@2011-06-01" from sysrepo.
[INF]: Module ietf-netconf@2011-06-01 already present in context.
[INF]: Module "ietf-netconf@2011-06-01" now implemented.
[INF]: Loading schema "ietf-netconf-acm@2018-02-14" from sysrepo.
[INF]: Module ietf-netconf-acm@2018-02-14 already present in context.
[INF]: Loading schema "nc-notifications@2008-07-14" from sysrepo.
[INF]: Reading module "nc-notifications".
[INF]: Reading module "notifications".
[INF]: Module "notifications@2008-07-14" successfully parsed as imported.
[INF]: Module "nc-notifications@2008-07-14" successfully parsed as implemented.
[INF]: Loading schema "notifications@2008-07-14" from sysrepo.
[INF]: Module notifications@2008-07-14 already present in context.
[INF]: Module "notifications@2008-07-14" now implemented.
[INF]: Loading schema "turing-machine@2013-12-27" from sysrepo.
[INF]: Reading module "turing-machine".
[INF]: Module "turing-machine@2013-12-27" successfully parsed as implemented.
[INF]: Loading schema "iana-if-type@2014-05-08" from sysrepo.
[INF]: Reading module "iana-if-type".
[INF]: Reading module "ietf-interfaces".
[INF]: Module "ietf-interfaces@2014-05-08" successfully parsed as imported.
[INF]: Module "iana-if-type@2014-05-08" successfully parsed as implemented.
[INF]: Loading schema "ietf-interfaces@2014-05-08" from sysrepo.
[INF]: Module ietf-interfaces@2014-05-08 already present in context.
[INF]: Module "ietf-interfaces@2014-05-08" now implemented.
[INF]: Loading schema "ietf-ip@2014-06-16" from sysrepo.
[INF]: Reading module "ietf-ip".
[INF]: Module "ietf-ip@2014-06-16" successfully parsed as implemented.
[INF]: Loading schema "ietf-netconf-with-defaults@2011-06-01" from sysrepo.
[INF]: Reading module "ietf-netconf-with-defaults".
[INF]: Module "ietf-netconf-with-defaults@2011-06-01" successfully parsed as implemented.
[INF]: Loading schema "ietf-netconf-monitoring@2010-10-04" from sysrepo.
[INF]: Reading module "ietf-netconf-monitoring".
[INF]: Module "ietf-netconf-monitoring@2010-10-04" successfully parsed as implemented.
[INF]: Loading schema "ietf-yang-library@2018-01-17" from sysrepo.
[INF]: Module ietf-yang-library@2018-01-17 already present in context.
[INF]: Loading schema "ietf-datastores@2017-08-17" from sysrepo.
[INF]: Module ietf-datastores@2017-08-17 already present in context.
[WRN]: Sysrepo does not have the "ietf-netconf-server" module or keystored keys dir unknown, using default NETCONF server options.
[INF]: Listening on 0.0.0.0:830 for SSH connections.
[INF]: Accepted a connection on 0.0.0.0:830.
[2018/11/15 09:19:43.169010, 2] ssh_pki_import_privkey_base64:  Trying to decode privkey passphrase=false
[2018/11/15 09:19:43.170382, 1] ssh_server_connection_callback:  SSH client banner: SSH-2.0-libssh_0.7.0
[2018/11/15 09:19:43.170396, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-libssh_0.7.0
[2018/11/15 09:19:43.219241, 2] ssh_server_curve25519_init:  SSH_MSG_KEX_ECDH_REPLY sent
[2018/11/15 09:19:43.220826, 2] ssh_server_curve25519_init:  SSH_MSG_NEWKEYS sent
[2018/11/15 09:19:43.222254, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
[INF]: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: Received an SSH message "request-auth" of subtype "none".
[INF]: Received an SSH message "request-auth" of subtype "interactive".
[2018/11/15 09:19:43.223508, 2] ssh_message_auth_interactive_request:  Warning: Got a keyboard-interactive response but it seems we didn't send the request.
[ERR]: User "wuq54973" failed to authenticate for too long, disconnecting.

**Comment by michalvasko** [comment]
Hi,
you are most likely experiencing a regression bug of `libssh`, try to update your version to the [most recent](https://www.libssh.org/2018/10/29/libssh-0-8-5-and-libssh-0-7-7/) one. You can verify this by skipping `interactive` and authenticating using `password` authentication, that one should work without problems.

Regards,
Michal

**Comment by victor5d** [comment]
Updated libssh to 0.8.5 and the issue is resolved. Thanks to Michal for his help.

**Comment by michalvasko** [comment]
Hi,
if you are using `netopeer2-cli`, best is to set the highest priority for `password` authentication (command `auth pref ...`). But, it should also work to just pass empty answer for `interactive` authentication so that it fails and the next method is tried.

Regards,
Michal
