### ISSUE TITLE
Edit-config returns incorrect tag for invalid value and disabled feature

### ISSUE THREAD

**Issue by bhart3** [CESNET/Netopeer2#353]
This issue was present as of b52d01c .

In our tests, we are getting an error tag of 'operation-failed' instead of 'invalid-value' when we do an edit-config on a node that has a value restriction and 'operation-failed' instead of 'unknown-element' when we do an edit-config on a node that is disabled by a feature. We have integration tests that demonstrate these failures [here](https://github.com/ADTRAN/netopeer2-integration-tests/blob/master/tests/test_validation.py) at line 25 through 266. The following YANG models were used in these tests:
- [test-validation.yang](https://github.com/ADTRAN/netopeer2-integration-tests/blob/master/yang/test-models/test-validation.yang)
- [test-module.yang](https://github.com/ADTRAN/netopeer2-integration-tests/blob/master/yang/test-models/test-module.yang)
- [test-submodule.yang](https://github.com/ADTRAN/netopeer2-integration-tests/blob/master/yang/test-models/test-submodule.yang)

The [CI Results](https://travis-ci.org/ADTRAN/netopeer2-integration-tests/builds/455586320) are at lines 7604 through 7610.

**Comment by michalvasko** [comment]
Hi,
sorry, I have missed one unnecessary change that should not have made into upstream. I have changed it back without testing in the hope that it was all that was wrong, could you please verify it? If it is not fixed, I will take a real look at it.

Regards,
Michal

**Comment by bhart3** [comment]
It looks like the changes are passing our integration tests. Thanks for the quick feedback!

-Brandon Hart
