### ISSUE TITLE
netopeer2 server failed to start - Unable to connect to sysrepod: The peer disconnected.

### ISSUE THREAD

**Issue by victor5d** [CESNET/Netopeer2#354]
I have had the server/cli worked with the default yang modules. Then , I tried to import some locally defined yang modules (which were working on the libnetconf/netopeer) using 'sysrepoctl' command. The importing failed with the sysrepod coredump. From that point, I could no longer start the netopeer2-server. I guess that the sysrepo repository might have been  corrupted. So I deleted the /etc/sysrepo folder altogether in the hope of restarting the procedure from the scratch would get the thing back again. I rebuilt the stuff, libyang, libnetcong2, sysrepo and netopeer2-server, starting with removing everything form .../build folder. The build and install went smoothly. To be assured, I run "make test" on each of them after built and they were all passed. Unfortunately, I could not start the server anymore. 

Below is the error log from the console:
------------------------------------------------
$ sudo /usr/local/bin/netopeer2-server -v 2 -d &
[1] 13515
$ [INF]: Sysrepo daemon has been started.
[ERR]: Unable to connect to sysrepod: The peer disconnected.
[ERR]: Connecting to sysrepo failed (The peer disconnected).
[ERR]: Server init failed.

Here is the relevant syslog:
------------------------------------
Nov 15 16:26:02 linux64ide netopeer2-server[13592]: Sysrepo daemon has been started.
Nov 15 16:26:02 linux64ide netopeer2-server[13592]: Unable to connect to sysrepod: The peer disconnected.
Nov 15 16:26:02 linux64ide netopeer2-server[13592]: Connecting to sysrepo failed (The peer disconnected).
Nov 15 16:26:02 linux64ide netopeer2-server[13592]: Server init failed.

**Comment by victor5d** [comment]
After restarted the machine, more logs come out:
-----------------------------
$ [INF]: (sr_connect:402) Sysrepo daemon has been started.
[INF]: Netopeer2 connected to sysrepod.
[INF]: Plugin "/usr/local/lib/libyang/extensions/nacm.so" successfully loaded.
[INF]: Plugin "/usr/local/lib/libyang/extensions/libyang_ext_test.so" successfully loaded.
[INF]: Plugin "/usr/local/lib/libyang/extensions/metadata.so" successfully loaded.
[INF]: Plugin "/usr/local/lib/libyang/extensions/yangdata.so" successfully loaded.
[INF]: Plugin "/usr/local/lib/libyang/user_types/user_date_and_time.so" successfully loaded.
[INF]: Reading module "ietf-yang-metadata".
[INF]: Module "ietf-yang-metadata@2016-08-05" successfully parsed as implemented.
[INF]: Reading module "yang".
[INF]: Resolving "yang" unresolved schema nodes and their constraints...
[INF]: All "yang" schema nodes and constraints resolved.
[INF]: Module "yang@2017-02-20" successfully parsed as implemented.
[INF]: Reading module "ietf-inet-types".
[INF]: Resolving derived type "union" failed, it will be attempted later.
[INF]: Resolving derived type "union" failed, it will be attempted later.
[INF]: Resolving derived type "union" failed, it will be attempted later.
[INF]: Resolving derived type "union" failed, it will be attempted later.
[INF]: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
[INF]: All "ietf-inet-types" schema nodes and constraints resolved.
[INF]: Module "ietf-inet-types@2013-07-15" successfully parsed as implemented.
[INF]: Reading module "ietf-yang-types".
[INF]: Module "ietf-yang-types@2013-07-15" successfully parsed as implemented.
[INF]: Reading module "ietf-datastores".
[INF]: Module "ietf-datastores@2017-08-17" successfully parsed as implemented.
[INF]: Reading module "ietf-yang-library".
[INF]: Module "ietf-yang-library@2018-01-17" successfully parsed as implemented.
[INF]: Loading schema "example-module" from sysrepo.
[INF]: Reading module "example-module".
[INF]: Module "example-module" successfully parsed as implemented.
[INF]: Loading schema "test-module" from sysrepo.
[INF]: Reading module "test-module".
[INF]: Reading module "referenced-data".
[INF]: Module "referenced-data" successfully parsed as imported.
[INF]: Resolving "test-module" unresolved schema nodes and their constraints...
[INF]: All "test-module" schema nodes and constraints resolved.
[INF]: Module "test-module" successfully parsed as implemented.
[INF]: Loading schema "referenced-data" from sysrepo.
[INF]: Module referenced-data already present in context.
[INF]: Module "referenced-data" now implemented.
[INF]: Loading schema "small-module" from sysrepo.
[INF]: Reading module "small-module".
[INF]: Module "small-module" successfully parsed as implemented.
[INF]: Loading schema "info-module" from sysrepo.
[INF]: Reading module "info-module".
[INF]: Reading module "small-module".
[INF]: Module "small-module@<latest>" already in context.
[INF]: Module "small-module" successfully parsed as implemented.
[INF]: Module "info-module" successfully parsed as implemented.
[INF]: Loading schema "id-ref-aug" from sysrepo.
[INF]: Reading module "id-ref-aug".
[INF]: Reading module "id-ref-base".
[INF]: Module "id-ref-base" successfully parsed as imported.
[INF]: Reading module "id-def-base".
[INF]: Module "id-def-base" successfully parsed as imported.
[INF]: Resolving "id-ref-aug" unresolved schema nodes and their constraints...
[INF]: All "id-ref-aug" schema nodes and constraints resolved.
[INF]: Module "id-ref-aug" successfully parsed as implemented.
[INF]: Loading schema "id-ref-base" from sysrepo.
[INF]: Module id-ref-base already present in context.
[INF]: Loading schema "id-def-base" from sysrepo.
[INF]: Module id-def-base already present in context.
[INF]: Loading schema "id-ref-hello" from sysrepo.
[INF]: Reading module "id-ref-hello".
[INF]: Reading module "id-ref-hello-cont".
[INF]: Module "id-ref-hello-cont" successfully parsed as imported.
[INF]: Module "id-ref-hello" successfully parsed as implemented.
[INF]: Loading schema "id-ref-hello-cont" from sysrepo.
[INF]: Module id-ref-hello-cont already present in context.
[INF]: Loading schema "id-def-extended" from sysrepo.
[INF]: Reading module "id-def-extended".
[INF]: Module "id-def-extended" successfully parsed as implemented.
[INF]: Loading schema "id-ref-main" from sysrepo.
[INF]: Reading module "id-ref-main".
[INF]: Reading module "id-ref-imported".
[INF]: Module "id-ref-imported" successfully parsed as imported.
[INF]: Module "id-ref-main" successfully parsed as implemented.
[INF]: Loading schema "id-ref-imported" from sysrepo.
[INF]: Module id-ref-imported already present in context.
[INF]: Loading schema "id-ref-installed" from sysrepo.
[INF]: Reading module "id-ref-installed".
[INF]: Reading module "id-ref-extend-main".
[INF]: Reading module "id-ref-main".
[INF]: Module "id-ref-main@<latest>" already in context.
[INF]: Module "id-ref-main" successfully parsed as implemented.
[INF]: Module "id-ref-extend-main" successfully parsed as imported.
[INF]: Module "id-ref-installed" successfully parsed as implemented.
[INF]: Loading schema "id-ref-extend-main" from sysrepo.
[INF]: Module id-ref-extend-main already present in context.
[INF]: Loading schema "augm_leafref_m1" from sysrepo.
[INF]: Reading module "augm_leafref_m1".
[INF]: Reading module "augm_leafref_m2".
[INF]: Module "augm_leafref_m2" successfully parsed as imported.
[INF]: Resolving "augm_leafref_m1" unresolved schema nodes and their constraints...
[INF]: All "augm_leafref_m1" schema nodes and constraints resolved.
[INF]: Module "augm_leafref_m1" successfully parsed as implemented.
[INF]: Loading schema "augm_leafref_m2" from sysrepo.
[INF]: Module augm_leafref_m2 already present in context.
[INF]: Loading schema "module-a@2016-02-10" from sysrepo.
[INF]: Reading module "module-a".
[INF]: Reading submodule "sub-a-one".
[INF]: Submodule "sub-a-one" successfully parsed.
[INF]: Reading submodule "sub-a-two".
[INF]: Submodule "sub-a-two" successfully parsed.
[INF]: Module "module-a@2016-02-10" successfully parsed as implemented.
[INF]: Loading schema "module-b@2016-02-05" from sysrepo.
[INF]: Reading module "module-b".
[INF]: Reading module "module-a".
[INF]: Reading submodule "sub-a-one".
[INF]: Submodule "sub-a-one" successfully parsed.
[INF]: Reading submodule "sub-a-two".
[INF]: Submodule "sub-a-two" successfully parsed.
[INF]: Module "module-a@2016-02-02" successfully parsed as imported.
[INF]: Module "module-b@2016-02-05" successfully parsed as implemented.
[INF]: Loading schema "module-a@2016-02-02" from sysrepo.
[INF]: Module module-a@2016-02-02 already present in context.
[INF]: Loading schema "ietf-interfaces@2014-05-08" from sysrepo.
[INF]: Reading module "ietf-interfaces".
[INF]: Module "ietf-interfaces@2014-05-08" successfully parsed as implemented.
[INF]: Loading schema "iana-if-type@2014-05-08" from sysrepo.
[INF]: Reading module "iana-if-type".
[INF]: Reading module "ietf-interfaces".
[INF]: Module "ietf-interfaces@2014-05-08" already in context.
[INF]: Module "ietf-interfaces@2014-05-08" successfully parsed as implemented.
[INF]: Module "iana-if-type@2014-05-08" successfully parsed as implemented.
[INF]: Loading schema "ietf-ip@2014-06-16" from sysrepo.
[INF]: Reading module "ietf-ip".
[INF]: Module "ietf-ip@2014-06-16" successfully parsed as implemented.
[INF]: Loading schema "state-module@2016-07-01" from sysrepo.
[INF]: Reading module "state-module".
[INF]: Module "state-module@2016-07-01" successfully parsed as implemented.
[INF]: Loading schema "top-level-mandatory" from sysrepo.
[INF]: Reading module "top-level-mandatory".
[INF]: Module "top-level-mandatory" successfully parsed as implemented.
[INF]: Loading schema "cross-module" from sysrepo.
[INF]: Reading module "cross-module".
[INF]: Resolving "cross-module" unresolved schema nodes and their constraints...
[INF]: All "cross-module" schema nodes and constraints resolved.
[INF]: Module "cross-module" successfully parsed as implemented.
[INF]: Loading schema "turing-machine@2013-12-27" from sysrepo.
[INF]: Reading module "turing-machine".
[INF]: Module "turing-machine@2013-12-27" successfully parsed as implemented.
[INF]: Loading schema "ietf-netconf-notifications@2012-02-06" from sysrepo.
[INF]: Reading module "ietf-netconf-notifications".
[INF]: Reading module "ietf-netconf".
[INF]: Reading module "ietf-netconf-acm".
[INF]: Module "ietf-netconf-acm@2018-02-14" successfully parsed as imported.
[INF]: Module "ietf-netconf@2011-06-01" successfully parsed as imported.
[INF]: Resolving "ietf-netconf-notifications" unresolved schema nodes and their constraints...
[INF]: All "ietf-netconf-notifications" schema nodes and constraints resolved.
[INF]: Module "ietf-netconf-notifications@2012-02-06" successfully parsed as implemented.
[INF]: Loading schema "ietf-netconf@2011-06-01" from sysrepo.
[INF]: Module ietf-netconf@2011-06-01 already present in context.
[INF]: Module "ietf-netconf@2011-06-01" now implemented.
[INF]: Loading schema "ietf-netconf-acm@2018-02-14" from sysrepo.
[INF]: Module ietf-netconf-acm@2018-02-14 already present in context.
[INF]: Loading schema "nc-notifications@2008-07-14" from sysrepo.
[INF]: Reading module "nc-notifications".
[INF]: Reading module "notifications".
[INF]: Module "notifications@2008-07-14" successfully parsed as imported.
[INF]: Module "nc-notifications@2008-07-14" successfully parsed as implemented.
[INF]: Loading schema "notifications@2008-07-14" from sysrepo.
[INF]: Module notifications@2008-07-14 already present in context.
[INF]: Loading schema "servers" from sysrepo.
[INF]: Reading module "servers".
[INF]: Module "servers" successfully parsed as implemented.
[INF]: Loading schema "commit-nacm" from sysrepo.
[INF]: Reading module "commit-nacm".
[INF]: Module "commit-nacm" successfully parsed as implemented.
[INF]: Loading schema "ietf-netconf-with-defaults@2011-06-01" from sysrepo.
[INF]: Reading module "ietf-netconf-with-defaults".
[INF]: Module "ietf-netconf-with-defaults@2011-06-01" successfully parsed as implemented.
[INF]: Loading schema "ietf-netconf-monitoring@2010-10-04" from sysrepo.
[INF]: Reading module "ietf-netconf-monitoring".
[INF]: Module "ietf-netconf-monitoring@2010-10-04" successfully parsed as implemented.
[INF]: Loading schema "ietf-yang-library@2018-01-17" from sysrepo.
[INF]: Module ietf-yang-library@2018-01-17 already present in context.
[INF]: Loading schema "ietf-datastores@2017-08-17" from sysrepo.
[INF]: Module ietf-datastores@2017-08-17 already present in context.
[ERR]: Module "ietf-netconf" feature "writable-running" not enabled in sysrepo.
[ERR]: Server init failed.
[INF]: (cl_sm_cleanup:1797) Client Subscription Manager successfully destroyed.

[1]+  Exit 1                  sudo /usr/local/bin/netopeer2-server -v 2 -d

**Comment by victor5d** [comment]
Using sysrepoctl command I enabled the 'missing features' (they should be built already in sysrepo) in 'ietf-netconf' one after another. At the end, I got the error which I have no idea of fixing:
[ERR]: Module "notifications" not implemented in sysrepo.
[ERR]: Server init failed.
[INF]: (cl_sm_cleanup:1797) Client Subscription Manager successfully destroyed.

**Comment by michalvasko** [comment]
Hi,
please clear the repository and build files again. After that, if you just `make install` first `sysrepo` and then `netopeer2-server`, you will not have to do anything manually, all of the features and models will be installed correctly.

Regards,
Michal

**Comment by victor5d** [comment]
Hi Michal,

Followed your instructions, everything comes back.

Thank you.

Victor

**Comment by michalvasko** [comment]
Hi Victor,
I would have forgotten, please provide the models that are causing `sysrepoctl` to crash, we will fix it.

Regards,
Michal
