### ISSUE TITLE
Why can't I write data directly into running?

### ISSUE THREAD

**Issue by kingsalone** [CESNET/netopeer2#359]
edit.xml:
```xml
    <edit-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"> 
	<target> 
		<candidate/> 
	</target> 
	<default-operation>merge</default-operation> 
	<test-option>set</test-option> 
	<config> 
		<capable-switch  xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="create" xmlns="urn:onf:config:yang"> 
			<id>capable-switch-0</id> 
			<logical-switches> 
				<switch> 
					<id>logic-switch-1</id> 
					<datapath-id>11:11:11:11:11:11:11:11</datapath-id> 
					<enabled>true</enabled> 
					<controllers> 
						<controller> 
							<id>controller-0</id> 
							<role>master</role> 
							<ip-address>192.168.2.1</ip-address> 
							<port>6633</port> 
							<protocol>tcp</protocol> 
						</controller> 
					</controllers> 
				</switch> 
			</logical-switches> 
		</capable-switch> 
	</config> 
</edit-config> 
```
 netopeer2-cli : 
```
    user-rpc --content edit.xml
```

Errors encountered：
```
  ERROR
        type:     application
        tag:      operation-failed
        severity: error
        path:     /of-config-1.2:capable-switch/id
        message:  The node is not enabled in running datastore
```
How do I solve this problem?

**Comment by kingsalone** [comment]
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="55"><edit-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><target><running/></target><default-operation>merge</default-operation><test-option>set</test-option><config><capable-switch xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="create" xmlns="urn:onf:config:yang"><id>capable-switch-0</id><logical-switches><switch><id>logic-switch-1</id><datapath-id>11:11:11:11:11:11:11:11</datapath-id><enabled>true</enabled><controllers><controller><id>controller-0</id><role>master</role><ip-address>192.168.2.1</ip-address><port>6633</port><protocol>tcp</protocol></controller></controllers></switch></logical-switches></capable-switch></config></edit-config></rpc>

**Comment by kingsalone** [comment]
The format of XML seems to be wrong, but I'm all written in accordance with the protocol, so there should be no problem.

**Comment by kingsalone** [comment]
There seems to be something wrong with the XML format I submitted, but I'm all written in accordance with the protocol, so there should be no problem.

**Comment by michalvasko** [comment]
Hi,
it all seems fine and the error should be self-explaining if you read [this](http://www.sysrepo.org/static/doc/html/ds_page.html#rds). To fix this error you can run `examples/application_example <module-name>` with `module-name` being the name of the module with namespace `urn:onf:config:yang`. Why is briefly explained in the referenced doc.

Regards,
Michal
