### ISSUE TITLE
netopeer2-server[1650]: Invalid order of elements 

### ISSUE THREAD

**Issue by dongyangf** [CESNET/netopeer2#360]
Hi, 
Regarding RPC parameters, have sequential checks been added after netopeer2-server version 0.6.x? 
**For example:**
Yang file:
[https://github.com/OpenROADM/OpenROADM_MSA_Public/blob/4.0.0/model/Device/org-openroadm-de-operations.yang](url)

Order xml:
```xml
<restart xmlns="http://org/openroadm/de/operations">
  <resourceType>
    <type>device</type>
  </resourceType>
  <option>warm</option>
</restart> 
```

Unordered xml:
```xml
<restart xmlns="http://org/openroadm/de/operations">
  <option>warm</option>
  <resourceType>
    <type>device</type>
  </resourceType>
</restart>
```

On netopeer2-server 0.5.26 version, Both of the above XML can be executed successfully.
On netopeer2-server 0.6 version, Only order xml can be executed successfully.  Unordered xml executed result:
```xml
<nc:rpc-error xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <nc:error-type>protocol</nc:error-type>
  <nc:error-tag>missing-element</nc:error-tag>
  <nc:error-severity>error</nc:error-severity>
  <nc:error-message xml:lang="en">Invalid order of elements "resourceType" and "option".</nc:error-message>
  <nc:error-info>
    <nc:bad-element>/org-openroadm-de-operations:restart/resourceType</nc:bad-element>
  </nc:error-info>
</nc:rpc-error>
```
Please help me analyze it. Thank you.

Best Regards
-- Dongyang

**Comment by leimgitub** [comment]
I think this is from libyang.
libyang/src/log.c:/* LYE_INORDER */      "Invalid order of elements \"%s\" and \"%s\".",

**Comment by michalvasko** [comment]
Hi,
my guess is that you updated not just *netopeer2-server* but also *libyang* which was not checking this correctly before but it does not matter. It is an error as written [here](https://tools.ietf.org/html/rfc7950#section-7.14.4).

Regards,
Michal

**Comment by leimgitub** [comment]
Thanks. 
Next time I will check this rpc.  I only check netconf' rfc6020 this time.
