### ISSUE TITLE
the data problem of rpc-reply

### ISSUE THREAD

**Issue by kingsalone** [CESNET/netopeer2#361]
rpc data ：
```xml
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <get xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <filter type="subtree">
      <capable-switch xmlns="urn:onf:config:yang">
        <logical-switches>
          <switch/>
        </logical-switches>
      </capable-switch>
    </filter>
  </get>
</rpc>
```
rpc-reply data：
```xml
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"/>
</rpc-reply>
```
Error in controller analysis ：
org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 2; 文档中根元素前面的标记必须格式正确。

Hi，Does data need a namespace here?  Or lack of XML headers（`<?xml version="1.0" encoding="UTF-8"?>`）？

**Comment by michalvasko** [comment]
Hi,
you pasted an error here from a "controller" that I have no idea what is and I am pretty sure its not our software. So, did you use *netopeer2* at all? If so, which end? Other than that I do not see anything wrong with these XMLs and I think they are valid NETCONF messages.

Regards,
Michal

**Comment by kingsalone** [comment]
Thank you for your reply, I also think there is no error in the XML file, but I use netopeer2 and receive rpc-reply in the controller, parse XML with SAXParseException tool, lineNumber: 2; columnNumber: 2 corresponds to the data namespace? I can not locate the fault point. Perhaps it's a problem with parsing tools.

**Comment by michalvasko** [comment]
Well, the reply is valid, but empty, maybe your tools do not expect that?
