### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by wmakuch** [CESNET/netopeer2#363]
Hello Michal!

Netopeer2 and sysrepo are great tools used in my project for communication via netconf.
There are some features I need to use, but there is no support provided.
I would like to open discussion and ask you about advices, code review and opinion about feature I prepared.
The feature is:
"Application should receive information from which netconf client (session-id) specific rpc has been sent."

My questions:
1. Would you like to merge such feature into repository (Netopeer2 and sysrepo)?
2. What is the best way to write feature like this? - I just added field in sysrepo.proto and extended rpc_cb with additional parameter.
3. I cannot dereference struct nc_session* and get id without copy entire class from netconf into Netopeer2. What is best way to avoid it?
In the future I am going to extend this feature: print session-id in notification, get info when rpc has been sent.

Please let me know, if you wish to see my changes.
If yes - in what form should I send it - you prefer patches? or open pull request in Netopeer2 and sysrepo repository?

Best Regards,
Wojciech Makuch

**Comment by michalvasko** [comment]
Hi,
we are glad you are using our NETCONF suite and we generally always welcome patches, best in the form of a pull request.

1. Create a pull request and we will see, probably yes.
2. Seems OK but I would have to see the changes themselves to be sure.
3. Using `nc_session_get_id()`?

Regards,
Michal

**Comment by wmakuch** [comment]
Hello,

Thank you for quick reply!
Soon I will open new pull request.

Best Regards,
Wojciech Makuch
