### ISSUE TITLE
How to construct such get rpc with correct CONSTSTRING filter?

### ISSUE THREAD

**Issue by foxge** [CESNET/Netopeer2#364]
https://github.com/CESNET/Netopeer2/blob/6db56863fcac3fc21c18835576314a75ceea1267/server/operations.c#L2598

create such message:
```
<filter type=\"subtree\">
    const string
</filter>
```
but this is not a correct message.  how can I construct a correct message ?
Thanks.

**Comment by michalvasko** [comment]
Hi,
we do not support attributes without a namespace, so you must use `ietf-netconf:type`.

Regards,
Michal

**Comment by foxge** [comment]
Hi,
lyxml_parse_mem means that the server received a netconf get or get-config request  which filter's content is string or const string but not XML elment.

the question is that i don't what netconf request is satisfied with the string/const-string message?

Thanks you reply.

**Comment by michalvasko** [comment]
Hi,
sorry, I did not notice the invalid content. But exactly are you asking? That is not a valid filter because it does not conform to [subtree filtering](https://tools.ietf.org/html/rfc6241#section-6) so empty should probably be returned.

Regards,
Michal

**Comment by foxge** [comment]
I think I got it, thanks.
