### ISSUE TITLE
The performance between cli and server edit-conf operation is not very good, is there some paremeters i can use let the operation faster?

### ISSUE THREAD

**Issue by foolloow** [CESNET/netopeer2#366]
First sorry for my poor English.
Today i test the result of edit-conf between client and server, the program (client and server) all run in the same linux system, the message is same to the example of "oven" edit-conf message which sysrepo's example gives.
The difference is i send the message 100 or 1000 times. And the interface between netopeer2 and sysrepo just return OK to eliminate the sysrepo's effect to the performance.
The result is a little frustrating, 100 times operations takes almost 8 seconds.
I modified some delay time including ssh and others, but the result is not improved,  so is it a common result of the code or can be improved by modify some parameters?
Look forward to get some feedbacks.

**Comment by michalvasko** [comment]
Hi,
there is not much you can do. Even though your `edit-config` may be small, there is quite a lot of things always happening mainly in *sysrepo*. We are working on improving this situation.

Regards,
Michal

**Comment by foolloow** [comment]
Hi,i modify the op_editconfig function and before it calls any sysrepo library function, it returns OK, i think in this way, sysrepo will not process any request, but the result is the same.
Is there any other operations i missed during the edit-config process and it takes time?

**Comment by michalvasko** [comment]
Hi,
I am sorry, I missed this part in your initial post. So, you are testing the performance of `<edit-config>` of *neotpeer2-server* while it does not communicate with *sysrepo* at all? Then there is no functionality, what purpose is there to test it?

Regards,
Michal

**Comment by foolloow** [comment]
Thanks for the quick reply.
So i need to explain the use of netconf2&netopeer2 in my project. The program has already a database(just like sysrepo), so we may just replace the sysrepo,  before that i test the performance of netconf's communication between client and server.We have the performance of our database, so this test result may be a key reference to the integration result.

**Comment by michalvasko** [comment]
HI,
if you really just changed all `np2srv_sr_*()` calls so that they immediately return, then you should get fairly accurate performance of just the server. If this is what you did and 100 `edit-config`s take 8 seconds then I would also expect much better performance. Did the tool you used for measuring generate any graphs you could share?

Regards,
Michal
