### ISSUE TITLE
use user-rpc, but display "message:  Request could not be completed because the requested operation is not supported by this implementation"

### ISSUE THREAD

**Issue by cloudandzack007** [CESNET/netopeer2#367]
I install a YANG module [xran-software-management]
It contains a rpc
```yang
rpc software-download {
    description
      "Rpc needed to perform software download operation.";
    input {
      leaf remote-file-path {
        type inet:uri;
        mandatory true;
        description
          "URI of the software image including username.
           The following format is possible:
           sftp://<username>@<host>[:<port>]";
      }

      choice credentials {
        description
          "Type of authentication to use for software downloads.";
        case password {
          container password {
            presence "true";
            description
              "password authentication method in use";
            leaf password {
              type string;
              mandatory true;
              description
                "password needed for authentication.";
            }
          }
        }

        case certificate {
          container certificate {
            presence "true";
            description
              "certificate authentication method in use";
          }
        }
      }
    }

    output {
      leaf status {
        type enumeration {
          enum "STARTED" {
            description
              "Operation has been started without error.";
          }
          enum "FAILED" {
            description
              "Operation cannot be started because of error, more detailed information can be found in error-message.";
          }
        }
        mandatory true;
        description
          "Status of the software files download";
      }

      leaf error-message {
        when "../status = 'FAILED'";
        type string;
        description
          "Detailed error Message when the status is failed.";
      }

      leaf notification-timeout {
        type int32;
        units "seconds";
        default "30";
        description
          "Notification timeout is the time NETCONF client shall
           wait for a 'download-event' notification from RU. If there is no
           'download-event' notification received within notification-timeout,
           NETCONF client shall assume the download timeout/failure, and follow necessary steps.";
      }
    }
  }
```
I connect the server and use [user-rpc --content filename.xml] to get response.
The fileanme.xml:
```xml
<software-download xmlns = "urn:xran:software-management:1.0">
        <remote-file-path></remote-file-path>
        <password>
        <password></password>
        </password>
</software-download>
```
But the server display:
```
ERROR
        type:     protocol
        tag:      operation-not-supported
        severity: error
        path:     /xran-software-management:software-download
        message:  Request could not be completed because the requested operation is not supported by this implementation.
```
So how to fix it.
Thanks.

**Comment by michalvasko** [comment]
Hi,
you need to have a handler (subscriber) of this specific RPC for it to be supported. Meaning a client that will call `sr_rpc_subscribe()` on this RPC. Take a look at `sysrepo/examples/rpc_example.c`.

Regards,
Michal

**Comment by cloudandzack007** [comment]
Where is the file [sysrepo/examples/rpc_example.c] ? I can not find it in Netopeer2-master

**Comment by cloudandzack007** [comment]
I find the rpc_example.c and run it.
one terminal ./rpc_example.c
another termianl ./rpc_example.c 122
then I can see Sending RPC and Received RPC.
What is the relationship between user-rpc and these?
When I use user-rpc , it also display [Request could not be completed because the requested operation is not supported by this implementation]

**Comment by qiangzhang0925** [comment]
i use ncclient, and i encounter this problem. how to fix it ?thanks

**Comment by michalvasko** [comment]
Hi,
what is the YANG module you are using? What RPC (XML) did you execute?

Regards,
Michal

**Comment by qiangzhang0925** [comment]
i am using the "ietf-interfaces" module, i use edit_config command in ncclient to send my XML
![QQ截图20200601205428](https://user-images.githubusercontent.com/48346295/83411155-43305e80-a44a-11ea-84b8-338d4b7d7615.png)

**Comment by michalvasko** [comment]
Okay, what *netopeer2* version are you using? Could you run it with `-c MSG` so that the actual received XML can be seen?

Regards,
Michal

**Comment by qiangzhang0925** [comment]
i pull the sysrepo/sysrepo-netopeer2 v0.7.6 images to use netopeer2, how to check its version?

**Comment by michalvasko** [comment]
That is good enough, you are using a really ancient, now obsolete version. But you should still be able to use the command I posted before, I do not know what exactly is the client sending to the server without that output.

Regards,
Michal

**Comment by qiangzhang0925** [comment]
i execute python file in ubuntu bash, the output like this:
![image](https://user-images.githubusercontent.com/48346295/83412496-be930f80-a44c-11ea-8ed9-805f32ab5125.png)

**Comment by michalvasko** [comment]
No, this is the client side, I do not care about that, I need the server side. Unless you provide me the output I mentioned, I am not able to help you.

Regards,
Michal
