### ISSUE TITLE
Change the repository location for Debug build

### ISSUE THREAD

**Issue by dwdrajesh** [CESNET/netopeer2#368]
Hi,

I have installed the Debug build which, after installing, I found out sets the REPOSITORY_LOC to be the 'tests/data' relative to where cmake is run.

Is there any way I can change this directory to /etc/sysrepo (same as for the release build) but without having to reinstall sysrepo. Maybe some config file that I can modify? Couldn't find anything related to that in sysrepocfg. 

Thanks,
Rajesh

**Comment by michalvasko** [comment]
Hi Rajesh,
nope, it is defined during compilation. You can redefine it (`cmake` `REPOSITORY_LOC` variable) and install. If you then move the whole repository contents from the previous path to the new one, all the data will be kept.

Regards,
Michal
