### ISSUE TITLE
start server faile

### ISSUE THREAD

**Issue by cloudandzack007** [CESNET/netopeer2#370]
I build code and make install it.
then run "sudo netopeer2-server -d -v3"

ERROR: (cl_request_process:543) Error by processing of the subscribe request (session id=1452190819): Invalid expression..
ERROR: (sr_subtree_change_subscribe:2617) Error by processing of the request.
ERROR: (cl_request_process:543) Error by processing of the unsubscribe request (session id=1452190819): The item expected to exist is missing.
ERROR: (cl_subscription_close:233) Error by processing of the request.
ERROR: np2srv_sr_subtree_change_subscribe failed (sysrepo: Request contains unknown element).
ERROR: Server init failed.
VERBOSE: (cl_sm_cleanup:1797) Client Subscription Manager successfully destroyed.

So,how to fix it.
Thanks.

**Comment by michalvasko** [comment]
Hi,
little information in this log you provided, but the error is a weird one so my guess is that it is caused by some invalid installation of a library or something similar. Can you post output of *sysrepo* `# make install` and then of *netopeer2-server* `# make install`? Thanks.

Regards,
Michal

**Comment by cloudandzack007** [comment]
I do everything again.
mkdir build, cmake, make, make install
sysrepod -d -l4
ok, now output is all right.
then start another termianl
run netopeer2-server -d -v3

ERROR: Module "ietf-netconf" not implemented in sysrepo.
So, I run "sudo sysrepoctl --install --yang=/home/tao/5g/Netopeer2/modules/ietf-netconf.yang --owner=tao:tao --permissions=777"

netopeer2-server -d -v3 again
ERROR: Module "ietf-netconf" feature "writable-running" not enabled in sysrepo.
So, I run "sysrepoctl --feature-enable=writable-running --module=ietf-netconf"
and many feature error "candidate,rollback-on-error,validate......" and some install error.

Now ,I fix them all. Run netopeer2-server -d -v3 again
But:
ERROR: (sr_set_data_file_permissions:2323) Unable to stat data file for 'ietf-yang-library': No such file or directory.
WARNING: (cl_sm_get_server_socket_filename:1459) Attempt to subscribe to unknown 'ietf-yang-library' module.
ERROR: (cl_sm_get_server_socket_filename:1461) Unable to set socket directory permissions for '/tmp/sysrepo-subscriptions/ietf-yang-library/'.
ERROR: (cl_sm_server_init:1519) Cannot generate server socket path.
ERROR: (cl_subscription_init:293) Cannot initialize Client Subscription Manager.
ERROR: (cl_sm_subscription_cleanup:1891) NULL value detected for subscription argument of cl_sm_subscription_cleanup
ERROR: (sr_dp_get_items_subscribe:3420) Error by initialization of the subscription in the client library.
ERROR: Subscribing for providing "Requested schema model is not known" state data failed ((null)).
ERROR: Server init failed.
VERBOSE: (cl_sm_cleanup:1797) Client Subscription Manager successfully destroyed.

I run "sysrepo # make install"
sysrepo: command not found
I run "sysrepod # make install"
[ERR] (sr_daemon_check_single_instance:2172) Another instance of sysrepo daemon is running, unable to start.
I kill the process
Run "sysrepod # make install" again
nothing happen
Run "netopeer2-server # make install"
nothing happen

So,please help me.Thanks

**Comment by michalvasko** [comment]
Okay, you are doing a lot of redundant commands so please read `INSTALL.md` for *sysrepo* and `README.md` for *netopeer2-server* installation instructions and follow them. Then everything will work for you just fine.

Regards,
Michal
