### ISSUE TITLE
can netopeer2 work without sysrepo?

### ISSUE THREAD

**Issue by foolloow** [CESNET/netopeer2#371]
Hi, 
I installed the sysrepo and netopeer2 and they work fine, but sysrepo is a big database for my device and i test if i use sysrepo to maintain yang module, i can use netopeer2 write/write in my own database  through modifing the edit-conf and get functions.

So, my question is can i use it without sysrepo? 
If i can, how to install the yang module directly into netopeer2-server?
I think i may send hello msg by my self, so the key question may be can server works well without getting these yang modules?

Sysrepo needs many libs, and the device resource is limit,so i may not use it.

Sorry for the description typing by my phone can not have good format.

**Comment by michalvasko** [comment]
Hi,
no, *netopeer2* (*libnetconf2*) needs a separate datastore implementation and we are using *sysrepo* for this purpose. If you do not want to use it, you would have to write your own datastore.

Regards,
Michal

**Comment by foolloow** [comment]
Hi,
So i have a database, but not including yang modules' database just as sysrepoctl stored in sysrepo. After reading the server code, sysrepo add yang modules to server is complex, so is there some simple way to add yang modules' info to server and make just edit-config and get operations works well?

Maybe it's a little wired to use code in this way, but i only need to process get/set operations, not all functions supported is OK.

I test if not adding yang modules to server, the server will return ERR to xml RPC.

**Comment by michalvasko** [comment]
Hi,
yes, there certainly is a simpler way of storing the YANG module database but you would have to write it yourself anyway. I would suggest you wait for the new *sysrepo* that should be released in about half a year and which should have no dependencies and be much smaller/simpler overall.

Regards,
Michal
