### ISSUE TITLE
lyd_node_leaf_list and lyd_node

### ISSUE THREAD

**Issue by cloudandzack007** [CESNET/netopeer2#373]
I want to know
lyd_node.attr->value_str and lyd_node_leaf_list.value_str are  same or not?

**Comment by michalvasko** [comment]
Hi,
no, they are not. `lyd_node.attr` is a pointer to the first attribute defined on a data node. `attr->value_str` is the string value of the particular attribute. `lyd_node_leaf_list.value_str` is a string value of the particular leaf or leaf-list data node.

Regards,
Michal
