### ISSUE TITLE
Cross-compiling sysrepo

### ISSUE THREAD

**Issue by dwdrajesh** [CESNET/netopeer2#374]
Hi,
As per the instructions provided in the INSTALL.md file in the sysrepo github repository, there are a number of required libraries (libyang, google proto buffer, protobuf-c, libev and libredblack). Other than that, if we want to compile for an ARM architecture, we need to provide the REPOSITORY_LOC pointing to /et/sysrepo on the target's rootfs. 
(1) Can I just compile (make only) by providing the /etc/sysrepo to any local directory on my host PC and then copy the sysrepo.h and other header files and sysrepod, sysrepoplugind to /bin or wherever the environment variable on my target is set to? Will this work if I manually copy those files and set my env variable properly?

(2) For the "Required libraries", is there something similar to building sysrepo for a cross-compiling or is it the same as the default option which is x86? 
Thanks.

**Comment by dwdrajesh** [comment]
Hi,
So, I was trying to manually copy the libsysrepo.a, libsysrepo.so* files to my local directory and compile a piece of code that is supposed to run on my target (the compiler for the target is "arm-wrs-linux-gnueabi-g++", the linker is: "arm-wrs-linux-gnueabi-ld").

The compilation happened fine after I pointed the correct sysrepo.h and other header files but the linker gives me an error saying "libsysrepo.a: error adding symbols: File format not recognized: ld returned 1 exit status".
It seems the sysrepo library has to be compiled for this specific target . How can I do that? Thanks

**Comment by jktjkt** [comment]
It seems that you are having difficulties setting up your cross-compiling environment correctly. My suggestion is to use existing tooling which already handles these use cases well. If you're manually copying files around, you *will* have troubles.

There are makefiles/recipes for Buildroot, for example, in [our Buildroot development branch](https://gerrit.cesnet.cz/plugins/gitiles/github/buildroot/buildroot/+log/cesnet/2018-11-09). If you are using a different system, such as Yocto, you will have to adapt a similar technique yourself.

The short answers to your questions are "no". Also understand that there's no env variable, `REPOSITORY_LOC` is a build option which hard-codes the prefix into the resulting binaries. You cannot override it at runtime, and you will have to understand the build process if you want to customize it.

**Comment by mislavn** [comment]
Hi,
I agree with @jktjkt, it's inconvenient to cross compile sysrepo from the ground up because you will need to cross compile libpcre, libyang, libredblack/libavl and sysrepo. There are sysrepo OpenWrt packages and we sometimes cross compile programs for OpenWrt and for that we use the cmake command:

```
$ mkdir build
$ cd build
$ # path to OpenWrt target toolchain
$ export STAGING_DIR=/opt/openwrts/staging_dir/target-arm_xscale_uClibc-0.9.33.2_eabi
$ export COMP=$STAGING_DIR/../toolchain-arm_xscale_gcc-4.8-linaro_uClibc-0.9.33.2_eabi
$ $STAGING_DIR/../host/bin/cmake -DCMAKE_FIND_ROOT_PATH=$STAGING_DIR --DCMAKE_LIBRARY_PATH=$STAGING_DIR -DCMAKE_C_COMPILER=$COMP/bin/arm-openwrt-linux-uclibcgnueabi-gcc -DCMAKE_C_FLAGS="-Wall -std=gnu99" -DCMAKE_BUILD_TYPE=Debug ..
$ make
```

Hope this helps.
