### ISSUE TITLE
Netopeer2 server ssh key issue when connecting from client on the same machine

### ISSUE THREAD

**Issue by dwdrajesh** [CESNET/netopeer2#380]
Hi,

I installed libnetconf2 and netopeer on my local machine and was trying to connect the netopeer2-cli to the server. However, when i run "connect --host localhost --port 830 --login root" on the client cli, I get this error on the netopeer2-server: 
**Setting method: no algorithm for method "server host key algo" (/etc/ssh/ssh_host_rsa_key)

[ERR]: Failed to set hostkey "default" (/etc/ssh/ssh_host_rsa_key).**

Looks like there is a problem with the rsa key. When I installed the netopeer2, I was following the instructions on the Dockerfile at: https://github.com/sysrepo/sysrepo/blob/devel/deploy/docker/sysrepo-netopeer2/Dockerfile. It seems the instructions were creating a id_dsa.pub file while this error seems to be coming from rsa key. 
Is anyone familiar with this issue? I have been trying to figure out for quite some time now without success. Thank you

**Comment by michalvasko** [comment]
Hi,
what *libssh* version are you using? Did you generate the key yourself?

Regards,
Michal

**Comment by dwdrajesh** [comment]
Hi,
yes, i generated the key myself following the instructions in this Docker file: https://github.com/sysrepo/sysrepo/blob/devel/deploy/docker/sysrepo-netopeer2/Dockerfile . It seems to use dsa. For libssh, I seem to be using /usr/lib/x86_64-linux-gnu/libssh.so.4 for both libnetconf and netopeer2-server. 
Should I clear the keys at: /home/netconf/.ssh/authorized_keys as mentioned in the Docker file and try to generate a new key? Thank you

**Comment by michalvasko** [comment]
Hi,
if you look at the error, it mentions only `/etc/ssh/ssh_host_rsa_key` SSH key, no other ones. That you generated your client SSH key is irrelevant now.

You indirectly answered one question I asked, please answer the other, what *libssh* version are you using?

Regards,
Michal

**Comment by dwdrajesh** [comment]
Hi Michal, Thanks for the reply.
I was able to get the version for libssh using dpkg:
dpkg --list | grep libssh ------------ libssh-4:amd64
dpkg -s libssh-4 | grep Version ------------ Version: 0.6.3-4.3ubuntu0.2

I seem to be using 0.6.3-4.3 , is that the supported one? Thanks

**Comment by michalvasko** [comment]
Hi,
I seem to remember that to be the exact version that is causing the error you are experiencing. It is really old anyway, so please update it, best to the latest one (`0.8.6`). That should fix your problem.

Regards,
Michal

**Comment by dwdrajesh** [comment]
Hi Michal,
Unfortunately, Ubuntu xenial 16.04 seems to only support the version 0.6.3-4.3ubuntu0.2 as given here: https://packages.ubuntu.com/xenial/libssh-4

Do you know which version you are using or the latest one so I can install from source? 
Thanks,
Rajesh
