### ISSUE TITLE
Netopeer2-server error : Unable to add new data tree node '/ietf-netconf-notifications:netconf-session-start/source-host

### ISSUE THREAD

**Issue by shishirpandey29** [CESNET/Netopeer2#382]
Hi,
During testing call-home , I configured domain-name of call home client in Netopeer-2 server.
```xml
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <call-home>
    <netconf-client>
      <name>test_ssh_ch_client<name>
      <ssh>
        <endpoints>
          <endpoint>
            <name>test_ssh_ch_endpt<name>
            <address>test.chclient.com<address>  <----domain name
```
           
while establishing call-home , I observed below error in "netopeer2-server"
```
RBOSE: Call Home client "test_ssh_ch_client" session 1 established.
[ERR] (dm_ly_log_cb:1472) libyang error: Invalid value "test.chclient.com" in "source-host" element.
[ERR] (dm_ly_log_cb:1472) libyang error: Failed to create node "source-host" as a child of "netconf-session-start".
[ERR] (dm_sr_val_node_to_ly_datatree:6172) Unable to add new data tree node '/ietf-netconf-notifications:netconf-session-start/source-host': Failed to create node "source-host" as a child of "netconf-session-start"..
[ERR] (dm_validate_procedure:6605) Error by converting sysrepo values/trees to libyang data tree.
[ERR] (rp_event_notif_req_process:3242) Validation of an event notification (/ietf-netconf-notifications:netconf-session-start) message failed.
ERROR: (sr_event_notif_send:3712) Error by processing of the request.
ERROR: np2srv_sr_event_notif_send failed (sysrepo: Validation of the changes failed).
```
As I checked ietf-netconf-notifications(revision : 2016-11-02) yang , /ietf-netconf-notifications:netconf-session-start/source-host type is  inet:ip-address
```yang
 leaf source-host {
      type inet:ip-address;
      description
        "Address of the remote host for the session.";
    }
```
  so source-host accept only ip address. 
I think, that's why it is failing .

if I configure ip-address of call-home-client , then I did not observe any error.
```xml
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <call-home>
    <netconf-client>
      <name>test_ssh_ch_client<name>
      <ssh>
        <endpoints>
          <endpoint>
            <name>test_ssh_ch_endpt<name>
            <address>127.0.0.1<address>  <----domain name 
```
```
VERBOSE: Call Home client "test_ssh_ch_client" session 1 established.
VERBOSE: Generated new event (netconf-session-start).
```
Please check.

**Comment by michalvasko** [comment]
Hi,
so what exactly is the issue? You set a domain name, it did not work. You then checked the type and found out it is not allowed and when you used a correct value it worked as expected.

Regards,
Michal

**Comment by shishirpandey29** [comment]
Hi Michal,

In our project, one application has subscribed to "ietf-netconf-notifications:netconf-session-start" notification.
The issue is that when we set domain-name (ex: test.chclient.com) for call home client , application does not receive "ietf-netconf-notifications:netconf-session-start".

Earlier , we were using ip-address(ex: 127.0.0.1) for call home client so when call home was established , application was receiving "netconf-session-start notification".

Now our current requirement is to use domain-name (ex: test.chclient.com) for call home client .
When we tested with domain-name(ex: test.chclient.com)  for call home client , application was not receiving "netconf-session-start" notification and when we checked Netopeer2-server logs shared earlier, found that it was failing because of wrong type of source-host in  " ietf-netconf-notifications:netconf-session-start".

**Comment by michalvasko** [comment]
Hi,
I am repeating my question, what exactly is the problem? It is **not allowed** to set a domain name instead of an IP address so you cannot do that. Nothing for us to fix.

Regards,
Michal

**Comment by shishirpandey29** [comment]
Hi Michal,

It is valid to configure domain-name for netconf-server/ call-home/netconf-client/ssh/endpoints/endpoint/address.
When Netopeer2 generates netconf-session-start notification, instead of filling the resolved ip-address corresponding to above domain-name, it blindly copies the domain-name to netconf-session-start/source-host. This is wrong because the source-host is of type inet:ip-address.

**Comment by michalvasko** [comment]
Hi,
okay, sorry, I did not understand the connection before. If you update *libnetconf2*, it should work.

Regards,
Michal
