### ISSUE TITLE
Netopeer2 server rejects client connection

### ISSUE THREAD

**Issue by dwdrajesh** [CESNET/Netopeer2#383]
Hi,
I am unable to connect to the netopeer2-server from the cli using:
"connect --host localhost --port 830 --login <username>"
> connect --host localhost --login ezdawra

(1) netopeer2-cli screen output:
Interactive SSH Authentication
Type your password:
Password: 
ezdawra@localhost password: 
nc ERROR: Unable to authenticate to the remote server (all attempts via supported authentication methods failed).
cmd_connect: Connecting to the localhost:830 as user "ezdawra" failed.

(2q) The server rejects saying: 
[INF]: Received an SSH message "request-auth" of subtype "interactive".
[INF]: User "ezdawra" is not allowed to authenticate using a password.
[INF]: Failed user "ezdawra" authentication attempt (#1).
[INF]: Received an SSH message "request-auth" of subtype "password".
[INF]: User "ezdawra" is not allowed to authenticate using a password.
[INF]: Failed user "ezdawra" authentication attempt (#2).
[2019/01/21 09:45:13.615312, 1] ssh_packet_disconnect_callback:  Received SSH_MSG_DISCONNECT: 11:Bye Bye
[ERR]: Communication SSH socket unexpectedly closed.

I see that there was something like this mentioned in another issue at: https://github.com/CESNET/Netopeer2/issues/284 @michalvasko , @rajenderk18, @swathins079, but that issue says using no password. I tried that but it doesn't work.

Thanks,
Rajesh

**Comment by michalvasko** [comment]
Hi,
I believe the answer is in that issue, in my [post](https://github.com/CESNET/Netopeer2/issues/284#issuecomment-398290665).

Regards,
Michal

**Comment by dwdrajesh** [comment]
Hi Michal, it rejects the connection even without the password (just pressing enter on password prompt). I tried both with root and my current username but it didn't work.

**Comment by michalvasko** [comment]
Hi,
that would all make sense if neither of those users are allowed to authenticate using a password in your user configuration. I am really not sure what more to add except for repeating what I wrote in the post I referenced. Did you check your `/etc/password` or more likely `/etc/shadow`?

Regards,
Michal

**Comment by dwdrajesh** [comment]
Hi Michal, thanks the connection seems to be working now after I changed my password using the command "passwd" . 
However, I am still getting issue with the netconf. 

"connect --host localhost --login netconf" produces the following on the netopeer2-cli screen: 
Interactive SSH Authentication
Type your password:
Password: 
ly ERROR: Unable to use search directory "/usr/local/share/libnetconf2" (No such file or directory)
ly ERROR: Opening file "/usr/local/share/libnetconf2/ietf-netconf.yin" failed (No such file or directory).
nc ERROR: Loading base NETCONF schema failed.

Have you encountered similar errors before ? Thank you

**Comment by dwdrajesh** [comment]
Hi Michal, thank you very much for the help. Sorry to bother you with these issues.
I was able to connect to netopeer2-server after I changed my password using the command 'passwd'. 
However, I had a Debug version of sysrepo and the netopeer2-server was looking at /usr/local/share/libnetconf2 while my schemas were at /home/.....
So, I did a new sysrepo install using the argument 'Relesae'. All went well, I did a new install of keystored, netopeer2-server and netopeer2-cli and generated a new ssh key also and replaced the existing on at /home/${USER}/.ssh.
However, now it is giving another error as below in the netopeer2-cli: 

> connect --host localhost  --port 830 --login netconf

nc ERROR: Remote host key changed, the connection will be terminated!
nc ERROR: Checking the host key failed.
cmd_connect: Connecting to the localhost:830 as user "netconf" failed

The 'netconf' is my username which was working until I did a new install of sysrepod and netopeer2-server, cli and keystored. I already have created a new ssh key , do you know what might be causing this issue? 

The netopeer2-server gives the below error:
[2019/01/21 12:43:23.169421, 2] ssh_pki_import_privkey_base64:  Trying to decode privkey passphrase=false
[2019/01/21 12:43:23.170541, 1] ssh_server_connection_callback:  SSH client banner: SSH-2.0-libssh_0.8.90
[2019/01/21 12:43:23.170556, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-libssh_0.8.90
[2019/01/21 12:43:23.171677, 2] ssh_kex_select_methods:  Negotiated curve25519-sha256,ssh-rsa,aes256-gcm@openssh.com,aes256-gcm@openssh.com,hmac-sha2-256,hmac-sha2-256,none,none,,
[2019/01/21 12:43:23.250746, 2] ssh_server_curve25519_init:  SSH_MSG_KEX_ECDH_REPLY sent
[2019/01/21 12:43:23.251159, 2] ssh_init_rekey_state:  Set rekey after 4294967296 blocks
[2019/01/21 12:43:23.255367, 2] ssh_init_rekey_state:  Set rekey after 4294967296 blocks
[2019/01/21 12:43:23.255502, 2] ssh_server_curve25519_init:  SSH_MSG_NEWKEYS sent
[2019/01/21 12:43:23.265713, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
[2019/01/21 12:43:23.266541, 1] ssh_packet_disconnect_callback:  Received SSH_MSG_DISCONNECT: 11:Bye Bye
[ERR]: Communication SSH socket unexpectedly closed.

Thank you

**Comment by michalvasko** [comment]
Hi,
this is expected because like you said, you generated a new SSH key. You can fix this by removing the old one from *known hosts*. This is possible directly using `netopeer2-cli` with the command `knownhosts`. It will display all your stored known host keys. You need to look for one with `hostname` `localhost`. You should delete it with `knownhosts --del <ID>`. Then you will be able to connect.

Regards,
Michal

**Comment by dwdrajesh** [comment]
Thanks Michal, its working now :)

**Comment by alecanty** [comment]
How can ı edit the password of the netopeer2 server.

**Comment by michalvasko** [comment]
Not sure why you are replying to this closed unrelated issue but the password for each user is read from the system currently, so you would have to change the system password of the user.
