### ISSUE TITLE
Get errors when Enable call home

### ISSUE THREAD

**Issue by qynum123** [CESNET/Netopeer2#385]
Hi, I got the following errors when enabling Netopeer2 ssh call home. Did anybody meet this before or know how to fix this? Thanks in advance!
> edit-config --target candidate --config
with the following:
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <call-home>
    <netconf-client>
      <name>main</name>
      <ssh>
        <endpoints>
          <endpoint>
            <name>endpt_name</name>
            <address>127.0.0.1</address>
          </endpoint>
        </endpoints>
        <host-keys>
          <host-key>
            <name>rsa_key</name>
            <public-key>ssh_host_rsa_key</public-key>
          </host-key>
        </host-keys>
      </ssh>
      <connection-type>
        <persistent/>
      </connection-type>
    </netconf-client>
  </call-home>
</netconf-server>

ERROR
	type:     application
	tag:      operation-failed
	severity: error
	path:     /ietf-netconf-server:netconf-server/call-home/netconf-client[name='main']/ssh/host-keys/host-key[name='rsa_key']/public-key
	message:  Leafref "/ietf-keystore:keystore/ietf-keystore:private-keys/ietf-keystore:private-key/ietf-keystore:name" of value "ssh_host_rsa_key" points to a non-existing leaf.

I have run the following commands:
sysrepoctl --install --yang=/home/steven/5g/Netopeer2/modules/ietf-netconf-server.yang --owner=root:root --permissions=777
sysrepoctl --install --yang=/home/steven/5g/Netopeer2/modules/ietf-keystore.yang --owner=root:root --permissions=777

# sysrepoctl -l
Module Name                | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
example-module             |            | Installed   | yugbai:yugbai       | 666         |                               |
test-module                |            | Installed   | yugbai:yugbai       | 666         |                               |
referenced-data            |            | Installed   | yugbai:yugbai       | 666         |                               |
small-module               |            | Installed   | yugbai:yugbai       | 666         |                               |
info-module                |            | Installed   |                     |             |                               |
id-ref-aug                 |            | Installed   |                     |             |                               |
id-ref-base                |            | Implemented | yugbai:yugbai       | 666         |                               |
id-def-base                |            | Imported    |                     |             |                               |
id-ref-hello               |            | Installed   | yugbai:yugbai       | 666         |                               |
id-ref-hello-cont          |            | Imported    |                     |             |                               |
id-def-extended            |            | Installed   |                     |             |                               |
id-ref-main                |            | Installed   | yugbai:yugbai       | 666         |                               |
id-ref-imported            |            | Imported    |                     |             |                               |
id-ref-installed           |            | Installed   |                     |             |                               |
id-ref-extend-main         |            | Imported    |                     |             |                               |
augm_leafref_m1            |            | Installed   | yugbai:yugbai       | 666         |                               |
augm_leafref_m2            |            | Implemented | yugbai:yugbai       | 666         |                               |
module-a                   | 2016-02-10 | Installed   | yugbai:yugbai       | 666         |  sub-a-one sub-a-two          |
module-b                   | 2016-02-05 | Installed   | yugbai:yugbai       | 666         |                               |
module-a                   | 2016-02-02 | Imported    |                     |             |  sub-a-one sub-a-two          |
ietf-interfaces            | 2014-05-08 | Installed   | yugbai:yugbai       | 666         |                               |
iana-if-type               | 2014-05-08 | Installed   |                     |             |                               |
ietf-ip                    | 2014-06-16 | Installed   |                     |             |                               |
state-module               | 2016-07-01 | Installed   | yugbai:yugbai       | 666         |                               |
top-level-mandatory        |            | Installed   | yugbai:yugbai       | 666         |                               |
cross-module               |            | Installed   | yugbai:yugbai       | 666         |                               |
turing-machine             | 2013-12-27 | Installed   | yugbai:yugbai       | 666         |                               |
ietf-netconf-notifications | 2012-02-06 | Installed   | yugbai:yugbai       | 666         |                               |
ietf-netconf               | 2011-06-01 | Installed   | root:root           | 666         |                               | writable-running candidate rollback-on-error validate startup xpath url
ietf-netconf-acm           | 2018-02-14 | Imported    |                     |             |                               |
nc-notifications           | 2008-07-14 | Installed   | yugbai:yugbai       | 666         |                               |
notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
servers                    |            | Installed   | yugbai:yugbai       | 666         |                               |
commit-nacm                |            | Installed   | yugbai:yugbai       | 666         |                               |
swig-test-cpp-changes      | 2017-03-09 | Installed   | yugbai:yugbai       | 666         |                               |
swig-test-cpp-operations   | 2017-03-09 | Installed   | yugbai:yugbai       | 666         |                               |
ietf-netconf-with-defaults | 2011-06-01 | Installed   |                     |             |                               |
ietf-netconf-monitoring    | 2010-10-04 | Installed   | root:root           | 666         |                               |
ietf-yang-library          | 2018-01-17 | Installed   | root:root           | 666         |                               |
ietf-datastores            | 2017-08-17 | Imported    |                     |             |                               |
ietf-netconf-server        | 2016-11-02 | Installed   | root:root           | 777         |                               | call-home ssh-call-home
ietf-x509-cert-to-name     | 2014-12-10 | Imported    |                     |             |                               |
ietf-ssh-server            | 2016-11-02 | Imported    |                     |             |                               |
ietf-keystore              | 2016-10-31 | Installed   | root:root           | 777         |                               |
ietf-tls-server            | 2016-11-02 | Imported    |                     |             |                               |

**Comment by qynum123** [comment]
Hi Machal,
Thanks for your help, I have clean and reinstalled libyang, libnetconf2, sysrepo, netopeer2.  When I send rpc by netopeer2-client to enable netopeer2 to SSH connection. It seems which is not work.  as follows:
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <call-home>
    <netconf-client>
      <name>main</name>
      <ssh>
        <endpoints>
          <endpoint>
            <name>endpt_name</name>
            <address>127.0.0.1</address>
          </endpoint>
        </endpoints>
        <host-keys>
          <host-key>
            <name>rsa_key</name>
            <public-key>ssh_host_rsa_key</public-key>
          </host-key>
        </host-keys>
      </ssh>
      <connection-type>
        <persistent/>
      </connection-type>
    </netconf-client>
  </call-home>
</netconf-server>

after send this,  netopeer2-client  return OK. and netopeer2-server show the following:
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: _****There is no leafref "/ietf-keystore:keystore/ietf-keystore:private-keys/ietf-keystore:private-key/ietf-keystore:name" with the value "ssh_host_rsa_key", but it is not required.**_**
[INF]: All data nodes and constraints resolved.
[INF]: Session 1: thread 3 event new RPC.

Did I missed some things? Thanks.

**Comment by michalvasko** [comment]
Hi,
why do you think it is not working? If only based on this one message, it is fine. All it says is that the server is not able to perform validation of that leaf because it does not have all the data, but *sysrepo* has already validated it at that point. If you really followed the instructions and did not forget to run `sysrepo-plugind`, then it should work.

Regards,
Michal

**Comment by qynum123** [comment]
I have already started the sysrepo-plugind.
Because I got the timeout for listen with netopeer2-cli, as follows:
> listen
Waiting 60s for an SSH Call Home connection on port 4334...
cmd_listen: Receiving SSH Call Home on port 4334 as user "root" timeout elapsed.

**Comment by michalvasko** [comment]
Can you please provide the output of `# sysrepocfg -d startup -f xml ietf-netconf-server -x`? Thanks.

Regards,
Michal

**Comment by qynum123** [comment]
As follows:
[root@hadoop02 ~]# sysrepocfg -d startup -f xml ietf-netconf-server -x
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <listen>
    <endpoint>
      <name>all-interfaces</name>
      <ssh>
        <address>0.0.0.0</address>
        <port>830</port>
        <host-keys>
          <host-key>
            <name>imported SSH key</name>
            <public-key>ssh_host_rsa_key</public-key>
          </host-key>
        </host-keys>
      </ssh>
    </endpoint>
  </listen>
</netconf-server>
[root@hadoop02 ~]#

**Comment by michalvasko** [comment]
Hi,
you have not configured Call Home, that is why it is not working. Look at `netopeer2/server/configuration/README.md` section `Call Home` to learn how to set it up.

For proper XML pasting, look at your post now after I edited it.

Regards,
Michal

**Comment by qynum123** [comment]
Thanks! 
After I run the following command:
sysrepocfg --import=ssh_callhome.xml --format=xml --datastore=startup ietf-netconf-server
and sysrepocfg -d startup -f xml ietf-netconf-server -x
```xml
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <call-home>
    <netconf-client>
      <name>test_ssh_ch_client</name>
      <ssh>
        <endpoints>
          <endpoint>
            <name>test_ssh_ch_endpt</name>
            <address>127.0.0.1</address>
            <port>4334</port>
          </endpoint>
        </endpoints>
        <host-keys>
          <host-key>
            <name>test_ssh_callhome_key</name>
            <public-key>ssh_host_rsa_key</public-key>
          </host-key>
        </host-keys>
      </ssh>
      <connection-type>
        <persistent/>
      </connection-type>
    </netconf-client>
  </call-home>
</netconf-server>
```

**Comment by michalvasko** [comment]
Hi,
it seems you still have not followed the instructions I mentioned the very first time. So, please, do everything I said in my [first post](https://github.com/CESNET/Netopeer2/issues/385#issuecomment-456338941) and then import the Call Home configuration.

Regards,
Michal

**Comment by qynum123** [comment]
Hi,
I really followed the README and instruction, the only problem I met is I got error when cmake the keystore:
if (PKG_CONFIG_FOUND)
    # generate and install pkg-config file
    configure_file("keystored.pc.in" "keystored.pc" @ONLY)
    install(FILES "${CMAKE_CURRENT_BINARY_DIR}/keystored.pc" DESTINATION "${CMAKE_INSTALL_LIBDIR}/pkgconfig")
    execute_process(COMMAND ${PKG_CONFIG_EXECUTABLE} "--variable=pc_path" "pkg-config" RESULT_VARIABLE RET OUTPUT_VARIABLE OUT)
    if (RET)
    {
         ....
    }
I dont' know why execute_process can't get the path, so I use cmake -D to specified SR_PLUGINS_DIR and then compile and install the libkeystored successfully.
According to above the message, I guess it is related the KEYSTORED_KEYS_DIR, so I cmake Netopeer2-server by specified KEYSTORED_KEYS_DIR(cmake -DKEYSTORED_KEYS_DIR=/usr/local/etc/keystored/keys ..), after make and install Netopeer2-server again, SSH call home successfully now!

So my question now is why the KEYSTORED_KEYS_DIR/SR_PLUG_DIR can't be got  successfully(pkg-config version is too low or ?), could you please give me some hints about this? Thanks.

**Comment by qynum123** [comment]
Hi,
I'm installing the Netopeer2 on CenOS, it seems this issue is related to OS,  pkgconfig installed dir is: /usr/lib64/pkgconfig:/usr/share/pkgconfig, but the libyang.pc, libnetconf2.pc, libsysrepo.pc are installed in /usr/local/lib64/pkgconfig/, should I do some setting before cmake, make and install these libs?

**Comment by michalvasko** [comment]
Hi,
then you have at least 3 options I can think of.

Firstly, you can leave it as it is and pay **really good** attention to the messages displayed by `cmake` and `make install`. You will have to manually specify all the paths for all the libraries to be found but if you do, you will be able to install everything and make it working.

Next, somehow simpler should be to specify just `-DPKG_CONFIG_PATH=/usr/local/lib64/pkgconfig` for `cmake`. Then I think it may be all that is needed but there still may be some problems, I am not certain.

Finally, you could manually change the prefix for installation of all the libraries to `/usr` and then `pkg-config` should be able to find all the package information on its own.

Regards,
Michal
