### ISSUE TITLE
is it better use ly_errmsg than np2log_lasterr when we validate the config data failed in op_validate.c?

### ISSUE THREAD

**Issue by ZhaoGuangYue1986** [CESNET/Netopeer2#387]
is it better use ly_errmsg than np2log_lasterr when we validate the config data failed in op_validate.c?
as if use np2log_lasterr the msg show to user may be contains words like: "libyang error"

```C
        case LYD_ANYDATA_LYBD:
            EINT;
            e = nc_err(NC_ERR_OP_FAILED, NC_ERR_TYPE_APP);
            nc_err_set_msg(e, np2log_lasterr(np2srv.ly_ctx), "en"); ///is it better use ly_errmsg in this place
            ereply = nc_server_reply_err(e);
            goto finish;
        }
```

**Comment by michalvasko** [comment]
Hi,
so is that such a problem? It differentiates the messages generated by *libyang* from those generated directly by *libnetconf2*. It should not matter and if nothing else, it can provide more information in case there is something wrong, which library to look at for the problem.

Regards,
Michal

**Comment by ZhaoGuangYue1986** [comment]
It is not a problem, just cause user confused as the errMsg has the words "libyang error".
Of cause ,if we filter this words before we set np2err->msg is much better, but this may change  libnetconf2,sysrepo.

By the way,if the code entered into this branch, some libnetconf2 problems cat be caused?
