### ISSUE TITLE
Opendaylight netopeer2-server communication failed

### ISSUE THREAD

**Issue by mashemat** [CESNET/Netopeer2#388]
Hello all, 

I am going to configure an interface through opendaylight and netopeer2-server.
This is my xml body:
```xml
<input xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<target>
<running/>
</target>
<config>
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
<interface>
    <name>host-vpp1out</name>
    <description>Ethernet</description>
    <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
    <ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip">
    <enabled>true</enabled>
      <address>
        <ip>172.16.137.165</ip>
        <prefix-length>24</prefix-length>
      </address>
    </ipv4>
  </interface>
</interfaces>
</config>
</input>
```

When I send by restapi the netopeer2-server says 
```
[ERR]: Unknown element "interfaces". (/)
```

Any help is very welcomed.
Thanks,

**Comment by michalvasko** [comment]
Hi,
I know nothing about OpenDaylight so I can only help you with *netopeer2-server* and *sysrepo*. Anyway, do you have `ietf-interfaces` installed? What is the output of `sysrepoctl -l`?

Regards,
Michal

**Comment by mashemat** [comment]
Actually, the output off sysrepo seems everything is good. The only thing that I receive from netopeer2-server which is a bit suspicious is:
Sysrepo does not have the "ietf-netconf-server" module or keystored keys dir unknown, using default NETCONF server options.

So, in sysrepo I don't have the ietf-netconf-server. It could be a problem. I try to install it but later I receive an error 👍 
 Error by processing of the subscribe request (session id=1488598074): Invalid expression..

**Comment by mashemat** [comment]
Here it is my output of the sysrepo:

[DBG] (sr_log_stderr:141) Setting log level for stderr logs to 4.
[DBG] (cm_init:1904) Connection Manager init started.
[DBG] (sr_cbuff_init:457) Initiating circular buffer for 10 elements.
[DBG] (sm_init:287) Session Manager initialized successfully, ctx=0x5571d0032480.
[DBG] (cm_server_init:151) Initializing sysrepo server at socket=/tmp/sysrepod.sock
[DBG] (rp_init:3939) Request Processor init started.
[DBG] (sr_cbuff_init:457) Initiating circular buffer for 10 elements.
[DBG] (sr_cbuff_enqueue:516) Circular buffer enqueue to position=0, current count=1.
[DBG] (np_setup_notif_store_cleanup_timer:726) Notification store cleanup timer set up for 600 seconds.
[DBG] (np_init:809) Notification Processor initialized successfully.
[INF] (dm_init:2270) Initializing Data Manager, schema_search_dir=/home/mhemmatp/sysrepo/build/repository/yang/, data_search_dir=/home/mhemmatp/sysrepo/build/repository/data/
[DBG] (rp_worker_thread_execute:3748) Starting worker thread id=140693925447424.
[DBG] (rp_worker_thread_execute:3810) Thread id=140693925447424 will wait.
[DBG] (cm_init:1963) Connection Manager initialized successfully.
[DBG] (rp_worker_thread_execute:3748) Starting worker thread id=140693900269312.
[DBG] (rp_worker_thread_execute:3810) Thread id=140693900269312 will wait.
[DBG] (rp_worker_thread_execute:3748) Starting worker thread id=140693917054720.
[DBG] (rp_worker_thread_execute:3810) Thread id=140693917054720 will wait.
[DBG] (rp_worker_thread_execute:3748) Starting worker thread id=140693908662016.
[DBG] (rp_worker_thread_execute:3810) Thread id=140693908662016 will wait.
[INF] (main:133) Sysrepo daemon initialized successfully.
[DBG] (cm_event_loop:1872) Starting CM event loop.
[DBG] (cm_msg_enqueue_cb:1791) New message enqueued into CM message queue.
[DBG] (sr_cbuff_dequeue:532) Circular buffer dequeue, new buffer head=1, count=0.
[DBG] (cm_delayed_msg_process:323) Scheduling a delayed request for 600.000000 seconds.

**Comment by jktjkt** [comment]
The information that was asked was output of `sysrepoctl -l`.

**Comment by mashemat** [comment]
This is the updated one:

example-module             |            | Installed   | mhemmatp:mhemmatp   | 666         |                               |
test-module                |            | Installed   | mhemmatp:mhemmatp   | 666         |                               |
referenced-data            |            | Installed   | mhemmatp:mhemmatp   | 666         |                               |
small-module               |            | Installed   | mhemmatp:mhemmatp   | 666         |                               |
info-module                |            | Installed   |                     |             |                               |
id-ref-aug                 |            | Installed   |                     |             |                               |
id-ref-base                |            | Implemented | mhemmatp:mhemmatp   | 666         |                               |
id-def-base                |            | Imported    |                     |             |                               |
id-ref-hello               |            | Installed   | mhemmatp:mhemmatp   | 666         |                               |
id-ref-hello-cont          |            | Imported    |                     |             |                               |
id-def-extended            |            | Installed   |                     |             |                               |
id-ref-main                |            | Installed   | mhemmatp:mhemmatp   | 666         |                               |
id-ref-imported            |            | Imported    |                     |             |                               |
id-ref-installed           |            | Installed   |                     |             |                               |
id-ref-extend-main         |            | Imported    |                     |             |                               |
augm_leafref_m1            |            | Installed   | mhemmatp:mhemmatp   | 666         |                               |
augm_leafref_m2            |            | Implemented | mhemmatp:mhemmatp   | 666         |                               |
module-a                   | 2016-02-10 | Installed   | mhemmatp:mhemmatp   | 666         |  sub-a-one sub-a-two          |
module-b                   | 2016-02-05 | Installed   | mhemmatp:mhemmatp   | 666         |                               |
module-a                   | 2016-02-02 | Imported    |                     |             |  sub-a-one sub-a-two          |
ietf-interfaces            | 2014-05-08 | Installed   | mhemmatp:mhemmatp   | 666         |                               |
iana-if-type               | 2014-05-08 | Installed   |                     |             |                               |
ietf-ip                    | 2014-06-16 | Installed   |                     |             |                               |
state-module               | 2016-07-01 | Installed   | mhemmatp:mhemmatp   | 666         |                               |
top-level-mandatory        |            | Installed   | mhemmatp:mhemmatp   | 666         |                               |
cross-module               |            | Installed   | mhemmatp:mhemmatp   | 666         |                               |
turing-machine             | 2013-12-27 | Installed   | mhemmatp:mhemmatp   | 666         |                               |
ietf-netconf-notifications | 2012-02-06 | Installed   | mhemmatp:mhemmatp   | 666         |                               |
ietf-netconf               | 2011-06-01 | Installed   | root:root           | 666         |                               | writable-running candidate rollback-on-error validate startup xpath url
ietf-netconf-acm           | 2018-02-14 | Imported    |                     |             |                               |
nc-notifications           | 2008-07-14 | Installed   | mhemmatp:mhemmatp   | 666         |                               |
notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
servers                    |            | Installed   | mhemmatp:mhemmatp   | 666         |                               |
commit-nacm                |            | Installed   | mhemmatp:mhemmatp   | 666         |                               |
swig-test-cpp-changes      | 2017-03-09 | Installed   | mhemmatp:mhemmatp   | 666         |                               |
swig-test-cpp-operations   | 2017-03-09 | Installed   | mhemmatp:mhemmatp   | 666         |                               |
ietf-netconf-with-defaults | 2011-06-01 | Installed   |                     |             |                               |
ietf-netconf-monitoring    | 2010-10-04 | Installed   | root:root           | 666         |                               |
ietf-yang-library          | 2018-01-17 | Installed   | root:root           | 666         |                               |
ietf-datastores            | 2017-08-17 | Imported    |                     |             |                               |
interface                  | 2019-01-21 | Installed   | mhemmatp:mhemmatp   | 666         |                               |
ietf-yang-types            | 2013-07-15 | Installed   |                     |             |                               |
ietf-netconf-server        | 2016-11-02 | Installed   | root:root           | 666         |                               |
ietf-x509-cert-to-name     | 2014-12-10 | Imported    |                     |             |                               |
ietf-ssh-server            | 2016-11-02 | Imported    |                     |             |                               |
ietf-keystore              | 2016-10-31 | Implemented | root:root           | 666         |                               |
ietf-tls-server            | 2016-11-02 | Imported    |                     |             |                               |
iana-crypt-hash            | 2014-08-06 | Imported    |                     |             |                               |
ietf-system                | 2014-08-06 | Installed   | root:root           | 666         |                               |

**Comment by michalvasko** [comment]
Hi,
the output seems fine to me. Can you start *netopeer2-server* with `-c MSG`? Then provide its output, it should print the exact message it receives from the client and I want to make sure it is correct.

Regards,
Michal

**Comment by mashemat** [comment]
with -c MSG I don't receive any output but the following is the output of the -d -v 4

[ERR]: (cl_request_process:543) Error by processing of the subscribe request (session id=1978632029): Invalid expression..
[ERR]: (sr_subtree_change_subscribe:2617) Error by processing of the request.
[ERR]: (cl_request_process:543) Error by processing of the unsubscribe request (session id=1978632029): The item expected to exist is missing.
[ERR]: (cl_subscription_close:233) Error by processing of the request.
[ERR]: np2srv_sr_subtree_change_subscribe failed (sysrepo: Request contains unknown element).
[ERR]: Server init failed.


Regards,

**Comment by michalvasko** [comment]
Hi,
then you are most likely using some ancient `netopeer2-server`, what is the output of `netopeer2-server -V`?

Regards,
Michal

**Comment by mashemat** [comment]
This is the output. 
netopeer2-server 0.7.3

Actually I cloned it from 
https://github.com/CESNET/Netopeer2

what is the latest version? Is mine obsolete.

**Comment by michalvasko** [comment]
Hi,
right, that is good enough but if you do not see any output you have then compiled it as `Release`. If you recompile it with target build `Debug` (the default), the parameter should work and I should be able to determine whether the server is at fault or the client.

Regards,
Michal

**Comment by mashemat** [comment]
I don't have a debug option here it is the output of make help:
        @echo "The following are some of the valid targets for this Makefile:"
        @echo "... all (the default if no target is provided)"
        @echo "... clean"
        @echo "... depend"
        @echo "... install/strip"
        @echo "... install"
        @echo "... rebuild_cache"
        @echo "... netopeer2-server"
        @echo "... integration-test"
        @echo "... list_install_components"
        @echo "... serverobj"
        @echo "... edit_cache"
        @echo "... install-scripts-ide"
        @echo "... install/local"
        @echo "... cleancache"
        @echo "... test"
        @echo "... test_edit_get_config"
        @echo "... test_generic"
        @echo "... test_copy_config"
        @echo "... test_get"
        @echo "... testobj"
        @echo "... test_close_session"
        @echo "... test_validate_config"
        @echo "... test_un_lock"
        @echo "... test_notif"
        @echo "... test_kill"
        @echo "... test_delete_config"

Regards,

**Comment by mashemat** [comment]
This is the output of my netopeer2-server:

[WRN]: Identity found, but in a non-implemented module "ietf-x509-cert-to-name".
[WRN]: Failed to resolve identityref "ietf-x509-cert-to-name:specified". (/ietf-netconf-server:map-type)
[WRN]: Previous warning generated by XPath subexpression[3] "map-type = 'ietf-x509-cert-to-name:specified'".
[WRN]: Identity found, but in a non-implemented module "ietf-x509-cert-to-name".
[WRN]: Failed to resolve identityref "ietf-x509-cert-to-name:specified". (/ietf-netconf-server:map-type)
[WRN]: Previous warning generated by XPath subexpression[3] "map-type = 'ietf-x509-cert-to-name:specified'".
[ERR]: np2srv_sr_subtree_change_subscribe failed (sysrepo: Request contains unknown element).
[ERR]: Server init failed.

Regsrds,

**Comment by michalvasko** [comment]
Okay, I am a bit confused now about what exactly are you doing since you had to change the build target to not have debug messages enabled but at the same time it seems you do not know what I am talking about. Regarding these errors, you should run `# make uninstall_with_repo` target of *sysrepo* so that you can properly reinstall all the software.

So, once you did the uninstallation, reinstall *sysrepo* (`cmake ..`, `make`, and `# make install`) and then *netopeer2-server* (`cmake ..`, `make`, and `# make install` again). Then you will not have to manually install any modules or anything, it will be all set up automatically. After that you should also be able to run `# netopeer2-server -d -c MSG` and see the raw message received.

Regards,
Michal

**Comment by mashemat** [comment]
I installed all my packages from scratch. Netopeer2-server installed successfully but I don't have the ietf-netconf yang modules.

Regards,

**Comment by mashemat** [comment]
I install netopeer2 from here:
https://github.com/CESNET/Netopeer2

Here it is the output of my **netopeer2-server -c MSG**

[INF]: Session 1: thread 1 event new RPC.
[DBG]: Session 1: received message:
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<rpc message-id="m-12" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<edit-config>
<target>
<running/>
</target>
<config>
<interfaces>
  <interface>
    <name>host-vpp1out</name> 
    <description>Ethernet</description>
    <type>ianaift:ethernetCsmacd</type>
    <ipv4>
      <enabled>true</enabled>
      <mtu>1514</mtu>
      <address>
        <ip>10.80.17.54</ip>
        <prefix-length>24</prefix-length>
      </address>
    </ipv4>
    <enabled>true</enabled>
  </interface>
</interfaces>
</config>
</edit-config>
</rpc>


[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[ERR]: Unknown element "interfaces". (/)
[DBG]: Session 1: sending message:

#380


[DBG]: Session 1: sending message:
<rpc-reply message-id="m-12" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><rpc-error><error-type>application</error-type><error-tag>operation-not-supported</error-tag><error-severity>error</error-severity><error-message xml:lang="en">Request could not be completed because the requested operation is not supported by this implementation.</error-message></rpc-error></rpc-reply>

Kind Regards,

**Comment by michalvasko** [comment]
Hi,
okay, so you did not install it from a package after all. No matter, this is exactly the output I needed from you and from that I can say that *netopeer2-server* correctly replies with an error, this RPC is missing both `ietf-interfaces` and `iana-if-type` XML namespaces meaning this is a problem of the client. So, you should contact OpenDaylight instead and if you reference this issue, they should know exactly what the problem is.

Regards,
Michal

**Comment by mashemat** [comment]
Sure, thanks. But in general, what is the difference between ietf-netconf and ietf-netconf-server?
is ietf-netconf-server essential for the communication?

Regards,

**Comment by michalvasko** [comment]
Well, best is to look at the model itself in YANG and read through the configuration, it should always be explained what the particular node means. Generally, `ietf-netconf` is the core module for NETCONF as it defines all of the basic NETCONF RPCs (`get-config`, `edit-config`, ...). `ietf-netconf-server` holds configuration of a particular NETCONF server and no, it is not necessary (and actually not installed by default in case of *netopeer2-server*).

Regards,
Michal
