### ISSUE TITLE
Call Home 

### ISSUE THREAD

**Issue by vishalwc** [CESNET/Netopeer2#39]
any update on call home support ? 
do we have this functionality getting merge with master branch

if not when is this planned and can be expected .

**Comment by michalvasko** [comment]
Hi,
Call Home is currently being worked on, but to make it fully working we want to enable its configuration using *ietf-netconf-server* and adjoining modules. And that will take some additional time. It should definitely be ready in a month, but I am hoping it will take around 2 weeks.

Regards,
Michal

**Comment by vishalwc** [comment]
Hi Michal 

can you please update on the call home support development .

**Comment by michalvasko** [comment]
Hi,
it should be fully implemented in *libnetconf2*, so now I'm working on making it configurable in **netopeer2-server**, which should be done within a week.

Regards,
Michal

**Comment by vishalwc** [comment]
Thanks Michal , looking forward for the merge in this week 

Regards
Vishal

**Comment by vishalwc** [comment]
can you please update on call home Merge ?
