### ISSUE TITLE
Call home functionality not working

### ISSUE THREAD

**Issue by dwdrajesh** [CESNET/Netopeer2#390]
Hi,

After merging the Netopeer2/server/configuration/ssh_callhome.xml file which lists the example configuration, I tried to restart netopeer2-server and it keeps sending the call home requests. However, when I enter "listen" on the netopeer2-cli, it rejects the connection giving the following error:

**Netopeer2-cli log**:
> listen
Waiting 60s for an SSH Call Home connection on port 4334...
The authenticity of the host '::ffff:127.0.0.1' cannot be established.
ssh-rsa key fingerprint is df:4c:d1:ec:d1:d7:48:6d:d4:78:5d:86:c5:9b:e2:e8:ac:e6:3e:0e.
Are you sure you want to continue connecting (yes/no)? yes
root@::ffff:127.0.0.1 password: 
Interactive SSH Authentication
Type your password:
Password: 
nc ERROR: Unable to authenticate to the remote server (all attempts via supported authentication methods failed).
cmd_listen: Receiving SSH Call Home on port 4334 as user "root" failed.

**Netopeer2-server log**:
[INF]: Resolving "ietf-system" unresolved schema nodes and their constraints...
[INF]: All "ietf-system" schema nodes and constraints resolved.
[INF]: Module "ietf-system@2014-08-06" successfully parsed as implemented.
[INF]: Loading schema "iana-crypt-hash@2014-08-06" from sysrepo.
[INF]: Module iana-crypt-hash@2014-08-06 already present in context.
[INF]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/name" created.
[INF]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/ssh" created.
[INF]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/ssh/address" created.
[INF]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/ssh/port" created.
[INF]: Listening on 0.0.0.0:830 for SSH connections.
[INF]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/ssh/host-keys" created.
[INF]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/ssh/host-keys/host-key[name='imported SSH key']/name" created.
[INF]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/ssh/host-keys/host-key[name='imported SSH key']/public-key" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/name" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/ssh" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/ssh/endpoints" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/ssh/endpoints/endpoint[name='test_ssh_ch_endpt']/name" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/ssh/endpoints/endpoint[name='test_ssh_ch_endpt']/address" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/ssh/endpoints/endpoint[name='test_ssh_ch_endpt']/port" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/ssh/host-keys" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/ssh/host-keys/host-key[name='test_ssh_callhome_key']/name" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/ssh/host-keys/host-key[name='test_ssh_callhome_key']/public-key" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/connection-type" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/connection-type/persistent" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/connection-type/persistent/idle-timeout" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/connection-type/persistent/keep-alives" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/connection-type/persistent/keep-alives/max-wait" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/connection-type/persistent/keep-alives/max-attempts" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/reconnect-strategy" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/reconnect-strategy/start-with" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/reconnect-strategy/max-attempts" created.
[INF]: Call Home client "test_ssh_ch_client" connecting...
[INF]: nc_sock_connect(127.0.0.1, 4334, 5, -1)
[INF]: Trying to connect via IPv4.
[INF]: getsockopt error: (Connection refused).

**Comment by michalvasko** [comment]
Hi,
this outputs seems correct to me, you have simply failed to authenticate as `root`. However, I do think there is some output from the server missing because it does not say anything about any user being connected while you obviously did connect.

Regards,
Michal

**Comment by dwdrajesh** [comment]
Hi Michal, Thanks for replying.
I could not find any log related to connection, I am trying the call home functionality and the netopeer2-cli keeps rejecting the login. Here is the log that is printed after netopeer2-server finishes loading all the modules:

Netopeer2-server:

[INF]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/name" created.
[INF]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/ssh" created.
[INF]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/ssh/address" created.
[INF]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/ssh/port" created.
[INF]: Listening on 0.0.0.0:830 for SSH connections.
[INF]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/ssh/host-keys" created.
[INF]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/ssh/host-keys/host-key[name='imported SSH key']/name" created.
[INF]: Path "/ietf-netconf-server:netconf-server/listen/endpoint[name='all-interfaces']/ssh/host-keys/host-key[name='imported SSH key']/public-key" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/name" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/ssh" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/ssh/endpoints" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/ssh/endpoints/endpoint[name='test_ssh_ch_endpt']/name" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/ssh/endpoints/endpoint[name='test_ssh_ch_endpt']/address" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/ssh/endpoints/endpoint[name='test_ssh_ch_endpt']/port" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/ssh/host-keys" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/ssh/host-keys/host-key[name='test_ssh_callhome_key']/name" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/ssh/host-keys/host-key[name='test_ssh_callhome_key']/public-key" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/connection-type" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/connection-type/persistent" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/connection-type/persistent/idle-timeout" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/connection-type/persistent/keep-alives" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/connection-type/persistent/keep-alives/max-wait" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/connection-type/persistent/keep-alives/max-attempts" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/reconnect-strategy" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/reconnect-strategy/start-with" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/reconnect-strategy/max-attempts" created.

**[INF]: Call Home client "test_ssh_ch_client" connecting...**
[INF]: nc_sock_connect(127.0.0.1, 4334, 5, -1)
[INF]: Trying to connect via IPv4.
[INF]: Successfully connected to 127.0.0.1:4334 over IPv4.
[INF]: Path "/ietf-system:system/authentication/user[name='ezdawra']/authorized-key[name='ezdawra-key-name']/name" created.
[INF]: Path "/ietf-system:system/authentication/user[name='ezdawra']/authorized-key[name='ezdawra-key-name']/algorithm" created.
[INF]: Path "/ietf-system:system/authentication/user[name='ezdawra']/authorized-key[name='ezdawra-key-name']/key-data" created.
[INF]: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: Received an SSH message "request-auth" of subtype "none".
[INF]: Received an SSH message "request-auth" of subtype "password".
[INF]: User "root" is not allowed to authenticate using a password.
[INF]: Failed user "root" authentication attempt (#1).
[INF]: Received an SSH message "request-auth" of subtype "interactive".
[ERR]: User "root" failed to authenticate for too long, disconnecting.
[INF]: nc_sock_connect(127.0.0.1, 4334, 5, -1)
[INF]: Trying to connect via IPv4.
[INF]: Successfully connected to 127.0.0.1:4334 over IPv4.
[ERR]: SSH key exchange timeout.
[INF]: nc_sock_connect(127.0.0.1, 4334, 5, -1)
[INF]: Trying to connect via IPv4.
[INF]: getsockopt error: (Connection refused).
[INF]: nc_sock_connect(127.0.0.1, 4334, 5, -1)
[INF]: Trying to connect via IPv4.
[INF]: getsockopt error: (Connection refused).
[INF]: nc_sock_connect(127.0.0.1, 4334, 5, -1)
[INF]: Trying to connect via IPv4.
[INF]: getsockopt error: (Connection refused).
[INF]: nc_sock_connect(127.0.0.1, 4334, 5, -1)
[INF]: Trying to connect via IPv4.
[INF]: getsockopt error: (Connection refused).
[INF]: nc_sock_connect(127.0.0.1, 4334, 5, -1)
[INF]: Trying to connect via IPv4.
[INF]: getsockopt error: (Connection refused).
[INF]: nc_sock_connect(127.0.0.1, 4334, 5, -1)
[INF]: Trying to connect via IPv4.
[INF]: getsockopt error: (Connection refused).
^C[INF]: Client Subscription Manager successfully destroyed.
[WRN]: String "test_ssh_ch_endpt" not freed from the dictionary, refcount 1
[WRN]: String "test_ssh_ch_client" not freed from the dictionary, refcount 1
[WRN]: String "127.0.0.1" not freed from the dictionary, refcount 1

**Netopeer2-cli log:** 
netopeer2-cli 
> 
> 
> 
> listen
Waiting 60s for an SSH Call Home connection on port 4334...
The authenticity of the host '::ffff:127.0.0.1' cannot be established.
ssh-rsa key fingerprint is df:4c:d1:ec:d1:d7:48:6d:d4:78:5d:86:c5:9b:e2:e8:ac:e6:3e:0e.
Are you sure you want to continue connecting (yes/no)? yes
root@::ffff:127.0.0.1 password: 
Interactive SSH Authentication
Type your password:
Password: 
nc ERROR: Authentication response timeout.
cmd_listen: Receiving SSH Call Home on port 4334 as user "root" failed.

**Comment by michalvasko** [comment]
Hi,
now, this is helpful and the problem is
```
[INF]: User "root" is not allowed to authenticate using a password.
```
Look into the manual `shadow(5)`, section *encrypted password* for explanation.

Regards,
Michal

**Comment by dwdrajesh** [comment]
Hi Michal,
I understand that the user 'root' has the ! or * in the shadow file which means root user cannot login using password. But the problem is, if I try to start netopeer2-server without sudo access, it gives an error 'Permission Denied' on the very first line of the log. Do you have any suggestions ? Or can we specify other username (other than 'root') when using call-home ?

**Comment by michalvasko** [comment]
Hi,
you must start *netopeer2-server* with `root` access, that is true. But you can create a NETCONF session with any user on the system that can login, so yes, just pick another user.

Regards,
Michal

**Comment by dwdrajesh** [comment]
Thanks Michal. Adding a new authorization key using "auth keys add" worked!

**Comment by dwdrajesh** [comment]
Thanks Michal. Adding a new authorization key using "auth keys add" from the netopeer2-cli side worked!
