### ISSUE TITLE
Empty rpc-reply

### ISSUE THREAD

**Issue by kpbarrett** [CESNET/netopeer2#392]
An RPC output set with only nonpresence container(s) results in netopeer2-server generating an empty \<rpc-reply>, which causes a libnetconf2 client to fail with the message "An empty \<rpc-reply>."

The attached patch contains a passing test which illustrates this; see test_rpc_empty_container() in test_generic.c.

I'm not sure how this should be fixed. I don't see where the RFC explicitly disallows an empty rpc-reply, so maybe just eliminating the error condition?

[empty-reply-patch.txt](https://github.com/CESNET/Netopeer2/files/2861008/empty-reply-patch.txt)

**Comment by michalvasko** [comment]
Hi,
it is technically written [here](https://tools.ietf.org/html/rfc6241#section-4.4). Anyway, it should work now with the updated *libnetconf2*. I have also corrected the output in *neotpeer2-cli* in these cases, so if you are using it, you should update it, too.

Regards,
Michal
