### ISSUE TITLE
Question: When will the new version of netopeer2 be released?

### ISSUE THREAD

**Issue by yangtian127** [CESNET/Netopeer2#393]
Hi,
The new version of libyang has been released witch is compatible with the lower version of gcc.
When will the new version of netopeer2 be released ?

**Comment by michalvasko** [comment]
Hi,
only *libyang* used to require new GCC. You can compile *netopeer2* with old GCC versions (I have just tested it using GCC 4.8.4).

Regards,
Michal

**Comment by yangtian127** [comment]
Hi,
Sorry, I make a mistake.
libnetconf2 compile with new GCC, is the new version released soon?

**Comment by michalvasko** [comment]
Hi,
I have tested compiling current *libyang*, *libnetconf2*, *sysrepo*, and *netopeer2-server* with GCC 4.8.4 (on Ubuntu 14.04.5) and it was successful. What exactly is the error you are getting?

Regards,
Michal

**Comment by yangtian127** [comment]
Hi,
I compiled libnetconf2-v0.12-r1 with GCC 4.8.5 on CentOS7, report an error:
stdatomic.h No such file or directory 

thks

**Comment by michalvasko** [comment]
Hi,
okay, I did not test the "release", I simply took the latest `devel` (or `master`, makes no difference) libraries. I suggest you do the same.

Regards,
Michal

**Comment by rkrejci** [comment]
New releases should be available during March. The problem with `stdatomic.h` is known issue and, as Michal mentioned, it is currently fixed in `devel` and `master`, but not yet available in any release package.

**Comment by yangtian127** [comment]
Ok, tanks very much.
