### ISSUE TITLE
SSH key exchange timeout

### ISSUE THREAD

**Issue by qynum123** [CESNET/netopeer2#394]
Hi, 
After someone connect the Netopeer2 server from other computer with the same root account, the Netopeer2 server can't work, the messages show "SSH key exchange timeout", I don't know why this happen, and could you please help me fix this without reinstall the netopeer2? Thanks in advance.

The following are the netopeer2-server logs:
[INF]: Loading schema "ietf-ssh-server@2016-11-02" from sysrepo.
[INF]: Module ietf-ssh-server@2016-11-02 already present in context.
[INF]: Resolving "ietf-system" unresolved schema nodes and their constraints...
[INF]: Loading schema "ietf-hardware@2018-03-13" from sysrepo.
[INF]: Reading module "ietf-hardware".
[INF]: Module "xran-hardware@2018-11-14" successfully parsed as implemented.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/name" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/ssh" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/ssh/endpoints" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/ssh/host-keys" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/connection-type" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/connection-type/persistent" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/connection-type/persistent/idle-timeout" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/connection-type/persistent/keep-alives" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/connection-type/persistent/keep-alives/max-wait" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/connection-type/persistent/keep-alives/max-attempts" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/reconnect-strategy" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/reconnect-strategy/start-with" created.
[INF]: Path "/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']/reconnect-strategy/max-attempts" created.
[INF]: Call Home client "test_ssh_ch_client" connecting...
[INF]: nc_sock_connect(127.0.0.1, 4334, 5, -1)
[INF]: Trying to connect via IPv4.
[INF]: Successfully connected to 127.0.0.1:4334 over IPv4.
**_**[ERR]: SSH key exchange timeout.**_**
[INF]: nc_sock_connect(127.0.0.1, 4334, 5, -1)
[INF]: Trying to connect via IPv4.
[INF]: Successfully connected to 127.0.0.1:4334 over IPv4.
[ERR]: SSH key exchange timeout.
[INF]: nc_sock_connect(127.0.0.1, 4334, 5, -1)
[INF]: Trying to connect via IPv4.
[INF]: Successfully connected to 127.0.0.1:4334 over IPv4.

**Comment by michalvasko** [comment]
Hi,
it is not a problem that you are connecting with the same account. SSH key exchange is entirely up to *libssh* so if it does not work, there is a problem in the SSH transport on either communication side, not in our software. What client are you using? Does it generate any relevant output? It seems to me the client is at fault.

Regards,
Michal

**Comment by qynum123** [comment]
Thanks very much for your help, I'm using xshell 4, after reboot the machine, netopeer2 works now.
