### ISSUE TITLE
I have a question about leafref in rpc.

### ISSUE THREAD

**Issue by yahovevo** [CESNET/Netopeer2#395]
I have a problem to response about rpc which includes leafref but I can't find the solution to send data properly.

We use 2 kinds of yang file like below.
Can you analyzer this problem?

------------------------- yang files
xran-ald.yang
```yang
  rpc ald-communication {
    description
      "Rpc to support communication between lls-CU and Antenna Line Devices";

	input {
      leaf port-id {
	    type leafref {
		  path "/ap:ald-ports-io/ap:ald-port/ap:port-id";
		}
        mandatory true;
        description
          "Unique ALD port identifier reported by radio";
      }

	  leaf ald-req-msg {
	    type binary {
		  length "0..1200";
		}

		description
		  "Response message to be forwarded to ALD in type of binary-string";
	  }
    }

	output {
      leaf port-id {
	    type leafref {
		  path "/ap:ald-ports-io/ap:ald-port/ap:port-id";
		}
        mandatory true;
        description
          "Unique ALD port identifier reported by radio";
      }

      leaf status {
        type enumeration {
          enum ACCEPTED {
		    description
			  "Operation was accepted, message was processed towards ALD and response is provided";
		  }
          enum REJECTED {
		    description
			  "Operation was rejected by RU";
		  }
        }
        mandatory true;

        description
		  "Status of RPC handling seen from RU perspective";
      }
     }
}
```
xran-ald-port.yang
```yang
  container ald-ports-io {
    description
      "ALD port information.
       ALD port of the RU that can be used to connect External Equipment (Antenna Line Devices).
       Communication uses AISG over HDLC.
       Physical connection depends on connector type offered by the port (RS-485 or antenna line)
       Note: Single instance of ALD Port can point to more than one antenna line devices.";

    leaf over-current-supported {
      type boolean;
      default false;
      description
	    "Set to TRUE when the RU supports over curent notifications";
    }

    list ald-port {
      key "name";
      description
        "Leaf nodes describing ALD Port";
      leaf name {
        type string {
          length "1..255";
        }
        description
          "A name that is unique across the RU that identifies a ald port instance.
          This name may be used in fault management to refer to a fault source
          or affected object";
      }

      leaf port-id {
        type uint8;
		    config false;
		    mandatory true;

		    description
          "A number which identifies an ALD Port.
          The number of the Physical ALD port connector in the module.
          If the module supports 2 ALD Port connectors, use 0 and 1.";
      }
```
------------------------- netopeer2-cli response
 user-rpc --content rpc_ald_communication.xml 
```xml
<ald-communication xmlns="urn:xran:ald:1.0" xmlns:xran-ald="urn:xran:ald:1.0">
  <port-id>0</port-id>
  <ald-req-msg/>
</ald-communication>
```
---> response
```
nc DEBUG: Session 2: received message:
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="36"><rpc-error><error-type>application</error-type><error-tag>data-missing</error-tag><error-severity>error</error-severity><error-app-tag>instance-required</error-app-tag><error-path>/xran-ald:ald-communication/port-id</error-path><error-message xml:lang="en">Leafref "/xran-ald-port:ald-ports-io/xran-ald-port:ald-port/xran-ald-port:port-id" of value "0" points to a non-existing leaf.</error-message></rpc-error></rpc-reply>

ERROR
	type:     application
	tag:      data-missing
	severity: error
	app-tag:  instance-required
	path:     /xran-ald:ald-communication/port-id
	message:  Leafref "/xran-ald-port:ald-ports-io/xran-ald-port:ald-port/xran-ald-port:port-id" of value "0" points to a non-existing leaf.
```

------------------------- data store
```
/sambashare/yang/sysrepo/build/repository/data$ cat xran-ald-port.running
<ald-ports-io xmlns="urn:xran:ald-port:1.0">
  <over-current-supported>false</over-current-supported>
  <ald-port>
    <name>ald001</name>
    <port-id>0</port-id>
  </ald-port>
</ald-ports-io>
```
------------------------- netopeer2 server log
```
VERBOSE: Resolving unresolved data nodes and their constraints...
VERBOSE: There is no leafref "/xran-ald-port:ald-ports-io/xran-ald-port:ald-port/xran-ald-port:port-id" with the value "0", but it is not required.
VERBOSE: All data nodes and constraints resolved.
DEBUG: (cl_request_process:493) Sending check-exec-permission request.
DEBUG: (cl_request_process:506) check-exec-permission request sent, waiting for response.
DEBUG: (cl_request_process:519) check-exec-permission response received, processing.
DEBUG: (cl_request_process:493) Sending rpc request.
DEBUG: (cl_request_process:506) rpc request sent, waiting for response.
DEBUG: (cl_request_process:519) rpc response received, processing.
VERBOSE: Resolving unresolved data nodes and their constraints...
ERROR: Leafref "/xran-ald-port:ald-ports-io/xran-ald-port:ald-port/xran-ald-port:port-id" of value "0" points to a non-existing leaf. (/xran-ald:ald-communication/port-id)
VERBOSE: Session 2: thread 4 event new RPC.
VERBOSE: Session 2: thread 4 event reply error.
```
Regards
Boyong

**Comment by yahovevo** [comment]
I miss call back function.

int sysrepo_thread::XRanRpcALDCommunicationCb(const char *xpath, const sr_val_t *input, const size_t input_cnt,
                                        sr_val_t **output, size_t *output_cnt, void *private_ctx)
{
#if defined(TRACE_CALL)
  aprintf(LOG_RMS,  "[%s#,%d] %s\n\r", __FILE__, __LINE__, xpath);
#endif

  sysrepo_thread *pfSysrepo = static_cast<sysrepo_thread*>(private_ctx);
  string strXpath, strMXpath;
  strXpath= string(xpath);

  //Input
  if(sr_xpath_node_name_eq(input[0].xpath,"port-id"))
    aprintf(LOG_RMS,  "[%s#,%d] value=%d\n\r", __FILE__, __LINE__, input[0].data.uint8_val);
  if(sr_xpath_node_name_eq(input[1].xpath,"ald-req-msg"))
    aprintf(LOG_RMS,  "[%s#,%d] ald-req-msg\n\r", __FILE__, __LINE__);

  //Output
  *output_cnt = 2;
  *output = (sr_val_t*)calloc(*output_cnt, sizeof(**output));
  //strMXpath= "/xran-ald-port:ald-ports-io/ald-port[name='ald001']/port-id";
  strMXpath= strXpath + "/port-id";

#if 1
  (*output)[0].xpath = strdup(strMXpath.c_str());
  (*output)[0].type = SR_UINT8_T;
  (*output)[0].data.uint8_val = 0;
#endif

  strMXpath= strXpath + "/status";
  (*output)[1].xpath = strdup(strMXpath.c_str());
  (*output)[1].type = SR_ENUM_T;
  (*output)[1].data.enum_val = strdup("ACCEPTED");

  return SR_ERR_OK;
}

**Comment by michalvasko** [comment]
Hi,
the problem is that `/ap:ald-ports-io/ap:ald-port/ap:port-id` is a `config false` (state) node. To have it in the datastore (for the validation to pass) you need to provide this node using a `sr_dp_get_items_cb` callback (set by `sr_dp_get_items_subscribe()`).

Regards,
Michal

**Comment by yahovevo** [comment]
Thanks for reply.

I already registered sr_dp_get_items_subscribe() callback.

---------------------------------
rc = sr_dp_get_items_subscribe(m_srSession, "/xran-ald-port:ald-ports-io", XRanGetALDPortCb, this, SR_SUBSCR_CTX_REUSE, &m_srSubscription);

int sysrepo_thread::XRanGetALDPortCb(const char *xpath, sr_val_t **values, size_t *values_cnt, void *private_ctx)
{
#if defined(TRACE_CALL)
  aprintf(LOG_RMS,  "[%s#,%d], xpath=%s\n\r", __FILE__, __LINE__, xpath);
#endif
  UNUSED(values);
  UNUSED(values_cnt);
  UNUSED(private_ctx);
  //sysrepo_thread *pfSysrepo = static_cast<sysrepo_thread*>(private_ctx);
  string strXpath, strMXpath;
  static string strLeaf;

  if (0 == strcmp("/xran-ald-port:ald-ports-io/ald-port[name='ald001']/port-id", xpath))
  {
    int z=0;
    *values = (sr_val_t*)calloc(1, sizeof(**values));
    if (NULL == *values) {
      printf("Allocation failed");
      return -2;
    }

    (*values)[z].xpath = strdup(xpath);
    (*values)[z].type = SR_UINT8_T;
    (*values)[z++].data.uint8_val= 0;

    *values_cnt = z;
  }
}
---------------------------------
But I get response from netopeer2 server.

nc DEBUG: Session 1: received message:
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="56"><rpc-error><error-type>application</error-type><error-tag>data-missing</error-tag><error-severity>error</error-severity><error-app-tag>instance-required</error-app-tag><error-path>/xran-ald:ald-communication/port-id</error-path><error-message xml:lang="en">Leafref "/xran-ald-port:ald-ports-io/xran-ald-port:ald-port/xran-ald-port:port-id" of value "0" points to a non-existing leaf.</error-message></rpc-error></rpc-reply>

ERROR
	type:     application
	tag:      data-missing
	severity: error
	app-tag:  instance-required
	path:     /xran-ald:ald-communication/port-id
	message:  Leafref "/xran-ald-port:ald-ports-io/xran-ald-port:ald-port/xran-ald-port:port-id" of value "0" points to a non-existing leaf.
> 

Please check it one more... Thanks

**Comment by yahovevo** [comment]
I've attach more log. I can't find why it doesn't work. Please help  me.

> get --filter-xpath /xran-ald-port:*
ly VERBOSE: Resolving unresolved data nodes and their constraints...
ly VERBOSE: All data nodes and constraints resolved.
DATA
<ald-ports-io xmlns="urn:xran:ald-port:1.0">
  <over-current-supported>false</over-current-supported>
  <ald-port>
    <name>ald001</name>
    <port-id>0</port-id>
  </ald-port>
</ald-ports-io>

> user-rpc --content rpc_ald_communication.xml    
ly VERBOSE: Resolving unresolved data nodes and their constraints...
ly VERBOSE: There is no leafref "/xran-ald-port:ald-ports-io/xran-ald-port:ald-port/xran-ald-port:port-id" with the value "0", but it is not required.
ly VERBOSE: All data nodes and constraints resolved.
ly VERBOSE: Resolving unresolved data nodes and their constraints...
ly VERBOSE: All data nodes and constraints resolved.
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	path:     /xran-ald:ald-communication/port-id
	message:  Leafref "/xran-ald-port:ald-ports-io/xran-ald-port:ald-port/xran-ald-port:port-id" of value "0" points to a non-existing leaf.
> 
//rpc_ald_communication.xml
<ald-communication xmlns="urn:xran:ald:1.0">
  <port-id>0</port-id>
  <ald-req-msg/>
</ald-communication>

//libyang, libnetconf, netopeer2-serverlog
VERBOSE: Resolving unresolved data nodes and their constraints...
VERBOSE: All data nodes and constraints resolved.
VERBOSE: Session 1: thread 1 event new RPC.
DEBUG: DICT: inserting "rpc" with collision 
DEBUG: DICT: inserting (refcount) "urn:ietf:params:xml:ns:netconf:base:1.0"
DEBUG: DICT: inserting "message-id" with collision 
DEBUG: DICT: inserting "37" with collision 
DEBUG: DICT: inserting (refcount) "get"
DEBUG: DICT: inserting (refcount) "urn:ietf:params:xml:ns:netconf:base:1.0"
DEBUG: DICT: inserting (refcount) "filter"
DEBUG: DICT: inserting (refcount) "type"
DEBUG: DICT: inserting (refcount) "xpath"
DEBUG: DICT: inserting (refcount) "xran-ald-port"
DEBUG: DICT: inserting (refcount) "urn:xran:ald-port:1.0"
DEBUG: DICT: inserting (refcount) "select"
DEBUG: DICT: inserting "/xran-ald-port:*" with collision 
DEBUG: DICT: inserting (refcount) ""
DEBUG: DICT: inserting (refcount) ""
DEBUG: DICT: inserting (refcount) ""
DEBUG: DICT: inserting (refcount) "type"
DEBUG: DICT: inserting (refcount) "xpath"
DEBUG: DICT: inserting (refcount) "select"
DEBUG: DICT: inserting (refcount) "/xran-ald-port:*"
DEBUG: DICT: inserting (refcount) "/xran-ald-port:*"
DEBUG: DICT: inserting (refcount) ""
VERBOSE: Resolving unresolved data nodes and their constraints...
VERBOSE: All data nodes and constraints resolved.
DEBUG: DICT: inserting (refcount) "*"
DEBUG: DICT: inserting (refcount) "filter"
DEBUG: DICT: inserting (refcount) "*"
DEBUG: DICT: inserting (refcount) "with-defaults"
DEBUG: DICT: inserting (refcount) "false"
DEBUG: DICT: inserting "ald001" with collision 
DEBUG: DICT: inserting (refcount) "ald001"
DEBUG: DICT: inserting (refcount) "0"
VERBOSE: Resolving unresolved data nodes and their constraints...
VERBOSE: All data nodes and constraints resolved.
VERBOSE: Session 1: thread 0 event new RPC.
DEBUG: DICT: inserting "rpc" with collision 
DEBUG: DICT: inserting (refcount) "urn:ietf:params:xml:ns:netconf:base:1.0"
DEBUG: DICT: inserting "message-id" with collision 
DEBUG: DICT: inserting "38" with collision 
DEBUG: DICT: inserting (refcount) "ald-communication"
DEBUG: DICT: inserting (refcount) "urn:xran:ald:1.0"
DEBUG: DICT: inserting (refcount) "port-id"
DEBUG: DICT: inserting (refcount) "0"
DEBUG: DICT: inserting (refcount) "ald-req-msg"
DEBUG: DICT: inserting (refcount) ""
DEBUG: DICT: inserting (refcount) ""
DEBUG: DICT: inserting (refcount) ""
DEBUG: DICT: inserting (refcount) "0"
DEBUG: DICT: inserting (refcount) ""
VERBOSE: Resolving unresolved data nodes and their constraints...
DEBUG: DICT: inserting (refcount) "ald-ports-io"
VERBOSE: There is no leafref "/xran-ald-port:ald-ports-io/xran-ald-port:ald-port/xran-ald-port:port-id" with the value "0", but it is not required.
VERBOSE: All data nodes and constraints resolved.
DEBUG: DICT: inserting (refcount) "*"
ERROR: (cl_rpc_send:3154) Error by processing of the request.
DEBUG: DICT: inserting "Request could not be completed because the requested operation failed for a non-specific reason." with collision 
DEBUG: DICT: inserting "en" with collision 
DEBUG: DICT: inserting "Leafref "/xran-ald-port:ald-ports-io/xran-ald-port:ald-port/xran-ald-port:port-id" of value "0" points to a non-existing leaf." with collision 
DEBUG: DICT: inserting "en" with collision 
DEBUG: DICT: inserting "/xran-ald:ald-communication/port-id" with collision 
VERBOSE: Session 1: thread 3 event new RPC.
VERBOSE: Session 1: thread 3 event reply error.

**Comment by michalvasko** [comment]
Hi,
I see several possible issues with your overall set up. Firstly, you have `<port-id>0</port-id>` in your `running` file. It is a `config false` value, it should not be in the file at all. This also may be the reason you are seeing this value in `<get>` output even though it is actually not there, for *sysrepo* anyway.

Then, you subscribed to providing `/xran-ald-port:ald-ports-io` data. The documentation warns that if this path is `config true`, it will not do anything. Therefore, I think your callback is never called. Did you check?

Lastly, you are providing the value only if the `xpath` is `/xran-ald-port:ald-ports-io/ald-port[name='ald001']/port-id`. I do not think you will ever get this XPath because in these callbacks you should never get any predicates, you always provide children for all possible parent instances.

Regards,
Michal

**Comment by yaxueXu** [comment]
Hi, yahovevo,
Have you fixed the issue describled in  #395 'I have a question about leafref in rpc.'? what is your solution to this issue?
I have a similar problem to your #395.

**Comment by michalvasko** [comment]
Hi,
it would be best if you could use the current *sysrepo* (versions 1.x). But, if you describe you use-case I may be able to help you anyway, it most likely is working correctly even in the old *sysrepo*.

Regards,
Michal

**Comment by yaxueXu** [comment]
Hi, Michal
Thanks for your reply.
I opened a new issue that is #522. 
And I am upgrading the current sysrepo and netopeer2 that you have suggested, and have not finished installing them yet. I will test my case after finishing installation.

Regards,
yaxue

**Comment by late-pankaj** [comment]
Hello @michalvasko ,

Details:- 
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v2.2.73 (SO v7.14.32)
netopeer2-server 2.1.62

Here port-id is set to config true in o-ran-ald-port.yang (yang version 1.1)
I am still getting below error whenever ald-communication rpc is invoked 

Error:- 
libyang[0]: Invalid leafref value "0" - no target instance "/ap:ald-ports-io/ap:ald-port/ap:port-id" with the same value. (path: Data location "/o-ran-ald:ald-communication/port-id".)
Error by sr_rpc_send: Validation failed

port configuration is fine :-
root@bmirusim1:/opt/dev/mplane-rusim/rusim_src/aisg# sysrepocfg -X -m /o-ran-ald-port -d running -v3
[INF] Connection 5041 created.
[INF] Session 23986 (user "root", CID 5041) created.
<ald-ports-io xmlns="urn:o-ran:ald-port:1.0">
  <ald-port>
    <name>AldPort_0</name>
    <port-id>0</port-id>
    <dc-control-support>true</dc-control-support>
    <supported-connector>ANTENNA_CONNECTOR</supported-connector>
  </ald-port>
</ald-ports-io>

Neither the rpc subscribe is working fine ,
// Subscribe to the RPC
    rc = sr_rpc_subscribe(session, "/o-ran-ald:ald-communication", rpc_callback, NULL, 2, SR_SUBSCR_DEFAULT, &subscription);
    if (rc != SR_ERR_OK) {
        fprintf(stderr, "Error by sr_rpc_subscribe: %s\n", sr_strerror(rc));
        goto cleanup;
    }

this is getting succesfully triggered but callback never reaches

**Comment by michalvasko** [comment]
Try `sysrepocfg -X -m /o-ran-ald-port -d operational -v3` instead, the RPC is always validated with the **operational** datastore, not **running**.

**Comment by late-pankaj** [comment]
Thank you @michalvasko .
It worked .
