### ISSUE TITLE
Sending notification cause netopeer2-server crash

### ISSUE THREAD

**Issue by yangtian127** [CESNET/Netopeer2#396]
Hi,
On netopeer-cli has subscribed notifications, if notification is sending while netopeer-cli disconnection cause netopeer2-server crash.

On netopeer2-server:
op_ntf_unsubscribe work in worker_thread, free the struct np_subscriber *subscriber directly.
np2srv_ntf_clb work in cl_sm_event_loop_threaded, access private_ctx without protection.

A notification is sending while netopeer-cli disconnected, will cause the np2srv_ntf_clb or np2srv_ntf_send access the pointer has been free.

**Comment by michalvasko** [comment]
Hi,
I do not think this issue can be perfectly solved because there will always be a data race between the unsubscribe request and a new notification delivered. However, now it should happen only very rarely.

Regards,
Michal
