### ISSUE TITLE
Data model not found

### ISSUE THREAD

**Issue by qynum123** [CESNET/Netopeer2#397]
Hi,
I want to install a new module, but it failed as follows:
sysrepoctl --install --yang=/home/steven/5g/yangmodel/Interfaces/xran-interfaces.yang --owner=root:root --permissions=777
Installing a new module from file '/home/steven/5g/yangmodel/Interfaces/xran-interfaces.yang'...
[ERR] (srctl_ly_log_cb:506) libyang: Data model "iana-if-type" not found.
[ERR] (srctl_ly_log_cb:506) libyang: Importing "iana-if-type" module into "xran-interfaces" failed.
[ERR] (srctl_ly_log_cb:506) libyang: Module "xran-interfaces" parsing failed.
Error: Unable to load the module by libyang.
Install operation failed.
but the module "iana-if-type" actually installed, as follows:
[root@hadoop02 Interfaces]# sysrepoctl -l | grep iana-if-type
iana-if-type               | 2018-07-03 | Installed   |

Could you please give some hints? Thanks in advance!

**Comment by michalvasko** [comment]
Hi,
installed modules are not considered by default when installing another one. You can change this behavior with the `-S` parameter (`sysrepoctl -h` informs about this).

Regards,
Michal

**Comment by qynum123** [comment]
Thanks, can -S specified multiple directories?

**Comment by michalvasko** [comment]
Hi,
please read the help, `-S` parameter does not have an argument and it adds a **single** search directory for YANG modules being the one where all already installed modules are. You can also specify an arbitrary search directory with `-s` and a path to that directory. That can be done **multiple** times.

Regards,
Michal

**Comment by qynum123** [comment]
It works, thanks a lot!
