### ISSUE TITLE
Query : API to identify netconf session created via call home in netopeer2 

### ISSUE THREAD

**Issue by shishirpandey29** [CESNET/Netopeer2#398]
Hi,
 is there any API available in netopeer-server to identify netconf session created via call home?

**Comment by michalvasko** [comment]
Hi,
no, but a flag is stored internally in *libnetconf2* so I could add a simple function for checking it. But you are talking about *netopeer2* so I am not sure what is it that you are asking.

Regards,
Michal

**Comment by shishirpandey29** [comment]
Hi Michal,

Our application has to send a  user defined notification via netconf session created during call home.
So we subscribed to "ietf-netconf-notifications:netconf-session-start" in our application  but it seems that "ietf-netconf-notifications:netconf-session-start" is generated for all netconf-sessions created in Netopeer2 (netconf session created during call home or not ).

Basically , our application needs netconf session start notification when netconf session creates during call home.
1) Is it possible to provide a notification for a netconf session created during call home from Netopeer2?
OR
2) Add a logic in Netopeer2 to detect a netconf session creation during call home ?

**Comment by michalvasko** [comment]
Hi,
I have added a new function `nc_session_is_callhome` into *libnetconf2*. If you use it in `main.c:np2srv_new_session_clb()` to generate your specific notification in addition to the standard one, you should get the functionality you want.

Regards,
Michal

**Comment by shishirpandey29** [comment]
Hi Michal,

I applied the changes as suggested , it worked fine.
Thanks
