### ISSUE TITLE
how to install netopeer2 in cent os 7

### ISSUE THREAD

**Issue by arun-ashok** [CESNET/Netopeer2#399]

**Comment by michalvasko** [comment]
Hi,
generally, just follow the instructions. If you encountered any error, please provide details.

Regards,
Michal

**Comment by arun-ashok** [comment]
I am very new to Netopeer. Can you share any docker file or can I get step
by step instructions to install?

**Comment by arun-ashok** [comment]
Is there any tutorial to understand about the working of netopeer??

**Comment by michalvasko** [comment]
Hi,
before looking at the links below, you should have at least basic understanding of YANG and NETCONF, we have no tutorial on these topics alone.

Then, main documentation is in the [sysrepo](https://github.com/sysrepo/sysrepo) project as it is used as the back-end (datastore), *netopeer2* just provides the NETCONF layer. Some basic *sysrepo* tutorial is in the full [documentation](http://www.sysrepo.org/static/doc/html/start_page.html). You can also find [docker files](https://github.com/sysrepo/sysrepo/tree/master/deploy/docker) there with all the software running including *netopeer2*.

Regards,
Michal

**Comment by arun-ashok** [comment]
Ok Thank You.

I will go through those.

Regards,
Arun Ashok
