### ISSUE TITLE
How to install netopeer2-cli

### ISSUE THREAD

**Issue by arun-ashok** [CESNET/Netopeer2#400]
I have installed netopeer2-server and it is running successfully.
But when I give netopeer2-cli error is shown as command not found.

**Comment by michalvasko** [comment]
Hi,
CLI is in a separate directory and it must also be compiled and installed separately.

Regards,
Michal

**Comment by arun-ashok** [comment]
Is there any docker file to install netopeer2-cli?

**Comment by michalvasko** [comment]
Hi,
this [docker script](https://github.com/sysrepo/sysrepo/tree/master/deploy/docker/sysrepo-netopeer2) should install both *neotpeer2-server* and *netopeer2-cli*.

Regards,
Michal
