### ISSUE TITLE
Couldn't start a netconf session

### ISSUE THREAD

**Issue by arun-ashok** [CESNET/Netopeer2#401]
I am trying to start a netconf session but I am getting following error

> connect
Interactive SSH Authentication
Type your password:
Password:
root@localhost password:
nc ERROR: Unable to authenticate to the remote server (all attempts via supported authentication methods failed).
cmd_connect: Connecting to the localhost:830 as user "root" failed.

**Comment by michalvasko** [comment]
Hi,
what does *netopeer2-server* prints? When started with `-d -v2`.

Regards,
Michal
