### ISSUE TITLE
cross-compiling error in keystored

### ISSUE THREAD

**Issue by foolloow** [CESNET/netopeer2#403]
I need to install the netopeer in ppc64, so i build many libs in ppc64 cross-compiler.
When i make install the keystored according to the install process, it failed with errors.
(https://github.com/sartura/sr_uci/blob/master/docker/cross_compiling/Dockerfile.cross)

I think that may be the problem of libyang.
Because if i make&&make install libyang in x86 and make&&make install keystored in x86, it will be OK, but if i cross-compiled libyang, both make&&make install keystored in x86 or ppc64 have the same errors.

cross-compile libyang replace the /usr/local/lib/libyang/extensions/*.so 
I think that was not my intension.

The error is just occured in these *.so.

So my questions is netopeer2 need to installed directly in a ppc64?
If i want to cross-compile it in a x86, what should i do?

**Comment by michalvasko** [comment]
Hi,
I have never tried cross-compiling this myself so I am unable to help you, but the least you could do is to include the errors you got, no one will be able to help you without them.

Regards,
Michal

**Comment by OlympusHo** [comment]
Hi,
i have the same problem ,see the error log below:
.....
[100%] Linking C shared library libkeystored.so
[100%] Built target keystored
[100%] Built target keystored
Install the project...
-- Install configuration: "Release"
-- Installing: /home/olympus/toolchain/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabi/lib/pkgconfig/keystored.pc
-- Up-to-date: /home/olympus/toolchain/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabi/etc/keystored/keys
/usr/local/bin/sysrepoctl: error while loading shared libraries: libsysrepo.so.0.7: wrong ELF class: ELFCLASS32
- Installing module ietf-x509-cert-to-name...
/usr/local/bin/sysrepoctl: error while loading shared libraries: libsysrepo.so.0.7: wrong ELF class: ELFCLASS32
/usr/local/bin/sysrepocfg: error while loading shared libraries: libsysrepo.so.0.7: wrong ELF class: ELFCLASS32
- SSH hostkey found, no need to generate a new one.
- Importing ietf-keystore stock key configuration...
/usr/local/bin/sysrepocfg: error while loading shared libraries: libsysrepo.so.0.7: wrong ELF class: ELFCLASS32
-- Installing: /usr/local/lib/sysrepo/plugins/libkeystored.so
-- Set runtime path of "/usr/local/lib/sysrepo/plugins/libkeystored.so" to ""



root@ubuntu:/home/olympus/build-root/Netopeer2-0.7-r1/keystored/build# file /usr/local/bin/sysrepoctl
/usr/local/bin/sysrepoctl: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=67d26927d11b2b1222178ea864324628b790151d, not stripped
root@ubuntu:/home/olympus/build-root/Netopeer2-0.7-r1/keystored/build# file /usr/lib/libsysrepo.so.0.7
/usr/lib/libsysrepo.so.0.7: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=8c5b31f9cf8f28d53fc0f83c03890e83dd979a93, not stripped
