### ISSUE TITLE
A basic question that how to register yang module file to netopeer2 server

### ISSUE THREAD

**Issue by LilyCuili** [CESNET/Netopeer2#409]
Hi
I use netopeer2 docker image to create netopeer2 docker,now I want to register yang module file to the netopeer2 server,I want to know how to do it.
Can you give the userguide?

Thanks a log

**Comment by michalvasko** [comment]
Hi,
*netopeer2* uses *sysrepo* for YANG module and data handling, so look into its [documentation](http://www.sysrepo.org/static/doc/html/start_page.html).

Regards,
Michal

**Comment by LilyCuili** [comment]
Thank you for the quick response,it can resolve my problem clearly.
