### ISSUE TITLE
copy-config always failed

### ISSUE THREAD

**Issue by fanchanghu** [CESNET/Netopeer2#41]
I get this error message when I execute `copy-config --target running --src-config=/root/d.xml` in netopeer2-cli.
```
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        path:     /ietf-netconf-acm:nacm/enable-nacm
        message:  Requested schema model is not known
```

module:
```
module t{
  namespace "ttt:1";
  prefix t;
  
  container c1{
    leaf f1{
      type int8;
    }
  }
}
```
d.xml
```
<c1 xmlns="ttt:1">
<f1>10</f1>
</c1>
```

**Comment by rkrejci** [comment]
Hi, can you try it again with the current master branches (including sysrepo)?

**Comment by fanchanghu** [comment]
Hi, I don't think this is caused by sysrepo, it seems that `lyd_parse_mem` or `lyd_parse_xml `added some default value to the data tree in `op_editconfig`, it caused netopeer server sent the default value node to sysrepo by `sr_set_item`.

**Comment by rkrejci** [comment]
By asking for updating source codes including sysrepo I'm not saying that it was caused by sysrepo. I'm just not able to reproduce the issue with the current master branches of libyang, libnetconf2, sysrepo and Netopeer2.

**Comment by rkrejci** [comment]
It was probably caused really by Netopeer2 because it was using (because of dependency) ietf-netconf-acm module which is not yet implemented in sysrepo. However, this was changed in netopeer2-server 0.2.28.

**Comment by fanchanghu** [comment]
ok, I will try it later.

**Comment by fanchanghu** [comment]
hi, it is ok now~~
