### ISSUE TITLE
Question: Is there any developing document  or architecture document for netopeer2

### ISSUE THREAD

**Issue by hongshengzhang** [CESNET/netopeer2#410]
Hi
   I have a question, is there any developing document  or architecture document for netopeer2? I don't kown how can I porting netopeer2 to a deveice for management, for example, add new yang module or new feature support for the deveice?

**Comment by michalvasko** [comment]
Hi,
I guess [this](http://www.sysrepo.org/static/doc/html/index.html) page can be helpful.

Regards,
Michal

**Comment by hongshengzhang** [comment]
Hi michalvasko：
    Your refered page is sysrepo document, not for netopeer2, Is there any document about netopeer2? However,  If you means that if I need add new yang module or other feature into netopeer2, I need add it into sysrepo and fllow sysrepo rule?

**Comment by michalvasko** [comment]
Hi,
yeah, if you look at the architecture image in the page I referenced, it should be clear that *netopeer2* does not handle YANG modules or data, this is performed by *sysrepo* and *netopeer2* just communicates with it.

Regards,
Michal
