### ISSUE TITLE
Can't edit-config yang model added to netopeer2 server

### ISSUE THREAD

**Issue by LilyCuili** [CESNET/Netopeer2#411]
Hi,
I added a yang model to netopeer server by below operation:
```
sysrepoctl --install --yang=/opt/dev/sysrepo/yang/secom-equipment@2018-10-30.yang
```

and then I log in netopeer2 cli to do edit config:
```
> edit-config --target running --config=/home/netconf/config_loid.xml
ERROR
	type:     protocol
	tag:      unknown-element
	severity: error
	message:  Unknown element "managed-element".
	bad-elem #1: /secom-equipment:managed-element
```
this is my config_loid.xml
```xml
<managed-element xmlns="http://www.secom.com/netconf/common/secom-equipment">
<name>secom</name>
		            <product-name>iEdge8000</product-name>
			          <product-type>VCPE</product-type>
				   <loid>netopeerdocker1</loid>
</managed-element>
```

this message can work well when config it to another kind of netconf server,so it not the rpc message issue.
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<rpc message-id="1" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<edit-config>
    <target>
      <running/>
    </target>
<config>    
<managed-element xmlns="http://www.secom.com/netconf/common/secom-equipment">
		      <name>secom</name>
		            <product-name>iEdge8000</product-name>
			          <product-type>VCPE</product-type>
				        <loid>netopeerdocker1</loid>
</managed-element>
 </config>
</edit-config>
</rpc>
]]>]]>
```
I want to know if there is other step should I do to make the yang model can be operated.

Thanks

**Comment by LilyCuili** [comment]
Can you see the config_loid.xml,some special character can't be shown after submitting?

I want to know if the operation is suffiet "sysrepoctl --install --yang=/opt/dev/sysrepo/yang/secom-equipment@2018-10-30.yang" to register the yang model to netopeer server,is there any other steps should be done?

**Comment by michalvasko** [comment]
Hi,
there could be a number of problems here, but no, in general it is enough to install the module. However, to actually work with the `running` data you also need to subscribe to the module but if that was the problem, you would get another kind of error.

I could not find the YANG module you are using so my guess is that it is not public, Without that I cannot check whether the element really exists and should be known. Other than that, you could look at `# sysrepoctl -l` output and you should see your module there. That means it is installed correctly.

Regards,
Michal

**Comment by LilyCuili** [comment]
from sysrepoctl -l output I can see my module there,how to  to subscribe to the module, 
 like this?

examples/application_example ietf-interfaces

**Comment by LilyCuili** [comment]
root@bdaf47050caa:/opt/dev/sysrepo/build/examples# ./application_example raisecom-equipment


 ========== READING STARTUP CONFIG raisecom-equipment: ==========

Error by sr_get_items: Item not found


 ========== STARTUP CONFIG raisecom-equipment APPLIED AS RUNNING ==========

**Comment by michalvasko** [comment]
Hi,
yes, you can use `application_example <module-name>` to subscribe to a module. However, like I said, this is not the problem you are facing. Could you maybe send me the model privately to mvasko@cesnet.cz? Then I may be able to help you.

Regards,
Michal

**Comment by LilyCuili** [comment]
thank you Michal,I have sent it to you.

**Comment by LilyCuili** [comment]
by the way,Could you please give me a hello message for netopeer2?

**Comment by michalvasko** [comment]
Hi,
okay, the problem is that your top-level `managed-element` container is a **state** node (`config` value `false`). You cannot simply set such configuration, it is always expected to be provided by the application to be up-to-date (using a callback set by [sr_dp_get_items_subscribe()](http://www.sysrepo.org/static/doc/html/group__cl.html#ga9e68dfe535ddabfebe056b43047ad7e8)). This [page](http://www.sysrepo.org/static/doc/html/subscribtions.html#data_providers) may also be useful.

Regards,
Michal

**Comment by michalvasko** [comment]
> by the way,Could you please give me a hello message for netopeer2?

Are you not using *netopeer2-cli* (or perhaps some other NETCONF client)? There is no reason to write the messages yourself.

Regards,
Michal

**Comment by LilyCuili** [comment]
Hi Michal,
In fact I have changed the top container to config true when I register the yang model,but it still  the same error output,so I ask you for help.

> edit-config --target running --config=/home/netconf/config_loid.xml
ERROR
	type:     protocol
	tag:      unknown-element
	severity: error
	message:  Unknown element "managed-element".
	bad-elem #1: /raisecom-equipment:managed-element


    container managed-element {
        config true;
        description "managed element info.";
        uses managed-element-entry;
        container rack {

**Comment by LilyCuili** [comment]
Hi Michal,
I reboot /usr/local/bin/sysrepod -d after registered yang model and subscribe examples/application_example ietf-interfaces
now it works well.

Should reboot sysrepod be necessary?

**Comment by michalvasko** [comment]
Hi,
for one, you need to start a new NETCONF session after module installation because capabilities of an existing one cannot change. Other than that, it should work right after installing it.

Regards,
Michal

**Comment by LilyCuili** [comment]
Thanks Michal.
