### ISSUE TITLE
A question about netopeer docker ssh host key

### ISSUE THREAD

**Issue by LilyCuili** [CESNET/Netopeer2#413]
Hi,
I use netopeer2 docker to connect odl as call home mode.
now I find all the dockers I created have the same ssh host key as below.
I want to change each docker as different one.
Could you please tell how to do it?

root@bdaf47050caa:/usr/local/etc/keystored/keys# cat ssh_host_rsa_key.pem.pub 
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGUwg9ZywQgvgsA17m+FuVOooEK1kkKeqWOxzrbkMNw5Kx8VUDqmXQJeSt41CyZiTgXy5KdXu28nPxxXpXnde4/z1oWdNx0nggCDjYwEcfzvfRzNdzRahZUmrHfjTg1MGjMNokPJ2qeyVjY9tuqv2AQiGlIAY1fS4BotAvk1oCkL8Lrprxqjh9sb09HDyo7+TxnL/EsLAYFwreVyl7yIFMYCTV0+/2k+vXuyZ07urLbXeg968caFVoOHuHmD5hv65dcDjalqXcovvFudJ/ZyyshsdK6DEP7tTfCaaE/bKDOz3gohD1OUErDTg7iKh8cPuDDHnlNa99jgSLTgRS/DGf root@280467fb61a3

**Comment by michalvasko** [comment]
Hi,
it should not be too hard to generate a new SSH key using `ssh-keygen(1)` to replace the old one.

Regards,
Michal

**Comment by LilyCuili** [comment]
I know how to generate a new SSH key,but after I generate, the netopeer2 docker still use the key in this file root@bdaf47050caa:/usr/local/etc/keystored/keys/ssh_host_rsa_key.pem.pub  to connect client .
I don't know how to change it.

**Comment by michalvasko** [comment]
Hi,
I may be missing something but if you change this key in the running docker, it should use the new key, right?

Regards,
Michal

**Comment by LilyCuili** [comment]
remove ssh_host_rsa_key.pem，ssh_host_rsa_key.pem.pub  and generate new one copy to this folder can resolve this issue.
