### ISSUE TITLE
Netopeer2 server does not receive client login 

### ISSUE THREAD

**Issue by dwdrajesh** [CESNET/netopeer2#414]
Hi,

I am trying to setup a netopeer2 server-client connection on my local machine using password from the following command on the cli: connect --host localhost . This , I believe, should try to login using the current user's username (unless I run sudo, which I am not ). I understand that logging in with 'root' user is not allowed as per linux policy but if I am not sudo, this should be possible right?
However ,the cli prints a connection refused message while on the server side, I do not see any message received even though I have enabled all log levels. 
I wanted to understand how to debug these connection issues and where the username//password combinations are stored? Aren't these stored in ietf-netconf-server yang data files?
Please find the attached logs:

netopeer2-cli log:
ezdawra@elx62302135:~/xran/sysrepo/examples$  netopeer2-cli
> connect --host localhost
nc ERROR: Unable to connect to localhost:830 (Connection refused).
cmd_connect: Connecting to the localhost:830 as user "ezdawra" failed.
> 

netopeer2-server:
ezdawra@elx62302135:~/xran/oran_Spec/ORAN-WG4.MP-YANGs-v01.00$ **sudo netopeer2-server -d -v3** 
[INF]: Connected to daemon Sysrepo Engine at socket=/var/run/sysrepod.sock
[INF]: Netopeer2 connected to sysrepod.
[INF]: Plugin "/usr/local/lib/libyang/extensions/metadata.so" successfully loaded.
[INF]: Plugin "/usr/local/lib/libyang/extensions/nacm.so" successfully loaded.
[INF]: Plugin "/usr/local/lib/libyang/extensions/libyang_ext_test.so" successfully loaded.
[INF]: Plugin "/usr/local/lib/libyang/extensions/yangdata.so" successfully loaded.
[INF]: Plugin "/usr/local/lib/libyang/user_types/user_date_and_time.so" successfully loaded.
[INF]: Reading module "ietf-yang-metadata".
[INF]: Module "ietf-yang-metadata@2016-08-05" successfully parsed as implemented.
[INF]: Reading module "yang".
[INF]: Resolving "yang" unresolved schema nodes and their constraints...
[INF]: All "yang" schema nodes and constraints resolved.
[INF]: Module "yang@2017-02-20" successfully parsed as implemented.
[INF]: Reading module "ietf-inet-types".
[INF]: Resolving derived type "union" failed, it will be attempted later.
[INF]: Resolving derived type "union" failed, it will be attempted later.
[INF]: Resolving derived type "union" failed, it will be attempted later.
[INF]: Resolving derived type "union" failed, it will be attempted later.
[INF]: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
[INF]: All "ietf-inet-types" schema nodes and constraints resolved.
[INF]: Module "ietf-inet-types@2013-07-15" successfully parsed as implemented.
[INF]: Reading module "ietf-yang-types".
[INF]: Module "ietf-yang-types@2013-07-15" successfully parsed as implemented.
[INF]: Reading module "ietf-datastores".
[INF]: Module "ietf-datastores@2017-08-17" successfully parsed as implemented.
[INF]: Reading module "ietf-yang-library".
[INF]: Module "ietf-yang-library@2018-01-17" successfully parsed as implemented.
[INF]: Loading schema "ietf-netconf-notifications@2012-02-06" from sysrepo.
[INF]: Reading module "ietf-netconf-notifications".
[INF]: Reading module "ietf-netconf".
[INF]: Reading module "ietf-netconf-acm".
[INF]: Module "ietf-netconf-acm@2018-02-14" successfully parsed as imported.
[INF]: Module "ietf-netconf@2011-06-01" successfully parsed as imported.
[INF]: Resolving "ietf-netconf-notifications" unresolved schema nodes and their constraints...
[INF]: All "ietf-netconf-notifications" schema nodes and constraints resolved.
[INF]: Module "ietf-netconf-notifications@2012-02-06" successfully parsed as implemented.
[INF]: Loading schema "ietf-netconf@2011-06-01" from sysrepo.
[INF]: Module ietf-netconf@2011-06-01 already present in context.
[INF]: Module "ietf-netconf@2011-06-01" now implemented.
[INF]: Loading schema "ietf-netconf-acm@2018-02-14" from sysrepo.
[INF]: Module ietf-netconf-acm@2018-02-14 already present in context.
[INF]: Loading schema "nc-notifications@2008-07-14" from sysrepo.
[INF]: Reading module "nc-notifications".
[INF]: Reading module "notifications".
[INF]: Module "notifications@2008-07-14" successfully parsed as imported.
[INF]: Module "nc-notifications@2008-07-14" successfully parsed as implemented.
[INF]: Loading schema "notifications@2008-07-14" from sysrepo.
[INF]: Module notifications@2008-07-14 already present in context.
[INF]: Module "notifications@2008-07-14" now implemented.
[INF]: Loading schema "turing-machine@2013-12-27" from sysrepo.
[INF]: Reading module "turing-machine".
[INF]: Module "turing-machine@2013-12-27" successfully parsed as implemented.
[INF]: Loading schema "xran-uplane-conf@2018-07-20" from sysrepo.
[INF]: Reading module "xran-uplane-conf".
[INF]: Resolving "xran-uplane-conf" unresolved schema nodes and their constraints...
[INF]: All "xran-uplane-conf" schema nodes and constraints resolved.
[INF]: Module "xran-uplane-conf@2018-07-20" successfully parsed as implemented.
[INF]: Loading schema "ietf-x509-cert-to-name@2014-12-10" from sysrepo.
[INF]: Reading module "ietf-x509-cert-to-name".
[INF]: Module "ietf-x509-cert-to-name@2014-12-10" successfully parsed as implemented.
[INF]: Loading schema "ietf-keystore@2016-10-31" from sysrepo.
[INF]: Reading module "ietf-keystore".
[INF]: Module "ietf-keystore@2016-10-31" successfully parsed as implemented.
[INF]: Loading schema "ietf-netconf-with-defaults@2011-06-01" from sysrepo.
[INF]: Reading module "ietf-netconf-with-defaults".
[INF]: Module "ietf-netconf-with-defaults@2011-06-01" successfully parsed as implemented.
[INF]: Loading schema "ietf-netconf-monitoring@2010-10-04" from sysrepo.
[INF]: Reading module "ietf-netconf-monitoring".
[INF]: Module "ietf-netconf-monitoring@2010-10-04" successfully parsed as implemented.
[INF]: Loading schema "ietf-yang-library@2018-01-17" from sysrepo.
[INF]: Module ietf-yang-library@2018-01-17 already present in context.
[INF]: Loading schema "ietf-datastores@2017-08-17" from sysrepo.
[INF]: Module ietf-datastores@2017-08-17 already present in context.
[INF]: Loading schema "ietf-netconf-server@2016-11-02" from sysrepo.
[INF]: Reading module "ietf-netconf-server".
[INF]: Reading module "ietf-x509-cert-to-name".
[INF]: Module "ietf-x509-cert-to-name@2014-12-10" already in context.
[INF]: Module "ietf-x509-cert-to-name@2014-12-10" successfully parsed as implemented.
[INF]: Reading module "ietf-ssh-server".
[INF]: Reading module "ietf-keystore".
[INF]: Module "ietf-keystore@2016-10-31" already in context.
[INF]: Module "ietf-keystore@2016-10-31" successfully parsed as implemented.
[INF]: Module "ietf-ssh-server@2016-11-02" successfully parsed as imported.
[INF]: Reading module "ietf-tls-server".
[INF]: Module "ietf-tls-server@2016-11-02" successfully parsed as imported.
[INF]: Resolving "ietf-netconf-server" unresolved schema nodes and their constraints...
[INF]: All "ietf-netconf-server" schema nodes and constraints resolved.
[INF]: Module "ietf-netconf-server@2016-11-02" successfully parsed as implemented.
[INF]: Loading schema "ietf-ssh-server@2016-11-02" from sysrepo.
[INF]: Module ietf-ssh-server@2016-11-02 already present in context.
[INF]: Loading schema "ietf-tls-server@2016-11-02" from sysrepo.
[INF]: Module ietf-tls-server@2016-11-02 already present in context.
[INF]: Loading schema "ietf-system@2014-08-06" from sysrepo.
[INF]: Reading module "ietf-system".
[INF]: Reading module "iana-crypt-hash".
[INF]: Module "iana-crypt-hash@2014-08-06" successfully parsed as imported.
[INF]: Resolving "ietf-system" unresolved schema nodes and their constraints...
[INF]: All "ietf-system" schema nodes and constraints resolved.
[INF]: Module "ietf-system@2014-08-06" successfully parsed as implemented.
[INF]: Loading schema "iana-crypt-hash@2014-08-06" from sysrepo.
[INF]: Module iana-crypt-hash@2014-08-06 already present in context.
[INF]: Loading schema "ietf-interfaces@2018-02-20" from sysrepo.
[INF]: Reading module "ietf-interfaces".
[INF]: Module "ietf-interfaces@2018-02-20" successfully parsed as implemented.
[INF]: Loading schema "ietf-ip@2018-02-22" from sysrepo.
[INF]: Reading module "ietf-ip".
[INF]: Reading module "ietf-interfaces".
[INF]: Module "ietf-interfaces@2018-02-20" already in context.
[INF]: Module "ietf-interfaces@2018-02-20" successfully parsed as implemented.
[INF]: Module "ietf-ip@2018-02-22" successfully parsed as implemented.
[INF]: Loading schema "o-ran-interfaces@2019-02-04" from sysrepo.
[INF]: Reading module "o-ran-interfaces".
[INF]: Reading module "iana-if-type".
[INF]: Module "iana-if-type@2017-01-19" successfully parsed as imported.
[INF]: Reading module "ietf-ip".
[INF]: Module "ietf-ip@2018-02-22" already in context.
[INF]: Module "ietf-ip@2018-02-22" successfully parsed as implemented.
[INF]: Reading module "ietf-hardware".
[INF]: Reading module "iana-hardware".
[INF]: Module "iana-hardware@2018-03-13" successfully parsed as imported.
[INF]: Resolving "ietf-hardware" unresolved schema nodes and their constraints...
[INF]: All "ietf-hardware" schema nodes and constraints resolved.
[INF]: Module "ietf-hardware@2018-03-13" successfully parsed as imported.
[INF]: Resolving "o-ran-interfaces" unresolved schema nodes and their constraints...
[WRN]: Identity found, but in a non-implemented module "iana-if-type".
[WRN]: Failed to resolve identityref "iana-if-type:ethernetCsmacd". (/ietf-interfaces:type)
[WRN]: Previous warning generated by XPath subexpression[0] "ietf-interfaces:type = 'iana-if-type:ethernetCsmacd'".
[WRN]: Identity found, but in a non-implemented module "iana-if-type".
[WRN]: Failed to resolve identityref "iana-if-type:l2vlan". (/ietf-interfaces:type)
[WRN]: Previous warning generated by XPath subexpression[0] "ietf-interfaces:type = 'iana-if-type:l2vlan'".
[WRN]: Schema node "ietf-hardware:class" not found (derived-from-or-self(deref(current())/../ietf-hardware:class) with context node "/ietf-interfaces:interfaces/ietf-interfaces:interface/port-reference/port-name".
[WRN]: Argument #1 of xpath_derived_from_or_self not a node-set as expected.
[WRN]: Previous warning generated by XPath function "derived-from-or-self(deref(current())/../ietf-hardware:class, 'iana-hardware:port')".
[WRN]: Identity found, but in a non-implemented module "iana-if-type".
[WRN]: Failed to resolve identityref "iana-if-type:ethernetCsmacd". (/ietf-interfaces:type)
[WRN]: Previous warning generated by XPath subexpression[1] "ietf-interfaces:type = 'iana-if-type:ethernetCsmacd'".
[WRN]: Identity found, but in a non-implemented module "iana-if-type".
[WRN]: Failed to resolve identityref "iana-if-type:l2vlan". (/ietf-interfaces:type)
[WRN]: Previous warning generated by XPath subexpression[59] "ietf-interfaces:type = 'iana-if-type:l2vlan'".
[INF]: All "o-ran-interfaces" schema nodes and constraints resolved.
[INF]: Module "o-ran-interfaces@2019-02-04" successfully parsed as implemented.
[INF]: Loading schema "iana-if-type@2017-01-19" from sysrepo.
[INF]: Module iana-if-type@2017-01-19 already present in context.
[INF]: Loading schema "ietf-hardware@2018-03-13" from sysrepo.
[INF]: Module ietf-hardware@2018-03-13 already present in context.
[INF]: Loading schema "iana-hardware@2018-03-13" from sysrepo.
[INF]: Module iana-hardware@2018-03-13 already present in context.
[INF]: Loading schema "o-ran-uplane-conf@2019-02-04" from sysrepo.
[INF]: Reading module "o-ran-uplane-conf".
[INF]: Reading module "o-ran-processing-element".
[INF]: Reading module "o-ran-interfaces".
[INF]: Module "o-ran-interfaces@2019-02-04" already in context.
[INF]: Module "o-ran-interfaces@2019-02-04" successfully parsed as implemented.
[INF]: Resolving "o-ran-processing-element" unresolved schema nodes and their constraints...
[INF]: All "o-ran-processing-element" schema nodes and constraints resolved.
[INF]: Module "o-ran-processing-element@2019-02-04" successfully parsed as imported.
[INF]: Reading module "o-ran-laa".
[INF]: Reading module "o-ran-module-cap".
[INF]: Reading module "o-ran-compression-factors".
[INF]: Module "o-ran-compression-factors@2019-02-04" successfully parsed as imported.
[INF]: Resolving "o-ran-module-cap" unresolved schema nodes and their constraints...
[INF]: All "o-ran-module-cap" schema nodes and constraints resolved.
[INF]: Module "o-ran-module-cap@2019-02-04" successfully parsed as imported.
[INF]: Resolving "o-ran-laa" unresolved schema nodes and their constraints...
[WRN]: Schema node "o-ran-module-cap:module-capability" not found (number-of-laa-scarriers <= /o-ran-module-cap:module-capability) with context node "/o-ran-laa:laa-config".
[WRN]: Schema node "o-ran-module-cap:band-capabilities" not found (number-of-laa-scarriers <= /o-ran-module-cap:module-capability/o-ran-module-cap:band-capabilities) with context node "/o-ran-laa:laa-config".
[WRN]: Schema node "o-ran-module-cap:sub-band-info" not found (number-of-laa-scarriers <= /o-ran-module-cap:module-capability/o-ran-module-cap:band-capabilities[o-ran-module-cap:band-number = '46']/o-ran-module-cap:sub-band-info) with context node "/o-ran-laa:laa-config".
[WRN]: Schema node "o-ran-module-cap:number-of-laa-scarriers" not found (number-of-laa-scarriers <= /o-ran-module-cap:module-capability/o-ran-module-cap:band-capabilities[o-ran-module-cap:band-number = '46']/o-ran-module-cap:sub-band-info/o-ran-module-cap:number-of-laa-scarriers) with context node "/o-ran-laa:laa-config".
[INF]: All "o-ran-laa" schema nodes and constraints resolved.
[INF]: Module "o-ran-laa@2019-02-04" successfully parsed as imported.
[ERR]: The leafref leaf is config but refers to a non-config leaf. (/o-ran-uplane-conf:user-plane-configuration/low-level-tx-endpoints/name)
[ERR]: Module "o-ran-uplane-conf" parsing failed.
[WRN]: Getting o-ran-uplane-conf@2019-02-04 schema from sysrepo failed, data from this module won't be available.
[INF]: Loading schema "o-ran-processing-element@2019-02-04" from sysrepo.
[INF]: Module o-ran-processing-element@2019-02-04 already present in context.
[INF]: Loading schema "o-ran-laa@2019-02-04" from sysrepo.
[INF]: Module o-ran-laa@2019-02-04 already present in context.
[INF]: Loading schema "o-ran-module-cap@2019-02-04" from sysrepo.
[INF]: Module o-ran-module-cap@2019-02-04 already present in context.
[INF]: Module "o-ran-module-cap@2019-02-04" now implemented.
[INF]: Loading schema "o-ran-compression-factors@2019-02-04" from sysrepo.
[INF]: Module o-ran-compression-factors@2019-02-04 already present in context.
[INF]: Path "/ietf-system:system/authentication/user[name='ezdawra']/authorized-key[name='ezdawra-key-name']/name" created.
[INF]: Path "/ietf-system:system/authentication/user[name='ezdawra']/authorized-key[name='ezdawra-key-name']/algorithm" created.
[INF]: Path "/ietf-system:system/authentication/user[name='ezdawra']/authorized-key[name='ezdawra-key-name']/key-data" created.

**Comment by michalvasko** [comment]
Hi,
firstly, your understanding of users is mostly correct except all the information is loaded form the system so if you have it configured that you can log in with `root`, you will also be able to use it for NETCONF sessions.

The reason you cannot connect has nothing to do with users (the errors would be different). Refused connection means that there is no one listening on the particular address/port you are connecting to. That is correct if you look at the last output of *netopeer2-server*, it has only configuration for authorized SSH keys, not for any endpoints. You have the module installed (`ietf-netconf-server`) so all you need to do is to configure it properly. You should have had the default configuration installed (`netopeer2/server/stock_config.xml`) but maybe you accidentally deleted it. In any case, if you write it into the datastore (using `sysrepocfg --datastore=startup --merge=<path-to-stock_config.xml> --format=xml ietf-netconf-server`, for example), you should be able to connect.

Regards,
Michal

**Comment by fushion2018** [comment]
how  to import the ORAN model to netopeer2？

**Comment by michalvasko** [comment]
Hi,
import it to *sysrepo*. Using `sysrepoctl -i`, for example.

Regards,
Michal

**Comment by fushion2018** [comment]
thks，i will give it a try.

**Comment by Aaru47527** [comment]
**Issue Description:**

I am experiencing issues with starting the Netopeer2 server on my system. The service fails to start and provides the following status:

sudo systemctl status netopeer2-server.service
[sudo] password for user: 
● netopeer2-server.service - Netopeer2 Server
     Loaded: loaded (/etc/systemd/system/netopeer2-server.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2024-07-17 09:18:21 IST; 57min ago
   Main PID: 923 (code=exited, status=127)

Jul 17 09:18:21 13266--SW--MCP7 systemd[1]: netopeer2-server.service: Scheduled restart job, restart counter is at 5.
Jul 17 09:18:21 13266--SW--MCP7 systemd[1]: Stopped Netopeer2 Server.
Jul 17 09:18:21 13266--SW--MCP7 systemd[1]: netopeer2-server.service: Start request repeated too quickly.
Jul 17 09:18:21 13266--SW--MCP7 systemd[1]: netopeer2-server.service: Failed with result 'exit-code'.
Jul 17 09:18:21 13266--SW--MCP7 systemd[1]: Failed to start Netopeer2 Server.
13266--SW--MCP7:~$ 

**When I attempt to start the server manually with debugging enabled, I encounter the following errors:**

13266--SW--MCP7:~$ sudo netopeer2-server -d -v3
[ERR]: SR: JSON DS file: Opening "/dev/shm/sr_ietf-netconf-acm.running" failed (File exists).
[ERR]: NP: Connecting to sysrepo failed (System function call failed).
[ERR]: NP: Server init failed.
[INF]: NP: Server terminated.
Segmentation fault
**Request for Assistance:**

Any insights into the cause of the segmentation fault?
Recommendations for resolving the sysrepo connection issue?
Potential steps to debug and fix the file permission error in /dev/shm?

**Comment by michalvasko** [comment]
Firstly, you have some leftover files from some previous installation or something like that, should be fixed by running `make shm_clean` in *sysrepo* `build` or simply restarting the machine. Then, you are using a really old *sysrepo* version so my suggestion would be to update to the latest release.
