### ISSUE TITLE
How to change call home connect duration?

### ISSUE THREAD

**Issue by LilyCuili** [CESNET/Netopeer2#415]
now when call home connect fail it will reconnect using diffrent source port per second.
how to change the time value?

**Comment by michalvasko** [comment]
Hi,
all the available options can be found in the module `ietf-netconf-server` and [this](https://github.com/CESNET/Netopeer2/blob/master/modules/ietf-netconf-server.yang#L369) is probably the option you are looking for.

Regards,
Michal

**Comment by LilyCuili** [comment]
Hi,
I configure as below,set reconnect_timeout as 60,but when call home connect failed for the first time,it will reconnect once per second.I expect its reconnetion period is 60 s. Is it coded in the source code?
Can I configure it?
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <call-home>
    <netconf-client>
      <name>main</name>
      <ssh>
        <endpoints>
          <endpoint>
            <name>endpt_name</name>
            <address>$1</address>
			<port>6666</port>
          </endpoint>
        </endpoints>
        <host-keys>
          <host-key>
            <name>rsa_key</name>
            <public-key>ssh_host_rsa_key</public-key>
          </host-key>
        </host-keys>
      </ssh>
      <connection-type>
		<periodic>
		<reconnect_timeout>60</reconnect_timeout>
		</periodic>
      </connection-type>
    </netconf-client>
  </call-home>
</netconf-server>

**Comment by michalvasko** [comment]
Hi,
I have just tested it and it behaved as I expected. I have configured the Call Home and the *server* immediately tried to connect, trying it once per second. After it connected, I terminated the session in the client. Then, the server was correctly waiting 60 minutes before trying to connect again. Have you observed different behavior? Do you think this is not the correct behavior?

Regards,
Michal

**Comment by LilyCuili** [comment]
Yes，I know the behavior.
now when the netopeer2 server connect to client failed, it will connect once per second.  I want to change the duration.Where can I change the time ? I want when connect fail,it send the connect packets after 60 seconds.
Could you please help about it?


Thanks

**Comment by michalvasko** [comment]
Hi,
I think there is misunderstanding of what the `reconnect_timeout` means. In my understanding, it is the time waited before a Call Home client reconnect attempt is made after a session was terminated. It is not the time period between trying to connect to endpoints of a Call Home client.

When you configure Call Home, it is assumed you immediately want to connect. After you do and the session is terminated, for periodic connection it is first slept for the `reconnect_timeout` value after it tries to connect again. Now, what I mean by *to connect* is to iterate through all the endpoints of a client using round-robin until a connection is made. The timeout between each of these attempts is implementation-specific (unless you can point me to a text mentioning it somewhere). So, *libnetconf2* defines this value in `session_p.h:331`, the macro `NC_CH_ENDPT_FAIL_WAIT`. So, if you really want to change this value, you have to modify it there and recompile *libnetconf2*.

Regards,
Michal

**Comment by LilyCuili** [comment]
Thanks a lot for so quick response,I got it.
I will have a try.

**Comment by LilyCuili** [comment]
Hi,it works well after change NC_CH_ENDPT_FAIL_WAIT.
Thanks for the help.
