### ISSUE TITLE
we should better throw the error msg of  sysrepo to the client, when commit data failed .

### ISSUE THREAD

**Issue by ostack** [CESNET/Netopeer2#42]
we should better throw the error msg of  sysrepo to the client rather than a msg  ourselves define when commit data failed .as we know the more clear of the error msg the better for the client to modify the errors.

**Comment by ZhaoGuangYue** [comment]
#

**Comment by rkrejci** [comment]
can you be more specific? From your description I don't know what you suggest to change.
