### ISSUE TITLE
Where I can find netopeer2  documentation?

### ISSUE THREAD

**Issue by Akijdarvajkar** [CESNET/Netopeer2#423]
Where I can find netopeer2  documentation?

**Comment by michalvasko** [comment]
Hi,
it is mentioned in the [sysrepo docs](http://www.sysrepo.org/static/doc/html/index.html) but, unfortunately, does not have its own documentation. However, there is not much to document from the user point-of-view, it is a NETCONF server and it behaves as a [NETCONF server should](https://tools.ietf.org/html/rfc6241).

Regards,
Michal

**Comment by Akijdarvajkar** [comment]
Thanks
