### ISSUE TITLE
Disable call home feature is not working 

### ISSUE THREAD

**Issue by Akijdarvajkar** [CESNET/Netopeer2#425]
steps to reproduce the issue.
1.Enable the call home 

sysrepoctl -l
Sysrepo schema directory: /etc/sysrepo/yang/
Sysrepo data directory:   /etc/sysrepo/data/
(Do not alter contents of these directories manually)

Module Name                | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
ietf-netconf-notifications | 2012-02-06 | Installed   | root:root           | 666         |                               |
ietf-netconf               | 2011-06-01 | Installed   | root:root           | 666         |                               | writable-running candidate rollback-on-error validate startup xpath
ietf-netconf-acm           | 2018-02-14 | Imported    |                     |             |                               |
nc-notifications           | 2008-07-14 | Installed   | root:root           | 666         |                               |
notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
turing-machine             | 2013-12-27 | Installed   | root:root           | 666         |                               |
iana-if-type               | 2014-05-08 | Installed   |                     |             |                               |
ietf-interfaces            | 2014-05-08 | Installed   | root:root           | 666         |                               |
ietf-ip                    | 2014-06-16 | Installed   |                     |             |                               |
ietf-x509-cert-to-name     | 2014-12-10 | Installed   |                     |             |                               |
ietf-keystore              | 2016-10-31 | Installed   | root:root           | 666         |                               |
ietf-netconf-with-defaults | 2011-06-01 | Installed   |                     |             |                               |
ietf-netconf-monitoring    | 2010-10-04 | Installed   | root:root           | 666         |                               |
ietf-yang-library          | 2018-01-17 | Installed   | root:root           | 666         |                               |
ietf-datastores            | 2017-08-17 | Imported    |                     |             |                               |
ietf-netconf-server        | 2016-11-02 | Installed   | root:root           | 666         |                               | call-home ssh-call-home listen ssh-listen
ietf-ssh-server            | 2016-11-02 | Imported    |                     |             |                               |
ietf-tls-server            | 2016-11-02 | Imported    |                     |             |                               |
ietf-system                | 2014-08-06 | Installed   | root:root           | 666         |                               | authentication local-users
iana-crypt-hash            | 2014-08-06 | Imported    |                     |             |                               |

2.. sysrepocfg --merge= ssh_callhome.xml --format=xml --datastore=startup ietf-netconf-server

<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <call-home>
    <netconf-client>
      <name>test_ssh_ch_client</name>
      <ssh>
        <endpoints>
          <endpoint>
            <name>test_ssh_ch_endpt</name>
            <address>127.0.0.1</address>
            <port>4334</port>
          </endpoint>
        </endpoints>
        <host-keys>
          <host-key>
            <name>test_ssh_callhome_key</name>
            <public-key>ssh_host_rsa_key</public-key>
          </host-key>
        </host-keys>
      </ssh>
      <connection-type>
              <persistent>
                      <idle-timeout>280</idle-timeout>
                      <keep-alives>
                              <max-wait>30</max-wait>
                              <max-attempts>3</max-attempts>
                      </keep-alives>
              </persistent>
      </connection-type>
      <reconnect-strategy>
              <max-attempts>4</max-attempts>
              <start-with>last-connected</start-with>
      </reconnect-strategy>
    </netconf-client>
  </call-home>
</netconf-server>

4.Test the call home using cli
root@4192e7524fc0:/# netopeer2-cli
> listen
Waiting 60s for an SSH Call Home connection on port 4334...
The authenticity of the host '::ffff:127.0.0.1' cannot be established.
ssh-rsa key fingerprint is 14:c9:e0:b6:4f:77:a2:40:58:3d:cd:26:47:57:73:ef:fe:d5:22:c8.
Are you sure you want to continue connecting (yes/no)? yes
root@::ffff:127.0.0.1 password:
> get

5.Disable the call home 
sysrepoctl -l
Sysrepo schema directory: /etc/sysrepo/yang/
Sysrepo data directory:   /etc/sysrepo/data/
(Do not alter contents of these directories manually)

Module Name                | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
ietf-netconf-notifications | 2012-02-06 | Installed   | root:root           | 666         |                               |
ietf-netconf               | 2011-06-01 | Installed   | root:root           | 666         |                               | writable-running candidate rollback-on-error validate startup xpath
ietf-netconf-acm           | 2018-02-14 | Imported    |                     |             |                               |
nc-notifications           | 2008-07-14 | Installed   | root:root           | 666         |                               |
notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
turing-machine             | 2013-12-27 | Installed   | root:root           | 666         |                               |
iana-if-type               | 2014-05-08 | Installed   |                     |             |                               |
ietf-interfaces            | 2014-05-08 | Installed   | root:root           | 666         |                               |
ietf-ip                    | 2014-06-16 | Installed   |                     |             |                               |
ietf-x509-cert-to-name     | 2014-12-10 | Installed   |                     |             |                               |
ietf-keystore              | 2016-10-31 | Installed   | root:root           | 666         |                               |
ietf-netconf-with-defaults | 2011-06-01 | Installed   |                     |             |                               |
ietf-netconf-monitoring    | 2010-10-04 | Installed   | root:root           | 666         |                               |
ietf-yang-library          | 2018-01-17 | Installed   | root:root           | 666         |                               |
ietf-datastores            | 2017-08-17 | Imported    |                     |             |                               |
ietf-netconf-server        | 2016-11-02 | Installed   | root:root           | 666         |                               |
ietf-ssh-server            | 2016-11-02 | Imported    |                     |             |                               |
ietf-tls-server            | 2016-11-02 | Imported    |                     |             |                               |
ietf-system                | 2014-08-06 | Installed   | root:root           | 666         |                               | authentication local-users
iana-crypt-hash            | 2014-08-06 | Imported    |                     |             |                               |

4.Test the call home using cli
root@4192e7524fc0:/# netopeer2-cli
> listen
Waiting 60s for an SSH Call Home connection on port 4334...
The authenticity of the host '::ffff:127.0.0.1' cannot be established.
ssh-rsa key fingerprint is 14:c9:e0:b6:4f:77:a2:40:58:3d:cd:26:47:57:73:ef:fe:d5:22:c8.
Are you sure you want to continue connecting (yes/no)? yes
root@::ffff:127.0.0.1 password:

**Comment by michalvasko** [comment]
Hi,
if you want it to work correctly, you should first delete Call Home configuration and then disable the feature, it is unfortunately not performed otherwise. I do not think this is such an inconvenience to be worth fixing, which would likely take considerable time, so it will stay this way, sorry.

Regards,
Michal

**Comment by Akijdarvajkar** [comment]
Hi,
How to delete call home config programmatically?

Thanks,
Akkij

**Comment by michalvasko** [comment]
Hi Akkij,
you can use
```
sysrepocfg -evim -fxml -dstartup ietf-netconf-server
```
and simply remove the configuration.

Regards,
Michal
