### ISSUE TITLE
Netconf get is not working when all feature of netconf-server is disabled

### ISSUE THREAD

**Issue by Akijdarvajkar** [CESNET/Netopeer2#426]
Hi,

Steps to reproduce the issue.
1.disabled the all the feature of netconf server module.
 sysrepoctl --feature-disable=call-home --module=ietf-netconf-server
 sysrepoctl --feature-disable=ssh-call-home --module=ietf-netconf-server
 sysrepoctl --feature-disable=tls-call-home --module=ietf-netconf-server
 sysrepoctl --feature-disable=listen  --module=ietf-netconf-server
 sysrepoctl --feature-disable=ssh-listen  --module=ietf-netconf-server
 sysrepoctl --feature-disable=tls-listen --module=ietf-netconf-server

 2.connect to netconf using netopeer-cli tool

root@ca578041a0e1:/opt/dev#  netopeer2-cli
> connect
Interactive SSH Authentication
Type your password:
Password:
> get
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  np2srv_sr_get_items_iter failed (sysrepo: Sysrepo-internal error).

> exit

Thanks,
Akkij

**Comment by Akijdarvajkar** [comment]
sysrepo logs :

[ERR] libyang error: Failed to find matching hash for a child of "netconf-server".
[ERR] Parsing data tree from file /etc/sysrepo/data/ietf-netconf-server.running failed: Failed to find matching hash for a child of "netconf-server".

2019-04-25 06:37:51,433 DEBG 'netopeer2-server' stdout output:
[ERR]: np2srv_sr_get_items_iter failed (sysrepo: Sysrepo-internal error).

2019-04-25 06:37:51,433 DEBG 'sysrepod' stdout output:
[ERR] Getting data tree for ietf-netconf-server failed.
[ERR] Getting data tree failed (4) for xpath '/ietf-netconf-server:*//.'
[ERR] rp_dt_prepare_data failed
[ERR] Get items failed for '/ietf-netconf-server:*//.', session id=515120996.

2019-04-25 06:38:16,649 DEBG 'sysrepod' stdout output:
[ERR] libyang error: Node already exists.
[WRN] Error by adding new notification entry /sysrepo-notification-store:notifications/notification[xpath='/ietf-netconf-notifications:netconf-capability-change'][generated-time='2019-04-25T06:38:16+00:00'][logged-time='998607044']: Node already exists..

2019-04-25 06:38:32,478 DEBG 'sysrepo-plugind' stdout output:
[ERR] File "/usr/local/etc/keystored/keys/ssh_host_rsa_key.pem.pub" is not a public key in PEM format.
[ERR] Memory allocation failed (Resource temporarily unavailable).

2019-04-25 06:38:32,496 DEBG 'sysrepod' stdout output:
[ERR] libyang error: Failed to find matching hash for a child of "endpoint".
[ERR] Parsing data tree from file /etc/sysrepo/data/ietf-netconf-server.running failed: Failed to find matching hash for a child of "endpoint".

2019-04-25 06:38:32,496 DEBG 'netopeer2-server' stdout output:
[ERR]: np2srv_sr_get_items_iter failed (sysrepo: Sysrepo-internal error).

2019-04-25 06:38:32,496 DEBG 'sysrepod' stdout output:
[ERR] Getting data tree for ietf-netconf-server failed.
[ERR] Getting data tree failed (4) for xpath '/ietf-netconf-server:*//.'
[ERR] rp_dt_prepare_data failed
[ERR] Get items failed for '/ietf-netconf-server:*//.', session id=614767245.

**Comment by michalvasko** [comment]
Hi,
this is the exact same problem as #425, I have nothing more to add.

Regards,
Michal
