### ISSUE TITLE
possible use of uninitialized variable in np2srv_sr_check_exec_permission()

### ISSUE THREAD

**Issue by olivier-matz-6wind** [CESNET/Netopeer2#428]
Hi,

While investigating another issue (which you already solved upstream ;) ), I've seen a potential issue in np2srv_sr_check_exec_permission():

```
int
np2srv_sr_check_exec_permission(sr_session_ctx_t *srs, const char *xpath, struct nc_server_reply **ereply)
{
    int rc = SR_ERR_DISCONNECT;
    struct nc_server_error *e;
    bool permitted;

    pthread_rwlock_rdlock(&sr_lock);

    if (!np2srv.disconnected) {
        rc = sr_check_exec_permission(srs, xpath, &permitted);
    }
```

Here, if rc != 0, *permitted is not set.
Also, rc can also be != SR_ERR_DISCONNECT.

```
    if (rc == SR_ERR_DISCONNECT) {
        // (...) not our case
        return np2srv_sr_check_exec_permission(srs, xpath, ereply);
    }

    // XXX the variable here may be unset. Maybe we should also check if rc == 0 ?
    if (!permitted) {
        rc = SR_ERR_UNAUTHORIZED;
    }
    if (rc != SR_ERR_OK) {
        if (ereply) {
            *ereply = op_build_err_sr(*ereply, srs, rc);
        } else {
            ERR("%s failed (sysrepo: %s).", __func__, sr_strerror(rc));
        }
    }

```
I don't think there is a big impact, I suppose it can just lead to loose the error value.

**Comment by michalvasko** [comment]
Hi,
it is a bit confusing but should work properly. If `(!np2srv.disconnected)` is true, then both `rc` and `permitted` are set and everything is fine. If `(!np2srv.disconnected)` is false, then `rc` does not change meaning it is `SR_ERR_DISCONNECT` and then the code will never get to the line where `permitted` is actually read.

Regards,
Michal

**Comment by olivier-matz-6wind** [comment]
But what happens if !np2srv.disconnected) is true, and sr_check_exec_permission() returns an error (for instance NOMEM)?
To me, it looks that permission is tested but not initialized.

**Comment by michalvasko** [comment]
Okay, that is true but I am not sure whether that is *netopeer2* or *sysrepo* problem. Anyway, should be fine now.

Regards,
Michal
