### ISSUE TITLE
cli timeout(1 second) is too short, can we make it configurable in netopeer2-cli?

### ISSUE THREAD

**Issue by fanchanghu** [CESNET/Netopeer2#43]

**Comment by michalvasko** [comment]
Hi,
it's not a problem to make it configurable, but first I want to make sure your problem is truly with the timeout being too short. Do you really see that `netopeer2-cli` waits for 1 seconds without getting a reply? Or is the error displayed immediately?

Regards,
Michal

**Comment by fanchanghu** [comment]
yes, I'm sure, when I changed it to 10 seconds, I can get OK reply. In fact, the config data I used is a little big(about 100k), so it timed out when executing 'copy-config'.

**Comment by michalvasko** [comment]
Hi,
this was actually an issue of libnetconf2 and now the timeout is 30s by default. You can change it by definig cmake variable `READ_TIMEOUT` with the desired amount of seconds.

Regards,
Michal

**Comment by fanchanghu** [comment]
Hi,
in fact , I just modify `cli_send_recv` in file `commands.c` in netopeer to resolve my problem, like this:
```
...
recv_reply:
    msgtype = nc_recv_reply(session, rpc, msgid, 1000*10,
                            LYD_OPT_DESTRUCT | LYD_OPT_NOSIBLINGS, &reply);
...
```
