### ISSUE TITLE
How to change the duration of tcp ack packets after call home connected ?

### ISSUE THREAD

**Issue by LilyCuili** [CESNET/netopeer2#433]
Hi,
now after call home connected, tcp ack packets are sent per 5 seconds,how to change the duration?

**Comment by michalvasko** [comment]
Hi,
I will assume you are talking about keep-alive TCP probes. You are, again, unable to change this run-time (yet), but can change it manually in [session.c](https://github.com/CESNET/libnetconf2/blob/master/src/session.c#L139).

Regards,
Michal

**Comment by michalvasko** [comment]
Can be changed now in the `ietf-netconf-server` configuration.
