### ISSUE TITLE
netopeer server crashing

### ISSUE THREAD

**Issue by yahovevo** [CESNET/netopeer2#434]
I want to share netopeer-server backtrace message. I can't find any clue from this crash message. Is there anyone meets this problem?

```
Communication SSH socket unexpectedly closed.
Communication SSH socket unexpectedly closed.
Communication SSH socket unexpectedly closed.
Communication SSH socket unexpectedly closed.
Session 1: failed to write reply.
Session 3: SSH channel poll error (Socket error: disconnected).
Session 4: SSH channel poll error (Socket error: disconnected).
Session 5: SSH channel poll error (Socket error: disconnected).
Session 3: Call Home thread failed to wake up in a timely manner, fatal synchronization problem.

Segmentation fault, backtrace: 3
STACK: Called by:
netopeer2-server(signal_handler+0x74) [0x105e8]
/lib/libc.so.6(__default_sa_restorer+0) [0x36839ed0]
/lib/libpthread.so.0(pthread_mutex_lock+0x8) [0x36f83778]
]
```
Current version
    netopeer server 0.5.31
    libnetconf2.so.0.11.48

Regards,
Boyong

**Comment by michalvasko** [comment]
Hi Boyong,
it seems the main problem is on the client side, it disconnects unexpectedly from the server. Anyway, you are using really old versions of both *libnetconf2* and *netopeer2*, so even if there was a problem in our applications, you would have to reproduce it with the current versions.

Regards,
Michal
