### ISSUE TITLE
NETCONF enterprise Roadmap: Confirmed-commit and others

### ISSUE THREAD

**Issue by chaitu-tk** [CESNET/netopeer2#435]
Hi, 

Is there any plan to add support for below NETCONF capabiities?

confirmed-commit: 1.1, 
rollback-on-error: 1.1 (1.0 is supported)
commit queus (proprietary feature, companies like Cisco/Juniper use it to make commit in a large network faster).

There are needed mainly for enterprise networks, are there any people/companies using Netopeer2 for enterprise deployements?

**Comment by michalvasko** [comment]
Hi,
`confirmed-commit` is planned to be supported with a relatively high priority once we have finished our current work (which there is a lot of).

I have not found any mention of `rollback-on-error:1.1` anywhere and I do not know what it is, can you provide more information?

Lastly, no proprietary features will be implemented in our tools unless there is a specific contract signed.

Regards,
Michal

**Comment by chaitu-tk** [comment]
Hi Michal, 

Thanks for the reply. I came across `rollback-on-error:1.1` across vendors listing, but there is no mention of it in the RFC.

I wasn't referring to implementing proprietary features per se, but more how do we solve the problem on commit's in a large network.

Also, do you know of any enteprise solutions based on Netopeer2/Sysrepo?
