### ISSUE TITLE
SSH key problems in Fedora 30 Server

### ISSUE THREAD

**Issue by psch-k** [CESNET/netopeer2#439]
Hi,
I tried to install netconf2 / sysrepo / netopeer2 and required dependencies on a freshly installed Fedora 30 virtual machine, using last updates as of 2019-06-25. It did not work out of the box. Starting sysrepod, sysrepo-plugind and netopeer-server startet sucessfully without error messages (loglevel=3), but connecting via netopeer2-cli didn't succeed.
netopeer2-cli says:
```
> connect
nc ERROR: Starting the SSH session failed (Socket error: Connection reset by peer).
cmd_connect: Connecting to the localhost:830 as user "devel" failed.
>

```
netopeer2-server says:

```
[INF]: Accepted a connection on 0.0.0.0:830.
[2019/06/26 16:52:17.027497, 2] ssh_pki_import_privkey_base64:  Trying to decode privkey passphrase=false
[2019/06/26 16:52:17.027718, 1] pki_private_key_from_base64:  Unknown or invalid private key.
[ERR]: Failed to set hostkey "ssh_host_rsa_key" (/etc/keystored/keys/ssh_host_rsa_key.pem).

```

Googling around resulted in the possibility to use '-m PKCS8' instead of '-m PEM' when generating the keys with ssh-keygen. I removed the keys in /etc/keystored/keys and generated new keys with '-m PKCS8'. As a result, I could connect to the netopeer2-server from netopeer2-cli, without anything showing any error.
That's good SO FAR.
But, when I execute the command 'get' from within netopeer2-cli, sysrepo-plugind shows errors:

```
...
[ERR] (keystored_read_pubkey_skip_type:75) File "/etc/keystored/keys/ssh_host_rsa_key.pem.pub" is not a public key in PEM format.
[ERR] (ks_privkey_get_cb:185) Memory allocation failed (Resource temporarily unavailable).
...

```
The reason is, that there is no headline (-----BEGIN ...) / footline (-----END ...) in the .pub file. Converting the .pub file with ssh-keygen into a PEM file isn't enough, because ssk-keygen generates the headline '-----BEGIN RSA PUBLIC KEY-----', whereas keystored expects '-----BEGIN PUBLIC KEY-----' (and vv for the footline).
Thus, the final working solution is:

```
cd /etc/keystored/keys
rm -f ssh_host_rsa_key.pem*
ssh-keygen -m PKCS8 -t rsa -q -N "" -f ./ssh_host_rsa_key.pem
ssh-keygen -f ssh_host_rsa_key.pem -e -m pem | sed -e 's/RSA PUBLIC KEY/PUBLIC KEY/' > ssh_host_rsa_key.pem.pub

```
I don't know whether there is the same problem in other distros (now or in the near future), so I cannot decide whether it makes sense to update the file keystored/scripts/ssh-key-import.sh in order to respect this, future will show.
As reference, the versions of related stuff is:

> openssh: version 8.0p1 (release 4.fc30)
> libssh:  version 0.8.7 (release 1.fc30)
> openssl: version 1.1.1c (release 2.fc30)
> As mentioned above, the rest actual as of 2019-06-25.
> 

Not a big thing, just to let you know.
Kind Regards,
Peter

**Comment by michalvasko** [comment]
Hi Peter,
thanks for letting us know. In the new *netopeer2* (that is almost ready and will soon go public) the key generation is implemented differently, so I would keep the current *netopeer2* the way it is. If you encounter this problem with the new *netopeer2*, we can discuss an appropriate fix.

Regards,
Michal

**Comment by psch-k** [comment]
Hi Michal,
thank you for the fast response.
That's okay for me, since a simple workaround exists. I will recheck it when the new netopeer2 is available.
Kind Regards,
Peter
