### ISSUE TITLE
two question about call-home  keepalive

### ISSUE THREAD

**Issue by nic1225** [CESNET/Netopeer2#441]
hi，
    I user netopeer2-server-0.7.0 in my uCPE and use call-home feature to connect the ODL(OpenDaylight) controller. some times, Odl show uCPE's  status is offline, and use `netstat  -ant` command to view the tcp link does not exist. but ssh to the uCPE，use `netstat -ant` command show link is OK as below, so uCPE  will not reconnect to ODL.
`tcp        0      0 10.0.0.2:39510          192.168.1.107:6666      ESTABLISHED`

**two  questions are as follow:**
1. how to keep(or check) this netconf link between uCPE and ODL?
2. I configure callhome with connection-type parameters max-wait, max-attempts for keepalive，but failed to hit any packets to ODL using wireshark. 

Sincerely.

**Comment by michalvasko** [comment]
Hi,
keep-alive is the responsibility of *libnetconf2* and it should be enabled by default, in the current version 0.12.55. It was added quite some time ago but maybe you have an older version where it is not, so please update.

Regards,
Michal
