### ISSUE TITLE
Issue parsing matching data in subtree filter for instance-identifier

### ISSUE THREAD

**Issue by amandeepsethi** [CESNET/Netopeer2#446]
I am trying to parse data using matching subtree filter passed but getting issue in getting a match for instance-identifier.
I am using latest version (1.1.36) of libyang but the result is same. Though code used for Netopeer2 server is previous version of internal implemented filter APIs (my project limitation is not to use sysrepo library).
Attached are my code files for reference. Request you to please provide your inputs.

The issue is not observed when the instance-identifier value doesn't have a container at the top and matching data gets printed:
```
$ cat stream.yang
module stream {
namespace "urn:test:params:xml:ns:yang:stream";
prefix stream;

    list subject {
      key "name";
      leaf name {
        type string;
        description
          "The name of subject.";
      }
    }
}
```
Filter and Data is:
```
char *inputStr = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
  <rpc xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\" message-id=\"1\">
    <get>
      <filter type=\"subtree\">
        <student:student-data xmlns:student=\"urn:test:params:xml:ns:yang:student\">
          <student:resource xmlns:stream=\"urn:test:params:xml:ns:yang:stream\">/stream:subject[name='medical']</student:resource>
        </student:student-data>
      </filter>
    </get>
  </rpc>";
```
```
char *data = "
  <student-data xmlns=\"urn:test:params:xml:ns:yang:student\">
    <id>7</id>
    <resource xmlns:stream=\"urn:test:params:xml:ns:yang:stream\">/stream:subject[stream:name=&apos;medical&apos;]</resource>
  </student-data>";
```

But when container is present then there is blank data after matching:
```
onl-fogwall-112:code (master %=)]$ cat stream.yang
module stream {
namespace "urn:test:params:xml:ns:yang:stream";
prefix stream;
  container roles {
    list subject {
      key "name";
      leaf name {
        type string;
        description
          "The name of subject.";
      }
    }
  }
}
```
Filter and Data is:
```
char *inputStr = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
  <rpc xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\" message-id=\"1\">
    <get>
      <filter type=\"subtree\">
        <student:student-data xmlns:student=\"urn:test:params:xml:ns:yang:student\">
          <student:resource xmlns:stream=\"urn:test:params:xml:ns:yang:stream\">/stream:roles/stream:subject[name='medical']</student:resource>
        </student:student-data>
      </filter>
    </get>
  </rpc>";
```
```
char *data = "
  <student-data xmlns=\"urn:test:params:xml:ns:yang:student\">
    <id>7</id>
    <resource xmlns:stream=\"urn:test:params:xml:ns:yang:stream\">/stream:roles/stream:subject[stream:name=&apos;medical&apos;]</resource>
  </student-data>";
```

Note: Also observed, when root container is not present in instance-identifier then matching data is printed twice.
[Code having matching data output.zip](https://github.com/CESNET/Netopeer2/files/3435524/Code.having.matching.data.output.zip)
[Code having no data output.zip](https://github.com/CESNET/Netopeer2/files/3435530/Code.having.no.data.output.zip)

**Comment by michalvasko** [comment]
Hi,
so, the 2 duplicate instances should be fixed in the referenced commit. However, the second case, with no match, will not be fixed (now). The problem is actually a really complex one, concerning instance-identifiers and how to represent them in XPath. I can only suggest you change
```
/stream:roles/stream:subject[name='medical']
```
to
```
/stream:roles/subject[name='medical']
```
and it is going to work.

We are working on a new version of *libyang* where all the types are implemented in a much more robust way and it would work there. But it is almost impossible to cover all the use-cases in the current *libyang*.

Regards,
Michal

**Comment by amandeepsethi** [comment]
@michalvasko : Thank you very much for the quick fix, yes both the provided solutions are working for me.
Can you provide a tentative date by which the robust solution as mentioned above will be available to users.

**Comment by michalvasko** [comment]
Hi,
we are hoping to have some working version by the end of the year.

Regards,
Michal

**Comment by amandeepsethi** [comment]
Thanks Michal, closing this issue.
