### ISSUE TITLE
cross compile error when make install 

### ISSUE THREAD

**Issue by OlympusHo** [CESNET/Netopeer2#447]
i have the same problem(cross built on vm,not inside docker) ,see the error log below:
.....
[100%] Linking C shared library libkeystored.so
[100%] Built target keystored
[100%] Built target keystored
Install the project...
-- Install configuration: "Release"
-- Installing: /home/olympus/toolchain/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabi/lib/pkgconfig/keystored.pc
-- Up-to-date: /home/olympus/toolchain/gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabi/etc/keystored/keys
/usr/local/bin/sysrepoctl: error while loading shared libraries: libsysrepo.so.0.7: wrong ELF class: ELFCLASS32
-- Installing module ietf-x509-cert-to-name...
/usr/local/bin/sysrepoctl: error while loading shared libraries: libsysrepo.so.0.7: wrong ELF class: ELFCLASS32
/usr/local/bin/sysrepocfg: error while loading shared libraries: libsysrepo.so.0.7: wrong ELF class: ELFCLASS32
-- SSH hostkey found, no need to generate a new one.
-- Importing ietf-keystore stock key configuration...
/usr/local/bin/sysrepocfg: error while loading shared libraries: libsysrepo.so.0.7: wrong ELF class: ELFCLASS32
-- Installing: /usr/local/lib/sysrepo/plugins/libkeystored.so
-- Set runtime path of "/usr/local/lib/sysrepo/plugins/libkeystored.so" to ""

root@ubuntu:/home/olympus/build-root/Netopeer2-0.7-r1/keystored/build# file /usr/local/bin/sysrepoctl
/usr/local/bin/sysrepoctl: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=67d26927d11b2b1222178ea864324628b790151d, not stripped
root@ubuntu:/home/olympus/build-root/Netopeer2-0.7-r1/keystored/build# file /usr/lib/libsysrepo.so.0.7
/usr/lib/libsysrepo.so.0.7: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=8c5b31f9cf8f28d53fc0f83c03890e83dd979a93, not stripped 

#403

**Comment by jktjkt** [comment]
Cross compiling is tricky, I recommend to use a real tool for this, such as Buildroot or Yocto.

It looks like you're invoking `sysrepoctl` built for your target architecture while still on the host. Sysrepo's build does this, and therefore you have to build sysrepo twice, once for host and the second time for the target and using an appropriate `-DCALL_SYSREPOCTL_BIN=...` (and the same for `sysrepocfg`) should get you going.

See the git log for details.
