### ISSUE TITLE
cli print "Malformed message"after timeout  

### ISSUE THREAD

**Issue by nic1225** [CESNET/Netopeer2#449]
hi.
version: netopeer2-0.7-r1 and sysrepo (v0.7.7) 

I used netopeer2-cli  to get the interface state first, and it timed out due to my own reason, but the next operation returned a 'Malformed message'. After that, getting anything returns  'Malformed message'.

    > get --filter-xpath /ietf-interfaces:*
    ERROR
            type:     application
            tag:      operation-failed
            severity: error
            message:  np2srv_sr_get_items_iter failed (sysrepo: Timeout has expired).

    > get --filter-xpath /ietf-interfaces:*
    ERROR
            type:     application
            tag:      operation-failed
            severity: error
            message:  Malformed message

    > get --filter-xpath /device-info:*
    ERROR
            type:     application
            tag:      operation-failed
            severity: error
            message:  Malformed message

log as follow:

    Aug  1 17:53:47 localhost netopeer2-server[10559]: np2srv_sr_get_items_iter failed (sysrepo: Timeout has expired).
    Aug  1 17:53:53 localhost netopeer2-server[10559]: SSH key exchange timeout.
    Aug  1 17:54:02 localhost sysrepod[9225]: [ERR] Time out waiting for operational data expired before all responses have been received, session id = 1378662113, req = 286
    Aug  1 17:54:07 localhost netopeer2-server[10559]: SSH key exchange timeout.
    Aug  1 17:54:19 localhost netopeer2-server[10559]: np2srv_sr_get_items_iter failed (sysrepo: Timeout has expired).
    Aug  1 17:54:21 localhost netopeer2-server[10559]: SSH key exchange timeout.
    Aug  1 17:54:34 localhost sysrepod[9225]: [ERR] Time out waiting for operational data expired before all responses have been received, session id = 1378662113, req = 291
    Aug  1 17:54:35 localhost netopeer2-server[10559]: SSH key exchange timeout.
    Aug  1 17:54:49 localhost netopeer2-server[10559]: SSH key exchange timeout.
    Aug  1 17:54:50 localhost sysrepod[9225]: [ERR] State data arrived after timeout expiration or session id=1378662113 is invalid (msg=286, session->req=0).
    Aug  1 17:54:50 localhost vnet[4406]: vl_msg_api_send_shmem:748: WARNING: client input queue at 1301cea40 is stuffed...
    Aug  1 17:55:00 localhost systemd: Starting Cleanup of Temporary Directories...
    Aug  1 17:55:00 localhost systemd: Started Cleanup of Temporary Directories.
    Aug  1 17:55:03 localhost netopeer2-server[10559]: SSH key exchange timeout.
    Aug  1 17:55:17 localhost netopeer2-server[10559]: SSH key exchange timeout.
    Aug  1 17:55:31 localhost netopeer2-server[10559]: SSH key exchange timeout.
    Aug  1 17:55:45 localhost netopeer2-server[10559]: SSH key exchange timeout.
    Aug  1 17:55:46 localhost sysrepod[9225]: [ERR] State data arrived after timeout expiration or session id=1378662113 is invalid (msg=291, session->req=0).
    Aug  1 17:55:59 localhost netopeer2-server[10559]: SSH key exchange timeout.

Sincerely,
Nick.

**Comment by michalvasko** [comment]
Hi Nick,
this is a know issue, unfortunately. We do not really plan on fixing it, timeout should never occur.

Regards,
Michal
