### ISSUE TITLE
netopeer2-devel-server not compatible with latest sysrepo-devel

### ISSUE THREAD

**Issue by huw305** [CESNET/Netopeer2#456]
I'm seeing netopeer2 crashed in the callback subscribed by "sr_oper_get_items_subscribe".
As of sysrepo-devel version 1.1.0, the definition for "sr_oper_get_items_cb" has been changed to add request_xpath and request_id to callbacks, but the netopeer2-devel is not updated for this change.

SW version:
netopeer2-server 1.0.1
libsysrepo.so.1.1.2

**Comment by michalvasko** [comment]
Hi,
sorry about that, should be updated now.

Regards,
Michal

**Comment by huw305** [comment]
Thanks Michal, I confirm the latest code is working.
