### ISSUE TITLE
Service crashes after receiving malformed HELLO packet

### ISSUE THREAD

**Issue by Sisyphus67** [CESNET/Netopeer2#474]
Any summary here would be redundant, since the title captures the problem.

Attached please find the following log files:

* auth.log
* messages.txt
* sysrepo.txt

Also attached is a text file that can be executed as a python script to reproduce the failure.

I also have pcap, but I do not know how to encode it to a file type that can be decoded

[auth.log](https://github.com/CESNET/Netopeer2/files/3735123/auth.log)
[messages.txt](https://github.com/CESNET/Netopeer2/files/3735124/messages.txt)
[sysrepo.txt](https://github.com/CESNET/Netopeer2/files/3735125/sysrepo.txt)
[netconfAttack.txt](https://github.com/CESNET/Netopeer2/files/3735474/netconfAttack.txt)

**Comment by michalvasko** [comment]
Hi,
a "print injection", nice. Should be fixed now.

Regards,
Michal
