### ISSUE TITLE
OpenWRT: netopeer2-server fails with error Server init failed

### ISSUE THREAD

**Issue by anusha2508** [CESNET/netopeer2#479]
Hi,

Below are the packages build for OpenWRT 18.06 and on installing them, netopeer2-server failed to start with error "Module "ietf-netconf" feature "writable-running" not enabled in sysrepo.". Even tried cleaning up /etc/sysrepo/ and then reinstallation.

libev_4.22-1_x86_64.ipk
libnetconf2_0.12-r1_x86_64.ipk
libpcre_8.41-2_x86_64.ipk
libprotobuf-c_v1.3.0-1_x86_64.ipk
libredblack_0.2.3-a399310d99b61eec4d3c0677573ab5dddcf9395d_x86_64.ipk
libssh_0.7.5-1_x86_64.ipk
libsysrepo_0.7.7-5_x86_64.ipk
libyang_v0.16-r2-2ec826a984204d034f43a7ad72d835bc99974ede_x86_64.ipk
netopeer2-cli_0.7-r1-3_x86_64.ipk
netopeer2-keystored_0.7-r1-3_x86_64.ipk
netopeer2-server_0.7-r1-3_x86_64.ipk
openssh-keygen_7.7p1-1_x86_64.ipk
protobuf_3.3.0-1_x86_64.ipk
sysrepo_0.7.7-5_x86_64.ipk
sysrepocfg_0.7.7-5_x86_64.ipk
sysrepoctl_0.7.7-5_x86_64.ipk

Wjhile installing netopeer2-server package , observed below error
Enabling feature 'url' in the module 'ietf-netconf'.
[ERR] Error by processing of the feature-enable request (session id=1434141376): Requested schema model is not known.
[ERR] Error by processing of the request.
Error: Requested schema model is not known

Please suggest on how to proceed further.

**Comment by michalvasko** [comment]
Hi,
have you properly executed all steps of *netopeer2-server* installation? It should install `ietf-netconf` before trying to enable all these features, it seems this did not happen in your case.

Regards,
Michal
