### ISSUE TITLE
Invalid processing of a get request

### ISSUE THREAD

**Issue by rastislavszabo** [CESNET/Netopeer2#48]
This behavior can be seen in the devel branch code, I've not tried the master branch.

The following NETCONF request:
```
#198
<rpc message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<get>
    <filter>
        <interfaces-state xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces" />
    </filter>
</get>
</rpc>
##
```

Renders to incorrect request in sysrepo:
```
[INF] (rp_dt_get_values_wrapper:911) Get items request running datastore, xpath: /ietf-interfaces:interfaces-state
```

and therefore returns no data:
```
#143
<rpc-reply message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"/></rpc-reply>
##
```

The correct xpath is supposed to be `/ietf-interfaces:interfaces-state//*` instead of `/ietf-interfaces:interfaces-state`

**Comment by michalvasko** [comment]
Hi,
this behavior is generally correct, it should first ask for the parent node, then the next request asks for all the children. What exactly is not working?

Regards,
Michal

**Comment by rastislavszabo** [comment]
Hi,
you are right, it seems that sysrepo incorrectly returns SR_ERR_NOT_FOUND error for `/ietf-interfaces:interfaces-state` container -> bug in sysrepo. Thanks.
