### ISSUE TITLE
Query: How to compile Netopeer2 with custom sysrepo.

### ISSUE THREAD

**Issue by iGovindY** [CESNET/netopeer2#480]
Hi

I have added some changes in sysrepo client lib for my need. For testing, I'm using `sysrepod ` binary from `build/` directory.

Now I want to compile and test netopeer2 using the above changes in client library.
What flags do I need to set for netopeer2 to compile with my sysrepo changes, not the installed sysrepo?

Thanks
Govind.

**Comment by michalvasko** [comment]
Hi,
obviously, the easiest way would be to install your modified *sysrepo*. But if you insist on having one *sysrepo* installed and compiling with another, you should be able to do that by defining `SYSREPO_LIBRARIES` and `SYSREPO_INCLUDE_DIRS`.

Regards,
Michal

**Comment by iGovindY** [comment]
Well It didn't worked, tried below ways.

 1. export both Variables explicitly before `cmake ..`.
 2. also tried `cmake -DSYSREPO_LIBRARIES=<libsysrepo.so directory Path> -DSYSREPO_INCLUDE_DIRS=<sysrepo/build/src/inc/> ..`

both ways cmake finds sysrepo in the installed path.
Can you please point me in the correct direction? I am very new to cmake.

**Comment by michalvasko** [comment]
Hi,
okay, it seems to work for me when I use
```
cmake -DSYSREPO_INCLUDE_DIR=<path> -DSYSREPO_LIBRARY=<path> ..
```
I then see this path in `CMake` output.

Regards,
Michal
