### ISSUE TITLE
When cross-compiling, is there an option to control whether to invoke sysrepoctl during install?

### ISSUE THREAD

**Issue by manas42** [CESNET/Netopeer2#482]
Hi,

I'm cross-compiling **Netopeer2** on a x86-64 platform for an arm device. I have successfully cross-compiled **sysrepo** by setting `CALL_TARGET_BINS_DIRECTLY=OFF`, then manually call `sysrepoctl` in the install script of my deb when installing the deb on the arm device. 

I wonder whether **Netopeer2** have such an option, or must I edit the CMakelist.txt myself?

P.S. the advice of "installing **sysrepo** twice" in https://github.com/sysrepo/sysrepo/blob/master/INSTALL.md would not work, because I do not have the privilege to install anything on the compile server, so "installing sysrepo on the host" would automatically fail. Thus, I suppose the only available approach is to compile and copy everything into the deb, then run sysrepoctl with a script after installing deb on the target device. Would appreciate it if there is a better approach.

Best Regards.

**Comment by jktjkt** [comment]
When "installing sysrepo on the host", you should not have to install directly to `/` or `/usr`. Therefore I do not understand your remark about not enough permissions.

The approach that is documented in the docs works. The [Buildroot recipes we provide](https://gerrit.cesnet.cz/plugins/gitiles/github/buildroot/buildroot/+/refs/heads/cesnet/2019-06-10/package/sysrepo/sysrepo.mk) also work. If you want to do things differently for some reason, more power to you, but I do not think people will provide free support.

**Comment by manas42** [comment]
I see. By changing `REPOSITORY_LOC` I should be able to compile **sysrepo** for host and store the binaries in a temp location. Then specify the location in the makefile of **Netopeer2**. 

I should try if that works for my purpose, and thanks for your help.

**Comment by manas42** [comment]
Sadly, as the dependencies of **sysrepo** are not ready on host platform but only on the arm platform, this approach would require more work. I'll try to modify the CMakelist.txt.
