### ISSUE TITLE
How do I create objects using edit-config?

### ISSUE THREAD

**Issue by MickAbson** [CESNET/Netopeer2#484]
Hi
The rfc6241 just show how to replace/delete the configuration,I perform the get-edit operation，and then I found that both "running"and"candidate" is enpty.
so that how can i creat something?
There is no example for edit-config "create" in rfc6241.
So I try it myself,but failed.
The order I try is "edit-config --target candidate --config=/tmp/bbb.xml",
and the content of bbb.xml is :
```xml
<config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
	<top xmlns="http://example.com/schema/1.2/config">
		<interface xc:operation="create">
			<name>Ethernet0/0</name>
			<mtu>1500</mtu>
			<address>
				<type>string</type>
				<name>192.0.2.4</name>
				<prefix-length>24</prefix-length>
			</address>
		</interface>
	</top>
</config>
```
Then the cli show this :
```
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	message:  Sysrepo-internal error
```
And the server show this:
```
[ERR]: Type can not be mapped to gpb type '(null)' type 0
[ERR]: Setting type in gpb failed for xpath '(null)'
[ERR]: value duplication failed.
[DBG]: EDIT_CONFIG: stop-on-error (Sysrepo-internal error).
```
I just want to know how to creat something ，or where to learn about it.
Please tell me what I can do to solve this problem。（i am not good at english,thank you！--fizz）

**Comment by MickAbson** [comment]
Thank you for your prompt reply.I've been searching a lot of NETCONF blogs for the last two weeks, but I still can't find what I'm looking for. Thank you for your advice. I've tried again and it still doesn't seem to work.

This time the command I typed was:edit-config --target candidate --config=/tmp/bbb.xml --test test-then-set

The cli send this(I've deleted the “type” line):
NC Session 2: sending message:
```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="55"><edit-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><target><candidate/></target><test-option>test-then-set</test-option><config><top xmlns="http://example.com/schema/1.2/config">
 <interface>
 <name>Ethernet0/0</name>
    <mtu>1500</mtu>
    <address>
      <name>192.0.2.4</name>
      <prefix-length>24</prefix-length>
    </address>
  </interface>
</top>
</config></edit-config></rpc>
```
Then the server displays this:
[ERR]: Unknown element "top". (/)

Then the cli displays this:
ERROR
	type:     application
	tag:      operation-not-supported
	severity: error
	message:  Request could not be completed because the requested operation is not supported by this implementation.

So what mean "Unknown element "top" "?Is it means that the server has no this model?But the content of bbb.xm shouldn't be wrong which I copy from rfc6241 section 7.2.What can I do to solve this ?

**Comment by michalvasko** [comment]
Hi,
yes, it means the server does not have any model with namespace `http://example.com/schema/1.2/config` and top-level container `top`. You can see all the supported models by executing `sysrepoctl -l`. It is up to you to create data that fit a particular model, I will not explain to you the basics of YANG.

Regards,
Michal

**Comment by MickAbson** [comment]
Hi,
Thank you for your guidance. I can now configure "candidate", but not "running", not even the operation "commit".
Every time I tried to configure "running", the server reported an error:
[ERR]: Error by processing of the set-item request (session id=1621956262): The node is not enabled in running datastore.what can I do to fix this?

Regards,
Fizz

**Comment by michalvasko** [comment]
Hi Fizz,
there is a concept of enabled data implemented for [running datastore](http://www.sysrepo.org/static/doc/html/ds_page.html#rds).

Regards,
Michal

**Comment by MickAbson** [comment]
Hi Michal,
I just looked at the sysrepo example, and I found that Netopeer2 and the sysrepo example connect to sysrepo in the same way, so how does sysrepo distinguish between managed and non-managed sessions?

Regards,
Fizz

**Comment by arodage** [comment]
Hi Fizz,

I am trying to get netopeer2 working and facing some issues. Looks like it's been a year since you started this thread. Do you have more info about how to add config with different yang movels? How to add custom yang models and edit config based on that?

**Comment by MickAbson** [comment]
Chinese:是的，我现在非常熟悉netopeer2,netconf和sysrepo。首先，你要保证你的netopeer2和sysrepo以及他们的依赖软件库（libyang,libnetconf2,libssh...）正确安装，并且可以正常运行。然后你可以使用sysrepoctl工具安装你的自定义模型，至于配置数据，你可以参考sysrepo里面的example目录下的实例。另外建议你先了解一下整个架构框图。



---Original---

**Comment by arodage** [comment]
Hi fizz,

Thanks for your response. I have already gone through sysrepo documentation examples and was able to add custom schema to sysrepo and was able to use C applications in examples to update and fetch data to and from sysrepo. However, I did not find the way to send data to netopeer2 server using netopeer-cli. There is edit-config and edit-data both ask for config file as parameter. I could not find the example for that config file.

Regards,
Alpesh

**Comment by arodage** [comment]
For example: I have my custom yang module loaded in sysrepo which I can fetch from netopeer2-cli:

---------------------------------

> get-schema --model interfacecfg

MODULE

module interfacecfg {

  namespace "demo:interfacecfg";

  prefix int;



  typedef dotted-quad {

    type string {

      pattern "(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])";

    }

    description

      "Four octets written as decimal numbers and

       separated with the '.' (full stop) character.";

  }



  container interface {

    leaf name {

      type string;

      description

        "Interface name. Example value: GigabitEthernet 0/0/0";

    }



    leaf address {

      type dotted-quad;

      description

        "Interface IP address. Example value: 10.10.10.1";

    }



    leaf subnet-mask {

      type dotted-quad;

      description

        "Interface subnet mask. Example value: 255.255.255.0";

    }



    leaf enabled {

      type boolean;

      default "false";

      description

        "Enable or disable the interface. Example value: true";

    }

  }

}



>

---------------------------------



Now I want to add config using netopeer2-cli. I am not sure whether to use edit-data or edit-config. I tried both but failed failed.

> edit-data --datastore running --config=cfg1.xml

ERROR

        type:     application

        tag:      operation-failed

        severity: error

        path:     /

        message:  Unknown element "interface".



> edit-config --target running --config=cfg1.xml

ERROR

        type:     application

        tag:      operation-failed

        severity: error

        path:     /

        message:  Unknown element "interface".



>



Here are contents of  cfg1.xml:

<interface xmlns="demo:interfacecfg">

    <name>Ethernet0/0</name>

    <address>192.0.2.4</address>

</interface>



I'm sure I am missing something but not sure what.



Please help me here.



Regards,

Alpesh


From: Rodage, Alpesh Ramesh
Sent: Thursday, December 17, 2020 1:47 PM
To: CESNET/netopeer2 <reply@reply.github.com>; CESNET/netopeer2 <netopeer2@noreply.github.com>
Cc: Comment <comment@noreply.github.com>
Subject: RE: [CESNET/netopeer2] How do I create objects using edit-config? (#484)

Hi fizz,

Thanks for your response. I have already gone through sysrepo documentation examples and was able to add custom schema to sysrepo and was able to use C applications in examples to update and fetch data to and from sysrepo. However, I did not find the way to send data to netopeer2 server using netopeer-cli. There is edit-config and edit-data both ask for config file as parameter. I could not find the example for that config file.

Regards,
Alpesh

**Comment by MickAbson** [comment]
我看了一下你的自定义模型，以及你的配置文件，好像都没有什么问题，但是报错信息很明显提示顶层容器interfere未知，以我的经验，出现这种错误有以下几种情况:1，你的模型缺乏某些元素（这有可能是sysrepo或者netopeer本身的bug导致的，所以尽量补全模型中的其它细节，如yang version,revision等。关于这点你可以尝试在一些简单的并且已经成功配置过数据的模型上进行修改，一部分一部分地修改成你想要的模型）。2，开源软件自身bug导致的元素未知，不管是sysrepo还是netopeer都或多或少有点bug，这点你是知道的，不然也不会有这么多人在这里提问，我也曾经反馈过几个。所以为了尽量避开bug，你可以尝试以下几点。1，sysrepo,netconf,yang,netopeer这四个软件都使用最新正式发布版本。2，每次进行模型安装等重大操作之前，先把其他进程杀掉，如netopeer2-server，应用程序等（所有调用了libsysrepo的进程）。并且在安装完成以后，重启系统或删除/dev/shm目录下以sr开头的所有文件，那是sysrepo产生的临时文件，删除了好让它们重新构造。
另外，我一直使用edit-config进行数据编辑，也就是你上诉的第二种方式。
祝你好运



---Original---

**Comment by arodage** [comment]
Hi Fizz,

It worked after creating fresh setup. No other changes made in yang schema or anything else. Not sure what was wrong.

Thanks,
Alpesh
