### ISSUE TITLE
How do I enable URL capabilities with scheme arguments?

### ISSUE THREAD

**Issue by mictra** [CESNET/netopeer2#485]
Hi,

The URL capability must contain a "scheme" argument assigned a comma-separated list of scheme names indicating which schemes the NETCONF peer supports, according to [Section 8.8.3](https://tools.ietf.org/html/rfc6241#section-8.8.3).
How do I enable a URL scheme, say HTTP for example?
I know that you can enable the URL feature for the ietf-netconf module using sysrepoctl, but I am not sure how to specify which/what schemes to support? Is this the right way to enable NETCONF capabilities?

Regards,
Michael

**Comment by michalvasko** [comment]
Hi,
you do not have t manually enable anything. As long as you have *libcurl* installed, URL should be enabled automatically by default. Can you paste `CMake` output of *netopeer2-server*?

Regards,
Michal
