### ISSUE TITLE
why there is no uninstall rule for server and cli?

### ISSUE THREAD

**Issue by iGovindY** [CESNET/Netopeer2#487]
So I wanted to move to the new sysrepo from devel branch.
For this, I am guessing I need Netopeer2, libyang and libnetconf2 from devel branch also.

How do I uninstall netopeer2 so that I can install netopeer2 from devel branch?

**Comment by michalvasko** [comment]
Hi,
there is now.

Regards,
Michal

**Comment by iGovindY** [comment]
Hi Michal,

I am overwhelmed by the real-time change requests, you are providing.
Thank you for the great work you guys are doing.

Is it possible to provide same for keystored also.
thanks
Govind.

**Comment by michalvasko** [comment]
Hi,
okay, I have added it for `keystored` as well even though it will be obsolete in a week or so (the new *netopeer2* does not need it).

As for the changes, it all depends on whether I am working on something I do not want to interrupt and on how difficult the change is. This was trivial.

Regards,
Michal
