### ISSUE TITLE
will netopeer2-server advertise submodule capabilities

### ISSUE THREAD

**Issue by navya46** [CESNET/netopeer2#490]
Hi,
    Will netopeer2-server advertise submodules in hello capabilities??

Regards,
navya

**Comment by michalvasko** [comment]
Hi,
no, submodules are not advertised in `hello` messages. However, they are included in [ietf-yang-library](https://github.com/CESNET/libyang/blob/master/models/ietf-yang-library%402019-01-04.yang) data provided by *netopeer2-server*.

Regards,
Michal

**Comment by navyakankanala46** [comment]
Hi Michal, 

Thanks for the reply.
We have our custom yang models, where we have defined modules and submodules.
As you said, the submodules are not advertised in hello capabilities and neither get-schema reply contains the details of submodule. So from your statement, any explicit request to be sent to netopeer2-server to get the submodule schema?. Please clarify.

**Comment by michalvasko** [comment]
Hi,
yes, you should send `<get>` with XPath filter `/ietf-yang-library:yang-library` and use these data to learn about submodules.

Regards,
Michal
