### ISSUE TITLE
libyang API wrong

### ISSUE THREAD

**Issue by feldi59** [CESNET/Netopeer2#492]
Hello,
i have updated to the latest releases.
Nearly all works, except finally installinf keystored i get the following error.
Can anyone give me a hint why the API version of libyang is wrong, i updated, recompiled and reinstalled all (libyang, libnetconf, sysrepo, ...).
Thanks in advance

```
[100%] Built target keystored
[100%] Built target keystored
Install the project...
-- Install configuration: "debug"
-- Up-to-date: /usr/local/lib/pkgconfig/keystored.pc
-- Installing: /usr/local/etc/keystored/keys
- Module ietf-x509-cert-to-name already installed.
- Module ietf-keystore already installed.
- SSH hostkey not found, generating a new one...
libyang[1]: Processing "user_date_and_time" user type plugin failed, wrong API version - 1 expected, 0 found.
libyang[1]: Processing "user_date_and_time" user type plugin failed, wrong API version - 1 expected, 0 found.
-- Up-to-date: /usr/local/lib/sysrepo/plugins/libkeystored.so

```

**Comment by michalvasko** [comment]
Hi,
you have old *libyang* plugins installed, just remove `/usr/local/lib64/libyang/user_types/user_date_and_time.so` (default path on my system) and it should work. Also, you can simply ignore these warnings.

Regards,
Michal

**Comment by feldi59** [comment]
thanks a lot
