### ISSUE TITLE
How do I get a trigger, after netconf capabilities discovery?

### ISSUE THREAD

**Issue by jiantuo** [CESNET/Netopeer2#495]
Hi guys,
I'm using netopeer2 and sysrepo for xran's netconf development.
One of it's boot sequence need our application to send a notification after netconf capabilities discovery.
But we could not find a way to tell the application netconf capabilities discovery have just finished.
May you help with this?
Thanks.

**Comment by michalvasko** [comment]
Hi,
let me get this straight, you need to send a NETCONF notification to the client after you parse its capabilities?

Regards,
Michal

**Comment by jiantuo** [comment]
may be i did not make it clear.

I just need to send a NETCONF notification to the client after the netconf capabilities discovery process.
no need to parse.

**Comment by jiantuo** [comment]
cause the netconf capabilities discovery process , is done by your helpful open source libs.
I cann't the triger.

**Comment by michalvasko** [comment]
Hi,
okay, you can send a notification only after a NETCONF session is created. The simplest way is to subscribe to `<netconf-session-start>` notification, it informs about the same thing. If you need a specific notification, then just create a simple *sysrepo* client that will "transform" this notification into the one you need.

It will subscribe to `<netconf-session-start>` and when it is received, it will send the other notification.

Regards,
Michal

**Comment by jiantuo** [comment]
Will consider your way instead.
Thank you, Michal.
