### ISSUE TITLE
subscribe error

### ISSUE THREAD

**Issue by MickAbson** [CESNET/Netopeer2#496]
Hi Michal,
    I failed to subscribe to the notification，Operating as follows：
```
> subscribe --filter-xpath /o-ran-file-management:file-download-event
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	message:  np2srv_sr_event_notif_subscribe failed (sysrepo: Requested schema model is not known).
```

The server：
```
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[ERR]: Unable to stat data file for 'ietf-crypto-types': .
[WRN]: Attempt to subscribe to unknown 'ietf-crypto-types' module.
[ERR]: Unable to set socket directory permissions for '/var/run/sysrepo-subscriptions/ietf-crypto-types/'.
[ERR]: Cannot generate server socket path.
[ERR]: Cannot initialize Client Subscription Manager.
[ERR]: NULL value detected for subscription argument of cl_sm_subscription_cleanup
[ERR]: Error by initialization of the subscription in the client library.
[ERR]: np2srv_sr_event_notif_subscribe failed (sysrepo: Requested schema model is not known).
[INF]: Session 2: thread 1 event new RPC.
[INF]: Session 2: thread 1 event reply error.
```

I'm sure I've installed model o-ran-file-management：
```
srbn@ubtVM:/mnt/hgfs/Notepeer/o-ran-modules$ sudo sysrepoctl -l
Sysrepo schema directory: /etc/sysrepo/yang/
Sysrepo data directory:   /etc/sysrepo/data/
(Do not alter contents of these directories manually)

Module Name                | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
ietf-netconf-notifications | 2012-02-06 | Installed   | root:root           | 666         |                               |
ietf-netconf               | 2011-06-01 | Installed   | root:root           | 666         |                               | writable-running candidate rollback-on-error validate startup xpath
ietf-netconf-acm           | 2018-02-14 | Installed   | root:root           | 666         |                               |
nc-notifications           | 2008-07-14 | Installed   | root:root           | 666         |                               |
notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
turing-machine             | 2013-12-27 | Installed   | root:root           | 666         |                               |
iana-if-type               | 2014-05-08 | Installed   |                     |             |                               |
ietf-interfaces            | 2014-05-08 | Installed   | root:root           | 666         |                               |
ietf-ip                    | 2014-06-16 | Installed   |                     |             |                               |
ietf-netconf-with-defaults | 2011-06-01 | Installed   |                     |             |                               |
ietf-netconf-monitoring    | 2010-10-04 | Installed   | root:root           | 666         |                               |
ietf-yang-library          | 2018-01-17 | Installed   | root:root           | 666         |                               |
ietf-datastores            | 2017-08-17 | Imported    |                     |             |                               |
ietf-yang-types            | 2013-07-15 | Installed   |                     |             |                               |
ietf-crypto-types          | 2019-04-29 | Installed   |                     |             |                               |
o-ran-file-management      | 2019-07-03 | Installed   | root:root           | 666         |                               |
```
The content of YANG model is ：
```yang
module o-ran-file-management {
  yang-version 1.1;
  namespace "urn:o-ran:file-management:1.0";
  prefix "o-ran-file-mgmt";

  import ietf-crypto-types {
    prefix "ct";
  }
  organization "O-RAN Alliance";

		/*......*/

  rpc file-download {
    description
      "Management plane triggered to generate the download file of O-RU.";
    input {
      uses file-path-grouping;
      uses credential-information;
    }
    output {
      uses output-status-grouping;
    }
  }

  notification file-download-event {
    uses file-path-grouping;
    uses output-status-grouping;
    description "";
  }
}
```
Note: I once subscribed successfully in the oven example and the the application is already running.
Would you do me a favor?

Regards,
Fizz

**Comment by michalvasko** [comment]
Hi,
so I assume the RPC `file-download` uses a grouping from `ietf-crypto-types`?

Regards,
Michal

**Comment by MickAbson** [comment]
Hi Michal,
Yes, part of it is.


Regards,
Fizz

**Comment by MickAbson** [comment]
Hi Michal,
I noticed something interesting, and I guess that's the problem.
The OVEN model was originally installed in SYSREPO, but the o-ran-file-management model and its dependency model were not installed.
At this point I can subscribe to the notification of the OVEN model:
`
srbn@ubtVM:~/workdocs/NetConfStudy/aboutNetConf/sysrepo/examples/plugins$ sudo netopeer2-cli 
> connect 
Interactive SSH Authentication
Type your password:
Password: 
> subscribe --filter-xpath /oven:oven-ready
OK
> 
`
Then, after I installed the o-ran-file-management model and its dependencies, I found that the subscription function was broken, and I couldn't subscribe to any notifications, including the notifications from the OVEN model that I had successfully subscribed to previously.
Here's what happens when two subscriptions fail:：
`
srbn@ubtVM:~/workdocs/NetConfStudy/aboutNetConf/sysrepo/examples/plugins$ sudo netopeer2-cli 
> connect 
Interactive SSH Authentication
Type your password:
Password: 
> 
> subscribe --filter-xpath /o-ran-file-management:file-download-event
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	message:  np2srv_sr_event_notif_subscribe failed (sysrepo: Requested schema model is not known).

> subscribe --filter-xpath /oven:oven-ready
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	message:  np2srv_sr_event_notif_subscribe failed (sysrepo: Requested schema model is not known).

[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[ERR]: Unable to stat data file for 'ietf-crypto-types': .
[WRN]: Attempt to subscribe to unknown 'ietf-crypto-types' module.
[ERR]: Unable to set socket directory permissions for '/var/run/sysrepo-subscriptions/ietf-crypto-types/'.
[ERR]: Cannot generate server socket path.
[ERR]: Cannot initialize Client Subscription Manager.
[ERR]: NULL value detected for subscription argument of cl_sm_subscription_cleanup
[ERR]: Error by initialization of the subscription in the client library.
[ERR]: np2srv_sr_event_notif_subscribe failed (sysrepo: Requested schema model is not known).
[INF]: Session 3: thread 1 event new RPC.
[INF]: Session 3: thread 1 event reply error.
[INF]: Resolving unresolved data nodes and their constraints...
[INF]: All data nodes and constraints resolved.
[ERR]: Unable to stat data file for 'ietf-crypto-types': .
[WRN]: Attempt to subscribe to unknown 'ietf-crypto-types' module.
[ERR]: Unable to set socket directory permissions for '/var/run/sysrepo-subscriptions/ietf-crypto-types/'.
[ERR]: Cannot generate server socket path.
[ERR]: Cannot initialize Client Subscription Manager.
[ERR]: NULL value detected for subscription argument of cl_sm_subscription_cleanup
[ERR]: Error by initialization of the subscription in the client library.
[ERR]: np2srv_sr_event_notif_subscribe failed (sysrepo: Requested schema model is not known).
[INF]: Session 3: thread 0 event new RPC.
[INF]: Session 3: thread 0 event reply error.

`
The relevant model file is nearby. Please help me analyze it. I guess the problem comes from the model.
[YANG.zip](https://github.com/CESNET/Netopeer2/files/3884856/YANG.zip)


Regards,
Fizz

**Comment by michalvasko** [comment]
Hi Fizz,
it seems the module was updated and it no longer even imports `ietf-crypto-types` ([link](https://wiki.onap.org/display/DW/O-RAN+Fronthaul+Specification+1.0)). As this is a problem in the old *sysrepo* I would prefer not having to fix it so would it be a problem for you to use the module without the import? Or is that the old version?

Regards,
Michal
