### ISSUE TITLE
It is possible to add timeout for netopeer-cli get

### ISSUE THREAD

**Issue by leimgitub** [CESNET/netopeer2#498]
hi:
    I have a get operation, it will consume 60 seconds. But the default timeout is fixed in the code.
    It is possible to add a timeout in config for get operation. Thanks.

    These code in command.c->cli_send_recv. 
recv_reply:
    msgtype = nc_recv_reply(session, rpc, msgid, **20000**,
                            LYD_OPT_DESTRUCT | LYD_OPT_NOSIBLINGS, &reply);

**Comment by michalvasko** [comment]
HI,
okay, it was added.

Regards,
Michal
