### ISSUE TITLE
Cross compilation of netopeer2

### ISSUE THREAD

**Issue by meghna-doshi** [CESNET/netopeer2#501]
Hi,
We have to cross compile netopeer2, so this implies that we have to cross compile libyang, libssh, cmocka and libnetconf2. So that means :

1. we dont want to use make install, what is the alternative to this.
2. we want to give different gcc compiler, how to do this? Is this to be done via CMakeList file?

Regards,
Meghna

**Comment by michalvasko** [comment]
Hi,

1. Do not have experience with this but there should be several, such as Buildroot, [here](https://gerrit.cesnet.cz/plugins/gitiles/github/buildroot/buildroot/+/refs/heads/cesnet/2019-06-10/package/sysrepo/sysrepo.mk) is a script written for it for *sysrepo* by @jktjkt.
2. Normally you just do `CC=clang cmake ..`, but it is different for certain when using some special build tool.

Regards,
Michal
