### ISSUE TITLE
Netopeer2 with IPv6

### ISSUE THREAD

**Issue by meghna-doshi** [CESNET/netopeer2#502]
Hi,
Does netopeer2 support IPv6?
If yes, what are the steps to make this work.

**Comment by michalvasko** [comment]
Hi,
it is supported and there should be no special steps required, just configure *netopeer2* correctly. Its configuration is stored as data of `ietf-netconf-server` model, which you can edit using `sysrepocfg`, for instance.

Regards,
Michal

**Comment by Tian-Sijia** [comment]
Hi,
what should I do?

best wishes

**Comment by michalvasko** [comment]
Hi,
you mean what you should do to listen on an IPv6 address? Like I said, just edit the server configuration. The exact command would be `sysrepocfg -Evim -m ietf-netconf-server`, for example, but it depends on what editor you want to use/what format of data.

Regards,
Michal

**Comment by Tian-Sijia** [comment]
Hi, 
If I want to log in with ipv6, can I change 0.0.0.0 to: : under the function server­_init straightly, instead of loading the ietf-netconf-server module? 
And if this method work, what I should do when cli is connecting?
Looking forward to your reply. 

Regards
TSJ

**Comment by michalvasko** [comment]
Hi,
wait, you are using the legacy *netopeer2*? Please, always mention that first. But yes, if you do not mind changing the code it should work if you simply change that IP.

Regards,
Michal

**Comment by Tian-Sijia** [comment]
Hi,
Thanks a lot for your help. I will try again.

Regards, 
TSJ
