### ISSUE TITLE
Input data are not valid: Leafref "/ietf-keystore:keystore/ietf-keystore:private-keys/ietf-keystore:private-key/ietf-keystore:name"

### ISSUE THREAD

**Issue by Arvliu** [CESNET/netopeer2#504]
Hi, i had cross-compiled libyang, libnetconf2, sysrepo, keystored and netopeer2-server/cli, and transplant them to ARM development board.

Exact sequences and issue logs as below:
root@am335x-evm:/netopeer2_server# ./sysrepod
root@am335x-evm:/netopeer2_server# ./sysrepo-plugind
root@am335x-evm:/netopeer2_server# ./netopeer2-server
root@am335x-evm:/netopeer2_server# ./sysrepocfg --merge=/netopeer2_server/ssh_callhome.xml --format=xml --datastore=running ietf-netconf-server -l 3

[INF] Connected to daemon Sysrepo Engine at socket=/var/run/sysrepod.sock
[WRN] libyang: Identity found, but in a non-implemented module "ietf-x509-cert-to-name". ((null))
[WRN] libyang: Failed to resolve identityref "ietf-x509-cert-to-name:specified". (/ietf-netconf-server:map-type)
[WRN] libyang: Previous warning generated by XPath subexpression[3] "map-type = 'ietf-x509-cert-to-name:specified'". ((null))
[WRN] libyang: Identity found, but in a non-implemented module "ietf-x509-cert-to-name". ((null))
[WRN] libyang: Failed to resolve identityref "ietf-x509-cert-to-name:specified". (/ietf-netconf-server:map-type)
[WRN] libyang: Previous warning generated by XPath subexpression[3] "map-type = 'ietf-x509-cert-to-name:specified'". ((null))
[WRN] libyang: Leafref "/ietf-keystore:keystore/ietf-keystore:private-keys/ietf-keystore:private-key/ietf-keystore:name" of value "ssh_host_rsa_key" points to a non-exi
[WRN] libyang: Leafref "/ietf-keystore:keystore/ietf-keystore:private-keys/ietf-keystore:private-key/ietf-keystore:name" of value "ssh_host_rsa_key" points to a non-exi
[ERR] Input data are not valid: Leafref "/ietf-keystore:keystore/ietf-keystore:private-keys/ietf-keystore:private-key/ietf-keystore:name" of value "ssh_host_rsa_key" po
Segmentation fault (core dumped)

Before this issue appear, i had tested some other features as below:
1) cli connect to server is ok;
2) get, get-schema; status, these cli commands are all ok too;

`sysrepo-plugind` is running without errors, but this issue is still there, can you help to solve this issue? Thanks in advance.

**Comment by michalvasko** [comment]
Hi,
can you please post the output of `sysrepoctl -l`? Also, can you try running `sysrepo-plugind` with debug output `-l4`? Just make sure you have `keystored` plugin correctly installed.

Regards,
Michal

**Comment by Arvliu** [comment]
Hi, Michal
Thanks for your reply.
Details logs of sysrepoctl -l and sysrepo-plugind -d -l4 are as below:

1.root@am335x-evm:/netopeer2_server# ./sysrepoctl -l
Sysrepo schema directory: /etc/sysrepo/yang/
Sysrepo data directory:   /etc/sysrepo/data/
(Do not alter contents of these directories manually)

Module Name                | Revision   | Conformance | Data Owner          | Permissions | Submodules                    | Enabled Features
-----------------------------------------------------------------------------------------------------------------------------------------------
ietf-netconf-notifications | 2012-02-06 | Installed   | root:root           | 666         |                               |
ietf-netconf               | 2011-06-01 | Installed   | root:root           | 666         |                               | writable-running candidate rollback-on-error validate startup xpath url
ietf-netconf-acm           | 2018-02-14 | Imported    |                     |             |                               |
nc-notifications           | 2008-07-14 | Installed   | root:root           | 666         |                               |
notifications              | 2008-07-14 | Installed   | root:root           | 666         |                               |
turing-machine             | 2013-12-27 | Installed   | root:root           | 666         |                               |
iana-if-type               | 2014-05-08 | Installed   |                     |             |                               |
ietf-interfaces            | 2014-05-08 | Installed   | root:root           | 666         |                               |
ietf-ip                    | 2014-06-16 | Installed   |                     |             |                               |
ietf-netconf-with-defaults | 2011-06-01 | Installed   |                     |             |                               |
ietf-netconf-monitoring    | 2010-10-04 | Installed   | root:root           | 666         |                               |
ietf-yang-library          | 2018-01-17 | Installed   | root:root           | 666         |                               |
ietf-datastores            | 2017-08-17 | Imported    |                     |             |                               |
o-ran-ald-port             | 2019-02-04 | Installed   | root:root           | 666         |                               |
ietf-hardware              | 2018-03-13 | Installed   | root:root           | 666         |                               |
iana-hardware              | 2018-03-13 | Imported    |                     |             |                               |
ietf-x509-cert-to-name     | 2014-12-10 | Installed   |                     |             |                               |
ietf-yang-types            | 2013-07-15 | Imported    |                     |             |                               |
ietf-keystore              | 2016-10-31 | Installed   | root:root           | 666         |                               |
ietf-netconf-server        | 2016-11-02 | Installed   | root:root           | 666         |                               | listen ssh-listen tls-listen call-home ssh-call-home tls-call-home
ietf-ssh-server            | 2016-11-02 | Imported    |                     |             |                               |
ietf-tls-server            | 2016-11-02 | Imported    |                     |             |                               |
ietf-system                | 2014-08-06 | Installed   | root:root           | 666         |                               | authentication local-users
iana-crypt-hash            | 2014-08-06 | Imported    |                     |             |                               |
pnf-mplane-ext             | 2018-09-12 | Installed   | root:root           | 666         |                               |
xran-supervision           | 2018-07-20 | Installed   | root:root           | 666         |                               |

2.root@am335x-evm:/netopeer2_server# ./sysrepo-plugind -d -l4
[DBG] Setting log level for stderr logs to 4.
[DBG] Sysrepo plugin daemon initialization started.
[DBG] Connecting to Sysrepo Engine.
[DBG] Connecting to socket=/var/run/sysrepod.sock
[INF] Connected to daemon Sysrepo Engine at socket=/var/run/sysrepod.sock
[DBG] Sending version-verify request.
[DBG] version-verify request sent, waiting for response.
[DBG] version-verify response received, processing.
[DBG] Sending session-start request.
[DBG] session-start request sent, waiting for response.
[DBG] session-start response received, processing.
[DBG] Loading plugins from '/liu_newGcc/sysrepo_arm_Alignment_trap/sysrepo_cross/lib/sysrepo/plugins'.
[DBG] Loading plugin from file 'libturing-machine.so'.
[DBG] Client Subscription Manager init started.
[DBG] An event loop in the background thread successfully started.
[DBG] Client Subscription Manager initialized successfully.
[DBG] Initializing sysrepo subscription server at socket=/var/run/sysrepo-subscriptions/turing-machine/996.YsYa2m.sock
[DBG] Sending subscribe request.
[DBG] Starting client subscription event loop.
[DBG] Server context changed.
[DBG] subscribe request sent, waiting for response.
[DBG] subscribe response received, processing.
[DBG] Sending subscribe request.
[DBG] subscribe request sent, waiting for response.
[DBG] New connection on fd 10
[DBG] fd 10 readable
[DBG] Input buffer for fd=10 expanded to 1024 bytes.
[DBG] 111 bytes of data received on fd 10
[DBG] fd 10 would block
[DBG] New message of size 107 bytes received.
[DBG] Received a notification for subscription id=851506560 (source address='/var/run/sysrepod.sock').
[DBG] HELLO notification received on subscription id=851506560.
[DBG] subscribe response received, processing.
[DBG] Sending subscribe request.
[DBG] subscribe request sent, waiting for response.
[DBG] fd 10 readable
[DBG] 111 bytes of data received on fd 10
[DBG] fd 10 would block
[DBG] New message of size 107 bytes received.
[DBG] Received a notification for subscription id=933488932 (source address='/var/run/sysrepod.sock').
[DBG] HELLO notification received on subscription id=933488932.
[DBG] subscribe response received, processing.
[DBG] turing-machine plugin initialized successfully
current turing-machine configuration:
[DBG] Sending get-items request.
[DBG] get-items request sent, waiting for response.
[DBG] fd 10 readable
[DBG] 111 bytes of data received on fd 10
[DBG] fd 10 would block
[DBG] New message of size 107 bytes received.
[DBG] Received a notification for subscription id=2008893384 (source address='/var/run/sysrepod.sock').
[DBG] HELLO notification received on subscription id=2008893384.
[DBG] get-items response received, processing.
/turing-machine:turing-machine/transition-function/delta[label='left summand'] (list instance)
/turing-machine:turing-machine/transition-function/delta[label='left summand']/label = left summand
/turing-machine:turing-machine/transition-function/delta[label='left summand']/input (container)
/turing-machine:turing-machine/transition-function/delta[label='left summand']/input/state = 0
/turing-machine:turing-machine/transition-function/delta[label='left summand']/input/symbol = 1
/turing-machine:turing-machine/transition-function/delta[label='left summand']/output (container)
/turing-machine:turing-machine/transition-function/delta[label='left summand']/output/head-move = right [default]
/turing-machine:turing-machine/transition-function/delta[label='separator'] (list instance)
/turing-machine:turing-machine/transition-function/delta[label='separator']/label = separator
/turing-machine:turing-machine/transition-function/delta[label='separator']/input (container)
/turing-machine:turing-machine/transition-function/delta[label='separator']/input/state = 0
/turing-machine:turing-machine/transition-function/delta[label='separator']/input/symbol = 0
/turing-machine:turing-machine/transition-function/delta[label='separator']/output (container)
/turing-machine:turing-machine/transition-function/delta[label='separator']/output/state = 1
/turing-machine:turing-machine/transition-function/delta[label='separator']/output/symbol = 1
/turing-machine:turing-machine/transition-function/delta[label='separator']/output/head-move = right [default]
/turing-machine:turing-machine/transition-function/delta[label='right summand'] (list instance)
/turing-machine:turing-machine/transition-function/delta[label='right summand']/label = right summand
/turing-machine:turing-machine/transition-function/delta[label='right summand']/input (container)
/turing-machine:turing-machine/transition-function/delta[label='right summand']/input/state = 1
/turing-machine:turing-machine/transition-function/delta[label='right summand']/input/symbol = 1
/turing-machine:turing-machine/transition-function/delta[label='right summand']/output (container)
/turing-machine:turing-machine/transition-function/delta[label='right summand']/output/head-move = right [default]
/turing-machine:turing-machine/transition-function/delta[label='right end'] (list instance)
/turing-machine:turing-machine/transition-function/delta[label='right end']/label = right end
/turing-machine:turing-machine/transition-function/delta[label='right end']/input (container)
/turing-machine:turing-machine/transition-function/delta[label='right end']/input/state = 1
/turing-machine:turing-machine/transition-function/delta[label='right end']/input/symbol =
/turing-machine:turing-machine/transition-function/delta[label='right end']/output (container)
/turing-machine:turing-machine/transition-function/delta[label='right end']/output/state = 2
/turing-machine:turing-machine/transition-function/delta[label='right end']/output/head-move = left
/turing-machine:turing-machine/transition-function/delta[label='write separator'] (list instance)
/turing-machine:turing-machine/transition-function/delta[label='write separator']/label = write separator
/turing-machine:turing-machine/transition-function/delta[label='write separator']/input (container)
/turing-machine:turing-machine/transition-function/delta[label='write separator']/input/state = 2
/turing-machine:turing-machine/transition-function/delta[label='write separator']/input/symbol = 1
/turing-machine:turing-machine/transition-function/delta[label='write separator']/output (container)
/turing-machine:turing-machine/transition-function/delta[label='write separator']/output/state = 3
/turing-machine:turing-machine/transition-function/delta[label='write separator']/output/symbol = 0
/turing-machine:turing-machine/transition-function/delta[label='write separator']/output/head-move = left
/turing-machine:turing-machine/transition-function/delta[label='go home'] (list instance)
/turing-machine:turing-machine/transition-function/delta[label='go home']/label = go home
/turing-machine:turing-machine/transition-function/delta[label='go home']/input (container)
/turing-machine:turing-machine/transition-function/delta[label='go home']/input/state = 3
/turing-machine:turing-machine/transition-function/delta[label='go home']/input/symbol = 1
/turing-machine:turing-machine/transition-function/delta[label='go home']/output (container)
/turing-machine:turing-machine/transition-function/delta[label='go home']/output/head-move = left
/turing-machine:turing-machine/transition-function/delta[label='final step'] (list instance)
/turing-machine:turing-machine/transition-function/delta[label='final step']/label = final step
/turing-machine:turing-machine/transition-function/delta[label='final step']/input (container)
/turing-machine:turing-machine/transition-function/delta[label='final step']/input/state = 3
/turing-machine:turing-machine/transition-function/delta[label='final step']/input/symbol =
/turing-machine:turing-machine/transition-function/delta[label='final step']/output (container)
/turing-machine:turing-machine/transition-function/delta[label='final step']/output/state = 4
/turing-machine:turing-machine/transition-function/delta[label='final step']/output/head-move = right [default]
[INF] Sysrepo plugin daemon initialized successfully.

**Comment by michalvasko** [comment]
Hi,
I do not see any information about `keystored` plugin being loaded so my guess is that you have not installed it in the correct path for `sysrepo-plugind` to find.

Regards,
Michal

**Comment by Arvliu** [comment]
Hi, Michal.
I installed sysrepo first, and then installed keystored and server.

For sysrepo installation, i did not specify the  -DPLUGINS_DIR:PATH, so the default plugins dir should be [/liu_newGcc/sysrepo_arm_Alignment_trap/sysrepo_cross/lib/sysrepo/plugins], and only libturing-machine.so is there.

Then, i installed keystored, and specified  
-DCMAKE_INSTALL_PREFIX=/liu_newGcc/sysrepo_arm_Alignment_trap/Netopeer2_arm/keystored

These operations may caused sysrepo-plugind load keystored plugin failed.

-->What is the correct order of installation? And how to make sysrep-plugind to load keystored?

Looking forward to your reply, and thanks in advance.

PS.
1. cmake parameters of sysrepo installation is:
cmake -DCMAKE_INSTALL_PREFIX=/liu_newGcc/sysrepo_arm_Alignment_trap/sysrepo_cross -DCMAKE_BUILD_TYPE=Release .. -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++  -DUSE_SR_MEM_MGMT=OFF -DYANG_INCLUDE_DIR=/liu_newGcc/libyang_arm/include  -DYANG_LIBRARY="/liu_newGcc/libyang_arm/lib/libyang.so" -DCALL_SYSREPOCTL_BIN=/netconf_arm/sysrepo/build/src/sysrepoctl -DCALL_SYSREPOCFG_BIN=/netconf_arm/sysrepo/build/src/sysrepocfg -DREDBLACK_INCLUDE_DIR=/liu_newGcc/libredblack_arm/include -DREDBLACK_LIBRARY="/liu_newGcc/libredblack_arm/lib/libredblack.so"  -DPROTOBUF-C_INCLUDE_DIR=/liu_newGcc/protobuf-c_arm/include -DPROTOBUF-C_LIBRARY="/liu_newGcc/protobuf-c_arm/lib/libprotobuf-c.so" -DEV_INCLUDE_DIR=/liu_newGcc/libev_arm/include -DEV_LIBRARY="/liu_newGcc/libev_arm/lib/libev.so" -DCMAKE_EXE_LINKER_FLAGS="/liu_newGcc/libpcre_arm/lib/libpcre.so.1" 

2.cmake parameters of keystored installation is:
cmake -DCMAKE_INSTALL_PREFIX=/liu_newGcc/sysrepo_arm_Alignment_trap/Netopeer2_arm/keystored -DCMAKE_BUILD_TYPE=Release ..   -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++ -DSYSREPOCTL_EXECUTABLE=/netconf_arm/sysrepo/build/src/sysrepoctl -DSYSREPOCFG_EXECUTABLE=/netconf_arm/sysrepo/build/src/sysrepocfg -DSYSREPO_INCLUDE_DIR=/liu_newGcc/sysrepo_arm_Alignment_trap/sysrepo_cross/include  -DSYSREPO_LIBRARY="/liu_newGcc/sysrepo_arm_Alignment_trap/sysrepo_cross/lib/libsysrepo.so"

**Comment by michalvasko** [comment]
Hi,
it is quite simple, you just need to install `keystored` into *sysrepo* plugin directory. You say that it is `/liu_newGcc/sysrepo_arm_Alignment_trap/sysrepo_cross/lib/sysrepo/plugins` so, looking at the CMake file, you should configure `keystored` with

```
-DSR_PLUGINS_DIR=/liu_newGcc/sysrepo_arm_Alignment_trap/sysrepo_cross/lib/sysrepo/plugins
```
It seems `CMAKE_INSTALL_PREFIX` does not really do anything because there are no other files being installed except for the plugin. Just do not forget to execute all the scripts so that the required modules are installed in *sysrepo* but based on your `sysrepoctl -l` output it seems you have this covered.

Regards,
Michal

**Comment by Arvliu** [comment]
Hi,

I re-cross compiled sysrepo and keystored with specified DSR_PLUGINS_DIR, the issue is solved.
Thank you very much.

Best regards,
Arvliu.
