### ISSUE TITLE
netopeer2-server asserts with get-config RPC

### ISSUE THREAD

**Issue by iGovindY** [CESNET/Netopeer2#505]
Netopeer2-server asserts with get-config RPC 

Steps to reproduce:
**1. install attached oven(modified) model.**
**2. edit-config with below xml**

```
<oven xmlns="urn:sysrepo:oven" >
    <turned-on>true</turned-on>
    <temperature>123</temperature>
	<make>assisrvana</make>
	<make>commsaacope</make>
	<buttons>
		<name>heaat</name>
		<position>tsdop</position>
	</buttons>
	<buttons>
		<name>microdswave</name>
		<position>dowsdn</position>
	</buttons>
</oven>
```

**3. Do a get-config with below CLI**
```
get-config --source running --filter-xpath /oven:oven/turned-on|/oven:oven/buttons/name|/oven:oven/buttons/position
```

#### CLI Logs
nc ERROR: Session 2: SSH channel poll error (Socket error: disconnected).
cli_send_recv: Failed to receive a reply.

#### Server Logs
[INF]: SR: Processing "/ietf-netconf:get-config" "rpc" event with ID 9 priority 0 (remaining 1 subscribers).
[INF]: SR: Finished processing "rpc" event with ID 9 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 9 priority 0 succeeded.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: NP: Session 2: thread 1 event new RPC.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Session 21 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 10 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:get-config" "rpc" event with ID 10 priority 0 (remaining 1 subscribers).
netopeer2-server: /home/airvana/masif/netconf/libyang/src/xpath.c:1603: set_sort: Assertion `!lyht_find(set->ht, &hnode, hash, ((void *)0))' failed.
Aborted

**4. after that no calls to sysrepo works **
gives below error
[ERR]: Waiting on a conditional variable failed (sr_shmmain_lock_remap: Connection timed out).

### Model in use 
Please note we have added list and leaf-list in oven model for testing.
```
module oven {
    namespace "urn:sysrepo:oven";
    prefix ov;

    revision 2018-01-19 {
        description "Initial revision.";
    }

    typedef oven-temperature {
        description "Temperature range that is accepted by the oven.";
        type uint8 {
            range "0..250";
        }
    }

    container oven {
        description "Configuration container of the oven.";

        leaf turned-on {
            description "Main switch determining whether the oven is on or off.";
            type boolean;
            default false;
        }

        leaf temperature {
            description "Slider for configuring the desired temperature.";
            type oven-temperature;
            default 0;
        }
                leaf-list make {
                        description "Company name."; 
                        type string;
                }
                list buttons {
                        key "name";
                        leaf name {
                                type string;
                        }
                        leaf position {
                                description "Position of the button on the oven.";
                                type string;
                        }
                }
    }
}
```

Please let me know what is the issue here?
Also how to come out of it once the issue has occured? as restaring netopeer server doesn't work.?

Thanks
Govind.

**Comment by michalvasko** [comment]
Hi,
a rare use-case because of the XPath filter you have used. The problem was in *libyang* and when you use the latest `devel`, it should work fine.

Regards,
Michal

**Comment by iGovindY** [comment]
Thanks for the fix, Michal. I will use the changes from `deval`

One more query regarding same issue.
when such errors occur like below in sysrepo.
`[ERR]: Waiting on a conditional variable failed (sr_shmmain_lock_remap: Connection timed out).` 

Any calls to sysrepo don't work at all. what is the recovery procedure once it has happened.

Thanks
Govind.

**Comment by michalvasko** [comment]
Hi,
in case you get to such a situation, you can probably only reset *sysrepo* shared memory. I have just added a `cmake` target `shm_clean` to do just that but you cannot have any running *sysrepo* applications when you execute that. There is also `sr_clean` target but that will in addition remove even all persistent data such as installed modules and all their data.

Regards,
Michal
