### ISSUE TITLE
install server failed

### ISSUE THREAD

**Issue by tonyguo-spirent** [CESNET/Netopeer2#508]
when execute make install for server on 1.1.1 release, there are some erros shown as below, how to solve them?  I use the release version libnetconf2-1.1.3  libyang-1.0.109  Netopeer2-1.1.1  sysrepo-1.3.21
----------------------------------------
[root@localhost build]# make install
[ 81%] Built target serverobj
[100%] Built target netopeer2-server
Install the project...
-- Install configuration: "debug"
-- Up-to-date: /usr/local/bin/netopeer2-server
-- Installing sysrepo modules...
[ERR]: Failed to open "/sr_ietf-netconf.running" (Permission denied).
sysrepoctl error: Failed to connect (System function call failed)
-- Generating a new RSA host key "genkey"...
[ERR]: Failed to open "/sr_ietf-netconf.running" (Permission denied).
sysrepocfg error: Failed to connect (System function call failed)
-- Merging default server listen configuration...
[ERR]: Failed to open "/sr_ietf-netconf.running" (Permission denied).
sysrepocfg error: Failed to connect (System function call failed)

**Comment by brchiu** [comment]
@tonyguo-spirent, I have encountered this issue before. After upgrading to newest `libyang` and `sysrepo` (https://github.com/sysrepo/sysrepo/commit/70454826ced83a3c58eb69a218ec2d1e24f7e0a8) it does not happen again. 

Perhaps you can also upgrade sysrepo and do `make sr_clean` first under `sysrepo/build` directory.

**Comment by tonyguo-spirent** [comment]
Hi, brciu
after I get the latest code, it also has the similar issue
----------------
[ 81%] Built target serverobj
[100%] Built target netopeer2-server
Install the project...
-- Install configuration: "debug"
-- Up-to-date: /usr/local/bin/netopeer2-server
-- Installing sysrepo modules...
[ERR]: Opening "/sr_ietf-netconf.running" SHM failed (Permission denied).
[ERR]: Copying module "ietf-netconf" data from <startup> to <running> failed.
sysrepoctl error: Failed to connect (Initialization failed)
-- Generating a new RSA host key "genkey"...
sysrepocfg error: libyang: Unknown element "keystore".
sysrepocfg error: Data parsing failed
-- Merging default server listen configuration...
sysrepocfg error: libyang: Unknown element "netconf-server".
sysrepocfg error: Data parsing failed

**Comment by michalvasko** [comment]
Hi,
please pull the latest *sysrepo* `devel` and execute `make sr_clean`. Then you should be able to normally install *sysrepo* and *netopeer2* without these permission errors.

Regards,
Michal

**Comment by tonyguo-spirent** [comment]
solved, thanks very much.
