### ISSUE TITLE
how to use netopeer2-cli to communicate with netopeer2-server

### ISSUE THREAD

**Issue by tonyguo-spirent** [CESNET/Netopeer2#509]
I use all default operations complied netopeer2-server and cli, but 
1) I don't know how to make cli access server with interactive password, 
2) I don't know how to use a ssh key to make cli communciate with server.
can you tell me how to do them, and is there a guide for them? thanks very much.

**Comment by michalvasko** [comment]
Hi,
firstly, please include the versions you have used (mainly *netopeer2-server*).

1. What exactly is the problem? Just run `auth --help` command in *netopeer2-cli* and then `connect --help`, you should then know what to do.
2. On the client side, it is just another command with the correct arguments, `auth`. For the server, this depends on the version and is not completely trivial.

Regards,
Michal

**Comment by tonyguo-spirent** [comment]
I use the latest code, by netopeer2-cli, the output is following
----
> version
Netopeer2 CLI 2.0.55
Compile time: Dec 17 2019, 22:09:38
> auth pref
The SSH authentication method preferences:
        'publickey':   0
        'password':    0
        'interactive': 1
> auth pref password 1
> auth pref interactive 0
> connect localhost
nc ERROR: Starting the SSH session failed ().
cmd_connect: Connecting to the localhost:830 as user "root" failed.
> auth pref interactive 1
> connect localhost
nc ERROR: Starting the SSH session failed ().
cmd_connect: Connecting to the localhost:830 as user "root" failed.
--------------------------------------------
and on the server side, the output was following
[INF]: SR: Session 31 (user "root") created.
[2019/12/18 19:56:54.862535, 1] ssh_server_connection_callback:  SSH client banner: SSH-2.0-libssh-0.7.1
[2019/12/18 19:56:54.862565, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-libssh-0.7.1
[2019/12/18 19:56:54.866933, 1] ssh_socket_exception_callback:  Socket exception callback: 1 (0)
[2019/12/18 19:56:54.866959, 1] ssh_socket_exception_callback:  Socket error: disconnected
[ERR]: LN: SSH key exchange error (Socket error: disconnected).
[INF]: LN: Accepted a connection on 0.0.0.0:830.
[INF]: SR: Session 32 (user "root") created.
[2019/12/18 19:57:21.960669, 1] ssh_server_connection_callback:  SSH client banner: SSH-2.0-libssh-0.7.1
[2019/12/18 19:57:21.960697, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-libssh-0.7.1
[2019/12/18 19:57:21.965055, 1] ssh_socket_exception_callback:  Socket exception callback: 1 (0)
[2019/12/18 19:57:21.965080, 1] ssh_socket_exception_callback:  Socket error: disconnected
[ERR]: LN: SSH key exchange error (Socket error: disconnected).
-------------------------
libssh version is libssh-0.7.1-7.el7.x86_64, openssl version was openssl-1.0.2k-19.el7.x86_64

**Comment by tonyguo-spirent** [comment]
I have another question,  I use ssh-keygen generated id_rsa and id_rsa.pub and put them in /root/work, I use auth add keys add them in netopeer2-cli, 
>auth keys
The keys used for SSH authentication:
#0: /root/work/id_rsa.pub (private /root/work/id_rsa)
Can you tell me how to import the id_rsa to netopeer2-server?
thanks very much

**Comment by michalvasko** [comment]
Hi,
I think the problem will be the old *libssh* version. I am planning to fix all these problems but I am not sure when I will get to that, way too much other things to work on. Also, *netopeer2-server* loads known SSH keys from the system, so if you put the key to `/root/.ssh/authorized_keys`, it should automatically be used.

Regards,
Michal

**Comment by tonyguo-spirent** [comment]
Hi, Michal, then which version of libssh will be ok for it?

**Comment by michalvasko** [comment]
Hi,
I am using *libssh* 0.9.2 and *OpenSSL* 1.1.1d but the latest versions should also be fine.

Regards,
Michal

**Comment by tonyguo-spirent** [comment]
Hi, Michal
use the libssh and openssl you mentioned, finally it works. thanks very much
