### ISSUE TITLE
Callback Fail issue

### ISSUE THREAD

**Issue by masif-cs** [CESNET/netopeer2#510]
Hi,

I am trying to fail a RPC intentionally by returning error from code. So I created two files of example application out of which one returns failure from callback function.

After I perform edit-config with below data:

```
<oven xmlns="urn:sysrepo:oven">
    <turned-on>true</turned-on>
    <temperature1>210</temperature1>
</oven>
<oven xmlns="urn:sysrepo:oven2">
    <temperature>210</temperature>
</oven>
```

After this I got expected error:
```
[ERR]: SR: User callback failed
[WRN]: SR: Event "change" with ID 1 priority 0 failed (User callback failed).
[INF]: SR: Published event "abort" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Published event "abort" with ID 1 priority 0 for 0 subscribers.
[INF]: SR: Finished processing "rpc" event (callback fail) with ID 6 priority 0 (remaining 1 subscribers).
[ERR]: SR: User callback failed
[WRN]: SR: Event "rpc" with ID 6 priority 0 failed (User callback failed).
[ERR]: NP: Failed to send an RPC (User callback failed).
```

After this I am trying to do successful edit-config but everytime it is failing with below errors:
```
[ERR]: SR: Callback event processing timed out.
[WRN]: SR: Event "rpc" with ID 7 priority 0 failed (Timeout expired).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 2: thread 1 event new RPC.
[INF]: NP: Session 2: thread 1 event reply error.
[ERR]: SR: Locking subscription of "oven" failed, previous event "abort" with ID 1 was not processed.
[ERR]: SR: Unable to finish processing event with ID 7 priority 0 (timeout probably).
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Session 28 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 8 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 8 priority 0 (remaining 1 subscribers).
[INF]: NP: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[ERR]: SR: Callback event processing timed out.
[WRN]: SR: Event "rpc" with ID 8 priority 0 failed (Timeout expired).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 2: thread 4 event new RPC.
[INF]: NP: Session 2: thread 4 event reply error.
[ERR]: SR: Locking subscription of "oven" failed, previous event "abort" with ID 1 was not processed.
[ERR]: SR: Unable to finish processing event with ID 8 priority 0 (timeout probably).
```

Can you please let me know if this is known issue or I am not doing it properly?

**Comment by michalvasko** [comment]
Hi,
it is hard to say what is happening based on this output only. So, please run `make shm_clean` and then post the exact steps you are doing when the timeout occurs.

Regards,
Michal

**Comment by masif-cs** [comment]
Hi @michalvasko,

I did clean of /dev/shm/ and /etc/sysrepo/ before starting this.

**Comment by michalvasko** [comment]
Hi,
fine, but there is a lot of information missing. How exactly did you modify your `oven` module? To what RPC did you subscribe and what flags have you used? After you have executed the RPC and it failed, did your app continue to run? What edit-config did you then try that it executed another RPC of `oven`?

Regards,
Michal

**Comment by masif-cs** [comment]
Hi @michalvasko,

Here are the changes and the steps:
1. application_changes_example changes:
Here one application remained same other one I added return SR_ERR_INTERNAL on top of the callback function.
2. Two Yang models:
[oven.zip](https://github.com/CESNET/Netopeer2/files/3978442/oven.zip)
3. Used command to start netopeer2 server: netopeer2-server -d -v 2
4: Started example_application on oven and modified example_application on oven2
5: Used command in netopeer2-cli:
connect --tls --host localhost --port 6513 --cert /usr/local/tls_certs/client.crt --key /usr/local/tls_certs/client.key --trusted /usr/local/tls_certs/ca.pem
edit-config --target running --config --error continue
<-- Yang model I already copied in the first comment -->
6: This gave me error posted in first comment
7: No application or server crashed/stopped. All were working fine.
8: Now I gave edit-config on oven only which is subscribed by example_application which doesnt return any error. Expected result was edit-config will pass, but it failed with
```
> edit-config --target running --config
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Callback event processing timed out.
```
Netopeer2-server logs I posted in first comment.

**Comment by michalvasko** [comment]
Hi,
should be fixed now (https://github.com/sysrepo/sysrepo/commit/8072356615a41fc787c4167d558c7e297cd04c1a) but I failed to reference it correctly. There was a problem in *sysrepo*, so that is what you need to update.

Regards,
Michal
