### ISSUE TITLE
about NETCONF subscription 

### ISSUE THREAD

**Issue by chunlovemail** [CESNET/Netopeer2#515]
Hi, 
     I had found that about NETCONF event subscription:
     "one client can ONLY subscribe once, user can NOT subscribe same streams and can NOT subscribe more than one streams in one session"
     So where can i get this standard?  I had check with "rfc5277 NETCONF Event Notifications", still can NOT find this imformation.
     Could u give me some suggestion?

Thanks!
Chun Ye

**Comment by michalvasko** [comment]
Hi,
it is in the RFC you mentioned but unfortunately only indirectly. If a server does not support the `interleave` capability, it is not able to process any further RPCs meaning not even another `<create-subscription>`. And even if this capability is supported, [this RPC cannot be processed again](https://tools.ietf.org/html/rfc5277#section-6.5).

Regards,
Michal

**Comment by chunlovemail** [comment]
Hi,

    Thank u very much, it helps me a lot.
