### ISSUE TITLE
Can Netopeer2 work well without NC_ENABLED_SSH or NC_ENABLED_TLS options？

### ISSUE THREAD

**Issue by Julian-younger** [CESNET/Netopeer2#516]

**Comment by Julian-younger** [comment]
We have openssh in our system,and we do not want to use build-in libssh. Can we run Netopeer2 without NC_ENABLED_SSH or NC_ENABLED_TLS options?Thanks.

**Comment by michalvasko** [comment]
Hi,
unfortunately, *netopeer2* requires `NC_ENABLED_SSH` and can only run with *libssh*. If you want to use OpenSSH (`sshd(7)`), *libnetconf2* supports it but you would have to write your own server.

Regards,
Michal

**Comment by Julian-younger** [comment]
All right.Thank for your reply,michalvasko.
