### ISSUE TITLE
netopeer2-server crash

### ISSUE THREAD

**Issue by jiantuo** [CESNET/netopeer2#518]
Hi , I have a netopeer2-server crash issue.
my netopeer2-server crash every time when I received a rpc from the management.
But it works well with my own netopeer2-cli.
the rpc command is:
> user-rpc --content watchdog-reset.xml

for the management,which version info is:

> [root@mavdu yang]# netopeer2-server -V
> netopeer2-server 0.5.22
> compile time: Oct 18 2019, 06:22:49
> [root@mavdu yang]# sysrepoctl -v
> sysrepoctl - sysrepo control tool, version 0.7.4
>  
> [root@mavdu yang]# sysrepod -v
> sysrepod - sysrepo daemon, version 0.7.4
>  
> [root@mavdu yang]# sysrepo-plugind -v
> sysrepo-plugind - sysrepo plugins daemon, version 0.7.4
>  
> [root@mavdu yang]# netopeer2-server -V
> netopeer2-server 0.5.22
> compile time: Oct 18 2019, 06:22:49
> [root@mavdu yang]# netopeer2-cli
> > version
> Netopeer2 CLI 2.0.47
> Compile time: Oct 18 2019, 06:22:51
> > 

my device version info is:

> root@fe54d3cf735e:/opt/dev# sysrepoctl -v
> sysrepoctl - sysrepo control tool, version 0.7.8
> root@fe54d3cf735e:/opt/dev# sysrepod -v
> sysrepod - sysrepo daemon, version 0.7.8
> root@fe54d3cf735e:/opt/dev# sysrepo-plugind -v
> sysrepo-plugind - sysrepo plugins daemon, version 0.7.8
> root@fe54d3cf735e:/opt/dev# netopeer2-server -V
> netopeer2-server 0.7.15
> compile time: Sep 27 2019, 09:16:46
> root@fe54d3cf735e:/opt/dev# netopeer2-cli
> > version
> Netopeer2 CLI 2.0.52
> Compile time: Sep 27 2019, 09:16:50
> > 
.
please find the yang file, xml file
[watchdog-reset.xml.txt](https://github.com/CESNET/Netopeer2/files/4005099/watchdog-reset.xml.txt)
[xran-supervision.yang.txt](https://github.com/CESNET/Netopeer2/files/4005100/xran-supervision.yang.txt)
[core dump.zip](https://github.com/CESNET/Netopeer2/files/4005101/core.dump.zip)
[log-before-crash.txt](https://github.com/CESNET/Netopeer2/files/4005154/log-before-crash.txt)

 and logs and core dump file as attachment.
Need you help.
Thanks

**Comment by michalvasko** [comment]
Hi,
you are using an ancient version of the old *sysrepo* so I really do not have the time to debug it. More importantly, you yourself said it works with your newer *sysrepo* version 0.7.8 so it was obviously fixed and I am not sure what support you expect exactly.

Regards,
Michal

**Comment by jiantuo** [comment]
Hi Michal,
the netconf client does use a rather ancient version of sysrepo, and this is beyond our control.
which confused me a lot is, the netconf client side's ancient version of libnetconf2 makes netopeer2-server 0.7.15 crash.

**Comment by michalvasko** [comment]
Hi,
you are right, this should not ideally happen but it is hard to say where exactly is the problem. Could you maybe provide the backtrace of the crash? Or at least the exact *libnetconf2* version so that I can load the core dump and see it there?

Regards,
Michal

**Comment by jiantuo** [comment]
Hi，
libnetconf2 Version: 0.11.37.
the core dump file I uploaded is for arm architecture, gcc is arm-linux-gnueabihf-gcc.
because of platform limit, did not have backtrace.

**Comment by michalvasko** [comment]
Hi,
oh, then the core dump is of no use to me and I am not able to help at all.

Regards,
Michal

**Comment by jiantuo** [comment]
tried to parse the core,hope will have some help：

```
root@am335x-evm:/netopeer2_server# gdb netopeer2-server core
GNU gdb (GDB) 8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from netopeer2-server...done.

warning: core file may not match specified executable file.
[New LWP 585]
[New LWP 583]
[New LWP 580]
[New LWP 581]
[New LWP 582]
[New LWP 584]

warning: .dynamic section for "/lib/libpcre.so.1" is not at the expected address (wrong library or version mismatch?)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
Core was generated by `netopeer2-server -d -v 2'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xb696cbd4 in nc_session_free () from /lib/libnetconf2.so.0.12
[Current thread is 1 (Thread 0xb44fc450 (LWP 585))]
(gdb) 
```

**Comment by michalvasko** [comment]
Hi,
you do not even have debugging symbols enabled so this not help much, sorry.

Regards,
Michal

**Comment by jiantuo** [comment]
Hi Michal,

Have more info, please have a check.

**Comment by michalvasko** [comment]
Hi,
okay, thanks for the backtrace, it should now be covered in the latest *libnetconf2* `devel`.

Regards,
Michal

**Comment by jiantuo** [comment]
Thanks Michal for quick response.
The fix works.
