### ISSUE TITLE
Where can I find how enable TLS for Call Home?

### ISSUE THREAD

**Issue by eraonel** [CESNET/netopeer2#527]
Hi,

I managed to get call home for SSH working with Docker instance using the developer branch.
Really nice feature!
Now I need to  implement SSL/TLS support for Call Home in my java client and I found out that there is support for it in netopeer2 server. Sounds excellent!

I found this information:
https://github.com/CESNET/Netopeer2/tree/devel-server/server

"Using the same certificates and authorization options, a TLS client can be connected to using Call Home when tls_callhome.xml file is imported. But tls_keystore.xml and tls_truststore.xml need to be imported first."

Questions:

1. Is there a guide for it?
2. Using "edit-config --target running --config" can I add all the information in  tls_callhome.xml,  tls_keystore.xml and tls_truststore.xml into the vi-window that opens up?
Do I need to have them in specific order? Or must I commit each of them?

br,

//mikael

**Comment by michalvasko** [comment]
Hi,
1. Nothing more than you have already found. Each configuration value is explained in the corresponding model.

2. Yes, if using *netopeer2--cli*, you can simply paste those XMLs and that is it. Apply `tls_truststore.xml` and `tls_keystore.xml` before `tls_callhome.xml`, otherwise you should get a validation error.

This way your NETCONF server should be set, but in order to connect with a client, it must present the certificates from `netopeer2/server/example_configuration/tls_certs` (client ones).

Regards,
Michal

**Comment by eraonel** [comment]
Hi,
tls_keystore.xml worked fine but when I try tls_truststore.xml I get:
edit-config --target running --config
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        path:     /ietf-truststore:truststore/certificates[name='clientcerts']/certificate[name='clientcert']/cert
        message:  Invalid Base64 character.
The only possible problem I could see was missing == at the end of cert ( see below). However it did not solve problem. What is the decoder expecting? Have you tried it?

br,

//mikael


`MIIECTCCAvGgAwIBAgIBBzANBgkqhkiG9w0BAQsFADCBjDELMAkGA1UEBhMCQ1ox
FjAUBgNVBAgMDVNvdXRoIE1vcmF2aWExDTALBgNVBAcMBEJybm8xDzANBgNVBAoM
BkNFU05FVDEMMAoGA1UECwwDVE1DMRMwEQYDVQQDDApleGFtcGxlIENBMSIwIAYJ
KoZIhvcNAQkBFhNleGFtcGxlY2FAbG9jYWxob3N0MB4XDTE1MDczMDA3MjcxOFoX
DTM1MDcyNTA3MjcxOFowgYUxCzAJBgNVBAYTAkNaMRYwFAYDVQQIDA1Tb3V0aCBN
b3JhdmlhMQ8wDQYDVQQKDAZDRVNORVQxDDAKBgNVBAsMA1RNQzEXMBUGA1UEAwwO
ZXhhbXBsZSBjbGllbnQxJjAkBgkqhkiG9w0BCQEWF2V4YW1wbGVjbGllbnRAbG9j
YWxob3N0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAueCQaNQWoNmF
K6LKu1p8U8ZWdWg/PvDdLsJyzfzl/Qw4UA68SfFNaY06zZl8QB9W02nr5kWeeMY0
VA3adrPgOlvfx3oWlFbkETnMaN4OT3WTQ0Wt6jAWZDzVfopwpJPAzRPxACDftIqF
GagYcF32hZlVNqqnVdbXh0S0EViweqp/dbG4VDUHSNVbglc+u4UbEzNIFXMdEFsJ
ZpkynOmSiTsIATqIhb+2srkVgLwhfkC2qkuHQwAHdubuB07ObM2z01UhyEdDvEYG
HwtYAGDBL2TAcsI0oGeVkRyuOkV0QY0UN7UEFI1yTYw+xZ42HgFx3uGwApCImxhb
j69GBYWFqwIDAQABo3sweTAJBgNVHRMEAjAAMCwGCWCGSAGG+EIBDQQfFh1PcGVu
U1NMIEdlbmVyYXRlZCBDZXJ0aWZpY2F0ZTAdBgNVHQ4EFgQUXGpLeLnh2cSDARAV
A7KrBxGYpo8wHwYDVR0jBBgwFoAUc1YQIqjZsHVwlea0AB4N+ilNI2gwDQYJKoZI
hvcNAQELBQADggEBAJPV3RTXFRtNyOU4rjPpYeBAIAFp2aqGc4t2J1c7oPp/1n+l
ZvjnwtlJpZHxMM783e2ryDQ6dkvXDf8kpwKlg3U3mkJ3xKkDdWrM4QwghXdCN519
aa9qmu0zdFL+jUAaWlQ5tsceOrvbusCcbMqiFGk/QfpHqPv52SVWbYyUx7IX7DE+
UjgsLHycfV/tlcx4ZE6soTzl9VdgSL/zmzG3rjsr58J80rXckLgBhvijgBlIAJvW
fC7D0vaouvBInSFXymdPVoUDZ30cdGLf+hI/i/TfsEMOinLrXVdkSGNo6FXAHKSv
XeB9oFKSzhQ7OPyRyqvEPycUSw/qD6FVr80oDDc=`

**Comment by michalvasko** [comment]
Hi,
I have tried, of course, and did so again, it worked fine. Maybe you have pasted the XML incorrectly? Try using
```
edit-config --target running --config=tls_truststore.xml
```

Regards,
Michal

**Comment by eraonel** [comment]
Hi
I took the base64 encoded strings and fixed them using:
https://base64.guru/tools/repair
and it resulted into:
`<truststore xmlns="urn:ietf:params:xml:ns:yang:ietf-truststore">
    <certificates>
        <name>clientcerts</name>
        <certificate>
            <name>clientcert</name>
            <cert>MIIECTCCAvGgAwIBAgIBBzANBgkqhkiG9w0BAQsFADCBjDELMAkGA1UEBhMCQ1oxFjAUBgNVBAgMDVNvdXRoIE1vcmF2aWExDTALBgNVBAcMBEJybm8xDzANBgNVBAoMBkNFU05FVDEMMAoGA1UECwwDVE1DMRMwEQYDVQQDDApleGFtcGxlIENBMSIwIAYJKoZIhvcNAQkBFhNleGFtcGxlY2FAbG9jYWxob3N0MB4XDTE1MDczMDA3MjcxOFoXDTM1MDcyNTA3MjcxOFowgYUxCzAJBgNVBAYTAkNaMRYwFAYDVQQIDA1Tb3V0aCBNb3JhdmlhMQ8wDQYDVQQKDAZDRVNORVQxDDAKBgNVBAsMA1RNQzEXMBUGA1UEAwwOZXhhbXBsZSBjbGllbnQxJjAkBgkqhkiG9w0BCQEWF2V4YW1wbGVjbGllbnRAbG9jYWxob3N0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAueCQaNQWoNmFK6LKu1p8U8ZWdWg/PvDdLsJyzfzl/Qw4UA68SfFNaY06zZl8QB9W02nr5kWeeMY0VA3adrPgOlvfx3oWlFbkETnMaN4OT3WTQ0Wt6jAWZDzVfopwpJPAzRPxACDftIqFGagYcF32hZlVNqqnVdbXh0S0EViweqp/dbG4VDUHSNVbglc+u4UbEzNIFXMdEFsJZpkynOmSiTsIATqIhb+2srkVgLwhfkC2qkuHQwAHdubuB07ObM2z01UhyEdDvEYGHwtYAGDBL2TAcsI0oGeVkRyuOkV0QY0UN7UEFI1yTYw+xZ42HgFx3uGwApCImxhbj69GBYWFqwIDAQABo3sweTAJBgNVHRMEAjAAMCwGCWCGSAGG+EIBDQQfFh1PcGVuU1NMIEdlbmVyYXRlZCBDZXJ0aWZpY2F0ZTAdBgNVHQ4EFgQUXGpLeLnh2cSDARAVA7KrBxGYpo8wHwYDVR0jBBgwFoAUc1YQIqjZsHVwlea0AB4N+ilNI2gwDQYJKoZIhvcNAQELBQADggEBAJPV3RTXFRtNyOU4rjPpYeBAIAFp2aqGc4t2J1c7oPp/1n+lZvjnwtlJpZHxMM783e2ryDQ6dkvXDf8kpwKlg3U3mkJ3xKkDdWrM4QwghXdCN519aa9qmu0zdFL+jUAaWlQ5tsceOrvbusCcbMqiFGk/QfpHqPv52SVWbYyUx7IX7DE+UjgsLHycfV/tlcx4ZE6soTzl9VdgSL/zmzG3rjsr58J80rXckLgBhvijgBlIAJvWfC7D0vaouvBInSFXymdPVoUDZ30cdGLf+hI/i/TfsEMOinLrXVdkSGNo6FXAHKSvXeB9oFKSzhQ7OPyRyqvEPycUSw/qD6FVr80oDDc=</cert>
        </certificate>
    </certificates>
    <certificates>
        <name>cacerts</name>
        <certificate>
            <name>cacert</name>
            <cert>MIID7TCCAtWgAwIBAgIJAMtE1NGAR5KoMA0GCSqGSIb3DQEBBQUAMIGMMQswCQYDVQQGEwJDWjEWMBQGA1UECAwNU291dGggTW9yYXZpYTENMAsGA1UEBwwEQnJubzEPMA0GA1UECgwGQ0VTTkVUMQwwCgYDVQQLDANUTUMxEzARBgNVBAMMCmV4YW1wbGUgQ0ExIjAgBgkqhkiG9w0BCQEWE2V4YW1wbGVjYUBsb2NhbGhvc3QwHhcNMTQwNzI0MTQxOTAyWhcNMjQwNzIxMTQxOTAyWjCBjDELMAkGA1UEBhMCQ1oxFjAUBgNVBAgMDVNvdXRoIE1vcmF2aWExDTALBgNVBAcMBEJybm8xDzANBgNVBAoMBkNFU05FVDEMMAoGA1UECwwDVE1DMRMwEQYDVQQDDApleGFtcGxlIENBMSIwIAYJKoZIhvcNAQkBFhNleGFtcGxlY2FAbG9jYWxob3N0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArD3TDHPAMT2Z84orK4lMlarbgooIUCcRZyLe+QM+8KY8Hn+mGaxPEOTSL3ywszqefB/Utm2hPKLHX684iRC14ID9WDGHxPjvoPArhgFhfV+qnPfxKTgxZC12uOj4u1V9y+SkTCocFbRfXVBGpojrBuDHXkDMDEWNvr8/52YCv7bGaiBwUHolcLCUbmtKILCG0RNJyTaJpXQdAeq5Z1SJotpbfYFFtAXB32hVoLug1dzl2tjG9sb1wq3QaDExcbC5w6P65qOkNoyym9ne6QlQagCqVDyFn3vcqkRaTjvZmxauCeUxXgJoXkyWcm0lM1KMHdoTArmchw2Dz0yHHSyDAQIDAQABo1AwTjAdBgNVHQ4EFgQUc1YQIqjZsHVwlea0AB4N+ilNI2gwHwYDVR0jBBgwFoAUc1YQIqjZsHVwlea0AB4N+ilNI2gwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQUFAAOCAQEAI/1KH60qnw9Xs2RGfi0/IKf5EynXt4bQX8EIyVKwSkYKe04zZxYfLIl/Q2HOPYoFmm3daj5ddr0ZS1i4p4fTUhstjsYWvXs3W/HhVmFUslakkn3PrswhP77fCk6eEJLxdfyJ1C7Uudq2m1isZbKih+XF0mG1LxJaDMocSz4eAya7M5brwjy8DoOmA1TnLQFCVcpn+sCr7VC4wE/JqxyVhBCk/MuGqqM3B1j90bGFZ112ZOecyE0EDSr6IbiRBtmeNbEwOFjKXhNLYdxpBZ9D8A/368OckZkCrVLGuJNxK9UwCVTe8IhotHUqU9EqFDmxdV8oIdU/OzUwwNPA/Bd/9g==</cert>
        </certificate>
    </certificates>
</truststore>`

And vola it worked!

**Comment by eraonel** [comment]
Hi again,
Just one follow-up question.
In last file https://raw.githubusercontent.com/CESNET/Netopeer2/master/server/example_configuration/tls_callhome.xml
there is a <fingerprint>02:E9:38:1F:F6:8B:62:DE:0A:0B:C5:03:81:A8:03:49:A0:00:7F:8B:F3</fingerprint>
How was that generated? Or is it static? 

br,

//mikael

**Comment by michalvasko** [comment]
Hi,
as for your fix, that is quite interesting because I used to have problems when I did not include those newlines. But it is just formatting, the content itself is the same.

As for your other question, the value should be self-describing if you look at the model. But to answer you, I got it when I opened the certificate using `View file` on my OpenSUSE, not sure what the utility is exactly. But I am pretty sure any certificate viewer can calculate the fingerprint.

Regards,
Michal

**Comment by eraonel** [comment]
Hi,
Yes content is the same. So no big issue.

I don't really have a good way of looking at the model. I am working on windows :-)
But I guess I can find it out.

I have managed to start with Docker and get log to std out but I get a lot of annoying:

```
[DBG]: LN: PS 0x0x55f159c5d0c0 TID 140326068119296 queue: added 0, head 0, lenght 1
[DBG]: LN: PS 0x0x55f159c5d0c0 TID 140326068119296 queue: removed 0, head 0, lenght 0
[DBG]: LN: PS 0x0x55f159c5d0c0 TID 140326059726592 queue: added 0, head 0, lenght 1
[DBG]: LN: PS 0x0x55f159c5d0c0 TID 140326059726592 queue: removed 0, head 0, lenght 0
[DBG]: LN: PS 0x0x55f159c5d0c0 TID 140326177752960 queue: added 0, head 0, lenght 1
[DBG]: LN: PS 0x0x55f159c5d0c0 TID 140326177752960 queue: removed 0, head 0, lenght 0
[DBG]: LN: PS 0x0x55f159c5d0c0 TID 140326084904704 queue: added 0, head 0, lenght 1
[DBG]: LN: PS 0x0x55f159c5d0c0 TID 140326084904704 queue: removed 0, head 0, lenght 0
[DBG]: LN: PS 0x0x55f159c5d0c0 TID 140326076512000 queue: added 0, head 0, lenght 1
[DBG]: LN: PS 0x0x55f159c5d0c0 TID 140326076512000 queue: removed 0, head 0, lenght 0
[DBG]: LN: PS 0x0x55f159c5d0c0 TID 140326068119296 queue: added 0, head 0, lenght 1
[DBG]: LN: PS 0x0x55f159c5d0c0 TID 140326068119296 queue: removed 0, head 0, lenght 0
[DBG]: LN: PS 0x0x55f159c5d0c0 TID 140326059726592 queue: added 0, head 0, lenght 1
[DBG]: LN: PS 0x0x55f159c5d0c0 TID 140326059726592 queue: removed 0, head 0, lenght 0
[DBG]: LN: PS 0x0x55f159c5d0c0 TID 140326177752960 queue: added 0, head 0, lenght 1
[DBG]: LN: PS 0x0x55f159c5d0c0 TID 140326177752960 queue: removed 0, head 0, lenght 0
[DBG]: LN: PS 0x0x55f159c5d0c0 TID 140326084904704 queue: added 0, head 0, lenght 1
[DBG]: LN: PS 0x0x55f159c5d0c0 TID 140326084904704 queue: removed 0, head 0, lenght 0
[DBG]: LN: PS 0x0x55f159c5d0c0 TID 140326076512000 queue: added 0, head 0, lenght 1
[DBG]: LN: PS 0x0x55f159c5d0c0 TID 140326076512000 queue: removed 0, head 0, lenght 0
[DBG]: LN: PS 0x0x55f159c5d0c0 TID 140326068119296 queue: added 0, head 0, lenght 1
[DBG]: LN: PS 0x0x55f159c5d0c0 TID 140326068119296 queue: removed 0, head 0, lenght 0
```

When I use:
` /usr/local/bin/netopeer2-server -d -c MSG,SSH`

So it is hard to see the messages sent.
Is there a log file I can use?

br,

//mikael

**Comment by michalvasko** [comment]
Hi,
right, that is expected. Well, you can always log everything into a file and it is much easier to see that way. Also, you can then filter out some messages easily. I do not feel like rewriting logging in *libnetconf2* right now.

Regards,
Michal

**Comment by michalvasko** [comment]
The periodic messages are no longer enabled on debug log level.
