### ISSUE TITLE
Can't import ssh_callhome.xml

### ISSUE THREAD

**Issue by Georgigt23** [CESNET/netopeer2#528]
Hi, i am trying to enable call home feature,
with netopeer2-cli i am sending edit-config rpc with the content of  ssh_callhome.xml, but this is what i get:

ERROR
	type:     protocol
	tag:      unknown-element
	severity: error
	message:  Unknown element "call-home".
	bad-elem #1: /ietf-netconf-server:netconf-server/call-home

Thanks.
Georgi

**Comment by michalvasko** [comment]
Hi,
what *netopeer2-server* version are you using? But based on the error I would guess 0.7.x. In that case read [README](https://github.com/CESNET/Netopeer2/blob/legacy/server/configuration/README.md) to learn about how to enable Call Home. If you do not succeed, just use the current 1.x version, it is much simpler there and you should be using that one, anyway.

Regards,
Michal

**Comment by Georgigt23** [comment]
I followed the steps in the README, but it gave the same error again. I checked in logs and this is what i saw: 
[ERR] Feature state can not be modified because 3 is using the module
[ERR] Failed to enable feature 'call-home' in module 'ietf-netconf-server'.

Is there a way to see who is using ietf-netconf-server?

**Comment by michalvasko** [comment]
Hi,
I think only `netopeer2-server` actually subscribes to (uses) this module, try stopping it before changing the feature.

Regards,
Michal

**Comment by Georgigt23** [comment]
I tried disabling netopeer2-server and enabling the feature, but it still doesn't work.

I forgot to mention that those errors i get from executing:
sysrepoctl --feature-enable=call-home --module=ietf-netconf-server

I also tried:
sysrepocfg --merge=/tmp/ssh_callhome.xml --format=xml ietf-netconf-server

Those errors occur:
[ERR] Set item failed
[ERR] Set item failed for '/ietf-netconf-server:netconf-server/call-home/netconf-client[name='test_ssh_ch_client']'

**Comment by michalvasko** [comment]
HI,
are you executing `sysrepoctl --feature-enable=call-home --module=ietf-netconf-server` manually? That is **not** what the README told you to do. If you follow what is written there, then I can help you in case something does not work.

Regards,
Michal

**Comment by Georgigt23** [comment]
HI,
I appreciate your help, i managed to enable call-home by stopping sysrepod, sysrepo.plugind and netopeer2-server and after that i enabled the feature manually

Regards,
Georgi

**Comment by michalvasko** [comment]
I do not think that will work because there is a reason why it was not enabled automatically (probably not installed `keystored`) but that is your problem. Just don't report issues when some keys or certificates cannot be found unless you let it be enabled during installation.

Regards,
Michal
