### ISSUE TITLE
Format of client crt and key files

### ISSUE THREAD

**Issue by eraonel** [CESNET/Netopeer2#530]
Hi,

1 .What is the format of client certificate and private key?
2. How were they generated?

br,

//mikael

**Comment by michalvasko** [comment]
Hi,
I am not sure what exactly are you asking. All the certificates and keys are in PEM format, which is actually ASN.1 DER format encoded with base64. They were generated by `openssl(1)` but I will not tell you the exact commands, it was quite some time ago. However, most information (if not all) should be stored in the files themselves (algorithms used, ...), just use some utility that can read them. Other than that, `ca` is the certificate authority (self-signed) that was used to create `server` and `client` certificates, so it must be configured as trusted in whatever software you want to use it.

Regards,
Michal

**Comment by eraonel** [comment]
Hi
That is exactly what I wanted to know. I have now been able to establish a TLS connection using Call Home.
`[INF]: SR: Session 826 (user "root") created.
[INF]: SR: Session 827 (user "root") created.
[INF]: SR: Session 828 (user "root") created.
[INF]: LN: Cert verify: depth 1.
[INF]: LN: Cert verify: subject: /C=CZ/ST=South Moravia/L=Brno/O=CESNET/OU=TMC/CN=example CA/emailAddress=exampleca@localhost.
[INF]: LN: Cert verify: issuer:  /C=CZ/ST=South Moravia/L=Brno/O=CESNET/OU=TMC/CN=example CA/emailAddress=exampleca@localhost.
[INF]: LN: Cert verify CTN: entry with a matching fingerprint found.
[INF]: LN: Cert verify CTN: new client username recognized as "tls-test".
[INF]: LN: Cert verify: depth 0.
[INF]: LN: Cert verify: subject: /C=CZ/ST=South Moravia/O=CESNET/OU=TMC/CN=example client/emailAddress=exampleclient@localhost.
[INF]: LN: Cert verify: issuer:  /C=CZ/ST=South Moravia/L=Brno/O=CESNET/OU=TMC/CN=example CA/emailAddress=exampleca@localhost.
[INF]: LN: Call Home client "default-client" session 11 established.
[INF]: SR: Session 829 (user "root") created.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-start).
[INF]: NP: Session 11: thread 4 event new RPC.
[INF]: NP: Session 11: thread 4 event session terminated.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-end).
[INF]: LN: Call Home client "default-client" session terminated, reconnecting...`

I guess this above proves I got a TLS connection. Right?

**Comment by michalvasko** [comment]
Hi,
yep, from the log it seems the Call Home session was established and then the client terminated it.

Regards,
Michal
