### ISSUE TITLE
Can't connect to netopeer2-server (another query with similar name)

### ISSUE THREAD

**Issue by igortern** [CESNET/Netopeer2#534]
Hi Michal,

I've a 3rd party NETCONF client that works fine with the old netopeer2-server, but I'm unable to connect with the new one.
Versions:
- libyang, sysrepo, libnetconf2: devel  (today's snapshot)
- libssh 0.9.2
When client attempts to connect, there are the following messages in netopeer2-server log

[INF]: LN: Accepted a connection on 0.0.0.0:10830.
[INF]: SR: Session 62 (user "root") created.
[2020/01/22 12:42:27.762834, 2] ssh_pki_import_privkey_base64:  Trying to decode privkey passphrase=false
[2020/01/22 12:42:27.763182, 1] pki_private_key_from_base64:  Parsing private key
[ERR]: LN: Failed to set hostkey "genkey" (/tmp/qVSFOM).

Do you have any advice what to check?

Thanks,
Igor

**Comment by michalvasko** [comment]
Hi Igor,
what OpenSSL version do you use? The only thing you can try that I can think of is manually edit the generated key in `ietf-keystore` and remove all the newlines in the keys themselves. Recently someone else may have had a similar problem and this fixed it.

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,

The problem only manifests if libssh is built with gcrypt (WITH_GCRYPT=ON).
If libssh is using openssl for cryptography - it works.
I guess the genkey should be generated differently depending on the
discovered libssh configuration.
This issue is no longer pressing for me though, since I found configuration
that works.

Thanks,
Igor

**Comment by michalvasko** [comment]
Hi Igor,
thanks for the information. So you did not try my suggestion and you do not know how to fix the problem when using *gcrypt*?

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,

I didn't try to remove line endings, but before switching to openssl I
added debug prints in libssh module pki_gcrypt.c (which is compiled instead
of pki_crypto.c when gcrypt is used).
From the prints and also comparing pki_gcrypt.c with pki_crypto.c, they
appear to expect the key in different formats. genkey format is compatible
with pki_cripto.c, but not with pki_gcrypt.c
I might be wrong - not my area of expertise.

Thanks,
Igor

**Comment by michalvasko** [comment]
Thanks for the information, I will further inquire on *libssh* mailing list.

Regards,
Michal

**Comment by vpatodia** [comment]
Hi Igor,

I am facing same issue. Which configuration did you change to avoid this issue ? 

Thanks,
Vishwas

**Comment by igortern** [comment]
Hi Vishwas,

I built libssh with option -DWITH_GCRYPT=OFF. In this case it uses openssh.

Regards,
Igor

**Comment by vpatodia** [comment]
Igor,

This works for me.

Thanks
Vishwas

**Comment by jabilmplane** [comment]
Hi all. I have the same problem. I've tried to delete line endings in ssh keys, but it doesn't help...

**Comment by kuailedeluojie-sudo** [comment]
![image](https://user-images.githubusercontent.com/60098441/90623873-b7a8bb80-e249-11ea-9cda-43ef19a0dda0.png)
Trying to use these methods is still not solved.
![image](https://user-images.githubusercontent.com/60098441/90623934-c7280480-e249-11ea-9d96-5d93e164e713.png)

![image](https://user-images.githubusercontent.com/60098441/90624020-e6bf2d00-e249-11ea-9b1d-659d5996867c.png)

Now, I have this problem.

**Comment by michalvasko** [comment]
Hi,
that is a problem of some kind with your *libssh* or its crypto backend (depends, most often *openssl*). It is not able to parse a private key for some reason.

**Comment by kuailedeluojie-sudo** [comment]
![image](https://user-images.githubusercontent.com/60098441/90847386-f438fc00-e39c-11ea-9923-4f4f743a119e.png)
thank you! So what options should I add when compiling OpenSSL?

**Comment by michalvasko** [comment]
Hi,
I cannot help you more with this, I have never compiled OpenSSL by hand.
