### ISSUE TITLE
netopeer2-server/sysrepo rejects valid rpc

### ISSUE THREAD

**Issue by igortern** [CESNET/Netopeer2#537]
Hi,
The new netopeer2-server / sysrepo rejects valid RPC which is a part of the initial handshake with NETCONF client. The same scenario works with the old netopeer2-server.

- versions: netopeer2-server. libyang, libnetconf2, sysrepo from devel. Snapshots taken on Jan 23
- shm_mem was cleaned before the test
- The problematic request/response sequence is below, marked "====RPC exchange" 
- The yang models bundle is attached to [https://github.com/sysrepo/sysrepo/issues/1720]
- netopeer2-server log is below, marked ====netopeer2-server

Please let me know what additional information to collect to help reproduce the issue.

Regards,
Igor

====RPC exchange
\<rpc message-id="5" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  \<copy-config>
    \<target>
      \<running/>
    \</target>
    \<source>
      \<config>
        <bbf-qos-filt:filters xmlns:bbf-qos-filt="urn:bbf:yang:bbf-qos-filters"/>
        <bbf-lt:link-table xmlns:bbf-lt="urn:bbf:yang:bbf-link-table"/>
        <ipfix:ipfix xmlns:ipfix="urn:ietf:params:xml:ns:yang:ietf-ipfix-psamp"/>
        <hw:hardware xmlns:hw="urn:ietf:params:xml:ns:yang:ietf-hardware"/>
        <bbf-qos-cls:classifiers xmlns:bbf-qos-cls="urn:bbf:yang:bbf-qos-classifiers"/>
        <pw:pseudowires xmlns:pw="urn:ietf:params:xml:ns:yang:ietf-pseudowires"/>
        <bbf-xpon:xpon xmlns:bbf-xpon="urn:bbf:yang:bbf-xpon"/>
        <bbf-ghn:ghn xmlns:bbf-ghn="urn:bbf:yang:bbf-ghn"/>
        <bbf-qos-pol:qos-policy-profiles xmlns:bbf-qos-pol="urn:bbf:yang:bbf-qos-policies"/>
        <al:alarms xmlns:al="urn:ietf:params:xml:ns:yang:ietf-alarms"/>
        <bbf-vdsl:vdsl xmlns:bbf-vdsl="urn:bbf:yang:bbf-vdsl"/>
        <bbf-xpongemtcont:xpongemtcont xmlns:bbf-xpongemtcont="urn:bbf:yang:bbf-xpongemtcont"/>
        <sys:system xmlns:sys="urn:ietf:params:xml:ns:yang:ietf-system"/>
        <bbf-qos-plc-ep:envelope-profiles xmlns:bbf-qos-plc-ep="urn:bbf:yang:bbf-qos-policer-envelope-profiles"/>
        <bbf-ghs:ghs xmlns:bbf-ghs="urn:bbf:yang:bbf-ghs"/>
        <if:interfaces xmlns:if="urn:ietf:params:xml:ns:yang:ietf-interfaces"/>
        <bbf-qos-pol:policies xmlns:bbf-qos-pol="urn:bbf:yang:bbf-qos-policies"/>
        <bbf-qos-tm:tm-profiles xmlns:bbf-qos-tm="urn:bbf:yang:bbf-qos-traffic-mngt"/>
        <bbf-qos-plc:policing-profiles xmlns:bbf-qos-plc="urn:bbf:yang:bbf-qos-policing"/>
        <bbf-selt:selt xmlns:bbf-selt="urn:bbf:yang:bbf-selt"/>
        <bbf-l2-d4r:l2-dhcpv4-relay-profiles xmlns:bbf-l2-d4r="urn:bbf:yang:bbf-l2-dhcpv4-relay"/>
        <dot1x:nid-group xmlns:dot1x="urn:ieee:std:802.1X:yang:ieee802-dot1x"/>
        <nacm:nacm xmlns:nacm="urn:ietf:params:xml:ns:yang:ietf-netconf-acm"/>
        <bbf-hw-rpf-dpu:rpf xmlns:bbf-hw-rpf-dpu="urn:bbf:yang:bbf-hardware-rpf-dpu"/>
        <bbf-pppoe-ia:pppoe-profiles xmlns:bbf-pppoe-ia="urn:bbf:yang:bbf-pppoe-intermediate-agent"/>
        <bbf-fast:fast xmlns:bbf-fast="urn:bbf:yang:bbf-fast"/>
        <bbf-mgmd:multicast xmlns:bbf-mgmd="urn:bbf:yang:bbf-mgmd"/>
        <bbf-melt:melt xmlns:bbf-melt="urn:bbf:yang:bbf-melt"/>
        <bbf-subprof:subscriber-profiles xmlns:bbf-subprof="urn:bbf:yang:bbf-subscriber-profiles"/>
        <bbf-ldra:dhcpv6-ldra-profiles xmlns:bbf-ldra="urn:bbf:yang:bbf-ldra"/>
        <bbf-l2-fwd:forwarding xmlns:bbf-l2-fwd="urn:bbf:yang:bbf-l2-forwarding"/>
      \</config>
    \</source>
  \</copy-config>
\</rpc>

response 

\<rpc-reply message-id="5" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  \<rpc-error>
    \<error-type>application\</error-type>
    \<error-tag>operation-failed\</error-tag>
    \<error-severity>error\</error-severity>
    \<error-path>/\</error-path>
    \<error-message>Unknown element "subscriber-profiles".\</error-message>
  \</rpc-error>
\</rpc-reply>

====netopeer2-server
[INF]: LN: Accepted a connection on 0.0.0.0:10830.
[INF]: SR: Session 3 (user "root") created.
[2020/01/23 12:24:44.494308, 2] ssh_pki_import_privkey_base64:  Trying to decode privkey passphrase=false
[2020/01/23 12:24:44.506179, 2] ssh_server_connection_callback:  SSH client banner: SSH-2.0-SSHD-UNKNOWN
[2020/01/23 12:24:44.506224, 2] ssh_analyze_banner:  Analyzing banner: SSH-2.0-SSHD-UNKNOWN
[2020/01/23 12:24:44.506290, 2] ssh_kex_select_methods:  Negotiated ecdh-sha2-nistp521,ssh-rsa,aes128-ctr,aes128-ctr,hmac-sha1,hmac-sha1,none,none,,
[2020/01/23 12:24:44.554152, 2] ssh_packet_server_ecdh_init:  SSH_MSG_KEXDH_REPLY sent
[2020/01/23 12:24:44.554568, 2] ssh_init_rekey_state:  Set rekey after 4294967296 blocks
[2020/01/23 12:24:44.554697, 2] ssh_init_rekey_state:  Set rekey after 4294967296 blocks
[2020/01/23 12:24:44.554871, 2] ssh_packet_server_ecdh_init:  SSH_MSG_NEWKEYS sent
[2020/01/23 12:24:44.581145, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
[INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: LN: Received an SSH message "request-auth" of subtype "none".
[INF]: LN: Received an SSH message "request-auth" of subtype "interactive".
[2020/01/23 12:24:44.629423, 2] ssh_message_auth_interactive_request:  Warning: Got a keyboard-interactive response but it seems we didn't send the request.
[INF]: LN: Received an SSH message "request-auth" of subtype "interactive".
[INF]: LN: User "igort" authenticated.
[INF]: LN: Received an SSH message "request-channel-open" of subtype "session".
[INF]: LN: Received an SSH message "request-channel" of subtype "subsystem".
[2020/01/23 12:24:44.641976, 2] grow_window:  growing window (channel 43:0) to 1280000 bytes
[INF]: SR: Session 4 (user "root") created.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-start).
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Session 5 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:get" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: SR: Published event "operational" with ID 1.
[INF]: SR: Processing "operational" "ietf-yang-library" event with ID 1.
[INF]: SR: Finished processing "operational" event with ID 1.
[INF]: SR: Event "operational" with ID 1 succeeded.
[INF]: SR: Finished processing "rpc" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 1 priority 0 succeeded.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: NP: Session 1: thread 1 event new RPC.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Session 6 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 2 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:get" "rpc" event with ID 2 priority 0 (remaining 1 subscribers).
[INF]: SR: Published event "operational" with ID 1.
[INF]: SR: Processing "operational" "nc-notifications" event with ID 1.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Finished processing "operational" event with ID 1.
[INF]: SR: Event "operational" with ID 1 succeeded.
[INF]: SR: Finished processing "rpc" event with ID 2 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 2 priority 0 succeeded.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: NP: Session 1: thread 0 event new RPC.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Session 7 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 3 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:get" "rpc" event with ID 3 priority 0 (remaining 1 subscribers).
[ERR]: SR: Internal error (/home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/modinfo.c:95).
[ERR]: NP: Getting data "/ietf-system:system-state/clock/current-datetime" from sysrepo failed (Internal error).
[INF]: SR: Finished processing "rpc" event (callback fail) with ID 3 priority 0 (remaining 1 subscribers).
[ERR]: SR: Internal error
[WRN]: SR: Event "rpc" with ID 3 priority 0 failed (Internal error).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 1: thread 1 event new RPC.
[INF]: NP: Session 1: thread 1 event reply error.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Session 8 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/notifications:create-subscription" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[New Thread 0x7ffff1982700 (LWP 15352)]
[INF]: SR: Finished processing "rpc" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 1 priority 0 succeeded.
[INF]: NP: Session 1: thread 2 event new RPC.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Session 9 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:copy-config" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[ERR]: LY: Unknown element "subscriber-profiles". (/)
[INF]: SR: Finished processing "rpc" event (callback fail) with ID 1 priority 0 (remaining 1 subscribers).
[ERR]: SR: Unknown element "subscriber-profiles".
[WRN]: SR: Event "rpc" with ID 1 priority 0 failed (libyang error).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 1: thread 0 event new RPC.
[INF]: NP: Session 1: thread 0 event reply error.

**Comment by igortern** [comment]
I identified the issue. The problem was that bbf-subscriber-profile.yang module was scheduled for addition to sysrepo, but not actually added. Additional call to "sysrepoctl -l" was required to "push it out". After that the problem disappeared.
As a suggestion, it would be good if sysrepoctl where to push out all scheduled changes immediately. Otherwise, it creates a false impression that yang model was imported was in fact it wasn't yet. 

In any case, sorry for false alarm. 

Regards,
Igor

**Comment by michalvasko** [comment]
Hi Igor,
yes, I am planning to improve this and in case the module changes can be performed immediately, do so. But note that it is possible only if there are no other *session* clients (including *neotpeer2*) running. Also, you should always check the module changes with `sysrepoctl -l` after you are done and if you install them with `-v3` it will give the right impression, just that the module was scheduled to be installed.

However, I am wondering about this error
```
[ERR]: SR: Internal error (/home/igort/Perforce/OLT/aspen/external/build/host-sim/third_party/sysrepo/sysrepo-devel/src/modinfo.c:95).
```
It should have been detected earlier that the module `ietf-system` is not installed, only scheduled, so that is what I would like to reproduce. So, was it only scheduled or actually installed?

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,
Unfortunately I missed the error status when installing ietf-system and didn't check if this module was installed. Module ietf-subscriber-profiles was scheduled, but not installed.
For now I added "sysrepoctl -l" in the end of module installation sequence to push everything out.
Regards,
Igor

**Comment by michalvasko** [comment]
Hi Igor,
okay, so can you help me reproduce the internal error? You should never be able to get to that point, so I would like to fix it.

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,
I didn't see this internal error today, will keep an eye on it and send sysrepo repository and traceback if able to reproduce.
Regards,
Igor
