### ISSUE TITLE
Connect to port 830 using ietf-netconf-server

### ISSUE THREAD

**Issue by eraonel** [CESNET/netopeer2#539]
Hi,

Now I am trying to make our client to connect to netopeer2 server running in a docker instance.
Port 830 is exposed but my client gives:
Caused by: java.net.ConnectException: Connection refused: connect
Is there a way to check that my server is actually listening on port 830?
Would it be possible to use:

 ssh  -p 2022 netconf@10.0.75.1 -s netconf

br,

//mikael

**Comment by michalvasko** [comment]
Hi,
yes, you can normally use `ssh(1)` to connect to a NETCONF server and you should get the hello message if you did it correctly.

Regards,
Michal

**Comment by eraonel** [comment]
Hi,

ok. so no specific configuration for this and use port 22?

br,

//mikael

**Comment by eraonel** [comment]
Hi again,

It seems that I can connect to port 830 from inside docker container using:

`root@docker-desktop:/opt/dev# ssh -p 830 netconf@127.0.0.1 -s netconf
The authenticity of host '[127.0.0.1]:830 ([127.0.0.1]:830)' can't be established.
RSA key fingerprint is SHA256:UZZQ5IU34inktQi1S8je/yzZ/NMh5QKgUgl2W0GFIeY.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[127.0.0.1]:830' (RSA) to the list of known hosts.
ssh_dispatch_run_fatal: Connection to 127.0.0.1 port 830: Broken pipe
root@docker-desktop:/opt/dev# ssh -p 830 netconf@127.0.0.1 -s netconf
Interactive SSH Authentication
Type your password:
Password:
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><capabilities><capability>urn:ietf:params:netconf:base:1.0</capability><capability>urn:ietf:params:netconf:base:1.1</capability><capability>urn:ietf:params:netconf:capability:writable-running:1.0</capability><capability>urn:ietf
:params:netconf:capability:candidate:1.0</capability><capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</capability><capability>urn:ietf:params:netconf:capability:validate:1.1</capability><capability>urn:ietf:params:netconf:capability:startup:1.0</capability><capab
ility>urn:ietf:params:netconf:capability:url:1.0</capability><capability>urn:ietf:params:netconf:capability:xpath:1.0</capability><capability>urn:ietf:params:netconf:capability:with-defaults:1.0?basic-mode=explicit&amp;also-supported=report-all,report-all-tagged,trim,explicit</capab
ility><capability>urn:ietf:params:netconf:capability:notification:1.0</capability><capability>urn:ietf:params:netconf:capability:interleave:1.0</capability><capability>urn:ietf:params:xml:ns:yang:ietf-yang-metadata?module=ietf-yang-metadata&amp;revision=2016-08-05</capability><capab
ility>urn:ietf:params:xml:ns:yang:1?module=yang&amp;revision=2017-02-20</capability><capability>urn:ietf:params:xml:ns:yang:ietf-inet-types?module=ietf-inet-types&amp;revision=2013-07-15</capability><capability>urn:ietf:params:xml:ns:yang:ietf-yang-types?module=ietf-yang-types&amp;r
evision=2013-07-15</capability><capability>urn:ietf:params:netconf:capability:yang-library:1.0?revision=2019-01-04&amp;module-set-id=30</capability><capability>urn:ietf:params:xml:ns:yang:ietf-netconf-acm?module=ietf-netconf-acm&amp;revision=2018-02-14</capability><capability>urn:ie
tf:params:xml:ns:netconf:base:1.0?module=ietf-netconf&amp;revision=2013-09-29&amp;features=writable-running,candidate,rollback-on-error,validate,startup,url,xpath</capability><capability>urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults?module=ietf-netconf-with-defaults&amp;rev
ision=2011-06-01</capability><capability>urn:ietf:params:xml:ns:yang:ietf-netconf-notifications?module=ietf-netconf-notifications&amp;revision=2012-02-06</capability><capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring?module=ietf-netconf-monitoring&amp;revision=2010-10-0
4</capability><capability>urn:ietf:params:xml:ns:netconf:notification:1.0?module=notifications&amp;revision=2008-07-14</capability><capability>urn:ietf:params:xml:ns:netmod:notification?module=nc-notifications&amp;revision=2008-07-14</capability><capability>urn:ietf:params:xml:ns:ya
ng:ietf-x509-cert-to-name?module=ietf-x509-cert-to-name&amp;revision=2014-12-10</capability><capability>urn:ietf:params:xml:ns:yang:iana-crypt-hash?module=iana-crypt-hash&amp;revision=2014-08-06</capability></capabilities><session-id>1</session-id></hello>]]>]]>
`

I tried:
`
ssh -p 830 netconf@10.0.75.1 -s netconf
`
but that does not give a connection. Any ideas?

**Comment by eraonel** [comment]
Found out that I need to change:
`docker run --network="host"  -it --name sysrepo -p 830:830 --rm netopeer2-mod-image:latest`
to:
`docker  run  -it --name sysrepo -p 830:830  --rm netopeer2-mod-image:latest`

since network=host contradicts -p 

//mikael
