### ISSUE TITLE
Internal error in netopeer2/sysrepo when handling valid rpc

### ISSUE THREAD

**Issue by igortern** [CESNET/Netopeer2#545]
Hi,

version info: sysrepo, netopeer2, libyang, libnetconf2 development snapshots from Feb 3 (AEST)
all models are attached to Models: attached to issue https://github.com/sysrepo/sysrepo/issues/1720
NETCONF client sends RPC as in [https://github.com/CESNET/Netopeer2/issues/541](url)

netopeer2-server reports internal error in sysrepo. Events related to <bbf-xpon:wavelength-profiles> are not reported to the local sysrepo client. Note that the following line in netopeer2-server appears to be wrong. There is a subscriber to "/bbf-xpon:xpon/wavelength-profiles/wavelength-profile" subtree.

[INF]: SR: There are no subscribers for changes of the module "bbf-xpon" in running DS.

netopeer2-server log is below.

Regards,
Igor
```
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Session 10 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: NP: edit-config test-option "set" not supported, validation will be performed.
[INF]: NP: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: There are no subscribers for changes of the module "bbf-xpon" in running DS.
[WRN]: LY: Augmentations from modules "bbf-xpon" and "bbf-ghn" have fatal hash collision.
[WRN]: LY: It will cause no errors if module "bbf-xpon" is always loaded before "bbf-ghn".
[INF]: SR: Published event "change" with ID 1 priority 0 for 1 subscribers.
[ERR]: SR: /ietf-interfaces:interfaces/interface[name='channelpair.1']/bbf-xpon:channel-pair/wavelength-prof-ref
[WRN]: SR: Event "change" with ID 1 priority 0 failed (Internal error).
[WRN]: LY: Augmentations from modules "bbf-xpon" and "bbf-ghn" have fatal hash collision.
[WRN]: LY: It will cause no errors if module "bbf-xpon" is always loaded before "bbf-ghn".
[INF]: SR: Finished processing "rpc" event (callback fail) with ID 1 priority 0 (remaining 1 subscribers).
[ERR]: SR: /ietf-interfaces:interfaces/interface[name='channelpair.1']/bbf-xpon:channel-pair/wavelength-prof-ref
[WRN]: SR: Event "rpc" with ID 1 priority 0 failed (User callback failed).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 1: thread 3 event new RPC.
[INF]: NP: Session 1: thread 3 event reply error.
[2020/02/03 09:59:37.647475, 1] ssh_socket_exception_callback:  Socket exception callback: 1 (0)
[2020/02/03 09:59:37.647557, 1] ssh_socket_exception_callback:  Socket error: disconnected
[ERR]: LN: Session 1: SSH channel poll error (Socket error: disconnected).
[INF]: NP: Session 1: thread 3 event session terminated.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-end).
```

**Comment by michalvasko** [comment]
Hi,
please include also your `sysrepoctl -l` output so that I know which models to load. Then, what are all your subscribers except for `/bbf-xpon:xpon/wavelength-profiles/wavelength-profile`? Finally, based on these 2 messages
```
[ERR]: SR: /ietf-interfaces:interfaces/interface[name='channelpair.1']/bbf-xpon:channel-pair/wavelength-prof-ref
[WRN]: SR: Event "change" with ID 1 priority 0 failed (Internal error).
```
I would say the first one is printed by your callback, which then returns `SR_ERR_INTERNAL` and the second message just informs about your callback failing with this error. The same for the RPC event. So, what exactly is the problem? Only that you have subscribed to `bbf-xpon` and your callback is not called?

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,
You are right. After commenting out internal validation in my code the error message in netopeer2-server disappeared. The problem is that my callback for 
/bbf-xpon:xpon/wavelength-profiles/wavelength-profile never gets called and it causes validation errors. Below are:

Subscription to /bbf-xpon:xpon/wavelength-profiles/wavelength-profile is done using 
sr_rc = sr_module_change_subscribe(srs, "bbf-xpon", "/bbf-xpon:xpon/wavelength-profiles/wavelength-profile",  bbf_xpon_wavelen_prof_change_cb, NULL, 0, SR_SUBSCR_ENABLED | SR_SUBSCR_CTX_REUSE, &sr_ctx); 
which returned OK. 
Could you think of a reason why bbf_xpon_wavelen_prof_change_cb is not called? 

Updated fragment of netopeer2-server log related to the RPC handling is below.

Thanks,
Igor

[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Session 10 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: NP: edit-config test-option "set" not supported, validation will be performed.
[INF]: NP: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: There are no subscribers for changes of the module "bbf-xpon" in running DS.
[WRN]: LY: Augmentations from modules "bbf-xpon" and "bbf-ghn" have fatal hash collision.
[WRN]: LY: It will cause no errors if module "bbf-xpon" is always loaded before "bbf-ghn".
[INF]: SR: Published event "change" with ID 2 priority 0 for 1 subscribers.
[INF]: SR: Event "change" with ID 2 priority 0 succeeded.
[WRN]: LY: Augmentations from modules "bbf-xpon" and "bbf-ghn" have fatal hash collision.
[WRN]: LY: It will cause no errors if module "bbf-xpon" is always loaded before "bbf-ghn".
[WRN]: LY: Augmentations from modules "bbf-xpon" and "bbf-ghn" have fatal hash collision.
[WRN]: LY: It will cause no errors if module "bbf-xpon" is always loaded before "bbf-ghn".
[INF]: SR: Published event "done" with ID 2 priority 0 for 1 subscribers.
[INF]: SR: Published event "notif" with ID 2 priority 0 for 1 subscribers.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: There is no instance of "/bbf-xpon:xpon/wavelength-profiles/wavelength-profile[name='wavelengthprofile.A']", but it is not required.
[INF]: LY: There is no instance of "/bbf-xpon:xpon/wavelength-profiles/wavelength-profile[name='wavelengthprofile.A']/name", but it is not required.
[INF]: LY: There is no instance of "/bbf-xpon:xpon/wavelength-profiles/wavelength-profile[name='wavelengthprofile.A']/upstream-channel-id", but it is not required.
[INF]: LY: There is no instance of "/bbf-xpon:xpon/wavelength-profiles/wavelength-profile[name='wavelengthprofile.A']/downstream-channel-id", but it is not required.
[INF]: LY: There is no instance of "/bbf-xpon:xpon/wavelength-profiles/wavelength-profile[name='wavelengthprofile.A']/downstream-wavelength", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelgroup.1']", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelgroup.1']/name", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelgroup.1']/type", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelgroup.1']/bbf-xpon:channel-group", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelgroup.1']/bbf-xpon:channel-group/polling-period", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelgroup.1']/bbf-xpon:channel-group/raman-mitigation", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelgroup.1']/enabled", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelgroup.1']/bbf-qos-traffic-mngt:tm-root", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelpartion.1']", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelpartion.1']/name", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelpartion.1']/type", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelpartion.1']/bbf-xpon:channel-partition", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelpartion.1']/bbf-xpon:channel-partition/channel-group-ref", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelpartion.1']/bbf-xpon:channel-partition/channel-partition-index", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelpartion.1']/bbf-xpon:channel-partition/closest-onu-distance", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelpartion.1']/bbf-xpon:channel-partition/maximum-differential-xpon-distance", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelpartion.1']/bbf-xpon:channel-partition/authentication-method", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelpartion.1']/bbf-xpon:channel-partition/downstream-fec", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelpartion.1']/bbf-xpon:channel-partition/multicast-aes-indicator", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelpartion.1']/bbf-qos-traffic-mngt:tm-root", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelpartion.1']/enabled", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelpair.1']", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelpair.1']/name", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelpair.1']/type", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelpair.1']/bbf-xpon:channel-pair", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelpair.1']/bbf-xpon:channel-pair/channel-partition-ref", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelpair.1']/bbf-xpon:channel-pair/channel-group-ref", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelpair.1']/bbf-xpon:channel-pair/wavelength-prof-ref", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelpair.1']/bbf-xpon:channel-pair/channel-pair-type", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelpair.1']/enabled", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channelpair.1']/bbf-qos-traffic-mngt:tm-root", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channeltermination.1']", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channeltermination.1']/name", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channeltermination.1']/type", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channeltermination.1']/bbf-xpon:channel-termination", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channeltermination.1']/bbf-xpon:channel-termination/channel-pair-ref", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channeltermination.1']/bbf-xpon:channel-termination/channel-termination-type", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channeltermination.1']/bbf-xpon:channel-termination/xgs-pon-id", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channeltermination.1']/bbf-xpon:channel-termination/ber-calc-period", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channeltermination.1']/enabled", but it is not required.
[INF]: LY: There is no instance of "/ietf-interfaces:interfaces/interface[name='channeltermination.1']/bbf-qos-traffic-mngt:tm-root", but it is not required.
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Processing "notif" "ietf-netconf-notifications" event with ID 2.
[INF]: SR: Finished processing "notif" event with ID 2 priority 0 (remaining 0 subscribers).
[INF]: SR: Finished processing "rpc" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 1 priority 0 succeeded.
[INF]: NP: Session 1: thread 1 event new RPC.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Session 11 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 2 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 2 priority 0 (remaining 1 subscribers).
[INF]: NP: edit-config test-option "set" not supported, validation will be performed.
[INF]: NP: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: No datastore changes to apply.
[INF]: SR: Finished processing "rpc" event with ID 2 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 2 priority 0 succeeded.
[INF]: NP: Session 1: thread 3 event new RPC.

**Comment by michalvasko** [comment]
Hi,
the log is quite clear saying that there are no subscriptions to `bbf-xpon` for __running__ DS. Can you please check that when you are subscribing, `srs` has `SR_DS_RUNNING` datastore set?

Regards,
Michal

**Comment by igortern** [comment]
Hi,
All registrations except for ietf-interfaces were done with session @ SR_DS_STARTUP and in the end switched to SR_DS_RUNNING using sr_switch_ds. ietf-interfaces registration was done after the switch.
I removed this logic for now and create session @ SR_DS_RUNNING from the start. After this change all callbacks are called.
So, it appears that sr_switch_ds doesn't "migrate" registrations to the new datastore.

It doesn't bother me, I can fork in SR_DS_RUNNING from the start. So, closing this issue.

Thanks,
Igor

**Comment by michalvasko** [comment]
Hi Igor,
well, yes, when you switch the datastore after the subscribe, it will not affect it. That seems quite natural but maybe not to everyone. So, I have added a note to the docs.

Regards,
Michal
