### ISSUE TITLE
Timeout error when sending notification

### ISSUE THREAD

**Issue by igortern** [CESNET/Netopeer2#546]
Hi,

I'm getting a timeout error (below) when sending notification. There is no subscription for this notification in my code. Could you advise what might be the issue?
Versions: sysrepo, netopeer2-server, libyang,libnetconf2 from devel, snapshots taken on Feb 4

Local sysrepo client calls 
```
sr_rc = sr_event_notif_send(sess, "/bbf-xpon-onu-states:onu-state-change", values, num_values);
```
(5 values in total).

Sysrepo reports:
```
[692691: E SYSREPO             ] Callback event "operational" with ID 2 processing timed out.
[692691: W SYSREPO             ] Event "operational" with ID 2 failed (Timeout expired).
```
What is this "operational" callback that times out?

Thanks,
Igor

**Comment by michalvasko** [comment]
Hi Igor,
you have not provided much information. However, notifications are always validated with respect to the `operational` datastore so it seems when a part of them was retreeved that you have subscribed for providing, your callback timed out. Why I cannot say without more details.

Regards,
Michal

**Comment by igortern** [comment]
Hi Michal,
Thank you for the explanation. I'll investigate.
Regards,
Igor
