### ISSUE TITLE
How to call RPC from netopeer2-cli

### ISSUE THREAD

**Issue by serega911** [CESNET/Netopeer2#550]
Hi!

Could you please help me to create valid rpc call;

My model is:
```
module test {
	namespace "urn:test";
	prefix e;

	rpc update_datastore {
        input {
            leaf arg {
                type enumeration
				{
					enum disable;
					enum enable;
				}
            }
        }

        output {
            leaf ret {
                type enumeration
				{
					enum FAILED;
					enum OK;
				}
            }
        }
    }
}
```
XML file is:
```
<run xmlns="urn:test">
	<update_datastore>
		<arg>enable</arg>
	</update_datastore>
</run>
```
or
`<run xmlns="urn:test:update_datastore"/>`
Netopeer2-cli command:
```
> user-rpc --content /home/spasichn/cesnet/demo/xml/rpc.xml 
ly ERROR: Unknown element "run". (/)
cli_send_recv: Failed to send the RPC.
> 
```

Thanks in davance!

**Comment by michalvasko** [comment]
Hi,
what exactly did you try to achieve with the `run` element? Please, _run_ my RPC? :) Just skip that element and it should work.
```xml
<update_datastore xmlns="urn:test">
	<arg>enable</arg>
</update_datastore>
```

Regards,
Michal

**Comment by serega911** [comment]
Thanks)

**Comment by arthurlintw** [comment]
Hi, Is there anyone can help ? I spent a few days but got stuck in the error .
The following debug message  comes from netopeer2-server , it seems the server got the RPC from client , but  rpc-reply error . ( I have  installed the  test yang module ), is there any setting that needs to be done on the server site ?
Thanks.

----------------------------------------------------------------------------------------------------
netopeer2-server 1.1.39

[INF]: NP: Session 2: thread 2 event new RPC.
[DBG]: LN: Session 2: received message:
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="18"><update_datastore xmlns="urn:test"><arg>enable</arg></update_datastore></rpc>

[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[ERR]: NP: Failed to send an RPC (Operation not supported).
[DBG]: LN: Session 2: sending message:

#389


[DBG]: LN: Session 2: sending message:
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="18"><rpc-error><error-type>application</error-type><error-tag>operation-failed</error-tag><error-severity>error</error-severity><error-path>/test:update_datastore</error-path><error-message xml:lang="en">There are no matching subscribers for RPC/action "/test:update_datastore".</error-message></rpc-error></rpc-reply>

[DBG]: LN: Session 2: sending message:

**Comment by michalvasko** [comment]
Firstly, please do not write into old resolved issues and open new ones instead. As for the error, I dare say it is quite self-explaining because that is all I can tell you, you must have a subscription for an RPC before you can send it, which makes sense. You cannot expect a "procedure" to be executed unless there is some other end that actually executes it (whatever that exactly means). You can use `sysrepo/examples/rpc_subscribe_example` to simply print the RPC. More info [here](https://netopeer.liberouter.org/doc/sysrepo/master/html/subs.html#rpc_subs).
