### ISSUE TITLE
Question: is <with-defaults> retrieval implemented in netopeer2-server 1.1.11

### ISSUE THREAD

**Issue by bbergquist0930** [CESNET/Netopeer2#558]
I see the Netopeer-cli passing the options and see the code in netopeer-server that parses out the option in `np2srv_rpc_get_cb` but I don't see it doing anything with it. 

Defaults do not seem to be returned when using `get-config` through the Netopeer2-cli either.

**Comment by michalvasko** [comment]
Hi,
well, maybe you should try issuing `get-config --defaults report-all-tagged` instead in *netopeer2-cli*. By default, no default values should be returned.

Regards,
Michal

**Comment by bbergquist0930** [comment]
This is the test that I did.  I modified "examples.yang" and change the leaf to look like:

```
    container cont {
        leaf l {
            type string;
	    default "default value";
        }
    }
```

I installed the module with 

```
sudo sysrepoctl -i examples.yang
```

I started netopeer2-server with 
```
sudo netopeer2-server -d
```

and then in another window started netopeer2-cli and ran

```
> connect
> connect
Interactive SSH Authentication
Type your password:
Password: 
> get-config --source running --filter-xpath /examples:cont/* --defaults report-all
DATA

> get-config --source running --filter-xpath /examples:cont/* --defaults report-all-tagged
DATA
```
edited the leaf to have the value `value`

```
> edit-config --target running --config
OK
> get-config --source running --filter-xpath /examples:cont/* --defaults report-all
DATA
<cont xmlns="urn:examples">
  <l>value</l>
</cont>

> get-config --source running --filter-xpath /examples:cont/* --defaults report-all-tagged
DATA
<cont xmlns="urn:examples" xmlns:ncwd="urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults">
  <l>value</l>
</cont>
```
edited the leaf to have the value `default value` which is the default value in the YANG model

```
> edit-config --target running --config
OK
> get-config --source running --filter-xpath /examples:cont/* --defaults report-all
DATA
<cont xmlns="urn:examples">
  <l>default value</l>
</cont>

> get-config --source running --filter-xpath /examples:cont/* --defaults report-all-tagged
DATA
<cont xmlns="urn:examples" xmlns:ncwd="urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults">
  <l ncwd:default="true">default value</l>
</cont>

> 
```

I would think that before the value was set initially that the 
```
get-config --source running --filter-xpath /examples:cont/* --defaults report-all
```

Would return the default value since there was no value set and the RFC states 

```
3.1.  'report-all' Retrieval Mode

   When data is retrieved with a <with-defaults> parameter equal to
   'report-all', all data nodes MUST be reported, including any data
   nodes considered to be default data by the server.
```

Am I reading that wrong?

Thank you for your time.

**Comment by michalvasko** [comment]
Hi,
you are right, with-defaults mode was parsed at one place, where it was not even used and not used where it should have been. Now it should work correctly. Also, update *libyang* as well to use *netopeer2-cli* for testing this, otherwise it will print a (harmless) warning.

Regards,
Michal

**Comment by bbergquist0930** [comment]
Works now with your changes.  Thanks!
