### ISSUE TITLE
Question if the capabilities for 'yang-library' return by Netopeer-cli status has the correct version

### ISSUE THREAD

**Issue by bbergquist0930** [CESNET/netopeer2#559]
This is my build of Netopeer2-server
```
$ sudo netopeer2-server -V
netopeer2-server 1.1.12
compile time: Feb 14 2020, 10:46:36
```
The capabilities being return is
```
	urn:ietf:params:netconf:capability:yang-library:1.0?revision=2019-01-04&module-set-id=31
```
It looks like the current implementation is supporting '1.1'.   I have not found where it is generated in the source yet to check to see if there is just an issue there.

From RFC 8525, I see 
```
Note that for a NETCONF server implementing the NETCONF extensions to
   support the NMDA [RFC8526], a change of the YANG library content
   identifier results in a new value for the :yang-library:1.1
   capability defined in [RFC8526].
```

It looks like RFC 8526 is supported as there is the support for 'get-data' and 'edit-data'.   So maybe just the version reported in the capabilities needs to be updated?

**Comment by michalvasko** [comment]
Hi,
you are right, but it was just an outdated capability name, should be fixed now in *libnetconf2* (https://github.com/CESNET/libnetconf2/commit/f0fba4e738c903aad75d1c03f6fa6427539801a8).

Regards,
Michal

**Comment by bbergquist0930** [comment]
It is correct now so closing
