### ISSUE TITLE
Inquiry : RFCs supported by netopeer2

### ISSUE THREAD

**Issue by kjhjekwls** [CESNET/netopeer2#560]
Hello,

Could you tell me full RFC lists that latest netopeer2 server(with sysrepo) supports ?

I can't see full RFC lists here.

**Comment by michalvasko** [comment]
Hi,
most of them should be mentioned in [libnetconf2 README](https://github.com/cesnet/libnetconf2). One additional (NMDA) is mentioned in [sysrepo docs](https://netopeer.liberouter.org/doc/sysrepo/master/). I do not know anymore exactly for which features there even are RFCs so there may be some missing.

Regards,
Michal
