### ISSUE TITLE
sr_shmmod_modinfo_rdlock_upgrade: Assertion `shm_lock->write_locked' failed. After multiple operations

### ISSUE THREAD

**Issue by andre-brizido** [CESNET/netopeer2#564]
With the latest source code from the devel branches the netopeer2-server is terminating with the debug below after several edit configs.

> 2020/02/24 15:32:01.203128, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
[INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: LN: Received an SSH message "request-auth" of subtype "password".
[INF]: LN: User "root" authenticated.
[INF]: LN: Received an SSH message "request-channel-open" of subtype "session".
[INF]: LN: Received an SSH message "request-channel" of subtype "subsystem".
[2020/02/24 15:32:01.254767, 2] grow_window:  growing window (channel 43:0) to 1280000 bytes
[INF]: SR: Session 57 (user "root") created.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-start).
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 28 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 28 priority 0 (remaining 1 subscribers).
[INF]: NP: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[ERR]: SR: Callback event "rpc" with ID 28 processing timed out.
[WRN]: SR: Event "rpc" with ID 28 priority 0 failed (Timeout expired).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 28: thread 4 event new RPC.
[INF]: NP: Session 28: thread 4 event reply error.
[INF]: NP: Session 28: thread 0 event new RPC.
[INF]: NP: Session 28: thread 0 event session terminated.
[ERR]: SR: Session 57 (NC SID 28) was working with module "ietf-interfaces"!
[ERR]: SR: Internal error (/opt/dev/sysrepo/src/shm_mod.c:660).
[ERR]: SR: Session 57 (NC SID 28) was working with module "ietf-hardware"!
[ERR]: SR: Internal error (/opt/dev/sysrepo/src/shm_mod.c:660).
[ERR]: SR: Session 57 (NC SID 28) was working with module "bbf-l2-forwarding"!
[ERR]: SR: Internal error (/opt/dev/sysrepo/src/shm_mod.c:660).
[ERR]: SR: Session 57 (NC SID 28) was working with module "bbf-link-table"!
[ERR]: SR: Internal error (/opt/dev/sysrepo/src/shm_mod.c:660).
[ERR]: SR: Session 57 (NC SID 28) was working with module "bbf-xpongemtcont"!
[ERR]: SR: Internal error (/opt/dev/sysrepo/src/shm_mod.c:660).
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-end).
[INF]: SR: There are no subscribers for changes of the module "ietf-interfaces" in running DS.
[INF]: SR: There are no subscribers for changes of the module "bbf-l2-forwarding" in running DS.
[INF]: SR: There are no subscribers for changes of the module "bbf-xpongemtcont" in running DS.
[INF]: SR: There are no subscribers for changes of the module "ietf-hardware" in running DS.
[INF]: SR: There are no subscribers for changes of the module "bbf-link-table" in running DS.
netopeer2-server: /opt/dev/sysrepo/src/shm_mod.c:513: sr_shmmod_modinfo_rdlock_upgrade: Assertion `shm_lock->write_locked' failed.

yang list below. I used the _install_modules_v1.x.sh and the _install_features_v1.x.sh to load them.
[yangs.zip](https://github.com/CESNET/Netopeer2/files/4245424/yangs.zip)

The following zip contains a script for performing multiple edit-configs using the netconf-console application.
[test-script.zip](https://github.com/CESNET/Netopeer2/files/4245435/test-script.zip)

Before crashing, in the last operation the server throws the following error:

> <nc:rpc-error xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
>   <nc:error-type>application</nc:error-type>
>   <nc:error-tag>operation-failed</nc:error-tag>
>   <nc:error-severity>error</nc:error-severity>
>   <nc:error-message xml:lang="en">Callback event "rpc" with ID 28 processing timed out.</nc:error-message>
> </nc:rpc-error>

I noticed that as time goes by, the operations are getting slower until it terminates in the assertion.

**Comment by michalvasko** [comment]
Hi,
firstly, just to be clear what is happening, you are continually adding list instances into the datastore so it is expected that it will take longer with each new instance. Until it takes too long and the RPC timeout elapses. That is all expected and the only problem here is how *netopeer2-server* reacts to this timeout.

Now, what *sysrepo* version are you using? With the latest `devel` it worked mostly fine meaning no assert occurred and the server continued to work normally. Except that the edit-config was applied even when the whole RPC returned time out. This is due to how the server communicates with *sysrepo* and I do think it is too much of a problem. To solve it you can simply adjust the *sysrepo* timeouts in *netopeer2-server*. You should do that if you know it is required because such a timeout is basically a fatal error, anyway.

Regards,
Michal

**Comment by andre-brizido** [comment]
Hi 

I'm using the latest devel code (pulled yesterday).
Initially was building with -DCMAKE_BUILD_TYPE:String="Debug" (took the docker hub dockerfile as reference) but then I removed the option and now the server stops at a new location:
```
NF]: NP: Generated new event (netconf-session-end).
[INF]: LN: Accepted a connection on 0.0.0.0:830.
[INF]: SR: Session 142 (user "root") created.
[2020/02/27 11:46:36.367487, 2] ssh_pki_import_privkey_base64:  Trying to decode privkey passphrase=false
[2020/02/27 11:46:36.371466, 1] ssh_server_connection_callback:  SSH client banner: SSH-2.0-paramiko_2.7.1
[2020/02/27 11:46:36.371486, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-paramiko_2.7.1
[2020/02/27 11:46:36.441562, 2] ssh_server_curve25519_init:  SSH_MSG_KEX_ECDH_REPLY sent
[2020/02/27 11:46:36.441774, 2] ssh_server_curve25519_init:  SSH_MSG_NEWKEYS sent
[2020/02/27 11:46:36.447094, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
[INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: LN: Received an SSH message "request-auth" of subtype "password".
[INF]: LN: User "root" authenticated.
[INF]: LN: Received an SSH message "request-channel-open" of subtype "session".
[INF]: LN: Received an SSH message "request-channel" of subtype "subsystem".
[2020/02/27 11:46:36.531268, 2] grow_window:  growing window (channel 43:0) to 1280000 bytes
[INF]: SR: Session 143 (user "root") created.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-start).
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 71 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 71 priority 0 (remaining 1 subscribers).
[INF]: NP: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: There are no subscribers for changes of the module "ietf-interfaces" in running DS.
[INF]: SR: There are no subscribers for changes of the module "bbf-l2-forwarding" in running DS.
[INF]: SR: There are no subscribers for changes of the module "bbf-xpongemtcont" in running DS.
[INF]: SR: There are no subscribers for changes of the module "ietf-hardware" in running DS.
[INF]: SR: There are no subscribers for changes of the module "bbf-link-table" in running DS.
[WRN]: LY: Augmentations from modules "ieee802-ethernet-interface" and "bbf-interface-usage" have fatal hash collision.
[WRN]: LY: It will cause no errors if module "ieee802-ethernet-interface" is always loaded before "bbf-interface-usage".
[INF]: LY: Resolving unresolved data nodes and their constraints...
[ERR]: SR: Callback event "rpc" with ID 71 processing timed out.
[WRN]: SR: Event "rpc" with ID 71 priority 0 failed (Timeout expired).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 71: thread 0 event new RPC.
[INF]: NP: Session 71: thread 0 event reply error.
[INF]: NP: Session 71: thread 4 event new RPC.
[INF]: NP: Session 71: thread 4 event session terminated.
[ERR]: SR: Session 143 (NC SID 71) was working with module "ietf-interfaces"!
[ERR]: SR: Internal error (/opt/dev/sysrepo/src/shm_mod.c:660).
[ERR]: SR: Session 143 (NC SID 71) was working with module "ietf-hardware"!
[ERR]: SR: Internal error (/opt/dev/sysrepo/src/shm_mod.c:660).
[ERR]: SR: Session 143 (NC SID 71) was working with module "bbf-l2-forwarding"!
[ERR]: SR: Internal error (/opt/dev/sysrepo/src/shm_mod.c:660).
[ERR]: SR: Session 143 (NC SID 71) was working with module "bbf-link-table"!
[ERR]: SR: Internal error (/opt/dev/sysrepo/src/shm_mod.c:660).
[ERR]: SR: Session 143 (NC SID 71) was working with module "bbf-xpongemtcont"!
[ERR]: SR: Internal error (/opt/dev/sysrepo/src/shm_mod.c:660).
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-end).
[INF]: LN: Accepted a connection on 0.0.0.0:830.
[INF]: SR: Session 144 (user "root") created.
[2020/02/27 11:46:43.180905, 2] ssh_pki_import_privkey_base64:  Trying to decode privkey passphrase=false
[2020/02/27 11:46:43.185035, 1] ssh_server_connection_callback:  SSH client banner: SSH-2.0-paramiko_2.7.1
[2020/02/27 11:46:43.185135, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-paramiko_2.7.1
[2020/02/27 11:46:43.235023, 2] ssh_server_curve25519_init:  SSH_MSG_KEX_ECDH_REPLY sent
[2020/02/27 11:46:43.235307, 2] ssh_server_curve25519_init:  SSH_MSG_NEWKEYS sent
[2020/02/27 11:46:43.237733, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
[INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: LN: Received an SSH message "request-auth" of subtype "password".
[INF]: LN: User "root" authenticated.
[INF]: LN: Received an SSH message "request-channel-open" of subtype "session".
[INF]: LN: Received an SSH message "request-channel" of subtype "subsystem".
[2020/02/27 11:46:43.262947, 2] grow_window:  growing window (channel 43:0) to 1280000 bytes
[INF]: SR: Session 145 (user "root") created.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-start).
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 72 priority 0 for 1 subscribers.
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
netopeer2-server: /opt/dev/sysrepo/src/shm_mod.c:564: sr_shmmod_modinfo_wrlock_downgrade: Assertion `shm_lock->write_locked' failed.
Aborted (core dumped)
```

By the way, I'm running the server inside a docker container and the yangs are installed during the docker build process. I don't have any plugin or any other application connecting to sysrepo.

Anyway, if I interpreted correctly, in your case even if the server does not crash it will eventually always return an internal timeout after a certain number of instances:
```
[INF]: LY: Resolving unresolved data nodes and their constraints...
[ERR]: SR: Callback event "rpc" with ID 71 processing timed out.
[WRN]: SR: Event "rpc" with ID 71 priority 0 failed (Timeout expired).
[ERR]: NP: Failed to send an RPC (User callback failed).
```

The models of the BBF are quite extent, but the configurations that I was testing are based on a real world scenario and simulate the configuration of ONTs on an OLT (I'm simplifying by repeating vlans and serial numbers).
In my case Netopeer2/sysrepo is failing after ~70 ONTs but a 1RU OLT with 8 ports can support up to 128x8=1024 ONTs.
The docker container is running inside a VM with 2,5Gbps of memory and on an Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz laptop.

**Comment by michalvasko** [comment]
Hi,
okay, I think I have figured out the problem without reproducing it. I believe a *sysrepo* session is being stopped while a NETCONF edit-config (*sysrepo* `sr_apply_changes()`) is happening on the same session. That is a *netopeer2* bug, specifically of its timeouts. Please pull the latest `devel-server` *neotpeer2*, which has a new compile-time variable `RPC_TIMEOUT`. Even with the default values you should no longer see any crash or abort, but just a timeout error. Then you can adjust `DATA_CHANGE_TIMEOUT` and `RPC_TIMEOUT` so that your-use case does not time out.

Regards,
Michal

**Comment by andre-brizido** [comment]
Hi

I've pulled the latest changes and it still happens:
```
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[ERR]: SR: Callback event "rpc" with ID 45 processing timed out.
[WRN]: SR: Event "rpc" with ID 45 priority 0 failed (Timeout expired).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 45: thread 3 event new RPC.
[INF]: NP: Session 45: thread 3 event reply error.
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: NP: Session 45: thread 4 event new RPC.
[INF]: NP: Session 45: thread 4 event session terminated.
[ERR]: SR: Session 93 (NC SID 45) was working with module "ietf-interfaces"!
[ERR]: SR: Internal error (/opt/dev/sysrepo/src/shm_mod.c:649).
[ERR]: SR: Session 93 (NC SID 45) was working with module "ietf-hardware"!
[ERR]: SR: Internal error (/opt/dev/sysrepo/src/shm_mod.c:649).
[ERR]: SR: Session 93 (NC SID 45) was working with module "bbf-l2-forwarding"!
[ERR]: SR: Internal error (/opt/dev/sysrepo/src/shm_mod.c:649).
[ERR]: SR: Session 93 (NC SID 45) was working with module "bbf-link-table"!
[ERR]: SR: Internal error (/opt/dev/sysrepo/src/shm_mod.c:649).
[ERR]: SR: Session 93 (NC SID 45) was working with module "bbf-xpongemtcont"!
[ERR]: SR: Internal error (/opt/dev/sysrepo/src/shm_mod.c:649).
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-end).
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
netopeer2-server: /opt/dev/sysrepo/src/shm_mod.c:553: sr_shmmod_modinfo_wrlock_downgrade: Assertion `shm_lock->write_locked' failed.
```
But what you mentioned makes sense, on my test a new session is open for each RPC.
Meanwhile I will try to adjust timeouts.

**Comment by michalvasko** [comment]
Hi Andre,
I do not quite understand this then. Current *netopeer2* should have 5s timeout for all the specific RPCs while 6s for the one main RPC callback. The problem here is that the main RPC timeout elapses before the specific RPC one, which I was hoping could no longer happen.

If it does, it may be a *sysrepo* problem that for some reason the `edit-config` (`sr_apply_changes()`) 5s timeout is not honored. And actually, this timeout is for each subscriber separately meaning if you have a large edit with many subscribers, this whole scenario can easily be explained. For example, if you have 10 subscribers each taking 1s to process their changes, the whole edit will take 10s even though the timeout is 5s. But that is a feature, I think it makes more sense to limit each subscriber than the whole edit and adding another timeout is a redundant API change. So, I will improve *sysrepo* documentation so that the behavior is clear and as for you, try to increase `RPC_TIMEOUT`. In theory (assuming all specific RPC callbacks are correct), you can increase this timeout even to some huge number because the only point is that it does not time out before the specific RPC callbacks do.

Regards,
Michal
