### ISSUE TITLE
Invalid attribute error for nc:operation="replace"

### ISSUE THREAD

**Issue by andre-brizido** [CESNET/Netopeer2#565]
In the latest code from the devel branch, I get the following error:

```
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="2">
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-path>/ietf-interfaces:interfaces</error-path>
    <error-message xml:lang="en">Invalid attribute "operation".</error-message>
  </rpc-error>
</rpc-reply>
```

For the following request:
```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="">
  <edit-config>
    <target>
      <running/>
    </target>
    <config xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
      <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces" nc:operation="replace"/>
    </config>
  </edit-config>
</rpc>
```

This is working fine in the legacy branch.

**Comment by michalvasko** [comment]
Hi,
it may have worked in the legacy *sysrepo* even though it actually should not have because *libyang* simply did not support forward namespace declarations until now so I think some checks were not performed. Anyway, with the latest *libyang* it should work fine.

Regards,
Michal

**Comment by andre-brizido** [comment]
Hi 

I've pulled the latest changes and now Netopeer2 accepts the request mentioned above, however it does not clear the interface list as expected. 
For example, if I have the following data:
```
<?xml version="1.0" encoding="utf-8"?>
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
    <interface>
      <name>interfaceA</name>
      <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
    </interface>
    <interface>
      <name>interfaceB</name>
      <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
    </interface>
  </interfaces>
</data>
```
I would expect that the edit-config with the replace parameter would clear all the interfaces. 
This is the behavior that I observe in the legacy branch.

**Comment by michalvasko** [comment]
Hi,
sorry about that, I just assumed the only problem was with the operation. But there was also a bug in *sysrepo*, please try it again with the latest version.

Regards,
Michal

**Comment by andre-brizido** [comment]
Hi

I confirm. It now works as expected.

Regards
Andre
