### ISSUE TITLE
How to call user-rpc without xml file?

### ISSUE THREAD

**Issue by li9270** [CESNET/netopeer2#567]
Hello,
I read the Plugin Example of sysrepo：oven module. I have a question.
I want call the user-rpc insert-food. I want to write the commad name and parameter, not a xml file, is there any tool or method to covert the insert-food to xml file? Or any advise to finish the convertion? Thanks a lot!

**Comment by michalvasko** [comment]
Hi,
unfortunately, *netopeer2-cli* does not allow this, you will have to use some other NETCONF client. I do not use any other clients so you will have to search for one, there should be several ones available.

Regards,
Michal
