### ISSUE TITLE
np2srv_pubkey_auth_cb only tests the first key

### ISSUE THREAD

**Issue by berstrob** [CESNET/Netopeer2#569]
Hi again,

i just was wondering if it is intended that only the first key out of  authorized_keys is read and validated against?

Greatings Bernd

**Comment by michalvasko** [comment]
Hi,
yes, it was intended because it was much easier but with a TODO to fix it later. I had no reason to implement it until now, so you can try it, should work.

Regards,
Michal

**Comment by berstrob** [comment]
Hello, 
thank you for adding it so quick, i did miss read your TODO at first and thought it only did mean other types of keys, but now i get it.

Regards,
Bernd
