### ISSUE TITLE
call Home

### ISSUE THREAD

**Issue by vishalwc** [CESNET/Netopeer2#57]
Creating the new ticket as earlier was closed related to it  . 
can you please let us know when is call home support available in Master branch.

**Comment by michalvasko** [comment]
Hi,
in a very basic form it is available in the devel branch, but it will not be merged until it fully works and for that some bugfixing in sysrepo is required.

Regards,
Michal

**Comment by vishalwc** [comment]
any communication and update from sysrepo to fix the bug related to call home .
based on your experience with sysrepo update can you give some ball park estimates

**Comment by michalvasko** [comment]
Hi,
I am hoping during the next week full installation and basic configuration of NETCONF server with Call Home will work.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
in the branch `devel-server` the Call Home should work, but only for SSH for now. But you must first install **authd** (in the repository) and then have **sysrepo-plugind** running in addition to **sysrepod**.

Regards,
Michal

**Comment by vishalwc** [comment]
we are in between the development with  master branch libraries and once call home comes would  update it . will it be good idea to migrate to devel-server ?
when is the merge plan ?

**Comment by michalvasko** [comment]
Hi,
there are a few started features in the `devel-server`, which you should not try to use, otherwise everything that works in `master` should work in this branch too. Namely, do not do anything related to notifications and do not try to configure NETCONF server options other than SSH listen and SSH Call Home.

So, to test it, first install **authd**, in the repository (standard `make & make install`), then the same for **netopeer2-server**. After that, when you start the server, it should listen on the default address `0.0.0.0:830`. Connect to it and then send an edit-config with this configuration:
```xml
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <call-home>
    <netconf-client>
      <name>main</name>
      <ssh>
        <endpoints>
          <endpoint>
            <name>endpt_name</name>
            <address>127.0.0.1</address>
          </endpoint>
        </endpoints>
        <host-keys>
          <host-key>
            <name>rsa_key</name>
            <public-key>ssh_host_rsa_key</public-key>
          </host-key>
        </host-keys>
      </ssh>
      <connection-type>
        <persistent/>
      </connection-type>
    </netconf-client>
  </call-home>
</netconf-server>
```
It should enable Call Home on localhost on the port 4334.

Regarding the merge, it is not planned this year. Also, there could be something broken in the devel-server, which is working in the master, but you can report this and we will fix it (if it's not something from what I mentioned that is not ready).

Regards,
Michal

**Comment by vishalwc** [comment]
Thanks Michal for your support and update  
let say we have remote client listening on xxxx port how do I enable call home ?

If you use the  listen  command in client ( remote client) ,what needs to be done to initiate the call home?

**Comment by michalvasko** [comment]
Hi,
if you need the server to connect to client on a specific port, just add another element `netconf-server/call-home/netconf-client/ssh/endpoints/endpoint/port` with the desired value.

To listen for Call Home using **netopeer2-cli**, just use its `listen` command. Also, the server intiates Call Home, not the client.

Regards,
Michal

**Comment by vishalwc** [comment]
Just want to have clarity on sequence of operation 
1) start netopeer2-server ( it will listen on 830 port ) 
2) from remote client send edit config command to the server with above mentioned configuration 
3) it would by  enable client call home on port configured in ->server/call-home/netconf-client/ssh/endpoints/endpoint/port  

4) now we need some app on server to start the TCP connection using SSH with client call home port configured ? 

am I right ?

**Comment by michalvasko** [comment]
1. Start server - it **listens** on port `830` by default,
2. start client - **connect** to the server on port `830`,
3. send edit-config with the configuration I mentioned before, that will cause server to start **connecting** to a client on `127.0.0.1:4334` (that is what Call Home is),
4. start another client and **listen** for Call Home on localhost port `4334` (`127.0.0.1:4334`), it should get connected in a matter of seconds.

Regards,
Michal

**Comment by vishalwc** [comment]
Got it !!! 

and as per your previous mail we can configure client port to listen on defined port in  netconf-server/call-home/netconf-client/ssh/endpoints/endpoint/port

**Comment by vishalwc** [comment]
I assume the other libraries libyang , sysrepo ,libnetconf2 should be build from master branch 
However Netopeer2 should be taken from devel-server branch ?
please confirm

**Comment by michalvasko** [comment]
Hi,
no, generally, if you want to use `devel` of one software, you need `devel` of all our libraries. However, **libyang** `master` and `devel` branch are currently the same, so it does not matter in that one case. You definitely need **libnetconf2** devel.

Regards,
Michal

**Comment by vishalwc** [comment]
how about sysrepo code ?

**Comment by michalvasko** [comment]
Well, I am using `master` code and suggest you do the same, but I believe it should work with `devel` too.

Regards,
Michal
