### ISSUE TITLE
Netopeer2-sever issue 

### ISSUE THREAD

**Issue by Akhil-123456789** [CESNET/netopeer2#570]
[ERR]: SR: Data provider subscription for "ietf-netconf-monitoring" on "/ietf-netconf-monitoring:netconf-state" already exists.
[ERR]: NP: Subscribing for providing "ietf-netconf-monitoring" state data failed (Invalid argument).
[ERR]: NP: Server data subscribe failed.
[INF]: NP: Server terminated.
[INF]: SR: Ext SHM was defragmented and 4976 B were saved.

First time Sever is connected fine after running the "Netopeer2-sever -d -v2"
After running couple of times the sever, i facing about issue.

Can any one help me.

**Comment by michalvasko** [comment]
Hi,
please first state what *sysrepo* and *netopeer2* version are you using. Then, what exactly do you mean by "after running couple of times", starting and terminating the server?

Regards,
Michal
