### ISSUE TITLE
netopeer2-cli get-data -defaults always reports an error

### ISSUE THREAD

**Issue by bbergquist0930** [CESNET/Netopeer2#571]
Latest netopeer2-server built yesterday from devel-server branch
Latest netopeer2-cli built yesterday from devel-server branch

```
> get-data --datastore running --defaults report-all
ly ERROR: Failed to find "with-defaults" as a sibling to "ietf-netconf-nmda:datastore".
cli_send_recv: Failed to send the RPC.
> 
```

This error occurs no matter what option is passed to `--defaults`

**Comment by michalvasko** [comment]
Hi,
right, should work with the latest *libnetconf2*.

Regards,
Michal
