### ISSUE TITLE
Features defined in sub modules are not shown as part of capabilities

### ISSUE THREAD

**Issue by BanuPrakashReddy** [CESNET/Netopeer2#573]
I have a feature(feature-submodule) defined in a submodule. I  loaded the main module and enabled the feature using sysrepoctl. 
I could see the feature as part of "Enabled Features" column in "sysrepoctl -l" output , but feature misses in server capabilities returned. 

Attached the main module and sub module fyr. 

===========================
The output of "sysrepoctl -l" : 
device-queues              | 2015-07-20 | Installed   | root:root           | 666         |  device-queue-types           | feature-submodule 

===========================
The output of capabiliies:
<capability>http://www.abc.com/ns/yang/device-queues?module=device-queues&amp;revision=2015-07-20&amp;</capability>

===========================
[device-queue-types.txt](https://github.com/CESNET/Netopeer2/files/4318565/device-queue-types.txt)
[device-queues.txt](https://github.com/CESNET/Netopeer2/files/4318568/device-queues.txt)

**Comment by michalvasko** [comment]
Hi,
right, try again with the latest *libnetconf2*.

Regards,
Michal
