### ISSUE TITLE
The key exchange failed during the call home

### ISSUE THREAD

**Issue by MickAbson** [CESNET/netopeer2#574]
Hi
Netopeer2, which I compiled with a cross-compiler, failed to call home on two devices (" one for server, one for client ").But it works if you call home on the same device.

`[INF]: LN: Trying to connect via IPv4 to 192.168.2.5:4334.

[INF]: LN: Successfully connected to 192.168.2.5:4334 over IPv4.

[INF]: SR: Session 2 (user "root") created.

[ERR]: LN: SSH key exchange error (Received SSH_MSG_DISCONNECT: 11:Bye Bye).

[INF]: LN: Trying to connect via IPv4 to 192.168.2.5:4334.`

So how do I solve this problem?
Wish get your help,Thanks!
Regards,
Fizz

**Comment by michalvasko** [comment]
Hi Fizz,
look at the client output, it is the one terminating the connection.

Regards,
Michal

**Comment by MickAbson** [comment]
Hi Michal,
the client output is :
`> listen 
Waiting 60s for an SSH Call Home connection on port 4334...
nc ERROR: SSH connect timeout.
cmd_listen: Receiving SSH Call Home on port 4334 as user "root" failed.
> `

Regards,
Fizz

**Comment by michalvasko** [comment]
Hi,
what exact version of *libssh* are you using and is it from a package or compiled manually?

Regards,
Michal

**Comment by MickAbson** [comment]
Hi,
The version of libssh I used was 0.9.2 downloaded from the official website. I downloaded the source package and cross-compiled it to generate the dynamic library.

Regards,
Fizz

**Comment by michalvasko** [comment]
Hi Fizz,
okay, that should work. Then I suggest you enable debug messages for both the server (`-c SSH`) and client (`verb debug`). There will be a lot of output but the relevant information should be found there.

Regards,
Michal
