### ISSUE TITLE
how to close local session

### ISSUE THREAD

**Issue by peter-summer** [CESNET/Netopeer2#576]
hi,

We are using netconf call-home. 
In netopeer2-server,how to close or kill a session? Can the client is notified automatically?

Thank you.

**Comment by michalvasko** [comment]
Hi,
please be more exact. You have *netopeer2-server* running with configured Call Home and connected to a client. What do you want to do?

You want to close the session on the server end and then what? Normally, the server would try reconnecting to the client based on its configuration, is that what you want? Also, why do you want to do this? In NETCONF it is not normally expected for the server to terminate the connection, the client should be the one to send `close-session`.

Regards,
Michal

**Comment by peter-summer** [comment]
Hi,Michal:

Somtimes, I want to close a session in netopeer2-server without the help of client..
I have tried to call following sysrepo sdk.

rc = sr_rpc_send(s_session, "/ietf-netconf:close-session", &input, 0, &output, &output_cnt);

But it will return "SR_ERR_NOT_FOUND".

Is there any other solution?

Thank you.

**Comment by michalvasko** [comment]
Okay, so you can use `kill-session` RPC to terminate some other session. But I still do not know where you want to do this, whether in a separate application or by modifying the server code (where exactly in the code did you try sending that RPC?).

Regards,
Michal

**Comment by peter-summer** [comment]
hi,Michal:

I have tried to call kill-session.

input.xpath = "/ietf-netconf:kill-session/session-id";
input.type = SR_UINT32_T;
input.data.uint32_val = 1;
rc = sr_rpc_send(s_session, "/ietf-netconf:kill-session", &input, 1, &output, &output_cnt);

But it still return "SR_ERR_NOT_FOUND".I have checked that the session id is correct.

CPE> show controller
session 1
        username: vpp
        source-host: 192.168.100.69
        login-time: 2020-03-19T14:30:32+01:00
        in-rpcs: 30
        in-bad-rpcs: 0
        out-rpc-errors: 0
        out-notifications: 9
CPE>


In my linux machine,there are netopeer2-server and sysrepo. I call sysrepo SDK in another process.

Can you help to check if there are any mistake ?

Thank you.

**Comment by michalvasko** [comment]
Hi,
okay, should have been my first question, what *sysrepo*/*netopeer2* version are you using? Also, do you see the error message or just the return code?

Regards,
Michal

**Comment by peter-summer** [comment]
Hi,Michal:

Following is the version list:
sysrepo-0.7.7
Netopeer2-0.7-r1

I read the return code is 3

nemngd: Mar 19 21:30:58  killSession fail:rc=3

Thank you.

**Comment by peter-summer** [comment]
Hi,Mihal:

There is an error message in syslog:

Mar 19 22:22:50 localhost sysrepod[3357]: [ERR] No subscription found for RPC delivery (xpath = '/ietf-netconf:kill-session').

**Comment by michalvasko** [comment]
Hi,
yes, now it makes sense. So, if you want to keep using this legacy version, you will have to create a NETCONF session to the server, send a kill-session RPC, and then terminate the session. The reason is that `kill-session` is processed internally without going through *sysrepo* so you cannot send it directly by *sysrepo*. However, it should work exactly as you would expect in the current *sysrepo* and *netopeer2* versions (1.x) meaning you could sent the RPC by *sysrepo*.

Regards,
Michal

**Comment by peter-summer** [comment]
Hi，Michal:

Do you have an example code to create NETCONF session?

I also found that there are follwing code in sysrepo. Can I add them in SYSREPO init function to remove the kill-session limitation.

    add_nacm_rule(nacm_config, "acl2", "permit-kill-session", "ietf-netconf", NACM_RULE_RPC,
            "kill-session", "exec", "permit", "Permit execution of the kill-session NETCONF operation.");

Thank you.

**Comment by michalvasko** [comment]
Hi,
the [CLI](https://github.com/CESNET/Netopeer2/blob/legacy/cli/commands.c#L1533) can connect to the NETCONF server, obviously. You could also connect on the local UNIX socket with [nc_connect_unix](https://github.com/CESNET/libnetconf2/blob/legacy/src/session_client.h#L169) but the server must be set to create the socket (try `netopeer2-server -h`).

Other than that you are probably right and you will need to enable the RPC in the NACM. I am not sure it is worth all the trouble and it is not easier to migrate to the current version but that choice is up to you.

Regards,
Michal

**Comment by peter-summer** [comment]
Hi,Michal:
I have tried your method and it did work. My issue is resolved.
Thank you very much.
