### ISSUE TITLE
netopeer2-cli connection refused (localhost)

### ISSUE THREAD

**Issue by change-my-username** [CESNET/Netopeer2#579]
I cant connect to netopeer2-server with localhost. I`ve tried to rebuild Netopeer2/server Netopeer2/cli but It didnt help.  
It is very strange behavior, because it worked properly several days ago.

Here is my server and client log 

`celeno@celeno-VirtualBox:~/netconf/Netopeer2/server/build$ sudo netopeer2-server -d -v2

[INF]: LY: Plugin "/usr/local/lib/libyang/extensions/yangdata.so" successfully loaded.
[INF]: LY: Plugin "/usr/local/lib/libyang/extensions/nacm.so" successfully loaded.
[INF]: LY: Plugin "/usr/local/lib/libyang/extensions/metadata.so" successfully loaded.
[INF]: LY: Plugin "/usr/local/lib/libyang/user_types/user_inet_types.so" successfully loaded.
[INF]: LY: Plugin "/usr/local/lib/libyang/user_types/user_yang_types.so" successfully loaded.
[INF]: LY: Reading module "ietf-yang-metadata".
[INF]: LY: Module "ietf-yang-metadata@2016-08-05" successfully parsed as implemented.
[INF]: LY: Reading module "yang".
[INF]: LY: Resolving "yang" unresolved schema nodes and their constraints...
[INF]: LY: All "yang" schema nodes and constraints resolved.
[INF]: LY: Module "yang@2017-02-20" successfully parsed as implemented.
[INF]: LY: Reading module "ietf-inet-types".
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-inet-types" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-inet-types@2013-07-15" successfully parsed as implemented.
[INF]: LY: Reading module "ietf-yang-types".
[INF]: LY: Module "ietf-yang-types@2013-07-15" successfully parsed as implemented.
[INF]: LY: Reading module "ietf-datastores".
[INF]: LY: Module "ietf-datastores@2017-08-17" successfully parsed as implemented.
[INF]: LY: Reading module "ietf-yang-library".
[INF]: LY: Searching for "ietf-yang-types" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Searching for "ietf-yang-types" in /home/celeno/netconf/Netopeer2/server/build.
[INF]: LY: Searching for "ietf-inet-types" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Searching for "ietf-inet-types" in /home/celeno/netconf/Netopeer2/server/build.
[INF]: LY: Searching for "ietf-datastores" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Searching for "ietf-datastores" in /home/celeno/netconf/Netopeer2/server/build.
[INF]: LY: Module "ietf-yang-library@2019-01-04" successfully parsed as implemented.
[INF]: LY: Resolving "sysrepo" unresolved schema nodes and their constraints...
[INF]: LY: All "sysrepo" schema nodes and constraints resolved.
[INF]: LY: Module "sysrepo@2020-01-15" successfully parsed as implemented.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Applying scheduled changes.
[INF]: LY: Searching for "ietf-netconf-with-defaults" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/ietf-netconf-with-defaults@2011-06-01.yang" file.
[INF]: LY: Searching for "ietf-netconf" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Searching for "ietf-netconf" in /home/celeno/netconf/Netopeer2/server/build.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/ietf-netconf@2013-09-29.yang" file.
[INF]: LY: Searching for "ietf-netconf-acm" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Searching for "ietf-netconf-acm" in /home/celeno/netconf/Netopeer2/server/build.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/ietf-netconf-acm@2018-02-14.yang" file.
[INF]: LY: Module "ietf-netconf-acm@2018-02-14" successfully parsed as imported.
[INF]: LY: Module "ietf-netconf@2013-09-29" successfully parsed as imported.
[INF]: LY: Resolving "ietf-netconf-with-defaults" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-netconf-with-defaults" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-netconf-with-defaults@2011-06-01" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-netconf-notifications" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/ietf-netconf-notifications@2012-02-06.yang" file.
[INF]: LY: Resolving "ietf-netconf-notifications" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-netconf-notifications" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-netconf-notifications@2012-02-06" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-origin" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/ietf-origin@2018-02-14.yang" file.
[INF]: LY: Searching for "ietf-yang-metadata" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Searching for "ietf-yang-metadata" in /home/celeno/netconf/Netopeer2/server/build.
[INF]: LY: Resolving "ietf-origin" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-origin" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-origin@2018-02-14" successfully parsed as implemented.
[INF]: LY: Module "ietf-netconf-acm@2018-02-14" now implemented.
[INF]: LY: Searching for "ietf-netconf-monitoring" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/ietf-netconf-monitoring@2010-10-04.yang" file.
[INF]: LY: Module "ietf-netconf-monitoring@2010-10-04" successfully parsed as implemented.
[INF]: LY: Module "ietf-datastores@2017-08-17" now implemented.
[INF]: LY: Searching for "ietf-netconf-nmda" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/ietf-netconf-nmda@2019-01-07.yang" file.
[INF]: LY: Searching for "ietf-origin" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Searching for "ietf-origin" in /home/celeno/netconf/Netopeer2/server/build.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/ietf-origin@2018-02-14.yang" file.
[INF]: LY: Searching for "ietf-netconf-with-defaults" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Searching for "ietf-netconf-with-defaults" in /home/celeno/netconf/Netopeer2/server/build.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/ietf-netconf-with-defaults@2011-06-01.yang" file.
[INF]: LY: Resolving "ietf-netconf-nmda" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-netconf-nmda" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-netconf-nmda@2019-01-07" successfully parsed as implemented.
[INF]: LY: Searching for "nc-notifications" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/nc-notifications@2008-07-14.yang" file.
[INF]: LY: Searching for "notifications" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Searching for "notifications" in /home/celeno/netconf/Netopeer2/server/build.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/notifications@2008-07-14.yang" file.
[INF]: LY: Module "notifications@2008-07-14" successfully parsed as imported.
[INF]: LY: Module "nc-notifications@2008-07-14" successfully parsed as implemented.
[INF]: LY: Module "notifications@2008-07-14" now implemented.
[INF]: LY: Searching for "ietf-x509-cert-to-name" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/ietf-x509-cert-to-name@2014-12-10.yang" file.
[INF]: LY: Module "ietf-x509-cert-to-name@2014-12-10" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-crypto-types" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/ietf-crypto-types@2019-07-02.yang" file.
[INF]: LY: Module "ietf-crypto-types@2019-07-02" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-keystore" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/ietf-keystore@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-crypto-types" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Searching for "ietf-crypto-types" in /home/celeno/netconf/Netopeer2/server/build.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/ietf-crypto-types@2019-07-02.yang" file.
[INF]: LY: Resolving "ietf-keystore" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-keystore" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-keystore@2019-07-02" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-truststore" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/ietf-truststore@2019-07-02.yang" file.
[INF]: LY: Module "ietf-truststore@2019-07-02" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-tcp-common" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/ietf-tcp-common@2019-07-02.yang" file.
[INF]: LY: Module "ietf-tcp-common@2019-07-02" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-ssh-server" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/ietf-ssh-server@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-ssh-common" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/ietf-ssh-common@2019-07-02.yang" file.
[INF]: LY: Module "ietf-ssh-common@2019-07-02" successfully parsed as imported.
[INF]: LY: Searching for "ietf-keystore" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Searching for "ietf-keystore" in /home/celeno/netconf/Netopeer2/server/build.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/ietf-keystore@2019-07-02.yang" file.
[INF]: LY: Searching for "iana-crypt-hash" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Searching for "iana-crypt-hash" in /home/celeno/netconf/Netopeer2/server/build.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/iana-crypt-hash@2014-08-06.yang" file.
[INF]: LY: Module "iana-crypt-hash@2014-08-06" successfully parsed as imported.
[INF]: LY: Module "ietf-ssh-server@2019-07-02" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-tls-server" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/ietf-tls-server@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-tls-common" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/ietf-tls-common@2019-07-02.yang" file.
[INF]: LY: Module "ietf-tls-common@2019-07-02" successfully parsed as imported.
[INF]: LY: Searching for "ietf-truststore" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Searching for "ietf-truststore" in /home/celeno/netconf/Netopeer2/server/build.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/ietf-truststore@2019-07-02.yang" file.
[INF]: LY: Module "ietf-tls-server@2019-07-02" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-netconf-server" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/ietf-netconf-server@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-x509-cert-to-name" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Searching for "ietf-x509-cert-to-name" in /home/celeno/netconf/Netopeer2/server/build.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/ietf-x509-cert-to-name@2014-12-10.yang" file.
[INF]: LY: Searching for "ietf-tcp-client" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Searching for "ietf-tcp-client" in /home/celeno/netconf/Netopeer2/server/build.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/ietf-tcp-client@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-tcp-common" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Searching for "ietf-tcp-common" in /home/celeno/netconf/Netopeer2/server/build.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/ietf-tcp-common@2019-07-02.yang" file.
[INF]: LY: Module "ietf-tcp-client@2019-07-02" successfully parsed as imported.
[INF]: LY: Searching for "ietf-tcp-server" in /home/celeno/netconf/sysrepo/build/repository/yang.
[INF]: LY: Searching for "ietf-tcp-server" in /home/celeno/netconf/Netopeer2/server/build.
[INF]: LY: Loading schema from "/home/celeno/netconf/sysrepo/build/repository/yang/ietf-tcp-server@2019-07-02.yang" file.
[INF]: LY: Module "ietf-tcp-server@2019-07-02" successfully parsed as imported.
[INF]: LY: Resolving "ietf-netconf-server" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-netconf-server" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-netconf-server@2019-07-02" successfully parsed as implemented.
[INF]: SR: No scheduled changes.
[INF]: SR: Session 1 (user "root") created.
[INF]: SR: Ext SHM was defragmented and 4296 B were saved.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Ext SHM was defragmented and 4120 B were saved.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
`

`celeno@celeno-VirtualBox:~/netconf/sysrepo/build$ netopeer2-cli

verb debug
connect
nc DEBUG: nc_sock_connect(localhost, 830, -1, -1)
nc VERBOSE: Trying to connect via IPv4 to 127.0.0.1:830.
nc VERBOSE: getsockopt() error (Connection refused).
nc ERROR: Unable to connect to localhost:830 (Connection refused).
cmd_connect: Connecting to the localhost:830 as user "celeno" failed.

`
Could you help me please?

**Comment by michalvasko** [comment]
Hi,
I am not sure what *netopeer2* version are you using, so your output may differ slightly, but this is my output of a fresh installation
```
...
[INF]: LY: Module "ietf-tcp-server@2019-07-02" successfully parsed as imported.
[INF]: LY: Resolving "ietf-netconf-server" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-netconf-server" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-netconf-server@2019-07-02" successfully parsed as implemented.
[INF]: SR: Session 8 (user "root") created.
[INF]: SR: Ext SHM was defragmented and 4152 B were saved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: There is no leafref "/ietf-keystore:keystore/ietf-keystore:asymmetric-keys/ietf-keystore:asymmetric-key/ietf-keystore:name" with the value "genkey", but it is not required.
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: LN: Listening on 0.0.0.0:830 for SSH connections.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Ext SHM was defragmented and 4152 B were saved.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-keystore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-truststore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
```
and you are missing the message
```
[INF]: LN: Listening on 0.0.0.0:830 for SSH connections.
```
so your server is not listening on any interfaces. Check `ietf-netconf-server` configuration.

Regards,
Michal

**Comment by change-my-username** [comment]
I`ve checked this two files 
> $ vim sysrepo/build/repository/yang/ietf-netconf-server@2019-07-02.yang
> $ vim Netopeer2/modules/ietf-netconf-server@2019-07-02.yang
And they both have, at least, ssh-call-home and ssh-listen feature. Sysrepo confirms

**Comment by change-my-username** [comment]
I`ve checked this two files

$ vim sysrepo/build/repository/yang/ietf-netconf-server@2019-07-02.yang
$ vim Netopeer2/modules/ietf-netconf-server@2019-07-02.yang

And they both have, at least, ssh-call-home and ssh-listen feature. Sysrepo confirms

ietf-netconf-server | 2019-07-02 |   | root:root     | 600    |     | ssh-listen tls-listen ssh-call-home tls-call-home 

So. I`ve tried to download and build netopeer server and  I`ve had the error after make install 

$ sudo make install

[ 81%] Built target serverobj
[100%] Built target netopeer2-server
Install the project...
-- Install configuration: "debug"
-- Up-to-date: /usr/local/bin/netopeer2-server
-- Installing sysrepo modules...
[ERR]: Module "ietf-netconf-acm" not scheduled for deletion.
[ERR]: Module "ietf-netconf-acm" is already in sysrepo.
[ERR]: Module "ietf-netconf@2013-09-29" already installed.
sysrepoctl error: Failed to update module "/home/celeno/netconf/Netopeer2/server/../modules/ietf-netconf@2013-09-29.yang" (Item already exists)
-- Generating a new RSA host key "genkey"...
-- Merging default server listen configuration...

cmake and make passed successful

**Comment by change-my-username** [comment]
Well, I am sorry for disturbing. I run netopeer server and it works properly. It is kind of magic. I just download and build netopeer server ("make install" with error by the way). Thanks for your reply.

**Comment by michalvasko** [comment]
Hi,
it is not magic. I told you to look at __configuration__ and not YANG modules or their features. Try `sysrepocfg -X -m ietf-netconf-server`, for example. It works after `make install` because of precisely what it says it does
```
-- Generating a new RSA host key "genkey"...
-- Merging default server listen configuration...
```
meaning it has imported the listening configuration so that the server listens on `0.0.0.0` after start. The modules were already installed so they failed to be installed again. I suppose you installed them manually, which you should not have. If you simply run `make install`, it would all get performed automatically and work out-of-the-box.

Regards,
Michal
