### ISSUE TITLE
Error occurred when use get-config to get state data 

### ISSUE THREAD

**Issue by zzyyll2** [CESNET/Netopeer2#58]
If there ars some state yang model and data(config=false) in sysrepo,when using get --filter-xpath=/stateModel:stateModel in netopeer2-cli，it get some correct data,but using get-config --source running,it response error msg back.
like this,dataAid is a leaf with config=false property.
> get-config --source running
ly ERROR: Unknown element "dataAid". (/stateModel:stateModel/dataAid)
nc ERROR: Failed to parse <get-config> reply.
cli_send_recv: Failed to receive a reply.

**Comment by michalvasko** [comment]
Hi,
it should work now, please verify.

Regards,
Michal
