### ISSUE TITLE
Netopeer2-client issue

### ISSUE THREAD

**Issue by Arvliu** [CESNET/Netopeer2#580]
Hi,

netopeer2-cli is not able to parse command: 
>get  --filter-xpath /mavenir-stats:stats/intervals/interval[start-time='2020-03-20 15:25:00']
cmd_get: Unparsed command arguments.
get [--help] [--filter-subtree[=<file>] | --filter-xpath <XPath>] [--defaults report-all|report-all-tagged|trim|explicit] [--out <file>]

But it changed the command like this:
>get  --filter-xpath /mavenir-stats:stats/intervals/interval[start-time='2020-03-20T15:25:00']
it can be executed successfully.

Since we have to use the format of the first command, can you help solve this problem? Thanks.

**Comment by michalvasko** [comment]
Hi,
just use quotes
```
get --filter-xpath "/mavenir-stats:stats/intervals/interval[start-time='2020-03-20 15:25:00']"
```
How else is the CLI supposed to know the space you used is not another argument but still part of the previous one?

Regards,
Michal

**Comment by Arvliu** [comment]
Hi, Michal

Using quotes works, thanks very much.

Best regards,
