### ISSUE TITLE
Edit-config issue on netopeer2-server with a different Netconf client.

### ISSUE THREAD

**Issue by Akhil-123456789** [CESNET/netopeer2#581]
I have connected  the netopeer2-server and i am trying to changing the attributes values in container by using edit-config. It is giving the error as "Server Error. Status: [500] RemoteDevice{Test}: Commit of transaction failed".
Could please help me in this issue.

Netopeer2-server log attached below of netopeer2 errors.

[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Session 538 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 21 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:get-config" "rpc" event with ID 21 priority 0 (remaining 1 subscribers).
[INF]: SR: Finished processing "rpc" event with ID 21 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 21 priority 0 succeeded.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: NP: Session 2: thread 2 event new RPC.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Session 539 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 5 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:lock" "rpc" event with ID 5 priority 0 (remaining 1 subscribers).
[ERR]: SR: Callback event "rpc" with ID 5 processing timed out.
[WRN]: SR: Event "rpc" with ID 5 priority 0 failed (Timeout expired).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 2: thread 4 event new RPC.
[INF]: NP: Session 2: thread 4 event reply error.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Session 540 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[ERR]: SR: Module "yang" is locked by session 505 (NC SID 2).
[INF]: SR: Published event "rpc" with ID 6 priority 0 for 1 subscribers.
[ERR]: SR: Unable to finish processing event "rpc" with ID 5 priority 0 (timeout probably).
[INF]: SR: Processing "/ietf-netconf:lock" "rpc" event with ID 6 priority 0 (remaining 1 subscribers).
[ERR]: SR: Callback event "rpc" with ID 6 processing timed out.
[WRN]: SR: Event "rpc" with ID 6 priority 0 failed (Timeout expired).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 2: thread 4 event new RPC.
[INF]: NP: Session 2: thread 4 event reply error.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Session 541 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[ERR]: SR: Module "yang" is locked by session 506 (NC SID 2).
[INF]: LY: All data nodes and constraints resolved.
[ERR]: SR: Unable to finish processing event "rpc" with ID 6 priority 0 (timeout probably).
[INF]: SR: Published event "rpc" with ID 22 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:get-config" "rpc" event with ID 22 priority 0 (remaining 1 subscribers).
[INF]: SR: Finished processing "rpc" event with ID 22 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 22 priority 0 succeeded.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: NP: Session 2: thread 4 event new RPC.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Session 542 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 3 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 3 priority 0 (remaining 1 subscribers).
[ERR]: SR: Callback event "rpc" with ID 3 processing timed out.
[ERR]: SR: Module "oven" is locked by session 506 (NC SID 2).
[WRN]: SR: Event "rpc" with ID 3 priority 0 failed (Timeout expired).
[ERR]: SR: Unable to finish processing event "rpc" with ID 3 priority 0 (timeout probably).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 2: thread 0 event new RPC.
[INF]: NP: Session 2: thread 0 event reply error.
[INF]: SR: Session 543 (user "root") created.
[INF]: SR: Published event "rpc" with ID 3 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:commit" "rpc" event with ID 3 priority 0 (remaining 1 subscribers).
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[ERR]: SR: Callback event "rpc" with ID 3 processing timed out.
[WRN]: SR: Event "rpc" with ID 3 priority 0 failed (Timeout expired).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 2: thread 0 event new RPC.
[INF]: NP: Session 2: thread 0 event reply error.
[ERR]: SR: Module "yang" is locked by session 505 (NC SID 2).
[ERR]: SR: Unable to finish processing event "rpc" with ID 3 priority 0 (timeout probably).
[INF]: SR: Session 544 (user "root") created.
[INF]: SR: Published event "rpc" with ID 3 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:discard-changes" "rpc" event with ID 3 priority 0 (remaining 1 subscribers).
[INF]: SR: Finished processing "rpc" event with ID 3 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 3 priority 0 succeeded.
[INF]: NP: Session 2: thread 2 event new RPC.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Session 545 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 5 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:unlock" "rpc" event with ID 5 priority 0 (remaining 1 subscribers).
[ERR]: SR: Callback event "rpc" with ID 5 processing timed out.
[WRN]: SR: Event "rpc" with ID 5 priority 0 failed (Timeout expired).
[ERR]: SR: Module "yang" is locked by session 506 (NC SID 2).
[ERR]: SR: Unable to finish processing event "rpc" with ID 5 priority 0 (timeout probably).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 2: thread 2 event new RPC.
[INF]: NP: Session 2: thread 2 event reply error.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Session 546 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 6 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:unlock" "rpc" event with ID 6 priority 0 (remaining 1 subscribers).
[ERR]: SR: Callback event "rpc" with ID 6 processing timed out.
[WRN]: SR: Event "rpc" with ID 6 priority 0 failed (Timeout expired).
[ERR]: SR: Module "yang" is locked by session 505 (NC SID 2).
[ERR]: SR: Unable to finish processing event "rpc" with ID 6 priority 0 (timeout probably).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 2: thread 2 event new RPC.
[INF]: NP: Session 2: thread 2 event reply error.

**Comment by michalvasko** [comment]
Hi,
I am not sure about the log because it only says that `<lock>` RPC timed out, which then resulted in the rest of the errors. However, working with metadata (XML attributes) is not supported by NETCONF (not specified anywhere) so whatever you were doing, it was wrong.

Regards,
Michal

**Comment by Akhil-123456789** [comment]
how to enable the content of RPC received at netopeer2 server ?

**Comment by michalvasko** [comment]
Hi,
by `netopeer2-server -c MSG`, works only when build in debug mode.

Regards,
Michal

**Comment by Akhil-123456789** [comment]
Hi,
Below is the RPC being sent from a client, not sure why is failing on server side.

<rpc  message-id="m-4" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<edit-config>
<target>
<candidate/>
</target>
<error-option>rollback-on-error</error-option>
<config>
<oven xmlns="urn:sysrepo:oven" xmlns:a="urn:ietf:params:xml:ns:netconf:base:1.0" a:operation="replace">
<temperature>45</temperature>
<turned-on>true</turned-on>
</oven>
</config>
</edit-config>
</rpc>

Could you please help me in this issue.

**Comment by michalvasko** [comment]
Hi,
I do not know either. If the initial server output is still relevant then there is some problem with how the datastore is locked, possibly just a timeout problem but it is hard to guess. You can increase the timeouts in *netopeer2* by setting `DATA_CHANGE_TIMEOUT` and `RPC_TIMEOUT` (only in `devel`).

Regards,
Michal

**Comment by Akhil-123456789** [comment]
Hi,
I am trying to perform the edit-config operation by using netopeer2-cli and it is getting error. 
I am not able find the issue.
```
<SubNetwork
 xmlns="urn:3gpp:sa5:_3gpp-common-subnetwork"
 xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <id>3</id>
  <attributes>
   <userLabel>Test</userLabel>
   <priorityLabel>5</priorityLabel>
  </attributes>
  <MeasurementControl xmlns="urn:3gpp:sa5:_3gpp-common-measurements">
   <id>6</id>
   <MeasurementReader>
    <id>7</id>
    <attributes>
     <measurementTypes>abc</measurementTypes>
    </attributes>
   </MeasurementReader>
  </MeasurementControl>
</SubNetwork>
```
Netopeer-cli Error::

> edit-config --target running --config=/usr/local/bin/subnetwork.xml
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	path:     /_3gpp-common-subnetwork:SubNetwork[id='3']
	message:  Unknown element "MeasurementControl".

Netopeer2 server log::

[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Session 18 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 3 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 3 priority 0 (remaining 1 subscribers).
[INF]: NP: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
[ERR]: LY: Unknown element "MeasurementControl". (/_3gpp-common-subnetwork:SubNetwork[id='3'])
[INF]: SR: Finished processing "rpc" event (callback fail) with ID 3 priority 0 (remaining 1 subscribers).
[ERR]: SR: Unknown element "MeasurementControl".
[WRN]: SR: Event "rpc" with ID 3 priority 0 failed (libyang error).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 2: thread 2 event new RPC.
[INF]: NP: Session 2: thread 2 event reply error.

**Comment by michalvasko** [comment]
Hi,
I cannot know what the exact problem is without seeing the YANG modules. Most likely the node `MeasurementControl` does not belong to the namespace `urn:3gpp:sa5:_3gpp-common-measurements` or has a disabled `if-feature`.

Regards,
Michal

**Comment by Akhil-123456789** [comment]
Hi,
Please find the below yang model and also edit-config operations.
Please let me know what are change i need to do for working it. so i can do some operation on 3gpp measurement yang model. 
```
<SubNetwork
 xmlns="urn:3gpp:sa5:_3gpp-common-subnetwork"
 xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <id>3</id>
  <attributes>
   <userLabel>Test</userLabel>
   <priorityLabel>5</priorityLabel>
  </attributes>
  <MeasurementControl xmlns="urn:3gpp:sa5:_3gpp-common-measurements">
   <id>6</id>
   <MeasurementReader>
    <id>7</id>
    <attributes>
     <measurementTypes>abc</measurementTypes>
    </attributes>
   </MeasurementReader>
  </MeasurementControl>
</SubNetwork>
```

```
module _3gpp-common-subnetwork {
 yang-version 1.1;
 namespace "urn:3gpp:sa5:_3gpp-common-subnetwork";
 prefix "subnet3gpp";

 import _3gpp-common-yang-types { prefix types3gpp; }
 import _3gpp-common-top { prefix top3gpp; }
 import _3gpp-common-measurements { prefix meas3gpp; }
 import ietf-yang-schema-mount { prefix yangmnt; }
 organization "3GPP SA5";

 description "Defines basic SubNetwork which will be augmented by other IOCs";
 reference "3GPP TS 28.622
 Generic Network Resource Model (NRM)
 Integration Reference Point (IRP);
 Information Service (IS)

 3GPP TS 28.620
 Umbrella Information Model (UIM)";

 revision 2019-06-17 {
 description "Initial revision";
 reference "Based on
 3GPP TS 28.620 V15.X.XX
 3GPP TS 28.622 V15.X.XX";
 }
 feature ExternalsUnderSubNetwork {
 description "Classes representing external entities like EUtranFrequency,
 ExternalGNBCUCPFunction, ExternalENBFunction
 are contained under a Subnetwork list/class.";
 }

 feature MeasurementsUnderSubNetwork {
 description "The MeasurementSubtree shall be contained under SubNetwork";
 }

 grouping Domain_Grp {
 description "A domain is a partition of instances of managed entities
 such that :
 - the group represents a topological structure which describes the
 potential for connectivity
 - Subject to common administration
 - With common characteristics";

 leaf dnPrefix {
 type types3gpp:DistinguishedName;
 reference "Annex C of 32.300 ";
 }

 leaf userLabel {
 type string;
 description "A user-friendly (and user assignable) name of this object.";
 }

 leaf userDefinedNetworkType {
 type string;
 description "Textual information indicating network type, e.g. 'UTRAN'.";
 }
 }
 grouping SubNetworkGrp {
 uses Domain_Grp;
 uses meas3gpp:Measurements;

 leaf-list setOfMcc {
 description "Set of Mobile Country Code (MCC).
 The MCC uniquely identifies the country of domicile 
 of the mobile subscriber. MCC is part of the IMSI (3GPP TS 23.003)
 This list contains all the MCC values in subordinate object
 instances to this SubNetwork instance.
 See clause 2.3 of 3GPP TS 23.003 for MCC allocation principles.
 It shall be supported if there is more than one value in setOfMcc
 of the SubNetwork. Otherwise the support is optional.";
 type types3gpp:Mcc;
 }
 leaf priorityLabel {
 mandatory true;
 type uint32;
 }

 }
 list SubNetwork {
 key id;
 description "Represents a set of managed entities";
 uses top3gpp:Top_Grp;
 container attributes {
 uses SubNetworkGrp;
 leaf-list parents {
 description "Reference to all containg SubNetwork instances
 in strict order from the root subnetwork down to the immediate
 parent subnetwork.
 If subnetworks form a containment hierarchy this is
 modeled using references between the child SubNetwork and the parent
 SubNetworks.
 This reference MUST NOT be present for the top level SubNetwork and
 MUST be present for other SubNetworks.";
 type leafref {
 path "../../../SubNetwork/id";
 }
 }

 leaf-list containedChildren{
 description "Reference to all directly contained SubNetwork instances.
 If subnetworks form a containment hierarchy this is
 modeled using references between the child SubNetwork and the parent
 SubNetwork.";
 type leafref {
 path "../../../SubNetwork/id";
 }
 }
 }

 uses meas3gpp:MeasurementSubtree {
 if-feature MeasurementsUnderSubNetwork ;
 }
 yangmnt:mount-point children-of-SubNetwork {
 description "Mountpoint for ManagedElement";
 reference "RFC8528 YANG Schema Mount";
 }

 // augment external parts here
 }
} 



module _3gpp-common-measurements {
 yang-version 1.1;
 namespace "urn:3gpp:sa5:_3gpp-common-measurements";
 prefix "meas3gpp";

 import _3gpp-common-top { prefix top3gpp; }
 import _3gpp-common-yang-types { prefix types3gpp; }
 organization "3GPP SA5";

 description "Defines Measurement related groupings
 Any list/class intending to use this should include 2 uses statements
 controlled by a feature:

 A)
+++ feature MeasurementsUnderMyClass {
+++ description 'Indicates whether measurements are supported for this class.';
+++ }

 B) include the attribute supportedMeasurementsGPs indicating the
 supported measurmentTypes and GPs. Note that for classes inheriting from
 ManagedFunction, EP_RP or SubNetwork this attribute is already inherited,
 so there is no need to include it once more.E.g.

 grouping MyClassGrp {
+++ uses meas3gpp:Measurements;
 }

 C) include the classes MeasurementControl & MeasuremntReader to
 control the measurements. E.g.

 list MyClass {
 container attributes {
 uses MyClassGrp;
 }
+++ uses meas3gpp:MeasurementSubtree {
+++ if-feature MeasurementsUnderMyClass ;
+++ }
 }

 Measurements can be contained under ManagedElement, SubNetwork, or
 any list representing a class inheriting from EP_RP, Subnetwork or
 ManagedFunction.";

 reference "3GPP TS 28.622
 Generic Network Resource Model (NRM) 
 Integration Reference Point (IRP);
 Information Service (IS)";
 revision 2019-06-17 {
 reference "Based on
 3GPP TS 28.622 V15.X.XX";
 }

 feature StreamingSupported {
 description "The delivery of measurement data using streaming is supported.";
 }
 grouping Measurements {
 description "Identifies the supported Measurement types and their
 supported GPs.";

 list supportedMeasurementsGPs {
 config false;
 key measurementType;
 description "List of supported Measurement types and their
 supported GPs for the parent function/class";

 leaf measurementType {
 type string;
 }

 leaf-list supportedGPs {
 type uint32 ;
 min-elements 1;
 units second;
 description "GP (granularity period) is the time between the initiation
 of two successive gatherings of measurement data.";
 }
 }
 }

 grouping MeasurementControlGrp {
 description "represents the capabilities to produce and deliver Measurements
 identified by a MeasurementReader.
 There are two delivery methods (i.e. file-based and stream-based) via
 which the consumer(s) can receive the Measurements.";
 leaf pMAdministrativeState {
 default LOCKED;
 type types3gpp:AdministrativeState ;
 description "It describes the permission to use or prohibition against
 using the capability of MeasurementControl, imposed through the consumer
 of OAM services produced by MeasurementControl,
 The measurement report production would begin when pMadministrativeState
 is UNLOCKED and pMoperationalState is ENABLED.";
 }

 leaf pMOperationalState {
 config false;
 mandatory true;
 type types3gpp:OperationalState ;
 description "Indicates whether the MeasurementControl is working.";
 }
 leaf defaultFileLocation {
 type string ;
 description "It is the path to the location where produced
 measurement reports (containing PM data) are stored. File based
 measurement delivery will not start if this leaf does not have a
 valid value.

 It is the path to a location on either the producer’s file system or a
 URI to a network file location that is not part of the producer’s file
 system. In case it points to a location on the producer’s file system,
 it is a relative path based on a vendor-specified root directory for
 measurement files.

 The size of this fileLocation is decided by consumer and producer.
 The producer is expected to remove old files to make room for
 new files, when necessary.

 This value is ignored in case the fileLocation leaf in the 
 MeasurementReader is defined.";
 }

 leaf defaultFileBasedGP {
 when '../defaultFileLocation' ;
 mandatory true;
 type uint32 ;
 units second;
 description "GP (granularity period) defines the frequency of producing
 measurement data. Measurement data would be produced immediately at the
 end of each fileBasedGP.

 This value is ignored in case the fileBasedGP leaf in the
 MeasurementReader is defined.";
 }

 leaf defaultFileReportingPeriod {
 when '../defaultFileLocation' ;
 must '. *60 >= ../defaultFileBasedGP' {
 error-message "defaultFileBasedGP must not be greater than defaultFileReportingPeriod";
 }
 mandatory true;
 type uint32 ;
 units minute;
 description "The frequency of producing the measurement report files.
 A measurement report file contains multiple measurement data.

 This value is ignored in case the fileReportingPeriod leaf in the
 MeasurementReader is defined.";
 }

 leaf defaultStreamTarget {
 if-feature StreamingSupported ;
 type string ;
 description "Identifies the target of the notifications carrying the
 content of the measurement report.
 This value is ignored in case the streamTarget leaf in the
 MeasurementReader is defined.";
 }

 leaf defaultStreamBasedGP {
 if-feature StreamingSupported ;
 when '../defaultStreamTarget' ;
 mandatory true;
 type uint32 ;
 units second;
 description "It defines the frequency of producing and sending the
 Measurement to the streamTargets.

 This value is ignored in case the streamBasedGP leaf in the
 MeasurementReader is defined.";
 }
 }

 grouping MeasurementReaderGrp {
 description "Identifies the entity whose Measurements are required by
 consumer, the types of Measurements required and the delivery method for
 the measurements.";
 leaf-list measurementTypes {
 type string ;
 description "The Measurement type to be reported. It must be one of the
 measurmentTypes supported by the containing function/class.
 The Measurement type can be those specified in TS 28.552,
 TS 32.404 and can be those specified by other SDOs or can be
 vendor-specific.";
 }

 leaf-list managedObjectDNsBasic {
 type types3gpp:DistinguishedName ;
 description "Identifies the managed functions whose Measurements are
 required to be produced.

 It identifies specific managed entities (say X, Y, Z). It would mean
 Measurements type specified in MeasurementReader.measurementTypes,
 are required to be produced if X, Y, Z are capable of supporting
 the Measurement types. 
 If managedObjectDNs of the same MeasurementReader instance has valid
 information, the information of this leaf-list is ignored.";
 }

 leaf-list managedObjectDNs {
 type types3gpp:DistinguishedName ;
 description "Identifies the managed entities whose Measurements are
 required to be produced.
 In case the base is SubNetwork, it identifies all, including the base,
 managed entities that are subordinates, in the sense of name-containment,
 of the base.
 In case the base is NetworkSliceSubnet, it identifies all, including
 the base, managed entities that has aggregation association relation
 with the base.
 We called the identified entities a collection. It would mean
 Measurement types specified in attribute
 MeasurementReader.measurementTypes, are required to be produced if the
 member (of the collection) is capable of supporting the Measurement
 types.";
 }
 leaf fileLocation {
 type string ;
 description "It is the path to the location where produced
 measurement reports (containing PM data) are stored. File based
 measurement delivery will not start if this leaf does not have a
 valid value.

 It is the path to a location on either the producer’s file system or a
 URI to a network file location that is not part of the producer’s file
 system. In case it points to a location on the producer’s file system,
 it is a relative path based on a vendor-specified root directory for
 measurement files.

 The size of this fileLocation is decided by consumer and producer.
 The producer is expected to remove old files to make room for
 new files, when necessary.

 If defined this value overrides the value of defaultFileLocation in the
 parent MeasuremnetControl.";
 }

 leaf fileBasedGP {
 when '../fileLocation' ;
 mandatory true;
 type uint32 ;
 units second;
 description "GP (granularity period) defines the frequency of producing
 measurement data.";
 }

 leaf fileReportingPeriod {
 when '../fileLocation' ;
 must '. *60 >= ../fileBasedGP' {
 error-message "fileBasedGP must not be greater than fileReportingPeriod";
 }
 mandatory true;
 type uint32 ;
 units minute;
 description "The frequency of producing the measurement report files.";
 }

 leaf streamTarget {
 when 'not(../fileLocation)' ;
 type string ;
 description "Identifies the target of the notification carrying the
 content of the measurement report.
 There are two delivery methods (i.e. file-based and stream-based) via
 which the consumer(s) can receive the Measurements. This attribute
 is used for the stream-based delivery method.";
 }

 leaf streamBasedGP {
 when '../streamTarget' ; 
 mandatory true;
 type uint32 ;
 units second;
 description "Defines the frequency of producing and sending the
 Measurement to the consumer.";
 }
 }

 grouping MeasurementSubtree {
 description "Contains classes that define measurements.
 Should be used in al classes (or classes inheriting from)
 - SubNnetwork
 - ManagedElement
 - ManagedFunction
 - NetworkSliceSubnet
 - EP_RP

 If some YAM wants to augment these classes/list/groupings they must
 augment all user classes!

 If a class uses this grouping in its list it shall also use the
 grouping Measurements to add supportedMeasurementsGPs as
 an attribute to its grouping";

 list MeasurementControl {
 description "Represents the properties of the file-based and stream-based
 measurement delivery methods.

 The file-based delivery method has properties for the file location,
 the file reporting period and the file-based GP.
 The stream-based delivery method has properties for the stream target
 and the stream-based GP.
 These properties are labelled as default (e.g. defaultFileBasedGP) in
 that they will be ignored in case the same properties captured in
 MeasurementReader are used.

 Instance of this list shall not be created nor deleted by client. It
 shall be created and deleted by the system.
 Depending on particular deployment context and agreement between
 operator and vendor, all attributes could be config=false.";
 key id;
 uses top3gpp:Top_Grp ;
 container attributes {
 uses MeasurementControlGrp ;
 }

 list MeasurementReader {
 description "Identifies the entity (derivatives of ManagedFunction)
 whose Measurements are required by consumer to be produced and
 captured. The types of Measurements required are identified by the
 measurementNames.

 It captures the properties of the two delivery methods for delivering
 the Measurements.
 The file-based delivery method has properties: fileLocation,
 reportingPeriod and fileBasedGP.
 The stream-based delivery method has properties: streamTarget and
 streamBasedGP.
 The parent MeasurementControl list entry also can capture the
 properties of the file-based and stream-based delivery methods.
 If the MeasurementReader instance’s file-based delivery method has
 valid properties, the file-based delivery method is used and the
 MeasurementControl instance’s file-based delivery method is ignored.
 If the MeasurementReader instance’s stream-based delivery method has
 valid properties, the stream-based delivery method is used and the
 MeasurementControl instance’s stream-based delivery is ignored.
 The file-based and stream-based delivery methods can be active at the
 same time for a MeasurementReader instance.
 The activity of a MeasurementReader instance is independent of that
 of other MeasurementReader instances.
 This IOC uses managedObjectDNs or managedObjectDNsBasic to identify
 specific managed entities whose Measurements are required by consumer.";

 key id; 
 uses top3gpp:Top_Grp ;
 container attributes {
 uses MeasurementReaderGrp;
 }
 }
 }
 }
} 
```

**Comment by michalvasko** [comment]
Hi,
so it seems you are using schemas with `schema-mount` extension and *libyang* does not support that currently. But may soon (cesnet/libyang#691).

Regards,
Michal
