### ISSUE TITLE
subscribe --filter-xpath failed

### ISSUE THREAD

**Issue by Arvliu** [CESNET/Netopeer2#582]
Hi,

I met a netopeer2-cli subscribe issue:

>subscribe --filter-xpath /xran-troubleshooting:troubleshooting-log-generated
ly ERROR: Module name "xran-troubleshooting" refers to an unknown module.
cli_send_recv: Failed to send the RPC.

I have successfully  installed xran-troubleshooting.yang using command:
./sysrepoctl --install --yang=/netconf/share/logs/xran-troubleshooting.yang

And, i have tried another yang module:
subscribe --filter-xpath /xran-file-management:file-upload-notification
>ok

Can you help to solve this issue? Thanks.

**Comment by michalvasko** [comment]
Hi,
please post the output of `sysrepoctl -v3 -l`, thanks.

Regards,
Michal

**Comment by Arvliu** [comment]
Hi,

The details are as below:
./sysrepoctl -v3 -l
sysrepoctl - sysrepo control tool, version 0.7.8

./sysrepoctl  -l
xran-troubleshooting        | 2018-07-20 | Installed   | root:root           | 666         |                               |


Best regards,
Arvin.

**Comment by michalvasko** [comment]
Hi,
oh, you are using the deprecated *sysrepo* version 0.7.8. If I had some spare time I may have taken a look but it is not the case. So I am sorry, but I am not able to provide support. I can only suggest to switch to the current *sysrepo* version 1.x.

Regards,
Michal

**Comment by Arvliu** [comment]
Hi,

Sorry for late reply.
The issue had been solved.
Thanks.

Best regards,
Arvin.
