### ISSUE TITLE
Timed command in Netopeer2-cli

### ISSUE THREAD

**Issue by ChinmayaAgarwal** [CESNET/Netopeer2#583]
We executed "timed on" and after that on executing edit-config we get the following out put :   
> edit-config --target running --config=/root/srv6_policy_config.xml
OK
mono  0m1,011s

What is the meaning of the string **mono  0m1,011s**? If some one can explain?

**Comment by michalvasko** [comment]
HI,
since it is in the same format as `time(1)` I was hoping ti would be obvious to everyone. Anyway, it means that your RPC took `0` minutes and `1,011` seconds.

Regards,
Michal

**Comment by ChinmayaAgarwal** [comment]
1011 seconds?..but how is that possible it takes around 1 seconds to execute. Am i miss understanding something? Does it mean the command is taking 1011 miliseconds?


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by michalvasko** [comment]
Okay, I would never think this may be a problem, but I have changed `,` to `.` because I suppose it is used more. I hope you will understand it now.

Regards,
Michal
