### ISSUE TITLE
inactive read timeout elapsed

### ISSUE THREAD

**Issue by change-my-username** [CESNET/netopeer2#584]
I am using 
netopeer2-server (netopeer2-server 1.1.7 compile time: Apr  2 2020, 15:23:19)
and 
netopeer2-cli (Netopeer2 CLI 2.0.56 Compile time: Mar 17 2020, 11:28:11)

My problem is that after connection from netopeer cli netopeer server closed down my connection (approximately after 15-20 seconds) with message:

[ERR]: LN: nc_ps_poll: failed to wait for a pollsession condition (Connection timed out).
[ERR]: LN: nc_ps_poll: failed to wait for a pollsession condition (Connection timed out).
[ERR]: LN: Session 1: inactive read timeout elapsed.
[INF]: NP: Session 1: thread 4 event session terminated.
[ERR]: LN: nc_ps_poll: failed to wait for a pollsession condition (Connection timed out).
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-end).

Could you help me please ? How can I increase idle time? I've tried to edit merge_config.sh in Netopeer2/server and set  idle-time to 100 but it's failed (connection time is still 15-20 seconds)

Btw when server closed down connection netopeer cli still thinking that it connected 

> connect --host 192.168.1.2 --login login
cmd_connect: Already connected to 192.168.1.2

And I need to send for example get-config to disconnect  

> get-config --source running
nc ERROR: Session 1: communication socket unexpectedly closed.
cli_send_recv: Failed to send the RPC.

**Comment by michalvasko** [comment]
Hi,
firstly, what *libssh* version are you using?

Regards,
Michal

**Comment by change-my-username** [comment]
Hi, Michal

dpkg -l | grep ssh

ii  libssh-4:amd64                0.8.0~20170825.94fa1e38-1ubuntu0.5  amd64        tiny C SSH library (OpenSSL flavor)
ii  libssh-dev                    0.8.0~20170825.94fa1e38-1ubuntu0.5  amd64        tiny C SSH library. Development files (OpenSSL flavor)

**Comment by michalvasko** [comment]
Hi,
okay, it is a bit old but it is probably not the problem here. Could you please try it with the latest `devel` branches of all the projects (libyang, sysrepo, libnetconf2, netopeer2)? The problem is not caused by any specific timeout value but I cannot tell you more, it is the first time I am seeing it.

Regards,
Michal

**Comment by change-my-username** [comment]
Well, I've switched branch master to devel in all of this repo, rebuild it, and now connection with netopeer is stable. Thanks Michal.

**Comment by change-my-username** [comment]
Problem is returned. Connection was stable only when I starting netopeer as local like 
'''sudo ./netopeer2-server -d'''
but when I am trying to start like
''' sudo netopeer2-server -d ''' 
It fails like in my first message ((

**Comment by michalvasko** [comment]
Hi,
so did you install the `devel` or just compiled? If it works locally then it certainly is not a problem in *netopeer2* but in the libraries you have installed. I suggest you remove them all manually and install the latest ones so that only those are always used.

Regards,
Michal
