### ISSUE TITLE
[ERR]: LN: Session 2: failed to write reply (would block).

### ISSUE THREAD

**Issue by qjwu888** [CESNET/Netopeer2#588]
Hi Michal,
netopeer2 devel-server 1.1.16
libnetconf2 devel
sysrepo devel
libyang devel

Callhome mode ,sometimes got  error log and configuration failure,hope to get your help, thanks!

[INF]: Processing "gwtt-ietf-ipsec" "change" event with ID 41 priority 0 (remaining 2 subscribers).
[DBG]: plugin: ipsec_subtree : get ipsec_subtree changes all successfully, xpath=/gwtt-ietf-ipsec:ipsec/proposal/ipsec-proposal, line=2218

[INF]: Finished processing "change" event with ID 41 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "change" with ID 41 priority 0 succeeded.
[INF]: SR: Published event "done" with ID 41 priority 0 for 2 subscribers.
[INF]: Processing "gwtt-ietf-ipsec" "done" event with ID 41 priority 0 (remaining 2 subscribers).
[INF]: SR: Published event "notif" with ID 63 priority 0 for 1 subscribers.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: SR: Finished processing "rpc" event with ID 90 priority 0 (remaining 0 subscribers).
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ipsec/proposal/ipsec-proposal[name='IpsecProposal_6577']", but it is not required.
[INF]: SR: Event "rpc" with ID 90 priority 0 succeeded.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ipsec/proposal/ipsec-proposal[name='IpsecProposal_6577']/name", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ipsec/proposal/ipsec-proposal[name='IpsecProposal_6577']/esp", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ipsec/proposal/ipsec-proposal[name='IpsecProposal_6577']/esp/authentication", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ipsec/proposal/ipsec-proposal[name='IpsecProposal_6577']/esp/encryption", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ipsec/proposal/ipsec-proposal[name='IpsecProposal_6577']/lifetime", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ipsec/proposal/ipsec-proposal[name='IpsecProposal_6577']/lifetime/seconds", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ipsec/proposal/ipsec-proposal[name='IpsecProposal_6577']/perfect-forward-secrecy", but it is not required.
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Processing "notif" "ietf-netconf-notifications" event with ID 63.
[INF]: SR: Finished processing "notif" event with ID 63 priority 0 (remaining 0 subscribers).
[INF]: NP: Session 2: thread 1 event new RPC.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: Finished processing "done" event with ID 41 priority 0 (remaining 0 subscribers).
[INF]: SR: Published event "rpc" with ID 90 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:unlock" "rpc" event with ID 90 priority 0 (remaining 1 subscribers).
[INF]: SR: Finished processing "rpc" event with ID 90 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 90 priority 0 succeeded.
[INF]: NP: Session 2: thread 1 event new RPC.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 91 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:lock" "rpc" event with ID 91 priority 0 (remaining 1 subscribers).
[INF]: SR: Finished processing "rpc" event with ID 91 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 91 priority 0 succeeded.
[INF]: NP: Session 2: thread 1 event new RPC.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 91 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 91 priority 0 (remaining 1 subscribers).
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "change" with ID 42 priority 0 for 2 subscribers.
[INF]: Processing "gwtt-ietf-ipsec" "change" event with ID 42 priority 0 (remaining 2 subscribers).
[INF]: Finished processing "change" event with ID 42 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "change" with ID 42 priority 0 succeeded.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "done" with ID 42 priority 0 for 2 subscribers.
[INF]: Processing "gwtt-ietf-ipsec" "done" event with ID 42 priority 0 (remaining 2 subscribers).
[INF]: SR: Published event "notif" with ID 64 priority 0 for 1 subscribers.
[INF]: SR: Finished processing "rpc" event with ID 91 priority 0 (remaining 0 subscribers).
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: SR: Event "rpc" with ID 91 priority 0 succeeded.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/proposal[name='Ikev2Proposal_6577']", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/proposal[name='Ikev2Proposal_6577']/name", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/proposal[name='Ikev2Proposal_6577']/encryption", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/proposal[name='Ikev2Proposal_6577']/encryption/algorithm", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/proposal[name='Ikev2Proposal_6577']/authentication", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/proposal[name='Ikev2Proposal_6577']/authentication/algorithm", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/proposal[name='Ikev2Proposal_6577']/lifetime", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/proposal[name='Ikev2Proposal_6577']/description", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/proposal[name='Ikev2Proposal_6577']/dh-group", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/ike-peer/ike-peer-entries[peer-name='Ikev2Peer_6577']", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/ike-peer/ike-peer-entries[peer-name='Ikev2Peer_6577']/peer-name", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/ike-peer/ike-peer-entries[peer-name='Ikev2Peer_6577']/ip", but it is not required.
[INF]: NP: Session 2: thread 1 event new RPC.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/ike-peer/ike-peer-entries[peer-name='Ikev2Peer_6577']/remote-id", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/ike-peer/ike-peer-entries[peer-name='Ikev2Peer_6577']/local-id", but it is not required.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/ike-peer/ike-peer-entries[peer-name='Ikev2Peer_6577']/PresharedKey", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/ike-peer/ike-peer-entries[peer-name='Ikev2Peer_6577']/traffic-selectors[ts-name='TsName_6577']", but it is not required.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/ike-peer/ike-peer-entries[peer-name='Ikev2Peer_6577']/traffic-selectors[ts-name='TsName_6577']/ts-name", but it is not required.
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/ike-peer/ike-peer-entries[peer-name='Ikev2Peer_6577']/traffic-selectors[ts-name='TsName_6577']/proposal", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/ike-peer/ike-peer-entries[peer-name='Ikev2Peer_6577']/traffic-selectors[ts-name='TsName_6577']/autostartup", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/ike-peer/ike-peer-entries[peer-name='Ikev2Peer_6577']/traffic-selectors[ts-name='TsName_6577']/local-address-low", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/ike-peer/ike-peer-entries[peer-name='Ikev2Peer_6577']/traffic-selectors[ts-name='TsName_6577']/vti-name", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/ike-peer/ike-peer-entries[peer-name='Ikev2Peer_6577']/traffic-selectors[ts-name='TsName_6577']/remote-address-high", but it is not required.
[INF]: SR: Published event "rpc" with ID 91 priority 0 for 1 subscribers.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/ike-peer/ike-peer-entries[peer-name='Ikev2Peer_6577']/traffic-selectors[ts-name='TsName_6577']/local-address-high", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/ike-peer/ike-peer-entries[peer-name='Ikev2Peer_6577']/traffic-selectors[ts-name='TsName_6577']/remote-address-low", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/ike-peer/ike-peer-entries[peer-name='Ikev2Peer_6577']/peer-enable", but it is not required.
[INF]: SR: Processing "/ietf-netconf:unlock" "rpc" event with ID 91 priority 0 (remaining 1 subscribers).
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/ike-peer/ike-peer-entries[peer-name='Ikev2Peer_6577']/remote-ip-address", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2ec:ikev2/ike-peeer-entries[peer-name='Ikev2Peer_6577']/ike-proposal-number", but it is not required.
[INF]: LY: There is no instance of "/gwtt-ietf-ipsec:ikev2/ike-peer/ike-peer-entries[peer-name='Ikev2Peer_6577']/nat-traversal", but it is not required.
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Processing "notif" "ietf-netconf-notifications" event with ID 64.
[INF]: SR: Finished processing "notif" event with ID 64 priority 0 (remaining 0 subscribers).
[INF]: SR: Finished processing "rpc" event with ID 91 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 91 priority 0 succeeded.
[ERR]: LN: Session 2: failed to write reply (would block).
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 92 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:lock" "rpc" event with ID 92 priority 0 (remaining 1 subscribers).
[INF]: SR: Finished processing "rpc" event with ID 92 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 92 priority 0 succeeded.
[INF]: NP: Ses NP: Session 2: thread 4ew RPC.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 92 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 92 priority 0 (remaining 1 subscribers).
[INF]: SR: Published event "change" with ID 17 priority 0 for 1 subscribers.
[INF]: Processing "gwtt-vxlan" "change" event with ID 17 priority 0 (remaining 1 subscribers).

**Comment by michalvasko** [comment]
Hi,
what platform are you on? A timeout used in the server seems not to be enough but I am not sure simply increasing it is the right solution.

Regards,
Michal

**Comment by qjwu888** [comment]
Hi Michal,
Thanks for your reply .
I am on MTK7621 mips platform .
What  timeout in the server, could you tell me ,let me try .thanks!

**Comment by michalvasko** [comment]
Hi,
you can try that, [this](https://github.com/CESNET/Netopeer2/blob/devel-server/server/main.c#L933) timeout. Just change the `10` to `100`, for example. Based on the output it would seem that both an RPC reply and a notification were being sent on a session at the same time, which is handled by a lock. But it seems 10 ms was not enough for the notification to be sent and release the lock. And on a slower platform that is possible, I guess.

Regards,
Michal

**Comment by qjwu888** [comment]
Hi Michal,
Timeout from 10 to 50 ,now look like ok.
I need long time to test,and reply to you, 
Thanks!
