### ISSUE TITLE
Locking a mutex failed (sr_connect: Operation timed out).

### ISSUE THREAD

**Issue by qjwu888** [CESNET/netopeer2#589]
Hi Michal,
netopeer2 devel-server 1.1.20
libnetconf2 devel
 After testing ,I found the issue, my steps as following.
1. Netopeer2-server connected to ODL in callhome mode .
   callhome setting remote IP is 192.168.10.123.(ODL ip).
2. Change the remote IP to 192.168.10.124.
  sysrepocfg --edit=/var/callhome.xml -d startup -f xml -m ietf-netconf-server -v2
  sysrepocfg -C startup -m ietf-netconf-server -v2 
3. The device still can set by ODL. Capture in ODL , Found the device still send keep-alive to it (192.168.10.123). So the device can't connect to 192.168.10.124. No package send to it.

Hope to get your help,thanks!

[callhome.txt](https://github.com/CESNET/Netopeer2/files/4469020/callhome.txt)

**Comment by qjwu888** [comment]
Hi Michal,
Is there this issue  in your environment?

**Comment by qjwu888** [comment]
Hi Michal,
For fix this issue,
My steps changed.
1. First ,Netopeer2-server connected to ODL in callhome mode .
Callhome setting with remote IP  192.168.10.123.(ODL ip), 
Setting by ODL ,work fine.

2. Change the remote IP to 192.168.10.124.
sysrepocfg --edit=/var/callhome.xml -d startup -f xml -m ietf-netconf-server -v2
sysrepocfg -C startup -m ietf-netconf-server -v2
/etc/init.d/netopeer2-server restart

3. The device can connect new IP soon, But after 1, 2 steps, setting several times will find new bugs.
LOG as following:
Tue Dec 17 11:04:33 2019 daemon.err netopeer2-server[7986]: Locking a mutex failed (sr_connect: Operation timed out).
Tue Dec 17 11:04:33 2019 daemon.err netopeer2-server[7986]: Connecting to sysrepo failed (Timeout expired).
Tue Dec 17 11:04:33 2019 daemon.err netopeer2-server[7986]: Server init failed.

**Comment by michalvasko** [comment]
Hi,
as for your original issue, this is meant to be a feature. It is not written anywhere (and I think it is not really expected) that you should forcefully terminate an established Call Home session if its configuration changed. It should only be applied on the next reconnect. I think you should change other connection parameters (persistent vs. periodic) to achieve what you want.

As for your other issue, I have no idea what it is exactly that you are doing so I cannot help you. Please try to provide more details and a way for me to reproduce it (best with *netopeer2-cli* client but it should not really matter).

Regards,
Michal

**Comment by qjwu888** [comment]
Hi Michal,
 **For first issue:
If callhome setting from persistent to  periodic,I don’t know if the controller（ODL)） can always set the device.**
     connection-type
        persistent-->periodic
        connection-type


**For the second issue：
my steps as following:**
**1. Netopeer2-server connected to ODL in callhome mode .**
  Callhome setting with remote IP 192.168.10.123.(ODL ip),
 This time work fine .

**2. Creat var/callhome.xml  ,just change remote IP to 192.168.10.124.**
The  following three lines CMD is  in a scripts.
#!/bin/sh
sysrepocfg --edit=/var/callhome.xml -d startup -f xml -m ietf-netconf-server -v2
sysrepocfg -C startup -m ietf-netconf-server -v2
/etc/init.d/netopeer2-server restart

**(because my os is openwrt, /etc/init.d/netopeer2-server restart = /etc/init.d/netopeer2-server stop 
  /etc/init.d/netopeer2-server start)**

**3. Creat var/callhome.xml  ,just change remote IP to 192.168.10.123.**
The  following three lines CMD is  in a scripts.
#!/bin/sh
sysrepocfg --edit=/var/callhome.xml -d startup -f xml -m ietf-netconf-server -v2
sysrepocfg -C startup -m ietf-netconf-server -v2
/etc/init.d/netopeer2-server restart

**4. Repeat steps 2 and 3，Will found the following log.**
Tue Dec 17 11:04:33 2019 daemon.err netopeer2-server[7986]: Locking a mutex failed (sr_connect: Operation timed out).
Tue Dec 17 11:04:33 2019 daemon.err netopeer2-server[7986]: Connecting to sysrepo failed (Timeout expired).
Tue Dec 17 11:04:33 2019 daemon.err netopeer2-server[7986]: Server init failed.

**Comment by michalvasko** [comment]
Hi,
okay, I have not managed to reproduce this but I did discover a possibly serious issue of accessing freed memory when *netopeer2* is being terminated. So please pull latest *libnetconf2* `devel` for a fix. Other than that I am not able to reproduce this or debug it in any way.

But how exactly is the server being restarted? Is it properly terminated by being sent `SIGTERM` or forcefully by `SIGKILL`? Also, you can try using `-w` parameter for the second `sysrepocfg` call to make it wait for all the callbacks so that the server is not being terminated before that (although it should not matter to my knowledge).

Regards,
Michal

**Comment by qjwu888** [comment]
Hi Michal,
Thanks for your reply, I will implement according to your suggestion.
Is it properly terminated by being sent SIGTERM or forcefully by SIGKILL? 
It's  SIGTERM .

In some case, We meet the following log, Could it help you reproduce?
1. 
[11:10:19]Thu Apr 16 10:29:34 2020 kern.info kernel: [  346.512215] do_page_fault(): sending SIGSEGV to netopeer2-serve for invalid read access from 77f04000
[11:10:19]Thu Apr 16 10:29:34 2020 kern.info kernel: [  346.521495] epc = 77ece3e4 in libc.so[77e5c000+95000]
[11:10:19]Thu Apr 16 10:29:34 2020 kern.info kernel: [  346.526656] ra  = 77e852d0 in libc.so[77e5c000+95000]


[11:10:19]Thu Apr 16 10:46:44 2020 daemon.err netopeer2-server[3926]: Locking a mutex failed (sr_connect: Operation timed out).
[11:10:19]Thu Apr 16 10:46:44 2020 daemon.err netopeer2-server[3926]: Connecting to sysrepo failed (Timeout expired).
[11:10:19]Thu Apr 16 10:46:44 2020 daemon.err netopeer2-server[3926]: Server init failed.
[11:10:19]Thu Apr 16 10:46:44 2020 daemon.info procd: Instance netopeer2-server::instance1 s in a crash loop 7 crashes, 15 seconds since last crash
[11:10:19]Thu Apr 16 10:51:42 2020 daemon.info procd: Instance sysrepo::instance1 s in a crash loop 6 crashes, 16 seconds since last crash
[11:10:19]Thu Apr 16 10:52:26 2020 daemon.info procd: Instance sysrepo::instance1 s in a crash loop 7 crashes, 16 seconds since last crash
[11:10:19]Thu Apr 16 10:56:03 2020 daemon.err netopeer2-server[4139]: Locking a mutex failed (sr_connect: Operation timed out).
[11:10:19]Thu Apr 16 10:56:03 2020 daemon.err netopeer2-server[4139]: Connecting to sysrepo failed (Timeout expired).
[11:10:19]Thu Apr 16 10:56:03 2020 daemon.err netopeer2-server[4139]: Server init failed.
[11:10:20]Thu Apr 16 10:56:03 2020 daemon.info procd: Instance netopeer2-server::instance1 s in a crash loop 8 crashes, 16 seconds since last crash

2、root@gpn-000FE9001001:~#sysrepo-plugind -d -v 4 &

root@gpn-000FE9001001:~# [INF]: Scheduled changes not applied because of other existing connections.
[ERR]: Locking a mutex failed (sr_connect: Operation timed out).
sysrepo-plugind error: Failed to connect (Timeout expired)
[1]+  Done(1)                    sysrepo-plugind -d -v 4

3、root@gpn-000FE9001001:~#/etc/sysrepo# ls

root@gpn-000FE9001001:/etc/sysrepo# ls
data          sr_evpipe2    sr_evpipe4    sr_evpipe6    sr_main_lock
sr_evpipe1    sr_evpipe3    sr_evpipe5    sr_evpipe7    yang
root@gpn-000FE9001001:/etc/sysrepo#

**Comment by michalvasko** [comment]
Hi,
oh, so the server crashes and the timeout is just the result of that. In that case it would be great if you could run *netopeer2* with `gdb` or even `valgrind` when it crashes, if possible. That would definitely provide some information about what is happening and may even be enough for me to fix it. Also, you are using *sysrepo* from current `devel` branch, right? You have mentioned only *netopeer2* and *libnetconf2*.

Regards,
Michal

**Comment by qjwu888** [comment]
Hi Michal,
1. you are using sysrepo from current devel branch, right? 
No. i am using  2020.03.18 sysrepo devel branch.
2. I will update all version to the last,and try to give you more info,

**Comment by vladique00** [comment]
> Offtop:
> 
> qjwu888,
> Could you contact me?
> v.semikolennykh@gmail.com

**Comment by qjwu888** [comment]
Hi  What  can  I  do  for  you?Qjwu-------- 原始邮件 --------发件人： vladique00 <notifications@github.com>日期： 2020年4月28日周二 下午3:55收件人： CESNET/Netopeer2 <Netopeer2@noreply.github.com>抄送： qjwu888 <wuqingjun888@126.com>, Author <author@noreply.github.com>主    题： Re: [CESNET/Netopeer2] Locking a mutex failed (sr_connect: Operation timed out). (#589)

Offtop:
qjwu888,
Could you contact me?
v.semikolennykh@gmail.com
