### ISSUE TITLE
netopeer2-cli getting error in ietf-datastores

### ISSUE THREAD

**Issue by meghna-doshi** [CESNET/Netopeer2#590]
Hi,
Following versions used:
sysrepo : 1.4.38 (devel branch)
Netopeer2 : 1.1.21 (devel-server branch)
libyang : 1.0.157 (devel branch)

1. running netopeer2-server with options -d -v 2
2. At netopeer2-cli, following error seen whenever connect done with server:

```
> connect --ssh --host 10.206.1.21 --port 830 --login root
The authenticity of the host '10.206.1.21' cannot be established.
ssh-rsa key fingerprint is ae:8b:03:0b:b3:f5:2d:97:cf:25:9f:fe:0a:9f:ec:00:9c:1b:a3:9a.
Are you sure you want to continue connecting (yes/no)? yes
Interactive SSH Authentication
Type your password:
Password: 
ly ERROR: Identity found, but in a non-implemented module "ietf-datastores".
ly ERROR: Failed to resolve identityref "ietf-datastores:running". (/ietf-yang-library:yang-library/datastore[name='ds:running']/name)
nc ERROR: Failed to parse <get> reply.
```
Can you please help what is wrong here, this error started coming after we upgraded sysrepo to 1.4.38 version, i think upto sysrepo 1.4.37 it was fine.

**Comment by michalvasko** [comment]
Hi,
you did not mention *libnetconf2* so I will assume that is where the problem is, please update even that one to the latest version.

Regards,
Michal

**Comment by meghna-doshi** [comment]
Hi Michal,
Oh ok, will try. Currently libnetconf2 in on version 1.1.7 of master branch.
I will use the latest from devel branch and check.
Thanks.

Regards,
Meghna

**Comment by meghna-doshi** [comment]
Hi Michal,
Thanks, it worked after upgrading libnetconf2 with latest devel version.

Regards,
Meghna
