### ISSUE TITLE
Call Home function issue

### ISSUE THREAD

**Issue by Akhil-123456789** [CESNET/netopeer2#592]
Hi,
In netopeer2-server i have enable the call Home function and set the client IP and default port is 4334.
```
SERVER="<netconf-server xmlns=\"urn:ietf:params:xml:ns:yang:ietf-netconf-server\">
    <call-home>
        <netconf-client>
            <name>default-client</name>
            <endpoints>
                <endpoint>
                    <name>default-ssh</name>
                    <ssh>
                        <tcp-client-parameters>
                            <remote-address>10.123.156.148</remote-address>
                            <keepalives>
                                <idle-time>1</idle-time>
                                <max-probes>10</max-probes>
                                <probe-interval>5</probe-interval>
                            </keepalives>
                        </tcp-client-parameters>
                        <ssh-server-parameters>
                            <server-identity>
                                <host-key>
                                    <name>default-key</name>
                                    <public-key>
                                        <keystore-reference>genkey</keystore-reference>
                                    </public-key>
                                </host-key>
                            </server-identity>
                            <client-authentication>
                                <supported-authentication-methods>
                                    <publickey/>
                                    <passsword/>
                                    <other>interactive</other>
                                </supported-authentication-methods>
                                <users/>
                            </client-authentication>
                        </ssh-server-parameters>
                    </ssh>
                </endpoint>
            </endpoints>
            <connection-type>
                <persistent/>
            </connection-type>
        </netconf-client>
    </call-home>
</netconf-server>"
```
After starting the netopeer2-server, it try to connect the Client IP : 4334 .

In client setup :: I need to fill this filled ::  name, IP ,Port ,userid ,password.
Here client and server are in different IP and also login credentials are different.

Now i need to connect the client to server.
In client i have give name :: Test ,IP :: client IP , port :: 4334 , userid and password ::  Client setup

when i disable call home and enable SSH only i am able to connect successfully the client with server on port 830.

when i enable call home and disable SSH ,i am try to connect now but the connection is getting refused on port 4334.

1)Client port is different that 4334.while making connection i need to set client port on server instead of 4334? 

2)For call home function i need to set any authentication key of client or credentials on server for connecting or validation ?

**Comment by michalvasko** [comment]
Hi,
I am somewhat confused as to what exactly is the issue and what is your setup. I do not know what client are you using but you must set it up to **listen** instead of **connect** when using Call Home so that the server can connect to it. And whatever port the client will listen on, that is the port that needs to be set in the server Call Home configuration. As for authentication, that will occur in the standard way meaning you do not have to do any additional steps for Call Home authentication.

Regards,
Michal

**Comment by Akhil-123456789** [comment]
Hi,
Is there any software that it can covert the yang model into the xml struture .
Can you please provide the link.

**Comment by michalvasko** [comment]
Hi,
[pyang](https://github.com/mbj4668/pyang) should be able to do this, the feature
```
Generate a skeleton XML instance document from the data model.
```

Regards,
Michal

**Comment by Akhil-123456789** [comment]
Hi,
Once we perform some edit-config operation and set some parameter values into the yang model from netopeer-cli. where this parameter will be store in the server in which path ? 
After connecting the server and client through hello message capability will get exchange.
we need to keep the yang model of both in server and client ?
How client will know that this yang model is have which attributes inside it like different container , leaf , leaf list etc ?

**Comment by michalvasko** [comment]
Hi,
I do not really understand the first question, are you asking where the server stores its data? If so, then in binary files either as shared memory files (`/dev/shm`) or standard files (`repository/data`).

As for client-side YANG modules, by default they are retrieved from the server so you do not have to worry about that at all. If that is not supported/fails, they are loaded locally from specific directories as configured.

Regards,
Michal
