### ISSUE TITLE
How to subscribe for notification in netopeer_cli?

### ISSUE THREAD

**Issue by soso8282** [CESNET/netopeer2#595]
Hi Michal,
    I have passed the test of the sample program provided by sysrepo：notif_send_example and notif_subscribe_example.Both applications directly access sysrepo for subscribe testing.
    If I want to pass the notification test through the ‘subscribe’ command in netopeer2_cli, how should I set the parameters of subscribe?
    >subscribe ?
      subscribe [--help] [--filter-subtree[=<file>] | --filter-xpath <XPath>] [--begin <time>] [--end 
                      <time>] [--stream <stream>] [--out <file>] [--rpc-timeout <seconds>]
    I don't know how to fill in these parameters.
    
    Regards
    soso

**Comment by michalvasko** [comment]
Hi,
if you do not understand the parameters, you should look at the [definition](https://github.com/CESNET/Netopeer2/blob/master/modules/notifications%402008-07-14.yang) of the RPC. However, you can see they are all optional so you can simply use `subscribe`. That is what you want in most cases anyway.

Regards,
Michal

**Comment by soso8282** [comment]
Hi Michal,
    I tried to use the ‘subscribe’ command directly.The cli returned is：
”
    > subscribe 
        OK
    > 
        nc ERROR: Session 1: poll error (Success).
”
     I don't know what this part of log means.

**Comment by michalvasko** [comment]
Hi,
I don't have any idea either so I would guess you are using some old/incompatible versions of *netopeer2-cli* or some of the libraries. Try updating everything to either the latest release or current `devel` and make sure all the executables are using them. Then try this again. Also, to be safe, what version are you currently using (of at least *netopeer2-cli*, *libnetconf2*, and *sysrepo*).

Regards,
Michal

**Comment by soso8282** [comment]
Hi Michal,
    The version of the lib I use is as follows:
        netopeer2-CLI 2.0.56(netopeer-cli)
	netopeer2-server 1.1.7(netopeer-server)
	libnetconf2, libyang and sysrepo ，I don't know how to check their version num.
        Can you suggest a more stable version for me? I will use this version to try it out.
        Thanks.
  Regards
  soso

**Comment by michalvasko** [comment]
Hi,
so you are using the latest `master`, which should be fine. However, you not knowing how to check library versions tells me that it is quite possible you are using some older versions without knowing it. Because like I said, this is the first time I am seeing the error and it is a weird one, too. So, you can check your libraries on the system by using, for example, `ldconfig -p | grep sysrepo` and so on for each library. Please make sure you have only one library version installed (it will usually have 2 entries in the output because of symbolic links).

Regards,
Michal

**Comment by esend7881** [comment]
> Hi,
> if you do not understand the parameters, you should look at the [definition](https://github.com/CESNET/Netopeer2/blob/master/modules/notifications%402008-07-14.yang) of the RPC. However, you can see they are all optional so you can simply use `subscribe`. That is what you want in most cases anyway.
> 
> Regards,
> Michal

I'm having issues seeing usage examples for the various `subscribe` arguments. I looked at the RPC but its of no help. Basically, I want to subscribe to only see notifications about a certain leaf in my yang. When I simple type in `subscribe` I end up getting any/all changes to any leaf. 

I have tried:

```
> subscribe --filter-subtree=urn:com:tug:rmbn
cmd_subscribe: Unable to open the local datastore file "urn:com:tug:rmbn" (No such file or directory).
```
And
```
> subscribe --stream urn:com:tug:rmbn
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Item not found
```
And this did not return an error, however it also did not spit out any data when I did change the contents in my leaf:
```
> subscribe --stream rmbn
OK
```

Some usage examples would be very helpful
