### ISSUE TITLE
Module "ietf-inet-types" parsing failed

### ISSUE THREAD

**Issue by wjn111** [CESNET/netopeer2#596]
Hi,
When I run netopeer2-cli, I am getting the following errors : 
ly ERROR: Regular expression "(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(%[\p{N}\p{L}]+)?" is not valid ("p{N}\p{L}]+)?)$": support for \P, \p, and \X has not been compiled).
ly ERROR: Module "ietf-inet-types" parsing failed. 
load_config: Failed to create context. 
load_config: Unable to load configuration due to the previous error.
Can you please help me resolving this issue.

**Comment by michalvasko** [comment]
Hi,
please refer to *libyang* [FAQ](https://github.com/CESNET/libyang/blob/devel/FAQ.md).

Regards,
Michal

**Comment by wjn111** [comment]
Hi, Michal
     Thank you very much, I solved the problem above. But I have a new problem. I hope I can get your help. 
     I can not connect netopeer2-server by using netopeer2-cli. I installed netopeer2-server on openwrt and installed netopeer2-cli on my computer. 
 
1.client log:
# netopeer2-cli 
> connect --host 192.168.1.33 --port 830 --login localhost
nc ERROR: Remote host key changed, the connection will be terminated!
nc ERROR: Checking the host key failed.
cmd_connect: Connecting to the 192.168.1.33:830 as user "localhost" failed.
> knownhosts
ID Hostname Algorithm Key

0: (hashed hostname) ecdsa-sha2-nistp256: (key 0)
1: (hashed hostname) ecdsa-sha2-nistp256: (key 1)
2: (hashed hostname) ssh-rsa: (key 2)
3: (hashed hostname) ssh-rsa: (key 2)
> 

2.server log:
[INF]: Accepted a connection on :::830.
[2020/04/21 12:40:27.588470, 1] ssh_server_connection_callback:  SSH client banner: SSH-2.0-libssh_0.8.90
[2020/04/21 12:40:27.589933, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-libssh_0.8.90
[2020/04/21 12:40:27.650930, 2] ssh_server_curve25519_init:  SSH_MSG_KEX_ECDH_REPLY sent
[2020/04/21 12:40:27.651752, 2] ssh_server_curve25519_init:  SSH_MSG_NEWKEYS sent
[2020/04/21 12:40:27.658852, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
[2020/04/21 12:40:27.659401, 1] ssh_packet_disconnect_callback:  Received SSH_MSG_DISCONNECT: 11:Bye Bye
[ERR]: Communication SSH socket unexpectedly closed.

Can you please help me resolving this issue.

**Comment by michalvasko** [comment]
Hi,
this is a general SSH problem (or rather a feature) of a changed host key. It occurs fairly often with *netopeer2* because it generates a new key every time it is installed. You can learn more by yourself. But to fix it, there is basic support of `knownhost` in *netopeer2-cli* as you have discovered. You probably want to delete the old key (`--del x`) so a new one can be stored. It will likely be the 2nd and 3rd key because *netopeer2* generates RSA keys.

Regards,
Michal
