### ISSUE TITLE
DOS by not sending hello

### ISSUE THREAD

**Issue by immibis** [CESNET/Netopeer2#6]
Open an SSH session, observe server hello:

```
root@t460s:~/ietf962/libnetconf2# ssh -s -p6001 localhost netconf
Interactive SSH Authentication
Type your password:
Password: tmp
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><capabilities><capability>urn:ietf:params:netconf:base:1.0</capability><capability>urn:ietf:params:netconf:base:1.1</capability><capability>urn:ietf:params:netconf:capability:writable-running:1.0</capability><capability>urn:ietf:params:netconf:capability:candidate:1.0</capability><capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</capability><capability>urn:ietf:params:netconf:capability:validate:1.1</capability><capability>urn:ietf:params:netconf:capability:startup:1.0</capability><capability>urn:ietf:params:netconf:capability:xpath:1.0</capability><capability>urn:ietf:params:netconf:capability:with-defaults:1.0?basic-mode=explicit&amp;also-supported=report-all,report-all-tagged,trim,explicit</capability><capability>urn:ietf:params:xml:ns:yang:1?module=yang&amp;revision=2016-02-11</capability><capability>urn:ietf:params:xml:ns:yang:ietf-inet-types?module=ietf-inet-types&amp;revision=2013-07-15</capability><capability>urn:ietf:params:xml:ns:yang:ietf-yang-types?module=ietf-yang-types&amp;revision=2013-07-15</capability><capability>urn:ietf:params:xml:ns:yang:ietf-yang-library?module=ietf-yang-library&amp;revision=2016-02-01</capability><capability>http://example.net/turing-machine?module=turing-machine&amp;revision=2013-12-27</capability><capability>urn:ietf:params:xml:ns:yang:ietf-interfaces?module=ietf-interfaces&amp;revision=2014-05-08</capability><capability>urn:ietf:params:xml:ns:yang:iana-if-type?module=iana-if-type&amp;revision=2014-05-08</capability><capability>urn:ietf:params:xml:ns:yang:ietf-ip?module=ietf-ip&amp;revision=2014-06-16</capability><capability>urn:ietf:params:xml:ns:yang:ietf-netconf-acm?module=ietf-netconf-acm&amp;revision=2012-02-22</capability><capability>urn:ietf:params:xml:ns:yang:iana-crypt-hash?module=iana-crypt-hash&amp;revision=2014-04-04</capability><capability>urn:ietf:params:xml:ns:yang:ietf-system?module=ietf-system&amp;revision=2014-08-06</capability><capability>urn:ietf:params:xml:ns:netconf:base:1.0?module=ietf-netconf&amp;revision=2011-06-01&amp;features=writable-running,candidate,rollback-on-error,validate,startup,xpath</capability><capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring?module=ietf-netconf-monitoring&amp;revision=2010-10-04</capability><capability>urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults?module=ietf-netconf-with-defaults&amp;revision=2011-06-01</capability></capabilities><session-id>1</session-id></hello>]]>]]>
```

Then open another one, in another terminal, and observe this one hangs before authentication:

<pre>
root@t460s:~/ietf962/libnetconf2# ssh -s -p6001 localhost netconf
</pre>

The second session will proceed to authentication once the server receives to hello from the first session.

**Comment by michalvasko** [comment]
Hi,
this is quite expected. netopeer2-server (currently, it may change in the future) uses only 2 threads, one for accepting sessions, another for handling requests on existing ones. Everything transport-related in handled in the first thread including receiving/sending the hello message. libnetconf2 enables to set hello message timeout and netopeer2-server will allow it too, but not just yet.

Regards,
Michal

**Comment by rastislavszabo** [comment]
Hi,
I don't think that the hello timeout is a correct way of solving of this issue. Let's say that you would configure it for one second. The attacker just needs to open a new session once per second to effectively deny the access for any other users.

**Comment by michalvasko** [comment]
Hi,
there is no better solution using 2 threads. We will likely change the architecture in the future, but for now it is unimportant, the server must first support all the NETCONF features.

Regards,
Michal

**Comment by rkrejci** [comment]
I would like to keep this and #7 issues open and discuss here the best (or at least a better than the current) solution to this - any ideas?

I just want to note, that the described attack can be performed only by already authenticated users, so the risk of the attack is quite low, IMHO.

Michal, what is the behavior if the client hangs with/before authentication?

**Comment by michalvasko** [comment]
In all cases authentication timeout is used (even for starting netconf subsystem). As I see it, we will likely go for an architecture with 1 main server thread and then a separate thread for every session (you can already limit maximum number of sessions in libnetconf2), just like in the old netopeer.

Another solution would perhaps be to keep a pool of sessions in various states (just connected, requesting authentication, authenticated and requesting subsystem, sent an RPC, ...) and one/specific number of threads will iterate over all the sessions and perform one non-blocking action if there is some pending on the session. More challenging implementation than the former architecture, so the question is whether it would be worth the effort, but it would prevent any DOS attack as well. It would likely scale very nicely, too (if the number of threads could be changed, maybe even during runtime).

Regards,
Michal

**Comment by rastislavszabo** [comment]
I would vote for something similar to the latter solution, one thread per session does not scale very well.  Of course that this does not need to have any immediate priority, but eventually it should be solved somehow.

**Comment by michalvasko** [comment]
Hi,
the latter architecture was implemented a few months ago.

Regards,
Michal
