### ISSUE TITLE
netopeer2-server crash with callhome mode

### ISSUE THREAD

**Issue by qjwu888** [CESNET/Netopeer2#601]
Hi Michal,
netopeer2 devel-server 1.1.22
sysrepo devel
libnetconf2 devel
libyang devel
Netopeer2-server crash with callhome mode.
Hope to get your help, thanks!
My steps:
1.	Sysrepo-plugind 、netopeer2-server enabled with callhome mode.
![image](https://user-images.githubusercontent.com/50397234/79963680-4552e500-84bc-11ea-850a-a6a6d562c645.png)
2.	ODL show 192.168.10.80 connected. This time work fine.
![image](https://user-images.githubusercontent.com/50397234/79963806-6b788500-84bc-11ea-8d1a-0f6a907111d7.png)
3.Kill – 9 netopeer2-server , found netopeer2-server was killed. Wait a moment, another netopeer2-server will enable auto. But crash as following.
![image](https://user-images.githubusercontent.com/50397234/79963861-80edaf00-84bc-11ea-9517-23c96afd688f.png)
4.Error log as following. 
![image](https://user-images.githubusercontent.com/50397234/79963925-94991580-84bc-11ea-9f9c-8f168fcc227c.png)

Steps as attach file.
[netopeer2_crash.docx](https://github.com/CESNET/Netopeer2/files/4514134/netopeer2_crash.docx)

**Comment by qjwu888** [comment]
Hi Michal,

**Kill – 9 netopeer2-server , found netopeer2-server was killed. 
Wait a moment, another netopeer2-server will enable auto. 
Crash log following.**

daemon.info netopeer2-server[2847]: Searching for "gwtt-vti" in /etc/sysrepo/yang.
daemon.info netopeer2-server[2847]: Loading schema from "/etc/sysrepo/yang/gwtt-vti@2019-09-20.yang" file.
daemon.info netopeer2-server[2847]: Module "gwtt-vti@2019-09-20" successfully parsed as implemented.
daemon.info netopeer2-server[2847]: Searching for "gwtt-bridge" in /etc/sysrepo/yang.
daemon.info netopeer2-server[2847]: Loading schema from "/etc/sysrepo/yang/gwtt-bridge@2019-09-20.yang" file.
daemon.info netopeer2-server[2847]: Searching for "ietf-ip" in /etc/sysrepo/yang.
daemon.info netopeer2-server[2847]: Loading schema from "/etc/sysrepo/yang/ietf-ip@2014-06-16.yang" file.
daemon.info netopeer2-server[2847]: Module "gwtt-bridge@2019-09-20" successfully parsed as implemented.
daemon.info netopeer2-server[2847]: Searching for "gwtt-vlan" in /etc/sysrepo/yang.
daemon.info netopeer2-server[2847]: Loading schema from "/etc/sysrepo/yang/gwtt-vlan@2019-12-20.yang" file.
daemon.info netopeer2-server[2847]: Module "gwtt-vlan@2019-12-20" successfully parsed as implemented.
daemon.info netopeer2-server[2847]: Searching for "gwtt-dhcpd" in /etc/sysrepo/yang.
daemon.info netopeer2-server[2847]: Loading schema from "/etc/sysrepo/yang/gwtt-dhcpd@2019-08-09.yang" file.
daemon.info netopeer2-server[2847]: Module "gwtt-dhcpd@2019-08-09" successfully parsed as implemented.
daemon.warn netopeer2-server[2847]: Cleaning up after a non-existent sysrepo client with PID 2702.
daemon.info netopeer2-server[2847]: Ext SHM was defragmented and 5364 B were saved.
daemon.info netopeer2-server[2847]: Session 6 (user "root") created.
daemon.info netopeer2-server[2847]: Resolving unresolved data nodes and their constraints...
daemon.info netopeer2-server[2847]: There is no leafref "/ietf-keystore:keystore/ietf-keystore:asymmetric-keys/ietf-keystore:asymmetric-key/ietf-keystore:name" with the value "genkey", but it is not required.
daemon.info netopeer2-server[2847]: There is no leafref "/ietf-keystore:keystore/ietf-keystore:asymmetric-keys/ietf-keystore:asymmetric-key/ietf-keystore:name" with the value "genkey", but it is not required.
daemon.info netopeer2-server[2847]: All data nodes and constraints resolved.
daemon.info netopeer2-server[2847]: Triggering "ietf-netconf-server" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Triggering "ietf-netconf-server" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Triggering "ietf-netconf-server" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Listening on 0.0.0.0:830 for SSH connections.
daemon.info netopeer2-server[2847]: Triggering "ietf-netconf-server" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Triggering "ietf-netconf-server" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Triggering "ietf-netconf-server" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Triggering "ietf-netconf-server" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Triggering "ietf-netconf-server" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Triggering "ietf-netconf-server" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Triggering "ietf-netconf-server" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Triggering "ietf-netconf-server" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Triggering "ietf-netconf-server" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Triggering "ietf-netconf-server" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Triggering "ietf-netconf-server" "done" event on enabled datbled data.
daemon.info netopeer2-server[2847]: Triggering "ietf-netconf-server" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Ext SHM was defragmented and 4372 B were saved.
daemon.info netopeer2-server[2847]: Triggering "ietf-netconf-server" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Triggering "ietf-netconf-server" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Triggering "ietf-netconf-server" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Triggering "ietf-netconf-server" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Triggering "ietf-netconf-server" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Triggering "ietf-netconf-server" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Triggering "ietf-netconf-server" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Triggering "ietf-keystore" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Triggering "ietf-truststore" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Triggering "ietf-netconf-acm" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Triggering "ietf-netconf-acm" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Triggering "ietf-netconf-acm" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Triggering "ietf-netconf-acm" "done" event on enabled data.
daemon.info netopeer2-server[2847]: Call Home client "default-client" connecting...
daemon.info netopeer2-server[2847]: Trying to connect via IPv4 to 192.168.10.123:6666.
daemon.info netopeer2-server[2847]: Successfully connected to 192.168.10.123:6666 over IPv4.
daemon.info netopeer2-server[2847]: Session 7 (user "root") created.
daemon.info netopeer2-server[2847]: Received an SSH message "request-service" of subtype "ssh-userauth".
daemon.info netopeer2-server[2847]: Received an SSH message "request-auth" of subtype "none".
daemon.info netopeer2-server[2847]: Received an SSH message "request-auth" of subtype "interactive".
daemon.info netopeer2-server[2847]: Received an SSH message "request-auth" of subtype "interactive".
daemon.info netopeer2-server[2847]: Received an SSH message "request-auth" of subtype "interactive".
daemon.info netopeer2-server[2847]: Received an SSH message "request-auth" of subtype "interactive".
daemon.info netopeer2-server[2847]: Received an SSH message "request-auth" of subtype "password".
daemon.info netopeer2-server[2847]: User "root" authenticated.
daemon.info netopeer2-server[2847]: Received an SSH message "request-channel-open" of subtype "session".
daemon.info netopeer2-server[2847]: Received an SSH message "request-channel" of subtype "subsystem".
daemon.info netopeer2-server[2847]: Call Home client "default-client" session 1 established.
daemon.info netopeer2-server[2847]: Session 8 (user "root") created.
daemon.info netopeer2-server[2847]: There are no subscribers for "ietf-netconf-notifications" notifications.
daemon.info netopeer2-server[2847]: Generated new event (netconf-session-start).
daemon.info netopeer2-server[2847]: Resolving unresolved data nodes and their constraints...
daemon.info netopeer2-server[2847]: All data nodes and constraints resolved.
daemon.info netopeer2-server[2847]: Resolving unresolved data nodes and their constraints...
daemon.info netopeer2-server[2847]: All data nodes and constraints resolved.
daemon.info netopeer2-server[2847]: Published event "rpc" with ID 1 priority 0 for 1 subscribers.
daemon.info netopeer2-server[2847]: Processing "/ietf-netconf:get" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
daemon.info netopeer2-server[2847]: Published event "operational" with ID 1.
daemon.info netopeer2-server[2847]: Processing "operational" "ietf-netconf-monitoring" event with ID 1.
daemon.info netopeer2-server[2847]: Finished processing "operational" event with ID 1.
daemon.info netopeer2-server[2847]: Event "operational" with ID 1 succeeded.
daemon.info netopeer2-server[2847]: Finished processing "rpc" event with ID 1 priority 0 (remaining 0 subscribers).
daemon.info netopeer2-server[2847]: Event "rpc" with ID 1 priority 0 succeeded.
daemon.info netopeer2-server[2847]: Resolving unresolved data nodes and their constraints...
daemon.info netopeer2-server[2847]: All data nodes and constraints resolved.
daemon.info netopeer2-server[2847]: Session 1: thread 4 event new RPC.
daemon.info netopeer2-server[2847]: Resolving unresolved data nodes and their constraints...
daemon.info netopeer2-server[2847]: All data nodes and constraints resolved.
daemon.info netopeer2-server[2847]: Resolving unresolved data nodes and their constraints...
daemon.info netopeer2-server[2847]: All data nodes and constraints resolved.
daemon.info netopeer2-server[2847]: Published event "rpc" with ID 2 priority 0 for 1 subscribers.
daemon.info netopeer2-server[2847]: Processing "/ietf-netconf:get" "rpc" event with ID 2 priority 0 (remaining 1 subscribers).
daemon.info netopeer2-server[2847]: Published event "operational" with ID 1.
daemon.info netopeer2-server[2847]: Processing "operational" "nc-notifications" event with ID 1.
daemon.info netopeer2-server[2847]: Resolving unresolved data nodes and their constraints...
daemon.info netopeer2-server[2847]: All data nodes and constraints resolved.
daemon.info netopeer2-server[2847]: Finished processing "operational" event with ID 1.
daemon.info netopeer2-server[2847]: Event "operational" with ID 1 succeeded.
daemon.info netopeer2-server[2847]: Finished processing "rpc" event with ID 2 priority 0 (remaining 0 subscribers).
daemon.info netopeer2-server[2847]: Event "rpc" with ID 2 priority 0 succeeded.
daemon.info netopeer2-server[2847]: Resolving unresolved data nodes and their constraints...
daemon.info netopeer2-server[2847]: All data nodes and constraints resolved.
daemon.info netopeer2-server[2847]: Session 1: thread 0 event new RPC.
daemon.info netopeer2-server[2847]: Resolving unresolved data nodes and their constraints...
daemon.info netopeer2-server[2847]: All data nodes and constraints resolved.
daemon.info netopeer2-server[2847]: Resolving unresolved data nodes and their constraints...
daemon.info netopeer2-server[2847]: All data nodes and constraints resolved.
daemon.info netopeer2-server[2847]: Published event "rpc" with ID 2 priority 0 for 2 subscribers.
daemon.err netopeer2-server[2847]: Opening "/etc/sysrepo/sr_evpipe7" for writing failed (No such file or directory).
daemon.err rtty: (uwsc.c:603) tcp_connect failed: Try again
kern.info kernel: [  157.346892] do_page_fault(): sending SIGSEGV to netopeer2-serve for invalid read access from 00000000
kern.info kernel: [  157.356144] epc = 77d1b5e9 in libsysrepo.so.5.4.0[77cf9000+3d000]
kern.info kernel: [  157.362423] ra  = 77d02f15 in libsysrepo.so.5.4.0[77cf9000+3d000]

**Comment by michalvasko** [comment]
Hi,
much to my surprise, I did manage to reproduce this in a simpler scenario. Except the crash, in my case the error was handled correctly so I will assume that was fixed. But the error itself was not supposed to happen so please pull the latest *sysrepo* `devel`, it should be fixed now.

Regards,
Michal

**Comment by qjwu888** [comment]
Hi Michal,
Could you  tell me which commit to fix this issue in sysrepo devel?
I want to just update those code。

**Comment by michalvasko** [comment]
Hi,
the fix is referenced in this issue, above my previous post. But I cannot guarantee it will all work as it should if you take just that commit.

Regards,
Michal

**Comment by Julian-younger** [comment]
Hi,Michal
    I got the same problem with qjwu888，also the callhome scenario. I found that my code has included the fix code.
And it reproduced sometimes. 

> <?xml version="1.0" encoding="UTF-8"?>
> <rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="2">
>   <create-subscription xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0"/>
> </rpc>
> 
> [INF]: LY: Resolving unresolved data nodes and their constraints...
> [INF]: LY: All data nodes and constraints resolved.
> [INF]: LY: Resolving unresolved data nodes and their constraints...
> [INF]: LY: All data nodes and constraints resolved.
> [INF]: SR: Published event "rpc" "/notifications:create-subscription" with ID 2 priority 1 for 2 subscribers.
> [ERR]: SR: Opening "/etc/sysrepo/sr_evpipe7" for writing failed (No such file or directory).

**Comment by michalvasko** [comment]
So what version of *sysrepo* are you using exactly?
