### ISSUE TITLE
Permission control to start the stack

### ISSUE THREAD

**Issue by IvanAguiar95** [CESNET/Netopeer2#602]
Hi,
We noticed a weird behavior to start the stack and I'd like to check with you if it is the correct way, or what action we must do to adjust it.

To start the `netopeer2-server`, the sysrepo expect that the yang modules have a read-write permission  (600, 666, etc. 777 is not allowed), however, to use the sysrepo module into a python binding, is necessary to set the permission to 777 (right now, we're setting to 777 all the dependencies), and the app crashes when we try to restart the stack, so we have to:
- set to 666
- start netopeer
- set to 777
- start bindings

Do you have any suggestion to adjust this way?

BR, 
Ivan

**Comment by michalvasko** [comment]
Hi,
what exactly is the reason the Python bindings require permissions `777`? That is definitely wrong, no valid reason for that.

Regards,
Michal

**Comment by IvanAguiar95** [comment]
Michal, 

I rerun the stack in my env, and I validated this scenario. 
When the dependencies are in 666, the sysrepo returns `System function call failed`.

It works when it is in 777.

**Comment by michalvasko** [comment]
Hi,
could you please provide an __exact__ example of what function fails if the permissions are not `777`? I have tried `python_application_example.py`, which worked fine.

Also, what output does *netopeer2-server* produce when it refuses to start? I would expect an error from *sysrepo* saying that specific permissions are wrong.

Regards,
Michal

**Comment by IvanAguiar95** [comment]
Hi Michal,

Setting the dependencies to 777 (including the yangs), and running the netopeer2-server 
`sudo netopeer2-server -d -v2`, we got:

![Capture-777](https://user-images.githubusercontent.com/49284882/80218648-d5597180-8617-11ea-8acd-f580a7723806.PNG)

but setting the dependencies to 666, the **server works fine**, but the python callback returns:

![image](https://user-images.githubusercontent.com/49284882/80220248-eb683180-8619-11ea-93cc-2ee023f07066.png)

**Comment by michalvasko** [comment]
Hi,
could you maybe provide the full cut-off `sysrepoctl` output? Specifically, what permissions does `ietf-netconf` module (to which you are subscribing) has?

Regards,
Michal

**Comment by IvanAguiar95** [comment]
When I do the `sudo chmod ...` all the files from sysrepo repository, sysrepo cache, and all modules and dependencies as swig, libnetconf, etc, receive the permission.

**Comment by michalvasko** [comment]
Hi,
okay, I think the problem was with the permissions on the directories, which should be fixed now. Please pull latest *sysrepo* `devel` and try again.

Regards,
Michal
