### ISSUE TITLE
USECOMPAT issue while compiling with single CMakeLists file

### ISSUE THREAD

**Issue by sriramkandukuri** [CESNET/Netopeer2#603]
Hi,

We are using below CMakeLists file to compile both server and cli at same time.
```
cmake_minimum_required(VERSION 2.6)

set_property(GLOBAL PROPERTY ALLOW_DUPLICATE_CUSTOM_TARGETS 1)
add_subdirectory(server)
add_subdirectory(cli)
```
After recent commit to use macro `use_compat`
We are observing below error while compiling. Could you please suggest a way to solve this.
```
CMake Error at CMakeModules/UseCompat.cmake:26 (add_library):
  add_library cannot create target "compat" because another target with the
same name already exists.  The existing target is created in source
  directory
"netopeer2-1.1.23/server".
  See documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  cli/CMakeLists.txt:38 (use_compat)
```

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi,
please try it now.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi,

Now error `compat.h no such file or directory` from cli compilation.

Thanks & Regards,
Sriram.K

**Comment by michalvasko** [comment]
Hi Sriram,
please try again, hopefully works this time.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,

Yes its working fine now

Thanks & Regards,
Sriram.K
