### ISSUE TITLE
Question - SSH Server CBC Mode Ciphers Enabled

### ISSUE THREAD

**Issue by jjin62** [CESNET/Netopeer2#607]
Hi,
Nessus scan tool report the following issue:
70658 - SSH Server CBC Mode Ciphers Enabled:
tcp/830
The following client-to-server Cipher Block Chaining (CBC) algorithms
are supported :
10.1.101.188 7
3des-cbc
aes128-cbc
aes192-cbc
aes256-cbc
blowfish-cbc
des-cbc-ssh1
The following server-to-client Cipher Block Chaining (CBC) algorithms
are supported :
3des-cbc
aes128-cbc
aes192-cbc
aes256-cbc
blowfish-cbc
des-cbc-ssh1

How can I disable these weak algorithm? Are encryption algorithm configurable in netopeer-2 or libnetconf2? I am using openssl-1.1.1g and libssh-0.8.8, seems they don't have configurations for choosing ncryption algorithm.

thanks,
Jimmy

**Comment by michalvasko** [comment]
Hi,
the easiest thing to do would probably be to update *libssh* to at least 0.9.0 when the SSH configuration is read from the system including all the supported algorithms. If you do not want to do that, I think you could only directly modify *libnetconf2* code and manually set allowed algorithms.

Regards,
Michal

**Comment by jjin62** [comment]
Michal,
thanks for quick response. I will try to upgrade libssh to 0.9.4.
BTW, I also noticed that encryption-algorithm-t in ../modules/ietf-crypto-types@2019-07-02.yang. Seems it is used in key encryption.  But I guess data transport encryption algorithm does not belong to netconf server config, right? Certainly, this question is more related to the netconf standard, not specific to Netopeer2.

regards,
Jimmy

**Comment by michalvasko** [comment]
Hi,
actually, many of the nodes in the used modules are not supported mostly because they are still only drafts and there is some chaos in them. Also, please do not upgrade to 0.9.4 nor 0.9.3. Unfortunately they both include (a different) critical regression bug and *libnetconf2* will refuse to compile outright. Versions 0.9.0 - 0.9.2 should be fine.

Regards,
Michal

**Comment by jjin62** [comment]
Michal,
Seem libssh 0.9.4 works for me and I can config the Cipher algorithms I wanted.  I am using an old version linnetconf2 v0.12.55. May be that version has no compile issue with 0.9.4??

thanks for the help.
Jimmy

**Comment by michalvasko** [comment]
Hi,
well, the problem I had with *libssh* 0.9.4 was that after I connected, *libnetconf2* continued to measure inactive timeout, which elapses in around 10 seconds, and got automatically disconnected. It can be compiled, it is just unusable.

Regards,
Michal

**Comment by jjin62** [comment]
Michal,
Yes, I found the same issue. The session will disconnect unless client keep sending the requests. So I switched to 0.9.2 and it works.
Thanks for the heads up!
Jimmy
