### ISSUE TITLE
Plan: repository reorganization

### ISSUE THREAD

**Issue by michalvasko** [CESNET/netopeer2#608]
Hi,
we would like to gather some quick feedback on a major change in the repository that we plan to make starting next week (May 4th).

The idea is to make the server the main project and change CLI's role to something akin to a subproject. The main reason for this is to make clear what the project includes and create a single `cmake` list for building both the server and CLI. That will also break any existing external build scripts but minimal changes should be required. Also, this change will unify *netopeer2* repository organization with the other projects (*libyang*, *sysrepo*) and the branches as well, as after this change there would be `master` and `devel` instead of `devel-server`.

We are hoping no one will have any strong objections so we mostly want to let everyone interested know that such a change is planned.

Regards,
Michal

**Comment by iljatab** [comment]
Hi Michal,

Looks like a pretty painful change... yocto recipis should be rewritten.
But OK, nothing to do.
Could you please clarify if current content in devel-server branch will be still available with the same git commit hashes?

Ilja.

**Comment by michalvasko** [comment]
Hi Ilja,
right, it makes sense to keep that branch for some time after this change. But on the next release after this one or some time after it will be removed and will not be updated at all.

Regards,
Michal

**Comment by sriramkandukuri** [comment]
Hi Michal,
Thank you very much for the change. This literally reduces lot of maintenance.

Thanks & Regards,
Sriram.K
