### ISSUE TITLE
Edit-config returns ok despite validation failure

### ISSUE THREAD

**Issue by lukasmacko** [CESNET/Netopeer2#61]
See the issue https://github.com/sysrepo/sysrepo/issues/526
Return code from sr_validate is ignored and ok is returned. I think the cause of the issue is [here](https://github.com/CESNET/Netopeer2/blob/a3dd97d95c89f9623f4e9f4a9b431224e44c63f2/server/op_editconfig.c#L588-L604).

**Comment by michalvasko** [comment]
Hi,
please verify it works now.

Regards,
Michal

**Comment by lukasmacko** [comment]
Hi,

the rpc-reply is error as it should be. However, the error message contains operation succeeded.
```XML
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="29">
 <rpc-error>
   <error-type>application</error-type>
   <error-tag>operation-failed</error-tag>
   <error-severity>error</error-severity>
   <error-message xml:lang="en">Operation succeeded</error-message>
 </rpc-error>
</rpc-reply>
```

Regards,
Lukas

**Comment by michalvasko** [comment]
Hi Lukas,
the server simply calls `sr_get_last_errors` and builds the reply based on that so I believe sysrepo does something wrong, could you please check?

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
please try it again.

Michal

**Comment by lukasmacko** [comment]
Hi,

it's fixed.

Thanks & regards,
Lukas
