### ISSUE TITLE
netopeer2-server prints unexpected warning message

### ISSUE THREAD

**Issue by iljatab** [CESNET/Netopeer2#610]
Hi Michal,

We are starting netopeer2-server like `/usr/bin/netopeer2-server -v 0` and expect only error messages to be printed t the syslog.

However we are still getting warning messages like:
```
May  1 16:23:37 A5-AF A5-AF warning netopeer2-server[647]: Identity "INSTALL_PROTOCOL_TYPE" has no derived identities, identityref with this base can never be instatiated.
May  1 16:23:37 A5-AF A5-AF warning netopeer2-server[647]: Identityref value is not derived from all its bases. (/openconfig-network-instance:identifier)
May  1 16:23:37 A5-AF A5-AF warning netopeer2-server[647]: Failed to resolve identityref "PIM". (/openconfig-network-instance:identifier)
May  1 16:23:37 A5-AF A5-AF warning netopeer2-server[647]: Previous warning generated by XPath subexpression[7] "identifier = 'PIM'".
May  1 16:23:37 A5-AF A5-AF warning netopeer2-server[647]: Identityref "identifier" comparison with identity "IGMP" without prefix, consider adding a prefix or best using "derived-from(-or-self)()" functions.
May  1 16:23:37 A5-AF A5-AF warning netopeer2-server[647]: Previous warning generated by XPath subexpression[7] "identifier = 'IGMP'".
May  1 16:23:37 A5-AF A5-AF warning netopeer2-server[647]: Identity "INSTALL_PROTOCOL_TYPE" has no derived identities, identityref with this base can never be instatiated.
```

There are literally thousands of these message, printed by netopeer2-server and start-up (most caused by openconfig yang models).

Would it be possible to really switch off all warning messages?

Ilja.

**Comment by michalvasko** [comment]
Hi Ilja,
I have just tried this and it worked correctly for me, are you using *netopeer2* from `devel-server`?

Regards,
Michal

**Comment by iljatab** [comment]
$ /usr/bin/netopeer2-server -V
netopeer2-server 1.1.25
compile time: May  1 2020, 06:34:07

Could it be so that these warnings come from libyang and are not affected by `netopeer2-server -v 0` switch?

Ilja.

**Comment by michalvasko** [comment]
Hi Ilja,
yes, they do come from *libyang* but are affected by *netopeer2* verbose level for my case, at least I think so. Anyway, could you please try the attached patch? I will commit it if it works for you.

Regards,
Michal

[diff.patch.txt](https://github.com/CESNET/Netopeer2/files/4573705/diff.patch.txt)

**Comment by iljatab** [comment]
Thanks, looks like it helps!
Are you going to commit it?
Ilja.

**Comment by michalvasko** [comment]
Hi Ilja,
yes, I just did.

Regards,
Michal

**Comment by iljatab** [comment]
Thanks!
