### ISSUE TITLE
Multiple threads on the server

### ISSUE THREAD

**Issue by maksimvuleta** [CESNET/netopeer2#612]
I installed the sysrepo, netopeer-server, libyang, libnetconf2 from devel branches.
In the netopeer2 server, I set THREAD COUNT to 5.

We have over 10 YANG modules installed and implemented.
Also, we have some tests to check the concurrent access to the modules with python ncclient.
I am talking about getting and edit data via netconf from the multiple processes and multiple threads.

Sometimes the sysrepo-plugind and netopeer2-server are running but I am not able to connect anymore with ncclient or netopeer2-client.
Sometimes the sysrepo-plugind or netopeer2-server are crashed. 

When I set the THREAD COUNT to 1, and reinstall the netopeer2 server, everything seems to be fine.

I am not able to provide the test scripts and installed modules now and my idea is the issue stays as a reminder for me or netopeer2 contributors to pay attention to multiple server threads and netconf access from multiple threads and processes. 
Also, maybe some tests should be added for these staff.

Best regards,
Maksim.

**Comment by michalvasko** [comment]
Hi Maksim,
actually most of the tests are multi-threaded and there are even multi-process ones so only finding the problematic use-cases is the problem and I simply do not have the time for that. I am just trying to fix problems if anyone encounters them. I have recently fixed quite a complex one with general concurrency when having many callbacks with the same priority on the same module.

Anyway, for starters you could provide the output of the server when started with `-v3`. Additionally, you can collect some information about the crash if you run the server using `valgrind` or `gdb`. That should not be too difficult or require much effort and may be enough for me to reproduce the problem or even fix it right away.

Regards,
Michal
