### ISSUE TITLE
Compilation and installation issues

### ISSUE THREAD

**Issue by achudejiejie** [CESNET/Netopeer2#614]
Hi,
    
    When I make it, the following error appears:
`/mnt/Netopeer2/src/log.c:155:10: error: ‘NC_VERB_DEBUG_LOWLVL’ undeclared (first use in this function)`
    Then I commented NC_VERB_DEBUG_LOWLVL and it can be compiled successfully.

    But when I make install, I got an error again:
`-- Set runtime path of "/usr/local/bin/netopeer2-server" to ""
-- Installing missing sysrepo modules...
/usr/local/bin/sysrepoctl: error while loading shared libraries: libsysrepo.so.5: cannot open shared object file: No such file or directory
/usr/local/bin/sysrepoctl: error while loading shared libraries: libsysrepo.so.5: cannot open shared object file: No such file or directory
CMake Warning (dev) at cmake_install.cmake:61 (if):
  given arguments:

    "127"

  An argument named "127" appears in a conditional statement.  Policy CMP0012
  is not set: if() recognizes numbers and boolean constants.  Run "cmake
  --help-policy CMP0012" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at cmake_install.cmake:63 (elseif):
  given arguments:

    "GREATER" "0"

  Unknown arguments specified

Makefile:61: recipe for target 'install' failed
make: *** [install] Error 1
`
    It seems to be a problem with libsysrepo.so.5, but I do have this file
`root@76a0fa33d8d8:/mnt/Netopeer2/build# find / -name libsysrepo.so.5
/usr/local/lib/libsysrepo.so.5
/mnt/sysrepo/build/libsysrepo.so.5
root@76a0fa33d8d8:/mnt/Netopeer2/build# ls /usr/local/lib/libsysrepo.so.5*
/usr/local/lib/libsysrepo.so.5  /usr/local/lib/libsysrepo.so.5.5.0
`
    I wonder if my sysrepo is not installed correctly.
    Can you help point out my problem

Regards,
Fred

**Comment by michalvasko** [comment]
Hi Fred,
as for your first problem, please correctly update *libnetconf2*, that is why the symbol is not found. The second problem is caused by your dynamic linker not having found *libsysrepo.so*. You should be able to fix that by simply running `# ldconfig`. Check that it was found by executing `ldconfig -p | grep libsysrepo`.

Regards,
Michal

**Comment by achudejiejie** [comment]
Yes, this problem caused by a problem with sysrepo installation has been solved, thank you
