### ISSUE TITLE
[cli] Unable to build only the cli separately

### ISSUE THREAD

**Issue by kramarz89** [CESNET/Netopeer2#616]
Hi Michal,

I had netopeer2-cli cross-compiled as a separate "being" without the server.
After the repo reorganization the build fails, it is no longer possible to build only the CLI? 
Sad to see the change not being backwards compatible.

```
 CMake Error at CMakeLists.txt:19 (add_executable):
|   Error evaluating generator expression:
| 
|     $<TARGET_OBJECTS:compat>
| 
|   Objects of target "compat" referenced but no such target exists.
| 
| 
| CMake Error at CMakeLists.txt:19 (add_executable):
|   No SOURCES given to target: netopeer2-cli
| 
| 
| -- Build files have been written to: /build/qemux86/build/tmp-glibc/work/i586-wrs-linux/netopeer2-cli/1.1.27-r0.0/build
| WARNING: /build/qemux86/build/tmp-glibc/work/i586-wrs-linux/netopeer2-cli/1.1.27-r0.0/temp/run.do_configure.9784:1 exit 1 from 'cmake -G Ninja -DCMAKE_MAKE_PROGRAM=ninja $oecmake_sitefile /build/qemux86/build/tmp-glibc/work/i586-wrs-linux/netopeer2-cli/1.1.27-r0.0/Netopeer2-1.1.27/cli -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_BINDIR:PATH=bin -DCMAKE_INSTALL_SBINDIR:PATH=sbin -DCMAKE_INSTALL_LIBEXECDIR:PATH=libexec -DCMAKE_INSTALL_SYSCONFDIR:PATH=/etc -DCMAKE_INSTALL_SHAREDSTATEDIR:PATH=../com -DCMAKE_INSTALL_LOCALSTATEDIR:PATH=/var -DCMAKE_INSTALL_LIBDIR:PATH=lib -DCMAKE_INSTALL_INCLUDEDIR:PATH=include -DCMAKE_INSTALL_DATAROOTDIR:PATH=share -DCMAKE_INSTALL_SO_NO_EXE=0 -DCMAKE_TOOLCHAIN_FILE=/build/qemux86/build/tmp-glibc/work/i586-wrs-linux/netopeer2-cli/1.1.27-r0.0/toolchain.cmake -DCMAKE_VERBOSE_MAKEFILE=1 -DCMAKE_NO_SYSTEM_FROM_IMPORTED=1 -DCMAKE_BUILD_TYPE:String=Release -Wno-dev'
| ERROR: Function failed: do_configure (log file is located at /build/qemux86/build/tmp-glibc/work/i586-wrs-linux/netopeer2-cli/1.1.27-r0.0/temp/log.do_configure.9784)
ERROR: Task (/test-vm-build/layers/meta-netopeer2-sysrepo/recipes-core/netopeer2/netopeer2-cli_1.1.27.bb:do_configure) failed with exit code '1'
```

BR,
Adam

**Comment by michalvasko** [comment]
Hi Adam,
yes, after the changes the CLI cannot be build without the server, only the other way around. Is that a problem? Before there were 2 projects in the repository but after this change we would like it to be a single project. The package (once done) will also include both the server and CLI.

Regards,
Michal

**Comment by kramarz89** [comment]
Yeah, this caused some additional work, and lots of yocto recipes changes for me, thought that there might be a "switch" or something that you've hidden somewhere. 
Doesn't matter now, the harm was done :D Worked through it.

Regards
Adam

**Comment by michalvasko** [comment]
HI Adam,
I was aware of "the harm" but I am afraid it was inevitable :) But now the *netopeer2* repository looks just like the others and is organized better because it has one main `cmake` list. It will also allow to reuse packaging scripts from those other repositories, which was actually the main reason for this.

Regards,
Michal
