### ISSUE TITLE
How to get the result of copy-config?

### ISSUE THREAD

**Issue by mookhone** [CESNET/netopeer2#618]
Hi,

The copy-config command was executed, but the resulting file is empty.
Is there anything else I need to do to get results?

### netopeer2 log
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Session 15 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" with ID 8 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:copy-config" "rpc" event with ID 8 priority 0 (remaining 1 subscribers).
[INF]: SR: Finished processing "rpc" event with ID 8 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 8 priority 0 succeeded.
[INF]: NP: Session 3: thread 4 event new RPC.

### netopeer-cli command history
> connect 127.0.0.1
> copy-config --target url:file:///root/copy-config-result.xml --source running
OK
>

### the result of copy-config
[root@4783aa7d6f45 ~]# ls -al /root/copy-config-result.xml 
-rw-r--r-- 1 root root 58 May 12 04:51 /root/copy-config-result.xml
[root@4783aa7d6f45 ~]# cat /root/copy-config-result.xml 
<config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"/>
[root@4783aa7d6f45 ~]#

I expected that the copy-config-result.xml file contain config data, but it is empty.

Thank you for your help.

**Comment by michalvasko** [comment]
Okay, what *netopeer2* version are you using?

**Comment by mookhone** [comment]
I'm using netopeer2-server 1.1.7.

Thanks.

**Comment by michalvasko** [comment]
Right, there were some basic problems with `url` capability that should be fixed in the latest release (1.1.27) so please update to that and it should work.

Regards,
Michal

**Comment by mookhone** [comment]
Thank you for your help.
I will try again using latest release(1.1.27).
