### ISSUE TITLE
Ubuntu 20.04 LTS installation problem

### ISSUE THREAD

**Issue by michalvasko** [CESNET/netopeer2#621]
When executing `sudo make install` on Ubuntu 20.04 a `permission denied` error is observed. After brief investigation, the reason for this is that `shm_open` with `O_RDWR | O_CREAT` on an existing shared memory file with permissions `00666` owned by other user than `root` fails with the error. This seems to be a direct violation of POSIX specification hence we do not know about any solution currently and any comments are welcome.

It was also learned that if the `O_CREAT` flag is removed, it succeeds. But using `open` instead of `shm_open` or calling this function when logged directly as `root` does not make any difference.

**Comment by rjarry** [comment]
Hi Michal,

Are you encountering this into a linux container? If so, this *may* be related to the default docker [AppArmor profile](https://docs.docker.com/engine/security/apparmor/).

I already encountered this kind of confusing errors because of AppArmor.

**Comment by michalvasko** [comment]
Hi,
I have it as a virtual machine in VirtualBox. But I still went through the configuration files and found nothing relevant and what "app" rules would be applied here anyway, `make`? I also did not see any messages in `dmesg` when the error occurred so I think this is not the cause. Thanks for the idea, though.

Regards,
Michal

**Comment by rkrejci** [comment]
- https://askubuntu.com/questions/1264273/permission-denied-on-shared-memory-segments-in-dev-shm
- https://stackoverflow.com/questions/63233822/permission-denied-on-shared-memory-segments-in-dev-shm-on-ubuntu-20-04
- https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1890168

**Comment by Varrrro** [comment]
Hey, just wanted to ask if there are any news about this problem, as I am facing it myself on a new Ubutnu 20.04 installation.

**Comment by michalvasko** [comment]
Look into the other referenced issue, there is a workaround provided in *sysrepo*. Other than that I guess we are simply hoping this "feature" will be disabled in newer Ubuntu versions. I am not sure how it is in 21.04, actually.

**Comment by Varrrro** [comment]
Oh I see. I just tried with an Ubuntu 21.04 PC and couldn't install either.

```
-- Installing missing sysrepo modules...
[ERR]: Failed to open ext shared memory (Permission denied).
sysrepoctl error: Failed to connect (System function call failed)
[ERR]: Failed to open ext shared memory (Permission denied).
sysrepoctl error: Failed to connect (System function call failed)
CMake Error at cmake_install.cmake:86 (message):
    scripts/setup.sh failed: 1
```

Also, `sysctl fs.protected_regular` returns `2`, which is different from what is said in the referenced issue.

**Comment by myonlystarWang** [comment]
Hi everyone,
     I have installed Ubuntu 20.04.2 LTS and installed _sysrepo_/_netopeer2_ just one minute before,no errors were reported and everything works fine and the callhome function also works well! I also did not set any system parameters, it is the default installation.
Here is the system info and kernal info:
```
root@user:/home/user# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
root@user:/home/user# uname -mrn
user 5.4.0-73-generic x86_64
root@user:/home/user#
```
 
Is that the issue that doesn't exist now?

**Comment by michalvasko** [comment]
Can you post the output of `sysctl fs.protected_regular`?

**Comment by myonlystarWang** [comment]
Here it is:
```
root@user:/home/user# sysctl fs.protected_regular
fs.protected_regular = 2
```

**Comment by michalvasko** [comment]
Hm, that is quite strange because that value means the extra protection that prevents *sysrepo* from working normally is enabled.

**Comment by myonlystarWang** [comment]
The version of netopeer2 is 1.1.70
The version of libnetconf2 is 1.1.43
The version of libyang is 1.0.225
The version of sysrepo is 1.4.122

It worked the first time

**Comment by Varrrro** [comment]
Hey, I tried again due to @myonlystarWang saying it works and it indeed does. `fs.protected_regular` is `2` but it didn't show any errors.
