### ISSUE TITLE
Configuring <module-name> inside NACM <rule> causes errors

### ISSUE THREAD

**Issue by jabilmplane** [CESNET/netopeer2#625]
Hi
Could you, please, help me with following issue:

To test NACM privileges features a new group "engineer-group" and user "engineer" were configured.
The idea is to grant to new user ("engineer") full permissions only for certain module.
To achieve such behavior the <module-name> value inside appropriate NACM group rule should be changed from default value("*") to the specified module name.

However, when the certain module name specified for <module-name> some issues occur. Also there are two different cases depending the default module's name is configured or the custom's one: 
1. Whenever default module's name is configured the user cannot access the data from permited module because of "access-denied" error.
2. Whenever custom module's name is configured the "Module name <module name> refers to an unknown module" error occurred.

Below you can find the steps to reproduce the issues. All steps are verified on the latest "devel" brunch for all repositories.

Steps: 
1) Create a new Linux user "engineer".
2) Configure the user in NACM by adding new group and and rule-list into datastore:
  ```
<group>
    <name>engineer-group</name>
    <user-name>engineer</user-name>
  </group>
	...
  <rule-list>
    <name>Engineer</name>
    <group>engineer-group</group>
    <rule>
      <name>test-any-access</name>
      <module-name>*</module-name>
      <access-operations>*</access-operations>
      <action>permit</action>
      <comment>Full permissions to admin group.</comment>
    </rule>
  </rule-list>
```

3. Verify that "engineer" user is able to login into CLI: 
pavlo@pavlo-RF-temp:~$ sudo netopeer2-cli -d -v2
[sudo] password for pavlo: 
> connect --login engineer
Interactive SSH Authentication
Type your password:
Password: 
> 

4. Verify that "engineer" user have access to data from some default module (e.g. ietf-netconf-acm):
```
> get-config --source running --filter-xpath /ietf-netconf-acm:*
DATA
<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
  <enable-nacm>true</enable-nacm>
  <read-default>deny</read-default>
  <write-default>deny</write-default>
  <exec-default>deny</exec-default>
  <enable-external-groups>false</enable-external-groups>
  <groups>
    <group>
      <name>admin</name>
      <user-name>pavlo</user-name>
      <user-name>tls-test</user-name>
    </group>
    <group>
      <name>engineer-group</name>
      <user-name>engineer</user-name>
    </group>
  </groups>
  <rule-list>
    <name>Administration</name>
    <group>admin</group>
    <rule>
      <name>any-access</name>
      <module-name>*</module-name>
      <access-operations>*</access-operations>
      <action>permit</action>
      <comment>Full permissions to admin group.</comment>
    </rule>
  </rule-list>
  <rule-list>
    <name>Engineer</name>
    <group>engineer-group</group>
    <rule>
      <name>test-any-access</name>
      <module-name>*</module-name>
      <access-operations>*</access-operations>
      <action>permit</action>
      <comment>Full permissions to admin group.</comment>
    </rule>
  </rule-list>
</nacm>
```

4. Verify that "engineer" user have access to data from some custom module ("test" is a custom module installed by me):
```
> get-config --source running --filter-xpath /test:*
DATA
<test xmlns="urn:test">
  <cont1>
    <leaf1>11</leaf1>
  </cont1>
</test>
```

5. Restrict the user rights to access only one default module by changing <module-name> from "*" to "ietf-netconf-acm": 
  ```
<rule-list>
    <name>Engineer</name>
    <group>engineer-group</group>
    <rule>
      <name>test-any-access</name>
      <module-name>ietf-netconf-acm</module-name>
      <access-operations>*</access-operations>
      <action>permit</action>
      <comment>Full permissions to admin group.</comment>
    </rule>
  </rule-list>
```

6. Try to access the data from permitted module:
```
> get-config --source running --filter-xpath /ietf-netconf-acm:*
ERROR
	type:     application
	tag:      access-denied
	severity: error
	path:     /ietf-netconf:get-config
	message:  Access to the requested protocol operation or data model is denied because authorization failed.
```

7. Restrict the user rights to access only the custom module "test" by changing <module-name> to "test":
 ```
 <rule-list>
    <name>Engineer</name>
    <group>engineer-group</group>
    <rule>
      <name>test-any-access</name>
      <module-name>test</module-name>
      <access-operations>*</access-operations>
      <action>permit</action>
      <comment>Full permissions to admin group.</comment>
    </rule>
  </rule-list>
```

8. Try to access the data from permitted module:
```
> get-config --source running --filter-xpath /test:*
ly ERROR: Module name "test" refers to an unknown module.
cli_send_recv: Failed to send the RPC.
```

Thanks in advance!

**Comment by michalvasko** [comment]
Hi,
I am not sure what NETCONF server are you connected to but it certainly is not the current `devel` *sysrepo* or *netopeer2*. Based on the message
```
Access to the requested protocol operation or data model is denied because authorization failed.
```
it seems it is actually the legacy *sysrepo* and *netopeer2*. Could you please run `netopeer2-server -V` and paste it here?

Regards,
Michal

**Comment by jabilmplane** [comment]
@michalvasko, when you say "legacy", do you mean "master" branch?

**Comment by jabilmplane** [comment]
pavlo@pavlo-RF-temp:~$ netopeer2-server -V
netopeer2-server 1.1.31
compile time: May 18 2020, 18:02:27

Also I’ve checked sysrepo and netopeer2 repositories:
1) The last commit for sysrepo:
commit 0389c7255007c3b4814ef25fa1d58bec567e3250 (HEAD -> devel, origin/devel)
Author: FredGan <ganshaolong@vip.qq.com>
Date: Mon May 18 17:58:05 2020 +0800
2) The last commit for Netopeer2:
commit 6767db7f17ce162de514d77d1777f48dfa4eaa23 (HEAD -> devel, origin/devel)
Author: Michal Vasko <mvasko@cesnet.cz>
Date: Wed May 13 08:56:48 2020 +0200

So, as far as I see, the only changes Netopeer2 does not contain were committed today.

**Comment by michalvasko** [comment]
Hi,
okay, sorry, you are using a recent version, I was just confused by the generic message. I have improved it.

As for your issue, the first error is correct. It says you do not have the permission to execute `get-config` RPC, which is correct as `exec-default` is set to `deny`. Before, you had an explicit rule that allowed all rights for all the modules so all the operations were covered by that.

The unknown module error is probably also correct if you do not have any module named `test` installed in *sysrepo*.

Regards,
Michal

**Comment by jabilmplane** [comment]
Hi,
It seems, the issue is resolved. It was my mistake in the way I am configuring NACM rules.
So, I think, the issue could be closed.

Thank you for your support!
