### ISSUE TITLE
Problem making netopeer2

### ISSUE THREAD

**Issue by eraonel** [CESNET/netopeer2#627]
Hi

I am using Docker image to create a runnable netopeer2. 
When making and building my docker image I get:
Step 11/15 : RUN       git clone -b devel-server https://github.com/CESNET/Netopeer2.git &&       cd Netopeer2/server && mkdir build && cd build &&       cmake -DCMAKE_BUILD_TYPE:String="Debug" .. &&       make -j2 &&      make install &&       cd ../../cli && mkdir build && cd build &&       cmake -DCMAKE_BUILD_TYPE:String="Debug" .. &&       make -j2 &&       make install
 ---> Running in 22ff2d2d7215
Cloning into 'Netopeer2'...
-- The C compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- libnetconf2 was compiled with support of up to 6 threads
-- Looking for vdprintf
-- Looking for vdprintf - found
-- Looking for asprintf
-- Looking for asprintf - found
-- Looking for vasprintf
-- Looking for vasprintf - found
-- Looking for get_current_dir_name
-- Looking for get_current_dir_name - found
-- Looking for strndup
-- Looking for strndup - found
-- Looking for getline
-- Looking for getline - found
-- Looking for strdupa
-- Looking for strdupa - found
-- Looking for strchrnul
-- Looking for strchrnul - found
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
-- libcurl not found, url capability will not be supported
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Looking for stdatomic.h
-- Looking for stdatomic.h - found
-- Found LibSSH: /usr/lib/x86_64-linux-gnu/ (Required is at least version "0.7.0")
-- Looking for NC_ENABLED_SSH
-- Looking for NC_ENABLED_SSH - found
-- Looking for NC_ENABLED_TLS
-- Looking for NC_ENABLED_TLS - found
-- Found sysrepo: /usr/local/lib/libsysrepo.so
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/dev/Netopeer2/server/build
Scanning dependencies of target compat
Scanning dependencies of target serverobj
[  8%] Building C object CMakeFiles/compat.dir/opt/dev/Netopeer2/compat/compat.c.o
[ 16%] Building C object CMakeFiles/serverobj.dir/common.c.o
[ 16%] Built target compat
[ 25%] Building C object CMakeFiles/serverobj.dir/netconf.c.o
/opt/dev/Netopeer2/server/netconf.c: In function 'np2srv_rpc_editconfig_cb':
/opt/dev/Netopeer2/server/netconf.c:232:14: error: too few arguments to function 'sr_validate'
         rc = sr_validate(session, 0);
              ^~~~~~~~~~~
In file included from /opt/dev/Netopeer2/server/netconf.c:26:0:
/usr/local/include/sysrepo.h:961:5: note: declared here
 int sr_validate(sr_session_ctx_t *session, const char *module_name, uint32_t timeout_ms);
     ^~~~~~~~~~~
/opt/dev/Netopeer2/server/netconf.c: In function 'np2srv_rpc_validate_cb':
/opt/dev/Netopeer2/server/netconf.c:619:14: error: too few arguments to function 'sr_validate'
         rc = sr_validate(session, 0);
              ^~~~~~~~~~~
In file included from /opt/dev/Netopeer2/server/netconf.c:26:0:
/usr/local/include/sysrepo.h:961:5: note: declared here
 int sr_validate(sr_session_ctx_t *session, const char *module_name, uint32_t timeout_ms);
     ^~~~~~~~~~~
CMakeFiles/serverobj.dir/build.make:86: recipe for target 'CMakeFiles/serverobj.dir/netconf.c.o' failed
make[2]: *** [CMakeFiles/serverobj.dir/netconf.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/serverobj.dir/all' failed
make[1]: *** [CMakeFiles/serverobj.dir/all] Error 2

Any ideas?

//mike

**Comment by eraonel** [comment]
Docker file used:
git clone -b devel-server https://github.com/CESNET/Netopeer2.git
so I changed to master but got a different error message:
Scanning dependencies of target netopeer2-cli
[ 16%] Building C object cli/CMakeFiles/netopeer2-cli.dir/main.c.o
[ 22%] Building C object CMakeFiles/serverobj.dir/src/netconf.c.o
[ 27%] Building C object cli/CMakeFiles/netopeer2-cli.dir/commands.c.o
[ 33%] Building C object CMakeFiles/serverobj.dir/src/netconf_monitoring.c.o
[ 38%] Building C object CMakeFiles/serverobj.dir/src/netconf_server.c.o
[ 44%] Building C object CMakeFiles/serverobj.dir/src/netconf_server_ssh.c.o
[ 50%] Building C object cli/CMakeFiles/netopeer2-cli.dir/completion.c.o
[ 55%] Building C object CMakeFiles/serverobj.dir/src/netconf_server_tls.c.o
[ 61%] Building C object cli/CMakeFiles/netopeer2-cli.dir/configuration.c.o
[ 66%] Building C object CMakeFiles/serverobj.dir/src/netconf_acm.c.o
[ 72%] Building C object cli/CMakeFiles/netopeer2-cli.dir/linenoise/linenoise.c.o
[ 77%] Building C object CMakeFiles/serverobj.dir/src/netconf_nmda.c.o
[ 83%] Linking C executable ../netopeer2-cli
/usr/local/lib/libnetconf2.so: undefined reference to `ssh_threads_get_pthread'
collect2: error: ld returned 1 exit status
cli/CMakeFiles/netopeer2-cli.dir/build.make:204: recipe for target 'netopeer2-cli' failed
make[2]: *** [netopeer2-cli] Error 1
CMakeFiles/Makefile2:279: recipe for target 'cli/CMakeFiles/netopeer2-cli.dir/all' failed
make[1]: *** [cli/CMakeFiles/netopeer2-cli.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

Which branch to use?

//mike

**Comment by michalvasko** [comment]
Hi,
please use either `devel` of all the projects or `master`. In *netopeer2*, `devel-server` is an obsolete branch that should no longer be used and will be deleted.

Regards,
Michal

**Comment by eraonel** [comment]
Tried devel on all:

[ 77%] Building C object CMakeFiles/serverobj.dir/src/netconf_nmda.c.o
[ 83%] Linking C executable ../netopeer2-cli
/usr/local/lib/libnetconf2.so: undefined reference to `ssh_threads_get_pthread'
collect2: error: ld returned 1 exit status
cli/CMakeFiles/netopeer2-cli.dir/build.make:204: recipe for target 'netopeer2-cli' failed
make[2]: *** [netopeer2-cli] Error 1
CMakeFiles/Makefile2:279: recipe for target 'cli/CMakeFiles/netopeer2-cli.dir/all' failed
make[1]: *** [cli/CMakeFiles/netopeer2-cli.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 88%] Building C object CMakeFiles/serverobj.dir/src/log.c.o
[ 88%] Built target serverobj
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Still error.

**Comment by michalvasko** [comment]
Okay, what *libssh* version are you using? It is obviously not detected properly. Could you also paste the output of `cmake` for *libnetconf2*?

Regards,
Michal

**Comment by eraonel** [comment]
_BUILD_TESTS=OFF .. &&       make -j2 &&       make install &&       ldconfig
 ---> Running in f2d72061c915
Cloning into 'libnetconf2'...
Already on 'devel'
Your branch is up to date with 'origin/devel'.
-- The C compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for vdprintf
-- Looking for vdprintf - found
-- Looking for asprintf
-- Looking for asprintf - found
-- Looking for vasprintf
-- Looking for vasprintf - found
-- Looking for get_current_dir_name
-- Looking for get_current_dir_name - found
-- Looking for strndup
-- Looking for strndup - found
-- Looking for getline
-- Looking for getline - found
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Looking for stdatomic.h
-- Looking for stdatomic.h - found
-- Looking for pthread_mutex_timedlock
-- Looking for pthread_mutex_timedlock - found
-- Looking for pthread_rwlockattr_setkind_np
-- Looking for pthread_rwlockattr_setkind_np - found
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1")
-- OPENSSL found, required for TLS
-- Found LibSSH: /usr/include (found suitable version "0.7.0", minimum required is "0.7.0")
-- Found LibYANG: /usr/local/lib/libyang.so (found version "1.8.0")
-- Looking for shadow.h
-- Looking for shadow.h - found
-- Looking for crypt.h
-- Looking for crypt.h - found
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Missing tools (devscripts, debhelper package) for building DEB package.
-- Missing tools (rpm package) for building RPM package.
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Could NOT find CMocka (missing: CMOCKA_LIBRARIES CMOCKA_INCLUDE_DIR) (Required is at least version "1.0.0")
-- Configuring done
WARNING: Target "netconf2" requests linking to directory "/usr/lib/x86_64-linux-gnu/".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /opt/dev/libnetconf2/build
Scanning dependencies of target compat
[  7%] Building C object CMakeFiles/compat.dir/compat/compat.c.o
[  7%] Built target compat
Scanning dependencies of target netconf2
[ 21%] Building C object CMakeFiles/netconf2.dir/src/io.c.o
[ 21%] Building C object CMakeFiles/netconf2.dir/src/log.c.o
[ 28%] Building C object CMakeFiles/netconf2.dir/src/messages_client.c.o
[ 35%] Building C object CMakeFiles/netconf2.dir/src/messages_server.c.o
[ 42%] Building C object CMakeFiles/netconf2.dir/src/session.c.o
[ 50%] Building C object CMakeFiles/netconf2.dir/src/session_client.c.o
[ 57%] Building C object CMakeFiles/netconf2.dir/src/session_server.c.o
[ 64%] Building C object CMakeFiles/netconf2.dir/src/time.c.o
[ 71%] Building C object CMakeFiles/netconf2.dir/src/session_client_ssh.c.o
[ 78%] Building C object CMakeFiles/netconf2.dir/src/session_server_ssh.c.o
/opt/dev/libnetconf2/src/session_client_ssh.c: In function 'sshauth_hostkey_check':
/opt/dev/libnetconf2/src/session_client_ssh.c:298:5: warning: 'ssh_get_publickey' is deprecated [-Wdeprecated-declarations]
     ret = ssh_get_publickey(session, &srv_pubkey);
     ^~~
In file included from /opt/dev/libnetconf2/src/session_client_ssh.c:40:0:
/usr/include/libssh/libssh.h:489:31: note: declared here
 SSH_DEPRECATED LIBSSH_API int ssh_get_publickey(ssh_session session, ssh_key *key);
                               ^~~~~~~~~~~~~~~~~
[ 85%] Building C object CMakeFiles/netconf2.dir/src/session_client_tls.c.o
[ 92%] Building C object CMakeFiles/netconf2.dir/src/session_server_tls.c.o
[100%] Linking C shared library libnetconf2.so
[100%] Built target netconf2
[  7%] Built target compat
[100%] Built target netconf2
Install the project...
-- Install configuration: "Debug"
-- Installing: /usr/local/lib/libnetconf2.so.1.3.5
-- Installing: /usr/local/lib/libnetconf2.so.1
-- Installing: /usr/local/lib/libnetconf2.so
-- Set runtime path of "/usr/local/lib/libnetconf2.so.1.3.5" to ""
-- Installing: /usr/local/include/nc_client.h
-- Installing: /usr/local/include/nc_server.h
-- Installing: /usr/local/include/libnetconf2/config.h
-- Installing: /usr/local/include/libnetconf2/log.h
-- Installing: /usr/local/include/libnetconf2/netconf.h
-- Installing: /usr/local/include/libnetconf2/session.h
-- Installing: /usr/local/include/libnetconf2/messages_client.h
-- Installing: /usr/local/include/libnetconf2/messages_server.h
-- Installing: /usr/local/include/libnetconf2/session_client.h
-- Installing: /usr/local/include/libnetconf2/session_client_ch.h
-- Installing: /usr/local/include/libnetconf2/session_server.h
-- Installing: /usr/local/include/libnetconf2/session_server_ch.h
-- Installing: /usr/local/lib/pkgconfig/libnetconf2.pc

possible to specify a tag for each lib and not get latest each time?

br,

//mikael

**Comment by michalvasko** [comment]
Hi,
please try it again, in the latest *libnetconf2* `devel` it should work, I hope. I have just failed to reference this issue properly in the commit. Also, you are using an ancient *libssh* version and I seem to remember there was some critical bug in 0.7.0 but it should compile now, anyway.

Regards,
Michal

**Comment by eraonel** [comment]
Hi,

-- roff2html not found, html version of man pages cannot be generated!
CMake Error at CMakeLists.txt:40 (install):
  install TARGETS given no RUNTIME DESTINATION for executable target
  "netopeer2-cli".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.10)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

br,

//mike

**Comment by michalvasko** [comment]
Hi,
do not build the CLI directly, if you just build the whole project [normally](https://github.com/CESNET/Netopeer2/#compilation-and-installation), it will also build and install the CLI.

Regards,
Michal

**Comment by eraonel** [comment]
Works now since I did not make cli dir separate.
Thanks for great support.

br,

//mike
