### ISSUE TITLE
XML input and Output of RPC

### ISSUE THREAD

**Issue by masif-cs** [CESNET/netopeer2#629]
Hi,

I want to understand how XML input/output works for Netconf RPC. What I can see is Netopeer CLI accepts XML input with multiple root node like below. But this kind of XML cant be generated by XML because one XML file can have only one Root Node.

```
<oven1 xmlns="something">
     <temperature>100</temperature>
</oven1>
<oven2 xmlns="something">
     <temperature>100</temperature>
</oven2>
```

Similarly if Root Node has multiple instance like below, XML cant have multiple instance at root level.

```
<oven1 xmlns="something">
        <id>1</id>
        <temperature>100</temperature>
</oven1>
<oven1 xmlns="something">
        <id>2</id>
        <temperature>100</temperature>
</oven1>
```

Here I am using libxml2 to generate the XML input for RPC. Please let me know if my understanding is not correct or I am not doing it right way?

**Comment by michalvasko** [comment]
Hi,
yes, you are absolutely correct but it works this way because it simplifies adding the configuration (you input it directly without any envelope or anything) and since we handle XML on our own, we are not strictly limited in any way. If you want to use the CLI and feed its input as a well-formed XML, you can always use `user-rpc` for all the RPCs. You just have to include the whole RPC with its input.

Regards,
Michal

**Comment by masif-cs** [comment]
Hi @michalvasko 

Problem what I am trying to tell is if I add dummy node or envelope on my XML, sysrepo wont understand it because it wont know what is the dummy node. So it will fail the edit-config or even user-rpc.

```
<root>
    <oven1 xmlns="something">
        <id>1</id>
        <temperature>100</temperature>
   </oven1>
   <oven1 xmlns="something">
        <id>2</id>
        <temperature>100</temperature>
   </oven1>
</dummy>
```

Is there any other option by which I can send multiple modules or multiple instance of root node in one edit-config so that RPC doesnt fail?

**Comment by michalvasko** [comment]
Hi,
but I still do not know what exactly is your interface. Are you trying to send an RPC using *sysrepo* `sr_rpc_send()`? Or through NETCONF using *libnetconf2* `nc_send_rpc()`? Or using  some binary client such as *netopeer2-cli*?

Regards,
Michal

**Comment by masif-cs** [comment]
Hi,

I am using nc_send_rpc to send using libnetconf2.

**Comment by michalvasko** [comment]
Okay, so you were probably trying to use `nc_rpc_edit()` to create the RPC. But if you can work only with well-formed XMLs, you can use `nc_rpc_act_generic_xml()` (that is what *netopeer2-cli* `user-rpc` is actually using). It expects an XML starting with the RPC invocation, which would be `<edit-config ...` in your case and that is always a well-formed XML as you cannot execute several RPCs at once. Note that `nc_rpc_edit()` is just a convenient interface specific for the RPC, nothing else.

Regards,
Michal

**Comment by masif-cs** [comment]
Hi,

I think I am not able to explain my problem properly. I will try once again.

Actually I want to send multiple instance or multiple modules in one RPC. Its good to send large data in one RPC instead of sending multiple RPC with small data. But my problem is libxm2 cant generate multiple modules or multiple instance at root level in one XML output. So if I add a dummy root node on my own in the XML input then sysrepo will reject because that node is not present in yang model. So if there any way libnetconf can ignore the dummy root node added in XML and process what is present inside the root node/envelope?

I am considering oven yang model given with sysrepo.

```
<root>
    <oven1 xmlns="something">
        <id>1</id>
        <temperature>100</temperature>
   </oven1>
   <oven1 xmlns="something">
        <id>2</id>
        <temperature>100</temperature>
   </oven1>
</dummy>
```

**Comment by michalvasko** [comment]
Hi,
you are right, I still do not know what exactly is the problem. Is it simply that you have the data in *libxml2* and are not able to print them without an envelope because they include several top-level nodes? Why not print each subtree separately and just concatenate the strings? *libxml2* should be able to print subtrees.

Also, *libnetconf2* cannot "ignore" any envelope nodes or what have you. That would be incorrect and confusing.

Regards,
Michal

**Comment by masif-cs** [comment]
I will try concatenating the strings. Thats a better option. Thanks
