### ISSUE TITLE
Q: disable capabilities?

### ISSUE THREAD

**Issue by iljatab** [CESNET/netopeer2#634]
Hello Michal,

Sorry for maybe trivial question but would be good to get an authoritative answer :-)

How do I disable some capabilities on netopeer2-server?
Say, "rollback-on-error" or "startup" or any other?
Could I configure this via sysrepoctl or sysrepocfg?

Thanks!

Ilja.

**Comment by michalvasko** [comment]
Hi Ilja,
we support a strict set of features for *netopeer2* because allowing to change them would add a lot of work for us. So, officially it is not possible. But, depending on the capability, some may be fairly easy to disable if you do not mind changing server code directly.

Regards,
Michal

**Comment by iljatab** [comment]
Thanks for reply!

By "disabling" capabilities I mean that netopeer2-server would simply not advertise them.
I don't expect any other internal logic changes neither in sysrepo nor in netopeer2-server.

Say, a device backend may technically not support "startup" configuration store.
In such case would be good not to advertise "startup" as capability.

Sorry, I also have another, related question:
How do I add a callback to the configuration copy procedure?
Say, netconf user does `copy-config` from `running` to `startup` - configuration gets written to regular files.
However the device might need some post-processing - say, copy startup configuration files from tmpfs to some kind of nvram.
So is there currently an API in sysrepo to add such pre-/post-processing hooks?

Ilja.

**Comment by michalvasko** [comment]
Hi Ilja,
okay, then it is even simpler but like I said, you will have to modify the server code, it does not allow configuring the capabilities.

As for your other question, this is supported but not with any special API. You are able to register several callbacks on an RPC so you are free to register your own except for the *netopeer2* one. Just note that *netopeer2* callbacks have a priority of `0` so your callback will have to use a higher priority and will be called before the *netopeer2* one, which enables it to fail without much hassle. On the other hand, if you want to be called only after the *netopeer2* callback succeeds, that is not currently possible as the `SR_EV_DONE` event is not generated unlike change subscriptions.

Regards,
Michal

**Comment by iljatab** [comment]
Thanks!
