### ISSUE TITLE
Extra Data during Call-Home

### ISSUE THREAD

**Issue by masif-cs** [CESNET/netopeer2#638]
Hi,

I want to send some extra data from server to client during call-home connection. Is there any field where I can fill that data on server side and get it in session object on client side after call-home is established?

If yes, can you please tell the api to be used to fill that data? Data which I want is the MAC ID/Serial number of server.

**Comment by michalvasko** [comment]
Hi,
no, nothing like that is supported by NETCONF. But you are free to retrieve the data separately by an RPC, for example. Server can define some `get-server-info` RPC, which the server can execute right after connecting.

Regards,
Michal
