### ISSUE TITLE
./netopeer2-server -d  ? Module "ietf-netconf" feature "writable-running" not enabled in sysrepo.

### ISSUE THREAD

**Issue by kuailedeluojie-sudo** [CESNET/netopeer2#652]
![image](https://user-images.githubusercontent.com/60098441/84647573-3164b600-af36-11ea-9e8a-9cfac6292b36.png)
[ERR]: NP: Module "ietf-netconf" feature "writable-running" not enabled in sysrepo.
[ERR]: NP: Server init failed.

**Comment by michalvasko** [comment]
Hi,
try running `make install`.

Regards,
Michal

**Comment by kuailedeluojie-sudo** [comment]
hi,
![image](https://user-images.githubusercontent.com/60098441/84652843-e0a58b00-af3e-11ea-8097-cd7962f6a616.png)
![image](https://user-images.githubusercontent.com/60098441/84652904-ff0b8680-af3e-11ea-9742-6244380a95f6.png)

**Comment by michalvasko** [comment]
Try running `make install` for *netopeer2*...

**Comment by kuailedeluojie-sudo** [comment]
![image](https://user-images.githubusercontent.com/60098441/84653105-5c9fd300-af3f-11ea-9520-b866832a4247.png)
![image](https://user-images.githubusercontent.com/60098441/84653113-63c6e100-af3f-11ea-86a5-bd59f015692a.png)

**Comment by michalvasko** [comment]
Fair enough, but this is a generic Linux issue. Run `# ldconfig` and then `make install`.

Regards,
Michal

**Comment by kuailedeluojie-sudo** [comment]
![image](https://user-images.githubusercontent.com/60098441/84653266-b0aab780-af3f-11ea-892d-da12f04c7a10.png)
It's what causes the delay in the upgrading process.

**Comment by kuailedeluojie-sudo** [comment]
> 足够公平，但这是一个通用的Linux问题。运行`# ldconfig`然后`make install`。
> 
> 问候，
> 米哈尔

thanks

**Comment by kuailedeluojie-sudo** [comment]
![image](https://user-images.githubusercontent.com/60098441/84653425-f8314380-af3f-11ea-8c13-4610e1ea9e07.png)

**Comment by michalvasko** [comment]
Because of what is says, you have some *sysrepo* applications running, you cannot have those during the installation. So, run `# make sr_clean`, reboot, then run `# make install` for *netopeer2*.

Regards,
Michal

**Comment by kuailedeluojie-sudo** [comment]
> 正因为如此，您正在运行某些_sysrepo_应用程序，因此在安装过程中无法运行这些应用程序。因此，运行`# make sr_clean`，重新启动，然后`# make install`为_netopeer2_运行。
> 
> 问候，
> 米哈尔

![image](https://user-images.githubusercontent.com/60098441/84654375-a1c50480-af41-11ea-9222-eb6bc37c087f.png)

**Comment by kuailedeluojie-sudo** [comment]
![image](https://user-images.githubusercontent.com/60098441/84654498-ddf86500-af41-11ea-8e31-291710c9ab4f.png)
after reboot.

**Comment by kuailedeluojie-sudo** [comment]
> ![图片](https://user-images.githubusercontent.com/60098441/84654498-ddf86500-af41-11ea-8e31-291710c9ab4f.png)
> 重新启动后。

**Comment by michalvasko** [comment]
Please, try to be at least a bit self-reliant. Yes, I forgot to mention that you must run `# make sr_clean` for *sysrepo*. Then this `make install` for *netopeer2* should work.

**Comment by kuailedeluojie-sudo** [comment]
> 请，至少要自力更生。是的，我忘了提到您必须`# make sr_clean`为_sysrepo_运行。然后，这`make install`对于_netopeer2_应该起作用。

OK, thank you. It's a bit urgent to contact this project for the first time. Thank you for your help.

**Comment by michalvasko** [comment]
Um, are you by any chance running Ubuntu 20.04? Because I just noticed the `permission denied` errors even when you run the installation with `sudo`. If so, then it will not work at all, there seems to be a bug of some sort on that distribution and we do not know about any solution currently.

Regards,
Michal

**Comment by kuailedeluojie-sudo** [comment]
> 嗯，您是否有机会运行Ubuntu 20.04？因为`permission denied`即使您使用进行安装，我也注意到了错误`sudo`。如果是这样，那么它将根本无法工作，该发行版上似乎存在某种错误，并且我们目前不知道任何解决方案。
> 
> 问候，
> 米哈尔

**Comment by kuailedeluojie-sudo** [comment]
Linux kali 4.19.118-Re4son-v7+ #1 SMP Wed May 6 14:25:41 AEST 2020 armv7l GNU/Linux

**Comment by michalvasko** [comment]
Okay, I suppose it should but the errors still do not make sense. You cannot get a `permission denied` error if you run a command as `root`.

**Comment by kuailedeluojie-sudo** [comment]
> Okay, I suppose it should but the errors still do not make sense. You cannot get a `permission denied` error if you run a command as `root`.

![image](https://user-images.githubusercontent.com/60098441/84655989-89a2b480-af44-11ea-9250-9f3d6c91ac64.png)

**Comment by michalvasko** [comment]
Like I said, I do not know why this happens and it seems to be a deviation from the POSIX standard. On Ubuntu 20.04 it started to work after all the files' owner was changed to the user you are logged as meaning `root` could not get access to files owned by other users. But simply changing the owner will not really help you, *netopeer2* must be executed with `root` access because it needs permissions for all the *sysrepo* files. That seems not to help in this case.

Regards,
Michal

**Comment by kuailedeluojie-sudo** [comment]
> Like I said, I do not know why this happens and it seems to be a deviation from the POSIX standard. On Ubuntu 20.04 it started to work after all the files' owner was changed to the user you are logged as meaning `root` could not get access to files owned by other users. But simply changing the owner will not really help you, _netopeer2_ must be executed with `root` access because it needs permissions for all the _sysrepo_ files. That seems not to help in this case.
> 
> Regards,
> Michal

ok，thanks。

**Comment by kuailedeluojie-sudo** [comment]
![image](https://user-images.githubusercontent.com/60098441/85188297-2b752900-b2d8-11ea-8946-9d9a0fa67fe2.png)
in ubuntu 18.04 server,why?

**Comment by koala027** [comment]
Hi kuailedeluojie-sudo, did you find the final solution for this issue, since i am puzzled it also.

**Comment by kuailedeluojie-sudo** [comment]
In fact, I have transplanted this application to my embedded device, and then I need to connect this application with my previous application and need support.

**Comment by kuailedeluojie-sudo** [comment]
> Hi kuailedeluojie-sudo, did you find the final solution for this issue, since i am puzzled it also.

In fact, I have transplanted this application to my embedded device, and then I need to connect this application with my previous application and need support.

**Comment by michalvasko** [comment]
Hi,
I hope you do not expect any support from me because we have discussed the problem extensively and you finished it with repeating the original question without any details. If so, then please express yourself better and try not to waste my time.

Regards,
Michal
