### ISSUE TITLE
notification replay fails intermittently

### ISSUE THREAD

**Issue by jkmuller** [CESNET/netopeer2#653]
Hi,

I noticed that notification replay (with `<time>` in the past) fails sometimes. The reason is that 
  https://github.com/CESNET/netopeer2/blob/d0e154aa11a6bfd1549de011284e122442f17ea4/src/netconf.c#L751
is called after
https://github.com/CESNET/netopeer2/blob/d0e154aa11a6bfd1549de011284e122442f17ea4/src/netconf.c#L727
Now, as long  `nc_session_set_notif_status()` is not called the notifications are dropped in `nc_server_notif_send()`. That is, all notifications triggered by the call to `sr_event_notif_subscribe_tree(nc_session_get_data` before the call to  `nc_session_set_notif_status()` are dropped. This is what I have seen on our test system.

The possible fix for this issue is just to move `nc_session_set_notif_status()` up before 
https://github.com/CESNET/netopeer2/blob/d0e154aa11a6bfd1549de011284e122442f17ea4/src/netconf.c#L712

Could you please fix that?

Thanks
Jens

**Comment by michalvasko** [comment]
Hi,
right, that makes sense, thanks for looking more into it. Should work now.

Regards,
Michal

**Comment by jkmuller** [comment]
Hi Michal,
Thanks a lot for the quick fix.
Regards,
Jens
