### ISSUE TITLE
<error-tag>'operation-failed' instead of 'lock-denied'

### ISSUE THREAD

**Issue by jkmuller** [CESNET/netopeer2#654]
Hi Michal et al,

when trying to `<lock>` an already locked datastore, netopeer2 replies correctly with an `<rpc-error>` message, but the `<error-tag>` element just contains '_operation-failed_' but shall be '_lock-denied_'.

When looking into the logs, netopeer2 seems to obtain the correct reason from sysrepo2

> Jun 15 15:21:12 58e962bf7514 netopeer2-server: [ERR]: SR: Requested resource already locked

but then it maps that just to the tag 'operation-failed'. Could you look at this?

Thanks and regards,
Jens

Here a longer section of the logfile:
 
> Jun 15 15:21:09 58e962bf7514 netopeer2-server[3442]: Published event "rpc" "/ietf-netconf:lock" with ID 6 priority 0 for 1 subscribers.
> Jun 15 15:21:10 58e962bf7514 netopeer2-server: [INF]: SR: Published event "rpc" "/ietf-netconf:lock" with ID 6 priority 0 for 1 subscribers.
> Jun 15 15:21:10 58e962bf7514 netopeer2-server[3442]: Processing "/ietf-netconf:lock" "rpc" event with ID 6 priority 0 (remaining 1 subscribers).
> Jun 15 15:21:10 58e962bf7514 netopeer2-server: [INF]: SR: Processing "/ietf-netconf:lock" "rpc" event with ID 6 priority 0 (remaining 1 subscribers).
> Jun 15 15:21:12 58e962bf7514 netopeer2-server[3442]: Module "yang" is locked by session 14 (NC SID 5).
> Jun 15 15:21:12 58e962bf7514 netopeer2-server[3442]: Failed processing of "rpc" event with ID 6 priority 0 (remaining 1 subscribers).
> Jun 15 15:21:12 58e962bf7514 netopeer2-server: [ERR]: SR: Module "yang" is locked by session 14 (NC SID 5).
> Jun 15 15:21:12 58e962bf7514 netopeer2-server: [INF]: SR: Failed processing of "rpc" event with ID 6 priority 0 (remaining 1 subscribers).
> Jun 15 15:21:12 58e962bf7514 netopeer2-server[3442]: Requested resource already locked
> Jun 15 15:21:12 58e962bf7514 netopeer2-server: [ERR]: SR: Requested resource already locked
> Jun 15 15:21:12 58e962bf7514 netopeer2-server[3442]: Event "rpc" with ID 6 priority 0 failed (Requested resource already locked).
> Jun 15 15:21:12 58e962bf7514 netopeer2-server: [WRN]: SR: Event "rpc" with ID 6 priority 0 failed (Requested resource already locked).
> Jun 15 15:21:12 58e962bf7514 netopeer2-server[3442]: Failed to send an RPC (User callback failed).
> Jun 15 15:21:12 58e962bf7514 netopeer2-server: [ERR]: NP: Failed to send an RPC (User callback failed).
> Jun 15 15:21:12 58e962bf7514 netopeer2-server[3442]: Session 6: thread 0 event new RPC.
> Jun 15 15:21:12 58e962bf7514 netopeer2-server: [INF]: NP: Session 6: thread 0 event new RPC.
> Jun 15 15:21:12 58e962bf7514 netopeer2-server[3442]: Session 6: thread 0 event reply error.
> Jun 15 15:21:12 58e962bf7514 netopeer2-server: [INF]: NP: Session 6: thread 0 event reply error.

**Comment by michalvasko** [comment]
Hi,
okay, should be correct now.

Regards,
Michal

**Comment by jkmuller** [comment]
Hi Michal,
thanks a lot. 
Meanwhile I saw a similiar issue with 'in-use' being reported as 'operation-failed'. Has this also been fixed with this?

Regards,
Jens

**Comment by jkmuller** [comment]
Hi,

I have retested with 2bd857b and it seems the issue is not solved: 
`<error-tag>` is still `operation-failed` instead of `lock-denied`

Regards
Jens

**Comment by jkmuller** [comment]
Same applies for `<error-tag>` = `data-exists`...

**Comment by jkmuller** [comment]
I have now create [PR#657](https://github.com/CESNET/netopeer2/pull/657) as solution proposal.
- Jens

**Comment by Sneha-star** [comment]
Hi ,
How to subscribe for lock/unlock RPC ?
Do we need to use rpc_subscribe("/ietf-netconf:lock", mycb) so that the proprietry callback (mycb) handler will also get hit ?
