### ISSUE TITLE
<unlock> on candidate datastore does not discard outstanding changes as in RFC

### ISSUE THREAD

**Issue by jkmuller** [CESNET/netopeer2#655]
Hi,

this issue refers to lock / unlock of candidate datatore. RFC says:
> https://tools.ietf.org/html/rfc6241#section-8.3.5.2
> When a client fails with outstanding changes to the candidate
>    configuration, recovery can be difficult.  To facilitate easy
>    recovery, any outstanding changes are discarded when the lock is
>    released, whether explicitly with the <unlock> operation or
>    implicitly from session failure.

The failing test sequences are:
```
    //unlock
    <lock> (target=candidate)
    <edit-config> <someleaf>sometext</someleaf>
    <unlock> (target=candidate)
    <get-config> (datastore=candidate) - assert text(<someleaf>) == ""
```

```
    // session loss
    [session1] <lock> (target=candidate)
    [session1] <edit-config> <someleaf>sometext</someleaf>
    [session1] closed
    [session2]<get-config> (datastore=candidate) - assert text(<someleaf>) == ""
```

```
    // session kill
    [session1] <lock> (target=candidate)
    [session1] <edit-config> <someleaf>sometext</someleaf>
    [session2] kill session 1 
    [session2]<get-config> (datastore=candidate) - assert text(<someleaf>) == ""
```

Btw, this all worked with legacy sysrepo / netopeer2.

Thanks and regards
Jens

**Comment by Sneha-star** [comment]
Hi Michal,

How to subscribe for lock/unlock RPC ?
Do we need to use rpc_subscribe("/ietf-netconf:lock", mycb);

**Comment by jkmuller** [comment]
Hello @michalvasko, what is your opinion about that? - Thanks Jens

**Comment by michalvasko** [comment]
Hi,
right, it just took some time until I got to this issue. With the latest *sysrepo* it should work now as suggested.

Regards,
Michal
