### ISSUE TITLE
Netopeer2-server and linux service (systemctl)

### ISSUE THREAD

**Issue by esend7881** [CESNET/netopeer2#659]
I am wanting to start netopeer2-server using `systemctl` and I am wondering if there is any guide on how to make that work properly with netopeer2-server?

**Comment by michalvasko** [comment]
Hi,
no, there is no official guide but since it is a standard daemon without any special requirements, it should not be difficult.

Regards,
Michal

**Comment by bbergquist0930** [comment]
This is what we use
```
[Unit]
Description=A NETCONF server on top of sysrepo
After=network.target sysrepo-plugind.service
StartLimitIntervalSec=0

[Service]
Type=forking
ExecStart=/usr/bin/netopeer2-server -v 1
PIDFile=/var/run/netopeer2-server.pid
PrivateTmp=yes
PrivateDevices=yes
ProtectSystem=yes
ProtectHome=yes
SystemCallArchitectures=native
Restart=always

[Install]
WantedBy=multi-user.target
```
