### ISSUE TITLE
Question: Installing a schema while netopeer2-server is running

### ISSUE THREAD

**Issue by chaichairiko** [CESNET/netopeer2#668]
I was unsure if this question is more relevant to sysrepo or netopeer:

According to the sysrepo doc:
**Before it is possible to work with any data, YANG schemas (modules) need to be installed into Sysrepo. However, such a YANG module change is not performed immediately. These changes, which also include removing, updating a module or changing its features, are only scheduled to be performed and are applied during new Sysrepo connection creation if there are no other connections.**

Maybe I am missing something very basic, but as long as netopeer2-server is running, there will always be a connection:
root@netconf:/# sysrepoctl -C
1

Thus, it is impossible to apply a change to the schema while netopeer2-server is running. Am I correct in this conclusion? I was looking for a solution in the docs/issues/any where else, but could not find one

**Comment by michalvasko** [comment]
Hi,
yes, your conclusion is absolutely correct, you cannot install YANG modules while *netopeer2* is running.

Regards,
Michal

**Comment by chaichairiko** [comment]
@michalvasko Thank you for the quick response.

Is there a proper way for updating/creating new models other than killing netopeer2?

**Comment by michalvasko** [comment]
No, you must stop *netopeer2* server to change YANG modules in any way. This is not just a made-up requirement because any changes in YANG modules (even installing new ones) can change the existing modules and if there are any data using these modules, they would get corrupted.

Regards,
Michal

**Comment by chaichairiko** [comment]
Thanks!
