### ISSUE TITLE
Extensions needed in netopeer2 similar to tailf extensions in confd

### ISSUE THREAD

**Issue by som-1981** [CESNET/netopeer2#670]
We are adding  classification of attributes whether type A, type B or type C in yang file using tailf(confd) as below:

leaf port {
type uint16;
   tailf:meta-data alertType {
        tailf:meta-value "typeA";
  }
default 2905;
  description "Port for the endpoint";
}                                                                    

How do I define the same in yang file (netopeer2/sysrepo) as we don't have tailf extensions?

**Comment by michalvasko** [comment]
Hi,
it seems like a fairly simple extension so you should be able to use these if you implement a plugin for *libyang* that will add the support. There is no other way.

Regards,
Michal
