### ISSUE TITLE
build-rpm  error: License field must be present in package: (main package)

### ISSUE THREAD

**Issue by nic1225** [CESNET/netopeer2#675]
hi,
    When compiling netopeer2-1.1.34, I used the following steps to compile the RPM package. 

    mkdir build; cd build
    cmake ..
    make build-rpm

and the error infomation as follow:

    [root@localhost build]# make build-rpm
    ./
    ./CMakeLists.txt
    ./CMakeModules/
    ./CMakeModules/FindCMocka.cmake
    ./CMakeModules/FindLibNETCONF2.cmake
    ./CMakeModules/FindLibSSH.cmake
    ./CMakeModules/FindLibYANG.cmake
    ./CMakeModules/FindSysrepo.cmake
    ./CMakeModules/UseCompat.cmake
    ./CMakeModules/uninstall.cmake
    ./CODINGSTYLE.md
    ./LICENSE
    ./README.md
    ./cli/
    ./cli/CMakeLists.txt
    ./cli/README.md
    ./cli/certs/
    ./cli/certs/ca.pem
    ./cli/certs/client.crt
    ./cli/certs/client.key
    ./cli/cli_version.h.in
    ./cli/commands.c
    ./cli/commands.h
    ./cli/completion.c
    ./cli/completion.h
    ./cli/configuration.c
    ./cli/configuration.h
    ./cli/doc/
    ./cli/doc/netopeer2-cli.1
    ./cli/linenoise/
    ./cli/linenoise/LICENSE
    ./cli/linenoise/linenoise.c
    ./cli/linenoise/linenoise.h
    ./cli/main.c
    ./cli/sample_script.sh
    ./compat/
    ./compat/compat.c
    ./compat/compat.h.in
    ./example_configuration/
    ./example_configuration/ssh_callhome.xml
    ./example_configuration/tls_callhome.xml
    ./example_configuration/tls_certs/
    ./example_configuration/tls_certs/ca.key
    ./example_configuration/tls_certs/ca.pem
    ./example_configuration/tls_certs/client.crt
    ./example_configuration/tls_certs/client.key
    ./example_configuration/tls_certs/server.crt
    ./example_configuration/tls_certs/server.key
    ./example_configuration/tls_keystore.xml
    ./example_configuration/tls_listen.xml
    ./example_configuration/tls_truststore.xml
    ./modules/
    ./modules/iana-crypt-hash@2014-08-06.yang
    ./modules/ietf-crypto-types@2019-07-02.yang
    ./modules/ietf-datastores@2017-08-17.yang
    ./modules/ietf-keystore@2019-07-02.yang
    ./modules/ietf-netconf-acm@2018-02-14.yang
    ./modules/ietf-netconf-monitoring@2010-10-04.yang
    ./modules/ietf-netconf-nmda@2019-01-07.yang
    ./modules/ietf-netconf-server@2019-07-02.yang
    ./modules/ietf-netconf@2013-09-29.yang
    ./modules/ietf-ssh-common@2019-07-02.yang
    ./modules/ietf-ssh-server@2019-07-02.yang
    ./modules/ietf-tcp-client@2019-07-02.yang
    ./modules/ietf-tcp-common@2019-07-02.yang
    ./modules/ietf-tcp-server@2019-07-02.yang
    ./modules/ietf-tls-common@2019-07-02.yang
    ./modules/ietf-tls-server@2019-07-02.yang
    ./modules/ietf-truststore@2019-07-02.yang
    ./modules/ietf-x509-cert-to-name@2014-12-10.yang
    ./modules/nc-notifications@2008-07-14.yang
    ./modules/notifications@2008-07-14.yang
    ./packages/
    ./packages/CMakeLists.txt
    ./packages/create-package.sh
    ./packages/debian.compat
    ./packages/debian.control.in
    ./packages/debian.copyright
    ./packages/debian.netopeer2.install
    ./packages/debian.postinst.in
    ./packages/debian.rules.in
    ./packages/local-deb.sh.in
    ./packages/local-rpm.sh.in
    ./packages/netopeer2.dsc.in
    ./packages/netopeer2.spec.in
    ./packages/upload-package.sh
    ./scripts/
    ./scripts/merge_config.sh
    ./scripts/merge_hostkey.sh
    ./scripts/setup.sh
    ./src/
    ./src/common.c
    ./src/common.h
    ./src/config.h.in
    ./src/log.c
    ./src/log.h
    ./src/main.c
    ./src/netconf.c
    ./src/netconf.h
    ./src/netconf_acm.c
    ./src/netconf_acm.h
    ./src/netconf_monitoring.c
    ./src/netconf_monitoring.h
    ./src/netconf_nmda.c
    ./src/netconf_nmda.h
    ./src/netconf_server.c
    ./src/netconf_server.h
    ./src/netconf_server_ssh.c
    ./src/netconf_server_ssh.h
    ./src/netconf_server_tls.c
    ./src/netconf_server_tls.h
    error: License field must be present in package: (main package)
    Built target build-rpm

**Comment by michalvasko** [comment]
Hi,
unfortunately, we are building the packages differently and this script is not used. However, we are planning some overhaul so it should be improved in future. Or you can provide a patch, if you can fix it.

Regards,
Michal

**Comment by esend7881** [comment]
> Hi,
> unfortunately, we are building the packages differently and this script is not used. However, we are planning some overhaul so it should be improved in future. Or you can provide a patch, if you can fix it.
> 
> Regards,
> Michal

I also get the license error. I assume the overhaul has not happened yet. Could you copy and paste the actual build script?

**Comment by michalvasko** [comment]
There is no [actual build script](https://build.opensuse.org/project/show/home:liberouter) available. And there will be no overhaul, at least none is planned anymore. This is just some minor problem that anyone can solve. So I would appreciate if someone or you would take a look and fix it, I do not have much experience with packaging so I would have to spend some time learning the basics first. I will keep this issue open but I simply have more important work to do.
