### ISSUE TITLE
Can't get notification from other netconf client except from netopeer2 cli.

### ISSUE THREAD

**Issue by LilyCuili** [CESNET/netopeer2#676]
Hi,
I can't get notification from other netconf client
for example:
 step1 ssh netconf@localhost -p 830 -s netconf
 step2 then send hello message:
 ```xml
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
        <capabilities>
                <capability>urn:ietf:params:netconf:base:1.0</capability>
				<capability>urn:ietf:params:netconf:capability:notification:1.0</capability>
        </capabilities>
</hello>
]]>]]>
```
step 3 send subscribe and server reply ok
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<rpc message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <create-subscription xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
    </create-subscription>
</rpc>
]]>]]>
```
step 4 use sysrepocfg --notification=/home/sdn/notification.xml
from netopeer cli,after subscribe,I can get the notification;
but from ssh client,I can't get the notification
from odl netconf client I can't get the notification either.

can you help me to find the reason?

**Comment by michalvasko** [comment]
Hi,
did you check *netopeer2* output? Try running it with `-d -v2`. Also, it is difficult to use `ssh(1)` and NETCONF correctly, so I would advise against that.

Regards,
Michal

**Comment by LilyCuili** [comment]
Hi,
Michal,I connect using ssh client or odl client and then I can't recieve the notification.Below is the log,after send sysrepocfg --notification=/home/sdn/upgrade_noti.xml ,there are some error logs.

root@sdns:/home/sdn# [INF]: LN: Accepted a connection on 0.0.0.0:830.
[INF]: SR: Session 3 (user "root") created.
[2020/07/15 00:59:20.835504, 2] ssh_pki_import_privkey_base64:  Trying to decode privkey passphrase=false
[2020/07/15 00:59:20.838710, 1] ssh_server_connection_callback:  SSH client banner: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
[2020/07/15 00:59:20.838747, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
[2020/07/15 00:59:20.838764, 1] ssh_analyze_banner:  We are talking to an OpenSSH client version: 7.6 (70600)
[2020/07/15 00:59:20.864335, 2] ssh_server_curve25519_init:  SSH_MSG_KEX_ECDH_REPLY sent
[2020/07/15 00:59:20.864402, 2] ssh_server_curve25519_init:  SSH_MSG_NEWKEYS sent
[2020/07/15 00:59:20.869008, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
[INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: LN: Received an SSH message "request-auth" of subtype "none".
[INF]: LN: Received an SSH message "request-auth" of subtype "interactive".
[2020/07/15 00:59:20.870138, 2] ssh_message_auth_interactive_request:  Warning: Got a keyboard-interactive response but it seems we didn't send the request.
[INF]: LN: Received an SSH message "request-auth" of subtype "interactive".
[INF]: LN: User "netconf" authenticated.
[INF]: LN: Received an SSH message "request-channel-open" of subtype "session".
[INF]: LN: Received an SSH message "request-channel" of subtype "env".
[INF]: LN: Received an SSH message "request-channel" of subtype "subsystem".
[2020/07/15 00:59:34.086732, 2] grow_window:  growing window (channel 43:0) to 1280000 bytes
[INF]: SR: Session 4 (user "root") created.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-start).
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" "/notifications:create-subscription" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/notifications:create-subscription" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: SR: Successful processing of "rpc" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 1 priority 0 succeeded.
[INF]: NP: Session 1: thread 0 event new RPC.
[INF]: LN: Accepted a connection on 0.0.0.0:830.
[INF]: SR: Session 5 (user "root") created.
[2020/07/15 00:59:48.219999, 2] ssh_pki_import_privkey_base64:  Trying to decode privkey passphrase=false
[2020/07/15 00:59:48.222509, 1] ssh_server_connection_callback:  SSH client banner: SSH-2.0-APACHE-SSHD-2.2.0
[2020/07/15 00:59:48.222573, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-APACHE-SSHD-2.2.0
[2020/07/15 00:59:48.246154, 2] ssh_server_ecdh_init:  SSH_MSG_KEXDH_REPLY sent
[2020/07/15 00:59:48.246264, 2] ssh_server_ecdh_init:  SSH_MSG_NEWKEYS sent
[2020/07/15 00:59:48.254784, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
[INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: LN: Received an SSH message "request-auth" of subtype "none".
[INF]: LN: Received an SSH message "request-auth" of subtype "interactive".
[2020/07/15 00:59:48.298597, 2] ssh_message_auth_interactive_request:  Warning: Got a keyboard-interactive response but it seems we didn't send the request.
[INF]: LN: Received an SSH message "request-auth" of subtype "interactive".
[INF]: LN: User "netconf" authenticated.
[INF]: LN: Received an SSH message "request-channel-open" of subtype "session".
[INF]: LN: Received an SSH message "request-channel" of subtype "subsystem".
[2020/07/15 00:59:48.308721, 2] grow_window:  growing window (channel 43:0) to 1280000 bytes
[INF]: SR: Session 6 (user "root") created.
[INF]: SR: Published event "notif" "ietf-netconf-notifications" with ID 1 priority 0 for 1 subscribers.
[INF]: NP: Generated new event (netconf-session-start).
[INF]: SR: Processing "notif" "ietf-netconf-notifications" event with ID 1.
[INF]: SR: Successful processing of "notif" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" "/notifications:create-subscription" with ID 2 priority 0 for 1 subscribers.
[INF]: SR: Processing "/notifications:create-subscription" "rpc" event with ID 2 priority 0 (remaining 1 subscribers).
[ERR]: LN: Session 1: failed to write notification (would block).
[ERR]: NP: Sending a notification to session 1 timed out.
[INF]: SR: Successful processing of "rpc" event with ID 2 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 2 priority 0 succeeded.
[INF]: NP: Session 2: thread 3 event new RPC.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" "/ietf-netconf:get" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:get" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: SR: Published event "operational" "/ietf-netconf-monitoring:netconf-state" with ID 1.
[INF]: SR: Processing "ietf-netconf-monitoring" "operational" event with ID 1.
[INF]: SR: Successful processing of "operational" event with ID 1.
[INF]: SR: Event "operational" with ID 1 succeeded.
[INF]: SR: Successful processing of "rpc" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 1 priority 0 succeeded.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: NP: Session 2: thread 3 event new RPC.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" "/ietf-netconf:get" with ID 2 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:get" "rpc" event with ID 2 priority 0 (remaining 1 subscribers).
[INF]: SR: Successful processing of "rpc" event with ID 2 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 2 priority 0 succeeded.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: NP: Session 2: thread 4 event new RPC.

root@sdns:/home/sdn#
root@sdns:/home/sdn#
root@sdns:/home/sdn#
root@sdns:/home/sdn# sysrepocfg --notification=/home/sdn/upgrade_noti.xml
[INF]: SR: Processing "notif" "netconf-upgrade" event with ID 1.
[INF]: SR: Successful processing of "notif" event with ID 1 priority 0 (remaining 0 subscribers).
root@sdns:/home/sdn# [ERR]: LN: Session 1: **failed to write notification** (would block).
[ERR]: NP: **Sending a notification to session 1 timed out.**

root@sdns:/home/sdn#
root@sdns:/home/sdn# [ERR]: LN: Session 1: inactive read timeout elapsed.
[INF]: NP: Session 1: thread 0 event session terminated.
[INF]: SR: Published event "notif" "ietf-netconf-notifications" with ID 2 priority 0 for 1 subscribers.
[INF]: NP: Generated new event (netconf-session-end).
[INF]: SR: Processing "notif" "ietf-netconf-notifications" event with ID 2.
[INF]: SR: Successful processing of "notif" event with ID 2 priority 0 (remaining 0 subscribers).

**Comment by michalvasko** [comment]
Hi,
okay, I made the effort of debugging this but it turns out I was right in my first reply. I have not tried the ODL client but it seems it is not sending correct NETCONF messages, I can illustrate with `ssh(1)` although I have already explained this several times.

When you connect, you receive the hello message and send yours. However, you can only send a message by writing the XML manually and __finish it with a newline__, otherwise the message is not sent. However, that last newline is not a part of a NETCONF message so *netopeer2* (*libnetconf2*) thinks that you are sending another message. Unless you finish the message in 20s by default, you get disconnected with an error that inactive read timeout elapsed, this is the reason. However, if you manage to subscribe and receive a notification until then, you see the `would block` error. The reason being that *netopeer2* is still waiting for you to finish writing the previous message (which you started by the spare newline) and so it is holding a lock on that session.

So, there is nothing for us to fix.

Regards,
Michal

**Comment by LilyCuili** [comment]
Hi Michal，
the question you mentioned I have met sometime.now I know the reason.
This time When I send hello and then send subscribe,got the rpc reply ok,so it seems that the hello works.
But from the client can't get the notification,and some seconds later,the ssh client broke.

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<rpc message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
    <create-subscription xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
    </create-subscription>
</rpc>
]]>]]>
<rpc-reply message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><ok/></rpc-reply>]]>]]>r

[INF]: LN: Accepted a connection on 0.0.0.0:830.
[INF]: SR: Session 3 (user "root") created.
[2020/07/15 08:10:11.898206, 2] ssh_pki_import_privkey_base64:  Trying to decode privkey passphrase=false
[2020/07/15 08:10:11.902472, 1] ssh_server_connection_callback:  SSH client banner: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
[2020/07/15 08:10:11.902522, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
[2020/07/15 08:10:11.902553, 1] ssh_analyze_banner:  We are talking to an OpenSSH client version: 7.6 (70600)
[2020/07/15 08:10:11.923175, 2] ssh_server_curve25519_init:  SSH_MSG_KEX_ECDH_REPLY sent
[2020/07/15 08:10:11.925449, 2] ssh_server_curve25519_init:  SSH_MSG_NEWKEYS sent
[2020/07/15 08:10:11.929766, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
[INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: LN: Received an SSH message "request-auth" of subtype "none".
[INF]: LN: Received an SSH message "request-auth" of subtype "interactive".
[2020/07/15 08:10:11.970697, 2] ssh_message_auth_interactive_request:  Warning: Got a keyboard-interactive response but it seems we didn't send the request.
[INF]: LN: Received an SSH message "request-auth" of subtype "interactive".
[INF]: LN: User "raisecom" authenticated.
[INF]: LN: Received an SSH message "request-channel-open" of subtype "session".
[INF]: LN: Received an SSH message "request-channel" of subtype "env".
[INF]: LN: Received an SSH message "request-channel" of subtype "subsystem".
[2020/07/15 08:10:26.603966, 2] grow_window:  growing window (channel 43:0) to 1280000 bytes
[INF]: SR: Session 4 (user "root") created.
[INF]: SR: Replay file "ietf-netconf-notifications.notif.1594777274-1594800482" renamed to "ietf-netconf-notifications.notif.1594777274-1594800627".
[INF]: SR: Notification "netconf-session-start" stored for replay.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-start).
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" "/notifications:create-subscription" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/notifications:create-subscription" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: SR: Successful processing of "rpc" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 1 priority 0 succeeded.
[INF]: NP: Session 1: thread 1 event new RPC.

root@sdns:/home/sdn# sysrepocfg --notification=/home/sdn/upgrade_noti.xml
**[INF]: SR: Processing "notif" "raisecom-upgrade" event with ID 1.
[INF]: SR: Successful processing of "notif" event with ID 1 priority 0 (remaining 0 subscribers).**
root@sdns:/home/sdn#
root@sdns:/home/sdn#
root@sdns:/home/sdn#
root@sdns:/home/sdn#
root@sdns:/home/sdn# sysrepocfg --notification=/home/sdn/upgrade_noti.xml
**[INF]: SR: Processing "notif" "raisecom-upgrade" event with ID 2.
[INF]: SR: Successful processing of "notif" event with ID 2 priority 0 (remaining 0 subscribers).**
root@sdns:/home/sdn# [ERR]: LN: Session 1: inactive read timeout elapsed.
[INF]: NP: Session 1: thread 1 event session terminated.
[INF]: SR: Replay file "ietf-netconf-notifications.notif.1594777274-1594800627" renamed to "ietf-netconf-notifications.notif.1594777274-1594800659".
[INF]: SR: Notification "netconf-session-end" stored for replay.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-end).

**Comment by michalvasko** [comment]
Hi,
I have nothing new to tell you, I have mentioned everything that fully explains this behavior.

Regards,
Michal

**Comment by LilyCuili** [comment]
Change another way to verify why can‘t recieve the notification，close this issue’
