### ISSUE TITLE
 How to solve this problem?

### ISSUE THREAD

**Issue by kuailedeluojie-sudo** [CESNET/netopeer2#679]
[ERR]: NP: Module "ietf-netconf" feature "writable-running" not enabled in sysrepo.
[ERR]: NP: Server init failed.
![image](https://user-images.githubusercontent.com/60098441/87924343-5908ea00-cab1-11ea-9213-7cc440e8c12e.png)

**Comment by tonynii** [comment]
sysrepoctl -e writable-running -c ietf-netconf

**Comment by kuailedeluojie-sudo** [comment]
[ERR]: Failed to open "/sr_yang.operational" (No such file or directory).

**Comment by kuailedeluojie-sudo** [comment]
[ERR]: NP: Module "ietf-netconf" feature "candidate" not enabled in sysrepo.
[ERR]: NP: Server init failed.

**Comment by tonynii** [comment]
sysrepoctl -e candidate -c ietf-netconf
sysrepoctl -e rollback-on-error -c ietf-netconf
sysrepoctl -e validate -c ietf-netconf
sysrepoctl -e startup -c ietf-netconf
sysrepoctl -e xpath -c ietf-netconf
sysrepoctl -e url -c ietf-netconf

**Comment by kuailedeluojie-sudo** [comment]
[ERR]: NP: Module "ietf-netconf-acm" not implemented in sysrepo.
[ERR]: NP: Server init failed.

**Comment by kuailedeluojie-sudo** [comment]
[ERR]: NP: Subscribing for "/ietf-netconf-nmda:get-data" RPC failed (Item not found).
[ERR]: NP: Server RPC subscribe failed.

**Comment by kuailedeluojie-sudo** [comment]
[ERR]: NP: Subscribing for providing "ietf-netconf-monitoring" state data failed (Invalid argument).
[ERR]: NP: Server data subscribe failed.

**Comment by michalvasko** [comment]
Please stop asking the same question over, I have told you several times you are getting this error because you have not executed *netopeer2* install scripts (normally just `# make install`). It is up to you to figure this out if you have a complex environment and are doing cross-compilation.

Regards,
Michal

**Comment by kuailedeluojie-sudo** [comment]
> 请不要再问相同的问题，我已经多次告诉您您收到此错误，因为您尚未执行_netopeer2_安装脚本（通常只是`# make install`）。如果您有复杂的环境并且正在进行交叉编译，则由您自己确定。
> 
> 问候，
> 米哈尔



> Please stop asking the same question over, I have told you several times you are getting this error because you have not executed _netopeer2_ install scripts (normally just `# make install`). It is up to you to figure this out if you have a complex environment and are doing cross-compilation.
> 
> Regards,
> Michal

thank you!

**Comment by Karl-ZhangBD** [comment]
Please tell me, I have this problem and how to solve it。

root@s32g399ardb3:/home/karl/netopeer2-server -d -v3
[INF]: SR: Connection 21 created.
[INF]: SR: Session 10 (user "root", CID 21) created.
[ERR]: NP: Module "ietf-netconf-monitoring" not implemented in sysrepo.
[ERR]: NP: Server init failed.
[INF]: NP: Server terminated.


> > 请不要再问相同的问题，我已经多次告诉您您收到此错误，因为您尚未执行_netopeer2_安装脚本（通常只是`# make install`）。如果您有复杂的环境并且正在进行交叉编译，则由您自己确定。
> > 问候，
> > 米哈尔
> 
> > Please stop asking the same question over, I have told you several times you are getting this error because you have not executed _netopeer2_ install scripts (normally just `# make install`). It is up to you to figure this out if you have a complex environment and are doing cross-compilation.
> > Regards,
> > Michal
> 
> thank you!
