### ISSUE TITLE
Failed SSH autentication prevents further logins

### ISSUE THREAD

**Issue by jktjkt** [CESNET/Netopeer2#68]
- start netopeer2-server
- start the CLI
- try connecting, but with wrong password:
```
> connect --ssh --login root --port 830 --host dev-f25
Interactive SSH Authentication
Type your password:
Password:                               [type some garbage here]
root@dev-f25 password:        [another garbage]
nc ERROR: Unable to authenticate to the remote server (no supported authentication methods left).
cmd_connect: Connecting to the dev-f25:830 as user "root" failed.
```
This is in server's logs:
```
netopeer2-server[4261]: Accepted a connection on 0.0.0.0:830.
[2016/11/24 15:48:22.064422, 1] ssh_server_connection_callback:  SSH client banner: SSH-2.0-libssh-0.7.3
[2016/11/24 15:48:22.064561, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-libssh-0.7.3
[2016/11/24 15:48:22.111234, 2] ssh_server_curve25519_init:  SSH_MSG_KEX_ECDH_REPLY sent
[2016/11/24 15:48:22.111404, 2] ssh_server_curve25519_init:  SSH_MSG_NEWKEYS sent
[2016/11/24 15:48:22.113811, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
netopeer2-server[4261]: Received an SSH message "request-service" of subtype "ssh-userauth".
netopeer2-server[4261]: Received an SSH message "request-auth" of subtype "none".
netopeer2-server[4261]: Received an SSH message "request-auth" of subtype "interactive".
[2016/11/24 15:48:22.116128, 2] ssh_message_auth_interactive_request:  Warning: Got a keyboard-interactive response but it seems we didn't send the request.
netopeer2-server[4261]: Received an SSH message "request-auth" of subtype "interactive".
netopeer2-server[4261]: Failed user "root" authentication attempt (#1).
netopeer2-server[4261]: Received an SSH message "request-auth" of subtype "password".
netopeer2-server[4261]: Failed user "root" authentication attempt (#2).
[2016/11/24 15:48:24.068822, 1] ssh_packet_disconnect_callback:  Received SSH_MSG_DISCONNECT: 11:Bye Bye
```
- After that, I cannot connect to the server anymore, the CLI says:
```
nc ERROR: SSH connect timeout.
cmd_connect: Connecting to the dev-f25:830 as user "root" failed.
```
It seems that there's only one thread which accepts the incoming requests, and that thread waits until a timeout even though the CLI is already gone, because this is what gets shown in the server's log after a while:

```
netopeer2-server[4264]: Client failed to authenticate for too long, disconnecting.
netopeer2-server[4264]: Accepted a connection on 0.0.0.0:830.
[2016/11/24 15:51:38.646052, 1] ssh_socket_exception_callback:  Socket exception callback: 1 (0)
[2016/11/24 15:51:38.646142, 1] ssh_socket_exception_callback:  Socket error: disconnected
netopeer2-server[4264]: SSH key exchange error (Socket error: disconnected).
```

I guess that the first line is the client which used wrong PW, and the second one is my second connection which "failed to connect".

**Comment by michalvasko** [comment]
Hi,
this is actually a feature and not a bug :) After failing to authenticate the client disconnects, which leaves the socket on server-side in `TIME_WAIT` state. What that means is well explained [here](https://vincent.bernat.im/en/blog/2014-tcp-time-wait-state-linux.html). Long story short, to solve this we need to change the thread architecture of **netopeer2-server**, which was discussed in #6 and #7. I will look into it once the server configuration is finished, several weeks I presume.

Regrads,
Michal

**Comment by vishalwc** [comment]
limitation of thread waits until a timeout for next session has been worked out in devel branch    

does it mean we can create connect session with timeout periodicity and check the number of session ?

**Comment by michalvasko** [comment]
Hi,
I started working on it yesterday, so hopefully some time next week it will be implemented.

Regards,
Michal

**Comment by michalvasko** [comment]
Hi,
I have forgotten about the issue, has been fixed for some months I believe.

Regards,
Michal

**Comment by naveenchaubey** [comment]
Hi 
Above mentioned feature has been implemented or not? I'm having same problem.

**Comment by michalvasko** [comment]
Hi,
yes, it should be. Are you using most recent *sysrepo* version from either `devel` or `master`?

Regards,
Michal

**Comment by naveenchaubey** [comment]
Hi Michal,
  Im using the master branch. Checkout  2 days before.

**Comment by naveenchaubey** [comment]
I have taken master latest branch 3 days before. Also i have created one thread for this #301. Please do check the logs.
