### ISSUE TITLE
netopeer2 v1.1.39 release depend?

### ISSUE THREAD

**Issue by ivor911** [CESNET/netopeer2#681]
In [netopeer2 release page](https://github.com/CESNET/Netopeer2/releases), says v1.1.39 depends on libyang (v1.0.174), libnetconf2 (v1.1.26) and sysrepo (v1.4.70).
But I can not find [libyang v1.0.174](https://github.com/CESNET/libyang/releases/tag/v1.0.174), only [v1.0.184](https://github.com/CESNET/libyang/releases/tag/v1.0.184) existed. Is it a typo?

**Comment by rkrejci** [comment]
yes, it is a typo. Thanks! Fixed.
