### ISSUE TITLE
Sysrepo reports events out-of-order

### ISSUE THREAD

**Issue by igortern** [CESNET/netopeer2#688]
Hi,

I'm still using
- libyang-1.0.176
- sysrepo-1.4.66
- netopeer2-1.1.34

In the attached script object /ietf-interface:interfaces/interface[name='vAni_ont1'] is created in line 687, BEFORE object /xpongemtcont:tconts/tcont[name='tcont_ont1'] that refers to the interface above (line 824). 
However, when sysrepo reports events, creation of the 'tcont' is reported before the interface. It creates a problem for the underlying implementation because it tries to resolve the reference that doesn't exist yet.

Question: is it possible to force sysrepo report events in the same order as they appear in EDIT_CONFIG/COPY_CONFIG messages? Baring that, is it possible to force SYSREPO to report events in such an order that would ensure that all references are resolved?

Thank you and regards,
Igor
[bbwf-2019_demo-complete-v4.zip](https://github.com/CESNET/netopeer2/files/5005477/bbwf-2019_demo-complete-v4.zip)

**Comment by michalvasko** [comment]
Hi,
the order of changes being applied as far as YANG modules are concerned should be preserved as it is in the `edit-config` so it is a bug if it's not. Could you please provide all the YANG modules used so that I can easily try it out? Best to just attach your whole `repository/yang` directory.

Regards,
Michal

**Comment by igortern** [comment]
Attached.
Regards,
Igor
[sysrepo.tar.gz](https://github.com/CESNET/netopeer2/files/5005526/sysrepo.tar.gz)

**Comment by igortern** [comment]
Here is a netooper2 log. Note that xpongemtcont events are published before interface.

Regards,
Igor

[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" "/ietf-netconf:edit-config" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: NP: edit-config test-option "set" not supported, validation will be performed.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[WRN]: LY: Augmentations from modules "bbf-xpon" and "bbf-ghn" have fatal hash collision.
[WRN]: LY: It will cause no errors if module "bbf-xpon" is always loaded before "bbf-ghn".
[INF]: SR: Published event "change" "ietf-hardware" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Event "change" with ID 1 priority 0 succeeded.
[INF]: SR: Published event "change" "bbf-l2-dhcpv4-relay" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Event "change" with ID 1 priority 0 succeeded.
[INF]: SR: Published event "change" "bbf-qos-classifiers" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Event "change" with ID 1 priority 0 succeeded.
[INF]: SR: Published event "change" "bbf-qos-policies" with ID 1 priority 0 for 2 subscribers.
[INF]: SR: Event "change" with ID 1 priority 0 succeeded.
[INF]: SR: There are no subscribers for changes of the module "ietf-interfaces" in running DS.
[INF]: SR: Published event "change" "bbf-xpongemtcont" with ID 1 priority 0 for 3 subscribers.
[ERR]: SR: tcont tcont_ont1 references v-ani vAni_ont1 which doesn't exist

**Comment by igortern** [comment]
Hi Michal,
Please ignore this issue, my fault. Looking in the log that I've just attached, I see that there is no subscription for ietf-interfaces, that's why the events are not reported.
Apologies for the false alarm.
Regards,
Igor
