### ISSUE TITLE
Cross-Compilation of Netopeer2

### ISSUE THREAD

**Issue by jeffreymarius** [CESNET/netopeer2#692]
Hi Michal,
Could you please let me know the procedure to cross-compile netopeer2/sysrepo/libyang/libnetconf and their dependencies for ARM ?

I did see a support for buildroot in this ticket https://github.com/CESNET/Netopeer2/issues/374 but I dont see how to clone this and make use of it. Your help is highly appreciated

Thank You.

**Comment by michalvasko** [comment]
Hi,
I am sorry but I am not able to help as I have no practical experience with cross-compilation. But you should be able to find similar issues here. Just note that cross-compilation is quite complex and we do not have any official support for it.

Regards,
Michal

**Comment by jeffreymarius** [comment]
ok thank you.

**Comment by jeffreymarius** [comment]
The cross compilation of Netopeer2 server and other dependencies are pretty smooth.  I have been able to generate libs and binaries for ARM 64.

Netopeer2-Server:
CXX=/usr/bin/aarch64-linux-gnu-g++ CC=/usr/bin/aarch64-linux-gnu-gcc cmake -DINSTALL_MODULES=ON -DGENERATE_HOSTKEY=ON -DMERGE_LISTEN_CONFIG=ON -DCMAKE_INSTALL_PREFIX=/usr/aarch64-linux-gnu  ..

Of course there some changes to be made in FindLibNETCONF2.cmake, FindLibSSH.cmake, FindLibYANG.cmake, FindSysrepo.cmake of find_path() and find_library() to point to the place where the Cross-compiled libraries are present. For example, in FindLibNETCONF2.cmake it should be changed as such.
 ```
   find_path(LIBNETCONF2_INCLUDE_DIR
        NAMES
        nc_client.h
        nc_server.h
        PATHS
        /usr/aarch64-linux-gnu/include/libnetconf2/
    )

    find_library(LIBNETCONF2_LIBRARY
        NAMES
        netconf2
        libnetconf2
        PATHS
        /usr/aarch64-linux-gnu/lib
    )
```

Also, a new module FindOpenSSL.cmake must be created and the following simple find_path() & find_library() will find the Cross-compiled OpenSSL Lib and headers.
```
include(FindPackageHandleStandardArgs)
    find_path(OPENSSL_INCLUDE_DIR
        NAMES
        openssl/ssl.h
        PATHS /usr/aarch64-linux-gnu/include NO_DEFAULT_PATH
    )

    find_library(OPENSSL_LIBRARIES
        NAMES
        libcrypto.so
        PATHS /usr/aarch64-linux-gnu/lib NO_DEFAULT_PATH
    )
```


The above same method can be followed for Sysrepo, LibYang, libnetconf2 and other dependecies like libssh. 

Hope this helps someone!!!

**Comment by michalvasko** [comment]
Hi,
you should not need to change any CMake modules, you can provide the paths to your libraries as a CMake variable.

**Comment by jeffreymarius** [comment]
Hi michal,
I think I tried that but it didn't work, particularly Openssl was causing issue. Openssl does not have the "FindXXX.cmake" file like we have sysrepo,netconf and yang libraries so when searching for Openssl eventhough I give the place where my library is it always ends up with the default /usr/lib. That is when I figured that we need a separate CMake for Openssl and also to mention "NO_DEFAULT_PATH" so that Cmake doesn't search in the Host system's default path.

And also, we need to have a separate file called "DefineOptions.cmake" to include Options for  paths to our libraries.

Thanks.

**Comment by michalvasko** [comment]
Hi,
as for `FindOpenSSL.cmake`, it is a module just like ours except it is shipped with `cmake`. In it I have found
```
Hints
^^^^^

Set ``OPENSSL_ROOT_DIR`` to the root directory of an OpenSSL installation.
Set ``OPENSSL_USE_STATIC_LIBS`` to ``TRUE`` to look for static libraries.
Set ``OPENSSL_MSVC_STATIC_RT`` set ``TRUE`` to choose the MT version of the lib.
```
so you should be fine with setting specific `OPENSSL_ROOT_DIR`.

Regarding `DefineOptions.cmake`, I do not know what exactly you want to use it for but every well-written cmake module should always take into consideration some standard paths. More in the cmake [docs](https://cmake.org/cmake/help/v3.0/command/find_path.html).

Regards,
Michal
