### ISSUE TITLE
netopeer2-server can save custom data without custom module running.

### ISSUE THREAD

**Issue by ryanking8215** [CESNET/netopeer2#693]
I am using netopeer2-server 1.1.34

I had installed a custom yang. My application is not running, once the netconf client write-config and commit, netopeer2-server will save the data to running datastore. 

I wonder why netopeer2-server can save data without my application verifying?

**Comment by michalvasko** [comment]
Hi,
*netopeer2* completely relies on *sysrepo* in this aspect so I have answered in sysrepo/sysrepo#2081.

Regards,
Michal
