### ISSUE TITLE
Data provider subscription for "ietf-netconf-monitoring" on "/ietf-netconf-monitoring:netconf-state" already exists.

### ISSUE THREAD

**Issue by robbynet** [CESNET/netopeer2#696]
Hello,
Netopeer2 1.1.39 is used with  libyang (v1.0.184), libnetconf2 (v1.1.26) and sysrepo (v1.4.70).
We would like to have /netconf-state/capabilities/... extended with application modules
So our application subcribes for operational data using this call 
    rc = sr_oper_get_items_subscribe(orusw.sr_sess, mod_name, xpath, cb, NULL, SR_SUBSCR_OPER_MERGE, &orusw.sr_data_sub); 
where 
- mod_name = "ietf-netconf-monitoring"
- xpath = "/ietf-netconf-monitoring:netconf-state"

Then application is started first without error ( so subscription is well understood by sysrepo ) 
But then, we have the following failure when Netopeere2 server is started : 
[INF]: LY: Module "o-ran-test-fm@2020-07-07" successfully parsed as implemented.
[INF]: LY: Module "ietf-ssh-common@2019-07-02" now implemented.
[INF]: SR: Session 26 (user "root") created.
[INF]: SR: Ext SHM was defragmented and 4328 B were saved.
[ERR]: SR: Data provider subscription for "ietf-netconf-monitoring" on "/ietf-netconf-monitoring:netconf-state" already exists.
[ERR]: NP: Subscribing for providing "ietf-netconf-monitoring" state data failed (Invalid argument).
[ERR]: NP: Server data subscribe failed.
[INF]: NP: Server terminated.
[INF]: SR: Ext SHM was defragmented and 5208 B were saved.

It seems that only one sysrepo client can subscribe to "/ietf-netconf-monitoring:netconf-state", even if we can read in some documentation that multi operational subscription to a given module is supported.
=> Maybe there is a special combination of option to use at sysrepo subscription level  ( here we only use SR_SUBSCR_OPER_MERGE ) ?

Note that is we start Netopeer2 server first, there is no issue, but then same error is raised in our application when started after Netopper2 server.

**Comment by michalvasko** [comment]
You cannot subscribe to the same XPath twice because the data would get overwritten anyway (*netopeer2* subscription is not using the merge flag). So, your use-case is not really supported and you would have to 1) modify *netopeer2* code so that it uses the merge flag and 2) create a nested subscription for `/netconf-state/capabilities` so that *sysrepo* does not complain about XPath duplicity.

**Comment by robbynet** [comment]
Thanks for your support. At the end, as netopeer2 needs to be modified, it looks like to me more straightforward to extend this [part ](https://github.com/CESNET/netopeer2/blob/master/src/main.c#L674) with application specific module by adding call to nc_server_set_capability()..

**Comment by robbynet** [comment]
Thanks for your support. At the end, as netopeer2 needs to be modified, it looks like to me more straightforward to extend this [part ](https://github.com/CESNET/netopeer2/blob/master/src/main.c#L674) with application specific module by adding call to nc_server_set_capability()..
