### ISSUE TITLE
netopeer2-server occurs bus error.

### ISSUE THREAD

**Issue by rydy** [CESNET/netopeer2#697]
Hi Michal,

    I used the 'subscribe' command of the 'netopeer2-cli/server' tool to test the custom sysrepo plugin,  Netopeer2-server  bus error occurred when I using the 'subscribe' command, Can you give me some advice?

   third party version:
     (netopeer2-1.1.39、libyang-1.0.184、libnetconf2-1.1.26 and sysrepo-1.4.70) .

   netopeer2-cli log:
       > subscribe --filter-xpath /o-ran-software-management:download-event
        nc ERROR: Session 1: SSH channel poll error (Socket error: disconnected).
       cli_send_recv: Failed to receive a reply.

    netopeer2-server log:
        [INF]: LY: Resolving unresolved data nodes and their constraints...
	[INF]: LY: All data nodes and constraints resolved.
	[INF]: LY: Resolving unresolved data nodes and their constraints...
	[INF]: LY: All data nodes and constraints resolved.
	[INF]: SR: Published event "rpc" "/notifications:create-subscription" with ID 1 priority 0 for 1 subscribers.
	[INF]: SR: Processing "/notifications:create-subscription" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
	Bus error

Thanks,
Best regards.
Reid

**Comment by michalvasko** [comment]
Hi,
I do not think I can help you based on this information. Do you think you could provide output when running *netopeer2-server* with `valgrind`?

**Comment by rydy** [comment]
thank you for your reply,  I'm trying to delete 'sr_module_change_subscribe',, that doesn't happen，Is there a problem with the following code?


//subscribe for ietf-interfaces module changes - also causes startup ietf-interfaces data to be copied into running and enabling the module
    rc = sr_module_change_subscribe(session
          , "ietf-interfaces"
          , NULL
         , o_ran_interface_config_change_cb
         , NULL
         , 0
         , SR_SUBSCR_ENABLED | SR_SUBSCR_DONE_ONLY
        , &subscription);
    if (rc != SR_ERR_OK) {
        goto error;
    }


.......
static int o_ran_interface_config_change_cb(sr_session_ctx_t *session
	, const char *module_name
	, const char *xpath
	, sr_event_t event
	, uint32_t request_id
	, void *private_data)
{
	SRP_LOG_DBGMSG("O-RAN-INTERFACE: o_ran_interface_config_change_cb handling...");
        return SR_ERR_OK;
}

**Comment by michalvasko** [comment]
Hi,
firstly, the comment in the code is outdated and not true for the current *sysrepo*, `running` subscriptions do not cause data to be copied from `startup` to `running` but instead for data in `running` to appear in `operational`. Just a note.

Secondly, your code seems okay and it is not the reason for the error, your code is not even executed then. But the error is a weird one so my guess is that you have some incompatibilities in your libraries. Did you update something before? You can try running `# make sr_clean` for *sysrepo*, then `make uninstall` for all the projects (*libyang*, *sysrepo*, *libnetconf2*, and *netopeer2*), and then reinstalling it all again.

**Comment by rydy** [comment]
Though I reinstalled all the projects, this problem also exists, this happens after I install o-ran-sync.yang(sysrepoctl -i), if  the o-ran-sync.yang is not installed,  the problem will not appear.

kernel log as follows:
Aug  2 11:11:46 sysinit: Starting netopeer2-server: OK
	root@OpenWrt:~# cat /var/log/messages | grep netopeer*
	Aug  2 11:11:46 sysinit: Starting netopeer2-server: OK
	Aug  2 11:23:09 kernel: [  728.615362] netopeer2-serve[3560]: unhandled level 3 translation fault (7) at 0x7f88ad5000, esr 0x92000047, in libpthread-2.26.so[7f8c2e8000+18000]
	Aug  2 11:23:09 kernel: [  728.615382] CPU: 2 PID: 3560 Comm: netopeer2-serve Not tainted 4.14.0 #44

**Comment by michalvasko** [comment]
Hi,
seeing that you are using OpenWRT, the problem will likely be specific to this platform and so I have limited options of debugging it. In other words, you would have to provide much more information for me to be able to even attempt to fix this.

**Comment by rydy** [comment]
Hi, The use of *_subscribe interfaces. Is there a problem with the following code?

   //subscribe for providing the operational data(software-inventory)
    rc = sr_oper_get_items_subscribe(session
    , "o-ran-software-management"
    , "/o-ran-software-management:software-inventory/software-slot"
    , get_software_inventory_cb
    , NULL
    , SR_SUBSCR_DEFAULT
    , &subscription);
    if (rc != SR_ERR_OK) {
		goto error;
    }
    //subscribe for software-download RPC calls
    rc = sr_rpc_subscribe(session
    , "/o-ran-software-management:software-download"
    , rpc_software_download_cb
    , NULL
    , 0
    , SR_SUBSCR_CTX_REUSE
    , &subscription);
    if (rc != SR_ERR_OK) {
        goto error;
    }
    //subscribe for rpc_software_install_cb RPC calls
    rc = sr_rpc_subscribe(session
    , "/o-ran-software-management:software-install"
    , rpc_software_install_cb
    , NULL
    , 0
    , SR_SUBSCR_CTX_REUSE
    , &subscription);
    if (rc != SR_ERR_OK) {
        goto error;
    }
    //subscribe for rpc_software_active RPC calls
    rc = sr_rpc_subscribe(session
    , "/o-ran-software-management:software-activate"
    , rpc_software_activate_cb
    , NULL
    , 0
    , SR_SUBSCR_CTX_REUSE
    , &subscription);
    if (rc != SR_ERR_OK) {
        goto error;
    }

**Comment by michalvasko** [comment]
Hi,
no, this code looks okay.

**Comment by rydy** [comment]
Hi,

The following links patch sysrepo(v1.4.58) , libnetcof2(v1.1.24) and netopeer2 (v1.1.27) in  the OpenWRT ,  Using the [original version](https://github.com/CESNET/netopeer2/releases/tag/v1.1.27)(libssh(9.2 ), ibyang (v1.0.167), sysrepo(v1.4.58) , libnetcof2(v1.1.24) and netopeer2 (v1.1.27) ) directly has a[ Segmentation fault problem](https://github.com/CESNET/netopeer2/issues/685),I try to use the [latest version](https://github.com/CESNET/netopeer2/releases/tag/v1.1.39), but the current problem appears, I'm not sure which version to use about OpenWRT .
    https://github.com/openwrt/packages/tree/master/net/sysrepo
    https://github.com/openwrt/packages/tree/master/libs/libnetconf2
    https://github.com/openwrt/packages/tree/master/net/Netopeer2

Thanks,
Best regards.

**Comment by michalvasko** [comment]
Okay, could you please mention exactly what platform are you on (ARM version)?

**Comment by rydy** [comment]
The ARM version is ARM cortex-A53, I don't know what to do with it now.

**Comment by michalvasko** [comment]
We had some problems with unaligned memory access that some old processors could not handle but your one (ARMv8) should be fine. The bus error is most likely caused by *sysrepo* if that is what you were asking. We are working on reproducing this on an actual OpenWRT system so please be patient.

**Comment by rydy** [comment]
Thank you very much for your support, When the problem occur, the kernel logs are as follows.

Aug  2 11:14:06 kernel: [  185.481404] netopeer2-serve[3559]: unhandled level 3 translation fault (7) at 0x7fb4141000, esr 0x92000047, in libpthread-2.26.so[7fb7958000+18000]
Aug  2 11:14:06 kernel: [  185.481423] CPU: 3 PID: 3559 Comm: netopeer2-serve Not tainted 4.14.0 #5
Aug  2 11:14:06 kernel: [  185.481425] Hardware name: xlnx,zynqmp (DT)
Aug  2 11:14:06 kernel: [  185.481428] task: ffffffc00780e200 task.stack: ffffff800e898000
Aug  2 11:14:06 kernel: [  185.481432] PC is at 0x7fb7960e3c
Aug  2 11:14:06 kernel: [  185.481434] LR is at 0x7fb777788c
Aug  2 11:14:06 kernel: [  185.481437] pc : [<0000007fb7960e3c>] lr : [<0000007fb777788c>] pstate: 40000000
Aug  2 11:14:06 kernel: [  185.481439] sp : 0000007fb715b270
Aug  2 11:14:06 kernel: [  185.481441] x29: 0000007fb715b270 x28: 0000007fac023b40
Aug  2 11:14:06 kernel: [  185.481445] x27: 00000000000001b0 x26: 0000007fa40109a0
Aug  2 11:14:06 kernel: [  185.481450] x25: 0000000000000000 x24: 0000000000000000
Aug  2 11:14:06 kernel: [  185.481454] x23: 0000007fa400ab20 x22: 0000007fa40228c0
Aug  2 11:14:06 kernel: [  185.481459] x21: 0000000000000000 x20: 0000007fb715b2e8
Aug  2 11:14:06 kernel: [  185.481463] x19: 0000007fb4141000 x18: 0000000000000020
Aug  2 11:14:06 kernel: [  185.481468] x17: 0000007fb7960df8 x16: 0000007fb77b0258
Aug  2 11:14:06 kernel: [  185.481472] x15: 00002dd7ace21031 x14: 0000000000000016
Aug  2 11:14:06 kernel: [  185.481477] x13: 006669746f6e2e63 x12: 6e79732d6e61722d
Aug  2 11:14:06 kernel: [  185.481481] x11: 0000000000000020 x10: 0000007fb715b0a0
Aug  2 11:14:06 kernel: [  185.481485] x9 : 0000000000000000 x8 : 00000000000000de
Aug  2 11:14:06 kernel: [  185.481490] x7 : 0000007fb715c0c0 x6 : 0000007fb715c8c0
Aug  2 11:14:06 kernel: [  185.481494] x5 : 0000000000000000 x4 : 000000000000002d
Aug  2 11:14:06 kernel: [  185.481529] x3 : 0000000000000001 x2 : 0000000000000000
Aug  2 11:14:06 kernel: [  185.481549] x1 : 0000000000000000 x0 : 0000000080000000

**Comment by rydy** [comment]
Hi Michal,

For my OpenWrt ENV, The reason for this problem is that the /dev space is too small, By default, sysrepo's SHM file is stored in /dev/shm space. How should i change it?

**Comment by michalvasko** [comment]
Hi,
you cannot change the path because it is the storage for shared memory files.

**Comment by rydy** [comment]
> Hi,
> you cannot change the path because it is the storage for shared memory files.

I got it, thanks.

**Comment by robbynet** [comment]
Hello,
We are currently facing same issue as the one describe above on same Netopeer2 version.
We have coredump of netopeer2 along with the stack, traces, logs.
The problem occurs more and more often without having changed anything in our environment.
Please let me know the best way to proceed : Create a new ticket to provide material along with this closed ticket ?
Regards.
Christian.

**Comment by michalvasko** [comment]
Yes, please create a separate issue. Please include any relevant information including your system and platform.
