### ISSUE TITLE
How to resolve this call-home config failure?

### ISSUE THREAD

**Issue by LilyCuili** [CESNET/netopeer2#698]
Hi,
when I config call-home using the latest sysrepo-netopeer2 docker,there is error.I use the examples fomat to configure it. 
The error is "value "genkey" points to a non-existing leaf. " Do you know the reason?

log of netopeer-server
```
[INF]: LY: There is no leafref "/ietf-keystore:keystore/ietf-keystore:asymmetric-keys/ietf-keystore:asymmetric-key/ietf-keystore:name" with the value "genkey", but it is not required.
```
call home config.xml
```xml
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
    <call-home>
        <netconf-client>
            <name>main</name>
            <endpoints>
                <endpoint>
                    <name>default-ssh</name>
                    <ssh>
                        <tcp-client-parameters>
                            <remote-address>172.16.110.68</remote-address>
							<remote-port>6666</remote-port>
                            <keepalives>
                                <idle-time>30</idle-time>
                                <max-probes>10</max-probes>
                                <probe-interval>5</probe-interval>
                            </keepalives>
                        </tcp-client-parameters>
                        <ssh-server-parameters>
                            <server-identity>
                                <host-key>
                                    <name>default-key</name>
                                    <public-key>
                                        <keystore-reference>genkey</keystore-reference>
                                    </public-key>
                                </host-key>
                            </server-identity>
                            <client-authentication>
                                <supported-authentication-methods>
                                    <publickey/>
                                    <passsword/>
                                    <other>interactive</other>
                                </supported-authentication-methods>
                                <users/>
                            </client-authentication>
                        </ssh-server-parameters>
                    </ssh>
                </endpoint>
            </endpoints>
            <connection-type>
                <periodic>
                <reconnect_timeout>60</reconnect_timeout>
                </periodic>
            </connection-type>
        </netconf-client>
    </call-home>
</netconf-server>
```
```
root@a995ddc7216a:/# sysrepocfg --import=/callhome_enable.xml
[ERR]: Leafref "/ietf-keystore:keystore/ietf-keystore:asymmetric-keys/ietf-keystore:asymmetric-key/ietf-keystore:name" of value "genkey" points to a non-existing leaf. (path: /ietf-netconf-server:netconf-server/call-home/netconf-client[name='default-client']/endpoints/endpoint[name='default-ssh']/ssh/ssh-server-parameters/server-identity/host-key[name='default-key']/public-key/keystore-reference)
[ERR]: Validation failed.
sysrepocfg error: Replace config failed (Validation failed)
```

**Comment by michalvasko** [comment]
Hi,
well, it seems you do not have `genkey` key in the `ietf-keystore` configuration. It should be there after successful *netopeer2* installation so I do not know what the problem is, what image did you use exactly?

**Comment by LilyCuili** [comment]
Hi Michal
I used sysrepo-netopeer docker ，the latest version:
netopeer2-server 1.1.39
compile time: Aug 17 2020, 11:37:17

**Comment by michalvasko** [comment]
Hi,
okay but I am sorry, I do not maintain this image and have no capacity to do so because something is constantly not working properly. My suggestion is not to use `docker`. Other than that, maybe @lpaulic can help.

**Comment by lpaulic** [comment]
Hi,

I have checked the image and successfully reproduced the issue with a slight change to the `callhome_enable.xml`: 
* I renamed the `reconnect_timeout` leaf to `period` according to the ietf-netconf-server@2019-07-02.yang model that is instaled on the Docker image.

I also checked the ietf-keystore data store using the command `sysrepocfg -E -f xml -d running -m ietf-keystore` and the `genkey` exists with the private-public key pair generated during netopeer2 compilation.

I am not sure what is causing the problem.

@michalvasko how does the call-home feature work exactly?
Do you have any suggestions where should I look to find the cause of the issue?

Best regards

**Comment by michalvasko** [comment]
Hi,
what XML file are you talking about? I have just tested merging [ssh_callhome.xml](https://github.com/CESNET/netopeer2/blob/master/example_configuration/ssh_callhome.xml) into default *netopeer2* configuration and it worked just fine.

**Comment by lpaulic** [comment]
Hi,

Sorry about the misunderstanding, I am talking about the XML that @LilyCuili mentioned in the first comment.

Best regards

**Comment by michalvasko** [comment]
Oh, okay, now I figured it out, sorry about that. The XML is fine but the command
```
sysrepocfg --import=/callhome_enable.xml
```
is not. What it effectively does is import the XML into the `running` datastore meaning the **whole** datastore is now the contents of this XML. So, `ietf-keystore` data (among all the other modules except for `ietf-netconf-server`) are deleted, hence the error. Just add `-m ietf-netconf-server` to limit the import on this module. Even better, you can use `--edit=/callhome_enable.xml`, which will merge the XML instead of import so any existing data (including listen configuration of `ietf-netconf-server`) will be preserved.

**Comment by lpaulic** [comment]
Great, thank you for the clarification @michalvasko

**Comment by LilyCuili** [comment]
There is another problem ：P
root@a995ddc7216a:/# /usr/bin/netopeer2-cli
> connect --login netconf
Interactive SSH Authentication
Type your password:
Password:
> edit-config --target running --config=/callhome_enable.xml
ERROR
        type:     protocol
        tag:      access-denied
        severity: error
        path:     /ietf-netconf-server:netconf-server/call-home
        message:  Access to the data model "ietf-netconf-server" is denied because "netconf" NACM authorization failed.

**Comment by michalvasko** [comment]
Hi,
that is up to you to fix, it is [documented](https://github.com/CESNET/Netopeer2/#nacm).

**Comment by LilyCuili** [comment]
Thank you for the support,now I can config callhome.
