### ISSUE TITLE
Netooper server return error with get-config

### ISSUE THREAD

**Issue by Rohit2387** [CESNET/netopeer2#699]
cli connect 👍 
```
get-config --source running
nc ERROR: Session 2: received a <rpc-reply> with an unexpected message-id "9".
cli_send_recv: Unexpected reply received - ignoring and waiting for the correct reply.
cli_send_recv: Timeout for receiving a reply expired.
>

Netopper server error:
Locking subscription of "/ietf-netconf:get-config" failed, previous event "rpc" with ID 1 was not processed.
```

**Comment by Rohit2387** [comment]
[INF]: LY: Plugin "/usr/local/lib64/libyang1/extensions/nacm.so" successfully loaded.
[INF]: LY: Plugin "/usr/local/lib64/libyang1/extensions/metadata.so" successfully loaded.
[INF]: LY: Plugin "/usr/local/lib64/libyang1/extensions/yangdata.so" successfully loaded.
[INF]: LY: Plugin "/usr/local/lib64/libyang1/extensions/libyang_ext_test.so" successfully loaded.
[INF]: LY: Plugin "/usr/local/lib64/libyang1/user_types/user_yang_types.so" successfully loaded.
[INF]: LY: Plugin "/usr/local/lib64/libyang1/user_types/user_inet_types.so" successfully loaded.
[INF]: LY: Reading module "ietf-yang-metadata".
[INF]: LY: Module "ietf-yang-metadata@2016-08-05" successfully parsed as implemented.
[INF]: LY: Reading module "yang".
[INF]: LY: Resolving "yang" unresolved schema nodes and their constraints...
[INF]: LY: All "yang" schema nodes and constraints resolved.
[INF]: LY: Module "yang@2017-02-20" successfully parsed as implemented.
[INF]: LY: Reading module "ietf-inet-types".
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving derived type "union" failed, it will be attempted later.
[INF]: LY: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-inet-types" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-inet-types@2013-07-15" successfully parsed as implemented.
[INF]: LY: Reading module "ietf-yang-types".
[INF]: LY: Module "ietf-yang-types@2013-07-15" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-yang-types" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Resolving "sysrepo" unresolved schema nodes and their constraints...
[INF]: LY: All "sysrepo" schema nodes and constraints resolved.
[INF]: LY: Module "sysrepo@2020-01-15" successfully parsed as implemented.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Applying scheduled changes.
[INF]: LY: Searching for "ietf-datastores" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-datastores@2018-02-14.yang" file.
[INF]: LY: Module "ietf-datastores@2018-02-14" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-yang-library" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-yang-library@2019-01-04.yang" file.
[INF]: LY: Searching for "ietf-inet-types" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Searching for "ietf-datastores" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-datastores@2018-02-14.yang" file.
[INF]: LY: Module "ietf-yang-library@2019-01-04" successfully parsed as implemented.
[INF]: LY: Searching for "sysrepo-monitoring" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/sysrepo-monitoring@2020-04-17.yang" file.
[INF]: LY: Resolving "sysrepo-monitoring" unresolved schema nodes and their constraints...
[INF]: LY: All "sysrepo-monitoring" schema nodes and constraints resolved.
[INF]: LY: Module "sysrepo-monitoring@2020-04-17" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-netconf-with-defaults" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-netconf-with-defaults@2011-06-01.yang" file.
[INF]: LY: Searching for "ietf-netconf" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-netconf@2013-09-29.yang" file.
[INF]: LY: Searching for "ietf-netconf-acm" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-netconf-acm@2018-02-14.yang" file.
[INF]: LY: Module "ietf-netconf-acm@2018-02-14" successfully parsed as imported.
[INF]: LY: Module "ietf-netconf@2013-09-29" successfully parsed as imported.
[INF]: LY: Resolving "ietf-netconf-with-defaults" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-netconf-with-defaults" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-netconf-with-defaults@2011-06-01" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-netconf-notifications" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-netconf-notifications@2012-02-06.yang" file.
[INF]: LY: Resolving "ietf-netconf-notifications" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-netconf-notifications" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-netconf-notifications@2012-02-06" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-origin" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-origin@2018-02-14.yang" file.
[INF]: LY: Searching for "ietf-yang-metadata" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Resolving "ietf-origin" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-origin" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-origin@2018-02-14" successfully parsed as implemented.
[INF]: LY: Module "ietf-netconf-acm@2018-02-14" now implemented.
[INF]: LY: Searching for "ietf-netconf-monitoring" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-netconf-monitoring@2010-10-04.yang" file.
[INF]: LY: Module "ietf-netconf-monitoring@2010-10-04" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-netconf-nmda" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-netconf-nmda@2019-01-07.yang" file.
[INF]: LY: Searching for "ietf-origin" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-origin@2018-02-14.yang" file.
[INF]: LY: Searching for "ietf-netconf-with-defaults" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-netconf-with-defaults@2011-06-01.yang" file.
[INF]: LY: Resolving "ietf-netconf-nmda" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-netconf-nmda" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-netconf-nmda@2019-01-07" successfully parsed as implemented.
[INF]: LY: Searching for "nc-notifications" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/nc-notifications@2008-07-14.yang" file.
[INF]: LY: Searching for "notifications" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/notifications@2008-07-14.yang" file.
[INF]: LY: Module "notifications@2008-07-14" successfully parsed as imported.
[INF]: LY: Module "nc-notifications@2008-07-14" successfully parsed as implemented.
[INF]: LY: Module "notifications@2008-07-14" now implemented.
[INF]: LY: Searching for "ietf-x509-cert-to-name" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-x509-cert-to-name@2014-12-10.yang" file.
[INF]: LY: Module "ietf-x509-cert-to-name@2014-12-10" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-crypto-types" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-crypto-types@2019-07-02.yang" file.
[INF]: LY: Module "ietf-crypto-types@2019-07-02" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-keystore" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-keystore@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-crypto-types" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-crypto-types@2019-07-02.yang" file.
[INF]: LY: Resolving "ietf-keystore" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-keystore" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-keystore@2019-07-02" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-truststore" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-truststore@2019-07-02.yang" file.
[INF]: LY: Module "ietf-truststore@2019-07-02" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-tcp-common" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-tcp-common@2019-07-02.yang" file.
[INF]: LY: Module "ietf-tcp-common@2019-07-02" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-ssh-server" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-ssh-server@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-ssh-common" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-ssh-common@2019-07-02.yang" file.
[INF]: LY: Module "ietf-ssh-common@2019-07-02" successfully parsed as imported.
[INF]: LY: Searching for "ietf-keystore" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-keystore@2019-07-02.yang" file.
[INF]: LY: Searching for "iana-crypt-hash" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/iana-crypt-hash@2014-08-06.yang" file.
[INF]: LY: Module "iana-crypt-hash@2014-08-06" successfully parsed as imported.
[INF]: LY: Module "ietf-ssh-server@2019-07-02" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-tls-server" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-tls-server@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-tls-common" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-tls-common@2019-07-02.yang" file.
[INF]: LY: Module "ietf-tls-common@2019-07-02" successfully parsed as imported.
[INF]: LY: Searching for "ietf-truststore" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-truststore@2019-07-02.yang" file.
[INF]: LY: Module "ietf-tls-server@2019-07-02" successfully parsed as implemented.
[INF]: LY: Searching for "ietf-netconf-server" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-netconf-server@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-x509-cert-to-name" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-x509-cert-to-name@2014-12-10.yang" file.
[INF]: LY: Searching for "ietf-tcp-client" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-tcp-client@2019-07-02.yang" file.
[INF]: LY: Searching for "ietf-tcp-common" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-tcp-common@2019-07-02.yang" file.
[INF]: LY: Module "ietf-tcp-client@2019-07-02" successfully parsed as imported.
[INF]: LY: Searching for "ietf-tcp-server" in /root/netconf/sysrepo-devel/build/repository/yang.
[INF]: LY: Loading schema from "/root/netconf/sysrepo-devel/build/repository/yang/ietf-tcp-server@2019-07-02.yang" file.
[INF]: LY: Module "ietf-tcp-server@2019-07-02" successfully parsed as imported.
[INF]: LY: Resolving "ietf-netconf-server" unresolved schema nodes and their constraints...
[INF]: LY: All "ietf-netconf-server" schema nodes and constraints resolved.
[INF]: LY: Module "ietf-netconf-server@2019-07-02" successfully parsed as implemented.
[INF]: SR: No scheduled changes.
[INF]: SR: Session 26 (user "root") created.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: There is no leafref "/ietf-keystore:keystore/ietf-keystore:asymmetric-keys/ietf-keystore:asymmetric-key/ietf-keystore:name" with the value "genkey", but it is not required.
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: LN: Listening on 0.0.0.0:830 for SSH connections.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-keystore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-truststore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.

**Comment by michalvasko** [comment]
Hi,
> Can you paste the output of the server when executed as netopeer2-server -d -v3?

... and execute the `<get-config>`?

**Comment by Rohit2387** [comment]
netopper-server:
[INF]: LY: All data nodes and constraints resolved.
[ERR]: SR: Locking subscription of "/ietf-netconf:get-config" failed, previous event "rpc" with ID 1 was not processed.
[ERR]: NP: Failed to send an RPC (Timeout expired).
[INF]: NP: Session 2: thread 3 event new RPC.
[INF]: NP: Session 2: thread 3 event reply error.

netopper-cli:
> get-config --source running
nc ERROR: Session 2: received a <rpc-reply> with an unexpected message-id "7".
cli_send_recv: Unexpected reply received - ignoring and waiting for the correct reply.
cli_send_recv: Timeout for receiving a reply expired.

**Comment by michalvasko** [comment]
Okay, please start with `make sr_clean` in *sysrepo* repository, then reinstall *netopeer2-server* and then try again. Do you have any *sysrepo* applications of your own running?

**Comment by Rohit2387** [comment]
Now connect is failing with below error:
> connect
nc ERROR: Remote host key changed, the connection will be terminated!
nc ERROR: Checking the host key failed.
cmd_connect: Connecting to the localhost:830 as user "root" failed.

**Comment by michalvasko** [comment]
That is a generic SSH error, you can learn all about it if you search a bit. I can just help you with the usual solution - removing the old key from your known hosts. Use `knownhosts` command to print all the stored hosts and find the offending one. Then delete it using `knownhosts --del <num>`.
