### ISSUE TITLE
DOS by not using netconf subsystem

### ISSUE THREAD

**Issue by immibis** [CESNET/Netopeer2#7]
SSH to the netconf port normally:
{code}
ssh -p 6001 localhost
{code}

Authenticate and then the server will disconnect you.
Attempt to connect again, and observe that the connection will hang until the first connection times out (even though it was already closed by the server).

**Comment by michalvasko** [comment]
Hi,
in this case I believe everything works fine. After you connect and authenticate with `ssh`, it sends shell environment request. libnetconf2 ignores SSH messages it does not support, so no shell is opened, but it keeps waiting for netconf subsystem initialization (it is not closed yet). Only when the timeout expires it is disconnected. libnetconf2 allows to set this timeout (netopeer2-server not just yet), so it is up to the user to make use of it and prevent any DOS attacks.

It would only be possible to close every connection that sends a valid SSH message that is unknown to NETCONF, but I don't think this is really necessary.

Regards,
Michal

**Comment by rastislavszabo** [comment]
Hi,
I don't think that the timeout is a correct way of solving of this issue. Let's say that you would configure it for one second. The attacker just needs to open a new session once per second to effectively deny the access for any other users.

**Comment by michalvasko** [comment]
Replied in #6.

**Comment by rkrejci** [comment]
Reopening the issue to discuss solution to this.

**Comment by michalvasko** [comment]
Solved by the new thread architecture.
