### ISSUE TITLE
Number fo netconf session 

### ISSUE THREAD

**Issue by vishalwc** [CESNET/Netopeer2#70]
How many parallel NETCONF sessions are supported ?

**Comment by michalvasko** [comment]
Hi,
you can test for yourself, we never tried and there is no artificial limit by default. But the performance will likely degrade quite quickly as there is currently only one thread handling all the session requests. It will change in the future (see #68).

Regards,
Michal

**Comment by vishalwc** [comment]
Thanks for the update
