### ISSUE TITLE
Install script setup.sh fails when /etc/group has no name for used group

### ISSUE THREAD

**Issue by hthiery** [CESNET/netopeer2#701]
When no user/group is specified during configuration cmake tries to figure out the current user/group by using the `id` command. But when the /etc/group has no name for the gid the command will fail.

This was observed while cross-compiling with buildroot:
http://autobuild.buildroot.org/results/b2b5c26b03a71fcbf956789aaa8bf6638e6c0994/build-end.log

Normally buildroot will not use the file permission set during the build but will change the permission to root when creating the rootfilesystem. Would it be an option to change the setup.sh to not use the `-o` and `-p` when e.g. the value is set to `-1` during the configuration?

**Comment by michalvasko** [comment]
Hi,
could you please test it with [script.patch.txt](https://github.com/CESNET/netopeer2/files/5116283/script.patch.txt)? It worked fine for me and if it is fine for you as well, I will commit it.

**Comment by hthiery** [comment]
Hi Michal,

you're too quick ;-) I started doeing a similar fix. But yours looks better. Just started a rebuild and I will let you know if it works.

**Comment by hthiery** [comment]
Hi Michal,

looks good. On my machine I can succesfully build. I created a user whose group name is empty and the netopeer can be build/installed successfully.

Many thanks for your support.

**Comment by michalvasko** [comment]
Okay, it is committed now. Next time you can mention that you are willing to provide a patch, will save me the time :)

**Comment by hthiery** [comment]
> Okay, it is committed now. Next time you can mention that you are willing to provide a patch, will save me the time :)

sorry .. for sure ;-)
