### ISSUE TITLE
Netopeer2  release v 1.1.39 depends on libyang (v1.0.184) and libyang (v1.0.167)?

### ISSUE THREAD

**Issue by starx1000** [CESNET/netopeer2#702]
Netopeer2 release 1.1.39 say it depends on libyang v1.0.184, libnetconf2 (v1.1.26) 
https://github.com/CESNET/netopeer2/releases
version 1.1.39
This release depends on libyang **(v1.0.184**), libnetconf2 (**v1.1.26**) and sysrepo (v1.4.70).

But libnetconf2 (v1.1.26)  depends on libyang v1.0.167
https://github.com/CESNET/libnetconf2/releases/tag/v1.1.26
This release depends on libyang (**v1.0.167**)

Then I am conflict for the versions .
Netopeer2 finally depends on both libyang v1.0.167 and v1.0.184?
Both compatible?

Thanks.

**Comment by michalvasko** [comment]
Hi,
whenever something says it depends on some specific version of a library, it means the specific version **or higher**. There is no conflict and if you always use the latest versions of all the libraries, you will be fine.

**Comment by starx1000** [comment]
OK, thanks very much.
