### ISSUE TITLE
sysrepo support for RFC 6241 defined <error-tag> 

### ISSUE THREAD

**Issue by iGovindY** [CESNET/netopeer2#703]
Hi

as per discussion on #654 and #657.

looks like currently, All `<error-tag>` defined in [rfc6241#appendix-A](https://tools.ietf.org/html/rfc6241#appendix-A) is supported by sysrepo with Netopeer2 for backend application.
is this correct?
If Yes, when will it be supported?
```
# sysrepoctl -V
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.38 (SO v5.3.5)
```

A netconf client would expect to have support for these error-tags, if netconf server is compliant with rfc6241

**Comment by iGovindY** [comment]
I tried returning different errors from the backend app while processing a `module_change_cb` 
error-tag is operation-failed for all errors.

Am I doing it wrong?

```
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Invalid argument
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  libyang error
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  System function call failed
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Out of memory
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Item not found
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Item already exists
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Internal error
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Operation not supported
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Validation failed
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Operation failed
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Operation not authorized
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Requested resource already locked
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Timeout expired
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  User callback failed
```

Thanks
Govind.

**Comment by michalvasko** [comment]
Hi,
> looks like currently, All <error-tag> defined in rfc6241#appendix-A is supported by sysrepo with Netopeer2 for backend application.
is this correct?
A netconf client would expect to have support for these error-tags, if netconf server is compliant with rfc6241

Actually, `<error-tag>`s are supported only by the server (*netopeer2*) but this is not extended to *sysrepo* applications. Seems to me that this is a reasonable requirement so we will try to add support for this. But I am not able to tell you when, think several months at least because we are currently working on the other projects.

**Comment by michalvasko** [comment]
Custom errors (with error-app-tags) should be supported in *netopeer2* v2.
