### ISSUE TITLE
call-home can't connect to ODL because of SSH key exchange error

### ISSUE THREAD

**Issue by LilyCuili** [CESNET/netopeer2#706]
Hi Michal
now when configure call-home on the netopeer-server(latest docker image) 
 
root@66a2df7359fa:/# /usr/bin/netopeer2-server -V
netopeer2-server 1.1.39
compile time: Aug 17 2020, 11:37:17

the netopeer server connect to ODL client failed because SH key exchange error (Socket error: No such file or directory),the log is as below:
 
 
[INF]: LN: Trying to connect via IPv4 to 172.16.110.54:6666.
[INF]: LN: Successfully connected to 172.16.110.54:6666 over IPv4.
[INF]: SR: Session 254 (user "root") created.
[ERR]: LN: SSH key exchange error (Socket error: No such file or directory).
[INF]: LN: Trying to connect via IPv4 to 172.16.110.54:6666.
[INF]: LN: Successfully connected to 172.16.110.54:6666 over IPv4.
[INF]: SR: Session 255 (user "root") created.
[ERR]: LN: SSH key exchange error (kex error : no match for method server host key algo: server [rsa-sha2-512,rsa-sha2-256], client [ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,ssh-rsa,ssh-dss]).

do you know how to resolve it?

**Comment by michalvasko** [comment]
Hi,
I cannot tell you anything regarding the first error but
```
[ERR]: LN: SSH key exchange error (kex error : no match for method server host key algo: server [rsa-sha2-512,rsa-sha2-256], client [ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,ssh-rsa,ssh-dss]).
```
means that the algorithm of the server host key is not accepted by the client. In general, you can either change the host key (to use another algorithm) of the server or configure the client to accept the algorithm.

As for the first problem, you can manually (using `sysrepocfg`) edit `ietf-keystore` configuration and set a new key. But I cannot help you with the other solution, it is client-specific.

**Comment by LilyCuili** [comment]
Hi Michal
I found in docker container,the keystore configured as below,there is no private key.Do you know why can't configure private key.
<keystore xmlns="urn:ietf:params:xml:ns:yang:ietf-keystore">
  <asymmetric-keys>
    <asymmetric-key>
      <name>genkey</name>
      <algorithm>rsa2048</algorithm>
      <public-key>MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA+nM8L0l/T+HnmoSuO1PF
BqGijM7d0I14RjOFAxnr010Esyt6Gcd2/bPG4TWInLpJUcehsrxzwci/WFRxZwdN
nDAHwE/vQiwlHgVhlQ7j6g3bd7/i7SsSwFQo/ISD2YkKMS2GzsOwEn2BTO5LWgLV
VxXFmuw/D+3naJAuL+MoFeiVrooPR3aZP0+oH6Ub6oW/FbFrOdNPrKNRoTiKzIAl
y5METm4YwKlAifwg2TpBlmdjcsBlY4ugCO8qM4ptCz6fcfk9YV7Gbz82/p802/q9
SFIcFOlUWtfmS6PYCyWH+blm+MaID7JlAdrlx8AikS47h6fuzd8h3DYONGdiN5AM
bwIDAQAB</public-key>
    </asymmetric-key>
  </asymmetric-keys>
</keystore>

**rerun script  merge_hostkey.sh,still no private key in the datastore.**

**using below command can see the private key**
sysrepocfg -X -x "/ietf-keystore:keystore/ietf-keystore:asymmetric-keys/ietf-keystore:asymmetric-key[name='genkey']/private-key"
<keystore xmlns="urn:ietf:params:xml:ns:yang:ietf-keystore">
  <asymmetric-keys>
    <asymmetric-key>
      <name>genkey</name>
      <private-key>MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQD6czwvSX9P4eea
hK47U8UGoaKMzt3QjXhGM4UDGevTXQSzK3oZx3b9s8bhNYicuklRx6GyvHPByL9Y
VHFnB02cMAfAT+9CLCUeBWGVDuPqDdt3v+LtKxLAVCj8hIPZiQoxLYbOw7ASfYFM
7ktaAtVXFcWa7D8P7edokC4v4ygV6JWuig9Hdpk/T6gfpRvqhb8VsWs500+so1Gh
OIrMgCXLkwRObhjAqUCJ/CDZOkGWZ2NywGVji6AI7yozim0LPp9x+T1hXsZvPzb+
nzTb+r1IUhwU6VRa1+ZLo9gLJYf5uWb4xogPsmUB2uXHwCKRLjuHp+7N3yHcNg40
Z2I3kAxvAgMBAAECggEBAMaCGdz9K1y8mJ8ftR2u+waTjMyAls3bo844vZ/EpufD
3ZrJxiCyubzDBsqwbNSUztJ0IdUSi8m3/PndDHl2D2zRoQMsGF7hsJXH/B1yTPHS
A/c5b3s+XcF1s3ra6cq9VQe/pw8xidhOA/NfGPiCMGizCAoQYLeWgImfZgxsxvP8
8Wk9Y05LJzDia2FGkeWWYFd+UzUK1h6dpU3udY9DQq5g4i1AcFtj4JemoPfl5u2E
+IisLZY6b1DRzad0naOSTT9IbVPq2gaFWujv06wDIL/jBp7c5Y6aI1rPZbG/romd
PcOUYmZvL4vO1P8CHhXHPs9x02ml2ufSZxE1lc2qyrkCgYEA/YAB0My1NY+Au8nY
YNk9RX2DftXxs9dLSPwa96PF6Vvxv5Njhupwc5OCLSZ2imOP+qL8Kw+xNLmF9AA5
jvAbJIzyNj6Hu0noB+mXc/9YJv7nyb3Ur7hePmOvp8YuM1x5zl5bbUX1qFv8M1Yc
VB3/TL4dgDI9mdX4jp0hOqIY3OsCgYEA/OuHNhugmBvZIh+/GmjQJ/P685p2PX5r
fHJ0MSlTHysxZMEFbS0U8onUxbg9kEITRelEU90rhrrd6AbSbAjvDINKjWLMaJgg
3z4PQZMlO3VVGRGti9A3V03cvL1eCN/1doFXrq6VnH7suVMYAVSCDimLrfvAQu0p
3980QouXXY0CgYEAojvH7a700aBTTNsypViiQ9S90PBuzR+dyMm/IHkpcd0r6+UR
rwheizj9+JNDDfIF9OtV4uEaEZohxjRWocm8NToW0OxXxV7ZJicyjEQAUISWJqBc
e1DMz7TQd9j3PFuUgKQWcupw+xxTXS9g1dyUxLJvAtokXk130x1wZKvUqZ0CgYBB
ILVUrZCRGrqzGtGvD0Zqw1zf1eqUszUieqaI8kdBQ3IYq8ul7XHzcqKjt2nC+ADW
g9bgcZd/vibeVMNipnpIEpbkCYjxdhsg4W40SJvRz8j2B6NU2W0mwhoRUAIi7uja
dzwI81P7VIPIxSjtTsGeu/wH9Ufw8/lQeL2QVTnJEQKBgBHaxPeK2Vgvkr4Ii6gE
rouRRMmxthI+FoSKUX6FNDjMMgYrAffOFMp3G1ELIhPT/3W53xEbXWHIeHJD9U7C
KSOb46RHwRF1lvjVt+bUnZfcYOmxEzMMwrvazBnjXSEkgAK3LL9Zm3lIenE1ur/B
oemLQUPudDkafeXdzZhG8p1x</private-key>
    </asymmetric-key>
  </asymmetric-keys>
</keystore>

**Comment by michalvasko** [comment]
Hi,
I would say the private key is there the first time, it was just filtered out by NACM. Try retrieving the data as `root`, then you should really see all the data.

**Comment by LilyCuili** [comment]
Hi,
now I use the latest docker image,there is ssh key exchange error
root@66a2df7359fa:/# /usr/bin/netopeer2-server -V
netopeer2-server 1.1.39
compile time: Aug 17 2020, 11:37:17
when I install netopeer in a vm ,the version is netopeer2-server 1.1.34,there is no this issue.
because I want to use docker to do some test ,if you know the reason,could you please help about it?

**Comment by LilyCuili** [comment]
Hi
before I used docker image compiled on Dec  6 2018，it works well.the ssh config is as below.
now I just want to make it work.How to configure the ssh with the same as before algorithm
 to make it works.I am confused about the new ietf-keystore yang.could you please help show about it?

root@cd211956e87d:/usr/local/bin# netopeer2-server -V
netopeer2-server 0.7.1
compile time: Dec  6 2018, 10:27:30

<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <listen>
    <endpoint>
      <name>all-interfaces</name>
      <ssh>
        <address>0.0.0.0</address>
        <port>830</port>
        <host-keys>
          <host-key>
            <name>imported SSH key</name>
            <public-key>ssh_host_rsa_key</public-key>
          </host-key>
        </host-keys>
      </ssh>
    </endpoint>
  </listen>
  <call-home>
    <netconf-client>
      <name>main</name>
      <ssh>
        <endpoints>
          <endpoint>
            <name>endpt_name</name>
            <address>100.100.0.254</address>
            <port>6666</port>
          </endpoint>
        </endpoints>
        <host-keys>
          <host-key>
            <name>rsa_key</name>
            <public-key>ssh_host_rsa_key</public-key>
          </host-key>
        </host-keys>
      </ssh>
      <connection-type>
        <periodic>
          <reconnect_timeout>1</reconnect_timeout>
        </periodic>
      </connection-type>
    </netconf-client>
  </call-home>
</netconf-server>
<keystore xmlns="urn:ietf:params:xml:ns:yang:ietf-keystore">
  <private-keys>
    <private-key>
      <name>ssh_host_rsa_key</name>
      <algorithm>rsa</algorithm>
    </private-key>
  </private-keys>
</keystore>

**Comment by michalvasko** [comment]
Hi,
I believe it worked before because a shorter RSA key was used that is no longer considered safe. You should use the solution I mentioned in my first post. If you really want to, you can generate some weak RSA key and replace it in the `ietf-netconf-server` configuration to get the "older functionality". Just be aware that actually deploying such a key would be a security hazard.

**Comment by gogolovefish** [comment]
> Hi,
> I cannot tell you anything regarding the first error but
> 
> ```
> [ERR]: LN: SSH key exchange error (kex error : no match for method server host key algo: server [rsa-sha2-512,rsa-sha2-256], client [ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,ssh-rsa,ssh-dss]).
> ```
> 
> means that the algorithm of the server host key is not accepted by the client. In general, you can either change the host key (to use another algorithm) of the server or configure the client to accept the algorithm.
> 
> As for the first problem, you can manually (using `sysrepocfg`) edit `ietf-keystore` configuration and set a new key. But I cannot help you with the other solution, it is client-specific.

excuse me ,i meet the same SSH key exchange error problem,as you said i need to edit `ietf-keystore` configuration,but  how can I get the new key when i using"sysrepocfg" to edit "ietf-keystore",would mind to give a exameple,thank U.

**Comment by LilyCuili** [comment]
Hi,
thank you for the reply.I have used Netopeer1.1.34 to work around this problem.
I can cloase the issue now.
