### ISSUE TITLE
SSH subsystem support in netopeer2-cli

### ISSUE THREAD

**Issue by mikaabra** [CESNET/netopeer2#713]
I have a netconf server device that requires me to supply the subsystem in order to get the netconf interface.

So if I ssh to the device on port 830 I get the CLI. If I add "-s netconf" to the ssh command I get the netconf interface.

I can't seem to find a way to tell netopeer2-cli to configure the netconf subsystem when connecting, is there a way or would this be a feature request?

**Comment by rkrejci** [comment]
And netoper2-cli is not able to connect? I believe that the SSH subsystem is actually a standard way for NETCONF servers. Even netopeer2-server should actually provide `netconf` SSH subsystem from the SSH perspective, the only difference is that there is no code for the case when no (or other than netconf) SSH subsystem is requested by client. So I believe that there is nothing to configure on the client side.

**Comment by mikaabra** [comment]
Sorry, I misinterpreted the problem because I was running "verb 2" and it wasn't clear that it got through to the netconf layer.

It seems instead my problem is that get-schema doesn't work properly all the time, and sometimes it fails on the first attempt.
