### ISSUE TITLE
sometimes SSH Port 830 not work

### ISSUE THREAD

**Issue by UCNTFME** [CESNET/netopeer2#718]
sometime, even though netopeer2-server start success, but 830 port is not work.

![image](https://user-images.githubusercontent.com/39721431/93551591-d7deae00-f9a0-11ea-8acb-522b11d60309.png)

-- cli log
![image](https://user-images.githubusercontent.com/39721431/93551628-ed53d800-f9a0-11ea-9b92-28b8154fd29c.png)

it happened both on CentOS and Ubuntu, sometimes but not frequently

**Comment by UCNTFME** [comment]
maybe some clues i found:
1. start netopeer2-server normally 
2. kill netopeer2-serve by kill command
3. install some *.yang and *.xml
4. restart netopeer2-server, then it not work

------------ how to slove ----------
remake and reinstall maybe solve this problem

**Comment by michalvasko** [comment]
Hi,
what *netopeer2-server* version are you using?

**Comment by UCNTFME** [comment]
> Hi,
> what _netopeer2-server_ version are you using?

netopeer2-server -V
netopeer2-server 1.1.39
compile time: Sep 17 2020, 23:46:01

**Comment by UCNTFME** [comment]
latest progress..
maybe the issue was caused by sysrepo shm problem..
after run "make shm_clean" in sysrepo proj, it fixed

**Comment by michalvasko** [comment]
Hi,
please do not kill the server (by sending `SIGKILL`, send `SIGINT` instead), it is not yet supported and yes, it will break *sysrepo*.

**Comment by UCNTFME** [comment]
> Hi,
> please do not kill the server (by sending `SIGKILL`, send `SIGINT` instead), it is not yet supported and yes, it will break _sysrepo_.

k, thanks for your help..
