### ISSUE TITLE
[devel branch ]inactive read timeout elapsed.

### ISSUE THREAD

**Issue by UCNTFME** [CESNET/netopeer2#720]
netopeer2-server close my ssh connection with unknown reason, maybe 10/20 seconds after my ssh setup by another netconf-client
![image](https://user-images.githubusercontent.com/39721431/93853469-7db65380-fce6-11ea-9aa0-64d0b5a850a4.png)

and i just update all the components to latest devel branch any you mentioned before, but it not work.
software version&branch 
1. libyang  - devel branch 
2. sysrepo - devel branch
3. libnetconf2 - devel branch
4. netopeer2 - devel branch
5. libssh libssh2-1.8.0-3.el7.x86_64
6. ssh 
openssh-server-7.4p1-21.el7.x86_64
openssh-7.4p1-21.el7.x86_64
openssh-clients-7.4p1-21.el7.x86_64
libssh2-1.8.0-3.el7.x86_64

**Comment by michalvasko** [comment]
You either have an unsupported *libssh* version (*libssh2* is not used at all, the package name is usually `libssh4`) but that should be checked by *libnetconf2* `cmake` or a non-compliant NETCONF client that is sending more data than expected.

**Comment by UCNTFME** [comment]
> You either have an unsupported _libssh_ version (_libssh2_ is not used at all, the package name is usually `libssh4`) but that should be checked by _libnetconf2_ `cmake` or a non-compliant NETCONF client that is sending more data than expected.

hi, 
sorry that, where can i found libssh4,
and this is my cmake output
![image](https://user-images.githubusercontent.com/39721431/93858495-d7bb1700-fcee-11ea-951f-8d1bc0fa33f4.png)

**Comment by michalvasko** [comment]
> sorry that, where can i found libssh4,

Just search your packages for `libssh`, I do not know the exact package name.

> and this is my cmake output

*libssh* version 0.8.90 means compiled from source and that does not help much. Try downloading the latest 0.9.5 release tarball and install that instead.

**Comment by UCNTFME** [comment]
thanks for your help, but still not work after update my libssh to 0.9.5

more information that i use a third-party netconf client (go-netconf) to connect to netopeer2 server,
is any problem here?

**Comment by michalvasko** [comment]
Hi,
I cannot say for certain that the problem is in the client, but it is most likely. You can try to run the server with `-c MSG` so that you see all the received messages. If you paste the output here, I should be able to point at the problem. Or you can compare it with the output when using our *netopeer2-cli* NETCONF client.

**Comment by UCNTFME** [comment]
thanks michalvasko for your suggestion, i will try it later.

besides, i found a parameter **READ_INACTIVE_TIMEOUT** used in libnetconf2 for closing SSH client after wait that time(default 20s), but I am not sure whether is can be set to unlimited. 

but i am worried if the ssh keepalive will work together with this parameter, anyway i will try

**Comment by michalvasko** [comment]
No, it cannot be set to unlimited, only a larger value. And SSH keep-alive has nothing to do with this, it will work just like before. However, this is just a workaround, not a proper solution.

**Comment by UCNTFME** [comment]
thanks michal,

my purpose is to setup a ssh for listen on netconf-notification event, but not find solution yet,  so i checked the netopeer2-cli and libnetconf2 code. 

then, I use my golang netconf client to setup a ssh connection to netopee2, but during the session alive , libssh output some logs until the session is closed by netopeer2-server , like that ：
![image](https://user-images.githubusercontent.com/39721431/93991743-34860280-fdbf-11ea-8f16-db6fd22e4df6.png)

however , the log not shown by using netopeer2-cli, so i want to know why this happened ,and how to make a right solution for my purpose.. because this the socket io is locked by nc_read_msg_io() called looply..

**Comment by michalvasko** [comment]
Okay, if it works fine with *netopeer2-cli*, it means your NETCONF client is at fault here, it is sending some redundant characters (such as newline after the message). Either report it to them so they fix it or use another client.

**Comment by UCNTFME** [comment]
yes, it's right, and i find my client send message like "<message/>]]>]]>**\n**",  i think the LF character "**\n**" should be removed here, Am i right ?

**Comment by michalvasko** [comment]
Yes, it [should not be there](https://tools.ietf.org/html/rfc6242#section-4.1).

**Comment by UCNTFME** [comment]
ok, thanks for your sharing ! i will close the issue
