### ISSUE TITLE
netopeer2-server don't  automatic connect another call-home ip which imported by sysrepocfg

### ISSUE THREAD

**Issue by adamzyg** [CESNET/netopeer2#723]
first, I import a call-home endpoint by sysrepocfg, I can see the logs of connecting to this endpoint.
and then I import another call-home endpoint, that's  different with first one. So I think call-home config have two step to do:
1. delete the old call-home connect
2. connect to the new one

But in the log I don't see the case connecting to the new one.

```c
/* /ietf-netconf-server:netconf-server/call-home/netconf-client */
int
np2srv_ch_client_cb(sr_session_ctx_t *session, const char *UNUSED(module_name), const char *xpath,
        sr_event_t UNUSED(event), uint32_t UNUSED(request_id), void *UNUSED(private_data))
{
    sr_change_iter_t *iter;
    sr_change_oper_t op;
    const struct lyd_node *node;
    const char *prev_val, *prev_list, *client_name;
    bool prev_dflt;
    int rc;

    rc = sr_get_changes_iter(session, xpath, &iter);
    if (rc != SR_ERR_OK) {
        ERR("Getting changes iter failed (%s).", sr_strerror(rc));
        return rc;
    }

    while ((rc = sr_get_change_tree_next(session, iter, &op, &node, &prev_val, &prev_list, &prev_dflt)) == SR_ERR_OK) {
        /* get name */
        client_name = ((struct lyd_node_leaf_list *)node->child)->value_str;

        /* ignore other operations */
        if (op == SR_OP_CREATED) {
            rc = nc_server_ch_add_client(client_name);
            if (!rc) {
                rc = nc_connect_ch_client_dispatch(client_name, np2srv_new_session_cb);
            }
        } else if (op == SR_OP_DELETED) {
            rc = nc_server_ch_del_client(client_name);
        }
        if (rc) {
            sr_free_change_iter(iter);
            return SR_ERR_INTERNAL;
        }
    }
    sr_free_change_iter(iter);
    if (rc != SR_ERR_NOT_FOUND) {
        ERR("Getting next change failed (%s).", sr_strerror(rc));
        return rc;
    }

    return SR_ERR_OK;
}
```
In the code every call-home endpoint will be created a new pthread to manage the session, But why the actual performance is different?

**Comment by michalvasko** [comment]
I assume you have simply changed the endpoints of a single `netconf-client`? The behavior is not explicitly defined (or you can point me to a definition) so *netopeer2* behaves the following way. As long as you are connected to a client, it keeps the connection even after you change your configuration. Only once the connection is terminated (for whatever reason) and a reconnect is attempted, the new addresses are used.

**Comment by adamzyg** [comment]
OK, I thought it was like this.
Can i understand that if the call-home endpoint changed, just when the connection is terminated, then the new endpoint will be connect?

**Comment by michalvasko** [comment]
Yes, that is what I said, when the configuration is modified and the connection terminates, the new configuration is used.

**Comment by adamzyg** [comment]
OK. this issue can be closed.
