### ISSUE TITLE
cancel-commit not working

### ISSUE THREAD

**Issue by DineshReddyK** [CESNET/netopeer2#725]
Hi,

when I perform `cancel-commit` operation I get strange errors from lib yang.

```
> edit-config --target candidate --config=/root/data.xml
OK
> get-config --source candidate --filter-xpath /oven:*
DATA
<oven xmlns="urn:sysrepo:oven">
  <turned-on>false</turned-on>
  <temperature>0</temperature>
  <name>newnametest</name>
</oven>


> get-config --source running --filter-xpath /oven:*
DATA
<oven xmlns="urn:sysrepo:oven">
  <turned-on>true</turned-on>
  <temperature>250</temperature>
  <name>qwertyui</name>
</oven>

> cancel-commit
ly ERROR: Failed to find "cancel-commit" as a sibling to "ietf-netconf:get-config".
cli_send_recv: Failed to send the RPC.
>



> edit-config --target candidate --config=/root/data.xml
OK
> commit
OK
> cancel-commit
ly ERROR: Failed to find "cancel-commit" as a sibling to "ietf-netconf:get-config".
cli_send_recv: Failed to send the RPC.
> cancel-commit -h
cancel-commit is not supported by the current session.
>
```

I assumed that `cancel-commit` will not work as `confirmed-commit` feature is not enabled.
So when I try to enable `confirmed-commit` feature, I get different unrelated errors from sysrepo.

```
root@62a7d74453ce:# sysrepoctl -c ietf-netconf.yang -e confirmed-commit
[ERR]: Module "ietf-netconf.yang" was not found in sysrepo.
sysrepoctl error: Failed to enable feature "confirmed-commit" (Item not found)
root@62a7d74453ce:#

root@62a7d74453ce:# sysrepoctl -i ietf-netconf.yang -e confirmed-commit
[ERR]: Module "ietf-netconf" not scheduled for deletion.
[ERR]: Module "ietf-netconf" is already in sysrepo.
root@62a7d74453ce:/ORAN_Models#
```

To me it looks like both of these (netopeer2 and sysrepo) are problems and I failed to understand the issue.

**Comment by michalvasko** [comment]
The `confirmed-commit` is simply not supported even if you enabled the feature in the module, it will not help you, you would only get a more obvious error.

You failed to do that because of mistakes in your commands.
```
sysrepoctl -c ietf-netconf.yang -e confirmed-commit
```
In this one the `-c` parameter expects the module name, not the file name meaning you should have used just `ietf-netconf`.
```
sysrepoctl -i ietf-netconf.yang -e confirmed-commit
```
Here you are trying to install `ietf-netconf` with the `confirmed-commit` feature enabled but the module is already installed (as the error tells you). So you should have used only the previous command but with the correct module name.

**Comment by DineshReddyK** [comment]
Yes. you are right. After enabling that feature if I try `cancel-commit` i get different errors now

```
> edit-config --target candidate --config=/root/data.xml
OK
> cancel-commit
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        path:     /ietf-netconf:cancel-commit
        message:  There are no matching subscribers for RPC/action "/ietf-netconf:cancel-commit".

```

**Comment by AravindaSwamy** [comment]
Hi,

I am not able to bringup the Sysrepo with latest version of 2.1.36. Below are the logs observed while bringing up sysrepo

[INF]: LY: The ordered-by statement is ignored in lists representing notification content (/ietf-yang-push:push-change-update/datastore-changes/{uses='ypatch:yang-patch'}/yang-patch/edit).
[INF]: SR: Datastore copied from <startup> to <running>.
[INF]: SR: Connection 1 created.
[INF]: SR: Session 1 (user "root", CID 1) created.
[ERR]: NP: Module "ietf-netconf" feature "confirmed-commit" not enabled in sysrepo.
[ERR]: NP: Server init failed.
[INF]: NP: Server terminated.
[INF]: SR: No datastore changes to apply.

Let me know if any libraries to be installed for latest sysrepo version.

Thanks,
Aravind.

**Comment by jktjkt** [comment]
The Netopeer2 server refuses to start when the `confirmed-commit` capability is not enabled. Normally, that's done via the `scripts/setup.sh`; did you run it?
