### ISSUE TITLE
netopeer2 error logs， Does anyone come across this situation

### ISSUE THREAD

**Issue by superandrewaaa** [CESNET/netopeer2#726]
Sep 29 19:53:59 localhost netopeer2-server[2199]: Invalid arguments (lyd_new_leaf()).
Sep 29 19:53:59 localhost netopeer2-server[2199]: Invalid arguments (lyd_new_leaf()).
Sep 29 19:53:59 localhost netopeer2-server[2199]: Failed to find "global-lock" as a sibling to "ietf-netconf-monitoring:name".
Sep 29 19:53:59 localhost netopeer2-server[2199]: Invalid arguments (lyd_new_leaf()).
Sep 29 19:53:59 localhost netopeer2-server[2199]: Invalid arguments (lyd_new_leaf()).
Sep 29 19:53:59 localhost netopeer2-server[2199]: Failed to find "global-lock" as a sibling to "ietf-netconf-monitoring:name".
Sep 29 19:53:59 localhost netopeer2-server[2199]: Invalid arguments (lyd_new_leaf()).
Sep 29 19:53:59 localhost netopeer2-server[2199]: Invalid arguments (lyd_new_leaf()).
Sep 29 19:53:59 localhost netopeer2-server[2199]: Failed to find "global-lock" as a sibling to "ietf-netconf-monitoring:name".

**Comment by michalvasko** [comment]
Duplicate of #721.
