### ISSUE TITLE
NETCONF server logs for RPC's in xml format

### ISSUE THREAD

**Issue by sunnyarelli** [CESNET/netopeer2#727]
Hi,

Do we have any logging or how to enable logs for RPC Messages to dump in xml format  in NETCONF Server side so that we can check what all RPC messages are getting in and out from netconf server point of view?

We are currently using netopeer2-server of version NP2SRV_VERSION 1.1.43 taken from devel branch.

Regards,
Sunny

**Comment by michalvasko** [comment]
Hi,
yes, by specifying `-c MSG` for *netopeer2-server* (available only when built for `Debug` target).

**Comment by sunnyarelli** [comment]
Thanks Michal....
