### ISSUE TITLE
netopeer2-server crashes on notification event

### ISSUE THREAD

**Issue by umbertino** [CESNET/netopeer2#734]
Hello community,

still new to the netopeer2- and the sysrepo-tools and facing a new problem.
I'm playing around with the "oven"-model featured in [sysrepo](https://github.com/sysrepo/sysrepo). The oven.yang is imported properly to sysrepo. I can connect to a running netopeer2-server via UNIX-socket easily, edit configs and data. All is done manually with netopeer2-cli. I can register to the [oven-ready](https://github.com/sysrepo/sysrepo/blob/master/examples/plugin/oven.yang) notification. When firing the desired notification to the client using `sysrepocfg --notification=notify.xml -v 4`. this leads to a netopeer2-server crash due to a segmentation violation.
Here are the steps I perform:
`netopeer2-server -d -v 3 -U var/run/netopeer2-server.sock` No issues, everything is fine

 `netopeer2-cli` No issues, everything okay!

```
connect --unix
subscribe --filter-xpath /oven:oven-ready
OK
```
This works, too. No issues, neither on cli nor on server. Server reports
```
[INF]: SR: Published event "rpc" "/notifications:create-subscription" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/notifications:create-subscription" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: SR: Successful processing of "rpc" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 1 priority 0 succeeded.
[INF]: NP: Session 1: thread 4 event new RPC.
```
I now increase verbosity to 3 on client to get more information.
`verb 3`

On a third terminal I issue the following command:
`sysrepocfg --notification=notify.xml -v 4`

notify.xml contains only: `<oven-ready xmlns="urn:sysrepo:oven"/>`

```
[INF]: Scheduled changes not applied because of other existing connections.
[INF]: Session 31 (user "root") created.
[INF]: Published event "notif" "oven" with ID 1 priority 0 for 1 subscribers.
```
The netopeer-cli reports:
```
nc DEBUG: Session 1: received message:
<notification xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0"><eventTime>2020-10-12T06:26:23Z</eventTime><oven-ready xmlns="urn:sysrepo:oven"/></notification>

> 
notification (2020-10-12T06:26:23Z)
<oven-ready xmlns="urn:sysrepo:oven"/>

> 
nc ERROR: Session 1: communication file descriptor (3) unexpectedly closed.
> 
nc VERBOSE: Session 1: notification thread exit.
> 
```
And the netopeer-server states:

```
[INF]: SR: Processing "notif" "oven" event with ID 1.
[INF]: SR: Successful processing of "notif" event with ID 1 priority 0 (remaining 0 subscribers).
[ERR]: NP: Internal error (/home/pi/Development/OpAndManageTechStudy/netopeer2/src/netconf_monitoring.c:57)
zsh: segmentation fault  netopeer2-server -d -v 3 -U var/run/netopeer2-server.sock
```

It seems, the notification reaches the client and the server seems to process it successfully, too. Unfortunately the server crashes with error mentioned above. I'm running everything as root on a raspberry pi 4.
Does anyone have an idea?

Best regards and thank you!

Umberto

**Comment by michalvasko** [comment]
Right, should now be fixed in *netopeer2* in `devel`.

**Comment by umbertino** [comment]
Hello Michal,

thanks for the Bugfix. It works!
There are some new issues related to the `merge_hostkey.sh` script which prevents me frome a successfull `make install`. But this is not related to that issue I guess. 
Additionally, also not related to this issue, I encountered a strange behavior  with the netopeer2-cli binary. It runs properly in my local build directory but states an `lpcre` linker error after `make install`. (it is then the binary in the target dir /usr/local/bin). Interestingly the `md5sums` are different. If I `sudo cp netopeer2-cli` to the target dir, the checksums are the same and the binary runs from the target location properly.

Once more thank you for the quick fix!

Best regards

Umberto
