### ISSUE TITLE
ODL client fails push data with error "ssh_host_rsa_key" points to a non-existing leaf

### ISSUE THREAD

**Issue by viji459** [CESNET/netopeer2#736]
Hi ,
I am using netopeer docker version legacy. ODL client is able to connect and read data from netconf server. But it fails when it push data with following error.
Caused by: NetconfDocumentedException{message=Leafref "/ietf-keystore:keystore/ietf-keystore:private-keys/ietf-keystore:private-key/ietf-keystore:name" of value "ssh_host_rsa_key" points to a non-existing leaf.

I have not faced this issue when I was using previous docker versions till v0.7.7.
Can you please direct me how to resolve.

netopeer:
    container_name: netopeer
    image: sysrepo/sysrepo-netopeer2:legacy
/# netopeer2-server -V
netopeer2-server 0.7.18
compile time: Sep  1 2020, 10:40:49

```
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <listen>
    <endpoint>
      <name>all-interfaces</name>
      <ssh>
        <address>0.0.0.0</address>
        <port>830</port>
        <host-keys>
          <host-key>
            <name>imported SSH key</name>
            <public-key>ssh_host_rsa_key</public-key>
          </host-key>
        </host-keys>
      </ssh>
    </endpoint>
  </listen>
</netconf-server>
```
```
<keystore xmlns="urn:ietf:params:xml:ns:yang:ietf-keystore">
  <private-keys>
    <private-key>
      <name>ssh_host_rsa_key</name>
    </private-key>
  </private-keys>
</keystore>
```

**Comment by michalvasko** [comment]
We do not really provide support for the `legacy` version anymore but the error shows up when the leafref target data data are not in `running`. And even though they may be configured, you must have the `keystored` plugin enabled (have *sysrepo-plugind* running) for them to actually show up in `running`.

**Comment by viji459** [comment]
Thank you michalvasko. After running sysrepo-plugind, able to resolve the issue.
