### ISSUE TITLE
fight with the xpath filter in the CLI

### ISSUE THREAD

**Issue by robbynet** [CESNET/netopeer2#737]
Hello,
CLI report the following content : 
```xml
> get --filter-xpath /ietf-hardware:hardware//.
DATA
<hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
  <component>
    <name>ABCD</name>
    <class xmlns:o-ran-hw="urn:o-ran:hardware:1.0">o-ran-hw:O-RAN-RADIO</class>
    <hardware-rev>hw-rev01</hardware-rev>
    <software-rev>sw-rev01</software-rev>
    <serial-num>S01234567</serial-num>
    <mfg-name>FJ</mfg-name>
    <model-name>RADIOGEN1</model-name>
    <state>
      <oper-state>enabled</oper-state>
      <usage-state>active</usage-state>
      <admin-state>unlocked</admin-state>
      <power-state xmlns="urn:o-ran:hardware:1.0">AWAKE</power-state>
      <availability-state xmlns="urn:o-ran:hardware:1.0">NORMAL</availability-state>
    </state>
    <o-ran-name xmlns="urn:o-ran:hardware:1.0">ABCD</o-ran-name>
    <label-content xmlns="urn:o-ran:hardware:1.0">
      <model-name>true</model-name>
      <serial-number>true</serial-number>
    </label-content>
    <product-code xmlns="urn:o-ran:hardware:1.0">474611A</product-code>
  </component>
  <component>
    <name>ABCD-P1</name>
    <class xmlns:ianahw="urn:ietf:params:xml:ns:yang:iana-hardware">ianahw:port</class>
    <hardware-rev>hw-p01</hardware-rev>
    <software-rev>sw-p01</software-rev>
    <serial-num>S01234</serial-num>
    <mfg-name>FJ</mfg-name>
    <state>
      <oper-state>enabled</oper-state>
      <usage-state>active</usage-state>
      <admin-state>unlocked</admin-state>
    </state>
    <o-ran-name xmlns="urn:o-ran:hardware:1.0">ABCD-P1</o-ran-name>
  </component>
  <component>
    <name>ABCD-P2</name>
    <class xmlns:ianahw="urn:ietf:params:xml:ns:yang:iana-hardware">ianahw:port</class>
    <hardware-rev>hw-p01</hardware-rev>
    <software-rev>sw-p01</software-rev>
    <serial-num>S01234</serial-num>
    <mfg-name>FJ</mfg-name>
    <state>
      <oper-state>enabled</oper-state>
      <usage-state>active</usage-state>
      <admin-state>unlocked</admin-state>
    </state>
    <o-ran-name xmlns="urn:o-ran:hardware:1.0">ABCD-P2</o-ran-name>
  </component>
</hardware>
```
We see in this result above three component elements.
The need is to filter only on the component having:
```xml 
<class xmlns:o-ran-hw="urn:o-ran:hardware:1.0">o-ran-hw:O-RAN-RADIO</class>
```
Note: In the yang model:
```xml
<name>
``` 
is a key, but the need is to have a filter without this key.
I tried several syntax without any success : 
> get --filter-xpath /ietf-hardware:hardware/component/class[.="o-ran-hw:O-RAN-RADIO"]
DATA

> get --filter-xpath /ietf-hardware:hardware/component/class[text()="o-ran-hw:O-RAN-RADIO"]
DATA

> get --filter-xpath /ietf-hardware:hardware//class[text()="o-ran-hw:O-RAN-RADIO"]
DATA

> get --filter-xpath /ietf-hardware:hardware/*/class[text()="o-ran-hw:O-RAN-RADIO"]
DATA

Any idea ?

**Comment by michalvasko** [comment]
At the beginning of your expression you have used module name as the prefix (`ietf-hardware:`) but for the identityref value you have used the XML namespace prefix (`o-ran-hw:`). Do not mix these, *netopeer2-cli* (and *sysrepo* also) always expect module names. So, if you change the expected value to `o-ran-hardware:O-RAN-RADIO` (or whatever the module name is), it should work.

**Comment by robbynet** [comment]
Thanks for your support, it works : 
```xml
> get --filter-xpath /ietf-hardware:hardware//class[text()="o-ran-hardware:O-RAN-RADIO"]/../.
DATA
<hardware xmlns="urn:ietf:params:xml:ns:yang:ietf-hardware">
  <component>
    <name>ABCD</name>
    <class xmlns:o-ran-hw="urn:o-ran:hardware:1.0">o-ran-hw:O-RAN-RADIO</class>
    <hardware-rev>hw-rev01</hardware-rev>
    <software-rev>sw-rev01</software-rev>
    <serial-num>S01234567</serial-num>
    <mfg-name>FJ</mfg-name>
    <model-name>RADIOGEN1</model-name>
    <state>
      <oper-state>enabled</oper-state>
      <usage-state>active</usage-state>
      <admin-state>unlocked</admin-state>
      <power-state xmlns="urn:o-ran:hardware:1.0">AWAKE</power-state>
      <availability-state xmlns="urn:o-ran:hardware:1.0">NORMAL</availability-state>
    </state>
    <o-ran-name xmlns="urn:o-ran:hardware:1.0">AEUD</o-ran-name>
    <label-content xmlns="urn:o-ran:hardware:1.0">
      <model-name>true</model-name>
      <serial-number>true</serial-number>
    </label-content>
    <product-code xmlns="urn:o-ran:hardware:1.0">474611A</product-code>
  </component>
</hardware>
```

**Comment by robbynet** [comment]
Next step of the story is to brings this new customised xptah filter into Sysrepo API : 
Current implementation was using :
 const char mfg_name_path[]="/ietf-hardware:hardware/component[name='ABCD']//.";
And when this code is called : 
    rc = sr_get_items(session, mfg_name_path, 0, 0, &vals, &val_count);
Then Sysrepo returns a val_count = 20 elements

Now trying the new xpath just checked above : 
const char mfg_name_path[]="/ietf-hardware:hardware//class[.=\"o-ran-hardware:O-RAN-RADIO\"]/../.";
And then the outcome is that sysrepo return only ONE element : [INF]: OR: (list instance).
=> Expectation was also to have around 20 elements returned by Sysrepo as in CLI !
Where is the concern ?

**Comment by michalvasko** [comment]
This difference is subtle but important. NETCONF xpath filter defines that ["The response message contains the subtrees selected by the filter expression."](https://tools.ietf.org/html/rfc6241#section-8.9). However, *sysrepo* docs state ["Retrieve an array of data elements selected by the provided XPath."](https://netopeer.liberouter.org/doc/sysrepo/master/group__get__data__api.html#ga6a5f50da7ad03a5c52900e86be560759) for `sr_get_items`.

The same goes for all getters in *sysrepo* because they actually allow stronger filtering than NETCONF this way. You can always get a subtree if you append `//.` to the expression.

Finally, you should probably use some of the XPaths you have tried before this last one. In case you only want `component` instances use
```
/ietf-hardware:hardware/component[class="o-ran-hardware:O-RAN-RADIO"]
```
In case there can be instances named some other way
```
/ietf-hardware:hardware/*[class="o-ran-hardware:O-RAN-RADIO"]
```
And when the names and even depths are different
```
/ietf-hardware:hardware//*[class="o-ran-hardware:O-RAN-RADIO"]
```
Like I said, just append `//.` for subtrees instead of specific nodes.

**Comment by robbynet** [comment]
Go it, thanks it works !
