### ISSUE TITLE
Query about custom PAM based authentication

### ISSUE THREAD

**Issue by DineshReddyK** [CESNET/netopeer2#739]
Hi,
Is it possible to use `pam` based authentication for netopeer2?
It looks like `libnetconf` is not really supporting such authentication.
How can we have custom authentication which can enforce our additinal security rules?

**Comment by michalvasko** [comment]
Hi,
what SSH authentication method do you want to use? *libnetconf2* supports `publickey`, `password`, and `interactive`, you can define your own callback for each of them and perform whatever authentication you want to.

**Comment by DineshReddyK** [comment]
Ok. May be I was not clear. This is nothing to do with authentication methods, but how we do authentication it self.

Using PAM we can write our custom authentication stack (pam configuration) using all opensource libraries like `pam_unix.so`, `pam_tally2.so`  etc and this will simplify a lot of things.

PAM - https://www.redhat.com/sysadmin/pluggable-authentication-modules-pam
PAM - https://tldp.org/HOWTO/User-Authentication-HOWTO/x115.html

One of our main security requirement is, when there is successive failed attempts for a user, that user has to be temporarily locked.  If there is a pam support then the configuration would just be

```
auth       required     pam_tally2.so serialize lock_time=1 unlock_time=3600 deny=5
```

Without this, now we have to add a lot of code and re implement pam_tally2 functionality. 


`sshd/openssh` has the compilation options to decide whether to support PAM or not. Can `libssh/libnetconf2` can be improved to add PAM support?

**Comment by michalvasko** [comment]
I understood your query and answered it. The only way to implement this is to choose an authentication method and define your own callback for that method. Then, in the callback, you can do the PAM authentication yourself, there is no direct support for it. But if you do implement such a callback, we would definitely accept a patch but we will not implement this ourselves, there is too much more important work.

**Comment by DineshReddyK** [comment]
Sure. Once we implement and test we will try to contribute to upstream.
