### ISSUE TITLE
namespace is missing for ietf types

### ISSUE THREAD

**Issue by joanlandry** [CESNET/Netopeer2#74]
a rpc-reply for an interface is
```
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <data>
    <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
      <interface>
        <name>eth0</name>
        <enabled>true</enabled>
        <description>Ethernet 0</description>
        <type>ethernetCsmacd</type>
      </interfaces>
  </data>
</rpc-reply>
```
I believe the type should be:
       ` <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
`

**Comment by joanlandry** [comment]
I think this causes and issue in sysrepo make
- Exec: /mnt/images/netopeer2/sysrepo/build/src/sysrepocfg --import=/mnt/images/netopeer2/sysrepo/examples/yang/ietf-interfaces.data.xml --datastore=startup --format=xml --level=0 ietf-interfaces
CMake Error at examples/cmake_install.cmake:79 (message):
  Error: 1
Call Stack (most recent call first):
  cmake_install.cmake:146 (INCLUDE)

**Comment by jktjkt** [comment]
Ah yeah, I filed a bug about that at https://github.com/sysrepo/sysrepo/issues/603 (with a result of my git bisection).
