### ISSUE TITLE
make install fails when executing setupsh

### ISSUE THREAD

**Issue by umbertino** [CESNET/netopeer2#740]
Hi,

I switched to the devel-branch in order to get some fixes. Unfortunately after a successful build `sudo make install` fails with the following information:
```

-- Installing missing sysrepo modules...
su: failed to execute zsh: Datei oder Verzeichnis nicht gefunden
/home/umberto/Development/netopeer2/scripts//setup.sh: Line 82: -l: Command not found.
/home/umberto/Development/netopeer2/scripts//setup.sh: Line 51: : Command not found
CMake Error at cmake_install.cmake:81 (message):
   scripts/setup.sh failed: 127


make: *** [Makefile:74: install] Fehler 1
```

A brief investigation from my side revealed a problem in all of the 3 scripts `(setup.sh, merge_hostkey.sh and merge_config.sh)` when trying to initialize the `SYSREPOCFG` variable. This error is reproducible on my Raspberry Pi 4 and on my LinUX-machine running a 64-Bit Debian based distro (LMDE 4). Any hints?
`cmake` and `make`  completed successfully. No missing library or any other issue.

Cheers,

Umberto

**Comment by michalvasko** [comment]
It is a continuous effort of several people already to make these scripts portable and obviously it seems like an impossible task. But in this case I am not sure what to do. The problem is with `SYSREPOCTL` variable (but it does not matter as they are initialized the same way) but I do not know what exactly. You can try executing the right side of [this line](https://github.com/CESNET/netopeer2/blob/devel/scripts/setup.sh#L15) and [this line](https://github.com/CESNET/netopeer2/blob/devel/scripts/setup.sh#L17) and post the output.

**Comment by umbertino** [comment]
Hi Michal,

both lines lead to a valid variable:

```
[umberto@venere]/home/umberto/Development/netopeer2> SYSREPOCTL=`su -c 'which sysrepoctl' -l $USER`                        [git][netopeer2/.][devel]
[umberto@venere]/home/umberto/Development/netopeer2> echo $SYSREPOCTL                                                      [git][netopeer2/.][devel]
/usr/local/bin/sysrepoctl
[umberto@venere]/home/umberto/Development/netopeer2> SYSREPOCTL=`which sysrepoctl`                                         [git][netopeer2/.][devel]
[umberto@venere]/home/umberto/Development/netopeer2> echo $SYSREPOCTL                                                      [git][netopeer2/.][devel]
/usr/local/bin/sysrepoctl
[umberto@venere]/home/umberto/Development/netopeer2>                                                                       [git][netopeer2/.][devel]
```
This is fine.
I think, that when executing the shell-script through `cmake`, the environment is somehow different. 

```
-- Installing missing sysrepo modules...
su: failed to execute zsh: Datei oder Verzeichnis nicht gefunden
1 SYSREPOCTL : 
NP2_MODULE_DIR:  /usr/local/share/yang/modules/netopeer2
NP2_MODULE_PERMS:  600
MODDIR:  /usr/local/share/yang/modules/netopeer2
PERMS:  600
OWNER:  umberto
GROUP:  umberto
USER:  root
PATH:  /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/home/umberto/Development/netopeer2/scripts/setup.sh: Zeile 95: -l: Kommando nicht gefunden.
/home/umberto/Development/netopeer2/scripts/setup.sh: Zeile 64: : Kommando nicht gefunden.
CMake Error at cmake_install.cmake:81 (message):
   scripts/setup.sh failed: 127


make: *** [Makefile:74: install] Fehler 1
```

As you can see, it is not possible to set `SYSREPOCTL` correctly. (empty string).

I did the following and was successful:
```
[umberto@venere]/home/umberto/Development/netopeer2/build> export NP2_MODULE_DIR=/usr/local/share/yang/modules/netopeer2                              [git][netopeer2/build][develU]
[umberto@venere]/home/umberto/Development/netopeer2/build> export NP2_MODULE_PERMS=600                                                                [git][netopeer2/build][develU]
[umberto@venere]/home/umberto/Development/netopeer2/build> ../scripts/setup.sh                                                                        [git][netopeer2/build][develU]
2 SYSREPOCTL: /usr/local/bin/sysrepoctl
NP2_MODULE_DIR:  /usr/local/share/yang/modules/netopeer2
NP2_MODULE_PERMS:  600
MODDIR:  /usr/local/share/yang/modules/netopeer2
PERMS:  600
OWNER: 
GROUP: 
USER:  umberto
PATH:  /Users/umberto/anaconda3/bin:/Users/umberto/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sbin:/usr/sbin:/sbin:/home/umberto/bin:/home/umberto/.cabal/bin:/home/umberto:/home/umberto/bin:/home/umberto/bin/node/bin:/home/umberto/anaconda3/bin:/Applications/ARM/bin:/home/umberto/bin:/home/umberto/.cabal/bin:/home/umberto:/home/umberto/bin:/home/umberto/bin/node/bin:/home/umberto/anaconda3/bin:/Applications/ARM/bin
[umberto@venere]/home/umberto/Development/netopeer2/build>                                                                                            [git][netopeer2/build][develU]
[umberto@venere]/home/umberto/Development/netopeer2/build> echo $?                                                                                    [git][netopeer2/build][develU]
0
```
As you can see even as a standard user the script executes successfully. same applies to the other 2 scripts `merge_hostkey.sh` and `merge_config.sh`.
Anyway, this is not straight forward in terms of `sudo make install`. I tried another solution which seems to be more elegant and does not require the `which` commands. I added 2 extra lines in cmake_install.cmake which are:
```
set(ENV{SYSREPOCTL_EXECUTABLE} "/usr/local/bin/sysrepoctl")
set(ENV{SYSREPOCFG_EXECUTABLE} "/usr/local/bin/sysrepocfg")
```
This works. You would need to generate these in `CMakeLists.txt`  somewhere around line 230.

Does this help you?

Best Reards,

Umberto

**Comment by michalvasko** [comment]
> Does this help you?

Sadly, no. The point of using `which` is to handle situations when you have installed *sysrepo* into some custom path (but it is included in `PATH`). The idea was so that the user must define the exact path only in case the binaries are installed in some completely unknown path, in which case it is really the only safe solution.

**Comment by umbertino** [comment]
Okay, but these scripts are called only when installing, i.e. `sudo make install`, aren't they? So you have the exact location of installation, even if the user chooses a non-default one. 

Best regards,

Umberto

**Comment by michalvasko** [comment]
Well, yes, the location of *netopeer2* installation, not of *sysrepo* and that is what is needed here.

**Comment by umbertino** [comment]
Oh yes, you are right. I got confused.
Thank you for your replies. 
Shall we keep the issue open or is this covered in a more appropriate one? If so, feel free to close this one.

Regards

**Comment by michalvasko** [comment]
You are the first one with this exact issue, to my knowledge. Whether this stays open I do not care much, but it would be great if a solution was found. The `su` trick is meant to handle situations when `$USER` and `root` environments differ so the user environment is used to learn the path to `sysrepoctl`. I still do not know why it does not work for you.

**Comment by umbertino** [comment]
Hi Michal,

that topic keeps me thinking about it.
Once more here is another solution to retrieve the sysrepo* binaries via `cmake`:

```
 find_program(SYSREPOCTLPATH NAMES sysrepoctl)
 find_program(SYSREPOCFGPATH NAMES sysrepocfg)
 message(STATUS "sysrepoctl is ${SYSREPOCTLPATH}")
 message(STATUS "sysrepocfg is ${SYSREPOCFGPATH}")
 set(ENV{SYSREPOCTL_EXECUTABLE} "${SYSREPOCTLPATH}")
 set(ENV{SYSREPOCFG_EXECUTABLE} "${SYSREPOCFGPATH}")
```
What do you think? Some plausibility checks would be needed of course and it would have to introduced in the main `CMakeLists.txt`.

I uninstalled and cleaned everything, pulled everything from the devel-branches (libyang, sysrepo, libnetconf2 and netopeer2) to make sure there is nothing else interfering but had the same problem. So, I came up with that idea.

Regards,

umbertino

**Comment by michalvasko** [comment]
Yes, this is one of the possible solutions but it is not suitable for all use-cases of the scripts. They are also used when installing *netopeer2* from packages and in that case this will not help you. My idea would be for you to learn what exactly is causing the changes in your environment for `make install`. Based on that information it can be decided whether it can be fixed.

**Comment by umbertino** [comment]
Thanks for your feedback. Going to investigate my environment more deeply.

**Comment by umbertino** [comment]
Hi, 
after my last weeks vacation I recaptured this issue.
I found out, that there were some stale artefacts (wrong libyang library) installed which conflicted. I properly cleaned my system (Raspi4) and went step by step through the installations: libyang, sysrepo, libnetconf and then netopeer2. It works now. 
A hint to you main developers: The shell scripts in netopeer2 (setup.sh, merge_*.sh) seem to have CRLF which makes them not executable. Changed them to LF and it was fine.
Thanks for your help.

Regards,

Umberto

**Comment by michalvasko** [comment]
I have checked the scripts and could find no CR (`0D`) even when I printed them in hex so I must assume you have opened and saved them with an editor that did this change (on Windows).
