### ISSUE TITLE
Q: Exclude models from capabilities?

### ISSUE THREAD

**Issue by iljatab** [CESNET/netopeer2#741]
Hi Michal,

I got a question about advertised capabilities.

Is it possible to exclude some YANG models from capabilities, advertised by netopeer2-server?
I mean we have some modules installed in sysrepo in a usual way but do not want them to be exposed via netcopeer2-server.
These models/databases are supposed to be operated via sysrepo API directly and not via NETCONF.

Is there any way to do it now, apart from just a code patch?

Ilja.

**Comment by michalvasko** [comment]
No, this is not possible and I do not think it ever will be. The problem is that this would have to be configured in *netopeer2* and it uses the standardized modules for its configuration.

**Comment by iljatab** [comment]
I don't mean we need to be configured it "on the fly".
Jjust on netopeer2-server start it would be enough.

**Comment by iljatab** [comment]
Ok, understood, no problems!
