### ISSUE TITLE
Poll error prompted for subscribe command in netopeer2-cli

### ISSUE THREAD

**Issue by aswin19996** [CESNET/netopeer2#743]
Hi , 

I am trying to work on the notification aspects in Netopeer2
To subscribe to notifications I gave the command:
`subscribe --stream NETCONF --begin 2020-10-26T16:00:00Z`
and i encountered 2 errors:
1.

> nc ERROR: Session 9: invalid session to send RPCs.
> cli_send_recv: Failed to send the RPC.

The Server and Client got disconnected, also that i have encountered this disconnection many times while configuring values to the Yang modules using the command like "user-rpc", but then, i get them up and running using call home procedure and then, upon issuing the same command, it works.

What could be the reason for this disconnection at the first time upon sending RPCs, and is there any fix to avoid this disconnection?

2. Upon re-connection, and giving the same command:
`subscribe --stream NETCONF --begin 2020-10-26T16:00:00Z`

I encountered the following error:

> OK
> nc ERROR: Session 10: poll error (Success).

Since I received a Rpc reply as OK, how should i expect the notification from the server.
Or the notifications are not working due to the poll error.
It will be helpful if i could get any help on this issue

**Comment by michalvasko** [comment]
Firstly, what *netopeer2* version are you using? Then, can you provide more information about the disconnections? You can run the server (`-v3`) and client (`verb verbose`) with increased verbosity to see more messages and then paste them here. Just form this, I have no idea why it would disconnect except for some actual network issues.

**Comment by aswin19996** [comment]
The version of Netopeer2-server, i am using is 1.1.27

Restarted the server with verbosity 3, and below is the server logs after the disconnection:
PS: i have trimmed out the yang schema loading logs, FYI.

> [INF]: SR: No scheduled changes.
> [INF]: SR: Session 32 (user "root") created.
> [INF]: LY: Resolving unresolved data nodes and their constraints...
> [INF]: LY: There is no leafref 

> "/ietf-keystore:keystore/ietf-keystore:asymmetric-keys/ietf-keystore:asymmetric-key/ietf-keystore:name" with the value "genkey", but it is not required.

> [INF]: LY: There is no leafref "/ietf-keystore:keystore/ietf-keystore:asymmetric-keys/ietf-keystore:asymmetric-key/ietf-keystore:name" with the value "genkey", but it is not required.
> [INF]: LY: All data nodes and constraints resolved.
> [INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
> [INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
> [INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
> [INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
> [INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
> [INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
> [INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
> [INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
> [INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
> [INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
> [INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
> [INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
> [INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
> [INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
> [INF]: SR: Ext SHM was defragmented and 4368 B were saved.
> [INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
> [INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
> [INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
> [INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
> [INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
> [INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
> [INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
> [INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
> [INF]: SR: Triggering "ietf-keystore" "done" event on enabled data.
> [INF]: SR: Triggering "ietf-truststore" "done" event on enabled data.
> [INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
> [INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
> [INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
> [INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
> [INF]: LN: Call Home client "default-client" connecting...

**Comment by michalvasko** [comment]
This shows only that you started the server and it attempted to connect to a configured Call Home client. Everything is in order here, what disconnections are you talking about?

**Comment by aswin19996** [comment]
As soon as the server gets disconnected, i get the following prompt at netopeer2-server log:

> [2020/10/26 18:55:48.394621, 1] ssh_socket_exception_callback:  Socket exception callback: 1 (0)
> [2020/10/26 18:55:48.394689, 1] ssh_socket_exception_callback:  Socket error: disconnected

**Comment by michalvasko** [comment]
That seems like a normal disconnect from the client, so what is the client printing?

**Comment by aswin19996** [comment]
The client prints:
> nc ERROR: Session 9: invalid session to send RPCs.
> cli_send_recv: Failed to send the RPC.

so i had to reconnect to the server.

**Comment by michalvasko** [comment]
Like I said, please increase client verbosity using the command `verb verbose` and only then connect to the server. The error you posted is too generic.

**Comment by aswin19996** [comment]
Okay, so the client prints:

> subscribe --stream NETCONF --begin 2020-10-26T16:00:00Z
> nc ERROR: Session 3: invalid session to send RPCs.
> cli_send_recv: Failed to send the RPC.
> [2020/10/26 19:14:34.333284, 3] ssh_packet_need_rekey:  packet: [data_rekey_needed=0, out_blocks=1058, in_blocks=62390
> [2020/10/26 19:14:34.333441, 3] ssh_socket_unbuffered_write:  Enabling POLLOUT for socket
> [2020/10/26 19:14:34.333479, 3] packet_send2:  packet: wrote [type=96, len=16, padding_size=10, comp=5, payload=5]
> [2020/10/26 19:14:34.333497, 3] ssh_channel_send_eof:  Sent a EOF on client channel (43:43)
> [2020/10/26 19:14:34.333516, 3] ssh_packet_need_rekey:  packet: [data_rekey_needed=0, out_blocks=1058, in_blocks=62390
> [2020/10/26 19:14:34.333551, 3] packet_send2:  packet: wrote [type=97, len=16, padding_size=10, comp=5, payload=5]
> [2020/10/26 19:14:34.333576, 3] ssh_channel_close:  Sent a close on client channel (43:43)
> [2020/10/26 19:14:34.333618, 3] ssh_packet_socket_callback:  packet: read type 96 [len=16,padding=10,comp=5,payload=5]
> [2020/10/26 19:14:34.333639, 3] ssh_packet_process:  Dispatching handler for packet type 96
> [2020/10/26 19:14:34.333662, 3] channel_rcv_eof:  Received eof on channel (43:43)
> [2020/10/26 19:14:34.333679, 3] ssh_packet_socket_callback:  Processing 36 bytes left in socket buffer
> [2020/10/26 19:14:34.333700, 3] ssh_packet_socket_callback:  packet: read type 97 [len=16,padding=10,comp=5,payload=5]
> [2020/10/26 19:14:34.333720, 3] ssh_packet_process:  Dispatching handler for packet type 97
> [2020/10/26 19:14:34.333742, 3] channel_rcv_close:  Received close on channel (43:43)
> [2020/10/26 19:14:34.333761, 3] ssh_packet_need_rekey:  packet: [data_rekey_needed=0, out_blocks=1058, in_blocks=62390
> [2020/10/26 19:14:34.333777, 3] ssh_packet_need_rekey:  packet: [data_rekey_needed=0, out_blocks=1058, in_blocks=62390
> [2020/10/26 19:14:34.333799, 3] ssh_socket_unbuffered_write:  Enabling POLLOUT for socket
> [2020/10/26 19:14:34.333844, 1] ssh_socket_exception_callback:  Socket exception callback: 2 (32)
> [2020/10/26 19:14:34.333869, 1] ssh_socket_exception_callback:  Socket error: Broken pipe

**Comment by aswin19996** [comment]
Hi Michal, 
Any leads on this issue?
also for the second part of the issue regarding notification, am i supposed to expect a notification like this?

https://github.com/CESNET/Netopeer2/issues/120#issuecomment-293258509

**Comment by michalvasko** [comment]
Okay, anything printed before the output you provided? There are, again, no hints of any problems, it would seem the client simply got disconnected. What libssh version are you using? Other than that, I think it can only be some library incompatibility.

Also, yes, that is how a normal notification should look like.

**Comment by aswin19996** [comment]
Hi Michal, Apologies on the delay with the response, 
Libssh version : 0.8.0

There is nothing printed as an output to the subscribe command.
I don't find any outputs like how it is in the link i had attached in my previous comment.

**Comment by michalvasko** [comment]
Okay, then I am not able to help you. You may try reinstalling all the libraries and tools.

**Comment by aswin19996** [comment]
So, i tried re-installing all the files and again tried with the subscribe command.
This time, it prompted

> > subscribe
> OK
> > 
> nc ERROR: Session 48: SSH channel unexpected EOF.

Any leads on this ?

**Comment by michalvasko** [comment]
In this case it is the other peer (server) that unexpectedly disconnects. What *libssh* version are you using?

**Comment by aswin19996** [comment]
libssh version 0.8.0

**Comment by michalvasko** [comment]
On both ends in case you are not connecting to localhost? In any case, you may want to try something more recent, *libssh* is know to be buggy at times, 0.9.5 is tested and should work.

**Comment by aswin19996** [comment]
Okay, So i will try with the latest version and get back
