### ISSUE TITLE
Schema mount support

### ISSUE THREAD

**Issue by venkukakumani** [CESNET/netopeer2#744]
Hi,

Does the Netopeer2 server support YANG Schema Mount?

Thanks
Venkat

**Comment by michalvasko** [comment]
Hi,
no, it does not. The feature is planned to be implemented once other tasks are finished and there are none with higher priority. Definitely not this year, maybe the next one.

**Comment by venkatkakumani** [comment]
appreciate your support in providing schema mount feature
