### ISSUE TITLE
How APP can trigger a failure of edit-config ?

### ISSUE THREAD

**Issue by robbynet** [CESNET/netopeer2#753]
Hi,
Even if a callback, registered via sr_module_change_subscribe, generates return code SR_ERR_VALIDATION_FAILED or SR_ERR_OPERATION_FAILED, observation is that the originated edit-config command generated by the Client succeeds.
Then it seems that there is no way for a APP to trigger a failure of an edit-config command, is it a correct assumption ?

**Comment by michalvasko** [comment]
Hi,
no, if any callback fails, the whole edit-config will fail, too. But it must be on `SR_EV_CHANGE` event, the other events do not allow failing.

**Comment by robbynet** [comment]
Ok, got it !  sr_subscr_options_t opt was not properly set, not it works, thanks for the support.
