### ISSUE TITLE
NACM : It is not possible to manage access to data struct through "key" vaules

### ISSUE THREAD

**Issue by berstrob** [CESNET/netopeer2#755]
Hi, 

so i tried to use the NACM to filter my acces with a "key" like in RFC 8341   Page 55 , and it did not work as pland.

I added this rule: 

```
  <rule>
            <name>system</name>
            <path xmlns:oc-p="http://openconfig.net/yang/platform">/oc-p:platform/oc-p:components/oc-p:component[oc-p:name='SYSTEM']/oc-p:properties/oc-p:property</path>
            <access-operations>update</access-operations>
            <action>deny</action>
            <module-name>openconfig-system</module-name>
  </rule>

```

But the user was still able to use it (i tried the other way around with permit to component name='PORT' ,and default deny and nothing was able to be updated at all). then i checkt the code (netconf_acm.c 1069) 

```
 cmp = strncmp(path, rule->target, strlen(rule->target));

the vaules are:

 path= /openconfig-platform:components/component/properties/property/config/value 
 rule->target = /openconfig-platform:platform/components/component[name='SYSTEM']/properties/property
```

I did not see an easy fix since the node is a lys_node, so not sure if it even has the "key", so i went and did limit the acces on my end, to deny changes for the user group (is easy for write, if i did need read protetcion, i would not know how ) , but i was wondering if it might be abel to be implemented (or if i did miss something) .

Regards Bernd

**Comment by michalvasko** [comment]
Hi,
please try the attached [fix.patch.txt](https://github.com/CESNET/netopeer2/files/5536322/fix.patch.txt) applied on the latest `devel`. I did not test it all because I just do not have the time so I am asking you to do so, maybe tune some details in case it
wouldn't work because of a minor problem. Thanks.

**Comment by berstrob** [comment]
Hi, 

thank you very much, i did test a bit and in all my cases it did work as expeceted.  

So the "right node" just did hide one layer higher :) . 

I also looked at the new matching check and i could not see a reason why it should make proplems, other maybe the fact that with  the old match  ` rule= ".../system" ` would have  matched ` "target=.../systemkey" ` if both were in the same model, same branch , but that would have been a wrong match anyway as far as i understandt, and your new function should handel it right. 

Regards Bernd

**Comment by michalvasko** [comment]
Okay, thanks for the assistance, merged.
