### ISSUE TITLE
Creation of a container leaf fails if an action is present

### ISSUE THREAD

**Issue by frimpler** [CESNET/netopeer2#758]
Hi Michal et al.,

I have a simple yang module:

```
 module act {
   yang-version 1.1;
   namespace "urn:act";
   prefix a;
 
   revision 2019-04-30 {
     description
       "Initial revision.";
   }
 
   container action_cont {
     leaf created {
       type string;
     }
     action do_it {
       input {
         leaf ileaf {
           type string;
         }
       }
       output {
         leaf oleaf {
           type string;
         }
       }
     }
   }
 }
```
An edit-config RPC with this snippet:
```
<action_cont xmlns="urn:act" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <created nc:operation="create">YES</created>
</action_cont>

```
Fails with:
```
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" "/ietf-netconf:edit-config" with ID 6 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 6 priority 0 (remaining 1 subscribers).
[INF]: NP: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
[ERR]: SR: Node "created" to be created already exists.
[ERR]: SR: Applying operation "create" failed.
[INF]: SR: Failed processing of "rpc" event with ID 6 priority 0 (remaining 1 subscribers).
[ERR]: SR: Node "created" to be created already exists.
[WRN]: SR: Event "rpc" with ID 6 priority 0 failed (Item already exists).
[ERR]: NP: Failed to send an RPC (User callback failed).
[INF]: NP: Session 1: thread 2 event new RPC.
[INF]: NP: Session 1: thread 2 event reply error.
ERROR
        type:     application
        tag:      data-exists
        severity: error
        message:  Node "created" to be created already exists.
```
It's probably a sysrepo-issue, but when I tried to provide a mocka-test for sysrepo, I couldn't catch the issu for some reasons. Therefore, I took netopeer2-server + netopeer2-cli (nacm disabled, one dummy subscription for the module "act") and was able to produce the issue (and, thus, it became a netopeer2-ticket).

Btw.: If you change the operation in the edit-config RPC from "create" to "merge" it works.  And, if the container "action_cont" doesn't contain the action-leaf "do_it", the leaf "created" can be created, too.

Regards,
Frank

**Comment by michalvasko** [comment]
Hi,
I have tried to execute the RPC on a freshly installed `act` YANG, worked fine. Please execute `get-config` on `running` before sending the RPC and make sure the leaf really does not exist yet.

**Comment by frimpler** [comment]
Michal, thanks for trying it out. 
The background for writing the issue is, that we have a regression test, which tests explicitly the RFC conformance in this regard. This test fails with the sysrepo2-flavor of the stack. So you can be sure, that the data store of module is always empty for the test and was when I reproduced it with the stack as delivered by you guys. My retest had the following commits:
--------------libnetconf2-----------
b647aa1: 2020-11-04 08:53:14 +0100
--------------libyang-----------
98fb0d0b: 2020-11-12 11:39:02 +0100
--------------sysrepo-----------
c8c0ecaa: 2020-11-13 18:53:39 +0100
--------------Netopeer2-----------
63be3b5: 2020-11-05 14:51:06 +0100

It's all  from devel (and still libyang, no libyang2). Maybe I should also mention, that the test is always executed in a docker environment.

Regards,
Frank

**Comment by michalvasko** [comment]
Okay, I have tried it exactly the way you described it, having `application_changes_example act` running and then send the provided `edit-config`, I could still not reproduce it. Please, try to provide more details, otherwise I cannot help.

**Comment by frimpler** [comment]
Hello Michal,

we created some time ago an integration-test environment. It seemed reasonable to me, to put the test there. So, if you don't mind, do the following steps to reproduce the issue:
•	`git clone https://github.com/ADTRAN/netopeer2-integration-tests.git`
•	`cd netopeer2-integration-tests`
•	`make docker-shell`
(this will take a while, because the docker image will be built. You will afterward be prompted to the command line inside a docker container)
•	`./init-services`
(execute the init script in order to start all services incl. netopeer2-server)
•	`netopeer2-cli`
•	`connect --login netconf`
(password: netconf)
•	`edit-config --target running --config=rpcs/action_container.rpc`

Btw. the test tests the issue in question, but the yang module looks a bit different compared to the one above.
If needed, log files can be found under /local/log/supervisor.

That's what you can expect:
```
edit-config --target running --config=rpcs/action_container.rpc
ERROR
        type:     application
        tag:      data-exists
        severity: error
        message:  Node "config-container" to be created already exists.
```
(leaving the docker container by CTRL-D or exit will also stop and remove the container)

I hope you won't have any issues with the environment. But if, please don't hesitate to complain.

Regards,
Frank

**Comment by michalvasko** [comment]
Okay, I manage to reproduce the issue with your docker image but it is testing something else than what you presented. Not a leaf is being created but a non-presence container, which is a huge difference.

It is not even clear (from the RFC) what the behavior should be. But *libyang* treats NP containers almost like default values meaning it automatically creates them whenever their parent exists, recursively. So, the container really does exist even though you have not created it. This particular situation could be handled and the error suppressed but I do not really see any reason to do so. Also, it was working before? That may be because the container was not being created and after some bugfixes it is now.

**Comment by frimpler** [comment]
I've only now realized that I copied a wrong snippet - sorry for that and it explains, why you couldn't reproduce the issue (I tried different snippets when I wrote the ticket and picked apparently the wrong one)

Anyway. The test is related to this statement from RFC7950, 7.15:
>  The "action" statement is used to define an operation connected to a specific container or list data node.

So this means, that a specific data node must exist, before I could access the action - but I cannot create it, as complained here.

Btw.:
*    the test is an old one, it runs successfully through with the former stack (w/o sysrepo2), I'd say.
*    There is another test (in the mentioned repo), which tests the same for lists. Here it seems to work correctly: the action is accessible only once you've created the list entry. But for containers it doesn't work that way and, moreover, I can invoke the action w/o container creation - maybe this would have been the more fitting text of this ticket.

**Comment by michalvasko** [comment]
Yes, everything you are saying is correct and is intentional, based on what I said before. It makes sense you can execute an action in a container and that you cannot create it, since it already exists. Essentially, it is a feature, of *libyang*, because it is underspecified.

**Comment by frimpler** [comment]
Ok, "underspecified" is a good word for it - indeed, I didn't find any hints in RFC7950 which explain how to deal with actions in a NP container. IMHO the "action" gives the NP container kind of a "meaning", no just being a structural element. I found this: https://tools.ietf.org/id/draft-ietf-netmod-rfc6087bis-20.html#rfc.section.4.14.1, especially this sentence:

> Although these containers do not have any semantics, they can impact protocol operations for the descendant data nodes within a non-presence container, so use of these containers SHOULD be considered carefully

So if you like, close the ticket, but I'm still convinced, that the "action" should not be executed, if the container or any leaf under it has not been created, **_explicitly_**.

**Comment by michalvasko** [comment]
Okay, we have discussed this a bit internally and decided that this will keep the way it is meaning you do not have to create NP containers to be able to execute a nested action. If you want such a behavior, use presence containers. I believe that is what the text you quoted is trying to say.

However, it is now possible to create NP containers without any errors, they are simply ignored and no actual data changes take place.

**Comment by frimpler** [comment]
sounds good. Thanks.
