### ISSUE TITLE
Query on netopeer2 build type release and debug

### ISSUE THREAD

**Issue by mdoshi-com** [CESNET/netopeer2#759]
Hi,
While compiling netopeer2, one of the following can be done:
1. -DCMAKE_BUILD_TYPE=Release
2. -DCMAKE_BUILD_TYPE=Debug

When we do type "release" and if there is any crash in "netopeer2-server" binary, we are not able to get useful information (like like number, local variables etc) from the corefile in gdb as there is no symbols present (mostly the binary appears to be stripped binary).

So just wanted to know, if we build with type "Debug" then is it that the only difference is symbols would be added hence size of binary would increase?
We are trying to see if we should build binaries using "Debug" option only, else how will we debug crashes, if we get the corefile of the crash.

Regards,
Meghna

**Comment by mdoshi-com** [comment]
Hi Michal,
Ok got it. But if we use "Release" for production, then how can we debug crash issues, if any, reported from production sites.

Regards,
Meghna

**Comment by michalvasko** [comment]
> But if we use "Release" for production, then how can we debug crash issues, if any, reported from production sites.

Not sure, it is very difficult. `Release` target is not meant for any debugging. If you encounter many crashes (are still debugging technically), keep using the `Debug` target, there is no inherent problem with that.
