### ISSUE TITLE
call home with management system 

### ISSUE THREAD

**Issue by vishalwc** [CESNET/Netopeer2#76]
if the management entity connects with the server on call home connection .
how server locally configure port and IP ( it will be known upfront )  with the edit config command ,the client ( management server ) listening on the configured port gets connected ?
secondly is there any other way to do it, please suggest ?

Note : client ( management entity will not have netconf connectivity to send edit config )

**Comment by michalvasko** [comment]
Hi,
the whole server configuration is stored in sysrepo. So just use `sysrepocfg` on the startup datastore and modify the configuration to include Call Home configuration. Then it will start connecting to the client as soon as it is started.

Regards,
Michal

**Comment by vishalwc** [comment]
Thanks for the information and indeed useful
