### ISSUE TITLE
Query on publickey based authentication method

### ISSUE THREAD

**Issue by iGovindY** [CESNET/netopeer2#766]
Hi,

As part of merge_hostkey.sh, we are setting Public and private key in `ietf-keystore` module? like below

```
CONFIG="<keystore xmlns=\"urn:ietf:params:xml:ns:yang:ietf-keystore\">
    <asymmetric-keys>
        <asymmetric-key>
            <name>genkey</name>
            <algorithm>rsa2048</algorithm>
            <public-key>$PUBKEY</public-key>
            <private-key>$PRIVKEY</private-key>
        </asymmetric-key>
    </asymmetric-keys>
</keystore>"
```

1. is above for a local client authentication?

2. So If a server supports ssh mode without call-home, and if it needs to support only publickey based authentication
with below config in `ietf-netconf-server`
```
                                <supported-authentication-methods>
                                        <publickey/>
                                </supported-authentication-methods>
```

  * Then server should configure only the public key in `ietf-keystore` yang?
  * for netopeer2-cli to connect, auth keys add <public_key> <private_key> should be used?

Thanks
Govind.

**Comment by michalvasko** [comment]
1. It is the server hostkey meaning the (fingerprint of) key that is presented for any clients that attempt to connect. Not sure what "local client authentication" means.
2. `publickey` authentication is client authentication, something completely unrelated to the server hostkey. Server will accept any keys that are considered authorized for each user on the local system (keys present in `~/.ssh/authorized_keys`), it is not (yet) configured by any YANG module configuration. For a client to actually use a key for authentication, you need to add it with `auth keys add`, yes.

**Comment by iGovindY** [comment]
ohhh got it now, I confused hostkey with public key.

With local client authentication, I meant client running on the same machine.
Thank you for clearing doubt on `publickey` authentication

Thanks
Govind.
