### ISSUE TITLE
edit-config delete operation?

### ISSUE THREAD

**Issue by esend7881** [CESNET/netopeer2#772]
I am looking at RFC-6241 and I am wanting to use the [delete operation from edit-config:](https://tools.ietf.org/html/rfc6241#section-7.2) 

But, when looking at the edit-config options in netopeer2-cli, I don't see delete:
> edit-config [--help] --target running|candidate (--config[=<file>] | --url <url>) [--defop merge|replace|none] [--test set|test-only|test-then-set] [--error stop|continue|rollback] [--rpc-timeout <seconds>]

I only see `merge|replace|none` 

How do I access the delete aspect? I would to issue an edit-config of the vane shown in the RFC:

     <rpc message-id="101"
          xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
       <edit-config>
         <target>
           <running/>
         </target>
         <default-operation>none</default-operation>
         <config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
           <top xmlns="http://example.com/schema/1.2/config">
             <protocols>
               <ospf>
                 <area>
                   <name>0.0.0.0</name>
                   <interfaces>
                     <interface xc:operation="delete">
                       <name>192.0.2.4</name>
                     </interface>
                   </interfaces>
                 </area>
               </ospf>
             </protocols>
           </top>
         </config>
       </edit-config>
     </rpc>

When I try to submit this with `xc:operation='delete'` I get this error:
```
{
  "message-id" : "2",
  "rpc-error" : {
    "error-type" : "application",
    "error-tag" : "operation-failed",
    "error-severity" : "error",
    "error-path" : "/my-module:Elem1/Elem2/Elem3",
    "error-message" : {
      "lang" : "en",
      "" : "Invalid attribute \"operation\"."
    }
  }
}
```

- sysrepo 1.4.70
  - compiled with `cmake -DGEN_LANGUAGE_BINDINGS=ON ..`
- netopeer2 1.1.39 
  - compiled with `cmake -DSYSREPO_TIMEOUT=119 -DRPC_TIMEOUT=120 ..`
- libyang 1.0.184 
  - compiled with `cmake -DGEN_LANGUAGE_BINDINGS=ON ..`
- CentOS 7
- python 2.7.5/3.6.8

**Comment by michalvasko** [comment]
The request seems okay to me but the error is quite a strange one, especially the path. Also, the `message-id` does not match meaning it was not a reply for the RPC. Please include an actual non-working example, I cannot help you otherwise. Also, the specific `operation` can be included in the `config`, like in this case. The `edit-config` command simply lets you choose the `default-operation`, hence only the 3 operations ([ref](https://tools.ietf.org/html/rfc6241#section-7.2)).

**Comment by esend7881** [comment]
@michalvasko - you are right. When I force in the `xc:operation='delete'` I am able to perform the delete operation!
