### ISSUE TITLE
Netopeer2 is not supporting configuring ciphers and macs?

### ISSUE THREAD

**Issue by DineshReddyK** [CESNET/netopeer2#773]
Hi,
Based on `ietf-netconf-server` yang model,  we can configure the ciphers and mac that the server session can use right?

Tried the following configuration:

```xml
<listen>
 <endpoint>
   <ssh>
    <ssh-server-parameters>
      <transport-params>
         <encryption>
           <encryption-alg xmlns:sshcmn="urn:ietf:params:xml:ns:yang:ietf-ssh-common">sshcmn:triple-des-cbc</encryption-alg>
         </encryption>
         <mac>
           <mac-alg xmlns:sshcmn="urn:ietf:params:xml:ns:yang:ietf-ssh-common">sshcmn:hmac-sha1</mac-alg>
         </mac>
       </transport-params>
     </ssh-server-parameters>
   </ssh>
 </endpoint>
</listen>
```

When I see the server offering, it is offering what `libssh` supports by default.

```
debug2: peer server KEXINIT proposal
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr,3des-cbc
debug2: MACs ctos: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
```

Is `netopeer2` not supporting this?
I tried to look in `libnetconf2/src/session_server.c`, I couldn't easily find where this cipher and macs can be set to the server.

**Comment by michalvasko** [comment]
No, *netopeer2* does not support direct configuration of these parameters for now. It is fully handled by `libssh` so if you configure that to use specific ciphers, *netopeer2* will use those.

**Comment by DineshReddyK** [comment]
Ok. Thanks for the clarification.

**Comment by AeroFlorian** [comment]
Hi @michalvasko, I see there were a lot of commits around ssh configuration on libnetconf2 side. Are those parameters taken into account or still handled by libssh?

**Comment by michalvasko** [comment]
By default, they are handled by *libssh* but you are right, if you configure the nodes, they should be reflected and only the selected algorithms used. The current version should implement **all** the configuration nodes except those turned off by features (and some RPC messages are not supported yet).
