### ISSUE TITLE
Running 2 instances of netopeer2-server on same server

### ISSUE THREAD

**Issue by ashishsaxenahsc** [CESNET/netopeer2#774]
Hi all,

I want to run 2 different instances of netopeer2-server on a single machine such that both instances  are running on different ip/port combination and will receive configuration from different machines and write to either same or 2 different instances of sysrepo database.
Is it possible to do so ? Or there is any other way to accomplish this task ? 
 
Thanks and Regards,
Ashish

**Comment by michalvasko** [comment]
It is not officially supported and I have never tried it but I think with some patience you might be able to make it work. Because both *netopeer2* and *sysrepo* now have parameters/environment variables that should allow to isolate several of their instances. However, it is really simple to configure single *netopeer2* instance to listen on several interfaces so that may be all you need.

**Comment by oerdnj** [comment]
Hi @ashishsaxenahsc, perhaps you might want to start to describe what you are trying to do and not how are you trying to do that?

**Comment by ashishsaxenahsc** [comment]
Hi
Thanks for the quick reply.
Can you please give me pointers on configuring a single netopeer2 instance to listen on several interfaces .

Thanks and Regards,
Ashish


________________________________

**Comment by michalvasko** [comment]
You configure *netopeer2-server* by editing `ietf-netconf-server` configuration in *sysrepo* (using `sysrepocfg`, for example). You can look at the [default configuration](https://github.com/CESNET/netopeer2/blob/devel/scripts/merge_config.sh#L21), `endpoint` is actually a list so you can add more instances and just use different `local-address` for each interface to listen on.

**Comment by ashishsaxenahsc** [comment]
Hi Michal,

Thanks for your reply.
As you have mentioned, I have created my configuration as:

<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <listen>
    <endpoint>
      <name>tap0</name>
      <ssh>
        <address>10.0.0.1</address>
        <port>830</port>
        <host-keys>
          <host-key>
            <name>imported SSH key</name>
            <public-key>ssh_host_rsa_key</public-key>
          </host-key>
        </host-keys>
      </ssh>
    </endpoint>
    <endpoint>
      <name>tap1</name>
      <ssh>
        <address>20.0.0.1</address>
        <port>831</port>
        <host-keys>
          <host-key>
            <name>imported SSH key</name>
            <public-key>ssh_host_rsa_key</public-key>
          </host-key>
        </host-keys>
      </ssh>
    </endpoint>
  </listen>
</netconf-server>



And I am using sysrepocfg command to edit ietf-netconf-server as :
sysrepocfg --format=xml --editor=vim --datastore=startup ietf-netconf-server
The new configuration was successfully applied.

But after restarting netopeer2-server , I am not able to login to the netopeer-cli :

netopeer2-cli
> connect netconf --port 830
nc ERROR: Unable to connect to localhost:830 (Connection refused).
cmd_connect: Connecting to the localhost:830 as user "root" failed.

Can you please guide me what I am doing wrong here.

Thanks and Regards,
Ashish
________________________________

**Comment by michalvasko** [comment]
Just because you restart *netopeer2-server*, the configuration is not copied from `startup` to `running`. That occurs only on machine reboot. So get the configuration somehow into `running` (such as manual copy-config using `sysrepocfg`) and it should work.
