### ISSUE TITLE
How to call RPC from netopeer2-cli  ?  by following issue #550

### ISSUE THREAD

**Issue by arthurlintw** [CESNET/netopeer2#778]
By following the link , I still got problem. Can anyone help ? please ...
[https://github.com/CESNET/Netopeer2/issues/550](url)

 I spent a few days but got stuck in the error .
The following debug message comes from netopeer2-server , it seems the server got the RPC from client , but rpc-reply error . ( I have installed the test yang module ), is there any setting that needs to be done on the server site ?
Thanks.

netopeer2-server 1.1.39

[INF]: NP: Session 2: thread 2 event new RPC.
[DBG]: LN: Session 2: received message:
<update_datastore xmlns="urn:test">enable</update_datastore>

[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[ERR]: NP: Failed to send an RPC (Operation not supported).
[DBG]: LN: Session 2: sending message:

#389

[DBG]: LN: Session 2: sending message:
applicationoperation-failederror/test:update_datastoreThere are no matching subscribers for RPC/action "/test:update_datastore".

[DBG]: LN: Session 2: sending message:

**Comment by michalvasko** [comment]
Answered in the referenced issue, please post replies here.

**Comment by arthurlintw** [comment]
Thanks Michal , I see your reply in the reference link ( I was not sure if I reply in the closed issue or open a new issue is the right way , so I did both , sorry for the inconvenience ) and I would close this issue here.
