### ISSUE TITLE
Adjusting timeouts - Command fails after 15 seconds

### ISSUE THREAD

**Issue by esend7881** [CESNET/netopeer2#782]
### Issue:
I am having problems with timeouts in my netconf system. Here are the lines from 

### Log details
```.log
Dec 21 20:04:49 localhost netopeer2-server[5842]: Published event "rpc" "/ietf-netconf:edit-config" with ID 1 priority 0 for 1 subscribers.
Dec 21 20:04:49 localhost netopeer2-server[5842]: Processing "/ietf-netconf:edit-config" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
Dec 21 20:04:49 localhost netopeer2-server[5842]: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
Dec 21 20:04:49 localhost netopeer2-server[5842]: Published event "change" "rmbn-full" with ID 1 priority 0 for 1 subscribers.

Dec 21 20:04:54 localhost netopeer2-server[5842]: Callback event "change" with ID 1 processing timed out.
Dec 21 20:04:54 localhost netopeer2-server[5842]: Event "change" with ID 1 priority 0 failed (Timeout expired).
Dec 21 20:04:54 localhost netopeer2-server[5842]: Failed processing of "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
Dec 21 20:04:54 localhost netopeer2-server[5842]: Callback event "change" with ID 1 processing timed out.
Dec 21 20:04:54 localhost netopeer2-server[5842]: Event "rpc" with ID 1 priority 0 failed (User callback failed).
Dec 21 20:04:54 localhost netopeer2-server[5842]: Failed to send an RPC (User callback failed).
```
Notice the jump from time `20:04:49` to `20:04:54`. There are no log lines between those two. It seems after 15 seconds, netopeer2-server has timed out while my system was processing config data.

### Steps

**Installing the following RPMs in order:**
(note: [rpms sourced from here.](https://download.opensuse.org/repositories/home:/liberouter/CentOS_7/x86_64/))
```.sh
sudo yum localinstall ...

1. libyang1-1.0.184-7.2.x86_64.rpm
2. sysrepo-1.4.70-2.3.x86_64.rpm
3. libnetconf2-1.1.26-2.3.x86_64.rpm
4. netopeer2-1.1.39-2.3.x86_64.rpm
5. libyang-cpp1-1.0.184-7.2.x86_64.rpm
6. python3-yang1-1.0.184-7.2.x86_64.rpm
7. sysrepo-cpp-1.4.70-2.3.x86_64.rpm
8. python3-sysrepo-1.4.70-2.3.x86_64.rpm 
```

After install, I run the following command to fire up the system:
```.sh
/bin/sysrepoctl -a -i /opt/rmbn-yang/rmbn-full.yang -v 4
/bin/netopeer2-server -v 2 #I believe `-v 2` is the most verbose of logging I can attain in syslog. 
```

Prior to installing the system via RPMs, I manually compiled and built each aspect of the system and I was able to build netopeer2 with `cmake -DSYSREPO_TIMEOUT=119 -DRPC_TIMEOUT=120 ..` but with the RPM I am unable to issue an rpc_timeout or sysrepo_timeout limit.

### My questions:
1. I find it odd that 15 seconds is the timeout for waiting for a response from a change event, is that normal?
2. I would like to expand the timeout to at least 120 seconds. Without programming it into the `cmake` call, how can I ensure 120 second buffer time?

### My edit-config submission:
```.xml
<?xml version="1.0" encoding="utf-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="2">
<edit-config xmlns='urn:ietf:params:xml:ns:netconf:base:1.0'>
<target><running/></target>
<default-operation>replace</default-operation>
<config xmlns:xc='urn:ietf:params:xml:ns:netconf:base:1.0'>
<?xml version="1.0" encoding="UTF-8"?>
<MyModel xmlns="urn:com:tug:my_model">
...
</MyModel>
</config>
</edit-config>
</rpc>]]>]]>
```

I know according to RFC-6241, the `confirm-timeout` element is set to 600 seconds. Other than `confirm-timeout` I don't see any other timeout related element to use in netconf.

### My env:
- CentOS 7
- python 2.7.5/3.6.8

## A Thought - netopeer2-cli's implementation?

I notice in `netopeer2-cli` when I issue an `edit-config` there is an option for rpc-timeout, here:
```
> edit-config --help
edit-config 
[--help] 
--target running|candidate 
(--config[=<file>] | --url <url>) 
[--defop merge|replace|none] 
[--test set|test-only|test-then-set] 
[--error stop|continue|rollback] 
[--rpc-timeout <seconds>]
```
Unfortunatly, I am unable to use `netopeer2-cli` to issue my commands, I use [netconf-java](https://github.com/Juniper/netconf-java) which internally uses SSH. But that said, how does `netopeer2-cli` lump in the `rpc-timeout` instruction? Perhaps I could fold that in to netconf-java.

**Comment by michalvasko** [comment]
I believe in your case you can only keep configuring *sysrepo* manually, setting your own timeout, and not using the packages. Generally speaking, the used timeouts should be enough but you probably have a specific use-case (slow platform/device).

**Comment by esend7881** [comment]
> I believe in your case you can only keep configuring _sysrepo_ manually, setting your own timeout, and not using the packages. Generally speaking, the used timeouts should be enough but you probably have a specific use-case (slow platform/device).

Yeah my commands will take ~30 seconds or more. I am using sysrepo to hold a configuration of a remote system. The configuration changes occur atomically with changes to sysrepo and if the config fails to implement in the remote system, I don't want sysrepo to accept the new config. 

Not sure if other people have similar systems as this, but I got to imagine some people have big systems that take extra time to fully implement a config? Or maybe other systems choose not to make the process occur atomically (like a SQL transaction with commit/roll-back)
