### ISSUE TITLE
What commands are used to generate the RPMs?

### ISSUE THREAD

**Issue by esend7881** [CESNET/netopeer2#784]
I am phasing my system to run netopeer2/sysrepo/libyang by installing the RPMs (instead of compiling them all manually).

That said, I am wanting a few custom features included with the RPMs, which means I anticipate I will need to compile some of the RPMs on my own. For example, for netopeer2, I need to include custom flags in cmake:
```.sh
cmake -DSYSREPO_TIMEOUT=120 -DRPC_TIMEOUT=120 ..
```

**Is there a packaging script to generate the RPMs for netopeer after I have finished compiling?** 

Essentially I want to create the example same [RPM as this](https://download.opensuse.org/repositories/home:/liberouter/CentOS_7/x86_64/netopeer2-1.1.39-2.3.x86_64.rpm), except with those customer SYSREPO_TIMEOUT and RPC_TIMEOUT values. 

Note:
I am attempted to make RPMs on my own for sysrepo ([see this](https://github.com/sysrepo/sysrepo/issues/2208#issuecomment-722219893)) but @michalvasko mentioned package names could be off, so I want to make sure all my ducks are in a row for netopeer2.

**Comment by esend7881** [comment]
I'm still working this issue, but I found that after `make` commands run in netopeer2, a file is produced: `build/build-packages/local-rpm.sh`

That is good, however an error occurs when I run it. It seems a line regarding license is missing. I added the following line just before the `%description` section:

```
... (circa line 31)
License: OtherLicense
%description
NETCONF tools suite including a server and command-line client
...
```

When I do that, the error goes away. After this, I need to make sure I install the various sysrepo-devel, libyang-devel, and libnetconf2-devel rpms are installed.

Anyway, I am rebuilding as we speak, not sure if my custom RPM will work and my custom RPC_TIMEOUT value will pass through, but I thought I would make note of this.

**Comment by michalvasko** [comment]
Yeah, the error with the libyang package name was present and should be fixed in `devel`. Please, wait a few weeks until a new release is made that will hopefully fix these problems. In any case there is no point in fixing anything until then.

**Comment by esend7881** [comment]
> Yeah, the error with the libyang package name was present and should be fixed in `devel`. Please, wait a few weeks until a new release is made that will hopefully fix these problems. In any case there is no point in fixing anything until then.

@michalvasko - the thing is, the `seq fault` is not a problem with the [RPMs created and published officially](https://download.opensuse.org/repositories/home:/liberouter/CentOS_7/x86_64/netopeer2-1.1.39-2.3.x86_64.rpm), so I think if I just had the specific steps used to create the offical RPMs, I could replicate that work on my own.

I do look forward to the next versions of netopeer, though in the mean time this issue is a bit of a blocker. I'll continue researching ways around this and maybe for the time being, I'll manually compile netopeer2, but that won't work on our production environment. Ideally I find out how the official RPMs are compiled and move on from there.

**Comment by michalvasko** [comment]
That will not help you much, I am afraid, but [here](https://build.opensuse.org/project/show/home:liberouter) are the official RPMs being built.

**Comment by esend7881** [comment]
> That will not help you much, I am afraid, but [here](https://build.opensuse.org/project/show/home:liberouter) are the official RPMs being built.

Could it be possible to include in the next version of netopeer2-server a start up config or a start up input argument to allow for a custom `rpc_timeout` default value? I.e.,

```.sh
> netopeer2-server -v 2 -d --rpc-timeout-default 120
```
