### ISSUE TITLE
NACM : Deny for any operations for a module does not work.

### ISSUE THREAD

**Issue by Jagansingh22** [CESNET/netopeer2#786]
Hi,

I tried adding a rule to deny any operation on nacm module from users belonging to group g1.
I added the following rule,

```xml
<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm"
	xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">

	<rule-list>
		<name>rule-list1</name>
		<group>g1</group>
		
		<rule>
			<name>deny_all</name>
			<module-name>ietf-netconf-acm</module-name>
			<access-operations>*</access-operations>
			<action>deny</action>
		</rule>		
	</rule-list>
</nacm>
```

edit-config on nacm module is allowed, its not denying any of write operations.

from the netconf_acm.c code, issue seems to be in following code

```c
    for (rule = rlist->rules; rule; rule = rule->next) {

         /* module name matching */

         if (rule->module_name && (rule->module_name != lyd_node_module(node)->name)) {

         continue;

         }
```

I tried to print both rule->module_name and  lys_node_module(node)->name, 
`rule  module [ietf-netconf-acm], input node module name [ietf-netconf]` 

lys_node_module(node)->name is pointing to "ietf-netconf" for all operations, which should ideally have "ietf-netconf-acm"

Issue is same for get-config also but in sysrepo callback it again check for NACM access, where it is denying the operation.
Output of the get-config and edit-config commands,

```bash
> get-config --source running --filter-xpath /ietf-netconf-acm:*
DATA

> edit-config --target running --config=/nacm_config_files/test.xml
OK
```

**Comment by michalvasko** [comment]
Okay, firstly, you must distinguish between executing `edit-config` RPC and writing into data, those are 2 different operations that have separate NACM configuration. So, `edit-config` itself will be always permitted because you did not restrict it.

As for writing into data, it is checked separately by a [callback](https://github.com/CESNET/netopeer2/blob/master/src/netconf_acm.c#L1344). But note that writing into `ietf-netconf-acm` data is disabled by default because an [extension](https://github.com/CESNET/netopeer2/blob/master/modules/ietf-netconf-acm%402018-02-14.yang#L214) is used. So my guess is that you are using the recovery session (logged into the server as `root`) that bypasses both the extension and any configuration.

**Comment by Jagansingh22** [comment]
Hello,

Can you brief more about what writing into data mean?
And we are not using the recovery session.

Please check more details on issue and let me know if i am missing something.

Configuration in nacm:
```bash
> get-config --source running --filter-xpath /ietf-netconf-acm:*
DATA
<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
  <enable-nacm>true</enable-nacm>
  <groups>
    <group>
      <name>sudo</name>
      <user-name>oransudouser</user-name>
    </group>
    <group>
      <name>g1</name>
      <user-name>user1</user-name>
    </group>
  </groups>
  <rule-list>
    <name>rule-list1</name>
    <group>g1</group>
    <rule>
      <name>deny_all</name>
      <module-name>ietf-netconf-acm</module-name>
      <access-operations>*</access-operations>
      <action>deny</action>
    </rule>
  </rule-list>
</nacm>
```

Input xml file (add_group.xml) to create new group in nacm data model.
```xml
<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm"
	xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
	<groups>
	<group>
            <name>g2</name>
            <user-name>user2</user-name>
	</group>
	</groups>
</nacm>
```
Now logged in using user1 and tried get-config, edit-config operations.
No data is shown for get-config but edit-config is allowed.
```bash
$ netopeer2-cli
> connect --host 192.168.107.3 -l user1
Interactive SSH Authentication
Type your password:
Password: 
> 
> get-config --source running --filter-xpath /ietf-netconf-acm:*
DATA

> edit-config --target running --config=/nacm_config_files/add_group.xml
OK
> get-config --source running --filter-xpath /ietf-netconf-acm:*
DATA

>
```
edit-config command run with user1, added new group in nacm, which should have been denied.
get-config command output when tried with root user shows new group added.
```bash
$ netopeer2-cli 
> connect --host 192.168.107.3 -l root
Interactive SSH Authentication
Type your password:
Password:
> get-config --source running --filter-xpath /ietf-netconf-acm:*
DATA
<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
  <enable-nacm>true</enable-nacm>
  <groups>
    <group>
      <name>sudo</name>
      <user-name>oransudouser</user-name>
    </group>
    <group>
      <name>g1</name>
      <user-name>user1</user-name>
    </group>
    <group>
      <name>g2</name>
      <user-name>user2</user-name>
    </group>
  </groups>
  <rule-list>
    <name>rule-list1</name>
    <group>g1</group>
    <rule>
      <name>deny_all</name>
      <module-name>ietf-netconf-acm</module-name>
      <access-operations>*</access-operations>
      <action>deny</action>
    </rule>
  </rule-list>
</nacm>
```

**Comment by michalvasko** [comment]
Before I try it, can you mention your *sysrepo* and *netopeer2* version?

**Comment by Jagansingh22** [comment]
```bash
netopeer2-server 1.1.39
libsysrepo v1.4.70 (SO v5.5.12)
```

**Comment by michalvasko** [comment]
Okay, I have tested it with the current `devel` and it worked fine. There did not even had to be any NACM configuration and I could not write into it, as expected. I am not really aware of such major fixes but it is possible, so please use the `devel` branch of all the projects (*libyang*, *libnetconf2*, *sysrepo*, *netopeer2*) and try again. Or you can wait until they are released, should not take more than a few weeks.

**Comment by Jagansingh22** [comment]
Hello,
I have checked with sysrepo-netopeer2 docker where it works fine.
With our own image, issue is still there.
I had added logs in netopeer2-server code and found np2srv_diff_check_cb from following callback registration is not being called during edit-config request,
```c
sr_set_diff_check_callback(np2srv.sr_conn, np2srv_diff_check_cb);
```
It will be helpful if you could suggest what to check or how to debug this.

**Comment by Jagansingh22** [comment]
Hi,

In the sysrepo.c code found that registering the callback need root access and in our case, we start netopeer2 server as a non-root user.

Can you please share reason behind why this needs the root access, is it OK to skip this root check and allow non-root user to register for this callback?

```c
API void
sr_set_diff_check_callback(sr_conn_ctx_t *conn, sr_diff_check_cb callback)
{
    sr_error_info_t *err_info = NULL;

    if (!conn) {
        return;
    }

    if (geteuid()) {
        /* not a root */
        sr_errinfo_new(&err_info, SR_ERR_UNAUTHORIZED, NULL, "Root access required.");
        sr_errinfo_free(&err_info);
        return; 
    }    
          
    conn->diff_check_cb = callback;
}
```

**Comment by michalvasko** [comment]
Root is required because this callback can arbitrarily filter all edit-configs that are being processed by *sysrepo*. Also, in case of *netopeer2*, the callback then applies NACM configuration, which is not available even for reading for any user. So you cannot avoid having a special secure user for this purpose, might as well be `root`.

**Comment by DineshReddyK** [comment]
Hi Michal,
Does this mean, we can not run netopeer2 as non-root if we want to use NACM?

**Comment by michalvasko** [comment]
Yes, that is what it means, currently. We can talk about some possible change to avoid this but I am not sure what exactly. This callback is very sensitive so it should be restricted, somehow. I am not even sure about running *netopeer2* as non-root because it handles all the *sysrepo* data, which are very often sensitive (even `ietf-netconf-server` configuration is sensitive).

**Comment by DineshReddyK** [comment]
Ok. If this thread is open for discussions,

Can there be any UID registered for this, just like how it is done for recovery account  `NP2SRV_NACM_RECOVERY_UID` ?
which can be decided during compile time, and we can give access to that specific UID to read this sensitive information.

**Comment by michalvasko** [comment]
Okay, that should be fine and solve most of problems of this kind. But note that you set this UID for **all** the *sysrepo* applications on the system, unlike the recovery UID which is specific to *netopeer2*.

**Comment by Jagansingh22** [comment]
Hello,

I have tested the changes, the NACM authorization works fine when netopeer2 starts with the UID. 
Thanks,
