### ISSUE TITLE
failed to load new yang model

### ISSUE THREAD

**Issue by Bijendra0508** [CESNET/netopeer2#787]
Hello Team,

I am trying to install new yang module using **sysrepoctl**. during so i got following error:

> root@embedded-PC:~# sysrepoctl -i /root/o-ran-mplane-int.yang -v 4
> [INF]: Applying scheduled changes.
> [INF]: No scheduled changes.
> [ERR]: Data model "ietf-interfaces" not found.
> [ERR]: Importing "ietf-interfaces" module into "o-ran-mplane-int" failed.
> [ERR]: Module "o-ran-mplane-int" parsing failed.
> sysrepoctl error: Failed to install module "/root/o-ran-mplane-int.yang" (libyang error)

Looking at above logs it seems **ietf-interfaces** is not available in sysrepoctl. So i checked the sysrepoctl list. List attached below:
[new_yang_intsall_failed.txt](https://github.com/CESNET/netopeer2/files/5753879/new_yang_intsall_failed.txt)
 
As a result i see that `ietf-interfaces` is not found in above sysrepoctl list. So i tried to install `ietf-interfaces` from [link](http://www.netconfcentral.org/modules/ietf-interfaces) but this also failed to install. I believe something else is not correct here which i am not aware of.

Please suggest how can i fix this issue.

**Comment by robbynet** [comment]
Hello,
Hopefully, issue is explained into the error message:  "ietf-interfaces" not found.
To solve it path to this module need to be provided into the sysrepoctl cmd via "-s" option as follow : 
 sysrepoctl --verbosity 3 --apply --install o-ran-mplane-int.yang -s ../imported
../imported being the path where "ietf-interfaces" is supposed to be located.
Regards
Christian.

**Comment by michalvasko** [comment]
What @robbynet wrote is correct, or you can install the module separately the way you wanted to. But you have not mentioned why installing `ietf-interfaces` failed for you so I cannot help you more.

**Comment by Bijendra0508** [comment]
Hello Michal,

I picked ietf-interfaces from [here](http://www.netconfcentral.org/modulereport/ietf-interfaces)
while installing ietf-interfaces i got following error
`[ERR]: Invalid keyword ""Base identity from which specific interface types are derived."".`

I got a worked around by removing **base** from following structure
Not very sure if it is correct thing to do, but for now ietf-interfaces module installed successfully.

>  identity interface-type {
>      description
>         "Base identity from which specific interface types are
> derived.";
>     }

**Comment by michalvasko** [comment]
Yeah, I had problems with netconf central modules in the past. Best to download everything from [here](https://github.com/YangModels/yang/blob/master/standard/ietf/RFC/ietf-interfaces%402018-02-20.yang), those modules should always be fine.

**Comment by Bijendra0508** [comment]
Hello Michal,

With above modules installed I again tried to install o-ran-mplan.yang but it again failed with following errors:

> root@embedded-PC:~# sysrepoctl --verbosity 3 --apply --install o-ran-mplane-int.yang -s ~/
> [INF]: Applying scheduled changes.
> [INF]: No scheduled changes.
> [WRN]: Module's revisions are not unique (2018-06-28).
> [ERR]: Invalid keyword "ianahw:sensor".
> [ERR]: Module "ietf-hardware" parsing failed.
> [ERR]: Importing "ietf-hardware" module into "o-ran-interfaces" failed.
> [ERR]: Module "o-ran-interfaces" parsing failed.
> [ERR]: Importing "o-ran-interfaces" module into "o-ran-mplane-int" failed.
> [ERR]: Module "o-ran-mplane-int" parsing failed.
> sysrepoctl error: Failed to install module "o-ran-mplane-int.yang" (libyang error)
> [INF]: Ext SHM was defragmented and 5160 B were saved.

As per error its seems like **ianahw:sensor** keyword listed in **ietf-hardware.yang** (download from [here)](https://github.com/YangModels/yang/blob/master/standard/ietf/RFC/ietf-hardware-state%402018-03-13.yang) module has been wrong.  Also I install iana-hardware.yang also from above link as it is a dependent module.

Could you please suggest what i am doing wrong.

**Comment by michalvasko** [comment]
Hm, okay, it seems there are problems even in these modules, unfortunately. You are free to report it and to fix, change [this line](https://github.com/YangModels/yang/blob/master/standard/ietf/RFC/ietf-hardware%402018-03-13.yang#L1006), the next line is a continuation of the previous line so both of them should be on a single line.

**Comment by Bijendra0508** [comment]
Hello Michal,

Request you to please check the reply https://github.com/YangModels/yang/issues/930#issuecomment-754950512
According to them sysrepo parser has some issue.

**Comment by michalvasko** [comment]
Okay, sorry about that, the module there is really correct. But I am not able to reproduce your `sysrepoctl` problem. Can you please append all the required YANGs and the command to reproduce the problem? Also mention what *sysrepo* version you are using.
