### ISSUE TITLE
does netopeer2 can provide service stable?

### ISSUE THREAD

**Issue by RogerYaozhenyu** [CESNET/Netopeer2#80]
Hi, 
i saw the descriton at the bottom of the README file " The Netopeer2 toolset is still under development. While CLI is already usable, the server is pure work in progress and we don't recommend to use it in this phase."    so i want to know that if the netopeer2 can work well ,   i plan to choose libnetconf2, syspro,and netopper2  as our new project basement to provide netconf service.  hope to get your reply. 
thanks, 
  roger.

**Comment by michalvasko** [comment]
Hi,
the master branch is actually usable and in a better state than described. However, the devel branch has many new features and bugfixes and even the README was changed and the whole part you cited was removed. So, to answer your question, the devel branch should be ready and it will be merged around the end of January. Until then there may be some problems, but you can start using it.

Regards,
Michal
