### ISSUE TITLE
Netconf acm path not getting updated 

### ISSUE THREAD

**Issue by Abrahamma97** [CESNET/netopeer2#801]
Hi
I have updated the path permission in ietf-netconf-acm after giving default deny all. 
```xml
   <rule>
      <name>o-ran-usermgmt-permission</name>
      <module-name>o-ran-usermgmt</module-name>
      <path xmlns:u="urn:o-ran:user-mgmt:1.0">/u:users/u:user/u:name"</path>
      <access-operations>*</access-operations>
    </rule>
```

But I am not able to read info using get and get-config
Kindly do help
If I replace it with
```xml
   <name>o-ran-usermgmt-permission</name>
      <module-name>o-ran-usermgmt</module-name>
      <access-operations>*</access-operations>
      <action>permit</action>
    </rule>
```

I am able to use get and get-config correctly
Kindly help in telling what I did wrong at first

**Comment by Abrahamma97** [comment]
Hi @michalvasko 
Can you help out

**Comment by Abrahamma97** [comment]
Hi Can anybody help?

**Comment by michalvasko** [comment]
Sorry, GitHub has hidden the notification about this thread for me for some reason. So, I am not sure how did you manage to set the first config because `action` node is mandatory so any configuration without it should be refused.

**Comment by Abrahamma97** [comment]
Hi @michalvasko ,
Sorry that was a typo from my part .. This is the correct configuration.
<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
  <enable-nacm>true</enable-nacm>
  <read-default>deny</read-default>
  <write-default>deny</write-default>
  <exec-default>deny</exec-default>
  <enable-external-groups>false</enable-external-groups>
  <groups>
    <group>
      <name>sudo</name>
      <user-name>root</user-name>
      <user-name>Operator</user-name>
    </group>
    <group>
      <name>nms</name>
      <user-name>Observor</user-name>
    </group>
    <group>
      <name>swm</name>
      <user-name>Installer</user-name>
    </group>
  </groups>
  <rule-list>
    <name>sudo-access</name>
    <group>sudo</group>
    <rule>
      <name>permit-all</name>
      <module-name>*</module-name>
      <access-operations>*</access-operations>
      <action>permit</action>
    </rule>
  </rule-list>
  <rule-list>
    <name>nms-access</name>
    <group>nms</group>
    <rule>
      <name>o-ran-hardware-permission</name>
      <module-name>o-ran-hardware</module-name>
      <access-operations>read exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-hardware-permission</name>
      <module-name>ietf-hardware</module-name>
      <access-operations>create read update delete exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>iana-hardware-permission</name>
      <module-name>iana-hardware</module-name>
      <access-operations>create read update delete exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-fm-permission</name>
      <module-name>o-ran-fm</module-name>
      <access-operations>read exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-sync-permission</name>
      <module-name>o-ran-sync</module-name>
      <access-operations>create read update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-delay-management-permission</name>
      <module-name>o-ran-delay-management</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-module-cap-permission</name>
      <module-name>o-ran-module-cap</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-udp-echo-permission</name>
      <module-name>o-ran-udp-echo</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-operations-permission</name>
      <module-name>o-ran-operations</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-uplane-conf</name>
      <module-name>o-ran-uplane-conf</module-name>
      <access-operations>create read update delete exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-lbm-permission</name>
      <module-name>o-ran-lbm</module-name>
      <access-operations>create read update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-software-management-permission</name>
      <module-name>o-ran-software-management</module-name>
      <access-operations>create read update delete exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-file-management-permission</name>
      <module-name>o-ran-file-management</module-name>
      <access-operations>exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-performance-management-permission</name>
      <module-name>o-ran-performance-management</module-name>
      <access-operations>create read update delete exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-transceiver-permission</name>
      <module-name>o-ran-transceiver</module-name>
      <access-operations>create read update delete exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-interfaces-permission</name>
      <module-name>o-ran-interfaces</module-name>
      <access-operations>create read update delete exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-ip-permission</name>
      <module-name>ietf-ip</module-name>
      <access-operations>create read update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-interfaces-permission</name>
      <module-name>ietf-interfaces</module-name>
      <access-operations>create read update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>iana-if-type-permission</name>
      <module-name>iana-if-type</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-inet-types-permission</name>
      <module-name>ietf-inet-types</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-processing-elements-permission</name>
      <module-name>o-ran-processing-elements</module-name>
      <access-operations>create read update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-mplane-interfaces-permission</name>
      <module-name>o-ran-mplane-interfaces</module-name>
      <access-operations>create read update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-dhcp-permission</name>
      <module-name>o-ran-dhcp</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-troubleshooting-permission</name>
      <module-name>o-ran-troubleshooting</module-name>
      <access-operations>exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-trace-permission</name>
      <module-name>o-ran-trace</module-name>
      <access-operations>exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-netconf-acm-permission</name>
      <module-name>ietf-netconf-acm</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-yang-library-permission</name>
      <module-name>ietf-yang-library</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-netconf-monitoring-permission</name>
      <module-name>ietf-netconf-monitoring</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
  </rule-list>
  <rule-list>
    <name>fm-pm-access</name>
    <group>fm-pm</group>
    <rule>
      <name>ietf-hardware-permission</name>
      <module-name>ietf-hardware</module-name>
      <access-operations>read exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>iana-hardware-permission</name>
      <module-name>iana-hardware</module-name>
      <access-operations>read exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-fm-permission</name>
      <module-name>o-ran-fm</module-name>
      <access-operations>read exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-sync-permission</name>
      <module-name>o-ran-sync</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-delay-management-permission</name>
      <module-name>o-ran-delay-management</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-module-cap-permission</name>
      <module-name>o-ran-module-cap</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-operations-permission</name>
      <module-name>o-ran-operations</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-uplane-conf</name>
      <module-name>o-ran-uplane-conf</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-lbm-permission</name>
      <module-name>o-ran-lbm</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-software-management-permission</name>
      <module-name>o-ran-software-management</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-file-management-permission</name>
      <module-name>o-ran-file-management</module-name>
      <access-operations>exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-performance-management-permission</name>
      <module-name>o-ran-performance-management</module-name>
      <access-operations>create read update delete exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-transceiver-permission</name>
      <module-name>o-ran-transceiver</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-interfaces-permission</name>
      <module-name>o-ran-interfaces</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-ip-permission</name>
      <module-name>ietf-ip</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-interfaces-permission</name>
      <module-name>ietf-interfaces</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>iana-if-type-permission</name>
      <module-name>iana-if-type</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-inet-types-permission</name>
      <module-name>ietf-inet-types</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-processing-elements-permission</name>
      <module-name>o-ran-processing-elements</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-mplane-interfaces-permission</name>
      <module-name>o-ran-mplane-interfaces</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-dhcp-permission</name>
      <module-name>o-ran-dhcp</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-troubleshooting-permission</name>
      <module-name>o-ran-troubleshooting</module-name>
      <access-operations>exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-trace-permission</name>
      <module-name>o-ran-trace</module-name>
      <access-operations>exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-netconf-acm-permission</name>
      <module-name>ietf-netconf-acm</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-yang-library-permission</name>
      <module-name>ietf-yang-library</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-netconf-monitoring-permission</name>
      <module-name>ietf-netconf-monitoring</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
  </rule-list>
  <rule-list>
    <name>swm-access</name>
    <group>swm</group>
    <rule>
      <name>o-ran-software-management-permission</name>
      <module-name>o-ran-software-management</module-name>
      <access-operations>create read update delete exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>iana-if-type-permission</name>
      <module-name>iana-if-type</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-inet-types-permission</name>
      <module-name>ietf-inet-types</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-netconf-acm-permission</name>
      <module-name>ietf-netconf-acm</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-yang-library-permission</name>
      <module-name>ietf-yang-library</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-netconf-monitoring-permission</name>
      <module-name>ietf-netconf-monitoring</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-netconf-permission</name>
      <module-name>ietf-netconf</module-name>
      <access-operations>exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-usermgmt-permission</name>
      <module-name>o-ran-usermgmt</module-name>
      <path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:users/o-ran-usermgmt:user/o-ran-usermgmt:name</path>
      <access-operations>*</access-operations>
      <action>permit</action>
    </rule>
  </rule-list>
</nacm>



But I am not able to get username in swm group user. Can you please help me solve this issue?

**Comment by Abrahamma97** [comment]
Hi Can anybody help?

**Comment by Abrahamma97** [comment]
Hi @michalvasko 
Can you help out

**Comment by michalvasko** [comment]
What *netopeer2* version are you using? There are some bugfixes in NACM in the `devel` branch.

**Comment by Abrahamma97** [comment]
I am using latest netopeer2 from master

**Comment by michalvasko** [comment]
Well, yes, unless you encounter bugs, when you should switch to `devel` to get the most recent bugfixes. Note that in that case you also need `devel` of *libyang*, *sysrepo*, and *libnetconf2*.

**Comment by Abrahamma97** [comment]
Hi @michalvasko  is this issue already fixed in the develop  branch?

**Comment by michalvasko** [comment]
Yes, I do believe so. Even if not, I would try to fix it only if you have the problem on `devel`, otherwise I could not be sure it was not fixed.

**Comment by Abrahamma97** [comment]
Hi @michalvasko 
<rule>
      <name>o-ran-usermgmt-permission</name>
      <module-name>o-ran-usermgmt</module-name>
      <path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:users/o-ran-usermgmt:user/o-ran-usermgmt:name</path>
      <access-operations>*</access-operations>
      <action>permit</action>
    </rule>
I have updated this configuration in develop and still it is not getting reflected. I have given default deny and am not able to get username. If I remove <path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:users/o-ran-usermgmt:user/o-ran-usermgmt:name</path> then I am able to access everything. What I want to do is to permit everything other than password leaf. Can you help @michalvasko

**Comment by michalvasko** [comment]
Okay, please pull *netopeer2* and try again, I hope I have fixed it.

**Comment by Abrahamma97** [comment]
Hi @michalvasko,
I had tried this again ....
`<rule>
      <name>o-ran-usermgmt-permission</name>
      <module-name>o-ran-usermgmt</module-name>
      <path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:users/o-ran-usermgmt:user/o-ran-usermgmt:name</path>
      <access-operations>*</access-operations>
      <action>permit</action>
    </rule>`
with latest commit and this time everything is getting displayed in usermanager. Actually I want only to see like this '<users xmlns="urn:o-ran:user-mgmt:1.0">
  <user>
    <name>oranuser</name>
    <account-type>PASSWORD</account-type>
    <enabled>true</enabled>
  </user>
  <user>' 
But here I am getting like this only 
'<users xmlns="urn:o-ran:user-mgmt:1.0">
  <user>
    <name>oranuser</name>
    <account-type>PASSWORD</account-type>
    <password>oranuser</password>
    <enabled>true</enabled>
  </user>
  <users>'
Can you help out?? This is the latest develop branch

**Comment by michalvasko** [comment]
It works just fine for me.

Test module and data:
```yang
module test {
  namespace "urn:test";
  prefix t;

  container cont {
    list list1 {
      key "k";
      leaf k {
        type string;
      }

      leaf l1 {
        type string;
      }

      leaf l2 {
        type string;
      }

      leaf l3 {
        type string;
      }
    }
  }
}
```
```xml

<cont xmlns="urn:test">
  <list1>
    <k>k1</k>
    <l1>l1val1</l1>
    <l2>l2val1</l2>
    <l3>l3val1</l3>
  </list1>
  <list1>
    <k>k2</k>
    <l1>l1val2</l1>
    <l2>l2val2</l2>
    <l3>l3val2</l3>
  </list1>
</cont>
```

NACM config:
```xml
<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
  <enable-nacm>true</enable-nacm>
  <read-default>deny</read-default>
  <write-default>deny</write-default>
  <exec-default>permit</exec-default>
  <enable-external-groups>false</enable-external-groups>
  <groups>
    <group>
      <name>testgroup</name>
      <user-name>vasko</user-name>
    </group>
  </groups>
  <rule-list>
    <name>testrules</name>
    <group>testgroup</group>
    <rule>
      <name>testrule1</name>
      <module-name>test</module-name>
      <path xmlns:t="urn:test">/t:cont/t:list1/t:l1</path>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>testrule2</name>
      <module-name>test</module-name>
      <path xmlns:t="urn:test">/t:cont/t:list1/t:l3</path>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
  </rule-list>
</nacm>
```
Connected to the server and logged as `vasko`, these are all the commands I tried:
```
> get-config --source running --filter-xpath /test:cont/list1
DATA
<cont xmlns="urn:test">
  <list1>
    <k>k1</k>
    <l1>l1val1</l1>
    <l3>l3val1</l3>
  </list1>
  <list1>
    <k>k2</k>
    <l1>l1val2</l1>
    <l3>l3val2</l3>
  </list1>
</cont>

> get-config --source running --filter-xpath /test:cont/list1/k
DATA

> get-config --source running --filter-xpath /test:cont/list1/l1
DATA
<cont xmlns="urn:test">
  <list1>
    <k>k1</k>
    <l1>l1val1</l1>
  </list1>
  <list1>
    <k>k2</k>
    <l1>l1val2</l1>
  </list1>
</cont>

> get-config --source running --filter-xpath /test:cont/list1/l3
DATA
<cont xmlns="urn:test">
  <list1>
    <k>k1</k>
    <l3>l3val1</l3>
  </list1>
  <list1>
    <k>k2</k>
    <l3>l3val2</l3>
  </list1>
</cont>

> get-config --source running --filter-xpath /test:cont/list1/l2
DATA

>
```

**Comment by Abrahamma97** [comment]
Hi @michalvasko , Yes when we login as a normal user I am able to get the correct configuration. For example if I create a user like "Vasco" or "User2" it works perfectly when I login as the Vasco or User2.

 But when I login as root I am able to get everything. Kindly note that Vasco and root are put in the same group called sudo.

**Comment by michalvasko** [comment]
Then it works correctly, *netopeer2* support [recovery session](https://tools.ietf.org/html/rfc8341#section-3.3.3) which is by default UID 0, `root`. You can change it by setting the compile-time variable `NACM_RECOVERY_UID`.

**Comment by Abrahamma97** [comment]
Hi @michalvasko ,
Thanks for your reply. One question is so in which netconf-acm  group should I place root in. Or is that not needed as root is recovery session

**Comment by michalvasko** [comment]
You should not place the recovery session user in any group, it will always be the recovery session no matter what is the NACM configuration.

Yes, there will be a new release today.

**Comment by Abrahamma97** [comment]
Hi @michalvasko ,
Great news. Will wait for the same then.
