### ISSUE TITLE
Invalid arguments (lyd_find_path()) in <get> operation

### ISSUE THREAD

**Issue by iljatab** [CESNET/netopeer2#805]
$ yanglint --version
yanglint SO 1.9.22
$ sysrepoctl --version
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.96 (SO v5.6.12)
$ netopeer2-server -V
netopeer2-server 1.1.49

Hi Michal,

We have an issue with `get` requests .

Say, we have openconfig-interfaces.yang model installed in sysrepo, however it applies to any model.

At this time our back-end application have no sysrepo subscriptions for openconfig-interfaces.yang.
No configuration change subscription, no state data subscription, no rpc subscription.
There are no objects (interfaces) configured in openconfig-interfaces.yang model - neither startup nor running.

Now, doing `get-config` we get a reasonable empty data set:
```
> get-config --source running --filter-xpath=/openconfig-interfaces:*
DATA

>
```

However `get` returns an error:
```
> get --filter-xpath=/openconfig-interfaces:*
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  libyang error

>
```

The log messages are not really helpful, even with max log level for netopeer2-server:
```
Jan 13 19:46:40.712252 A8-C7 err netopeer2-server[709]: Invalid arguments (lyd_find_path()).
Jan 13 19:46:40.712749 A8-C7 err netopeer2-server[709]: Failed to send an RPC (User callback failed).
```

Could you please clarify if this is expected behavior or is it a bug?

I agree that such use case might look strange, but we have same `get` error also in regular use cases, when subscriptions from applications are there. I just cannot yet provide a detailed scenario.

BRGDS,

Ilja.

**Comment by iljatab** [comment]
Hi Michal,

Sorry to disturb.
If possible, could you please comment on this issue?

Thanks in advance,
Ilja.

**Comment by michalvasko** [comment]
Sorry, too much work and issues. Should be fixed now.

**Comment by iljatab** [comment]
Thanks a lot!
