### ISSUE TITLE
passwordless ssh into netopeer2 server

### ISSUE THREAD

**Issue by ashishsaxenahsc** [CESNET/netopeer2#807]
Hi all,

We are using latest netopeer (version 1.1.39) , and it is require to do passswordless ssh into netopeer server . What configuration shall we use to achieve this ?  

Thanks and Regards,
Ashish

**Comment by michalvasko** [comment]
Use SSH keys. *netopeer2* reads them from `authorized_keys` of the authenticating user.

**Comment by ashishsaxenahsc** [comment]
Hi Michal,

Thanks for the reply.
I have added the SSH keys of the remote client into the authorized_keys of the netipeer2 server at path: /root/.ssh/authorized_keys

 But still , I am unable to access the netopeer2 server from remote client.
Do we need to do anything else apart from this?

Thanks and Regards,
Ashish

**Comment by michalvasko** [comment]
Well, are you connecting to *netopeer2-server* as `root`? If yes, it should work, if not, then it will not work.

**Comment by ashishsaxenahsc** [comment]
Hi Michal,

I copied keys of root user and now it is working .

Thanks for your help.
Regards,
Ashish
