### ISSUE TITLE
During robust testing , observed some logs, and need clarity

### ISSUE THREAD

**Issue by manmohanpatel2005** [CESNET/netopeer2#808]
We are using below version of Netopeer2 server.
[root@localhost ~]# netopeer2-server -V
netopeer2-server 1.1.43

We Performed some robustness testing where, at the same time below 2 steps were executed, 
1. triggered edit-config (running datastore) from netconf client to server
2. triggered notification from application to netconf client (using sysrepo)
3. We observed below log:
```
| INFO | SR | netopeer2-server | Published event "change" "_3gpp-common-managed-element" with ID 21 priority 0 for 1 subscribers. |
| INFO | SR | netopeer2-server | Event "change" with ID 21 priority 0 succeeded. |
| INFO | SR | netopeer2-server | Published event "done" "_3gpp-common-managed-element" with ID 21 priority 0 for 1 subscribers. |
| INFO | SR | netopeer2-server | Published event "notif" "ietf-netconf-notifications" with ID 8 priority 0 for 1 subscribers. |
| INFO | LY | netopeer2-server | Resolving unresolved data nodes and their constraints... |
| INFO | LY | netopeer2-server | There is no instance of "/_3gpp-common-managed-element:ManagedElement[id='MEid']/attributes/dnPrefix", but it is not required. |
| INFO | SR | netopeer2-server | Successful processing of "rpc" event with ID 21 priority 0 (remaining 0 subscribers). |
| INFO | LY | netopeer2-server | There is no instance of "/_3gpp-common-managed-element:ManagedElement[id='MEid']/_3gpp-nr-nrm-gnbdufunction:GNBDUFunction[id='GNbduID']/attributes/gNBId", but it is not required. |
| INFO | LY | netopeer2-server | All data nodes and constraints resolved. |
```

Can you please help us understand what do these logs signify? Does it mean there is any issue? Any new version of software to avoid such logs ?
I could see both edit-config and notification working successfully, so not able to conclude what these logs are signifying.

Br,
MMP

**Comment by michalvasko** [comment]
They are only `INFO` messages so they should inform about what is happening, never print any problems. You can safely ignore all of them, if you do not understand what they mean.

**Comment by manmohanpatel2005** [comment]
Thanks michalvasko for quick response.
