### ISSUE TITLE
Got 'too many open files' and 'Operation now in progress' error when Netopeer2-server callhome

### ISSUE THREAD

**Issue by rydy** [CESNET/netopeer2#813]

**Comment by rydy** [comment]
Hi Michal,
    If the callhome address is configured as a non-accessed address, After a while, netopeer2-server will report "[Bad file descriptor](https://github.com/CESNET/libnetconf2/issues/244)" error.,I have tried [this patch](https://github.com/CESNET/libnetconf2/commit/2af7c38390b6f10698d90f5609bef9860a771b48) and occasionally I get 'Operation now in progress' wrong.
log as fllow :
```
[INF]: LN: Call Home client "default-client" connecting...
[INF]: LN: Trying to connect via IPv4 to 192.168.160.1:4334.
[INF]: LN: Successfully connected to 192.168.160.1:4334 over IPv4.
[INF]: SR: Session 165 (user "root") created.
[ERR]: LN: SSH key exchange timeout.
[INF]: LN: Trying to connect via IPv4 to 192.168.160.1:4334.
[INF]: LN: Timed out after 5s (Operation now in progress).
[INF]: LN: Trying to connect the pending socket=34.
[INF]: LN: Timed out after 5s (Operation now in progress).
[INF]: LN: Trying to connect the pending socket=34.
[INF]: LN: Timed out after 5s (Operation now in progress).
[INF]: LN: Trying to connect the pending socket=34.
[INF]: LN: Timed out after 5s (Operation now in progress).
[INF]: LN: Trying to connect the pending socket=34.
[INF]: LN: Timed out after 5s (Operation now in progress).
[INF]: LN: Trying to connect the pending socket=34.
[INF]: LN: Timed out after 5s (Operation now in progress).
[INF]: LN: Trying to connect the pending socket=34.
[INF]: LN: Timed out after 5s (Operation now in progress).
[INF]: LN: Trying to connect the pending socket=34.
[INF]: LN: Timed out after 5s (Operation now in progress).
[INF]: LN: Trying to connect the pending socket=34.
[INF]: LN: Timed out after 5s (Operation now in progress).
[INF]: LN: Trying to connect the pending socket=34.
[INF]: LN: Timed out after 5s (Operation now in progress).
[INF]: LN: Trying to connect the pending socket=34.
[INF]: LN: Timed out after 5s (Operation now in progress).
[INF]: LN: Trying to connect the pending socket=34.
[INF]: LN: Timed out after 5s (Operation now in progress).
[INF]: LN: Trying to connect the pending socket=34.
[INF]: LN: Timed out after 5s (Operation now in progress).
[INF]: LN: Trying to connect the pending socket=34.
[INF]: LN: Timed out after 5s (Operation now in progress).
[INF]: LN: Trying to connect the pending socket=34.
[INF]: LN: Timed out after 5s (Operation now in progress).
[INF]: LN: Trying to connect the pending socket=34.
[INF]: LN: Timed out after 5s (Operation now in progress).
[INF]: LN: Trying to connect the pending socket=34.
[INF]: LN: Timed out after 5s (Operation now in progress).
[INF]: LN: Trying to connect the pending socket=34.
[INF]: LN: Timed out after 5s (Operation now in progress).
[INF]: LN: Trying to connect the pending socket=34.
[INF]: LN: Timed out after 5s (Operation now in progress).
[INF]: LN: Trying to connect the pending socket=34.
[INF]: LN: Timed out after 5s (Operation now in progress).
[INF]: LN: Trying to connect the pending socket=34.
[INF]: LN: Timed out after 5s (Operation now in progress).
[INF]: LN: Trying to connect the pending socket=34.
[INF]: SR: Session 211 (user "root") created.
[ERR]: LN: SSH key exchange timeout.
[INF]: LN: Trying to connect via IPv4 to 192.168.160.1:4334.
[INF]: LN: Timed out after 5s (Operation now in progress).
[INF]: LN: Trying to connect the pending socket=34.
[INF]: LN: Timed out after 5s (Operation now in progress).
[INF]: LN: Trying to connect the pending socket=34.
[INF]: LN: Timed out after 5s (Operation now in progress).
[INF]: LN: Trying to connect the pending socket=34.
[INF]: SR: Session 221 (user "root") created.
[ERR]: LN: SSH key exchange timeout.
```
Is there a problem with [this patch](https://github.com/CESNET/libnetconf2/commit/2af7c38390b6f10698d90f5609bef9860a771b48)?What do you suggest? 

Best regards,
thanks.

**Comment by michalvasko** [comment]
So this happens only sometimes? Like I wrote in the commit, SSH key exchange timeout is a fatal error. Can you also post your Call Home configuration? But I am not really sure what to do about this.

**Comment by rydy** [comment]
netconf server configuration as fllow:
```
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <listen>
    <endpoint>
      <name>default-ssh</name>
      <ssh>
        <tcp-server-parameters>
          <local-address>10.0.0.94</local-address>
          <keepalives>
            <idle-time>1</idle-time>
            <max-probes>10</max-probes>
            <probe-interval>5</probe-interval>
          </keepalives>
        </tcp-server-parameters>
        <ssh-server-parameters>
          <server-identity>
            <host-key>
              <name>default-key</name>
              <public-key>
                <keystore-reference>genkey</keystore-reference>
              </public-key>
            </host-key>
          </server-identity>
          <client-authentication>
            <supported-authentication-methods>
              <publickey/>
              <passsword/>
              <other>interactive</other>
            </supported-authentication-methods>
            <users/>
          </client-authentication>
        </ssh-server-parameters>
      </ssh>
    </endpoint>
  </listen>
  <call-home>
    <netconf-client>
      <name>default-client</name>
      <endpoints>
        <endpoint>
          <name>default-ssh</name>
          <ssh>
            <tcp-client-parameters>
              <remote-address>10.0.0.1</remote-address>
            </tcp-client-parameters>
            <ssh-server-parameters>
              <server-identity>
                <host-key>
                  <name>default-key</name>
                  <public-key>
                    <keystore-reference>genkey</keystore-reference>
                  </public-key>
                </host-key>
              </server-identity>
              <client-authentication>
                <supported-authentication-methods>
                  <publickey/>
                  <passsword/>
                  <other>interactive</other>
                </supported-authentication-methods>
                <users/>
              </client-authentication>
            </ssh-server-parameters>
          </ssh>
        </endpoint>
      </endpoints>
      <connection-type>
        <persistent/>
      </connection-type>
    </netconf-client>
  </call-home>
</netconf-server>
```
What is the reason for the timeout of  SSH key exchange?  The configured parameters(idle-time、max-probes and probe-interval) are not reasonable?

**Comment by michalvasko** [comment]
What *libssh* version are you using? That is most likely causing the key exchange timeout errors, it has nothing to do with your configuration.

**Comment by rydy** [comment]
> What _libssh_ version are you using? That is most likely causing the key exchange timeout errors, it has nothing to do with your configuration.
I used libssh0.9.4,  This error happens occasionally,After this error('Operation now in progress&SSH key exchange timeout.'), I tried to restart the netopeer2-serve, and it was fine after restart.

**Comment by michalvasko** [comment]
I would still advise you to update to *libssh* 0.9.5. Other than that, there is not much more I can do. In this scenario some *libssh* function returns a timeout for receiving SSH keys so it is retried, in hope that they will come later. However, the problem is most likely not in the timeout but rather that the other end is bugged and does not send the SSH keys at all.

Maybe there could be another much higher timeout introduced that will close the created socket. This whole mechanism was introduced by a PR when there actually was a use-case of needing to wait for the other end for quite a long time.

**Comment by rydy** [comment]
> I would still advise you to update to _libssh_ 0.9.5. Other than that, there is not much more I can do. In this scenario some _libssh_ function returns a timeout for receiving SSH keys so it is retried, in hope that they will come later. However, the problem is most likely not in the timeout but rather that the other end is bugged and does not send the SSH keys at all.
> 
> Maybe there could be another much higher timeout introduced that will close the created socket. This whole mechanism was introduced by a PR when there actually was a use-case of needing to wait for the other end for quite a long time.

I have one more question. Should both Netopeer2 server and client libssh use the unified version?

**Comment by rydy** [comment]
Is the reason for the  SSH key exchange timeout related to these configurations(idle-time、max-probes and probe-interval)?

**Comment by michalvasko** [comment]
> Should both Netopeer2 server and client libssh use the unified version?

Well, it is definitely not required, SSH 2.0 has its definition that all the libraries must be compliant with. However, it is recommended to avoid possible problems.

> Is the reason for the SSH key exchange timeout related to these configurations(idle-time、max-probes and probe-interval)?

No, I already told you it is not.

**Comment by rydy** [comment]
> > Should both Netopeer2 server and client libssh use the unified version?
> 
> Well, it is definitely not required, SSH 2.0 has its definition that all the libraries must be compliant with. However, it is recommended to avoid possible problems.
> 
> > Is the reason for the SSH key exchange timeout related to these configurations(idle-time、max-probes and probe-interval)?
> 
> No, I already told you it is not.
A new [version ](https://github.com/CESNET/netopeer2/releases/tag/v1.1.53)was released yesterday, which seems to fix a lot of issues? Is it recommended to update?

**Comment by michalvasko** [comment]
It is always recommended to use the latest version, especially if it is a new release. But it will most likely not help you with this particular issue.

**Comment by rydy** [comment]
> Hi Michal,
> If the callhome address is configured as a non-accessed address, After a while, netopeer2-server will report "[Bad file descriptor](https://github.com/CESNET/libnetconf2/issues/244)" error.,I have tried [this patch](https://github.com/CESNET/libnetconf2/commit/2af7c38390b6f10698d90f5609bef9860a771b48) and occasionally I get 'Operation now in progress' wrong.
> log as fllow :
> 
> ```
> [INF]: LN: Call Home client "default-client" connecting...
> [INF]: LN: Trying to connect via IPv4 to 192.168.160.1:4334.
> [INF]: LN: Successfully connected to 192.168.160.1:4334 over IPv4.
> [INF]: SR: Session 165 (user "root") created.
> [ERR]: LN: SSH key exchange timeout.
> [INF]: LN: Trying to connect via IPv4 to 192.168.160.1:4334.
> [INF]: LN: Timed out after 5s (Operation now in progress).
> [INF]: LN: Trying to connect the pending socket=34.
> [INF]: LN: Timed out after 5s (Operation now in progress).
> [INF]: LN: Trying to connect the pending socket=34.
> [INF]: LN: Timed out after 5s (Operation now in progress).
> [INF]: LN: Trying to connect the pending socket=34.
> [INF]: LN: Timed out after 5s (Operation now in progress).
> [INF]: LN: Trying to connect the pending socket=34.
> [INF]: LN: Timed out after 5s (Operation now in progress).
> [INF]: LN: Trying to connect the pending socket=34.
> [INF]: LN: Timed out after 5s (Operation now in progress).
> [INF]: LN: Trying to connect the pending socket=34.
> [INF]: LN: Timed out after 5s (Operation now in progress).
> [INF]: LN: Trying to connect the pending socket=34.
> [INF]: LN: Timed out after 5s (Operation now in progress).
> [INF]: LN: Trying to connect the pending socket=34.
> [INF]: LN: Timed out after 5s (Operation now in progress).
> [INF]: LN: Trying to connect the pending socket=34.
> [INF]: LN: Timed out after 5s (Operation now in progress).
> [INF]: LN: Trying to connect the pending socket=34.
> [INF]: LN: Timed out after 5s (Operation now in progress).
> [INF]: LN: Trying to connect the pending socket=34.
> [INF]: LN: Timed out after 5s (Operation now in progress).
> [INF]: LN: Trying to connect the pending socket=34.
> [INF]: LN: Timed out after 5s (Operation now in progress).
> [INF]: LN: Trying to connect the pending socket=34.
> [INF]: LN: Timed out after 5s (Operation now in progress).
> [INF]: LN: Trying to connect the pending socket=34.
> [INF]: LN: Timed out after 5s (Operation now in progress).
> [INF]: LN: Trying to connect the pending socket=34.
> [INF]: LN: Timed out after 5s (Operation now in progress).
> [INF]: LN: Trying to connect the pending socket=34.
> [INF]: LN: Timed out after 5s (Operation now in progress).
> [INF]: LN: Trying to connect the pending socket=34.
> [INF]: LN: Timed out after 5s (Operation now in progress).
> [INF]: LN: Trying to connect the pending socket=34.
> [INF]: LN: Timed out after 5s (Operation now in progress).
> [INF]: LN: Trying to connect the pending socket=34.
> [INF]: LN: Timed out after 5s (Operation now in progress).
> [INF]: LN: Trying to connect the pending socket=34.
> [INF]: LN: Timed out after 5s (Operation now in progress).
> [INF]: LN: Trying to connect the pending socket=34.
> [INF]: SR: Session 211 (user "root") created.
> [ERR]: LN: SSH key exchange timeout.
> [INF]: LN: Trying to connect via IPv4 to 192.168.160.1:4334.
> [INF]: LN: Timed out after 5s (Operation now in progress).
> [INF]: LN: Trying to connect the pending socket=34.
> [INF]: LN: Timed out after 5s (Operation now in progress).
> [INF]: LN: Trying to connect the pending socket=34.
> [INF]: LN: Timed out after 5s (Operation now in progress).
> [INF]: LN: Trying to connect the pending socket=34.
> [INF]: SR: Session 221 (user "root") created.
> [ERR]: LN: SSH key exchange timeout.
> ```
> 
> Is there a problem with [this patch](https://github.com/CESNET/libnetconf2/commit/2af7c38390b6f10698d90f5609bef9860a771b48)?What do you suggest?
> 
> Best regards,
> thanks.

**Comment by rydy** [comment]
When multiple 'SSH key exchange timeout & Operation now in progress ' errors occur, Netopeer2-server will block and will not print the log. If restart Netopeer2-server, it will work fine.

**Comment by michalvasko** [comment]
Repeating what you already written is not going to help. But maybe one more question, what NETCONF client are you connecting to?

**Comment by rydy** [comment]
> Repeating what you already written is not going to help. But maybe one more question, what NETCONF client are you connecting to?
