### ISSUE TITLE
netopeer2-server crashes after attempting to connect to it

### ISSUE THREAD

**Issue by Roky7250** [CESNET/netopeer2#814]
Hi, I am using the next versions of the software:

1) sysrepo from devel brach version 1.4.103 commit id = 2273ee4239781dcbbaa9b3064e29ec52bc62fdb2
2) libyang from devel branch version 1.0.213 commit id = 9148a0ab4616a3af33f604287c3414c513c958b6
3) libnetconf2 from devel branch version 1.4.36 commit id = d771fd9c8d9e4a91a174de3af55b2ca100d16b9c
4) netopeer2 from devel branch version 1.1.53 commit id = 2642955b8f9a14a88381c26da324aab542ca6a36

After installing sysrepo, netopeer2 and my sysrepo plugins on the device I attempted to connect to the netopeer2-server from another device that has netopeer2-cli installed.
Connection fails every time with a segmentation fault on the server-side.

Then I tried to connect to the device using python3 ncclient, but the same thing happens.
This is log on the server-side when I try to connect to the device with ncclient:

```
[INF]: LN: Accepted a connection on 0.0.0.0:830.
[INF]: SR: Session 3 (user "root", CID 2) created.
[2021/01/27 11:02:52.022984, 1] ssh_server_connection_callback:  SSH client banner: SSH-2.0-paramiko_2.7.1
[2021/01/27 11:02:52.023133, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-paramiko_2.7.1
[INF]: LN: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: LN: Received an SSH message "request-auth" of subtype "password".
[WRN]: LN: User authentication successful with an empty password!
[INF]: LN: User "root" authenticated.
[INF]: LN: Received an SSH message "request-channel-open" of subtype "session".
[INF]: LN: Received an SSH message "request-channel" of subtype "subsystem".
[INF]: SR: Session 4 (user "root", CID 2) created.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-start).
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: SR: Published event "rpc" "/ietf-netconf:get-config" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:get-config" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: SR: Successful processing of "rpc" event with ID 1 priority 0 (remaining 0 subscribers).
Segmentation fault
```
Can someone point me, where the problem is?
Regards

**Comment by michalvasko** [comment]
I cannot help you just with these logs but my guess would be that you are actually not using the latest version of some of the libraries, you can check that with `ldd netopeer2-server` and then look what libraries are actually used with `ldconfig -p`. If you think your setup if fine, then please provide `gdb` backtrace or `valgrind` output of *netopeer2-server* when it crashes.
