### ISSUE TITLE
Multithreading and multi-process questions

### ISSUE THREAD

**Issue by rydy** [CESNET/netopeer2#822]
Hi Michal,

   For netopeer2, libnetconf2 , sysrepo and libyang, I have the following questions.
   1. The  libnetconf2 , sysrepo and libyang interfaces multithreaded?
   2. Does the sysrepo database support multi-process access?

Best regards,
Thanks

**Comment by michalvasko** [comment]
1. Yes, all of those have multi-threaded support.
2. Details in the [docs](https://netopeer.liberouter.org/doc/sysrepo/master/html/index.html#threads).

**Comment by rydy** [comment]
> 1. Yes, all of those have multi-threaded support.
> 2. Details in the [docs](https://netopeer.liberouter.org/doc/sysrepo/master/html/index.html#threads).

I got it, thanks.
