### ISSUE TITLE
a61eb89 changes selection nodes functionality

### ISSUE THREAD

**Issue by syyyr** [CESNET/netopeer2#825]
Hi, I have found out that https://github.com/CESNET/netopeer2/commit/a61eb8983e5253bed6c770752cbc924b508509f9 changes how selection nodes work.
This is my schema:
```yang
module netopeer2-change-list {
  yang-version 1.1;
  prefix aha;
  namespace "http://example.com";

  list ports {
    key 'name';
    leaf name {
      type string;
    }

    leaf type {
      type string;
    }
  }
}
```
And this is my data:
```xml
<ports xmlns="http://example.com">
  <name>AHOJ</name>
  <type>AHOJ</type>
</ports>
```
Now if I connect to Netopeer via netopeer2-cli and use this command:
```
get --filter-subtree
```
And use this filter:
```xml
<ports xmlns="http://example.com">
  <name/>
</ports>
```
then, if I understand https://tools.ietf.org/html/rfc6241#section-6.2.4 correctly, I should only get this output:
```xml
<ports xmlns="http://example.com">
  <name>AHOJ</name>
</ports>
```
This is the way it worked until https://github.com/CESNET/netopeer2/commit/a61eb8983e5253bed6c770752cbc924b508509f9. After this commit I get this data:
```xml
<ports xmlns="http://example.com">
  <name>AHOJ</name>
  <type>AHOJ</type>
</ports>
```
What's your opinion on this?

**Comment by michalvasko** [comment]
Yes, I believe you are right, please follow a duplicate issue #824.

**Comment by syyyr** [comment]
Sorry, I didn't check for duplicate issues. Thank you.

**Comment by michalvasko** [comment]
Sorry, it was not really the exact same issue, so it is not a duplicate. Should be fixed now.
