### ISSUE TITLE
User manager change password rpc not working

### ISSUE THREAD

**Issue by Abrahamma97** [CESNET/netopeer2#827]
Hi @michalvasko ,
When giving the change password rpc,
`<chg-password xmlns="urn:o-ran:user-mgmt:1.0">
	<currentPassword>swagbgm</currentPassword>
	<newPassword>swagillabgm</newPassword>
	<newPasswordConfirm>swagillabgm</newPasswordConfirm>
</chg-password>`
I get the following error
> edit-config --target running --config   --defop replace
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	path:     /o-ran-usermgmt:chg-password
	message:  Unexpected rpc node "chg-password".

Can you give the reason why this is happening. This is latest develop release.

**Comment by michalvasko** [comment]
My guess is that `chg-password` is defined as RPC in your YANG module. For that you cannot use `edit-config` because that is also a RPC. Use `user-rpc` instead, with the same data content.

**Comment by Abrahamma97** [comment]
Hi @michalvasko ,
Yes I understand it was a  mistake from my part.
Thanks now it worked
Cheers!.
