### ISSUE TITLE
Default NACM config

### ISSUE THREAD

**Issue by syyyr** [CESNET/netopeer2#829]
Hi, I'm setting up NACM for our apps and I saw that there is no default configuration for modules which Netopeer2 itself uses. For example, the default configuration is that everyone can read the server private key. This seems like a security issue. The solution could be to just deny access to the Netopeer modules. However, that'll stop working if at some point Netopeer implements a new module. The other solution is to deny access to everything (even read) and then selectively pick what I want. What is your opinion on this? Maybe there is another solution to this?

cc @jktjkt

**Comment by michalvasko** [comment]
> the default configuration is that everyone can read the server private key

You are right and it was a regression bug after last changes, it should be fixed now. [This](https://github.com/CESNET/Netopeer2/#nacm) should be default configuration that I consider is safe enough since it just uses the default values from `ietf-netconf-acm`.
