### ISSUE TITLE
Question related to imported module?

### ISSUE THREAD

**Issue by Roky7250** [CESNET/netopeer2#831]
Hi, I have a question related to the module that is imported inside another module but only for using datatypes.
For example, I have a module called "main-module" and "tmp-module".

The main module contains containers and leaves that I am implementing.
"tmp-module" is imported inside "main-module" because I use datatypes from it, nothing else.

Problem is that "tmp-module" is showing up in the capabilities of netconf, because "main-module" depends on it.
That module is not actually implemented and I do not provide NETCONF data for it.
Imported yang module "tmp-module" is a legacy module and I don't want it to be shown inside the capabilities.

So my question is can I somehow hide "tmp-module" so it not shown in capabilities?
I found this inside [RFC7950 ](https://tools.ietf.org/html/rfc7950#section-5.6.5) :
```
   If a server implements a module A that imports a module C without
   specifying the revision date of module C and the server does not
   implement C (e.g., if C only defines some typedefs), the server MUST
   list module C in the "/modules-state/module" list from
   "ietf-yang-library" [RFC7895], and it MUST set the leaf
   "conformance-type" to "import" for this module.
```

Or I will have to move all datatypes that I am using from "tmp-module" and put them inside "main-module".
After that "tmp-module" will no longer exist.

Regards

**Comment by michalvasko** [comment]
It depends what exactly is the dependency of `main-module` on `tmp-module`. If it really does not need to be implemented, it should not be when you do not install it directly into *sysrepo*, but just implicitly when installing `main-module`. But if you did that and `tmp-module` is implemented, it means it needs to be.
