### ISSUE TITLE
change password rpc not getting proper NACM

### ISSUE THREAD

**Issue by Abrahamma97** [CESNET/netopeer2#834]
Hi @michalvasko ,
When I give change password rpc the following is shown.
```
> user-rpc --content /home/Bigil/Desktop/validated/user_rpc.xml
ERROR
	type:     application
	tag:      access-denied
	severity: error
	path:     /o-ran-usermgmt:chg-password
	message:  Executing the operation is denied because "Bigil" NACM authorization failed.
```

This issue is seen but I have set nacm as below...
```xml
<rule>
      <name>o-ran-usermgmt-permission1</name>
      <module-name>o-ran-usermgmt</module-name>
      <path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:users/o-ran-usermgmt:user/o-ran-usermgmt:name</path>
      <access-operations>create read update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-usermgmt-permission2</name>
      <module-name>o-ran-usermgmt</module-name>
      <path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:users/o-ran-usermgmt:user/o-ran-usermgmt:account-type</path>
      <access-operations>create read update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-usermgmt-permission3</name>
      <module-name>o-ran-usermgmt</module-name>
      <path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:users/o-ran-usermgmt:user/o-ran-usermgmt:password</path>
      <access-operations>create update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-usermgmt-permission4</name>
      <module-name>o-ran-usermgmt</module-name>
      <path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:users/o-ran-usermgmt:user/o-ran-usermgmt:enabled</path>
      <access-operations>create read update delete</access-operations>
      <action>permit</action>
    </rule>
<rule>
      <name>o-ran-usermgmt-permission5</name>
      <module-name>o-ran-usermgmt</module-name>
      <path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:users/o-ran-usermgmt:chg-password</path>
      <access-operations>*</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-usermgmt-permission6</name>
      <module-name>o-ran-usermgmt</module-name>
      <path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:users/o-ran-usermgmt:chg-password/o-ran-usermgmt:currentPassword</path>
      <access-operations>*</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-usermgmt-permission7</name>
      <module-name>o-ran-usermgmt</module-name>
      <path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:users/o-ran-usermgmt:chg-password/o-ran-usermgmt:newPassword</path>
      <access-operations>*</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-usermgmt-permission8</name>
      <module-name>o-ran-usermgmt</module-name>
      <path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:users/o-ran-usermgmt:chg-password/o-ran-usermgmt:newPasswordConfirm</path>
      <access-operations>*</access-operations>
      <action>permit</action>
    </rule>
```

Please note that I am using latest release. Kindly tell me if there is a fix for this??

**Comment by michalvasko** [comment]
The error path mentions `/o-ran-usermgmt:chg-password` but in your NACM I see only `/o-ran-usermgmt:users/o-ran-usermgmt:chg-password`. Which of the paths is wrong?

**Comment by Abrahamma97** [comment]
Sorry the latter was wrong.... I have updated the rule list but still I am not able to change my password. Kindly see below
`<rule>
      <name>o-ran-usermgmt-permission5</name>
      <module-name>o-ran-usermgmt</module-name>
      <path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:chg-password</path>
      <access-operations>*</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-usermgmt-permission6</name>
      <module-name>o-ran-usermgmt</module-name>
      <path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:chg-password/o-ran-usermgmt:currentPassword</path>
      <access-operations>*</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-usermgmt-permission7</name>
      <module-name>o-ran-usermgmt</module-name>
      <path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:chg-password/o-ran-usermgmt:newPassword</path>
      <access-operations>*</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-usermgmt-permission8</name>
      <module-name>o-ran-usermgmt</module-name>
      <path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:chg-password/o-ran-usermgmt:newPasswordConfirm</path>
      <access-operations>*</access-operations>
      <action>permit</action>
    </rule>`

Still this error is coming 
> user-rpc --content /home/Bigileee/Desktop/validated/user_rpc.xml
ERROR
	type:     application
	tag:      access-denied
	severity: error
	path:     /o-ran-usermgmt:chg-password
	message:  Executing the operation is denied because "Bigileee" NACM authorization failed.

**Comment by michalvasko** [comment]
Could I see the full NACM configuration? It should work this way, as long as the rule is applied.

**Comment by Abrahamma97** [comment]
yes
`<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
<enable-nacm>true</enable-nacm>
<read-default>deny</read-default>
<write-default>deny</write-default>
<exec-default>deny</exec-default>
<enable-external-groups>false</enable-external-groups>
<groups>
	<group>
		<name>sudo</name>
		<user-name>Bigileee</user-name>
	</group>
	<group>
		<name>nms</name>
		<user-name>Master</user-name>
		</group>
	<group>
		<name>swm</name>
		<user-name>oshinshilin</user-name>
	</group>
</groups>
<rule-list>
	<name>sudo-access</name>
	<group>sudo</group>
	<rule>
        <name>ietf-netconf-permission</name>
        <module-name>ietf-netconf</module-name>
        <access-operations>exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-supervision-permission</name>
        <module-name>o-ran-supervision</module-name>
        <access-operations>exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
		<name>o-ran-hardware-permission</name>
		<module-name>o-ran-hardware</module-name>
		<access-operations>read exec</access-operations>
		<action>permit</action>
	</rule>
	<rule>
		<name>ietf-hardware-permission</name>
		<module-name>ietf-hardware</module-name>
		<access-operations>create read update delete exec</access-operations>
		<action>permit</action>
	</rule>
	<rule>
        <name>iana-hardware-permission</name>
        <module-name>iana-hardware</module-name>
        <access-operations>create read update delete exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-usermgmt-permission1</name>
        <module-name>o-ran-usermgmt</module-name>
	<path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:users/o-ran-usermgmt:user/o-ran-usermgmt:name</path>
        <access-operations>create read update delete</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-usermgmt-permission2</name>
        <module-name>o-ran-usermgmt</module-name>
	<path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:users/o-ran-usermgmt:user/o-ran-usermgmt:account-type</path>
        <access-operations>create read update delete</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-usermgmt-permission3</name>
        <module-name>o-ran-usermgmt</module-name>
	<path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:users/o-ran-usermgmt:user/o-ran-usermgmt:password</path>
        <access-operations>create update delete</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-usermgmt-permission4</name>
        <module-name>o-ran-usermgmt</module-name>
	<path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:users/o-ran-usermgmt:user/o-ran-usermgmt:enabled</path>
        <access-operations>create read update delete</access-operations>
        <action>permit</action>
    </rule>
	<rule>
      <name>o-ran-usermgmt-permission5</name>
      <module-name>o-ran-usermgmt</module-name>
      <path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:chg-password</path>
      <access-operations>*</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-usermgmt-permission6</name>
      <module-name>o-ran-usermgmt</module-name>
      <path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:chg-password/o-ran-usermgmt:currentPassword</path>
      <access-operations>*</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-usermgmt-permission7</name>
      <module-name>o-ran-usermgmt</module-name>
      <path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:chg-password/o-ran-usermgmt:newPassword</path>
      <access-operations>*</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-usermgmt-permission8</name>
      <module-name>o-ran-usermgmt</module-name>
      <path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:chg-password/o-ran-usermgmt:newPasswordConfirm</path>
      <access-operations>*</access-operations>
      <action>permit</action>
    </rule>
    <rule>
        <name>o-ran-fm-permission</name>
        <module-name>o-ran-fm</module-name>
        <access-operations>read exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-sync-permission</name>
        <module-name>o-ran-sync</module-name>
        <access-operations>create read update delete</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-delay-management-permission</name>
        <module-name>o-ran-delay-management</module-name>
        <access-operations>create read update delete</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-module-cap-permission</name>
        <module-name>o-ran-module-cap</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-udp-echo-permission</name>
        <module-name>o-ran-udp-echo</module-name>
        <access-operations>create read update delete</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-operations-permission</name>
        <module-name>o-ran-operations</module-name>
        <access-operations>read exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-uplane-conf</name>
        <module-name>o-ran-uplane-conf</module-name>
        <access-operations>create read update delete exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-lbm-permission</name>
        <module-name>o-ran-lbm</module-name>
        <access-operations>create read update delete exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-software-management-permission</name>
        <module-name>o-ran-software-management</module-name>
        <access-operations>create read update delete exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-file-management-permission</name>
        <module-name>o-ran-file-management</module-name>
        <access-operations>exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-performance-management-permission</name>
        <module-name>o-ran-performance-management</module-name>
        <access-operations>create read update delete exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-transceiver-permission</name>
        <module-name>o-ran-transceiver</module-name>
        <access-operations>create read update delete</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-interfaces-permission</name>
        <module-name>o-ran-interfaces</module-name>
        <access-operations>create read update delete exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>ietf-ip-permission</name>
        <module-name>ietf-ip</module-name>
        <access-operations>create read update delete</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>ietf-interfaces-permission</name>
        <module-name>ietf-interfaces</module-name>
        <access-operations>create read update delete</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>iana-if-type-permission</name>
        <module-name>iana-if-type</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>ietf-inet-types-permission</name>
        <module-name>ietf-inet-types</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-processing-elements-permission</name>
        <module-name>o-ran-processing-elements</module-name>
        <access-operations>create read update delete</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-mplane-interfaces-permission</name>
        <module-name>o-ran-mplane-interfaces</module-name>
        <access-operations>create read update delete</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-dhcp-permission</name>
        <module-name>o-ran-dhcp</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-troubleshooting-permission</name>
        <module-name>o-ran-troubleshooting</module-name>
        <access-operations>exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-trace-permission</name>
        <module-name>o-ran-trace</module-name>
        <access-operations>exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>ietf-netconf-acm-permission</name>
        <module-name>ietf-netconf-acm</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>ietf-yang-library-permission</name>
        <module-name>ietf-yang-library</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>ietf-netconf-monitoring-permission</name>
        <module-name>ietf-netconf-monitoring</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
</rule-list>

<rule-list>
	<name>nms-access</name>
	<group>nms</group>
	<rule>
        <name>ietf-netconf-permission</name>
        <module-name>ietf-netconf</module-name>
        <access-operations>exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
		<name>o-ran-hardware-permission</name>
		<module-name>o-ran-hardware</module-name>
		<access-operations>read exec</access-operations>
		<action>permit</action>
	</rule>
	<rule>
		<name>ietf-hardware-permission</name>
		<module-name>ietf-hardware</module-name>
		<access-operations>create read update delete exec</access-operations>
		<action>permit</action>
	</rule>
	<rule>
        <name>iana-hardware-permission</name>
        <module-name>iana-hardware</module-name>
        <access-operations>create read update delete exec</access-operations>
        <action>permit</action>
    </rule>
		<rule>
        <name>o-ran-fm-permission</name>
        <module-name>o-ran-fm</module-name>
        <access-operations>read exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-sync-permission</name>
        <module-name>o-ran-sync</module-name>
        <access-operations>create read update delete</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-delay-management-permission</name>
        <module-name>o-ran-delay-management</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-module-cap-permission</name>
        <module-name>o-ran-module-cap</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-udp-echo-permission</name>
        <module-name>o-ran-udp-echo</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-operations-permission</name>
        <module-name>o-ran-operations</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-uplane-conf</name>
        <module-name>o-ran-uplane-conf</module-name>
        <access-operations>create read update delete exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-lbm-permission</name>
        <module-name>o-ran-lbm</module-name>
        <access-operations>create read update delete</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-software-management-permission</name>
        <module-name>o-ran-software-management</module-name>
        <access-operations>create read update delete exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-file-management-permission</name>
        <module-name>o-ran-file-management</module-name>
        <access-operations>exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-performance-management-permission</name>
        <module-name>o-ran-performance-management</module-name>
        <access-operations>create read update delete exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-transceiver-permission</name>
        <module-name>o-ran-transceiver</module-name>
        <access-operations>create read update delete exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-interfaces-permission</name>
        <module-name>o-ran-interfaces</module-name>
        <access-operations>create read update delete exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>ietf-ip-permission</name>
        <module-name>ietf-ip</module-name>
        <access-operations>create read update delete</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>ietf-interfaces-permission</name>
        <module-name>ietf-interfaces</module-name>
        <access-operations>create read update delete</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>iana-if-type-permission</name>
        <module-name>iana-if-type</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>ietf-inet-types-permission</name>
        <module-name>ietf-inet-types</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-processing-elements-permission</name>
        <module-name>o-ran-processing-elements</module-name>
        <access-operations>create read update delete</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-mplane-interfaces-permission</name>
        <module-name>o-ran-mplane-interfaces</module-name>
        <access-operations>create read update delete</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-dhcp-permission</name>
        <module-name>o-ran-dhcp</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-troubleshooting-permission</name>
        <module-name>o-ran-troubleshooting</module-name>
        <access-operations>exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-trace-permission</name>
        <module-name>o-ran-trace</module-name>
        <access-operations>exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>ietf-netconf-acm-permission</name>
        <module-name>ietf-netconf-acm</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>ietf-yang-library-permission</name>
        <module-name>ietf-yang-library</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>ietf-netconf-monitoring-permission</name>
        <module-name>ietf-netconf-monitoring</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
</rule-list>
<rule-list>
	<name>fm-pm-access</name>
	<group>fm-pm</group>
	<rule>
        <name>ietf-netconf-permission</name>
        <module-name>ietf-netconf</module-name>
        <access-operations>exec</access-operations>
        <action>permit</action>
    	</rule>
	<rule>
		<name>ietf-hardware-permission</name>
		<module-name>ietf-hardware</module-name>
		<access-operations>read exec</access-operations>
		<action>permit</action>
	</rule>
	<rule>
        <name>iana-hardware-permission</name>
        <module-name>iana-hardware</module-name>
        <access-operations>read exec</access-operations>
        <action>permit</action>
    </rule>
		<rule>
        <name>o-ran-fm-permission</name>
        <module-name>o-ran-fm</module-name>
        <access-operations>read exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-sync-permission</name>
        <module-name>o-ran-sync</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-delay-management-permission</name>
        <module-name>o-ran-delay-management</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-module-cap-permission</name>
        <module-name>o-ran-module-cap</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-operations-permission</name>
        <module-name>o-ran-operations</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-uplane-conf</name>
        <module-name>o-ran-uplane-conf</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-lbm-permission</name>
        <module-name>o-ran-lbm</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-software-management-permission</name>
        <module-name>o-ran-software-management</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-file-management-permission</name>
        <module-name>o-ran-file-management</module-name>
        <access-operations>exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-performance-management-permission</name>
        <module-name>o-ran-performance-management</module-name>
        <access-operations>create read update delete exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-transceiver-permission</name>
        <module-name>o-ran-transceiver</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-interfaces-permission</name>
        <module-name>o-ran-interfaces</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>ietf-ip-permission</name>
        <module-name>ietf-ip</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>ietf-interfaces-permission</name>
        <module-name>ietf-interfaces</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>iana-if-type-permission</name>
        <module-name>iana-if-type</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>ietf-inet-types-permission</name>
        <module-name>ietf-inet-types</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-processing-elements-permission</name>
        <module-name>o-ran-processing-elements</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-mplane-interfaces-permission</name>
        <module-name>o-ran-mplane-interfaces</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-dhcp-permission</name>
        <module-name>o-ran-dhcp</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-troubleshooting-permission</name>
        <module-name>o-ran-troubleshooting</module-name>
        <access-operations>exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-trace-permission</name>
        <module-name>o-ran-trace</module-name>
        <access-operations>exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>ietf-netconf-acm-permission</name>
        <module-name>ietf-netconf-acm</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>ietf-yang-library-permission</name>
        <module-name>ietf-yang-library</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>ietf-netconf-monitoring-permission</name>
        <module-name>ietf-netconf-monitoring</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
</rule-list>
<rule-list>
	<name>swm-access</name>
	<group>swm</group>
	<rule>
        <name>ietf-netconf-permission</name>
        <module-name>ietf-netconf</module-name>
        <access-operations>exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>o-ran-software-management-permission</name>
        <module-name>o-ran-software-management</module-name>
        <access-operations>create read update delete exec</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>iana-if-type-permission</name>
        <module-name>iana-if-type</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>ietf-inet-types-permission</name>
        <module-name>ietf-inet-types</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>ietf-netconf-acm-permission</name>
        <module-name>ietf-netconf-acm</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>ietf-yang-library-permission</name>
        <module-name>ietf-yang-library</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
	<rule>
        <name>ietf-netconf-monitoring-permission</name>
        <module-name>ietf-netconf-monitoring</module-name>
        <access-operations>read</access-operations>
        <action>permit</action>
    </rule>
</rule-list>
</nacm>`

**Comment by Abrahamma97** [comment]
Can you help @michalvasko

**Comment by michalvasko** [comment]
Okay, I had to reproduce it myself to find out why it is not working but that is no excuse for you not reading the `ietf-netconf-acm` module nodes description. If you did, you would learn that the `path` node is *associated with the data node, action, or notification*. You cannot use it for an RPC.

**Comment by Abrahamma97** [comment]
Hi @michalvasko ,
Yes I got your point. But if I have to  permit everything in user manager except password. I will have to go with this scheme right? or in addition to this point should I just add  
`<rule>
      <name>o-ran-usermgmt-permission5</name>
      <module-name>o-ran-usermgmt</module-name>
      <path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:chg-password</path>
      <access-operations>*</access-operations>
      <action>permit</action>
    </rule>
`

**Comment by michalvasko** [comment]
> Yes I got your point.

No, I do not think you did. I told you to look into `ietf-netconf-acm`, did you? My point is that you are not supposed to use `path` but `rpc-name` instead, because that is what is used for RPCs, it will work then.

**Comment by Abrahamma97** [comment]
Yes Now I got it. Many thanks closing the same question.
