### ISSUE TITLE
subtree filter stopped working between commits c596ed5 and df3412c

### ISSUE THREAD

**Issue by gwendlan** [CESNET/netopeer2#835]
in netconf.c this particular code changed its behaviour:
```C
    /* now filter only the requested data from the created running data + state data */
    for (i = 0; i < filter_count; ++i) {
        set = lyd_find_path(ds_data, filters[i]); 
        if (!set) {
            rc = SR_ERR_LY;
            goto cleanup;
        }

        for (j = 0; j < set->number; ++j) {
            node = lyd_dup(set->set.d[j], LYD_DUP_OPT_RECURSIVE | LYD_DUP_OPT_WITH_PARENTS | LYD_DUP_OPT_WITH_KEYS |
                    LYD_DUP_OPT_WITH_WHEN);  <==== after this function has been called 
=== node contains only what filters[i] meant to filter for c596ed5 but
=== node contains all siblings of the top container, certainly much more than filters->filter[i].str meant to filter (code moved to op_filter_data_filter in common.c) for df3412c
=== filters[0] / filters.filter[0].str is "/namespace:container-A/list-A[key-A='key-value-A']/key-A"
            if (!node) {
                rc = SR_ERR_LY;
                goto cleanup;
            }

            /* always find parent */
            while (node->parent) {
                node = node->parent;
            }

            /* merge */
            if (!*data) {
=>              *data = node;
            } else if (node && lyd_merge(*data, node, LYD_OPT_DESTRUCT | LYD_OPT_EXPLICIT)) {
                lyd_free_withsiblings(node);
                rc = SR_ERR_LY;
                goto cleanup;
            }
        }
```

**Comment by gwendlan** [comment]
This is the subtree filter, it just follows the structure of the respective yang module. The idea is to get only (!) the value of leaf-C
container-A/list-A[key-A='key-value-A']/container-B/list-B[key-B='key-value-B']/container-C/list-C[key-C='key-value-C']/leaf-C.
It worked with c596ed5 but does not work with df3412c.
<container-A>
  <list-A>
    <key-A>key-value-A</key-A>
    <container-B>
      <list-B>
        <key-B>key-value-B</key-B>
        <container-C>
          <list-C>
            <key-C>key-value-C</key-C>
            <leaf-C>
            </leaf-C>
          </list-C>
        </container-C>
      </list-B>
    </container-B>
  </list-A>
</container-A>

**Comment by gwendlan** [comment]
`<container-A>
  <list-A>
    <key-A>key-value-A</key-A>
    <container-B>
      <list-B>
        <key-B>key-value-B</key-B>
        <container-C>
          <list-C>
            <key-C>key-value-C</key-C>
            <leaf-C>
            </leaf-C>
          </list-C>
        </container-C>
      </list-B>
    </container-B>
  </list-A>
</container-A>
`

**Comment by michalvasko** [comment]
So what is the difference exactly, that you are additionally getting `key-A`, `key-B` and `key-C` nodes?

**Comment by gwendlan** [comment]
It prints the whole subtree under container-A/list-A[key-A="key-value-As-sibling"]/...

**Comment by gwendlan** [comment]
Can you reproduce? Do you need more information? Unfortunately I could not find a mocka test case for netopeer2 which I could use as a copy base.

**Comment by michalvasko** [comment]
Yes, I have just fixed it. There are no tests, unfortunately, which I have been trying to remedy for some time now but the framework will not be simple and there are always something with higher priority.

**Comment by gwendlan** [comment]
I put in my local setup and it worked as expected now.
