### ISSUE TITLE
subscribe notifications by RPC /notifications:create-subscription

### ISSUE THREAD

**Issue by adamzyg** [CESNET/netopeer2#842]
For example, if I want to subscribe to /o-ran-software-management:download-event, can I use the user-rpc command, the content of this RPC is
```xml
<create-subscription xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
     <stream>o-ran-software-management</stream>
     <filter netconf:type="subtree">
         <download-event xmlns="urn:o-ran:software-management:1.0">
     </filter>
</create-subscription>
```

But in fact, when I use _user-rpc --content create-subscription.xml_ to subscribe to this notification, I did not receive the corresponding notification when the corresponding RPC was completed.

[create-subscriptions.zip](https://github.com/CESNET/netopeer2/files/6014047/create-subscriptions.zip)

**Comment by adamzyg** [comment]
hi @michalvasko , because the netconf client of my customer don't have the subscribe command like netopeer2-cli, they want subscribe the notifications. I think they should encapsulate an RPC with the same process as the subscribe command.

**Comment by adamzyg** [comment]
I have try this content:
```xml
<create-subscription xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
    <filter type="xpath" xmlns:o-ran-swm="urn:o-ran:software-management:1.0" select="/o-ran-swm:download-event"/>
</create-subscription>
```
But still haven't received the notifications.

**Comment by michalvasko** [comment]
The `create-subscription` RPCs seems fine, is the notification being generated? You must have a *sysrepo* application that calls `sr_event_notif_send()` before the notification can be received.

**Comment by adamzyg** [comment]
Hi @michalvasko there is a applications generating the notification, but the netopeer2-cli can not receive it.
if i subscribe the notification normally:
```
> subscribe --filter-xpath "/o-ran-software-management:download-event"
OK
> user-rpc --content userrpc-software-download.xml
DATA
<status xmlns="urn:o-ran:software-management:1.0">STARTED</status>
<notification-timeout xmlns="urn:o-ran:software-management:1.0">180</notification-timeout>

> 
notification (2019-09-24T11:45:12Z)
<download-event xmlns="urn:o-ran:software-management:1.0">
  <file-name>/tmp/download/AS-AV27-R1.2.1.zip</file-name>
  <status>COMPLETED</status>
</download-event>
```
 Then i exit from netopeer2-cli, and subscribe this notification by `user-rpc --content create-subscription.xml`. And then re-run the download application, nothing received. If i re-subscribe this notification, the error occurs:
```
root@oru-project:~# netopeer2-cli 
> connect 
Interactive SSH Authentication
Type your password:
Password: 
> user-rpc --content create-subscription.xml 
OK
> user-rpc --content userrpc-software-download.xml
DATA
<status xmlns="urn:o-ran:software-management:1.0">STARTED</status>
<notification-timeout xmlns="urn:o-ran:software-management:1.0">180</notification-timeout>

> 
> 
> 
> user-rpc --content create-subscription.xml 
nc ERROR: Session 2: received a <notification> but session is not subscribed.
cli_send_recv: Failed to receive a reply.
```

**Comment by michalvasko** [comment]
Okay, there was one thing to improve, the check whether notifications can be received was redundant and wrong, it is removed now. However, in *netopeer2-cli* only the `subscribe` command [starts the notification thread](https://github.com/CESNET/netopeer2/blob/master/cli/commands.c#L4597) that actually reads and prints the notifications. Without it, there is no thread/callback for notifications and *libnetconf2* does not know what to do with them, so they are simply buffered. That is why you will not see them in the CLI unless you call the `subscribe` command.

So, if you want to use our CLI, you must use `subscribe`. If you are using some other client based on *libnetconf2*, you must either start the notification thread the same way *netopeer2-cli* does or call periodically `nc_recv_notif()`.
