### ISSUE TITLE
--rpc-timeout 120 not getting reflected in edit-config

### ISSUE THREAD

**Issue by Abrahamma97** [CESNET/netopeer2#844]
Hi @michalvasko ,
--rpc-timeout 120  is failing as this is seen in 2 seconds. Should I reinstall netopeer2
```
edit-config --config --target running --defop replace --rpc-timeout 120
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	message:  Callback event "rpc" with ID 42 processing timed out.
```

**Comment by michalvasko** [comment]
What *netopeer2* version are you using? In the latest one it was renamed to `timeout` because it is more generic, its functionality was extended.

**Comment by michalvasko** [comment]
You most likely need to increase the timeout for *netopeer2-server* itself as well, use a parameter (seen in `--help`).

**Comment by Abrahamma97** [comment]
Hi @michalvasko ,
Yes when I gave parameter to netopeer2-server  also it worked. Thanks!
