### ISSUE TITLE
netopeer server exiting with exit code -7

### ISSUE THREAD

**Issue by hellonikita** [CESNET/netopeer2#845]
Hi

We are seeing a sporadic issue in our K8s container where netopeer server exits continuously.
Initially the return code is -7, later on subsequent restarts it changes to 1.
Can you please share your comments?

Logs:
Feb 20 12:36:57.544032 debug ruproxy-1-0 netopeer[124]: Starting netopeer2 Server.....
Feb 20 12:36:58.522142 debug ruproxy-1-0 sysrepoplugind[126]: Starting sys-repo plugind
Feb 20 12:36:59.510692 debug ruproxy-1-0 netopeer[124]:
Feb 20 12:36:59.511073 debug ruproxy-1-0 netopeer[124]:  Started netopeer2 return code  :-7
Feb 20 12:36:59.511188 debug ruproxy-1-0 netopeer[124]: -----------------
Feb 20 12:36:59.511327 info ruproxy-1-0 netopeer[124]: exiting Netopeer2

script:
        oam_logger.debug("Starting netopeer2 Server.....")
        command = "netopeer2-server -d -v 4"
        p = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE ,encoding='utf-8')
        out, err = p.communicate()
        oam_logger.debug(out)
        oam_logger.debug(" Started netopeer2 return code  :%s" % (p.returncode))

BR
Nikita

**Comment by michalvasko** [comment]
Could you please share the actual *netopeer2-server* logs?
