### ISSUE TITLE
XPath filtering NACM issue

### ISSUE THREAD

**Issue by awesomenode** [CESNET/netopeer2#846]
Hi!

I have a question regarding NACM in Netopeer2.

If I have a list, and I block every access operation on one of the list's leaf, for a
certain user, that user can still use the XPath filtering to filter with the node they
were denied access to.

E.g., If I have the following list:

```
list people {
        key "name";
        leaf name {
                type string;
        }
        leaf weight {
                type uint16;
                description "Blocked leaf";
        }
}
```

Using XPath filtering:
`//people[weight>'100']`

Will return the users weighing more than 100 correctly, thus exposing information to the
unauthorized user.

Is there a solution for this, or it's working as intended and NACM is simply not capable
hiding data like this?

netopeer2 version: 1.1.34

Thanks!

**Comment by michalvasko** [comment]
There were some major improvements in NACM so please try using the latest `devel` version. Let us know if there are some problems with that one.

**Comment by awesomenode** [comment]
Sadly, I can't seem to make the newest devel working. Although, browsing the code I cannot find any relevant part that explicitly checks if incoming XPath filter references unauthorized nodes (either directly like in my example, or with an XPath function), I might have just glossed over it.

Is there an upcoming new release to Netopeer2 soon, so I can check it with the docker image(https://hub.docker.com/r/sysrepo/sysrepo-netopeer2)? That usually works fine for me.

Thanks!

**Comment by michalvasko** [comment]
Not sure what the problem of making it work from source is but a new release should happen in a week or so.

**Comment by awesomenode** [comment]
Ok, I've managed to successfully start the newest Netopeer2 (sysrepo, libyang, libnetconf2 and Netopeer2 are all at the latest devel).

But it still seems to me it's not working properly. I'll attach the example config and module I've used.

Basically by denying access to anything inside a container, I couldn't retrieve any data from it. I could edit the data (except the denied one) and the change was properly set in the datastore (I checked it with sysrepocfg), but every get from the same container returned empty.

[nacm_issue.tar.gz](https://github.com/CESNET/netopeer2/files/6062419/nacm_issue.tar.gz)

**Comment by michalvasko** [comment]
Right, having default permit and rules for denying access was not properly tested, only the inverted scenario. Please try again now.

**Comment by awesomenode** [comment]
Ok, it works fine now, but my inital issue still stands.

Using the same config I attached, and adding some list items to the /test:basics/animals list (before adding the respective deny rule), when I execute the following:
```
<?xml version="1.0" encoding="utf-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="">
  <get>
    <filter type="xpath" xmlns:t="urn:com:test" select="//t:animals[weight>20]"/>
  </get>
</rpc>
```

netopeer2 will return every list item where the weight is larger than 20. Is this a security concern, or just an NACM limitation?

**Comment by michalvasko** [comment]
Reading your first post I understood what your original question is and you raise a good point. However, it seems our implementation is correct because this behaviour is [intentional](https://tools.ietf.org/html/rfc8341#section-3.2.4).

**Comment by awesomenode** [comment]
Ok, I've misunderstood that part as the filter is only applied to the readable subset of the datastore too. (So you cannot filter using unreadable nodes).

Thank you for your answer, seems like a NACM limitation then!
