### ISSUE TITLE
Performance issues for <edit-config> while netconf client create-subscribe 

### ISSUE THREAD

**Issue by yangtian127** [CESNET/netopeer2#847]
Hi Michal,
There is another issue for <create-subscribe>.
If a netconf client subscribe netconf-config-change notifications, edit-config a list with 10k entries, it will take a lot time.  about 30 second. if no netconf client subscribe, the time less than 1 second
The reason may be that it takes a lot of CPU time to generate netconf-config-change data.

**Comment by michalvasko** [comment]
> The reason may be that it takes a lot of CPU time to generate netconf-config-change data.

Well, yeah, obviously, but there is nothing we can do about this. You may want to wait some time, we are going to implement yang-push very soon (which is basically a much more complex mechanism that replaces this notification) that should allow to handle use-cases such as this one with a smaller performance impact.
