### ISSUE TITLE
issues in netopeera2 cross compilaton issues

### ISSUE THREAD

**Issue by syamkumarv** [CESNET/netopeer2#848]
Hi MIchalvasco,
i am trying to build netopeera2 (git file ) on x86 64bit  architecture ,little endian & ubuntu operating system.
Doing arm cross compilations on it.

**_i am getting issues in /path/netopeera2/build/sudo cmake .._**

i am getting following errors.
-- ******Unable to learn libnetconf2 thread support, check skipped******
-- Check if the system is big endian
-- Searching 16 bit integer
CMake Error at /usr/share/cmake-3.10/Modules/TestBigEndian.cmake:49 (message):
  no suitable type found
Call Stack (most recent call first):
  CMakeModules/UseCompat.cmake:20 (TEST_BIG_ENDIAN)
  CMakeLists.txt:171 (use_compat)
-- Configuring incomplete, errors occurred!
Regards
Syam

**Comment by michalvasko** [comment]
Could you please look at the actual error? It most likely has nothing to do with anything that was printed. Should be in `CMakeError.txt` or something like that.
