### ISSUE TITLE
callhome  configuration in start up datastore throws an error 

### ISSUE THREAD

**Issue by vishalwc** [CESNET/Netopeer2#85]
I am using devel-server branch ,call home is not recognized by sysrepo 

-bash-4.2$ sysrepo/build/src/sysrepocfg --import=stock_key_config.xml --format=xml --datastore=startup ietf-keystore
The new configuration was successfully applied.
-bash-4.2$ sysrepo/build/src/sysrepocfg --import=callhome.xml  --format=xml --datastore=startup ietf-netconf-server
[ERR] Data validation failed: Unknown element "call-home".
[ERR] Error by processing of commit request.
[ERR] Error returned from sr_commit: Validation of the changes failed.
[ERR] (null) : Validation of the changes failed
Errors were encountered during importing. Cancelling the operation.

=================callhome.xml  file content ====================

```xml
<netconf-server xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-server">
  <call-home>
    <netconf-client>
      <name>main</name>
      <ssh>
        <endpoints>
          <endpoint>
            <name>endpt_name</name>
            <address>127.0.0.1</address>
          </endpoint>
        </endpoints>
        <host-keys>
          <host-key>
          <name>rsa_key</name>
          <public-key>ssh_host_rsa_key</public-key>
          </host-key>
        </host-keys>
      </ssh>
      <connection-type>
        <persistent/>
      </connection-type>
    </netconf-client>
  </call-home>
</netconf-server>
```

**Comment by michalvasko** [comment]
Hi,
it's likely because `ietf-netconf-server` model does not have call-home feature enabled. It will be enabled as part of installation, but Call Home in general is not fully done yet, so I kept it disabled. Either use Call Home on your own and solve any problems without our help or wait a few days until I can finish it properly.

Regards,
Michal

**Comment by vishalwc** [comment]
Thanks Michal for update 

I was wondering I am using sysrepo datastore and utility to install the ietf-netconf-server module  directly .
how it is dependent on Netopeer2 ? 

I would prefer to start doing some development towards call-home by enabling the feature and later next week when it is ready I will pick the completed version .
please let me know how to enable the complete feature to try thing on it ?

**Comment by michalvasko** [comment]
Hi,
if you installed `ietf-netconf-server` on your own, then fine, but it is also installed (with `call-home` feature off) as part of **netopeer2-server** installation. So, to enable the feature manually, just use `sysrepoctl` with the correct parameters.

Regards,
Michal

**Comment by vishalwc** [comment]
-bash-4.2$ sysrepo/build/src/sysrepoctl --feature-enable=ssh-call-home  --module=ietf-netconf-server
Enabling feature 'ssh-call-home' in the module 'ietf-netconf-server'.
[ERR] Error by processing of the request.
Error: The operation failed

am I missing some parameters ?

**Comment by michalvasko** [comment]
Is that all the output? Still, this concerns sysrepo, not libyang.

**Comment by vishalwc** [comment]
yes it all the output from sysrepoctl command , yes I agree that it should be raise to sysrepo I will do that 

mean while can you tell me how to enable in netopeer2 just move further in development

**Comment by michalvasko** [comment]
`netopeer2-server` just reads the features from sysrepo, so it must be enabled there, there is no other way how to turn it on. I have checked the server installation and noticed that I have already added these features, so all you should need to do is `# make install` and all the models with correct features should be in sysrepo.

Regards,
Michal
