### ISSUE TITLE
netopeera2

### ISSUE THREAD

**Issue by syamkumarv** [CESNET/netopeer2#850]
Hi MIchalvasco,
i am trying to build netopeera2 (git file ) on x86 64bit  architecture ,little endian & ubuntu operating system.
Doing arm cross compellation on it.
i am getting following errors.

-- ******Unable to learn libnetconf2 thread support, check skipped******
-- Check if the system is big endian
-- Searching 16 bit integer
CMake Error at /usr/share/cmake-3.10/Modules/TestBigEndian.cmake:49 (message):
  no suitable type found
Call Stack (most recent call first):
  CMakeModules/UseCompat.cmake:20 (TEST_BIG_ENDIAN)
  CMakeLists.txt:171 (use_compat)
-- Configuring incomplete, errors occurred!
listed below are CMakeErrro.log file
```
1 Determining size of unsigned short failed with the following output:
  2 Change Dir: /home/labadmin/rohit/netopeer2/build/CMakeFiles/CMakeTmp
  3
  4 Run Build Command:"/usr/bin/make" "cmTC_8b58f/fast"
  5 /usr/bin/make -f CMakeFiles/cmTC_8b58f.dir/build.make CMakeFiles/cmTC_8b58f.dir/build
  6 make[1]: Entering directory '/home/labadmin/rohit/netopeer2/build/CMakeFiles/CMakeTmp'
  7 Building C object CMakeFiles/cmTC_8b58f.dir/CMAKE_SIZEOF_UNSIGNED_SHORT.c.o
  8 /usr/bin/cc -D_GNU_SOURCE -D_POSIX_C_SOURCE=200809L -D__BSD_VISIBLE=1 -I/usr/local/include -I/home/labadmin/rohit/anji/libnetconf2/src   -o CMakeFiles/cm    TC_8b58f.dir/CMAKE_SIZEOF_UNSIGNED_SHORT.c.o   -c /home/labadmin/rohit/netopeer2/build/CMakeFiles/CheckTypeSize/CMAKE_SIZEOF_UNSIGNED_SHORT.c
  9 Linking C executable cmTC_8b58f
 10 /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_8b58f.dir/link.txt --verbose=1
 11 /usr/bin/cc      -rdynamic CMakeFiles/cmTC_8b58f.dir/CMAKE_SIZEOF_UNSIGNED_SHORT.c.o  -o cmTC_8b58f -Wl,-rpath,/usr/local/lib /usr/lib/x86_64-linux-gnu/l    ibssl.so /usr/lib/x86_64-linux-gnu/libcrypto.so /usr/local/lib/libssh.so
 12 /usr/bin/ld: cannot find CMakeFiles/cmTC_8b58f.dir/CMAKE_SIZEOF_UNSIGNED_SHORT.c.o: No such file or directory
 13 collect2: error: ld returned 1 exit status
 14 CMakeFiles/cmTC_8b58f.dir/build.make:100: recipe for target 'cmTC_8b58f' failed
 15 make[1]: *** [cmTC_8b58f] Error 1
 16 make[1]: Leaving directory '/home/labadmin/rohit/netopeer2/build/CMakeFiles/CMakeTmp'
 17 Makefile:126: recipe for target 'cmTC_8b58f/fast' failed
 18 make: *** [cmTC_8b58f/fast] Error 2
```
Best Regards
Syam Kumar

**Comment by michalvasko** [comment]
I see, that was not helpful, unfortunately. Maybe try increasing verbosity of `cmake` or something, there must be some actual error, this just shows that an object failed to be build, does not print the reason why.

**Comment by jktjkt** [comment]
>   8 /usr/bin/cc -D_GNU_SOURCE -D_POSIX_C_SOURCE=200809L -D__BSD_VISIBLE=1 -I/usr/local/include -I/home/labadmin/rohit/anji/libnetconf2/src   -o CMakeFiles/cm    TC_8b58f.dir/CMAKE_SIZEOF_UNSIGNED_SHORT.c.o   -c /home/labadmin/rohit/netopeer2/build/CMakeFiles/CheckTypeSize/CMAKE_SIZEOF_UNSIGNED_SHORT.c

You're saying you're cross-compiling, yet this shows that the host's compiler is invoked, not the target one. I suggest using a proper tool for cross builds, such as Buildroot or Yocto. It is not just a matter of setting a correct $CC.
