### ISSUE TITLE
How to remove a netconf capability from Netopeer2

### ISSUE THREAD

**Issue by robbynet** [CESNET/netopeer2#851]
Hello,
For test scenario purpose focus on failure, we would like being able to start Netopeer2 without one of the following capabilities into <hello> message :   
- urn:ietf:params:netconf:capability:writable-running:1.0
- urn:ietf:params:netconf:capability:xpath:1.0
- urn:ietf:params:netconf:capability:notification:1.0
- urn:ietf:params:netconf:capability:interleave:1.0

Is there a way to configure Netopeer2 to reach this goal ?
Regards.

**Comment by michalvasko** [comment]
No, *netopeer2* does not allow modifying its capabilities. But if you do not mind, you can easily change the code so that they are not there.
