### ISSUE TITLE
ERROR: Module name <module> refers to an unknown module

### ISSUE THREAD

**Issue by Jagansingh22** [CESNET/netopeer2#852]
Hi,

In our product `read-default` parameter in `ietf-netconf-acm` module is set to `deny`. 
The reason is we dont want to show any data to user without proper permissions. 
With this config, `get-config` on modules with `yang-version 1.1;` is not working and throws below error

```
> get-config --source running --filter-xpath /ietf-tcp-common:*
ly VERBOSE: Resolving unresolved data nodes and their constraints...
ly VERBOSE: All data nodes and constraints resolved.
ly ERROR: Module name "ietf-tcp-common" refers to an unknown module.
cli_send_recv: Failed to send the RPC.
```

where as when `get-config` is run for other modules which do not have yang-version 1.1; it does not throw an error.
```
> get-config --source running --filter-xpath /ietf-netconf-monitoring:*
ly VERBOSE: Resolving unresolved data nodes and their constraints...
ly VERBOSE: All data nodes and constraints resolved.
DATA

>
```
All these get-config commands are run with netopeer2-cli.

It is noticed, when verbose is set in netopeer2-cli, after connect, log shows, it reads only a few yang models (the one's which does not have yang-version 1.1;)

The same works fine when a user is associated with ACM group which is part of some proper rule-list.

Why is this error coming and can this be fixed?

Versions:
```
netopeer2-server -V
netopeer2-server 1.1.53
compile time: Jan 27 2021, 22:10:03

sysrepoctl -V
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.103 (SO v5.6.19)

libyang (1.0.215-1)
```

**Comment by michalvasko** [comment]
So you have tried connecting with CLI and increased verbosity? What I can think of is you forbidding for the client to read `ietf-yang-library` data which are used to retrieve module information, which is then used to get all the individual modules. If this fails, the modules are being loaded locally but if not found, the client has no other way of getting these modules so it should warn about it and continue working with whatever modules it managed to get.

**Comment by Jagansingh22** [comment]
One question then,
Why there is a difference in the client reading the yang modules with yang-version 1.1 and yang models without that?
If read-default is set to deny, the client should not read access to all yang models.

**Comment by michalvasko** [comment]
The difference is specified [here](https://tools.ietf.org/html/rfc7950#page-12).
