### ISSUE TITLE
Multiple times subscribing results in multiple watchdog reset rpc-reply

### ISSUE THREAD

**Issue by hellonikita** [CESNET/netopeer2#853]
Hi 

We have observed that there are multiple watchdog reset request getting generated, even though only one watchdog reset is sent from odu. This is seen only when we multiple time subscribe is sent from odu.
oDU simulator output:
> subscribe --filter-xpath /o-ran-supervision:supervision-notification
OK
> 
> 
> subscribe --filter-xpath /o-ran-supervision:supervision-notification
OK
> 
> 
> subscribe --filter-xpath /o-ran-supervision:supervision-notification
OK
> 
> 
> user-rpc 
DATA
<next-update-at xmlns="urn:o-ran:supervision:1.0">2021-03-02T17:23:28Z</next-update-at>
> 
notification (2021-03-02T11:53:28Z)
<supervision-notification xmlns="urn:o-ran:supervision:1.0"/>

> 
notification (2021-03-02T11:53:28Z)
<supervision-notification xmlns="urn:o-ran:supervision:1.0"/>

> 
notification (2021-03-02T11:53:28Z)
<supervision-notification xmlns="urn:o-ran:supervision:1.0"/>

> user-rpc 
DATA
<next-update-at xmlns="urn:o-ran:supervision:1.0">2021-03-02T17:25:11Z</next-update-at>

Ideally only one notification should be sent even if subscribed multiple times from the same sesssion. Can you please share your comments?

Thanks!
BR
Nikita

**Comment by michalvasko** [comment]
If you use the latest `devel`, you should not be able to subscribe several times, it is incorrectly allowed.

**Comment by hellonikita** [comment]
Thanks Michal, by when this fix will be available as part of released version?

**Comment by panniruram** [comment]
Hi @michalvasko,
Could you please share the diff of the code changes also.

**Comment by michalvasko** [comment]
They are commits 81eed76b8b114943abcc603abea89d0d3590542a and e339d5ed35652f69af6f8547a76ec23294ad0586. But you are applying them on `master` on your own risk, they may depend on some other changes in `devel`.
