### ISSUE TITLE
Session details not accessible during the sr_event_notif_subscribe_tree callback for netconf-session-end or netconf-session-start

### ISSUE THREAD

**Issue by panniruram** [CESNET/netopeer2#854]
@michalvasko,

Have one query,
Subscribed for the "sr_event_notif_subscribe_tree" and callback works when start new session and close-session as well as.
rc = sr_event_notif_subscribe_tree(session, "ietf-netconf-notifications", "/ietf-netconf-notifications:netconf-session-start", 0, 0, session_start_callback, NULL, SR_EV_NOTIF_REPLAY, &subscription);

rc = sr_event_notif_subscribe_tree(session, "ietf-netconf-notifications", "/ietf-netconf-notifications:netconf-session-end", 0, 0, notif_callback, NULL, SR_SUBSCR_CTX_REUSE, &subscription);

But when trying to access the session details. its not working as per accepted. Below session ID always print as 0. we need these session details(like session id, Username etc..). Could you please help me what's wrong with the shared code. And let us know if have any alternate solutions to get the session id and username for the close-session.

static void
notif_callback(sr_session_ctx_t *session, const sr_ev_notif_type_t notif_type, const struct lyd_node *notif, time_t timestamp, void *private_data)
{
**int nc_id = sr_session_get_nc_id(session);
SRP_LOG_ERR("Sessions id:%d", nc_id);**
}

**Comment by michalvasko** [comment]
This was changed, please use `sr_session_get_event_nc_id()`.

**Comment by panniruram** [comment]
Thanks @michalvasko,
 is it in Dev or release version.   getting below warning while compiling.
warning: implicit declaration of function 'sr_session_get_event_nc_id'; did you mean 'sr_session_get_nc_id'? [-Wimplicit-function-declaration]
         int nc_id = sr_session_get_event_nc_id(session);

Versions: 
sysrepo-devel-1.4.104-1.fpld.x86_64
sysrepo-1.4.104-1.fpld.x86_64

**Comment by michalvasko** [comment]
Oh, sorry, I have not read the issue properly. If the function did not stop working because of am update (which I incorrectly assumed), you, naturally, cannot use the new one because it is not available.

The problem is that *netopeer2* does not set NC ID for the session it uses to send the notification. It could be added but I do not really see the point since you can read the ID directly from the notification data, so that is what I suggest.
