### ISSUE TITLE
Netopeer2 cross compilation failed for ARM 32 bit, undefined reference for libssh

### ISSUE THREAD

**Issue by ankit7gup** [CESNET/netopeer2#856]
Hi Michal, 

We are cross compiling sysrepo-netopeer2 and all dependencies for ARM 32 bit architecture.
Rest all compilation is done except netopeer-2. 
Getting errors for 

/usr/local/lib/libssh.so: undefined reference to `OpenSSL_version_num@OPENSSL_1_1_0'
/usr/local/lib/libssh.so: undefined reference to `EVP_des_ede3_cbc@OPENSSL_1_1_0'
/usr/local/lib/libssh.so: undefined reference to `EC_KEY_get0_group@OPENSSL_1_1_0'
/usr/local/lib/libssh.so: undefined reference to `EVP_PKEY_get_raw_private_key@OPENSSL_1_1_1'

Even though openssl and libssh are ARM compatible and found in respective path. Attaching Cmake and make logs for reference.
[make_logs.txt](https://github.com/CESNET/netopeer2/files/6083695/make_logs.txt)
[cmake_logs.txt](https://github.com/CESNET/netopeer2/files/6083696/cmake_logs.txt)

Libs: 
/usr/local/lib# file *ssh*
libssh.so:        symbolic link to libssh.so.4
libssh.so.4:      symbolic link to libssh.so.4.8.6
libssh.so.4.8.6:  ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=1d1800c9dadd276ac65c7d6d8dc36dc9e13ac0bb, stripped
root@u1804cloudvm:/usr/local/lib# file *ssl*
libssl.a:     current ar archive
libssl.so:    symbolic link to libssl.so.3
libssl.so.3:  ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=403888c04aa273559a455633e74495367b80b41f, not stripped
root@u1804cloudvm:/usr/local/lib# file *curl*
libcurl.so:       ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=d57dacf727a07acb34b8cd5a5bc2cbf5e6c4ef83, not stripped
libcurl.so.4:     symbolic link to libcurl.so.4.7.0
libcurl.so.4.7.0: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=deff417458b179feed2acb57c3b46a4e7da4706d, stripped

We are stuck at this point, please help, if we are doing something wrong or missing some step.

Regards,
Ankit

**Comment by michalvasko** [comment]
This is strictly a problem with linking *libssh*, not sure why you are asking me for help. In any case, I cannot help you because I have no experience with cross-compilation.

**Comment by ankit7gup** [comment]
Hi Michal,

I have figured out the issue and found, Issue is with compatibility for LIBSSH and OPENSSL compatibility.
Even latest LIBSSH 0.9.5 only works with OPENSSL 1.0.2k version for ARM cross compilation.

Adding here as might be helpful to somebody with similar issue in future.

Thanks for your help anyways!

Regards,
Ankit

**Comment by michalvasko** [comment]
Fine, no problem.

**Comment by NTUGY** [comment]
> Hi Michal,
> 
> I have figured out the issue and found, Issue is with compatibility for LIBSSH and OPENSSL compatibility. Even latest LIBSSH 0.9.5 only works with OPENSSL 1.0.2k version for ARM cross compilation.
> 
> Adding here as might be helpful to somebody with similar issue in future.
> 
> Thanks for your help anyways!
> 
> Regards, Ankit

Hi，
I'm sorry to bother you.I have completed the cross compilation of netopeer 2, but I don't know how to transplant it to the arm development board. Can you show me the next detailed steps？
Regards,
NTU

**Comment by Karl-ZhangBD** [comment]
> > Hi Michal,
> > I have figured out the issue and found, Issue is with compatibility for LIBSSH and OPENSSL compatibility. Even latest LIBSSH 0.9.5 only works with OPENSSL 1.0.2k version for ARM cross compilation.
> > Adding here as might be helpful to somebody with similar issue in future.
> > Thanks for your help anyways!
> > Regards, Ankit
> 
> Hi， I'm sorry to bother you.I have completed the cross compilation of netopeer 2, but I don't know how to transplant it to the arm development board. Can you show me the next detailed steps？ Regards, NTU

Hi, I've also been working on cross-compiling netopeer2 recently, can I ask you some questions?

**Comment by michalvasko** [comment]
Like I said, I have no experience with cross-compilation so I am not able to tell you much. Except for the variables mentioned in the [README](https://github.com/CESNET/netopeer2/#compilation-options), you should set it up for cross-compilation just like any other project.

**Comment by jktjkt** [comment]
I strongly suggest to use Buildroot or Yocto. Trying to do a DYI cross-compilation and/or "injecting" some random cross-built binaries to an ARM target is a recipe for failure.

**Comment by jktjkt** [comment]
Yes. Use Buildroot or Yocto, and don't invent a hand-crafted, DYI build. That's what I already suggested in my previous post above.
