### ISSUE TITLE
Sysrepo API's not getting called

### ISSUE THREAD

**Issue by rohitkathuria102** [CESNET/netopeer2#858]
Hi michal,
I am trying to run netopeer2 module on the 32 bit ARM board, even sysrepo is working when called seperately ,but isn't able to run from the netopeer2 build.

This is the error i'm currently facing ::

root@arria10:~/netopeerbuild/build# ./netopeer2-server -d -v2
[ERR]: SR: access() failed (Not a directory).
[ERR]: NP: Connecting to sysrepo failed (System function call failed).
[ERR]: NP: Server init failed.
[INF]: NP: Server terminated.

**Comment by michalvasko** [comment]
Please use the current `devel` of sysrepo, which should print more information, and post the output again,
