### ISSUE TITLE
How to permit specific users to connect with SSH

### ISSUE THREAD

**Issue by matth65** [CESNET/netopeer2#860]
Is it possible to block SSH connections for unauthorized users, and/or only allow specific users to connect with SSH? For example, the system has 'someuser' defined, but I don't want to allow connections to the Netconf Server for the 'someuser' user.  I can use NACM to block access to data for unauthorized users. However, I would also like to be able to block the connection to the Netconf server itself. I would like to deny 'someuser' from logging into the server altogether.

Regards,
Matt

**Comment by michalvasko** [comment]
This is not possible currently as the user configuration is directly read from the system. But once all the `ietf-netconf-server` configuration modules are finished and published as RFCs, the plan is to make the authentication specific to NETCONF and fully configurable. However, that will probably not happen any time soon.
