### ISSUE TITLE
Segfault in Netopeer2-server on calling connect from netopeer2-cli [ARM 32 Bit] on master branch

### ISSUE THREAD

**Issue by ankit7gup** [CESNET/netopeer2#861]
Hi, 

We are running Netopeer2 on RM 32 Bit architecture. 

For master branch code, 
While trying to connect to server from netopeer2-cli, getting segfault in the server.

#############cli####################### 
netopeer2-cli
```
> connect --host 0.0.0.0 --port 830
The authenticity of the host '0.0.0.0' cannot be established.
ssh-rsa key fingerprint is 3d:fb:9a:9d:d7:39:d0:8d:ae:02:7f:2c:da:3c:4f:f9:94:45:79:c6.
Are you sure you want to continue connecting (yes/no)? yes
Interactive SSH Authentication
Type your password:
Password:
nc ERROR: Session 1: SSH channel poll error (Socket error: disconnected).
nc ERROR: Session 1: invalid session, discarding.
cmd_connect: Connecting to the 0.0.0.0:830 as user "root" failed.
>
```

#########BT (without debug Mode)#######################
```
Program terminated with signal SIGSEGV, Segmentation fault.
Python Exception <type 'exceptions.AttributeError'> 'module' object has no attribute 'objfiles':
#0  0x4076e5b6 in ?? ()
[Current thread is 1 (LWP 7552)]
 ```
###########Server Logs###############

[server_logs.txt](https://github.com/CESNET/netopeer2/files/6114569/server_logs.txt)

########Version###########
netopeer2-server 1.1.53
compile time: Mar  5 2021, 19:48:47

However for debug branch it works fine.

Regards,
Ankit

**Comment by michalvasko** [comment]
You are saying you encounter this problem only for `Release` build target and not for `Debug`? That will make it much more difficult to fix. The first thing you can try is to update everything to the latest release. But if you still have the problem, I am not sure what to suggest. You can try using `valgrind` or `gdb` to get some information about the crash but not sure if there will be any usable information since there are no debugging symbols.

**Comment by ankit7gup** [comment]
I had taken the latest build from master branch 5 days back, that had failed, while the latest build from devel branch taken yesterday worked fine. I shall try taking the latest from master sometime soon, and keep you posted for the status.

**Comment by michalvasko** [comment]
Okay, then I believe it was fixed also in the  `master` branch because there was a release 3 days ago (`devel` merged into `master`).

**Comment by NTUGY** [comment]
Hi，
I'm sorry to bother you.I have completed the cross compilation of netopeer 2, but I don't know how to transplant it to the arm development board. Can you show me the next detailed steps？
Regards,
NTU
