### ISSUE TITLE
Netopeer-srv method of setting configuration data

### ISSUE THREAD

**Issue by wangshdong** [CESNET/netopeer2#862]
Requirement: After netopeer-srv is started, the configuration data is read from other places, and the read configuration data is set in the sysrepo running library, and then obtained in netopeer-cli through the getconfig method.

Can I use the sr_set_item method to achieve it? Or do you have any good suggestions?

**Comment by michalvasko** [comment]
To simply answer your question, yes, you can set configuration data using several functions and `sr_set_item()` is one of them, `sr_set_item_str()` probably easier to use.

**Comment by wangshdong** [comment]
Encountered a problem in the process of implementation,
Netopeer-srv uses function: sr_set_item_str() is successfully set,
Then call the sr_apply_changes() function to return: SR_ERR_CALLBACK_FAILED.

**Comment by michalvasko** [comment]
Look at the server output with `-d -v2` to see the exact problem or get it from the session after the call failed (`sr_get_error()`). I am not able to help you with the information you provided.
