### ISSUE TITLE
Support of confirmed-commit:1.1 capability

### ISSUE THREAD

**Issue by frimpler** [CESNET/netopeer2#864]
Hello Michal,

the implementation of Netopeer2 server (devel branch) seem not to support confirmed-commit, including operations and parameters stated here: https://tools.ietf.org/html/rfc6241#section-8.4. I assume also that your statement of last year https://github.com/CESNET/netopeer2/issues/725#issuecomment-701191266 is still valid.

Are there plans in the near future to provide an implementation for it and if so, what would be the time horizon?

Btw. I really appreciate your "Labels/Milestone" section which makes things really transparent. Maybe one could expand it and declare what features may be or not be supported in the project.

Thank you and regards,
Frank

**Comment by michalvasko** [comment]
> Are there plans in the near future to provide an implementation for it

No and we have trouble keeping up with the timeline for the tasks that are planned so it is unlikely we will be able to implement this any time soon.

**Comment by frimpler** [comment]
Thank you for this information. I suppose we keep this issue open until implemented.
