### ISSUE TITLE
get-config/get with filter regular expression like: '\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?' + '(Z|[\+\-]\d{2}:\d{2})'

### ISSUE THREAD

**Issue by Abrahamma97** [CESNET/netopeer2#868]
Hi @michalvasko 
Below example for regular expression based request from NETCONF client to server.

Below example is to extract the date and time with some pattern:

here we are using the regular expression like: '\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(\.\d+)?' + '(Z|[\+\-]\d{2}:\d{2})'

Is there any way I can get  the date as such by giving a reqular expression
like """""get-config --source=running"regular expression" """ like that

**Comment by michalvasko** [comment]
No, I do not think you can do this. These RPCs define only 2 kinds of filters, `subtree` and `xpath`, and neither of them support regular expressions. But you can always filter it twice, execute the RPC with a less strict filter and then process the result with some filtering tool that supports this.

**Comment by Abrahamma97** [comment]
Hi @michalvasko 
>>execute the RPC with a less strict filter and then process the result with some filtering tool that supports this.
Can you give a clarification or sample(example)  for the same as I did not understand.
Thank you

**Comment by Abrahamma97** [comment]
Thanks @michalvasko,
I got your point. Hence closing the issue
