### ISSUE TITLE
Netopeer2 to  subscribe to include multiple yang models specifically and to exclude particular yang models

### ISSUE THREAD

**Issue by Abrahamma97** [CESNET/netopeer2#869]
Hi @michalvasko,
I want to subscribe to notifications  using netopeer2 client, but I also want to exclude particular yang models for the same. Is there any method to do the same?

**Comment by michalvasko** [comment]
Just use a filter, either subtree or xpath, to get only the notifications you want.

**Comment by Abrahamma97** [comment]
This can be done even for multipls yangs..... ?

**Comment by michalvasko** [comment]
Yes, you can use a filter `/module1:* | /module2:*`, for example, and subscribe to `NETCONF` stream. Then you should get all notifications from these 2 modules.

**Comment by Abrahamma97** [comment]
Yes I am able to get this closing the same 
Thanks @michalvasko
