### ISSUE TITLE
Netopeer Client Log customisation

### ISSUE THREAD

**Issue by Abrahamma97** [CESNET/netopeer2#870]
Hi  @michalvasko,
We get standard replies from netopeer server to netopeer client like access denied, validation failed. Is it possible to give customised messages for the same?

**Comment by michalvasko** [comment]
What exactly do you mean? If the errors are due to your *sysrepo* callbacks failing, you can set the message with `sr_set_error()`. Otherwise it is all handled internally and code would have to be changed to improve any particular message.

**Comment by Abrahamma97** [comment]
Yes this is what I mean. Custom messages can be created then using  sr_set_error()?

**Comment by michalvasko** [comment]
That is what I just wrote, yes.

**Comment by Abrahamma97** [comment]
Thank you @michalvasko , Closing this issue
