### ISSUE TITLE
sr_session_get_nc_id()  returns always 0

### ISSUE THREAD

**Issue by Abrahamma97** [CESNET/netopeer2#872]
Hi @michalvasko ,

![Screenshot from 2021-03-16 19-10-07](https://user-images.githubusercontent.com/54631352/111321598-19b98a00-868e-11eb-9a6e-36771443b4ee.png)

sr_session_get_nc_id() returns always 0. This issue is seen in latest release. in releases before Feb 25  sr_session_get_nc_id() is coming correctly as 1,2,3....etc
Can you help fix this issue?

**Comment by michalvasko** [comment]
Yes, use `sr_session_get_event_nc_id()`...

**Comment by Abrahamma97** [comment]
Ok I will check and update you at the latest,
Thank you!!

**Comment by Abrahamma97** [comment]
@michalvasko , Yes it worked. Thanks!!
Can you tell why this change in value had come  and why we had to use this API instead of the other as before?

**Comment by michalvasko** [comment]
In short, because the session management was a mess before leading to a lot of potential problems. Now you must strictly distinguish what information you want, whether of the session itself or about an event originator session.

**Comment by Abrahamma97** [comment]
Oh thanks for the info appreciate it. Cheers and closing this issue.
