### ISSUE TITLE
netopeer2-cli is unable to connect with netopeer2-server

### ISSUE THREAD

**Issue by kishore-vvdn** [CESNET/netopeer2#875]
server logs:
sudo netopeer2-server -d -v3
[INF]: Connected to daemon Sysrepo Engine at socket=/var/run/sysrepod.sock
[INF]: Netopeer2 connected to sysrepod.
[INF]: Plugin "/usr/lib/x86_64-linux-gnu/libyang/extensions/nacm.so" successfully loaded.
[INF]: Plugin "/usr/lib/x86_64-linux-gnu/libyang/extensions/metadata.so" successfully loaded.
[INF]: Plugin "/usr/lib/x86_64-linux-gnu/libyang/extensions/yangdata.so" successfully loaded.
[INF]: Plugin "/usr/lib/x86_64-linux-gnu/libyang/user_types/user_inet_types.so" successfully loaded.
[INF]: Plugin "/usr/lib/x86_64-linux-gnu/libyang/user_types/user_yang_types.so" successfully loaded.
[INF]: Reading module "ietf-yang-metadata".
[INF]: Module "ietf-yang-metadata@2016-08-05" successfully parsed as implemented.
[INF]: Reading module "yang".
[INF]: Resolving "yang" unresolved schema nodes and their constraints...
[INF]: All "yang" schema nodes and constraints resolved.
[INF]: Module "yang@2017-02-20" successfully parsed as implemented.
[INF]: Reading module "ietf-inet-types".
[INF]: Resolving derived type "union" failed, it will be attempted later.
[INF]: Resolving derived type "union" failed, it will be attempted later.
[INF]: Resolving derived type "union" failed, it will be attempted later.
[INF]: Resolving derived type "union" failed, it will be attempted later.
[INF]: Resolving "ietf-inet-types" unresolved schema nodes and their constraints...
[INF]: All "ietf-inet-types" schema nodes and constraints resolved.
[INF]: Module "ietf-inet-types@2013-07-15" successfully parsed as implemented.
[INF]: Reading module "ietf-yang-types".
[INF]: Module "ietf-yang-types@2013-07-15" successfully parsed as implemented.
[INF]: Reading module "ietf-datastores".
[INF]: Module "ietf-datastores@2017-08-17" successfully parsed as implemented.
[INF]: Reading module "ietf-yang-library".
[INF]: Searching for "ietf-yang-types" in /home/kishore.
[INF]: Searching for "ietf-inet-types" in /home/kishore.
[INF]: Searching for "ietf-datastores" in /home/kishore.
[INF]: Module "ietf-yang-library@2019-01-04" successfully parsed as implemented.
[INF]: Loading schema "ietf-netconf-notifications@2012-02-06" from sysrepo.
[INF]: Reading module "ietf-netconf-notifications".
[INF]: Reading module "ietf-netconf".
[INF]: Reading module "ietf-netconf-acm".
[INF]: Module "ietf-netconf-acm@2018-02-14" successfully parsed as imported.
[INF]: Module "ietf-netconf@2011-06-01" successfully parsed as imported.
[INF]: Resolving "ietf-netconf-notifications" unresolved schema nodes and their constraints...
[INF]: All "ietf-netconf-notifications" schema nodes and constraints resolved.
[INF]: Module "ietf-netconf-notifications@2012-02-06" successfully parsed as implemented.
[INF]: Loading schema "ietf-netconf@2011-06-01" from sysrepo.
[INF]: Module ietf-netconf@2011-06-01 already present in context.
[INF]: Module "ietf-netconf@2011-06-01" now implemented.
[INF]: Loading schema "ietf-netconf-acm@2018-02-14" from sysrepo.
[INF]: Module ietf-netconf-acm@2018-02-14 already present in context.
[INF]: Loading schema "nc-notifications@2008-07-14" from sysrepo.
[INF]: Reading module "nc-notifications".
[INF]: Reading module "notifications".
[INF]: Module "notifications@2008-07-14" successfully parsed as imported.
[INF]: Module "nc-notifications@2008-07-14" successfully parsed as implemented.
[INF]: Loading schema "notifications@2008-07-14" from sysrepo.
[INF]: Module notifications@2008-07-14 already present in context.
[INF]: Module "notifications@2008-07-14" now implemented.
[INF]: Loading schema "turing-machine@2013-12-27" from sysrepo.
[INF]: Reading module "turing-machine".
[INF]: Module "turing-machine@2013-12-27" successfully parsed as implemented.
[INF]: Loading schema "iana-if-type@2014-05-08" from sysrepo.
[INF]: Reading module "iana-if-type".
[INF]: Reading module "ietf-interfaces".
[INF]: Module "ietf-interfaces@2014-05-08" successfully parsed as imported.
[INF]: Module "iana-if-type@2014-05-08" successfully parsed as implemented.
[INF]: Loading schema "ietf-interfaces@2014-05-08" from sysrepo.
[INF]: Module ietf-interfaces@2014-05-08 already present in context.
[INF]: Module "ietf-interfaces@2014-05-08" now implemented.
[INF]: Loading schema "ietf-yang-types@2013-07-15" from sysrepo.
[INF]: Module ietf-yang-types@2013-07-15 already present in context.
[INF]: Loading schema "ietf-ip@2014-06-16" from sysrepo.
[INF]: Reading module "ietf-ip".
[INF]: Module "ietf-ip@2014-06-16" successfully parsed as implemented.
[INF]: Loading schema "ietf-netconf-with-defaults@2011-06-01" from sysrepo.
[INF]: Reading module "ietf-netconf-with-defaults".
[INF]: Module "ietf-netconf-with-defaults@2011-06-01" successfully parsed as implemented.
[INF]: Loading schema "ietf-netconf-monitoring@2010-10-04" from sysrepo.
[INF]: Reading module "ietf-netconf-monitoring".
[INF]: Module "ietf-netconf-monitoring@2010-10-04" successfully parsed as implemented.
[INF]: Loading schema "ietf-yang-library@2018-01-17" from sysrepo.
[INF]: Reading module "ietf-yang-library".
[ERR]: Module "ietf-yang-library@2018-01-17" in another revision "2019-01-04" already implemented.
[ERR]: Module "ietf-yang-library" parsing failed.
[WRN]: Getting ietf-yang-library@2018-01-17 schema from sysrepo failed, data from this module won't be available.
[INF]: Loading schema "ietf-datastores@2017-08-17" from sysrepo.
[INF]: Module ietf-datastores@2017-08-17 already present in context.
[INF]: Loading schema "ietf-system@2014-08-06" from sysrepo.
[INF]: Reading module "ietf-system".
[INF]: Reading module "iana-crypt-hash".
[INF]: Module "iana-crypt-hash@2014-08-06" successfully parsed as imported.
[INF]: Resolving "ietf-system" unresolved schema nodes and their constraints...
[INF]: All "ietf-system" schema nodes and constraints resolved.
[INF]: Module "ietf-system@2014-08-06" successfully parsed as implemented.
[INF]: Loading schema "iana-crypt-hash@2014-08-06" from sysrepo.
[INF]: Module iana-crypt-hash@2014-08-06 already present in context.
[INF]: Module "iana-crypt-hash@2014-08-06" now implemented.
[INF]: Loading schema "ietf-netconf-server@2016-11-02" from sysrepo.
[INF]: Reading module "ietf-netconf-server".
[INF]: Reading module "ietf-x509-cert-to-name".
[INF]: Module "ietf-x509-cert-to-name@2014-12-10" successfully parsed as imported.
[INF]: Reading module "ietf-ssh-server".
[INF]: Reading module "ietf-keystore".
[INF]: Module "ietf-keystore@2016-10-31" successfully parsed as imported.
[INF]: Module "ietf-ssh-server@2016-11-02" successfully parsed as imported.
[INF]: Reading module "ietf-tls-server".
[INF]: Module "ietf-tls-server@2016-11-02" successfully parsed as imported.
[INF]: Resolving "ietf-netconf-server" unresolved schema nodes and their constraints...
[WRN]: Identity found, but in a non-implemented module "ietf-x509-cert-to-name".
[WRN]: Failed to resolve identityref "ietf-x509-cert-to-name:specified". (/ietf-netconf-server:map-type)
[WRN]: Previous warning generated by XPath subexpression[3] "map-type = 'ietf-x509-cert-to-name:specified'".
[WRN]: Identity found, but in a non-implemented module "ietf-x509-cert-to-name".
[WRN]: Failed to resolve identityref "ietf-x509-cert-to-name:specified". (/ietf-netconf-server:map-type)
[WRN]: Previous warning generated by XPath subexpression[3] "map-type = 'ietf-x509-cert-to-name:specified'".
[INF]: All "ietf-netconf-server" schema nodes and constraints resolved.
[INF]: Module "ietf-netconf-server@2016-11-02" successfully parsed as implemented.
[INF]: Loading schema "ietf-x509-cert-to-name@2014-12-10" from sysrepo.
[INF]: Module ietf-x509-cert-to-name@2014-12-10 already present in context.
[INF]: Module "ietf-x509-cert-to-name@2014-12-10" now implemented.
[INF]: Loading schema "ietf-ssh-server@2016-11-02" from sysrepo.
[INF]: Module ietf-ssh-server@2016-11-02 already present in context.
[INF]: Loading schema "ietf-keystore@2016-10-31" from sysrepo.
[INF]: Module ietf-keystore@2016-10-31 already present in context.
[INF]: Loading schema "ietf-tls-server@2016-11-02" from sysrepo.
[INF]: Module ietf-tls-server@2016-11-02 already present in context.
[WRN]: Sysrepo does not have the "ietf-netconf-server" module or keystored keys dir unknown, using default NETCONF server options.
[INF]: Listening on 0.0.0.0:830 for SSH connections.
[INF]: Accepted a connection on 0.0.0.0:830.
[2021/03/24 11:32:24.413694, 2] ssh_pki_import_privkey_base64:  Trying to decode privkey passphrase=false
[2021/03/24 11:32:24.413894, 2] ssh_pki_openssh_import:  Opening OpenSSH private key: ciphername: none, kdf: none, nkeys: 1
[2021/03/24 11:32:24.415329, 2] ssh_server_connection_callback:  SSH client banner: SSH-2.0-libssh_0.9.3
[2021/03/24 11:32:24.415391, 2] ssh_analyze_banner:  Analyzing banner: SSH-2.0-libssh_0.9.3
[2021/03/24 11:32:24.416641, 2] ssh_kex_select_methods:  Negotiated curve25519-sha256,ssh-rsa,aes256-gcm@openssh.com,aes256-gcm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-256-etm@openssh.com,none,none,,
[2021/03/24 11:32:24.445095, 2] ssh_packet_server_curve25519_init:  SSH_MSG_KEX_ECDH_REPLY sent
[2021/03/24 11:32:24.445204, 2] ssh_init_rekey_state:  Set rekey after 4294967296 blocks
[2021/03/24 11:32:24.445235, 2] ssh_init_rekey_state:  Set rekey after 4294967296 blocks
[2021/03/24 11:32:24.445291, 2] ssh_packet_server_curve25519_init:  SSH_MSG_NEWKEYS sent
[2021/03/24 11:32:24.446472, 2] ssh_packet_newkeys:  Received SSH_MSG_NEWKEYS
[INF]: Received an SSH message "request-service" of subtype "ssh-userauth".
[INF]: Received an SSH message "request-auth" of subtype "none".
[INF]: Received an SSH message "request-auth" of subtype "interactive".
[2021/03/24 11:32:24.447257, 2] ssh_message_auth_interactive_request:  Warning: Got a keyboard-interactive response but it seems we didn't send the request.
[INF]: Received an SSH message "request-auth" of subtype "interactive".
[INF]: User "kishore" authenticated.
[INF]: Received an SSH message "request-channel-open" of subtype "session".
[INF]: Received an SSH message "request-channel" of subtype "subsystem".
[2021/03/24 11:32:26.881559, 2] grow_window:  growing window (channel 43:43) to 1280000 bytes
[ERR]: Client's <hello> timeout elapsed.
[2021/03/24 11:32:26.881681, 2] channel_rcv_change_window:  Adding 1216950 bytes to channel (43:43) (from 60728 bytes)
[2021/03/24 11:32:26.881740, 1] ssh_socket_exception_callback:  Socket exception callback: 1 (0)
[2021/03/24 11:32:26.881757, 1] ssh_socket_exception_callback:  Socket error: disconnected

client logs:
netopeer2-cli
> connect 
Interactive SSH Authentication
Type your password:
Password: 
nc ERROR: Server's <hello> timeout elapsed.
cmd_connect: Connecting to the localhost:830 as user "kishore" failed.

can anyone help on this issue please
thanks

**Comment by michalvasko** [comment]
What *libssh* version are you using?

**Comment by kishore-vvdn** [comment]
libssh version -- v0.9.3
sysrepo version -- v0.7.8
netopeer2 version -- v0.7-r2
thanks

**Comment by lin13051275755** [comment]
@kishore-vvdn 
I had the same problem

**Comment by michalvasko** [comment]
*libssh* 0.9.3 is the problem, both 0.9.3 and 0.9.4 releases are buggy. Best to use 0.9.5 but 0.9.2 should work fine as well.

**Comment by kishore-vvdn** [comment]
i have tried installing both 0.9.5 and 0.9.2 versions still the same behaviour. can you please suggest why it is happening.
thanks

**Comment by lin13051275755** [comment]
had the same problem: Client's <hello> timeout elapsed；

**Comment by lin13051275755** [comment]
Client's <hello> timeout elapsed

**Comment by lin13051275755** [comment]
Client's <<hello>> timeout elapsed.

**Comment by michalvasko** [comment]
> i have tried installing both 0.9.5 and 0.9.2 versions still the same behaviour. can you please suggest why it is happening.
> thanks

Are you sure those versions were actually used? You can see it in the output.
```
[2021/03/24 11:32:24.415329, 2] ssh_server_connection_callback: SSH client banner: SSH-2.0-libssh_0.9.3
[2021/03/24 11:32:24.415391, 2] ssh_analyze_banner: Analyzing banner: SSH-2.0-libssh_0.9.3
```
Did you see this version actually change? Because I am pretty sure the *libssh* version is the problem.

**Comment by kishore-vvdn** [comment]
yes that is the issue with libssh version it was solved after changing the version.thanks

now im building netopeer2-server in buildroot
im getting error while configuring netopeer2 dependencies in buildroot
-- The C compiler identification is GNU 7.3.0
-- Check for working C compiler: /home/kishore/PROJECTS/STLI_SCEL/base-SDK-10.3.5.0-PR2/cn9130_crb-r1p3-release-output/host/bin/aarch64-marvell-linux-gnu-gcc
-- Check for working C compiler: /home/kishore/PROJECTS/STLI_SCEL/base-SDK-10.3.5.0-PR2/cn9130_crb-r1p3-release-output/host/bin/aarch64-marvell-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /home/kishore/PROJECTS/STLI_SCEL/base-SDK-10.3.5.0-PR2/cn9130_crb-r1p3-release-output/host/bin/pkg-config (found version "0.28") 
CMake Warning at CMakeLists.txt:57 (message):
  keystored pkg-config file copied into a directory not searched by
  pkg-config.


CMake Warning at CMakeLists.txt:58 (message):
  For netopeer2-server configuration to work, pkg-config search path must
  include "/usr/lib/pkgconfig" or keystored keys directory will have to be
  set manually to "/etc/keystored/keys".


-- Found sysrepo: /home/kishore/PROJECTS/STLI_SCEL/base-SDK-10.3.5.0-PR2/cn9130_crb-r1p3-release-output/host/aarch64-buildroot-linux-gnu/sysroot/usr/lib/libsysrepo.so  
CMake Error at CMakeLists.txt:75 (string):
  string sub-command STRIP requires two arguments.


CMake Error at CMakeLists.txt:79 (message):
  Cannot get sysrepo plugins directory due to missing pkg-config, set
  SR_PLUGINS_DIR manually.


-- Configuring incomplete, errors occurred!
could you please help on this
thanks

**Comment by kishore-vvdn** [comment]
Please reply to my latest query
Thanks & Regards

**Comment by michalvasko** [comment]
> Please reply to my latest query

I am pretty sure I did but in some other issue. Please stop creating duplicate replies.

**Comment by kishore-vvdn** [comment]
I didn't get what do you mean by duplicate replies.
FYI: libssh issue solved i have posted new issue

**Comment by kishore-vvdn** [comment]
I didn't get what do you mean by duplicate replies.
FYI: libssh issue solved i have posted new issue

**Comment by michalvasko** [comment]
I mean you are asking the same thing you did in #878. And you are right, this is a new issue so I do not know why you have replied in this issue and not created a new one.

**Comment by kishore-vvdn** [comment]
thank you **michalvasko**

**Comment by sheep94lion** [comment]
> _libssh_ 0.9.3 is the problem, both 0.9.3 and 0.9.4 releases are buggy. Best to use 0.9.5 but 0.9.2 should work fine as well.

I have the same problem and I am using 0.8.4. Is this version okay?

**Comment by michalvasko** [comment]
I think so but I am not sure I have ever used that version and if you are having problems, it may be best to try updating it.
