### ISSUE TITLE
Query: Missing capabilities in the output of netopeer2-cli status command

### ISSUE THREAD

**Issue by jonessos** [CESNET/netopeer2#876]
Hi @michalvasko,

These are the yang models installed in my host machine:
![installed_models](https://user-images.githubusercontent.com/52527326/112274264-4a0fb280-8ca4-11eb-98d8-b1ea7d8946c6.png)

When I run the status command on the client, the listed out capabilities are as follows:
![capabilties](https://user-images.githubusercontent.com/52527326/112274254-47ad5880-8ca4-11eb-92ec-a80d7491213f.png)

It only seems to be showing NETCONF related models. Is it possible to list out the other models as well?

**Comment by michalvasko** [comment]
So once again... Assuming your modules are YANG 1.1, none of these modules show up in capabilities because they are [not allowed](https://tools.ietf.org/html/rfc7950#page-12) to be sent as a capability.

**Comment by jonessos** [comment]
Understood. Thanks :)
