### ISSUE TITLE
Netopeer2-server logging question

### ISSUE THREAD

**Issue by jabilmplane** [CESNET/netopeer2#877]
Hi

I’m looking for possibility to log all incoming RPCs (edit-config, get, user-rpc, etc ) in text format.

Does netopeer2-server have such mechanism?
If not, could you, please, point out place in the code where I may put some custom logging?
Do you know any another ways to achieve the goal?

Thanks in advance!

**Comment by michalvasko** [comment]
Use `netopeer2-server -c MSG`, then you should be able to filter out only the messages from the output.

**Comment by jabilmplane** [comment]
Thanks!
Your help is very appreciated!
