### ISSUE TITLE
netopeer2-keystored building issue in buildroot for SR_PLUGINS_DIR

### ISSUE THREAD

**Issue by kishore-vvdn** [CESNET/netopeer2#878]
im building netopeer2-server in buildroot while building dependices i.e,netopeer2-keystored throughing following issue

-- The C compiler identification is GNU 7.3.0
-- Check for working C compiler: /home/kishore/<DIR>/host/bin/aarch64-marvell-linux-gnu-gcc
-- Check for working C compiler: /home/<DIR>host/bin/aarch64-marvell-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /home/kishore/<DIR>/host/bin/pkg-config (found version "0.28") 
CMake Warning at CMakeLists.txt:57 (message):
  keystored pkg-config file copied into a directory not searched by
  pkg-config.

CMake Warning at CMakeLists.txt:58 (message):
  For netopeer2-server configuration to work, pkg-config search path must
  include "/usr/lib/pkgconfig" or keystored keys directory will have to be
  set manually to "/etc/keystored/keys".

-- Found sysrepo: /home/kishore/<DIR>/host/aarch64-buildroot-linux-gnu/sysroot/usr/lib/libsysrepo.so  
CMake Error at CMakeLists.txt:76 (string):
  string sub-command STRIP requires two arguments.

CMake Error at CMakeLists.txt:80 (message):
  Cannot get sysrepo plugins directory due to missing pkg-config, set
  SR_PLUGINS_DIR manually.

-- Configuring incomplete, errors occurred!
Could you please suggest solution for this issue
Thanks

**Comment by michalvasko** [comment]
I am sorry but I am not able to help you with the legacy *netopeer2* installation, there was quite a lot of things to install making cross-compilation a pain.

**Comment by kishore-vvdn** [comment]
> im building netopeer2-server in buildroot while building dependices i.e,netopeer2-keystored throughing following issue
> 
> -- The C compiler identification is GNU 7.3.0
> -- Check for working C compiler: /home/kishore/
> 
> /host/bin/aarch64-marvell-linux-gnu-gcc
> -- Check for working C compiler: /home/host/bin/aarch64-marvell-linux-gnu-gcc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Found PkgConfig: /home/kishore//host/bin/pkg-config (found version "0.28")
> CMake Warning at CMakeLists.txt:57 (message):
> keystored pkg-config file copied into a directory not searched by
> pkg-config.
> CMake Warning at CMakeLists.txt:58 (message):
> For netopeer2-server configuration to work, pkg-config search path must
> include "/usr/lib/pkgconfig" or keystored keys directory will have to be
> set manually to "/etc/keystored/keys".
> 
> -- Found sysrepo: /home/kishore/
> 
> /host/aarch64-buildroot-linux-gnu/sysroot/usr/lib/libsysrepo.so
> CMake Error at CMakeLists.txt:76 (string):
> string sub-command STRIP requires two arguments.
> CMake Error at CMakeLists.txt:80 (message):
> Cannot get sysrepo plugins directory due to missing pkg-config, set
> SR_PLUGINS_DIR manually.
> 
> -- Configuring incomplete, errors occurred!
> Could you please suggest solution for this issue
> Thanks

**Comment by kishore-vvdn** [comment]
Thank you **michalvasko**
