### ISSUE TITLE
In reverse ssh mode , configuration push fails with SSH error

### ISSUE THREAD

**Issue by sivaprasadmsr** [CESNET/netopeer2#879]
In reverse SSH mode, configuration push using netconf-console fails after 2 or 3 times with SSH error.

On SSH Client
ssh -R 2501:127.0.0.1:830 user@10.10.10.123

On SSH Server:
 netconf-console --host=127.0.0.1 --port=2501 -u nxp -p nxp -r 120 --edit-config abc.xml

No handlers could be found for logger "ncclient.transport.ssh"
Operation failed: SSHError - Negotiation failed

In reverse SSH mode, netconf session still in time-wait state after configuration applied

 netstat -natpu | grep 2501       (Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:2501          0.0.0.0:*               LISTEN      -
tcp       25      0 127.0.0.1:2501          127.0.0.1:37426         CLOSE_WAIT  -
tcp       25      0 127.0.0.1:2501          127.0.0.1:37424         CLOSE_WAIT  -
tcp6       0      0 ::1:2501                :::*                    LISTEN      -

Any suggestions are much appreciated

**Comment by michalvasko** [comment]
So where exactly is our *netopeer2-server*, all you have mentioned are `netconf-console` and `ncclient`. And even if it is there somewhere underneath, I am not able to provide any support unless you have a specific problem with *netopeer2-server* that you can describe independently of all those other processes you have there.

**Comment by sivaprasadmsr** [comment]
netopeer2-server is running on SSH client where I am initiating reverse SSH 
 root@router000002:~# ps | grep netopeer
 7152 root     62380 S    /bin/netopeer2-server -d -v 0
18264 root      3128 S    grep netopeer
root@router000002:~# ssh -R 2501:127.0.0.1:830 user@10.10.10.123

Is  maximum number of  netconf-client sessions that can be connected to  netconf server configurable? If so, where do we need to configure ?

**Comment by michalvasko** [comment]
Um, I am still not sure why are you doing what you are doing but you may want to take a look at [Call Home](https://tools.ietf.org/html/rfc8071), it is fully supported by *netopeer2*.

As for maximum number of NETCONF sessions, you cannot configure that anymore because it was removed from the `ietf-netconf-server` YANG module and replaced with several timeouts. The idea then is to configure these timeouts correctly to prevent some DoS attacks instead of a flat session limit.

**Comment by sivaprasadmsr** [comment]
Yes my requirement is callhome
I found out that same functionality can be implemented using reverse-ssh 
I am facing an issue while configuring from netconf-console. The issue is in case of reverse ssh mode "when I configure a series of XML using netconf-console, the existing netconf sessions are not closed. Instead they are in time-wait state. So , when there are a maximum of 5 netconf sessions in time-wait state, I am not able to configure the 6th XML using netconf-console ". So , I asked you how to increase the maximum client sessions that can be connected to server. 
Please provide your inputs regaring callhome implementation and the issue which I described above. 

Thanks

**Comment by michalvasko** [comment]
What you are describing sounds more like a netconf-console problem. In any case, there is no session limit in *netopeer2* but there are 5 threads handling all the requests so it may be possible that all of them are stuck on some timeout and hence not able to accept the new session. I would suggest you fix your setup first, I doubt anything else can be done about this, anyway.

**Comment by sivaprasadmsr** [comment]
okay 
This is the error that we observe when configuration push is failed on netconf-console
netconf-console --host=127.0.0.1 --port=55001 -u abc -p abc -r 300 --edit-config ipgroup.xml

No handlers could be found for logger "ncclient.transport.ssh"
Operation failed: SSHError - Negotiation failed

Any suggestions ?
