### ISSUE TITLE
Failed to copy-config from running to startup when running is locked in the same cli

### ISSUE THREAD

**Issue by niuzhiquan** [CESNET/Netopeer2#88]
Hi,
I find that I failed to  copy-config from running to startup when the running is locked. 
After I  run "lock --target running" and "edit-config --target running --config=/root/data/data.xml", I fail to do "copy-config --target running  --source startup".

Here is the cli error msg:

> 
> lock --target running
OK
> edit-config --target running --config=/root/data/data.xml
OK
> copy-config --target startup  --source running
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	message:  Requested resource is already locked

>

and the netopeer2-server log:

netopeer2-server[6388]: [nc_read_msg-338]Session 1: received message:
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="21"><copy-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><target><running/></target><source><startup/></source></copy-config></rpc>
netopeer2-server[6388]: [dict_insert-274]DICT: inserting "rpc" with collision 
netopeer2-server[6388]: [dict_insert-233]DICT: inserting (refcount) "urn:ietf:params:xml:ns:netconf:base:1.0"
netopeer2-server[6388]: [dict_insert-274]DICT: inserting "message-id" with collision 
netopeer2-server[6388]: [dict_insert-274]DICT: inserting "21" with collision 
netopeer2-server[6388]: [dict_insert-233]DICT: inserting (refcount) "copy-config"
netopeer2-server[6388]: [dict_insert-233]DICT: inserting (refcount) "urn:ietf:params:xml:ns:netconf:base:1.0"
netopeer2-server[6388]: [dict_insert-233]DICT: inserting (refcount) "target"
netopeer2-server[6388]: [dict_insert-233]DICT: inserting (refcount) "running"
netopeer2-server[6388]: [dict_insert-274]DICT: inserting "" with collision 
netopeer2-server[6388]: [dict_insert-233]DICT: inserting (refcount) ""
netopeer2-server[6388]: [dict_insert-233]DICT: inserting (refcount) "source"
netopeer2-server[6388]: [dict_insert-233]DICT: inserting (refcount) "startup"
netopeer2-server[6388]: [dict_insert-233]DICT: inserting (refcount) ""
netopeer2-server[6388]: [dict_insert-233]DICT: inserting (refcount) ""
netopeer2-server[6388]: [dict_insert-233]DICT: inserting (refcount) ""
netopeer2-server[6388]: [dict_insert-233]DICT: inserting (refcount) ""
netopeer2-server[6388]: [resolve_unres_data-6877]Resolving unresolved data nodes and their constraints...
netopeer2-server[6388]: [resolve_unres_data-7074]All data nodes and constraints resolved.
netopeer2-server[6388]: [print_expr_struct_debug-172]XPATH: expression "/ietf-netconf:copy-config/target/*":
netopeer2-server[6388]: [print_expr_struct_debug-183]Tmp is:XPATH:	Token Operator(Path), in expression "/"
netopeer2-server[6388]: [print_expr_struct_debug-183]Tmp is:XPATH:	Token NameTest, in expression "ietf-netconf:copy-config"
netopeer2-server[6388]: [print_expr_struct_debug-183]Tmp is:XPATH:	Token Operator(Path), in expression "/"
netopeer2-server[6388]: [print_expr_struct_debug-183]Tmp is:XPATH:	Token NameTest, in expression "target"
netopeer2-server[6388]: [print_expr_struct_debug-183]Tmp is:XPATH:	Token Operator(Path), in expression "/"
netopeer2-server[6388]: [print_expr_struct_debug-183]Tmp is:XPATH:	Token NameTest, in expression "*"
netopeer2-server[6388]: [eval_absolute_location_path-6138]XPATH: eval_absolute_location_path parsed Operator(Path)[0]
netopeer2-server[6388]: [dict_insert-233]DICT: inserting (refcount) "copy-config"
netopeer2-server[6388]: [eval_node_test-5739]XPATH: eval_node_test              parsed NameTest[1]
netopeer2-server[6388]: [eval_relative_location_path-6039]XPATH: eval_relative_location_path parsed Operator(Path)[25]
netopeer2-server[6388]: [dict_insert-233]DICT: inserting (refcount) "target"
netopeer2-server[6388]: [eval_node_test-5739]XPATH: eval_node_test              parsed NameTest[26]
netopeer2-server[6388]: [eval_relative_location_path-6039]XPATH: eval_relative_location_path parsed Operator(Path)[32]
netopeer2-server[6388]: [dict_insert-233]DICT: inserting (refcount) "*"
netopeer2-server[6388]: [eval_node_test-5739]XPATH: eval_node_test              parsed NameTest[33]
netopeer2-server[6388]: (tid[139699712177920] 03:37:35:015368) (cl_request_process:417) Sending session-refresh request.
netopeer2-server[6388]: (tid[139699712177920] 03:37:35:015425) (cl_request_process:439) session-refresh request sent, waiting for response.
netopeer2-server[6388]: (tid[139699712177920] 03:37:35:015925) (cl_request_process:461) session-refresh response received, processing.
netopeer2-server[6388]: [print_expr_struct_debug-172]XPATH: expression "/ietf-netconf:copy-config/source/*":
netopeer2-server[6388]: [print_expr_struct_debug-183]Tmp is:XPATH:	Token Operator(Path), in expression "/"
netopeer2-server[6388]: [print_expr_struct_debug-183]Tmp is:XPATH:	Token NameTest, in expression "ietf-netconf:copy-config"
netopeer2-server[6388]: [print_expr_struct_debug-183]Tmp is:XPATH:	Token Operator(Path), in expression "/"
netopeer2-server[6388]: [print_expr_struct_debug-183]Tmp is:XPATH:	Token NameTest, in expression "source"
netopeer2-server[6388]: [print_expr_struct_debug-183]Tmp is:XPATH:	Token Operator(Path), in expression "/"
netopeer2-server[6388]: [print_expr_struct_debug-183]Tmp is:XPATH:	Token NameTest, in expression "*"
netopeer2-server[6388]: [eval_absolute_location_path-6138]XPATH: eval_absolute_location_path parsed Operator(Path)[0]
netopeer2-server[6388]: [dict_insert-233]DICT: inserting (refcount) "copy-config"
netopeer2-server[6388]: [eval_node_test-5739]XPATH: eval_node_test              parsed NameTest[1]
netopeer2-server[6388]: [eval_relative_location_path-6039]XPATH: eval_relative_location_path parsed Operator(Path)[25]
netopeer2-server[6388]: [dict_insert-233]DICT: inserting (refcount) "source"
netopeer2-server[6388]: [eval_node_test-5739]XPATH: eval_node_test              parsed NameTest[26]
netopeer2-server[6388]: [eval_relative_location_path-6039]XPATH: eval_relative_location_path parsed Operator(Path)[32]
netopeer2-server[6388]: [dict_insert-233]DICT: inserting (refcount) "*"
netopeer2-server[6388]: [eval_node_test-5739]XPATH: eval_node_test              parsed NameTest[33]
netopeer2-server[6388]: (tid[139699712177920] 03:37:35:016544) (cl_request_process:417) Sending copy-config request.
netopeer2-server[6388]: (tid[139699712177920] 03:37:35:016606) (cl_request_process:439) copy-config request sent, waiting for response.
netopeer2-server[6388]: (tid[139699712177920] 03:37:35:019006) (cl_request_process:461) copy-config response received, processing.
netopeer2-server[6388]: (tid[139699712177920] 03:37:35:019059) (cl_request_process:484) Error by processing of the copy-config request (session id=927500260): Requested resource is already locked.
netopeer2-server[6388]: (tid[139699712177920] 03:37:35:019097) (sr_copy_config:1987) Error by processing of the request.
netopeer2-server[6388]: [dict_insert-202]DICT: inserting "Request could not be completed because the requested operation failed for a non-specific reason."
netopeer2-server[6388]: [dict_insert-274]DICT: inserting "en" with collision 
netopeer2-server[6388]: [dict_insert-274]DICT: inserting "Requested resource is already locked" with collision 
netopeer2-server[6388]: [dict_insert-274]DICT: inserting "en" with collision 
netopeer2-server[6388]: [nc_write-589]Session 1: sending message:

#304

[2017/01/06 03:37:35.019383, 3] ssh_socket_unbuffered_write:  Enabling POLLOUT for socket
[2017/01/06 03:37:35.019416, 3] packet_send2:  packet: wrote [len=28,padding=12,comp=15,payload=15]
[2017/01/06 03:37:35.019466, 3] channel_write_common:  channel_write wrote 6 bytes
netopeer2-server[6388]: [nc_write-589]Session 1: sending message:
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="21"><rpc-error><error-type>application</error-type><error-tag>operation-failed</error-tag><error-severity>error</error-severity><error-message xml:lang="en">Requested resource is already locked</error-message></rpc-error></rpc-reply>
[2017/01/06 03:37:35.019599, 3] packet_send2:  packet: wrote [len=332,padding=18,comp=313,payload=313]
[2017/01/06 03:37:35.019645, 3] channel_write_common:  channel_write wrote 304 bytes
[2017/01/06 03:37:35.019780, 3] ssh_socket_unbuffered_write:  Enabling POLLOUT for socket
netopeer2-server[6388]: [nc_write-589]Session 1: sending message:

##

[2017/01/06 03:37:35.019940, 3] packet_send2:  packet: wrote [len=28,padding=14,comp=13,payload=13]
[2017/01/06 03:37:35.019991, 3] channel_write_common:  channel_write wrote 4 bytes
[2017/01/06 03:37:35.020054, 3] ssh_socket_unbuffered_write:  Enabling POLLOUT for socket

**Comment by michalvasko** [comment]
Hi,
I tried it now on my machine (`devel` branches) and I think it works. Anyway, the server is simply sending what **sysrepo** responds with, so I think it would be their issue.

Regards,
Michal
