### ISSUE TITLE
Is there a way to delete whole list (not individual entries in a list)

### ISSUE THREAD

**Issue by rakichinni** [CESNET/netopeer2#882]
I have been trying to delete the whole list (not one at a time) through netopeer2-cli.

```
Yang:
list list1
{
  key id;
  leaf id
  {
    type string;
  }
}
```

**Below are the different xml blocks i tried:**

I thought if the key is not provided then the server will delete everything in the list but it is not.
```
<list1 xmlns="urn:model_1" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="delete">
</list1>
message:  Missing required element "id" in "list1".
```

Below one provides key but no value, thought the server will consider this as to clean all entries in list
```
<list1 xmlns="urn:model_1" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="delete">
 <id></id>
</list1>
message:  Node "list1" to be deleted does not exist.
```

Last try is to use replace instead of delete
```
<list1 xmlns="urn:model_1" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" xc:operation="replace">
</list1>
message:  Missing required element "id" in "list1".
```

Any suggestions.

Thanks,
Chinni.

**Comment by michalvasko** [comment]
This is not possible because NETCONF does not support it. However, you can do this in *sysrepo* itself, but that works only locally.

**Comment by rakichinni** [comment]
**“This is not possible because NETCONF does not support it. However, you can do this in sysrepo itself, but that works only locally.”**

^= What I understood from the above statement is that Netconf currently does not have support for cleaning up the whole list with one XML request. But it can be achieved by directly interacting with sysrepo. Please correct me.

--------------------------------------------------------

`[List delete](https://github.com/CESNET/libnetconf/issues/90)`, from the examples given here clearly gives an indication that libnetconf has the support for deleting the entire list.

**Comment by michalvasko** [comment]
> What I understood from the above statement is that Netconf currently does not have support for cleaning up the whole list with one XML request. But it can be achieved by directly interacting with sysrepo. Please correct me.

Yes, that is what I said.

> libnetconf has the support for deleting the entire list.

Right, it seems *libnetconf* did (incorrectly) support this. Like I said, *libnetconf2*/*netopeer2* is compliant with all the RFCs so it is not supported.
