### ISSUE TITLE
import ssh_callhome.xml fail

### ISSUE THREAD

**Issue by mcjackteng** [CESNET/netopeer2#883]
Hi
Sorry for interrupt you for helping me to figure out this issue

when I use sysrepocfg command to import the ssh_callhome.xml,it  show the error below:

root@localhost:/work/command/# sysrepocfg --import=ssh_callhome.xml -m ietf-netconf-server
[ERR]: Leafref "/ietf-keystore:keystore/ietf-keystore:asymmetric-keys/ietf-keystore:asymmetric-key/ietf-keystore:name" of value "genkey" points to a non-existing leaf. (path: /ietf-netconf-server:netconf-server/call-home/netconf-client[name='default-client']/endpoints/endpoint[name='default-ssh']/ssh/ssh-server-parameters/server-identity/host-key[name='default-key']/public-key/keystore-reference)
[ERR]: Validation failed.
sysrepocfg error: Replace config failed (Validation failed)

[ssh_callhome.zip](https://github.com/CESNET/netopeer2/files/6278006/ssh_callhome.zip)

Netopeer2 version:1.1.39
sysrepo version:1.4.70

**Comment by michalvasko** [comment]
Have you installed (`# make install`) *netopeer2*? It should import some default configuration as part of that, which includes the missing SSH key.

**Comment by mcjackteng** [comment]
Hi michalvasko
   This is caused by unexpected env LD_LIBRARY_PATH setting, when I change the item's order  of LD_LIBRARY_PATH ,it works well.
   I think it was caused by linking unexpected library which is not the compile time library.
   anyway , thanks
