### ISSUE TITLE
Is there a limit to how much edit-config can be logged when using -c MSG option?

### ISSUE THREAD

**Issue by wlau** [CESNET/netopeer2#884]
I am using this option to log/see the edit-config coming in to netopeer2-server.  What I noticed is that it works great for shorter edit-configs, but on longer edit-configs, when it spans more than ~70-100 lines, it gets cut's off and only less than 100 (varies) shows up.  Is there a limit set somewhere that can be changed?

.....
  <bbf-qos-cls:classifier-entry>
    <bbf-qos-cls:name>classifier_eg2</bbf-qos-cls:name>
    <bbf-qos-cls:filter-operation>bbf-qos-cls:match-all-filter</bbf-qos-cls:filter-operation>
    <bbf-qos-cls:classifier-action-entry-cfg>
      <bbf-qos-cls:action-type>bbf-qos-cls:scheduling-traffic-clas
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...

**Comment by michalvasko** [comment]
Could you please provide the whole output? I think the message is not "cut off" but simply split into several chunks and each chunk is written separately in the debug output since that is how *libnetconf2* is sending it.

**Comment by wlau** [comment]
I use the netopeer2-cli to send the edit-config.  I have included the last bits from the connect from the netopeer2-cli (which has a lot of output).  The edit config I sent after is starting from "----------------", which only 1st part is logged to the output.  The complete edit-config I sent is attached.

#1024


[DBG]: LN: Session 1: sending message:
 legal notices.";

  revision 2019-10-09 {
    description
      "Initial revision.";
    reference
      "TR-451: Section 5.2.1 vOMCI Function Connectivity";
  }

  grouping onu-criteria-grouping {
    description
      "The choice allows to specify combinations of ONU criteria
       values or allows to indicate any ONU.";
    choice onu-criterion {
      default "any-onu";
      description
        "ONU selection criterion values";
      case any-onu {
        leaf any-onu {
          type empty;
          description
            "Identifies any ONU";
        }
      }

      case onu-vendor {
        leaf onu-vendor {
          type bbf-vomci-types:onu-vendor-id;
          description
            "ONU vendor as defined in the TC layer ONU-ID.";
        }
      }

      case onu-serial-number {
        leaf onu-serial-number {
          type bbf-xpon-types:onu-serial-number;
          description
            "ONU serial number as defined in the TC layer
             ONU serial number.";
        }
      }
 

[DBG]: LN: Session 1: sending message:

#30


[DBG]: LN: Session 1: sending message:
   }
  }
}
</data></rpc-reply>

[DBG]: LN: Session 1: sending message:

##


[INF]: NP: Session 1: thread 0 event new RPC.




----------------



[DBG]: LN: Session 1: received message:
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="305"><edit-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><target><running/></target><default-operation>merge</default-operation><test-option>test-then-set</test-option><config>
<bbf-xpongemtcont:xpongemtcont xmlns:bbf-xpongemtcont="urn:bbf:yang:bbf-xpongemtcont">
  <bbf-xpongemtcont:traffic-descriptor-profiles>
    <bbf-xpongemtcont:traffic-descriptor-profile>
      <bbf-xpongemtcont:name>TDP0</bbf-xpongemtcont:name>
      <bbf-xpongemtcont:assured-bandwidth>10000000</bbf-xpongemtcont:assured-bandwidth>
      <bbf-xpongemtcont:fixed-bandwidth>10000000</bbf-xpongemtcont:fixed-bandwidth>
      <bbf-xpongemtcont:maximum-bandwidth>5000000000</bbf-xpongemtcont:maximum-bandwidth>
    </bbf-xpongemtcont:traffic-descriptor-profile>
  </bbf-xpongemtcont:traffic-descriptor-profiles>
</bbf-xpongemtcont:xpongemtcont>


<bbf-l2-d4r:l2-dhcpv4-relay-profiles xmlns:bbf-l2-d4r="urn:bbf:yang:bbf-l2-dhcpv4-relay">
  <bbf-l2-d4r:l2-dhcpv4-relay-profile>
    <bbf-l2-d4r:name>DHCP_Default</bbf-l2-d4r:name>
    <bbf-l2-d4r:max-packet-size>1500</bbf-l2-d4r:max-packet-size>
    <bbf-l2-d4r:option82-format>
      <bbf-l2-d4r:access-loop-suboptions/>
      <bbf-l2-d4r:default-circuit-id-syntax/>
      <bbf-l2-d4r:default-remote-id-syntax>N-VID:N2VID</bbf-l2-d4r:default-remote-id-syntax>
      <bbf-l2-d4r:start-numbering-from-zero>false</bbf-l2-d4r:start-numbering-from-zero>
      <bbf-l2-d4r:use-leading-zeroes>false</bbf-l2-d4r:use-leading-zeroes>
      <bbf-l2-d4r:suboptions>remote-id</bbf-l2-d4r:suboptions>
    </bbf-l2-d4r:option82-format>
  </bbf-l2-d4r:l2-dhcpv4-relay-profile>
</bbf-l2-d4r:l2-dhcpv4-relay-profiles>


<bbf-qos-cls:classifiers xmlns:bbf-qos-cls="urn:bbf:yang:bbf-qos-classifiers">
  <bbf-qos-cls:classifier-entry>
    <bbf-qos-cls:name>classifier_eg0</bbf-qos-cls:name>
    <bbf-qos-cls:filter-operation>bbf-qos-cls:match-all-filter</bbf-qos-cls:filter-operation>
    <bbf-qos-cls:classifier-action-entry-cfg>
      <bbf-qos-cls:action-type>bbf-qos-cls:scheduling-traffic-class</bbf-qos-cls:action-type>
      <bbf-qos-cls:scheduling-traffic-class>0</bbf-qos-cls:scheduling-traffic-class>
    </bbf-qos-cls:classifier-action-entry-cfg>
    <bbf-qos-cls:match-criteria>
      <bbf-qos-cls:any-protocol/>
      <bbf-qos-cls:dscp-range>any</bbf-qos-cls:dscp-range>
      <bbf-qos-cls:match-all/>
      <bbf-qos-plc:pbit-marking-list xmlns:bbf-qos-plc="urn:bbf:yang:bbf-qos-policing">
        <bbf-qos-plc:index>0</bbf-qos-plc:index>
        <bbf-qos-plc:pbit-value>0</bbf-qos-plc:pbit-value>
      </bbf-qos-plc:pbit-marking-list>
    </bbf-qos-cls:match-criteria>
  </bbf-qos-cls:classifier-entry>
  <bbf-qos-cls:classifier-entry>
    <bbf-qos-cls:name>classifier_eg1</bbf-qos-cls:name>
    <bbf-qos-cls:filter-operation>bbf-qos-cls:match-all-filter</bbf-qos-cls:filter-operation>
    <bbf-qos-cls:classifier-action-entry-cfg>
      <bbf-qos-cls:action-type>bbf-qos-cls:scheduling-traffic-class</bbf-qos-cls:action-type>
      <bbf-qos-cls:scheduling-traffic-class>1</bbf-qos-cls:scheduling-traffic-class>
    </bbf-qos-cls:classifier-action-entry-cfg>
    <bbf-qos-cls:match-criteria>
      <bbf-qos-cls:any-protocol/>
      <bbf-qos-cls:dscp-range>any</bbf-qos-cls:dscp-range>
      <bbf-qos-cls:match-all/>
      <bbf-qos-plc:pbit-marking-list xmlns:bbf-qos-plc="urn:bbf:yang:bbf-qos-policing">
        <bbf-qos-plc:index>0</bbf-qos-plc:index>
        <bbf-qos-plc:pbit-value>1</bbf-qos-plc:pbit-value>
      </bbf-qos-plc:pbit-marking-list>
    </bbf-qos-cls:match-criteria>
  </bbf-qos-cls:classifier-entry>
  <bbf-qos-cls:classifier-entry>
    <bbf-qos-cls:name>classifier_eg2</bbf-qos-cls:name>
    <bbf-qos-cls:filter-operation>bbf-qos-cls:match-all-filter</bbf-qos-cls:filter-operation>
    <bbf-qos-cls:classifier-action-entry-cfg>
      <bbf-qos-cls:action-type>bbf-qos-cls:scheduling-traffic-clas
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[INF]: NP: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
[INF]: LY: Resolving unresolved data nodes and their constraints...
[INF]: LY: All data nodes and constraints resolved.
[WRN]: LY: Augmentations from modules "bbf-xpon" and "bbf-ghn" have fatal hash collision.
[WRN]: LY: It will cause no errors if module "bbf-xpon" is always loaded before "bbf-ghn".
[WRN]: LY: Augmentations from modules "bbf-xpon" and "bbf-ghn" have fatal hash collision.
[WRN]: LY: It will cause no errors if module "bbf-xpon" is always loaded before "bbf-ghn".
[WRN]: LY: Augmentations from modules "bbf-xpon" and "bbf-ghn" have fatal hash collision.
[WRN]: LY: It will cause no errors if module "bbf-xpon" is always loaded before "bbf-ghn".
[DBG]: LN: Session 1: sending message:

#93


[DBG]: LN: Session 1: sending message:
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="305"><ok/></rpc-reply>

[DBG]: LN: Session 1: sending message:

##


[INF]: NP: Session 1: thread 3 event new RPC.
[ERR]: LN: Session 1: session idle timeout elapsed.
[INF]: NP: Session 1: thread 2 event session terminated.
[INF]: NP: Generated new event (netconf-session-end).

[All-1-infra.txt](https://github.com/CESNET/netopeer2/files/6305512/All-1-infra.txt)

**Comment by michalvasko** [comment]
Right, the truncating was occurring deeper in the code that I looked, sorry. Should be fixed now.

**Comment by wlau** [comment]
Thank you, we will test it out.
