### ISSUE TITLE
callhome proc but Failed user "user" authentication attempt

### ISSUE THREAD

**Issue by myonlystarWang** [CESNET/netopeer2#885]
Hi Michal,
     I have installed netopeer2-1.1.27 and sysrepo-1.4.58 in one machine for new test environment.But I met a problem which I never seen before:
     ![log](https://user-images.githubusercontent.com/65654902/114988241-b1e2a300-9ec8-11eb-9ae5-8a909f40c18b.png)
     libssh was re-installed and version is 0.9.5
     The error log 
```
      Failed user "user" authentication attempt(#2)
      Communication SSH socket unexpectly closed
```
      

I really don't know how to fix it,I hope you can give me some advice!!

BR,
wang

**Comment by michalvasko** [comment]
What client are you using, did it print anything? From the server log it seems you have tried to authenticate first using the `keyboard-interactive` method, then `password`. Both failed and probably because of that the client disconnected.

**Comment by myonlystarWang** [comment]
Hi michal,
     Thanks for your response.
     I re-installed the netopeer2-server and the problem has gone.
     This was probably a problem I had myself during the installation
     I am sorry to bother you.Now let me close the issue.Thank you.

BR,
Wang
