### ISSUE TITLE
sysrepocfg error: libyang: Unknown element "keepalives".

### ISSUE THREAD

**Issue by xheke** [CESNET/netopeer2#886]
I  meet same issue like 1969:
[1969](https://github.com/sysrepo/sysrepo/issues/1969)

then I use `make sr_clean`  as 1969 suggestion.

And add "oven" successfully, but I see all Netopeer2 related yang have been cleared yet.
I add them one by one from Netopeer2 src folder.

But Netopeer2 server still not work.
Seems the netopeer2 server ssh listener on port 830 not start.

And netopeer2 client get below error:

```
connect localhost
nc ERROR: connect() failed (Cannot assign requested address).
nc ERROR: Unable to connect to localhost:830 (Cannot assign requested address).
```

So, I try to run below script,
`./sysrepocfg --edit=/src/Netopeer2/example_configuration/ssh_callhome.xml`

But get below error:
```
sysrepocfg error: libyang: Unknown element "keepalives".
sysrepocfg error: Data parsing failed
```

the version information as following:
```
./sysrepocfg -V
sysrepocfg - sysrepo configuration manipulation tool, compiled with libsysrepo v1.4.122 (SO v5.6.38)
```

Please kindly help how to resolve this issue and let Netopeer2 go back to work?

**Comment by michalvasko** [comment]
Could you share the steps for reproducing the internal error (if that is what you are referring to)? Everything else, starting from installing *netopeer2* modules by hand, is wrong and you should not be doing that. It is expected that nothing works after that.

**Comment by xheke** [comment]
Hi Michal,

The netopeer2 is installed by my colleague in docker.
I test it, seems everything is fine, such as netopeer2 server start normally and listen on the port 830.
And netopeer2 client connect to the netopeer2 server by using `connect localhost` and using `get-config --source running` also get expected result.

Then, I try to run sysrepo `oven` example.
First, I use `sysrepoctl -i  oven.yang`, I see `oven` installed without error, but status is `N`, and sysrepo plug-in can not work, it always said, "oven is unknow module".

Second, I follow  1969 suggestion, use `make sr_clean`, and reinstall oven.yang, this time, oven module status is 'i‘, I believe it works. but unfortunately,  I see here many yang modules be removed by sr_clean.  And netopeer2 server can not start yet.

Third,  I  try to reinstall all yang modules under netopeer2 source folder and enable some features following netopeer2 server output message when start until no error message.
But I don't see listener start on the port 830.

the last step, I follow netopeer2 doc, try to run `ssh_callhome.xml` and get `sysrepocfg error: libyang: Unknown element "keepalives".`

I have no more idea, how to get the next step  :(

**Comment by michalvasko** [comment]
> First, I use sysrepoctl -i oven.yang, I see oven installed without error, but status is N, and sysrepo plug-in can not work, it always said, "oven is unknow module".

If you run `sysrepoctl -l -v3` instead, you should be informed about the reason why the module status is always `N`. Specifically, because you must now have any *sysrepo* applications (including *netopeer2-server* or *sysrepo-plugind*) running if you want to install a new module.

Please do not run `make sr_clean` when you have some *sysrepo* applications running, it removes all the data from under them so no wonder you get an internal error, I am surprised it did not crash.

**Comment by xheke** [comment]
Thanks Michael， I got it, just like you point out,  I stop sysrepo applications and reinstall oven module successfully.
