### ISSUE TITLE
NETCONF Access Control group users could not initiate "subscribe to Notifications"

### ISSUE THREAD

**Issue by ramiyer92** [CESNET/netopeer2#891]
Hello @michalvasko 

I am using yang-version 1.1. From my netopeer client, I have logged in with the user that is been mapped with the NETCONF Access Control groups "sudo”, “nms”, “fm-pm”, and “swm”.

As mentioned in the table **Table 2: Mapping of account groupings to O-RU module privileges** ORAN-WG4.MP.0-v02.00.00, I am unable to subscribe with any of the users that are mapped with these access groups. 

I am getting the below-mentioned error from my Netopeer client. As mentioned in the table only "sudo" group have RW rules defined. Can you help me out ?
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
$ netopeer2-cli 
> connect --ssh --host 192.168.1.10 --port 830 --login Observer
Interactive SSH Authentication
Type your password:
Password: 
> subscribe 
ERROR
	type:     application
	tag:      access-denied
	severity: error
	path:     /notifications:create-subscription
	message:  Executing the operation is denied because "Observer" NACM authorization failed.

> status 
Current NETCONF session:
  ID          : 3
  Host        : 192.168.1.10
  Port        : 830
  Transport   : SSH
  Capabilities:
	urn:ietf:params:netconf:base:1.0
	urn:ietf:params:netconf:base:1.1
	urn:ietf:params:netconf:capability:writable-running:1.0
	urn:ietf:params:netconf:capability:candidate:1.0
	urn:ietf:params:netconf:capability:rollback-on-error:1.0
	urn:ietf:params:netconf:capability:validate:1.1
	urn:ietf:params:netconf:capability:startup:1.0
	urn:ietf:params:netconf:capability:xpath:1.0
	urn:ietf:params:netconf:capability:with-defaults:1.0?basic-mode=explicit&also-supported=report-all,report-all-tagged,trim,explicit
	urn:ietf:params:netconf:capability:notification:1.0
	urn:ietf:params:netconf:capability:interleave:1.0
	urn:ietf:params:xml:ns:yang:ietf-yang-metadata?module=ietf-yang-metadata&revision=2016-08-05
	urn:ietf:params:xml:ns:yang:1?module=yang&revision=2017-02-20
	urn:ietf:params:xml:ns:yang:ietf-inet-types?module=ietf-inet-types&revision=2013-07-15
	urn:ietf:params:xml:ns:yang:ietf-yang-types?module=ietf-yang-types&revision=2013-07-15
	urn:ietf:params:netconf:capability:yang-library:1.1?revision=2019-01-04&content-id=60
	urn:sysrepo:plugind?module=sysrepo-plugind&revision=2020-12-10
	urn:ietf:params:xml:ns:yang:ietf-netconf-acm?module=ietf-netconf-acm&revision=2018-02-14
	urn:ietf:params:xml:ns:netconf:base:1.0?module=ietf-netconf&revision=2013-09-29&features=writable-running,candidate,rollback-on-error,validate,startup,url,xpath
	urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults?module=ietf-netconf-with-defaults&revision=2011-06-01
	urn:ietf:params:xml:ns:yang:ietf-netconf-notifications?module=ietf-netconf-notifications&revision=2012-02-06
	urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring?module=ietf-netconf-monitoring&revision=2010-10-04
	urn:ietf:params:xml:ns:netconf:notification:1.0?module=notifications&revision=2008-07-14
	urn:ietf:params:xml:ns:netmod:notification?module=nc-notifications&revision=2008-07-14
	urn:ietf:params:xml:ns:yang:ietf-x509-cert-to-name?module=ietf-x509-cert-to-name&revision=2014-12-10
	urn:ietf:params:xml:ns:yang:iana-crypt-hash?module=iana-crypt-hash&revision=2014-08-06
	urn:notification_history?module=notification_history
	urn:ietf:params:xml:ns:yang:iana-if-type?module=iana-if-type&revision=2017-01-19
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by michalvasko** [comment]
Please paste the NACM configuration, otherwise I cannot help you.

**Comment by ramiyer92** [comment]
@michalvasko I have pasted the below NACM configuration used. 

-------------------------------------------------------------------------------------------------
<nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
  <enable-nacm>true</enable-nacm>
  <read-default>false</read-default>
  <write-default>false</write-default>
  <exec-default>false</exec-default>
  <enable-external-groups>false</enable-external-groups>
  <groups>
    <group>
      <name>sudo</name>
      <user-name>Operator</user-name>
    </group>
    <group>
      <name>nms</name>
      <user-name>Observor</user-name>
    </group>
    <group>
      <name>swm</name>
      <user-name>Installer</user-name>
      <user-name>vvdn</user-name>
    </group>
	    <group>
      <name>fm-pm</name>
      <user-name>Activator</user-name>
    </group>
  </groups>
  <rule-list>
    <name>sudo-access</name>
    <group>sudo</group>
    <rule>
      <name>ietf-netconf-permission</name>
      <module-name>ietf-netconf</module-name>
      <access-operations>exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-supervision-permission</name>
      <module-name>o-ran-supervision</module-name>
      <access-operations>exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-hardware-permission</name>
      <module-name>o-ran-hardware</module-name>
      <access-operations>read exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-hardware-permission</name>
      <module-name>ietf-hardware</module-name>
      <access-operations>create read update delete exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>iana-hardware-permission</name>
      <module-name>iana-hardware</module-name>
      <access-operations>create read update delete exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-usermgmt-permission1</name>
      <module-name>o-ran-usermgmt</module-name>
      <path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:users/o-ran-usermgmt:user/o-ran-usermgmt:name</path>
      <access-operations>create read update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-usermgmt-permission2</name>
      <module-name>o-ran-usermgmt</module-name>
      <path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:users/o-ran-usermgmt:user/o-ran-usermgmt:account-type</path>
      <access-operations>create read update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-usermgmt-permission3</name>
      <module-name>o-ran-usermgmt</module-name>
      <path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:users/o-ran-usermgmt:user/o-ran-usermgmt:password</path>
      <access-operations>create update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-usermgmt-permission4</name>
      <module-name>o-ran-usermgmt</module-name>
      <path xmlns:o-ran-usermgmt="urn:o-ran:user-mgmt:1.0">/o-ran-usermgmt:users/o-ran-usermgmt:user/o-ran-usermgmt:enabled</path>
      <access-operations>create read update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-fm-permission</name>
      <module-name>o-ran-fm</module-name>
      <access-operations>read exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-sync-permission</name>
      <module-name>o-ran-sync</module-name>
      <access-operations>create read update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-delay-management-permission</name>
      <module-name>o-ran-delay-management</module-name>
      <access-operations>create read update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-module-cap-permission</name>
      <module-name>o-ran-module-cap</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-udp-echo-permission</name>
      <module-name>o-ran-udp-echo</module-name>
      <access-operations>create read update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-operations-permission</name>
      <module-name>o-ran-operations</module-name>
      <access-operations>read exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-uplane-conf</name>
      <module-name>o-ran-uplane-conf</module-name>
      <access-operations>create read update delete exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-lbm-permission</name>
      <module-name>o-ran-lbm</module-name>
      <access-operations>create read update delete exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-software-management-permission</name>
      <module-name>o-ran-software-management</module-name>
      <access-operations>create read update delete exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-file-management-permission</name>
      <module-name>o-ran-file-management</module-name>
      <access-operations>exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-performance-management-permission</name>
      <module-name>o-ran-performance-management</module-name>
      <access-operations>create read update delete exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-transceiver-permission</name>
      <module-name>o-ran-transceiver</module-name>
      <access-operations>create read update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-interfaces-permission</name>
      <module-name>o-ran-interfaces</module-name>
      <access-operations>create read update delete exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-ip-permission</name>
      <module-name>ietf-ip</module-name>
      <access-operations>create read update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-interfaces-permission</name>
      <module-name>ietf-interfaces</module-name>
      <access-operations>create read update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>iana-if-type-permission</name>
      <module-name>iana-if-type</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-inet-types-permission</name>
      <module-name>ietf-inet-types</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-processing-elements-permission</name>
      <module-name>o-ran-processing-elements</module-name>
      <access-operations>create read update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-mplane-interfaces-permission</name>
      <module-name>o-ran-mplane-interfaces</module-name>
      <access-operations>create read update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-dhcp-permission</name>
      <module-name>o-ran-dhcp</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-troubleshooting-permission</name>
      <module-name>o-ran-troubleshooting</module-name>
      <access-operations>exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-trace-permission</name>
      <module-name>o-ran-trace</module-name>
      <access-operations>exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-netconf-acm-permission</name>
      <module-name>ietf-netconf-acm</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-yang-library-permission</name>
      <module-name>ietf-yang-library</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-netconf-monitoring-permission</name>
      <module-name>ietf-netconf-monitoring</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
  </rule-list>
  <rule-list>
    <name>nms-access</name>
    <group>nms</group>
    <rule>
      <name>ietf-netconf-permission</name>
      <module-name>ietf-netconf</module-name>
      <access-operations>exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-hardware-permission</name>
      <module-name>o-ran-hardware</module-name>
      <access-operations>read exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-hardware-permission</name>
      <module-name>ietf-hardware</module-name>
      <access-operations>create read update delete exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>iana-hardware-permission</name>
      <module-name>iana-hardware</module-name>
      <access-operations>create read update delete exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-fm-permission</name>
      <module-name>o-ran-fm</module-name>
      <access-operations>read exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-sync-permission</name>
      <module-name>o-ran-sync</module-name>
      <access-operations>create read update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-delay-management-permission</name>
      <module-name>o-ran-delay-management</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-module-cap-permission</name>
      <module-name>o-ran-module-cap</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-udp-echo-permission</name>
      <module-name>o-ran-udp-echo</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-operations-permission</name>
      <module-name>o-ran-operations</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-uplane-conf</name>
      <module-name>o-ran-uplane-conf</module-name>
      <access-operations>create read update delete exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-lbm-permission</name>
      <module-name>o-ran-lbm</module-name>
      <access-operations>create read update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-software-management-permission</name>
      <module-name>o-ran-software-management</module-name>
      <access-operations>create read update delete exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-file-management-permission</name>
      <module-name>o-ran-file-management</module-name>
      <access-operations>exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-performance-management-permission</name>
      <module-name>o-ran-performance-management</module-name>
      <access-operations>create read update delete exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-transceiver-permission</name>
      <module-name>o-ran-transceiver</module-name>
      <access-operations>create read update delete exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-interfaces-permission</name>
      <module-name>o-ran-interfaces</module-name>
      <access-operations>create read update delete exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-ip-permission</name>
      <module-name>ietf-ip</module-name>
      <access-operations>create read update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-interfaces-permission</name>
      <module-name>ietf-interfaces</module-name>
      <access-operations>create read update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>iana-if-type-permission</name>
      <module-name>iana-if-type</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-inet-types-permission</name>
      <module-name>ietf-inet-types</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-processing-elements-permission</name>
      <module-name>o-ran-processing-elements</module-name>
      <access-operations>create read update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-mplane-interfaces-permission</name>
      <module-name>o-ran-mplane-interfaces</module-name>
      <access-operations>create read update delete</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-dhcp-permission</name>
      <module-name>o-ran-dhcp</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-troubleshooting-permission</name>
      <module-name>o-ran-troubleshooting</module-name>
      <access-operations>exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-trace-permission</name>
      <module-name>o-ran-trace</module-name>
      <access-operations>exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-netconf-acm-permission</name>
      <module-name>ietf-netconf-acm</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-yang-library-permission</name>
      <module-name>ietf-yang-library</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-netconf-monitoring-permission</name>
      <module-name>ietf-netconf-monitoring</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
  </rule-list>
  <rule-list>
    <name>fm-pm-access</name>
    <group>fm-pm</group>
    <rule>
      <name>ietf-netconf-permission</name>
      <module-name>ietf-netconf</module-name>
      <access-operations>exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-hardware-permission</name>
      <module-name>ietf-hardware</module-name>
      <access-operations>read exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>iana-hardware-permission</name>
      <module-name>iana-hardware</module-name>
      <access-operations>read exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-fm-permission</name>
      <module-name>o-ran-fm</module-name>
      <access-operations>read exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-sync-permission</name>
      <module-name>o-ran-sync</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-delay-management-permission</name>
      <module-name>o-ran-delay-management</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-module-cap-permission</name>
      <module-name>o-ran-module-cap</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-operations-permission</name>
      <module-name>o-ran-operations</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-uplane-conf</name>
      <module-name>o-ran-uplane-conf</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-lbm-permission</name>
      <module-name>o-ran-lbm</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-software-management-permission</name>
      <module-name>o-ran-software-management</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-file-management-permission</name>
      <module-name>o-ran-file-management</module-name>
      <access-operations>exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-performance-management-permission</name>
      <module-name>o-ran-performance-management</module-name>
      <access-operations>create read update delete exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-transceiver-permission</name>
      <module-name>o-ran-transceiver</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-interfaces-permission</name>
      <module-name>o-ran-interfaces</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-ip-permission</name>
      <module-name>ietf-ip</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-interfaces-permission</name>
      <module-name>ietf-interfaces</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>iana-if-type-permission</name>
      <module-name>iana-if-type</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-inet-types-permission</name>
      <module-name>ietf-inet-types</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-processing-elements-permission</name>
      <module-name>o-ran-processing-elements</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-mplane-interfaces-permission</name>
      <module-name>o-ran-mplane-interfaces</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-dhcp-permission</name>
      <module-name>o-ran-dhcp</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-troubleshooting-permission</name>
      <module-name>o-ran-troubleshooting</module-name>
      <access-operations>exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-trace-permission</name>
      <module-name>o-ran-trace</module-name>
      <access-operations>exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-netconf-acm-permission</name>
      <module-name>ietf-netconf-acm</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-yang-library-permission</name>
      <module-name>ietf-yang-library</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-netconf-monitoring-permission</name>
      <module-name>ietf-netconf-monitoring</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
  </rule-list>
  <rule-list>
    <name>swm-access</name>
    <group>swm</group>
    <rule>
      <name>ietf-netconf-permission</name>
      <module-name>ietf-netconf</module-name>
      <access-operations>exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>o-ran-software-management-permission</name>
      <module-name>o-ran-software-management</module-name>
      <access-operations>create read update delete exec</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>iana-if-type-permission</name>
      <module-name>iana-if-type</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-inet-types-permission</name>
      <module-name>ietf-inet-types</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-netconf-acm-permission</name>
      <module-name>ietf-netconf-acm</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-yang-library-permission</name>
      <module-name>ietf-yang-library</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
    <rule>
      <name>ietf-netconf-monitoring-permission</name>
      <module-name>ietf-netconf-monitoring</module-name>
      <access-operations>read</access-operations>
      <action>permit</action>
    </rule>
  </rule-list>
</nacm>

**Comment by michalvasko** [comment]
The problem is that `create-subscription` RPC (which is actually generated for the `subscribe` CLI command) is in the [notification](https://github.com/CESNET/netopeer2/blob/master/modules/notifications%402008-07-14.yang#L31) module so you need to set specific permissions for that one.

**Comment by ramiyer92** [comment]
@michalvasko Thank you, will implement and get back regarding the same.
