### ISSUE TITLE
upgrade sysrepo and netopeer2 failed

### ISSUE THREAD

**Issue by xheke** [CESNET/netopeer2#892]
I want upgrade sysrepo and netopeer2 to latest code.

Seems sysrepo is OK, but netopeer2 is failed on "make install" step.

Below is netopeer2 install failed information, how to resolve this issue?

Thanks,

```

-- Installing missing sysrepo modules...
[WRN]: Recovered a lock with a dead owner (sr_lydmods_conn_ctx_update).
/src/CESNET/github/netopeer2/scripts//setup.sh: line 51:  4059 Segmentation fault      (core dumped) '/usr/local/bin/sysrepoctl' -a -i /usr/local/share/yang/modules/netopeer2/ietf-netconf-acm@2018-02-14.yang -s '/usr/local/share/yang/modules/netopeer2' -p '600' -v2 -o 'root' -g 'root'
CMake Error at cmake_install.cmake:81 (message):
   scripts/setup.sh failed: 139
```

seems it is caused by:

`./sysrepoctl -a -i /usr/local/share/yang/modules/netopeer2/ietf-netconf-acm@2018-02-14.yang -s '/usr/local/share/yang/modules/netopeer2' -p '600' -v2 -o 'root' -g 'root'`

```
[WRN]: Recovered a lock with a dead owner (sr_lydmods_conn_ctx_update).
Segmentation fault (core dumped)
```

**Comment by michalvasko** [comment]
Unfortunately, there is no special support for upgrading *sysrepo*. Especially if you are updating between releases, you should reset *sysrepo* state first by calling `make sr_clean`, which will delete all the installed modules and data that you may have had in *sysrepo* previously.

**Comment by xheke** [comment]
Hi Michal.,

I use make sr_clean and make shm_clean.
But netopeer still report error as following:

```
-- Installing missing sysrepo modules...
[ERR]: Opening "/src/CESNET/github/sysrepo/build/repository/data/sysrepo.startup" failed (No such file or directory).
[WRN]: Recovering "sysrepo" startup data from a backup.
[ERR]: Opening "/src/CESNET/github/sysrepo/build/repository/data/sysrepo.startup.bck" failed (No such file or directory).
[ERR]: rename() failed (No such file or directory).
[WRN]: Recovered a lock with a dead owner (sr_lydmods_conn_ctx_update).
/src/CESNET/github/netopeer2/scripts//setup.sh: line 51:  6598 Segmentation fault      (core dumped) '/usr/local/bin/sysrepoctl' -a -i /usr/local/share/yang/modules/netopeer2/ietf-netconf-acm@2018-02-14.yang -s '/usr/local/share/yang/modules/netopeer2' -p '600' -v2 -o 'root' -g 'root'
CMake Error at cmake_install.cmake:81 (message):
   scripts/setup.sh failed: 139
```

**Comment by xheke** [comment]
after reinstall sysrepo,  I found sysrepoctl will crash as following, 
I think it is root cause, but how to resolve it?

```
./sysrepoctl -l
Segmentation fault (core dumped)
```

**Comment by xheke** [comment]
(gdb) r -l
Starting program: /usr/local/bin/sysrepoctl -l
Missing separate debuginfos, use: yum debuginfo-install glibc-2.28-127.el8.x86_64
warning: Loadable section ".note.gnu.property" outside of ELF segments
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
warning: Loadable section ".note.gnu.property" outside of ELF segments

Program received signal SIGSEGV, Segmentation fault.
sr_lydmods_ctx_load_modules (sr_mods=0x621fa0, ly_ctx=0x6065d0, removed=1, 
    updated=1, change=0x0) at /src/CESNET/github/sysrepo/src/lyd_mods.c:1026
1026	        if (!strcmp(sr_mod->schema->name, "installed-module")) {
Missing separate debuginfos, use: yum debuginfo-install libatomic-8.3.1-5.1.el8.x86_64
(gdb) p sr_mod->schema->name
Cannot access memory at address 0x1000000009
(gdb) p sr_mod->schema
$1 = (struct lys_node *) 0x1000000009
(gdb) p sr_mod
$2 = (struct lyd_node *) 0x638630
(gdb) p *sr_mod
$3 = {schema = 0x1000000009, validity = 0 '\000', dflt = 0 '\000', 
  when_status = 0 '\000', attr = 0x7ffff74d0bf0 <lyd_hash_table_val_equal>, 
  next = 0x0, prev = 0x100002, parent = 0x639ff0, hash = 6493008, ht = 0xe1, 
  child = 0x616b60}

**Comment by michalvasko** [comment]
What *sysrepo* version are you trying to use? In an case, try to install it with a clean state, there is most likely something wrong on your system. Start by running `make sr_clean` for *sysrepo*, then run `make uninstall`, `make clean`, `make`, and `make install` for all the projects.

**Comment by xheke** [comment]
Hi Michal,

I can reproduce this issue.

if we upgrade by below order, there is ok with no problem.
```
step 1, upgrade sysrepo
step 2, upgrade libyang
```

But if we upgrade by below order,  sysrepoctl will crash and can't repair even run make sr_clean/uninstall/clean..

```
step 1, upgrade libyang
step 2, upgrade sysrepo
```

For first installation, there should install libyang before sysrepo, is that right?
But why it not work for upgrade?

**Comment by xheke** [comment]
netopeer2 have same issue.
The upgrade order should follow below step:

1, sysrepo
2, netopeer2
3, libnetconf
4, libyang

otherwise, netopeer-server will crash as sysrepoctl.

**Comment by xheke** [comment]
Seem it is libyang problem.

I found that after reinstall libyang,  sysrepo and netopeer2 can not install again.

**Comment by xheke** [comment]
using clean environment and re-install all software successfully.
