### ISSUE TITLE
Issues/Queries with sr_get APIs

### ISSUE THREAD

**Issue by jjin62** [CESNET/netopeer2#893]
Hi,

there are following APIs for get data for a non-leaf node:
int sr_get_items(sr_session_ctx_t *session, const char *xpath, uint32_t timeout_ms, const sr_get_oper_options_t opts,  sr_val_t **values, size_t *value_cnt);
**issue:** opts is not used in the implementation of the API. so it does not take effect.

int sr_get_subtree(sr_session_ctx_t *session, const char *path, uint32_t timeout_ms, struct lyd_node **subtree);
**issue**: there is no sr_get_oper_options_t as input parameter.

int sr_get_data(sr_session_ctx_t *session, const char *xpath, uint32_t max_depth, uint32_t timeout_ms, const sr_get_oper_options_t opts, struct lyd_node **data);
**this works fine.**

I wonder we can add opts as input for sr_get_subtree and pass opts into sr_modinfo_add_modules()  in the implementation of sr_get_items(). This would make all 3 above APIs consistent?

thanks,
Jimmy

**Comment by michalvasko** [comment]
Thanks for noticing the unused options, that was a bug and should be fixed now. Other than that, it is designed this way intentionally. There are 2 APIs (`sr_val_t` and `struct lyd_node`) and both have a simple getter (you forgot `sr_get_item`) and a complex one, only the complex one has options and it always provides a superset of the simpler getter functionality.

**Comment by jjin62** [comment]
thanks for the fix and comments.
