### ISSUE TITLE
How to avoid exposing the YANG model for internal use

### ISSUE THREAD

**Issue by lqlucky** [CESNET/netopeer2#894]
Hi,

Have a question about that some Yang models are intended for internal use only, but they can be obtained through the "get " command on netopeer cli. Is there any way to avoid this situation?

**Comment by michalvasko** [comment]
No, there is currently no way of doing this. But since you are at least 5th one asking for this, I will add it to my TODO list, just do not expect it too soon.

**Comment by lqlucky** [comment]
Thanks for your replay and appreciate will do that. 
I have tried to use NACM which can forbid access the data but not the model itself.
I'd like to modify the code of netopeer2 or sysrepo to avoid that, although it is not a good way.
