### ISSUE TITLE
Invalid context for LYB data parsing, missing module "ietf-ip@2018-02-22"

### ISSUE THREAD

**Issue by zewei0920** [CESNET/netopeer2#896]
Hi, I compiled the sysrepoctl version 1.4.122 on Centos7.3. I want to install some Yang models which I download form here: https://github.com/YangModels/yang/tree/master/standard/ietf/RFC.
when install the  ietf-interfaces.yang, everything seems ok, but gtt error message as below when execute "sysrepoctl -l" after installed ietf-ip@2018-02-22.yang.  and then any sysrepoctl cmd failed to excute with the same error message excpet only "sysrepoctl --help".

please help to check.
Thanks a lot.
Jim

`
[root@localhost modules_hn]# sysrepoctl -i ietf-interfaces.yang
[root@localhost modules_hn]# sysrepoctl -l
Sysrepo repository: /apps/sysrepo-1.4.122/build/repository

Module Name                | Revision   | Flags | Owner     | Permissions | Submodules | Features
-------------------------------------------------------------------------------------------------
ietf-datastores            | 2018-02-14 | I     | root:root | 664         |            |
ietf-inet-types            | 2013-07-15 | i     |           |             |            |
ietf-interfaces            | 2018-02-20 | I     | root:root | 600         |            |
ietf-netconf               | 2011-06-01 | I     | root:root | 664         |            |
ietf-netconf-notifications | 2012-02-06 | I     | root:root | 664         |            |
ietf-netconf-with-defaults | 2011-06-01 | I     | root:root | 664         |            |
ietf-origin                | 2018-02-14 | I     | root:root | 664         |            |
ietf-yang-library          | 2019-01-04 | I     | root:root | 664         |            |
ietf-yang-metadata         | 2016-08-05 | i     |           |             |            |
ietf-yang-types            | 2013-07-15 | i     |           |             |            |
sysrepo-monitoring         | 2021-01-15 | I     | root:root | 600         |            |
sysrepo-plugind            | 2020-12-10 | I     | root:root | 664         |            |
yang                       | 2017-02-20 | I     | root:root | 664         |            |

Flags meaning: I - Installed/i - Imported; R - Replay support; N - New/X - Removed/U - Updated; F - Feature changes
Features: ! - Means that the feature is effectively disabled because of its false if-feature(s)

[root@localhost modules_hn]# sysrepoctl -i ietf-ip\@2018-02-22.yang
[root@localhost modules_hn]# sysrepoctl -l
[ERR]: Invalid context for LYB data parsing, missing module "ietf-ip@2018-02-22".
[ERR]: Failed to update data for the new context.
sysrepoctl error: Failed to connect (Operation failed)
[root@localhost modules_hn]# sysrepoctl -u ietf-ip\@2018-02-22.yang
[ERR]: Invalid context for LYB data parsing, missing module "ietf-ip@2018-02-22".
[ERR]: Failed to update data for the new context.
sysrepoctl error: Failed to connect (Operation failed)
[root@localhost modules_hn]# sysrepoctl -c ietf-ip\@2018-02-22.yang --owner=root:root --permission=644
[ERR]: Invalid context for LYB data parsing, missing module "ietf-ip@2018-02-22".
[ERR]: Failed to update data for the new context.
sysrepoctl error: Failed to connect (Operation failed)
[root@localhost modules_hn]#
[root@localhost modules_hn]#`

**Comment by zewei0920** [comment]
hi, michalvasko, thanks a lot for your reply. I download source code of the latest official released version, and compile on Centos7.3.   
sysrepo-1.4.122
netopeer2-1.1.70
libyang-1.0.225
libssh-0.7.2
libnetconf2-1.1.43

1. I tried this way as blow to work around the issue of "missing module "ietf-ip@2018-02-22"
sysrepoctl -i iana-if-type.yang  -a -o root -p 644 -s ./
sysrepoctl -i ietf-ip.yang  -a -o root -p 644 -s ./

2. but unfortunately, I got another similar error message when install  the "openconfig-if-ethernet.yang" as below:

`[root@localhost openconfig]# sysrepoctl -l
Sysrepo repository: /apps/sysrepo-1.4.122/build/repository

Module Name                  | Revision   | Flags | Owner     | Permissions | Submodules | Features
------------------------------------------------------------------------------------------------------------------------------------------------------------------
iana-crypt-hash              | 2014-08-06 | i     |           |             |            |
iana-if-type                 | 2017-01-19 | I     | root:root | 644         |            |
ietf-crypto-types            | 2019-07-02 | I     | root:root | 600         |            |
ietf-datastores              | 2018-02-14 | I     | root:root | 664         |            |
ietf-inet-types              | 2013-07-15 | i     |           |             |            |
ietf-interfaces              | 2018-02-20 | I     | root:root | 600         |            |
ietf-ip                      | 2018-02-22 | I     | root:root | 644         |            |
ietf-keystore                | 2019-07-02 | I     | root:root | 600         |            | keystore-supported
ietf-netconf                 | 2013-09-29 | I     | root:root | 600         |            | writable-running candidate rollback-on-error validate startup url xpath
ietf-netconf-acm             | 2018-02-14 | I     | root:root | 600         |            |
ietf-netconf-monitoring      | 2010-10-04 | I     | root:root | 600         |            |
ietf-netconf-nmda            | 2019-01-07 | I     | root:root | 600         |            | origin with-defaults
ietf-netconf-notifications   | 2012-02-06 | I     | root:root | 664         |            |
ietf-netconf-server          | 2019-07-02 | I     | root:root | 600         |            | ssh-listen tls-listen ssh-call-home tls-call-home
ietf-netconf-with-defaults   | 2011-06-01 | I     | root:root | 664         |            |
ietf-origin                  | 2018-02-14 | I     | root:root | 664         |            |
ietf-ssh-common              | 2019-07-02 | i     |           |             |            |
ietf-ssh-server              | 2019-07-02 | I     | root:root | 600         |            | local-client-auth-supported
ietf-tcp-client              | 2019-07-02 | i     |           |             |            |
ietf-tcp-common              | 2019-07-02 | I     | root:root | 600         |            | keepalives-supported
ietf-tcp-server              | 2019-07-02 | i     |           |             |            |
ietf-tls-common              | 2019-07-02 | i     |           |             |            |
ietf-tls-server              | 2019-07-02 | I     | root:root | 600         |            | local-client-auth-supported
ietf-truststore              | 2019-07-02 | I     | root:root | 600         |            | truststore-supported x509-certificates
ietf-x509-cert-to-name       | 2014-12-10 | I     | root:root | 600         |            |
ietf-yang-library            | 2019-01-04 | I     | root:root | 664         |            |
ietf-yang-metadata           | 2016-08-05 | i     |           |             |            |
ietf-yang-types              | 2013-07-15 | i     |           |             |            |
nc-notifications             | 2008-07-14 | I     | root:root | 600         |            |
notifications                | 2008-07-14 | I     | root:root | 600         |            |
openconfig-alarm-mask-types  | 2020-06-17 | I     | root:root | 644         |            |
openconfig-alarm-types       | 2020-06-30 | I     | root:root | 644         |            |
openconfig-extensions        | 2018-10-17 | I     | root:root | 644         |            |
openconfig-if-types          | 2018-11-21 | I     | root:root | 644         |            |
openconfig-inet-types        | 2019-04-25 | I     | root:root | 644         |            |
openconfig-lldp-types        | 2018-11-21 | I     | root:root | 644         |            |
openconfig-performance-types | 2020-06-30 | I     | root:root | 644         |            |
openconfig-platform-types    | 2020-06-30 | I     | root:root | 644         |            |
openconfig-telemetry-types   | 2018-11-21 | I     | root:root | 644         |            |
openconfig-transport-types   | 2020-06-30 | I     | root:root | 644         |            |
openconfig-types             | 2020-06-30 | I     | root:root | 644         |            |
openconfig-vlan-types        | 2019-01-31 | I     | root:root | 644         |            |
openconfig-yang-types        | 2018-11-21 | I     | root:root | 644         |            |
sysrepo-monitoring           | 2021-01-15 | I     | root:root | 600         |            |
sysrepo-plugind              | 2020-12-10 | I     | root:root | 664         |            |
yang                         | 2017-02-20 | I     | root:root | 664         |            |

Flags meaning: I - Installed/i - Imported; R - Replay support; N - New/X - Removed/U - Updated; F - Feature changes
Features: ! - Means that the feature is effectively disabled because of its false if-feature(s)

[root@localhost openconfig]# `

`
[root@localhost openconfig]# sysrepoctl -i openconfig-interfaces.yang -a -s ./
[root@localhost openconfig]# sysrepoctl -i openconfig-if-ethernet.yang -a -s ./
[ERR]: Invalid context for LYB data parsing, missing module "openconfig-if-ethernet@2020-06-30".
[ERR]: Failed to update data for the new context.
sysrepoctl error: Failed to apply changes (Operation failed)
[root@localhost openconfig]#
`

ps: and because I plan to install in a production environment， so I prefer to use the official release version instead of the devel branch.

**Comment by michalvasko** [comment]
> ps: and because I plan to install in a production environment， so I prefer to use the official release version instead of the devel branch.

That is understandable but any fix that I could provide would always go to the `devel` branch first anyway so I am asking you to reproduce the problem using it. If I learned it was fixed already, I would have completely wasted my time. If it is fixed, you will know just to wait for the next release.
