### ISSUE TITLE
server TCP connection

### ISSUE THREAD

**Issue by BogdanF01** [CESNET/netopeer2#899]
Hi,
should server initiate the TCP connection binding to port 830  (RFC6242) ?  As I can see now it uses a random allocated port.

**Comment by michalvasko** [comment]
Not sure what exactly you mean. It does listen on port `830` by default but generates a random port for each connection, which is simply how it works. You cannot have all the clients connected on a single port, obviously. Or what exactly is the problem?

**Comment by BogdanF01** [comment]
thanks for your answer
