### ISSUE TITLE
Issue with subscribing for several notifications by using subtree filtering

### ISSUE THREAD

**Issue by jabilmplane** [CESNET/netopeer2#902]
Hello.

I am trying to use netopeer2-cli "subscribe" command to subscribe for particular notifications. I am using the "--filter-subtree" option for that. However I faced a few issue during my work. 

I am using the latest versions for all repos( the exact commits see in attached "versions.txt" file )
[versions.txt](https://github.com/CESNET/netopeer2/files/6509373/versions.txt)

So, I've tried the following tests:
1. At first, I’ve checked subscription for notification using subtree filter with one element.
I've created a file with following content:
```
cat filter_start.xml 
<netconf-session-start xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-notifications"/>
```

I've used it in “subscribe --filter-subtree=<file>” and got "ok" reply from the server( see details in the attached  "output1.txt" )
[output1.txt](https://github.com/CESNET/netopeer2/files/6509376/output1.txt)
I've tried to connect the server from another terminal and got a proper “netconf-session-start” notification without any problem:
```
> 
notification (2021-05-19T13:15:28+03:00)
<netconf-session-start xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-notifications">
  <username>pavlo</username>
  <session-id>15</session-id>
  <source-host>127.0.0.1</source-host>
</netconf-session-start>
```
So, no issue there.

2. Then I’ve tried to subscribe for "netconf-session-start" and “netconf-session-end” notifications one by one. From my understanding, it should be possible to do that.
I've got "ok" reply for “netconf-session-start” notification as before but for “netconf-session-end” I've got the following error:
```
nc DEBUG: Session 19: received message:
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="15"><rpc-error><error-type>protocol</error-type><error-tag>operation-failed</error-tag><error-severity>error</error-severity><error-message xml:lang="en">Session already subscribed.</error-message></rpc-error></rpc-reply>

ERROR
                type:     protocol
                tag:      operation-failed
                severity: error
                message:  Session already subscribed.

>
```
The message generated by the client seems right:
```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="15">
  <create-subscription xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
    <filter type="subtree">
      <netconf-session-end xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-notifications"/>
    </filter>
  </create-subscription>
</rpc>
```
So for some reason the server rejects the attempt while it is different notification( see detailed output in "output2.txt" )
[output2.txt](https://github.com/CESNET/netopeer2/files/6509381/output2.txt)

3. In the end, I’ve tried to subscribe for two notification at ones.
I've put both notifications in one file
```
cat filter_both.xml 
<netconf-session-start xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-notifications"/>
<netconf-session-end xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-notifications"/>
```
and provided it to “subscribe --filter-subtree=<file>” command ( see "output3.txt" file ).
[output3.txt](https://github.com/CESNET/netopeer2/files/6509384/output3.txt)
Again, the generated message is seems right:
```
<create-subscription xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
    <filter type="subtree">
      <netconf-session-start xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-notifications"/>
      <netconf-session-end xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-notifications"/>
    </filter>
  </create-subscription>
</rpc>
```
Moreover, I've got "ok" reply from the server.
However, none notification were sent from the server when I connected/disconnected to the server from another terminal.

So I hope you can help me understand whether I am doing something wrong or it is the issue in netopeer2 server/cli code.

Thanks in advance!

**Comment by jabilmplane** [comment]
Hi. I've checked the new version and can confirm that the problem has been resolved. I am going to close the issue.
Thank you for your help and quick response!

**Comment by jabilmplane** [comment]
Hi Michal.

Could you please clarify why it is not allowed to create several subscriptions?
For example we issue create-subscription to subscribe for "netconf-session-start" notification, and then in another create-subscription RPC we subscribe for netconf-session-end.

I did take a look into RFC5277 and it says:
```
   If a malicious or buggy NETCONF client sends a number of <create-
   subscription> requests, then these subscriptions accumulate and may
   use up system resources.  In such a situation, subscriptions can be
   terminated by terminating the suspect underlying NETCONF sessions
   using the <kill-session> operation.
```
From this statement I can make a conclusion that it is allowed to call create-subscription RPC several times.

Thanks for your responses!

**Comment by michalvasko** [comment]
[Here](https://datatracker.ietf.org/doc/html/rfc5277#section-6.5) is the reference.

**Comment by jabilmplane** [comment]
Thanks!
