### ISSUE TITLE
Pipelining versus NETCONF Session

### ISSUE THREAD

**Issue by robbynet** [CESNET/netopeer2#904]
Hello,
We have observed that pipelining has specified in chapter 4.5 of RFC 4741 is supported by Netopeer2, meaning that a given RPC on a given NETCONF Session is pepelined until the previous one ( one the same NETCONF Session ) ended.
But there remains an ambiguity in the RFC in the case where the two parallel RPCs are in different NETCONF Sessions. After a bit of prototyping, it seems that Netopeer does not do pipelining between two NETCONF Sessions, can you confirm this observation?

**Comment by michalvasko** [comment]
Yes, 2 NETCONF sessions are independent and their RPCs should execute in parallel, to whatever extent permitted (mostly limited by *sysrepo*).

**Comment by robbynet** [comment]
Thanks for your support
