### ISSUE TITLE
how to resolve "event" not processed

### ISSUE THREAD

**Issue by xheke** [CESNET/netopeer2#905]
After restart plugin,  I can not reproduce test with below error.
Even restart netopeer2 server,  I still get below error.
How to remove this abnormal "event" gracefully?

Thanks,

```
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  Waiting for subscription of "openconfig-platform" failed, previous event "done" with ID 1 was not processed.
```

**Comment by michalvasko** [comment]
With current versions this should never occur, it is a bug and there is no way of "gracefully" fixing this. The simplest thing to do is stop all *sysrepo* applications, run `make shm_clean`, and restart them. It should work then.

**Comment by xheke** [comment]
Thanks Michal, I got it.
