### ISSUE TITLE
How to call user-rpc for multiple key 

### ISSUE THREAD

**Issue by vshaker** [CESNET/netopeer2#906]
Hi , 
I have a yang action defined in a list called "aggregation" and "ru-instance " is the key of the list 
When i try to pass multiple ru-instance in same xml i'm getting the below error . Please let me know how to pass multiple ru-instance action in the same xml file . 
```
> user-rpc --content /home/airvana/vimala/DateTime/usr/bin/examples-action-mul.xml 
ly ERROR: Invalid order of elements "ru-instance" and "ru-instance". (/o-ran-aggregation-base:aggregated-o-ru/aggregation[ru-instance='2']/ru-instance)
ly ERROR: Invalid position of the key "ru-instance" in a list "aggregation". (/o-ran-aggregation-base:aggregated-o-ru/aggregation[ru-instance='2']/ru-instance)
cli_send_recv: Failed to send the RPC.
```
xml file:
```xml
<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" >
    <aggregation xmlns="urn:o-ran:agg-base:1.0">
        <ru-instance>2</ru-instance>
            <X0005B9_reset xmlns="urn:commscope:o-ran:ru:1.0">
            </X0005B9_reset>
            <ru-instance>4</ru-instance>
                        <X0005B9_reset xmlns="urn:commscope:o-ran:ru:1.0">
            </X0005B9_reset>
              </aggregation>
</aggregated-o-ru>
```

**List example:**
```
augment  "/or-agg-base:aggregated-o-ru/or-agg-base:aggregation" {
        action X0005B9_reset {
            output {
              leaf reset-response {
                type enumeration { enum RP_RESET_OK;}

              }
        }
        }
```
 /o-ran-aggregation-base:aggregated-o-ru/aggregation[ru-instance='2']/commscope-o-ran-ru:X0005B9_reset

**Comment by michalvasko** [comment]
My guess is that you are trying to create 2 instances of a list, your XML is wrong. This is probably the right one.
```xml
<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" >
    <aggregation>
        <ru-instance>2</ru-instance>
        <X0005B9_reset xmlns="urn:commscope:o-ran:ru:1.0">
        </X0005B9_reset>
    </aggregation>
    <aggregation>
        <ru-instance>4</ru-instance>
        <X0005B9_reset xmlns="urn:commscope:o-ran:ru:1.0">
        </X0005B9_reset>
    </aggregation>
</aggregated-o-ru>
```

**Comment by vshaker** [comment]
I'm etting the below error now  

> user-rpc --content /home/airvana/vimala/DateTime/usr/bin/examples-action-mul.xml 
ly ERROR: Unknown element "X0005B9_reset". (/o-ran-aggregation-base:aggregated-o-ru/aggregation[ru-instance='4']/commscope-o-ran-ru:X0005B9_reset)
ly ERROR: Unexpected action node "X0005B9_reset". (/o-ran-aggregation-base:aggregated-o-ru/aggregation[ru-instance='4']/commscope-o-ran-ru:X0005B9_reset)
cli_send_recv: Failed to send the RPC.

**Comment by michalvasko** [comment]
Okay, sorry, I somehow completely missed the fact that you are executing an action. In that case you cannot include several instances of a parent list, it would defeat the purpose of action, which is to tie an operation to specific parent instances.

**Comment by vshaker** [comment]
Thank you @michalvasko . 

Can i execute 2 actions for the same instance ?

Example : X0005B9_reset and X0005B9_reboot are action under "aggregation " list 


<aggregated-o-ru xmlns="urn:o-ran:agg-base:1.0" xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0" >
    <aggregation>
        <ru-instance>2</ru-instance>
        <X0005B9_reset xmlns="urn:commscope:o-ran:ru:1.0">
        </X0005B9_reset>
        <X0005B9_reboot xmlns="urn:commscope:o-ran:ru:1.0">
        </X0005B9_reboot>
    </aggregation>
</aggregated-o-ru>

**Comment by michalvasko** [comment]
No, you cannot. There must always be a single RPC/action in every NETCONF `<rpc>` message.

**Comment by vshaker** [comment]
Thank you @michalvasko
