### ISSUE TITLE
One Subscribe failing causing all other notification failures

### ISSUE THREAD

**Issue by masif-cs** [CESNET/netopeer2#910]
Hi,

In my system we normally subscribe to multiple yang because notification is scattered over multiple yangs. Recently I observed that out of 5 yang subscribe one got failed. So the expectation was the one for which subscribe failed, I will not get those notifications.
But I should get notification from other 4 subscribe which got succeeded.

What I see is netconf server is not able to send any notification to client. Please let me know if this is a known issue or I am doing something wrong.

**Comment by michalvasko** [comment]
> subscribe to multiple yang

First, please explain this in more detail. Are you using *netopeer2-cli* `subscribe` command? It is not possible to subscribe several times so you are using a filter for all the modules or what exactly?

**Comment by masif-cs** [comment]
I have written my code to do the subscribe for multiple yangs using netconf api
rpc = **nc_rpc_subscribe**(stream, inputXML, NULL, NULL, NC_PARAMTYPE_CONST);

**Comment by michalvasko** [comment]
Alright, so the filter you have used here selects notifications from 5 YANG modules? And you say that the RPC fails? In that case no notifications will be sent because the RPC can only succeed or fail, nothing in between.

**Comment by michalvasko** [comment]
Okay but then every RPC after the first one should fail, unless you are using an older version that did not have this check. It is also possible that this older version had a bug that it wrongly stopped session notifications on this error, I seem to remember fixing that.

**Comment by masif-cs** [comment]
It is working perfectly fine. We receive all notifications from all yangs which we subscribed. Infact using netopeer2-cli also we subscribe to multiple xpath like below and it works fine.
subscribe --filter-xpath /commscope-o-ran-ru:ru-notification-info
subscribe --filter-xpath /o-ran-agg-uplane-conf:tx-array-carriers-state-change

This is the libnetconf2 version which we are using:
set(LIBNETCONF2_MAJOR_VERSION 1)
set(LIBNETCONF2_MINOR_VERSION 1)
set(LIBNETCONF2_MICRO_VERSION 31)

**Comment by michalvasko** [comment]
Yes, there is no reason for it not working other than being specified that way. And if you update *netopeer2* (I assume you have a version current at the time the reported *libnetconf2* version was current), it will stop working but the problem you had should be solved. I have nothing more to add.

**Comment by masif-cs** [comment]
One last question:
How we will be able to subscribe to multiple yangs in updated libnetconf2?

**Comment by michalvasko** [comment]
You can use a filter to select notifications from particular modules. By default, you subscribe to all the notifications of all the modules. Note that *netopeer2* v2 implements `ietf-subscribed-notifications` that does support multiple subscriptions on a session.

**Comment by masif-cs** [comment]
Now I am able to subscribe to all instead of specific yangs. But now I am getting too many unnecessary notifications. Is it possible to unsubscribe specific yangs?

**Comment by michalvasko** [comment]
Try to understand something on your own, I am just repeating myself and what is written in RFCs. Just use a filter, like I said.
