### ISSUE TITLE
Install netopeer2 error

### ISSUE THREAD

**Issue by alexjiao2021** [CESNET/netopeer2#911]
Hi,
When trying to install netopeer2 with 'sudo make install' command on Ubuntu 18.04, there is an error shown as below:
![netopeer2_install_fail](https://user-images.githubusercontent.com/84055495/120628966-e1a93280-c497-11eb-9b6d-40b23a28fd7c.PNG)
Could you please help? Thanks.

**Comment by michalvasko** [comment]
Run `# ldconfig`.

**Comment by alexjiao2021** [comment]
Thanks!
