### ISSUE TITLE
SSH connection to netopeer2-server fail

### ISSUE THREAD

**Issue by alexjiao2021** [CESNET/netopeer2#913]
Hi,
When trying to use PuTTY to connect to server, login as root, connection is closed, could you please help?
![Connect_to_netopeer2-server_fail](https://user-images.githubusercontent.com/84055495/120745364-93e00900-c52f-11eb-8d93-8389771777cd.PNG)

**Comment by michalvasko** [comment]
If you knew some in-depth information about SSH, PuTTY error with *netopeer2* error provide the exact reason why this has failed. But in short, *netopeer2* is a NETCONF server and has no other features meaning you can connect only with a NETCONF client and remote shell (which PuTTY requests by default) is not available.

**Comment by alexjiao2021** [comment]
So it means if I want to config server, like callhome settings, I must use NETCONF client to connect and then send 'edit-config' command?

**Comment by michalvasko** [comment]
Well, yes, I suppose. In general it means you can communicate only using [NETCONF](https://datatracker.ietf.org/doc/html/rfc6241).

**Comment by alexjiao2021** [comment]
Hi Michal,
I tried with another NETCONF client which has 'oranuser' as username and a password, how can I set them in ssh_callhome.xml example you provided?
![Auth_fail](https://user-images.githubusercontent.com/84055495/120758892-f98ac000-c544-11eb-90f9-4b10edb99c82.PNG)

**Comment by michalvasko** [comment]
Currently, you cannot connect by SSH using a user that is not present locally on the system.

**Comment by alexjiao2021** [comment]
Use root as user, now SSH can connect, thanks.
