### ISSUE TITLE
Deviating container from included submodule

### ISSUE THREAD

**Issue by peckato1** [CESNET/netopeer2#914]
Hello, I have a trouble deviating an included submodule. Whenever I connect with `netopeer2-cli` to the `netopeer2-server`, I get LY errors. See further for a reproducer.

```
ly ERROR: Schema node not found. (/mod:test/mod:c)
ly ERROR: Invalid value "/mod:test/mod:c" of "deviation".
```

Consider the following two YANG models (this is actually a simplified case for `ietf-interfaces`,`ietf-ip`, `ietf-routing` and `ietf-ipv6-unicast-routing` with `ietf-ipv6-router-advertisements` submodule)

```yang
module mod {
    yang-version 1.1;
	namespace "urn:bla:mod";
	prefix m;

	include mod-submodule {
		revision-date 2018-03-13;
	}

	container test {
		leaf name {
			config false;
			type string;
		}
		leaf type {
			type string;
		}
	}
}
```

```yang
submodule mod-submodule {
  yang-version "1.1";

  belongs-to mod {
    prefix "m";
  }


  revision 2018-03-13 {
  	description "aaa";
  	reference "aaa";
  }

  augment "/m:test" {
	  container c {
		  leaf l {
		  	type string;
		  }
	  }
  }
}
```

Now, let's deviate the included submodule as `not-supported`. (In the real-case we write 
`deviation /if:interfaces/if:interface/ip:ipv6/v6ur:ipv6-router-advertisements { deviate not-supported; }`. )

```yang
module dev {
    yang-version 1.1;
    namespace "urn:bla:d";
    prefix d;

    import mod { prefix m; }

    deviation /m:test/m:c { deviate not-supported; }
}
```

`yanglint` is OK with the YANG models and `sysrepoctl` install them with no errors.

```bash
$ yanglint -f tree mod.yang dev.yang 
module: mod
  +--rw test
     +--ro name?   string
     +--rw type?   string

module: dev
$ sysrepoctl --search $(pwd) -i mod.yang -a
$ sysrepoctl --search $(pwd) -i dev.yang -a
$
```

But If I start a `netopeer2-server` and connect to it, I get the following error:

```bash
$ netopeer2-cli 
> connect --unix --socket /tmp/net.sock
ly ERROR: Schema node not found. (/mod:test/mod:c)
ly ERROR: Invalid value "/mod:test/mod:c" of "deviation".
```

I'm running current `libyang1` branches for `sysrepo`, `libyang`, `libnetconf2` and `Netopeer2`, i.e.,
* sysrepo `e3657e6c5aa49e2de45504450a06e1a21e2706b5`
* libyang `3cfdb044fed5d393a419e939827fb4f0546dc0ee`
* libnetconf2 `c3fd42c6e3fd4cb0cbe6a10ee729b4566cfcb556`
* Netopeer2 `1a4d404a91ab71f526bc42f8e482c4b675460dc8`

**Comment by michalvasko** [comment]
Okay, should be fixed except I referenced it wrong, the problem was in *libyang*.

**Comment by peckato1** [comment]
Thanks, it works with the fix https://github.com/CESNET/libyang/commit/f80a5083f85e4608162eea7bf8c65ab31e7c6b0a.
