### ISSUE TITLE
netconf "remove" CMD can not work in 2.0

### ISSUE THREAD

**Issue by xheke** [CESNET/netopeer2#915]
Hi Michal,

It is very strange the netconf `remove` can not work properly.
Below CMD can work in 1.0, the behavior like below: 
if data already exists, the data was removed as expected,
if not,  nothing happened.

But in 2.0,  the behavior is changed:
if data already exists, nothing happened,
if not,  the data was created abnormally.

```
> config --target running --config=/mnt/sysrepo.example/c.nc.platform.power.remove.xml --rpc-timeout 20
OK
> get-config --source running --filter-xpath /openconfig-platform:*
DATA
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <components xmlns="http://openconfig.net/yang/platform">
    <component>
      <name>abc</name>
      <config>
        <name>abc</name>
      </config>
      <power-supply>
        <config>
          <enabled xmlns="http://openconfig.net/yang/platform/psu">false</enabled>
        </config>
      </power-supply>
    </component>
  </components>
</data>
```

c.nc.platform.power.remove.xml

```xml
<components xmlns="http://openconfig.net/yang/platform"
xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0"
xc:operation="remove">
<component>
<name>abc</name>
<config>
<name>abc</name>
</config>
<power-supply>
<config>
<enabled xmlns="http://openconfig.net/yang/platform/psu">false</enabled>
</config>
</power-supply>
</component>
</components>
```

libyang  commit:  * devel  60dc258b [origin/devel] actions BUGFIX typo
sysrepo commit:  * devel  b823dbd3 [origin/devel] build REFACTOR bugfixes
netopeer2 commit:  * master 6116166 [origin/master] lgtm FEATURE add config file

Thanks and Regards,
He Ke

**Comment by xheke** [comment]
Hi Michal,

I retest this case based on last codes(06/08 `devel branch`) , include libnetconf2, libyang, netopeer2, and sysrepo, it still get the same result.

And then I rollback all codes to 05/18 (based on` master branch`),  the netconf cmd "remove" and "replace" can work as expected.

Please let me know if you need more information.

Thanks and Regards,
He Ke

**Comment by michalvasko** [comment]
Right, it was my bugfix causing the problem, now it should all work.

**Comment by xheke** [comment]
Thanks Michal, I will test it on devel branch later.

**Comment by xheke** [comment]
Hi Michal,

I retest it today, 
Now it work as expected. 

Thanks,
He Ke
