### ISSUE TITLE
Where do I put the module that change device state according to the running configuration?

### ISSUE THREAD

**Issue by sheep94lion** [CESNET/netopeer2#917]
In our project, we implement an ethernet switch which is configured by NETCONF. The netopeer2 server runs on the switch device. I think there should be a program that monitors the changes to the running configuration datastore and takes appropriate actions on the switch devices. What is the proper way of implementation for this program to monitor the configuration changes? I can think of two options:
1. This program is also a NETCONF Client and monitors the configuration changes through subscription. If this is the proper way, are there any examples?
2. This program directly talks to sysrepo which stores the configuration data.
Thanks for your help!

**Comment by michalvasko** [comment]
1. While possible, this is an overly complex way of doing things and would make sense only if the actual switch is on a remote machine, which is unlikely.
2. This is exactly what you want to do.
