### ISSUE TITLE
Question related to netopeer2 hello exchange

### ISSUE THREAD

**Issue by igortern** [CESNET/netopeer2#919]
netopeer2: latest

Hi,

I've a sysrepo-based application that supports only a Running datastore. netopeer2-server provides the external netconf interface to this application. Is it possible to make netopeer2-server NOT to report the 'candidate' datastore capability?
 <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>

Thank you and best regards,
Igor Ternovsky

**Comment by michalvasko** [comment]
No, *netopeer2* currently does not allow customizing its supported capabilities.

**Comment by igortern** [comment]
Thanks
