### ISSUE TITLE
No matching subscribers for RPC action

### ISSUE THREAD

**Issue by alexjiao2021** [CESNET/netopeer2#920]
Hi,
I tried to install ORAN Yang models, then run xml script to test with Netopeer2-server.
After successful subscription, the server reply 'no matching subscribers for RPC/action...'
Netopeer2-server log as below:
![RPC_fail](https://user-images.githubusercontent.com/84055495/121290138-ab950400-c918-11eb-8519-60a6c87117f1.PNG)
Could you please help? Thanks!

**Comment by michalvasko** [comment]
It is basically a *sysrepo* problem of you executing an RPC without a subscriber so what exactly should happen? Where should *sysrepo*/*netopeer2* get the output from? If you are fine with subscribing just so that there is a subscriber, use `sysrepo/examples/rpc_subscribe_example "/o-ran-supervision:supervision-watchdog-reset"`. It will print some messages when the RPC is executed.

**Comment by alexjiao2021** [comment]
Before executing the failed RPC, client has already sent subscription RPC and netopeer2-server responded OK.
Please check below log from client:

2021-06-09 11:54:44 SUCCESS Minimum capability check passed.
2021-06-09 11:54:44 DEBUG NetconfClientSession(sid:1): Sending RPC message-id: 0
2021-06-09 11:54:44 DEBUG Sending message (216): 
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="0">
  <create-subscription xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
        <stream>NETCONF</stream>
    </create-subscription>
</rpc>

2021-06-09 11:54:45 DEBUG Received message:
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="0">
  <ok/>
</rpc-reply>

2021-06-09 11:54:45 DEBUG NetconfClientSession(sid:1): Received rpc-reply message-id: 0
2021-06-09 11:54:45 DEBUG NetconfClientSession(sid:1): Sending RPC message-id: 1
2021-06-09 11:54:45 DEBUG Sending message (313): 
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <supervision-watchdog-reset xmlns="urn:o-ran:supervision:1.0">
        <supervision-notification-interval>60</supervision-notification-interval>
        <guard-timer-overhead>10</guard-timer-overhead>
    </supervision-watchdog-reset>
</rpc>

2021-06-09 11:54:45 DEBUG Received message:
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message lang="en">There are no matching subscribers for RPC/action "/o-ran-supervision:supervision-watchdog-reset".</error-message>
  </rpc-error>
</rpc-reply>

**Comment by michalvasko** [comment]
Okay, what is required here is to strictly differentiate when talking about *sysrepo* and about *netopeer2-server* and NETCONF. What you have done is sent a `<create-subscription>` NETCONF RPC to *netopeer2* that subscribes you to receiving NETCONF notifications. What you have not done and I have suggested is to subscribe to specific RPC handling in *sysrepo*.

As you can see, these 2 perhaps have similar names (you are subscribing to something) but nothing else in common. The former is **NETCONF RPC execution** subscribing for **notifications** and the latter is **sysrepo subscribe API function** subscribing to handling **RPCs**.

**Comment by alexjiao2021** [comment]
Hi Michal,
Thanks for the detailed explanation, another question:
sysrepo/examples/rpc_subscribe_example "/o-ran-supervision:supervision-watchdog-reset" 
above line seems not a command, right? Could you please tell where to execute this and get messages?

**Comment by michalvasko** [comment]
Well, no, it is not a command but I was hoping you could understand what the actual command is. There is a source `sysrepo/examples/rpc_subscribe_example.c` that is compiled into a binary `rpc_subscribe_example` executable. Its path depends on your build directory so I could not write it directly. So just execute that with `"/o-ran-supervision:supervision-watchdog-reset"` argument.

**Comment by alexjiao2021** [comment]
Sorry to bother again, when compiling rpc_subscribe_example.c, there is error below:
![compile_error](https://user-images.githubusercontent.com/84055495/121546479-e775b980-ca3d-11eb-9347-c214fa5ce1b9.PNG)

**Comment by michalvasko** [comment]
Please do not run any other `CMakeLists.txt` than the main one in the repository root. Examples are compiled by default when you run that one.

**Comment by alexjiao2021** [comment]
Thanks. With rpc_subscribe_example running, now RPC is executed with no error.

**Comment by FAR5HID** [comment]
Thanks @michalvasko, the suggestion of rpc_subscribe_example has been helpful for me as well. However, I've faced an rpc error.

My netconf rpc request was this serializedYang:
```
<invoke-notification xmlns="urn:o-ran-sc:params:xml:ns:yang:nts:network:function">
    <notification-format>json</notification-format>
    <notification-object>{"o-ran-supervision:supervision-notification": {}}</notification-object>
</invoke-notification>
```

The sysrepo rpc subscribe (`rpc_subscribe_example /nts-network-function:invoke-notification`) was successful, with response:
```
 ========== RPC "/nts-network-function:invoke-notification" RECEIVED: =======================

/nts-network-function:invoke-notification/notification-format = json
/nts-network-function:invoke-notification/notification-object = {"o-ran-supervision:supervision-notification": {}}
```

But the netconf rpc response was:
```
returnType: RPC_ERROR
message:
"<rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-path>/nts-network-function:invoke-notification</error-path>
    <error-message xml:lang=\"en\">Missing required element \"status\" in \"invoke-notification\".</error-message>
    <error-info>
    </error-info>
</rpc-error>
<rpc-error>
    <error-type>application</error-type>
    <error-tag>operation-failed</error-tag>
    <error-severity>error</error-severity>
    <error-message xml:lang=\"en\">RPC output validation failed.</error-message>
    <error-info>
    </error-info>
</rpc-error>"
```

The expected response message was:
`"<status xmlns=\"urn:o-ran-sc:params:xml:ns:yang:nts:network:function\">SUCCESS</status>\n"`

Does getting the response properly require any additional steps?
I understand that this is a separate query, not sure if I can make this somewhere else. Appreciate any help with this.

**Comment by michalvasko** [comment]
You must write your own proper RPC handler instead of just using `rpc_subscribe_example` (well, you can simply modify this example, too) because your RPC defines some mandatory `output` nodes that need to be returned.

**Comment by FAR5HID** [comment]
An RPC handler like [this](https://github.com/o-ran-sc/sim-o1-interface/blob/master/ntsimulator/ntsim-ng/features/manual_notification/manual_notification.c) I suppose?

**Comment by michalvasko** [comment]
Like I said, just modify the example (or starting with that) is fine. Currently, the output is generated only for [`examples:oper` RPC](https://github.com/sysrepo/sysrepo/blob/master/examples/rpc_subscribe_example.c#L134), you are executing another RPC.
