### ISSUE TITLE
module name is too much in request path in operational DS callback function 

### ISSUE THREAD

**Issue by xheke** [CESNET/netopeer2#922]
Hi Michal,

Seems there are too much module name in the request path, see below information:

`get-data --datastore operational --filter-xpath /openconfig-platform:components/component[name='abc']/power-supply/state/openconfig-platform-psu:enabled`

Get response in callback function:

```
[INF]: Processing "openconfig-platform" "operational" event with ID 4.
[DBG]: plugin: sragent(op): (heke1)   module_name: openconfig-platform
[DBG]: plugin: sragent(op): (heke1)    request_id: 4
[DBG]: plugin: sragent(op): (heke1)         xpath: /openconfig-platform:*
```
`[DBG]: plugin: sragent(op): (heke1) request_xpath: /openconfig-platform:components/openconfig-platform:component[openconfig-platform:name='abc']/openconfig-platform:power-supply/openconfig-platform:state/openconfig-platform-psu:enabled`

I remember the request path is short in 1.0 with only one module name in the first component.
Is that right?

(the code is based on today [ 06/10 devel ])

Thanks and Regards,
He Ke

**Comment by michalvasko** [comment]
Okay, I suppose the superfluous prefixes should not be there. If you update *libyang*, it should be fixed.

**Comment by xheke** [comment]
Yes, I test it with last code on the devel branch, it is ok now.

Thanks Michal.
