### ISSUE TITLE
can not add operational data via callback function

### ISSUE THREAD

**Issue by xheke** [CESNET/netopeer2#923]
Hi Michal,

Since the code is upgraded to 2.0,  lyd_new_path is changed also.

Below code can not work in 2.0

```
static int
dp_get_items_cb(sr_session_ctx_t *session, uint32_t sub_id, const char *module_name, const char *path, const char *request_xpath, uint32_t request_id, struct lyd_node **parent, void *private_data)
{
    rc = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(sess)), "/openconfig-platform:components/component[name='abc']/state/name", "abc", 0, 0);
```

the plugin log shows below information, seems rc is OK, but actually, no data insert to operational DS.

```
> get-data --datastore operational --filter-xpath /openconfig-platform:components/*
DATA
<data xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-nmda"/>
```

```
[INF]: Processing "openconfig-platform" "operational" event with ID 3.
[DBG]: plugin: sragent(op): (heke1)   module_name: openconfig-platform
[DBG]: plugin: sragent(op): (heke1)    request_id: 3
[DBG]: plugin: sragent(op): (heke1)         xpath: /openconfig-platform:*
[DBG]: plugin: sragent(op): (heke1) request_xpath: /openconfig-platform:components/openconfig-platform:*
[DBG]: plugin: sragent(op): (heke1)            rc: 0
[INF]: Successful processing of "operational" event with ID 3.
```

Per 1.0 document is not suitable for 2.0 anymore,  Could you provide some example for 2.0 in module level for `sr_oper_get_items_subscribe`

Thanks and Regards,
He Ke

**Comment by michalvasko** [comment]
Next time, actually look at the prototype and the changes you need to make, not just put `0` to make it compile. The return value changed and you are not modifying `parent` in any way, of course there are no data returned.

**Comment by xheke** [comment]
Thanks Michal, it is perfect, I add all data to operational DS as expected.

```
> get-data --datastore operational --filter-xpath /openconfig-platform:components/*
DATA
<data xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-nmda">
  <components xmlns="http://openconfig.net/yang/platform">
    <component>
      <name>abc</name>
      <state>
        <name>abc</name>
        <id>test</id>
      </state>
      <power-supply>
        <state>
          <enabled xmlns="http://openconfig.net/yang/platform/psu">false</enabled>
          <capacity xmlns="http://openconfig.net/yang/platform/psu">EjRWeA==</capacity>
        </state>
      </power-supply>
    </component>
  </components>
</data>
```


May I ask one more question:

Currently, I use below code to get parent by  `lyd_new_path`, then use this parent to add other data:
`rc = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(sess)), "/openconfig-platform:components/component[name='abc']/state/name", "abc", 0, parent);`
```
snprintf(s, sizeof(s), "/openconfig-platform:components/component[name='abc']/power-supply/state/openconfig-platform-psu:enabled");
rc = lyd_new_path(*parent, NULL, s, "false", 0, 0);
```

```
    snprintf(s, sizeof(s), "/openconfig-platform:components/component[name='abc']/state/id");
    rc = lyd_new_path(*parent, NULL, s, "test", 0, 0);
```

May question is does there have some way to get parent with `session, module_name, xpath(module level)` to get parent instead of `lyd_new_path` ?

Thanks, 
Ke

**Comment by michalvasko** [comment]
I am sorry but I do not understand the question at all, you are creating nodes, why do you want to "get parent"? Or are you asking whether there are any other ways of creating the `parent` data tree?

**Comment by xheke** [comment]
Hi Michal,

This is for first data creation.

 **first:**  ` rc = lyd_new_path(NULL, sr_get_context(sr_session_get_connection(sess)), "/openconfig-platform:components/component[name='abc']/state/name", "abc", 0, parent);`

we get `parent ` above and use it for others data:

**second and others:**  `rc = lyd_new_path(*parent, NULL, s, "false", 0, 0);`

I want use below function to create all data include first data.

`rc = lyd_new_path(*parent, NULL, s, "false", 0, 0);`

That is why I ask to  get `*parent ` in another way.

I don't know if we have some  method to get this *parent directly but not get it from `lyd_new_path` with first data creation in CB?

Thanks,

**Comment by michalvasko** [comment]
If you subscribe to top-level data, you get no `parent` in the callback so you must create it. `lyd_new_path()` can either create a new subtree or connect new nodes to an existing parent, which is distinguished by the first parameter, which is naturally documented.

> I want use below function to create all data include first data.

Like I have tried to explain, the first node creation is simply different. However, you can probably fill the first, second, and last parameter in all the `lyd_new_path()` calls and if using absolute paths, the created data tree should be the same. But I believe that way it would just be much more confusing and you should probably give up such pointless requirements.

**Comment by xheke** [comment]
Thanks Michal, 

Assumption, If there have many data get from outside system,  we want use a loop to add these data one by one,  according to current way, we should handle first data in different way, and others can handled by the loop.

Normally, It is fine.  But if we can handle all data in the loop will be better, I think.

BRs,

**Comment by michalvasko** [comment]
Nothing prevents you from creating the first container `/openconfig-platform:components` separately and then append all list instances in a loop, you do not have to have all the function calls the same.

**Comment by xheke** [comment]
Thanks Michal, I will try it.

**Comment by xheke** [comment]
Thanks Michal， I got it.
