### ISSUE TITLE
Updating knownhosts to avoid warning when connecting over the CLI the first time

### ISSUE THREAD

**Issue by fruv** [CESNET/netopeer2#924]
Hi,

When using the CLI, I'd like to get rid of the warning about the fingerprint. I would like to add a key in the knownhosts but I cannot find the host key on the server. Can anyone tell me how I can retrieve it?

F.

```
get_netconf_dir: Configuration directory "/root/.netopeer2-cli" did not exist, created.
load_config: No saved history.
load_config: No saved configuration.
> connect --login user1
The authenticity of the host 'localhost' cannot be established.
ssh-rsa key fingerprint is 2e:64:93:6d:7a:ce:39:cc:93:70:24:0b:6e:fe:3b:e3:31:46:4d:17.
Are you sure you want to continue connecting (yes/no)? 
```

**Comment by fruv** [comment]
In fact, editing ~/.ssh/config to disable strict host key checking does that very well. Sorry for the noise.

**Comment by michalvasko** [comment]
Right, that would not have been my advice but it makes sense, *libssh* reads the config file and applies most of the parameters.
