### ISSUE TITLE
Warning when no datastore changes applied

### ISSUE THREAD

**Issue by esend7881** [CESNET/netopeer2#927]
### Issue 

When I submit an edit-config but no changes are needed to be applied, I get an <ok/> response back:

```.xml
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="2"><ok/></rpc-reply>
```

And the server log files only show:
```
Jun 10 09:38:52 rmbn netopeer2-server[4452]: Accepted a connection on 0.0.0.0:830.
Jun 10 09:38:52 rmbn netopeer2-server[4452]: Session 1172 (user "root", CID 15) created.
Jun 10 09:38:52 rmbn netopeer2-server[4452]: Received an SSH message "request-service" of subtype "ssh-userauth".
Jun 10 09:38:52 rmbn netopeer2-server[4452]: Received an SSH message "request-auth" of subtype "none".
Jun 10 09:38:52 rmbn netopeer2-server[4452]: Received an SSH message "request-auth" of subtype "publickey".
Jun 10 09:38:52 rmbn netopeer2-server[4452]: Received an SSH message "request-auth" of subtype "publickey".
Jun 10 09:38:52 rmbn netopeer2-server[4452]: User "admin" authenticated.
Jun 10 09:38:52 rmbn netopeer2-server[4452]: Received an SSH message "request-channel-open" of subtype "session".
Jun 10 09:38:52 rmbn netopeer2-server[4452]: Received an SSH message "request-channel" of subtype "subsystem".
Jun 10 09:38:52 rmbn netopeer2-server[4452]: Session 1173 (user "root", CID 15) created.
Jun 10 09:38:52 rmbn netopeer2-server[4452]: There are no subscribers for "ietf-netconf-notifications" notifications.
Jun 10 09:38:52 rmbn netopeer2-server[4452]: Generated new event (netconf-session-start).
Jun 10 09:38:52 rmbn netopeer2-server[4452]: Resolving unresolved data nodes and their constraints...
Jun 10 09:38:52 rmbn netopeer2-server[4452]: All data nodes and constraints resolved.
Jun 10 09:38:52 rmbn netopeer2-server[4452]: Resolving unresolved data nodes and their constraints...
Jun 10 09:38:52 rmbn netopeer2-server[4452]: All data nodes and constraints resolved.
Jun 10 09:38:52 rmbn netopeer2-server[4452]: Published event "rpc" "/ietf-netconf:edit-config" with ID 182 priority 0 for 1 subscribers.
Jun 10 09:38:52 rmbn netopeer2-server[4452]: Processing "/ietf-netconf:edit-config" "rpc" event with ID 182 priority 0 (remaining 1 subscribers).
Jun 10 09:38:52 rmbn netopeer2-server[4452]: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
Jun 10 09:38:52 rmbn netopeer2-server[4452]: No datastore changes to apply.
```

The notable item in the logs is **No datastore changes to apply.**

### Solution ideas/questions:

My question is, would it be possible to do one of the following

1. Subscribe to the event when `no datastore changes needed to apply` in sysrepo's API?
    - Similar to how we can subscribe to `<get>` events `subscribe.oper_get_items_subscribe` or `subscribe.module_change_subscribe`, is there another event to subscribe to for `no datastore changes`?
2. Allow an option to use more than `<ok/>` as the response or use a warning? For example, the definition of `<ok/>` is:

```.yang
   grouping RpcReplyType {
      description "Generic NETCONF 'rpc-reply' content. ";

      choice ok-or-data-error {
        mandatory true;
        config false;

        leaf ok {
          description
            "Sent in 'rpc-reply' messages if no errors or
             warnings occurred during the processing of an 'rpc' request.";
          type empty;
        }

        case data-error {
           uses RpcDataReplyType;
        }
      }
   }
```

The definition of okay says `...no errors or warnings occurred...` but could we set as an input to netopeer2-server an argument that will categorize `no datastore changes` as a warning? 

3. Send both an `<rpc-reply>` with more details before sending the final `<ok/>`? I think it is reasonable to say that if an edit-config is rejected, even for good reason due to no datastore changes, it ought to warrant a warning on some level. 
    - For example, could an option be added like this:

```
$ netopeer2-server --help
netopeer2-server: invalid option -- '-'
Usage: netopeer2-server [-dhV] [-p path] [-U (path)] [-m mode] [-u uid] [-g gid] [-t timeout] [-v level] [-c category]
 -d         debug mode (do not daemonize and print verbose messages to stderr instead of syslog)
 -h         display help
 -V         show program version
 -p path    path to pidfile (default path is "/var/run/netopeer2-server.pid")
 -U[path]   listen on a local UNIX socket (default path is "/var/run/netopeer2-server.sock")
 -m mode    set mode for the listening UNIX socket
 -u uid     set UID/user for the listening UNIX socket
 -g gid     set GID/group for the listening UNIX socket
 -t timeout timeout in seconds of all sysrepo functions (applying edit-config, reading data, ...),
            if 0 (default), the default sysrepo timeouts are used
 -v level   verbose output level:
                0 - errors
                1 - errors and warnings
                2 - errors, warnings, and verbose messages
 -c category[,category]*
            verbose debug level, NOT SUPPORTED in release build type
 --warn-no-change rpc-reply with a warning when an edit-config results in no datastore changes.
```
With a `--warn-no-change` being the new input parameter specifying the wanted warning. 

I see the netopeer2 log message originates here: https://github.com/sysrepo/sysrepo/blob/v1.4.122/src/sysrepo.c#L1952 I wonder if this is where more code could be added to allow for additional warnings?

### Versions installed

- libyang1-1.0.224-1.1.x86_64.rpm
- sysrepo-1.4.122-1.1.x86_64.rpm
- libnetconf2-1.1.43-1.1.x86_64.rpm
- netopeer2-1.1.70-1.1.x86_64.rpm
- libyang-cpp1-1.0.224-1.1.x86_64.rpm
- python3-yang1-1.0.224-1.1.x86_64.rpm
- sysrepo-cpp-1.4.122-1.1.x86_64.rpm
- python3-sysrepo-1.4.122-1.1.x86_64.rpm

**Comment by michalvasko** [comment]
1. The most you can do is to subscribe to `edit-config` RPC and you would be notified whether there are any actual changes or not.
2. Would probably go against the specification of NETCONF.
3. Again, would probably not be okay. And no `edit-config` is being rejected, it is successfully applied, there are just no datastore changes.

**Comment by esend7881** [comment]
> 1. The most you can do is to subscribe to `edit-config` RPC and you would be notified whether there are any actual changes or not.
> 2. Would probably go against the specification of NETCONF.
> 3. Again, would probably not be okay. And no `edit-config` is being rejected, it is successfully applied, there are just no datastore changes.

Understood -- we'll adapt to this. Appreciate the explanation.
