### ISSUE TITLE
How to run a <get> across multiple, specific containers 

### ISSUE THREAD

**Issue by esend7881** [CESNET/netopeer2#928]
Currently, in `netopeer2-cli` when need to collect the data within my containers, I run:

```
> get --filter-xpath=/mymodel:*
```
Which successfully collects data from all my containers. 

What I am trying to research how to do within is collect from certain specified containers. I.e.,

```
> get --filter-xpath=/mymodel:container-A,mymodel:container-B,..
ERROR
        type:     application
        tag:      operation-failed
        severity: error
        message:  libyang error
```

The rpc it creates is:
```.xml
nc DEBUG: Session 73: sending message:
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="26"><get xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><filter type="xpath" xmlns:mymodel="urn:com:mymodel" select="/mymodel-state,/mymodel-flow-state"/></get></rpc>
```

So instead of using a wildcard to collect all the data from each container and instead of only collecting from one container at a time, is it possible to collect from specific containers?

I am using the `--filter-xpath` -- not sure if other methods work better. Hoping this is an easy question for an netconf pro (my google searches aren't yielding much good info on this). 

- libyang1-1.0.224-1.1.x86_64.rpm
- sysrepo-1.4.122-1.1.x86_64.rpm
- libnetconf2-1.1.43-1.1.x86_64.rpm
- netopeer2-1.1.70-1.1.x86_64.rpm
- libyang-cpp1-1.0.224-1.1.x86_64.rpm
- python3-yang1-1.0.224-1.1.x86_64.rpm
- sysrepo-cpp-1.4.122-1.1.x86_64.rpm
- python3-sysrepo-1.4.122-1.1.x86_64.rpm

**Comment by michalvasko** [comment]
Not sure it will work in v1, but definitely should in v2:
```
> get --filter-xpath="/mymodel:container-A|/mymodel:container-B"
```
Look more into XPath if you need some advanced expressions.

**Comment by esend7881** [comment]
Thank you!
