### ISSUE TITLE
Out of memory error comes 

### ISSUE THREAD

**Issue by Abrahamma97** [CESNET/netopeer2#932]
Hi  @michalvasko  can you help out here:
I had given the following configuration and got the following error.
```
> user-rpc


<chg-password xmlns="urn:o-ran:user-mgmt:1.0">
<currentPassword>vaibhav123</currentPassword>
<newPassword>vaibhav1</newPassword>
<newPasswordConfirm>vaibhav1</newPasswordConfirm>
</chg-password>


ERROR
	type:     application
	tag:      operation-failed
	severity: error
	message:  Out of memory
```
-------------------------------------------------------------------------------------------------------------------------
			RU-System Logs
-------------------------------------------------------------------------------------------------------------------------
```
Oct 29 11:47:50 abey daemon.info netopeer2-server[2019]: Resolving unresolved data nodes and their constraints...
Oct 29 11:47:50 abey daemon.info netopeer2-server[2019]: All data nodes and constraints resolved.
Oct 29 11:47:50 abey daemon.info netopeer2-server[2019]: Resolving unresolved data nodes and their constraints...
Oct 29 11:47:50 abey daemon.info netopeer2-server[2019]: All data nodes and constraints resolved.
Oct 29 11:47:50 abey daemon.info netopeer2-server[2019]: Published event "rpc" "/o-ran-usermgmt:chg-password" with ID 2 priority 0 for 1 subs.
Oct 29 11:47:50 abey daemon.info netopeer2-server[2019]: Processing "ietf-netconf-monitoring" "operational" event with ID 2.
Oct 29 11:47:50 abey daemon.info netopeer2-server[2019]: Successful processing of "operational" event with ID 2.
Oct 29 11:47:50 abey user.err USERMGMT[2043]: error in get item list !!
Oct 29 11:47:50 abey daemon.err netopeer2-server[2019]: Out of memory
Oct 29 11:47:50 abey daemon.warn netopeer2-server[2019]: Event "rpc" with ID 2 priority 0 failed (Out of memory).
Oct 29 11:47:50 abey daemon.err netopeer2-server[2019]: Failed to send an RPC (User callback failed).
Oct 29 11:47:50 abey daemon.info netopeer2-server[2019]: Session 1: thread 2 event new RPC.
Oct 29 11:47:50 abey daemon.info netopeer2-server[2019]: Session 1: thread 2 event reply error.`
```
Please note that this is in root user. Can you tell me how out of memory error is coming

**Comment by michalvasko** [comment]
I seem to remember fixing something like this some time ago, what *netopeer2*/*sysrepo* version are you using?

**Comment by Abrahamma97** [comment]
Hi @michalvasko , I am using Netopeer_server v1.1.70 and Sysrepo v1.4.122. Can you suggest a stable release

**Comment by michalvasko** [comment]
You can try using the latest v1 release 1.4.140.

**Comment by Abrahamma97** [comment]
Ok thanks

**Comment by Abrahamma97** [comment]
Hi I have used  v1 release v1 1.4.140 in server still same issue had come.

**Comment by michalvasko** [comment]
Please provide the code snippet generating the following message
```
Oct 29 11:47:50 abey user.err USERMGMT[2043]: error in get item list !!
```

**Comment by vaibhav1713109** [comment]
Hi miclalvasko, i got the same error out of memory did you know how to resolve that, i install the latest version of libyang, libnetconf, sysrepo and netopeer2 but this error is still come.

**Comment by michalvasko** [comment]
What exactly "latest version" means, could you write the exact versions? Also, please provide some details, at least the output of `netopeer2` when run with `-v2` and the steps leading to the problem.

**Comment by Abrahamma97** [comment]
Hi @michalvasko , 
please see the code snippet below
 
`char *findUser(sr_session_ctx_t *session, sr_conn_ctx_t *connection, char *username)
{
sr_session_ctx_t *oper_session;
rc = sr_session_start(connection, SR_DS_OPERATIONAL, &oper_session);
    if (rc != SR_ERR_OK) {
        PRINT(ERR, "USERMGMT", "error in start session !!%s", "\n");
        return NULL;`

**Comment by Abrahamma97** [comment]
Hi @michalvasko ,
sorry I forgot to add rest of snippet.
`rc = sr_get_item(oper_session, username_xpath, 0, &value);
    if (rc != SR_ERR_OK) {
        PRINT(ERR, "USERMGMT", "error in get item list !!%s", "\n");
        ret = rc;
        goto cleanup;
    }`

**Comment by michalvasko** [comment]
What I do not understand is that why no error is printed by `sr_get_item` if `SR_ERR_NO_MEMORY` is returned? In any case, you are using an obsolete *sysrepo* version and it would be a waste of time for me to try to debug this, especially since the whole problem is so odd.
