### ISSUE TITLE
Netconf session establishment takes time

### ISSUE THREAD

**Issue by masif-cs** [CESNET/netopeer2#933]
Hi,

I am using netopeer2-cli and netopeer2-server to establish call-home with TLS authentication. I see that when I execute connect cli command, it takes around 5-8 sec to return and establish call-home. Is there any way to optimize it? I tried capturing TCP dump to see why it takes so much time, I see that after CLIENT and Server HELLO and certificate exchange, lot of application data getting transferred which is causing delay I believe. But i was not able to decrypt the packet to know what exactly was getting exchanged.

Could you please help me to possibly optimize it?

**Comment by masif-cs** [comment]
Hi,

From code I see that after CLIENT HELLO, SERVER HELLO and certificate exchange, this function nc_ctx_check_and_fill is getting called for populating the session context which is causing delay I believe.

Any help in this regard to optimize it?

**Comment by masif-cs** [comment]
Hi,

I am trying to understand where the issue is. So I tried running netopeer2-server and netopeer2-cli on same machine, it gets connect in TLS mode in split seconds. But when I try on two different machine with IPV6 connectivity. I see a delay.

**Comment by michalvasko** [comment]
You may have waited till I get to your issue but I see you are struggling so I will answer quickly. The delay is most likely caused by loading all the YANG modules, which are most often requested from the server and sent using `<get-schema>`. That, obviously, takes some time. However, if the modules are available locally, they are loaded directly and do not have to be requested form the server.

**Comment by masif-cs** [comment]
Hi,

What do mean by having yang modules locally? And how to do that?
Normally on client side we dont install yangs n all right?

**Comment by masif-cs** [comment]
Hi,

I initialized the nc_client with nc_client_set_schema_searchpath and provided the yang folder path where all yangs are placed. I see a reduction in call-home establishment time. Now it is taking around 1-1.5 sec. But I am not able to find any code inside this  _nc_accept_callhome_ hierarchy where it is getting used.

Could you please tell me how it is helping in reducing the call-home time. Or point the function which is loading the yang schema into the context from search path I have set?

**Comment by michalvasko** [comment]
I am not sure you can reduce the connection time further. You can enable displaying received/sent messages on both server (`-c MSG`) and client (`verb debug`) to see what RPCs are exchanged until a session is established.

**Comment by masif-cs** [comment]
Didnt get it. Reduce connection time further from 4 sec or 1-1.5 sec?

Is the changes of setting the search path correct? because i see reduction in time taken to establish call-home from 4s to ~1.5s

**Comment by michalvasko** [comment]
> reduce the connection time further

This means more than you have already, what you did obviously helped and it is what I suggested.
