### ISSUE TITLE
How to config SSH server with e.g., "MaxAuthTries", "LoginGraceTime"

### ISSUE THREAD

**Issue by Roger886** [CESNET/netopeer2#935]
Does it able to use YANG model to enable a common SSHD config for the libssh ssh server, so that the SSHD parameter like "MaxAuthTries", "LoginGraceTime" can apply?

from the bellow netconf server model seems such kind of configuration not included, can we use customized grouping/container /leaf to achieve?
https://datatracker.ietf.org/doc/html/draft-ietf-netconf-server-model#section-4.4.1

**Comment by michalvasko** [comment]
Well, you could write your own module but the server will not magically understand what these parameters are meant to do so you would actually have to implement that yourself. But I am not sure that *libssh* does not read the sshd config file and apply the options it recognizes so you may simple be able to adjust those. It does work like this for the client-side and the ssh_config file.

**Comment by Roger886** [comment]
> Well, you could write your own module but the server will not magically understand what these parameters are meant to do so you would actually have to implement that yourself. But I am not sure that _libssh_ does not read the sshd config file and apply the options it recognizes so you may simple be able to adjust those. It does work like this for the client-side and the ssh_config file.

So you means libssh can re-use the sshd configuration?
How about the netconf call home related paramter? These paramter would over-write the sshd config?
             +--rw connection-type
             |  +--rw (connection-type)?
             |     +--:(persistent-connection)
             |     |  +--rw persistent!
             |     |     +--rw idle-timeout?   uint32
             |     |     +--rw keep-alives
             |     |        +--rw max-wait?       uint16
             |     |        +--rw max-attempts?   uint8
             |     +--:(periodic-connection)
             |        +--rw periodic!
             |           +--rw idle-timeout?        uint16
             |           +--rw reconnect_timeout?   uint16
             +--rw reconnect-strategy
                +--rw start-with?     enumeration
                +--rw max-attempts?   uint8

Meanwhile, when system have both libssh and OpenSSH, this would means only one sshd config apply right? For thoese paramater that not defined by netconf server model.

**Comment by michalvasko** [comment]
> So you means libssh can re-use the sshd configuration?

I am just saying it is possible. If not, then like I said, you would have to implement this yourself.

> These paramter would over-write the sshd config?

I think so, it all depends on *libssh* and when it applies what parameters.

> when system have both libssh and OpenSSH, this would means only one sshd config apply right?

Yes, if the config file is reused.
