### ISSUE TITLE
netopeer2 uses expired ietf yang models

### ISSUE THREAD

**Issue by igortern** [CESNET/netopeer2#937]
Hi,

A number of ietf YANG models included in the netopeer2-devel package are expired and newer versions are not backward compatible.
[https://datatracker.ietf.org/doc/html/draft-ietf-netconf-crypto-types-10](url)
[https://datatracker.ietf.org/doc/html/draft-ietf-netconf-netconf-client-server-14](url)
both drafts expire on January 3, 2020, the newer drafts are not backward compatible. 

If you are interested in updating the models, attached is the relevant netopeer2-devel patch

Regards,
Igor

[netopeer2-devel-patch.txt](https://github.com/CESNET/netopeer2/files/6691114/netopeer2-devel-patch.txt)

**Comment by michalvasko** [comment]
Well, I do not really see the point until the modules are finally published and we can switch to an RFC version. But have you tested these changes properly? If so, we may use it when migrating to the final versions later.

**Comment by igortern** [comment]
Yeah, unfortunately IETF publishing cycle is very long. The changes in the patch have been tested.

**Comment by igortern** [comment]
noticed that missed a line when merging changes to devel. updated version of the patch
[netopeer2-devel-patch.txt](https://github.com/CESNET/netopeer2/files/6697933/netopeer2-devel-patch.txt)

**Comment by gotthardp** [comment]
Also the `ietf-keystore` is outdated, which is causing us some troubles. Just reporting-- I understand that you want to switch once the RFC is ready.

**Comment by michalvasko** [comment]
We are already working on *libnetconf2* with full support of the current drafts (should be almost final) but it will take some time until it is finished.

**Comment by michalvasko** [comment]
You mean in the next *netopeer2* release? I am really hoping we can finally manage it in the next days so the YANG modules will not be changed. Like I said, it will take some time (meaning months, half a year at least) until *libnetconf2* supports them.

**Comment by robbynet** [comment]
No, I am not looking at netopeer2 release, just want to know what is the targeted revision of the new module ietf-crypto-types ?

**Comment by michalvasko** [comment]
The [latest](https://datatracker.ietf.org/doc/html/draft-ietf-netconf-crypto-types) of course and in all likelihood until the functionality is ready the RFC will be published and we will release it right with the published revision.
