### ISSUE TITLE
Does netopeer2 not trigger Sysrepo operational callbacks on `get`?

### ISSUE THREAD

**Issue by Varrrro** [CESNET/netopeer2#938]
Hi, I am having some trouble getting a Sysrepo plugin to work with Netopeer2. I am posting this here because the Sysrepo part seems to work fine, it just doesn't work with Netopeer2.

So, I have a normal operational subscription on a certain subtree of the `ietf-ptp` model. Using `sysrepocfg -X -m ietf-ptp -d operational` triggers the callback correctly and everything is fine. Then, I set up the Netopeer2 server, perform  `get --filter-xpath "/ietf-ptp:ptp"` with `netopeer2-cli` and the callback doesn't trigger, so no operational data is returned (using a more precise filter doesn't work either). Running an `edit-config` on the `running` datastore triggers the callback for my change subscription so I guess the plugin is working OK.

**Comment by michalvasko** [comment]
That is definitely strange, what exactly is the subtree you are subscribing for? Do you have any `running` data for this module?

**Comment by Varrrro** [comment]
Hey, thanks for the quick answer.

So, my operational subscription is done like this:

```c
rc = sr_oper_get_items_subscribe(
        session, "ietf-ptp", "/ietf-ptp:ptp/instance-list/current-ds",
        ptp_current_ds_oper_cb, NULL, SR_SUBSCR_CTX_REUSE, &subscription);
```

And yes, I have this data on the `running` datastore:

```xml
<ptp xmlns="urn:ietf:params:xml:ns:yang:ietf-ptp">
  <instance-list>
    <instance-number>0</instance-number>
  </instance-list>
</ptp>
```

The operational callback is supposed to provide the data from the `current-ds` container for the instance 0 shown.

**Comment by michalvasko** [comment]
Forgot to ask, what *sysrepo*/*netopeer2* versions are you using?

**Comment by Varrrro** [comment]
I am using the latest version available on `master` on both repos. I have just read in the README of this repo that I should use `devel` if a bug is found, so I will try this this afternoon if I have time. Should I also try `devel` version of Sysrepo?

**Comment by michalvasko** [comment]
Never use a project from one branch and any of its dependencies from another, so yes, please try it on `devel` for all *libyang*, *sysrepo*, *libnetconf2*, and *netopeer2*. If you still have the problem, I will try to reproduce it locally.

**Comment by Varrrro** [comment]
Hey, so I just installed `devel` versions of all components and tried again with no success. Same thing happens. [This is the plugin's repo](https://github.com/rabbits-ugr/sr-plugin-ptp). Let me know if you try to reproduce it and need any help getting it to run.

**Comment by michalvasko** [comment]
Before I get to reproducing it, have you tried it when connecting to *netopeer2* as `root`? So that you bypass NACM because that can easily be the problem, if you do not have access to the running data, there is no list instance and so calling this oper data callback would be redundant and is skipped.

**Comment by Varrrro** [comment]
Yes, I have connected to the netopeer2 server using netopeer2-cli and `connect --login root`. It doesn´t trigger the callback either.

**Comment by michalvasko** [comment]
Right, I had to try it myself to understand. It all comes to the [NMDA](https://www.rfc-editor.org/rfc/rfc8342.html#page-10) spec, second bullet. In short, the data your operational callback is providing are **not** part of the data returned by `<get>` because they are `config true` operational data. If you want to get it, use `<get-data>` instead.

**Comment by Varrrro** [comment]
Huh, you are right. I missed that, my bad. It is working correctly with `get-data`. Thanks for your help @michalvasko, I am closing the issue now.
