### ISSUE TITLE
C++ support

### ISSUE THREAD

**Issue by NNNKKK03** [CESNET/netopeer2#939]
Hi, 

I am just wondering what is your intension for C++ support? 
We are implementing some C++ project that would like to interact with netopeer2. 
Thanks

**Comment by michalvasko** [comment]
Since *netopeer2* is just a binary, I have no idea what you mean by C++ support and how are you "interacting" with *netopeer2*. Maybe you mean *sysrepo*?

**Comment by NNNKKK03** [comment]
Sorry, I meant sysrepo. I saw the posts about the c++ bindings. Thanks
