### ISSUE TITLE
Problem in retrieving default values

### ISSUE THREAD

**Issue by fabioantonini** [CESNET/Netopeer2#94]
Hi

I tried to retrieve the default values from my NETCONFc client with the option 'report-all'. They weren't shown

this is the RPC

```
<?xml version='1.0' encoding='UTF-8'?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="3">
  <get-config>
    <source>
      <running/>
    </source>
    <filter type="subtree">
      <cli:config xmlns:cli="http://www.tiesse.com/ns/tiesse-cli/1.0"/>
    </filter>
    <with-defaults xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults">report-all</with-defaults>
  </get-config>
</rpc>

```
The default values are instead visible when I try to retrieve the configuration directly from SYSREPO from my application. So I guess that some kind of problem could be in the Netopeer2 server.
The problem has been confirmed by Rastislav.
Have you any feedback or hint?
thanks a lot for your help
with regards

fabio

**Comment by michalvasko** [comment]
Hi,
please verify, it should work now.

Regards,
Michal

**Comment by fabioantonini** [comment]
It works fine now.

Thanks a lot Michal

kind regards

fabio
