### ISSUE TITLE
Is there any mechanism to notify client that its session is going to be closed?

### ISSUE THREAD

**Issue by jabilmplane** [CESNET/netopeer2#940]
Hi.

I'm trying to find a way how to properly terminate netconf sessions from the server side. I'm going to usee kill-session RPC,
But even session is killed, client does not recieve any information about it.

I use 2 clients to test. Both clients create netconf sessions with sid 1 and 2 respectivelly.

**Both clients are connected. Perform some get to ensure:**
client1:
```
> connect --login engineer
Interactive SSH Authentication
Type your password:
Password: 
> status
Current NETCONF session:
  ID          : 1
  Host        : 127.0.0.1
  Port        : 830
  Transport   : SSH
  Capabilities:
    ...
> get --filter-xpat /ietf-netconf-acm:nacm/enable-nacm
DATA
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
    <enable-nacm>true</enable-nacm>
  </nacm>
</data>
```
client2:
```
> connect --login engineer
Interactive SSH Authentication
Type your password:
Password: 
> status
Current NETCONF session:
  ID          : 2
  Host        : 127.0.0.1
  Port        : 830
  Transport   : SSH
  Capabilities:
      ...
> get --filter-xpat /ietf-netconf-acm:nacm/enable-nacm
DATA
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <nacm xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-acm">
    <enable-nacm>true</enable-nacm>
  </nacm>
</data>
```

**Then, client2 does kill-session --sid to kill session 1:**
```
> kill-session --sid 1
OK
> 
```
**As a result, client1 does not know that its session is closed. There is no any output in the console and "status" command says that everything is fine, But when it does get, error is shown:**
```
> status
Current NETCONF session:
  ID          : 1
  Host        : 127.0.0.1
  Port        : 830
  Transport   : SSH
  Capabilities:
	...
> get --filter-xpat /ietf-netconf-acm:nacm/enable-nacm
nc ERROR: Communication socket unexpectedly closed.
cli_send_recv: Failed to send the RPC.
> 
```

The same behaviour occurs if I terminate the server in linux.

**I have not found any description what should be done by netconf server when it initiates closing the session. Could you please clarify whether client should be somehow informed that session is terminated.**

Thanks in advance.

**Comment by michalvasko** [comment]
NETCONF does not define (allow) server terminating the session so *netopeer2* does not really support it. There is just TCP/IP keep-alive meaning on that layer it should be learned that the other end was disconnected. That results in an immediate error when further communication is attempted.

**Comment by jabilmplane** [comment]
That is my understanding too. Thanks!

But how that happened that netconf RFC defines <kill-session> RPC (which means that server will terminate the session), but don't allow server to close it?

**Comment by michalvasko** [comment]
The RPC `kill-session` is probably meant as a sort of last-resort solution to get rid of stuck/malicious sessions remotely, which do not really need to be notified.
