### ISSUE TITLE
netopeer2-cli cann't get operationcal data

### ISSUE THREAD

**Issue by zewei0920** [CESNET/netopeer2#941]
hi, michalvasko, could you help to check my problem:

### 2. apps: my app suscribe the yang module refrence the example ( oper_pull_push_example.c ), the code like this:
**get connection and sesson**
```
   ...
    /* connect to sysrepo */
    rc = sr_connect(0, &connection);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }
    rc = sr_session_start(connection, SR_DS_OPERATIONAL, &session);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }
    ...
```

**subcribe function:**
```
/* subscribe for providing pull operational data */
    rc = sr_oper_get_items_subscribe(session, mod_name, path, get_items_callback_fans, NULL, 0, &subscription);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }
    ....
    rc = sr_set_item_str(session, "/hengna-fans:fans/fan[slotindex='10']/state/fault-alarm", "false", NULL, 0);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }
    rc = sr_set_item_str(session, "/hengna-fans:fans/fan[slotindex='10']/config/address", "101", NULL, 0);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }
```

 **callback function:**
```
        lyd_new_path(NULL, sr_get_context(sr_session_get_connection(session)), "/hengna-fans:fans/fan[slotindex='10']/state/status", "true", 0, parent);
        lyd_new_path(*parent, NULL, "/hengna-fans:fans/fan[slotindex='10']/state/power-alarm", "false", 0, NULL);
        lyd_new_path(*parent, NULL, "/hengna-fans:fans/fan[slotindex='10']/state/fault-alarm", "true", 0, NULL);
        lyd_new_path(*parent, NULL, "/hengna-fans:fans/fan[slotindex='10']/config/address", "110", 0, NULL);
        lyd_new_path(*parent, NULL, "/hengna-fans:fans/fan[slotindex='10']/config/type", "111", 0, NULL);
        lyd_new_path(*parent, NULL, "/hengna-fans:fans/fan[slotindex='10']/config/function", "112", 0, NULL);
```

### 3. my yang module:
    `  grouping fans-top {
    description "Top-level grouping for device fans";
    container fans {
      description "Top-level container for device fans";
      list fan {
        key "slotindex";
        description "List of fans, keyed by a unique id: slotindex";
        leaf slotindex {
          type hn-types:slotindex;
          description "unique id: slot index";
        }
        container config {
          description "Configuration data for each alarm";
          uses fan-config;
        }
        container state {
          config false;
          description "Operational state data for a device alarm";
          uses fan-state;
        }
      }
    }
    uses fans-top;`

I also test the examples.yang , also get no data

### 4. my app can get the data normally
```
---- PULL OPERATIONAL DATA "/hengna-fans:fans/fan[slotindex='10']" REQUESTED ----
callback get_items_callback_fans
<fans xmlns="urn:hengna:fans">
  <fan>
    <slotindex>10</slotindex>
    <config>
      <address>110</address>
      <type>111</type>
      <function>112</function>
    </config>
    <state>
      <status>true</status>
      <power-alarm>false</power-alarm>
      <fault-alarm>true</fault-alarm>
    </state>
  </fan>
</fans>
PUSH OPERATIONAL DATA "/hengna-fans:fans/fan[slotindex='10']" REQUESTED ----
callback get_items_callback_fans
<fans xmlns="urn:hengna:fans">
  <fan>
    <slotindex>10</slotindex>
    <config>
      <address>110</address>
      <type>111</type>
      <function>112</function>
    </config>
    <state>
      <status>true</status>
      <power-alarm>false</power-alarm>
      <fault-alarm>true</fault-alarm>
    </state>
  </fan>
</fans>
```

### 5. question: when I execute cmds as below via netopeer2-cli  and I cann't get any data, and the callback functions are not called.
```
     get-data --datastore operational --filter-xpath /hengna-fans:fans/*
     get-data --datastore running --filter-xpath /hengna-fans:fans/*
     get-data --datastore running --filter-xpath /examples:stats
     get --filter-xpath /hengna-fans:fans/*
     get-config --source running --filter-xpath /hengna-fans:fans/*
```
always got that as below:
```
DATA
{
  "ietf-netconf-nmda:data": {}
}
```

**My goal** is to register the subscription callback function (sr_oper_get_items_subscribe) through my APP and then retrieve the device's configuration data and status data from Netopeer2-CLI. 
Is there anything wrong with my code or the YANG model?  Or maybe I misunderstood something about NetConf ？

Any help or advice would be greatly appreciated， thanks a lot in advance. and sorry for my so long description.

**Comment by michalvasko** [comment]
Please try `sysrepocfg -d operational -x "/hengna-fans:fans/*" -X`.

**Comment by zewei0920** [comment]
hi michalvasko. Thanks a lot for your quickly reply. I executed the cmd you adviced, but get nothing. 

And now I resloved this issue, Probably not the right way. the modification are as below:
1.  get connection and session again before call sr_oper_get_items_subscribe every time. I used global variable and config them 
 when my app start。
`    /* connect to sysrepo */
    rc = sr_connect(0, &connection);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }
    rc = sr_session_start(connection, SR_DS_OPERATIONAL, &session);
    if (rc != SR_ERR_OK) {
        goto cleanup;
    }` 

2. Comment out the function, I mean don't call sr_unsubscribe(subscription) and  sr_disconnect(connection);

3. **Question**:  
with the increasing of calling xx_subscribe in code, there will be more and more connections and sessions, is it reseanable ? 
Can I just keep one connection and seesion during the running time ?  or is there any other more  natural and reasonable way to implement ?

Thanks a lot in advance.

**Comment by michalvasko** [comment]
Oh, I see you have missed this feature, described [here](https://netopeer.liberouter.org/doc/sysrepo/master/html/index.html#oper_data), 3rd paragraph. Meaning as long as the connection that set the data is running, the data are available and are automatically deleted only after the connection terminates.

**Comment by zewei0920** [comment]
OK, got it, I see. thanks so much.
And may I ask another question.  I need to know the index of list instance in the callback function，and then I can generate state data about that embed sub-card with that index.  could you give some advice how to implement ？Thanks in advance.

**Comment by michalvasko** [comment]
It depends to what path you are subscribing to, exactly. But you get all the parents of the data you are supposed to provide, in case there is a list, it always has its key.
