### ISSUE TITLE
netopeer2-server started but not listening on port 830 and unlike netopeer, netopeer2 doesnt have datastore.xml file

### ISSUE THREAD

**Issue by dineshR478** [CESNET/netopeer2#942]
[INF]: SR: No scheduled changes.
[INF]: SR: Connection 28 created.
[INF]: SR: Session 141 (user "root", CID 28) created.
[INF]: SR: Triggering "ietf-subscribed-notifications" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[ERR]: LN: Could not bind "0.0.0.0" port 830 (Permission denied).
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-keystore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-truststore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.

And how to make the netopeer2-server to listen on port 830.

**Comment by michalvasko** [comment]
As for the question why the server is not listening on port 830, I will ignore it, just like you ignored the errors the server printed. And for the other question, *netopeer2* uses *sysrepo* as its datastore so yes, there is no longer one global XML file as the datastore.

**Comment by dineshR478** [comment]
Hi @michalvasko 

I found that my platform doesn't support listening on port below 1024.That could be the limitation and so i customized to listen on another port and which works fine. So, Thanks for that answer.

So, for datastore in netopeer2,we need to add the xml files if we wanted to add startup configurations.Am i right?

And is there any way to mention the log file to log the netopeer2/sysrepo/libyang logs instead of stdout?
I see there is no option currently provided to add the log file.

Also, can you provide example command to give netconf request to netopeer2-server from outside the box.

Thanks,
Dinesh R.

**Comment by michalvasko** [comment]
Regarding the datastore, like I said, it is *sysrepo* now that manages it, which does not support plain-text XML files anymore. But you can still work with them using `sysrepocfg`. Just use `-I` (import) or `-X` (export) to write/read the datastore in XML format.

As for the log file, no, there is no direct support for logging into a file. But you can always run it as `netopeer2-server -d -v2 > netopeer2.log`, for example.

Finally, all the standardized RPCs that can be sent to *netopeer2-server* are implemented as commands in *netopeer2-cli*, so just use those. Run the CLI, connect to the server and run `get`, for example.

**Comment by dineshR478** [comment]
Thanks @michalvasko for your inputs. Regarding the sending RPC request to the server, are you aware of any application in windows which can send the request to the server. Also i tried using ssh from outside of the box to connect to the netopeer-server.
But it is hanging.

Server is running
`[INF]: LN: Listening on 67.174.80.240:10830 for SSH connections.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-server" "done" event on enabled data.
[INF]: SR: Triggering "ietf-keystore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-truststore" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
[INF]: SR: Triggering "ietf-netconf-acm" "done" event on enabled data.
`
Trying from the client:
` ssh root@67.174.80.240 -p 10830
ssh: connect to host 67.174.80.240 port 10830: Connection refused`

**Comment by michalvasko** [comment]
As for your first question, I do not know about almost any other NETCONF clients because I always use our own. But if you really cannot find any Windows NETCONF client, I am sure there are many that are multi-platform. Ours is not mostly because it is written in C.

But you should be able to connect using `ssh` (you will just not get much further than that) and if you cannot, it means something is blocking it, perhaps firewall.

**Comment by dineshR478** [comment]
Thanks @michalvasko .You are right!!.. There was a rule blocking my packets.After removing , it works fine.
