### ISSUE TITLE
How to add new yang

### ISSUE THREAD

**Issue by dineshR478** [CESNET/netopeer2#943]
Hi @michalvasko 

I am new to netopeer2 and sysrepo. I never used it. I know much about confD & it's CDB database. 
So basically my questions are,

1. How to add a new yang file for the compilation.
2. Where to add a callback function(i.e which gets hit when I send new commit from the client) for configuring (RPC edit-config operation) the leaf element in my new yang file.
3. should we run another daemon for listening for the changes in my new yang file?

**Comment by michalvasko** [comment]
The first thing to know is that you will mostly work with *sysrepo*, *netopeer2* is just a remote NETCONF server for it, essentially.

1. You call [`sr_install_module()`](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__schema__api.html#gaf706c683d0d3c93625a9ba4736dce420) API function for that but you will most likely use `sysrepoctl` utility that just wraps the function in a tool.
2. You register the callback by [`sr_module_change_subscribe()`](https://netopeer.liberouter.org/doc/sysrepo/master/html/group__change__subs__api.html#ga9fc19731882299fe1864ccc20b9bd842), in general. More on this topic is at the very beginning of the [documentation](https://netopeer.liberouter.org/doc/sysrepo/master/html/index.html).
3. Covered in 2.
