### ISSUE TITLE
Segfault when removing leaf

### ISSUE THREAD

**Issue by awesomenode** [CESNET/netopeer2#944]
Hi!

The following `<edit-config>` request causes a SEGFAULT in Netopeer:

```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:t="urn:com:test"
     message-id="1">
  <edit-config>
    <target>
      <running/>
    </target>
    <config>
      <basics xmlns="urn:com:test">
        <scalar xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="remove"/>
      </basics>
    </config>
  </edit-config>
</rpc>
```

Relevant netopeer2 output (ran with -d -v2 flags):

> [INF]: NP: Session 1: thread 2 event new RPC.
> [INF]: SR: Published event "rpc" "/ietf-netconf:edit-config" with ID 5 priority 0 for 1 subscribers.
> Segmentation fault

Meanwhile, when I try this the following way, where I give a value to scalar (I know, technically it doesn't make sense):

```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:t="urn:com:test"
     message-id="1">
  <edit-config>
    <target>
      <running/>
    </target>
    <config>
      <basics xmlns="urn:com:test">
        <scalar xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" nc:operation="remove">321</scalar>
      </basics>
    </config>
  </edit-config>
</rpc>
```

The remove operation works fine.

Do you know what might cause this? I attached the test schema used.
[test.tar.gz](https://github.com/CESNET/netopeer2/files/6741910/test.tar.gz)

libyang/sysrepo/libnetconf2/netopeer2 are all the latest devel version.

Thank you!

**Comment by michalvasko** [comment]
Seems I have never this this use-case even though it is quite basic when talking about *opaque* nodes (new kind of generic *libyang* node that cannot be stored as normal data node for various reasons). But with latest *libyang* it should work.

**Comment by awesomenode** [comment]
Thank you, it's working fine now!
