### ISSUE TITLE
[ERR]: LN: SSH key exchange error (Could not sign the session id).

### ISSUE THREAD

**Issue by zewei0920** [CESNET/netopeer2#945]
hi, michalvasko, could you help to check my problem:

1. version: the latest devel branch  of netopeer2-server 2.0.0 and it's depencied components,
2. cross-compile for ARM platform:
    when compile netopeer2-server:
    a. cmake INSTALL_MODULES:OFF  GENERATE_HOSTKEY:OFF  MERGE_LISTEN_CONFIG:OFF  ..
    b. execute the three scripts: setup.sh  mergh_hostkey.sh  mergh_config.sh
3. **Error** Message:
    a. when connect to netopeer2-server via netopeer2-cli, I get the err message as below:
        netopeer2-cli -d -v2:
`
> connect  --ssh --host 127.0.0.1 --port 830 --login root
nc ERROR: Starting the SSH session failed (Received SSH_MSG_DISCONNECT: 11:Bye Bye).
cmd_connect: Connecting to the 127.0.0.1:830 as user "root" failed.
>
`
        netopeer2-server -d -v2:

> [INF]: LN: Accepted a connection on 0.0.0.0:830.
[INF]: SR: Session 124 (user "root", CID 136) created.
[2021/06/28 00:38:31.054523, 1] ssh_server_connection_callback:  SSH client banner: SSH-2.0-libssh-0.7.2
[2021/06/28 00:38:31.054856, 1] ssh_analyze_banner:  Analyzing banner: SSH-2.0-libssh-0.7.2
[2021/06/28 00:38:31.436692, 1] ssh_server_curve25519_init:  Could not sign the session id
[ERR]: LN: SSH key exchange error (Could not sign the session id).

4. **Question**:
Could you give some advice about the possible reason ? 
Does it depend on the OPENSSH which not yet installed in the ARM platform? 

Thanks a lot in advance.

**Comment by michalvasko** [comment]
Not sure I can help much because I see the error
```
[ERR]: LN: SSH key exchange error (Could not sign the session id).
```
for the first time. But yes, I would definitely guess either *libssh* or its crypto back-end (*OpenSSL*) are to blame. If nothing else, I would not be using *libssh* 0.7.2, which is really old, and compile the latest 0.9.5 release.

**Comment by guoqi78** [comment]
can you tell how to solve this problem last? thank you.
