### ISSUE TITLE
nc ERROR: Session 1: SSH channel poll error (Socket error: disconnected).

### ISSUE THREAD

**Issue by dineshR478** [CESNET/netopeer2#946]
When trying edit-config from netopeer2-cli, getting these errors and server abruptly goes down.

a.xml:

```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
    <edit-config>
        <target>
            <candidate/>
        </target>
                <config>
           <Ethernet>
                        <Ports>
                          <port-number>1</port-number>
                          <port-name>Eth-1</port-name>
                    </Ports>
                        </Ethernet>
        </config>
        </edit-config>
</rpc>
```

Client:
```

> edit-config --config=/tmp/a.xml --target candidate
nc ERROR: Session 1: SSH channel poll error (Socket error: disconnected).
cli_send_recv: Failed to receive a reply.
>
```

Server:

WRN]: LN: User authentication successful with an empty password!
[INF]: LN: User "root" authenticated.
[INF]: LN: Received an SSH message "request-channel-open" of subtype "session".
[INF]: LN: Received an SSH message "request-channel" of subtype "subsystem".
[INF]: SR: Session 37 (user "root", CID 9) created.
[INF]: SR: There are no subscribers for "ietf-netconf-notifications" notifications.
[INF]: NP: Generated new event (netconf-session-start).
[INF]: LN: Schema "ietf-yang-metadata@2016-08-05" was requested.
[INF]: NP: Session 1: thread 0 event new RPC.
[INF]: LN: Schema "ietf-yang-library@2019-01-04" was requested.
[INF]: NP: Session 1: thread 4 event new RPC.
[INF]: LN: Schema "ietf-datastores@<any>" was requested.
[INF]: NP: Session 1: thread 0 event new RPC.
[INF]: LN: Schema "ietf-datastores@<any>" was requested.
[INF]: NP: Session 1: thread 4 event new RPC.
[INF]: LN: Schema "ietf-netconf-nmda@<any>" was requested.
[INF]: NP: Session 1: thread 0 event new RPC.
[INF]: LN: Schema "ietf-origin@<any>" was requested.
[INF]: NP: Session 1: thread 0 event new RPC.
[INF]: LN: Schema "ietf-netconf-with-defaults@2011-06-01" was requested.
[INF]: NP: Session 1: thread 0 event new RPC.
[INF]: SR: Published event "rpc" "/ietf-netconf-nmda:get-data" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf-nmda:get-data" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: SR: Successful processing of "rpc" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 1 priority 0 succeeded.
[INF]: NP: Session 1: thread 0 event new RPC.
[INF]: LN: Schema "sysrepo@2021-03-31" was requested.
[INF]: NP: Session 1: thread 3 event new RPC.
[INF]: LN: Schema "sysrepo-monitoring@2021-01-15" was requested.
[INF]: NP: Session 1: thread 3 event new RPC.
[INF]: LN: Schema "sysrepo-plugind@2020-12-10" was requested.
[INF]: NP: Session 1: thread 3 event new RPC.
[INF]: LN: Schema "ietf-netconf-notifications@2012-02-06" was requested.
[INF]: NP: Session 1: thread 3 event new RPC.
[INF]: SR: Published event "rpc" "/ietf-netconf:edit-config" with ID 1 priority 0 for 1 subscribers.

**Comment by michalvasko** [comment]
If you use latest `devel`, it should not crash but it will not work either. Config for the edit-config is expected to be only
```xml
<Ethernet>
  <Ports>
    <port-number>1</port-number>
    <port-name>Eth-1</port-name>
  </Ports>
</Ethernet>
```
but you must specify the namespace of `Ethernet`.
