### ISSUE TITLE
Invalid argument error instead of missing argument in subscribe 

### ISSUE THREAD

**Issue by vshaker** [CESNET/netopeer2#948]
Hi , 
Instead of missing element i'm getting invalid argument error if starttime is not specified in subscribe command 
```
> user-rpc --content /home/airvana/vimala/DateTime/usr/bin/replay_error.xml 
ERROR
	type:     application
	tag:      operation-failed
	severity: error
	message:  Invalid argument
```

replay_error.xml:
```xml
<create-subscription xmlns="urn:ietf:params:xml:ns:netconf:notification:1.0">
        <stream>commscope_3gpp-nr-nrm-nrcelldu</stream>
        <stopTime>2021-06-23T18:59:36Z</stopTime>
</create-subscription>
```

If a `<stopTime>` is specified in a request without having specified
      a `<startTime>`, the following error is returned:
```
         Tag: missing-element

         Error-type: protocol

         Severity: error

         Error-info: <bad-element>: startTime

         Description: An expected element is missing.
``` 
```
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.140 (SO v5.6.56)
```

**Comment by michalvasko** [comment]
I have added the error with the others into *netopeer2* v2. As for the version you are using, it is basically missing the support for these specific errors so I am not able to add them without adding some messy code and I do not think the current behavior is bad enough to justify it so it will not be changed.
