### ISSUE TITLE
edit-config the same value as model default value maybe return success but don't save the change

### ISSUE THREAD

**Issue by yanjunxi** [CESNET/Netopeer2#95]
I have two model(model1.yang, model2.yang) and two data files(data1.xml, data2.xml).
When I use edit-config to config data2.xml, then config data1.xml, the last operation return OK but don't save the data to .running file, nonpre.running is empty. Use "get-config --source running" command can't get nonpre's data.
While I directly use edit-config to config data1.xml, it can save the data to nonpre.running correctly. Use "get-config --source running" command can get nonpre's data normally.

[attachment.txt](https://github.com/CESNET/Netopeer2/files/712877/attachment.txt)

**Comment by michalvasko** [comment]
Hi,
I don't know whether you used `master` or `devel` branches of all the applications, but when I tried in the current `devel`, it all worked as expected.

Regards,
Michal
