### ISSUE TITLE
Callback when the session ends and is not explcitly killed

### ISSUE THREAD

**Issue by fruv** [CESNET/netopeer2#950]
Hello,

Is there a callback we can subscribe to that will tell the session failed (ie the tcp session is lost, like not gracefully shutdown)?

Regards,

F.

**Comment by michalvasko** [comment]
Not really but you can subscribe to [`netconf-session-end`](https://github.com/sysrepo/sysrepo/blob/master/modules/ietf-netconf-notifications.yang#L179) notification that includes the termination reason.

**Comment by fruv** [comment]
Thanks Michal, it is working fine.
