### ISSUE TITLE
with-defaults trim option causes segfault

### ISSUE THREAD

**Issue by awesomenode** [CESNET/netopeer2#952]
Hi!

I've noticed, that using the trim with-default options using the `<get>` operation netopeer throws a segmentation fault.

> [INF]: NP: Session 1: thread 2 event new RPC.
> [INF]: SR: Published event "rpc" "/ietf-netconf:get" with ID 3 priority 0 for 1 subscribers.
> [INF]: SR: Processing "/ietf-netconf:get" "rpc" event with ID 3 priority 0 (remaining 1 subscribers).
> [INF]: SR: Successful processing of "rpc" event with ID 3 priority 0 (remaining 0 subscribers).
> [INF]: SR: Event "rpc" with ID 3 priority 0 succeeded.
> Segmentation fault

For example, the following RPC can reproduce the issue:
```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="">
  <get>
    <filter type="subtree">
      <t:basics xmlns:t="urn:com:test"/>
    </filter>
    <ncwd:with-defaults xmlns:ncwd="urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults">trim</ncwd:with-defaults>
  </get>
</rpc>
```

I've attached the test model I've used.

libyang/sysrepo/libnetconf2/netopeer are all the latest devel version.

Thanks!
[test.tar.gz](https://github.com/CESNET/netopeer2/files/6789481/test.tar.gz)

**Comment by michalvasko** [comment]
Right, should work now.
