### ISSUE TITLE
Invalid namespace hang

### ISSUE THREAD

**Issue by antonio-paunovic** [CESNET/Netopeer2#96]
Hi, 

Depending on rpc message:

```
netopeer2-server[116]: Session 1: received message:

<?xml version="1.0" encoding="UTF-8"?>
<rpc message-id="f805e7f7-a281-491f-aa94-16fa8b9f6a84"><get-config><source><running/></source></get-config></rpc>
netopeer2-server[116]: Session 1: invalid message root element (invalid namespace).
netopeer2-server[116]: Session 1: malformed message received.
[2017/01/27 11:42:38.611362, 3] ssh_channel_read_timeout:  Read (1) buffered : 1 bytes. Window: 1279834
[2017/01/27 11:42:38.611369, 3] ssh_channel_read_timeout:  Read (1) buffered : 0 bytes. Window: 1279834
[2017/01/27 11:42:38.611452, 3] ssh_channel_read_timeout:  Read (1) buffered : 0 bytes. Window: 1279834
[2017/01/27 11:42:38.611531, 3] ssh_channel_read_timeout:  Read (1) buffered : 0 bytes. Window: 1279834
```
And so on until I stop the client program:
```
[2017/01/27 11:42:39.585179, 3] ssh_channel_read_timeout:  Read (1) buffered : 0 bytes. Window: 1279834
[2017/01/27 11:42:39.585260, 3] ssh_channel_read_timeout:  Read (1) buffered : 0 bytes. Window: 1279834
[2017/01/27 11:42:39.585340, 3] ssh_channel_read_timeout:  Read (1) buffered : 0 bytes. Window: 1279834
[2017/01/27 11:42:39.585348, 1] ssh_socket_exception_callback:  Socket exception callback: 1 (0)
[2017/01/27 11:42:39.585357, 1] ssh_socket_exception_callback:  Socket error: disconnected
netopeer2-server[116]: Session 1: reading from the SSH channel failed (Socket error: disconnected).
netopeer2-server[116]: Sending session-stop request.
netopeer2-server[116]: session-stop request sent, waiting for response.
```

So, server hangs when rpc has invalid namespace. It may be an unexpected behavior.
This way it worked as expected: 
```
netopeer2-server[124]: Session 1: received message:

<?xml version="1.0" encoding="UTF-8"?>
<rpc message-id="a179dd76-7fbd-4f4e-b005-d5045493187d" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><get-config><source><running/></source></get-config></rpc>
netopeer2-server[124]: Sending session-switch-ds request.
netopeer2-server[124]: session-switch-ds request sent, waiting for response.
netopeer2-server[124]: fd 6 readable
netopeer2-server[124]: 29 bytes of data received on fd 6
netopeer2-server[124]: fd 6 would block
netopeer2-server[124]: New message of size 25 bytes received.
```

As a client [go-netconf](https://github.com/sartura/go-netconf) was used to create a get-config call.

Regards,
antoniop

**Comment by michalvasko** [comment]
Hi Antonio,

I did some general bugfixes and it may have solved this issue, so please try again. Even if not, I will need a better description of what is happening and what you would expect to happen.

It's better to start the server with just `-v2`, because there are many libssh debug messages otherwise, which can be actually correct. Still, the hang may be fine, it all depends on the data sent by the client. I would advise you to lower `READ TIMEOUT` (option of *libnetconf2*) to something like 5 s. Then you should see some message after maximum of 5 s and only if nothing would be happening and you could not send/receive any messages for longer than that, there is some actual problem.

Regards,
Michal

**Comment by antonio-paunovic** [comment]
Hi Michal,

For me problem was server hanging when it gets bad request like below:

```
<?xml version="1.0" encoding="UTF-8"?>
<rpc message-id="5dd936dc-7cfa-4f56-ae1e-23dec5348881"><edit-config><target><running/></target><config><interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces"><interface><name>eth42</name><type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type></interface></interfaces></config></edit-config></rpc>
netopeer2-server[77]: DICT: inserting "rpc" with collision 
netopeer2-server[77]: DICT: inserting "message-id" with collision 
netopeer2-server[77]: DICT: inserting "5dd936dc-7cfa-4f56-ae1e-23dec5348881" with collision 
netopeer2-server[77]: DICT: inserting (refcount) "edit-config"
netopeer2-server[77]: DICT: inserting (refcount) "target"
netopeer2-server[77]: DICT: inserting (refcount) "running"
netopeer2-server[77]: DICT: inserting (refcount) ""
netopeer2-server[77]: DICT: inserting (refcount) ""
netopeer2-server[77]: DICT: inserting (refcount) "config"
netopeer2-server[77]: DICT: inserting (refcount) "interfaces"
netopeer2-server[77]: DICT: inserting (refcount) "urn:ietf:params:xml:ns:yang:ietf-interfaces"
netopeer2-server[77]: DICT: inserting (refcount) "interface"
netopeer2-server[77]: DICT: inserting (refcount) "name"
netopeer2-server[77]: DICT: inserting "eth42" with collision 
netopeer2-server[77]: DICT: inserting (refcount) "type"
netopeer2-server[77]: DICT: inserting (refcount) "ianaift"
netopeer2-server[77]: DICT: inserting (refcount) "urn:ietf:params:xml:ns:yang:iana-if-type"
netopeer2-server[77]: DICT: inserting "ianaift:ethernetCsmacd" with collision 
netopeer2-server[77]: DICT: inserting (refcount) ""
netopeer2-server[77]: DICT: inserting (refcount) ""
netopeer2-server[77]: DICT: inserting (refcount) ""
netopeer2-server[77]: DICT: inserting (refcount) ""
netopeer2-server[77]: DICT: inserting (refcount) ""
netopeer2-server[77]: Session 1: invalid message root element (invalid namespace).
netopeer2-server[77]: Session 1: malformed message received.
```
I wasn't aware if this was expected behaviour. Server would give message about invalid namespace.
xmlns was missing from rpc element. 
So when I tried to make a valid request via other local client (netopeer2 server is running in container) while server was choking, it also failed. 
It didn't seem to me that this was an expected behaviour.
Curiously, ```ssh_channel_read_timeout``` repeats until ```ssh_socket_exception_callback``` happens and exceptions are opposite of expected behaviour.

I don't have problem right now but it seemed like a bug.

**Comment by michalvasko** [comment]
Hi Antonio,

I am not sure you read what I wrote before, but it all comes down to this. Either you describe exactly what you did, what commands did you send, what did the server display, **how long did you wait after seemingly hanged server** (like I said, it currently may be up to 30 seconds and the server still works fine), and what did you do with the other client, whether you connected before or after the hang or I will not be able to fix the issue.

Still, the reaction on `malformed-message` is different for NETCONF 1.0 and NETCONF 1.1, so I need to know what version did the client use as well. Next, the socket exception may be fine when the client disconnects before the server. Finally, the current server architecture uses only 1 thread for all requests for all sessions (but another thread for creating new sessions, that should always work), so if one client sends some malformed data, until it is properly dealt with (such as waiting 30s by default for some additional data that may be missing), no other request is responded to.

Regards,
Michal

**Comment by antonio-paunovic** [comment]
Hi Michal,

This actually seems to be issue in libnetconf2: 
There is a possibility to get in infinite loop and I found out that is what happens in my situation.
In this code:
https://github.com/CESNET/libnetconf2/blob/master/src/io.c#L86-L109

What happens to me is following:
`r` from https://github.com/CESNET/libnetconf2/blob/master/src/io.c#L89 is 0 and  
so is `ssh_channel_is_eof(session->ti.libssh.channel) ` from https://github.com/CESNET/libnetconf2/blob/master/src/io.c#L100.

This way loops goes on and if `readdr` is lower than `count` (0 < 1 in my case) it will stay in the loop until client application timeout expires, ssh connection breaks and then session stops.

If I do a request from from another client during first request, it will wait until first breaks and then continue normally, which is expected behaviour from what I understood from what you wrote.

So, in my case we patched client and it works. I don't know how it is to be addressed but it looked like a exceptional case which should be handled so I reported it.

Regards,
Antonio

**Comment by michalvasko** [comment]
Hi Antonio,

now I understand exactly what is happening and can confirm that what I thought at the beginning was correct. In short, this is a feature, not a bug (of Linux file descriptors). In the code you mentioned, you can see that I first try function `ssh_channel_read()` and then check for EOF using  `ssh_channel_is_eof()`. If both functions succeed there is nothing else I can (as a server in socket context) do. That is one of the reasons why `READ_TIMEOUT` was introduced so that such a buggy client will not hang the server forever. What is currently unfortunate is that while the timeout does not elapse, no other connection can be communicated on. I will address this issue tomorrow or the next week, I hope (add more threads for session handling).

Regards,
Michal

**Comment by antonio-paunovic** [comment]
I see, thanks  for explanation, haven't thought about that peculiarity.

Regards,
Antonio
