### ISSUE TITLE
Multiple replayComplete is coming when we subscribe for notifications 

### ISSUE THREAD

**Issue by vshaker** [CESNET/netopeer2#960]
Hi , 

When i subscribe for notification , i see that 3times replayComplete  is getting printed before notification replay could start
and timings all 3 replayComplete remains the same (2021-07-01T05:14:34Z) and the last replayComplete after the notification is replayed is also of same time (2021-07-01T05:14:34Z)
```
[root@kubernetes-master ~]# netopeer2-cli 
> connect --ssh --host 10.53.203.15 --port 830 --login root
> subscribe --filter-xpath /commscope-o-ran-ru:* --begin -600
OK
> 
notification (2021-07-01T05:14:34Z)
<replayComplete xmlns="urn:ietf:params:xml:ns:netmod:notification"/>

> 
notification (2021-07-01T05:14:34Z)
<replayComplete xmlns="urn:ietf:params:xml:ns:netmod:notification"/>

> 
notification (2021-07-01T05:14:34Z)
<replayComplete xmlns="urn:ietf:params:xml:ns:netmod:notification"/>

> 
notification (2021-07-01T05:10:13Z)
<ru-notification-info xmlns="urn:commscope:o-ran:ru:1.0">
  <ru-notification>
    <ru-instance>1</ru-instance>
    <cell-id>cellindex_1</cell-id>
    <ruConnectionStatus>DISCONNECTED</ruConnectionStatus>
    <interface-name>intf-name1</interface-name>
    <ruIpAddress>2001:25:207:196::124</ruIpAddress>
    <component-name>name1</component-name>
    <OUI>Product-code</OUI>
    <up_time>23</up_time>
    <serialNumber>0005B9Abab01</serialNumber>
    <swVersion>2</swVersion>
    <productClass>ru-ngrp-prodclass</productClass>
    <adminState>locked</adminState>
  </ru-notification>
</ru-notification-info>

> 
notification (2021-07-01T05:14:34Z)
<replayComplete xmlns="urn:ietf:params:xml:ns:netmod:notification"/>


### Version used :
Netopeer2 CLI 2.0.62
Compile time: Jul 15 2021, 11:14:12

netopeer2-server 1.1.76
compile time: Jul 15 2021, 11:14:11

sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo **v1.4.144 (SO v5.6.60)**

**Comment by meghna-doshi** [comment]
Hi,
We are also facing similar issue with notification replay feature.
We are seeing some inconsistent behaviour, like:

Case 1:
1. subcribe from netopeer2-cli 
`subscribe --filter-xpath /commscope-o-ran-ru:*|/commscope_3gpp-nr-nrm-nrcelldu:*|/o-ran-agg-sync:*|o-ran-agg-uplane-conf:* --begin -6000`

2. first 2 replayComplete are sent:

3. then actual notifications replayed
4. at the end of every stream, replay complete is sent.

As per RFC 5277, replayComplete should be sent only once at the end of all replay done. 
Can you please help us fix this issue.

netopeer2-server 1.1.76
sysrepoctl - sysrepo YANG schema manipulation tool, compiled with libsysrepo v1.4.144 (SO v5.6.60)

Regards,
Meghna

**Comment by michalvasko** [comment]
It should be fixed now, use the latest `libyang1` branch version of *sysrepo* and *netopeer2*.

**Comment by vshaker** [comment]
It worked with the latest version . Thank you
