### ISSUE TITLE
Using deref() in XPath filter causes segfault

### ISSUE THREAD

**Issue by awesomenode** [CESNET/netopeer2#961]
Hi!

I noticed while checking what happens when using wrong XPaths in a <get> operation, that
netopeer crashed while using the `deref()` function on a list node.

```
<nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"
        message-id="urn:uuid:49c03674-e69f-45fa-b13d-ed13c846ca6d">
  <nc:get>
    <nc:filter xmlns:t="urn:com:test" type="xpath" select="deref(/t:basics/t:animals)"/>
  </nc:get>
</nc:rpc>
```

> [INF]: SR: Published event "rpc" "/ietf-netconf:get" with ID 1 priority 0 for 1
> subscribers.
> [INF]: SR: Processing "/ietf-netconf:get" "rpc" event with ID 1 priority 0 (remaining 1
> subscribers).
> [WRN]: LY: Argument #1 of xpath_deref is a list node "animals".
> Segmentation fault

Of course this is not a valid use-case, but it might affect the server stability.

I attached the test schema I used.

libyang/sysrepo/libnetconf2/netopeer2 version are all the latest devel versions.

Thanks!
[test.tar.gz](https://github.com/CESNET/netopeer2/files/6831255/test.tar.gz)

**Comment by michalvasko** [comment]
Should not crash anymore.

**Comment by awesomenode** [comment]
Seems to work now, thanks!
