### ISSUE TITLE
Potential error(e.g., deadlock, ill peformance) due to the &stats.lock

### ISSUE THREAD

**Issue by jenny-cheung** [CESNET/netopeer2#964]
Hi, developers, thank you for your checking. The lock &stats.lock may not be correctly released if the `realloc` fails. Finally, the method returns with the unreleased lock. The fix is to insert  `pthread_mutex_unlock(&stats.lock); ` before returning.

https://github.com/CESNET/netopeer2/blob/a68ff29850cc3b3c1300ee066053cccf3d25a921/src/netconf_monitoring.c#L143
https://github.com/CESNET/netopeer2/blob/a68ff29850cc3b3c1300ee066053cccf3d25a921/src/netconf_monitoring.c#L153

```
void
ncm_session_add(struct nc_session *session)
{
    ...;
    pthread_mutex_lock(&stats.lock);

    ++stats.in_sessions;

    ++stats.session_count;
    new = realloc(stats.sessions, stats.session_count * sizeof *stats.sessions);
    if (!new) {
        EMEM;
        return; //return without releasing the lock
    }
    stats.sessions = new;
    new = realloc(stats.session_stats, stats.session_count * sizeof *stats.session_stats);
    if (!new) {
        EMEM;
        return; //return without releasing the lock
    }
    ...;

    pthread_mutex_unlock(&stats.lock);
}
```

Best,

**Comment by michalvasko** [comment]
Okay, I suppose, should be fixed now.

**Comment by jenny-cheung** [comment]
Thanks!
