### ISSUE TITLE
While establishing Netconf session via another user - user2, getting notification about root and not user2.

### ISSUE THREAD

**Issue by Abrahamma97** [CESNET/netopeer2#965]
Hi @michalvasko ,
Actually this is a question is the below expected?.
Procedure:
Establish the netconf session

Summary
When session is established via user2 we're getting the information about "root" in the notification  instead of "user2".
```
> connect --ssh --host 191.161.1.1 --port 830 --login user2
Interactive SSH Authentication
Type your password:
Password:
> subscribe 
OK
> 
notification (2021-07-22T07:56:49Z)
<netconf-config-change xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-notifications">
<changed-by>
<username>root</username>
<session-id>0</session-id>
</changed-by>
<datastore>running</datastore>
<edit>
<target xmlns:custom-yang="urn:custom-yang:1.1">/custom-yang:system-apps/custom-yang-wdm:supervision</target>
<operation>replace</operation>
</edit>
</netconf-config-change>
```

**Comment by michalvasko** [comment]
You have subscribed to receiving all the notifications including `netconf-config-change`. It seems someone authenticated as `root` has performed some datastore changes, so it was reported to you. I do not see you as `user2` doing any changes. If you did, you should be in the `changed-by` `username` node.
