### ISSUE TITLE
XPath filtering issue using bit-is-set() function

### ISSUE THREAD

**Issue by awesomenode** [CESNET/netopeer2#968]
Hi!

I've encountered an issue, when using the `bit-is-set()` XPath function. I know this is probably a libyang issue,
but I used netopeer2-server to reproduce this issue.

My test requires the 2 YANG schemas I've attached, and the following NETCONF commands:

First we put the 2 possible results of bit-is-set() into a leaf-list:
```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:t="urn:com:test"
     message-id="1">
  <edit-config>
    <target>
      <running/>
    </target>
    <config>
      <basics xmlns="urn:com:test">
        <sentence>true</sentence>
        <sentence>false</sentence>
      </basics>
    </config>
  </edit-config>
</rpc>
```

We set one of the bits:
```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:t2="urn:com:test2"
     message-id="1">
  <edit-config>
    <target>
      <running/>
    </target>
    <config>
      <basics xmlns="urn:com:test">
        <subbasics>
          <bitek xmlns="urn:com:test2">a</bitek>
        </subbasics>
      </basics>
    </config>
  </edit-config>
</rpc>
```

Then we return one of the elements of the leaf-list (true or false), depending on if the
respective bit (in this case 'a') was set:
```
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="">
  <get>
    <filter type="xpath" select="/t:basics/sentence[.=string(bit-is-
set(./../t:subbasics/t2:bitek,'a'))]" xmlns:t="urn:com:test" xmlns:t2="urn:com:test2"/>
  </get>
</rpc>
```

And last `<get>` RPC always returns 'true'. Shouldn't this return false? Am I doing something
wrong?

I'm using the latest devel of libyang/sysrepo/libnetconf2/netopeer2.

Thanks!
[test.tar.gz](https://github.com/CESNET/netopeer2/files/6891808/test.tar.gz)

**Comment by michalvasko** [comment]
It seems the function was comparing on the defined bits in the type instead of those set in the value for some reason. Should work now.

**Comment by awesomenode** [comment]
Works good now, thanks!
