### ISSUE TITLE
SSL Connect timeout/failed issue

### ISSUE THREAD

**Issue by masif-cs** [CESNET/netopeer2#969]
Hi,

I see one issue where on the client side I get "SSL_connect failed (Connection reset by peer)" or "SSL_connect timeout" log and from then on netopeer2-server never tries to retry call-home until restarted.

I have two question:
1.  When I am suppose to get that kind of error?
2. Why netopeer2-server never tries call-home again after this error?

Could you please help me in fixing this issue.

**Comment by michalvasko** [comment]
What versions of the projects are you using?

1. I have no idea, the error is a generic one but it seems the actual problem will be on the client side.
2. Not sure, it may be a bug or maybe caused by a socket that is not closed properly (or both).

**Comment by masif-cs** [comment]
I am using 1.0 latest image. I verified using netstat -nap command on linux, there are no stale socket.

**Comment by michalvasko** [comment]
> I am using 1.0 latest image.

What does that mean, some `docker` image or what exactly?

> By client side you mean netopeer2-cli? Why is that? I see that connection establishes once the netopeer-server restarts without changing anything on netopeer2-cli.

The server error you mentioned is most likely caused by a problem on the side of the client, what does *netopeer2-cli* print when you get that error in the server?

**Comment by masif-cs** [comment]
Let me put it like this, I am using all netconf libraries libyang, netopeer2 and sysrepo of 1.0 latest.

I am trying to establish call-home over TLS where netopeer2-cli is in listen mode using command:
listen --tls --cert /opt/gNB/cfg/client.crt --key /opt/gNB/cfg/client.key --trusted /opt/gNB/cfg/ca.pem

and netopeer2-server starts the call-home request. Thats when I get below error on netopeer2-cli side.
SSL_connect failed (Connection reset by peer)

**Comment by michalvasko** [comment]
Oh, sorry, I misread what you wrote. So the error you get is on the side of the client, what about the server then? Run it with `-d -v3` and paste the output here.

**Comment by Aaru47527** [comment]
**Title**
SSL/TLS Connection Timeout and Connection Refused Issues with Netopeer2
**Description**
I am experiencing issues with establishing a TLS connection using Netopeer2 CLI. The connection either times out or is refused. Below are the details of my setup and the steps I have taken:

### Setup Details
- **Netopeer2 CLI Version**: 2.0.62
- **Netopeer2 Server Version**: (Please provide the version here)
- **Operating System**: (Please provide your OS details here)
- **Configuration Files**:
  - `tls_keystore.xml`
  - `tls_truststore.xml`
  - `tls_listen.xml`

Steps Taken
Verified that the server is listening on port 830 using netstat and lsof.
Restarted the Netopeer2 server to apply configuration changes.
Verified that the certificates and keys are valid using openssl.
Attempted to connect using Netopeer2 CLI:

netopeer2-cli
> cert add /home/NETOPEER2_SRC/netopeer2-1.1.70/example_configuration/ca.pem
> cert replaceown /home/NETOPEER2_SRC/netopeer2-1.1.70/example_configuration/client.crt /home/NETOPEER2_SRC/netopeer2-1.1.70/example_configuration/client.key
> connect --host 192.168.1.10 --port 830 --tls --cert /home/NETOPEER2_SRC/netopeer2-1.1.70/example_configuration/client.crt --key /home/NETOPEER2_SRC/netopeer2-1.1.70/example_configuration/client.key --trusted /home/NETOPEER2_SRC/netopeer2-1.1.70/example_configuration/ca.pem
Error Messages
nc ERROR: SSL_connect timeout.
nc ERROR: Unable to connect to 192.168.1.10:830 (Connection refused).
nc ERROR: SSL_connect failed (certificate verify failed).
Log Output
From the server logs (mpru.log), there are recurring errors such as:

SSH key exchange error (Socket error: No such file or directory).
Unable to use Keyboard-Interactive authentication method without setting the name.
SSL_connect timeout.

**Questions:**
What might be causing the SSL/TLS connection timeout and refusal issues?
Are there any additional configurations or steps that I might be missing?
How can I debug the SSL_connect failed (certificate verify failed) error in more detail?
Any assistance or guidance on resolving these issues would be greatly appreciated. Thank you!

**Comment by michalvasko** [comment]
Why do you see SSH errors on the server side if you claim to be using TLS? Omit the port specification or manually set the port of the TLS server endpoint, not SSH.
