### ISSUE TITLE
Action support in netopeer2-server

### ISSUE THREAD

**Issue by fabioantonini** [CESNET/Netopeer2#97]
Hi 
I have some problem to assert an action (Yang 1.1) to netopeer2-server.

From my NETCONF client (NETCONFc) I send an action but netopeer2-server claims in this way
```
May 30 12:36:32 sysrepo netopeer2-server[5503]: Session 1: received message: <?xml version="1.0" encoding="UTF-8"?> <rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="e96d6d1e-e935-11e6-81fb-b870f4ee5398">   <action xmlns="urn:ietf:params:xml:ns:yang:1">     <cli:config xmlns:cli="http://www.tiesse.com/ns/tiesse-cli/1.0">       <dhcp-server:dhcp-server xmlns:dhcp-server="urn:ietf:params:xml:ns:yang:tiesse-dhcp-server">         <dhcp-server:on/>       </dhcp-server:dhcp-server>     </cli:config>   </action> </rpc>
May 30 12:36:32 sysrepo netopeer2-server[5503]: DICT: inserting "rpc" with collision
May 30 12:36:32 sysrepo netopeer2-server[5503]: DICT: inserting (refcount) "urn:ietf:params:xml:ns:netconf:base:1.0"
May 30 12:36:32 sysrepo netopeer2-server[5503]: DICT: inserting "message-id" with collision
May 30 12:36:32 sysrepo netopeer2-server[5503]: DICT: inserting "e96d6d1e-e935-11e6-81fb-b870f4ee5398" with collision
May 30 12:36:32 sysrepo netopeer2-server[5503]: DICT: inserting (refcount) "action"
May 30 12:36:32 sysrepo netopeer2-server[5503]: DICT: inserting (refcount) "urn:ietf:params:xml:ns:yang:1"
May 30 12:36:32 sysrepo netopeer2-server[5503]: DICT: inserting (refcount) "config"
May 30 12:36:32 sysrepo netopeer2-server[5503]: DICT: inserting (refcount) "cli"
May 30 12:36:32 sysrepo netopeer2-server[5503]: DICT: inserting (refcount) "http://www.tiesse.com/ns/tiesse-cli/1.0"
May 30 12:36:32 sysrepo netopeer2-server[5503]: DICT: inserting (refcount) "dhcp-server"
May 30 12:36:32 sysrepo netopeer2-server[5503]: Session 1: sending message: <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="e96d6d1e-e935-11e6-81fb-b870f4ee5398"><rpc-error><error-type>protocol</error-type><error-tag>operation-not-supported</error-tag><error-severity>error</error-severity><error-message xml:lang="en">Request could not be completed because the requested operation is not supported by this implementation.</error-message></rpc-error></rpc-reply>
May 30 12:36:32 sysrepo netopeer2-server[5503]: Session 1: sending message:  ## 
```

The I have tried to assert the same action from netopeer2-cli by the following file (/tmp/action)
```
<action xmlns="urn:ietf:params:xml:ns:yang:1">
      <cli:config xmlns:cli="http://www.tiesse.com/ns/tiesse-cli/1.0">                     
            <dhcp-server:dhcp-server xmlns:dhcp-server="urn:ietf:params:xml:ns:yang:tiesse-dhcp-server">                                 
                    <dhcp-server:on/>
             </dhcp-server:dhcp-server>
      </cli:config>
</action>
```

from inside netopeer2-cli
```
> user-rpc --content /tmp/action
nc VERBOSE: <rpc-error> <error-message> without the recommended "xml:lang" attribute.
ERROR
        type:     protocol
        tag:      operation-not-supported
        severity: error
        message:  Request could not be completed because the requested operation is not supported by this implementation.
```
The answer is the same received from the NETCONF client.

Then I have tried to assert the same action directly to sysrepo by a command of mine
```
~ # sysrepo-action-sender -x /tiesse:config/tiesse-dhcp-server:dhcp-server/on
```
and the action callback has been properly invoked by sysrepod

here below some traces from sysrepo-plugind
```
May 30 12:43:24 sysrepo sysrepo-sysrepo-plugind[5760]: [DBG] fd 3 readable
May 30 12:43:24 sysrepo sysrepo-sysrepo-plugind[5760]: [DBG] 136 bytes of data received on fd 3
May 30 12:43:24 sysrepo sysrepo-sysrepo-plugind[5760]: [DBG] fd 3 would block
May 30 12:43:24 sysrepo sysrepo-sysrepo-plugind[5760]: [DBG] New message of size 132 bytes received.
May 30 12:43:24 sysrepo sysrepo-sysrepo-plugind[5760]: [DBG] Received Action request for subscription id=2033137842.
May 30 12:43:24 sysrepo sysrepo-sysrepo-plugind[5760]: [DBG] Calling Action callback for subscription id=2033137842.
May 30 12:43:24 sysrepo sysrepo-sysrepo-plugind[5760]: [DBG] tiesse-dhcp-server: tiesse-dhcp-server: ACTIONS plugin handler called for xpath /tiesse:config/tiesse-dhcp-server:dhcp-server/on
```

So my feeling is that netopeer2-server is missing something.
Have I to enable YANG 1.1 support in some way?

Thanks a lot for your feedback
fabio

**Comment by michalvasko** [comment]
Hi Fabio,
could you please provide the schemas? Thanks.

Regards,
Michal

**Comment by fabioantonini** [comment]
Hi Michal


here below the excerpt of the schemas


     augment "/cli:config" {
         container "dhcp-server" {
             leaf "active" {
                 type cli-types:onoff;
                 description "[hidden] Admitted values: on/off";
                 default "off";
             }
             action on {}
             action off {}
             list server {
                 key "name";
                 leaf "name" {
                     type "string";
                     description "[hidden] Dhcp server name";
                 }
                 uses dhcp-params;
                      action on {}
                      action off {}
                 description "[hidden|noexec] Dhcp server list";
             }
             description "[deleteflag] Dhcp server container";
         }
     }

thanks

fabio

**Comment by michalvasko** [comment]
Hi Fabio,
are you using `master` or `devel` branches?

Michal

**Comment by fabioantonini** [comment]
I'm using the master branch for all the packages

thanks

fabio

**Comment by michalvasko** [comment]
Because I am using actions quite a lot lately and had no problems, but I use the `devel` branch. Could you please try it?

Michal

**Comment by fabioantonini** [comment]
AT the moment I cannot switch all the packages to the devel

is it possible to use the devel branch only for Netopeer2 and Libyang?

When do you plan to merge the devel into the master branch?

thanks a lot

fabio

**Comment by michalvasko** [comment]
No, you would have to use `devel` of libyang, libnetconf2, netopeer2-server, and sysrepo. We plan to do the merge at the end of February, could you maybe wait until then? If not, then I will try it myself on `master` and find the bugfixes from `devel` that will fix the issue, if I manage to reproduce it, but it will take some of my time, so I would rather avoid it.

Michal

**Comment by fabioantonini** [comment]
Hi Michal

thanks a lot for your support

We can wait because the actions are working writing directly to 
sysrepod. SO we can test them from the shell.

with regards

fabio

**Comment by fabioantonini** [comment]
I have successfully verified the Action feature with the devel branches. It works fine. So the issue can be closed. Thanks
fabio
