### ISSUE TITLE
build error when try to use custom library and header

### ISSUE THREAD

**Issue by khanhn29** [CESNET/netopeer2#972]
Hello,

I'm trying to build netopeer2 with custom library and header that I've put in other directory by doing this:

![image](https://user-images.githubusercontent.com/54073251/128002807-eabfdb9b-b4b5-43c7-be8e-6d63e6fd19c1.png)

but end up meet this error

![image](https://user-images.githubusercontent.com/54073251/128002953-fe6ed199-542b-482c-aaa0-0a86c4a3763a.png)

what am I missing here

**Comment by michalvasko** [comment]
Looking at the OpenSSL [repository](https://github.com/openssl/openssl/blob/master/include/openssl/x509.h.in), it seems this header is being generated. That means your OpenSSL include directory must be not only the one you have used but also the one where generated files are put in. It is up to you to find it.

However, you would spare yourself these problems if you followed the usual way of using custom libraries in compilation. Which is installing all of them into a specific path and then pass only this path as include/library directory. You will never miss any files that way.

**Comment by khanhn29** [comment]
Thank you for quick response and your advice. I installed all of them into same directory and only need to use prefix to install sysrepo, libnetconf2, netopeer2 still need include/library path as you said. 👍
![image](https://user-images.githubusercontent.com/54073251/128024837-60d747c5-281a-49f8-b7d7-20a35f1a0ac3.png)

If I use custom path directory to build:

- how can I specify the sysrepoctl path to automatically install netopeer2 YANG model by script

- how can I use lib files that I store in my custom directory to run sysrepoctl after I specify its path (I used to use export LD_LIBRARY_PATH to run)

- why I don't find netopeer2-cli in prefix directory

I got this error message
![image](https://user-images.githubusercontent.com/54073251/128023449-dd08f2c6-b956-4a61-9cc7-78e1b6478c40.png)

**Comment by michalvasko** [comment]
1. It is expected that it is somewhere in `PATH`. If it is not, you can temporarily make it so by adding the directory with it into the `PATH` environment variable.
2. Generic Linux question but fine, I will answer. You can either do it the way you mentioned or make sure your `ld(1)` finds it. Look into `ldconfig(8)` `man` page to learn how to add new paths with libraries to it.
3. Because it is installed in the last step of *netopeer2* installation but in your case it has failed before it.

**Comment by khanhn29** [comment]
Thanks, I set SYSREPOCTL_EXECUTABLE to sysrepoctl's path and then make install and netopeer2 installation successful
