### ISSUE TITLE
callback failed 

### ISSUE THREAD

**Issue by bkumarrr** [CESNET/netopeer2#974]
Hi all
I have written a sample callback and installed my sample yang model, but when I want to edit its config using **edit-config --target running --config** netopeer2-server gives following output
**[INF]: SR: Published event "rpc" "/ietf-netconf:edit-config" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: NP: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
[INF]: SR: Successful processing of "rpc" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 1 priority 0 succeeded.
[INF]: NP: Session 1: thread 3 event new RPC.**

I am not able to understand why netopeer2-serever not calling my registered callback function 

here are my edit config file logs 
```
xmlns= "urn:sysrepo:my"
<turned-on>1</turned-on>
```

Kindly help

**Comment by michalvasko** [comment]
Could you please share the YANG module, the XPath you have used for subscribing, and the exact config you have used for the `edit-config`? Thanks.

**Comment by bkumarrr** [comment]
Below is my Yang module
module my {
    namespace "urn:sysrepo:my";
    prefix my;

    revision 2021-05-29 {
        description "Initial revision.";
    }
    container led-data {
        description "Configuration container for led";
        leaf turned-on {
            description " determining whether the LED is on or off.";
            type uint8;
        }
    }
    container led-state {
        description "State data container of the LED.";
        config false;
        leaf temperature {
            description "Actual LED Condition";
            type boolean;
        }

    }
}

and below is my config
xmlns= "urn:sysrepo:my"
<turned-on>1</turned-on>

**Comment by michalvasko** [comment]
The config is not a valid XML, please include one. What I would expect to be valid is
```xml
<led-data xmlns="urn:sysrepo:my">
  <turned-on>1</turned-on>
</led-data>
```

**Comment by bkumarrr** [comment]
Hi @michalvasko 
getting same error with your XML also 
below are logs from server side
[INF]: SR: Published event "rpc" "/ietf-netconf:edit-config" with ID 1 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INF]: NP: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
[INF]: SR: Successful processing of "rpc" event with ID 1 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 1 priority 0 succeeded.
[INF]: NP: Session 2: thread 1 event new RPC.

**Comment by michalvasko** [comment]
Then the problem will be with your subscription, you have not posted it like I have asked you to. You can simply try running `examples/application_changes_example my` from *sysrepo* examples and you will see the changes.

**Comment by bkumarrr** [comment]
Hi @michalvasko 
I have tried that also but this infinitely waiting for change (even if edit-config is done with your suggested XML)
below are logs of sudo ./application_changes_example my
Application will watch for changes in "my".

 ========== READING RUNNING CONFIG: ==========

/my:led-data (container)


 ========== LISTENING FOR CHANGES ==========

**Comment by michalvasko** [comment]
What *sysrepo* version are you using? In any case, there is something seriously wrong with your installation.

**Comment by bkumarrr** [comment]
Hi @MarioKuka 
Sorry I don't know how to check its version,can you please tell me how to check

**Comment by michalvasko** [comment]
I see, then switch to using the `devel` branch for all the projects (*libyang*, *libnetconf2*, *sysrepo*, and *netopeer2*) and try again. The current `master` versions were still quite new and unpolished so it is possible there was such a bug.

**Comment by bkumarrr** [comment]
okay @michalvasko 
will try and let you know

**Comment by bkumarrr** [comment]
Hi @michalvasko 
I have switch to using the devel branch for all the projects (libyang, libnetconf2, sysrepo, and netopeer2) and tried again,everything compiled (libyang,libnetconf2,sysrepo) but netopeer2 was throwing error
Errors are attached in below file

**Comment by michalvasko** [comment]
Please attach the file.

**Comment by bkumarrr** [comment]
[netopeer2_buid_error.odt](https://github.com/CESNET/netopeer2/files/6938714/netopeer2_buid_error.odt)

**Comment by bkumarrr** [comment]
@michalvasko Please help its very urgent

**Comment by michalvasko** [comment]
I would suggest to remove the whole `build` directory and rerun `cmake`, I have no idea what all those errors are supposed to be so likely you have kept the old ones that cannot be used with the new version.

**Comment by bkumarrr** [comment]
Hi @michalvasko 
Getting same error even after removing###  build directory and rerun cmake ..

**Comment by bkumarrr** [comment]
Hi @MarioKuka 
I am still getting multiple errors in Netopeer2/cli/commands.c [ regarding error: conflicting types for ‘UNUSED’,error: conflicting types for ‘cmd_disconnect’, and multiple warnings like warning: unused parameter ‘UNUSED’ [-Wunused-parameter]
please help @michalvasko

**Comment by michalvasko** [comment]
Are you not by any chance running the `CMakeLists.txt` in `netopeer2/cli`? Because you must not do that, only the main `netopeer2/CMakeLists.txt` is meant to be executed, it will build both the server and the client.

**Comment by bkumarrr** [comment]
Hi @MarioKuka 
CMakeLists.txt is present in netopeer2/cli but not sure not it is executed or not

**Comment by michalvasko** [comment]
Firstly, please stop referencing my colleague Mario Kuka. Then, follow [these](https://github.com/CESNET/Netopeer2/#compilation-and-installation) instructions for compilation starting in the repository root.

**Comment by bkumarrr** [comment]
Ohh sorry for that

**Comment by bkumarrr** [comment]
Hi @michalvasko 
following the same steps but getting error

**Comment by michalvasko** [comment]
Can you post the **whole** output of those steps?

**Comment by bkumarrr** [comment]
Hi @michalvasko 
Please find attach
[netopeer2_buid_error.odt](https://github.com/CESNET/netopeer2/files/6943844/netopeer2_buid_error.odt)

**Comment by michalvasko** [comment]
Quite strange, that seems fine. Can you attach the file `build/compat/compat.h`?

**Comment by bkumarrr** [comment]
Hi @michalvasko 
[compact.h.odt](https://github.com/CESNET/netopeer2/files/6943955/compact.h.odt)

**Comment by michalvasko** [comment]
I honestly don't know, it seems your compiler does not recognize the `__unused__` attribute but based on all the output you should have GCC 7.5.0, which definitely should. Can you post the output of `cc --version`?

**Comment by bkumarrr** [comment]
Hi @michalvasko 

cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by michalvasko** [comment]
I have just tried it in my virtual Ubuntu 18.04, which should be exactly what you have, with the same GCC (exact same version as you have posted) and it compiled without problems. So I must assume there is something wrong on your end, are you sure you have the unmodified `devel` branch of *netopeer2*? When you run `git diff` in `netopeer2`, is it empty?

**Comment by bkumarrr** [comment]
Hi @michalvasko 
Yes git diff in netopeer2 is empty ,can you please suggest me what should I do now

**Comment by michalvasko** [comment]
I am sorry but I tried to helped how I could and since it is working fine on what should be the exact same system you are on, there is something wrong on your specific system. It is impossible for me to guess what, ask for help someone around you, the problem is not specific to *netopeer2*.

**Comment by bkumarrr** [comment]
Hi @michalvasko 
Thanks for your so much support . I resolve this issue by removing the netopeer2 and re cloning and re building with the same steps 
but I discussed above when i do edit-config on my yang module ,server gives below logs

[INF]: SR: Published event "rpc" "/ietf-netconf:edit-config" with ID 2 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 2 priority 0 (remaining 1 subscribers).
[INF]: NP: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
[INF]: SR: Successful processing of "rpc" event with ID 2 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 2 priority 0 succeeded.
[INF]: NP: Session 1: thread 1 event new RPC.

and application_changes_example is also waiting infinitely 
 sudo ./application_changes_example my
[sudo] password for vvdn: 
Application will watch for changes in "my".

 ========== READING RUNNING CONFIG: ==========

/my:led-data (container)


 ========== LISTENING FOR CHANGES ==========

**Comment by michalvasko** [comment]
Why did you run the application as `root`? That should not be required unless there is something wrong.

**Comment by bkumarrr** [comment]
I was doing that without root but getting error 
Application will watch for changes in "my".

 ========== READING RUNNING CONFIG: ==========

[ERR]: Write permission "my" check failed.

**Comment by bkumarrr** [comment]
I am able to got change message when I run it in root {but using sudo sysrepocfg -Iconfig.xml -d running -m my command only ]

**Comment by michalvasko** [comment]
If you run `sysrepoctl -l`, it will print all the modules with their permissions. There you see whether you have access to the module, which you obviously do not. So you should probably change that.

**Comment by bkumarrr** [comment]
Hi @michalvasko 
Given 644 permission but getting same errors

**Comment by michalvasko** [comment]
Look, the permissions/owner are using the standard file system access control. It seems you also need to change the owner or give write access to all the users. But you should know this, we are not providing Linux tutorial as part of our support.

**Comment by bkumarrr** [comment]
Hi @michalvasko 
Still getting same issue even after changing owner and permission 

getting below logs from netopeer2-server side 
[INF]: SR: Published event "rpc" "/ietf-netconf:edit-config" with ID 15 priority 0 for 1 subscribers.
[INF]: SR: Processing "/ietf-netconf:edit-config" "rpc" event with ID 15 priority 0 (remaining 1 subscribers).
[INF]: NP: edit-config error-option "stop-on-error" not supported, rollback-on-error will be performed.
[INF]: SR: Successful processing of "rpc" event with ID 15 priority 0 (remaining 0 subscribers).
[INF]: SR: Event "rpc" with ID 15 priority 0 succeeded.
[INF]: NP: Session 4: thread 4 event new RPC.

**Comment by bkumarrr** [comment]
Hi @michalvasko 
I need to verify one thing from you is that if I write one application(which does something on changes )  in sysrepo plugin directory and build sysrepo .so that application will automatically called when netopeer2-cli want to changes the subscribed data

**Comment by michalvasko** [comment]
No, it is not automatically opened and callbacks called. You must start `sysrepo-plugind` to load and use the plugins.
