### ISSUE TITLE
cmake throwing error even though libnetconf is built with SSL and TSL support

### ISSUE THREAD

**Issue by sudeeptoroy** [CESNET/Netopeer2#98]
```
sud@sud-VirtualBox:~/Documents/projects/Netopeer2/cli$ cd build/
sud@sud-VirtualBox:~/Documents/projects/Netopeer2/cli/build$ cmake .. 
CMake Error at CMakeLists.txt:50 (message):
  Missing SSH and TLS support in libnetconf2, CLI requires at least one them
  to be supported.


roff2html not found, html version of man pages cannot be generated!
-- Configuring incomplete, errors occurred!
See also "/home/sud/Documents/projects/Netopeer2/cli/CMakeFiles/CMakeOutput.log".
sud@sud-VirtualBox:~/Documents/projects/Netopeer2/cli/build$ whereis libnetconf2
libnetconf2: /usr/local/lib/libnetconf2.so
sud@sud-VirtualBox:~/Documents/projects/Netopeer2/cli/build$ 
sud@sud-VirtualBox:~/Documents/projects/Netopeer2/cli/build$ ldd /usr/local/lib/libnetconf2.so
	linux-vdso.so.1 =>  (0x00007ffccf5fc000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f55c4732000)
	libssh.so.4 => /usr/lib/x86_64-linux-gnu/libssh.so.4 (0x00007f55c44ec000)
	libssh_threads.so.4 => /usr/lib/x86_64-linux-gnu/libssh_threads.so.4 (0x00007f55c42ea000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f55c40b1000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f55c3e52000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f55c3a76000)
	libyang.so.0.11 => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f55c36b1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f55c4b87000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f55c34a9000)
	libz.so.1 => /usr/local/lib/libz.so.1 (0x00007f55c328e000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f55c308a000)
sud@sud-VirtualBox:~/Documents/projects/Netopeer2/cli/build$ cd ..
sud@sud-VirtualBox:~/Documents/projects/Netopeer2/cli$ cd ..
sud@sud-VirtualBox:~/Documents/projects/Netopeer2$ cd  ../libnetconf2/
sud@sud-VirtualBox:~/Documents/projects/libnetconf2$ 
sud@sud-VirtualBox:~/Documents/projects/libnetconf2$ grep -r LIBNETCONF2_ENABLED_SSH * 
FindLibNETCONF2.cmake:#  LIBNETCONF2_ENABLED_SSH - LibNETCONF2 was compiled with SSH support
FindLibNETCONF2.cmake:    check_symbol_exists("NC_ENABLED_SSH" "nc_client.h" LIBNETCONF2_ENABLED_SSH)
sud@sud-VirtualBox:~/Documents/projects/libnetconf2$ vim FindLibNETCONF2.cmake 
sud@sud-VirtualBox:~/Documents/projects/libnetconf2$ grep -r LIBNETCONF2_ENABLED_TLS * 
FindLibNETCONF2.cmake:#  LIBNETCONF2_ENABLED_TLS - LibNETCONF2 was compiled with TLS support
FindLibNETCONF2.cmake:    check_symbol_exists("NC_ENABLED_TLS" "nc_client.h" LIBNETCONF2_ENABLED_TLS)
sud@sud-VirtualBox:~/Documents/projects/libnetconf2$ 
sud@sud-VirtualBox:~/Documents/projects/libnetconf2$ cd .. 
sud@sud-VirtualBox:~/Documents/projects$ 
```

**Comment by michalvasko** [comment]
Hi,
please also sent the output of `# ldconfig -p | grep libnetconf2`.

Regards,
Michal

**Comment by sudeeptoroy** [comment]
sud@sud-VirtualBox:~/Documents/projects$ ldconfig -p | grep libnetconf2
	libnetconf2.so.0.7 (libc6,x86-64) => /usr/local/lib/libnetconf2.so.0.7
	libnetconf2.so (libc6,x86-64) => /usr/local/lib/libnetconf2.so
sud@sud-VirtualBox:~/Documents/projects$

**Comment by michalvasko** [comment]
Hi,
that seems fine so please post the content of `nc_client.h`, it should be found in `~/Documents/projects/libnetconf2`, thanks.

Regards,
Michal

**Comment by sudeeptoroy** [comment]
please find below:

Documents/projects/libnetconf2$ cat build/nc_client.h
/**
 * \file nc_client.h
 * \author Radek Krejci <rkrejci@cesnet.cz>
 * \brief libnetconf2's main public header for NETCONF clients.
 *
 * Copyright (c) 2015 CESNET, z.s.p.o.
 *
 * This source code is licensed under BSD 3-Clause License (the "License").
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://opensource.org/licenses/BSD-3-Clause
 */

#ifndef NC_CLIENT_H_
#define NC_CLIENT_H_

#ifndef NC_ENABLED_SSH
#define NC_ENABLED_SSH
#endif
#ifndef NC_ENABLED_TLS
#define NC_ENABLED_TLS
#endif

#include <libnetconf2/netconf.h>
#include <libnetconf2/log.h>
#include <libnetconf2/messages_client.h>
#include <libnetconf2/session_client.h>
#include <libnetconf2/session_client_ch.h>

#endif /* NC_CLIENT_H_ */

**Comment by michalvasko** [comment]
Hi,
that seems fine too. Perhaps you first installed a lnc2 version without SSH and TLS support and then later enabled it? You may try removing `CMakeCache.txt` from CLI directory and run `cmake` again. If that doesn't help, there could be a problem with 2 header versions, if you installed it somewhere else before. In that case you removed the old library itself, but you may have forgotten to remove the headers (that is where those macros that `cmake` can't seem to find are stored).

Regards,
Michal

**Comment by sudeeptoroy** [comment]
Hi MIchal,

you are right, i had initially disabled SSH and TLS and later enabled it.

I removed the CMakeCache.txt and tried build. This worked.

Thanks for this quick help.

Regards,
Sudeepto Roy
