### ISSUE TITLE
Where to run script https://github.com/CESNET/netopeer2/blob/master/cli/sample_script.sh

### ISSUE THREAD

**Issue by mpet** [CESNET/netopeer2#980]
Hi,

This is not an issue but a question where I can execute this file from? I guess netopeer2-server needs to be started first. Can I run it from a unix shell? 

br,

//mike

**Comment by michalvasko** [comment]
Yes, the server should be running and then you run it in a shell or simply execute it, the system knows it should be run by a shell because of [this](https://github.com/CESNET/netopeer2/blob/master/cli/sample_script.sh#L1) line.
