### ISSUE TITLE
Way to generater a c callback function for yang module 

### ISSUE THREAD

**Issue by bkumarrr** [CESNET/netopeer2#985]
Hi All
Is there any way through which can generate a dummy callback function(Then we can edit this function to our need) using a Yang module 
Thanks in adavance

**Comment by michalvasko** [comment]
No, there is no way of generating dummy callbacks because it is not needed. You simply call `sr_module_change_subscribe()` with an empty callback.

**Comment by bkumarrr** [comment]
Ok Thanks @michalvasko
