### ISSUE TITLE
Automatically load startup data when netopeer2-serer is started

### ISSUE THREAD

**Issue by bkumarrr** [CESNET/netopeer2#989]
Hi All,
how to enable automatically load startup data when netopeer2-serer is started ?
Thanks in adavance

**Comment by michalvasko** [comment]
That is not possible, `startup` DS is automatically copied to `running` DS only after machine boot. After that it must be performed manually.

**Comment by bkumarrr** [comment]
Ok Thanks @michalvasko for help 
Got This
