### ISSUE TITLE
regarding module_change_cb() API's argument

### ISSUE THREAD

**Issue by bkumarrr** [CESNET/netopeer2#991]
Hi 
I only want to pass argument (sess, module_name, event) in the callback function module_change_cb()
Is there any way to achieve this ?
Thanks in adavance

**Comment by michalvasko** [comment]
I am not sure I undertsand but if you want to pass your own argument to the `module_change` callback, use the `private_data` parameter of `sr_module_change_subscribe()`.

**Comment by bkumarrr** [comment]
Ok @michalvasko understood

can you please let me know who actually providing  data to following arguments in callback function module_change_cb()
(sub_id, request_id) ?

**Comment by michalvasko** [comment]
It depends on the argument but mostly *sysrepo* internally, why do you care? They are described so that should be all that you need.
