### ISSUE TITLE
multiple subscription

### ISSUE THREAD

**Issue by komik0** [CESNET/Netopeer2#994]
Hi all,
I would like to kindly ask if I am doing something wrong.
I am trying to subscribe for two xpaths:
```
# login to netopeer2-server
> subscribe --filter-xpath /o-ran-supervision:supervision-notification
OK
> subscribe --filter-xpath /o-ran-software-management:download-event
ERROR
        type:     protocol
        tag:      operation-failed
        severity: error
        message:  Session already subscribed.

> 
```
and here is my question - is it expected behavior?
I am asking because I've implemented suprvision mechanism (see sysrepo [2233](https://github.com/sysrepo/sysrepo/issues/2233)) and my plugin starts sending notification when there is subscriber on supervision-notification. but later I need to subscribe for download-event in my client and I see this error. If this behavior is expected can anyone give me a hint how to send create subscription for supervison-notification when I subscribe for all notification?

I will be thankful for any help

Regards
Mikolaj

**Comment by navneetkaurPS** [comment]
I am observing the same behavior.

**Comment by michalvasko** [comment]
There cannot be simultaneous subscriptions ([ref](https://www.rfc-editor.org/rfc/rfc5277.html#section-6.5)), use `<establish-subscription>` instead defined in [this RFC](https://www.rfc-editor.org/rfc/rfc8639).
