### ISSUE TITLE
[ERR]: LY: Invalid argument parent || module || ext (lys_getnext_())

### ISSUE THREAD

**Issue by PeterYFPeng** [CESNET/netopeer2#997]
I used sysrepo APIs to realize rpc defined by yang module. The netopeer2-server will occur  this error when the output cnt is more than 1. But if I calloc 2 size of output and set the output_cnt = 1,  I can call rpc successfully and get one output value.
**rpc define:** 
```yang
rpc oper {
        input {
            leaf arg {
                type string;
            }
        }

        output {
            leaf ret {
                type int64;
            }
            leaf ret1 {
                type string;
            }
        }
    }
```
**sysrepo plugins:**
```C
static int
rpc_cb(sr_session_ctx_t *session, uint32_t sub_id, const char *path, const sr_val_t *input, const size_t input_cnt,
        sr_event_t event, uint32_t request_id, sr_val_t **output, size_t *output_cnt, void *private_data)
{
    size_t i;

    (void)session;
    (void)sub_id;
   (void)event;
    (void)request_id;
    (void)private_data;

    printf("\n\n ========== RPC \"%s\" RECEIVED: =======================\n\n", path);
    for (i = 0; i < input_cnt; ++i) {
        print_val(&input[i]);
    }

    if (!strcmp(path, "/examples:oper")) {
        /* generate some output */
        // *output = malloc(sizeof **output);
        // *output_cnt = 1;

        // (*output)[0].xpath = strdup("/examples:oper/ret");
        // (*output)[0].type = SR_INT64_T;
        // (*output)[0].dflt = 0;
        // (*output)[0].data.int64_val = -123456;
        
        *output = calloc(2, sizeof **output);
        *output_cnt = 2;

        (*output)[0].xpath = strdup("/examples:oper/ret");
        (*output)[0].type = SR_INT64_T;
        (*output)[0].dflt = 0;
        (*output)[0].data.int64_val = -123456;

        (*output)[1].xpath = strdup("/examples:oper/ret1");
        (*output)[1].type = SR_STRING_T;
        (*output)[1].dflt = 0;
        (*output)[1].data.string_val = strdup("peter test");
    }
    printf("end tag\n");

    return SR_ERR_OK;
}
```
ERROR: 
[ERR]: LY: Invalid argument parent || module || ext (lys_getnext_())

**If I set output_cnt = 1, but output size is 2, I can call rpc successfully and get the first struct.**
```
> user-rpc
DATA
<ret xmlns="urn:examples">-123456</ret>
```

**Comment by michalvasko** [comment]
What *sysrepo*/*netopeer2* version are you using?

**Comment by wxes9250310s** [comment]
I met the same issue of [ERR]: LY: Invalid argument parent || module || ext (lys_getnext_()) when there is more than one leaf for rpc output.

**Comment by zewei0920** [comment]
hi, michalvasko,  any update about this issue ? because I met the a similar question. my yang as below :
```
    rpc get-history-alarms {
        description "get-history-alarms";
        input {
            leaf start-time {
                type yang:date-and-time;
                description "start-time";
            }
            leaf end-time {
                type yang:date-and-time;
                description "end-time";
            }
        }
        output {
            container alarms {
                uses alarms;
                description "output alarms";
            }
            container tcas {
                uses tcas;
                description "output tcas";
            }
        }
    }
```
and subscribe as below:
`rc = sr_rpc_subscribe(session, "/wdm-alarms:get-history-alarms", nc_reg_module_alarm_rpc_get_history_data, NULL, 0, 0, &subscription);`

and the cb is:
```
static int nc_reg_module_alarm_rpc_get_history_data(sr_session_ctx_t *session, uint32_t sub_id, const char *path, const sr_val_t *input, const size_t input_cnt, sr_event_t event, uint32_t request_id, sr_val_t **output, size_t *output_cnt, void *private_data)
{
            ......
            his_alarm_num = 1; 
            *output_cnt = 18 * his_alarm_num;
            *output = calloc(*output_cnt, sizeof **output);
            *output_cnt = 1;

            (*output)[0].xpath = strdup("xxxxxx");
            (*output)[0].type = SR_STRING_T;
            (*output)[0].dflt = 0;
            (*output)[0].data.string_val = strdup(alarm.objectName);

            (*output)[1]....
            (*output)[2]....
            ...
            (*output)[17]....
}
```

then I got the error msg in netopeer2-server:
`[ERR]: LY: Invalid argument parent || module || ext (lys_getnext_())`

PS:
In another example (only one output arg ) it works well with same subscribe way:
`    rpc get-history-performance-monitoring-data {
        description "none";
            input {
                leaf start-time {
                    mandatory false;
                    type yang:date-and-time;
                    description "none";
                }
                leaf end-time {
                    mandatory false;
                    type yang:date-and-time;
                    description "none";
                }
            }
            output {
                container performances {
                    uses performances;
                    description "none";
                } 
            }
    }`


Is there something wrong with my way to subscribe and fill the output ? could you kindly help to check . 
Thanks a lot in advance.

**Comment by michalvasko** [comment]
Sorry, not sure why I have not answered sooner but you need to update all the projects to their current `devel` branch versions, this bug should have already been fixed there. A new official release will be made this week of these versions.

**Comment by wxes9250310s** [comment]
Hi Michalvasko,

This issue is solved on newest devel branch, thanks.

**Comment by PeterYFPeng** [comment]
This issue is solved on newest devel branch, thanks.
