### ISSUE TITLE
NACM is slow because of calls to getgrgid_r

### ISSUE THREAD

**Issue by syyyr** [CESNET/netopeer2#998]
Hi,
through testing (and with the help of @jktjkt), I have found out that NACM is slow to the point it makes the server unusable, because almost all operations time out (unless you turn off NACM, or increase the timeout). The reason is that when connecting to Netopeer2, the `getgrgid_r` function is called about 5000 times and each call takes around 10 ms.

How to reproduce: The reason it takes so long is the configuration of NSS. My system is Arch Linux which is a modern distribution that tries to have the newest versions of software available. This is how the default  `/etc/nsswitch.conf` looks:
```
# Name Service Switch configuration file.
# See nsswitch.conf(5) for details.

passwd: files systemd
group: files [SUCCESS=merge] systemd
shadow: files

publickey: files

hosts: files mymachines myhostname resolve [!UNAVAIL=return] dns
networks: files

protocols: files
services: files
ethers: files
rpc: files

netgroup: files
```
The default `group:` setting causes the `getgrgid_r` function to be slow and basically makes Netopeer2 unusable on Arch Linux (and possibly other distribution that have the same defaults).

**Comment by michalvasko** [comment]
Could you please share your NACM configuration and the response data to `get` (which seem to take so long)? It is not common that so many times the groups need to be retrieved.

**Comment by syyyr** [comment]
My NACM configuration is the default (no explicit configuration). Just connecting to the server via netopeer2-cli is slow. What I mean by unusable is that the connection process is so slow, that it makes the schema retrieving fail (because a callback times out). I understand that you probably don't want to edit your system configuration to reproduce the problem. Perhaps you could simulate the failure of schema retrieval (which gives me the JSON printing problem) by adding `sleep(10ms)` between each call to `getgrgid_t`.

I don't know why there are 5000 calls to the getgrgid_t function. [Here](https://gist.github.com/syyyr/c9d6dd38d4c8c01a01de5e4831624783) is a log where I start the server and connect with netopeer2-cli, but I guess there is not any useful information

**Comment by michalvasko** [comment]
I see. We first need to find out why you have so many calls to `getgrgid_t` before we can do anything about it, no need toreproduce the schema retrieval failure. Could you post the output of `id -Gn` for the user you are using to log into *netopeer2*?

**Comment by syyyr** [comment]
This is the output:
```
$ id -Gn
vk docker libvirt zigbee2mqtt adbusers video uucp audio wheel tracing
```
Btw, I'm running Netopeer2 as the same user.

**Comment by michalvasko** [comment]
Okay, please post the *netopeer2* server output when actually connecting with a user. Also, are you running *netopeer2* as `root` or as another user and you have customized *sysrepo* super-user? Are you connecting on SSH or on UNIX socket?

**Comment by syyyr** [comment]
I'm running the server as a non-root user called `vk` and customized the sysrepo super-user to also be `vk`. I am also connecting via the same user. I am connecting over a UNIX socket, but the problem seems to happen over both SSH and UNIX.

**Comment by michalvasko** [comment]
Should now be fixed by @tadeas-vintrlik.

**Comment by syyyr** [comment]
Okay, I tested the new version and it seems to work fine now, I'm no longer getting timeouts because of NACM. Thanks!
