### ISSUE TITLE
How to achieve zero touch provisioning using netopeer2

### ISSUE THREAD

**Issue by bkumarrr** [CESNET/netopeer2#999]
Hi All
I want to ask How to achieve zero touch provisioning using netopeer2 ?
Please give your feedback or steps to achieve this activity 
Thanks in Advance

**Comment by michalvasko** [comment]
I have not checked the exact specification but this is not implemented so you would likely have to add full support for it, which would include changing *netopeer2* code.

**Comment by bkumarrr** [comment]
Thanks @michalvasko for quick response.
Could you please tell me how can I achieve this, as I don't have no idea how to achieve this

**Comment by michalvasko** [comment]
If you have no idea how to achieve it then I suggest you do not even attempt to, it would not be a simple feature to add.
